{100}{}{You see a man in a military uniform.}
{101}{}{You see Quincy, the mechanic.}
{102}{}{You see a man in a military uniform. Judging by the grease spots you think
 he is more of a mechanic than a soldier.}

{103}{quin1}{Name's Quincy, soldier. Why are you tapping my shoulder and looking lost?}
{104}{}{Me need ask you something.}
{105}{}{Nothing.}
{106}{}{Hi. I need to ask you something.}
{107}{}{Never mind.}

{108}{quin2}{All right, but make it quick. I have inventory to do.}
{109}{quin3}{What do you need to know?}
{110}{}{What this place?}
{111}{}{Me look for vertibird plans. Where find?}
{112}{}{Me told by tech me find vertibird plans here.}
{113}{}{Me go now.}
{114}{}{What is this place?}
{115}{}{I'm looking for vertibird plans. Do you know where I can find them?}
{116}{}{I was told by a tech that I could find the vertibird plans here.}
{117}{}{Well, got to go.}

{118}{quin4}{This is maintenance. We repair pretty much anything except for the vertibirds.}
{119}{}{Where vertibird get repair?}
{120}{}{Where do the vertibirds get repaired?}

{121}{quin5}{They only fit in the hangar or outdoors. You figure it out from there, okay?}
{122}{}{Oh... okay.}
{123}{}{Oh, yeah. I get it.}

{124}{quin6}{Well... I've got a copy of the plans but I can't just hand them out to
 anyone who asks for them. What do you want with them?}
{125}{}{Me got friends down south who want.}
{126}{}{Uh... well...}
{127}{}{I've got some friends down south who want to get their hands on them.}
{128}{}{I was told by the Sarge to get them.}

{129}{quin7}{Down south... Holy shit! We've got a spy here! Guards! Alert!}
{130}{}{Ooops.}
{131}{}{Ooops. Put my foot in it this time.}

{132}{quin8}{You're one round short of a full clip, aren't you? Well, they call you
 grunts for a reason. Look, Einstein, I can't give you the plans without
 authorization, okay? So, go back to whoever sent you here and get the proper
 paperwork.}
{133}{quin9}{Look, Einstein, I can't give you the plans without authorization, okay?
 So, go back to whoever sent you here and get the proper paperwork.}
{134}{}{Okay, me go.}
{135}{}{No, me shoot you first, find plans second, then... what come after two?}
{136}{}{Hey, you got it.}
{137}{}{No, I think I'll shoot you instead and look around for the plans while
 you bleed.}

{138}{quin10}{A tech told you... You mean Raul? Did he send you?}
{139}{}{Uh, yeah.}
{140}{}{Uh, no.}
{141}{}{Yeah, that's the guy.}
{142}{}{No, I don't think it was Raul.}

{143}{quin11}{Damn it! You know, Raul would lose his head if it weren't placed so
 firmly up his ass! This is the third time this quarter that he's lost those
 plans! And now he doesn't even have the brass bouncing balls to come to me
 and ask for them? Fine, they're in the locker over there. Oh and, when you
 deliver them, tell that asshole I want to see him.}
{144}{}{Thanks.}

{145}{quin12}{So you're back. Did you get the authorization?}
{146}{quin13}{You again? What is it now?}
{147}{}{Yeah, me got plasma rifle. That good enough me!}
{148}{}{No, not yet.}
{149}{}{Yeah, I've got a big fucking gun. That's good enough for me!}
{150}{}{No, not yet.}
{151}{}{Me ask you something.}
{152}{}{Me just say 'Hi'.}
{153}{}{I need to ask you something.}
{154}{}{Nothing, just saying 'Hi'.}

{155}{quin14}{Are you nuts? Walking around here out of uniform? Get suited up!}
{156}{quin15}{If the sergeant catches you out of uniform, he'll hand you your ass.}
{157}{quin16}{Why are you out of uniform?}

{158}{quin17}{Holy shit! We're being invaded! Alert!}
{159}{quin18}{Intruders! Call the guard!}
{160}{quin19}{Guard! Intruders in maintenance!}

{161}{quin20}{What's up? Are we under attack?}
{162}{quin21}{Why the alert? What's happening?}
{163}{quin22}{What the hell's going on?}

{164}{quin26}{Hey! Don't be rummaging through those drawers.}
{165}{quin27}{I told you not to go through my stuff! Guards!}
{200}{quin28}{Yeah. Well, don't believe everything you hear.}
{201}{quin29}{Who told you that? 'Cause he's next after I knock some sense into you.}
{300}{quin23}{Can't you see that I am busy?}
{301}{quin24}{Hey! Don't be rummaging through those drawers!}
{302}{quin25}{I told you not to go through my stuff! Guards!}
