{100}{}{You see a man in power armor.}
{101}{}{This is Sir Bedemir.}
{102}{}{He seems to be deep in thought.}
{103}{sbed1}{Sir Bedemir at your service.}
{104}{sbed2}{...and that is how we know that the Earth is banana-shaped.}
{105}{sbed3}{Let me explain how sheep's bladders may be employed to prevent earthquakes.}
{106}{sbed4}{I need some time to think. Please, go bother someone else.}

{200}{sbed5}{Here now! Your hands are ice cold!}
{201}{sbed6}{That doesn't belong to you.}
{202}{sbed7}{Hey, those are my things!}
