{100}{}{You see a man in power armor.}
{101}{}{This is Sir Galahad.}
{102}{}{He blushes when he notices you staring at him.}
{103}{sgal1}{Sir Galahad, at the ready!}
{104}{sgal2}{I once was a prisoner of Castle Anthrax.}
{105}{sgal3}{Sir Lancelot rescued me. Damn him!}
{106}{sgal4}{I could have been a prisoner. [Sniff]}

{200}{sgal5}{Here now! Your hands are ice cold!}
{201}{sgal6}{That doesn't belong to you.}
{202}{sgal7}{Hey, those are my things!}
