{100}{}{You see a man strumming a lute.}
{101}{}{This is Joshua.}
{102}{}{He is a traveling minstrel.}

{103}{sjos1}{Brave Sir Robin ran away...}
{104}{sjos2}{Bravely ran away, away...}
{105}{sjos3}{When danger reared its ugly head, he bravely turned his tail and fled...}
{106}{sjos4}{Yes, Brave Sir Robin turned about...}
{107}{sjos5}{And gallantly he chickened out. Bravely taking to his feet...}
{108}{sjos6}{He beat a very brave retreat...}
{109}{sjos7}{Oh, Brave Sir Robin.}
