{100}{}{You see a man in power armor.}
{101}{}{This is Sir Robin.}
{102}{}{He looks like he's ready to run.}
{103}{srob1}{Sir Robin, at your service.}
{104}{srob2}{You're not going to try to hurt me are you?}
{105}{srob3}{There's no need for violence, is there?}
{106}{srob4}{Please go away.}

{200}{srob5}{Here now! Your hands are ice cold!}
{201}{srob6}{That doesn't belong to you.}
{202}{srob7}{Hey, those are my things!}
