{100}{}{You see a woman with a worried expression on her face.}
{101}{}{You see Suze.}
{102}{}{You see a woman with a worried expression on her face.}
{103}{suze9}{Aieee! Help me!}
{104}{suze10}{Save me! Please!}
{105}{suze11}{They're trying to kill me!}
{106}{suze12}{Please! They're going to kill me!}
{107}{suze13}{Stop them! Aieee!}
{108}{suze1}{Did Badger send you? I knew he would. I'm so relieved.}
{109}{}{Aagggh.}
{110}{}{What were you doing down there?}
{111}{}{Yeah. Follow me.}
{112}{suze2}{Oh, you poor dear. Radiation and the wasteland aren't nice, are they? I hope someone can help you.}
{113}{suze3}{It's kind of stupid, really. I was just exploring because Badger was on the computer and I went downstairs and got lost and then next thing you know, I'm surrounded by monsters. Good thing you came along.}
{114}{}{I have more questions.}
{115}{}{Yes, it is. Find anything interesting?}
{116}{}{Yes, it is. Let's go.}
{117}{suze4}{I found the room I was in. I also found a room that looked like a fueling area. I didn't get much farther because of the monsters.}
{118}{}{I have more questions.}
{119}{}{Where are you from?}
{120}{}{Great. That's all for now.}
{121}{suze5}{I'm from a place south of the Boneyard and south of the Glow. We're not too far from the sea. I used to be a nanny, but then the kids mutated into monsters.}
{122}{}{I have more questions.}
{123}{}{How'd you meet Badger?}
{124}{}{Fascinating. That's all for now.}
{125}{suze6}{He came down south and went to a club I used to go to. So, when things fell apart for me, I thought this would be the place to go.}
{126}{}{I have more questions.}
{127}{}{That's all. Thanks.}
{128}{suze7}{You saved my life. I'll answer any questions you have.}
{129}{}{Yaaaah.}
{130}{}{What were you doing down there?}
{131}{}{Did you find anything interesting?}
{132}{}{Where are you from?}
{133}{}{How did you meet Badger?}
{134}{}{None right now. Bye.}
{135}{suze8}{Oh my god... Badger is dead... I don't know what I'll do... I haven't got any friends here... all my family is dead... oh my god...}
{136}{suze14}{Thanks for all your help. I am going to go find Badger.}
