{100}{}{You see a ghoul wearing an apron.}
{101}{}{You see Phil, the bartender. He's washing a glass.}
{102}{}{You see a ghoul wearing an apron and washing a glass. Seeing as he's right behind the bar, you assume he's the bartender of this saloon.}

{103}{phil1}{Howdy, stranger. Welcome to town. What's your name?}
{104}{}{Doi?}
{105}{}{!}
{106}{}{.}
{107}{}{None of your business, pal.}
{108}{}{Well, I'm kind of undercover right now.}

{109}{phil2}{Doi's your name? Ha! Just kidding, pal. Here. Have a Nuka-Cola. Try not to disturb the other customers.}
{110}{}{Ganks!}

{111}{}{, eh? Well, pleased to meet you, bucko. Want something to drink?}

{112}{}{Grink yes!}
{113}{}{Oh no. No no no no.}

{114}{}{, pleased to meet you. I'm Phil. I own this place. Now... what'll it be?}
{115}{}{Nuka-Cola.}
{116}{}{Beer.}
{117}{}{Rotgut.}
{118}{}{Nothing.}
{119}{}{Nothing, sorry. Bye!}

{120}{phil5}{Fine, pal. Be that way. I'm Phil. I own this place and run it. What'll it be?}

{126}{phil6}{Undercover, eh? I guess I can understand that. I'm Phil, by the way. What'll it be?}

{132}{phil7}{You want beer? Rotgut? Nuka-Cola?}
{133}{}{Deer!}
{134}{}{Notblut!}
{135}{}{Gola!}

{136}{phil8}{Well, you just let me know when you want something and I'll get you set up, friend. Try not to disturb the other customers, all right?}
{137}{}{O-tay!}

{138}{phil9}{One beer it is. That'll be $3, plus a $1 tip for me. That's $4, kiddo.}
{139}{}{'Ere!}
{140}{}{No have.}

{141}{phil10}{Powerful drink, lad! That's $5, plus a $1 tip for me, which makes it $6.}
{142}{phil11}{Powerful drink, lass! That's $5, plus a $1 tip for me, which makes it $6.}

{145}{phil12}{Good for you, good for your skin. That's $2. I'll even let you off without tipping me. That's $2, straight up.}

{148}{}{. You need anything else to drink, you come on back to see me.}
{149}{}{Otay!}

{150}{}{! You want something to drink?}
{151}{}{Grink 'es!}
{152}{}{Grink no!}

{153}{phil15}{Hey, Doi! Welcome back. Got your seat all warmed up for you back there.}
{154}{}{Anks!}

{155}{phil16}{That'll be $2.}
{156}{phil17}{That'll be $4.}
{157}{phil18}{That's $5.}
{158}{}{There ya go.}
{159}{}{[Give Phil a $1 Tip] Here you go, Phil.}
{160}{}{[Give Phil a $2 Tip] Thanks, Phil.}
{161}{}{Oops, I'm tapped. }

{162}{phil19}{Nothing? Ha. Ha. You don't park yourself here without drinking something, friend. I gotta pay the bills, too. Let's try that again. SO! What'll it be?}
{167}{}{Forget it. I'm out of here.}

{168}{phil20}{'Til you're buying, I ain't talking. What's your pleasure?}
{173}{}{Forget this and forget your lousy drinks!}

{174}{phil21}{Thanks. Anything else?}
{175}{phil22}{Hey, thanks! Anything else?}
{176}{phil23}{Wow! Thanks! Anything else I can do for you?}
{177}{}{I want more to drink.}
{178}{}{What's been going on in town?}
{179}{}{What's there to do around here?}
{180}{}{What's new?}
{181}{}{Nothing. Forget it.}

{182}{phil25}{Tapped, eh? Too bad. You can stick around here, but don't bug the customers. I got work to do. See you.}
{183}{}{Bye!}

{184}{}{Hey! Welcome back. What'll it be?}
{185}{phil26}{Welcome back, pard. What'll it be?}
{186}{phil27}{You again? What'll it be?}
{187}{phil28}{You again? Whaddya want?}
{192}{}{To tell you my name. It's }
{193}{}{Nothing, sorry. Bye!}

{194}{phil29}{Well, all right then! What'll it be?}

{198}{phil30}{What's been going on in town? Well...}
{1981}{phil31}{A couple of loons've been locked up for spreading hate propaganda.}
{1982}{phil32}{Mine's purifiers are down.}
{1983}{phil33}{Caravans all over the place. That's about normal.}
{1984}{}{Go on.}
{199}{}{Thanks. I have more questions. }
{200}{}{Thanks. Bye.}

{201}{phil34}{What to do, what to do... let's see...}
{202}{}{- more - }

{203}{phil35}{Someone busted those lunatics out of jail!}
{204}{phil36}{Someone destroyed the mine! The town is doomed!}
{205}{}{All the mutants are dead!}
{206}{phil37}{Not much.}
{207}{}{I have more questions.}
{208}{}{Thanks. See ya.}

{209}{phil38}{You look like burly one. I'm betting you could arm wrestle with Francis. He's the mutant sitting over there. Apparently he's got a prize of some sort. Interested? Go talk to Francis.}
{210}{}{Thanks. Is there anything else?}
{211}{}{Thanks. See ya.}

{212}{phil39}{There are some people missing. We're not sure where they are. If you could find them, I'm sure there'd be something in it for you. Do you want to start with that? Go talk to Marcus.}
{213}{}{Thanks. Anything else?}
{214}{}{Thanks! Talk to you later.}

{215}{phil40}{Hmm. The mine's air purifiers are broken. You might want to go talk to Zaius, the mine foreman, about that.}
{216}{}{All right. Anything else?}
{217}{}{Thanks. See ya.}

{218}{phil41}{I understand that you can poke around the mine now. Hell, if you find anything, you might even get to keep it.}
{219}{}{You got anything else?}
{220}{}{Thanks.}

{221}{phil42}{Hell yeah! Find out where those two lunatics Franc and Manson went!}
{222}{}{I'm on it.}
{223}{}{Got it. See ya.}

{224}{phil43}{There's always a caravan headed out someplace. If you wanna be part of one of those, you can talk to the Bill, the Outfitter. Other than that, we haven't got much to do in this place. Sorry.}
{225}{}{Thanks! I have a few more questions.}
{226}{}{All right. Well, I'm outta here. See ya.}

{227}{phil44}{Yeah? Like what?}
{228}{}{I want more to drink.}
{229}{}{What's been going on in town?}
{230}{}{What's there to do around here?}
{231}{}{What's new?}
{232}{}{Nothing. Forget it.}

{233}{}{I hope you don't mind me saying that the folks 'round here are a little pissed off that you kept that uranium for yourself. You been warned. Anyway... ready for a drink?}
{234}{}{Yes.}
{235}{}{No. But I have some questions.}

{236}{phil45}{Some folks might be a tad pissed off about Chad. You been warned. Ready for a drink?}
{237}{}{Yes.}
{238}{}{No. But I have some questions.}

{239}{phil46}{All the mutants are dead. Someone blew up the damn mine while they were in it. Some bastard must have cried wolf and they all just came running to help. I just don't understand some people. Hell... Can I get you a drink?}
{240}{}{Yes.}
{241}{}{No. But I have questions.}

{242}{phil48}{Get out of my bar. Now. Scumbag.}
{300}{}{!}
{301}{}{.}
{302}{}{Well, }
{303}{}{Thanks, }
{304}{}{Hi again, }
{305}{}{Hey, }
{306}{}{You again, }

{307}{phil24}{No problem, pal. Here's your drink, too. Hey, anything else I can do ya' for?}
{308}{phil47}{Hey pal, thanks for all the tips. Lemme' give you one in return. I've heard that Liz, the owner of the General Store, keeps a stash of weapons in her basement. But you didn't hear it from me.}
{309}{}{Gee, thanks Phil. I'll keep that under my... uh... hat, or something.}

# VOCK Add Ons
# was Reply(dude_name+mstr(111)) in Node003; VA recorded phil3 with no PC name spoken
{1000}{phil3}{Well, pleased to meet you, bucko. Want something to drink?}
# was Reply(mstr(302)+dude_name+mstr(114)) in Node004; VA recorded phil4 with no PC name spoken
{1001}{phil4}{Well, pleased to meet you. I'm Phil. I own this place. Now... what'll it be?}
# was Reply(mstr(303)+dude_name+mstr(148)) in Node012; VA recorded phil13 with no PC name spoken
{1002}{phil13}{Thanks. You need anything else to drink, you come on back to see me.}
# was Reply(mstr(304)+dude_name+mstr(150)) in Node013; VA recorded phil14 with no PC name spoken
{1003}{phil14}{Hi again! You want something to drink?}
