{100}{}{You see a gray haired man in the uniform of the NCR police.}
{101}{}{It's the sheriff of NCR.}
{102}{}{This guy's about as regulation as they come - crew cut and square-jawed, a real no-nonsense kind of guy.}
{103}{dum1}{Welcome to NCR, stranger. Name's Dumont - Sheriff Dumont. Hope you're having a nice peaceful time here.}
{104}{dum2}{Take a word of advice from Sheriff Dumont, stranger - this town don't care for your kind. Any trouble and I come down hard. Now, is there anything I can do for you?}
{105}{dum3}{Hello again. Anything I can do for you?}
{106}{dum4}{Well, spit it out.}
{107}{}{Urrrgh.}
{108}{}{I'm looking for Vault 13. Do you know where it is?}
{109}{}{Do you have a GECK?}
{110}{}{I'm looking for some honest work. Can you help me?}
{111}{}{Oh, fine. Everything's been just peachy.}
{112}{dum5}{Primitive, eh? You. Questions? Ask me. Okay?}
{113}{}{Vault 13?}
{114}{}{GECK?}
{115}{}{Okay.}
{116}{dum6}{No, I don't. That's something even President Tandi would like to know. Solve a lot of problems.}
{117}{}{Problems?}
{118}{}{President Tandi?}
{119}{}{Great. Just my luck. Thanks.}
{120}{dum7}{Listen, I lead a clean and wholesome life! I don't have GECK or anything else.}
{121}{}{So-rry! I don't suppose you know where Vault 13 is?}
{122}{}{We'll just forget I asked. I'll leave you alone now.}
{123}{dum8}{I can think of a couple of things, if you're really interested.}
{124}{dum9}{You're joking right? After what you did with Jack? I suppose you could find some steady work.}
{125}{}{Like what?}
{126}{}{No, let's just change the subject.}
{127}{}{Forget it, I've changed my mind. Goodbye.}
{128}{dum10}{No Vault 13. Vault 15, yes.}
{129}{}{Fif-teen?}
{130}{}{No. Thir-teen!}
{131}{dum11}{Yes, 15! You talk Tandi. Big chief NCR. Tandi know Vault. Want help. You go Tandi.}
{132}{}{Tandi?}
{133}{}{No go. Want 13!}
{134}{dum12}{Lis-ten. No Vault 13. No find. No see. No 13. Vault 15 - people find. People live Vault 15. You understand?}
{135}{}{No thir-teen? Fif-teen?}
{136}{}{NO. WANT THIRTEEN!}
{137}{dum13}{Arrgh! THERE IS NO 13, YOU DUMB BOX OF ROCKS! No 13. No find. Never! Ever!}
{138}{dum14}{Tandi big chief. Tandi want help. You talk to Tandi. Go Con-gress house. Okay?}
{139}{}{GECK?}
{140}{}{Okay.}
{141}{dum15}{No GECK. Me healthy. Not sick.}
{142}{}{Vault 13?}
{143}{}{Okay.}
{144}{dum16}{Look around you. NCR's a growing place. We need parts, computers, whatnot. Been a problem ever since those squatters moved into Vault 15.}
{145}{}{Vault 15? Squatters? What's going on?}
{146}{}{What's this about President Tandi?}
{147}{}{Thanks for the info.}
{148}{dum17}{President of NCR, who else? Things have got her so worried she even asked to borrow one of my deputies for a special mission. Hated to turn her down, but I can't spare the manpower.}
{149}{}{How about me? Maybe you could recommend me.}
{150}{}{Hmm. Tough life, I guess.}
{151}{dum18}{You? Hmmm....I couldn't. Don't even know you - but she's looking to hire somebody so you can go talk to her yourself. Her office is in the Hall of Congress.}
{152}{}{Thanks. I'll do that.}
{153}{}{Know anything about a GECK?}
{154}{dum19}{Well, that's damn fine of you, stranger - and damn presumptuous, too. I don't know you from Adam and Eve and I don't like the way you look! I'm not recommending you to anybody. Now, I got work to do.}
{155}{dum20}{Well, there's Duppo at the Stockman's. He does the hiring for the brahmin drives. Then there's Mr. Westin. If you talk to him, tell him I sent you. Even President Tandi's been asking around for some help.}
{156}{dum21}{Duppo up at the Stockman's Association wrangles hands for the brahmin drives. Go try him.}


{157}{}{Westin?}
{158}{}{President Tandi?}
{159}{}{Got to go.}
{160}{dum22}{Roger Westin. His spread's just out the west gate. He's been having some problem with varmints. He'd take care of it himself, but his health ain't what it used to be. Bad ticker, Doc Jubilee says.}
{161}{dum23}{Yeah?}
{162}{}{Any work to be had in this town?}
{163}{}{Never mind. I'm going.}
{164}{dum24}{Just make sure things stay that way. Goodbye.}
{165}{dum25}{That's a damn fine piece of work you did with old Jack, stranger. As the sheriff, I'll take if from here.}
{166}{}{He's all yours.}
{167}{}{What about a reward?}
{168}{dum26}{Well, I can't say that I've got any reward money to give. Best I can do is my thanks.}
{169}{}{Wait. I've got some questions.}
{170}{}{Oh, I understand all right.}
{171}{dum32}{Sorry, can't talk right now. I'm already late for the coroner's inquest. Seems pretty clear cut to me.}
{172}{dum33}{Sorry, no crime, no time.}
{173}{dum27}{Desert rats. You got to understand -- this town traces its roots back to 15. Seems there was some trouble there a long time ago and the survivors founded Shady Sands. So by right, Vault 15 is our property. Few years back some squatters moved in and there's been trouble ever since. You should talk to Tandi about it.}
{174}{}{Tandi?}
{175}{}{I'll take that under advisement.}
{176}{dum28}{There is no more work that I am aware of.}
{177}{dum29}{Duppo up at the Stockman's Association wrangles hands for the brahmin drives. President Tandi's been asking around for some help.}
{178}{dum30}{Anyone else of your stature would be leaving town, much less look for work.}
{179}{dum31}{Duppo up at the Stockman's Association wrangles hands for the brahmin drives. Go try him. Then there's Mr. Westin. If you talk to him, tell him I sent you.}
