# VOCK - Fallout 2 character table
#
# (msg_stem, name, prefix, [ssl_stems], head)
#   msg_stem  : MSG file stem (rpu/data/text/english/dialog/<stem>.msg)
#   name      : character's in-game name
#   prefix    : audio tag prefix  (metzg -> metzg1, metzg2 ...)
#   ssl_stems : SSL file(s) whose dialog lines use the MSG
#   head      : talking head name(s)

CHARACTERS = [
    ("abmatt",     "Brother Matthew",            "bmatt",   ['abmatt'],                ['bmatt']),
    ("abmerch1",   "Abbey Merchant",             "merch",   ['abmerch1'],              ['merch']),
    ("abpetson",   "Peterson",                   "pet",     ['abpetson'],              ['pet']),
    ("acklint",    "Klint",                      "klint",   ['acklint'],               ['klint']),
    ("acmorlis",   "Morlis",                     "mor",     ['acmorlis'],              ['mor']),
    ("acmynoc",    "Mynoc",                      "mynoc",   ['acmynoc'],               ['mynoc']),
    ("actemvil",   "Cameron",                    "cam",     ['actemvil'],              ['cam']),
    ("ahelder",    "Arroyo Elder",               "elder",   ['ahelder'],               ['elder']),
    ("ahhakun",    "Hakunin",                    "hakun",   ['ahhakun'],               ['hakun', 'haku2', 'haku3']),
    ("ahmonk",     "Abbot",                      "abott",   ['ahmonk'],                ['abott']),
    ("amonk5",     "Brother Paul",               "paul",    ['amonk5'],                ['paul']),
    ("bccrissy",   "Chrissy",                    "chrsy",   ['bccrissy'],              ['chrsy']),
    ("bcdalia",    "Dalia",                      "dalia",   ['bcdalia'],               ['dalia']),
    ("bcdarion",   "Darion",                     "dario",   ['bcdarion'],              ['dario']),
    ("bcjones",    "Doc Jones",                  "jones",   ['bcjones'],               ['jones']),
    ("bcrebecc",   "Rebecca",                    "rb15",    ['bcrebecc'],              ['rb15']),
    ("bczeke",     "Zeke",                       "zeke",    ['bczeke'],                ['zeke']),
    ("ccchris",    "Chris",                      "chris",   ['ccchris'],               ['chris']),
    ("ccdoctor",   "Doctor Schreber",            "sch",     ['ccdoctor'],              ['sch']),
    ("ccdrill",    "Sergeant Arch Dornan",       "drill",   ['ccdrill'],               ['power']),
    ("ccgguard",   "Enclave Gate Guard",         "guard",   ['ccgguard'],              ['power']),
    ("cck9",       "K-9",                        "rdog",    ['cck9', 'ccfak9'],        ['rdog']),
    ("ccmandr",    "Navarro Base Commander",     "cmdr",    ['ccmandr'],               ['cmdr']),
    ("ccmaster",   "Quartermaster",              "qm2",     ['ccmaster'],              ['qm2']),
    ("ccqmstr",    "Quartermaster",              "qm",      ['ccqmstr'],               ['qm']),
    ("ccquincy",   "Quincy",                     "quin",    ['ccquincy'],              ['quin']),
    ("ccraul",     "Raul",                       "raul",    ['ccraul'],                ['raul']),
    ("ccxarn",     "Xarn",                       "xarn",    ['ccxarn'],                ['xarn']),
    ("dcanan",     "Great Ananias",              "ana",     ['dcanan'],                ['ana']),
    ("dcanna",     "Anna Winslow",               "anna",    ['dcanna'],                ['anna']),
    ("dcflick",    "Flick",                      "flick",   ['dcflick'],               ['flick']),
    ("dcfranki",   "Frankie",                    "frank",   ['dcfranki'],              ['frank']),
    ("dcjoey",     "Joey",                       "joeyd",   ['dcjoey'],                ['joeyd']),
    ("dclara",     "Lara",                       "larad",   ['dclara'],                ['larad']),
    ("dcmetzge",   "Metzger",                    "metzg",   ['dcmetzge'],             ['metzg']),
    ("dcmom",      "Mom",                        "mom",     ['dcmom'],                 ['mom']),
    ("dcrebecc",   "Rebecca Dyer",               "rbcca",   ['dcrebecc'],              ['rbcca']),
    ("dcsheila",   "Sheila",                     "shela",   ['dcsheila'],              ['shela']),
    ("dcsmitty",   "Smitty",                     "smit",    ['dcsmitty'],              ['smit']),
    ("dctubby",    "Tubby",                      "tubby",   ['dctubby'],               ['tubby']),
    ("dctyler",    "Tyler",                      "tyler",   ['dctyler'],               ['tyler']),
    ("dcvic",      "Vic",                        "vic",     ['dcvic'],                 ['vic']),
    ("ecarthur",   "Arthur Pendragon",           "arth",    ['ecarthur'],              ['arth']),
    ("ecbridge",   "Bridge Keeper",              "brige",   ['ecbridge'],              ['brige']),
    ("ecdogmet",   "Dogmeat",                    "dogmt",   ['ecdogmet'],              ['dogmt']),
    ("eckaga1",    "Kaga",                       "kaga",    ['eckaga1'],               ['kaga']),
    ("eckaga2",    "Kaga",                       "kaga",    ['eckaga2'],               ['kaga']),
    ("eckaga3",    "Kaga",                       "kaga",    ['eckaga3'],               ['kaga']),
    ("eckaga4",    "Kaga",                       "kaga",    ['eckaga4'],               ['kaga']),
    ("eckaga5",    "Kaga",                       "kaga",    ['eckaga5'],               ['kaga']),
    ("epac10",     "Dex",                        "dex",     ['epac10'],                ['dex']),
    ("epac11",     "Sergeant Cat Jules",         "cat",     ['epac11'],                ['cat']),
    ("epac12",     "Kitsune",                    "kit",     ['epac12'],                ['kit']),
    ("fcbadger",   "Badger",                     "badge",   ['fcbadger'],              ['badge']),
    ("fcchip",     "Chip",                       "chip",    ['fcchip'],                ['chip']),
    ("fcdragon",   "Dragon",                     "drago",   ['fcdragon'],              ['drago']),
    ("fcdrfung",   "Dr. Fung",                   "fung",    ['fcdrfung'],              ['fung']),
    ("fcdrwong",   "Wong Yi Tze",                "wong",    ['fcdrwong'],              ['wong']),
    ("fcfmatt",    "Matthew",                    "mat",     ['fcfmatt'],               ['mat']),
    ("fcjuavki",   "Vikki Goldman & Juan Cruz",  "vaj",     ['fcjuavki'],              ['vaj']),
    ("fckenlee",   "Ken Lee",                    "kensf",   ['fckenlee'],              ['kensf']),
    ("fclaocho",   "Lao Chou",                   "lao",     ['fclaocho'],              ['lao']),
    ("fclopan",    "Lo Pan",                     "lopan",   ['fclopan'],               ['lopan']),
    ("fcoz7",      "AHS-7",                      "ahs7",    ['fcoz7'],                 ['ahs7']),
    ("fcoz9",      "AHS-9",                      "ahs9h",   ['fcoz9'],                 ['ahs9h']),
    ("fcronmey",   "Ron Meyers",                 "cap",     ['fcronmey'],              ['cap']),
    ("fcsuze",     "Suze",                       "suze",    ['fcsuze'],                ['suze']),
    ("gcbrain",    "Brain (Mole Rat)",           "brain",   ['gcbrain'],               ['brain']),
    ("gcfestus",   "Festus",                     "fest",    ['gcfestus'],              ['fest']),
    ("gcgordon",   "Gordon",                     "gord",    ['gcgordon'],              ['gord']),
    ("gchank",     "Hank",                       "hank",    ['gchank'],                ['hank']),
    ("gcharold",   "Harold",                     "hrld2",   ['gcharold'],              ['hrld2']),
    ("gclenny",    "Lenny",                      "lenny",   ['gclenny'],               ['lenny']),
    ("gcskeetr",   "Skeeter",                    "skeet",   ['gcskeetr'],              ['skeet']),
    ("gcwooz",     "Wooz",                       "wooz",    ['gcwooz'],                ['wooz']),
    ("gczomak",    "Zomak The Destroyer",        "zomak",   ['gczomak'],               ['zomak']),
    ("hcchad",     "Chad",                       "chad",    ['hcchad'],                ['cha2', 'chad']),
    ("hcdan",      "Dan",                        "danbh",   ['hcdan'],                 ['danbh']),
    ("hcdoc",      "Doc Holliday",               "hol",     ['hcdoc'],                 ['hol']),
    ("hceric",     "Eric",                       "eric",    ['hceric'],                ['eric']),
    ("hcfranci",   "Francis",                    "franc",   ['hcfranci'],              ['franc']),
    ("hcjacob",    "Jacob",                      "jacob",   ['hcjacob'],               ['jacob']),
    ("hcmarcus",   "Marcus",                     "mrcus",   ['hcmarcus'],              ['mrcus']),
    ("hcseymor",   "Seymour",                    "plant",   ['hcseymor'],              ['plant']),
    ("hcsteve",    "Steve",                      "steve",   ['hcsteve'],               ['steve']),
    ("hctyphon",   "Typhon",                     "typhn",   ['hctyphon'],              ['typhn']),
    ("hczaius",    "Zaius",                      "zaius",   ['hczaius'],               ['zaius']),
    ("kcaldo",     "Aldo",                       "aldo",    ['kcaldo'],                ['aldo']),
    ("kcardin",    "Ardin Buckner",              "ardin",   ['kcardin'],               ['ardin']),
    ("kcdunton",   "Chuck and Buck Dunton",      "buck",    ['kcdunton'],              ['buck']),
    ("kcjenny",    "Jenny",                      "jenny",   ['kcjenny'],               ['jenny']),
    ("kcmaida",    "Maida Buckner",              "maida",   ['kcmaida'],               ['maida']),
    ("kcsajag",    "Sajag",                      "sajag",   ['kcsajag'],               ['sajag']),
    ("kcsally",    "Sally Dunton",               "sally",   ['kcsally'],               ['sally']),
    ("kcslim",     "Slim Picket",                "slim",    ['kcslim'],                ['slim']),
    ("kcsmiley",   "Smiley",                     "smiley",  ['kcsmiley'],              ['smiley', 'smilw']),
    ("kcsulik",    "Sulik",                      "sulik",   ['kcsulik'],               ['sulik']),
    ("kctorr",     "Torr Buckner",               "torr",    ['kctorr'],                ['torr']),
    ("mcbaltha",   "Balthas",                    "bal",     ['mcbaltha'],              ['bal']),
    ("mccornel",   "Cornelius",                  "corn",    ['mccornel'],              ['corn']),
    ("mcdavin",    "Davin",                      "davin",   ['mcdavin'],               ['davin']),
    ("mcfarrel",   "Farrel",                     "far",     ['mcfarrel'],              ['far']),
    ("mcgrisha",   "Grisham",                    "grish",   ['mcgrisha'],              ['grish']),
    ("mcjo",       "Jo",                         "jomod",   ['mcjo'],                  ['jomod']),
    ("mcjonny",    "Jonny",                      "jonny",   ['mcjonny'],               ['jonny']),
    ("mcladdie",   "Laddie",                     "lad",     ['mcladdie'],              ['lad']),
    ("mcmiria",    "Miria",                      "miria",   ['mcmiria'],               ['miria']),
    ("mcrose",     "Rose",                       "rose",    ['mcrose'],                ['rose']),
    ("mcvegeir",   "Vegeir",                     "veger",   ['mcvegeir'],              ['veger']),
    ("ncangbis",   "Angela Bishop",              "abshp",   ['ncangbis'],              ['abshp']),
    ("ncbigjes",   "Big Jesus Mordino",          "bgjes",   ['ncbigjes'],              ['bgjes']),
    ("ncbishop",   "John Bishop",                "bishp",   ['ncbishop'],              ['bishp']),
    ("ncchrwri",   "Christopher Wright",         "cw",      ['ncchrwri'],              ['cw']),
    ("nceldrid",   "Eldridge",                   "eld",     ['nceldrid'],              ['eld']),
    ("ncethwri",   "Ethyl Wright",               "ew",      ['ncethwri'],              ['ew']),
    ("ncftully",   "Father Tully",               "tully",   ['ncftully'],              ['tully']),
    ("ncjimmyj",   "Jagged Jimmy J",             "jimmy",   ['ncjimmyj'],              ['jimmy']),
    ("ncjules",    "Jules",                      "jules",   ['ncjules'],               ['jules']),
    ("nckeiwri",   "Keith Wright",               "keith",   ['nckeiwri'],              ['keith']),
    ("nckitty",    "Miss Kitty",                 "kitty",   ['nckitty'],               ['kitty']),
    ("nclabish",   "Leslie Anne Bishop",         "lbshp",   ['nclabish'],              ['lbshp']),
    ("ncliljes",   "Lil' Jesus Mordino",         "ljmrd",   ['ncliljes'],              ['ljmrd']),
    ("ncmason",    "Mason",                      "mason",   ['ncmason'],               ['mason']),
    ("ncnikki",    "Darlin' Nikki",              "nikki",   ['ncnikki'],               ['nikki']),
    ("ncorvill",   "Orville Wright",             "write",   ['ncorvill'],              ['write']),
    ("ncrenesc",   "Renesco",                    "rene",    ['ncrenesc'],              ['rene']),
    ("ncresear",   "Marjorie Reed",              "marj",    ['ncresear'],              ['marj']),
    ("ncsalvat",   "Louis Salvatore",            "salva",   ['ncsalvat'],              ['salva']),
    ("ncstulit",   "Stuart Little",              "stul",    ['ncstulit'],              ['stul']),
    ("nctray",     "T-Ray",                      "tray",    ['nctray'],                ['tray']),
    ("nhmyron",    "Myron",                      "myron",   ['nhmyron'],               ['myron']),
    ("ocariel",    "Ariel",                      "ariel",   ['ocariel'],               ['ariel']),
    ("ocdalia",    "Dalia",                      "dal13",   ['ocdalia'],               ['dal13']),
    ("ocgoris",    "Goris",                      "goris",   ['ocgoris'],               ['goris']),
    ("ocgrutha",   "Gruthar",                    "gruth",   ['ocgrutha'],              ['gruth']),
    ("ocjoseph",   "Joseph",                     "josep",   ['ocjoseph'],              ['josep']),
    ("qcbird",     "Vice President Bird",        "bird",    ['qcbird'],                ['bird']),
    ("qccurlng",   "Charles Curling",            "curl",    ['qccurlng'],              ['curl']),
    ("qcfrank",    "Frank Horrigan",             "ssa",     ['qcfrank'],               ['bosss']),
    ("qcgranit",   "Sergeant Granite",           "grani",   ['qcgranit'],              ['grani']),
    ("qhprzrch",   "Dick Richardson",            "presi",   ['qhprzrch'],              ['presi']),
    ("rcascort",   "Mayor Ascorti",              "ascor",   ['rcascort'],              ['ascor']),
    ("rcdrjohn",   "Painless Doc Johnson",       "docj",    ['rcdrjohn'],              ['docj']),
    ("rcfannie",   "Fannie Mae",                 "fanni",   ['rcfannie'],              ['fannc', 'fanni']),
    ("rchakes",    "Obidiah Hakeswill",          "obad",    ['rchakes'],               ['obad']),
    ("rclou",      "Louise",                     "lou",     ['rclou'],                 ['lou']),
    ("rcmarge",    "Marge LeBarge",              "marge",   ['rcmarge'],               ['marge']),
    ("rcmarion",   "Earl Marion",                "marin",   ['rcmarion'],              ['marin']),
    ("rcmcgrew",   "Dan McGrew",                 "dan",     ['rcmcgrew'],              ['dan']),
    ("rcwade",     "Ben Wade",                   "ben",     ['rcwade'],                ['ben']),
    ("scdocjub",   "Doctor Jubilee",             "jub",     ['scdocjub'],              ['jub']),
    ("scelise",    "Ranger Chief Elise",         "elise",   ['scelise'],               ['elise']),
    ("scenlone",   "Enlightened One",            "eo",      ['scenlone'],              ['eo']),
    ("schenry",    "Doctor Henry",               "henry",   ['schenry'],               ['henry']),
    ("scmerk",     "Merk",                       "merk",    ['scmerk'],                ['merk']),
    ("scmira",     "Mira",                       "skeri",   ['scmira'],                ['skeri']),
    ("scrobo",     "Robodog",                    "dogr",    ['scrobo'],                ['dogr']),
    ("scsherif",   "Sheriff Dumont",             "dum",     ['scsherif'],              ['dum']),
    ("scvortis",   "Vortis",                     "vort",    ['scvortis'],              ['vort']),
    ("scwestin",   "Roger Westin",               "west",    ['scwestin'],              ['west']),
    ("shtandi",    "Tandi",                      "tndi2",   ['shtandi'],               ['tndi2']),
    ("slvcc1",     "Don",                        "don",     ['slvcc1'],                ['don']),
    ("tribec1",    "Krom",                       "krom",    ['tribec1'],               ['krom']),
    ("tribec12",   "Chieftain",                  "chief",   ['tribec12'],              ['chief']),
    ("tribec4",    "Shaman",                     "sham",    ['tribec4'],               ['sham']),
    ("tribec7",    "Kurisu",                     "kur",     ['tribec7'],               ['kur']),
    ("vcamanda",   "Amanda",                     "ama",     ['vcamanda'],              ['ama']),
    ("vcandy",     "Doctor Andrew",              "andr",    ['vcandy'],                ['andr']),
    ("vcbarkus",   "Barkus",                     "bark",    ['vcbarkus'],              ['bark']),
    ("vccasidy",   "John Cassidy",               "casdy",   ['vccasidy'],              ['casdy']),
    ("vcconnar",   "Connar",                     "cnr",     ['vcconnar'],              ['cnr']),
    ("vcdrtroy",   "Doctor Troy",                "troy",    ['vcdrtroy'],              ['troy']),
    ("vcdwnbar",   "Lydia",                      "lydia",   ['vcdwnbar'],              ['lydia']),
    ("vcgreg",     "Gregory",                    "greg",    ['vcgreg'],                ['greg']),
    ("vcharry",    "Happy Harry",                "hhary",   ['vcharry'],               ['hhary']),
    ("vclynett",   "Joanne Lynette",             "lynet",   ['vclynett'],              ['lynet']),
    ("vcmainwk",   "Valerie",                    "vcval",   ['vcmainwk'],              ['vcval']),
    ("vcmclure",   "McClure",                    "mcclr",   ['vcmclure'],              ['mcclr']),
    ("vcmoore",    "Thomas Moore",               "moore",   ['vcmoore'],               ['moore']),
    ("vcnancy",    "Phyllis",                    "phl",     ['vcnancy'],               ['phl']),
    ("vcoldjoe",   "Old Joe",                    "ianoj",   ['vcoldjoe'],              ['ianoj']),
    ("vcstark",    "Stark",                      "stark",   ['vcstark'],               ['stark']),
    ("vcwalace",   "Wallace",                    "wall",    ['vcwalace'],              ['wall']),
    ("vilann",     "Ann",                        "annvv",   ['vilann'],                ['annvv']),
    ("wcbrnbot",   "Skynet",                     "sky",     ['wcbrnbot'],              ['sky']),
    ("wcdobbs",    "Private Dobbs",              "dobbs",   ['wcdobbs'],               ['dobbs']),
]
