{100}{}{Vidíš jednu ze svých tet, Morlis. Tu, která tì vždycky nesnášela.}
{101}{mor20}{Proè otravuješ, synovèe? Nevidíš, že mám práci?}
{102}{}{Hmm, dobøe. Promiò.}
{103}{mor1}{O co jde? Nevidíš, že mám spoustu práce?}
{104}{}{No... Mynoc øíkal...}
{105}{mor2}{Mynoc øíkal co? Ven s tím, dítì!}
{106}{}{Že, no... že bys mohla mít nìjaký pazourek.}
{107}{mor3}{Taky že mám. A ty ho teï ode mì budeš chtít, co?}
{108}{}{Vlastnì... no, ano.}
{109}{mor4}{Dobrá... chci tøi léèivé prášky. Blíží se zlé èasy a já chci být pøipravená. Pøines mi je a já ti dám pazourek. A teï bìž!}
{110}{}{Ano, madam!}
{111}{mor5}{Neplýtvej mým èasem. Máš pro mì ty léèivé prášky?}
{112}{}{Ano, tady jsou.}
{113}{}{No... vlastnì ne.}
{114}{mor6}{Tady je pazourek. A teï odtud zmiz! Nemám èas s tebou klábosit.}
{115}{}{Dìkuju, teto Morlis.}
{116}{mor7}{Zase plýtváš mým èasem! Jak se z tebe vùbec mohl stát Vyvolený?}
{117}{}{Ano, teto Morlis.}
{118}{}{Éé, teto Morlis, mám s sebou ty tøi prášky.}
{150}{}{Teto Morlis, jsem na velmi riskantní výpravì za záchranou naší vesnice. A moje šance na úspìch se dramaticky zvýší, když si ty léèivé prášky nechám pro sebe a ty mi dáš ten pazourek. Souhlasíš?}
{151}{mor8}{Co si myslíš, že dìláš, dítì? Takhle by se Vyvolený chovat nemìl. A teï mi zmiz z oèí!}
{152}{mor9}{Pokud je pro tebe ten pazourek tolik dùležitý, že jsi ochotný zneuctít jméno Vyvoleného, tak prosím. Vezmi si ho a zmiz mi z oèí.}
{153}{}{Ano, teto Morlis.}
{154}{mor10}{No... tak dobrá. Tady je ten pazourek. Pøeju ti bezpeènou cestu, dítì.}
{155}{mor11}{Ne, nesouhlasím. A teï pøestaò ztrácet mùj èas a zmiz odsud!}
{156}{}{Ano, teto Morlis.}
{200}{mor12}{Vítej zpìt. Co svatá Tøináctka? Už víš, kde leží?}
{201}{}{Ne, teto Morlis, já...}
{202}{mor13}{No tak odsud rychle vypadni a najdi ji! Jsi naše jediná nadìje!}
{203}{}{Ano, teto Morlis.}
{204}{mor14}{Á, to jsi zase ty. Zase jsi selhal v plnìní svého poslání?}
{205}{}{Ano, teto Morlis, ale...}
{206}{mor15}{Tak odsud vypadni a nevracej se, dokud ho nesplníš! Proè ztrácíš èas návratem sem, když místo toho mùžeš pokraèovat v pátrání!?}
{207}{}{Ano, teto Morlis.}
{208}{mor16}{Skuteènost, že tu stojíš, mùže znamenat jen to, že tvoje výprava je úspìšnì u konce. Neztrácel bys pøece drahocenný èas návratem s prázdnou, že ne?}
{209}{}{Ano, teto Morlis. Tedy ne, teto Morlis! Ehm, budu muset jít, teto Morlis.}
{210}{mor17}{Tak, dítì. Po kolikáté už tady pøede mnou stojíš... zase se vracíš s prázdnou?}
{211}{}{Ano, teto Morlis.}
{212}{}{Poslouchej, }
{213}{}{. Lidé umírají, dobytek hyne a úroda vadne. Všichni jsme vyhladovìlí, nemocní nebo obojí zároveò. Nezbývá nám už moc èasu. Pokud brzy nenajdeš GECK, je s námi konec. Rozumíš mi?}
{214}{}{Ano, teto Morlis.}
{215}{mor19}{Tak odsud padej a najdi GECK! Jsi naše jediná nadìje!}
{216}{}{Ano, teto Morlis.}
{300}{mor22}{Vypadá to, že jsem ten pazourek nìkam založila. No co, alespoò teï mám svoje léèivé prášky. A teï mazej pryè. Nemám èas na to, abych tady s tebou klábosila.}
{301}{mor21}{Proè otravuješ, neteøi? Nevidíš, že mám práci?}
{302}{mor23}{Nìjak ten pazourek nemùžu najít. Urèitì jsi mi ho sebral, když jsem se nedívala. Už jsem tì jednou takhle chytla. A teï mazej pryè, darebáku jeden. Nemám èas na to, abych tady s tebou klábosila.}
{303}{mor24}{Takže... ehm, omlouvám se, ale vypadá to, že jsem ten pazourek nìkam založila. Pøeju ti bezpeènou cestu, dítì.}
{304}{mor25}{Už jsem ti ten pazourek dala, hlupáku. Teï pøestaò plýtvat mým èasem a vypadni odsud!}
{305}{mor26}{Už jsem ti ten pazourek dala, hlupáku. Dobrá, alespoò teï mám svoje léèivé prášky. A teï padej! Nemám èas na klábosení.}
