{100}{}{Vidíš mladou enu.}
{101}{}{Vidíš Chrissy, Rebeèinu dceru.}
{102}{}{Vidíš hezkou mladou enu. Vypadá sebejistì a urèitì umí i bojovat.}
{103}{chrsy1}{Jestli se mì pokusíš znásilnit, budeš nosit svoje koule jako motılka. Je ti to jasnı?}
{104}{chrsy2}{Nech mì hádat. Kámoše u omrzelo dostávat ode mì kopance do koulí, tak poslali tebe, a zkusíš nìjakı oplzlosti. Fajn, dopadneš stejnì jako oni. Jen budu muset kopnout trochu vıš. Je ti to jasnı?}
{105}{}{Motılka?}
{106}{}{}
{107}{}{O co tu jít? Kdo ty?}
{108}{}{}
{109}{}{Chci jen vìdìt, kdo jsi a co se tady dìje.}
{110}{chrsy3}{Jo. Je to takovı ozdobnı kus látky, co se nosí okolo krku pro okrasu. Pøipomíná trošku šálu, ale pro mue. Tak, a teï si pøedstav, e tì nakopnu vší silou TAK, e se ti ta tvoje chlouba omotá kolem krku. U je ti to jasnı?}
{111}{}{Já rozumìt. Já nechtít motılka. Ty neubliovat.}
{112}{}{Dovedu si to ivì pøedstavit. Prosím, neubliuj mi.}
{113}{chrsy4}{Dobøe, ale proè jsi tady?}
{114}{}{}
{115}{}{Já chtít vìdìt o co tu jít? Kdo ty?}
{116}{}{}
{117}{}{Chci jen vìdìt, kdo jsi a co se tady dìje.}
{118}{chrsy5}{Opravdu? Skvìlé! Tak jdeme.}
{119}{}{Dobøe.}
{120}{}{V krátkosti, jmenuju se Chrissy a jsem ze Squatu. Byla jsem minulı tıden venku na prùzkumu a našla jsem tu nìjakı vchod.
 Myslela jsem si, e by to mohl bıt tøeba starı opuštìnı dùl nebo tak nìco. Rozhodla jsem se to zjistit.
 No a není to dùl, je to tajnı vstup do Vaultu 15. Vault pouívá banda nájezdníkù jako svoji základnu.
 Øíkají si Khanové. Chytili mì, kdy jsem èmuchala kolem a jejich vùdce, Darion, mì tady zamknul.}
{121}{}{Tak jo. Já vzít ty domù.}
{122}{}{Tak dobøe, vezmu tì domù.}
{123}{chrsy7}{No to mì podr. Dneska musí bıt mùj šastnı den. Èemu vdìèím za to, e tì zase vidím?}
{124}{}{}
{125}{}{O co tu jít? Kdo ty?}
{126}{}{}
{127}{}{Chci jen vìdìt, kdo jsi a co se tady dìje.}
{128}{chrsy12}{Prosím, vezmi mì k mojí matce, Rebecce.}
{129}{chrsy8}{Mùj rytíø v lesklé zbroji se vrací. A leskla by se ještì víc, kdybys ji nìkdy taky vyèistil. Jo a taky by neškodilo se obèas vykoupat. Take, co pro tebe mùu udìlat?}
{130}{}{Tak nashle. U muset jít.}
{131}{}{Jdu tì jen pozdravit. U musím jít.}
{132}{chrsy9}{Hele, já vím, e jsem trošku drzá, ale chtìla jsem ti øíct, e jsem ti opravdu moc vdìèná za svou záchranu. Díky moc!}
{133}{}{To bıt v poøádku.}
{134}{}{Není zaè.}
{135}{chrsy10}{Lidé ze Squatu chrání ty chlapy tím, e jim pomáhají dret Vault v tajnosti, ale ani netuší, co se tam dole doopravdy dìje. Darion nám øekl, e se Vault opravuje, abysme v nìm mohli všichni bezpeènì ít a mìli spoustu vody a jídla, ale všechno jsou to jenom li. Byla jsem tam a všechno jsem vidìla. Vault je mrtvı a stroje na vırobu jídla a vody jsou rozbité. Naše jídlo a voda pochází z pøepadenıch karavan.}
{136}{chrsy11}{Podívej, musím jít domù a všechny varovat. Nemùeme tìm zrùdám u dál pomáhat. Vezmeš mì domù?}
