{100}{}{Vidíš staršího mue.}
{101}{}{Vidíš Dariona, vùdce bandy Novıch Khanù.}
{102}{}{Vidíš staršího mue s øídkımi šedivımi vlasy. Vypadá to, e je na svùj vìk ve skvìlé kondici.}
{103}{dario1}{Tak koneènì jsi tady. Spasitel utiskovanıch, ochránce práva a symbol nadìje lidstva. Taková blbost! Poslyš, ještì ne zaèneš s tìma otravnıma vástama, chci ti øíct, e ti na nì seru. Take, co kdybysme se teï vykašlali na formality a pøešli rovnou k vìci a to máme z krku? Právì jsem se toti rozhodl, e z tebe udìlám rádlo pro mıho psa. Vem si ho, Èerte!}
{104}{}{Beru.}
