{100}{}{Vidíš starého mue.}
{101}{}{Vidíš Chrise, obsluhu èerpací stanice.}
{102}{}{Vidíš starce obleèeného ve špinavém fialovém rouchu.}
{103}{}{Zdravím tì, cizinèe. Och! Podívejme se na to krásnı auto. U léta jsem ádné nevidìl. Co pro tebe mùe starı Chris udìlat?}
{104}{}{Zdravím tì, cizinèe. Nikdy jsem tì v tìchto konèinách nevidìl. Co pro tebe mùe starı Chris udìlat?}
{105}{}{Co bıt tohle za místo?}
{106}{}{Hledat Navarro. To bıt tady?}
{107}{}{Vidìt ty letìt tady ocelové ptáky?}
{108}{}{Znát jméno Enkláva? Bıt oni zde?}
{109}{}{Jen se dívat.}
{110}{}{Co je tohle za místo?}
{111}{}{Hledám Navarro. Jsem tu dobøe?}
{112}{}{Nevidìl jsi tu nìkde létat vertibirdy?}
{113}{}{Neslyšel jsi nìkdy o Enklávì? Mìlo by to bıt nìkde tady.}
{114}{}{Jen se tu tak rozhlíím.}
{115}{}{Tady bydlím já, Chris, a tohle je èerpací stanice. Nikdy jsi nic takového nevidìl? Tøeba ve starıch èasopisech? Tak to je pøesnì to, co tady vidíš. Èerpací stanice s obsluhou.}
{116}{}{Hledat Navarro. To bıt tady?}
{117}{}{Vidìt ty letìt tady ocelové ptáky?}
{118}{}{Znát jméno Enkláva? Bıt oni zde?}
{119}{}{Eh... asi jít.}
{120}{}{Hledám Navarro. Jsem tu dobøe?}
{121}{}{Nevidìl jsi tu nìkde létat vertibirdy?}
{122}{}{Neslyšel jsi nìkdy o Enklávì? Mìlo by to bıt nìkde tady.}
{123}{}{Promiò, ale u musím jít.}
{124}{}{Navarro? O tom místì u jsem neslyšel dlouhá léta. Je to stará vojenská základna jihovıchodnì od San Francisca, tudí je to jiním smìrem odtud.}
{125}{}{Tam já bıt. To nebıt Navarro.}
{126}{}{Díky. Podívat se tam.}
{127}{}{Ty mi lhát. Já vìdìt, e tohle bıt Navarro. Ty øíct pravdu, nebo ty litovat!}
{128}{}{Tam jsem byl a to není Navarro.}
{129}{}{Dobøe. Podívám se tam. Díky.}
{130}{}{Leš mi. Vím, e Navarro je tady. Øekni mi pravdu, nebo toho budeš litovat!}
{131}{}{Co? Eh... samozøejmì e je. Pøed èasem jsem o ní slyšel! Vojenská základna Navarro se nachází jihovıchodnì od San Francisca.}
{132}{}{Ty lhát. Nemám trpìlivost. Øíct mi pravdu nebo já s ty zatoèit!}
{133}{}{Leš. Na tohle nemám trpìlivost. Øekni mi pravdu, nebo s tebou zatoèím.}
{134}{}{Jdi do prdele! (Vytáhne z roucha vysílaèku.) Chceš vidìt, kdo s kım zatoèí? Mám tu pár chlapù, kteøí ti ukáou novej vıznam tohohle slova! (Chystá se vysílaèku zapnout.)}
{135}{}{Já ty zabít!}
{136}{}{Co ty dìlat?}
{137}{}{Já jít.}
{138}{}{To byl špatnej tah, kámo.}
{139}{}{Co si myslíš, e dìláš?}
{140}{}{Poslyš, u jdu.}
{141}{chris7}{(Mluví do vysílaèky.) Poplach! Na stanici máme vetøelce! Poplach!}
{142}{}{[KONEC]}
{143}{}{No, hezky jsme si popovídali. Dám ti jednu radu. Tady není nic ne pustina a radiace. Civilizace je jinì odtud. Bıt tebou, zamíøím tím smìrem.}
{144}{}{Díky.}
{145}{}{Ocelové ptáky? Aha, ty myslíš vertibirdy. Proè je hledáš zrovna tady?}
{146}{}{Vertibirdy? To jsou moc zajímavé vìcièky. Proè je hledáš zrovna tady?}
{147}{}{Šaman øíkat, e ptáci co unést vesnici letìt do Navarro. Já zkusit najít.}
{148}{}{Lidi zajímat. Já zkusit pro nì najít.}
{149}{}{Ty vìdìt o ptáci? Co všechno ty vìdìt?}
{150}{}{Šaman mého kmene mi øíkal, e ty vertibirdy unesly naše lidi. Proto je chci najít.}
{151}{}{Znám pár lidí, kteøí se o vertibirdy zajímají. Snaím se je pro nì najít.}
{152}{}{Take ty vertibirdy znáš. Øekni mi o nich všechno, co víš.}
{153}{}{Šaman? Podívej, jestli tvùj šaman øíká, e vidìl nìjakou vìc, jak lítá a unáší lidi, tak se nejspíš jen moc naèuchal bylinek. Rozumíš?}
{154}{}{Hakunin bıt velkı šaman. Jestli øíct on vidìt tak to vidìt.}
{155}{}{Hakunin byl velkı šaman. Pokud øekl, e vidìl vertibirdy, tak je opravdu vidìl!}
{156}{}{No, to je mi sice úplnì jedno, ale v pøípadì, e bych nìjakı vertibird vidìl, komu to mám øíct?}
{157}{}{Øíct já. Já bıt nablízku.}
{158}{}{Øíct Shi.}
{159}{}{Øíct Bratrstvo Oceli.}
{160}{}{Øíct Hubologisti.}
{161}{}{Mùeš vybrat. Dát vìdìt Shi, Bratrstvu Oceli nebo Hubologisti. Všichni mít zájem.}
{162}{}{Øekneš to mnì. Budu nablízku.}
{163}{}{Dej vìdìt Shi.}
{164}{}{Dej vìdìt Bratrstvu Oceli.}
{165}{}{Dej vìdìt Hubologistùm.}
{166}{}{Mùeš si vybrat. Mùeš dát vìdìt Shi, Bratrstvu Oceli nebo Hubologistùm. Kadı z nich má o vertibirdy zájem.}
{167}{}{Shi, jo? No dobøe, kdy to øíkáš. Pošlu jim kdytak zprávu do Èínské ètvrti. Ale teï mám nìco na práci.}
{168}{}{Poèkat. Já mít mocné pøátele. Oni øíkat, e Navarro tady. Ty øíct kde, nebo já zatanèit váleènı tanec!}
{169}{}{Poèkej minutku, kámo. Oèividnì mám mocné pøátele a ti øíkají, e je Navarro nìkde tady. Øekni mi kde, nebo špatnì dopadneš!}
{170}{}{Bratrstvo... eh, jo, jasnì, e to udìlám. Ale teï mám nìco na práci.}
{171}{}{Poèkat. Já mít mocné pøátele. Oni øíkat, e Navarro tady. Ty øíct kde, nebo já zatanèit váleènı tanec!}
{172}{}{Poèkej minutku, kámo. Oèividnì mám mocné pøátele a ti øíkají, e je Navarro nìkde tady. Øekni mi kde, nebo špatnì dopadneš!}
{173}{}{Hubologisti? Jo, jasnì, dám jim vìdìt, jestli nìco uvidím. Ale teï mám nìco na práci.}
{174}{}{Poèkat. Já mít mocné pøátele. Oni øíkat, e Navarro tady. Ty øíct kde, nebo já zatanèit váleènı tanec!}
{175}{}{Poèkej minutku, kámo. Oèividnì mám mocné pøátele a ti øíkají, e je Navarro nìkde tady. Øekni mi kde, nebo špatnì dopadneš!}
{176}{}{Sakra, kdo si to má pamatovat... eh, dobøe, pokud nìco zjistím... no a teï mám nìco na práci.}
{177}{}{Poèkat. Já mít mocné pøátele. Oni øíkat, e Navarro tady. Ty øíct kde, nebo já zatanèit váleènı tanec!}
{178}{}{Poèkej minutku, kámo. Oèividnì mám mocné pøátele a ti øíkají, e je Navarro nìkde tady. Øekni mi kde, nebo špatnì dopadneš!}
{179}{}{Eh... hej, poèkej chvilku. Já takhle mluvím jen proto, abych vystrašil rùzné nezvané návštìvníky a tak. Nechci mít ádné problémy, o kterıch tu mluvíš.}
{180}{}{Pak ty øíct nejlepší cesta na základna... hned!}
{181}{}{Pak mi tedy øekni tu nejlepší cestu na základnu... a to hned!}
{182}{}{To bude nejspíš padacími dveømi v mém pokoji. A teï u jdi a nech mì na pokoji.}
{183}{}{Dobøe, já jít.}
{184}{}{Dobøe, u jdu.}
{185}{}{No, èas od èasu tudy prolétávají. Obvykle letí od jihu smìrem od San Francisca. Jestli se zajímáš o vertibirdy, šel bych tímto smìrem.}
{186}{}{Dobøe, zkusit to tam.}
{187}{}{Mít pøátele, kteøí poádat já, aby najít vertibirdy. Oni øíkat, e letìt odsud.}
{188}{}{Dobøe, podívám se tím smìrem.}
{189}{}{Mám pøátele, kteøí mì poádali, abych našel vertibirdy. Øíkají, e pøilétají právì odsud.}
{190}{}{Enkláva? To je nìjaká skupina nebo co? To mi vùbec nic neøíká. Co jim chceš?}
{191}{}{Chtít pøidat.}
{192}{}{Chci se k nim pøidat.}
{193}{chris21}{Ty se k nim chceš pøidat? Vdy jsi divoch! Proè myslíš, e by chtìli nìjakého divocha?}
{194}{}{Ty se k nim chceš pøidat? Vdy jsi divoch! Proè myslíš, e by chtìli nìjakého divocha? A ještì s takovou bandou?}
{195}{}{Já mluvit vánì. Já pøidat k Enkláva.}
{196}{}{Já mluvit vánì. Já pøidat se k Enkláva.}
{197}{}{Myslím to vánì. Chci se pøidat k Enklávì.}
{198}{}{Myslím to vánì. Chci se pøidat k Enklávì.}
{199}{}{Poèkej chvíli, blbeèku. Snaíš se mi øíct, e jsi jeden z tìch vojákù, kteøí sem byli pøeloeni?}
{200}{}{Poèkej chvíli. Snaíš se mi øíct, e jsi jeden z tìch vojákù, kteøí sem byli pøeloeni?}
{201}{}{Hmm... jo tak.}
{202}{}{Pøesnì tak.}
{203}{}{Sákryš. Promiò mi to lhaní.
 Chodí nám sem spousta nováèkù a mım úkolem je oddìlit zrno od plev.
 Jdi nahoru k bránì, projdi skrz stromy a øekni jim heslo. Je to 'Ovèí hlava.' Jo a neuhıbej z té cesty!}
{204}{}{Díky!}
{205}{}{Poèkej chvíli, blbeèku. Snaíš se mi øíct, e jsi jeden z tìch vojákù, kteøí sem byli pøeloeni? Proè tedy nejsi sám?}
{206}{}{Poèkej chvíli. Snaíš se mi øíct, e jsi jeden z tìch vojákù, kteøí sem byli pøeloeni? Proè tedy nejsi sám?}
{207}{}{Eh... doprovod.}
{208}{}{To je mùj doprovod!}
{209}{}{No, nechci bıt hrubı nebo tak, ale tohle je soukromı pozemek. Jestli se chceš poflakovat, tak to nedìlej tady.}
{210}{}{[KONEC]}
{211}{chris29}{Zase zpátky? Co pro tebe mùe starı Chris udìlat tentokrát?}
{212}{}{Ty øíct, e Navarro na jih. Ty lháø! Já chtít pravdu tentokrát.}
{213}{}{Øekl jsi mi, e je Navarro na jihu, starouši. Teï chci vìdìt pravdu.}
{214}{chris30}{Vypadáš povìdomì. Myslím, e u jsem tì nìkde vidìl... ale ne, to není moné.}
{215}{chris34}{Vetøelec na stanici! Pošlete pomoc!}
{216}{chris35}{Poplach!}
{217}{chris36}{Poplach, vetøelec! Poplach, vetøelec!}
{218}{chris37}{Chcípni, skunku!}
{219}{chris38}{Za tvoji smrt mì Enkláva povıší!}
{220}{chris39}{Chcípni, primitive!}
{221}{chris31}{Co to...?!}
{222}{}{Ty pouít ta vysílaèka a litovat!}
{223}{}{Zkus pouít tu vysílaèku a budeš toho litovat!}
{224}{}{Táhni k èertu! (Vytáhne z roucha vysílaèku.) Chceš vidìt, kdo s kım zatoèí? Mám tu pár chlapcù, kteøí ti ukáou novej vıznam tohohle slova! (Chystá se vysílaèku zapnout.)}
{225}{}{Já ty zabít!}
{226}{}{Co ty dìlat?}
{227}{}{Já jít.}
{228}{}{To byl špatnej tah, kámo.}
{229}{}{Co si myslíš, e dìláš?}
{230}{}{Poslyš, u jdu.}
{231}{chris33}{Jo, dobøe.}
{232}{}{Vytáhl vysílaèku a chystá se varovat celou základnu! Musím to s ním rychle vyøídit.}
{233}{}{Sakra. Chlap vytáhnout mluvící krabièka. On mì prozradit. Muset on zastavit.}
{800}{}{Podaøilo se ti pøelstít Chrise, aby ti øekl heslo.}
{810}{}{Podaøilo se ti zabít Chrise pøedtím, ne stihl varovat základnu.}
