{100}{}{Vidíš osobu v energo zbroji.}
{101}{}{Vidíš velitele základny Navarro.}
{102}{}{Vidíš osobu v energo zbroji neobvyklého vzhledu. Na prsou má znak, kterı nepoznáváš.}
{103}{cmdr1}{Kdo k èertu jste? Poplach! Vetøelci pronikli na základnu!}
{104}{cmdr2}{Nemám èas tlachat s pìšáky. Odchod.}
{105}{}{Èas zemøít.}
{106}{}{Dobøe.}
{107}{cmdr3}{U jsem øekl, e na tebe nemám èas. Vypadni z mojí kanceláøe a nevracej se, dokud tì nezavolám. Odchod!}
{108}{cmdr4}{Neuposlechnutí pøímého rozkazu nadøízeného dùstojníka je povaováno za zradu. Na váleènı soud nemám èas, take to vyøídím sám. Stráe! Zabijte toho idiota!}
{109}{}{Dobøe.}
{110}{}{Polib si!}
{111}{cmdr5}{FOB je v támhleté skøíòce. A mì vedoucí kontaktuje, jakmile bude zabezpeèen. Odchod!}
{112}{}{Ano, pane!}
{113}{cmdr6}{Pohni s tím, vojáku. Nemám na to celı den.}
{114}{}{Ano, pane!}
{115}{cmdr7}{Nech moji skøíòku na pokoji, nebo ti ukáu co je to opravdová bolest.}
{116}{}{Ano, pane!}
{117}{cmdr8}{Na základnì je vyhlášen poplach a já vás nepoznávám. Vaše doklady, vojáku.}
{118}{}{Jaké doklady?}
{119}{}{Ty vyhulit mi!}
{120}{}{Zdá se, e je nemám u sebe...}
{121}{}{Doklady? Mám vaše doklady pøímo tady!}
{122}{cmdr9}{Špatná odpovìï, èerve. Doklady bys mìl mít vdy u sebe. To bys mìl vìdìt!}
{123}{}{Jdi do prdele.}
{124}{cmdr10}{Nech moji skøíòku na pokoji, nebo ti ukáu co je to opravdová bolest.}
{125}{cmdr11}{Èas zemøít.}
{200}{cmdr12}{No dobøe, tak a to máme rychle za sebou. Nemám rád, kdy mi mutanti smrdí v kanceláøi a já mám práce, e bych se z toho mohl posrat. Pracuješ pro Salvatora? }
{201}{}{Do toho ti nic není, kreténe.}
{202}{}{Nepracuju pro nikoho.}
{203}{}{A pokud ano?}
{204}{}{Jasnì, pracuju pro Salvatora.}
{205}{}{Ne odpovím na jakoukoliv otázku, chci se nejdøív zeptat na pár vlastních.}
{210}{cmdr13}{Na takové kecy nemám èas. Stráe! Zabijte toho mutanta!}
{220}{cmdr14}{Take øíkáš, e nejsi nic ne bludná krysa z pustiny, která jen tak naskoèila do jednoho z našich vertibirdù?}
{221}{}{Eee, jo. Víceménì... a na tu èást, e jsem krysa.}
{222}{}{Pøesnì tak.}
{223}{}{Ne. Øíkám, e je to jenom jedno velké nedorozumìní. Vùbec nevím, kdo jste a ani mì to nezajímá. Take pokud vám to nebude vadit, pùjdu zase dál.}
{230}{cmdr15}{Dobøe, take pokud jsi sám, tak s tebou u nemusím dál ztrácet èas. Stráe! Zabijte toho mutanta!}
{240}{cmdr16}{Odsud se ivı nedostaneš, mutante. Nemùu pøece riskovat, e vykecáš polohu základny všem svım kamarádùm z pustiny, e? Stráe! Zabijte toho mutanta!}
{250}{cmdr17}{Øekni mi, co chci vìdìt a zaruèuju ti, e tvá smrt bude rychlá a... relativnì bezbolestná. Poslal tì Salvatore?}
{251}{}{Eeeee... ne? Poèkat, jo. Moná.}
{252}{}{Ne. Hrát si na schovku v tom vašem létajícím stroji byl mùj nápad. Geniální, já vím.}
{253}{}{Jo. Myslel si, e by ten obchod mohl ještì vylepšit, kdy mì pošle s váma. Dobrı, ne?}
{254}{}{Ne odpovím na jakoukoliv otázku, chci se nejdøív zeptat na pár vlastních.}
{260}{cmdr18}{Na takové kecy nemám èas. Stráe! Zabijte toho mutanta!}
{270}{cmdr19}{To má bıt vtip, mutante? Myslím, e budeš mnohem vtipnìjší jako krvácející mrtvola. Stráe! Zabijte toho mutanta!}
{280}{cmdr20}{Coe? (Zachechtá se.) Krucinál, proè ne? Stejnì u jseš jednou nohou v hrobì. Co chceš vìdìt, mutante?}
{281}{}{Proè mi poøád øíkáš mutant?}
{282}{}{Kdo k èertu jste, chlapi?}
{283}{}{Kde to jsem?}
{284}{}{Kde seenu takové hezké brnìní?}
{285}{}{To u mi staèilo.}
{290}{cmdr21}{Protoe jím JSI. Jistì, moná vypadáš jako èlovìk, ale nenech se zmást. Poøád jsi mutant. Ty a všichni ostatní na pevninì. Všichni jste nakaení. Nìjaké další otázky?}
{300}{cmdr22}{My jsme Enkláva. Poslední bašta skuteèného lidstva na téhle prokleté planetì. My jsme jediní, kteøí stále vzdávají hold staré èervenobílomodré. Je to tak, my jsme praví patrioti. Jíme orly bìlohlavé a serem hvìzdy a pruhy. Jsme vše, co zbylo ze slavnıch Spojenıch státù americkıch. Ale je nás dost. Ó ano, je nás dost na to, abysme to tady dali do poøádku. Na to se mùeš spolehnout, mutante. Nìjaké další otázky?}
{310}{cmdr23}{Tohle je Navarro. Naše skrytá základna na pevninì. Jsme pøímo na pobøeí Kalifornie a Tichého oceánu. Nìjaké další otázky?}
{320}{cmdr24}{Jen kdy ji sundáš z mého mrtvého tìla. Pøeju hodnì štìstí, mutante. Nìjaké další otázky?}
{330}{cmdr25}{To je dobøe, protoe mì u unavuje plıtvat dechem na tlachání s mutantem. Popravdì, celá tahle záleitost je jen plıtvání mım drahocennım èasem, protoe je mi úplnì jedno, co mi chceš sdìlit. Stráe! Zabijte toho mutanta!}
