{100}{}{Vidíš mue ve vojenské uniformì.}
{101}{}{Vidíš mechanika Quincyho.}
{102}{}{Vidíš mue ve vojenské uniformì. Soudì podle mastnıch skvrn na uniformì hádáš, e je to spíš mechanik ne voják.}
{103}{quin1}{Jmenuju se Quincy, vojáku. Proè mi klepeš na rameno? Ztratil ses?}
{104}{}{Potøebovat na nìco zeptat.}
{105}{}{No nic.}
{106}{}{Zdravím. Potøebuju se tì na nìco zeptat.}
{107}{}{Zapomeò na to.}
{108}{quin2}{No tak dobøe, ale ptej se rychle. Musím ještì dodìlat inventuru.}
{109}{quin3}{Co potøebuješ vìdìt?}
{110}{}{Co bıt tohle za místo?}
{111}{}{Vyvolenı hledat plány od vertibird. Kde je najít?}
{112}{}{Technik øíkat, e plány vertibird bıt nìkde tady.}
{113}{}{Já teï jít.}
{114}{}{Co je tohle za místo?}
{115}{}{Hledám plány k vertibirdùm. Nevíš, kde je najdu?}
{116}{}{Technik mi øekl, e tu najdu plány k vertibirdùm.}
{117}{}{No, u musím jít.}
{118}{quin4}{Tohle je údrba. Opravujeme tu všechno s vıjimkou vertibirdù.}
{119}{}{Kde opravovat vertibird?}
{120}{}{Kde se opravují vertibirdy?}
{121}{quin5}{Kvùli svojí velikosti se vejdou jen do hangáru nebo venku. Rozumíš?}
{122}{}{Hmm... jo.}
{123}{}{Hmm, jasnì. Rozumím.}
{124}{}{Hmm... no, já sice mám kopie tìch plánù, ale nemùu je dát kdejakımu pobudovi, kterej si o nì øekne. Na co je chceš?}
{125}{}{Mít na jih pøátele co je moc potøebovat.}
{126}{}{Hmm... no...}
{127}{}{Mám dole na jihu pár pøátel, kteøí po nich moc touí.}
{128}{}{Sera mi øekl, e mu je mám pøinést.}
{129}{quin7}{Tak dole na jihu... do prdele! Máme tu špeha! Stráe! Poplach!}
{130}{}{Jejda.}
{131}{}{A do prdele. Tak tohle se mi nepovedlo.}
{132}{}{Ty jsi asi trochu pomalejší, e jo? No, neøíkají vám poskoci jen tak bez dùvodu. Podívej, Einsteine, nemùu ti ty plány dát jen tak bez povolení, rozumíš? Take se vra zpátky za tím, kdo tì sem poslal, a pìknì si od nìj pøines písemnı potvrzení.}
{133}{}{Podívej, Einsteine, nemùu ti ty plány dát jen tak bez povolení. Rozumíš? Take se vra zpátky za tím, kdo tì sem poslal, a pìknì si od nìj pøines písemnı potvrzení.}
{134}{}{Dobøe, já jít.}
{135}{}{Ne, zaprvé já tì zastøelit, zadruhé najít plány a pak... k sakru, co následovat po dvojka?}
{136}{}{Fajn, máš to mít.}
{137}{}{Ne, myslím, e bude jednodušší, kdy tì zastøelím a zatímco budeš na zemi tiše krvácet, vezmu si ty plány.}
{138}{quin10}{Technik øíkáš... myslíš Raula? On tì poslal?}
{139}{}{Eh, no jo.}
{140}{}{Eh, ne.}
{141}{}{Jo, pøesnì on.}
{142}{}{Ne, myslím, e se nejmenoval Raul.}
{143}{}{Zatracenì! Víš, Raul by ztratil i svoji hlavu, kdyby mu ji tak pevnì nepøišili k prdeli. Sráè jeden! To je u potøetí v tomhle ètvrtletí, kdy ty plány ztratil! A teï u ani nemá odvahu na to, aby za mnou pøišel a øekl si o nì sám? Fajn, jsou támhle ve skøíni. Jo a a mu je doneseš, øekni tomu sráèovi, e bych ho rád vidìl.}
{144}{}{Díky.}
{145}{quin12}{Zase zpátky? U máš to potvrzení?}
{146}{quin13}{Zase ty? Co to bude tentokrát?}
{147}{}{Já mít plazmovou pušku. To úplnì staèit!}
{148}{}{Ne, ještì ne.}
{149}{}{Jo, mám zvláštní povolení. Velikou zasranou bouchaèku. Ta mi bude úplnì staèit!}
{150}{}{Ne, ještì ne.}
{151}{}{Chtít nìco zeptat.}
{152}{}{Chtít jen ty pozdravit.}
{153}{}{Chci se tì na nìco zeptat.}
{154}{}{Nic, jen jsem tì chtìl pozdravit.}
{155}{quin14}{Jseš blázen? Chodit tu bez uniformy? Rychle se pøevleè!}
{156}{quin15}{Jestli tì serant naèapá bez uniformy, nakope ti prdel.}
{157}{quin16}{Proè na sobì nemáš uniformu?}
{158}{quin17}{Zatracenì! Byli jsme napadeni! Poplach!}
{159}{quin18}{Vetøelci! Zavolejte stráe!}
{160}{quin19}{Stráe! Vetøelci na údrbì!}
{161}{quin20}{Co se dìje? Jsme napadeni?}
{162}{quin21}{Proè ten poplach? Co se stalo?}
{163}{quin22}{Co se to sakra zase dìje?}
{164}{quin26}{Hej! Nehrabej se v tìch šuplících!}
{165}{quin27}{Øíkal jsem ti, e se nemáš hrabat v mıch vìcech! Stráe!}
{200}{quin28}{Aha. No, nevìø všemu, co nìkde zaslechneš.}
{201}{quin29}{Kdo ti to øíkal? Protoe on bude po tobì další, komu to ruènì vysvìtlím.}
{300}{quin23}{Nevidíš, e nemám èas?}
{301}{quin24}{Hej! Nehrabej se v tìch šuplících!}
{302}{quin25}{Øíkal jsem ti, e se nemáš hrabat v mıch vìcech! Stráe!}
