{100}{}{Vidíš malého muu s mohutnım knírem.}
{101}{}{Vidíš Velkého Ananiase.}
{102}{}{Vidíš malého kníratého mue, kterı se tváøí nenápadnì.}
{103}{ana16}{Vy! Co chcete udìlat bıvalému Velkému Ananiasovi?}
{104}{ana17}{Jdìte ode mì!}
{105}{ana18}{Jdìte nièit kšefty nìkomu jinému.}
{106}{ana19}{Zkoušejte to na nìkoho jiného.}
{107}{ana20}{U jste mi zpùsobil dost škod.}
{108}{ana21}{Jdìte pryè, u jste mi zpùsobil dost škod.}
{109}{ana22}{Mám hlad.}
{110}{ana23}{Jak teï uivím svoji rodinu?}
{111}{ana24}{Narodil jste se s pøíliš malım srdcem.}
{112}{ana1}{Ne, mùj pøíteli, MUMIE! Pøivezená pøímo ze starobylého Egypta a sem do pustin! Exkluzivnì pro vás!}
{113}{}{Dobøe, zkusím to. Kolik mì ta vysušená mrtvola bude stát?}
{114}{}{(Pro sebe.) Hmm, mumie je pøesnì to, co by odpovídalo popisu ghoula. Dobøe, podívám se na ni. Kolik?}
{115}{}{U jsem vidìl dost mrtvol. Sbohem.}
{116}{ana2}{Zdravím, vítejte, buïte zdráv! Jsem Velkı Ananias (Lehce se ukloní a mávne rukou.) Pøináším záhady od blízkého i vzdáleného pøítele. Záhady ze svìta leícího za naším svìtem... záhady Podsvìtí.}
{117}{ana3}{Chcete poznat záhady Podsvìtí Velkého Ananiase?}
{118}{}{Jaké záhady?}
{119}{}{Eh, rád vás poznávám, pane Velkı Anál...nìco.}
{120}{}{Hmm, ze záhad mám tìké spaní, radìji pùjdu. Sbohem.}
{121}{ana30}{Pøistupte blíe!}
{127}{ana4}{Dnes, pøímo v této místnosti, tu mám, exkluzivnì pro vás... nefalšovanou egyptskou mumii!}
{128}{}{Mumii?}
{129}{}{Mumii? Hmm, zajímalo by mì, jestli to náhodou není... ne, nikdo pøece není tak hloupı.}
{130}{}{Takové vìci mì nezajímají. Z mrtvol mi bìhá mráz po zádech.}
{131}{ana25}{Ustupte na stranu, blokujete platící zákazníky.}
{132}{ana26}{Myslím, e to pro vás není.}
{133}{ana27}{Co kdybyste odešel s tím svım malım kmenem nìkam jinam?}
{134}{ana28}{To opravdu není pro vás.}
{135}{ana29}{Aha, hmmm, co takhle JÍT (Ukáe prstem.) PRYÈ?}
{136}{ana5}{Èlovìku vaší úrovnì milerád ukáu tento unikátní a historickı vzorek za pouhıch $25.}
{137}{}{Dobøe, tady jsou peníze. A teï... mi ukate tu mumii!}
{138}{}{Nechci tolik utrácet. Myslím, e to pøeiju, kdy tu vìc neuvidím. Sbohem.}
{139}{ana6}{Jednoduše otevøte víko sarkofágu a pøed vámi se zjeví úasná mumie ve své starobylé slávì. Ale prosím, nedotıkejte se ji a, eh, nefote s bleskem.}
{140}{}{Dobøe.}
{141}{ana7}{Pohleïte! MUMIE! (Dveøe sarkofágu se otevøou a odhalí vysušenou mrtvolu, která vypadá jako obyèejnı ghoul stojící v chudì zdobeném, otluèeném a popraskaném papírovém sarkofágu.)}
{142}{ana8}{Pohleïte! Pøedstavuji vám MUMII (Dveøe rakve se zaskøípáním otevøou a odkryjí nefalšovanou egyptskou mumii stojící v sarkofágu, kterı vypadá, e byl vyroben z èistého zlata!)}
{143}{}{Hej, tak moment. Tohle není mumie. To je ghoul. WOODY! Hej WOODY! Jsi to ty?}
{144}{}{Vypadá jako ghoul.}
{145}{}{Tohle e je mumie? Nemùu uvìøit, e jsem zaplatil $25, abych vidìl šest stop vysokou hroudu sušeného masa. Sbohem.}
{146}{}{Páni, to je úasné... asi. (Na chvíli se upøenì podíváš na Mumii.) Eh, díky, sbohem.}
{147}{ana9}{(Mumie funí, malátnì se protahuje a poté se na tebe ospale podívá.) Zdravím. (Øekne ospale.)}
{148}{}{Do prdele! To *je* Woody! Utíkej Woody, utíkej! Dobrá, eh, tak kulhej! Bì, Woody, bì!}
{149}{ana10}{Ujišuju vás, e je tato mumie opravdu nefalšovaná.}
{150}{}{Nevìøím vám. Poèkejte, nìco zkusím. WOODY! Hej WOODY! Jsi to ty?}
{151}{}{No, kdy to øíkáte... ale já si opravdu myslím, e vypadá jako obyèejnı ghoul. Sbohem.}
{152}{}{(Woody, protoe je to opravdu Woody a ne mumie, kdo tu teï omámenì stojí pøed tebou, protrhne stìny papírového sarkofágu, zajeèí, uteèe ke dveøím a zanechá po sobì jen spìšné "Díky moc, cizinèe!" a útrky toaletního papíru, kterımi byl omotanı.)}
{153}{}{Ha! Já to vìdìl! V tomhle mìstì jste skonèil. U nejste ádnı Velkı Ananias, ale jen další kretén.}
{154}{}{Bì, Woody, bì! Aha! Já to vìdìl!}
{155}{ana12}{(Velkı Ananias pokrèí rameny.) Já vìdìl, e jsem si mìl radìji vybrat tu jednohlavou brahmínu. Holt budu muset zaèít od zaèátku.}
{156}{}{Jednohlavá brahmína? No jistì, tomu tak budu vìøit! Sbohem, šarlatáne.}
{157}{}{Probudil jsi ghoula Woodyho a osvobodil jsi ho z nechtìné mumifikace.}
{158}{}{Myslím, e si radìji vyslechnu tu historku o duchovi.}
{200}{}{Vím o vìcech, které jsou obyèejnému smrtelníkovi zapovìzené. Ajííííí! Nyarloth... och, promiòte (hehe). Byl jsem chvíli myšlenkami nìkde jinde.
 Znám pøíbìhy o duchovi, kterı straší tyto konèiny, a také o nefalšované egyptské mumii,
 kterou mùete vidìt v tomto nádherném sarkofágu pøed sebou.}
{201}{}{Vyprávìjte mi o té mumii. Umírám nedoèkavostí se o ní dozvìdìt nìco víc.}
{202}{}{Musím slyšet tu historku o duchovi. Eh, dostanu k tomu šálek dobrého horkého kakaa?}
{203}{}{Myslím, e tu nebudu ztrácet èas, a u se mi snaíte vnutit cokoliv.}
{300}{}{Tak tedy, (ukáe, abys šel blí) kdysi ila mocná královna, která vládla celému království.
 Drela se na svém trùnì pomocí zvláštního amuletu, kterı stále nosila kolem svého krku. Zajímavé, e?}
{301}{}{Eh, ano. To si pište. Take ta princezna mìla *magickı* amulet. Prosím, pokraèujte. U mì dál nenapínejte (zív).}
{302}{}{Myslím, e u to nebudu poslouchat. Sbohem.}
{400}{}{No, tak já to zkrátím. Zlı kouzelník otrávil mladou princeznu a vzal jí amulet. Od té doby
 bloudí po vedlejší místnosti. No, eh, o pùlnoci. Proto nechávám dveøe zamknuté.
 Pìknì strašidelné, e?}
{401}{}{Duch princezny bez amuletu ve vedlejší zaneøádìné místnosti? To je všechno? Nemùu uvìøit, e *tohle* vydáváte za pøíbìh.
 Radìji mi povìzte o té pitomé mumii, kterou tu údajnì máte.}
{402}{}{Myslím, e u to nebudu poslouchat. Sbohem.}
