{100}{}{Vidíš Laru.}
{150}{}{Je vùdcem tohoto gangu.}
{200}{}{Jmenuju se Lara a vedu tenhle gang. Doufám, e nebudeš dìlat ádnı problémy, nebo si tì pìknì podáme.}
{201}{larad2}{Nazdar. Potøebuješ nìco?}
{202}{}{Nemáš nìjakou práci?}
{203}{}{Jenom se rozhlíím.}
{204}{}{Hledám obchodníka jménem Vic.}
{205}{}{Aruh.}
{206}{}{Rara.}
{220}{larad3}{Ve mìstì nemáme ádnıho doktora a já ti nedokáu pomoct.}
{221}{larad4}{Promiò, poøád nerozumím.}
{222}{}{Chjo.}
{230}{larad5}{To jméno mi nic neøíká, ale lidi pøichází a odchází. Já je nehlídám. Zkus to u Becky. Tam se ukáou skoro všichni. Tøeba tam nìkdo nìco ví.}
{231}{}{Nemáš nìjakou práci?}
{232}{}{Dík. Mìj se.}
{240}{larad6}{Jestli tu nemáš co na práci, tak radši odejdi. Není to tady moc bezpeènı.}
{241}{larad7}{Aha, dobøe.}
{242}{}{Nemáš nìjakou práci?}
{243}{}{Dokáu se o sebe postarat.}
{244}{}{Dobøe, díky.}
{250}{larad8}{O tom nepochybuju. Jinak by tì u dávno nìkdo odpráskl.}
{251}{larad9}{Eh, ano, já vím. Nìco podobného jsi u øíkala.}
{252}{}{Nemáš nìjakou práci?}
{253}{}{Dobøe, díky.}
{260}{larad10}{Záleí na tom, co umíš. Je tu nìco, co mì zajímá. Jestli se ti to podaøí zjistit, nìco ti za to dám.}
{261}{larad11}{Jak jsem øíkala, sháním o nìkom informace... nebo o nìèem. Samozøejmì zaplatím.}
{262}{}{Jasnì. O co jde?}
{263}{}{Moná pozdìji.}
{270}{larad12}{Pokud si to rozmyslíš, dej mi vìdìt.}
{271}{}{Tak dobøe.}
{280}{}{No, na vıchod odsud je kostel. A u je uvnitø cokoliv, Metzgerovi lidi to velice dobøe hlídaj. Zjisti, co to je a máš u mì $200.}
{281}{}{To bylo jednoduché. To u dávno vím.}
{282}{}{Jasnì.}
{283}{}{Uvidím, co se dá dìlat.}
{290}{larad14}{Díky. A nezamíchej se do bitky... zatím. Mám plán.}
{291}{}{ádnı problém.}
{292}{}{Hned se vrátím.}
{300}{larad15}{A co tam teda je?}
{301}{}{Èisté chemické slouèeniny ve velkıch bednách.}
{302}{}{Nìjaké chemikálie ve velkıch kontejnerech.}
{303}{}{Ještì se na to radìji podívám.}
{310}{larad16}{Hmm. To dává smysl. Díky. Tady máš peníze.}
{311}{}{Proè myslíte?}
{312}{}{ádnı problém. Nashle.}
{320}{larad17}{Vidìli jsme pøijídìt karavany z Vault City a pak nìco pøekládali do karavan z New Reno.}
{321}{}{A dál? Jakı to dává smysl?}
{322}{}{Aha.}
{340}{larad18}{New Reno je v okolí hlavní drogové mìsto. Odnìkud pøece musí získávat suroviny, ze kterého dìlají drogy a léky, e jo? Vypadá to, e èást nebo moná všechno berou z Vault City.}
{341}{}{Kde je New Reno?}
{342}{}{Dobøe, díky.}
{350}{larad19}{Nevím to pøesnì. Myslím, e nìkde na jihu. Nikdy jsem tam nebyla, jenom jsem si všimla, jak se tu jednou za èas zastaví karavany pro zásoby... jednou za dlouhou dobu.}
{351}{}{Aha, dobøe. Díky.}
{360}{larad20}{Nechceš si vydìlat další rychlı prachy? $50. Snadnı prachy.}
{361}{}{Jasnì.}
{362}{}{Dobøe, ale rychle.}
{370}{larad21}{Potøebuju od Metzgera zjistit, jestli mu nebude vadit, kdy si s Tylerem vyøídím nìjakou starší záleitost. On u bude vìdìt o co jde.}
{371}{}{Proè se mám jít zeptat já?}
{372}{}{Mùu to zkusit.}
{373}{}{Dobøe.}
{380}{larad22}{Protoe nechci, aby Tyler vidìl nìkoho z mıch lidí pøicházet nebo vycházet od Metzgera. Nechci, aby mìl nìjakı podezøení.}
{381}{larad23}{Ty to nechápeš? Jestli mì Tyler uvidí jak se najednou bavím s Metzgerem, mùe mu dojít, e tu nìco smrdí.}
{382}{}{Uvidíme.}
{383}{}{Dobøe.}
{390}{larad24}{Tak co, u víš, co tam je?}
{391}{}{Èisté chemické slouèeniny ve velkıch bednách.}
{392}{}{Nìjaké chemikálie ve velkıch kontejnerech.}
{393}{}{Ještì ne.}
{400}{larad25}{Tak co? Domluveno? Co øíkal?}
{401}{}{Souhlasí. Jestli vyhraješ, mùeš mít jejich práci stejnì jako pøedtím.}
{402}{}{Na.}
{410}{larad26}{Skvìlı. V to jsem doufala. Slyšela jsem, e si na nìj v poslední dobì stìoval. Tady jsou prachy.}
{411}{}{Pøedpokládám, e máš ještì nìco.}
{412}{}{Dík. Mìj se.}
{420}{larad27}{Mám pro tebe ještì jednu práci. Nejsem si jistá, jak to udìláš, ale kdy u se ti podaøilo dostat dovnitø, tak ti asi vìøí.}
{421}{}{Bez plíení to nešlo.}
{422}{}{Co to je?}
{430}{larad28}{Jsem si jistá, e nìco vymyslíš.}
{431}{}{Dobøe, o co jde?}
{440}{}{V takové pøesile na nì nemáme. Mají víc penìz a je jich o trochu víc. Kdyby se ti podaøilo najít nìjakou slabinu, pomohlo by nám to získat pøevahu. Nebo nìco, èeho by se dalo vyuít...}
{441}{}{Co? Najít slabinu? A jak to mám asi udìlat?}
{442}{}{Kolik za to?}
{443}{}{Povauj to za hotové.}
{450}{larad30}{Dáme ti $150. Nemùeme jít dost blízko na to, abysme si to sami zjistili.}
{451}{}{Kdy bude pøíleitost, tak to zkusím.}
{452}{}{Dobøe.}
{460}{larad31}{Nevím. Proto tì ádám o pomoc.}
{461}{}{Zkusím to.}
{462}{}{Tohle nemá cenu.}
{470}{larad32}{Tak co? Jak to vypadá?}
{471}{}{Mám to. Dnes v noci budou mít mejdan.}
{472}{}{Ještì nevím. Dám ti vìdìt.}
{473}{}{Gra.}
{474}{}{Na.}
{480}{}{Vıbornì! Urèitì tam nechaj jenom základní ostrahu. Proti nim máme slušnou šanci. A a udìláme kostel, sejmeme ty ostatní na mejdanu.}
{481}{}{A co moje peníze?}
{490}{}{Ještì ne. Jestli chceš peníze, musíš jít s náma. Nemusíš bojovat, jen se chceme ujistit, e to není past. Dáme ti celkem $300.}
{491}{larad35}{Jdeme na to?}
{492}{}{Dobøe, tak do toho.}
{493}{}{Dej mi chvilku, musím se pøipravit.}
{494}{}{V ádném pøípadì. Nech si ty peníze!}
{500}{larad36}{Fajn, ale musíme se do toho pustit co nejdøív, tak a ti to netrvá moc dlouho. Tohle je naše šance.}
{501}{}{Dobøe.}
{510}{larad37}{Nemusíš bojovat. Jsou to snadnı prachy.}
{511}{larad38}{Tak co, rozmyslel sis to?}
{512}{}{Tak jdeme.}
{513}{}{Dobøe, hned se vrátím.}
{514}{}{Ne.}
{515}{}{Uk}
{520}{larad50}{Kvùli tobì jsme prošvihli naši šanci.}
{521}{larad51}{Zbabìlèe!}
{522}{larad52}{Nic nedostaneš.}
{523}{larad53}{Stejnì to byla urèitì past.}
{524}{larad54}{Promiò, není na tebe spoleh.}
{525}{larad55}{Nemùu ti vìøit.}
{530}{larad56}{Dokázali jsme to!}
{531}{larad57}{Díky za pomoc.}
{532}{larad58}{Obzvláš díky tobì!}
{533}{larad59}{Koneènì jsem Tylerovi oplatila, co udìlal mımu bráchovi.}
{534}{larad60}{Ještì jednou díky.}
{540}{larad61}{Teï, kdy je Metzger mrtvej, nevím, co bude dál.}
{541}{larad62}{Moná bysme to mìli zabalit.}
{542}{larad63}{U se ti doneslo, e je Metzger mrtvej? Nevím, co budu dìlat.}
{543}{larad64}{Co bude s Denem? Moná se nìco zlepší.}
{544}{larad65}{Vlastnì by se to teï mìlo zlepšit.}
{550}{larad66}{Bastarde!}
{551}{larad67}{Dìvko!}
{560}{larad39}{Díky. Tady máš prachy a $100 navrch.}
{570}{larad40}{Tyler a jeho stráe jsou díky tobì mrtví? A jak se máme pøedvést Metzgerovi? Teï u si nás nikdy nenajme. To byla naše jediná šance.}
{571}{larad41}{Nemáme ádnou práci. Nìkdo sejmul Metzgerovy stráe a on s námi teï nemluví. Myslí si, e jsme to byli my. Ach jo.}
{572}{}{Omlouvám se.}
{573}{}{To je blbé.}
{574}{}{To jsem byl já a hádej, kdo je na øadì teï.}
{575}{}{Och. Dobøe, nashle.}
{576}{}{Uhr?}
{577}{}{Eh.}
{590}{larad42}{Øekla jsem ti, e pùjdeme spolu. A protoe to tam nikdo nehlídal, tak to nìkdo vyloupil a Metzger se teï fakt nasral.}
{591}{larad43}{Øekla jsem ti najdi slabinu, ne sejmi je! A protoe to tam nikdo nehlídal, tak to nìkdo vyloupil a Metzger se teï fakt nasral.}
{592}{larad44}{Do hajzlu! Øekla jsem ti promluv s Metzgerem a ne sejmi je! A protoe to tam nikdo nehlídal, tak to nìkdo vyloupil a Metzger se teï fakt nasral.}
{593}{larad45}{Do hajzlu! Øekla jsem bez bitky! A protoe to tam nikdo nehlídal, tak to nìkdo vyloupil a Metzger se teï fakt nasral.}
{594}{}{Aha, no, u musím jít.}
{595}{}{To je ale smùla.}
{596}{}{Teï jsi na øadì ty, dìvko.}
{597}{}{Hmph!}
{598}{}{Ty další.}
{610}{larad68}{Ty fakt umíš vìci poøádnì podìlat, víš to?}
{611}{larad69}{U tvoji pomoc nepotøebujeme.}
{612}{larad70}{Bì otravovat jinam.}
{613}{larad71}{Snad proti nám Metzger nic nepodnikne.}
{614}{larad72}{Je mi líto, ale nemùu ti pomoct.}
{615}{larad73}{Nemùu mluvit. Snaím se vymyslet co teï.}
{616}{larad74}{Doufám, e si Metzger nemyslí, e za to mùeme my.}
{617}{larad75}{Co teï budeme dìlat?}
{618}{larad76}{Radši bysme mìli vypadnout pro pøípad, e by si Metzger myslel, e jsme mu sejmuli stráe.}
{619}{larad77}{Jaké je to v New Renu? Moná tam zamíøíme... nebo na sever.}
{650}{larad78}{Dobøe! Jde se na to! Všichni za mnou!}
{700}{}{Paráda, postarali jsme se o tìch pár stráí v kostele, ale Tyler a jeho kumpáni jsou ještì poøád v Obytnı ètvrti. Teï u by mohli bıt poøádnì oralí, take bysme je mohli zastihnout nepøipravenı. Mùeme to dokonèit?}
{701}{}{Nejdøív se vyléèím. Øeknu ti, a budu moct.}
{702}{}{Pojïme.}
{710}{larad47}{Mùeme jít vyøídit Tylera a jeho partu?}
{720}{larad48}{Dobøe, ale nechoï moc daleko. Potøebujeme to dokonèit dnes v noci, nebo to udìláme bez tebe.}
{721}{}{Za chvíli se vrátím.}
{722}{}{Pojïme.}
{730}{larad49}{Dokázali jsme to. Nemùu tomu uvìøit! Jdeme zpátky ke kostelu pøevzít vedení. Pøijï si tam pro svou odmìnu.}
