{100}{}{Vidíš naštvanì vypadajícího mue.}
{101}{}{Vidíš Metzgera, šéfa otrokáøù.}
{150}{}{Metzger, hlava Cechu otrokáøù.}
{200}{metzg1}{Za tohle zaplatíš.}
{210}{metzg2}{Co tu kurva chceš? Tohle je Cech otrokáøù a ne nìjakej úkryt pro posranı feáky.}
{211}{metzg3}{Co tu sakra chceš, ty hnusná dìvko? Tohle je Cech otrokáøù a ne nìjakej posranej bordel.}
{212}{metzg4}{Co tu sakra chceš, dìvko? Tohle je Cech otrokáøù a ne nìjakej posranej bordel.}
{213}{metzg5}{Zaèínáš mì srát. Co teï sakra chceš?}
{214}{metzg6}{Krucinál, co zas?}
{215}{metzg7}{Coe?}
{216}{metzg8}{No, radši to vyøiï rychle.}
{217}{metzg9}{Jdeš sem pracovat za pár posranejch drobákù?}
{218}{metzg10}{Zaèínám si na tu tvoji hnusnou drku zvykat. Take... jseš tu z nìjakıho dùvodu nebo co?}
{219}{metzg11}{Vypadám snad jako tvùj posranej fotr nebo co? Doufám, e kurva ne. Tak to vybal, co chceš?}
{220}{metzg12}{Ale podívejme, kdo je tady. Myslíš, e jseš nìco extra nebo co? Mluv, nebo kurva vypadni.}
{221}{metzg13}{Co zase chceš, otrokáøi?}
{222}{metzg14}{To tam budeš furt stát, nebo taky nìco øekneš?}
{223}{metzg15}{Mluv. Na tyhle kraviny nemám celej den.}
{230}{metzg16}{No a 'kdo' to jako bude? Doufám, e neèekáš, e tuhle osobu ještì nìkdy uvidíš...}
{231}{metzg17}{Nemáš nikoho, o koho bych mìl zájem. Zajímají mì jenom lidi... ti normální.}
{232}{metzg18}{Ty zasranej magore, co si myslíš, e jsem? Posranej obchod nebo co? Jestli seeneš otroka na prodej, dej mi vìdìt. Jestli chceš prodat nìco jinıho, tak jdi do posranıho obchodu.}
{233}{}{Mirie}
{234}{}{Davina}
{235}{}{Vic}
{236}{}{Myron}
{237}{}{Cassidy}
{238}{}{Sulik}
{239}{}{Mùu se tì místo toho ještì na nìco zeptat?}
{240}{}{U nemám zájem. Nashle.}
{241}{}{Dex}
{242}{}{Kocour Jules}
{243}{}{Kitsune}
{245}{metzg19}{Pokraèuj.}
{246}{metzg20}{Jo?}
{247}{metzg21}{Nejsem tvùj zasranej sluha, tak s tím pohni.}
{248}{metzg22}{Tak co je? Nemám celej den.}
{249}{metzg23}{Mluvte.}
{250}{metzg24}{Moná.}
{255}{}{Mám nìkoho na prodej.}
{256}{}{Co se tıèe Vica...}
{257}{}{Hledám obchodníka.}
{258}{}{Lara se ptá, jestli si to mùe vyøídit s Tylerem.}
{259}{}{Mùu se pøidat k Cechu?}
{260}{}{Co mi mùeš øíct o Cechu?}
{261}{}{Chci jít na hon otrokù.}
{262}{}{Ale nic. Nashle.}
{263}{}{ chtít zabíjet.}
{264}{}{Na.}
{265}{}{Díval jsem se na ty otroky vzadu, ale víš, mám velmi, ehm...*konkrétní* poadavky, a ádnı z nich není úplnì to, co hledám. To jsou všichni otroci, které máš na prodej?}
{270}{metzg25}{Myslíš, e to zvládneš? Neberu jen tak nìkoho... k èertu s tím. Jestli nìco zkurvíš, tak tì prodám. Musíš si nechat udìlat tetování na èelo, aby kadej poznal, e jseš otrokáø. Je to napoøád, take si to poøádnì rozmysli.}
{271}{metzg26}{Take naše nìná, malá kvìtinka se vrátila... zmìnila jsi názor? Take si nakonec to tetování necháš udìlat?}
{272}{metzg27}{Jo, to mùeš... pøi honech stejnì moc mozek potøebovat nebudeš, ale jestli nìco zkurvíš, tak tì prostì prodám. Musíš si nechat udìlat tetování na èelo, aby kadej poznal, e jseš otrokáø.}
{273}{}{Pojïme na to.}
{274}{}{Musím si to rozmyslet. Ještì se vrátím.}
{275}{}{Asi ne. Nashle.}
{276}{}{Héé! [Kıvnout]}
{277}{}{Ne ne ne ne ne!}
{285}{metzg28}{Co myslíš, kurva? Tohle je Cech otrokáøù. Kupujeme a prodáváme otroky.}
{286}{}{Odkud berete otroky?}
{287}{}{Chci se k vám pøidat.}
{288}{}{Další otázku, prosím.}
{289}{}{Aha, dobøe. Nashle.}
{300}{metzg29}{No, tak rùznì. Vìtšinou bereme domorodce a tuláky, kdy na nì poøádáme hony.}
{301}{}{To mùe bıt sranda. Jak se k nìèemu takovému dostanu?}
{302}{}{Mám další otázku.}
{303}{}{Aha, dobøe. Nashle.}
{310}{metzg30}{No vida, a ani to moc nebolelo. Jsem na tebe fakt pyšnej... vlastnì ti to tetování docela sekne. Pak na mì zaøvi, a budeš chtít vyrazit na hon otrokù.}
{311}{}{Dík. Mìj se.}
{312}{}{Jsem pøipravenı právì teï.}
{313}{}{Já ZABÍJET TEÏ!}
{314}{}{Dobøe.}
{320}{metzg31}{Dva z mıch lidí tì zavedou poblí tvejm cílùm. Tvoje odmìna je zaloena na tom, kolik otrokù pøivedeš zpátky, ale dávej na nì pozor. Jestli nìkdo zemøe, tak ti strhnu pìknej balík.}
{321}{metzg32}{Sakra, u jsme je všechny pochytali. Musíme poèkat, a se zase nìjakı kmeny pøestìhujou zpátky do oblasti. Moná bysme je mìli zaèít chovat.}
{322}{metzg33}{Promiò, ale prostì to s tebou nejde. Tohle je obchod a ty máš moc ztrát. Potøebuju prachy vydìlávat, ne o nì pøicházet.}
{323}{metzg34}{Dobøe. Jsou pøipravenı.}
{324}{metzg35}{Fajn, u mùeš odejít.}
{325}{metzg36}{Tak jdi na to.}
{326}{metzg37}{Dobøe. A skonèíš, tak se u mì zastav.}
{327}{}{Dobøe.}
{328}{}{Eh.}
{340}{metzg38}{Prostì zabij všechny ty agresivní. Jestli zaútoèí, zab je. Nechci s nima u nic mít, je s tím kurva moc problémù. A skonèíš, ostatní otrokáøi seenou zbytek dohromady a oznaèkujou je.}
{341}{}{Dobøe.}
{342}{}{Aha.}
{350}{metzg39}{A zaènou otroky znaèkovat, tak se mùeš klidnì vrátit. Je na to potøeba speciální vıcvik, tak se do toho radši nemontuj. Mùeš dìlat cokoliv budeš chtít, jenom nesmíš poškodit zboí.}
{351}{}{Tak dobøe.}
{352}{}{Aha.}
{360}{metzg40}{Jo, jasnì. Je docela hezká. Dám ti za ni $}
{361}{metzg41}{Je v pohodì. Moná bych ho od tebe vzal za, hmm, øeknìme za $}
{362}{metzg42}{Ty zkurvenej idiote. Proè si kurva myslíš, e chci toho debila zpátky? Dy mu trvalo vìènost, ne spravil to blbı rádio! Rádio! U se ho nezbavíš. Nechci, aby tu rozbil ještì nìco jinıho.}
{363}{metzg43}{No já nevím, je nìjakej vychrtlej... je aspoò inteligentní? To by mohlo mít cenu. Dám ti za nìj $}
{364}{metzg44}{Tenhle vypadá, e bude moná dobøe bojovat. Hmm... $}
{365}{metzg45}{Další primitiv. Taková zrùda. No ale vypadá silnì a ten pohled by mohl vynıst nìco navíc. $}
{366}{}{A co nìkdo jinej?}
{367}{}{No, chci se ještì na nìco zeptat.}
{368}{}{Dobøe.}
{369}{}{Fajn.}
{370}{}{Dobøe.}
{371}{}{Nemá ádnou cenu.}
{372}{}{Ne.}
{380}{metzg46}{Tak dobøe, chlapi, strète ho do ohrady.}
{381}{metzg47}{Tak dobøe, chlapi, strète ji do ohrady.}
{382}{}{Jasnì, šéfe.}
{390}{metzg48}{No tak kurva neplıtvej mım èasem. Jestli nìkdy budeš mít nìkoho, koho budeš chtít prodat, tak se za mnou stav.}
{391}{}{Mám pro tebe ještì další otázku.}
{392}{}{Dobøe. Ahoj.}
{400}{metzg49}{Co to do ní krucinál najednou vjelo? U jsem tı krávì jednu šanci dal. Netušil jsem, e bude mít na tohle koule.}
{401}{}{O èem to mluvíš?}
{402}{}{Take je to v poøádku?}
{410}{metzg50}{Ale no tak, nedìlej ze sebe blbce. Vím pøesnì, co chce udìlat. U jsem jí dal šanci a nemìla na to, ale jestli si myslí, e na to teï má...}
{411}{}{Take je to v poøádku?}
{420}{metzg51}{No, øekl jsem, e ta nabídka stále platí. Jestli si myslí, e mu koneènì nakope prdel a postará se o moje posranı vìci líp...}
{421}{}{Ano?}
{422}{}{Take to znamená ano?}
{430}{metzg52}{Podívej, je mi u prdele, kdo to hlídá. Dokud bude moje zboí v bezpeèí, je mi to jedno.}
{431}{}{Ještì otázku, prosím.}
{432}{}{Dobøe, díky.}
{440}{metzg53}{Na co se mì to kurva ptáš? Vypadám snad jako nìjakej posranej... jo poèkat. Ty asi hledáš Vica, e jo?}
{441}{metzg54}{To je ten, co se 'specializuje' na Vault technologii, teda aspoò to tvrdí. On je teï mùj majetek. Nikam nepùjde.}
{442}{}{Co je s ním?}
{443}{}{Jo, to je on.}
{444}{}{Mùu ho vidìt?}
{445}{}{Proè ho tady dríš?}
{446}{}{Dobøe, díky. Nashle.}
{455}{metzg55}{Ten malej sráè... mi prodal rádio a øíkal, e na nìm chytne nìjakı pøenosy. Ale nechytl. Chytil jsem ho, jak se snaí proklouznout z mìsta, ne na to pøijdu. Hloupá chyba. Mì nikdo neojebe. Má štìstí, e je ještì ivej.}
{456}{metzg56}{Jak jsem øíkal. Musí napøed nìco spravit. Potom uvidíme.}
{457}{metzg57}{No, koneènì to rádio zprovoznil, ale to neznamená, e ho nechám jít tak lehce.}
{458}{metzg58}{Stejnì se mì pokusil ochcat.}
{459}{}{Mùu ho vidìt?}
{460}{}{O jakıch pøenosech to mluvíš?}
{461}{}{Dobøe, díky.}
{462}{}{Nevyøešily by to nìjaké peníze?}
{463}{}{O jakıch pøenosech jsi to pøedtím mluvil?}
{475}{metzg59}{Proè? No jo kurva, je mi to fuk. Hlavnì ho nezdruj od práce na tom podìlanım rádiu, mìl by ho spravit co nejdøív. U mì nebaví krmit tu jeho línou prdel.}
{476}{}{Proè ho tady dríš?}
{477}{}{Díky.}
{485}{metzg60}{Enkláva a New... hele, co je ti sakra po tom? Jde o obchod. Potøebuju si bejt jistej, e se mnou nikdo nechce vyjebat. Víc vìdìt nepotøebuješ.}
{486}{metzg61}{Hleï si svıho.}
{487}{}{Dobøe.}
{495}{metzg62}{Jasnì, ale bude tì stát $}
{496}{metzg63}{$}
{497}{}{Nemùeme se domluvit na nìjaké slevì?}
{498}{}{Dobøe. Tady.}
{499}{}{Mùu se tì nejdøív na nìco zeptat?}
{500}{}{Promiò, to si zatím nemùu dovolit.}
{510}{metzg64}{Fajn, je tvùj, ale odtáhni odsud tu jeho prdel, ne si to rozmyslím a pošlu mu kulku do tı jeho zkurvenı hlavy.}
{511}{}{Mùu se tì nejdøív na nìco zeptat?}
{512}{}{Díky.}
{520}{metzg65}{Ale ano, to víš, e se mùeme domluvit na slevì... polovinu ti slevím, kdy to s tebou bude stát za to...}
{521}{metzg66}{Radši mì pøestaò drádit, holka. Nejsem moc trpìlivej.}
{522}{}{Jenom jestli na mì budeš hodnı.}
{523}{}{Jasnì, proè ne.}
{524}{}{Moná pozdìji.}
{530}{metzg67}{Jo, vìø tomu.}
{531}{}{Dobøe.}
{540}{metzg68}{Tady je $}
{541}{metzg69}{Tady je $}
{542}{metzg70}{Dobrá práce. Tady je $}
{543}{metzg71}{Tady máš prachy, }
{544}{metzg72}{$}
{545}{metzg73}{Bude to $}
{546}{metzg74}{Nebylo to tak zlı, e ne? Pøíštì ádnı chyby. Tady je $}
{547}{metzg75}{$}
{548}{metzg76}{No tak! $}
{549}{metzg77}{Pamatuj si, dávej bacha a zabíjej jenom agresivní otroky. Tady je $}
{550}{metzg78}{Jenom $}
{551}{metzg79}{Chceš vydìlávat prachy nebo ne? Sereš mì. Dy to kurva není tak tìkı. Teï si vem svejch $}
{552}{metzg80}{Co to sakra bylo? Tentokrát nedostaneš ani hovno. Jsme tu kvùli vydìlávání penìz a ne abysme dìlali hovno.}
{553}{}{Polepším se.}
{554}{}{Díky za nic.}
{555}{}{Díky.}
{556}{}{Eh.}
{570}{metzg81}{Ty zatracená krávo, nebylo to pro tebe poprvı? Nevìøím, e to pro tebe nebylo poprvı.}
{571}{metzg82}{Holka zatracená, nebylo to pro tebe poprvı?}
{572}{metzg83}{Dost dobrı.}
{573}{metzg84}{Hodnì dobrı, moná bysme si to mohli nìkdy zopakovat.}
{574}{metzg85}{Sakra! To byly... dost dobøe utracenı prachy.}
{575}{metzg86}{Sakra! Jseš ta nejlepší kost, jakou jsem kdy mìl... a e jich bylo.}
{600}{metzg87}{TY BLBEJ SRÁÈI! Jak ses opováil nechat tam venku svoje kamarády otrokáøe? (Plivne ti do oblièeje.) ZABTE HO!}
{601}{}{Ale já...}
{602}{}{Fajn, jdeme na to.}
{620}{metzg88}{No, jsem rád, e ses vrátil.}
{621}{}{Jo, byl to drsnej hon.}
{622}{}{Díky. Trochu se to tam zvrtlo.}
{623}{}{Agra Moo ne!}
{630}{metzg89}{Aha, ty chceš peníze? Ty chceš vıplatu?}
{631}{}{Jo.}
{632}{}{Eh.}
{640}{metzg90}{Samozøejmì bych ti s tím MOC RÁD pomohl... ale je tu takovı drobnı problém... nìco ohlednì zaútoèení na jednoho z mıch muù.}
{641}{}{Promiò! Já to tak nemys... vlastnì... eh?}
{642}{}{Eh, och.}
{650}{metzg91}{No, neboj se. Ze srdce rád ti to vyplatím, vlastnì oplatím. Chlapi, vıplata.}
{651}{metzg92}{No, neboj se. Ze srdce rád ti to vyplatím, vlastnì oplatím. Chlapi, sejmìte tu dìvku.}
{652}{}{A sakra.}
{653}{}{Garaka!}
{654}{}{Eh... tank?}
{670}{metzg93}{Jo, jsem si jistej. Tenhle druh práce není nic jednoduchıho. Vyaduje dùvìru a loajalitu. Dáváme bacha jeden na druhıho. To jsou dobrı zásady, nemyslíš?}
{671}{}{Asi jo.}
{672}{}{Eh, co se dìje?}
{673}{}{Urèitì.}
{680}{metzg94}{Asi jo? Nevìdìl jsem, e jseš tak inteligentní. Fakt jseš pìknì blbej sráè. (Metzger na tebe chvíli zírá, poté se podívá na stráe a mávne rukou tvojím smìrem.)}
{681}{}{Akce?}
{682}{}{Coe?}
{690}{metzg95}{Hm, take nejseš zase takovej blbec, jak pøedstíráš. No, to je škoda. Víš, mám takovı malı dilema. Nìkdo mìl nervy na to, aby napadl mı mue.}
{691}{}{Opravdu?}
{692}{}{To byla nehoda!}
{700}{metzg96}{Opravdu? Jsem rád, e souhlasíš. A co udìláš, kdy nìkdo ztratí naši dùvìru?}
{701}{}{Eh, dám jim varování?}
{702}{}{Tohle. Ukáu ti to. [Zaútoèit]}
{703}{}{Nechám je za to zaplatit.}
{710}{metzg97}{Myslíš? Upøímnì? Já nevím. Pøemıšlel jsem o nìèem trochu... trvalejším. (Metzger se zlovìstnì zašklebí, podívá se na stráe a kıvne.)}
{711}{}{Coe?}
{712}{}{A sakra...}
{720}{metzg98}{Jsem rád, e se shodneme. (Metzger se podívá na stráe.) Chlapi, vıplata.}
{721}{}{Eh...}
{730}{metzg99}{Ano. Opravdu škoda. Ta osoba to prostì nechápe, ale oni jo. (Vidíš, jak Metzger provede rukou drobné gesto na své mue.) Èas se pobavit.}
{731}{}{Fakt jo?}
{732}{}{Oou.}
{740}{metzg100}{Ano, obávám se, e nehody se tu stávají docela èasto. Vlastnì se bojím, e tu bude brzo další. (Metzger se spokojenì usmìje a kıvne smìrem ke svım muùm.)}
{741}{}{Tak pojïte!}
{742}{}{Z tohohle se nedostanu nebo jo?}
{750}{metzg101}{Tohle bude zábava, vìø mi.}
{751}{}{Jdi do prdele.}
{752}{}{Eh, dobøe.}
{800}{}{Podaøilo se ti zabít vùdce Cechu otrokáøù.}
{900}{metzg102}{Tohle je všechno, co tu mám. Jestli se ti nelíbí moje zboí, tak se mi kurva kliï z oèí a pøestaò marnit mùj volnej èas.}
{901}{}{Ehm, promiò. Mùu se ještì na nìco zeptat?}
{902}{}{Dobøe. Myslím, e radìji pùjdu.}
{903}{}{Vlastnì myslím, e zlikviduju *tebe* i celej ten tvùj zkurvenej Cech.}
{910}{metzg103}{To je všechno, co tu mám, ty vybíravej sráèi, ale neustále mi pøichází novı zboí z ostatních otrokáøskejch kempù. Moná, kdy pøijdeš pozdìji, budu mít nìco, co by se ti mohlo líbit, ale vìtšinou jsou to nevychovaní divoši, co vypadaj kurva všichni stejnì, take pokud o to nestojíš, tak budeš mít nejspíš kurva smùlu.}
{911}{}{Poslyš, moná to bude trochu neobvyklı poadavek, ale chci vidìt kadé nové zboí jako první. Je nìjakı zpùsob, jak se podívat na zboí v ostatních kempech? Samozøejmì zaplatím nìco navíc.}
{912}{}{Dobøe, potom se na nì ještì podívám.}
{913}{metzg104}{Dobøe, ale pøíštì mi udìlej laskavost a neplıtvej mım èasem, pokud nebudeš chtít vyøídit nìjakı obchodní záleitosti.}
{914}{metzg105}{Nìco navíc, jo? Ta slova se mi líbí. Obvykle tu dìláme obchody zde, ale snad by se dala udìlat vıjimka, pokud to myslíš vánì. Øeknu ti, jak se tam dostaneš, ale radši si to nech pro sebe. Pøísahám, e jestli se z tebe vyklube špión tìch zasranıch Rangerù, tak pøísahám, e si tì najdu a stáhnu tì zaiva z kùe. (Posloucháš jeho pokyny a zaznamenáváš si polohu Tábora Otrokáøù do svého Pip-Boye).}
{915}{}{Mám to. Chci se ještì na nìco zeptat.}
{916}{}{Díky. Musím odejít. Nashle.}
{1360}{}{. Co ty na to?}
{1361}{}{?}
{1363}{}{.}
{1364}{}{.}
{1365}{}{?}
{1496}{}{.}
{1540}{}{. Kurevsky dobrá prácièka.}
{1541}{}{. To bylo fakt dobrı. Jen tak dál.}
{1542}{}{.}
{1543}{}{, $}
{1544}{}{ není suma, za kterou by se mìl èlovìk stydìt, ale víc si nevydìláš.}
{1545}{}{ pro tentokrát. Dost dobrá práce.}
{1546}{}{.}
{1547}{}{? To nebylo špatnı.}
{1548}{}{? Šlo by to i líp.}
{1549}{}{.}
{1550}{}{! To je kurva slabı! Pøidej, nebo ti nakopu prdel.}
{1551}{}{ a vypadni.}
{2540}{}{.}
{2543}{}{.}
{15401}{}{. Kurevsky dobrá prácièka, }
