{100}{}{Vidíš velmi atraktivní mladou dámu.}
{101}{}{Vidíš Rebeccu.}
{150}{}{Vidíš Rebeccu, majitelku Beckyina Kasíno Baru.}
{200}{rbcca1}{Vítejte, já jsem Rebecca. Mùu vám nìco nalít? Jistì máte ízeò po takovém vıletì pustinou.}
{201}{rbcca2}{Zdravím! Chcete drink, nebo mì chcete jen pozdravit?}
{202}{rbcca3}{Ahoj! Jsem ráda, e jste zpátky. Máte nìjaké otázky, nebo tu jste na sklenku vynikající whiskey?}
{203}{rbcca4}{Jsem opravdu ráda, e vás vidím. Jak to jde? Potøebujete nìco?}
{204}{rbcca5}{Doufám, e se mému oblíbenému hostu dobøe daøí! Co pro vás dnes mùeme udìlat?}
{205}{rbcca6}{Dobrı den!}
{206}{rbcca7}{Pokadé vás vdy ráda vidím.}
{207}{rbcca8}{Ahoj! Dáte si drink? Nejlepší whiskey široko daleko!}
{208}{rbcca9}{Vítejte!}
{209}{rbcca10}{To jste vy! Myslela jsem si to. Co takhle drink, drahoušku?}
{210}{rbcca11}{Jste zpìt kvùli Rebeèinì talentu bavit hosty, nebo kvùli svìtoznámé whiskey?}
{211}{rbcca12}{Vítejte zpìt v Rebeèinì Baru a Kasínu. Jak vám mùu pomoct?}
{212}{rbcca13}{Dobrı den, jak vám mùeme pomoct?}
{213}{rbcca14}{Dáte si dnes nìco? Co takhle drink?}
{214}{rbcca15}{Máte chu na drink nebo nìco jiného?}
{215}{rbcca16}{Èím poslouím?}
{216}{rbcca17}{Zdravím. Co to bude?}
{217}{rbcca18}{Potøebujete nìco?}
{218}{rbcca19}{Ráda vás zase vidím. Jak vám dnes mùu pomoct?}
{219}{rbcca20}{Coe?}
{220}{rbcca21}{Ano?}
{221}{rbcca22}{A teï co?}
{222}{rbcca23}{Prosím struènì, dnes mám nároènı den. Co potøebujete?}
{223}{rbcca24}{Co pro vás mùu udìlat? Mám opravdu hodnì práce.}
{224}{rbcca25}{Jste tu kvùli drinku? Stoly jsou támhle.}
{225}{rbcca26}{Nemám dobrou náladu. Co to bude?}
{226}{rbcca27}{U jste zpátky? Take si pøeci jen dáte drink?}
{240}{rbcca28}{Jistì, fešáku.}
{241}{rbcca29}{Co potøebujete vìdìt?}
{242}{rbcca30}{S radostí.}
{243}{rbcca31}{Ale samozøejmì.}
{244}{rbcca32}{Jasnì.}
{245}{rbcca33}{Nevadí.}
{246}{rbcca34}{Pomùu, pokud to bude v mıch silách.}
{247}{rbcca35}{Samozøejmì, nebuïte smìšnı.}
{248}{rbcca36}{Cokoliv. O co se jednalo?}
{249}{rbcca37}{Udìlám vše pro to, abych vám pomohla. Co potøebujete vìdìt?}
{250}{rbcca38}{Ptej se.}
{251}{rbcca39}{Kdy na tom trváte.}
{252}{rbcca40}{U to tak vypadá.}
{253}{rbcca41}{Zkrate to. Mám ještì nìco na práci.}
{254}{rbcca42}{No, dobøe. O co jde?}
{255}{rbcca43}{Domnívám se, e ano.}
{256}{rbcca44}{Coe?}
{257}{rbcca45}{Ne, promiòte.}
{258}{rbcca46}{Teï ne.}
{270}{}{Potøebuju drink.}
{271}{}{Hledám obchodníka, kterı prodává vybavení z Vaultù.}
{272}{}{Hledám obchodníka jménem Vic.}
{273}{}{Nemáte nìjakou práci?}
{274}{}{Co se tıèe té práce...}
{275}{}{Nemáte pro mì nìjakou další práci?}
{276}{}{Nic. Nashle.}
{277}{}{Whikí mòam òam.}
{278}{}{Maky maky?}
{279}{}{Iho shasha.}
{280}{}{Ee, pa.}
{281}{}{Maky maky?}
{300}{rbcca47}{Whiskey je moje specialita. V rodinì Dyerù je to témìø tradice. Úètuji velmi nízkou cenu, pouze $5.}
{301}{rbcca48}{Drink stojí stále $5 a Dyerova rodina dìlá zatracenì nejlepší drinky na celém svìtì.}
{302}{rbcca49}{Jste v poøádku? Nechcete whiskey? Stojí jen $5.}
{303}{}{Dám si drink.}
{304}{}{Proè jsou tvoje drinky tak levné?}
{305}{}{Dyer?}
{306}{}{Mùu se na nìco zeptat?}
{307}{}{Èau.}
{308}{}{Whikí.}
{309}{}{Urka.}
{320}{rbcca50}{Och, to je rodinné jméno. Jméno Dyer je v barovém byznysu u léta... samozøejmì ještì z pøedváleèné doby.}
{321}{rbcca51}{Jak jsem øekla, je to mé rodné pøíjmení. Kdysi byly Dyerovy hospody, salóny a podobnì, po celém svìtì.}
{322}{}{Dám si drink.}
{323}{}{Mùu se ještì na nìco zeptat?}
{324}{}{Èau.}
{330}{rbcca52}{No, jeliko jste tak dobrı zákazník, svìøím se vám s malım tajemstvím. Je to opravdu jednoduché. Mám destilátor a pøítel ze sousedního mìsta mì nauèil, jak pálit whiskey. Take, dáte si ještì jednu?}
{331}{rbcca53}{Nezlobte se, ale to je obchodní tajemství a navíc vás a tak dobøe neznám. Nechci, aby se to Frankie dozvìdìl, u tak dìlá dost problémù. Chcete ještì jednu? Je opravdu vynikající.}
{332}{}{Jasnì, dám si ještì jednu.}
{333}{}{Mùu se ještì na nìco zeptat?}
{334}{}{Dobøe, díky.}
{340}{rbcca54}{Tady je. Díky moc.}
{341}{}{Díky. Mùu se na nìco zeptat?}
{342}{}{Dobøe, díky.}
{343}{}{Dík.}
{344}{}{Ptát?}
{350}{rbcca55}{Je mi líto, ale nemám.}
{351}{rbcca56}{Fred mi dluí $200. Jestli od nìj ty peníze nìjak vyberete, odmìním se vám.}
{352}{rbcca57}{Stále je tu ten dluh, kterı potøebuji vybrat.}
{353}{rbcca58}{Derek si pøed nìjakou dobou pùjèil jednu moji knihu. Zaplatím vám $80, kdy mi ji vrátíte.}
{354}{rbcca59}{Stále postrádám tu svoji knihu.}
{355}{}{V èem je háèek?}
{356}{}{Povídej dál.}
{357}{}{Mùu se tì na nìco zeptat?}
{358}{}{Èau.}
{370}{rbcca60}{Háèek? No, kdo nezná Freda, nepochopí. U pìknì dlouho mi dluí peníze. Odepsala bych to jako ztrátu, ale pokud to z nìho dostanete, budu pøekvapená... a vdìèná. Vím urèitì, e je nìkde tady ve mìstì.}
{371}{rbcca61}{Ta kniha se jmenuje "Levandule". Derek by se mìl vyskytovat nìkde u Mámy ve vıchodní èásti.}
{372}{}{Uvidím, co se dá dìlat.}
{373}{}{To zní jednoduše.}
{374}{}{Mám ji u sebe.}
{375}{}{Ještì se vrátím.}
{385}{rbcca62}{Podaøilo se vám to z nìj vymámit? Divila bych se kdyby ano.}
{386}{rbcca63}{Podaøilo se vám získat moji knihu? Doufám, e ji Derek neponièil.}
{387}{}{Ano, podaøilo.}
{388}{}{Je mi líto. Je mrtvı.}
{389}{}{Bohuel ne a Derek je navíc mrtvı.}
{390}{}{Je mi líto, ale je mrtvı.}
{391}{}{Ano. Tady máte.}
{392}{}{Ne, promiòte.}
{400}{rbcca64}{Nemùu tomu uvìøit. Jak se vám to podaøilo? No, to je jedno. Jsem jen ohromena, víte. Abych ukázala, jak jsem vám vdìèná, rozdìlím se s vámi na pùl. Ještì jednou dìkuji, bylo to od vás velmi šlechetné.}
{401}{rbcca65}{Ach, jsem tak ráda, e se našla… zde jsou vaše peníze. Dìkuji mnohokrát.}
{402}{}{Není zaè.}
{410}{rbcca66}{Nemùu uvìøit, e jsou oba mrtví. Promiòte. Dìkuji vám za tuto informaci. A teï kdy mì omluvíte...}
{411}{rbcca67}{Nemùu uvìøit, e je mrtvı... po všech tìch letech.}
{412}{}{Jasnì.}
{413}{}{...}
{420}{rbcca68}{Jo, já vím, kdo to je. Vic je chlápek, kterého Metzger uvìznil.}
{421}{rbcca69}{Jo, znám Vica. Metzger ho strèil pod zámek. Ani nevím proè vlastnì.}
{422}{}{Kdo je Metzger?}
{423}{}{Mám další otázku.}
{424}{}{Skvìlé! Nashle.}
{430}{rbcca70}{Pøicházíte do Denu a nevíte, kdo je Metzger? Je to známı otrokáø. Sídlí ve vıchodní èásti mìsta. Nemùete ho minout.}
{431}{}{Mám další otázku.}
{432}{}{Díky.}
{440}{rbcca85}{Vrahu!}
{441}{rbcca86}{Vrahu dìtí!}
{442}{rbcca87}{Odejdìte prosím.}
{443}{rbcca88}{Takovım, jako jste vy, tu nenaléváme!}
{444}{rbcca89}{Bez boje mì nedostanete!}
{450}{rbcca71}{Buffy! Jsi to ty? Jak se ti daøí? Dlouho jsme se nevidìli!}
{451}{}{He?}
{452}{}{He?}
{460}{rbcca72}{Dave tì pozdravuje a byl by rád, kdyby tu mohl bıt osobnì, ale musel nìkam odbìhnout.}
{461}{}{Kam vyrazíme?}
{470}{rbcca73}{Nìco kvùli komandu... nebo šel moná po komandu. Nevím to pøesnì, ale tıká se to nìèeho takového.}
{471}{}{Aha.}
{480}{rbcca74}{Øekl, e ti mám tohle dát. Je to dar od rodiny Hendeeovıch. Mohlo by se ti to hodit.}
{481}{}{Co to je?}
{490}{rbcca75}{Ále, jen nìjaké cetky. Tady máš. (Becky ti podá $1000, 5 Stimpakù, kovovou zbroj, Uzi, 5 zásobníkù, plazmovı granát a kvìtinu.)}
{491}{}{Díky!}
{500}{rbcca76}{Není zaè. Schovávala jsem to jen pro tebe. No, radìji se vrátím do práce.}
{501}{}{Díky, nashle.}
{510}{rbcca77}{Vy o tom nevíte? Je mrtvı! Ach, já vím, e by mì to nemìlo tìšit, ale on byl velmi zlı èlovìk.}
{511}{}{Však také bojoval jako lev.}
{512}{}{Mám otázku.}
{513}{}{Ano, to byl. Sbohem.}
{514}{}{ zabít!}
{520}{rbcca78}{Coe? Vy? Já... nevím, co øíct. Byl to takovı zlı èlovìk...}
{521}{}{Podìkování by staèilo.}
{522}{}{Ehm.}
{530}{rbcca79}{Ne, jen podìkování by nestaèilo. Vím, e to není správné, ale... tady, vezmìte si tyto peníze. (Becky ti podá 1000 dolarù.)}
{531}{}{Nechte si ty peníze, Rebecco.}
{532}{}{Mockrát dìkuju.}
{533}{}{Dík!}
{534}{}{Uch! Cheská pani.}
{540}{rbcca80}{Jste úasnı mu. I pøesto, e vám nemùu prominout vaše èiny, udìlal jste pro svìt velikou slubu.}
{541}{rbcca81}{Jste úasná ena. I pøesto, e vám nemùu prominout vaše èiny, udìlala jste pro svìt velikou slubu.}
{542}{}{Díky.}
{550}{rbcca90}{Nechceme vás tu. Prosím, odejdìte.}
{551}{rbcca91}{Odejdìte prosím.}
{560}{rbcca82}{Proè jste znièil mùj destilátor? Co jsem vám kdy udìlala?}
{561}{}{Zaplatili mi za to.}
{562}{}{Nemusím se nikomu zpovídat.}
{563}{}{Nevím, o èem to mluvíte.}
{564}{}{Nevadí.}
{565}{}{Ooba gooba.}
{570}{rbcca83}{Opravdu? Urèitì vás do toho navezl ten lump Frankie. Tím jsem si jistá. Ale já si postavím novı, víte?}
{571}{}{To je mi jedno. U mi za to zaplatili.}
{572}{}{No a co.}
{573}{}{To mì nepøekvapuje.}
{580}{rbcca84}{Take vy jste také zbabìlec? To jsem si mohla myslet.}
{581}{}{...}
