{100}{}{Vidíš prostitutku.}
{150}{}{Je to naprosto obyèejná prostitutka.}
{152}{}{[MLUVIT]}
{153}{shela1}{Hej, já nedìlám enskı!}
{154}{}{Nevadí.}
{155}{}{Omlouvám se.}
{156}{}{Mami?}
{157}{shela2}{Hele, chlapeèku, bude to draší, jestli chceš mít i obecenstvo.}
{158}{}{Oni jdou tam, kam jdu já.}
{159}{}{Chci je mít s sebou.}
{160}{}{Ještì se vrátím.}
{161}{}{Mami?}
{162}{shela3}{Ach, zlato, celı ivot na tebe èekám. Kde jsi byl?}
{163}{}{Pøímo tady, zlato.}
{164}{}{Za kolik, sestro?}
{165}{}{Ach jo, musím jít. Nashle.}
{166}{}{Vííí!}
{167}{shela4}{Mám je ráda velkı a tupı.}
{168}{}{To jsem pøesnì já!}
{169}{}{Jó!}
{170}{}{Ach. Ne. Nashle.}
{171}{shela5}{Ty jseš ale velkej chlap!}
{172}{}{To máš pøece ráda.}
{173}{}{Ano, madam.}
{174}{}{Musím jít.}
{176}{}{Dobøe!}
{177}{}{Ne. Nashle.}
{178}{shela6}{Ty se vrátíš.}
{179}{}{Uvidíme.}
{180}{}{Eh, ne.}
{181}{}{[Slintat]}
{182}{shela7}{Nemáš dost penìz. Ztra se, zlato.}
{183}{}{Ještì se vrátím.}
{184}{}{Za to mi nestojíš, brouku.}
{185}{}{Ehh!}
{186}{shela8}{Byl jsi ohromnej!}
{187}{}{Jako vdycky, zlato.}
{188}{}{Nevadí.}
{189}{}{Ty taky.}
{190}{}{Já ochromenej!}
{191}{shela9}{Byl jsi skvìlej!}
{192}{}{Díky. Ty taky.}
{193}{}{Hmm.}
{194}{}{Jooo.}
{195}{}{Skvìlı!}
{196}{shela10}{Fajn, hotovo. Nashle.}
{197}{}{To je vše?}
{198}{}{Dobøe. Nashle.}
{199}{}{Bylo to dobrı.}
{200}{}{Pápá.}
{201}{shela11}{Za tohle mi platí málo.}
{202}{}{Tak tohle teda za ty prachy vùbec nestálo.}
{203}{}{Budu ti chybìt.}
{204}{}{Èau.}
{205}{}{Ztratil ses?}
{206}{shela12}{Zastav se zase nìkdy.}
{207}{}{Dobøe. Nashle.}
{208}{}{Jo, dobøe.}
{209}{}{Jehee!}
{210}{shela13}{Zatím.}
{211}{}{Èau.}
{212}{}{Pápá.}
{213}{shela14}{Stojí to $}
{214}{}{ za èíslo. Nejdøív zapla.}
{215}{shela17}{Pojï za mnou.}
{216}{shela18}{Já èekám.}
{217}{shela19}{Nehodlám v tıhle studené díøe stát celej den.}
{218}{shela20}{Mohl by sis pospíšit?}
{219}{shela21}{Poslední šance.}
{220}{shela22}{Fajn. U nehodlám èekat ani vteøinu.}
{221}{shela23}{Tak u pojï.}
{222}{shela16}{Jseš vzrušenej?}
{223}{shela24}{Pojï za mnou.}
{224}{shela25}{Hej, kámo, dej ty pracky pryè.}
{225}{shela26}{Ruce pryè! Nejsem ádná hraèka, se kterou si mùeš hrát.}
{230}{shela15}{Ehhh...? To bylo tvoje poprvé?}
