{100}{}{Vidíš otroka.}
{101}{}{Vidíš Vica.}
{150}{}{Tenhle otrok se zdá bıt pod pøísnım dohledem.}
{151}{}{Tohle je Vic.}
{152}{}{[MLUVIT]}
{153}{}{Mùeš mu øíct, e nemùu... poèkat. Kdo jsi?
 Ty nejsi otrokáø. Co tady dìláš?}
{154}{}{Jmenuju se }
{155}{}{. Chci tì dostat ven.}
{156}{}{Jsem }
{157}{}{, ale proè jsi v téhle místnosti zamèenı?}
{158}{}{Mùeš mi øíct, kde je Vault 13?}
{159}{}{Jsem }
{160}{}{. Hned jsem zpìt.}
{161}{}{Dubba iba }
{162}{}{.}
{163}{}{Metzger je na mì poøád naštvanı, i kdy jsem spravil to jeho podìlanı rádio. Vyhrouje, e mì prodá! Udìlám cokoliv budeš chtít, jen kdy mì dostaneš z tıdle šlamastiky.}
{164}{}{Dobøe, dostanu tì ven.}
{165}{}{Promiò, ale nemùu. Nashle.}
{166}{}{Jùù.}
{167}{}{Zdravím. Tohle podìlanı rádio se samo neopraví.
 Jak to mám asi tak podle nìj udìlat?}
{168}{}{Kde seenu náhradní díly?}
{169}{}{Moná to dokáu opravit.}
{170}{}{Mám tohle rádio. Mùeš ho pouít?}
{171}{}{Uvidím, co se dá dìlat.}
{172}{}{Spa pa?}
{173}{}{Já vím, e to dokáu opravit. Potøebuju jenom nìjakı náhradní díly. V mojí chatì v Klamathu je starı rádio, kterı má v sobì pøesnì to, co potøebuju. Znáš to u bratrù Duntonovıch? Moje chata je... vlastnì byla na vıchod odtamtud.}
{174}{}{Myslíš tohle rádio?}
{175}{}{Pùjdu se po nìm podívat.}
{176}{}{Hmmm... ještì se vrátím.}
{177}{vic5}{To je skvìlı! Hned to rádio opravím.}
{178}{}{Dobøe, promluvím si s Metzgerem.}
{179}{vic6}{Díky.}
{180}{}{Èau.}
{181}{vic7}{Coe? Je mi líto, ale nerozumím.}
{182}{}{Hurm.}
{183}{vic8}{Dìkuju ti! Jsem navìky tvım dluníkem. Jak ti to mùu oplatit?}
{184}{}{Øekni mi, kde je Vault 13.}
{186}{}{Pojï se mnou, pomoc se vdy hodí.}
{187}{}{To nic nebylo. Sbohem.}
{188}{}{Bonbón?}
{189}{}{Vault 13? Na vıchod odtud je Vault City.
 Obèas tam chodím obchodovat.}
{190}{}{Chceš tam jít se mnou?}
{191}{}{Dík. Mìj se.}
{192}{}{Jasnì, rád se k tobì pøidám! Tenhle prïola má pøed sebou ještì jedno velkı dobrodruství, tím jsem si jistej! A taky jsem docela dobrej v opravování vìcí, a si Metzger øíká, co chce.}
{193}{}{Skvìle, mùeme vyrazit.}
{194}{}{Vítej na palubì.}
{195}{}{Nevadí.}
{196}{}{Vic bıt nejlepší kámoš já.}
{197}{}{Chceš se ke mnì pøidat a pomoct mi pøi hledání?}
{198}{}{Skvìle! Díky.}
{203}{vic11}{Vault City je vıchodnì odtud. Ukáu ti to na tı tvı mapì.}
{204}{}{Díky.}
{206}{vic12}{Je to pøímo tady. (Ukazuje na mapì.)}
{220}{vic13}{Zatracenì. To je skoro to samı, jene já potøebuju rádio z mojí chaty v Klamathu. Vím, e má v sobì náhradní díly, kterı potøebuju.}
{300}{vic14}{Jo, asi ti mùu pomoct, ale nejdøív mì odsud musíš dostat.}
{301}{vic15}{Jak jsem øekl. Pomùu ti s èím budeš chtít, pokud mì odsud dostaneš.}
{302}{}{A jak to mám udìlat?}
{303}{}{Tak to máš smùlu.}
{304}{}{Dobøe. Uvidím, co se dá dìlat.}
{350}{vic117}{Myslíš, e mì mùeš pomoct?}
{351}{vic118}{Metzger mì poøád nechce nechat jít.}
{352}{vic119}{Tohle u moc dlouho nesnesu.}
{353}{vic120}{Udìlám pro tebe cokoliv, kdy mi pomùeš.}
{354}{vic121}{Všechny vıdaje ti zaplatím!}
{400}{}{Ještì jsi u mì nebyl, e? Já to rádio fakt potøebuju,
 Metzger je na mì èím dál naštvanìjší.}
{450}{}{Kde jsi pøišel k téhle lahvi na vodu?}
{451}{}{Mìl jsem láhev na vodu, na které byla velká lutá tøináctka. Vzpomínáš si, kde jsi k ní pøišel?}
{500}{vic17}{No jasnì, na to si vzpomínám. Koupil jsem ji od Eda. Obchoduje s brahmínama ve Vault City.}
{501}{}{Lahev na vodu? Jo, poèkat, mìl jsem jich tucty. A dobøe jsem je prodal. Mìl jsem je od Eda.
 Obchoduje s brahmínama ve Vault City.}
{502}{}{Vault City?}
{550}{}{Pøestal bys mi øíkat šéfe?}
{600}{vic19}{No jasnì, veliteli!}
{601}{}{Myslím to vánì! PØESTAÒ!}
{602}{}{To bude snad lepší.}
{650}{vic20}{Máš to mít, paráku!}
{651}{}{Uggg!}
{700}{}{Bıt pøítel já.}
{710}{}{Øekni mu, e to bez náhradních dílù neopravím. Nevím... poèkat.
 Kdo vlastnì jsi? Nìjakı novı rekrut? Neposlal tì, aby mì zase zmáèknul, e ne?
 To si vùbec nepomùe. Tady to opravit nedokáu.}
{750}{}{Joo?! Ty mì odsud dostaneš? Udìlám cokoliv, kdy mì vytáhneš z tıhle šlamastiky.
 Jedinı problém je, e mì sem Metzger zamkl, dokud mu nespravím tohle rádio
 a já nemám potøebné náhradní díly.}
{753}{}{Kde se dají sehnat ty díly, které potøebuješ?}
{754}{}{Uvidím, co se dá dìlat.}
{760}{}{To je dlouhı pøíbìh. V podstatì mì tu Metzger drí, dokud mu neopravím tohle podìlanı rádio.
 Krystal vyhoøel a já nemám ádné náhradní díly.
 Jak to mám asi tak podle nìj opravit?}
{761}{}{No, chci tì odsud dostat ven.}
{764}{}{Tak to nevím. Zatím.}
{800}{vic24}{Musím opravit tohle rádio. Kdy mi s tím pomùeš, tak se s ním moná domluvíme.}
{801}{}{Jak ti mùu pomoct?}
{803}{}{Tak to pochybuju. Hodnì štìstí.}
{810}{vic25}{Proè jsi zabil chudinku Mámu... asi jsi pro to mìl dùvod... promiò, šéfe. Nejsem tu od toho, abych se vyptával. Tohle je hodnì blbı mìsto. Jsem si jistej, e udìlala nìco hodnì škaredıho.}
{811}{vic26}{Hej, šéfe. Dík, e se ti podaøilo mì dostat z tı šlamastiky s Metzgerem. Nepotøebuješ nìco? Máma byla tak hodná, e mi dávala jídlo, kdy jsi byl pryè. Já ji tu pomáhám...}
{812}{}{Èau.}
{813}{}{Oooh.}
{814}{}{Èaaauua.}
{823}{}{Kde e je ten tvùj pøítel Ed?}
{830}{vic27}{To bych mohl, ale ty prostì nevypadáš dobøe. Byl bych jenom na obtí. Teï, kdy je po Mámì, pùjdu asi pryè. Nevím kam... moná se ještì nìkdy potkáme. Díky za všechno, co jsi pro mì udìlal.}
{831}{vic28}{To bych mohl, ale ty prostì nevypadáš dobøe. Vypadá to, e se sotva dokáeš postarat sám o sebe. Byl bych jenom na obtí. Prostì zùstanu tady, Mámino vaøení mi pøipomíná moji bıvalou enu...}
{832}{vic29}{To bych upøímnì mohl. Pro tebe bych udìlal skoro cokoliv. Jen teï prostì nevypadáš, e bys mohl nìkoho vést. Byl bych jenom na obtí. Já teï pùjdu k Mámì, za chvíli... dokud si to nevyøešíš. Její domácí jídlo u jsem dlouho nemìl.}
{833}{vic30}{Promiò, šéfe. Vypadá to, e u vás je hodnì. Teï, kdy je po Mámì, pùjdu asi pryè. Nevím kam... moná se ještì nìkdy potkáme. Díky za všechno, co jsi pro mì udìlal.}
{834}{vic31}{Vypadá to, e u vás je hodnì, šéfe. Poèkám tu na tebe, dokud si to nevyøešíš. Mámino vaøení mi pøipomíná moji bıvalou enu... jenom si nejsem jistej, jestli je to dobøe nebo špatnì...}
{835}{vic32}{To bych hroznì rád, šéfe, ale vypadá to, e u nemáš ádnı místo. Prostì pùjdu k Mámì. U jsem tam dlouho nebyl. Jestli u sebe najdeš místo, tak se pro mì zastav.}
{840}{vic33}{Ed je ve Vault City. Obchoduje s brahmínami. Byl jedním z mnoha mıch dodavatelù. Vault City odtud není daleko.}
{845}{vic34}{U jsem ti øíkal, e je to tady. (Vic ukazuje místo na tvém Pip-Boyi 2000.)}
{900}{}{Dozvídáš se o tom, e je Vic obchodník.}
{1000}{}{Chci se tì na nìco zeptat.}
{1100}{vic35}{Jsem úplnì vyléèenı, šéfe. Ještì nìco?}
{1200}{vic36}{Jsem skoro v naprostım poøádku, šéfe.}
{1300}{vic37}{Jsem víceménì vyléèenı, šéfe, ale u mi bylo líp.}
{1400}{vic38}{Zkusil jsem to, šéfe, ale necítím se moc dobøe. Ale i tak se budu snait.}
{1500}{vic39}{Jak myslíš, šéfe.}
{1501}{vic40}{Tady? Zrovna tady? Fajn, ty jsi tady šéf.}
{1502}{vic41}{Dobøe. Poèkám tu, dokud se pro mnì nevrátíš, šéfe. Vrátíš se, e jo?}
{1503}{vic42}{Jak dlouho budeš chtít. Nikam nepùjdu.}
{1504}{vic43}{Jasnì, šéfe.}
{1600}{vic44}{Kdy to øíkáš.}
{1601}{vic45}{Jasnì, šéfe.}
{1602}{vic46}{Bezva nápad, šéfe.}
{1603}{vic47}{Jasnì, šéfe. Ještì nìco?}
{1604}{vic48}{U je pryè, šéfe.}
{1605}{vic49}{ádnı problém, šéfe.}
{1606}{vic50}{Hotovo, šéfe.}
{1700}{vic51}{Jasnì, šéfe.}
{1701}{vic52}{Budu poblí, šéfe.}
{1702}{vic53}{Ty to víš nejlíp, šéfe.}
{1703}{vic54}{Jsem pøímo za tebou, šéfe.}
{1704}{vic55}{Jako lepidlo, šéfe.}
{1705}{vic56}{Kdy to øíkáš, šéfe.}
{1706}{vic57}{Dobøe, šéfe.}
{1800}{vic58}{Dobøe, budu se dret dál, ale ne moc daleko, šéfe.}
{1801}{vic59}{Dobøe, nebudu, šéfe.}
{1802}{vic60}{Budu se dret trochu dál, šéfe.}
{1803}{vic61}{Jasnì, šéfe.}
{1900}{vic62}{Jasnì, šéfe. Budu se dret dál.}
{1901}{vic63}{Cokoliv øekneš, šéfe.}
{1902}{vic64}{Hotovo, šéfe.}
{1903}{vic65}{Stojím dál, šéfe.}
{1904}{vic66}{Trochu ustoupím, šéfe.}
{1905}{vic67}{Rozptılíme se, šéfe.}
{1906}{vic68}{Dobøe, šéfe.}
{2000}{vic69}{Eh, šéfe? Vypadá to, e je vás u moc. Budu tu na tebe èekat.}
{2100}{}{Ty mì dìsíš, šéfe. Co se ti stalo? Vypadáš... no,
 pøíšernì. Myslím, e tu radši ještì chvíli zùstanu...}
{2200}{vic70}{To si piš, šéfe!}
{2201}{vic71}{Tak to kadopádnì, šéfe.}
{2202}{vic72}{Jasná páka, šéfe.}
{2203}{vic73}{Vdy pøipraven, šéfe.}
{2204}{vic74}{Skvìle! Tak pojïme.}
{2205}{vic75}{Skvìlı!}
{2206}{vic76}{Jsi nejlepší, šéfe!}
{2207}{vic77}{Nebudeš litovat. U ádnı chyby!}
{2208}{vic78}{Neboj, tentokrát si budu dávat pozor!}
{2209}{vic79}{Vìdìl jsem, e mi odpustíš to... ehm. Take, eh, šéfe... jakı je plán?}
{2210}{vic80}{Nezklamu tì, šéfe!}
{2211}{vic81}{Jsi super, šéfe!}
{2212}{vic82}{Já vìdìl, e na tohle ještì nejsem starej. To byly jenom ošklivı pomluvy! e jo, šéfe?}
{2300}{}{Od Eda. Oobchoduje s brahmínama ve Vault City. U jsi tam nìkdy byl? Ukáu ti to na tı tvı mapì.}
{2305}{vic199}{Vault City. Tady. Ukáu ti to na tı tvı parádní mapì.}
{2310}{vic84}{Mìl by bıt nìkde tady.}
{2311}{vic85}{Vault City. Mrkni se do tı svojí parádní mapy.}
{2403}{}{Odkud máš tuhle láhev na vodu?}
{2404}{}{Zapomeò na to.}
{2500}{vic86}{Jasnì, šéfe.}
{2501}{vic87}{Zeptej se mì na cokoliv, šéfe.}
{2502}{vic88}{Kdy mùu, pomùu, šéfe.}
{2503}{vic89}{Nejsem v prùseru, e ne šéfe?}
{2504}{vic90}{Udìlal jsem nìco špatnì, šéfe?}
{2505}{vic91}{Samozøejmì.}
{2600}{vic92}{A co teï, šéfe?}
{2601}{vic93}{Jakı je plán, šéfe?}
{2602}{vic94}{Snaím se, šéfe.}
{2603}{vic95}{Co pro tebe mùu udìlat, šéfe?}
{2604}{vic96}{Zmìna plánu, šéfe?}
{2605}{vic97}{Jiná strategie, šéfe?}
{2700}{}{Šéfe, koupil jsem to. Musíš mì dostat k doktorovi. Nevím,
 jestli ti mùu ještì krıt záda.}
{2701}{}{Potøebuju doktora, šéfe. Jsem na tom fakt blbì. Nevím,
 jestli s tebou mùu ještì bojovat.}
{2702}{vic100}{Šéfe, jsem na tom fakt blbì. Øekni Lennymu, a se na mì podívá.}
{2800}{vic101}{Hej, šéfe. Chceš, abych se teï k tobì pøidal?}
{2801}{vic102}{Hej, šéfe. Nevadí mi èekání. Jsem opravdu trpìlivı èlovìk.}
{2802}{vic103}{Zase spolu, šéfe? Budu se víc snait.}
{2803}{vic104}{U jsem se bál, e se nevrátíš. Rád tì zase vidím, šéfe.}
{2804}{vic105}{Zase sháníš spoleènost?}
{2805}{vic106}{Pøipraven na cestu, šéfe.}
{2806}{vic107}{Vìdìl jsem, e mì tu nenecháš.}
{2807}{vic108}{Potøebuješ nìkoho, kdo ti bude krıt záda?}
{2808}{vic109}{Potøebuješ nìco opravit, e jo? Jsem tvùj èlovìk, šéfe!}
{2809}{vic110}{Neboj se, šéfe. Se Sulikem nìjak vyjdeme, vánì.}
{2810}{vic200}{Pojïme.}
{2811}{vic201}{Zùstaò tady. Budu hned zpátky.}
{2812}{vic202}{Já jít.}
{3100}{vic111}{Coe? Eh... tak dobøe, šéfe. Kdy to øíkáš.}
{3101}{vic112}{Mùu na sebe natáhnout nìco jinıho, šéfe? Mám trochu obavy.}
{3102}{vic113}{Dobøe... ale nenecháš mì tu... e ne, šéfe?}
{3103}{vic114}{Ale... chci øíct... jasnì, šéfe. U si to sundávám.}
{3200}{vic115}{No, šéfe... s menšíma zbranìma jsem fakt dobrej. Poradím si skoro s kadou puškou, brokovnicí a vìtšinou malıch a støedních pistolí. 'Mùu' pouívat i noe. Taky umím docela dobøe házet, ale moje muška není nejlepší na svìtì... vlastnì je pìknì blbá. Promiò, šéfe. Opravdu se pokouším zlepšit.}
{3201}{vic116}{Jak jsem øíkal, šéfe, mám radìji menší zbranì. Zvládnu skoro kadou pušku, brokovnici a vìtšinu tìch malıch nebo støedních pistolí. Kdy se dostaneme do úzkıch, mùu zkusit pouít nù nebo dokonce vrhací zbranì.}
{3300}{vic203}{'Mùu' pouívat noe a taky umím docela dobøe házet, ale... moje muška není nejlepší na svìtì. Vlastnì je pìknì blbá. Promiò, šéfe. Opravdu se pokouším zlepšit.}
{3301}{vic204}{Jak jsem øíkal, šéfe. Noe a taky umím docela dobøe házet... jenom dost èasto nic netrefím.}
{3400}{vic122}{U toho mám dost!}
{3401}{vic123}{Utrhnu ti tu tvoji zatracenou hlavu! Nikdo nebude ubliovat mojí rodinì!}
{4000}{vic124}{Sem?}
{4001}{vic125}{Je to lepší, šéfe?}
{4002}{vic126}{Co tøeba sem?}
{4003}{vic127}{Ano, šéfe.}
{4004}{vic128}{Coe?}
{4005}{vic129}{Kam jdeme?}
{4006}{vic130}{Odcházíme, šéfe?}
{4007}{vic131}{U jdu.}
{4008}{vic132}{Promiò, šéfe.}
{4009}{vic133}{Lepší?}
{4010}{vic134}{Uuuf.}
{4011}{vic135}{A co tohle, šéfe?}
{4012}{vic136}{Budu stát tady.}
{4013}{vic137}{Pøesunu se sem.}
{4100}{vic138}{Šéfe! Není mi zrovna moc dobøe.}
{4101}{vic139}{Potøebuju doktora.}
{4102}{vic140}{Sakra, tohle fakt bolí.}
{4103}{vic141}{Au!}
{4104}{vic142}{Jau.}
{4105}{vic143}{Hergot.}
{4106}{vic144}{Doktor?}
{4107}{vic145}{Drím se... ale jen tak tak.}
{4200}{vic146}{Nikdy se mi tu nelíbilo.}
{4201}{vic147}{Proè je tu tak èisto?}
{4202}{vic148}{Necítíš nìco, šéfe?}
{4203}{vic149}{Víš, šéfe, myslím, e se sem u nikdy nevrátím. U to tady nemùu nazıvat domovem.}
{4204}{vic150}{Je to tu špinavìjší, ne si pamatuju.}
{4205}{vic151}{Nezùstaneme tu dlouho, e ne šéfe?}
{4206}{vic152}{Tohle místo se nikdy nezmìní.}
{4207}{vic153}{Šéfe, tohle místo mi nebude chybìt.}
{4208}{vic154}{Dík e jsi mì dostal ven, šéfe.}
{4209}{vic155}{Fakt ti dluím, šéfe.}
{4210}{vic156}{Páni, tady se to ale zmìnilo.}
{4211}{vic157}{Tady jsem nebyl vìènost.}
{4212}{vic158}{Sem pùjdu do dùchodu.}
{4213}{vic159}{Tady bych si mohl otevøít dílnu.}
{4300}{vic160}{Páni, šálí mì snad zrak? Tohle je... bylo moje místeèko, ale to u myslím víš. e jo, šéfe?}
{4400}{vic161}{Suliku, nedívej se na mì takhle.}
{4401}{vic162}{Šéfe, Sulik na mì u zase divnì èumí.}
{4402}{vic163}{Hodnı pejsek.}
{4500}{vic164}{La de da...}
{4501}{vic165}{Ho hum.}
{4502}{vic166}{Èekám na šéfa...}
{4503}{vic167}{Èekám na šéfa.}
{4504}{vic168}{Prostì èekám.}
{4505}{vic169}{Šéf by mì tu urèitì nenechal...}
{4506}{vic170}{uky uk... kdo je tam... poèkat. Jak to jenom bylo...}
{4507}{vic171}{Poøád èekám.}
{4508}{vic172}{Co to tu smrdí?}
{4509}{vic173}{Nepotøebuje tu nìkdo nìco opravit?}
{4510}{vic174}{Jsem tu a... èekám na šéfa.}
{4511}{vic175}{Takovı starı mu jako já a mrhá tu svım talentem.}
{4512}{vic176}{Mít tak kousek vıkaèky... u jsem ji nemìl dlouho.}
{4513}{vic177}{Mìl bych nechat toho obchodování se staroitnostma... jsou s tím jen problémy.}
{4514}{vic178}{Proè je èekání tak únavné...}
{4600}{vic179}{Eh, díky, šéfe.}
{4601}{vic180}{Díky.}
{4602}{vic181}{Víš urèitì, co dìláš?}
{4603}{vic182}{Nemùeme si místo toho prostì odpoèinout?}
{4604}{vic183}{Nepostavíme tábor?}
{4605}{vic184}{To jsem na tom fakt tak blbì?}
{4700}{vic185}{Nepøehánìj to, šéfe.}
{4701}{vic186}{Kdy na tom trváš, šéfe.}
{4702}{vic187}{Šéfe, nevybouchne mi hlava, e ne?}
{4703}{vic188}{Šéfe, zaèíná se mi to líbit.}
{4704}{vic189}{Cítím se trochu legraènì, šéfe.}
{4705}{vic190}{Opravdu toho máš tolik, e se mùeš rozdìlit?}
{4706}{vic191}{Jasnì, šéfe. Nìco si vezmu.}
{4707}{vic192}{Díky, šéfe.}
{4708}{vic193}{To není špatnı.}
{5000}{vic194}{Mám teï trochu hlad. Promluvíme si "U Mámy."}
{5500}{vic195}{Šéfe, myslím, e mám nìco zlomenıho. Radši se na to podívej.}
{5501}{vic196}{Šéfe, cítím se, jako kdybych hoøel. Radši se na to podívej.}
{5502}{vic197}{Šéfe, myslím, e jsem otrávenej. Radši se na to podívej.}
