{100}{}{Mu v tìké zbroji.}
{101}{}{Artuš, syn Uthera Pendragona.}
{102}{}{Má sklopené hledí.}
{103}{arth1}{Buï zdráv, pocestnı. Jmenuji se Artuš, syn Uthera Pendragona, z Bratrstva oceli. Jsme na vıpravì za svatım granátem z Antiochu. Nevidìl jsi ho nìkde?}
{104}{}{Svatı co a koho?}
{105}{}{Odpovìï hráèe}
{106}{}{Unga.}
{107}{arth13}{Není èas mluvit. Jsme na vıpravì.}
{108}{arth14}{Hledáme Svatı granát z Antiochu.}
{109}{arth15}{Pro Bratrstvo oceli!}
{110}{arth16}{Hmm... africká, nebo evropská vlaštovka?}
{111}{arth17}{Hej! To ti nepatøí!}
{112}{arth18}{Varuju tì. Dej ty ruce pryè.}
{113}{arth19}{Tak u dost. Èeho je moc, toho je pøíliš.}
{114}{arth2}{Svatı granát z Antiochu? To je nejlepší ruèní protipìchotní zbraò svého druhu.}
{115}{}{K èemu hledáte tak strašnou zbraò?}
{116}{arth3}{My z Bratrstva oceli usilujeme o nalezení této nejnièivìjší zbranì našich pøedkù. Chceme ji zachránit pøed tìmi, kteøí by zneuili nièivé síly Svatého granátu z Antiochu.}
{117}{}{Jak to?}
{118}{arth4}{Zkrátka proto, e Bratrstvo oceli chrání slabé a bezbranné a tahle vìc by skuteènì mohla nìkomu ublíit.}
{119}{}{Jak to?}
{120}{arth5}{Hmm... protoe to je jediná správná a morální vìc.}
{121}{}{Jak to?}
{122}{arth6}{No... eh... podívej, máme opravdu dost práce. Hodláš nám pomoci nebo ne? Vidìl jsi u nìkdy Svatı granát z Antiochu nebo ne?}
{123}{}{Ano.}
{124}{}{Ne.}
{125}{arth7}{Tak proè to neøekneš hned? Staèí nám povìdìt kde, my vyrazíme na cestu a ty se mùeš vrátit ke své práci, a u to bylo cokoliv.}
{126}{}{[Ukázat libovolnım smìrem]}
{127}{arth8}{Dobrá tedy. Díky za pomoc. Tady máš nìco za tvou slubu.}
{128}{}{Poèkat! Taky nìco hledám. Pátrám po svatém GECKu. Nevidìli jste ho?}
{129}{arth9}{Dobrá tedy, u nemá smysl dál pokraèovat v tomto rozhovoru. Odcházíme.}
{130}{}{[KONEC]}
{131}{arth10}{Zatracenı venkovan!}
{132}{}{[KONEC]}
{133}{arth11}{GECK, øíkáš? Ano, máme dva. Další u nepotøebujeme. Kadopádnì díky za optání.}
{134}{}{Kdy máte dva, moná byste mi mohli jeden dát.}
{135}{arth12}{Ne. Ne. To nemùeme. To by byl pøíliš snadnı konec tvého hledání. Nìjaké další jsou tamtím smìrem. Najdi si svùj vlastní. (Ukáe pøiblinì stejnım smìrem, jako jsi ukázal pøed chvílí ty, kdy jsi jim ukazoval, kde je svatı granát z Antiochu.)}
{136}{}{[KONEC]}
{200}{arth20}{Mluvíš královskım jazykem?}
{201}{arth21}{Ahój.}
{202}{arth22}{Hej, tady jsem.}
{203}{arth23}{Mìl bys chvilièku svého drahocenného èasu?}
{204}{arth24}{Ehm.}
{205}{arth25}{Ale no tak. Neignoruj mì.}
{206}{arth26}{Prosíííím! Potøebuju se tì na nìco hroznì dùleitého zeptat.}
{207}{arth27}{No, musíme pokraèovat v hledání svatého granátu z Antiochu. Pojï, Patsy.}
{300}{}{Náše poslání bylo naplnìno!}
{301}{}{Artuš, k tvım slubám.}
