{100}{}{Vidíš muže ve zdokonalené energo zbroji Mark II. Nevypadá pøátelsky.}
{101}{}{Vidíš Kagu ve zdokonalené energo zbroji Mark II.}
{102}{}{Je to obrovská hora železa s rukama a zbranìma.}
{103}{kaga41}{Už mì to pronásledování unavuje. Skonèeme to.}
{104}{kaga42}{To je naposled, kdy potkáváš Kagu.}
{105}{kaga43}{Kagovi se nemùžeš rovnat.}
{106}{kaga44}{Tìším se jak tì pošlu na onen svìt.}
{107}{kaga45}{Byl jsi dobrým soupeøem.}
{108}{kaga46}{V této èásti pustiny není potøeba dobráka, jako jsi ty.}
{109}{kaga47}{Až tì zabiju, budu nejobávanìjší osobou zdejší pustiny.}
{110}{kaga48}{Tìším se domù do Arroya... abych ho spálil na popel.}
{111}{kaga49}{Kaga se proslaví tvým zabitím.}
{120}{}{Kagaaaaaaaa!}
{150}{kaga1}{(Pøed tebou stojí vysoký a dobøe stavìný váleèník. Jeho oèi prahnou nenávistí, když si tì prohlíží.) Takže potom, co vyhnali Kagu, zvolili Vyvoleným tebe? Haha! Myslíš, že když jsi vnuk Zakladatele, že jsi výjimeèný?! Myslíš, že jsi lepší než já, velký Kaga?!}
{151}{}{No, já JSEM pøece Vyvolený, nebo ne?}
{152}{}{Hej hej, poèkej vteøinku. Nikdy jsem neøekl, že jsem lepší než ty.}
{160}{kaga2}{Ten titul nebude znamenat nic až ti Kaga utrhne hlavu!}
{161}{kaga3}{Žádné øeèi ti kùži nezachrání. Tvou smrtí bude Kagovi navrácena èest. Kaga se teï pomstí!}
{200}{}{*Chichi*}
{201}{kaga4}{Cože!? Ty jsi nový Vyvolený? No teda, ti už musí být vážnì zoufalí.}
{202}{}{Já ty nelíbit. Ty vypadat zlá.}
{203}{kaga5}{Kaga se ani nebude namáhat s tebou dál mluvit. Pøiprav se na smrt rukou Kagy!}
