{100}{}{Vidíš muže v kovové zbroji.}
{101}{}{Vidíš Kagu v kovové zbroji.}
{102}{}{Jo, je to Kaga, ne-až-tak-velký. Má kovovou zbroj a chce tì zabít.}
{103}{kaga24}{Zase ty!}
{104}{kaga25}{Už mì ta neustálá setkání zaèínají unavovat.}
{105}{kaga26}{Vyvolený - hmm!}
{106}{kaga27}{Skonèeme to.}
{107}{kaga28}{Bude tì mrzet, že jsi kdy slyšel jméno Kaga!}
{108}{kaga29}{Mé schopnosti doznaly velkého zlepšení od doby, co jsme se naposled setkali.}
{109}{kaga30}{Stává se z toho zlozvyk.}
{110}{kaga31}{Kaga musí ještì trochu trénovat.}
{111}{kaga32}{Kaga se vrátí.}
{120}{}{Takže se opìt setkáváme, Kago.}
{150}{kaga1}{(Pøed tebou stojí vysoký a dobøe stavìný váleèník. Jeho oèi prahnou nenávistí, když si tì prohlíží.) Takže potom, co vyhnali Kagu, zvolili Vyvoleným tebe? Haha! Myslíš, že když jsi vnuk Zakladatele, že jsi výjimeèný?! Myslíš, že jsi lepší než já, velký Kaga?!}
{151}{}{No, já JSEM pøece Vyvolený, nebo ne?}
{152}{}{Hej hej, poèkej vteøinku. Nikdy jsem neøekl, že jsem lepší než ty.}
{160}{kaga2}{Ten titul nebude znamenat nic až ti Kaga utrhne hlavu!}
{161}{kaga3}{Žádné øeèi ti kùži nezachrání. Tvou smrtí bude Kagovi navrácena èest. Kaga se teï pomstí!}
{200}{}{*Chichi*}
{201}{kaga4}{Cože!? Ty jsi nový Vyvolený? No teda, ti už musí být vážnì zoufalí.}
{202}{}{Já ty nelíbit. Ty vypadat zlá.}
{203}{kaga5}{Kaga se ani nebude namáhat s tebou dál mluvit. Pøiprav se na smrt rukou Kagy!}
