{100}{}{Vidíš mue v kevlarové zbroji.}
{101}{}{Vidíš Kagu v kevlarové zbroji.}
{102}{}{Má kevlarovou zbroj a zdá se, e má i docela slušné zbranì.}
{103}{kaga33}{Tentokrát jsem na tebe pøipraven.}
{104}{kaga34}{Vyvolenı se nikdy do Arroya nevrátí!}
{105}{kaga35}{Kaga tì rozdrtí!}
{106}{kaga36}{Kaga se nikoho nebojí!}
{107}{kaga37}{Stùj klidnì, a mùe Kaga poøádnì zamíøit.}
{108}{kaga38}{Ještì se uvidíme!}
{109}{kaga39}{Nevidíš Kagu naposled.}
{110}{kaga40}{Kaga nutnì potøebuje víc trénovat.}
{120}{}{Odejdi, Kago!}
{150}{kaga1}{(Pøed tebou stojí vysokı a dobøe stavìnı váleèník. Jeho oèi prahnou nenávistí, kdy si tì prohlíí.) Take potom, co vyhnali Kagu, zvolili Vyvolenım tebe? Haha! Myslíš, e kdy jsi vnuk Zakladatele, e jsi vıjimeènı?! Myslíš, e jsi lepší ne já, velkı Kaga?!}
{151}{}{No, já JSEM pøece Vyvolenı, nebo ne?}
{152}{}{Hej hej, poèkej vteøinku. Nikdy jsem neøekl, e jsem lepší ne ty.}
{160}{kaga2}{Ten titul nebude znamenat nic a ti Kaga utrhne hlavu!}
{161}{kaga3}{ádné øeèi ti kùi nezachrání. Tvou smrtí bude Kagovi navrácena èest. Kaga se teï pomstí!}
{200}{}{*Chichi*}
{201}{kaga4}{Coe!? Ty jsi novı Vyvolenı? No teda, ti u musí bıt vánì zoufalí.}
{202}{}{Já ty nelíbit. Ty vypadat zlá.}
{203}{kaga5}{Kaga se ani nebude namáhat s tebou dál mluvit. Pøiprav se na smrt rukou Kagy!}
