{100}{}{Vidíš muže v kožené zbroji.}
{101}{}{Vidíš Kagu v kovové zbroji.}
{102}{}{Má na sobì koženou zbroj a má protivný zlozvyk mluvit o sobì v tøetí osobì.}
{103}{kaga13}{To bude naposledy, kdy tì Kaga potkává.}
{104}{kaga14}{Až tì Kaga zabije, spálí Arroyo na prach.}
{105}{kaga15}{Pocítíš Kagùv hnìv!}
{106}{kaga16}{Jsem velký Kaga!}
{107}{kaga17}{Pøed Kagou se musí všichni tøást.}
{108}{kaga18}{Kaga si z tvé hlavy udìlá trofej.}
{109}{kaga19}{Vzdej se a tvoje smrt bude rychlá.}
{110}{kaga20}{Kaga se vrátí!}
{111}{kaga21}{Nemùžeš zabít velkého Kagu!}
{112}{kaga22}{Máš štìstí, že má Kaga nìco jiného na práci.}
{113}{kaga23}{Kaga se s tebou ještì setká.}
{120}{}{To je zase ten Kaga.}
{150}{kaga1}{(Pøed tebou stojí vysoký a dobøe stavìný váleèník. Jeho oèi prahnou nenávistí, když si tì prohlíží.) Takže potom, co vyhnali Kagu, zvolili Vyvoleným tebe? Haha! Myslíš, že když jsi vnuk Zakladatele, že jsi výjimeèný?! Myslíš, že jsi lepší než já, velký Kaga?!}
{151}{}{No, já JSEM pøece Vyvolený, nebo ne?}
{152}{}{Hej hej, poèkej vteøinku. Nikdy jsem neøekl, že jsem lepší než ty.}
{160}{kaga2}{Ten titul nebude znamenat nic až ti Kaga utrhne hlavu!}
{161}{kaga3}{Žádné øeèi ti kùži nezachrání. Tvou smrtí bude Kagovi navrácena èest. Kaga se teï pomstí!}
{200}{}{*Chichi*}
{201}{kaga4}{Cože!? Ty jsi nový Vyvolený? No teda, ti už musí být vážnì zoufalí.}
{202}{}{Já ty nelíbit. Ty vypadat zlá.}
{203}{kaga5}{Kaga se ani nebude namáhat s tebou dál mluvit. Pøiprav se na smrt rukou Kagy!}
