{100}{}{Vidíš exempláø z akumulaèních nádrí.}
{101}{}{Vidíš Kitsune.}
{102}{}{Kadé oko má jiné barvy. Jedno je svìtle hnìdé, druhé svìtle zelené.}
{103}{}{Vidíš štíhlou enu s tmavì hnìdımi vlasy. Vypadá nepøedvídatelnì.}
{104}{}{Má jemnou tváø a okouzlující oèi.}
{150}{}{Není slušné na mì takhle zírat.}
{200}{}{Pøed tebou leí otevøená nádr s ledovou vodou, která je odvádìna dlouhım spirálovitım potrubím pryè. Uvnitø leí ena, nahá, tak jak ji Bùh stvoøil. Rychle oddychuje a celá se chvìje. Bleskovì se rozhlédneš kolem, sáhneš po hromádce obleèení ze skøíòky, která je poblí, a zahalíš jím enu, aby se trochu zahøála.}
{201}{}{No teda, to musel bıt ale záitek. Jsi v poøádku?}
{202}{kit2}{A-ano, s-s-stabili-z-z-zátor o-obnovil moji t-tìlesnou t-t-teplotu.}
{203}{}{Zdá se, e ne na všech místech. }
{204}{}{(Chvíli poèkáš, ne jí pøestanou drkotat zuby zimou. Zotavila se rychleji, ne jsi oèekával. Vzhlédne k tobì naléhavım pohledem.) U... u to skonèilo?}
{205}{}{Co mìlo skonèit? }
{206}{}{Myslíš válku?}
{207}{kit4}{Válka. Všechny ty atomové bomby.}
{208}{kit5}{Ano, válka.}
{209}{}{Válka skonèila u dávno. Skonèila asi tak rychle jako zaèala.}
{210}{kit6}{(Sèesává si své mokré prameny vlasù z oèí. Všimneš si, e má jedno oko hnìdé, zatímco druhé smaragdovì zelené.) Kdo vyhrál?}
{211}{}{Nikdo.}
{212}{kit7}{(Nechápavì se na tebe podívá. Vypadá nádhernì, obzvláš, kdy si èlovìk uvìdomí, e právì roztála z velkého kusu ledu.)}
{213}{}{Kdy je 90% svìta spáleno na uhel, tak myslím, e bude velmi tìké vyhlásit koneèného vítìze. Jinak øeèeno, nezùstalo toho moc, co by mìlo nìjakou cenu.}
{214}{kit8}{Jaké... jaké je dnes datum? Co je za rok? Je poøád rok 2077?}
{215}{}{Kdepak. (Ukáeš ji datum v kalendáøi svého Pip-Boye.)}
{216}{kit9}{(Upøenì hledí na blikající obrazovku, zmrazena v èase, jako kdyby vùbec neopustila nádr.)}
{217}{}{Jsi v poøádku?}
{218}{kit10}{Ach mùj boe. Nemùu tomu uvìøit. Já jsem byla v té vìci zavøená pøes sto let?!}
{219}{}{Vypadá to tak. Poslyš, nedívej se na mì tak. Já za to nemùu, e tì tam nìkdo zavøel. Sakra, vdy ani mùj dìda nebyl tehdy naivu. Náhodou jsem na tohle místo narazil a rozhodl se ho prozkoumat. To je vše.}
{220}{kit11}{Tak pomùeš mi vstát, nebo bys byl radìji, kdybych ti dál sedìla nahá u nohou?}
{221}{}{Zrovna jsem se to chystal udìlat. [Pomoct jí na nohy]}
{222}{kit12}{Proè jsi mì probudil?}
{223}{}{Nemìl jsem pro to ádnı konkrétní dùvod.}
{224}{}{Bohuel trpím hroznım zlozvykem, e musím sahat na všechno, na co narazím. No a pak u to šlo samo.}
{225}{kit13}{Chceš mi øíct, e tady ani nepracuješ?}
{226}{}{Pøesnì tak.}
{227}{}{Take kdybys nešel kolem, tak bych zùstala uvìznìná v té vìci ještì déle. Moná navdy. (Oblékne si na sebe jedno z trièek, do kterıch jsi ji zabalil.) Jak teï vypadá svìt venku? Øíkal jsi, e bylo 90% povrchu znièeno?}
{228}{}{Mùj svìt je pustina, kde musí èlovìk bojovat o svoje pøeití kadı den. Vìtšina lidí našla úkryt v znièenıch mìstech nebo v troskách budov. Jiní, jako napøíklad mùj kmen, se pokusili vytvoøit fungující, jednoduchou spoleènost v drsné divoèinì. Pravdou je, e to mùe trvat i nìkolik staletí, ne se jen pøiblííme ke stavu, kterı byl pøed válkou.}
{229}{kit15}{Urèitì to nemùe bıt tak špatné, jak to zní. (Vùbec nezní tak, e by byla pøesvìdèena o tom, co právì øekla.)}
{230}{}{Neexistuje nic jako Amerika v roce 2077. Na to mùeš vzít jed.}
{231}{kit16}{(Oblékne si na sebe kalhoty.) Take, co teï?}
{232}{}{Ještì jsme se vlastnì ani nestaèili pøedstavit. Jmenuju se }
{233}{}{. Jak øíkají tobì?}
{234}{kit17}{Mùeš mi øíkat Kitsune.}
{235}{}{Take, Kitsune, jak ses dostala do toho kryo-mrazáku?}
{236}{kit18}{Nejsem si jistá. Vìdìli, e vypukne válka, tak mì umístili do stabilizátoru, tak jako všechny ostatní.}
{237}{}{Máš nìjaké ponìtí, co je tohle za místo?}
{238}{}{Co vím, tak tohle je jedna z poboèek Agentury na ochranu ivotního prostøedí Spojenıch státù americkıch. Byla jsem v Arizonì, kdy zaèala válka. Pak mì sem okamitì pøemístili.}
{239}{}{Musela jsi pro nì bıt velmi dùleitá, kdy tì chtìli takhle uchránit. Byla jsi Vyvolená jako já?}
{240}{kit20}{Eh, ne tak docela. Byla jsem ena v domácnosti, vdaná za radního. Pøedtím jsem psala pro nìkolik novin. Nebyl to ádnı vzrušující ivot.}
{241}{}{Co se stalo s tvım manelem?}
{242}{kit21}{Netuším. Pravdìpodobnì byl jednou z miliard obìtí. Nemyslím si, e nìkdo z mé rodiny pøeil válku. Mùj boe, i kdyby pøeili, je to tak dávno... kadı, koho jsem znala, je mrtvı. (Kousne se do rtu a její oèi se zalijí slzami. Rychle si je setøe, povzdechne si a uklidní se.)}
{245}{}{No, kdy mi dáváš na vıbìr, tak... [Ušklíbnout se]}
{246}{kit22}{(Rozzlobenì se na tebe podívá.)}
{247}{}{Eh, no, ovšem, e ti pomùu. [Pomoct jí na nohy]}
{250}{}{Co teï budeš dìlat?}
{251}{}{Nevím. Co bys udìlal ty, kdybys byl víc jak sto let v hibernaci? Ani medvìdi nespí tak dlouho. Svìt se zmìnil a já nevím, jestli dokáu ustát to, co se s ním stalo.}
{252}{}{Já vím, e tam venku je jen pustina, ale ty máš pøed sebou celı ivot. Chceš ho promarnit tady? Pojï se mnou a tøeba nìco zmìníme.}
{253}{}{Nevypadá to, e bys mìla moc na vıbìr. Mùeš zùstat tady a shnít, nebo mùeš jít se mnou. Je to jen na tobì.}
{260}{}{Víš, asi máš pravdu. Mohla bych se nechat znovu zmrazit a odespat si v klidu dalších nìkolik století, ne se z toho lidstvo dostane, ale to by bylo moc jednoduché. Chci vidìt, co se se svìtem stalo, v co se za tu dobu zmìnil a podílet se svou špetkou na jeho obnovì.}
{261}{}{Tak pojï. Dáme si dobrı brahmíní steak.}
{262}{kit97}{Doufám, e toho nebudu litovat.}
{270}{kit25}{Zapomeò na to. Víc jak sto let se nic nezmìnilo. Proè si myslíš, e zrovna my teï nìco zmìníme?}
{271}{}{Vrátím se pozdìji. Tøeba si to rozmyslíš.}
{272}{kit26}{Moná. Ale moc na to nespoléhej. Vrátím se zase ke svému spánku. Na další století nebo víc.}
{280}{}{Co kdy se ty stroje porouchají? Zemøeš a nikdy se nedozvíš, jestli se z toho svìt, kterı byl skoro znièen, nakonec vyhrabal.}
{281}{kit27}{Tak to budu pozorovat odjinud.}
{282}{}{Jak mùeš vìdìt, e budeš pøenesena na nìjaké speciální místo po tom, co usneš navìky? Pocházím z kmene, kterı vìøí na posmrtnı ivot a proroctví, ale z pragmatického hlediska jsme všichni jen stádo vodnatıch mìchù, organickıch strojù, které sice myslí, mluví a cítí, ale jenom proto, e se podaøilo pøírodì namíchat to správné sloení chemickıch sloek. Co kdy není nic po tom, co zemøeš? Vypneme se jako poèítaèe... tohle opravdu chceš?}
{283}{kit28}{Myslím, e budu radìji zmraená, ne se potulovat pustinou.}
{284}{}{Opravdu? U nezníš tak pøesvìdèivì jako pøedtím.}
{285}{kit29}{(Kitsune chvíli pøemıšlí nad tvımi slovy a poté se ti podívá do oèí.) Musím pøiznat, e na tom, co øíkáš, nìco je. Moná... moná to s tebou risknu.}
{286}{}{Pojïme tedy odsud pryè. Je nejvyšší èas, abychom tady z té špinavé díry vypadli.}
{287}{kit30}{I kdy, myslím, e asi vyrazím sama. Na vlastní pìst. Vdycky jsem byla samotáøka, take se nebojím, e by mi chybìla spoleènost. Hodnì se toho zmìnilo, zatímco jsem spala, a ráda bych to vidìla na vlastní oèi. Díky za rozmrazení. Mìj se.}
{288}{}{[KONEC]}
{300}{kit31}{Ano?}
{301}{kit32}{Jsem jedno velké ucho.}
{302}{kit33}{Copak máš na srdci?}
{303}{kit34}{Copak? Vypadáš, e máš nìco na srdci.}
{304}{kit35}{Co se dìje?}
{305}{kit36}{Potøebuješ ode mì nìco?}
{310}{}{Kitsune, je mi jasné, e tì neumístili do kryogenního mrazáku jenom tak pro nic za nic. Zajímalo by mì, co jsi opravdu udìlala, ne tì šoupli k ledu.}
{311}{kit37}{Proè tì to zajímá? Vdy u na tom nezáleí. Je to minulost.}
{312}{}{Táhneme teï za jeden provaz a chci se o tobì nìco dozvìdìt.}
{313}{kit38}{(Povzdechne si.) Tak dobøe. Pøedpokládám, e u nemá ádnı vıznam nìco skrıvat. Je pro mì tìké mluvit o nìèem, o èem jsem pøedtím celı ivot musela mlèet. Víš, narodila jsem se jako špión.}
{314}{kit39}{Mùj otec byl Èíòan, ale ani on, ani jeho rodina, nebyli pøátelé èínské vlády. Narodil se v Pekingu, ale nejdùleitìjší èást svého vzdìlání získal tady, ve Spojenıch státech. Kdy se vrátil domù do Èíny a získal práci jako státní zamìstnanec, tak u v té dobì pracoval pro Amerièany jako agent zpravodajské sluby.}
{315}{}{O tehdejší politické situaci toho moc nevím, ale myslím si, e chápu, co se mi snaíš øíct: Tvùj otec byl Èíòan, ale pracoval jako tajnı agent pro Amerièany. Stalo se nìkdy, e by ho Èíòané podezøívali?}
{316}{kit40}{Otec pracoval na Ministerstvu zemìdìlství tøicet osm let.}
{317}{}{Eh, dobøe. Hádám, e to znamená, e "ne". Take, kdy ses do toho pøipletla ty?}
{318}{kit41}{Jednoho dne mého otce nachytala pomocnice funkcionáøe, pro kterého mùj otec pracoval, jak poøizuje fotokopie tajnıch dokumentù.}
{319}{}{To nemohlo dopadnout dobøe...}
{320}{kit42}{Vlastnì to nedopadlo zase a tak špatnì. Víš, mìla s mım otcem podobné názory a bìhem nìkolika mìsícù se vzali.}
{321}{}{To má ale nìkdo štìstí, e?}
{322}{}{Narodila jsem se jim o rok pozdìji. Vyrùstala jsem v Èínì pod rouškou pravého vlastenectví. Ve škole jsem psala o tom, jak byla Èína nejsilnìjší, kdy byla sjednocená, a jak musíme i nadále pokraèovat v úsilí smìrovat spoleènost k sociální rovnosti. Kdy jsem pak byla starší, psala jsem pro nacionalistické noviny a úèastnila se diskuzí podporující vládnoucí stranu.}
{323}{}{Páni, vìtšinu z toho, co jsi øíkala, jsem vùbec nezachytil. Ale jestli tomu rozumím dobøe, tak jsi ty a tvoji rodièe lstí pøimìli Èíòany myslet si, e jste naprosto oddaní.}
{324}{}{Tvoji rodièe museli snášet velkou bolest, aby se ujistili, e skuteèná loajalita rodiny zùstane tajemstvím.}
{325}{kit44}{Všechny války jsou zaloeny na klamu. Mí rodièe milovali svou zemi. Nenávidìli jen lidi, kteøí ji øídili a kteøí si mysleli, e je jejich vedení lepší ne otevøená demokracie. Tak, jak to vidìli moji rodièe... oni nezrazovali Èínu, jen bojovali proti vládì, o které si mysleli, e zemi neprospívá.}
{326}{}{Pokraèuj.}
{327}{kit45}{Vzala jsem si funkcionáøe, kterı pracoval pro Èínské ministerstvo národní obrany. Zvolila jsem si právì jeho proto, e nejradìji hovoøil o své práci, kdy jsme byli spolu. Take jsem hrála svou roli oddané a milující manelky a zároveò jsem tajnì pøedávala dùleité informace svım americkım nadøízenım. Ale pak se to všechno hodnì zkomplikovalo.}
{328}{}{Jak to?}
{329}{kit46}{Mého otce kontaktoval Dr. Raynard Muldrake. Kolega, kterı s ním kdysi pracoval, kdy pobıval ve Státech. Dr. Muldrake naléhavì poádal o soukromou schùzku, ale mùj otec se v té dobì netìšil dobrému zdraví, take nepøipadalo v ádném úvahu, aby podstoupil nároènou cestu do Ameriky. Dr. Muldrake tedy souhlasil, e se setká se mnou u nìj doma.}
{330}{}{Co se stalo potom?}
{331}{kit47}{Ukázalo se, e Muldrake byl souèástí pøísnì tajného projektu, kterı probíhal ve vızkumném zaøízení West Tek v jiní Kalifornii. Celı projekt zaèal pomìrnì nevinnì, jako pokus najít zpùsob, aby byli lidé imunní vùèi Novému moru, ale rychle se vyvinul v nìco hrozivého. Øíkali tomu Virus zesílené evoluce nebo taky zkrácenì FEV.}
{332}{}{Pokraèuj.}
{333}{kit48}{FEV mìl potenciál vıraznì zvıšit sílu a intelekt osobì, které byl aplikován, ale byl velmi nestabilní. I pøesto armáda doufala, e se jí s pomocí FEV podaøí vytvoøit armádu super vojákù, kteøí by dokázali porazit Èíòany.}
{334}{kit49}{Dr. Muldrake byl proti jakékoliv zmìnì ve smìøování projektu, ale radìji mlèel, protoe se obával o svùj ivot. Jakmile se však dozvìdìl, e armáda testuje virus na nic netušícím obyvatelstvu malıch americkıch mìst, bylo mu jasné, e musí nìco udìlat. Svìt se musel dozvìdìt pravdu.}
{335}{}{A tehdy kontaktoval tvého otce...}
{336}{kit50}{Ano, pøesnì tak. Kdy jsme se pak sešli, pøedal mi holodisk obsahující pøísnì tajné dokumenty o projektu FEV. To mì postavilo do pomìrnì sloité situace: Mohla jsem zveøejnit informace, které disk obsahoval a zradit tak zemi, které jsem pøísahala svou vìrnost, nebo jsem mohla disk znièit a navdy tak pøed lidmi pohøbít tu ohavnou pravdu.}
{337}{}{A sakra. Neøíkej mi, e jsi...}
{338}{kit51}{Poslala jsem kopii disku všem pøedním novinovım deníkùm na svìtì. Tím jsem v podstatì znièila i tu poslední náklonnost, která ještì americké vládì zbyla. Sice jsem moná svìtu odhalila pravdu, ale bojím se, e jsem tím spustila i jeho destrukci... situace se poté rychle vyostøila a o osm mìsícù pozdìji dopadly první bomby.}
{339}{}{Jak ses nakonec dostala do té nádre, ve které jsi byla?}
{340}{kit52}{Americká vláda hledala osobu, která byla zodpovìdná za únik informací. Nakonec mì tìsnì pøed zaèátkem války odhalili. Pøípravy na mé zmrazení byly v plném proudu, kdy poprvé zaznìly sirény. Asi mì chtìli zachovat pro pøípad, e bych mìla další tajemství, o kterıch jsem jim neøekla.}
{341}{}{A mìla jsi?}
{342}{kit53}{Teï u je to všechno jedno. Všichni jsou u mrtví...}
{345}{}{Máš vùbec pøedstavu, co jsi vlastnì zpùsobila?}
{346}{kit54}{Co jsem tak mohla zpùsobit? Svìt by stejnì vyletìl do povìtøí. Byla to jen otázka èasu.}
{347}{}{Moná ses mohla vyhnout sdílení tak citlivıch informací s ostatními.}
{348}{kit55}{Chápu tì.}
{350}{}{Vím, co si asi myslíš, ale nemùeš se za nìco takového obviòovat.}
{351}{kit56}{Vdycky je jednodušší se zøíct zodpovìdnosti.}
{352}{}{Nemohla jsi to vìdìt. Krom toho, "mocnosti" mìly mezi sebou i jiné konflikty. Døív nebo pozdìji by se stejnì zasypali bombami. Byla to jen otázka èasu.}
{353}{kit57}{Lidé jsou ta nejhorší stvoøení na svìtì.}
{354}{}{Osobnì se nepovauju za tak hrozného.}
{355}{}{Pøíroda se nás snaí vymazat po tisíciletí všemi tìmi novımi nemocemi a pøírodními katastrofami. Jsme nìjakı evoluèní omyl. Moná jsme pøišli pøíliš brzy a moná jsme nemìli pøijít vùbec. Této planetì jsme zpùsobili víc škod ne kterékoliv jiné stvoøení, a u ijící nebo dávno vyhynulé.}
{356}{}{Mùeme to ale všechno odèinit. To je na nás to zvláštní, speciální.}
{357}{kit59}{Máš zatracenì dobrı zpùsob, jak všechno vyvrátit. Dìkuju ti za vyslyšení. Skoro cítím, e bych to mohla celé hodit za hlavu a ít spokojenì dál.}
{360}{}{Poslyš, kdy jsi byla ten špión, tak jsi urèitì hodnì dobrá v plíení a tak. Mohla bys mì nìco z toho nauèit?}
{361}{}{Ano, mám docela dost zkušeností s plíením, páèením zámkù a kradením. Teï ti ukáu pár fint, které v ádnıch knihách nenajdeš.}
{362}{kit61}{To je všechno. Pamatuj si, dùleitı je trénink.}
{363}{}{Paráda, díky. Myslím, e je nejvyšší èas, abychom vyrazili.}
{370}{}{Ty tvoje oèi...}
{371}{kit62}{Co je s nimi?}
{372}{}{Kadé má jinou barvu.}
{373}{}{Jak se tomu správnì øíká... heterochromie? Je to ono?}
{374}{}{Tohle není mùj pøirozenı stav. Levé oko není moje. O to své jsem pøišla pøi nehodì. Nikdy pøedtím jsem to nedokázala ocenit, a teï.}
{375}{}{Co tím myslíš?}
{376}{}{Od té transplantace jsem se vdy cítila, jako bych jedním okem vidìla minulost a druhım pøítomnost. Teï ještì víc ne pøedtím. A to mi pomáhá ít dál.}
{377}{}{Kadı máme svùj vlastní zpùsob, jak se vypoøádat se ivotem.}
{410}{kit65}{Co potøebuješ vìdìt?}
{411}{kit66}{Mám èernı pásek v sanshou. Ubodám èlovìka k smrti, pokud to situace vyaduje. Pistole, pušky a podobné zbranì zvládám taky docela dobøe.}
{420}{}{Musíme si promluvit o vzdálenosti mezi námi.}
{421}{kit67}{Co je s ní?}
{422}{}{Dr se blízko mì.}
{423}{kit68}{V poøádku. Budu ti krıt záda.}
{424}{}{Moc se nevzdaluj.}
{425}{kit69}{Je mi to jasné. Potøebuješ trochu víc místa.}
{426}{}{Udruj vìtší rozestup.}
{427}{kit70}{Jasnì. Takhle nebudeme snadnı cíl.}
{430}{kit71}{A ti to netrvá moc dlouho, protoe jinak odejdu bez tebe.}
{431}{kit72}{Zahraju si Solitaire, ne se vrátíš.}
{432}{kit73}{Nìèím se zatím zabavím do doby, ne se vrátíš.}
{440}{kit74}{Kdykoliv k slubám.}
{441}{kit75}{Jsem ráda, e jsi zpátky. Vypsala jsem nìkolik konkurzù, ale nemohla jsem za tebe najít dobrou náhradu.}
{442}{kit76}{Chybìla ti má spoleènost?}
{443}{kit77}{Cítíš se provinile, e jsi odešel beze mì?}
{444}{kit78}{U jsem si zaèínala pomalu myslet, e se nevrátíš.}
{445}{kit79}{U bylo naèase. Ve starovìké Èínì by tì za takovou nedochvilnost povìsili, natáhli na skøipec a potom rozètvrtili.}
{446}{kit80}{Ahoj. Zrovna jsem na tebe myslela.}
{450}{kit81}{No to to ale trvalo.}
{451}{kit82}{Jsem ráda, e jsme zase na cestách.}
{452}{kit83}{Kam vyrazíme?}
{453}{kit84}{Take kam teï pùjdeme?}
{454}{kit85}{Mùeme vyrazit.}
{460}{kit86}{Vypadá to, e u máš spoleèníkù víc ne dost. Nepotøebuješ další doprovod.}
{461}{kit87}{Moná a uvolníš nìjaké místo. Nemám ráda tlaèenice.}
{462}{kit88}{Jsi pøipraven mì vzít s sebou?}
{463}{}{Pojïme.}
{464}{}{Ne, ještì ne.}
{470}{kit89}{Jeíši, vypadáš jako smrtka. Radìji se nech vyšetøit.}
{480}{kit90}{ádnı problém. Bez ní se mi chodí daleko lépe.}
{490}{kit91}{Nikdy mi nebylo lépe. Mùeme jít.}
{491}{kit92}{U mi bylo lépe, ale je to jenom pár škrábancù.}
{492}{kit93}{Není to tak hrozné. Jen nìjaká povrchová zranìní.}
{493}{kit94}{Není mi zrovna nejlépe. Teèe ze mì spoustu krve.}
{494}{kit98}{Potøebuju doktora, nebo ti nebudu schopná s nièím pomoct.}
{495}{kit99}{Nemùu dál pokraèovat... nech mì tady, nebo mi okamitì seeò doktora. Rychle.}
{500}{kit95}{Kdy na tom trváš. Poøád ještì mùu urvat chlapovi hlavu holıma rukama.}
{1000}{kit100}{Poøád nemùu uvìøit, e jsem na tomhle místì strávila víc jak sto let.}
{1010}{kit101}{Bez uráky, ale tohle není místo, kde bych se chtìla narodit.}
{1020}{kit102}{Tohle vypadá jako nìjaká císaøská hrobka z 15. století.}
{1030}{kit103}{Tohle místo smrdí jako jedno velké brahmíní hovno.}
{1040}{kit104}{Myslím, e by nebylo moudré chodit dál bez správné obuvi.}
{1050}{kit105}{U jsem vidìla i horší místa, vìø mi. To ale neznamená, e se mi tu líbí.}
{1060}{kit106}{Venkov. Tady se mi líbí.}
{1070}{kit107}{Tady to vypadá jako vystøiené z nìjakého béèkového hororu.}
{1080}{kit108}{Úplnì cítím tu radiaci ve vzduchu.}
{1090}{kit109}{Co má tohle jako bıt? Pracovní tábor?}
{1100}{kit110}{Lidé uvnitø se mají daleko lépe ne ti venku. Svìt se zase tak moc nezmìnil.}
{1110}{kit111}{Co je tohle za hornické mìsto?}
{1120}{kit112}{Bez uráky, ale tohle není místo, kde bych se chtìla narodit.}
{1130}{kit113}{Perfektní místo, kdy se chceš schovat pøed zákonem.}
{1140}{kit114}{Zajímalo by mì, jestli je tady v okolí víc takovıch bunkrù.}
{1150}{kit115}{Vsadím se, e je tohle "Nejvìtší malé mìsto na svìtì".}
{1160}{kit116}{Tady urèitì nemají jenom dobytek...}
{1170}{kit117}{Smrt všude kam se podíváš...}
{1171}{kit118}{Tady bych nechtìla bıt pohøbená.}
{1180}{kit119}{Prostì pøedeeneme pøírodu a vyvineme se sami, e? }
{1190}{kit120}{Tak vysoké budovy jsem nevidìla od doby, kdy Taipei 101 srovnali se zemí.}
{1200}{kit121}{Tohle vypadá na dobøe støeené místo.}
{1210}{kit122}{O tomhle místì jsem kdysi slyšela...}
{1220}{kit123}{Je to pøíjemnı pocit pøijít do mìsta, kde to vypadá, e všechno funguje jak má.}
{1230}{kit124}{O tomhle místì jsem kdysi slyšela...}
{1240}{kit125}{Poslední svaté místo v tìchto nehostinnıch pustinách.}
{1250}{kit126}{Tady je ale horko.}
{1251}{kit127}{Potím se jako brahmína.}
{1252}{kit128}{Mám hrozné sucho v krku.}
{1253}{kit129}{Líbilo by se mi tady víc, kdyby to bylo moøe.}
{1254}{kit130}{Suliku, neumìl bys tancem pøivolat déš?}
{1260}{kit131}{Teï jsme tak daleko od civilizace, jak to jen jde.}
{1270}{kit132}{Pochybuju, e by se ta voda dala pít a to i po odfiltrování veškeré soli.}
{1271}{kit133}{Jestli tady jsou vùbec nìjaké ryby, tak budou urèitì zmutované.}
{1272}{kit134}{Je tady docela chladno.}
{1273}{kit135}{Sto babek tomu, kdo nahı vleze do té vody.}
{1280}{kit136}{Vùbec nic nevidím.}
{1281}{kit137}{Tady to strašnì smrdí. Kdybych nìco vidìla, tak to bude urèitì ještì horší.}
{1282}{kit138}{Opatrnì. Urèitì se tam schovává nìco hnusného a smradlavého.}
{1283}{kit139}{To byli netopıøi, co jsem teï slyšela?}
{1284}{kit140}{Co tady jako dìláme? Speleologii?}
{1285}{kit141}{Lepší bude zapálit svìtlici ne proklínat tmu.}
{1290}{kit142}{Válka... tak ta nám fakt pomohla.}
{1291}{kit143}{Prach jsi a v prach se obrátíš...}
{1292}{kit144}{Bydlela jsem na podobném místì jako je tohle.}
{2001}{kit145}{To tì moje oèi tak moc vadí?}
{2002}{kit146}{Dala bych si koupel v termálním prameni. Zajímalo by mì, jestli ještì nìjaké existují.}
{2003}{kit147}{Zabíjela bych, abych si mohla s nìkım zahrát mah-jong.}
{2004}{kit148}{Všichni jí a pijí, ale jen málokdo dokáe ocenit chu.}
{2005}{kit149}{Z tohohle svìta se stalo pravé peklo. Všech tøináct komnat.}
{2006}{kit150}{Vìøím v Boha i Ïábla, ale od obou si drím odstup.}
{2007}{kit151}{ijeme ve snu, nebo jsme jen sen nìkoho jiného?}
{2008}{kit152}{Nenávidím nás za to, co jsme zpùsobili.}
{2009}{kit153}{Zajímalo by mì, jak dlouho nám bude trvat, ne se z té války vzpamatujeme.}
{2010}{kit154}{Pokud nás stvoøilo nebe, tak si naše planeta pro nás nìjaké to vyuití najde.}
{2011}{kit155}{Máš ízeò? Já tedy urèitì.}
{2012}{kit156}{*zív*}
{2013}{kit157}{Èlovìk míní, Bùh èiní.}
{2020}{kit158}{Hej Suliku, co øíkají duchové?}
{2030}{kit159}{Nechceš zhubnout, Vicu? Dám ti lekce taebo, kdykoliv budeš chtít.}
{2040}{kit160}{Tvoje ena poøád vaní jen o sobì.}
{2041}{kit161}{Øekni té své venkovské enušce, aby to na mì pøestala zkoušet.}
{2050}{kit162}{Myrone, pøestaò mi laskavì poøád zírat na kozy.}
{2051}{kit163}{Co kdybys na dvì minuty ztichnul, Myrone? Zabilo by tì to?}
{2052}{kit164}{Ne, Myrone. Nevyspala bych se s tebou, i kdybys mi postavil stroj èasu.}
{2053}{kit165}{Poslouchej, Myrone. Jestli na mì ještì jedou sáhneš, tak z tebe udìlám eunucha.}
{2060}{kit166}{Hej, Marcusi. Nedáme si páku?}
{2070}{kit167}{U s sebou taháme dost psù, nepotøebujeme dalšího.}
{2100}{kit168}{Eh, cítím se hroznì.}
{2101}{kit169}{Myslím, e jsem otrávená...}
{2110}{kit170}{Nìco se mnou není v poøádku...}
{2111}{kit171}{Cítím se divnì...}
{2112}{kit172}{Moje ruka svítí.}
{2113}{kit173}{Jsem liška a ne had... tak proè se mi loupe kùe?}
{2114}{kit174}{Nìco mì uvnitø pálí... co se to se mnou dìje?}
{2120}{kit175}{Myslím, e mám nìco zlomeného. Potøebuju prohlédnout.}
{2121}{kit176}{Mám pocit, e mám nìco zlomeného...}
{2130}{kit177}{Sakra, skoro nic nevidím.}
{2131}{kit178}{Nesnáším, kdy nic nevidím.}
{2330}{}{Co kdybys mi øekla, jak se jmenuješ? Já jsem }
{3000}{kit179}{To je lepší.}
{3001}{kit180}{Díky moc. To mi hroznì pomohlo.}
{3002}{kit181}{U se cítím daleko lépe. Díky.}
{3003}{kit182}{Díky. Tohle jsem potøebovala.}
{3004}{kit183}{Máš dost i pro sebe?}
{3010}{kit184}{Silné pití. Ještì e vím kdy pøestat.}
{3011}{kit185}{Nevím, proè tohle piju. Chutná to jako Okena.}
{3012}{kit186}{Sice nemám chlast ráda, ale dobøe tlumí bolest.}
{3013}{kit187}{Máš ještì nìco dalšího na pití?}
{3014}{kit188}{Doufám, e se neprobudím ve vlastních zvratcích.}
{3015}{kit189}{Mùj plán zùstat dnes støízlivá je v troskách.}
{3020}{kit190}{Do prdele... doufám, e nikdy nebudu muset èelit celému gangu nadopovanım tímhle svinstvem.}
{3030}{kit191}{S tímhle opatrnì. Tohle svinstvo rozhodí tvùj testosteron.}
{3040}{kit192}{Doufám, e a odezní úèinky, tak ze mì nebude idiot.}
{3050}{kit193}{Zvyky jsou jako pavouci. Nejdøív tì chytnou a potom otráví.}
{3051}{kit194}{Meè je mocnìjší ne nebe.}
{3052}{kit195}{Oko za zub, zub za všechny.}
{3053}{kit196}{Èlovìk potøebuje oblièej, tak jako strom potøebuje štìkat.}
{3054}{kit197}{Strom padá, kdy na nìj leze opice.}
{3055}{kit198}{Všechny vrány na svìtì jsou chytøejší ne prùmìrnı jestøáb.}
{3056}{kit199}{Tak dlouho se chodí se dbánem pro vodu, a dno upadne.}
{3057}{kit200}{Synové tygra nejsou lvi.}
{3058}{kit201}{Uè se. A uè se chybám.}
{3059}{kit202}{Jízda pøedchází pádu.}
{3060}{}{Bojuj pískem proti ohni, prachem proti magii.}
{3061}{}{Musíme se všichni pøipravit na válku o mír.}
{3062}{}{Pøidej hadovy pruhy, a ho domaluješ.}
{3063}{}{Tygr se mùe zbavit svıch skvrn tím, e se z nìj tìko sesedá.}
{3064}{}{Èlovìk nemùe odmítnout jíst jen proto, e mùe mít pozdìji zase hlad.}
{3065}{}{Obraz je hoden sto letùm bolesti.}
{3066}{}{Mùe bıt krutá jako tygøice, nikdy však nesní své vlastní kraby.}
{3067}{}{Prsty moøské panny jsou krátké a sladké.}
{3068}{}{Zabij tisíce, ztratíš jednoho.}
{3069}{}{Své nepøátele si dr poblí a své pøátele pøímo pod sebou.}
{3070}{}{Vyhnout se nejvìtší slabinì, jeden udeøí na tu nejsilnìjší zepøedu.}
{3071}{}{Pokud je váš nepøítel dobøe vycvièenı, pøipravte se na extázi.}
{3072}{}{Zatlaè nepøítele, aby se mohl pøipravit.}
{3073}{}{Ten, kdo ví, ne jak bojovat, ale kdy, dosáhne vítìzství.}
{3074}{}{Le má krátké ruce.}
{3075}{}{Neviditelnost moná záleí na obranì nepøítele pøi vítìzném útoku.}
{3076}{}{Poznej sám sebe. Poznej svého nepøítele. Poznej své pøátele a rodinu.}
{3077}{}{Pøíleitosti se násobí podle toho kolikrát kıchneme.}
{3078}{}{Propíchni protivníka svım egem.}
{3079}{}{Pøedstírej slabost. Dodej odvahu protivníkovì ignoranci.}
{3080}{}{Taktická strategie znamená jisté vítìzství.}
{3081}{}{Opatrní vládci jsou obvykle høíšní.}
{3082}{}{Uteè v nejlepší chvíli a celı národ se bude tøást ve prospìchu prodlouené války.}
{3083}{}{Je lepší zapálit mìsto, ne si stìovat na tmu.}
{3084}{}{Existuje milion zpùsobù, jak se koèka mùe zbavit své kùe.}
{3085}{}{Neexistuje zpùsob, jak vymáèknout oblázky z kapky krve.}
{3086}{}{ádná krev není hustší ne voda.}
{3087}{}{Na obloze musí bıt dvì slunce.}
{3088}{}{Ukradni lidské maso a oznaè ho.}
{3089}{}{Mentalita je lidské maso nesoucí potenciál, kterı slábne.}
{3090}{}{Pták zpívá, protoe jeho zpìv je odpovìdí.}
{3091}{}{Sni svùj hlas a zvyš svou sílu.}
{3092}{}{Jez do prasknutí, choï podle vzdálenosti, kterou chceš ujít.}
{3093}{}{Jestlie slovo stojí za šejka, pak ticho stojí za císaøe.}
{3094}{}{Kdo se smìje naposled, ten se smìje poslední.}
{3095}{}{Bohaté uráet, chudé klamat.}
{3096}{}{Èím kdo zachází, tím také odchází.}
{3097}{}{Nikdo se neblíí k smrti, jako ten, kdo poslouchá.}
{3098}{}{Jeden za všechny, všichni za nás.}
{3099}{}{Všichni lidé jsou nesmrtelní jako Osm.}
{3100}{}{Kdy umíráte ízní, není ještì pozdì se k vodì prokopat.}
{3101}{}{Èím vyšší je bambus, tím blíe se panda objevuje.}
{3102}{}{Nikdy nevìø krásnému ránu a úsmìvu tchynì.}
{3103}{}{Oèi jsou našimi jedinımi okny.}
{3104}{}{Stáøí se k tobì plazí jako špinavı starı mu.}
{3105}{}{Nebe se nikdy nemılí. Bezbonım bude jejich mzda vyplacena v èasu.}
{3106}{}{Spravedlnost je mravná duše, která se rozprostírá po poušti.}
{3107}{}{Lepší deset mrtvıch nevinnıch, ne jeden trpící viník.}
{3108}{}{Sínì v síních spravedlnosti jsou jediná spravedlnost.}
{3109}{}{Zamkni stáje, kdy je kùò ukraden.}
{3110}{}{Chodí štìstí dokola, ne se unaví.}
{3111}{}{Nikdy si neber dar z koòské tlamy bez zeptání.}
{3112}{}{Celı svìt se ti smìje. Pak pláèeš spolu s kamarády.}
{3113}{}{Mnoho rukou èiní svìtlo funkèním.}
{3114}{}{Mísa mrkví, nepøebranıch, neoèištìnıch a se zeleninou.}
{3115}{}{Oslovy rty líbají tlamu konì jen, kdy dostane v noci zvláštní pøídìl píce.}
{3116}{}{S obuškem do tygøího doupìte nelez.}
{3117}{}{Svinì vrhá náhrdelník z perel.}
{3118}{}{Kaviár Imperátor.}
{3130}{}{Dobøe. Koneènì se nìkam dostáváme.}
{3210}{}{Dobøe. Teï, kdy znám ivotní pøíbìh tvého otce, nevadilo by ti, kdybys pøešla k té èásti, která je o tobì?}
{3260}{}{Take zradili své vlastní lidi, ale pro jejich vlastní dobro. Chápu.}
{3261}{}{Poslyš, ty povídaèky o tvıch rodièích mi u lezou krkem. Co kdybys tuhle èást pøeskoèila a pøešla rovnou k tomu, jak ses stala špiónem?}
{5000}{kit96}{(ena k tobì vzhlédne, její oèi se najednou rozšíøí a poté zaène lapat po dechu).}
{5001}{}{[KONEC]}
{5002}{}{Do prdele!}
