{100}{}{Vidíš plešatého pankáèe.}
{101}{}{Vidíš Chipa. Vypadá lépe.}
{102}{}{Vidíš plešatého pankáèe. Zdá se, že už se zotavil.}
{103}{chip1}{Au, moje vnitønosti... au, au, au.}
{104}{}{He?}
{105}{}{Auvajs?}
{106}{}{Co je to s tebou?}
{107}{}{Bolí tì nìco? Hehehe.}
{108}{}{Kdo jsi?}
{109}{}{Nevíš nìco o mých lidech?}
{110}{chip2}{Auuu, moje vnitønosti. Strašnì trpím. Prosím, nech mì na pokoji.}
{111}{}{Dobøe.}
{112}{chip3}{Co mi je? Tak já ti to povím: Minulej tejden jsem se ožral, zaèal jsem hrát s Lao Chouem a prohrál. Byl jsem tak opilej, že jsem vsadil svoji slezinu. Teï ji má on a já ji potøebuju zpátky.}
{113}{}{Ty jsi PRODAL vlastní slezinu?}
{114}{}{Tak to je zlé.}
{115}{}{Ty musíš být ale pìkný hlupák.}
{116}{}{Potøebuju nìjaké informace místo toho tvého naøíkání.}
{117}{chip4}{::lapá po dechu:: Jdi do prdele.}
{118}{chip5}{::lapá po dechu:: Jdi do hajzlu.}
{119}{}{Jak chceš.}
{120}{}{Poslyš, zmìnil jsem názor. Chci ti pomoct.}
{121}{chip6}{Jo, prodal jsem ji. Byl jsem opilej! A navíc mám dojem, že mi dal Lao Chou do pití trochu Jetu. Potøebuju zpátky svou slezinu, protože už dostávám infekce.}
{122}{}{Hele, ty jsi ji ztratil, takže je to tvùj problém. Smiø se s tím.}
{123}{}{Dobøe, sakra, podívám se ti po ní.}
{124}{chip7}{Ano, to je. Potøebuju zpátky svou slezinu, protože už dostávám infekce.}
{125}{}{Hele, ty jsi ji ztratil, takže je to tvùj problém. Smiø se s tím.}
{126}{}{Dobøe, sakra, podívám se ti po ní.}
{127}{chip8}{Toho si opravdu vážím. Jdi si promluvit s obchodníkem Lao Chouem a øekni mu, že potøebuju zpátky svoji slezinu.}
{128}{}{Ještì se vrátím.}
{129}{chip9}{Jsem Chip. A strašnì trpím.}
{130}{}{Co je to s tebou?}
{131}{}{Bolí tì nìco? Hehehe.}
{132}{}{Tak to je zlé. Mìj se.}
{133}{chip10}{Informace? Je mi zle a ty chceš informace?}
{134}{}{Co je to s tebou?}
{135}{}{Bolí tì nìco? Hehehe.}
{136}{}{Zapomeò na to.}
{137}{chip11}{Našel jsi už moji slezinu?}
{138}{}{Ano. Má ji Dr. Wong Yi Tze a vrátí ti ji zpìt. Jdi si s ním o tom promluvit.}
{139}{}{Ano. Jdi prohledat mrtvolu Dr. Wonga.}
{140}{}{Tak nìjak. Má ji Dr. Wong Yi Tze, ale nechce mi ji dát.}
{141}{}{Vím, kde je, ale myslím, že ji Dr. Wong snìdl.}
{142}{}{Ne, ještì ne. Ale najdu ji.}
{143}{}{Ne. Vlastnì ji ani nehledám.}
{144}{chip12}{Tak dobøe. ::supìní:: Než to udìlám, možná bysme mìli najít zpùsob, jak ji dostat zpátky do mì. Promluv si o tom s Dr. Fungem, ano? Díky.}
{145}{}{Tak dobøe.}
{146}{}{Ne.}
{147}{chip13}{Opravdu si vážím toho, co pro mì dìláš. Nezapomenu na to.}
{148}{}{Žádný problém.}
{149}{chip14}{Kámo, v tomhle stavu si tìžko nìkam dojdu. Jestli mi nepomùžeš, tak jsem v háji.}
{150}{}{Fajn. Pùjdu si promluvit s Fungem.}
{151}{}{Fajn. Stejnì jsi mi u zadku.}
{152}{chip15}{Mùžeš s tím nìco udìlat... zabít ho, pøemluvit ho a tak... bez sleziny umøu.}
{153}{}{Uvidím, co se dá dìlat.}
{154}{}{Promiò, chlape... ale myslím, že jsi v háji. Nedokážu ti pomoct.}
{155}{chip16}{Bez sleziny umøu. Ale stejnì ti dìkuju za pomoc.}
{156}{}{Mám ji. Zajdi k Dr. Wongovi.}
{157}{}{To nic, já to zaplatím. Zajdi k Fungovi.}
{158}{}{Žádný problém. Hodnì štìstí.}
{159}{chip17}{Mluvil jsi už s Fungem?}
{160}{}{Jo, øíká, že ti ji pøišije zadarmo.}
{161}{}{Jo a chce po mnì $1000.}
{162}{}{}
{163}{chip18}{Páni. Máš nejspíš velký známosti. Pøijï zítra a uvidím, s èím ti budu moct pomoct.}
{164}{}{Máš to mít.}
{165}{chip19}{Mùžeš mì založit?}
{166}{}{Jo, asi jo.}
{167}{}{Ne.}
{168}{chip20}{Opravdu si toho cením. Pøijï zítra a uvidím, s èím ti budu moct pomoct.}
{169}{}{To doufám.}
{170}{chip21}{To si nemùžu dovolit. Takže asi nejspíš umøu.}
{171}{}{No dobøe, zaplatím to za tebe.}
{172}{}{To je drsné. Jsem na mizinì.}
{173}{chip22}{Nedokážu ti ani popsat, jak dobøe se teï cítím. Takže co jsi to ode mì chtìl?}
{174}{}{Jak dám do pohybu tuhle loï?}
{175}{}{Víš, kde jsou mí lidé?}
{176}{}{Potøebuju nìjakou práci na poèítaèi.}
{177}{}{Teï zrovna nic, díky. Nashle.}
{178}{chip23}{Promluv si s kapitánem. Bydlí nahoøe v kapitánský kanceláøi.}
{179}{}{Díky. Další otázky...}
{180}{}{Dík. Mìj se.}
{181}{chip24}{Øíká se, že je unesli na západ, pøes oceán. Tvojí nejlepší nadìjí, jak se tam dostat, je rozbìhnout tenhle škopek.}
{182}{}{Díky. Další otázky...}
{183}{}{Dík. Mìj se.}
{184}{chip25}{Práce na poèítaèi? Když to nedokážeš získat od Shi nebo od Hubologistù, tak si promluv s Badgerem. Je to machr.}
{185}{}{Díky. Další otázky...}
{186}{}{Dík. Mìj se.}
{187}{chip26}{Do prdele. Promluv si s Hubologisty nebo Shi. Když je teï Badger mrtvej, tak mì nic jinýho nenapadá.}
{188}{}{Díky. Další otázky...}
{189}{}{Dík. Mìj se.}
{190}{chip29}{Parchante.}
{191}{chip30}{Budeš potøebovat prášky na bolest.}
{192}{chip31}{Hovado. Já ti ukážu.}
{193}{}{Vidíš plešatého pankáèe.}
{194}{}{Vidíš Chipa. Vypadá to, že hodnì trpí.}
{195}{}{Vidíš plešatého pankáèe. Drží se za bok a bolestí lapá po dechu.}
{196}{}{Tak dobøe. Promluvím si s Fungem.}
{197}{chip27}{Nìjaký novinky o mý slezinì?}
{198}{}{Jo a chtìl $1000... ale já jsem za tebe zaplatil.}
{199}{chip32}{Díky za pomoc, kámo.}
{200}{chip28}{Kámo, slyšel jsem, že jsi našel moji slezinu. Mluvil jsi s Dr. Fungem o jejím pøišití zpìt do mýho tìla?}
