{100}{}{Vidíš malého tlustého Shi mue.}
{101}{}{Vidíš Dr. Wong Yi Tze.}
{102}{}{Vidíš malého tlustého Shi mue.}
{103}{wong1}{Mohu vám s nìèím pomoci?}
{104}{}{Daghi nu?}
{105}{}{Kdo ty?}
{106}{}{Prı máte nìèí slezinu.}
{107}{}{Kdo jsi?}
{108}{}{Co tady dìláš?}
{109}{}{Ne, díky. To bude všechno.}
{110}{wong2}{Musím se pøiznat, e nehovoøím vaší øeèí. Zkuste si pohovoøit s Kenem Lee, ten rozumí mnoha rùznım jazykùm.}
{111}{}{Aha!}
{112}{wong3}{Jmenuji se Dr. Wong a jsem hlavní vìdec tohoto zaøízení.}
{113}{}{Další otázky, prosím.}
{114}{}{Dík. Mìj se.}
{115}{wong4}{Dohlíím na vìdecké pokusy, jen se zde provádìjí. Jsem také zodpovìdnı za poèítaèovou sí.}
{116}{}{Co plánujete?}
{117}{}{Jak získám pøístup do poèítaèové sítì?}
{118}{}{Mám další otázky.}
{119}{}{Aha. Nashle.}
{120}{wong5}{Hm, kdy vám øeknu naše plány, tak je poté bude znát kadı. Obávám se, e jsou prozatím tajné.}
{121}{}{Dobøe, dobøe. Mám další otázky.}
{122}{}{Dík. Mìj se.}
{123}{}{A co kdy vám strèím pistoli pod rypák a pøinutím vás mi to øíct?}
{124}{wong6}{Hm, nìkdo se nauèí, jak se do ní hacknout a nìkdo se spøátelí s jedním z mıch podøízenıch. O tom hackování samozøejmì ertuji. Pokud se o to pokusíte, pošlu nìkoho, aby vás zabil. (Usmìje se, aby dokázal, e to nemyslí vánì.)}
{125}{}{Vy byste mì opravdu nechal zabít?}
{126}{}{Take vám nebude vadit, kdy hacknu nìjakı poèítaè?}
{127}{}{Mám ještì nìjaké otázky.}
{128}{}{O tom nepochybuju. Nashle.}
{129}{wong7}{Pak bych to musel pokládat za hrozbu a varovat vás, e by taková èinnost mohla uškodit vašemu zdraví.}
{130}{}{Tak to vyzkoušíme.}
{131}{}{Jenom si dìlám legraci. Mám další otázky.}
{132}{wong8}{(Usmìje se.) Musíme si chránit vlastní èest, cizinèe.}
{133}{}{Eh, jasnì. Take vám nebude vadit, kdy hacknu nìjakı poèítaè?}
{134}{}{Jasnì. Mám další otázky.}
{135}{}{Tak to kadopádnì. Nashle.}
{136}{wong9}{Pokud se vám podaøí pøesvìdèit mé podøízené, aby to pro vás udìlali, tak klidnì, ale já to rozhodnì neudìlám.}
{137}{}{A co kdy vám strèím pistoli pod rypák?}
{138}{}{Skvìlé. No, mám další otázky.}
{139}{}{Hmm. Chápu. No, tak zatím.}
{140}{wong10}{Ach, ano! To vskutku mám. Chci si ji pøipravit s hráškem a dobrım Chianti.}
{141}{}{Vy ji poøád máte? To je dobøe. Chip ji potøebuje vrátit.}
{142}{}{To je lidská slezina, ty prašivej parchante!}
{143}{}{Víte doufám, e se to víno má podávat s játry místo sleziny?}
{144}{}{Víte, to je lidská slezina.}
{145}{wong11}{Kdo je ten Chip? Teï je to moje slezina a budu ji mít k veèeøi.}
{146}{}{Chip je pùvodní vlastník sleziny. Byl opilı a prodal ji Lao Chouovi.}
{147}{}{Potøebuje ji, aby pøeil, víte. Je z jeho tìla.}
{148}{}{V tom pøípadì vás kvùli ní nejspíš zabiju.}
{149}{wong12}{Dohoda je dohoda. Nemùe ji dostat zpìt. Lituji, ale dohodli jsme se spolu a to, e toho teï Chip lituje, ještì neznamená, e mùe z té dohody couvnout.}
{150}{}{[Více]}
{151}{}{To je lidská slezina? To mi Lao Chou neøekl!}
{152}{}{Hmm, v tom pøípadì na ní budu místo toho provádìt pokusy.}
{153}{}{Øeknìte vašemu kamarádovi, aby se pro ni bìhem zítøka stavil a já mu ji rád vrátím zpìt. Jenom doufám, e najdete zpùsob, jak mu ji voperovat vèas zpátky.}
{154}{}{Tak dobrá.}
{155}{wong15}{Hehe! Ano, také jsem ten starı film vidìl. Poèkat... co tím myslíte? Chcete øíct, e... ?}
{156}{}{Ano, je to lidská slezina.}
{157}{wong16}{Vlastnì mám vùèi tomu námitky. Nepodaøilo se vám dokázat, e máte dobrı charakter. Vskutku nevím, proè se s vámi vùbec bavím. Nashle.}
{158}{}{[KONEC]}
{159}{wong51}{Ajéje! Stráe! Je tady Lao wai vetøelec!}
{160}{wong17}{Nemáte pro mì jistá schémata?}
{161}{}{Ken Lee mi øekl, a vám je pøedám.}
{162}{}{Ano, ale co za to dostanu?}
{163}{}{Ne, ještì ne.}
{164}{wong18}{Promluvte si s Kenem Lee a on projedná vaši budoucnost. Dìkuji vám. Díky tìmto schématùm si budeme moci ovìøit nìkterá naše data z testù. Pøeji hezkı den.}
{165}{}{Vlastnì mám na vás další otázky.}
{166}{}{Zatím.}
{200}{}{Tato mrtvola byla pøechovávána v základnì Hubologistù. Myslím, e by se mohlo jednat o váš pohøešovanı exempláø z Xeno programu.}
{201}{wong19}{Ano, je to vskutku on! Mùj pøedchùdce do tohoto jedince vloil nemalé úsilí a byl velmi znepokojen, kdy se dozvìdìl, e se ztratil. I pøesto, e je ji pryè, moná budeme mít pro tohoto jedince nìjaké vyuití. Dìkuji vám za jeho navrácení.}
{202}{}{ádnı problém. Uvidíme se pozdìji.}
{203}{}{Tak moment. Nikdo neøekl, e to dìlám zadarmo.}
{204}{wong20}{Správnì. A také vás o to nikdo neádal. Bylo to jen z vaší vlastní vùle. Nyní bude ukradenı jedinec navrácen svım právoplatnım majitelùm a za to vám dìkujeme.}
{205}{}{To je sice hezké, ale já ho našel, take jestli ho chcete zpìt, tak vás to bude nìco stát.}
{206}{wong21}{Na tohle nemám èas...stráe!}
{207}{}{(Vypadá to, e zaène øvát, ale poté se uklidní.) Fajn. Tady je $500. Více ne adekvátní cena za nìco, co nám odjakiva patøilo. A teï odejdìte, mám práci.}
{208}{}{Bylo mi potìšením s tebou obchodovat. Nashle.}
{209}{}{A do prdele!}
{210}{}{Jdeme na to!}
{211}{}{Podaøilo se ti vrátit ztraceného jedince Xeno programu.}
{220}{wong23}{A kde tedy je? Zkoušíte na mì nìjakou hru?}
{221}{}{Promiòte, pokouším se nahromadit co nejvíce pøedmìtù, které unesu. Je to mùj koníèek.}
{230}{wong24}{Na tohle nemám èas. Vrate se, a budete mít toho jedince.}
{240}{wong25}{(Èichá nìco ve vzduchu.) Co je to za zápach? Jako nìjaké zkaené maso. (Podívá se na tebe a pozdvihne oboèí.)}
{241}{}{Jo, vy nejspíš cítíte tohle tìlo. Upøimnì ani nevím, proè ho vlastnì s sebou tahám.}
{242}{}{Hehe! (Vytáhneš rozpadající se mrtvolu.) Smrdící tìlo! Ty chtít?}
{250}{wong26}{Tak moment, to je ten jedinec z Xeno programu! Mùj pøedchùdce do nìj vloil nemalé úsilí a byl velmi znepokojen, kdy se dozvìdìl, e se ztratil. I pøesto, e je ji pryè, moná budeme mít pro tohoto jedince nìjaké vyuití. Dìkuji vám.}
{251}{wong27}{Ne, já nechci... tak moment, to je ten jedinec z Xeno programu! Mùj pøedchùdce do nìj vloil nemalé úsilí... (Všimne si tvého prázdného vırazu.) Ehm. Chci øíct, dìkuji vám za to tìlo. Dobrá práce. Další u nenoste, tohle mi staèí. Nashle!}
{252}{}{Pa pá!}
{253}{}{Já hromadit vìci. Já ukrıt to.}
{300}{}{Co se stalo mezi vámi a Dr. Shengem?}
{310}{wong28}{Jak víte o Dr. Shengovi? Eh, no to je jedno. Dr. Sheng Ming byl vıteènı, avšak vcelku nepøíjemnı mu, kterı byl mım pøedchùdcem. Jeho vıznam ji zde není pøíliš zásadní.}
{311}{}{Take pokud pro vás není dùleitı, tak proè by *mì* to mìlo zajímat? Chci se ještì na nìco zeptat.}
{312}{}{Co se s ním stalo?}
{320}{wong29}{Co se s ním stalo? Myslím, e se zbláznil. Bìhem svıch experimentù narazil na nìco, co bylo vskutku mimoøádné, to uznávám, ale zároveò také extrémnì nebezpeèné a navíc to vùbec nesouviselo s politikou Shi. Ale to Dr. Shenga nezajímalo. Svım vıtvorem se stal posedlı a jeliko byly jeho experimenty shledány jako pøíliš nebezpeèné, aby se v nich pokraèovalo, tak se rozhodl, e je bude provádìt jinde. Odešel ve svém volnu a u se nikdy nevrátil. Poté jsem pøevzal jeho pozici.}
{321}{}{Jaké experimenty Dr. Sheng provádìl? A co pøesnì byl ten jeho velikı objev?}
{322}{}{Take kde je Dr. Sheng teï?}
{330}{wong30}{Jako vìdec respektuji vaši zvídavou náturu. Nicménì se obávám, e se s vámi nebudu dìlit o tajemství Shi, cizinèe.}
{331}{}{Take kde je Dr. Sheng teï?}
{332}{}{Fajn, nechte si ty vaše úasné tajnosti. Já mám taky svá tajemství. Lepší, ne si vùbec dokáete pøedstavit.}
{340}{wong31}{(Zdvoøile se usmìje.) To urèitì máte. A teï kdy mì omluvíte, mám ještì spoustu práce. Hezkı den.}
{341}{}{[KONEC]}
{350}{wong32}{Dr. Sheng byl asi jeden den eskortován na jih. Zøídil si sídlo v nìjakém opuštìném domì, pokud se nepletu. Mìl bıt pryè jen mìsíc, ale ta doba ji dávno uplynula a ještì jsme o nìm od té doby neslyšeli. Myslím, e ho buï zabili jeho vlastní stvoøení, nebo se stal obìtí nespoèetnıch nástrah pustiny.}
{351}{}{Jeden z vašich hlavních vìdcù je moná mrtvı a vám je to jedno? To po nìm nebudete ani pátrat?}
{352}{}{Myslím, e se po tom Dr. Shengovi zkusím podívat. Mùete mi dát jeho poslední známou pozici?}
{353}{}{No, tak to bychom mìli. Chci se ještì na nìco zeptat.}
{360}{wong33}{Omluvte prosím moji zdánlivou bezcitnost tıkající se této záleitosti, ale pravdou je, e Dr. Sheng tu nebyl pøíliš oblíbenı a myslím, e nikomu z nás ani trochu nechybí.}
{361}{}{Myslím, e se po tom Dr. Shengovi zkusím podívat. Mùete mi dát jeho poslední známou pozici?}
{362}{}{Aha. Chci se ještì na nìco zeptat.}
{370}{wong34}{To bych nejspíše mohl... musím pøiznat, e i já sám jsem docela zvìdav, co se s ním stalo. Ukate, vyznaèím vám na vašem mapovacím zaøízení jeho poslední známou pozici. Avšak musím vás varovat, e to bude nejspíše velice nebezpeèné, i kdy v pustinì je to samozøejmì vdy nebezpeèné. Kadopádnì pokud najdete nìco zajímavého, urèitì mì informujte.}
{371}{}{Díky, to udìlám. Nashle.}
{372}{}{Chci se ještì na nìco zeptat.}
{380}{}{Dr. Sheng je stále naivu a vytvoøil nìjakı druh rostliny, která zakoøení v lidské mrtvole a pøevezme nad ní kontrolu.}
{390}{wong35}{Take jeho Xeno program byl do urèité míry úspìšnı. To je fascinující... a zároveò znepokojující. Jeho experimenty s vnímavımi rostlinami jsme ukonèili poté, co jsme pøišli o jednoho technika. Domníval jsem se, e se stal obìtí svıch vlastních stvoøení poté, co odešel, aby mohl pokraèovat ve svém vızkumu. Podaøilo se mu nad nimi pøevzít nìjakou kontrolu?}
{391}{}{Jo, nìkteøí se zdají bıt poslušní. Dokonce mu øíkají 'pane.'}
{400}{wong36}{Hmm... pokud by nìjakım zpùsobem vytvoøil celou armádu tìchto rostlinnıch pøíšer, nevìstilo by to pro Shi nic dobrého. Doufal jsem, e k tomu nebude muset dojít, ale zdá se, e nemáme na vybranou a budeme muset zlikvidovat Dr. Shenga vèetnì jeho experimentù. Jeliko vám vìøí natolik, e vám umoní se k nìmu pøiblíit, jste nejlepší kandidát pro tuto práci. Dokáete nìco takového udìlat? Samozøejmì dostanete náleitou odmìnu.}
{401}{}{Bude mi potìšením. Ten chlap i celá ta jeho èinnost mì dìsí.}
{402}{}{O jaké odmìnì se tu bavíme?}
{403}{}{Nemám zájem. Dr. Sheng je váš problém, tak si s ním poraïte vy.}
{410}{wong37}{Shi vám budou za tuto slubu velmi vdìèní. A bude Dr. Sheng i všechny jeho vıtvory zlikvidovány, ohlašte se mi a dostanete svoji odmìnu.}
{411}{}{[KONEC]}
{420}{wong38}{To nechám na vás. Poskytneme vám zbranì, zásoby, nebo peníze. Mùete se rozhodnout, a svùj úkol dokonèíte.}
{421}{}{Tak dobøe. Udìlám to.}
{422}{}{Nemám zájem. Dr. Sheng je váš problém, tak si s ním poraïte vy.}
{423}{}{Tak dobøe. Udìlám to. Ale ještì ne pùjdu, Dr. Sheng mì poádal o pøedání tohoto vzorku rostliny. Øíkal, e by vám to mìlo pomoct s vaším cílem vytvoøit rostlinu odolnou proti radiaci.}
{430}{wong39}{Tak dobøe. Postaráme se o ten problém sami, ale bude to muset poèkat, jeliko v této chvíli nemáme ádné zdroje, které bychom mohli postrádat. Doufejme, e u nebude pøíliš pozdì ve chvíli, kdy budeme schopni zasáhnout. Pokud mezitím zmìníte názor, informujte mì prosím.}
{431}{}{S tím nepoèítejte. Nashle.}
{432}{}{Budu o tom pøemıšlet. Nashle.}
{433}{}{Uvidíme. Chci se ještì na nìco zeptat.}
{440}{wong40}{Pøedpokládám, e si stále stojíte za svım, e? Pomùete nám zlikvidovat Dr. Shenga a jeho vıtvory?}
{441}{}{Ne, vlastnì se vás chci na nìco zeptat.}
{442}{}{Tak dobøe, oddìlám ho pro vás.}
{443}{}{Udìlám to, ale ne zadarmo. Øíkal jste pøedtím nìco o odmìnì?}
{450}{wong41}{Naši zvìdové nás informovali, e byl Dr. Sheng a jeho experimenty zlikvidováni. Taková škoda úasné mysli... nicménì si teï mùete vyzvednout svoji odmìnu. Máte zájem o zbranì, zásoby, nebo peníze?}
{451}{wong42}{Naši zvìdové nás informovali, e byl Dr. Sheng a jeho experimenty zlikvidováni. Taková škoda úasné mysli... jsme vám vdìèní i pøesto, e jsme vás nikdy o nic takového nepoádali. Za vaši snahu si mùete vyzvednout odmìnu. Máte zájem o zbranì, zásoby, nebo peníze?}
{452}{}{Vezmu si zbranì.}
{453}{}{Zásoby se vdycky hodí.}
{454}{}{Dejte mi peníze.}
{455}{}{Nechte si svoji odmìnu. Udìlal jsem to jen proto, protoe to bylo správné.}
{460}{wong43}{Tady máte. (Pøedá ti rùzné zbranì silného kalibru.)}
{461}{}{[KONEC]}
{470}{wong44}{Tady máte. (Pøedá ti rùzné zásoby.)}
{471}{}{[KONEC]}
{480}{wong45}{Tady máte. (Pøedá ti $5000.)}
{481}{}{[KONEC]}
{490}{wong46}{Shi si cení vaší pomoci. A teï mám spoustu práce. Hezkı den.}
{491}{}{[KONEC]}
{500}{}{Ale ještì ne pùjdu, Dr. Sheng mì poádal o pøedání tohoto vzorku rostliny. Øíkal, e by vám to mìlo pomoct s vaším cílem vytvoøit rostlinu odolnou proti radiaci.}
{501}{}{Dr. Sheng mì poádal o pøedání tohoto vzorku rostliny. Øíkal, e by vám to mìlo pomoct s vaším cílem vytvoøit rostlinu odolnou proti radiaci.}
{502}{}{Dr. Sheng mì poádal o pøedání tohoto vzorku rostliny jako dárek, ale musím vás varovat, je naplnìn jeho sérem vnímání. Nevím, co to má zpùsobovat, ale vím urèitì, e nic dobrého pro Shi.}
{510}{wong47}{Zajímavé. (Vezme si vzorek a nìkam ho uloí.) Mùj tım a já ho pozdìji prozkoumáme. Nemùu øíct, e vìøím jakémukoliv daru od Dr. Shenga, ale myslím, e je zde alespoò teoretická šance, e bude uiteènı. Uvidíme. Pokud u nic nepotøebujete, tak bych se rád vrátil ke své práci.}
{511}{wong48}{Zajímavé. (Vezme si vzorek a nìkam ho uloí.) Mùj tım a já ho pozdìji prozkoumáme. Nemùu øíct, e vìøím jakémukoliv daru od Dr. Shenga, ale myslím, e je zde alespoò teoretická šance, e bude uiteènı. Uvidíme. Ale myslel jsem, e chcete Dr. Shenga zlikvidovat a ne bıt jeho kurır. V kadém pøípadì bych se rád vrátil ke své práci.}
{512}{}{Vlastnì se vás chci ještì na nìco zeptat.}
{513}{}{Sbohem.}
{514}{}{Ve skuteènosti nebylo tak úplnì jednoduché pro vás ten vzorek získat. Myslím, e by si to zaslouilo odmìnu.}
{520}{wong49}{Opravdu? Shi po vás ten vzorek nepoadovali, ale pokud si myslíte, e si vaše skutky zaslouí odmìnu, tak myslím, e bychom toto mohli postrádat. (Pøedá ti Super Stimpak.) A teï u se opravdu musím vrátit zpìt ke své práci.}
{521}{}{Vlastnì se vás chci ještì na nìco zeptat.}
{522}{}{Dík. Mìj se.}
{523}{}{Opravdu? Tomu øíkáte odmìna? Budu vás mlátit tak dlouho, dokud z vás nevypadne nìco cenného.}
{530}{wong50}{(Vezme si semeno.) Dìkuji vám, ihned se toho zbavím. (Povzdechne si.) Vìdìl jsem, e se Dr. Sheng pomátl, ale netušil jsem, e zajde a tak daleko a pokusí se zabít své vlastní lidi. S tím se musí okamitì nìco udìlat.}
{531}{}{Souhlasím. Je to úplnı blázen.}
{540}{wong52}{*svírání srdce* Ááá.}
{541}{wong53}{Uch.}
{542}{}{Dr. Wongu!}
{600}{}{Podaøilo se ti zlikvidovat Dr. Shenga pro Shi.}
{601}{}{Podaøilo se ti pøedat vzorek rostliny Dr. Wongovi.}
{602}{}{Podaøilo se ti zavradit Dr. Wonga.}
