{100}{}{Vidíš inspirující pár vyznávající fyzické a psychické zdraví.}
{101}{}{Vidíš Juana Cruze a Vikki Goldmanovou, dvì velice známé filmové hvìzdy z New Rena.}
{102}{}{Vidíš tmavovlasého mue a blonïatou enu. Oba jsou velmi atraktivní. Vyzaøují ze sebe neodolatelné charisma.}
{103}{vaj1}{On: Ahoj! Já jsem Juan Cruz! Ona: A já Vikki Goldmanová! Oba: Jsme celebrity! A oba dva schvalujeme Hubologii! Oba: Pamatuj prosím, e jakákoliv podobnost mezi námi, lidmi nebo institucemi, a u ivımi nebo mrtvımi, je èistì náhodná.}
{104}{}{He? Klus? Vykid?}
{105}{}{Celebrity? Co z vás dìlá celebrity?}
{106}{}{Podobnost? Co tím myslíte?}
{107}{}{Chci bıt Hubologista. Jak se k vám mùu pøidat?}
{108}{}{Poslyš, Vikki, Dave H. tì miluje.}
{109}{}{Paráda. U musím jít.}
{110}{vaj2}{On: Ubohé dítì pustiny. Ona: Nepomohlo by tøeba srovnání? On: Ano. Ty. Chceš podstoupit srovnání?}
{111}{}{Jo!}
{112}{}{Ne!}
{113}{vaj3}{Ona: Doufám, e to pomohlo. Hodnì štìstí na cestách!}
{114}{}{Ahoj!}
{115}{}{Opravdu to pomohlo!}
{116}{vaj4}{On: Pokud nechceš pøijmout naši pomoc... Ona: ...pak ti nemùeme pomoci. Sbohem.}
{117}{}{Èau!}
{118}{vaj5}{On: Vidíš? Vìdomosti Hubu opìt pøedvedly svoji cenu!}
{119}{}{Mám nìjaké otázky.}
{120}{}{Diky! Nashle!}
{121}{vaj6}{Ona: Byli jsme souèástí filmového prùmyslu v New Renu. Natoèili jsme stovky filmù, z nich se mnohé staly klasiky, jako tøeba "Top Bun," "Pikantní Podnik," a "Bouølivé Sny". Díky tomu jsme celebrity.}
{122}{}{On: Ale jakoto èlen tohoto prùmyslu to jistì víš.}
{123}{}{Koneènì si mùu spojit jména s tváøemi.}
{124}{}{Koho zajímá, e se k nim HLÁSÍTE? Copak nemùu uèinit vlastní rozhodnutí?}
{125}{}{Aha. Mám na vás další otázky.}
{126}{}{Díky, nashle.}
{127}{vaj8}{Ona: Ale ano, samozøejmì e mùeš uèinit vlastní rozhodnutí. On: A v Hubovì poslední knize se mùeš doèíst, jak uèinit to PRAVÉ rozhodnutí!}
{128}{}{V jeho poslední knize? On není mrtvı?}
{129}{}{"Pravé rozhodnutí?" No jasnì. A co tøeba svobodná vùle?}
{130}{}{To zní skvìle. Jak se k vám mùu pøidat?}
{131}{}{Jistì. Mám další otázky.}
{132}{}{Jasnì. Nashle.}
{133}{vaj9}{On: Další otázky? V tom pøípadì máme odpovìdi! Samozøejmì poskytnuté Velkım Kolem.}
{134}{}{Jak se k vám mùu pøidat?}
{135}{}{Co z vás dìlá celebrity?}
{136}{}{Copak nemùu uèinit vlastní rozhodnutí místo toho, aby za mì rozhodovali celebrity?}
{137}{}{Jak se k vám mùu pøidat?}
{138}{}{Poslyš, Vikki, Dave H. tì miluje.}
{139}{}{Ne, ádné další otázky.}
{140}{vaj10}{Ona: (Prázdnı chladnı pohled.) On: Dìkujeme ti.}
{141}{}{Eh... mám nìjaké otázky.}
{142}{}{To bude ode mì všechno! Zatím!}
{143}{vaj11}{On: Mrtvı? Hehe! Moná. My si ale myslíme, e srovnal všechny svoje neurodyny a šel následovat Hvìzdného Otce. Ona: Intenzivnì vyuíváme jeho poznámky na papírcích a stìí èitelné rukopisy, abychom šíøili Hubova slova. On: Napøíklad jsme našli útrek, na kterém se píše: "2 tucty vejcí/mléko/toaleák". To jsou oèividnì vıznamná slova. Lid se o tom musí dozvìdìt.}
{144}{}{Eh... jasnì. Mám další otázky.}
{145}{}{Jenom proto, e si nìjakı magor nìco poznamenal, tak cítíte potøebu VŠECHNO zveøejnit?}
{146}{}{Ano! A ije Hub! Vidím svìtlo! Jak se k vám mùu pøidat?}
{147}{}{Jasnì. Nashle.}
{148}{vaj12}{On: Ano. Nìkteøí si mohou myslet, e se podobáme jistım lidem. Ona: Ale pravdou je, e je to jen èistì náhoda.}
{149}{}{Ach tak. No, tím se všechno vysvìtluje. Poslyšte, mám další otázky.}
{150}{}{Chápu. Zatím.}
{151}{vaj13}{Ona: Samozøejmì e máš svou svobodnou vùli. Máš monost nechat své neurodyny naplnit špínou svìta. On: Máš volbu ít bezradostnì a bezvıznamnì jako krysa. Oba: Nebo se mùeš dozvìdìt o smyslu ivota díky Velkému Kolu.}
{152}{}{Neurodyny? Co jsou zaè?}
{153}{}{To zní skvìle. Jak se k vám mùu pøidat?}
{154}{}{Hmm. Myslím, e budu radìji ít jako krysa.}
{155}{}{Jasnì. No, u musím bìet.}
{156}{vaj14}{Ona: Ty se opovauješ nazıvat Huba (A ije jeho vize.) magorem? Tady? V pevnosti oddané jeho uèení? On: Vypadni odsud. Jestli s nìkım odsud po cestì promluvíš, nebudeme mít slitování. Nevìøící. Oba: O dalšího nevìøícího ménì.}
{157}{}{V tom pøípadì udìlám první krok já. Vdycky jsem toti nenávidìl vaše filmy. Uvidíme, jak umíte zahrát mrtvé scény.}
{158}{}{Vaše filmy jsou pìknej brak. Sbohem.}
{159}{}{Èau.}
{160}{vaj15}{Ona: Neurodyny jsou podstatou duší znièenıch ve Velké Válce, které zneèišují tvou duševní podstatu a snaí se tì svést z cesty. On: Jestli chceš vìdìt více o naší vıuce, budeš muset navštívit náš kostel.}
{161}{}{Ano, to zní úasnì.}
{162}{}{Slyšel jsem, e je tohle jen sci-fi, ale nevìdìl jsem jak moc. Hub musel bıt opravdu magor.}
{163}{}{No, opravdu mì moc zajímá, co se nauèím. Poèítejte se mnou.}
{164}{}{Hmm. Ne, teï ne. Ale mám další otázky.}
{165}{}{Eh... musím jít. Nashle.}
{166}{vaj16}{On: To je od tebe velmi pozitivní myšlení. Ona: Velmi osvícené. On: Nabízíme naše názory lidem... a pokud naše sláva pøitáhne více vìøících, milerádi toho vyuijeme.}
{167}{}{Mám další otázky.}
{168}{}{Chci se k vám pøidat.}
{169}{}{Chápu. No, zatím.}
{170}{vaj17}{On: No, to je velmi prosté. Dáme ti tento informaèní holodisk. Ona: ...podíváš se na krátkı film... On: ...a poté si pùjdeš promluvit s AHS-7! Ona: Snadné, e ano?}
{171}{}{Pojïme na to.}
{172}{}{Myslím, e na to nejsem pøipraven.}
{173}{vaj18}{Ona: Na to máš samozøejmì právo. On: A já doufám, e pochopíš, e se nemùeš potulovat po naší základnì. Ona: Take radìji odejdi... stráe tì pravdìpodobnì zastøelí, pokud se tu budeš poflakovat.}
{174}{}{No páni, díky moc. Nejdøív dostanu nabídku k pøijetí a kdy odmítnu, tak mì zastøelíte? To se vám teda povedlo.}
{175}{}{V tom pøípadì nejdøív zastøelím já vás.}
{176}{}{Padám odsud.}
{177}{vaj19}{On: Toto je tvá poslední šance zmìnit své rozhodnutí. Ona: Nechceme, aby se ti stalo nìco zlého.}
{178}{}{Jdi se vycpat.}
{179}{}{Fajn. Jak se k vám mùu pøidat?}
{180}{}{Nìco zlého se brzy stane VÁM.}
{181}{}{Ne. Myslím, e to risknu. Zatím.}
{182}{vaj20}{On: Udìlali jsme pro tebe vše, co jsme mohli. Ona: Hodnì štìstí na cestách.}
{183}{}{Èau!}
{184}{vaj21}{Ona: Dave? Ten poèítaèovı geek? On: Haha! Taková nicka! Vikki je moje, jen moje... v ádném pøípadì se... promiò, èelím negativní energii. Mám nejspíš zneèištìné neurodyny. Ona: (Šeptá ti.) Myslím, e je Dave roztomilı, ale nic s ním nemùu mít, kdy je Juan poblí. On: Uf. Neurodyny u jsou zase èisté.}
{185}{}{Dobøe, mám další otázky.}
{186}{}{To u bude všechno. Nashle.}
{187}{vaj22}{Ona: Nebylo to a tak zlé, e ne? On: Teï si jdi promluvit s AHS-7 a poté se z nás stanou soudruzi v Hubologii. Ona: Jsem tak vzrušená! On: Získávání novıch rekrutù mì vdycky vzruší. Ona: Ach, miláèku... On: Ach, zlato...}
{188}{}{Asi se vrátím pozdìji.}
{189}{vaj23}{On: Pøíliš pozdì. Ona: U jsi zavázanı.}
{190}{}{[KONEC]}
{191}{vaj24}{On: Udìlal jsi ivotní rozhodnutí. Ona: A bohuel to bylo špatné rozhodnutí. Oba: Stráe! Stráe!}
{192}{}{Zatracenì.}
{193}{}{On: Zdravím, }
{194}{}{Take co mám teï jako Hubologista dìlat?}
{195}{}{Mùu s vámi nìkdy nìco podniknout?}
{196}{}{To bude nejspíš všechno. Zatím!}
{197}{}{}
{198}{}{}
{199}{vaj26}{On: Mùeš si promluvit s Harry Rocketem na povrchu. Tøeba potøebuje nìjakou pomoc. Ona: Nebo si promluv s AHS-7 nebo AHS-9. Ti vìtšinou o nìèem vìdí. On: Nebo mùeš sledovat vysílání modliteb. Ona: Nebo mùeš zpùsobit rozbroje mezi nepøáteli Kola.}
{200}{}{Díky. Mùu s vámi nìkdy nìco podniknout?}
{201}{}{Díky. To bude nejspíš všechno.}
{202}{vaj27}{Ona: Je nám líto... protoe Hvìzdnı Otec ví, e jsi roztomilı... ale nejspíš to nepùjde. On: Ale lichotíš nám! Ona: Moná bychom nìkdy mohli jít do New Rena a natoèit spolu film.}
{203}{}{Aha, tak dobøe. Co jiného mùu jako Hubologista dìlat?}
{204}{}{Aha, tak dobøe. Zatím.}
{205}{vaj28}{Ona: Lhaní je pro tvé neurodyny špatné. On: To je pravda. Ona: A proto musím bıt upøímná a øíct ti, e nejsi pøitalivı. On: Ale i pøesto tì milujeme jako kamaráda a následovníka Hubu!}
{206}{}{Páni, díky. Take co jiného mùu jako Hubologista dìlat?}
{207}{}{Jo, jasnì. [Zamumlat] Kreténi.}
{208}{vaj30}{Vítejte, noví rekruti!}
{209}{vaj31}{Já jsem Vikki Goldmanová!}
{210}{vaj32}{A já Juan Cruz!}
{211}{vaj33}{Jsme celebrity, jak jistì víte.}
{212}{vaj34}{Myslíme si, e je Hubologie cestou budoucnosti.}
{213}{vaj35}{My VÍME, e je Hubologie cestou budoucnosti.}
{214}{vaj36}{Dokáu usmait brouky pouhou myšlenkou!}
{215}{vaj37}{Vypadám ve staniolové èepici opravdu dobøe!}
{216}{vaj38}{Moná, kdy budete tvrdì pracovat na optimalizaci svého ducha, budete se k nám moci pøidat.}
{217}{vaj39}{To bychom uvítali.}
{218}{vaj40}{Ano. Neustále hledáme pøátele...}
{219}{vaj41}{...pokud jsou ochotni optimalizovat svého ducha.}
{220}{vaj42}{A pokud jsou natolik vysoce postavení jako my.}
{221}{vaj43}{Jsme AHS-5.}
{222}{vaj44}{Jednoho dne z vás mùe bıt také AHS-5.}
{223}{vaj45}{Kdy pøispìjete hodnì penìz, mùete bıt AHS-5 ještì døíve.}
{224}{vaj46}{Ale nemyslete si, e vás chceme jen pro peníze.}
{225}{vaj47}{Ne, my vám chceme POMOCI.}
{226}{vaj48}{A o tom všem je Hubologie.}
{227}{}{[Potlesk]}
{228}{}{. Doufám, e jde tvé osvícení dobøe. Ona: Vkládáme do tebe... veliké... nadìje.}
{229}{vaj49}{Lekce 1: Zde je vìènost, naše Velké Kolo. (Na nìco ukáe.) A tady jsme my. (Na nìco ukáe.) Nyní jen musíme urazit dlouhou cestu, abychom se mohli setkat s našimi hvìzdnımi bratry.}
{230}{}{Sakra, tak to budeme potøebovat opravdu hodnì bot.}
{231}{vaj29}{On: Teï si jdi promluvit s AHS-7 a poté se z nás stanou soudruzi v Hubologii! Ona: Jsem tak vzrušená! On: Získávání novıch rekrutù mì vdycky vzruší. Ona: Ach, miláèku... On: Ach, zlato...}
