{100}{}{Vidíš arogantního Shi gangstera.}
{101}{}{Vidíš Lo Pana, despotického a bezcitného mue.}
{102}{}{Vidíš Shi gangstera v hedvábném obleèení. Jeho ruce jsou mozolnaté a tvrdé. Vypadá nebezpeènì a zle.}
{103}{lopan1}{Co chceš?}
{104}{}{Daggle aggle aggle!}
{105}{}{Kdo ty?}
{106}{}{S kım jsi to bojoval?}
{107}{}{Kdo jsi?}
{108}{}{Chci se nauèit bojovat jako ty. Nauè mì to.}
{109}{}{Chci tì vyzvat na souboj.}
{110}{}{Zapomeò na to.}
{111}{lopan2}{Táhni odsud, idiote. Nemám ti co øíct.}
{112}{}{GRR!}
{113}{lopan3}{Jsem Lo Pan. Nejlepší bojovník ve mìstì kromì Dragona. Ale jednoho dne zemøe a a se tak stane, zaènu svùj styl uèit i ostatní.}
{114}{}{Ty uèit mì!}
{115}{}{Dík.}
{116}{lopan4}{Chceš se uèit? Myslíš, e na to máš? Uvidíme.}
{117}{}{[KONEC]}
{118}{lopan5}{Uèit tì? To si nemyslím. Vypadáš a pøíliš sebejistì. Vypadni.}
{119}{}{Co to...?}
{120}{lopan6}{Hele podívejte, idiot. Nechci s tebou mluvit. Jdi pryè.}
{121}{}{He...}
{122}{lopan7}{To byl Dragon. Je to padavka, kterı podporuje slabé.}
{123}{}{Lidi jsou ovce. Mìl bys slouit jen sám sobì.}
{124}{}{Ty jsi mi ale nìjakı zlı.}
{125}{}{Chápu. Mám další otázky.}
{126}{lopan8}{Zlı? Tìko. Jenom chytrı. Jdi radìji navštívit Dragona, pokud tì tak strašnì zajímá konat lidem dobro. Má rád prostoduché slabochy, jako jsi ty.}
{127}{}{[KONEC]}
{128}{lopan9}{Ano, to bych mìl. A taky to dìlám. Bohuel mi v cestì pøekáí Dragon. Jsme si pøíliš rovni v souboji proti sobì. Potøebuju nìkoho schopného, aby mi pomohl.}
{129}{}{Já jsem ten nìkdo.}
{130}{}{Chápu. No, mám další otázky.}
{131}{}{Chápu. No, zatím.}
{132}{lopan10}{Opravdu? Umíš bojovat mu proti mui jenom pìstmi a kopy bez zbroje a beze zbranì?}
{133}{}{Umím, ale proè bych mìl?}
{134}{}{To zní fér. Jak bude ta zkouška probíhat?}
{135}{}{Aha. Tak v tom pøípadì musím jít.}
{136}{lopan11}{Protoe jinak mì rolnící proklejí a bude mnohem tìší je vydìsit a porazím Dragona.}
{137}{}{Chápu. Zaèneme tu zkoušku.}
{138}{}{Chápu. Mám další otázky.}
{139}{}{Jasnì. Zatím.}
{140}{lopan12}{Chceš se mnou bojovat na smrt, nebo chceš jenom zjistit kdo je lepší?}
{141}{}{A do konce. Mám na tebe.}
{142}{}{Jenom zkoušku schopností. Nechci tì zabít.}
{143}{}{Ani jedno. Zapomeò na to.}
{144}{lopan13}{Skvìlé. Doufám, e u máš pøipravenı hrob. Poslal tì Dragon?}
{145}{}{Ano, dìlám to pro Shi.}
{146}{}{Ne. Dìlám to, protoe si myslím, e jsi hajzl.}
{147}{lopan14}{Aha, take tvrïák, jo? Napøed se utkáš s mımi mui a potom uvidíme, jestli jsi hoden bojovat se mnou.}
{148}{}{[Zaèít]}
{149}{lopan15}{Jsem Lo Pan. Jsem také "úhlavní nepøítel" Dragona. Nechápu proè trvá na tom, aby mìl úhlavního nepøítele. Bojuji stejnì dobøe jako on a myslím si, e je slabomyslnı a umoòuje ostatním ít ve svém stínu. Jsme nepøátelé, protoe bojujeme stejnım stylem a ten, kdo zvítìzí, pøevezme tradici.}
{150}{}{Nejsem úplnì nejhorší v pìstním souboji. Nechceš si mì vyzkoušet?}
{151}{}{Zajímavé. To musí bıt opravdu prospìšné. Mám další otázky.}
{152}{}{Dík. Mìj se.}
{153}{lopan16}{Moná jsem hajzl, ale nikdo nemùe øíct, e se nezastávám svıch lidí. Teï tì to bude poøádnì bolet.}
{154}{}{[KONEC]}
{155}{lopan17}{Potom jsi hlupák a mizera, kterı skáèe jak nìkdo jinı píská. Budu se smát a zemøeš.}
{156}{}{[Zaútoèit teï ve zbroji a se zbranìmi]}
{157}{}{[Vstoupit do ringu, odloit zbroj a zbranì a bojovat holıma rukama]}
{158}{lopan18}{Dobøe. Aspoò jsi svım vlastním pánem. Opravdu si troufáš bojovat bez zbroje a beze zbraní?}
{159}{}{[Zaútoèit teï ve zbroji a se zbranìmi]}
{160}{}{[Vstoupit do ringu, odloit zbroj a zbranì a bojovat holıma rukama]}
{161}{lopan33}{Beee, ovce, beee! Bì zpátky k tìm svım zahalenım pánùm. Nemám ti u co øíct.}
{162}{}{[KONEC]}
{163}{lopan19}{Neøíkal jsem ti, e si máš o svıch vıèitkách svìdomí promluvit s Dragonem? Ten ti bude naslouchat. Já ne. Teï odejdi.}
{164}{}{[KONEC]}
{165}{lopan20}{Musím pøiznat, e jsi ještì lepší bojovník ne já. Nechceš zkusit porazit Dragona?}
{166}{}{Ano. Udìlám to teï hned.}
{167}{}{To fakt není mùj boj.}
{168}{}{Jistì, ale mám ještì nìjaké otázky.}
{169}{lopan21}{Ne, to není. Ale Dragon mì stále poráí. Jestli máš alespoò trochu odvahy, dostaneš ho. Stejnì jsem nikdy neoèekával hrdost od lao wai.}
{170}{}{Dobøe. Mám otázky.}
{171}{}{Jasnì, jak myslíš. Zatím.}
{172}{lopan22}{Právì jsem se vrátil. Nìjakı lao wai se snail ukrást naše tajemství. Dragon a já jsme ho sejmuli. Musím uznat, e nám to šlo spolu dobøe.}
{173}{}{Skvìle. Mám otázky.}
{174}{}{Vıbornì. Nashle.}
{175}{lopan23}{Dragon je mrtvı. Nemùu tomu uvìøit. Alespoò nám teï ty otravné tradice nepøekáí na kadém kroku. Díky.}
{176}{}{Skvìle. Mám otázky.}
{177}{}{Vıbornì. Nashle.}
{178}{}{Fajn. Udìlám to hned teï.}
{200}{}{Lo Pan odhalí tvùj zámìr a ty kolem nìj jenom proklouzneš.}
{201}{lopan34}{Podívej, nemám rád, kdy mi nìkdo bere vìci, take si jdi krást nìkam jinam. Teï odejdi.}
{202}{lopan35}{Vyzval jsem tì k odchodu, ne ke smrti. Co u.}
{203}{lopan24}{Zdá se, e u ode mì nepotøebuješ ádnı trénink.}
{204}{lopan25}{Pro dnešek je náš trénink u konce. Vra se zítra.}
{205}{}{Jsem Mistr Khung, tvá poslední zkouška.}
{206}{}{Jsem Imbot. Pøiprav se.}
{207}{}{Jsem Wejungh. Pøiprav se.}
{208}{}{Jsem Loopal. Dál se nedostaneš.}
{209}{}{Jsem Smitty. Je naèase, aby tì nìkdo porazil.}
{210}{}{Jsem Mistr Krall. To je tvùj konec.}
{211}{lopan36}{BOJ!}
{212}{lopan37}{Potøebuješ víc trénovat.}
{213}{lopan38}{Pøiprav se!}
{214}{}{Podaøilo se ti porazit Lo Pana v souboji na smrt. Z nìjakého dùvodu dnes vypadá slunce o nìco jasnìjší.}
{215}{lopan26}{U jsi porazil moje mue. Sloil jsi zkoušku. Jsi pøipraven bojovat s Dragonem.}
{216}{lopan27}{U jsi dost dobrı. Jdi se nauèit støílet nebo tak nìco.}
{217}{lopan39}{Zaèneme. Opakuj po mì.}
{218}{lopan40}{Pro dnešek je náš trénink u konce.}
{219}{lopan41}{Uèíš se rychle.}
{220}{lopan28}{U jsi porazil moje mue. Nikdo další s tebou nechce bojovat.}
{221}{lopan29}{Pomohl jsi mi, ani bys nìco tušil. Teï, kdy je Dragon mrtvı, u se nemusím øídit tìmi zastaralımi morálními tradicemi.}
{222}{}{Bylo mi potìšením. Zatím.}
{223}{}{Rádo se stalo. Nashle.}
{224}{}{Rádo se stalo. Mùu se ještì zeptat?}
{225}{}{Prosím. Já ptát?}
{226}{lopan42}{VYHRÁL jsi!}
{227}{lopan43}{PROHRÁL jsi!}
{228}{lopan44}{Další protivník!}
{229}{lopan45}{Hej, podívej, co jsem našel.}
{230}{lopan30}{Nejprve musíš prokázat, e to dokáeš. Postavím tì proti svım pìti bojovníkùm - postupnì. Kdy je porazíš, èeká na tebe tvoje poslední zkouška.}
{231}{}{Co to máš?}
{232}{}{To zní moc obtínì. Nashle.}
{233}{lopan31}{Budeš muset porazit mého vybraného áka. Nicménì ádnı z tìchto soubojù nebude na smrt... samozøejmì kvùli bezpeèí mıch muù. (zachechtá se)}
{234}{}{Jdeme na to!}
{235}{}{Vyøiï si to s Dragonem sám.}
{236}{lopan32}{(Lo Pan tì chvíli pozoruje a poté najednou rychle vymrští svoji pìst, která tì udeøí do nosu ještì døív, ne stihneš vùbec zareagovat.) Nejsi dost dobrı.}
{237}{}{Dobøe, ale mùu se na nìco zeptat?}
{238}{}{Fajn. Èau.}
