{100}{}{Vidíš Hubologistu v kápi. Vypadá trochu odlišnì ne ostatní.}
{101}{}{Vidíš AHS-7, druhého vùdce.}
{102}{}{Vidíš Hubologistu v kápi.}
{103}{ahs739}{Stráe! Vetøelec! Zabijte ho!}
{104}{ahs71}{Ty, co tady chceš?}
{105}{}{Aaagh! Nu! Nee!}
{106}{}{Mám dopis pro AHS-9 od Osvícené z NCR.}
{107}{}{Potøebuju si promluvit s Crockettem o nìjaké zbroji.}
{108}{}{Chci se tu porozhlédnout.}
{109}{}{Mám zájem se k vám moná pøidat.}
{110}{}{Kdo jsi?}
{111}{}{Pøišel jsem vás všechny zabít.}
{112}{ahs72}{Ach, ubohé dítì. Chceš podstoupit srovnání?}
{113}{}{Jo!}
{114}{}{Ne!}
{115}{ahs73}{Ubohé dítì. Ji srovnán, ale stále neschopen mluvení. Pojï dál.}
{116}{}{Dik!}
{117}{ahs74}{Pojï dál a vyhledej Juana a Vikki. Oni ti pomohou. Hodnì štìstí, dítì.}
{118}{}{Dik!}
{119}{ahs75}{::jeho hlas zvání:: V tom pøípadì nevidím jedinı dùvod, proè bych tì mìl pouštìt dál. Hezkı den.}
{120}{}{Hej!}
{121}{ahs76}{No dobøe, ale rychle. Je to opravdu, ale opravdu zaneprázdnìnı mu.}
{122}{}{Dobøe.}
{123}{ahs77}{Toto není místo pro veøejné exkurze. Hezkı den.}
{124}{}{[KONEC]}
{125}{ahs78}{Vıbornì! Pojï dál, pojï dál. Promluv si s Juanem Cruzem a Vikki Goldmanovou - jsou to sice celebrity, ale budou se s TEBOU bavit.}
{126}{}{Co jsou zaè?}
{127}{}{Ó! Celebrity!}
{128}{ahs79}{Jsem AHS-7, druhı vùdce této základny. Ne se zeptáš: AHS znamená Srovnanı Hledaè Hubu, co znamená, e jsem oèistil sedm úrovní neurodynù ze své duše. Díky tomu jsem osvícenìjší a jsem blíe støedu pohybu Velkého Kruhu, ne jsi ty. A to znamená, e mi øekneš, co tu chceš. Hned teï.}
{129}{}{Mám dopis pro AHS-9 od Osvícené z NCR.}
{130}{}{Potøebuju si promluvit s Crockettem o nìjaké zbroji.}
{131}{}{Chci se tu porozhlédnout.}
{132}{}{Mám zájem se k vám moná pøidat.}
{133}{}{Pøišel jsem vás všechny zabít.}
{134}{ahs710}{Jsou to hvìzdy z New Rena. Pochopili pravdu naší doktríny a pøišli oèistit své neurodyny.}
{135}{}{Kde je najdu?}
{136}{}{No, zapomeò na to. Jdu pryè.}
{137}{ahs711}{Najdeš je v modlitebnì, kde ukazují našim nováèkùm a špinavcùm, jak pøínosné je bıt Hubologistou.}
{138}{}{No tak u mì pus dovnitø!}
{139}{}{Na to si udìlám vlastní názor. Pus mì dovnitø.}
{140}{}{Zapomeò na to. Mizím odsud.}
{141}{ahs712}{Á, ty u jsi mluvil s Juanem a Vikki. Pøipojíš se tedy k našim pøátelùm v hledání osvícení Velkého Kruhu?}
{142}{}{Ach ano. Ano, ano, ano.}
{143}{}{Jasnì.}
{144}{}{Ne, teï ještì ne. Mùu se vrátit pozdìji?}
{145}{}{Myslím, e nemám zájem. Promiò.}
{146}{}{Ani náhodou. Váš šílenı kult by zaslouil vyhladit.}
{147}{ahs713}{::usmìje se:: Nebudeš toho litovat. Staneš se souèástí naší komunity. Á... ty jsi èlovìk, kterı umí pouívat zbranì. Chceš je pouít ve slubì Velkému Kruhu?}
{148}{}{Ano.}
{149}{}{Moná pozdìji.}
{150}{ahs714}{Neotálej pøíliš dlouho ne se vrátíš s odpovìdí. Tvoje neurodyny budou zneèišovány víc a víc, dokud nezahájíme oèistnı proces.}
{151}{}{Rozmyslel jsem si to. Pøidám se.}
{152}{}{ádnı problém. Popovídáme se pozdìji.}
{153}{ahs715}{Mùeš odsud bezpeènì odejít, poutníku, ale nedoporuèuji ti se sem vracet. Pokud nepracuješ s námi, pracuješ proti nám. A já bych tì velice nerad vidìl trpìt.}
{154}{}{Díky za obavy. Zatím.}
{155}{}{Myslím, e bych nebyl ten, kdo by trpìl. Zatím.}
{156}{ahs716}{Vyhladit? VYHLADIT? STRÁE! ZABIJTE NEVÌØÍCÍHO!}
{157}{}{[KONEC]}
{158}{ahs717}{Take... u jsi mìl dost èasu pøemıšlet o svém rozhodnutí. Pøidáš se k nám?}
{159}{}{Ano.}
{160}{}{Ne.}
{161}{}{Dej mi ještì chvíli.}
{162}{ahs718}{Nemáš víc èasu. Rozhodni se teï, špinavèe.}
{163}{}{Dobøe, pøidám se.}
{164}{}{Zapomeò na to. Nemám rád mocenskou vládu.}
{165}{ahs719}{Tyranští Shi soupeøí s naší mocí a vytváøejí zmatek mezi našimi bratry pomocí vlastního zpùsobu, jak ovlivnit neurodyny. Vìøíme, e kdy bude jejich Císaø mrtvı, spatøí omyly své cesty. Zabiješ pro nás Císaøe?}
{166}{}{Ano, udìlám to.}
{167}{}{Ne, Shi mi nikdy nic neudìlali.}
{168}{ahs720}{Tøeba si to ještì rozmyslíš. Pokud ano, dej mi vìdìt. Mùe ti Hub ještì s nìèím pomoci, rekrute?}
{169}{}{Ano, mám nìjaké otázky.}
{170}{}{No, momentálnì ne. Díky.}
{171}{ahs721}{Pøemıšlel jsi o pomoci v našem boji proti utiskovatelùm Shi? Hvìzdnı Otec ti dá poehnání, pokud se zúèastníš naší køíové vıpravy.}
{172}{}{Stále nevím, jestli to chci udìlat.}
{173}{}{Udìlám to.}
{174}{ahs722}{Moná mùu pomoct tvé utrápené duši. Co potøebuješ?}
{175}{}{Kde získám palivo pro tanker Poseidon?}
{176}{}{Kde najdu popis všech vırazù, o kterıch jsi mluvil?}
{177}{}{Kdy odlétá raketoplán?}
{178}{}{Kde je Crockett?}
{179}{}{Nic, díky. Nashle.}
{180}{ahs723}{Dej nám vìdìt, a ten úkol splníš.}
{181}{}{Dám. Mám ještì otázky.}
{182}{}{Jasnı. Nashle.}
{183}{ahs724}{Odstranil jsi císaøskou skvrnu z materiální reality?}
{184}{}{Ještì ne.}
{185}{}{Ano, AHS-7. U je mrtvı.}
{186}{ahs725}{Vùdcem tulákù na tankeru je nevyléèitelnı špinavec jménem Badger. Pokud bude mrtvı, pochopí všichni naši pozici. Odstraníš ho pro nás?}
{187}{}{Udìlám to.}
{188}{}{Nijak mi neublíil. Radìji ne.}
{189}{ahs726}{Take... odstraníš pro nás toho "Badgera"?}
{190}{}{Udìlám to.}
{191}{}{Ne, stále radìji ne.}
{192}{ahs727}{Odstranil jsi u "Badgera"?}
{193}{}{Ještì ne.}
{194}{}{Ano. Je po nìm.}
{195}{ahs728}{Jeho lidé by mìli uvítat Hub! Vstøíc lepším zítøkùm! Tvé sluby zasluhují pochvalu!}
{196}{}{Díky! Mám další otázky.}
{197}{}{Všechno dìlám jen pro Kolo. Sbohem.}
{198}{}{Vlastnì tì teï zabiju taky.}
{199}{ahs729}{Teï, kdy je raketoplán naplnìn palivem, èekáme pouze na pokyn od Velikého a Strašlivého AHS-9 a poté mùeme odstartovat.}
{200}{}{To urèitì mùeme. Mám nìjaké otázky.}
{201}{}{Dík. Mìj se.}
{202}{ahs730}{O ádném nevím, kromì vzácného paliva, které potøebujeme k odletu našich hvìzdnıch bratrù na planetu Quetzel. Moná mají nìjaké Shi?}
{203}{}{Eh. Mám další otázky.}
{204}{}{Jo, moná.}
{205}{ahs731}{Vím, e Shi mají velké zásoby paliva. Moná bys jim ho mohl ukrást.}
{206}{}{Dobrı nápad. Mám ještì další otázky.}
{207}{}{Moná. Díky.}
{208}{ahs732}{Staèí pouít holodisk, kterı ti dali Juan a Vikki. V nìm najdeš slovníèek.}
{209}{}{Díky. Další otázky?}
{210}{}{Díky.}
{211}{ahs733}{A AHS-9 obdrí svou vizi od Hubu, odejdeme a pøipojíme se k nìmu v nebeské slávì!}
{212}{}{Jasnì, chvála Kruhu nebo tak nìco. Mám další otázky.}
{213}{}{Velmi informativní. Díky.}
{214}{ahs734}{Vìtšinou je ve své laboratoøi, kde pracuje na zpùsobu, jak zlepšit naše tìla a naše duše.}
{215}{}{Díky. Chci se zeptat na nìco jiného.}
{216}{}{Díky.}
{217}{ahs735}{Ne se opravdu staneš jedním z nás, musíme provést poèáteèní zeta scan - srovnání. Jsi pøipraven na scan?}
{218}{}{Ne! ádnı scan!}
{219}{}{Jistì. Jdeme na to.}
{220}{ahs736}{Bez scanu se k nám nemùeš pøidat. Víš urèitì, e chceš odmítnout?}
{221}{}{Naprosto. Nechci se nechat upravovat vašimi stroji.}
{222}{}{Aha, tak dobøe. Oskenujte mì.}
{223}{ahs737}{Odstranili jsme nìkteré tvé neèisté neurodyny. Nyní jsi klasifikován jako AHS-1. Jsi pøipraven pøidat se k našemu vznešenému cíli?}
{224}{}{Ach ano.}
{225}{}{Ne. Teï u nechci.}
{226}{ahs740}{Lekce 1: Zde máme vìènost. Tady je Quetzel. (Na nìco ukáe.) A zde jsme my. (Na nìco ukáe.) Teï se jen musíme vydat na velmi dlouhou cestu, abychom se tam dostali.}
{227}{}{Sakra, tak to budeme potøebovat opravdu hodnì bot.}
{228}{}{Mùu o tom ještì pøemıšlet?}
{229}{ahs738}{Zase ty? Co chceš?}
{230}{}{Mám ještì nìco udìlat?}
{231}{ahs741}{Tvá pøítomnost zde je neádoucí. Prosím, odejdi.}
