{100}{}{Vidíš ženu s ustaraným výrazem v oblièeji.}
{101}{}{Vidíš Suze.}
{102}{}{Vidíš ženu s ustaraným výrazem v oblièeji.}
{103}{suze9}{Ááááá! Pomóc!}
{104}{suze10}{Zachraò mì! Prosím!}
{105}{suze11}{Snaží se mì zabít!}
{106}{suze12}{Prosím! Oni mì zabijou!}
{107}{suze13}{Zastav je! Ááááá!}
{108}{suze1}{Poslal tì Badger? Vìdìla jsem, že to udìlá. To se mi ulevilo.}
{109}{}{Aáááá.}
{110}{}{Co jsi tam dole dìlala?}
{111}{}{Jo. Pojï za mnou.}
{112}{suze2}{Ach, ty chudinko. Radiace a pustina nejsou moc pøíjemné, co? Doufám, že ti nìkdo pomùže.}
{113}{suze3}{Je to docela hloupé, vážnì. Jenom jsem to tam chtìla prozkoumat, protože mìl Badger práci, tak jsem šla dolù, ztratila se a najednou mì obklíèila monstra. Naštìstí si ale pak pøišel ty.}
{114}{}{Mám další otázky.}
{115}{}{Jo, naštìstí. Našla jsi tam nìco zajímavého?}
{116}{}{Jo, naštìstí. Pojïme.}
{117}{suze4}{Našla jsem místnost, ve které jsem byla. Taky jsem našla místnost, která vypadala jako skladištì paliva. Dál jsem se ale kvùli tìm obludám nedostala.}
{118}{}{Mám další otázky.}
{119}{}{Odkud jseš?}
{120}{}{Skvìle. To bude prozatím všechno.}
{121}{suze5}{Pocházím kousek na jih od Pohøebištì a Kráteru. Není to daleko od moøe. Dìlala jsem chùvu, ale pak dìti zmutovaly v monstra.}
{122}{}{Mám další otázky.}
{123}{}{Jak jsi potkala Badgera?}
{124}{}{Fascinující. To bude prozatím všechno.}
{125}{suze6}{Pøicestoval na jih a jednou pøišel do klubu, kam jsem chodívala. A když se mi pak rozpadl život, tak jsem si øekla, že tohle bude dobré místo kam jít.}
{126}{}{Mám další otázky.}
{127}{}{To bude všechno, díky.}
{128}{suze7}{Vdìèím ti za svùj život, takže ti odpovím na všechny tvoje otázky.}
{129}{}{Jóóóó.}
{130}{}{Co jsi tam dole dìlala?}
{131}{}{Našla jsi tam nìco zajímavého?}
{132}{}{Odkud jseš?}
{133}{}{Jak jsi potkala Badgera?}
{134}{}{To bude všechno. Nashle.}
{135}{suze8}{Mùj bože... Badger je mrtvý ... nevím co budu dìlat... nemám tu žádné pøátele... celá moje rodina je mrtvá... mùj bože...}
{136}{suze14}{Díky za pomoc. Pùjdu najít Badgera.}
