{100}{}{Vidíš ozáøeného ghoula s ustaranım vırazem ve tváøi.}
{101}{}{Vidíš ozáøeného ghoula Hanka, kterı pracuje v elektrárnì jako dìlník.}
{102}{}{Vidíš ozáøeného ghoula jak kontroluje nìjaké pøístroje.}
{110}{hank1}{Ahoj, já jsem Hank. Starám se o vnitøek jádra reaktoru. I kdy tu vìtšinou není moc práce.}
{111}{hank2}{Ahoj, rád tì zase vidím. Tak blízko jádra je pøíjemnì teplouèko, e jo? Vìtšinu hezounù to ale nezajímá.}
{112}{}{Ahoj Hanku. Potøebuju se dostat dovnitø do reaktoru.}
{113}{}{Hanku, mám od Harolda zprávu o chlazení. Mìl by ses na ni podívat. Tady je.}
{114}{}{Nazdar Hanku. Jenom procházím. Sbohem.}
{120}{hank3}{Hehe. Tak to bych ti neradil, hezoune. Usmaíš se na škvarek. Já mám teplo rád, ale tobì to fakt nedoporuèuju. Je tam fakt dost hic a taky radiace. Kvùli tomu hezouni, co postavili tohle místeèko, pouívali na údrbu robota.}
{121}{}{Robota?}
{122}{}{Aha, díky. Sbohem.}
{130}{hank4}{Uka, podívám se na to. Podle téhle zprávy je to chlazení dost pøedimenzované. Myslel jsem, e kdy ho vypnu, tak se mi to okamitì roztaví pod rukama, ale vidím, e asi ne. Radši bych to mìl jít hned vypnout.}
{131}{}{Podle té zprávy je naše chlazení zbyteènì úèinné. Radši bych ho mìl jít hned vypnout, co myslíš?}
{132}{}{Myslím, e máš pravdu, Hanku. Já u budu muset jít. Sbohem.}
{133}{}{Kdy o tom tak pøemıšlím, moná bys mìl chvilku poèkat. Pùjdu si ještì promluvit s Haroldem. Sbohem.}
{140}{hank5}{Jo, hezounci, co to tady postavili, se taky nechtìli usmait, tak sem dali robota. Je urèenı k tomu, aby provádìl bìnou údrbu. Ovládá se dálkovì z toho terminálu za mnou.}
{141}{}{Perfektní. To by se mi mohlo hodit.}
{142}{}{Na to se musím podívat. Sbohem.}
{150}{hank6}{Máš u sebe hezkou vìcièku. Pøesnì to, co potøebujeme.}
{151}{}{To mám radost. Chceš ji nainstalovat?}
{152}{}{Díky, taky se mi líbí. Sbohem.}
{160}{hank7}{Rád bych ti pomohl, ale opravdu nevím, jak nìco takového nainstalovat. Víš, já vìtšinou jenom pozoruju tyhle pøístroje. Ale zkus Festuse, je to náš génius pøes souèástky... zeptej se jeho.}
{161}{}{Kde toho Festuse najdu?}
{162}{}{A nešlo by to udìlat nìjak jinak?}
{163}{}{Dobøe. Sbohem.}
{170}{hank8}{Tak co øíkal Festus? Nainstaluje tu souèástku?}
{171}{}{A kde vlastnì je?}
{172}{}{A nešlo by to udìlat nìjak jinak?}
{173}{}{Ještì ne. Moná se do toho pustím osobnì. Sbohem.}
{180}{hank9}{Festus je stejnım smìrem, odkud jsi pøišel. Je v øídící místnosti. Nemùeš ho minout... je to smraïoch a ufòukanec, co sotva zvládá svoje nabubøelé ego. Ale moná ti pomùe.}
{181}{}{Díky. Sbohem.}
{190}{hank10}{No, pokud zvládneš ovládat robota, mùeš to nainstalovat i bez cizí pomoci. Nebo mùeš jít prostì dovnitø a nainstalovat to osobnì.}
{191}{}{Robota?}
{192}{}{Nainstalovat to osobnì?}
{200}{hank11}{Víš, poslední dobou nedìlá dobrotu. Poøád se nìjak pøehøívá. Ale my ho stejnì nepouíváme, take jsme se ani neobtìovali opravit jeho tepelnej štít. Jestli ale pøijdeš na jeho ovládací kódy a nebudeš ho moc honit, moná se ti ho podaøí donutit, aby udìlal to, co potøebuješ.}
{201}{}{Díky. Sbohem.}
{210}{hank12}{Díky za opravení reaktoru.}
{211}{hank13}{Jak to vypadá s tím chlazením?}
{212}{hank14}{Díky za pomoc.}
{220}{hank15}{Ještì jsem to nikdy neslyšel takhle vrnìt.}
{221}{hank16}{Pøede jako kotì.}
{222}{hank17}{Bìí jako za mlada.}
{230}{hank18}{Dr se dál a na nic nesahej.}
{231}{hank19}{Jak ses sem dostal?}
{232}{hank20}{Vra se zpátky tìma dveøma. Záøící díra, hezká-fakt hezká. Hehehe.}
{300}{}{Podaøilo se ti pøesvìdèit Hanka, aby spustil roztavení reaktoru.}
{900}{hank21}{Nevidíš, e nemám èas?}
