{100}{}{Vidíš neobvykle malého, staršího ghoula.}
{101}{}{Vidíš Lennyho, Haroldova asistenta.}
{102}{}{Vidíš malého, staršího ghoula. Vypadá zamyšlenì.}
{110}{lenny1}{Nazdar, jmenuju se Lenny. J-jak ti mùu p-pomoct?}
{111}{lenny2}{Ještì j-jednou nazdar. J-jak ti mùu pomoct?}
{112}{lenny3}{Doslechl jsem se, e jsi potomek Zakladatele. Víš, jednou jsem se se Zakladatelem setkal.}
{113}{}{Nazdar. N-nepøestávám se d-divit, j-jak moc se podobáš Zakladatelovi. C-co pro tebe m-mùu udìlat?}
{114}{}{Dìda? Jùùù.}
{115}{}{Co tady dìláš?}
{116}{}{Mám zranìní. Pomùeš mi?}
{117}{}{Jeden z mıch pøátel je zranìnı. Pomùeš mu?}
{118}{}{Moji pøátelé jsou zranìní. Pomùeš jim?}
{119}{}{Lenny, u jsi nìkdy slyšel o vìci zvané GECK?}
{120}{}{Ty ses setkal s mım pøedkem?}
{121}{}{Jen se tak dívám kolem. Sbohem.}
{122}{}{Mùeš mì ošetøit?}
{125}{lenny5}{Ano. Co potøebuješ?}
{126}{}{Myslím, e teï nepotøebuju nic.}
{130}{lenny6}{O-opouštìt svoji v-vesnici byla chyba. Teï j-jdi domù.}
{131}{}{Domù? Pa.}
{140}{lenny65}{B-bì radši domù.}
{141}{lenny66}{N-nemám na tebe èas.}
{142}{lenny67}{P-padej. Jdi pryè!}
{150}{}{G-GECK? Slyšel jsem, e jeden mìli ve Vault City. O jinım jsem nikdy neslyšel.}
{151}{}{Mám zranìní. Pomùeš mi?}
{152}{}{Jeden z mıch pøátel je zranìnı. Pomùeš mu?}
{153}{}{No, mùj pøedek Zakladatel øíkal, e Vault 13 nám jeden dluí. Musím ho najít.}
{154}{}{Myslím, e to bude asi všechno. Sbohem.}
{160}{lenny8}{N-no, pøevánì p-pomáhám H-Haroldovi. K-kdy se nìkdo zraní, tak mu p-pomùu.}
{161}{}{S èím pomáháš Haroldovi?}
{162}{}{Chci se ještì na nìco zeptat.}
{163}{}{Umíš léèit zranìní?}
{164}{}{Mám zranìní. Pomùeš mi?}
{165}{}{Jeden z mıch pøátel je zranìnı. Pomùeš mu?}
{166}{}{Budu na to myslet, a se zraním. Díky. Sbohem.}
{170}{lenny9}{U-uka. M-myslím, e ti dokáu p-pomoct.}
{171}{}{Bude mì to nìco stát?}
{172}{}{Díky, Lenny. Chci se ještì na nìco zeptat.}
{173}{}{Díky, Lenny. Sbohem.}
{174}{lenny10}{M-mùu ti p-pomoct, ale b-bude tì to s-stát $30. Z-za materiál.}
{175}{}{Myslím, e teï tvoji pomoc nepotøebuju. Sbohem.}
{180}{lenny11}{No, tvùj p-pøítel p-potøebuje malou p-pomoc. M-mùu mu p-pomoct.}
{181}{lenny12}{V-vypadá to, e jste se d-dostali do p-problémù. M-mùu vám pomoct.}
{182}{}{Bude mì to nìco stát?}
{183}{}{Díky Lenny. Chci se ještì na nìco zeptat.}
{184}{}{Díky Lenny. Sbohem.}
{185}{lenny13}{T-tvùj p-pøítel je zranìnı. D-dám ho d-dokupy za $30. P-poøebuju ty p-peníze na m-materiál.}
{186}{}{Lidi, co jste d-dìlali? V-vypadá to, e byste opravdu p-potøebovali vyléèit. Uzdravení všech tì b-bude stát $60.}
{187}{lenny15}{Tvùj p-pøítel je podle mì v poøádku.}
{190}{lenny16}{M-mno, ve skuteènosti jsem se se Z-zakladatelem a jeho partou pøímo osobnì n-nesetkal. Ale vidìl jsem je. Jednou. }
{191}{}{Ty jsi vidìl Zakladatele? Kde?}
{192}{}{Aha, chápu. No, musím nìkam jít, nìco zabít. Sbohem.}
{200}{lenny17}{No, p-pøed v-válkou jsem b-byl doktor.}
{201}{}{Pøed válkou? Ale to muselo bıt skoro pøed 160-ti lety.}
{202}{}{Aha. No, tím se všechno vysvìtluje. Díky. Sbohem.}
{210}{}{To je p-pravda. Zdá se, e nám g-ghoulùm d-darovala radiace delší ivot. Ale skoro všechno ostatní nám vzala.}
{211}{}{Co vám vzala?}
{212}{}{Všechno má oèividnì svoje pro i proti. Sbohem.}
{220}{lenny19}{N-no, a-ano. Vypadáme j-jako p-podìlanı z-zrùdy. N-nemáme -ádnou kùi, do háje.}
{221}{}{No, asi u jste zaili i lepší èasy.}
{222}{}{Jako skupina urèitì nepatøíte mezi ty nejkrásnìjší na téhle planetì. Sbohem.}
{230}{lenny20}{D-dalo by se to t-tak øíct. V-vymìnil bych všechny ty roky za to, abych b-byl zase n-normální èlovìk.}
{231}{}{No, moc velkou nadìji asi nemáš.}
{232}{}{To vìøím. Sbohem.}
{240}{}{Jsem si jistı, e bysme se dokázali z-zbavit pøebyteèné r-radiace a sami sebe vyléèit, ale to by se s námi ti h-hlupáci ve Vault City museli p-podìlit o svoji lékaøskou technologii.}
{241}{}{Oni vám nepomùou?}
{242}{}{Myslím, e u to nechci poslouchat. Sbohem.}
{250}{}{T-ty jsi byl ve Vault City, e? P-potom mi t-tedy øekni, jaké m-myslíš, e máme šance na to, aby nám ti pánbíèkáøi p-pomohli. T-to asi døív zamrzne p-peklo.}
{251}{}{To nerad slyším, ale asi máš pravdu. Chci se ještì na nìco zeptat.}
{252}{}{To nerad slyším. Sbohem.}
{260}{}{N-ne. -ivot je pøíliš krátkı... hehe... no, pro v-vìtšinu lidí... na to, aby se èlovìk r-rozèiloval nad prkotinama. Víš ty co? Všechno jsou to prkotiny. Máš to z-zadarmo.}
{261}{}{Díky Lenny.}
{270}{}{B-bylo t-to pøed mnoha lety. V místì zvaném N-necropolis. ilo tam spousta ghoulù. Jednoho dne jsem vidìl, jak nìkdo bìí mìstem.}
{271}{}{Bìí?}
{272}{}{Myslím, e u mám dost tvıch nejasnıch vzpomínek. Sbohem.}
{280}{}{Ano, bìí. Víš, my ghoulové u n-nemùeme moc bìhat. Take kdy jsem je vidìl, vìdìl jsem, e jsou odjinud. Bìeli tak blízko mì, e jsem se jich mohl skoro dotknout. Ké bych se byl bıval pøipojil k Zakladateli...}
{281}{}{Ty ses chtìl pøipojit k mému pøedkovi?}
{282}{}{No jasnì, mùj pøedek by urèitì dovolil takové ohyzdné zrùdì, jako jsi ty, aby se k nìmu pøipojil. Sbohem.}
{283}{}{Eh, no, strašnì rád si poslechnu celı pøíbìh, ale mám nìco na práci. Sbohem.}
{290}{lenny26}{Ano. M-mìl jsem ivotní šanci a zahodil jsem ji.}
{291}{}{Co tím myslíš?}
{292}{}{No, tak u to chodí. Sbohem.}
{300}{}{P-pozdìji jsem se d-doslechl, e Zakladatel opravil náš vodní systém. Z-Zakladatel nás zachránil, nás všechny. Rozumíš? Bylo mu jedno, e jsme ghoulové. To bylo poprvé, kdy na tom nìkomu nezáleelo. B-byli jsem znovu lidmi. Hodni záchrany.}
{301}{}{Mùj pøedek byl zakladatelem našeho kmene. Moji lidé si tohoto skutku váí.}
{302}{}{No, mì jde jen o záchranu mého kmene. Ostatní a se starají sami o sebe. Sbohem.}
{310}{}{P-pozdìji jsem se d-doslechl, e Zakladatel znièil zdroj armády m-mutantù. Z-Zakladatel nás všechny zachránil. Lidi i ghouly... mohl jsem toho bıt souèástí, ale chybìla mi o-odvaha. Nikdy jsem si to neodpustil.}
{311}{}{Jdu ve stopách svého pøedka. Nechtìl bys ještì jednu šanci? Pøidáš se ke mnì?}
{312}{}{Jsem si jistı, e ta práce, kterou mezi ghouly dìláš, má cenu a smysl. Jsem rád, e jsi mi vyprávìl o mém pøedkovi. Chci se ještì na nìco zeptat.}
{313}{}{No, spousta lidí je hluboko uvnitø zbabìlá. Není dùvod se za to nìjak zvláš stydìt. Jsi prostì slabı. Sbohem.}
{314}{}{Ta správná cesta èasto není úplnì jasná. My všichni jsme tu z nìjakého dùvodu. Díky, e jsi mi vyprávìl o mém pøedkovi. Sbohem.}
{320}{}{Jsem š-šastnìjší ne b-brahmíní bık na pastvinì plnı krav! B-bude mi ctí se k tobì p-pøidat. M-moná jsem starı a nemùu se p-pohybovat moc rychle, alespoò ne moc dlouho, ale urèitì tì mùu zafáèit, a to budeš p-potøebovat.}
{321}{}{Mám radost, e se ke mnì mùeš pøidat. Vím urèitì, e se tvé léèitelské schopnosti budou hodit.}
{322}{}{Hmm, mohlo by to bıt pøíliš nároèné pro takového staøíka. Myslím, e bys mìl zùstat tady. Promiò. Sbohem.}
{330}{lenny30}{Mám tu práci. N-nemùu jít s tebou.}
{331}{lenny77}{Vùbec n-nejsi jako tvùj pøedek. D-dìláš ostudu jeho p-památce.}
{332}{lenny78}{M-máš se o -ivotì ještì co uèit. N-nelíbí se mi tvoje ch-chování.}
{333}{}{Je mi líto, e se ke mnì nemùeš pøidat.}
{334}{}{Jeíš, èlovìk by si myslel, e kus hnijícího masa, jako jsi ty, bude skákat radostí, kdy dostane šanci vypadnout z tıhle záøící mìstskı umpy. Sbohem.}
{340}{lenny31}{P-pomáhám H-Haroldovi se správou mìsta. P-poøád je tøeba vyplòovat nìjaké p-papíry.}
{341}{}{Co jsi øíkal, e tady ještì dìláš?}
{342}{}{Myslím, e to bude všechno. Nashle.}
{350}{}{N-nemáš dost p-penìz... ale s-stejnì ti pomùu. N-nemùu vystát, kdy lidé t-trpí.}
{351}{}{Nevím, jak ti dostateènì podìkovat, Lenny. Ale potøebuju od tebe ještì nìjaké informace.}
{352}{}{Díky, Lenny. Máš to u mì. Sbohem.}
{360}{lenny33}{Je tu t-tolik l-lidí. U moji pomoc n-nepotøebuješ. Pøeju h-hodnì štìstí.}
{370}{}{Nikdy jsem si n-nemyslel, e se d-doèkám d-dne, kdy se b-budu stydìt za to, e jsem souèástí tvıch skutkù. Dìláš ostudu památce Zakladatele. Šupity, dupity, sbohem.}
{371}{}{Víš, m-myslel jsem si, e by m-mohlo bıt fajn s t-tebou c-cestovat, ale jsi nepøíjemnı a k-konfliktní jako brahmíní bık s k-kaktusem v zadku. A o moc líp t-taky n-nevoníš. Šupity, dupity, sbohem.}
{372}{}{Je mi líto, e odcházíš, Lenny.}
{373}{}{Nedokáeš se s tím vyrovnat, co? V tom pøípadì bys mìl radìji odtáhnout tu svoji na pùl shnilou prdel, ne si rozmyslím, jestli má cenu na tebe plıtvat náboje.}
{374}{}{*krk* Jo, jak myslíš. Asi máš na práci nìco jiného, jako tøeba trávit všechen svùj volnı èas vzpomínkami na to, jaké to bylo mít kùi, která nevypadá jako tøi mìsíce stará mrtvola na silnici. Vypadni odsud, ty zasraná zrùdo.}
{375}{}{Dobøe.}
{380}{}{C-co ch-chceš, abych u-udìlal?}
{381}{}{Lenny, já vím, e se snaíš, ale uhni mi prosím tì z cesty.}
{382}{}{Potøebuju, abys bojoval jinak, Lenny.}
{383}{}{Potøebuju, abys tu poèkal.}
{384}{}{Ranhojiè, uzdrav sa sám.}
{385}{}{Potøebuju vyléèit, Lenny.}
{386}{}{Potøebuju, abys uzdravil nìkteré naše pøátelé.}
{387}{}{Potøebuju, abys nás uzdravil.}
{388}{}{Jak to jde, veteráne?}
{389}{}{Teï u od tebe nic dalšího nepotøebuju, Lenny.}
{400}{}{Chceš, abych b-bojoval j-jinak?}
{401}{}{Chci, abys zmìnil rozestup.}
{402}{}{Chci, abys pouil svoji nejlepší zbraò.}
{403}{}{Chci, abys pouil svoji nejlepší zbroj.}
{404}{}{Chci, abys bojoval jinak.}
{405}{}{Zapomeò na to.}
{410}{}{J-jak chceš, abych byl d-daleko? Víš, e se mi špatnì d-dobíhá.}
{411}{}{Chci, abys zùstal poblí mì.}
{412}{}{Chci, abys zùstal støednì daleko.}
{413}{}{Chci, abys zùstal daleko.}
{414}{}{Potøebuju, abys šel na prùzkum.}
{415}{}{Zapomeò na to.}
{420}{}{C-co chceš, abych u-udìlal?}
{421}{}{Chci, abys teï bojoval defenzivnì.}
{422}{}{Potøebuju, abys bojoval normálnì.}
{423}{}{Potøebuju, abys bojoval agresivnì.}
{424}{}{Zapomeò na to.}
{430}{}{Tak p-pøeci jen se dá nauèit starého p-psa novım kouskùm. To bylo v-vzrùšo.}
{431}{}{P-prostì tomu n-nìjak n-nemùu pøijít na kloub.}
{432}{}{Dobøe.}
{440}{}{Aha, dobøe. P-poèkám tu, dokud se n-nevrátíš. N-nechám odpoèívat svoje bolavé k-klouby.}
{441}{}{Odpoèiò si, Lenny. Sbohem.}
{442}{}{Mìl bys tu poèkat. Jo a ještì jedna vìc...}
{443}{}{Zapomeò na to.}
{450}{}{M-musím sehnat v-vìtší b-bouchaèku.}
{451}{}{Pouij svoji nejlepší zbraò, Lenny.}
{461}{}{Oblékni si svoji nejlepší zbroj, Lenny.}
{462}{}{Lenny, a si oblékneš svoji nejlepší zbroj, budu od tebe potøebovat ještì nìco dalšího.}
{463}{}{Zapomeò na to.}
{470}{}{To je d-dobrı nápad. Øíkal j-jsem si, e b-bysme se mohli zastavit. J-jsem docela z-zranìnej.}
{471}{}{M-mìl bych se p-podívat na ty t-tvoje r-rány.}
{472}{}{Z-zdá se, e nìkdo p-potøebuje z-znovu sešít.}
{473}{}{Zaèni se sám léèit.}
{474}{}{Uzdrav se a potom budu od tebe ještì nìco potøebovat.}
{475}{}{Zaèni mì léèit, prosím.}
{476}{}{Uzdrav mì a potom budu od tebe ještì nìco potøebovat.}
{477}{}{Zaèni nás léèit.}
{478}{}{Uzdrav nás a potom budu od tebe ještì nìco potøebovat.}
{479}{}{Zapomeò na to.}
{480}{}{N-nemùu to u-udìlat. Nejsem ani trochu dobrı zvìd.}
{481}{}{Aha, dobøe. Tak nic.}
{490}{}{Budu se d-dret p-poblí.}
{491}{}{Zùstaò poblí, Lenny.}
{492}{}{Zùstaò nablízku a potom budu od tebe ještì nìco potøebovat.}
{493}{}{Zapomeò na to.}
{500}{}{H-hádám, e takhle n-nás tak snadno n-netrefí, co?}
{501}{}{Nebuï tak blízko, Lenny. Chci, aby nás nemohli tak snadno trefit.}
{502}{}{Nepøibliuj se tolik. Potøebuju od tebe ještì nìco dalšího.}
{503}{}{Zapomeò na to.}
{510}{}{Dobøe, b-budu stát o t-trochu d-dál. S-stejnì to vypadá, e chtìjí všichni z-zabít jenom tebe.}
{511}{}{Potøebuju, aby ses v zájmu své vlastní bezpeènosti drel zpátky. Nemá to absolutnì nic spoleèného s tím, jak smrdíš.}
{512}{}{Pøedtím, ne se rozestoupíme, budu potøebovat, abys pro mì ještì nìco udìlal.}
{513}{}{Zapomeò na to.}
{520}{}{Za ty roky j-jsem se o s-sebe nauèil d-docela dobøe p-postarat.}
{521}{}{Jen chci, abys byl opatrnı, a se dostaneme do boje.}
{522}{}{Chci se ujistit, e se ti nic nestane. Hergot, vdy ty jsi vlastnì staroitnost. Jo, vlastnì ještì jedna vìc...}
{523}{}{Zapomeò na to.}
{530}{}{To je jedinı m-monı zpùsob.}
{531}{}{Prostì bojuj tak, jak jsi zvyklı a bude to v pohodì.}
{532}{}{Uvolni se a bojuj normálnì. Jo a ještì jedna vìc...}
{533}{}{Zapomeò na to.}
{540}{}{To n-nemùu udìlat. U jen s-samotnı boj je asi tak všechno, co t-tyhle staré k-kosti zvládnou.}
{541}{}{Dobøe. Tak nic.}
{1000}{lenny35}{C-co ch-chceš, abych u-udìlal?}
{1100}{lenny36}{J-je mi fajn.}
{1200}{lenny37}{Jsem trochu z-zranìnı, ale mùu p-pokraèovat.}
{1300}{lenny38}{To je d-dobrı nápad. Øíkal j-jsem si, e b-bysme se mohli zastavit. J-jsem docela z-zranìnej.}
{1400}{lenny39}{Potøebuju ihned vyléèit, nebo u-umøu.}
{1500}{}{Aha, dobøe. P-poèkám tu, dokud se n-nevrátíš. N-nechám odpoèívat svoje bolavé k-klouby.}
{1600}{lenny41}{Dobøe.}
{1700}{lenny42}{Budu se d-dret p-poblí.}
{1800}{lenny43}{H-hádám, e takhle n-nás tak snadno n-netrefí, co?}
{1900}{lenny44}{Dobøe, b-budu stát o t-trochu d-dál. S-stejnì to vypadá, e chtìjí všichni z-zabít jenom tebe.}
{2000}{lenny45}{U máš h-hodnì l-lidí. U moji pomoc n-nepotøebuješ. Pøeju h-hodnì štìstí.}
{2100}{}{Nikdy jsem si n-nemyslel, e se d-doèkám d-dne, kdy se b-budu stydìt za to, e jsem souèástí tvıch skutkù. Dìláš ostudu památce Zakladatele. Šupity, dupity, sbohem.}
{2200}{lenny47}{N-nebyl jsem si j-jistej, jestli se v-vrátíš.}
{2300}{}{Proè poøád tak spìcháme?}
{2301}{}{Aha, promiò. Uhnu ti z cesty.}
{2302}{}{Honem, honem, honem. Dobøe, v pohodì, u jdu. Promiò, nechtìl jsem se ti plést do cesty.}
{2303}{}{Je mi líto, ale prostì se nemùu pohybovat rychleji. Uhnu se ti.}
{2304}{}{Aha, dobøe, odbelhám se ti z cesty.}
{2305}{}{Tak já se odbelhám sem.}
{2306}{}{Nechci ti pøekáet.}
{2307}{}{Och, promiò.}
{3000}{lenny69}{Kolem tebe se dìje moc špatnıch vìcí. Odcházím, ne se mi nìco stane.}
{3001}{}{Nebudu pomáhat vrahovi dìtí. Sbohem.}
{3002}{lenny70}{Tvoje ízeò po krvi mì dìsí. U s tebou dál nepùjdu.}
{3003}{}{Nechci mít nic spoleèného s otrokáøem. Sbohem.}
{3004}{}{Jsi zrádce! Kvùli tobì je teï naše elektrárna znièená. Nepomùu ti.}
{3005}{lenny71}{N-nechci s tebou m-mít nic s-spoleèného.}
{4000}{lenny48}{No dobøe, ale urèitì tady nechci zùstat sám.}
{4001}{lenny49}{Tak jo, kdy myslíš, e je to opravdu dobrı nápad.}
{4002}{lenny50}{No, nerad pouívám zbranì, pokud opravdu nemusím, ale myslím, e bych mohl pouít nù. S pistolí umím zacházet, alespoò jsem to umìl. Kdybych opravdu musel, myslím, e bych zvládl i samopal. Jen kdyby nebyly tak hluèné. Jsem doktor, ne bojovník.}
{4003}{lenny51}{Sákryš, snad to nebudu potøebovat.}
{4004}{lenny52}{No, nerad pouívám zbranì, pokud opravdu nemusím, ale myslím, e bych mohl pouít nù. S pistolí umím zacházet, alespoò jsem to umìl. Kdybych opravdu musel, myslím, e bych zvládl i samopal. Jen kdyby nebyly tak hluèné. Jsem doktor, ne bojovník.}
{5000}{lenny72}{Myslím, e m-mám zlomenou k-konèetinu.}
{5001}{lenny73}{Myslím, e j-jsem o-ozáøenı.}
{5002}{lenny74}{Myslím, e j-jsem o-otrávenı.}
{5100}{lenny75}{Je m-mi teï nìjak h-horko.}
{5101}{lenny76}{To je l-lepší.}
{6000}{}{Potøebuju od tebe odbornou radu, Lenny. Co víš o léèbì srdeèních potíí?}
{6001}{}{Mùeš mi øíct nìco o tìhlech pilulkách, doktore?}
{6010}{lenny53}{Co máš za p-problém? N-eselhavá ti snad s-srdce nebo jo?}
{6011}{}{Ne, jen mì zajímá, jestli by se dalo nìco udìlat pro Cassidyho.}
{6012}{}{Ne. Chystám se zabít jednoho vetchého staøíka a snaím se pøijít na nìco kreativnìjšího ne jen to, e se k nìmu pøiplíím zezadu a bouchnu nafouknutı pytlík.}
{6013}{}{Øeknìme, e mám vrozenou zvìdavost.}
{6020}{lenny54}{Hehe. Není tøeba bıt p-podrádìnı.}
{6021}{lenny55}{No, vìtšinou se to d-dìlá bìnımi záleitostmi jako je zdravá strava, n-nebrat tvrdé d-drogy a tak podobnì. A n-nedostávat se do stresovıch s-situací. V p-podstatì ít v-víc jako d-dùchodkynì a míò jako... no, my. Hehe. S-samozøejmì asi n-nejlepší by bylo, k-kdyby se ti p-podaøilo do nìj napìchovat k-kardiovaskulární r-regulátory nebo m-moná nìjaké v-vazodilátory.}
{6022}{}{Kardio co?}
{6023}{}{Hmm. Pilulky na srdce.}
{6030}{lenny56}{Tak se na to podíváme... (Lenny si mumlá nìco pro sebe pøi ètení štítku.)}
{6040}{lenny57}{Pilulky na srdce. Zdá se, e to, c-co dneska v-vyrábìj ve Vault City a NCR, se moc neliší od toho, c-co jsme pouívali t-tehdá pøed v-válkou. Silnı l-léky. Øekni mu, a b-bere ty p-pilulky a za chvíli bude m-mít srdce jako m-mutantí m-maratonec. A kdyby poslouchal svıho d-doktora a b-bral je p-pravidelnì, tak by mohl pravdìpodobnì brát i t-tvrdé drogy a n-nebát se toho, e mu s-srdce by jen jednou v-vynechá. Eh, teda n-ne e bych to samozøejmì d-doporuèoval. L-lékaøi by mìli vdycky d-doporuèovat zdravı zpùsob ivota a h-hodnì v-vlákniny, e?}
{6041}{}{Eh, jasnì. Díky, Lenny. Chci se ještì na nìco zeptat.}
{6042}{}{Nejsou nebezpeèné? Nemají nìjaké vedlejší úèinky?}
{6043}{}{Myslíš, e to Cassidymu pomùe?}
{6050}{lenny58}{M-mohlo by to bıt p-pøesnì to p-pravé pro nìj. Vlastnì si myslím, e t-to je ono. Ale m-mìl by si d-dát na pár vìcí p-pozor.}
{6051}{}{Napøíklad?}
{6052}{}{Vdycky je v tom háèek.}
{6060}{lenny59}{Nic, co by d-dìlalo nìjaké èasté p-potíe. Je známo, e tyhle pilulky zpùsobujou m-malátnost. A taky se n-nedoporuèuje je zapíjet g-grepovım d-dusem, i kdy to v tıhle d-dobì asi nebude m-moc velkı p-problém. L-ledae by to byly ty z-zelené h-hrudkovité vìci. Hmmm... (Lenny si poloí ruku na svoji bradu a zírá do vesmíru.)}
{6061}{}{Lenny?}
{6070}{lenny60}{P-promiò. Och! Ještì jedna d-dùleitá vìc. Pokud n-neplánuješ zemøít z-zcela n-nedùstojnım zpùsobem, tak je *v ádném pøípadì* n-nemíchej s p-povzbuzujícíma p-pilulkama z N-new Rena.}
{6071}{}{Povzbuzujícíma... pilulkama?}
{6072}{}{Špatnì spolu reagují?}
{6080}{lenny61}{Jojo. To kdy ti tvùj m-malej p-pìšák nechce stát v p-pozoru. O-odbornì se jim øíká "PDE-5 tlumící sloky", ale víš jak to dnes chodí a jak TO chodí v New Renu... kde jsem to pøestal?}
{6081}{lenny62}{Jojo. To kdy muùm nechce jejich m-malej p-pìšák stát v p-pozoru. O-odbornì se jim øíká "PDE-5 tlumící sloky", ale víš jak to dnes chodí a jak TO chodí v New Renu... kde jsem to pøestal?}
{6082}{lenny63}{To teda. Kdy se ti t-tyhle látky v tìle s-smíchaj, tak nastane velkı BUM! Srdce ti vybouchne jako k-krvavá jitrnice. Pamatuju se, jak jsem p-pitval hned nìkolik ubohejch chlapíkù, co z-zasévali oves a n-nemìli èas na to, aby si p-pøeèetli v-varovnı štítek.}
{6083}{}{Krvavá jitrnice?}
{6084}{}{Pane jo. To je dobré vìdìt. Díky moc, Lenny.}
{6090}{lenny64}{Och. Hehe. N-nejspíš existovala j-jenom p-pøed tvım narozením. Promiò. Mùu pro tebe ještì n-nìco udìlat?}
{6091}{}{No, kdy se tak ptáš...}
{6092}{}{Ne, to bude všechno. Díky, Lenny.}
