{100}{}{Vidíš nadprùmìrnì velikého ghoula.}
{101}{}{Vidíš Zomaka, známého také jako Nièitele.}
{102}{}{Vidíš velkého, statného ghoula v jeho oblièeji se odráejí známky prostoduché nadøazenosti pod ostøe svaujícím se èelem.}
{110}{zomak1}{Obroï se, kamaráde! Jsem Zomak. Nìkteøí mi taky øíkají Zomak Nièitel. Co tu dìláš?}
{111}{zomak2}{Obroï se, kamaráde! Co tu dìláš? Objasni úèel své cesty Zomaku Nièitelovi.}
{112}{}{Pøebroï se!}
{113}{}{Ook?}
{114}{}{Jen se tu tak rozhlíím.}
{115}{}{Chci se Obrodit.}
{116}{}{Asi jsem na špatném místì.}
{120}{zomak3}{Tak se dívej nìkam jinam, nebo ti Zomak ukáe cestu do nebes.}
{130}{zomak4}{Pak ho tedy musíš navštívit.}
{131}{}{Jeho? Kde je jeho, chci øíct on?}
{132}{}{Nejsem hoden ho navštívit. Sbohem.}
{140}{zomak5}{On je posel osvícení. Je to on, kdo slibuje Obrození všem, kteøí ho následují.}
{141}{}{No, brzy se mám Obrodit. Kde ho najdu?}
{142}{}{To mi pøipadá jako naprostá blbost. Mizím odsud.}
{150}{zomak6}{No, je tam vzadu... hele, kdo vlastnì jsi?}
{151}{}{Jenom poutník.}
{152}{}{Jsem Vyvolenı.}
{153}{}{Jsem tu kvùli Obrození.}
{154}{}{To je jedno. Jenom se ho musím zeptat na pár otázek.}
{160}{zomak7}{No, tak odsud hezky rychle vypadni.}
{161}{}{Eh, dobøe. Sbohem.}
{170}{zomak8}{Dobøe, v tom pøípadì... mùeš vstoupit. Je hned ve vedlejší místnosti. Nenech ho èekat.}
{171}{}{Nenechám. Jdu rovnou za ním. Sbohem.}
{172}{}{Pøijdu pozdìji. Sbohem.}
{180}{zomak9}{Radši odejdi. Vypadni odsud.}
{181}{}{Dobøe.}
{200}{zomak10}{Ano, všichni se mùete Obrodit uvnitø.}
{201}{}{Dobøe.}
{210}{zomak11}{Coo? Co tím myslíš? Nejsi ty blbec?}
{211}{}{Blbec?}
{220}{zomak12}{Vypadni odsud. Brain nemá èas na takovı blbeèky, jako jsi ty.}
{221}{}{Dobøe, u pùjdu.}
{230}{zomak13}{Tam dole kromì Brainova doupìte nic není. Jeíši, ty jsi ale blbec.}
{231}{}{Brain?}
{232}{}{Byl to jenom takovı test. Prošel jsi. No a teï mì pus dovnitø.}
{233}{}{Zdá se, e jsem se spletl. To musí bıt tou radiací. Sbohem.}
{240}{zomak14}{Hej. Eh, tady nic není. Vùbec nic. Take odsud hezky vypadni.}
{241}{}{Jsi si jistı, e tady nic není?}
{242}{}{Dobøe. Sbohem.}
{250}{zomak15}{Joo. Jsem si naprosto jistej. A teï odsud vypadni.}
{251}{}{No, kdy to øíkáš. Sbohem.}
{260}{zomak16}{Aha, hehe .. já to vìdìl. Noo, take, eh, prošel jsem? }
{261}{}{Samozøejmì, e jsi prošel. A teï mì pus dovnitø.}
{262}{}{Ne, neprošel jsi a proto to teï musím nahlásit.}
{270}{zomak17}{Tak dobøe. Mùeš vstoupit.}
{271}{}{Dobøe. Sbohem.}
{280}{zomak18}{Vidím, e máš znamení. Mùeš vstoupit.}
{281}{}{U jdu.}
{282}{}{Znamení?}
{283}{}{Tøes se znamení! Sbohem.}
{290}{zomak19}{Ano, posvátnı talisman Obrození. Obroï se, kamaráde! Obroï se!}
{291}{}{Jo, taky se pøebroï. Sbohem.}
{300}{zomak20}{Obroï se, bratøe. Mùeš vstoupit.}
{301}{zomak21}{Obroï se, sestro. Mùeš vstoupit.}
