{100}{}{Vidíš pøátelsky vypadajícího hubeného mue.}
{101}{}{Vidíš Chada, správce karavan.}
{102}{}{Vidíš hubeného mue, kterı pøedstírá úsmìv. Má na sobì nepopsatelné obleèení a vypadá, e ví, co dìlá.}
{120}{chad1}{Jak to jde, pøíteli? Co pro tebe mùu udìlat?}
{121}{chad2}{Víc otázek? Pokusím se na nì odpovìdìt, jak nejlíp dokáu.}
{122}{}{Všiváku prašivej!}
{123}{}{Kdo ty?}
{124}{}{Marcus se na tebe ptal.}
{125}{}{Mám dost dùkazù na to, abys byl zatèen za kráde penìz urèenıch pro Broken Hills. Máš to spoèítanı.}
{126}{}{Je tu dost dùkazù na to, abys byl zatèen za kráde penìz urèenıch pro Broken Hills. Naval $1000 a zajistím ti bezpeènı útìk z mìsta.}
{127}{}{Kdo jsi?}
{128}{}{Povìz mi nìco o tomhle místì.}
{129}{}{Nic. Nashle.}
{130}{chad3}{Podívejte, co nám sem pustina donesla! Promiò kámo, ale nemùu ti pomoct.}
{131}{}{Razim!}
{132}{chad4}{Jsem Chad.}
{133}{chad5}{Podívej, mám moc práce. Bì prosím otravovat nìkoho jiného.}
{134}{chad6}{Jsem správce karavan tohohle mìsta. Starám se o vımìnu na druhém konci obchodních cest. Posledních pár dní jsem se zamìøoval hlavnì na Gecko.}
{135}{}{To fajn!}
{136}{}{Chci pro tebe pracovat.}
{137}{}{To zní skvìle.}
{138}{}{To zní nudnì.}
{139}{}{Mám další otázky.}
{140}{}{Dík. Mìj se.}
{141}{chad7}{O Broken Hills? Dobrá... pøišel jsem sem pøed nìkolika lety. Dostal jsem práci u vetešníka Billa a vypracoval se a tam, kde jsem teï. Zodpovídám se sice Marcusovi a Billovi, ale jsem zodpovìdnı za chod mìsta.}
{142}{}{Mám další otázky.}
{143}{}{Èau.}
{144}{chad8}{Napøíklad?}
{145}{}{Má podezøení, e si pro sebe uléváš peníze, které jsou urèené pro Broken Hills.}
{146}{}{Vlastnì na nic. Sbohem.}
{147}{chad9}{Podívej, o tom já nic nevím a k smrti nesnáším, kdy mì nìkdo z nìèeho obviòuje. Radím ti, abys teï odešel.}
{150}{}{Jdu zjistit, jak to doopravdy je. Sbohem.}
{156}{chad10}{Promluv si s Billem. On ti pomùe.}
{157}{}{Mám další otázky.}
{158}{}{Dík. Mìj se.}
{159}{chad11}{Jo, taky e je. Asi by tì to ani nenapadlo, ale docela cestuju po svìtì... a øekl bych, e pøispívám tomuhle mìstu. Je to dobrej ivot.}
{160}{}{To zní skvìle. Taková práce by se mi líbila.}
{161}{}{No, ve skuteènosti to zní jako pìkná nuda.}
{162}{}{Mám další otázky.}
{163}{}{Èau.}
{164}{chad12}{Urèitì je to podstatnì víc vzrušující ne to, co dìláš se svım ivotem ty, kokote.}
{165}{}{No jasnì, jak myslíš. Mám další otázky.}
{166}{}{Hahahaha! Jasnì. Zatím, pako.}
{167}{chad24}{Jednou za to zaplatíš, ocasi.}
{168}{chad25}{Zmiz mi z oèí, hovado.}
{169}{chad26}{Pìknì jsi tu karavanu podìlal, pøíteli. Na peníze zapomeò.}
{170}{chad27}{Opravdu si tu karavanu neskuteènì zbabral, pøíteli. Hodnì štìstí s nìkım jinım z Broken Hills.}
{171}{chad28}{Dobrá práce. Tady máš svıch $200.}
{172}{chad29}{Padej odsud. Tvoji pomoc tady nepotøebujeme.}
{173}{chad30}{Mìj oèi na šopkách.}
{174}{chad31}{Budu tì krıt.}
{175}{chad32}{Nenech ty bastardy kolem tebe proklouznout.}
{200}{chad13}{Nevím o èem to mluvíš. Radím ti, abys do toho nešoural, nebo nìkoho nasereš. A teï odsud vypadni.}
{201}{}{Mám lepší nápad. Co kdybych tì místo toho umlátil k smrti?}
{202}{chad14}{Špatná odpovìï. Vypadá to, e sis zaèal se špatnım tıpkem.}
{203}{}{Fajn, sbohem.}
{204}{chad15}{Krucinál, vìdìl jsem, e to nebude trvat vìènì. (Rozhlédne se kolem a ztiší hlas.) Dobøe, poslouchej. Dr o téhle malé záleitosti hubu. Tady máš $1000. (Pøedá ti peníze.) A teï kdy mì omluvíš, musím u jít.}
{205}{}{[KONEC]}
{206}{chad33}{Pomoc! Máme tu zlodìje.}
{207}{}{}
{208}{chad16}{Co to!? Kdo sakra jsi?}
{209}{}{Já? Eh, jsem Víla Zubìnka. Jsem tu, abych ti pøinesla veliké bohatství.}
{210}{chad17}{No jasnì a já jsem Svatı Mikuláš. A teï mi øekni, kdo kurva jsi a proè jsi v mım domì?}
{211}{}{Fakt? Potkal jsem v New Renu tıpka, kterı taky tvrdil, e je Svatı Mikuláš.}
{212}{}{*Tupì zírá*}
{213}{}{(pokraèuješ) Jo a pak jsem mu povìdìl svùj ivotní pøíbìh o Arroyu...}
{214}{chad18}{Tak poslouchej, ty tvoje zasranı kecy jsou mi úplnì u prdele. Ty jseš urèitì ten chlápek, co èmuchá kolem a ptá se na chybìjící peníze z karavan.}
{215}{}{To je pravda. A jsem tu, abych získal poslední dùkaz, kterı potøebuju, abych tì dostal.}
{216}{chad19}{Fakt jo? Tak já ti pomùu. Ty dokumenty, které hledáš, jsou v kuføíku, kterı je zamèenı ve spodním šuplíku támhletoho prádelníku. Ale ty se ho nikdy ani nedotkneš, páè tì teï zabiju, ty jeden zkurvenej naivko. Nebıt tebe, mohl jsem odírat karavany ještì nìkolik dalších mìsícù. Ale ne, ty jsi sem musel pøijít a míchat se do vìcí, do kterıch ti kurva nic není. Tak a teï musím zmizet z mìsta, ale bude mi potìšením nechat po sobì tvoji mrtvolu.}
{217}{}{Chade, nikdo tady nemusí zemøít. Místo toho, abys udìlal nìjakou blbost, která tì mùe stát ivot, bys mìl vychladnout a potom si o tom promluvíme s Marcusem.}
{218}{chad20}{Myslíš, e jsem blbej? Ten velkej hnusnej èùrák by mì hned zavøel. Ne, obávám se, e tady urèitì nìkdo umøe. A já to nebudu!}
{219}{}{Jsem tu pro poslední dùkaz v kauze ulévání penìz z karavan.}
{220}{}{Fakt jo?... já vìdìl, e jsem tì u nìkde vidìl.}
{221}{chad22}{Dobøe, dobøe. Ke všemu se pøiznávám. Nechci kvùli tomu umøít. Øekni Marcusovi, e se vzdám bez boje.}
{222}{}{Tak jo, ale ani se nehni. Jdu pro Marcuse.}
{300}{}{Dovolil jsi Chadovi opustit mìsto.}
{400}{chad34}{Nech mì bıt.}
{2040}{chad23}{Krucinál, vìdìl jsem, e to nebude trvat vìènì. (Rozhlédne se kolem a ztiší hlas.) Dobøe, poslouchej. Dr o téhle malé záleitosti hubu. Tady máš za to $1000. (Pøedá ti peníze a ty mu pøedáš jeho kuføík.) A teï kdy mì omluvíš, musím u jít.}
