{100}{}{Vidíš velmi silného supermutanta. Vypadá znudìnì.}
{101}{}{Vidíš Francise, zápasníka v páce.}
{102}{}{Vidíš velmi silného supermutanta. Je obleèenı do èerné kùe a má znudìnı vıraz ve tváøi.}
{103}{franc1}{Chceš s nìèím pomoct?}
{104}{}{Ook! Ook! Eep orp ook!}
{105}{}{Gdo ty?}
{106}{}{Nazdar, kámo. Kdo jsi?}
{107}{}{Co se dá v tomhle mìstì dìlat?}
{108}{}{Pøipraven na zápas v páce, elezná tykvo?}
{109}{franc2}{Kámo, netuším, co se mi snaíš øíct. Promiò.}
{110}{franc3}{Jsem Francis. Šampión v páce v tomhle mìstì. Vsadil jsem se, e mì nikdo neporazí.}
{111}{franc4}{Jsem Francis, pamatuješ? Šampión v páce v tomhle mìstì. Vsadil jsem se, e mì nikdo neporazí.}
{112}{}{Já tebe porazit! Já! Já!}
{113}{}{Vsadím se, e jsi nemìl pøíliš vyzyvatelù.}
{114}{}{Vsadím se, e tì porazím.}
{115}{}{Jsi a tak dobrı, jo?}
{116}{franc5}{Co se tady dá dìlat? No, tak podívej... máme tady salón, dùl, rafinérii a karavanu. Na zábavu moc èasu není, ale kdy u nìjakı je, tak chlastáme. A taky pracujeme na vztazích mezi lidmi a mutanty.}
{117}{}{Jak... vzrušující.}
{118}{}{Dobøe, díky.}
{119}{}{Na vztazích lidí a mutantù? Co tím myslíš?}
{120}{franc6}{Jsem vdy pøipraven. Dáme se do toho?}
{121}{}{Ne, musím se nejdøív uzdravit.}
{122}{}{Eh, ne.}
{123}{}{Jasnì e jo.}
{124}{franc7}{(Zmìøí si tì pohledem a prozkoumá tvé svaly.) Myslím, e ne, kámo. Jen bych mrhal svım èasem. Odprejskni.}
{125}{franc8}{Ty si myslíš, e mì pøemùeš, jo? Tak dobøe. Kdy vyhraješ, dám ti energo pìst. Kdy vyhraju já, budeš mi celou noc slouit. Chceš se do toho pustit hned, nebo si potøebuješ odpoèinout?}
{126}{}{Odpoèinout! Odpoèinout!}
{127}{}{Teï. My teï!}
{128}{}{Chci si nejdøív trochu odpoèinout.}
{129}{}{Rozdáme si to hned teï.}
{130}{}{Vlastnì s tebou u nechci zápasit.}
{131}{franc9}{Pøesnì tak. Zdá se, e v tıhle bohem zapomenutı pustinì není nikdo, kdo by se mì odváil vyzvat.}
{132}{}{To je škoda. Jestli nìkoho najdu, pošlu ho za tebou. Nashle.}
{133}{}{To, e jsi silnı, ještì neznamená, e jsi taky chytrı. Pamatuj na to.}
{134}{franc10}{Kámo, jestli se ti tady nelíbí, mùeš jít nìkam jinam.}
{135}{franc11}{ádnı problém. Jestli nìco potøebuješ, zeptej se barmana Phila nebo nìkoho jiného.}
{136}{franc12}{Kámo, tak chceš si dát páku, nebo ne? Nemíním ztrácet èas s posmìškama a zbabìlcema.}
{137}{}{Jo, jasnì. Pojïme na to.}
{138}{}{Ne. Myslím, e ne.}
{139}{franc13}{A budeš pøipraven, tak se vra. Budu nìkde poblí.}
{140}{franc14}{Vypadni odsud, nebo mi hrkne v bednì a rozbiju ti drku.}
{141}{franc15}{Vzdáváš to, co? To jsem si myslel. Zbabìlèe.}
{142}{}{Dobøe, dobøe, tak teda jo.}
{143}{}{Jo, jasnì. Zatím.}
{144}{franc16}{Kámo, to je poprvı, co mì nìkdo spravedlivì porazil. Vyhrál jsi. Tady máš. Dobrá práce.}
{145}{franc17}{Prohrál jsi. ádnı pøekvapení. Jdeš se mnou domù.}
{146}{franc18}{Nìco ti øeknu, kámo, ještì nikdy jsem nepotkal nìkoho tak dobrıho. Vyuij svoji sílu ve prospìch dobra. Uij si tu rukavici!}
{147}{franc19}{Nemáš dost? Chceš ještì? Stejná sázka?}
{148}{}{Jo, pojïme na to.}
{149}{}{Ne, promiòte.}
{150}{franc20}{Slyšel jsem o tobì. Se šmejdama se nekamarádím.}
{151}{franc21}{Kámo, díky za záchranu našeho mìsta. Pojï, koupím ti drink.}
{152}{franc22}{Nazdárek, hrdino!}
{153}{franc31}{Šmejde! Chcípni!}
{154}{franc23}{Moná sis všimnul, e ve mìstì ijou lidi i mutanti. Snaíme se tu ít v míru. Bohuel se ale vdycky najde nìkdo, kdo se nás pokouší proti sobì poštvat. Náš šéf Marcus byl spoluzakladatelem mìsta. Chceš slyšet víc?}
{155}{}{Jasnì, pokraèuj.}
{156}{}{Ne, ani ne.}
{157}{}{Já si upøímnì myslím, e vy mutanti jste šmejdi a lidi, co s vámi spolupracují, jsou zrádci.}
{158}{franc24}{Nìkdy mám tady o ty lidi starost... pro nìkterı je hroznì tìkı pøekonat strach. Øíká se, e je na spadnutí nìjakej prùser, ale asi je to jenom blábol.}
{159}{}{Dík. Mìj se.}
{160}{franc25}{Tak dobøe. No, a budeš chtít zase nìjakı informace, tak víš, kde mì najdeš.}
{161}{}{Samozøejmì. Díky. Nashle.}
{162}{franc26}{Opravdu? To je úchvatnı názor. Škoda e jsme nerozdrtili tvoji vesnici, kdy jsme ještì ovládali pustinu. Zmiz mi z oèí, èerve.}
{200}{}{[KONEC]}
{201}{}{Èau.}
{202}{}{Dík. Mìj se.}
{203}{}{[Více]}
{204}{}{Samozøejmì. Díky. Nashle.}
{300}{franc27}{Kámo, nejsem si jistej, jestli dokáeš pochopit moji nabídku. Vra se, a budeš mít víc zkušeností.}
{301}{}{Vidíš velmi silného supermutanta. Je obleèenı do èerné kùe a má znudìnı vıraz ve tváøi. Zdá se, e mu z kapsy trèí nìjaká obøí rukavice.}
{302}{}{Všechno tì bolí a vypadá to, e ti po setkání s Francisem zbyl suvenır.}
{400}{franc32}{Uuuuuf!}
{401}{franc33}{Áááááá!}
{402}{franc34}{Ajííííí.}
{403}{franc35}{Rnnrnrnrnnrrr.}
{404}{franc36}{Hagggahhhaaaggga.}
{405}{franc37}{Hominahominahomina.}
{406}{franc38}{Eeeeeccchhhh.}
{407}{franc39}{Chrocht!}
{408}{franc40}{Do øiti!}
{409}{franc41}{Jauvajs!}
{410}{franc42}{Au! Moje ruka!}
{411}{franc43}{Haha! Mám tì!}
{500}{}{Neskuteènı, Francisi! Neskuteènı!}
{501}{}{Sakra, tomu øíkám poøádnej náøez! Hahaha!}
{502}{}{Mìli byste oba vstoupit do armády. Hahaha!}
{503}{}{Nìco ti povím, pøíteli. Snaíš se zbyteènì!}
{504}{}{Au! To muselo bolet!}
{505}{}{Hej, Francisi! Zkus mu urvat ruku.}
{506}{}{Tehle souboj je fakt srandovní! Bahaha!}
{507}{}{Pouij svoje trapézy, Francisi! Pouij svoje trapézy!}
{508}{}{Oou... mìl bych se dret mimo dosah tvı ruky! Hahaha!}
{509}{}{To jsou ale bicepsy!}
{510}{}{Mám dojem, e jsem slyšel rupnout šlachu...}
{511}{}{Víš, jednoduchá matematika nám øíká, e je nejspíš Francis favorit.}
{512}{}{Francis! Fran-CIS! FRAN-CIS!}
{513}{}{Nandej mu to, Francisi!}
{530}{}{Dobøe, Francisi!}
{531}{}{Dobrá práce, Francisi!}
{532}{}{Páni! To se ještì nikdy nestalo!}
{599}{}{V tunelu leela nìjaká poznámka se jmény Francis a Zaius. Zdá se, e jsi spáchal nìjakı zloèin.}
{600}{franc28}{Zatracenì. Zaius zase nìkde nechal poznámku, co? Fajn, èlovìèe, nìco ti povím: Vìdìl jsem, e v tomhle mìstì ijou lidi, co chtìj zabít mutanty, a e je Marcus zavøe za katr, kdy bude mít dùkazy. Chtìl jsem to udìlat tak, aby zemøelo co nejmíò lidí.}
{601}{}{Take jsi zabil nevinné, jo?}
{602}{}{Aha. A co s tím chceš teï udìlat?}
{603}{franc29}{Nevinné? Ha! Ty lidi, kterı jsem zabil, se pokusili zabít MÌ! Jenom jsem jim to oplatil a udìlal z nich vıstrahu pro ostatní... takovou, která napomùe míru.}
{604}{}{V tom pøípadì nejsi nic jiného, ne obyèejnı zloèinec a vrah. Kromì tvıch slov nemám ádnı dùkaz o spiknutí.}
{605}{}{Jediná vìc, která napomùe míru, je smrt všech vrahù. A o to se teï postarám.}
{606}{franc30}{Pokud jsi s nìkım z mìsta mluvil o nenávisti k mutantùm, tak bys o spiknutí vìdìl. Já vím, e to nebylo zrovna nejšastnìjší øešení, ale šlo o sebeobranu. Uznávám, e to byla chyba. Nemùu tady zùstat. Najdu zpùsob, jak napravit svoje èiny... uspokojí to tvùj smysl pro spravedlnost?}
{607}{}{Bude muset.}
{608}{}{Ne, neuspokojí. Teï zemøeš.}
{700}{}{Podaøilo se ti porazit Francise v páce.}
{701}{}{Konfrontoval jsi Francise ohlednì dopisu pro Zaiuse.}
{800}{}{(Kdy se tak podíváš na obrovského mutanta, uvìdomíš si, e nemáš vùbec ádnou šanci. Je èas zmizet, dokud máš ještì svoji hrdost.)}
