{100}{}{Vidíš masoravou kytku.}
{101}{}{Vidíš kvìtinu Seymour.}
{102}{}{Vidíš kvìtinu, ze které z nìjakého dùvodu vyzaøuje inteligence.}
{103}{plant1}{Ahoj! Dneska máme ale hezké poèasí, e?}
{104}{}{Ty mluvit?}
{105}{}{Rrr?}
{106}{}{Promiòte, ale to mluví ta kvìtina?}
{107}{}{Nemáš nìjaké spoleèného s tím vìdcem?}
{108}{}{Èau.}
{109}{plant2}{Ano, umím mluvit. Dokonce lépe ne nìkteøí lidé. Usmála bych se na tebe, ale nemám ádná ústa. (Zasmìje se.) Poslyš, mùeš mi prokázat laskavost?}
{110}{}{Jo.}
{111}{}{Ne-e.}
{112}{plant3}{Hledám lepší místo pro ivot. Tady je sice moc hezky, ale upøímnì, tyhle kvìtiny toho zrovna moc nenamluví. Myslela jsem na nìjaké místo poblí budov, tøeba támhle, jak jsou ti staøí ghoulové... mùeš mì pøesadit?}
{113}{}{Jo!}
{114}{}{Ne-e!}
{115}{}{Jasnì.}
{116}{}{Myslím, e ne.}
{117}{plant4}{Skvìlé! Teï u jen najdi lopatu, vykopej mì a zasaï mì tam. A to udìláš, povím ti tajemství.}
{118}{}{Tak jo!}
{119}{}{Ne-e.}
{120}{plant5}{Tak dobøe. Take, eh... poèkám tu na tebe. Stejnì nemùu dìlat nic jiného. Navidìnou!}
{121}{}{Nashle!}
{122}{plant6}{Jestli náhodou zmìníš názor, víš, kde mì najdeš. Zapustila jsem tady toti koøeny. Hahaha! Jen trocha kvìtinového humoru. No, nebudu tì zdrovat. Navidìnou!}
{123}{}{Èau.}
{124}{plant7}{Hezky øeèeno, opravdu hezky! Je úasné vidìt homo sapiens vyívat plnou kapacitu svého mozku. Mùj drahı pøíteli, nechceš mi prokázat laskavost?}
{125}{}{Jo.}
{126}{}{Ne-e!}
{127}{plant8}{Ach ano! Ano, to je! Velmi mazané, pøíteli, velmi mazané. Vidím, e jsi nebyl zasazen teprve vèera! Mùj moudrı pøíteli, nechceš mi prokázat laskavost?}
{128}{}{Jasnì.}
{129}{}{Ne-e!}
{130}{plant9}{Úasné! Jsem velmi, ale opravdu velmi potìšena. Nejdøív najdi lopatu a poté se sem vra. A to udìláš, povím ti moná tajemství. Mùj pøíteli, doufám, e budeš i nadále vzkvétat.}
{131}{}{Eh, jasnì. Mìj se.}
{132}{}{Rozmyslel jsem si to.}
{133}{}{Ó ano, profesor. Vypìstoval mì a ivil mì u od malého semínka... jene u v ranném vìku jsem si uvìdomila, e pokud se budu chovat stejnì tak chytøe, jaká ve skuteènosti jsem, tak mì rozseká na kousíèky, aby mì mohl zkoumat. A tak jsem radìji hrála hloupou a skonèila jsem tady. Je tu pìknì... ale chtìla bych se trochu víc rozrùst. Moná, kdybych byla nìkde jinde...}
{134}{}{"Rozrùst." Jasnì.}
{135}{}{Aha. A co by sis pøála?}
{136}{}{Eh... coe? U musím jít. Nashle.}
{137}{}{Poøád má toho radškorpiona? Ta vìc je v šachách nepøemoitelná... i kdy to tak vùbec nevypadá, jestli mi rozumíš... ale vím, jak ho porazit. Kdy mi prokáeš laskavost, øeknu ti jak.}
{138}{}{Vánì? Jak?}
{139}{}{To je úasné. Kytka, co hraje šachy. To je asi nìjakı sen. Sbohem.}
{140}{plant12}{Mùj milı pøíteli, kdy mì zasadíš poblí támhletoho domu s ghoulama, mileráda ti na oplátku svìøím svou nejtajnìjší šachovou taktiku.}
{141}{}{Dohodnuto.}
{142}{}{Ne, díky. Porazím ho i bez cizí pomoci.}
{143}{plant13}{Á, pøíteli, vidím, e jsi zpátky. Tohle místo je prostì skvìlé. Je tu perfektní stín a spoleènost je tu jednoduše oslòující. Ten Typhon je ale šprımaø! Nenechá moje myšlenkové mízy na pokoji!}
{144}{}{Šachy?}
{145}{}{Co jsi to øíkala o šachách?}
{146}{}{Èau.}
{147}{}{No, mluvila jsem o tom, jak porazit profesorova radškorpiona v šachách. Mùj pøíteli, je to jednoduché jako facka. Ten degenerovanı poíraè broukù vdycky skoèí na Útok letících jater. Pøímo do nìj napochoduje a poté u se z nìj nedostane. Garantuju ti 100% úspìch.}
{148}{}{Dík moc! Pápá!}
{149}{}{Díky moc! Nashle!}
{150}{plant15}{Mùj pøíteli, svítí dnes na tebe slunce? Vzkvétá dnes tvé já? Jsi pøipraven na pøesunutí? Já rozhodnì ano!}
{151}{}{Jo!}
{152}{}{Ne-e! ádnı pøesun!}
{153}{}{Pojïme.}
{154}{}{Zmìnil jsem názor. U ti nechci pomoct.}
{155}{plant16}{Jsem tak vzrušená, e bych klidnì mohla vypustit celı mrak semen! Pojïme na to!}
{156}{}{[KONEC]}
{157}{}{To je škoda, opravdu škoda. Doufám, e èasem zmìníš svùj názor. Snad se jednou pyl tvé nerozhodnosti zmìní v mùj prospìch. Hezkı den.}
{158}{}{Eh.}
{159}{}{Hezkı den.}
{160}{}{Ó... pùda tady je taková... jiná. Èistší, nebo nìco takového. Moná proto, e jsem tu úplnì sama. Áááá. Ách! Ano! Jestli se nìkdy utkáš s profesorovım radškorpionem, zapamatuj si tenhle šachovı manévr: Jmenuje se Útok letících jater a on proti nìmu neobstojí.}
{161}{}{Dík!}
{162}{}{Díky, vyzkouším ho. Nashle!}
{163}{}{Taky bych ti ráda øekla, e náhodou vím, e Typhon uvnitø téhle budovy ví o nìjakém pokladu. Moná by se ti to mohlo nìkdy hodit.}
{164}{}{Dík! Nashle!}
{165}{plant20}{Pøemıšlel jsi o tom? Pomùeš mi?}
{166}{}{Jo!}
{167}{}{Ne-e!}
{168}{}{Jasnì.}
{169}{}{Myslím, e ne.}
{170}{plant21}{Bohuel to vypadá, e nemáš u sebe lopatu. Dokud nìjakou nenajdeš, nemùeš mì pøesadit. Budu na tebe èekat se zaatım pestíkem.}
{171}{}{Èau.}
{172}{plant22}{Psst! Halo! Halo, pøíteli! Tady!}
{173}{plant23}{Pojï blí! Slibuji, e ti neublíím.}
{174}{plant24}{Ale no tak! Snad se nebojíš kvìtiny?}
{175}{plant25}{Tady! Pojïme na to!}
{176}{plant26}{Ano, jsem mluvící kvìtina. Pochop to a mluv se mnou.}
{177}{plant27}{Pøíteli, momentíèek. Døív ne zaèneš kopat, mìli bychom se na tom domluvit. Promluvme si o tom.}
{178}{}{Zasazuješ Seymour u ghoulího domova dùchodcù.}
{179}{}{Mıt lopata! Kytka tam!}
{180}{}{Èirou náhodou mám jednu lopatu u sebe. Tak pojïme na to.}
