{100}{}{Vidíš drsnì vypadajícího starého mutanta.}
{101}{}{Vidíš Zaiuse, vrchního dùlmistra.}
{102}{}{Po bliším prozkoumání zjišuješ, e vidíš drsného starého mutanta s krumpáèem a hornickou pøilbou.}
{103}{zaius1}{Ty jsi ten nováèek ve mìstì?}
{104}{}{Eee, coetóó!}
{105}{}{Novı! Já! Mìsto!}
{106}{}{Pøesnì tak.}
{107}{}{Jo, jsem tu teprve chvíli.}
{108}{}{Ne asi, chytráku, iju tu od tı doby, co to tady stojí, ale ty sis mì nikdy nevšiml.}
{109}{}{Prı máte nìjaké problémy s dolem.}
{110}{}{Co mi mùeš øíct o tomto místì?}
{111}{zaius2}{Ehmmm... dooobøe. Nìco ti povím, tady máš pár doláèù, bì do salónu a kup si nìjakej chlast.}
{112}{}{Cink? Bum? ululu!}
{113}{zaius3}{Nerozumím ti, kámo. Nechceš jít radši do salónu? Tøeba si s tebou dá Francis páku.}
{114}{}{Máku? Dobe!}
{115}{zaius4}{Jasnì. No, jmenuju se Zaius. Teï kdy jsme se pøedstavili... máš šikovné ruce? Máme tu takovej problém s èistièkou vzduchu ve spodním podlaí dolu a bohuel nemáme díly na to, abysme to spravili a ani ochrannou vıstroj, kterou bysme se chránili pøed radonem, kterı se tam hromadí.}
{116}{}{Nemám šikovné ruce. Promiò.}
{117}{}{Docela jo. Co potøebuješ?}
{118}{zaius5}{No, tak doufám, e se ti bude v Broken Hills líbit.}
{119}{}{[Více]}
{120}{zaius6}{Haha. Dobrı vtip. Chytráci jsou na øešení problémù nejlepší.}
{121}{}{Jsi chytøejší ne všichni v tıhle prdeli.}
{122}{}{Vy máte nìjakı problém? O co jde?}
{123}{}{Hlavní problém je v tom, e jsi idiot.}
{124}{}{To jsem pøesnì já. Chytrák. V èem je problém?}
{125}{zaius7}{Naše èistièka vzduchu je rozbitá. Je ve spodním patøe dolu. Nemáme ádné náhradní díly ani ochrannou vıstroj. Bez dílù to neopravíme a bez ochrany nás ten radioaktivní plyn zabije. Máš šikovné ruce?}
{126}{}{Jsem v pohodì.}
{127}{}{Ne, ani ne.}
{128}{zaius8}{Zase ty, jo?}
{129}{}{Ork! Óó! Ehe!}
{130}{}{Ahoj! AHOOOJ! Já }
{131}{zaius9}{Kámo, u jsem ti peníze dal. Bì otravovat nìkoho jiného, slyšíš?}
{132}{zaius10}{Zdravím. Nechceš jít tøeba do... eh... mìstské banky? Jsem si jistı, e se tam najde pár lidí, kterı si s tebou rádi popovídají.}
{133}{zaius11}{No, tak pokud si to náhodou rozmyslíš, dej mi vìdìt.}
{134}{zaius12}{Opravdu? Udìláš to pro mì... a hlavnì pro Broken Hills?}
{135}{}{Co z toho budu mít?}
{136}{}{Jasnì, udìlám to.}
{137}{}{Teï ne.}
{138}{zaius13}{Fakt? Dobrá, chytráku, co takhle opravit tu èistièku vzduchu v dole? Budeš potøebovat náhradní díly a taky pøijít na zpùsob, jak dıchat ten plyn. Kdy dokáeš, e to zvládneš, pøestanu si myslet, e je chytrá jenom tvoje huba.}
{139}{}{Co z toho budu mít?}
{140}{}{Jasnì, udìlám to.}
{141}{}{Dìláš si srandu?}
{142}{zaius14}{Hlavní problém je v tom, e jsem idiot. Opakuju to proto, protoe jsem ještì neslyšel jedinı kloudnı slovo, kterı by vyšlo z tı tvı nevymáchanı drky. A teï se mi kliï z oèí, èerve.}
{143}{zaius15}{Kdy nepoèítám ty kretény, co mì poøád otravují, tak máme problém s èistièkou vzduchu v dolu. Je v háji, nemáme ádnou ochrannou vıstroj, se kterou bysme mohli dıchat radon, a taky nemáme náhradní díly na opravu. Myslíš, e to dokáeš? Jseš pøece chytrák, ne?}
{144}{}{Co z toho budu mít?}
{145}{}{Jasnì, udìlám to.}
{146}{}{Dìláš si srandu? V ádném pøípadì.}
{147}{zaius16}{. Co øíkáš?}
{148}{}{To si strè nìkam. Chci víc.}
{149}{}{To zní dobøe.}
{150}{}{Zapomeò na to. To se mi nelíbí.}
{151}{zaius17}{Skvìle! Budeš samozøejmì potøebovat nìjaké náhradní díly. Zajdi do New Rena a navštiv Renesca. Válí se mu po obchodì spousta haraburdí. Øekni mu, e tì posílá Zaius a taky heslo, "Kanárek chcípnul." Ale bohuel nevím, kde sehnat ochrannou vıstroj. Moná budeš moct jít dolù i bez ní, ale bude tì to bolet. Ještì jednou díky.}
{152}{}{ádnı problém. Nashle.}
{153}{zaius18}{No, pokud si to rozmyslíš, víš, kde mì najdeš.}
{154}{}{Jasnı. Nashle.}
{155}{zaius19}{ na ruku. Pùlku dostaneš teï a tu druhou a to bude hotovı. Zajdi do New Rena a navštiv Renesca. Válí se mu po obchodì spousta haraburdí. Urèitì ti seene nìjaké náhradní díly.}
{156}{}{Zatím.}
{157}{zaius20}{Promiò, víc ti nedám. Ber, nebo nech bıt.}
{158}{}{To beru.}
{159}{}{Nech si to.}
{160}{zaius21}{Fajn, tak nechtìj. Díky za nic.}
{161}{}{Nevadí.}
{162}{zaius22}{Nazdar pøíteli!}
{163}{zaius23}{A hele, to jsi zase ty.}
{164}{zaius24}{Nazdárek.}
{165}{zaius25}{Já vìdìl, e ti bastardi Franc, Manson, Jacob a Aileen proti nám nìco mají. Dobrá práce! Take...}
{166}{zaius26}{Doufám, e chceš vrátit mìstu tu rudu... take...}
{167}{zaius27}{Díky, e jsi prodal tu rudu. Vùbec jsme ji nepotøebovali... take...}
{168}{zaius28}{Díky za vrácení té rudy. Ani nevíš, kolik práce dá nìco takového získat.}
{169}{zaius29}{Co chceš teï?}
{170}{}{Mùeš mi øíct nìco o tomhle mìstì?}
{171}{}{Prı máte nìjaké problémy s dolem.}
{172}{}{Tak jak to jde?}
{173}{}{Vycházíš dobøe s lidmi?}
{174}{zaius30}{Pomùeš nám tedy opravit tu èistièku?}
{175}{}{Co z toho budu mít?}
{176}{}{Jasnì, udìlám to.}
{177}{}{Teï ne.}
{178}{}{Ne.}
{179}{zaius31}{Tak jak to jde? Doufám, e se na to brzy podíváš...}
{180}{}{Jde to celkem dobøe.}
{181}{}{Jsem zamìstnanı mu, take jsem se k tomu ještì nedostal.}
{182}{}{Dám ti brzy vìdìt.}
{183}{zaius32}{U máš ty díly? No vıbornì... snad máš taky nìjakou ochrannou vıstroj, ty vıpary by tì mohli sloit.}
{184}{}{Mùu se do toho dát.}
{185}{}{Za chvíli se na to podívám.}
{186}{zaius32}{U máš ty díly? No vıbornì... snad máš taky nìjakou ochrannou vıstroj, ty vıpary by tì mohli sloit.}
{187}{}{Mùu se do toho dát.}
{188}{}{Za chvíli se na to podívám.}
{189}{zaius33}{Opraveno? Vıbornì! Poslyš, já vím, e za to nic nechceš, ale... to od tebe nemùu chtít, take jsme se s chlapama sloili na tuhle opakovací brokovnici. Hodnì štìstí a díky.}
{190}{}{ádnı problém. Díky!}
{191}{zaius34}{Opraveno? Vıbornì! Tady máš zbytek odmìny, jak jsme se domluvili. Ještì jednou díky.}
{192}{zaius35}{Ty hajzle. Teï chcípneš.}
{193}{zaius36}{Dobøe, dobøe, ale pospìš si... naše mìsto ten dùl potøebuje.}
{194}{}{Jasnì. Zatím.}
{195}{}{Netlaè na mì, jsem zamìstnanı mu. Kreténe.}
{196}{zaius37}{Tak pardon, pane Všemohoucí, ale myslím, e pøeití mìsta je pomìrnì dùleité. Pospìš si, ano?}
{197}{}{Trhni si. A to bude, tak to bude. Zatím.}
{198}{}{Mùj pohár trpìlivosti právì pøetekl. Sbohem, mrtvolko.}
{199}{zaius38}{Pospìš si prosím, ten dùl je naše ivobytí.}
{200}{}{Dobøe, dobøe.}
{201}{zaius39}{No, nejlepší bude, kdy si promluvíš si s Marcusem pøed bankou nebo se Stevem u vstupu do mìsta.}
{202}{}{Hmm. Tak dobøe, díky.}
{203}{}{Pùjdu se jich tedy zeptat.}
{204}{zaius40}{Musím øíct, e to jde dobøe. Ale... vdycky mùe bıt líp.}
{205}{}{Hehe. Díky za informace.}
{206}{zaius41}{No, jeliko mutanti nestárnou a nejsou senilní... díky tomu plynu jsou toti mladí nebo tak nìco... tak musím øíct, e se máme fajn. Chci øíct, u nechceme všechny pozabíjet a pokud vím, lidé u o nás smıšlejí docela dobøe. To samé se ale nedá øíct o lidech z jinıch mìst... to jsou toti pìkní parchanti.}
{207}{}{Dobøe, díky. Nashle.}
{300}{zaius16}{. Co øíkáš?}
{301}{zaius16}{. Co øíkáš?}
{302}{}{$}
{381}{}{Jsem zamìstnaná ena, take jsem se k tomu ještì nedostala.}
{382}{}{Netlaè na mì, jsem zamìstnaná ena. Kreténe.}
{383}{zaius42}{Tak pardon, paní Všemohoucí, ale myslím, e pøeití mìsta je pomìrnì dùleité. Pospìš si, ano?}
{400}{}{Mám nìjakı dopis s tvım jménem. Leel u jedné mrtvé eny v tunelech. Mùeš mi k tomu nìco øíct?}
{401}{zaius43}{Hele, já ten dopis jen dostal. Bì si o tom promluvit s Francisem, ano? To on ho napsal.}
{402}{}{Jestli máš prsty v tìch vradách, tak o tom chci vìdìt.}
{403}{}{Tak dobøe. Zatím.}
{404}{zaius44}{Ne! Jen se chráníme pøed tím spiknutím. Marcus vìøí v právo a poøádek a i kdy ví, e jsou ti lidi nebezpeèní, tak neví, co jsou vlastnì zaè a je moc èestnı na to, aby jim podstrèil dùkazy. Mım úkolem bylo dret Francise na uzdì, aby se nezaèal všem mstít.}
{405}{}{To zní podezøele. Pùjdu si poslechnout Francisovu verzi.}
{406}{zaius45}{Já vìdìl, e Francis neunese prozrazení. Vìdìl, jaká rizika to obnáší, ale nejspíš nepoèítal s tím, e ho nìkdy chytí. Ale èasem bude v poøádku a stejnì tak doufám, e i Broken Hills.}
{407}{}{Taky doufám. Mám další otázky.}
{408}{}{Já taky. Nashle.}
{1130}{}{!}
