{100}{}{Vidíš jednoho ze dvou velmi podobnì vypadajících muù. Nejspíš dvojèata. Oba jsou poøádnì svalnatí a pøeènívá jim oboèí.}
{101}{}{Vidíš buï Chucka nebo Bucka Duntona. Jsou si však natolik podobní, e nevíš jistì, na kterého z nich se zrovna díváš.}
{102}{}{Vidíš vysokého, velmi svalnatého mue, jeho vıraz ve tváøi pøipomíná zamraèeného rváèe. Vypadá stejnì jako jeho bratr.}
{110}{buck1}{Bude lepší, kdy odsud vypadneš, nebo ti já a mùj bratr rozmlátíme ciferník na kaši.}
{111}{}{Hele, buïte v klidu. Byla to jen sranda. Opravdu se omlouvám. Nebijte mì, prosím. Chci se vás dva na nìco zeptat.}
{112}{}{Eh, promiòte, pane Dunton. U odcházím.}
{113}{}{Potøebuju nìjaké informace a bude lepší, kdy mi je øeknete.}
{114}{}{Ty a tvùj bratr? Bojíš se jít na mì sám? (Ts, Ts, Ts)}
{120}{buck2}{Vypadni odsud, nebo dostaneš ránu a udìláme z tebe sušenı maso.}
{121}{}{Hele, opravdu se omlouvám. Nebylo mım úmyslem vás naštvat. Jsem to ale blbec. Pøijdu pozdìji, a na mì nebudete tak naštvaní.}
{122}{}{Aha, dobøe, promiòte. Nebijte mì. Prosím.}
{123}{}{Aspoò u se nebudu muset dívat na ty vaše prdelní ksichty.}
{130}{buck3}{Co od nás chceš vìdìt?}
{131}{buck4}{Nemyslím, e bysme ti mìli vùbec nìco øíkat. Co sakra vlastnì chceš?}
{132}{buck5}{Take co od nás takovej malej òouma vlastnì chce?}
{133}{}{U jste nìkdo z vás slyšel o vìci zvané GECK?}
{134}{}{Chci obchodovat.}
{135}{}{Je tu nìjaká práce?}
{136}{}{Ehm, s kterım Duntonem to vlastnì mluvím?}
{137}{}{Neslyšeli jste nìco o mrzaèení brahmín v okolí?}
{138}{}{Myslím, e vlastnì nic nepotøebuju. Sbohem.}
{140}{buck6}{To u pøekraèuje všechny meze. Radši odsud vypadni, ne ti dáme lekci.}
{141}{}{Omlouvám se. Úplnì mì nadchla ta myšlenka s vámi pracovat. Radìji pùjdu. Sbohem.}
{142}{}{Meze? Jaké meze? S tím nápadem jste pøišli vy.}
{143}{}{Vy dva jste pøíliš velcí srabi na to, abyste s tím nìco udìlali.}
{150}{buck7}{No, máme k dispozici slušnı zásoby našeho celosvìtovì známıho Duntonovic sušenıho masa. Je chutnı, lahodnı a dost dobrı i pro tebe.}
{151}{}{Eh, to je skvìlé. }
{152}{}{Sušené maso? To nezní jako nìco, co zrovna teï potøebuju. Povìzte mi nìco jiného.}
{153}{}{Myslím, e vlastnì nechci obchodovat. Sbohem.}
{160}{buck8}{Pøíleitost tu byla, kámo.}
{161}{buck9}{Nemáme pro tebe ádnou práci.}
{162}{buck10}{No, je tu jedna vìc, s kterou bysme potøebovali pomoct. (Hehehe)}
{163}{}{A s èím, Chucku?}
{164}{}{A s èím, Bucku?}
{165}{}{Eh, a s èím?}
{166}{}{Jo no. Povìzte mi nìco jiného.}
{167}{}{Hej, poèkejte. Opravdu vám chci pomoct. Øeknìte mi ještì jednou o té práci.}
{168}{}{Hmm, to je škoda. Tak já tedy pùjdu. Sbohem.}
{169}{}{Dobøe. Ahoj.}
{170}{buck11}{Ty jeden neschopnej pytle geckonskejch sraèek! Co tu zase sakra dìláš?}
{171}{}{Chci se jen omluvit. Nechtìl jsem to podìlat. Prostì nejsem tak dobrı zlodìj dobytka, jako jste vy dva. Navíc od vás nìco potøebuju.}
{172}{}{No, máte pravdu, mohlo to bıt lepší. Asi nejsem rozenı zlodìj dobytka, jako jste vy dva. Nìco od vás ještì potøebuju.}
{173}{}{Geckonskı sraèky? Bavíme se o tom, co erete, nebo co máte místo mozku?}
{180}{buck12}{Zase zpátky, jo? Take s èím ti mùeme pomoct, paráku?}
{181}{buck13}{Nazdar, kámo. To byla bezva bouda, co jsme ušili na toho tupce Torra, co? Poèkej, dám ti tvùj podíl.}
{182}{}{To byl bezvadnı kšeft. Dejte mi vìdìt, a budete mít nìjakou podobnou prácièku. Nìco od vás ještì potøebuju. }
{183}{}{Jdu si pro svùj podíl, paráci.}
{184}{}{Stydím se za to, co jsme provedli. Musíte podvádìt hlupáka? Proè si vy zbabìlci radìji netroufnete na nìkoho, kdo se dokáe bránit? Sbohem.}
{185}{}{Myslím, e právì teï nic nepotøebuju. Sbohem.}
{190}{buck14}{Dobøe. Tady je $50 a k tomu ještì nìco malıho navíc. Nìkolik kouskù Duntonovic sušenıho masa. Ještì jednou díky, paráku.}
{191}{}{Díky. Mám na vás ještì pár dotazù.}
{192}{}{Ty peníze se budou urèitì hodit. Mmm, (koušeš) chutné maso, opravdu. Díky. Sbohem.}
{198}{buck15}{Fajn, vìc se má asi takhle. Potøebujeme trochu pomoct s... eh, vysvobozením nìkolika brahmín od toho idiota Torra. Nemìl by to bejt problém. Staèí se ho jen na chvíli zbavit. Co na to øíkáš?}
{199}{}{U si vzpomínám. Díky.}
{200}{buck79}{Setkáme se na brahmíních pastvinách dnes veèer v 6:00 PM. Je to kousek na vıchod od mìsta.}
{201}{buck80}{Setkáme se na brahmíních pastvinách zítra veèer v 6:00 PM. Je to kousek na vıchod od mìsta.}
{202}{}{Dobøe, postarám se o Torra. }
{203}{}{Dobøe, najdu Torra na pastvinách a postarám se o nìj. }
{204}{}{Myslím, e to nakonec neudìlám.}
{205}{}{Dobøe, budu tam. Sbohem.}
{206}{}{Chci se mezitím na nìco zeptat.}
{207}{}{Sbohem.}
{208}{buck17}{Jsem Chuck Dunton. Co jseš zaè? Blbec?}
{209}{buck18}{Jsem Buck Dunton. Co jseš zaè? Blbec?}
{210}{buck19}{Copak vypadám tak hnusnì? Jsem Chuck Dunton.}
{211}{buck20}{Copak vypadám tak hnusnì? Jsem Buck Dunton.}
{212}{buck21}{Jseš od malièka trošku pomalejší, co? Jsem Chuck Dunton.}
{213}{buck22}{Jseš od malièka trošku pomalejší, co? Jsem Buck Dunton.}
{214}{buck23}{Máš asi dlouhı vedení, co? Zatracenı tupı divoši. Jsem Chuck, blbeèku.}
{215}{buck24}{Máš asi dlouhı vedení, co? Zatracenı tupı divoši. Jsem Buck, blbeèku.}
{216}{buck25}{Jsem Nosatá Sally Duntonová. Líbí se ti moje šaty? Ne, jsem Chuck Dunton, ty blbej divochu.}
{217}{buck26}{Jsem Nosatá Sally Duntonová. Líbí se ti moje šaty? Ne, jsem Buck Dunton, ty blbej divochu.}
{218}{}{Ehm, dobøe. Bylo mi to hned jasné. Promiò.}
{219}{}{Bez obav. U to mám. Nìco od tebe potøebuju, ehm... pane Duntone.}
{220}{}{Jo, to je fuk, kdo jsi. Podívej, prostì mi øekni, co chci vìdìt.}
{221}{}{Kdy vy jste oba tak zatracenì hloupí a oškliví. Krom toho, je mi úplnì u prdele, na kterıho Duntona øvu. Sbohem, kreténi.}
{222}{}{Eh, jasnì. Take, povìzte mi nìco o té práci.}
{230}{buck27}{Dám ti radu... bude lepší, kdy budeš dret klapaèku. Paè jestli ne, tak nás pìknì naštveš. A to urèitì nechceš vidìt.}
{231}{}{Omlouvám se, nikomu to neøeknu. Slibuju, pane Dunton. Sbohem.}
{232}{}{Bez obav, nikomu to neøeknu. Povìzte mi o nìèem jiném.}
{233}{}{e vás nechci vidìt naštvané? Ty vaše hnusnı ksichty nechci vidìt vùbec. Sbohem.}
{240}{buck28}{Bezva, s tebou se obchoduje jedna radost. Hehehe. Potøebuješ ještì nìco?}
{241}{}{Hmm... myslím, e chci ještì nìco koupit.}
{242}{}{Ano, potøebuju.}
{243}{}{Ne, myslím, e to bude všechno, Chucku.}
{244}{}{Ne, myslím, e to bude všechno, Bucku.}
{250}{buck29}{Nazdar paráku. Dneska veèer s tebou poèítáme. Co pro tebe mùeme udìlat?}
{251}{}{Ehm, rozmyslel jsem si to. Myslím, e vám dnes veèer nepomùu.}
{252}{}{Jo. Budu tam. Chci se na nìco zeptat.}
{253}{}{Jasnì. Vím o tom. Sbohem.}
{259}{buck30}{A hele, náš namakanej kámoš.}
{260}{buck31}{Nazdárek. Tak co dìlá ruka? Dáme si to ještì jednou?}
{261}{buck32}{Nazdárek, ty malej prcku. Co dìláš v našem baru? Nejdøív se musíš pøed Duntonovımi pøedvést tím, e mì porazíš v páce a a potom ti dovolíme tu zùstat. (hahaha)}
{262}{buck33}{Nevypadáš tak tvrdì. Dej si se mnou, Chuckem Duntonem, páku a necháme tì pít v našem baru.}
{263}{buck34}{Nevypadáš tak tvrdì. Dej si se mnou, Buckem Duntonem, páku a necháme tì pít v našem baru.}
{264}{buck35}{Nazdar svatoušku. Do našeho baru si musíš získat pøístup. Staèí si dát páku se mnou, Chuckem Duntonem.}
{265}{buck36}{Nazdar svatoušku. Do našeho baru si musíš získat pøístup. Staèí si dát páku se mnou, Buckem Duntonem.}
{266}{buck37}{A hele, zdá se, e tu máme uchazeèe. Musíš si dát páku se mnou, Chuckem Duntonem, jestli tu chceš dostat nìco k pití.}
{267}{buck38}{A hele, zdá se, e tu mámje uchazeèe. Musíš si dát páku se mnou, Buckem Duntonem, jestli tu chceš dostat nìco k pití.}
{268}{}{Pojïme si dát tu páku. Asi je to jedinı zpùsob, jak mi dáte pokoj.}
{269}{}{Myslím, e si teï nechci dát páku.}
{270}{}{Nechci si teï dát páku. Chci jen nìjaké informace.}
{271}{}{Ehm, asi jsem ve špatném baru. Sbohem.}
{280}{buck39}{Tentokrát jsi vyhrál. Teda, jseš pìkná svinì. Rychlej jako geckon, kterımu hoøí ocas. Fajn, první drink je na mì.}
{281}{}{Díky. Moná bys mi mohl odpovìdìt na pár otázek.}
{282}{}{Prostì štìstí. Díky.}
{283}{}{Nechci tvoje pivo, díky. Chci se na nìco zeptat.}
{284}{}{Myslím, e nechci tvoje pivo. Sbohem.}
{290}{buck40}{Máš štìstí, e jsem ti tu ruèièku nezlomil jako suchou vìtev. (Bhahaha) No, zdá se, e tu pro mì poøád není poøádnej soupeø.}
{291}{buck41}{Nemáš u pro dnešek dost?}
{292}{}{Chci tì ještì jednou vyzvat. A tentokrát ti ukáu.}
{293}{}{Jauvajs. Fajn, fajn, to u by staèilo. Poslyš, mùu se na nìco zeptat?}
{294}{}{U mám dost. Sbohem.}
{300}{buck42}{Ty si s náma nechceš dát páku? Co, ty si myslíš, e jseš moc dobrej na to dát si páku s jedním z Duntonovic bratrù?}
{301}{}{Mám strach, e mi ublííte.}
{302}{}{Moná pozdìji. Teï potøebuju nìjaké informace.}
{303}{}{Vdy by to nebyl ádnı zápas. Jasná vıhra pro mì. Sbohem.}
{304}{}{Vypadáte jako pìkní slaboši. Zápasím jen s opravdovımi chlapy. Zmizte, tøasoøitky.}
{310}{buck43}{Co e to hledáš? Nejblí k rajskı zahradì se dostanu, kdy jsem v náruèi nádhernejch rukou Jenny z máminıch lázní. (Bhahaha)}
{311}{}{Eh, díky. Mùu se zeptat na nìco jiného?}
{312}{}{Myslím, e to bude všechno. Nashle.}
{320}{buck44}{No, slyšel jsem, e na vıchod odsud jsou nìjací (Bhaha) lido-brouci, co zabíjejí brahmíny. Ale èlovìk nesmí vìøit všemu, co slyší. (Bhahaha).}
{321}{}{Aha, dobøe. Díky. Chci se ještì na nìco zeptat.}
{322}{}{Myslím, e to bude všechno. Nashle.}
{330}{buck45}{Nazdar. Chceš koupit naše proslulı Duntonovic sušenı maso?}
{331}{buck46}{Tak jak? Chceš koupit nìjakı sušenı maso nebo ne?}
{332}{}{To zní dobøe. Chci obchodovat.}
{333}{}{Sušené maso? To zní zajímavì. Øeknìte mi o nìm víc.}
{334}{}{No, vlastnì mám na vás nìjaké otázky.}
{335}{}{Myslím, e zrovna teï nic nepotøebuju. Sbohem.}
{336}{}{Zajímají mì ty brahmíny, co máte vzadu. Zdá se, e nemají všechny stejné znaèkování.}
{340}{buck47}{Coe? Co tím sakra myslíš? Všechny jsou naše.}
{341}{}{Tím myslím, e nìkteré brahmíny vypadají, jako kdyby mìly jiné znaèkování, které nìkdo nešikovnì pøeznaèil.}
{342}{}{Aha, chápu. Hehe, moje chyba. Radìji u pùjdu. Sbohem.}
{343}{}{No, vlastnì toho o brahmínách moc nevím. To musí dìlat to jejich zbarvení nebo tak nìco. Máte tu pìkné brahmíny.}
{350}{buck48}{No, naše sušenı maso je úasná smìs jedenácti bylin a koøení. Musím øíct, e je tak dobrı, a si po nìm kadej olizuje prsty. I zvíøata ho milujou a budou tì pronásledovat, dokud nìjakı nedostanou. To musí bıt tím hnilobnım smradem.}
{351}{buck49}{Nic podobnıho nenajdeš. Nikde. Je unikátní. A vìtšina lidí je za nìj ráda.}
{352}{buck50}{Je to LIDSKİ maso! Bhahaha, jenom jsem chtìl vidìt, jak se pøi tom budeš tváøit. Je ho tam jen trochu. Bhaha.}
{353}{buck51}{Není to nìco, co by vìtšina lidí normálnì jedla. Je jinı. Ne lepší, jen jinı.}
{354}{buck52}{Pøi vırobì nedochází k ádnım krutostem na zvíøatech. Všechno je to maso, kterı se nìkde najde. Nìkdy nám chvíli trvá, ne nìjakı najdeme, ale vìtšinou ho pøineseme domù døív, ne úplnì shnije.}
{355}{buck53}{Po dlouhım dni v brahmíní ohradì seškrabeme z bot pár vybranejch kouskù, kterı tomu dodaj pøíchu.}
{356}{buck54}{No, zjistili jsme, e naše vlastnoruènì uvaøená omáèka, jestli mi rozumíš, dodává masu tu domácí pøíchu. }
{357}{buck55}{Vyrábí se z nejmíò šest mìsícù uleelıho hovìzího a je tenderizovanı tìma nejlepšíma larvama ovádù.}
{358}{}{Úasné. To zní, jako kdybyste opravdu jedli vlastní sušené maso. Eh, chci øíct, kdo by ne? Mòam. Mòam.}
{359}{}{Opravdu? To je fascinující. Øeknìte mi víc.}
{360}{}{Myslím, e to bude všechno. Sbohem.}
{361}{}{I v pøípadì šíleného hladu si radìji useknu svoji ruku a sním ji místo toho vašeho zatraceného sušeného masa.}
{370}{buck56}{Take sis to rozmyslel? Chceš pomoct zachránit ty ubohı malı brahmíny pøed Torrem?}
{371}{buck57}{Co tu ksakru dìláš? Chceš nám pomoct nebo ne? Moná pro tebe máme práci, jestli máš zájem.}
{372}{}{Jo, mám zájem. Povìzte mi o té práci.}
{373}{}{Myslím, e s vámi dvìma nechci nic mít. Sbohem.}
{374}{}{Támhle v té chatrèi leela hromada nìjakıch èástí broukù. Na co je máte?}
{380}{buck58}{Co sakra chceš? Nepamatuješ si, co máš udìlat?}
{381}{}{Pamatuju. Pustím se do našeho plánu.}
{382}{}{Zbláznili jste se? Jdou po nás. Chci vás varovat a ne pokoušet štìstí. Vsadím se, e nás teï právì sledují.}
{383}{}{Vypadlo mi to. Mùete mi ten plán zopakovat? Prosím.}
{384}{}{Támhle v té chatrèi leela hromada nìjakıch èástí broukù. Na co je máte?}
{390}{buck59}{Èásti broukù? Ehh, ee, hm, nevíme nic o ádnıch èástech broukù. O èem to vlastnì mluvíš?}
{391}{}{No, leela tam hromada nìjakıch èástí broukù, které na sobì mìli pøezky a øemínky, take vypadali, e by se dali nosit na rukou. Leeli na podlaze.}
{392}{}{Ehm, zapomeòte na to. Sbohem.}
{400}{}{Tak znova. Musíš se zbavit Torra.}
{401}{}{To zní dobøe, udìlám to.}
{402}{}{V ádném pøípadì. Padám odsud, Duntonovi. Sbohem.}
{403}{}{Zbláznili jste se? Jdou po nás. Chci vás varovat a ne pokoušet štìstí. Vsadím se, e nás teï právì sledují.}
{404}{}{A se Torr ukáe, tak ho musíš}
{405}{}{ dostat na chvíli odsud. Mùeš si s ním povídat nebo ho zmlátit do bezvìdomí, ale v ádnım pøípadì ho nezabíjej nebo naštveš celej Klamath. My mezitím odvleèeme brahmíny. Sejdeme se zítra v našem obchodì, kde na tebe bude èekat tvoje odmìna.}
{410}{buck62}{Asi máš pravdu. (Rychle se rozhlédne kolem.) Nelíbí se mi ta pøedstava, e mì nìkdo sleduje.}
{411}{}{Mìl bys bıt ke svım kámošùm hodnìjší. A teï jdi domù.}
{420}{}{Nikdo nás nesleduje. Dáváme si na to opravdu pozor. Máš z toho bobky, co? Pitomej srabe. }
{421}{}{Promiòte, asi z toho mám nervy. V takovıch situacích nejsem tak v pohodì jako vy dva.}
{422}{}{Promiòte, jen panikaøím. Pustím se zase do práce.}
{423}{}{V ádném pøípadì. Odcházím. Sbohem.}
{424}{}{Teï se vra zpátky ke svı práci a zbav se toho idiota Torra!}
{430}{buck65}{Jsi blázen. To jsou jenom zbytky nìjakejch radškorpionù, co jsme zabili. Jo, to je ono. Pøesnì tak to je. My, ehm, eh, pouíváme jejich jed jako jednu z tajnejch pøísad do našeho sušenıho masa.}
{431}{}{No jasnì. To vám uvìøím, a vyjde slunce na západì.}
{432}{}{No, kdy to øíkáte... tak je to pro mì dostateèné vysvìtlení. Sbohem.}
{440}{buck66}{Bude lepší, kdy budeš dret hubu, pokud nechceš pøijít k úrazu.}
{441}{}{Jeíš, v klidu. Chtìl jsem vám zrovna øíct, jakı to byl skvìlı nápad. Šmarjá, uklidnìte se.}
{442}{}{Promiòte. U budu zticha. Sbohem.}
{443}{}{Jasnì. No, mizím odsud. Sbohem.}
{444}{}{Mám lepší nápad. Co kdybyste pro zmìnu tu hubu zavøeli VY? U mì nebaví poslouchat, jak melete tìma vašima shnilejma pantama.}
{449}{}{Nazdárek, divochu. }
{450}{}{Jsem Chuck Dunton.}
{451}{}{Jsem Buck Dunton.}
{452}{}{Hnusná chláp.}
{453}{}{ Vyvolenı!}
{460}{buck69}{Hnusná chláp? Co? Koukám, e jsi zrovna takovej idiot jako Torr. To je bezvadnı, fakt potøebujeme ve mìstì novıho vesnickıho blbeèka. Torr u je moc okoukanej.}
{461}{}{Torr okukanej?}
{470}{buck70}{Vyvolenı jo? Vyvolenı leda tak na rozbití huby. To tì máma upustila hlavou na zem, nebo ses opravdu narodil tak blbej a ošklivej? Táhni odsud.}
{471}{}{Ook! }
{472}{}{ Vyvolenı!}
{480}{buck81}{Pøipraven? Dobøe, tak pojï. Nemáme na to celou noc. Máme dost práce.}
{481}{}{Eh, jo. Pøipraven. Mùeme jít.}
{482}{}{Jsem pøipraven udìlit tomu hloupému pasáèkovi lekci.}
{483}{}{Myslím, e to neudìlám. Uvidíme se pozdìji. }
{490}{buck76}{Hele, poèkej, a zajdeme dovnitø. Tam mùeme bez obav mluvit.}
{500}{}{Snaha byla, ale nakonec Duntonovic bratr zvítìzil.}
{510}{}{Po tìkém souboji se ti podaøilo porazit Duntonovic bratra!}
{520}{}{Dobøe.}
{530}{buck71}{Vypadni sakra odsud. Nìkteøí lidi mají práci.}
{531}{}{Eh, dobøe. Tak já pùjdu. Šmarjá, nìkteøí lidi jsou tak hákliví. Sbohem.}
{532}{}{Torr pase své brahmíny severnì od centra.}
{533}{}{A sem ten blbec Torr pøijde, tak se ho zbav.}
{600}{buck77}{I ten hloupı Torr je chytøejší ne ty, zlodìji!}
{601}{}{ Mùeme jít?}
{700}{}{Úspìšnì se ti podaøilo ukrást brahmíny.}
{702}{}{Ne, povím vám, na co je máte. Oblékáte se s nimi jako "Lido-brouci" a odháníte tak vystrašeného Torra pryè od jeho brahmín, e mám pravdu, e ano?! Ted u to všechno dává smysl. Jste oba dva jen hnusní darebáci.}
{703}{buck72}{(Oèi Duntonovıch bratrù se rozšíøily a zaèínají bıt neklidní.) Nn...nnn...no a co...je ti do toho, divochu? Kadej obèas potøebuje nìjakı peníze navíc. Co je ti vùbec do toho? A co s tím jako udìláš, hm?}
{704}{}{Nìco vám povím. Kdy pøestanete krást brahmíny a obtìovat Torra, tak vás neprásknu. Chci jen váš slib, protoe jestli se to stane ještì jednou, tak tu nezùstane nikdo, kdo by kradl další brahmíny. Rozumìli jste?!}
{705}{buck73}{[Bhahaha] No jasnì, divochu. Myslím, e je nejvyšší èas, abysme ti ukázali, co se stane zvìdavejm divochùm, jako jseš ty.}
{706}{buck74}{Dobrá, divochu, tentokrát jsi vyhrál. Necháme toho, jen nás nech na pokoji.}
{707}{}{Podaøilo se ti vydìsit bratry Duntonovy natolik, e u nikdy nebudou Torra obtìovat.}
{708}{}{[KONEC]}
{709}{buck78}{Nech nás bıt.}
{710}{buck75}{Jasnì. Jak myslíš, divochu. Starej se o sebe.}
{800}{}{V chatrèi na pastvinách leela hromada èástí broukù. Na co je máte?}
