{100}{}{Vidíš malého snìdého mue, kterı se na tebe usmívá.}
{101}{}{Vidíš Sajaga, majitele a barmana hospody U Zlatého geckona.}
{110}{sajag1}{Zdravím tì, cizinèe. Vítej U Zlatého geckona, podniku, kterı je hospodou, hotelem i obchodem. Jsem Sajag. Provozuju to tady. Èím mùu poslouit?}
{111}{}{Oh eh oh?}
{112}{}{Blití! (ukázat na sklenici)}
{113}{}{Chci nìco k pití.}
{114}{}{Chci koupit jednu rundu pro kadého v baru a tím se tak pøedstavit.}
{115}{}{Chci obchodovat.}
{116}{}{Chci nocleh.}
{120}{sajag2}{Hmm, další zatracenej idiot. Úplnì jako Torr. Vypadni z mıho baru!}
{130}{sajag3}{Ááá, e by další, co mezi nás dobøe zapadne? Jestli chceš utrácet, tak tohle je ta správná krèma. Èím ti mùu poslouit, kamaráde?}
{131}{sajag4}{Nezdáš se bıt pøíliš populární v téhle èásti mìsta. No, uvidíme co tvé další èiny. Jak ti mùu pomoct?}
{132}{}{Chci si dát nìjaké pivo.}
{133}{}{Chci koupit jednu rundu pro kadého v baru.}
{134}{}{Chci obchodovat.}
{135}{}{Chci nocleh.}
{136}{}{Díky za pomoc. Sbohem.}
{137}{}{Sbohem.}
{140}{sajag5}{Jeden vrchovatı dbánek Chcanek zlatého geckona u se nese. Pouze $5 za nejlepší pivo severnì od Reddingu.}
{141}{}{Ty jsi mi nalil dbánek chcanek!?!}
{142}{}{Díky za pivo. Mùu se teï zeptat na pár vìcí?}
{143}{}{Díky. To bude asi všechno. Sbohem.}
{150}{sajag6}{Rundu chcanek pro kadého v baru! Paráda! To bude za $30. (zeširoka se usmìje)}
{151}{}{To tu všichni pijete geckonskı chcanky!?!}
{152}{}{Doufám, e mají všichni radost z piva. Sajagu, potøebuju nìjaké informace.}
{153}{}{Uijte si všichni chcanky. Sbohem.}
{160}{sajag7}{Zdá se, e na to nemáš dost penìz. Lituju, pøíteli, ale na dluh nedávám. (usmìje se)}
{161}{sajag8}{Takovıch jako ty u tu bylo, co nemìli ani vindru a chtìli by chlast. Nejsou prachy, není obsluha. A teï odsud vypadni.}
{170}{sajag9}{Uklidni se, kamaráde, takhle tu øíkáme pivu. (uchichtne se) Tady jsi U Zlatého geckona, víš?}
{171}{sajag10}{Je to jen pivo. U Zlatého geckona, Chcanky zlatého geckona? Chápeš? Máš nìco s ušima nebo co? (zavrtí hlavou) Ach, ti divoši.}
{172}{}{Aha. Hehe, no, my v Arroyu ve skuteènosti... eh, zapomeò na to.}
{173}{}{Aha, u chápu. Hmm, máte tu zvláštní vırazy.}
{174}{}{Nebudu pít chcanky! A nezajímá mì, kde je nalejvaj nebo jak tomu øíkáte!}
{180}{sajag11}{Dobrá, teï kdy u jsme se trochu seznámili...jak ti mùu pomoct? (usmìje se)}
{181}{sajag12}{Pìknì se nám tu s tebou pije. (zahihòá se) Co vlastnì chceš?}
{182}{}{Myslím, e si dám další pití.}
{183}{}{Chci koupit rundu pro všechny svoje nové pøátele.}
{184}{}{Chci se tì na nìco zeptat.}
{185}{}{Myslím, e to bude prozatím všechno. Dìkuju.}
{190}{sajag13}{No, o informacích to všechno je, kamaráde. Co chceš vìdìt?}
{191}{sajag14}{Ano? O èem chceš ksakru vìdìt?}
{192}{}{Jsou tu nìkde poblí další mìsta?}
{193}{}{Jsou tu nìkde v Klamathu další obchodníci?}
{194}{}{Dìje se v Klamathu nìco mimoøádného?}
{195}{}{Hledám práci. Nebylo by nìco?}
{196}{}{Kde se dají získat nìjaké léèivé prostøedky?}
{197}{}{Hledám nìco, co se nazıvá GECK. Nevíš, kde by se dala taková vìc získat?}
{198}{}{To bude asi všechno. Ale potøebuju od tebe ještì nìco jiného.}
{199}{}{Myslím, e mi to prozatím bude staèit.}
{210}{sajag15}{Zdravím, pøíteli. Doneslo se ke mnì, e víš, kde je destilátor Whiskey Boba. Rád bych vìdìl, kde ho má.}
{211}{}{Tak to se asi pleteš. Jméno Whiskey Bob slyším poprvé v ivotì.}
{212}{}{Myslím, e ti to neøeknu.}
{213}{}{Proè chceš vìdìt kde je?}
{214}{}{Moná, e vím. Jakou to má pro tebe cenu?}
{215}{}{Potøebuješ se zbavit konkurence, co?}
{220}{sajag16}{Zapomeò na to. Není to zase tak dùleité. (usmìje se)}
{230}{sajag17}{No, Bob pøekáí jistım obchodním partnerùm. Mnì konkurence nevadí, (ušklíbne se), ale jim ano. Dám ti $50, kdy mi øekneš, kde má Bob ten destilátor. Nic víc od tebe neádám. (usmìje se)}
{231}{sajag18}{Problém je v tom, e Bobova podomácku pálená whisky lidem škodí. Zaplatím ti $50, kdy mi øekneš, kde má ten destilátor. Potom ho budeme moct pøedvolat pøed mìstskou radu a ukonèit tak jeho èinnost. (zeširoka se usmìje)}
{232}{}{$50 je dobrá cena, zvláš kdy pro to nemusím nic udìlat. (Øíct mu kde najde Bobùv destilátor.)}
{233}{}{Myslím, e ti neøeknu, kde ten destilátor je.}
{234}{}{Myslím, e Bobova whisky lidem nijak neškodí.}
{235}{}{Za $50 ti øeknu, kde je ten destilátor, ale chci slyšet víc o tvıch obchodních partnerech. (Øíct mu kde najde Bobùv destilátor.)}
{240}{sajag19}{Diky za informace, pøíteli. Ujišuju tì, e budou dobøe pouity. (usmìje se) Tady je tvıch $50 a jedny chcanky na podnik. Mùu ti ještì s nìèím pomoct?}
{241}{}{Myslím, e si dám jedny chcanky na oslavu.}
{242}{}{Co takhle chcanky pro všechny mé zdejší kamarády?}
{243}{}{Mám nìjaké otázky, na které se chci zeptat.}
{244}{}{To bude prozatím všechno. Sbohem.}
{250}{sajag20}{No, øeknìme, e mám kontakty s nìkolika dùleitımi lidmi jinì odsud, v Denu.}
{251}{}{Dobøe, budu si to pamatovat. Díky za peníze.}
{260}{sajag21}{Mám tu velké mnoství nejrùznìjších vìcí: léèivé prostøedky, chlast a tak podobnì. Dá se øíct, e mám své speciální zdroje. Vykupuju taky geckoní kùe.}
{261}{}{Uka mi co máš.}
{262}{}{Myslím, e zrovna teï nic nepotøebuju. Ale mám nìjaké otázky.}
{263}{}{Speciální zdroje? V tom pøípadì bys mi mìl dát opravdu dobré ceny, ne?}
{270}{sajag22}{Vdycky tu mám dostatek pokojù pro naše pøátele. Za pouhıch $20 mùeš mít 8 hodin bezpeèného a pohodlného spánku. Budeš mít celı pokoj jen pro sebe.}
{271}{sajag23}{Nemám volné pokoje, kamaráde. Lituju, mám plno.}
{272}{}{$20 zní jako dobrá a férová cena. Beru to.}
{273}{}{Myslím, e takovou nabídku nemùu pøijmout, Sajagu. Co kdybychom se bavili o nìèem jiném?}
{280}{sajag24}{Hej, kamaráde, díky za informaci. Moji pøátelé v Denu mají teï lepší spaní, kdy je konkurence zneškodnìna. (šibalsky se usmìje)}
{281}{sajag25}{Díky za informaci, pøíteli. Mìstská rada, eh, odhlasovala, e zakáe Bobovi pouívat destilátor. U nebude nikomu ubliovat. (upøímnì se usmìje)}
{282}{}{Jsem rád, e se to takhle vyøešilo. A tìch $50 se taky celkem hodí.}
{283}{}{No, taky se mi teï bude daleko klidnìji spát, kdy u v Klamathu neuvidím Bobovu pálenku.}
{284}{}{Je mi to fuk, kamaráde.}
{290}{}{No, asi takhle. Poslední dobou se dìje ve mìstì dost vìcí. (poèítá na prstech) Máme tu }
{291}{}{Povìz mi nìco o tìch lido-broucích mrzaèící brahmíny, prosím.}
{292}{}{Povìz mi nìco o tìch pøerostlıch hlodavcích, prosím.}
{293}{}{Povìz mi nìco o chodících duších, prosím.}
{294}{}{Ani mì moc nepøekvapuje, e se v tak rušném mìstì ztratí lovec. Povìz mi o nìm víc.}
{295}{}{Chci se zeptat na nìco jiného.}
{296}{}{Myslím, e u jsme probrali všechno.}
{300}{sajag27}{No, bratøi Duntonovi poøád hledají nìkoho, kdo by pro nì dìlal jejich špinavou práci. Doteï pro nì dìlal Torr, syn paní Bucknerové, jene se bojí hlídat brahmíny v noci kvùli lido-broukùm.}
{301}{}{Díky. Mám na tebe další otázku.}
{302}{}{Myslím, e víc u nepotøebuju vìdìt. Ale potøebuju od tebe ještì nìco jiného.}
{303}{}{To bude prozatím všechno. Sbohem.}
{310}{sajag28}{Okolo je pár dalších mìst. Na severozápadì ijí nìjací divoši, ale to nejspíš dobøe víš. (usmìje se) Dále je tu Den nìkolik dní na jihovıchod... ten je nejblí... a pak je tu ještì hornické mìsto Redding daleko na jihovıchodì.}
{320}{sajag29}{Ve mìstì není moc obchodníkù. Snad jen Vic, kdy o tom tak pøemıšlím. Má dùm ve vıchodní èásti centra. Prodával divochùm pøedváleèné vìci z Denu, ale u jsem ho nìjakı èas nevidìl.}
{330}{sajag30}{No, takové ceny nejsou pro kadého. Víš, není vùbec snadné dostat tohle zboí z Denu.}
{331}{sajag31}{Rád bych z tebe udìlal jednoho ze svıch dobrıch pøátel, zlatíèko. (ušklíbne se) Není snadné získat tohle zboí z Denu. Nìco ti øeknu... udìlám ti speciální cenu na všechno, co tu mám.}
{340}{sajag32}{Nevím o èem to mluvíš, kámo. Chceš obchodovat nebo ne?}
{341}{}{Jo, jasnì e chci obchodovat. Promiò mi tu otázku.}
{342}{}{Myslím, e s tebou vlastnì obchodovat nechci.}
{343}{}{Vdy máš kontakty v Denu. No tak... vím, e mi mùeš dát lepší ceny.}
{350}{sajag33}{No, øíká se, e tvorové, co vypadají jako brouci o velikosti èlovìka a chodí po dvou nohách, trhají brahmíny na kusy uprostøed noci. I kdy jenom Torr je vidìl zblízka. Dìsivé, e?}
{360}{sajag34}{Povídá se, e v Lovecké ètvrti je obrovská krysa o velikosti Corvegy, která vládne všem tamním krysám. Prı ije ve starém opuštìném dole a krysy tam tahají všechny lesklé pøedmìty, které najdou. (olízne si rty) Mmm, lesklı cetky.}
{370}{sajag35}{No, kousek na západ od mìsta je kaòon. Pøed nìkolika mìsíci odtamtud vycházelo jasné svìtlo a pak zaèali mizet zvíøata. Stopy vedou do kaòonu, ale ádné nevedou ven. Strašidelné, co? Pár lidí taky slyšelo podivné zvuky naøíkání odráející se od stìn kaòonu.}
{380}{sajag36}{No, Smiley byl jeden z nejlepších lovcù, jakého jsme tu kdy mìli. Jednoho dne vstal a opustil paní Bucknerovou, aby se pokusil najít místo, odkud pøicházejí zlatí geckoni. Tvrdil, e bude bohatı, jestli to místo najde. Jene se ještì nevrátil... a u je to nìjakı ten pátek.}
{381}{}{To je úasné. Povìz mi o dalších místních novinkách.}
{382}{}{To bude prozatím všechno.}
{390}{sajag43}{Rajská zahrada, jo? No, nejblí jsem byl rajské zahradì, kdy jsem byl u Jenny. A stojí to jen nìkolik málo dolarù. (usmìje se) Zní to hezky, ale opravdu nevím, kde by se to dalo najít.}
{391}{}{No, to je odpovìï, která mi moc nepomùe. Chci se ještì na nìco zeptat.}
{392}{}{To bude prozatím všechno.}
{2900}{sajag37}{Vlastnì se toho poslední dobou moc nedìje.}
{2901}{}{lido-brouky mrzaèící brahmíny}
{2902}{}{pøerostlé hlodavce}
{2903}{}{chodící duchy}
{2904}{}{pohøešovaného lovce}
{2905}{}{. V Klamathu to poslední dobou vøe.}
