{100}{}{Vidíš velikého mue pokrytého prachem. Tváøí se mírnì pøipitomìle.}
{101}{}{Vidíš Torra Bucknera, mìstského prosáèka.}
{102}{}{Vidíš velkého, svalnatého mue ve špinavém obleèení, které je pokryté špínou a prachem. Na tváøi má blaenı úsmìv.}
{110}{torr1}{Ty zlá. Ty bít Torr. Ty jít pryè hned!}
{111}{torr2}{Jít zlá osobá! Nebít Torr.}
{112}{torr3}{Jaùù! Jít pryè!}
{113}{torr4}{Nebít Torr u víc.}
{114}{torr5}{Torr hodná. Nebít Torr.}
{115}{torr6}{Torr zranìná. Zlá chlap! Zlá chlap jít pryè!}
{120}{torr7}{Pomoct Torr! (Pomoz mi prosím. Je tady jisté stvoøení, které mi zabraòuje v útìku z tohoto místa.)}
{121}{torr8}{Pomoct Torr!}
{122}{}{ pomoct Torr. (Pomùu ti, Torre. Vydr!)}
{123}{}{Pomùu ti, Torre.}
{130}{torr9}{Písk písk zlá! Pomoct Torr! (Dej si pozor na Ducha, kterı kráèí! Promluvíme si, a mì odsud dostaneš.)}
{131}{torr10}{Písk Písk! Au! Duch zlá! Zlá! Pomoct Torr! Torr jít hned!}
{132}{}{Dobe, Torr. (To je rozumné, Torre. Vypadneme odsud.)}
{133}{}{Promluvíme si pozdìji, teï odsud musíme vypadnout.}
{140}{torr11}{Já Torr (Jsem Torr. Mùu ti nìjak pomoct?)}
{141}{torr12}{Já Torr.}
{142}{}{Ty Torr. (Ahoj, Torre. Mám na tebe pár otázek.)}
{143}{}{Tìší mì, Torre. Nestalo se tady v poslední dobì nìco zajímavého?}
{144}{}{Jsem tu kvùli brah... eh, chci øíct bùbùm.}
{150}{torr13}{Já hlídkovat bùbù pøed broukochlapama. (Hlídám brahmíní stádo naší rodiny pøed zuøivımi noèními útoky dvounohıch bytostí pokrytıch chitinovım pancíøem, kterım øíkám lido-brouci.)}
{151}{torr14}{Já hlídkovat bùbù pøed broukochlapama.}
{152}{}{Broukochlapama? (Lido-brouci? No, to zní jako vıstinı název pro to, co jsi mi právì popsal. Povìz mi o nich víc.)}
{153}{}{Broukochlapama?}
{160}{torr15}{Broukochlap krást bùbù kdy noc. Torr strach! Pomoct Torr? (No, jak jsem øekl, jsou to noèní tvorové. Hodila by se mi nìjaká pomoc pøi hlídání. Pomùeš mi zabít lido-brouky, kteøí se dostanou blízko k brahmínám?)}
{161}{torr16}{Broukochlap krást bùbù kdy noc. Torr strach! Pomoct Torr?}
{162}{}{Pomoct Torr s bùbù. (Jistì, pomùu ti ochránit tvoje brahmíny pøed útoky tìch proradnıch lido-broukù.)}
{163}{}{Broukouchlap oni zlá. Nepomoct Torr. (Hmm, myslím, e ti s tím nepomùu, Torre. Ale pøeju ti hodnì štìstí. Sbohem.)}
{164}{}{Eh...jistì, Torre. Pomùu ti ohlídat brahmíny.}
{165}{}{Nemùu (zavrtíš hlavou) ti s tím pomoct. Sbohem.}
{166}{}{Obchoïák znát? (Ne se tam vydáme, Torre, nevíš o nìjakém obchodníkovi ve mìstì?}
{170}{torr17}{Ty pomoct Torr. Pole bùbù (ukáe na vıchod) ve tma jo? (usmìje se) (Díky za pomoc. Dnes v noci ji opravdu budu potøebovat.)}
{171}{torr18}{Ty pomoct Torr. Pole bùbù (ukáe na vıchod) ve tma jo? (usmìje se)}
{172}{}{ pomoct Torr. (Pomùu ti. Setkáme se na pastvinì pøi západu slunce.)}
{173}{}{Torr? (Pomùu ti ohlídat brahmíny, ale nejdøív se tì chci na nìco zeptat.)}
{174}{}{Pomùu ti ohlídat brahmíny, Torre. Setkáme se na pastvinì pøi západu slunce. Sbohem.}
{175}{}{Dnes v noci ti nemùu pomoct hlídat brahmíny, Torre. Nashle.}
{180}{torr19}{Torr øíct? (Co chceš vìdìt, pøíteli?)}
{181}{}{ tady! (Povìz mi, co se tu dìje.)}
{182}{}{ Chrrrrr. Jasnı? (Potøebuju místo k pøespání.)}
{183}{}{Chtít! (ukáeš na vìci)(Kde mùu obchodovat?)}
{184}{}{GGG ek? (Slyšel jsi nìkdy o vìci zvané GECK?)}
{185}{}{Jít Torr. (To mi zatím staèí. Sbohem, Torre.)}
{190}{torr20}{Dobe! Broukochlap, dívok Ulik, Smiley chybìt. (No, je tady ten mùj problém s lido-brouky a pak je tady Sulik, kterı si u mojí mámy odpracovává dluh... mám pocit, e je do nìj sestra zamilovaná. A mámin pøítel, chlápek jménem Smiley, se ztratil nìkde na západì. V poslední dobì je tady docela ivo.)}
{191}{}{Torr? (Tady to ale ije. Chci se ještì na nìco zeptat.)}
{192}{}{Dobe! (To mi zatím staèí. Sbohem.)}
{200}{torr21}{Chrrrr? Torr Chrrrr. (No, mùeš pøespat u mì. Zadarmo.)}
{201}{}{Torr Chrrrrrrr? (Necháš mì u sebe pøespat? To je od tebe opravdu milé. Hned toho vyuiju, u skoro spím. Díky.)}
{202}{}{Chrrrrr? (Teï se mi zrovna nechce spát, ale díky za nabídku, moná ji vyuiju pozdìji. Ale mám na tebe ještì pár otázek.)}
{203}{}{Chrrr Ne Torr. (Teï momentálnì spánek nepotøebuju, ale díky za nabídku. Sbohem, pøíteli.)}
{210}{torr22}{Buckner! Zlátág nene (Myslím, e nejlepší ceny dostaneš u nás, Bucknerù. U Zlatého geckona se ti jenom vysmìjí.)}
{211}{}{Uckner? (Díky, nakoupím tam. Chci se ještì na nìco zeptat.)}
{212}{}{Zlátág nene. (Dobrá rada. Ale teï stejnì nic nepotøebuju. Sbohem.)}
{220}{torr23}{GGGék? Vic Gék! (Take ty hledáš GECK, jo? Ty byly døív ve vaultech, ne? Nevím, kde by se dalo nìco takového sehnat, ale urèitì o tom nìco ví obchodník Vic. Specializuje se na pøedváleèné zboí. ije v severovıchodní èásti Klamathu.)}
{221}{}{Gék Vic? (Díky za informaci. Zkusím se toho Vica zeptat. Chci se ještì na nìco zeptat.)}
{222}{}{Gék Vic, dobøe! (Díky, zajdu za ním. Sbohem.)}
{229}{}{Torr ráda }
{230}{}{. Torr dìkovat. Broukochlap zlá, nenechat brokouchlap papat bùbù! (Dìkuju ti za pomoc, z tìhlech lido-broukù mi bìhá mráz po zádech. Doufám, e u o ádné další brahmíny nepøijdeme.)}
{231}{}{. Torr dìkovat. Broukochlap zlá, nenechat brokouchlap papat bùbù!}
{232}{}{Torr. (Kdy jsme tu dva, tak nám urèitì ádnou brahmínu nevezmou.)}
{233}{}{Doufám, e zastavíme ty útoky na tvé bùbù. Eh, chci øíct brahmíny. Myslím, e si na nás dva netroufnou.}
{234}{}{Vlastnì tì jdu varovat. Támhle na druhé stranì skály je nìkolik broukochlapù. Pohlídám bùbù za tebe a ty utíkej pro pomoc.}
{240}{torr26}{Dobe? Pomoct Torr s bùbù? Ne broukochlap! Broukochlap zlá! (Pomùeš mi ochránit brahmíny pøed útokem lido-broukù?)}
{241}{torr27}{Dobe? Pomoct Torr s bùbù? Ne broukochlap! Broukochlap zlá!}
{242}{}{ pomoct Torr s bùbù (Ano, jdu ti pomoct ochránit brahmíny proti lido-broukùm. Pokud tu budeme oba, nedostanou ani jeden kus!)}
{243}{}{Ne pomoct. (Promiò, ale já tudy jenom procházím. Nemùu ti pomoct. Sbohem.)}
{244}{}{Eh, ano. Jdu ti pomoct ochránit brahmíny... chci øíct bùbù... pøed broukochlapy.}
{245}{}{Vlastnì tì jdu varovat. Támhle na druhé stranì skály je nìkolik broukochlapù. Pohlídám bùbù za tebe a ty utíkej pro pomoc.}
{246}{}{Promiò, Torre. Mám moc práce na to, abych tady stál se stádem brahmín, a u mají dvì nohy nebo ètyøi.}
{249}{}{Torr milovat }
{250}{}{. Torr milovat máma. Torr milovat táta. (Jsem opravdu rád, e jsi mì zachránil. U jsem myslel, e to nepøeiju.)}
{251}{}{. Torr milovat máma. Torr milovat táta.}
{252}{}{Torr dobrá. (To nic nebylo, urèitì bys udìlal to samé i pro mì. Chci se ještì na nìco zeptat.)}
{253}{}{Torr hehehe. (No, vypadal jsi opravdu srandovnì, kdy tì ten robot drel v šachu. Pøíštì si dávej vìtší pozor. Sbohem.)}
{254}{}{Torre, buï opatrnìjší, ano? Sbohem, Torre.}
{255}{}{Nemáš ani páru, co ti øíkám, co? Kvùli tobì bylo málem bylo po mnì, blbeèku. Sbohem a doufám, e u tì nikdy neuvidím.}
{260}{torr30}{Broukochlap zlá. Torr bát.}
{261}{torr31}{Torr vidìt broukochlap bít bùbù.}
{262}{torr32}{Bùbù bít!}
{263}{torr33}{Brokochlap chodit z kaòon.}
{264}{torr34}{Torr vidìt mrtvá broukochlap.}
{265}{torr35}{Hehehe.}
{266}{torr36}{Leonard?}
{267}{torr37}{Duntoni zlá.}
{268}{torr38}{Maso mòam.}
{269}{torr39}{Torr silná.}
{270}{torr40}{Ook?}
{271}{torr41}{Zugzug.}
{272}{torr42}{Blabla?}
{273}{torr43}{Arroyo?}
{274}{torr44}{Muset èùrat.}
{275}{torr45}{Ahoj.}
{276}{torr46}{Ahoj.}
{277}{torr47}{Torr!}
{279}{}{Torr vidìt }
{280}{}{! (Vítej, pøíteli. Mùu ti s nìèím pomoct?)}
{281}{}{ vídìt Torr! (No, vlastnì se tì chci zeptat na pár vìcí.)}
{282}{}{Torr, ahoj. (Tìší mì, e tì zase vidím, Torre, ale jenom tudy procházím. Mìj se.)}
{300}{torr49}{Torr jít pro pomoc! (Torr zmizel v temnotì a nechal tì s bùbù, eh, s brahmínami.)}
{301}{torr50}{Brouka mrtvej. Bùbù v bezpeèí. Torr dìkovat.}
{400}{torr51}{Ty pomoct Torr. Bùbù na pole (ukáe na vıchod) támhle teï? (usmìje se) (Díky za pomoc, budu ji potøebovat.)}
{401}{torr52}{Ty pomoct Torr. Bùbù na pole (ukáe na vıchod) támhle teï? (usmìje se)}
{402}{}{ pomoct Torr. (Pùjdu s tebou na pastvinu na vıchod od mìsta.)}
{404}{}{Pomùu ti ohlídat brahmíny, Torre.}
{405}{}{Teï ti s hlídáním nemùu pomoct, Torre.}
{500}{torr53}{Pøestat bít bùbù.}
{501}{torr54}{Torr pomoct bùbù.}
{502}{torr55}{Zlej enská! Zlej! Nebít bùbù!}
{503}{torr56}{Jít pryè, zlá chlap.}
{504}{torr57}{Zlej enská! Zlej! Jít pryè!}
{505}{torr58}{Zlá chlap, zlá! Nebít bùbù!}
{506}{torr59}{Nebít Torrova bùbù!}
{507}{torr60}{Torr jít zachránit bùbù!}
{600}{torr61}{Torr dìkovat. Torr teï fajn. Ty jít.}
{700}{torr62}{Obchoïák? V Kamat? Ik v Den. (Obchodník v Klamathu? Ale jo, Vic prodává nìjaké staroitnosti, ale momentálnì není ve mìstì. Myslím, e obchoduje v Denu, kterı leí na jih odtud.)}
{701}{}{Groo! (Díky moc, Torre. Co jsi to øíkal o tìch predátorech?}
{702}{}{Grok! Torr! (Díky moc, Torre. Jsi dobrı mu. Bohuel musím odejít, ale pøeju ti hodnì štìstí pøi chování dobytka. Sbohem, pøíteli Torre.)}
{800}{}{Torr byl zachránìn.}
