{100}{}{Vidíš pohledného mladého muže.}
{101}{}{Vidíš Davina.}
{102}{}{Vidíš mladého muže, kterému je kolem dvaceti let. Je podobný Grishamovi.}
{150}{davin1}{Jestli chceš, mùžeš mì mít.}
{151}{davin2}{Uff! Miria není v posteli tak dobrá.}
{152}{davin3}{Nevìøím, že jsi mì zneužil.}
{153}{davin4}{Pøíštì to zkusíme ve tøech.}
{154}{davin5}{Ooo... ten je roztomilej.}
{155}{davin6}{Zeptej se jí.}
{156}{davin7}{To bylo skvìlé. Kdo je další?}
{157}{davin8}{Ahoj! Jmenuju se Davin. Pomáhám svému otci na jatkách v Modocu.}
{158}{}{Hledám Corneliovy zlaté hodinky. Nevidìl jsi je nìkde?}
{159}{}{Co na jatkách pøesnì dìláš?}
{160}{}{Kolují tady nìjaké povídaèky o tom, co dìláš s brahmínami.}
{161}{}{Povìz mi o svém otci.}
{162}{davin9}{Zdravím.}
{163}{davin10}{Vìdìl jsem, že se ke mnì vrátíš.}
{168}{}{Neudìláme si trochu pohodlí?}
{171}{}{Zùstaò tady.}
{172}{davin11}{Jistì, mám èas. Ptej se.}
{178}{davin12}{Ne, nikde jsem je nevidìl.}
{179}{}{Mùžu se ještì na nìco zeptat?}
{180}{davin13}{No, já eh... vlastnì, já... jen dohlížím na vìci. Koneckoncù jsem syn majitele. Všechno to tady zdìdím, až mùj otec zaklepe baèkorama.}
{182}{davin14}{To je lež. V noci chodím do stájí, abych... se pøesvìdèil, že je všechno zamèené. To víš, všude je plno divoké zvìøe.}
{184}{davin15}{Otec provozuje jatka. Jako otec je celkem dobrý. Ale dám ti jednu radu, jestli s ním chceš dìlat nìjaký obchod. Vìtšinou je v tom nìco víc, než se na první pohled zdá.}
{186}{davin16}{Pøijï za mnou, až si budeš chtít zase... popovídat.}
{187}{davin17}{Páni, nikdy bych nevìøil, že mì bude svádìt taková krasavice, jako jsi ty. Poèkat! Ty nejsi ženská! Ale neboj, jsi tak krásný, že o tom budu mlèet když ty taky.}
{188}{davin18}{To se mi snad jen zdá. Nemùžu uvìøit, že mì svádí taková krasavice. Chceš mì svést, že jo?}
{189}{}{Pohled tvých oèí je tak andìlský. Nekažme kouzlo tohoto okamžiku slovy. Nechme mluvit naše èiny.}
{190}{}{Pøestaò mluvit, pokazíš to. Jen seï a užij si to.}
{191}{}{Asi došlo k omylu, chci se jen na nìco zeptat.}
{192}{}{Díky za nabídku, ale radìji ne. Ehm... už musím jít.}
{193}{davin19}{Ach bože! Vem si mì! Chci tì teï hned! (Strhne ze sebe svoje obleèení, poté tvoje... a poté... použij svojí pøedstavivost.)}
{194}{davin20}{(Hihòá se.) "Jsem hotovej"! Ty mùžeš být pøíštì.}
{195}{}{(O dvì hodiny pozdìji: Zem se pohnula a tahle postel už nebude nikdy jako døív.)}
{196}{}{(O hodinu pozdìji a nejlepším orgasmu tvého života.)}
{197}{}{(O pùl hodiny pozdìji: Vyèerpáním nemùžeš pohnout ani prstem na noze.)}
{198}{}{(Za patnáct minut a pár vzdychù pozdìji.)}
{199}{}{(Dostala ses až k sundávání trika a pak sis uvìdomila, že už to vlastnì nechceš.)}
{200}{}{Musím jít. Nashle.}
{400}{davin21}{Otèe!}
{401}{}{A sakra!}
{402}{davin22}{ANO!}
{405}{davin23}{Strýèku Biffe!}
{410}{}{Eh...}
{411}{}{Eh... pokraèujte prosím...}
{412}{}{Tak urèitì...}
{413}{}{Eh... ano.}
{450}{davin24}{Eh, se mnou bys teï nemìl mluvit.}
{500}{davin25}{Ajéje, budu to tu mít na starost.}
{1000}{davin26}{Ano, zlato moje?}
{1001}{davin27}{Co pro tebe mùžu udìlat, miláèku?}
{1005}{}{Ty to nechápeš. Prostì nechci, aby ses na mì tak lepil, když nìkam jdeme.}
{1006}{}{Tvojí chybou je, že chci, abys mi nedýchal na záda.}
{1007}{davin28}{Ale... ale... co dìlám špatnì?}
{1008}{davin29}{Copak potøebuješ, drahoušku?}
{1009}{}{Díky, stejnì to zaèalo bejt na prd. A co teï, lásko??}
{1010}{davin30}{Na jatkách jsem stahoval kùži z brahmín, takže to s noži docela umím. Táta mì taky jednou nechal umlátit brahmínu páèidlem, takže když bude potøeba, mùžu použít kyj. Ehh, jo a jednou mì táta nechal vystøelit z pistole, ale docela mì to vydìsilo a málem jsem ho omylem zastøelil.}
{1020}{}{Potøebuju trochu víc místa, Davine.}
{1100}{davin31}{Už jsem úplnì vyléèená a pøipravená vyrazit.}
{1200}{davin32}{Už mám jen pár škrábancù.}
{1300}{davin33}{No, jsem témìø zdravý, ale budu potøebovat další léky, až bude pøíležitost.}
{1400}{davin34}{Vyléèila jsem se, jak jen to šlo, ale poøád jsem dost zranìná.}
{1500}{davin35}{Ne, brouku. Chci jít s tebou.}
{1600}{davin36}{Jistì, dám to pryè.}
{1700}{davin37}{Dobøe, jsem poøád hned za tebou.}
{1800}{davin38}{Pak tì ale nebudu moct chránit. Ne, radši budu poblíž.}
{1900}{davin39}{Takhle? V žádném pøípadì. Nespustím tì z oèí, ty mùj kvítku medový.}
{2000}{davin40}{Jauvajs, asi jsem si nìco zlomil. Mùžeš mi to pofoukat?}
{2001}{davin41}{Fuj, cítím se, jako kdybych hoøel. Asi jsem ozáøený.}
{2002}{davin42}{Fuj, je mi špatnì. Asi jsem otrávený.}
