{100}{}{Vidíš velmi èilého starého mue.}
{101}{}{Vidíš Grishama.}
{102}{}{Nedokáeš si vzpomenout, ale pøijde ti povìdomı.}
{151}{grish57}{Øíkal jsem, e tì dostanu!}
{152}{grish58}{Chachachacha!}
{153}{grish59}{Jdi pryè!}
{154}{grish60}{Mám práci!}
{155}{grish61}{Vìdìl jsem, e je na mı dceøi nìco divnıho.}
{156}{grish62}{Nìkdo má rád holky, jinı zase vdolky...}
{157}{grish63}{Myslím, e budu zvracet.}
{158}{grish64}{Vìdìl jsem, e je na mım synovi nìco divnıho.}
{159}{grish65}{Dobøe se o moji dcerku starej.}
{160}{grish66}{Tak a teï patøíš do rodiny.}
{161}{grish67}{Dobøe se o mıho synka starej.}
{162}{grish1}{Jmenuju se Grisham. Vítej na mıch jatkách. Pøicházíš s nìèím nebo pro nìco?}
{163}{}{Spíš pro nìco. Chci si koupit nìjaké zásoby na cestu.}
{164}{}{Èistì náhodou, nevidìl jste tu nìkde leet zlaté hodinky?}
{165}{grish2}{Co pro tebe mùu udìlat?}
{166}{}{Chci si koupit vaše povìstné sušené maso.}
{168}{}{Mùete mi øíct nìco o vašich jatkách?}
{169}{}{Koukám, e sucha nemají vliv na vaše obchody.}
{170}{grish3}{Já vìdìl, e to zvládneš. Take, dluím ti $1000 za dobøe odvedenou práci. Kolik e to padlo díky tvé nedbalosti kusù? }
{171}{}{. $100 je za jednu brahmínu, to dìlá celkem $}
{172}{}{. Jo a nezkoušej mi lhát o poètu zabitejch brahmín. Jeden z mıch chlapcù tì tajnì z dálky sledoval.}
{173}{}{Nikdy jste nemluvil o poplatku za mrtvé brahmíny!}
{174}{}{Ty intrikánskej, vyschlej, starej dìdku. Ááá! Pamatuj si tyhle slova... tohle je naposledy, co jsi mì takhle podvedl!}
{175}{}{Díky, tako. Je radost s vámi obchodovat.}
{176}{grish4}{Jak se tady opovauješ ukazovat? Díky tvojí zbabìlosti jsem pøišel o deset brahmín. Jestli se mi chceš omluvit, tak mi zapla $1500. To bude staèit na pokrytí mıch ztrát.}
{177}{}{Ty brahmíny nemìly vìtší cenu jak $1000.}
{178}{}{Tolik penìz nemám a i kdyby ano, nedám je takovému podvodníkovi, jako jste vy.}
{179}{}{Nechal jsem peníze ve svém pokoji. Dojdu pro nì.}
{180}{grish5}{Aha, no samozøejmì, samozøejmì. Take, na cesty ti mùu doporuèit naše proslulé sušené plátky z brahmín. Nezkazí se a jsou velmi dobré. Jen $10 za balíèek. Máš zájem?}
{181}{}{To zní dobøe. Dejte mi jedno balení.}
{182}{}{Ne, díky. Moná pozdìji. Ale chci se vás ještì na nìco zeptat.}
{183}{grish6}{Bylo mi potìšením s tebou obchodovat. Mùu pro tebe ještì nìco udìlat?}
{185}{grish7}{Poèkej! Zdá se, e máš velké zkušenosti s cestováním. Nechceš si vydìlat nìjaké peníze?}
{186}{grish8}{Opravdu si nechceš pøivydìlat? Myslím, e nìkdo jako ty by mùj problém lehce vyøešil.}
{187}{}{No, to záleí na tom, co je to za práci a hlavnì KOLIK ZA TO DOSTANU.}
{188}{grish9}{Chytrost ti nechybí! Pøipomínáš mi, jakej jsem byl za mlada. Je to jednoduchı. Stahujou se sem z hor divocí psi a hledají jídlo. Pro psy jsou brahmíny snadná koøist, take kadou noc napadají moje stáda. Pobij je a zaplatím ti $1000.}
{189}{}{Mám pocit, e pøede mnou nìco skrıváš, ty starej mazáku. V èem je háèek?}
{190}{grish10}{Haha, jsi jako liška, nic ti neujde. Vìdìl jsem, e to na tebe nemám zkoušet. Háèek je v tom, e za kadou zabitou brahmínu ti strhnu $100. Platím dobøe za dobrou práci a za chyby zase platíš ty. To je risk, kterı musíš pøijmout, kdy pracuješ pro mì.}
{191}{grish11}{Dobøe! Jdi v noci na pastviny a zabij smeèku divokıch psù, kteøí napadají moje brahmíny. Vra se, a bude práce hotová.}
{192}{grish12}{No to mì teda podr! Cornelius poøád hledá ty svoje hodinky? Proè se nesmíøí s tím, e u jsou prostì pryè? Ty mizernı hodinky stejnì nikdy nešly a vsadím boty na to, e stejnì nebyly zlatı. Vzdej to, nikdy je nenajdeš.}
{193}{}{Vlastnì ano, dohodli jsme se s Farrelem, e se po nich podívám.}
{194}{}{Mùu se ještì na nìco zeptat?}
{195}{}{Díky, ale radìji budu hledat dál.}
{196}{grish13}{Ne? Urèitì? Pøísahám, e jsem ti... pøíštì se nejdøív zeptej na detaily, ne vezmeš nìjakou práci. A teï mì omluv, mám ještì nìjakou práci.}
{197}{grish14}{Hehehe. No, pøijde na to. Zùstaneš ve mìstì dıl? Buahahaha!}
{198}{grish15}{Vidím, e nejsi ádnej hlupák. Dobøe. $1000 a jsme vyrovnanı. Ruku na to.}
{199}{}{[POTØÁST SI RUKOU S GRISHAMEM]}
{200}{}{Tak moment. Kdy o tom tak pøemıšlím, ty brahmíny byly pìknì vychrtlé. Co takhle $750?}
{201}{}{Ale ne, mìním názor. Nezaplatím vám.}
{202}{grish16}{(Široce se na tebe usmìje.) Rád vidím èlovìka s charakterem.}
{203}{grish17}{(Grisham zrudne a procedí skrz zaaté zuby.) Dobøe, tak teda $750. A teï mi dej ty prachy!}
{204}{}{Víte, $750 je poøád trochu moc. Ty brahmíny by stejnì chcíply, i kdyby je psi neserali. Ale nejsem úplnı lakomec, dám vám $50.}
{206}{grish18}{FAJN! TAK MI DEJ TY PRACHY A VYPADNI!}
{207}{}{[ODEJÍT BEZ ZAPLACENÍ]}
{208}{grish19}{Však on ti to jednou nìkdo oplatí.}
{209}{grish20}{(Grisham se na tebe smìje tak, e radìji o krok ustoupíš.) Radši si ty peníze nech. Mám pocit, e je budeš pozdìjc potøebovat.}
{210}{grish21}{No a co chceš vlastnì slyšet? Provozuju jatka v Modocu. Jestli chceš nìco porazit, pøiveï to ke mnì, já to zabiju a udìlám z toho nejlepší sušenı maso široko daleko.}
{211}{}{A co dìláte s kùí a vnitønostmi?}
{213}{grish22}{Vlastnì mi to dokonce pomáhá. Nikdo nemá dost potravy pro svoje brahmíny, take se jejich stáda zmenšujou. Ale je to jen doèasnı. Vìtší problém je v tom, e díky sniování stavu brahmín pùjdou moje obchody z kopce.}
{215}{grish23}{(Grisham projde kolem tebe, nìkolikrat do tebe šouchne, poté ti otevøe ústa a prohlédne si tvoje zuby.) Á! Pìknı, zdravı exempláø. Na tuhle práci se hodíš. Poslouchej... zlí pejskové zabíjí hodné brahmíny. Jdi zabít zlé pejsky pro kamaráda Grishama. Grisham ti dá velkou odmìnu. Rozumíš?}
{216}{}{Ne, já mít rád pejsky. Jenom zlá lidi nemít rádi pejsky. Já jít pryè od zlá mu.}
{217}{}{Já to udìlat. Jít teï tam!}
{218}{grish24}{Dobøe! Pamatuj si, zlá zvíøátka dìlají 'Haf! Haf!', hodná zvíøátka dìlají 'Bùùù.' Sna se nezabít ta hodná.}
{219}{grish25}{Zdá se, e nemáš moc penìz. Na dluh nedávám a zadarmo u vùbec ne.}
{221}{grish26}{Ach jo. To mám za to, e jsem tam poslal neandrtálce. Zmiz odsud!}
{222}{grish27}{Eh... unga bunga. Vezmi si peníze, buï hodnı neandrtálec a odejdi.}
{223}{grish28}{Nechodíš kolem horké kaše, e? Dobøe, povím ti to, kdy se ptáš. Mùeš si z mrtvoly vzít cokoliv. Balthus obvykle vykupuje kùe a Róza koupí jakékoliv vnitønosti, které nepotøebuješ. Dìlá z toho polívku pro svoje psy.}
{225}{grish29}{Dìláš si legraci? Kadej ví, e ty hodinky ukradl Farrel. Proè by tì jinak poádal o jejich nalezení... ledae by je opravdu neukradl! Nebo je to moná trik, aby všechny pøesvìdèil, e to neudìlal. Budu o tom pøemıšlet.}
{228}{grish30}{Hele, ani se mi to nepokoušej vysvìtlit. Nechci to slyšet. Seenu knìze, udìláme z toho právoplatnej svazek a ty odejdeš i s mım synkem.}
{229}{grish31}{Nemùu øíct, e mì to ani trochu nepotìšilo, ale nemùu ji nechat ít v tomhle domì potom, co jsem vidìl... musíte se vzít a odejít odsud.}
{230}{grish32}{Nechceš mi vysvìtlit, co tu dìláš s mojí dcerkou?}
{231}{grish33}{Nechceš mi vysvìtlit, co tu dìláš s mım synkem?}
{232}{}{Vysvìtlím vám to, tako. Víte, jsou ptáèkové, vèelièky...}
{233}{}{Jsem lékaø a jen jsem jí dìlal kompletní prohlídku.}
{234}{}{Jsem lékaøka a jen jsem mu dìlala kompletní prohlídku.}
{235}{}{Není to tak, jak si myslíte.}
{236}{grish34}{No to je skvìlı. Budu mít za zetì chytráka. Tak pojï, synku... a u je to za náma.}
{237}{grish35}{No to je skvìlı. Budu mít za snachu chytraèku. Tak pojï, dcerko... a u je to za náma.}
{238}{grish36}{Já si myslím, e jste si s mojí dcerou hráli na brahmíny v dobì páøení.}
{239}{grish37}{Já si myslím, e jste s mım synem tancovali pod peøinami horizontální tango.}
{240}{}{No, moná to tak vypadá, ale byl to jenom sex. Není v tom ádná láska nebo nìco takového.}
{241}{grish38}{Rozumím moc dobøe. Hormony a jaro dìlaj svoje.}
{242}{}{Jsem rád, e mì chápete.}
{243}{grish39}{Rozumím. Je ti doufám jasnı, e se teï musíte vzít? Nemùeme si tu dovolit pomluvy, víš. Take teï pùjdeme spolu za knìzem. A nechtìj, abych do tebe musel nasypat broky.}
{244}{grish40}{Opravdu? Tak proè jste byli oba nazí?}
{245}{}{Mikroby! Chci øíct, MIKROBY! Pøi takovıch vyšetøeních je tøeba dodrovat absolutní èistotu.}
{246}{grish41}{No, jestli jsi doktor, tak je to v poøádku. Ale radši se oblíkni. Z nedorozumìní lehce vznikaj rùznı pomluvy. A kdy u tu jseš, podívej se na moji øi... hroznì mì v ní bolí.}
{247}{}{Eh... podívám se na to pozdìji. Teï na mì èeká další pacient. Nashle.}
{248}{grish42}{Jasnì. Teï se mnou pùjdeš za knìzem. A nedìlej blbosti, nebo budeš potøebovat doktora.}
{260}{grish43}{Já vìdìl, e to zvládneš. Myslím, e ti dluím $1000 za dobøe odvedenou práci. Tady jsou.}
{300}{grish68}{Co se to tady sakra dìje?}
{301}{}{Ehhh... pane, jen jsem...}
{302}{grish69}{Okamitì z ní sundej ty svoje špinavı pracky...}
{350}{}{(Vrhneš pohled na Bessy.) S nìèím.}
{360}{}{Neudìlal byste pro mì trochu sušeného masa?}
{400}{grish70}{Co se to tady dìje?}
{402}{grish71}{Do prdele! Já vìdìl, e s }
{403}{grish72}{Jak se opovauješ pošpinit èest }
{404}{grish73}{Eh, Jo, nemùeme tu pøísahu prostì pøeskoèit?}
{406}{grish74}{Chlapèe...}
{407}{grish75}{Sleèinko...}
{410}{grish76}{Nechtìj, abych udìlal z }
{412}{grish77}{Mirie}
{413}{grish78}{Davina}
{414}{grish79}{Eh, Bo, nemùeme tu pøísahu prostì pøeskoèit?}
{420}{grish80}{Nikam nepùjdeš, chlapèe!}
{421}{grish81}{Nikam nepùjdete, sleèinko!}
{452}{grish82}{ není nìco v poøádku. Teï u zbıvá jen jedinej zpùsob, jak to napravit!}
{453}{grish83}{?! Existuje jen jedinej zpùsob, jak to napravit!}
{460}{grish84}{ vdovu.}
{461}{grish85}{ vdovce.}
{500}{grish44}{No to je ale pìknı zviøátko. Bude z nìj vıbornı sušenı maso. Poslouchej, udìláme to takhle. Pøipravím ti prvotøídní sušenı maso a nechám si z nìj pár kouskù jako odmìnu za práci. Co ty na to?}
{501}{}{Nikdy! Miluju Bess. Nikdo z ní sušené maso dìlat nebude.}
{502}{}{To zní dobøe. Kdy se mùu zastavit pro to sušené maso?}
{503}{}{Na to zapomeòte, dìdo. Odcházím.}
{510}{grish45}{Aha... ty tu brahmínu nemáš jenom tak... nechtìl jsem ti brát tvoje 'potìšení'. Noci v poušti by bez ní byly hroznì osamìlı, co? Na tohle opravdu nemám èas, mám práci.}
{515}{grish46}{Vıbornì! Pøijï tak za tıden. Maso si mùeš vyzvednout v udírnì hned u jatek. Nechám ho tam pro tebe v pytli. Bylo mi potìšením s tebou obchodovat.}
{600}{}{Nazdar }
{601}{}{Ááá, jestlipak to není }
{602}{}{Ehmm, je mrtvı.}
{603}{}{Ehmm, je mrtvá.}
{604}{}{Miria byla naivu, kdy jsme se rozešli, ale myslím, e teï u bude urèitì mrtvá.}
{605}{}{Davin byl naivu, kdy jsme se rozešli, ale myslím, e teï u bude urèitì mrtvı.}
{606}{}{Davin... ehm, nemohl se mnou jít, ale vyøídím mu tvùj pozdrav, a ho zase uvidím.}
{607}{}{Miria... ehm, nemohla se mnou jít, ale vyøídím jí jak moc ji milujete, a ji zase uvidím.}
{700}{grish47}{Ááááá... (Grishama popadne šok, poté se najednou chytí za prsa a zhroutí se na zem.)}
{750}{grish48}{Musím zpátky do práce. Uvidíme se pozdìji.}
{800}{}{Grishamovy brahmíny byly ochránìny.}
{1101}{}{Vidíš strıèka Biffa.}
{1155}{grish86}{Vìdìl jsem, e je na mojí neteøi nìco divnıho.}
{1156}{grish87}{Nìkdo má rád holky, jinı zase vdolky...}
{1157}{grish88}{Ještì, e se toho starej Grisham nedoil.}
{1158}{grish89}{Vìdìl jsem, e je na mım synovci nìco divnıho.}
{1159}{grish90}{Tak a teï patøíš do rodiny.}
{1160}{grish91}{Dobøe se o moji neteø starej.}
{1161}{grish92}{Dobøe se o mıho synovce starej.}
{1228}{grish49}{Hele, ani se mi to nepokoušej vysvìtlit. Nechci to slyšet. Seenu knìze, udìláme z toho právoplatnej svazek a ty odejdeš i s mım synovcem.}
{1229}{grish50}{Nemùu øíct, e mì to ani trochu nepotìšilo, ale musím udìlat to, co by si Grisham pøál... musíte se vzít a odejít odsud.}
{1230}{grish51}{Nechceš mi vysvìtlit, co tu dìláš s mojí neteøí?}
{1231}{grish52}{Nechceš mi vysvìtlit, co tu dìláš s mım synovcem?}
{1232}{}{Vysvìtlím vám to, strıèku Biffe. Víte, jsou ptáèkové, vèelièky...}
{1236}{grish53}{No to je skvìlı. Budu mít v rodinì chytráka. Tak pojï, synovèe... a u je to za náma.}
{1237}{grish54}{No to je skvìlı. Budu mít v rodinì chytraèku. Tak pojï, neteøi... a u je to za náma.}
{1238}{grish55}{Já si myslím, e jste si s mojí neteøí hráli na brahmíny v dobì páøení.}
{1239}{grish56}{Já si myslím, e jste s mım synovcem tancovali pod peøinami horizontální tango.}
{1403}{grish93}{Jak si dovoluješ pošpinit èest Grishamova potomka, }
{1412}{grish94}{jeho dcery?}
{1413}{grish95}{jeho syna?}
{1600}{}{. Doufám, e se dobøe staráš o moji dcerku Miriu. Ona je svìtlo mého ivota a zlomilo by mi srdce, kdyby se jí nìco stalo. Mimochodem, kde je? Doufal jsem, e ji zase uvidím.}
{1601}{}{. Tak jak se ti zamlouvá manelskej ivot? Vidím, e Davin s tebou necestuje. Moc mi chybí. Vezmi ho s sebou, a pøijdeš pøíštì na návštìvu. Starıho mue to potìší, kdy zase uvidí svıho jedinıho synka.}
