{100}{}{Vidíš vùdce Svìtloplachù.}
{101}{}{Vidíš Vegeira.}
{102}{}{Vysokı, statnı mu. Jeho pohyby ti pøipomínají koèku èíhající na svou koøist.}
{150}{veger30}{Mùeš odejít padacími dveømi v zadní èásti budovy.}
{151}{veger31}{Prosím, doruè tu zprávu do Modocu.}
{152}{veger32}{Modoc leí na jihu.}
{153}{veger33}{Jih.}
{154}{veger34}{Ne, ten druhı jih.}
{155}{veger1}{Á, návštìvník, právì vhod. Uvaoval jsem o zpùsobu, jak kontaktovat lidi na povrchu, ale díky tvému pøíchodu se tím u nemusím zabıvat. Vítej v sídle Svìtloplachù.}
{156}{veger2}{Dobøe, e jsi zpìt. Pøedpokládám, e byla zpráva doruèena do Modocu. Jak ji pøijali?}
{157}{}{Potøebují èas na rozmyšlenou.}
{158}{}{Mají nìjaké vıhrady.}
{159}{}{Chci vzít Jonnyho domù k rodièùm.}
{160}{veger3}{Chceš nám tedy pomoct?}
{161}{}{Nejdøív se tì chci na nìco zeptat.}
{162}{}{Odpovìï je stále NE.}
{163}{}{Moje rozhodnutí je, e vám pomùu.}
{165}{veger4}{Díky za pomoc. Vdy tì tu rádi uvítáme. A za tvé sluby ti nabízím tuto odmìnu. (Vegeir ti podá útoènou pušku.)}
{166}{veger5}{Díky za pomoc. Vdy tì tu rádi uvítáme.}
{167}{}{Mohl by se Jonny vrátit domù k rodièùm?}
{168}{veger6}{Omlouvám se za nepøíjemné okolnosti, za kterıch se potkáváme. Obvykle by se tì snaili Ochránci zastrašit. Chøestìní øetìzù a zoufalı náøek vìtšinou kadého zaene pryè, ale teï mají pøíkazy, aby ke mnì pøivedli kadého ze shora, na koho narazí.}
{169}{}{To je v poøádku. Já u pùjdu.}
{170}{}{Co ode mnì chcete?}
{171}{}{Duchové?}
{172}{veger7}{Pùjdeš, A ti to dovolím. Døív NE.}
{173}{veger8}{Jednoduchı úkol. Potøebujeme se spojit s mìstem na jihozápadì. Domnívám se, e se jmenuje "Modoc". Udìláš to pro nás?}
{174}{}{A co z toho budu mít?}
{175}{}{Chci se zeptat na pár vìcí, ne tenhle úkol pøijmu.}
{176}{veger9}{Tak dobøe. Ani bych neoèekával, e od cizincù jen tak pøijmeš úkol, ani bys o nich nìco vìdìl. Ptej se, povím ti všechno, co vím.}
{177}{}{Proè nepošlete nìkoho z vašich lidí, aby doruèili zprávu?}
{178}{}{Povìz mi o tvıch lidech.}
{179}{}{Jaká je vaše obrana?}
{180}{}{To u by staèilo. Chci se rozhodnout.}
{181}{veger10}{Ptej se.}
{190}{}{Proè jste se vrátili na povrch?}
{191}{}{Proè ta velká maškaráda s duchy na povrchu?}
{192}{}{Co je úèelem té zprávy?}
{194}{veger11}{Od Uzavøení jsme se jako lidé zmìnili. Jen málo z nás dokáe snést pobyt na povrchu, protoe nejsme zvyklí mít nad sebou èerné moøe nicoty. Hrùza z pádu vzhùru je pro nás tak silná, e leíme úplnì pøimraení k zemi, neschopni pohybu. Ale to není ten hlavní dùvod. Nikdo z nás nedokáe vydret to jasné svìtlo, které vy nazıváte Slunce. Díky dlouhodobému ivotu pod zemí jsou naše oèi pøíliš citlivé na svìtlo. Nemùeme cestovat daleko od bezpeèí našich domovù pod zemí.}
{195}{}{Mùu mít ještì pár otázek?}
{197}{veger12}{Kdysi dávno jsme byli jako lidé na povrchu. Také jsme ili nad zemí, dokud poár nezachvátil svìt. Naši pøedci, je byli souèástí tajné domobrany, se uzavøeli se svımi rodinami tady dole, aby se zachránili. Celé generace jsme ili zde, bezpeènì ukryti v lùnì Matky Zemì.}
{200}{veger13}{Poèet našich obyvatel od Uzavøení stále stoupal. Brzy bylo jasné, e nemùeme dále pøeít bez dalších zásob. Tak byla Peèe rozlomena a my jsme se znovu vydali na povrch, abychom pøeili.}
{203}{veger14}{Pøed lety se nìkdo pokoušel pøevzít naši farmu, sklízet plodiny a krást naše zvíøata. My nejsme od pøírody násilníci, ale bylo nutné s tím nìco udìlat. Vdy na tìchto sklizních záleelo naše pøeití. A tehdy jsme si vymysleli duchy. Po natøení se svìtélkujícími houbami jsme mohli krásnì odstrašit zlodìje a další slídivé sousedy. Bohuel to bylo a pøíliš úèinné. V poslední dobì jsme se snaili kontaktovat lidi ijící na povrchu, ale nikdo u na farmu nechodí kvùli strachu z duchù. Naštìstí jsi tu teï ty.}
{206}{veger15}{Tak dost! U ádné další otázky. Rozhodni se hned!}
{207}{}{Je mi líto, ale nemùu vám pomoct.}
{208}{}{Ano, s radostí doruèím vaši zprávu do Modocu.}
{209}{veger16}{To nerad slyším. Prosím, povauj se za hosta Svìtloplachù. A se nám podaøí navázat kontakt s lidmi na povrchu, budeš moct odejít. Do té doby se nepokoušej opustit jeskynì, následky by byly nepøíjemné.}
{210}{veger17}{Produkce potravin pøekraèuje naše potøeby díky dokonèení novıch zavlaovacích systémù. Rádi bychom zaèali obchodovat s lidmi nahoøe a vymìnili své pøebytky potravin za potøebné léky.}
{213}{veger18}{Prosím, sdìl nám své rozhodnutí.}
{216}{veger19}{Vìdìl jsem, e nás pochopíš. Zde je zpráva obsahující naše poadavky. Prosím, doruè ji do Modocu a pøedej pøíslušné osobì. A ten úkol dokonèíš, vra se zpìt. Øeknu Ochráncùm, aby oèekávali tvùj návrat. Dìkujeme ti za tuto slubu.}
{217}{veger20}{Jak typické pro lidi z povrchu. Nikdy neudìlají nic pro druhého, pokud z toho nemají osobní prospìch. Samozøejmì nemùeme vìøit nìkomu, jako jsi ty. Najdeme tedy nìkoho jiného, kdo doruèí zprávu. Aèkoliv nejsme násilníci, nepokoušej se opustit jeskynì, jinak toho budeš litovat.}
{218}{veger21}{Hmm... chápu. Takové rozhodnutí není jednoduché. Informuj mì prosím o jakékoliv novince.}
{219}{veger22}{V tom pøípadì mì u neobtìuj.}
{220}{veger23}{Jaké?}
{221}{}{Nevìøí vám. Myslí si, e zabíjíte kolemjdoucí a nabodáváte jejich tìla na kùly pøed farmou.}
{222}{}{Chtìjí vìdìt, co se stalo farmáøovi, kterı tady il.}
{223}{veger24}{Jsme mírumilovní lidé a nikoho jsme nezabili. Ty tìla jsou jenom atrapy, které jsme vyrobili, abychom zastrašili zlodìje. Kdy si je pozornì prohlédneš, zjistíš, e to jsou jen figuríny obalené brahmíními vnitønostmi.}
{224}{}{A co chudák Karl? Ten farmáø, kterı il na farmì?}
{225}{veger25}{Tak se jmenoval? Karl? My jsme ho jen vystrnadili z farmy, nic víc. Pøedpokládám, e se vrátil domù, kdy zjistil, e na farmì straší. Ochránci ho vidìli jít na západ. Mùeš ho tam jít zkusit hledat.}
{226}{}{Dobrá, budu vás informovat o novinkách.}
{227}{veger26}{My jsme ho jen vystrnadili z farmy, nic víc. Pøedpokládám, e se vrátil domù, kdy zjistil, e na farmì straší. Ochránci ho vidìli jít na západ. Mùeš ho tam jít zkusit hledat.}
{231}{veger27}{Vidím, e ses setkal s Jonnym. Nalezli jsme ho, kdy bloudil v temnotách jednoho z našich nejhlubších tunelù. Øíkal, e spadl do vyschlé studny u svého domova a pak byl uvìznìnı v tunelu poblí zavaliny. Starali jsme se o nìj jako o vlastního a všichni ho tady mají rádi, take chápeš, e jsem opatrnı, kdy ho mám svìøit cizinci, kterı mi ještì neprokázal svoji dùvìryhodnost. Vrátím Jonnyho, a se ujistím, e se bezpeènì dostane domù.}
{232}{veger28}{Mám v tobì ji plnou dùvìru. Pøestoe zde budeme malého Jonnyho velmi postrádat, pøipravili jsme pro vás dva doprovod do Modocu.}
{233}{veger29}{Propána! ádnı div, e tì naše malé triky nevydìsily. Jsi pøíliš hloupı na to, ne aby tì nìco takového vydìsilo. Nerad se spoléhám na takto mentálnì zaostalé jedince, ale potøebujeme tvoje sluby. Doruè tuto zprávu do Modocu. Pøedej ji vùdci Modocu a zkus se pøi tom neztratit.}
{300}{}{U pùjdu.}
{301}{}{Co ode mnì chcete?}
{302}{}{Èau.}
{303}{}{Duchové?}
{400}{}{Zpráva byla pøijata kladnì. Obyvatelé Modocu chtìjí obchodovat s tvımi lidmi.}
{401}{}{Modoc happy. Trade good!}
