{100}{}{Vidíš Velkého Jeíše Mordina.}
{150}{}{Vidíš tlustého mue s èernıma oèima. Tìce dıchá a je celı zpocenı.}
{151}{}{Vidíš Velkého Jeíše Mordina. Tìce dıchá a je celı zpocenı.}
{200}{bgjes1}{Tam nemùeš.}
{201}{bgjes2}{To... to ti nepatøí.}
{202}{bgjes3}{Ještì jednou se toho dotkni a skonèíš... v Golgotì.}
{210}{bgjes4}{::Vzzz hvízd::}
{211}{bgjes5}{*Kuc* *Kuc*}
{212}{}{::Utøe si pot z èela.::}
{220}{bgjes6}{Jsi... *kašel*... mùj nejlepší mu.}
{221}{bgjes7}{Projevují ti lidé v New Renu... *kašel*... dostateènı respekt?}
{230}{bgjes8}{Urgggg...}
{231}{bgjes9}{...Dios mio...}
{232}{bgjes10}{...moje srdce...}
{233}{bgjes11}{hurrkkkk}
{240}{}{(Mu se k tobì otoèí. Vypadá, e má horeèku. Pot mu stéká dolù po tváøi a vytváøí mokré skvrny na obleèení. }
{241}{}{(Ignoruje tì a upøenì se dívá na Myrona. Vypadá to, e èeká, a Myron promluví.)}
{242}{}{(Upøenì se na tebe dívá a vypadá to, e èeká, a promluvíš.)}
{243}{}{[Podívat se na nìj svım nejzlejším pohledem.]}
{244}{}{[Podívat se na nìj s mírnım nezájmem.]}
{245}{}{[Podívat se na nìj pohrdavım pohledem.]}
{246}{}{[Podívat se na nìj s pøedstíranım nezájmem.]}
{247}{}{Odbelhat se.}
{248}{}{Kdo jsi?}
{249}{}{Vy jste Jeíš Mordino?}
{250}{}{Pardon. Asi jsem ve špatné místnosti.}
{260}{bgjes12}{Ty. (Kdy vejde Myron dovnitø, Mordino se na nìj upøenì podívá a v oèích se mu zlovìstnì zablıskne.) Ty jsi... opustil svoje místo. U jsi mi... k nièemu. (Dá pokyn svım stráím, aby vytasily zbranì.)}
{261}{}{(Mu zaène supìt. Dá pokyn svım stráím, aby vytasily zbranì.)}
{262}{}{(Velkej Jeíš zaène supìt. Dá pokyn svım stráím, aby vytasily zbranì.)}
{263}{}{Ááááááááá!}
{264}{}{Vytasit zbranì!}
{265}{}{Bìet!}
{266}{}{Hej! Hej...!}
{267}{}{Hej! Tak moment...!}
{268}{}{Opravdu to CHCEŠ, *Tlusochu?!* Já ti ukáu, kdo JE to }
{275}{bgjes13}{(Mu zaène mluvit sípavım hlasem.) Já... jsem Jeíš Mordino. Ty... mì oslovuj seòore Mordino. (Kapka potu mu steèe z èela.) Co... ode mì potøebuješ?}
{276}{bgjes14}{Ty jsi... zpìt. (Kapka potu mu steèe z èela.) Co... ode mì potøebuješ?}
{277}{}{Hledám práci.}
{278}{}{Mluvil jsem s vaším synem, seòore Mordino. Hledám práci.}
{279}{}{Mluvil jsem s vaším synem, seòore Mordino. Jsem otrokáø a chci vám prodat nìjaké otroky.}
{280}{}{Nevíte nìco o smrti Wrightova syna?}
{281}{}{Není vám tady teplo? Pøijde mi, e vám není zrovna... pøíjemnì.}
{282}{}{Dnes nic. U musím jít.}
{290}{bgjes15}{(Dlouho si tì prohlíí a poté zakroutí hlavou.) Ty... nejsi pro mì dost SILNİ. Nemám pro tebe práci.}
{291}{bgjes16}{(Dlouho si tì prohlíí a poté zakroutí hlavou.) Ty jsi... ENA. Tahle práce není pro eny.}
{292}{}{Dejte mi šanci. Dejte mi práci... jakoukoliv... a nebudete toho litovat.}
{293}{}{Dejte mi šanci, seòore Mordino. Dejte mi práci, jakoukoliv, a nebudete toho litovat.}
{294}{}{Tak mì vyzkoušejte. Nebudete toho litovat.}
{295}{}{Tak mì vyzkoušejte, seòore Mordino. Nebudete toho litovat.}
{296}{}{Tak dobøe. Zatím.}
{305}{bgjes17}{(Kapka potu steèe Mordinovi po tváøi. Jeho vıraz v tváøi znejasní.) U jsem øekl... e pro tebe NEMÁM práci. Odejdi... a u se NEVRACEJ.}
{306}{}{No ták, Velkej Jeíši... aspoò jednu šanci...}
{307}{}{Tak dobøe. Nashledanou.}
{315}{bgjes18}{(Mordino je chvíli potichu a poté zaène mluvit.) Já jsem Jeíš Mordino, hlava Mordinovy rodiny. Vstoupil jsi do... mého kasína. Mého domova. Neprojevil jsi mi ani trochu... úcty. Budu ti muset dát LEKCI.}
{316}{}{Myslím, e to budete VY, kdo dostane lekci...}
{317}{}{Hej, zadrte! Pojïme si o tom promluvit! No ták...}
{318}{}{[Utéct ke dveøím]}
{319}{}{::Skoèit do krytu a pomalu vytasit zbraò.::}
{325}{}{(Mordino èeká. Jak se tak na nìj díváš, vidíš, jak další mu další kapka potu steèe dolù po tváøi.)}
{326}{}{Chci prodat nìjaké otroky...}
{327}{}{Co víte o smrti Richarda Wrighta?}
{329}{}{Zapomeò na to.}
{335}{}{(Prohlíí si tì.) Sice tì... neznám, ale... poslouchám. (Utøe si pot z èela.) }
{336}{bgjes20}{Ty máš otroky na prodej?}
{337}{}{Ano, jsou tu se mnou. Podívejte se a udìlejte mi nabídku.}
{338}{}{Ne, nemám. Vlastnì jsem se zmılil. Hledám práci, nechci prodat ádné otroky.}
{339}{}{Ne... vlastnì se chci na nìco zeptat.}
{340}{}{Ne, pardon. Vlastnì si teï vzpomínám, e mám bıt nìkde jinde.}
{345}{bgjes21}{(Mordino si prohlíí tvé spoleèníky. Jeho pohled strne na Mirii, pøièem si olízne rty.) Ta tvoje puta vypadá zachovale... dám ti za ni 250 babek.}
{346}{bgjes22}{(Mordino si prohlíí tvé spoleèníky. Jeho pohled strne na Davinovi.) Sice vypadá slabì, ale vezmu si toho kluka. Nabízím ti za nìj 200 babek.}
{347}{bgjes23}{(Mordino si prohlíí tvé spoleèníky. Jeho pohled strne na Sulikovi... nìkolikrát mu zmáèkne nos.) Ten divoch... smrdí, ale vypadá silnì. Nabízím ti za nìj 100 babek.}
{348}{bgjes24}{(Mordino si prohlíí tvé spoleèníky. Jeho pohled strne na Vicovi.) Vezmu si toho staøíka... vypadá to, e bude ještì pár let uiteènı. Nabízím ti za nìj 100 babek.}
{349}{bgjes25}{(Mordino si prohlíí tvé spoleèníky. Jeho pohled strne na Cassidym.) Vezmu si toho staøíka... vypadá to, e bude ještì pár let uiteènı. Nabízím ti za nìj 100 babek.}
{350}{bgjes26}{(Mordinùv pohled ihned strne na Skynetovi.) Ten stroj tam. Nabízím ti za nìj 500 babek.}
{351}{bgjes27}{(Mordinùv pohled ihned strne na kyberpsovi.) Koupím toho... mechanického psa. Nabízím ti za nìj 500 babek.}
{352}{bgjes28}{(Mordino si prohlédne tvé spoleèníky a poté zakroutí hlavou.) Nemáš nic, o co bych mìl zájem.}
{353}{}{Seòore Mordino, prosím... tenhle otrok má mnohem VÌTŠÍ cenu. Urèitì má pøed sebou spoustu let vìrné sluby.}
{354}{}{To je férová cena. Mùete si toho otroka vzít.}
{355}{}{Toho vlastnì ještì nechci prodat. Chci se ale na nìco zeptat...}
{356}{}{Tohohle otroka vlastnì ještì nechci prodat. Provedeme ten obchod jindy.}
{357}{}{Tak dobøe. Chci se ještì na nìco zeptat...}
{358}{}{Tak dobøe. Zastavím se, a budu mít lepší nabídku.}
{370}{bgjes29}{Ne. Je na ní vidìt, e hodnì cestovala a vypadá dost opotøebovanì... 250 babek nebo nic.}
{371}{bgjes30}{Ten chlapec vypadá zenštile a slabì. Nedám ti za nìj víc ne 200 babek.}
{372}{bgjes31}{Ne. Ten divoch smrdí a vypadá, e bude... tìko zvládnutelnı. Bude ho tìké zkrotit. 100 babek.}
{373}{bgjes32}{Ten mu je starı. Dám ti za nìj 100 babek.}
{375}{bgjes33}{Ne. 500 babek.}
{377}{}{Seòore Mordino, prosím... snad mì nechcete urazit? Tohle je prvotøídní zboí, urèitì má vìtší cenu.}
{390}{bgjes34}{(Mordino se projde kolem Mirie, poøádnì si prohlédne její tváø a poté ji plácne po zadku.) Hmmmm. Dám ti za ní 500 babek.}
{391}{bgjes35}{(Mordino se projde kolem Davina, vyhrne chlapci rukáv a prohlédne si jeho svaly. Poté se mu podívá do oèí, aby zjistil, jestli nebere drogy.) Hmmmm. Vypadá dobøe. Dám ti za nìj 400 babek.}
{392}{bgjes36}{(Mordino se zamraèenì projde kolem Sulika.) Hmmmm. Vypadá silnì... a kdy vidím tu jeho kost v nose, tak asi dobøe snáší bolest. Dám ti za nìj 200 babek.}
{393}{bgjes37}{(Mordino se zamraèenì projde kolem Vica.) Hmmmmm. Dám ti za nìj 200 babek. Víc ne.}
{394}{bgjes38}{(Mordino se zamraèenì projde kolem Cassidyho.) Hmmmmm. Dám ti za nìj 200 babek. Víc ne.}
{395}{bgjes39}{(Mordino si chvíli prohlíí Skyneta.) Nabízím tisíc babek.}
{396}{bgjes40}{(Mordino si chvíli prohlíí kyberpsa.) Nabízím tisíc babek.}
{410}{bgjes41}{(Mordino nechá odvést Miriu pryè a mezitím ti pøipraví peníze.) Tady.}
{411}{bgjes41}{(Mordino nechá odvést Davina pryè a mezitím ti pøipraví peníze.) Tady.}
{412}{bgjes41}{(Mordino nechá odvést Sulika pryè a mezitím ti pøipraví peníze.) Tady.}
{413}{bgjes41}{(Mordino nechá odvést Vica pryè a mezitím ti pøipraví peníze.) Tady.}
{414}{bgjes41}{(Mordino nechá odvést Cassidyho pryè a mezitím ti pøipraví peníze.) Tady.}
{415}{bgjes41}{(Mordino nechá odvést Skyneta pryè a mezitím ti pøipraví peníze.) Tady.}
{416}{bgjes41}{(Mordino nechá odvést kyberpsa pryè a mezitím ti pøipraví peníze.) Tady.}
{417}{}{Nechcete se podívat na moje další zboí?}
{418}{}{Díky, seòore Mordino. Mimochodem, mùu se vás na nìco zeptat...}
{419}{}{Díky, seòore Mordino. Doufám, e vám budou otroci dobøe slouit. Sbohem.}
{430}{bgjes42}{(Kapka potu steèe Mordinovi po tváøi a poté se zachmuøí.) Ty svinì, ty jeden zkurvysynu. Od takovıch lidí, jako jsi ty, si nic nekoupím. Odejdi... a u se NEVRACEJ.}
{431}{}{Seòore Mordino, prosím... zvate to ještì jednou...}
{432}{}{[Potichu odejít]}
{440}{bgjes43}{(Mordino si tì prohlíí.) No dobøe. Mám... pro tebe práci. Vezmi si... (Hluboce zasípá a poté si utøe pot z èela.) ...tenhle balík... a dones ho do *Stájí* severnì od Rena. Pøedej ho mui jménem... Ramirez a pak se vra.}
{441}{}{Dobøe. To bude snadné.}
{442}{}{Hned se vydám na cestu, seòore Mordino.}
{443}{}{Co je v tom balíku?}
{444}{}{Eh, myslím, e ne. Myslím, e konèím.}
{450}{bgjes44}{Já tì... neplatím za to... abys mi kladl otázky.}
{451}{}{No, chci vìdìt, co ponesu, pro pøípad, e to náhodou upustím... je to nebezpeèné?}
{452}{}{Tak na to zapomeòte. Odcházím.}
{460}{bgjes45}{Jdi nahoru na sever po ulici Panen, kolem kasína... a pak jdi po cestì, která vede z mìsta. Ta tì zavede... a ke Stájím. Teï bì.}
{461}{}{[Postupovat podle jeho instrukcí...]}
{470}{bgjes46}{Udìlal jsi, co jsem chtìl?}
{471}{}{Ne, ještì jsem ten balík nedoruèil.}
{472}{}{Ano, doruèil jsem ho Ramirezovi, pøesnì jak jste chtìl.}
{473}{}{Ano, byl jsem ve Stájích a odevzdal jsem ten balík... víte, co tam DÌLAJÍ? Oni tam pouívají otroky na testování drog.}
{474}{}{Ano, dal jsem ten balík Ramirezovi... víte, e je ten chlap závislı na Jetu? SMRDÌL vıparama z Jetu.}
{480}{bgjes47}{Tak... proè jsi ještì tady? (Velkej Jeíš si utøe èelo a zhluboka se sípavì nadechne.) PROÈ jsi ten balík ještì nedoruèil?}
{481}{}{No, nejdøív se chci na nìco zeptat...}
{482}{}{Jdu to hned vyøídit.}
{483}{}{Eh, víte co? Myslím, e se na to hned vrhnu...}
{490}{bgjes48}{(Pøikıvne.) Dobrá práce. Tady je... tvoje vıplata. Sto... babek. Za... pouhé doruèení... je to a moc.}
{491}{}{Je to lepší ne nic.}
{492}{}{Díky, seòore Mordino.}
{500}{bgjes49}{(Rozzlobenì pøimhouøí oèi. Krùpìj potu mu steèe dolù po tváøi.) Oni jsou... jen dobytek. Nic víc.}
{501}{}{Ty zrùdo... právì sis podepsal rozsudek smrti.}
{502}{}{Eh... jen se ptám. Co se tıèe mé vıplaty...}
{510}{bgjes50}{Nemám pro tebe další... práci. (Kıvne na dveøe.) Teï chci bıt sám. Odejdi... a u se NEVRACEJ.}
{511}{}{Ale no ták, urèitì by se pro mì našla ještì NÌJAKÁ práce...}
{512}{}{Dobøe.}
{520}{bgjes51}{Mám... pro tebe další práci. Potøebuju nìkoho... (Zhluboka se sípavì nadechne a kapka potu mu steèe z èela.) ...aby vybral mùj podíl od... Korsickıch bratrù. Trochu se OPOZDILI s platbou.}
{523}{}{Myslím, e konèím. Ale stejnì díky.}
{530}{bgjes52}{Jdi na sever po ulici Panen. Jsou naproti ringu... pokud budou dìlat problémy... nebo pokud budou mít vımluvy... tak jim uka, co je to BOLEST.}
{531}{}{Dobøe, jdu na to.}
{532}{}{Jistì, seòore Mordino.}
{540}{bgjes53}{Øekl jsem, e... mùeš Korsickım bratrùm ukázat, co je to BOLEST, ale nedal jsem ti povolení k tomu... abys je ZABIL.}
{541}{}{Hele, podívejte... oni si zaèali a já jsem se jenom bránil...}
{542}{}{Øíkali o vaší matce ošklivé vìci, Velkej Jeíši. MUSEL jsem je zabít.}
{543}{}{Aha, to jsem asi pøeslechl.}
{551}{}{Eh... ano, ale nemám ty peníze u sebe. Poèkejte chvíli a donesu vám je.}
{552}{}{Ano, tady jsou ty peníze.}
{553}{}{Ne, ještì ne.}
{554}{}{Ne, eh, ale jdu to hned teï vyøídit.}
{560}{bgjes54}{Tak... proè jsi ještì tady? (Utøe si èelo a poté se zhluboka sípavì nadechne.) PROÈ nemáš ty peníze?}
{561}{}{No, víte, nejdøív se chci ještì na nìco zeptat...}
{562}{}{Dobrá otázka. Hned to jdu vyøídit.}
{570}{bgjes55}{(Kdy mu dáváš peníze, pøikıvne hlavou.) Tady. Polovina... je tvoje. Hehe. Oni u mi tenhle mìsíc zaplatili, ale chci, aby vìdìli... kdo je tady šéf.}
{571}{}{Díky moc, Velkej Jeíši.}
{580}{bgjes56}{(Seòor Mordino se na tebe dlouze podívá a poté lehce pøikıvne.) Mám pro tebe poslední práci. Je zde jeden... (Hluboce a sípavì se nadechne a poté si utøe pot z èela.) ...MU, kterı musí zemøít.}
{581}{}{Ten mu je u teï mrtvı. Jak se ta mrtvola jmenuje?}
{582}{}{Kdo je ten mu?}
{583}{}{Kdo je ten mu, kterého mám zabít, seòore Mordino?}
{584}{}{Hele, já neøíkal nic o vradìní. Zapomeòte na to.}
{585}{}{Tu práci vzít nemùu, seòore Mordino, promiòte. Sbohem.}
{595}{bgjes57}{Pøišel jsi za mnou pro práci, já ti dal... práci a ty zaèneš naøíkat jako malé DÌCKO. (Zhluboka a s obtíemi se nadechne a poté zaène hned kašlat.) Ty... u nejsi vítán... v mém kasínu. Odejdi.}
{596}{bgjes58}{Pøišel jsi za mnou pro práci a odmítneš mou... nabídku. (Zhluboka a s obtíemi se nadechne a poté hned zaène kašlat.) Ty... u nejsi vítán... v mém kasínu. Odejdi.}
{597}{}{Ne odejdu, chci se vás ještì na nìco zeptat...}
{598}{}{Ještì jsem s vámi NESKONÈIL, "Velkej Jeíši."}
{599}{}{Omlouvám se, seòore Mordino. Hned odejdu.}
{600}{}{Zkuste mì DONUTIT odejít.}
{610}{bgjes59}{Ten mu, Louis Salvatore... zabil mnoho mıch muù... mnoho HRDİCH muù rodiny Mordino. On... zmasakroval je na ulici jako... prašivé psy. (Ruku sevøe v pìst.) Pøeju si, aby ten mu zemøel.}
{611}{}{Jestli dobøe zaplatíte, tak ten mu je u teï mrtvı.}
{612}{}{Poèkejte chvíli. Louis Salvatore, ten, kterı ovládá rodinu Salvatorù? Ten, kterı má ty svìtelné zbranì, které umí èlovìka rozpùlit vejpùl?}
{613}{}{Pomstím se za rodinu Mordinù, seòore Mordino. Vrátím se hned, jak ten úkol splním.}
{614}{}{Ten úkol nemùu pøijmout. Odcházím.}
{615}{}{Tak dobøe. Udìlám to.}
{620}{bgjes60}{Zaplatím ti, ale a... Salvatore nebude dıchat.}
{621}{}{Poèkejte chvíli. Louis Salvatore, ten, kterı ovládá rodinu Salvatorù? Ten, kterı má ty svìtelné zbranì, které umí èlovìka rozpùlit vejpùl?}
{623}{}{Nebudu riskovat svùj krk jen tak pro nic. Odcházím.}
{630}{bgjes61}{(Mordino pøikıvne a pozoruje tvùj vıraz.) Máš snad... strach? Pokud ano, tak odejdi. (Ukáe na dveøe.) V rodinì Mordinù není místo pro... zbabìlce.}
{631}{}{Ne, udìlám to.}
{633}{}{Moná, e jsem zbabìlec, ale taky mám rád svùj ivot. O tuhle práci nemám zájem.}
{640}{bgjes62}{(Pøikıvne.) To je dobøe. Ten mu je starı... mrzák... schovává se v "Baru Salvatore" vedle Bishopova kasína. Je to... zbabìlec a nikdy nevychází ze svého pokoje v patøe. A bude... mrtvı, tak se vra.}
{641}{}{Mrzák?}
{642}{}{Tak dobøe.}
{650}{bgjes63}{(Pøikıvne.) Nohy toho øezníka... jsou slabé. (Jeíš si utøe èelo a poté se opìt zhluboka nadechne.) Také má... potíe s... dıcháním. Dıchá jenom pomocí... kyslíkové bomby.}
{651}{}{Kyslíkové bomby, jo? Hmmmm. Tak dobøe.}
{652}{}{A ho zabiju, tak se vrátím, seòore Mordino.}
{660}{bgjes64}{Louis Salvatore je stále naivu, tak proè jsi tady?}
{661}{bgjes65}{(Kapka potu steèe Mordinovi dolù po tváøi.) Splnil jsi ten úkol, kterı jsem ti zadal? Je Louis Salvatore mrtvı?}
{662}{}{Je mrtvı. Tvá rodina byla pomstìna, seòore Mordino.}
{663}{}{Ne, a ho zabiji, vrátím se.}
{664}{}{Salvatore je velmi dobøe hlídán. O tuhle práci u nemám zájem.}
{670}{bgjes66}{Jestli... uteèeš od tohohle úkolu, tak tì nechám... ZABÍT.}
{671}{}{No, kdy to øeknete takhle, tak to se radìji vrátím, a bude mrtvı.}
{672}{}{Jestli se o nìco pokusíte, budete si moct promluvit se svımi mui, které Salvatore zmasakroval.}
{680}{bgjes67}{Slyšel jsem. (Uctivì pøikıvne.) Odvedl jsi dobrou... práci. Moje dùvìra v tebe nebyla pošetilá. Tady je... tvoje vıplata. Pìt set... babek. }
{681}{}{Díky.}
{682}{}{To bude staèit... prozatím.}
{683}{}{A... zbroj a zbraò, která by se ti mohla... hodit.}
{690}{bgjes69}{(Pøikıvne.) Tvùj úspìch... mì potìšil. Rád bych tì pøivítal do rodiny Mordinù. (Obejme tì.) Chceš se stát èlenem naší rodiny? Tvoje síla bude... i naší silou.}
{691}{}{Bude mi potìšením stát se èlenem rodiny Mordinù.}
{692}{}{Nemùu se stát èlenem rodiny Mordino. Ale nevykládejte si to špatnì, seòore Mordino, bylo mi opravdu potìšením pro vás pracovat.}
{693}{}{Nechci se stát èlenem rodiny, díky. Musím nejdøív zachránit svoji vesnici.}
{700}{bgjes70}{(Pøikıvne.) To je mi líto, ale je to tvoje volba. Jak jsem øekl, tvùj úspìch mì potìšil... a nechci, aby tvoje schopnosti vyuíval i nìkdo jinı, jako tøeba... mí nepøátelé. (Dá pokyn svım stráím, aby vytasily zbranì.)}
{710}{bgjes71}{To je dobøe. Máš nìjakı... nápad, jak bychom ti mohli øíkat? Všichni Mordinové... celé Reno... bude tohle jméno znát.}
{711}{}{Jasnì, co takhle...}
{720}{bgjes72}{...to je dobré jméno. (Pøikıvne.) Jméno Mordino má... svou váhu v New Renu. Navštiv... Koèièí Packu... nebo Lovecké potøeby... a øekni jim, e jsi èlenem mojí rodiny... budou s tebou dobøe zacházet.}
{730}{bgjes73}{(Dlouho se na tebe upøenì dívá a poté zmatenì pøimhouøí oèi.) Proè... se mì na to ptáš? SLYŠEL jsem... co se stalo. (Otøe si èelo.) Ten chlapec si vzal moc Jetu a zemøel.}
{731}{}{A to je ten problém. Mordinové jsou nejvìtším dodavatelem Jetu v New Renu. Tím pádem jste jedni z podezøelıch.}
{732}{}{Nevíte náhodou, kde ten Jet získal?}
{733}{}{No dobøe, jenom se ptám. Chci se ještì zeptat...}
{734}{}{Aha. Myslím, e u radìji pùjdu.}
{740}{bgjes74}{(Zasípá a poté si utøe další pot z èela.) Kdyby mìli Wrightové... alespoò TROCHU zdravého rozumu, vìdìli by... e my nejsme jediná rodina, která vlastní Jet v New Renu. My... NEZABÍJÍME dìti.}
{741}{}{Jenom dospìlé, co? Chci øíct, Jet nezabije èlovìka hned, potøebuje trochu èasu, ale funguje, nemám pravdu?}
{742}{}{Ale nìkdo jinı moná ano a moná chtìl pošpinit jméno Mordino. Nevíte, kdo mohl Richardovi prodat ten Jet, kterı ho zabil?}
{743}{}{Aha. Mám ještì nìjaké otázky...}
{744}{}{Díky za informace, seòore Mordino. U musím jít.}
{750}{bgjes75}{(Zatøese hlavou.) Já... toho vím málo o dealerech v Renu. (Zhluboka a sípavì se nadechne a poté lehce zakašle.) Ty... mùeš se zeptat mého syna... najdeš ho dole v kasínu.}
{751}{}{Zeptám se ho. Chci se ještì zeptat...}
{752}{}{Zeptám se ho. Díky, seòore Mordino.}
{760}{bgjes76}{Teplo... není mùj pøítel. Moje dıchání je... nìkdy obtíné. Rychle se unavím pøi fyzické námaze nebo kdy jsem ve stresu. A nìkdy mám strašné bolesti na prsou.}
{761}{}{Opravdu? No, tak to je dobøe, e neberete ádné metamfetaminy nebo stimulanty. Chci se ještì zeptat...}
{762}{}{Aha. No, radìji u pùjdu.}
{770}{bgjes77}{Neznám tì... pøijdeš si za mnou... bez jakékoliv doporuèení, které by mìlo nìjakou... váhu. (Utøe si èelo a poté se zhluboka a sípavì nadechne.) NEMÁM PRO TEBE PRÁCI.}
{771}{}{No tak, dejte mi šanci. Dejte mi jakoukoliv práci... nebudete toho litovat.}
{780}{bgjes78}{Ne všichni ve Stájích... VÌDÍ, e jsou testovací objekty.}
{781}{}{Eh... co prosím?}
{782}{}{Aha. Eh, co se tıèe mé vıplaty...}
{790}{bgjes79}{Ramirez nechal... minulı mìsíc utéct ètyøi otroky. (Zaène lehce tøást hlavou.) To je zlé. Bìhem hodiny zaène pùsobit ten Jet, co jsi dal Ramirezovi, a jeho srdce... pøestane bít. To je jeho TREST.}
{792}{}{Vy jste mì vyuil k tomu, abych toho chlapa ZABIL? Tak a dost, Jeíši, padám odsud.}
{850}{}{Podaøilo se ti vybrat poplatek pro Velkého Jeíše.}
{875}{}{Velkı Jeíš byl zavradìn.}
{900}{}{Nyní jsi èlenem rodiny Mordinù.}
{925}{}{Nájemná vrada pro Velkého Jeíše byla dokonèena.}
{1278}{}{Mluvil jsem s vaším synem, seòore Mordino. Jsem otrokáø a hledám práci.}
{1291}{}{No dobøe. Nechcete aspoò koupit nìjaké otroky?}
{1621}{}{No... tak dobøe. Udìlám to.}
{5268}{}{?!! Tak POJÏ, TY JEDEN TLUSTEJ ZKURVYSY...}
