{100}{}{Vidíš paní Wrightovou.}
{150}{}{Vidíš robustní enu se smutnım vırazem na tváøi. Vypadá sklesle a obèas si povzdechne.}
{151}{}{Vidíš paní Wrightovou. Vypadá sklesle a obèas si povzdechne.}
{175}{}{Vidíš boubelatou enu s èervenımi tváøemi. Zdá se, e má dobrou náladu a nìco si pobrukuje.}
{176}{}{Vidíš paní Wrightovou. Zdá se, e má dobrou náladu a nìco si pobrukuje.}
{200}{ew60}{*Vzdych*}
{201}{ew61}{Jak mi to jen mohl udìlat?}
{205}{ew62}{Další krásnı den v našem krásném Renu!}
{206}{ew63}{::Hvízdá si, zatímco ty pracuješ... ::}
{207}{ew64}{Tak do práce! To je pøeci potìšení dìlat práci a dìlat ji dobøe!}
{208}{ew65}{::Hmmmm-hmmm-hmmm-hm-hm -hmmmm::}
{209}{ew66}{Další krásná noc v našem krásném Renu!}
{210}{ew1}{(ena pøekvapenì vyskoèí.) Boínku, to jsem se ale polekala! (Zamourá na tebe.) Ano?}
{211}{ew2}{(Paní Wrightová pøekvapenì vyskoèí.) Boínku, to jsem se ale polekala! (Zamourá na tebe.) Ááá, to jste zase vy!}
{212}{}{Kdo, kdo?}
{213}{}{Ahoj, ahoj!}
{214}{}{Ty ne máma... mami? Mamiii...?! Mami! Já jít hledat máma.}
{215}{}{Kdo jsi?}
{216}{}{Koukám, e si tu tak broukáte, madam, tak si øíkám, e se zastavím na kus øeèi. Dneska máme ale pøekrásné poèasí, e?}
{217}{}{Promiò. Hledám nìkoho jiného.}
{220}{}{(Vypadá zmatenì a poté si tì mìøí od hlavy k patì.) }
{222}{}{(Zaloví ve svıch šatech, vytáhne nìjaké vìci a vtiskne ti je do dlanì.) Tady máte. Vezmìte si to.}
{223}{}{Dík.}
{224}{}{Odbelhat se.}
{230}{}{(Ach, vy chudáèku! Urèitì máte úpal... }
{231}{}{Ach, vy chudáèku... nemáte snad kam jít? }
{232}{}{(Zaloví ve svıch šatech.) Ké bych tak pro vás mìla nìjaké jídlo nebo pití...}
{240}{ew7}{Ano, to máme. (Usmìje se.) Jsem Ethyl Wrightová, hlava Protialkoholického hnutí v New Renu. A kdo jste vy?}
{241}{}{Jsem poutník a hledám GECK. Neslyšela jste nìkdy o nìjakém?}
{242}{}{Jsem poutník hledající místo zvané Vault 13. Nevíte, kde to je?}
{243}{}{Protialkoholické hnutí?}
{244}{}{Paní Wrightová? Není váš manel hlavou rodiny Wrightù?}
{245}{}{Vy jste Richardova matka, e ano? Doneslo se mi, e nedávno zemøel.}
{246}{}{Promiòte, ale musím odejít.}
{250}{ew8}{Já? Jsem Ethyl Wrightová, hlava Protialkoholického hnutí tady v New Renu. (Prohlédne si tì.) A kdo jste vy?}
{251}{}{Já jsem }
{252}{}{Jsem poutník a chci se na nìco zeptat ohlednì New Rena...}
{254}{}{Rád bych tu zùstal a povídal si s vámi, ale u musím jít.}
{260}{}{Šmankote! Vy jste DIVOCH, e? Váš pøízvuk vás prozradil! (Zaène mluvit víc nahlas a pomaleji.) TAK TEDY, VÍTÁM VÁS V NAŠEM MÌSTÌ!}
{261}{}{Co ty øíkat? Já obyèejná divoch. Nerozumìt ty.}
{262}{}{enská, nejsem ani hluchı, ani hloupı. Rozumím vám CELKEM dobøe, nemusíte pøede mnou zvyšovat hlas.}
{263}{}{Eh, díky. Chci se na nìco zeptat ohlednì New Rena...}
{264}{}{U MUSÍM JÍT.}
{270}{ew10}{POVÍDÁM, *JÁ*... (Ukáe na sebe.) ...VÁS VÍTÁM... (Ukáe na tebe.) ...VE... (Ukáe na mìsto okolo.) ...MÌSTÌ TISÍCE SVÌTEL!}
{272}{}{Nejspíš si myslíte, e tahle high-tech zbroj na mì jen tak spadla z nebe. Hele, pøestaòte se mnou mluvit jako s dubem, ano?}
{273}{}{Myslíte, e tahle zbraò je nìjakı kmenovı talisman, kterı mám jen tak pro parádu? Pøestaòte na mì hulákat jako na tupce, ano?}
{274}{}{RADÌJI PÙJDU, NE SE OPRAVDU NAŠTVU.}
{280}{}{Ach! Promiòte! (Vypadá vystrašenì.) Pardon, pardon! Já jsem jenom myslela, e... e... no to je jedno, nechme to bıt.
 Co pro vás mùu udìlat?}
{281}{}{Chci se zeptat na nìco jiného ohlednì Rena...}
{282}{}{U nic. Musím u jít.}
{290}{ew12}{(Zamourá a zamraèí se.) Prosím? G.E... coe? Ne, o takové vìci jsem nikdy neslyšela, lituji.}
{291}{}{Chci se ještì zeptat...}
{292}{}{Tak nic, radìji pùjdu.}
{300}{}{Vault 13? (Vypadá zmatenì.) Ne, vánì, nikdy jsem... poèkat. Teï si vzpomínám. Na severovıchodì odsud LEÍ Vault City.
 Je to to, co hledáte?}
{301}{}{Ne, to není ono. Ale moná mi pomùete s jinımi otázkami...}
{302}{}{Moná. Mùete mi ještì s nìèím pomoct...?}
{303}{}{Moná. Sbohem... a díky za informace.}
{310}{}{Ale jistì! (Zamává prstem.) New Reno je krásné mìsto, ale je tu také spousta HØÍCHÙ, za které vìtšinou mùe ten démon alkoholu... nebo jak tomu vy divoši øíkáte... (Dramaticky se odmlèí.) ...OHNIVÁ VODA!}
{311}{}{Eh, my "primitivové" tomu taky øíkáme alkohol.}
{312}{}{Ano, ale co dìlá Protialkoholické hnutí?}
{313}{}{U musím jít. Myslím, e mì moji soukmenovci u shánìjí.}
{315}{}{(Na chvíli se odmlèí.) }
{316}{}{Protialkoholické hnutí je tu proto, aby pomáhalo lidem odvrátit se od chlastu a aby ili perspektivnìjší a smysluplnìjší ivot.}
{317}{}{Aha. A co tøe...}
{318}{}{Jako napøí...}
{320}{}{(Vypadá šokovanì.) Urèitì se mılíte. I takovı divoch jako vy nemùe vánì mys...}
{321}{}{Není nic lepšího ne trocha spoleèenské lásky, trocha hazardu a zakonèit den nìkolika dbány zakysaného oslího mléka. Tak ije pravı èlen KMENE!}
{322}{}{Není nic lepšího ne trocha spoleèenské lásky, trocha hazardu a zakonèit den nìkolika dbány zakysaného oslího mléka. Tak ije pravá èlenka KMENE!}
{323}{}{Nechám to na vaší pøedstavivosti. Kdy vidím tu odpovìï vıše, tak myslím, e to tak bude lepší.}
{324}{}{U šamanova kolíku, ano! Všechny ty TØI høíchy velice rád provozuju. }
{325}{}{U Milouše Jakeše a jeho matky! Nevím, co vy divoši provozujete za ohavné orgie ve svıch brlozích neøesti, ale tady v New Renu je to jiné! My jsme CIVILIZOVANÍ lidé!}
{326}{}{U nás ve vesnici nemáme ádné ty ïábelské ohavnosti, které jste jmenovala. Moná bychom vás "civilizované" lidi mohli ledacos nauèit.}
{327}{}{Kdo všechno je èlenem vaší organizace?}
{328}{}{Èím se ta vaše organizace zabıvá?}
{329}{}{Jistì. Díky za váš názor. Sbohem.}
{330}{ew19}{(Zamyslí se.) No, tøeba Otec Tully.}
{331}{ew20}{(Zamyslí se.) No, tøeba Otec Tully byl naším èlenem. Ne umøel.}
{332}{}{Eh, Otec Tully je ten nejhorší konzument 'ohnivé vody', jakı kdy spatøil svìtlo tohohle svìta. Èlovìk by se oral jen z jeho vıparù.}
{333}{}{Otec Tully?}
{335}{}{Vlastnì u si nechci dál povídat. Radìji pùjdu.}
{340}{}{Tak a teï mì dobøe poslouchejte. (Zamraèí se.) Takovéhle pomluvy tu nehodlám trpìt. Chudák Otec mìl sice s pitím problémy, ale díky našemu Hnuti s tím zaèal bojovat a zvítìzil!}
{341}{}{Vím naprosto URÈITÌ, e dobrı Otec vdycky POBÌÍ k nejbliší pípì, kterou uvidí... pokud U v té dobì nebude zpitı do bezvìdomí.}
{342}{}{To není pomluva. Velkı duchovní vùdce New Rena je zdravı asi tak jako... samotné New Reno.}
{343}{}{Dobøe, nebudu se hádat. Take èím se to hnutí zabıvá?}
{344}{}{No, tak to jsou dobré zprávy. Radìji u pùjdu.}
{345}{}{Ach ano, náš duchovní vùdce New Rena. Stará se o jedinı kostel, kterı tady v New Renu máme. MUSÍTE si s ním promluvit. Jeho ivot je velmi inspirující!}
{346}{}{Dobøe, moná se za ním zastavím. Take èím se to vaše Protialkoholické hnutí zabıvá?}
{347}{}{Moná se za ním teï pùjdu podívat.}
{350}{ew23}{Hmf! e vám není hanba! Myslím, e bude lepší, kdy odejdete a víckrát se sem u nevrátíte.}
{351}{}{To mám v úmyslu.}
{352}{}{Tak dobrá.}
{355}{ew24}{Ano, je, to je. (Znovu si tì zmìøí pohledem.) Promiòte, ale vy znáte mého mue?}
{356}{}{Ano, znám ho. Wrightova rodina kontroluje veškerou distribuci alkoholu v New Renu.}
{357}{}{Neznáme se osobnì, ale vím, e Wrightova rodina kontroluje veškerou distribuci alkoholu v New Renu.}
{358}{}{Ne.}
{359}{}{Ani ne. Poslyšte, musím odejít.}
{360}{ew25}{Aha. (Zamrká.) Take co pro vás mùu udìlat?}
{361}{ew26}{Co chcete vìdìt?}
{362}{ew27}{(Pøekvapenì vyskoèí.) Boínku, to jsem se ale polekala! (Zamourá.) Ááá, to jste zase vy!}
{363}{}{Co jste to pøedtím øíkala o tom Protialkoholickém hnutí?}
{364}{}{Hledám GECK.}
{365}{}{Hledám místo, kterému se øíká Vault 13.}
{366}{}{Váš manel je hlavou rodiny Wrightù, e ano?}
{368}{}{Vlastnì nic. Radìji pùjdu.}
{369}{}{Promiòte, ale teï nemám èas. Sbohem.}
{375}{}{(Zamraèí se.) O èem to sakra blábolíte? "Obchod s alkoholem v New Renu?" Vím, e mùj mu se rád napije, ale U se toho zlozvyku zbavil...}
{376}{}{Stejnì jako se zbavil všech, co mu stáli v cestì jeho malému alkoholovému impériu.}
{377}{}{Ethyl, moná jste si toho JEŠTÌ nevšimla, ale váš manel je hlavou mafie, která prodává alkohol po celém New Renu. To, e se obèas napije, je ten jeho nejmenší zloèin.}
{378}{}{Hmm, asi mám na mysli jiného pana Wrighta. Zapomeòte na to. Sbohem.}
{380}{}{Coe... mùj ty Tondo kudrnatej! U sta hromù! (Zhluboka se nadechne.) }
{381}{}{To je VELICE váné obvinìní, mladı mui.}
{382}{}{To je VELICE váné obvinìní, mladá dámo.}
{383}{}{To máte pravdu, ale...}
{384}{}{Poslyšte, dámo, moná byste m...}
{385}{}{Ne, VY poslouchejte! Není tajemstvím, e mùj manel KDYSI vlastnil soukromou palírnu ve mìstì. Nicménì pøísahal, e je jen pro jeho vlastní potøebu a NA MOJE PØÁNÍ ji rozebral!}
{386}{}{Opravdu? No, moná byste...}
{387}{}{No, poslyšte, on u...}
{390}{}{(Zamraèí se a dá si ruce v bok.) Já se o tom pøesvìdèím, to si tedy pište! A jestli zjistím, e jsou to všechno li, tak bude lepší, kdy okamitì opustíte toto mìsto. Poèkejte na mì zítra ráno pøed kostelem a tam si promluvíme.}
{392}{}{Tak dobøe. Budu tam. Zatím nashle.}
{395}{ew33}{(Vytratí se jí úsmìv.) Ano, mùj syn Richard... on... ano, opustil nás pøíliš brzy. Já... hmmm. Ano. (Sklopí oèi.) Já...}
{396}{}{Prı se pøedávkoval Jetem... je to pravda?}
{397}{}{To je jedno. Zapomeòte na to. Chci se ještì na nìco zeptat...}
{398}{}{U nic. Radìji pùjdu.}
{400}{ew34}{(Zatne zuby.) To ïáblovo sémì! Já mu poøád øíkala, aby se ani NEPØIBLIOVAL k takovému svinstvu a potom...}
{401}{}{Mùete mi øíct, kde mohl ten Jet získat?}
{405}{}{Já nevím! (Zatne ruce v pìst.) Prodávají ten jed na kadém rohu New Rena! To svinstvo je prostì VŠUDE...!}
{406}{}{Znáte nìjaké konkrétní dealery?}
{407}{}{Zapomeòte na to. Chci se ještì na nìco zeptat...}
{410}{}{Ne podle jména. Znají mì dost dobøe na to, aby utekli, kdykoliv se pøiblíím... ale houfují se jako mouchy kolem ulice Panen, pøed vchodem do mìsta a u kasína.}
{411}{}{Aha. Mám ještì jiné otázky...}
{415}{}{Dr se ode mì dál, ty démone rozkoše! Ty, je smilníš ve filmu a nièíš lidskou mravnost!}
{416}{}{Taková nestydatost! Máš ale drzost se sem vrátit! Ty, je smilníš ve filmu a nièíš lidskou mravnost!}
{417}{}{Có? Já, je mìlním ve filcu mravencovitost èehoe?}
{418}{}{Jéééjej! Velkı slova! Velkı slova! Muset rychle pryè!}
{419}{}{Jo, to jsem já. Máte zájem? Líbí se mi mohutnìjší eny, jako jste vy. [Svùdnì zamrkat] Uvolnìte si trochu ty tìsné podvazky a mùeme jít na to.}
{420}{}{Podívejte, byl jsem mladı a potøeboval jsem peníze...}
{421}{}{Vidím, e si budeme mít o èem povídat. Sbohem.}
{425}{ew39}{Ven! Okamitì vypadnìte!}
{426}{}{Já jít! Já jít!}
{427}{}{Dobrá, dobrá! U odcházím!}
{428}{}{Pro pána krále. Odvate se taky trochu.}
{430}{}{(Zamraèí se na tebe a poté zpozoruje tvé otrokáøské ocejchování. Její hlas zchladne.) }
{431}{}{Ano?}
{432}{}{Zase vy? My dva si NEMÁME co øíct.}
{433}{}{Já... eh... já... já chtít... eh... já hledat... eh... sakryš! Já nesnášet bıt hloupá! Já nesnášet!}
{434}{}{Já... eh... och, blıskavá vìc!}
{435}{}{Mám nìjaké otázky...}
{436}{}{Vidím, e s vámi u ádná øeè nebude. Sbohem.}
{440}{ew43}{Hmm. Obávám se, e vám nemùu nijak pomoct. Hezkı den.}
{441}{ew44}{Hmm. Obávám se, e vám nemùu nijak pomoct. Dobrou noc.}
{442}{}{::Pokrèit rameny a odejít.::}
{443}{}{Tak dobøe. Pøeju hezkı den.}
{444}{}{Tak dobøe. Dobrou noc.}
{450}{ew45}{(Vidíš paní Wrightovou. Vypadá znièenì.)}
{451}{}{Eh... jste v poøádku, Ethyl?}
{452}{}{Take... co jste zjistila?}
{453}{}{Ahá! Take mám pravdu, nebo mám pravdu?}
{454}{}{Je mi to líto. Vrátím se pozdìji.}
{460}{}{Všechno je to pravda... úplnì všechno. (Vzdychne.) On tu palírnu nerozebral. Ani kousíèek! (Zamraèí se.) A já mu vìøila, ale ten alkohol ho donutil mi LHÁT! *Lhát své vlastní enì!*}
{461}{}{::Nechat ji vyzpovídat se.::}
{462}{}{Ano, Ethyl... další dùkaz toho, jak je alkohol ïábelskı. Nutí lidi dìlat hrozné vìci. OBZVLÁŠ pokud se to tıká dvou ïáblù v podobì penìz a moci.}
{463}{}{Asi chcete bıt teï chvíli sama... vrátím se pozdìji.}
{470}{}{(Zhluboka se nadechne.) Ale já ho DONUTÍM dodret slib, i kdybych tu palírnu mìla znièit vlastníma rukama.
 A pak si s Orvillem pìknì popovídám! Uvidíme, co na to ten malej syèák øekne!}
{471}{}{Netrapte se tím, paní Wrightová. U je o to postaráno.}
{472}{}{Kde je ta palírna? Znièím ji za vás.}
{473}{}{Ne, nechte to na mnì. Je pod eleznièní stanicí, e ano? Postarám se o ni.}
{474}{}{Dobrı nápad. Moná byste tu palírnu mìla pøeci jen znièit vy.}
{475}{}{Zatím nashle.}
{480}{}{...je pod eleznièní stanicí za naším domem! }
{481}{}{Rozbijte ji na kousíèky! Zniète ji! A z ní NIC nezbude!}
{482}{}{Tak dobøe...}
{490}{}{To taky udìlám, u ïasa! (Vyhrne si rukávy. K tvému pøekvapení má ruce jako vzpìraè.) Díky, e jste mi otevøel oèi, cizinèe. Já u si svého mue srovnám, i kdyby ho to mìlo ZABÍT.}
{491}{}{No, pøeju dobrou zábavu pøi nièení.}
{500}{ew51}{(Vidíš Ethyl. Kdy se pøiblííš, vzhlédne k tobì s nadìjí.) U je...?}
{501}{}{Je srovnaná se zemí. Nic z ní nezbylo. O VŠECHNO bylo postaráno.}
{502}{}{Ještì ne. Kde e je ta palírna?}
{503}{}{Ne, ještì není znièená. Vrátím se, a to bude hotové.}
{510}{ew52}{Je pod eleznièní stanicí za naším domem! Rozbijte ji na kousíèky! Zniète ji! A z ní NIC nezbude!}
{512}{}{Vrátím se, a to bude hotové.}
{515}{}{(Rozpláèe se.) Díky, cizinèe. Podaøilo se vám zasadit poøádnou ránu všemu tomu zlu v New Renu. Nevím, jak vám podìkovat...}
{516}{}{To nestálo za øeè. Mìjte se, paní Wrightová.}
{517}{}{No, mám zrovna hluboko do kapsy...}
{520}{ew54}{To se dá lehce napravit. Pojïte za mnou.}
{521}{}{[Následovat ji]}
{522}{}{Vlastnì to ani nestálo za øeè. Mìjte se, paní Wrightová.}
{525}{}{Tady máte. Vše, co je v té skøíòce, je vaše. Také trocha penìz na cestu... a takovou obzvláš uiteènou vìcièku, která dokáe pøesvìdèit i toho nejzabednìjšího osla. Dìkuji vám za všechno.}
{526}{}{Díky MOC, paní Wrightová.}
{530}{}{Dìkuji za vaši pomoc, }
{535}{}{New Reno nemùe existovat jen kvùli hazardu, alkoholu a prostituci! Ne ne! Ne dokud je Ethyl Wrightová u vesla! Nic takového!}
{536}{}{Ale lidé MILUJÍ hazard, chlast a dìvky. Napøíklad já rozhodnì ano.}
{539}{}{Promiòte, ale musím vyøídit naléhavou záleitost.}
{540}{}{(Vybuchne.) Moná je ve vašem kmeni normální veøejnì pomlouvat ostatní, ale tady v New Renu tedy rozhodnì ne! Máte ale poøádnou drzost ke mnì takhle veøejnì pøijít a pomlouvat mého manela!}
{541}{}{Poslyšte, já jen øíkám, e...}
{542}{}{Pravda bolí. Myslím, e budete brzy hodnì trpìt. Sbohem.}
{543}{}{To je jedno. Sbohem.}
{545}{}{Navíc se rozhodl mi pomoct se zbavováním dalších závislıch nešastníkù toho odporného alkoholového zlozvyku. Taková ohavnost jenom TVRDIT, e mùj manel prodává alkohol ostatním, je...}
{546}{}{Je to naprostá pravda. Paní Wrightová, váš manel obchoduje s alkoholem po celém New Renu a podporuje tak alkoholismus. To dìlá z mìsta ještì horší místo pro ivot, ne u je. Pomozte mi a spoleènì tomu uèiníme pøítr.}
{547}{}{Jestli mi nevìøíte, tak se jdìte podívat pod eleznièní stanici a pak pochopíte, co mám na mysli.}
{548}{}{Vidím, e s vámi nebude ádná øeè, dokud vám to nebudu moct dokázat.}
{550}{}{Ale nechci, aby se nìco stalo mım dìtem, take ádné máchání zbranìmi! Ony nejsou zlé, jenom jsou... na špatné cestì. Budu se muset postarat o jejich nápravu...}
{551}{}{Dobøe, nebojte se... nikdo nezemøe.}
{552}{}{Vrátím se, a to bude hotové. Nejdøív si ale musím zaøídit pár vìcí.}
{553}{}{Eh, to nemùu zaruèit... moná byste mìla na tu práci sehnat nìkoho jiného.}
{1251}{}{. Chci se na nìco zeptat ohlednì New Rena...}
{1415}{}{(Pøekvapenì vyskoèí.) Panenko skákavá! (Zamraèí se a poté se na tebe pohrdavì podívá.) Taková nestydatost! }
{1430}{}{(Pøekvapenì vyskoèí.) Boínku! }
{1431}{}{(Zamraèí se na tebe a poté její pohled zchladne.) }
{1480}{}{Vy ji znièíte? Já... no, tak dobøe... (Nadechne se.) }
{1530}{}{. Já u se postarám o to, aby Wrightovic rodina odteï ila èestnım a spoøádanım ivotem.}
