{100}{}{Vidíš Poøezanıho Jimma J.}
{150}{}{Vidíš podezøele vypadajícího mue. Má drobnı tik v oblièeji a dlouhou jizvu na tváøi.}
{151}{}{Vidíš Poøezanıho Jimma J. Vypadá to, e vyhlíí dalšího zákazníka.}
{152}{}{Vidíš Poøezanıho Jimma J. Jakmile tì spatøí, kıvne na tebe.}
{153}{}{Vidíš Poøezanıho Jimma J. Zachytí tvùj pohled a mávne na tebe, a jdeš blí.}
{200}{}{Nazdar, no jestlipak to není }
{201}{}{Nazdar, }
{202}{jimmy48}{Támhle jde jeden poøádnej tvrïák... a Jimmy J pozná poøádnıho tvrïáka.}
{203}{jimmy49}{Nestává se kadej den, aby nìkdo zapíchnul prezidenta v jeho vlastním bejváku.}
{204}{jimmy50}{Nechceš si trochu orazit a oslavit svı vítìzství trochou Jetu od Poøezanıho Jimma, hrdino?}
{205}{jimmy51}{Zachraníš svìt a Poøezanej Jimmy ti DÁ svìt, hrdino. Tolik Jetu, kolik budeš chtít.}
{206}{jimmy52}{Slyšel jsem, e tì shánìj Korsiètí bratøi, hrdino...}
{220}{jimmy53}{Jsem Poøezanej Jimmy a mám tolik Jetu, kolik budeš CHTÍT.}
{221}{jimmy54}{Chceš se proletìt? Poøezanej Jimmy je tvùj èlovìk.}
{222}{jimmy55}{Chceš lítat? Poøezanej Jimmy má pro tebe lístek.}
{223}{jimmy56}{Jestli chceš fet, Poøezanej Jimmy má Jet.}
{224}{jimmy57}{Chceš se vznášet? Poøezanej Jimmy má pro tebe Jet.}
{225}{jimmy58}{Tenhle tejden mám nìco speciálního, tak pojïme obchodovat.}
{226}{jimmy59}{Buï si koupíš sraèku po kterı lidi chcípaj, nebo si koupíš èistej, silnej fet u Poøezanıho Jimma.}
{227}{jimmy60}{Jimmy J má vdycky otevøíno, kámo.}
{228}{jimmy61}{Chceš lítat jako tryskáè? Tak si promluv s Jimmym, on je tvùj èlovìk.}
{240}{}{(Tento mu má drobnı tik v oblièeji a dlouhou jizvu na tváøi. Jizva vypadá jako po noi.) }
{241}{jimmy1}{Brácho, všiml jsem si tì sotva jsi vyšel na ulici. Víš, co vidím?}
{242}{jimmy2}{Ségro, všiml jsem si tì sotva jsi vyšla na ulici. Víš, co vidím?}
{243}{}{Ty vidìt já.}
{244}{}{Co ty vidìt?! Co ty vidìt?!}
{245}{}{Já muset jít n...}
{246}{}{Co vidíš?}
{247}{}{Nech tìch kecù, ty jeden blbej...}
{248}{}{Promiò, nemám zájem...}
{260}{jimmy3}{Vidím pilota. Vidím nìkoho, kdo chce LÍTAT. Potøebuješ akorát trochu píchnout, trochu... JETU.}
{261}{}{Jet? V nebe? Gde?}
{263}{}{Jet, jo? Chci se zep...}
{264}{}{Poslyš, já nejsem...}
{270}{}{Mùj leteckej kámo, kdy jde o JET, Poøezanej Jimmy J je tvùj MU. Mám nejlepší zboí v New Renu. Èistej Jet, silnej Jet a NEJBEZPEÈNÌJŠÍ Jet.}
{271}{}{Gde jet? Já nevidìt nikoho jet v nebe.}
{272}{}{Já muset JÍT n...}
{273}{}{Poøezanej Jimmy J, jo? Poslyš, chci se zep...}
{274}{}{Promiò, mì nezaj...}
{280}{}{OSTATNÍ dealery kvalita nezajímá, ale já, já si rád DRÍM stálı zákazníky a dohlíím na to, aby byli ŠASTNÍ, chápeš? To je mùj styl... styl Jimma J.}
{281}{}{Ja nevidìt nikoho jet. Ty lhát }
{282}{}{PUS JÁ CHTÍT J...}
{283}{}{No, eh, Jimmyho styl zní sice skvìle, ale já se chci na nìco ze...}
{284}{}{Ne, myslím, e ne...}
{290}{jimmy6}{Vìdìl jsem, e se vrátíš, vìdìl jsem to! Neøíkal to snad Poøezanej Jimmy J? Dohlídni na to, aby byli šastní a oni tì nikdy nezklamou. Take, mùj leteckej kámo... co pro tebe mùe dneska Poøezanej Jimmy J udìlat?}
{291}{jimmy7}{Ale, jestlipak to není mùj leteckej "kámoš"... POTØEBUJEŠ snad nìco od Poøezanıho Jimma?}
{292}{}{Eh... já zapomnìt co já chtít øíct. Já jít.}
{294}{}{My vymìnit vìci? Já RÁD vìci.}
{295}{}{Máš Jet? Tak pøejdìme k obchodu... kamaráde.}
{296}{}{Kde jsi pøišel k té jizvì, Jimmy?}
{297}{}{Odkud bereš Jet, Jimmy?}
{298}{}{Nevíš, kdo dal Wrightovic dìcku ten Jet, kterı ho zabil?}
{299}{}{Pøedtím jsi øíkal, e je tvùj Jet "nejbezpeènìjší." On se tu vyskytuje i nìjakı nebezpeènı Jet?}
{300}{}{Dnes nic. Díky, Jimmy.}
{310}{jimmy8}{Tak co to BUDE? Co pro tebe mùe dneska Poøezanej Jimmy J udìlat?}
{311}{jimmy9}{Jo, co chceš? Vymáèkni se... nemám na to celej den.}
{312}{jimmy10}{Nìco potøebuješ nebo máš otázky... co pro tebe mùe dneska Poøezanej Jimmy J udìlat?}
{314}{}{Já zapomnìt! Já koneènì vzpomnìt a já zas zapomnìt! }
{330}{jimmy11}{Hej... nìkoho mi PØIPOMÍNÁŠ. Neznáme se, mùj leteckej kámo?}
{331}{jimmy12}{PØÍSAHÁM, e tì znám, mùj leteckej kámo. Ten tvùj ksicht je mi povìdomej...}
{332}{}{JÁ MOC VELKÁ HRDINA, JÁ DOHRÁT HRA A NAKOPAT PRDEL A VYHODIT ROPNÁ VÌ DO VZDUCH A ZACHRÁNIT SVÌT.}
{333}{}{Já bojovat v ringu pøed moc hluèná lidi co øvát zabij sráè tak já mlátit dokud on nespadnout na zem.}
{334}{}{Já dìlat ošklivá vìci s cizá lidi co poøád mluvit s bùh.}
{335}{}{Já MAFIÁN. Já VELKÁ chlap v REEnu.}
{336}{}{Jak mùe nìkdo nìkoho DOOPRAVDY znát, Jimmy? Lze nìèeho takového vùbec dosáhnout na tomhle hrozném svìtì? Nebo je to moné a tehdy, kdy se osvobodíme od svıch fyzickıch tìl?}
{337}{}{Já CHTÍT mluvit ale ty mì NENECHAT já NASKLE.}
{338}{}{No, podaøilo se mi zastavit plány Enklávy na zabití všech lidí na tomhle svìtì, porazit Prezidenta, vyhodit do vzduchu jejich základnu a ztìí uniknout smrti.}
{339}{}{Moná mì znáš z boxerského ringu.}
{340}{}{Moná mì znáš z nìjakého filmu. Slyšel jsi o }
{341}{}{Jsem blízkı pøítel rodiny }
{342}{}{Ne, myslím, e ne, Jimmy. Budeme tedy obchodovat, nebo ne?}
{343}{}{Ne, myslím, e ne. Poslyš, chci se ještì na nìco zeptat...}
{344}{}{Ne, u musím jít. Zatím, Jimmy.}
{360}{}{To je ono! Já VÌDÌL, e jsem tì u nìkde vidìl! Sakra, máš to øíct hned a ne aby si s tím musel Jimmy lámat hlavu...?! Co pro tebe mùu udìlat?}
{361}{}{Eh... já zapomnìt. Já jít.}
{363}{}{No, sháním nìjakı Jet...}
{364}{}{Poèkej, potøebuju ještì nìco jiného...}
{365}{}{U musím jít. Zatím, Jimmy.}
{375}{}{(Jimmy pøekvapením ztichne. Asi jsi mu paralyzoval mozek.)}
{376}{}{[Ukrást mu všechno, co má]}
{377}{}{ je s prací hotov.}
{385}{jimmy14}{Poøezanej Jimmy J je plnej lásky, mùj leteckej kámo, ale svìt ne vdycky miluje Poøezanıho Jimma, chápeš?}
{386}{}{Chápu. Chápu.}
{387}{}{To mi povídej. Nìkdy je svìt opravdu krutı.}
{388}{}{To je SKVÌLİ pøíbìh. Poslyš, Jimmy, chci se ještì na nìco zeptat...}
{389}{}{Dobrı pøíbìh. Ty máš Jet, já mám prachy... jdeme obchodovat?}
{390}{}{Dobrı pøíbìh, ale u musím jít, Jimmy.}
{400}{}{(Ukáe na svoji jizvu.) Tohle mi zùstalo po tom, co jsem bránil jednu babu pøed takovım velkım OŠKLIVİM hajzlem, kterej ji chtìl uhodit, protoe se jí nelíbilo, jak ji osahává, chápeš?}
{401}{}{Opravdu? Jak se to stalo?}
{402}{}{Vánì? Øeknu ti, chlapi, co mlátí eny, si zaslouí dostat poøádnou nakládaèku.}
{415}{}{(Zaujme bojovı postoj.) Pøišel jsem k nìmu jo a on vytáhl KUDLU na starıho JJ! Já nemìl nic ne holı ruce, chápeš? Bohuel se mu povedl jeden šastnej zásah, ne jsem mu... *BUM!* nakopal prdel!}
{416}{}{Fakt jo? Jules øíkal, e jsi lítal na Jetu a poøezal sis oblièej, kdy ses snail oholit svım bojovım noem.}
{417}{}{Hovno! Na nìco takovıho bych teda nemìl koule. Vdy tì ten chlap mohl ZABÍT!}
{418}{}{SKVÌLİ pøíbìh. Poslyš, chci se ještì na nìco zeptat...}
{419}{}{Jo... poslyš, mám nìjaké peníze... jdeme obchodovat?}
{420}{}{Dobrı pøíbìh... tak dobrı, e musím odejít.}
{430}{}{Cooooo...? Jules mi mùe políbit moji pøírodnì èernou øi. Navíc by to byla jediná PRDEL ve mìstì, kterou ještì nepolíbil. Ví HOVNO. Nemá ani koule na to, aby mi takovı sraèky øekl do oèí. TY se rozhodni, kdo z nás dvou mluví pravdu.}
{431}{}{Jo, jo... poslyš, ty máš JET, já mám peníze... jdeme obchodovat?}
{432}{}{Jo, jo... poslyš, Jimmy, chci se ještì na nìco zeptat...}
{433}{}{Poslyš, pane Velká Hubo, jdeme obchodovat, nebo budu muset ty tvoje kecy poslouchat celı den?}
{434}{}{U to nehodlám poslouchat, Jimmy. Dej pozor, a se budeš zase holit, ano?}
{435}{}{Tak dobøe. Zatím, Jimmy.}
{445}{jimmy18}{Taky e skoro zabil! Víš, kdy jsem vidìl, co se dìje, nemyslel jsem si, e si 'Budu hrát na pana stateènıho a tak', ale...}
{446}{}{Udìlal jsi, co bylo podle tebe správné, e?}
{447}{}{Aha. Poslyš, chci se ještì na nìco zeptat...}
{448}{}{U musím jít. Zatím, Jimmy.}
{455}{}{Jó... jó... prostì jsem vidìl nìco špatnıho a tak jsem musel nìco UDÌLAT, chápeš? Nemohl jsem pøece dopustit, aby se taková vìc stala, kdy jsem byl poblí, chápeš?}
{456}{}{Máš opravdu KOULE, Jimmy. Vìtšina lidí by jen sklopila zrak a odešla.}
{457}{}{Rozumím. Poslyš, chci se ještì na nìco zeptat...}
{465}{jimmy20}{Já mám lidi RÁD a nemám rád nìkoho, kdo do lidí rejpá jen proto, e mùe. To není kurva SPRÁVNİ.}
{466}{}{Jsi stateènı mu, Jimmy, opravdu stateènı mu. Nos svoji jizvu s pıchou. Poslyš, mùu vidìt, co nabízíš?}
{467}{}{To máš pravdu. Poslyš, chci se ještì na nìco zeptat...}
{475}{jimmy21}{Sakra, mùj leteckej kámo, líbíš se mi, take tu kšeftovací obrazovku s tìma drátkama a pojistkama ani nevytahuj.}
{476}{}{Eh... tak dobøe... ale jak tedy budeme obchodovat...?}
{480}{}{Hele, sice je to pro mì špatnej kšeft a tak a nikomu ani muk, ale chci ti dát trochu Jetu jako pøátelskej dárek. Pøíštì budeš muset samozøejmì zaplatit, ale tohle je na Poøezanıho Jimma J, chápeš?}
{481}{}{Díky, Jimmy. Poslyš, mùu se ještì podívat, co nabízíš?}
{482}{}{Páni, díky. Poslyš, chci se ještì na nìco zeptat...}
{483}{}{Tak dobøe. Díky, Jimmy.}
{490}{}{Jsem rád, e se ptáš, mùj leteckej kámo. Víš, OSTATNÍ dealeøi, chápeš, maj fet z druhı ruky. Øedìnı a okoøenìnı všelijakım sajrajtem.}
{491}{}{Ale na druhou stranu tvùj Jet...}
{492}{}{Zapomeò na to. Chci se ještì na nìco zeptat...}
{500}{}{Døív jsem ho mìl od samotnıho boha Myrona, víš, jene se napakoval a pak zmizel... nebo to koupil. Teïka vìtšinou beru pøímo od rodiny Mordinù.}
{501}{}{No, DØÍV jsem ho mìl od starıho Myrona, ne se napakoval a vykašlal se na to... e jo, Myrone? Ha! Teïka vìtšinou toèím fet od Mordinù.}
{502}{}{Zajímavé. Mám ještì nìjaké otázky...}
{510}{}{Mám kontakty se samotnım STVOØITELEM, mùj leteckej kámo. Mám Jet pøímo od tı mozkovny MYRONA, ivıho boha chemickejch slouèenin.}
{511}{}{Myrona?}
{512}{}{Zajímavé. Mám ještì nìjaké otázky...}
{513}{}{Od Myrona, jo? Mùu se setkat... s tímhle ivım bohem?}
{514}{}{Opravdu? No, tak to se musím nìkdy stavit a trochu si koupit. Díky, Jimmy.}
{520}{}{Myron je zlatej kluk Mordinù. To on VYTVOØIL Jet. Kupovat od Poøezanıho Jimma je jako brát pøímo od Myrona, chápeš? A proto má J-J èistej Jet. Ten NEJLEPŠÍ Jet.}
{521}{}{To zní dobøe. Pojïme obchodovat.}
{523}{}{Myslíš, e by bylo moné se s tím Myronem setkat?}
{530}{}{Ani hovno! Mordinové toho kluka støeej líp ne panu v New Renu. V ádnım pøípadì nikoho nenechaj, aby se jejich ivobytí jenom dotkl, chápeš?}
{531}{}{Rozumím. Jak dobøe je ten chlapec hlídanı?}
{532}{}{A na to, e má prı spoustu pøítelkyò... mezi prostitutkami. Jak je to vùbec moné, kdy je tak dobøe hlídanı?}
{533}{}{Rozumím. Poslyš, chci se ještì na nìco zeptat...}
{534}{}{Zajímavé. Díky za informace, Jimmy.}
{540}{}{Stráe, stráe a další stráe. A nejsilnìjší elektronickej bezpeènostní systém v New Renu. Kdy budeš mít štìstí, tak moná USLYŠÍŠ o nìkom, kdo Myrona vidìl. A tak dobøe je hlídanej.}
{541}{}{Je dobøe hlídanı, jo? Kde pøesnì?}
{543}{}{Aha. Mám ještì jiné otázky...}
{550}{}{Maj ho schovanıho na místì zvanım "Stáje", severnì od Rena. Byl jsem tam jenom jednou. Nikdy mì nenechali projít pøes bránu a to pro rodinu PRACUJU.}
{551}{}{No tak, musí bıt pøece nìjakı zpùsob, jak se s ním mùu setkat.}
{554}{}{Stáje, jo? Severnì od Rena... (Hned si to poznamenám do Pip-Boye.) ...díky za informace, Jimmy.}
{560}{}{Nemám tušení, kámo. Sice pro toho kluka PRODÁVÁM, ale stejnì jsem ho vidìl asi jenom jednou nebo dvakrát a navíc ještì z pìknı dálky. Velkej Jeíš Mordino k nìmu nepustí nikoho, kdo nepatøí k rodinì.}
{561}{}{Tak dobøe, pojïme obchodovat.}
{564}{}{Tak dobøe. Díky, Jimmy. Já u pùjdu.}
{570}{jimmy32}{No, tak to je ale... úplnì... jinej pøíbìh, mùj leteckej kámo. To teda jo.}
{571}{}{Myslím, e tohle je pøesnì ten pøíbìh, kterı chci slyšet. Povídej, Jimmy...}
{572}{}{Zapomeòte na to. Chci se ještì na nìco zeptat...}
{573}{}{Myslím, e na tohle nemám èas, Jimmy. U musím jít.}
{580}{jimmy33}{Víš, o Myrona se dobøe staraj... Mordinové dávaj svımu ivobytí to NEJLEPŠÍ z New Rena.}
{581}{}{Tím myslíš...?}
{582}{}{Myslíš prostitutky, e ano? Jen tak ze zvìdavosti, odkud berou Mordinové ty prostitutky a jak je vybírají?}
{584}{}{Aha. Díky, Jimmy. U musím jít.}
{590}{}{Mordinové vodìj kurvy do Stájí osobnì a pak je zas odvádìj pryè. Hehe. Myronovi je sotva devatenáct, ale hormony má jako dvacet... dvacet CHLAPÙ.}
{592}{}{Zajímavé... poslyš, jen tak ze zvìdavosti, odkud berou Mordinové ty prostitutky a jak je vybírají?}
{600}{}{(Pokrèí rameny.) Slyšel jsem, e se jeden z Mordinovejch chlapù projde Koèièí Packou a vybere si jednu z nabídky sleèny Kitty, která by se mohla Myronovi líbit... (Jimmy najednou pøestane mluvit, podívá se na tebe a zamraèí se.) Tak moment...}
{601}{}{Co se dìje?}
{602}{}{Eh, zapomeòte na to. Chci se ještì na nìco zeptat...}
{603}{}{Eh, no, díky za informace, Jimmy.}
{610}{}{Proè tì zajímaj takovı sraèky? Já mám Jet a to je všechno, co potøebuješ. Nepotøebuješ vìdìt nic o Myronovi, ani co mìl k veèeøi, ani koho ojede, ne jde spát.}
{611}{}{Proè tì zajímaj takovı sraèky... (Zarazí se, poté se usmìje a prohlédne si tì od hlavy k patì.) Ahá, u je mi to jasnı. Chceš jít pøímo ke zdroji Jetu, e jo, ségro?}
{612}{}{Teï ne. Uka mi, co nabízíš, Jimmy.}
{613}{}{Zapomeò na to. Pojïme obchodovat.}
{614}{}{No tak nic. Chci se ještì na nìco zeptat...}
{615}{}{Moná. Poslyš, chci se ještì na nìco zeptat...}
{616}{}{Ne, jsem jenom zvìdavá. Díky, Jimmy. U musím jít.}
{617}{}{Tak dobøe. Zatím, Jimmy. U musím jít.}
{625}{}{Krucinál, JÁ jen øíkám, e má Jimmy rád svı kupce šastnı a IVİ. Domysli si zbytek, mùj leteckej kámo. Je pro tebe pøednìjší vlastní ivot nebo pár drobnejch pøi kupování další dávky Jetu?}
{626}{}{Rozumím. Mùeme obchodovat?}
{627}{}{Nevíš náhodou nìco o téhle prázdné nádobce od Jetu?}
{628}{}{Myslím, e se ten kluk nepøedávkoval Jetem. Spíš si myslím, e byl otráven.}
{629}{}{Chci se ještì zeptat...}
{635}{jimmy39}{Aha, tak TOHLE tì zajímá, jo?! Chceš vìdìt, jestli v tom starej Jimmy nemá pracky, co?!}
{636}{}{Ne, jen se ptám...}
{637}{}{Dobøe, zapomeò na to. Mùeme obchodovat?}
{638}{}{Poslyš, chci se ještì na nìco zeptat...}
{639}{}{Díky za radu, Jimmy. Radìji u pùj...}
{645}{}{JDI DO PRDELE! Já prodávám ÈISTEJ fet! Jestli chceš vìdìt, kdo otrávil Wrightovic kluka, tak se jdi zeptat toho starıho blbeèka Renesca nebo toho syèáka Julese a uvidíš, co z nich vypadne!}
{646}{}{Dobøe, dobøe. Uklidni se...}
{648}{}{Dobøe, dobøe. Poslyš, chci se ještì na nìco zep...}
{655}{}{Tak POSLOUCHEJ... jestli zjistím, e vykládáš nìjakı sraèky o tom, e mám nìco spoleènıho se smrtí Wrightovic kluka, tak skonèíš v Golgotì hned vedle nìj.}
{656}{}{Renesco øíká, e prodáváš JET øíznutı arsenem.}
{659}{}{ádnı problém. Poslyš, chci se ještì na nìco zeptat...}
{660}{}{Tak v Golgotì, jo? Jako Richard, co?}
{661}{}{Nevyhrouj MI, ty malej buzerante. Neštvi mì, nebo tì zabiju tolikrát, e si budeš myslet, e jsi Lazarus.}
{662}{}{Klídek, Jimmy. Nikdo nebude roznášet ádné drby.}
{663}{}{Nic neøeknu, Jimmy. U odcházím, vidíš? U odcházím.}
{675}{}{(Vezme si nádobku a prohlédne si ji.) Uuuf, já... (Èichne si k hrdlu a zamraèí se.) Kuuuurva. Tenhle Jet mìl v sobì šávu z radškorpiona. Ten, kdo si tohodle cucnul, dlouho nepøeil... (Vrátí ti nádobku.)}
{676}{}{Byl otrávenı?}
{677}{}{Hmmm. Chci se ještì zeptat...}
{678}{}{Aha. Díky.}
{685}{jimmy43}{Jo sakra! Dávej si bacha, komu tohle ve mìstì ukáeš... a proto Jimmy vdycky øíká...}
{686}{}{Nenapadá tì odkud mùe bıt?}
{695}{}{Ne, nenapadá... hele, nikomu neøíkej, e to máš ode mì, ale... na tvım místì bych se zeptal Julese nebo Renesca... ale ode mì to nemáš, jasnı?}
{696}{}{Tak dobøe. Chci se ještì na nìco zeptat...}
{697}{}{Renesca a Julese, jo? Pùjdu se jich zeptat. Díky za radu.}
{705}{jimmy45}{To mì vùbec nepøekvapuje.}
{706}{}{Co tím chceš øíct?}
{707}{}{Aha. Mám ještì jiné otázky...}
{708}{}{No, nevadí.}
{715}{jimmy46}{Jo, to øíká PROTO, protoe si myslí, e o tom ví VŠECHNO.}
{716}{}{Co tím myslíš?}
{725}{}{Co tím myslím? Tím myslím, e Jimmy má svı zákazníky rád šastnı a IVİ. Renescovi je to putna, take... zbytek si domysli, mùj leteckej kámo.}
{727}{}{Díky za radu, Jimmy. U musím jít.}
{800}{}{Podaøilo se ti zjistit, e byl Richard Wright otráven.}
{5200}{}{! Pojï si vzít trochu Jetu od J-J. Je to gratis...}
{5201}{}{! Jestli chceš slavit JETem, promluv si se starım Jimmym J...}
{5281}{}{ ty lhát }
{5314}{}{ ZABÍT TY.}
{5340}{}{?}
{5341}{}{ .}
{6281}{}{ o jet?}
