{150}{}{Vidíš èernocha v obnošeném obleku. Kdy si všimne, e se na nìj díváš, usmìje se a jeho zlaté zuby se zatøpytí ve svìtle lamp.}
{151}{}{Vidíš Julese.}
{200}{jules105}{Ukáu ti to tady, otrokáøi.}
{201}{jules106}{Jdi za Mordinama, otrokáøi. Kšeftujou s vìtšinou otrokù, kterı se dostanou do New Rena.}
{202}{jules107}{Nováèek v Renu, otrokáøi? Tak to potøebuješ pøátelskou radu.}
{203}{jules108}{Zdar, otrokáøi. Pojï si na chvíli pokecat.}
{204}{jules109}{Otrokáøi, kdy si nepromluvíš s Julesem, tak se nikdy nedozvíš ani POLOVINU vìcí, co New Reno nabízí.}
{205}{jules110}{Nazdar, otrokáøi! Máš minutku?}
{206}{jules111}{Hledáš nìco, otrokáøi? Jules ti to pomùe najít.}
{220}{jules112}{Nováèek ve mìstì? Nechceš se na nìco zeptat?}
{221}{jules113}{Nazdar. Pojï si na chvíli pokecat.}
{222}{jules114}{Kámo, kdy si nepromluvíš s Julesem, tak se nikdy nedozvíš ani POLOVINU vìcí, co New Reno nabízí.}
{223}{jules115}{New Reno je nebezpeènı místo, kámo. Pojï sem a já ti vysvìtlím, co je bezpeènı a co ne.}
{224}{jules116}{Nazdar! Máš minutku, kámo?}
{225}{jules117}{Kámo, ty a já bysme si mìli pokecat. Ukáu ti to tady.}
{226}{jules118}{Hledáš nìco, kámo? Jules ti to pomùe najít.}
{240}{jules119}{Halelujááá! Vdycky jsem vìdìl, e z tebe bude hrdina! Vìdìl jsem to!}
{241}{jules120}{Hrdina pøichází! Udìlejte místo, udìlejte místo!}
{242}{jules121}{Pojï se pozdravit se starım kámošem Julesem.}
{243}{jules122}{Nechceš se se mnou podìlit o trochu svı slávy, hrdino?}
{244}{jules123}{Nechceš se se mnou podìlit o trochu svıho bohatství, hrdino?}
{245}{jules124}{Jules se k tobì vdycky choval slušnì... take všem øíkej, e mì znáš, hrdino, jasnı?}
{246}{jules125}{Slyšel jsem, e tì shánìj Korsiètí bratøi, hrdino...}
{260}{jules126}{Sáákryš. Myslím, e my dva bysme mìli bıt kámoši.}
{261}{jules127}{Jak sakra chodíš s tou zbrojí na záchod?}
{262}{jules128}{Co TO sakra je? Chodící auto?}
{263}{jules129}{Feáci se podìlaj strachy, a tì v tomhle uvidìj.}
{280}{jules130}{Pøimluvíš se za mì u svıho šéfa, brácho?}
{281}{jules131}{Nazdar, brácho, doufám, e jsi pøi svım vzestupu nezapomnìl na starıho kámoše Julese.}
{282}{jules132}{Nazdar, Zlej a Nebezpeènej! Øekl bych, e se ti v New Renu daøí!}
{283}{jules133}{Kdyby tvùj šéf potøeboval nìjakıho dealera Jetu, jsem tu...}
{284}{jules134}{Pøimluvíš se za mì u svıho šéfa, ségro?}
{285}{jules135}{Nazdar, ségro, doufám, e jsi pøi svım vzestupu nezapomnìla na starıho kámoše Julese.}
{300}{jules136}{Zdar, šampióne! Øekl bych, e se ti v New Renu daøí!}
{301}{jules137}{Nazdar, šampióne, doufám, e jsi pøi svım vzestupu nezapomnìl na starıho kámoše Julese.}
{302}{jules138}{Štìstìna se na tebe usmála, brácho. Jseš boí.}
{303}{jules139}{Vdycky jsem vìdìl, e tvı jméno bude záøit. Vìdìl jsem to hned, jak jsem tì spatøil.}
{304}{jules140}{Zdar, ségro bitkáøko! Øekl bych, e se ti v New Renu daøí!}
{305}{jules141}{Nazdar, ségro šampiónko, doufám, e jsi pøi svım vzestupu nezapomnìla na starıho kámoše Julese.}
{306}{jules142}{Štìstìna se na tebe usmála, paní šampiónko. Jseš boí.}
{320}{jules143}{Sákryš, podívejte se na tu záøící hvìzdu... záøíš tak, e tì skoro nevidím, brácho!}
{321}{jules144}{Zdar, mùj obdaøenej brácho! Øekl bych, e se ti v New Renu daøí!}
{322}{jules145}{Co kdybys mì pøedstavil nìkterejm hereèkám, se kterıma dìláš, brácho?}
{323}{jules146}{Nazdar, doufám, e jsi pøi svım vzestupu nezapomnìla na starıho kámoše Julese.}
{324}{jules147}{Štìstìna se na tebe usmála, chlape. Jseš boí.}
{325}{jules148}{Vdycky jsem vìdìl, e tvı jméno bude záøit. Vìdìl jsem to hned, jak jsem tì spatøil.}
{340}{jules149}{No podívejte se na tu slaïounkou sestøièku.}
{341}{jules150}{Puká mi srdce, kdy tì vidím.}
{342}{jules151}{No tak, ségro, co takhle pusa pro starıho Julese?}
{343}{jules152}{Sákryš, podívejte se na tu záøící hvìzdu... záøíš tak, e tì skoro nevidím, ségro!}
{344}{jules153}{Nazdar! Øekl bych, e se ti v New Renu daøí!}
{345}{jules154}{Co kdybych si s tebou zahrál v pár scénách, drahoušku?}
{346}{jules155}{Nazdar, doufám, e jsi pøi svım vzestupu nezapomnìla na starıho kámoše Julese.}
{347}{jules156}{Štìstìna se na tebe usmála, drahoušku. Jseš boí.}
{348}{jules157}{Vdycky jsem vìdìl, e tvı jméno bude záøit. Vìdìl jsem to hned, jak jsem tì spatøil.}
{349}{jules158}{Jseš fakt parádní koèka, kdy øveš a vzdycháš ve filmech.}
{350}{jules159}{Nedokáu popsat, jak moc tvrdì tì zase vidím.}
{365}{jules160}{To je MUTANT?}
{366}{jules161}{Ten mutant vypadá jako pìknì velkej hajzl.}
{367}{jules162}{Mutanti v New Renu? To urèitì znamená, e se blíí pohroma...}
{368}{jules163}{Mutanti z pustin? Nebylo to tak pøed osmdesáti lety?}
{369}{jules164}{Ten mutant v Renu dlouho nepøeije...}
{370}{jules165}{To bude masakr, a si nìkdo z rodin všimne toho mutanta...}
{380}{jules166}{To je nìjakej hrací automat co za tebou poøád jezdí?}
{381}{jules167}{To je nìjakej novej hrací automat?}
{382}{jules168}{Umí ten tvùj robot nìjakı triky? Eh... myslím kouzelnı triky.}
{383}{jules169}{Nechceš toho robota prodat? Mozek si mùeš nechat.}
{390}{jules170}{A hele ghoul... já vìdìl, e nìco cítím.}
{391}{jules171}{Ten ghoul v Renu dlouho nepøeije...}
{392}{jules172}{To bude masakr, a si nìkdo z rodin všimne toho ghoula...}
{400}{jules173}{Hodnej kyberpejsek, hodnej pejsek...}
{401}{jules174}{Hodnej kyberpejsek... hodnej pejsek... moná mám u sebe nìjakou kostièku...}
{402}{jules175}{Ten pes je první dobrej dùvod, proè byl zavedenej zákon o nutnosti vodítka.}
{403}{jules176}{Ten pes je ze eleza? A já si o sobì myslel, e jsem tvrïák.}
{404}{jules177}{Zajímalo by mì, jestli se daj kyberpsi chovat...}
{410}{jules178}{Reno si tì dá klidnì ke snídani. Nebo svaèinì.}
{411}{jules179}{Èlovìk se tu snadno ztratí a Jules je ten, kterej ti pomùe.}
{412}{jules180}{Tohle mìsto je pro nováèky pìknì nebezpeènı... pojï si se mnou pokecat a já ti poradím.}
{413}{jules181}{enskı, prachy, enskı, prachy... co víc si pøát?}
{414}{jules182}{Jet, enskı, kvéry... vím všechno. Staèí se jenom ZEPTAT.}
{415}{jules183}{Reno... mìsto, kterı nikdy nespí.}
{416}{jules184}{Jet, prachy, Jet, prachy... co víc si pøát?}
{417}{jules185}{Pøistup blíe.}
{418}{jules186}{Jules jsou tvı OÈI a tvı UŠI v New Renu.}
{419}{jules187}{Reno - nejvìtší malı mìsto v pustinì, kámo.}
{420}{jules188}{Jseš novej ve mìstì? Tak to potøebuješ pøátelskou radu.}
{421}{jules189}{Jules je ten, kterıho POTØEBUJEŠ.}
{422}{jules190}{Ty máš chu, já mám spásu.}
{423}{jules191}{Reno NIKDY nespí, take potøebuješ pár rad.}
{424}{jules192}{Reno si tì dá klidnì ke snídani. A já taky.}
{425}{jules193}{enská se tu snadno ztratí. Jestli chceš, tak ti Jules pomùe.}
{426}{jules194}{Tohle mìsto dokáe enskou svlíknout donaha... pojï si se mnou pokecat a já tì svlíknu poøádnì.}
{427}{jules195}{Hej! Na slovíèko, ségro!}
{428}{jules196}{Jseš nová ve mìstì, ségro? Tak to potøebuješ pøátelskou radu, holka.}
{429}{jules197}{Potøebuješ Jet? Potøebuješ zbranì? Ségro, já vím všechno. Staèí se ZEPTAT.}
{450}{}{(Usmìje se a v jeho ústech se zatøpytí zlatı zub. Síla jeho kolínské ti vehnala slzy do oèí.) }
{451}{}{VÍTEJ v záøivıch ulicích mìsta New Reno, brácho!}
{452}{}{VÍTEJ v záøivıch ulicích mìsta New Reno, ségro!}
{453}{}{Cooo? Co...?}
{454}{}{A ty jsi...?}
{460}{}{Jmenuju se Jules a bude mi potìšením tì provıst tímhle mìstem a seenu ti cokoliv, co budeš potøebovat.}
{461}{}{Jmenuju se Jules a musím øíct, e jsem v ulicích New Rena ještì nevidìl hezèí enskou, ne jseš ty. Bude mi potìšením tì provıst tímhle mìstem a seenu ti cokoliv, co budeš potøebovat.}
{462}{jules5}{Hej, hej, hej, vítej zpátky. Potøebuješ nìco od Julese, kámo?}
{463}{}{Já hledat... eh. Já zase zapomnìt.}
{464}{}{Odbelhat se.}
{465}{}{Fajn. Mùeš mi pomoct?}
{466}{}{Jo, chtìl bych se zeptat na...}
{467}{}{Julesi, nevíš co se stalo synovi pana Wrighta?}
{468}{}{Julesi, nevidìl jsi moje auto? Bylo támhle zaparkovanı a teï je pryè.}
{469}{}{Poslyš... "Jules", ano? Nejspíš se touhle konverzací snaíš nìco získat, take na rovinu: O co se tu snaíš?}
{470}{}{No, zajímalo by mì... co máš z toho, kdy provádíš návštìvníky mìstem, Julesi?}
{471}{}{Dnes ne, Julesi. Díky.}
{472}{}{Ne, díky. Zatím, Julesi.}
{480}{jules6}{Eh... nenamáhej si mozek, brácho. Hlavnì si nìjak neubli, jasnı?}
{481}{jules7}{Eh... nenamáhej si mozek, ségro. Hlavnì si nìjak neubli, jasnı?}
{482}{}{Hi tı hi tı hi tı hou.}
{490}{}{Mùu ti sehnat COKOLIV, brácho. Jestli se chceš proletìt a vznášet se v nebeskejch vıšinách, Jules ví, kam jít. Take moje otázka zní: Bez èeho nemùeš dál ít?}
{491}{}{Jules ti seene cokoliv budeš chtít, ségro. Jestli se chceš proletìt a vznášet se v nebeskejch vıšinách, Jules ví, kam jít. Take moje otázka zní: Bez èeho nemùeš dál ít?}
{492}{}{Jules ti seene cokoliv budeš chtít, moje sladká sestøièko. Jestli se chceš proletìt a vznášet se v nebeskejch vıšinách, Jules ví, kam jít. Take moje otázka zní: Bez èeho nemùeš dál ít?}
{493}{jules11}{Jasnı, jasnı... take co potøebuješ?}
{494}{}{Mùeš mi øíct nìco o New Renu?}
{495}{}{Kde seenu nìjaké drogy?}
{496}{}{Sháním se po nìjaké poøádné palebné síle.}
{497}{}{Sháním zásoby.}
{498}{}{Chci si zapíchat.}
{499}{}{Hledám místo, kterému se øíká Vault 13.}
{500}{}{Hledám svùj kmen. Byl unesen.}
{501}{}{Nevíš, jak opravit ropnı tanker?}
{502}{}{Hledám GECK.}
{503}{}{Dnes nic, díky.}
{515}{}{Jestli ti mùe Jules ØÍCT nìco o New Renu? Jo, sakra! PRVNÍ vìc, kterou musíš vìdìt: Reno ovládaj ètyøi rodiny: Mordinové, Salvatoøi, Bishopové a Wrightové. Kadá z rodin má pod palcem kousek Rena.}
{516}{jules13}{Reno má ètyøi rodiny: Mordiny, Salvatory, Bishopy a Wrighty. Kadá z rodin má pod palcem kousek Rena.}
{517}{}{Povìz mi o tìch rodinách.}
{518}{}{A co zákony?}
{519}{}{Vlastnì se chci ještì zeptat...}
{520}{}{Zajímavé. Díky za rozhovor.}
{525}{jules14}{ádnı zákony, ádní fízlové, ádnej šerif. Jsou tu JENOM rodiny.}
{527}{}{Kdo tedy v Renu udruje poøádek?}
{528}{}{Aha. Mám ještì jiné otázky...}
{535}{}{O to se staraj samotnı rodiny. Nemaj RÁDI problémy v Renu, paè to narušuje turistickej ruch a to znamená míò penìz pro všechny. Nedìlej problémy, pla svı dluhy a neskonèíš v Golgotì.}
{537}{}{Golgotì?}
{545}{}{No, to je høbitov za mìstem. Tam odpoèívaj lidi, co se dostali do køíku s nìkterou z rodin. Pøiváou je na kùly a nechaj je pomalu umøít na slunci. Nechtìl bych takhle umøít. A taky to tam strašnì smrdí.}
{547}{}{Zajímavé. Mám ještì nìjaké otázky...}
{548}{}{Paráda. Díky za informace.}
{555}{jules17}{No a DALŠÍ vìc, kterou musíš o Renu vìdìt je to, e nic není zadarmo. A pokud jo, tak si to radši poøádnì provìø.}
{556}{jules18}{No, takovı informace nejsou levnı. Máš prachy? Pak máš moji pozornost.}
{557}{}{Zaplatit mu 25 dolarù.}
{558}{}{Zaplatit mu 50 dolarù.}
{559}{}{Zaplatit mu 75 dolarù.}
{560}{}{Zaplatit mu 100 dolarù.}
{561}{}{Vlastnì se chci ještì... zeptat na nìco, co... se netıká rodin.}
{562}{}{Vypadá to, e si tvé znalosti teï nemùu dovolit. Vrátím se, a budu mít víc penìz.}
{563}{}{Budu si to pamatovat. Díky za rady, Julesi.}
{575}{jules19}{(Jules schová peníze tak rychle, e to vypadá, jako by se vypaøily.) Take... která z rodin tì zajímá?}
{576}{jules20}{(Jules schová peníze.) Take... o kterı rodinì se chceš nìco dozvìdìt?}
{577}{}{Povìz mi o rodinì Mordinù.}
{578}{}{Povìz mi o rodinì Salvatorù.}
{579}{}{Povìz mi o rodinì Bishopù.}
{580}{}{Povìz mi o rodinì Wrightù.}
{581}{}{Chci se zeptat na nìco jiného ohlednì Rena...}
{582}{}{No, vlastnì nic. Promluvíme si pozdìji.}
{590}{jules21}{(Vztyèí dva prsty.) Mordinové jsou jako dvouhlavá saò, kámo, a obì hlavy se jmenujou Jeíš Mordino.}
{591}{}{Pokraèujte...}
{592}{}{Nìco mi øíkalo, e je Jeíš zapleten do organizovaného zloèinu.}
{594}{}{Vrame se k ostatním rodinám.}
{596}{}{No, vlastnì nic. Díky za rozhovor.}
{615}{}{Ti dva jsou tatík Velkej Jeíš Mordino a jeho synáèek Malej Jeíš Mordino. Oba jsou to ti nejvìtší zkurvysyni, jakı kdy mùeš potkat. Byli tu jako otroci, ale pøed pár lety se vzmohli a vybudovali si svoje vlastní malı impérium.}
{616}{}{Jak velké je to jejich "impérium?"}
{625}{}{Vlastní Desperado kousek dál na tıhle ulici. Nemùeš ho minout. A taky maj nejvìtší zdroje Jetu v celım New Renu. Take kdy budeš mít chu se proletìt...}
{626}{}{Co mi pøipomíná, nevíš, kde seenu nìjaké drogy?}
{627}{}{Jak to, e mají Mordinové nejvìtší zdroje Jetu?}
{628}{}{Povìz mi o ostatních rodinách.}
{635}{}{Protoe jsou na vrcholu, kámo. ádnej jinej dùvod pro to není. Maj továrny, svıho tvùrce a vlastní distribuci. Maj tolik Jetu, e jsou jako podìlaná letecká spoleènost.}
{636}{jules25}{Jo, co chceš ještì vìdìt?}
{637}{}{Jakou továrnu?}
{638}{}{Jakého "tvùrce?"}
{639}{}{Jak rozsáhlá je jejich distribuèní sí?}
{650}{}{Maj továrny po celım Renu, take dìlaj fet nepøetritì. Proto se dá koupit jakıkoliv mnoství Jetu skoro kdekoliv: v barech, kasínech, na ulici... a pochopitelnì i ode MÌ.}
{651}{}{Mùu se podívat, co máš?}
{652}{}{Zpátky k Mordinùm a Jetu...}
{660}{}{No... (Nakloní se k tobì.) ...víš, Mordinové získali svùj vlastní malej zlatej dùl jménem Myron. Díky nìmu jsou na vrcholu... víš, to on VYTVOØIL Jet.}
{662}{}{Dost o Mordinech a ostatních rodinách. Povìz mi nìco o Myronovi...}
{670}{}{Pumpujou to do celıho New Rena. Pak na sever do Denu a taky... eh... (Zarazí se, poté pokrèí rameny a pokraèuje.) ...no a teï ho taky prodávaj do Reddingu.}
{672}{}{Povìz mi o Reddingu.}
{685}{}{Není moc o èem mluvit. Je to hornickı mìsto severozápadnì odsud. Øíká se, e tam chtìj Mordinové získat vliv kvùli ZLATU, co se tam tìí. Take Mordino jim posílá Jet, oni posílaj nazpátek zlato a všichni jsou šastní.}
{695}{}{Tichá banda. Vede je Louis Salvatore, stárnoucí gangster. Jejich teritorium je na Druhı ulici. Jejich hlavní flek je bar Salvatore na Druhı ulici. Bejt tebou, nedìlám tam problémy.}
{696}{}{Proè ne?}
{710}{}{Dám ti radu: Jestli uvidíš nìjakıho Salvatora, skloò hlavu a dr hubu, nebo tì rozpùlí vejpùl. Maj nejsilnìjší zbranì na tıhle stranì mìsta, take nikdo, kdo má aspoò špetku rozumu, s nima nevyjebává, rozumíš?}
{711}{}{Jaké mají Salvatoøi "zbranì"?}
{712}{}{To zní, jako by mìli nìjaké brutální bouchaèky. Co je to za zbranì?}
{715}{}{Zajímavé... díky za varování.}
{725}{}{Pistole... a na to, e støílej SVÌTLO. Víš, Reno je sice mìsto svìtel, ale svìtlo, kterı TYHLE pistole støílej, dokáe rozpùlit chlapa vejpùl... *vum*... (Jules sekne rukou ve vzduchu.) Rozpùlí tì na dvì pùlky jako nic.}
{726}{}{Støílejí svìtlo? Neøíkají jim náhodou 'laserové pistole?'}
{727}{}{Tak na to si dám pozor. Mùeš mi øíct nìco o ostatních rodinách?}
{735}{}{No, eh, vlastnì ani nevím... nejsem si tak úplnì jistej, o èem to mluvíš, ale øeknu ti tohle: Neptej se na ty pistole Salvatorù. Maj takovej ošklivej zlozvyk zabíjet lidi, co jsou moc zvìdaví.}
{736}{}{Julesi, 'laserovımi pistolemi' myslím pistole, které vyzaøují paprsek koherentního svìtla. Takovı paprsek o síle... øeknìme nìkolika megawattù... dokáe napáchat znaèné škody, pokud se zamìøí na cíl po dobu nìkolika sekund, èím vytvoøí efekt, kterı popisuješ.}
{737}{}{Mìli tyhle pistole odjakiva?}
{750}{}{Odjakiva ne... jinak by u šéfovali New Renu... CELİMU New Renu. Zatím se jenom pomalu propracovávaj nahoru. Ty pistole se objevily... asi pøed pár mìsícema, jak byl ten masakr.}
{751}{}{Masakr?}
{765}{}{Jo... dva Salvatorovi mui zabili tìma pistolema hromadu Bishopovejch chlapù a pak ještì postøíleli pár Mordinù, co se chtìli dostat na Druhou ulici. Od tı doby si dávaj ostatní rodiny na Salvatory bacha.}
{766}{}{To urèitì zní jako lasery. Nevíš, èím Salvatoøi pohánìjí své laserové pistole? Pouívají baterie, fúzní èlánky nebo snad nìjaké napájení pøes kabely?}
{767}{}{Nenapadá tì, odkud ty pistole mají?}
{780}{}{Nemám páru, kámo, neptal jsem se a ty to taky radši nedìlej... vìø mi. Jestli se sháníš po zbraních, jsou i jinı... bezpeènìjší... místa, kde se mùeš poptat.}
{781}{}{Jako tøeba?}
{782}{}{Povìz mi ještì nìco o ostatních rodinách.}
{795}{}{Eh... no, o tom já nic nevím a... hmmmm. Víš, mluvíš jako jeden z tìch bílejch plášù ze Stájí. Nejseš náhodou jeden z nich?}
{796}{}{Stájí?}
{810}{}{(Nakloní se k tobì.) No, nechce se mi zrovna mluvit o míò PØÍJEMNEJCH èástech New Rena, ale ve Stájích na sever od mìsta je pár tıpkù v bílejch pláštích, co mluvìj pøesnì jako ty. Jsou tìce hlídanı Mordinovımi mui.}
{811}{}{A co tam dìlají?}
{825}{}{Co jsem slyšel, tak prej testujou novı druhy Jetu. Ale mezi náma, kámo, nechoï tam vyzvídat... Mordinové nemaj rádi návštìvníky. A krom toho... Jules ti seene jakıkoliv mnoství Jetu budeš chtít.}
{826}{}{Proè poøád Mordinové testují Jet? Pøipadá mi, e u je dost návykovı.}
{827}{}{Na kom Mordinové testují ty drogy?}
{828}{}{Nevíš, jak se do tìch Stájí dostat?}
{840}{}{Na otrocích. Maj je tam zavøenı ve stájích jako brahmíny. }
{841}{}{Mordinové je nakupujou od otrokáøù, kterı procházej kolem. }
{842}{}{Mordinové je nakupujou od otrokáøù, jako jseš ty, kterı procházej New Renem. }
{843}{}{Kupujou jich fakt hodnì, paè èasto onemocní, uteèou... nebo umøou. Vìtšinou umøou.}
{860}{}{Nejspíš proto, aby byl ještì lepší. Vylepšíš proces, vylepšíš drogu. Jet je dobrej, ale jestli ho dokáou udìlat ještì LEPŠÍ... tak to bude jako rozdíl mezi poletováním na obloze a letem na mìsíc.}
{880}{}{Zadr... na tvım místì bych na to ani NEPOMYSLEL, kámo. Mordinové to místo hlídaj jak vzteklí psi. Prostì na to zapomeò.}
{881}{}{Musí bıt nìjakı zpùsob, jak se tam dostat...}
{886}{}{Tak dobøe, kašli na to. Díky za informace.}
{895}{}{No... kdy budeš mluvit stejnì chytøe jako doteï, moná se budeš moct vydávat za jednoho z tìch bílejch plášù. No a nebo se mùeš nechat naverbovat Mordinama a oni tì tam tøeba pošlou...}
{910}{jules45}{Ha! John Bishop? Není o èem mluvit: Bishop je mazanej, tvrdej a chce mít VŠECHNO.}
{911}{}{No, tak to si to bude muset nejdøív vyøídit se mnou. Kde má ten kokot území?}
{912}{}{Kde je jeho území?}
{925}{}{Vìtšinou je v klubu Shark na Druhı ulici. Je kolem nìj spousta stráí, take na návštìvu zapomeò, pokud s ním nemáš OPRAVDOVEJ byznys. (Šibalsky se usmìje.) A dr se dál od jeho eny. A jeho DCERY.}
{926}{}{Eh, byznys?}
{927}{}{Nemusíš se bát.}
{935}{}{Však víš, co tím myslím, brácho. Dr se dál od tìch dvou, jestli se nechceš dostat na Bishopùv seznam.}
{936}{jules48}{No to je monı, ale na tom, CO máš mezi nohama, nezáleí... aspoò ne sleènì Bishopovı. Ta je nadrená jak stepní koza.}
{937}{}{Eh, povìz mi ještì nìco o ostatních rodinách.}
{945}{}{Wrightovi? Hehe. Wrightovi jsou jediná rodina, která JE opravdová rodina, kdeto ostatní rodiny maj jen oldáky a gangstery, ale Wrightovic rodina JE Wrigtovic rodina, rozumíš?}
{946}{jules50}{Mám pro tebe varování tıkající se Wrigtovic rodiny, otrokáøi... víš, Wrightovi jsou toti jediná rodina, která JE opravdová rodina.}
{947}{}{Jsou opravdová rodina? Kolik jich je?}
{960}{jules51}{Nejmíò dvacet nebo víc pokrevnì pøíbuznejch Wrightù. Jsou hroznì zlí a jeden ošklivìjší ne druhej.}
{961}{}{Nejmíò dvacet nebo víc pokrevnì pøíbuznejch Wrightù a nemaj vùbec v oblibì lidi tvıho øemesla. Øíká se, e jim kdysi nìjakej otrokáø unesl sestru a od tı doby je nemaj v lásce.}
{962}{}{Co ovládají Wrightové v New Renu?}
{975}{}{Nemaj ádnı kasína, take vìtšinou jen kšeftujou s alkoholem a prodávaj ho ostatním rodinám. Take jestli se sháníš po poøádnı flašce... najdeš je na vıchodní stranì mìsta v takovı velkı vile.}
{985}{}{Brácho, nemusíš chodit dál ne ke zde pøítomnımu Julesovi. }
{986}{}{Ségro, nemusíš chodit dál ne ke zde pøítomnımu Julesovi. }
{987}{}{Sladká sestøièko, nemusíš chodit dál ne ke zde pøítomnımu Julesovi. }
{988}{}{Mám VŠECHNO a co nemám, to nepotøebuješ. Take, mùem pøejít k obchodu?}
{989}{}{Jasnì. Pojïme obchodovat.}
{990}{}{Jaké drogy se dají v New Renu sehnat?}
{991}{}{Teï ne. Chci se ještì zeptat...}
{992}{}{Vlastnì mì teï ádné drogy nezajímají. Musím jít.}
{1005}{}{JAKİKOLIV. Mám vìci, po kterıch budeš nadrenej, tvoje stará bude nadrená, tvoje péro bude stát, daj ti sílu, rozum... a samozøejmì mám i drogu, která ti umoní lítat... Jet.}
{1006}{}{JAKİKOLIV. Mám vìci, po kterıch budeš nadrená, vlhká, zbavìj tì kocoviny, uklidnìj tì, zvıšej ti libido, budeš šastná, daj ti sílu, rozum... a samozøejmì mám i drogu, která ti umoní lítat... Jet.}
{1008}{}{Odkud pochází Jet? Byl tu odjakiva?}
{1025}{}{No... eh... Jet je odsud... z Rena. Není tady dlouho, ale je po nìm velká POPTÁVKA, jestli mi rozumíš. (Mrkne.) Totální hit mezi turisty, jako jseš ty.}
{1026}{}{Chci si nìco koupit. Pojïme obchodovat.}
{1027}{}{Ale jak to, e je Jet odsud?}
{1035}{}{No... víš, Mordinové mìli zatracenì velkı štìstí, kdy našli tu mozkovnu jménem Myron. Má talent, kdy jde o vytváøení drog. To on VYTVOØIL Jet.}
{1036}{}{Tak Myron, jo? Kde ho najdu?}
{1045}{}{(Nakloní se k tobì.) No, nechce se mi zrovna mluvit o míò PØÍJEMNEJCH èástech New Rena, ale na sever od mìsta jsou Stáje. Je to tam tìce hlídanı Mordinovımi mui. Tam najdeš i Myrona.}
{1046}{}{Stáje za mìstem?}
{1055}{}{Jo, Mordinové tam drej svıho zlatıho chlapce. Dávaj mu prachy, kurvy, cokoliv chce, dokud dìlá drogy. Jet je jeho NEJLEPŠÍ vıtvor. Nikdy jsem nevidìl nic tak návykovıho. Pøevrátil s ním Reno naruby, to ti teda øeknu.}
{1056}{}{Myslíš, e by bylo moné se s tím Myronem setkat?}
{1065}{}{(Jules se zastaví a prohlédne si tì od hlavy k patì.)}
{1066}{}{Julesi? Haló? Ptala jsem se, jestli se mùu setkat s Myronem.}
{1075}{}{Prr, bratøe, mám pro tebe radu: Nepokoušej se setkat s Myronem, paè jestli TO Mordinové zjistìj, tak tì vykuchaj a nechaj tì chcípnout v Golgotì.}
{1076}{}{To bych ani nezkoušel. Jestli potøebuješ Jet, nemusíš chodit za Myronem, protoe ho mùeš mít ode mì. Jestli Mordinové zjistìj, e se snaíš dostat k Myronovi, tak tì vykuchaj a nechaj tì chcípnout v Golgotì.}
{1077}{}{No... MONÁ by to šlo. Problém je v tom, e jestli se o tom dozvìdìj Mordinové, tak tì vykuchaj a nechaj tì chcípnout v Golgotì.}
{1078}{}{Opravdu to jinak nejde?}
{1079}{}{Jak by to moná šlo?}
{1080}{}{Proè sis mì pøed chvílí prohlíel jako nìjakou sochu?}
{1081}{}{Golgota? Co je to za místo?}
{1083}{}{Zajímavé. Díky za informace.}
{1101}{}{Opravdu to jinak nejde?}
{1102}{}{Jak by to moná šlo?}
{1103}{}{Proè sis mì pøed chvílí prohlíel jako nìjakou sochu?}
{1115}{}{Protoe jsem chtìl zjistit, jestli jseš Myronùv typ, ale nevypadáš na to. Moná kdyby ses trochu upravila, tak bys moná mohla Myrona zaujmout... víš, on je hodnì na enskı. }
{1116}{}{(Ušklíbne se.) Protoe vypadáš DOBØE, zlato. A Myron má rád enskı, kterı vypadaj DOBØE. }
{1117}{}{Ten kluk je jako králíèek, kterej poøád hledá novı jamky pro svı mrkvièky.}
{1118}{}{Co jsi to pøedtím øíkal o Golgotì?}
{1119}{}{Eh, skvìlı. Díky za radu, Julesi. Poslyš, chci se ještì zeptat...}
{1120}{}{No, tak to abych šla.}
{1121}{}{Krásnì øeèeno. Kdy mluvíš, je to jako poezie... díky slovu "mrkvièka" si to dokáu parádnì pøedstavit. DÍKY.}
{1130}{}{Moná kdybys byl hezká enská, ale jinak potøebuješ povolení od Mordinù. A ani jedno není moc pravdìpodobnı.}
{1132}{}{Aha. Mám ještì jiné otázky...}
{1145}{}{Pokud chceš zbranì, tak zajdi za mım kámošem Eldridgem do Obchodní ètvrti. Má bouchaèky, kterı zabijou èlovìka døív, ne tì vùbec UVIDÍ. Øekni mu, e tì posílám.}
{1146}{}{Rozumím, brácho, rozumím. Jestli chceš to nejlepší, tak zajdi za mım kámošem Eldridgem do Obchodní ètvrti. Má bouchaèky, kterı zabijou èlovìka døív, ne tì vùbec UVIDÍ. Øekni mu, e tì posílám.}
{1147}{}{Rozumím, ségro, rozumím. Jestli chceš to nejlepší, tak zajdi za mım kámošem Eldridgem do Obchodní ètvrti. Má bouchaèky, kterı zabijou èlovìka døív, ne tì vùbec UVIDÍ. Øekni mu, e tì posílám.}
{1148}{}{Drahoušku, ty U jseš ïábelsky vyzbrojená svım tìlem. Ale jestli chceš víc, tak zajdi za mım kámošem Eldridgem do Obchodní ètvrti. Má bouchaèky, kterı zabijou èlovìka døív, ne tì vùbec UVIDÍ. Øekni mu, e tì posílám.}
{1150}{}{Díky za radu. Myslím, e u pùjdu.}
{1165}{}{Potøebuješ zásoby? No, MÙEŠ jít za Renescem do Obchodní ètvrti... ale je v tom takovej malej háèek: ádnı drogy od nìj nekupuj, paè jsou NEBEZPEÈNİ. Sice má spoustu zboí, ale jestli chceš drogy, tak si radši promluv se mnou.}
{1166}{}{Budu si to pamatovat. Poslyš, chci se ještì zeptat...}
{1167}{}{Jeho drogy jsou nebezpeèné, jo? No, tak díky za radu, já u pùjdu.}
{1175}{}{Rozumím, brácho. Vìtšina TURISTÙ se jen projde po ulici Panen a nechaj si ho vykouøit od nìjakı lacinı kurvy, ale ty vypadáš na to, e máš docela úroveò, take zajdi do Koèièí Packy tady pøes ulici a øekni jim, e tì posílá Jules.}
{1176}{}{Rozumím, ségro. Vìtšina TURISTEK se jen projde po ulici Panen a nechaj si ji vylízat od nìjakıho teplouše, ale ty vypadáš na to, e máš docela úroveò, take zajdi do Koèièí Packy tady pøes ulici a øekni jim, e tì posílá Jules.}
{1177}{jules76}{(Usmìje se a roztáhne ruce.) Dál u nehledej, má sladká sestøièko. Jules je ti k slubám!}
{1178}{}{Eh, díky, Julesi, ale ne. Chci se ještì zeptat...}
{1180}{}{No, díky za radu, ale budu muset jít.}
{1181}{}{No, eh, díky, ale budu muset jít.}
{1190}{jules77}{Myslíš Vault CITY, e jo? To je na severovıchod. Nemùeš ho minout, staèí sledovat vyjetı cesty od karavan.}
{1191}{}{Dobøe. Poslyš, chci se ještì zeptat...}
{1192}{}{Díky za radu, ale u musím jít.}
{1200}{jules78}{GECK? To je nìjaká nová droga? Co to dìlá? Lítáš po ní?}
{1201}{}{Ne, to je... ale nic, to je jedno. Chci se zeptat na nìco jiného...}
{1202}{}{To je jedno. Budu muset jít.}
{1210}{jules79}{O tom nic nevím, promiò. Nemohli to bejt otrokáøi?}
{1211}{}{Moná. Chci se ještì zeptat...}
{1220}{jules80}{Coe?}
{1221}{}{Zapomeòte na to. Chci se ještì na nìco zeptat...}
{1230}{}{Eh... Wrightovic kluk? Jo, slyšel jsem o tom. Je to fakt škoda, takhle malı dìti by drogy brát nemìli. Mùou proít úasnej ivot i bez míchanıho fetu.}
{1231}{}{Kdy u mluvíme o míchaném fetu, Renesco øíkal, e prodáváš Jet øíznutı arsenem.}
{1232}{}{Co myslíš tím "míchaného fetu?"}
{1233}{}{Nevíš náhodou nìco o téhle prázdné nádobce Jetu?}
{1234}{}{Zajímavé, e to øíkáš zrovna ty... já si toti myslím, e se nepøedávkoval. Podle mì ho nìkdo otrávil.}
{1250}{}{(Pokrèí rameny.) Nìkterejm dealerùm je fuk co prodávaj a jestli lidi umøou. Nic jsem neøekl, ale já bych si proklepnul Rakeáka Renesca a zjistil, jak dobrej fet má.}
{1251}{}{Mluvil jsem s Renescem... a on mi øekl, e prodáváš Jet øíznutı arsenem.}
{1252}{}{Reno je velké mìsto, Julesi. Nenapadá tì ještì nìkdo?}
{1253}{}{Chci se ještì zeptat...}
{1254}{}{Dobøe, podívám se na nìj.}
{1270}{}{Ve mìstì je hromada dealerù... moná Malej Jeíš Mordino, ale proè by prodával Wrightovi? To nedává smysl. Pak je tady Poøezanej Jimmy J nahoøe na Druhı ulici, ale to je malá ryba. Já bych si stejnì proklepl Renesca.}
{1272}{}{"Poøezanej Jimmy J?" Kdo to je?}
{1273}{}{Malej Jeíš Mordino? Kde ho najdu?}
{1274}{}{To moná udìlám. Chci se ještì zeptat...}
{1275}{}{Malej Jeíš... Poøezanej Jimmy J... Renesco. Mám to. Díky.}
{1290}{}{(Julesùv úsmìv zmizí.) Hledám lidi, jako jseš ty. Lidi, co pøicházej do Rena. Tohle je toti skvìlı místo k obchodu. A navíc mi nìkterı podniky platìj za to, e k nim posílám turisty. Staèí ti TAKOVÁ odpovìï?}
{1291}{}{Ano. Chci se zeptat na nìco jiného...}
{1292}{}{Jen se tak ptám. Díky za upøímnost.}
{1305}{jules85}{Tvoje AUTO? Urèitì bylo zaparkovanı tady? Nevidìl jsem ho.}
{1306}{}{Coe? Najednou jsi SLEPİ? A moji PÌST vidíš, zmrde? VIDÍŠ ji?!! Ještì jednou øekni, e jsi moje auto nevidìl... a DOSTANEŠ ránu.}
{1307}{}{Julesi, jestli mi neøekneš, co se stalo s mım autem, øeknu Wrightovi, e jsi to byl TY, kdo prodal jeho synovi Jet, kterı ho zabil. Budeš mrtvej do hodiny. Mluv.}
{1308}{}{Jsi si JISTİ, Julesi?}
{1309}{}{Ano, bylo zaparkované tady. Nevíš náhodou, kde by mohlo bıt?}
{1310}{}{Tak dobøe. Chci se ještì na nìco zeptat...}
{1311}{}{Jdu se po nìm radìji podívat.}
{1320}{}{Ne, brácho, nevidìl jsem ho. }
{1321}{}{Ne, ségro, nevidìl jsem ho. }
{1322}{}{Zkusím se poptat. (Pokrèí rameny.) Ale Reno je velkı mìsto...}
{1323}{}{Julesi, mám takovı divnı POCIT, e víš, kam zmizelo moje auto. Jestli mi to neøekneš, pouiju tì jako cviènı terè. A teï mluv.}
{1324}{}{No, stejnì díky. Chci se zeptat...}
{1340}{}{Ségro, já o tvım autì NIC nevím. }
{1341}{}{Brácho, já o tvım autì NIC nevím. }
{1342}{}{NEVIDÌL jsem, co se s ním stalo a ani NEVÍM, kde je. }
{1343}{}{(Nenávistnì se podívá na Codyho pøes ulici.)}
{1344}{}{Opravdu? To zní jako pìkná hromada SRAÈEK.}
{1345}{}{Fakt? Já VÍM, e jsi s ním nìco udìlal, take mi radši øekni, kde je, ne TI nìco udìlám.}
{1346}{}{Tak nic, budu hledat dál.}
{1360}{}{Tak jo, brácho, tak jo! }
{1361}{}{Tak jo, ségro, tak jo! }
{1362}{}{...vidìl jsem nìjakı chlápky, jak ho pøed chvíli odtáhli. Bylo jich moc, abych je zastavil, víš, a...}
{1363}{}{Dr hubu a zaveï mì k nim. HNED.}
{1364}{}{Nevadí, podívám se po nich i bez tebe.}
{1375}{jules94}{Dobrá, dobrá ...}
{1376}{}{Mimochodem... Julesi... jestli se jenom špatnì PODÍVÁŠ na toho kluka pøes ulici, vrátím se zpátky a zabiju tì tolikrát, e budeš potøebovat nìkolik závìtí. Jasné? A teï jdi.}
{1377}{}{Ještì jedna vìc, Julesi: Jestli uslyším, e nìco zkoušíš na Codyho, tak tì zabiju. A teï mì zaveï k mému autu.}
{1378}{}{[Jít za ním]}
{1385}{jules95}{N... nazdar. (Nervóznì se usmìje. Jeho kolínská tì málem porazí.) Jmenuju se Jules. Potøebuješ nìco, kámo? C... cokoliv?}
{1386}{}{N... nazdar. Hej, vítej zpátky! (Nervóznì se usmìje. Jeho kolínská tì málem porazí.) Potøebuješ nìco od kámoše Julese, kámo? C... cokoliv?}
{1389}{}{Mám nìjaké otázky...}
{1390}{}{Fajn kolínská, Julesi. Byla cítit všude kolem Codyho tìla. Jsi mrtvı.}
{1391}{}{Cody je mrtvı, Julesi. A vsadím se, e za to mùeš ty. Jsi mrtvı.}
{1405}{jules97}{H-hej, RÁD bych ti pomohl, ale já nic nevím... poslyš, u musím jít.}
{1406}{}{Fajn kolínská, Julesi. Byla cítit všude kolem Codyho tìla. Jseš kurva mrtvej.}
{1407}{}{Cody je mrtvı, Julesi. A vsadím se, e za to mùeš ty. Jseš kurva mrtvej.}
{1408}{}{Zatím, Julesi.}
{1415}{}{To je jeden debilní zkurvysyn, kterej si myslí, e je velkej dealer. Nemùeš ho minout... má velkou jizvu pøes celej oblièej. Ten blbec jednou v noci lítal na Jetu a zkoušel se oholit bojovım noem. Smutnı je, e to PØEIL.}
{1416}{}{A Malej Jeíš Mordino? Kde najdu jeho?}
{1417}{}{Vidím, e se tu mají všichni rádi... poslyš, chci se ještì zeptat...}
{1425}{}{No, kámo, já bych byl opatrnej a rozhodnì bych jen tak nevtrhnul k Malımu Jeíšovi a nezaèal ho z nìèeho obviòovat. Ale jestli s ním chceš OPRAVDU mluvit, nebudu ti v tom bránit. Vìtšinou je v Desperadu támhle pøes ulici.}
{1426}{}{A "Poøezanej Jimmy J?" Kdo je to?}
{1427}{}{Poslyšte, chci se ještì zeptat...}
{1435}{jules100}{To mì nepøekvapuje... takovı vìci se v tomhle mìstì stávaj ÈASTO.}
{1436}{}{Co tím myslíš?}
{1437}{}{Co mi mùeš øíct o téhle prázdné nádobce Jetu?}
{1439}{}{Aha. No, díky za tvùj èas.}
{1450}{jules101}{(Podívá se na nádobku.) Takovejch jsem vidìl stovky. Ale moje není... mohla by bıt Poøezanıho Jimmyho J nebo Renesca.}
{1451}{}{Poøezanej Jimmy J?}
{1452}{}{Renesco?}
{1453}{}{Hmmm. Chci se ještì zeptat...}
{1470}{}{To je jeden debilní zkurvysyn na Druhı ulici. Nemùeš ho minout... má velkou jizvu pøes celej oblièej. Ten blbec jednou v noci lítal na Jetu a zkoušel se oholit bojovım noem. Smutnı je, e to PØEIL.}
{1471}{}{A Renesco? Kde najdu jeho?}
{1473}{}{Rozumím. Díky.}
{1485}{}{To je jeden starej hajzl, kterej má lékarnu v Obchodní ètvrti... jdi pár ulic na sever, zahni doleva u Salvatorova a Bishopova kasína a pak pokraèuj furt rovnì. Je to napravo.}
{1486}{}{A "Poøezanej Jimmy J?" Kde najdu jeho?}
{1487}{}{Dobøe... poslyš, chci se ještì na nìco zeptat...}
{1500}{}{Øekni tomu hajzlovi, e jestli ještì nìkdy øekne takovou sraèku, tak ho ZABIJU døív, ne to udìlá starej Wright. Víš, kdo takhle kecá? Takhle kecá nìkdo, kdo je posranej STRACHY.}
{1501}{}{Aha... mám ještì nìjaké otázky...}
{1502}{}{Rozumím. Pùjdu se za ním podívat.}
{2000}{jules198}{To je AUTO? Sákryš.}
