{100}{}{Vidíš Keitha Wrighta.}
{150}{}{Vidíš hubeného bledého mue s dlouhımi blond vlasy. Pozornì tì sleduje.}
{151}{}{Vidíš Keitha Wrighta. Pozornì tì sleduje.}
{200}{keith1}{Kdo jsi?}
{201}{keith2}{Co chceš?}
{220}{}{Nazdar, }
{230}{keith4}{Ještì jeden krok smìrem k tìm dveøím a budeš toho litovat.}
{240}{keith5}{Poøád nemùu uvìøit, e je táta mrtvej. Chtìl jsem mu toho ještì tolik øíct...}
{250}{keith6}{Otrokáøi, jseš ve špatnı èásti mìsta. Jestli rychle nevyklopíš, co tady chceš, tak si koleduješ o prùšvih.}
{251}{keith7}{Já tì neznám, táta tì nezná a jestli nezaèneš mluvit, tak na tom ani nebude záleet.}
{252}{}{Jak to jde, }
{253}{}{Díky za vypátrání Richardova vraha, }
{254}{keith10}{Co chceš?}
{255}{}{Mattah. Chlap je Mattah!}
{256}{}{Jabawookie cing cing.}
{257}{}{Odbelhat se.}
{258}{}{Hledám práci. Nabírají Wrightovi?}
{259}{}{Hledám práci. Posílá mì Chris. Nabírají Wrightovi?}
{262}{}{Nazdar, Keithe. Potkal jsem tvou mámu.}
{263}{}{Mùeš mi øíct nìco o tvém bratru Richardovi?}
{264}{}{Zapomeò na to. Omlouvám se za obtìování.}
{280}{keith11}{Vypadni odsaï, debile. Ještì jednou na mì promluvíš a udìlám z tebe cedník.}
{281}{}{Dírııı dírııı fšude dírıı.}
{282}{}{Šámma Lámma DING DONG.}
{290}{keith12}{Vypadni odsud! To je poslední varování!}
{291}{}{Já ale chııtrııı, cink cink.}
{292}{}{DING DONG! DING DONG!}
{300}{keith13}{Varoval jsem tì...}
{301}{}{Coo?}
{310}{keith14}{Jsem Keith Wright z rodiny Wrightù. Øekneš mi u koneènì co tady chceš?}
{312}{}{Chris mi øekl, a se tu zastavím. Hledám práci. Mùeš mi pomoct?}
{313}{}{Keith Wright, jo? Potkal jsem tvou mámu.}
{315}{}{Co je tohle za místo?}
{325}{keith15}{Tohle je DOMOV rodiny Wrightù. Øekneš mi u, co tady chceš?}
{335}{keith16}{Chris tì poslal, jo?}
{336}{}{Pøesnì tak. Øíkal, e by se pro mì moná našla nìjaká práce.}
{345}{keith17}{Sice nevím, jestli to má vùbec smysl, ale mùu se táty zeptat...}
{346}{}{To by bylo fajn.}
{355}{}{Ne... nenabíráme novı lidi jako ostatní rodiny. Alespoò zatím ne. }
{356}{}{Ne... my s otrokáøskou verbeí nespolupracujeme jako to dìlají ostatní rodiny. }
{357}{}{Radši zmiz.}
{358}{}{Nepùjdu, dokud si nepromluvím s panem Wrightem.}
{359}{}{Tak dobøe.}
{365}{keith20}{Ne, já si myslím, e ODEJDEŠ, paè vypadáš jako nìkdo, kdo rád ije. A teï padej.}
{366}{}{Já NEODEJDU.}
{367}{}{Tak dobøe.}
{375}{keith21}{VAROVAL jsem tì...}
{376}{}{Chceš si se mnou zahrávat, hajzle?! Tak pojï...}
{380}{keith22}{Eh... co je s ní? Zase je v nìjakım prùšvihu?}
{381}{}{Ne. To je u ní èasté?}
{383}{}{Ne, není. Zatím, Keithe.}
{390}{keith23}{Obèas jo. Poøád káe o tom, jak je chlast a hazard špatnej a... vlastnì skoro všechno. Obèas je z toho pìknej povyk a táta je pak dìsnì naštvanej.}
{391}{}{Ví vùbec tvoje máma, co dìlá vaše rodina?}
{392}{}{To vìøím. No, díky za rozhovor, Keithe.}
{400}{keith24}{Ne, nemá o tom ani páru. Myslí si, e je táta èistej a nedìlá nic nelegálního, ale není zrovna moc všímavá. Kdyby našla tu palírnu pod nádraím, udìlala by tu peklo.}
{401}{}{Aha. Díky, Keithe.}
{410}{keith25}{(Zavrtí hlavou.) Tak tohle u pøehnala, kdy znièila tátovu palírnu. Dìlníci mìli strach ji zastavit, táta jí pak jednu vlepil a ona mu to vrátila. (Pokrèí rameny.) Nìjakou dobu bude trvat, ne se z toho táta vzpamatuje.}
{420}{keith26}{Fajn kluk. Sakra, jestli nìkdy pøijdeme na to, kdo mu to udìlal...}
{421}{}{Nìjakı nápad, kdo to mohl udìlat?}
{422}{}{No, doufám, e toho vraha najdete. Nashle, Keithe.}
{430}{keith27}{Vìtšina ostatních rodin prodává Jet, take to mohl bejt kdokoliv z nich. Ale nejvíc dealerù maj Mordinové, protoe vırabìj nejvíc Jetu. Já bych to tipoval na jednoho z nich.}
{431}{}{Které dealery podezøíváš?}
{432}{}{Mùeš mi øíct nìco o Richardovi?}
{440}{keith28}{Je jich nìkolik: Poøezanej Jimmy J na Druhı ulici, starej zkurvysyn Renesco v Obchodní ètvrti... a taky Jules u vchodu do mìsta dealuje, ale vìtšinou jen blbejm turistùm. No a pak je tady Malej Jeíš Mordino.}
{441}{}{Malej Jeíš Mordino?}
{442}{}{Mùeš mi øíct nìco o Richardovi?}
{443}{}{Díky za info, Keithe.}
{450}{keith29}{Hodnej, èistej kluk. Drel se dál od problémù, co je na Wrighta docela úspìch. Pøed nìjakou dobou jsme ho pohøbili na Golgotskıch planinách, ale i tak máma nechce, abysme dìlali nìco s jeho pokojem. Je pro ni tìkı zapomenout, víš.}
{451}{}{Kterı pokoj byl jeho? Myslíš, e bude mít tvoje matka nìco proti, kdy se tam porozhlédnu?}
{452}{}{Kteøí dealeøi mu mohli dát ten Jet?}
{454}{}{Pohøbenı v Golgotì, jo? Hmmm. Díky za info, Keithe.}
{460}{keith30}{Jeho pokoj? Je to ten prázdnej vedle mámina, druhej odshora. A co se tıèe rozhlíení... no... hele, nezùstávej tam dlouho... a neudìlej tam ádnej bordel, nebo mámì praskne cévka.}
{461}{}{Díky, Keithe. Nebudu tam dlouho.}
{470}{keith31}{Poèkej. (Zaklepe na dveøe za sebou.) Tati? (Strèí hlavu dovnitø. Je slyšet nezøetelnı rozhovor, poté se vrátí a kıvne hlavou ke dveøím.) Mùeš jít dovnitø, ale dej si bacha. Táta má blbou náladu.}
{471}{}{Díky.}
{480}{keith32}{Je to syn Velkıho Jeíše. Pìknej bastard. Mohl nìkde potkat Richarda samotnıho a pak ho napumpovat Jetem. Jestli ho pùjdeš hledat, podívej se do Desperada. Oba se tam zdrujou.}
{1220}{}{. Co se dìje?}
{1252}{}{. Chovaj se k tobì všichni dobøe? Mùu ti nìjak pomoct?}
{1253}{}{. Jsme ti opravdu dluni a Wrightovi svoje dluhy vdycky platí. Co pro tebe mùu udìlat?}
