{100}{}{Vidíš paní Bishopovou.}
{101}{}{Vidíš jeèící paní Bishopovou.}
{150}{}{Vidíš atraktivní enu ve støedních letech. Vypadá znudìnì.}
{151}{}{Vidíš paní Bishopovou. Vypadá znepokojenì a zírá nìkam do dálky.}
{200}{lbshp1}{(ena se k tobì otoèí. Je docela atraktivní. Má na sobì šaty z kùe zlatého geckona s hlubokım vıstøihem. Chvíli si tì prohlíí a poté se zamraèí.) Ano, co je?}
{201}{lbshp2}{(Lehce se zamraèí.) Ano? Co potøebujete tentokrát?}
{203}{}{uk-uk.}
{204}{}{[Zírat na její prsa a slintat]}
{205}{}{Odbelhat se.}
{206}{}{Kdo jsi?}
{207}{}{Chci vám poloit pár otázek, paní Bishopová.}
{208}{}{Promiòte, to bude omyl. Sbohem.}
{210}{lbshp3}{*Coe?*}
{211}{}{uk-UK!}
{212}{}{[Zírat na její prsa a slintat]}
{215}{lbshp4}{(Mrkne.) Kdo je tam?}
{216}{}{Bù.}
{217}{}{Já zapomnìt.}
{218}{}{Kdo kde?}
{220}{lbshp5}{(Vypadá zmatenì.) Bù kdo?}
{221}{}{Bù kdo? Nebreèet, hezká pani! HA HA HA HA HA HA HA Hah Hahhh... hùùùù... chápat?}
{225}{lbshp6}{(Podívá se na tebe vzteklım pohledem.) Okamitì vypadnìte, nebo vás nechám zastøelit, vy odpornı hmyze.}
{226}{}{Bù... hù... hee-hee-hee-hee... bù kdo? Bù hù! HA HA HA HA HA...}
{227}{}{Já ne odbornı hmyz... *smrk*... já srandovní... máma øíkat... *smrk*...}
{230}{lbshp7}{(Sleduje, jak se jí díváš na prsa. Vztekem zrudne, otevøe ústa... a poté se zarazí.) Inteligencí pøíliš neoplıváte... (Prohlédne si tvou postavu.) Ale máte docela hezké... svaly. Pojïte za mnou na chvíli.}
{231}{lbshp8}{(Sleduje, jak se jí díváš na prsa. Vztekem zrudne, otevøe ústa... a poté se zarazí.) Inteligencí pøíliš neoplıváte... (Prohlédne si tvou tváø.) Ale máte docela... šarm. Pojïte za mnou na chvíli.}
{232}{lbshp9}{(Sleduje, jak se jí díváš na prsa. Její hlas zvání.) Diskrétnost není zrovna vaše silná stránka, e? (Znechucenì se na tebe podívá.) Vypadnìte, ne vás nechám zastøelit.}
{233}{}{[Následovat ji]}
{234}{}{My jít dobré místo?}
{235}{}{Ty jít. Já zùstat.}
{236}{}{Odbelhat se.}
{240}{lbshp10}{(Lehce se usmìje.) Ano. *Velmi* dobré místo. A teï pojïte.}
{245}{lbshp11}{(Zamraèí se a zrudne jí tváø.) Vypadnìte odsud, ne vás nechám zastøelit.}
{246}{}{Promíííò... já jít.}
{250}{}{(Pozdvihne oboèí.) Myslím, e na tuhle otázku bych se mìla spíše ptát *já*. (Zaloí ruce.) Jsem Leslie Anne Bishopová. }
{251}{}{Mùj manel je hlava rodiny Bishopù v New Renu. A VY jste...?}
{252}{}{Mùj nebotík manel byl hlava rodiny Bishopù v New Renu. A VY jste...?}
{253}{}{Jmenuju se }
{254}{}{Jsem jenom obyèejnı cestovatel.}
{255}{}{Jsem cestovatel a hledám Vault 13. Neslyšela jste o nìm nìkdy?}
{256}{}{Jsem cestovatel... nevíte náhodou, kde by se mohla nacházet vìc zvaná 'GECK?'}
{257}{}{Promiòte, ale u musím jít. Sbohem.}
{260}{lbshp14}{Ano?}
{261}{}{Mùete mi øíct nìco o panu Bishopovi?}
{262}{}{Mùete mi øíct nìco o rodinì Bishopù?}
{263}{}{Neslyšela jste nìkdy o místì zvaném Vault 13?}
{264}{}{Nevíte, kde by se mohla nacházet vìc zvaná 'GECK?'}
{265}{}{U nic. Radìji pùjdu.}
{270}{lbshp15}{Mùj manel? To je jednoduché. Je mrtvı. TAKOVÁ tragédie. Ještì poøád jsem se nevzpamatovala z toho šampaòského, které jsem vypila, kdy jsem se to dozvìdìla.}
{271}{lbshp16}{Mùj manel? Je hlava Bishopovy rodiny. V diplomacii, obchodì a kriminálních aktivitách si poèíná jako mazané zvíøe, co nelze neobdivovat, avšak jeho další schopnosti jsou opovreníhodné.}
{272}{}{Ano, jeho taktika najímání 'nájezdníkù', aby zapùsobil na Vault City, se zdá bıt docela efektivní.}
{273}{}{Další schopnosti?}
{275}{}{Promiòte, e se ptám. Radìji pùjdu.}
{276}{}{Promiòte, paní Bishopová. Nechci rıpat. U pùjdu.}
{280}{lbshp17}{(Zamraèí se.) To nechám na vaší pøedstavivosti. (Vypadá podrádìnì.) U je to *všechno?*}
{281}{}{Vlastnì se chci ještì zeptat...}
{285}{lbshp18}{O Bishopovì 'rodinì' toho není moc co øíct. No, vlastnì... její souèástí je jedna veliká rodina najatıch hrdloøezù, oldákù, kurev, feákù a otrokù, co je také jedinı dùvod, proè je Bishopova 'rodina' tak veliká.}
{286}{}{To zní, jako kdyby vaše manelství nebylo zrovna moc šastné.}
{287}{}{No, ještì je tady ta 'rodina' oldákù, které pan Bishop najal na nájezdy proti Vault City.}
{288}{}{Aha. Chci se ještì na nìco zeptat...}
{295}{}{(Pobavenì se podívá na tvou cho.) A jak jste na tom vy? (Opìt se zamraèí.) }
{296}{lbshp25}{To ne... mùj nebotík manel se zajímal jenom o moc. To nenechávalo prostor... pro cokoliv jiného. }
{297}{lbshp26}{To ne... mého manela zajímá jenom moc. To nenechává prostor... pro cokoliv jiného. }
{298}{}{Navíc se má drahá dcera rychle nauèila, co to znamená bıt enou v New Renu.}
{299}{}{Vaše dcera?}
{300}{}{Vaše dcera Angela?}
{301}{}{Chci se ještì zeptat...}
{305}{lbshp27}{Ano, ta Angela, se kterou jste *spal*. Urèitì si na ni vzpomínáte. (Podívá se na tebe kriticky.) *Doufám*, e jste pouili prezervativ. Její hormony jsou tak rozbouøené, e jen pouhá zmínka o spermatu by ji uvedla do jiného stavu.}
{306}{lbshp28}{Ano, má dcera Angela. Stala se z ní malá dìvka. (Posmutnìle se usmìje.) Jaká matka, taková dcera... (Podrádìnì si povzdechne.) Take u je to *všechno?*}
{308}{}{Eh, rez... rezervafit...? Eh, no, myslím, e ano... a u je to cokoliv. Víte co? Radìji se pùjdu pøesvìdèit.}
{309}{}{Eh, kondom? Samozøejmì, e jsme ho pouili. Aspoò myslím. Chci øíct, vím to docela urèitì. Asi si to pùjdu radìji ovìøit.}
{315}{}{'}
{316}{lbshp30}{(Zamraèí se.) Obyèejnı cestovatel. Jak upøímné a dùvìrné. A co bych pro vás mohla udìlat, "obyèejnı cestovateli?"}
{321}{}{Nic, díky. U opravdu musím jít.}
{325}{lbshp31}{Vím, kde je... ale to vám moc nepomùe. U byl jednou pouit.}
{326}{}{Kde je ten GECK?}
{328}{}{V tom pøípadì je mi k nièemu... ale stejnì díky.}
{330}{lbshp32}{(Lehce se usmìje, jako by si vzpomnìla na nìco pøíjemného.) Vy znáte Vault City? Je to na severovıchod od New Rena. Mìli GECK... pøed mnoha lety, ale pouili ho, kdy opustili svùj Vault.}
{331}{}{Mùete mi øíct nìco o Vault City?}
{332}{}{Mùu se vás ještì na nìco zeptat?}
{333}{}{Tak já se tam tedy pùjdu podívat. Díky za informace.}
{335}{lbshp33}{(Její úsmìv se vytratí a zaène se tváøit pøísnì a odmìøenì.) Není o èem mluvit. Myslím, e zjistíte, e je to tam... jiné. U je to všechno?}
{336}{}{Ne, vlastnì by mì ještì zajímalo...}
{337}{}{Ano, je. Omlouvám se za obtìování.}
{340}{lbshp34}{Jak jsem øíkala, na severovıchodì leí Vault City. Na tohle místo se ptáte?}
{341}{lbshp35}{Vím o Vault *City* na severovıchodì. Na tohle místo se ptáte?}
{342}{}{Ne. To není to místo.}
{343}{}{Moná.}
{345}{}{Moná... pùjdu si to ovìøit. Díky.}
{350}{lbshp36}{Hmmmm. V tom pøípadì se obávám, e vám nemùu nijak pomoct.}
{352}{}{Nevíte o nìkom, kdo by mohl?}
{353}{}{No, tak dobøe... stejnì díky.}
{354}{}{No, díky za váš èas, paní Bishopová. Sbohem.}
{360}{lbshp37}{Moná by nebyl špatnı nápad se tam jít podívat.}
{362}{}{Tak dobøe, pùjdu se tam podívat.}
{363}{}{Vıbornì, díky za informace, paní Bishopová. Sbohem.}
{370}{}{Drahı chlapèe... }
{371}{}{Drahé dìvèe... }
{372}{}{lidé v Renu mají u takhle docela problém si pamatovat se kterou kurvou spali minulou noc, nato aby vìdìli, kde najít nìco takového, co popisujete.}
{374}{}{Dobøe... jen se ptám. Tak zatím.}
{375}{}{Dobøe. Díky za váš èas.}
{380}{lbshp40}{Poèkejte chvíli. (Prohlédne si tì.) Zdá se, e jste... ve mìstì novı. Nechcete se ke mnì pøipojit na pár sklenièek v mém pokoji? Mùeme si popovídat o New Renu. Pro neznalé je tohle velmi nebezpeèné místo.}
{381}{lbshp41}{Ještì moment. (Opìt si tì prohlédne.) Nemáte teï èas na ten drink? Nebo zase nìkam spìcháte?}
{382}{}{No, pokud jsou ty drinky jen zaèátek...}
{383}{}{Jistì, nìco k pití by se hodilo.}
{384}{}{Promiòte, paní Bishopová, ale jsem enatı.}
{385}{}{Ne, díky. U opravdu musím jít.}
{386}{}{Ani náhodou. Nechci vašeho manela... rozzlobit.}
{387}{}{Pracuju pro vašeho manela, paní Bishopová. To by nebylo správné.}
{390}{lbshp42}{(Pozdvihne oboèí.) Uvidíme.}
{391}{}{To je pøesnì ta odpovìï, na kterou jsem èekal. Tak pojïme.}
{392}{}{Paní Bishopová, promiòte, ale musím odmítnout... pro tentokrát.}
{393}{}{Promiòte, ale nemùu, paní Bishopová. U opravdu musím jít.}
{394}{}{V ádném pøípadì. Nechci mít s vaším manelem problémy.}
{400}{}{(Usmìje se.) Vy si vìøíte. Jde jenom o drink. }
{401}{}{A i KDYBY se nìco mìlo stát, ujišuji vás, e mùj manel je docela MRTVİ. }
{402}{}{A i KDYBY se nìco mìlo stát, ujišuji vás, e mùj manel NENÍ árlivı typ. }
{404}{}{Paní Bishopová, je mi líto, ale i pøesto musím odmítnout... pro tentokrát.}
{410}{lbshp45}{(Pozdvihne oboèí.) Mùj manel je sice mrtvı, ale jeho mui jsou mi kdykoliv k dispozici. Dokáou se docela... rozzlobit... pokud nìkdo odmítne pozvání paní Bishopové. Jste si *opravdu* jistı, e se ke mnì nepøidáte?}
{411}{lbshp46}{(Pozdvihne oboèí.) Mùj manel není árlivı, ale dokáe se docela... rozzlobit... kdy je vlídné pozvání od nìkoho z Bishopovy rodiny odmítnuto. Jste si *opravdu* jistı, e se ke mnì nepøidáte?}
{412}{}{I tak musím odmítnout.}
{413}{}{Dobøe. Jenom jeden drink.}
{414}{}{Podívejte, u musím jít, paní Bishopová.}
{415}{lbshp47}{(Zamraèí se.) Tak tedy jdìte. Jestli se naše cesty opìt zkøíí, buïte si jistı, e nebudu mít ani nejmenší zájem si s vámi povídat.}
{416}{}{Tak dobøe... sbohem.}
{420}{lbshp48}{(Pøikıvne a usmìje se.) Tak dobøe. Pojïte za mnou.}
{425}{lbshp49}{Tak jdìte, ale zastavte se zase nìkdy. Má nabídka stále trvá.}
{426}{}{Eh... dobøe. Sbohem.}
{430}{lbshp115}{Nemáme si co øíct. Odejdìte, nebo zavolám stráe.}
{435}{lbshp50}{(Paní Bishopová se lehce usmìje, kdy tì uvidí.) Zdravím. Mùu pro vás nìco udìlat?}
{436}{}{Rád bych si s vámi dal ten drink, jestli máte èas, paní Bishopová.}
{437}{}{Rád bych si s vámi dal ještì jeden... drink, jestli máte èas, paní Bishopová.}
{438}{}{Mám nìjaké otázky...}
{439}{}{Momentálnì nic, díky. U musím jít.}
{440}{lbshp51}{No a? Já jsem také vdaná. Co myslíte, e ta moje pozvánka je? Nìjaká pøedehra k cizoloství? No tak, nebuïte hlupák. Pùjdete tedy?}
{441}{}{Tak dobøe. Jeden drink.}
{443}{}{Promiòte, ale nemùu, paní Bishopová. U opravdu musím jít.}
{445}{lbshp52}{Ach ano... je to dobøe promyšlenı pokus mého manela donutit jiné, aby pøijali jeho gesto dobré vùle. Doufala jsem, e ty oldáky upeèou laserové kanóny kolem Vault City.}
{446}{}{"Gesto dobré vùle?"}
{447}{}{Aha. Mám ještì jiné otázky...}
{448}{}{Zajímavé... no, díky za informace. Sbohem.}
{449}{}{Hmmm... zajímavé. Díky za váš èas, paní Bishopová.}
{450}{lbshp53}{Ano. Jeho pùvodní nabídka spojenectví byla odmítnuta, take poté zopakoval své mírumilovné úmysly pouitím násilí, aby si Vault City podrobil... samozøejmì skrz prostøedníky.}
{451}{}{To mi na tom pøijde zvláštní. Proè se lidé ve Vault City radìji neobrátí s pomocí na nìkoho jiného místo toho, aby souhlasili se spojením s Bishopy?}
{452}{}{To mi na tom pøijde zvláštní. Proè se lidé ve Vault City radìji neobrátí s pomocí na nìkoho jiného... napøíklad NCR... místo toho, aby souhlasili se spojenectvím s Bishopem?}
{453}{}{Máte o tom nìjakı dùkaz?}
{460}{lbshp54}{(Zaculí se.) No, *vy* jste mi ale inteligentní...}
{461}{}{Take? Víte, co Bishop naplánoval?}
{462}{}{No, nìkdy ano... ale ne kadı si to myslí. Chci se ještì zeptat...}
{470}{}{(Zamraèí se.) Ne. Mìla bych? (Dùkladnì si tì prohlédne a poté se zaène culit.) }
{471}{}{(Zamraèí se.) Ne. Mìla bych? (Dùkladnì si tì prohlédne a poté se zaène opìt culit.) }
{472}{}{Ptáte se na spoustu nebezpeènıch otázek o manelovì byznysu. Na vašem místì bych byla *velmi* opatrná.}
{473}{}{Eh, díky za radu. Mám ještì nìjaké další, bezpeènìjší, otázky...}
{474}{}{Dám si pozor. Sbohem.}
{475}{}{Díky za váš èas... a vaši radu, paní Bishopová.}
{480}{lbshp116}{*Vzdych*}
{481}{lbshp117}{Další NÁDHERNİ den v Renu.}
{482}{lbshp118}{Podle toho návalu v kasínu bych øekla, e do Rena pøijela další hromada lidského odpadu...}
{483}{lbshp119}{Reno... "nejvìtší malá velká umpa na svìtì." Hmmmph.}
{490}{}{Vidíš spící paní Bishopovou. Spokojenì se ve spánku usmívá.}
{491}{}{Vidíš spící paní Bishopovou. Spokojenì si ve spánku povzdechne a obrátí se na bok.}
{500}{}{Vidíš paní Bishopovou. Špatnì se ti ale soustøeïuje na její vzhled, kdy køièí na stráe.}
{510}{}{Mmmmm... ach, }
{511}{}{Mmmzrrmnmn... ještì, }
{512}{lbshp122}{Kombinace k sejfu... }
{515}{lbshp123}{Vetøelec! Pomoc!}
{516}{lbshp124}{Zlodìj! Zlodìj!}
{517}{lbshp125}{Vetøelec! Stráe! Stráe!}
{520}{lbshp57}{(Zavede tì nahoru do podivné, pøíjemnì vonící místnosti. Jakmile vejdete, zaène ti dávat divné pokyny, které jsou ti nìkdy pøíjemné, nìkdy nepøíjemné.) Nechceš se mì dotknout?}
{521}{}{E-he.}
{522}{}{Ne-e.}
{525}{lbshp58}{Hmmmm. Dobøe. Tak si lehni na postel a já se postarám o zbytek.}
{526}{}{Já odmítat já NECHTÍT já chtít jít DOMÙ do Arroyo.}
{527}{}{[Udìlat, co ti øekne]}
{530}{lbshp59}{(Zhluboka se nadechne a poté zaène jeèet tak hlasitì, a tì z toho bolí uši! Nìco o 'hvídaèích' a 'slodìjech', ale nevíš to jistì, protoe jeèí velmi hlasitì.)}
{531}{}{Pššššst! Jestli nebudeš sticha, tag mì George nenechá hrád s králíèkama! Pšššst!}
{532}{}{Co špatnì s tvoje zuby? Proè ty potøebovat stráe?}
{533}{}{Neøvat! Neøvat!}
{535}{lbshp60}{Ano, vím. Drby se v Renu šíøí rychle. (Povzdechne si.) To je jedno... myslím, e zjistíte, e jsem mnohem zkušenìjší v uspokojování muù ne ona. (Zarazí se.) POUILI jste prezervativ, e ano?}
{536}{}{Pre... rezer... kondom?}
{537}{}{Kondom?}
{538}{}{Jo, mìl jsem ho v inventáøi. Nejdøív jsem nevìdìl, co se s ním stalo, ale pak mi to došlo.}
{539}{}{Eh... asi bych mìl RADÌJI jít, paní Bishopová.}
{540}{lbshp61}{Ano, *kondom.* (Upøenì se na tebe podívá.) No skvìlé. Opravdu skvìlé. (Pokrèí rameny.) No, co u. Tøeba budu mít vnuka. No nic. Teï pøestaò mluvit a pojï ke mnì.}
{541}{lbshp62}{Jo, není to tak jasné, jak by si èlovìk myslel. Vsadím se, e jde o vtípek designerù. (Pokrèí rameny.) No, co u. Teï pøestaò mluvit a pojï ke mnì.}
{542}{}{Øíkala jste zkušenìjší ne Angela? Tak to MUSÍM vidìt.}
{543}{}{U musím jít.}
{545}{lbshp63}{(Pøidal ses k paní Bishopové na drink v jejím pokoji. Chvíli si spolu povídáte a poté se k tobì pøitiskne a zaène se s tebou mazlit.)}
{546}{}{[Jít na to]}
{547}{}{[Obejmout ji]}
{548}{}{Eh, paní Bishopová, spal jsem s vaší dcerou. Moná bychom nemìli...}
{549}{}{Ne se do "toho" dáme, neotevøete svùj sejf jako vaše dce... eh, jak se to obvykle dìlá?}
{550}{}{Podívejte, asi bych mìl radìji jít, paní Bishopová.}
{555}{lbshp64}{Ne. A teï pojïte ke mnì.}
{556}{}{[Jít na to]}
{557}{}{Podívejte, asi bych mìl RADÌJI jít, paní Bishopová.}
{560}{lbshp65}{Ale?! Kam musíte tak najednou odejít?}
{561}{}{Kamkoliv.}
{562}{}{Musím se sejít s Julesem kvùli... speciálnímu obchodu.}
{563}{}{Musím se sejít s jedním pøítelem a nesmím pøijít pozdì.}
{564}{}{Mám své dùvody. Sbohem, paní Bishopová.}
{565}{lbshp66}{Zkuste odejít a já zaènu køièet o pomoc.}
{566}{}{Kdy tak nad tím uvauju, tak mi pøipadají ty stráe bezpeènìjší. Sbohem.}
{567}{}{Musím se sejít s Julesem u vchodu do mìsta kvùli... speciálnímu obchodu... co nejdøív.}
{569}{}{Dobøe, dobøe, ale nemusela jste si hrát na nedostupnou. A teï pojïte ke mnì.}
{570}{}{Chci jen, abyste si uvìdomila, e tohle není správné a mít vìtší morální zásady, tak vám tu teï udìlám pøednášku. A teï pojïte ke mnì.}
{575}{lbshp67}{Stráe! Vetøelec! Zlodìj! Stráe! Vetøelec v domì!}
{576}{}{Kde? O èem to mluvíte, paní Bishopová?}
{577}{}{Kurva! Nesnáším tuhle hru!}
{580}{lbshp68}{Fajn. Kdy se mnou nechcete spát teï, tak chci, abyste si pamatoval, e za mnou mùete kdykoliv pøijít a na nìèem u se domluvíme. Rozumíte?}
{581}{}{Ano. A teï mì nechte odejít.}
{582}{}{Ano, rozumím.}
{585}{lbshp69}{(Oba opustíte místnost a paní Bishopová tì odvede zpìt do druhého patra.)}
{586}{}{Uff.}
{590}{lbshp70}{(Milujete se. Není to nejlepší, není to ani skvìlé, ale alespoò na krátkı okamik ve vašich bouølivıch ivotech zapomenete na krutost svìta a ztratíte se jeden v druhém...) }
{591}{}{(Zaène vášnivé milování. Na konci sexuálního maratónu se k tobì paní Bishopová pøitiskne a spokojenì se usmìje.) Mmmmm, }
{592}{}{Vy jste ale *chlap.* (Zachvìje se.) To s tím jazykem bylo...}
{593}{}{Vy jste ale *enská.* (Zachvìje se.) To s tím jazykem bylo...}
{594}{}{Take... co chcete dìlat teï?}
{595}{}{Mmmmm, Leslie.}
{596}{}{Eh, poslyšte, jenom pro PØÍPAD, e by nìkdo poslouchal kadé naše slovo... nechme si naše tajemství pro sebe. A teï se pojïme oddávat postelovım hrátkám.}
{600}{lbshp74}{(Paní Bishopová spokojenì vzdychne a protáhne se.)}
{601}{}{Povìzte mi o svém manelovi.}
{602}{}{Povìzte mi o své dceøi.}
{603}{}{Povìzte mi o své rodinì.}
{604}{}{Vy nejste z New Rena, e Leslie? Mluvíte jinak ne vìtšina místních lidí.}
{605}{}{Vy jste z Vault City?}
{606}{}{Poslyšte, radìji u pùjdu, paní Bishopová.}
{610}{lbshp75}{(Leslie se lehce zamraèí a pøikryje se prostìradlem.) MUSÍME se o nìm bavit? Nekame si tuhle chvíli.}
{611}{}{Opravdu to chci vìdìt. Povìzte mi o nìm nìco.}
{612}{}{Tak dobøe, co tøeba...}
{615}{lbshp76}{(Zasmìje se.) Koho to zajímá? John je mrtvı. A ije John! Bastard...}
{616}{lbshp77}{Pche! Ujišuji vás, e mezi mnou a Johnem u nic není. Ten malièkı kousek náklonnosti, kterı jsme k sobì cítili, se zmìnil v hoøkost. On má svoje eny a já mám vlastní... potìšení.}
{617}{}{Stejnì se ale musíte mít poøád rádi, alespoò trochu.}
{618}{}{Co má s NCR za kšefty?}
{619}{}{Co má za kšefty s tìmi 'nájezdníky', o kterıch lidé mluví?}
{620}{}{Znáte kombinaci k jeho sejfu?}
{621}{}{Bavme se radìji o nìèem jiném...}
{625}{lbshp78}{(Zamraèí se.) To nechám na vaší pøedstavivosti. Mùeme toho *prosím* nechat? Bavme se o nìèem jiném.}
{630}{}{Mám ho pro vás zabít?}
{635}{lbshp79}{No... *zív*... myslím, e s nimi chce John vycházet v dobrémmm... (Protáhne se.) ...a získat jejich pomoc, aby mohl zlikvidovat ostatní rodiny.}
{636}{}{To je všechno, co chce Bishop od NCR?}
{637}{}{Tak dobøe. Bavme se o nìèem jiném...}
{638}{}{Chci vìdìt ještì nìco o Johnovıch kšeftech...}
{645}{lbshp80}{(Otoèí se na bok.) John poslal nìjaké oldáky na vıchod, poblí Vault City, aby 'navštìvovali' mìsto. Chce na nì trochu zatlaèit, aby poprosili NCR o pomoc.}
{646}{}{Poprosit *NCR* o pomoc? Proè?}
{650}{lbshp81}{Mmmmm... no... víte... (Otoèí se.) John slíbil NCR, e jim dá Vault City. Take poslal pár svıch muù a øekl jim, a se chovají jako nájezdníci, dokud se Vault City nevzdá.}
{651}{}{Víte, kde jsou ti nájezdníci?}
{652}{}{Eh... víte o nìjakém DÙKAZU?}
{655}{lbshp82}{Ne... John má nejspíš nìkde mapu jejich úkrytu. (Popotáhne a utøe si nos.) Mmmmm...}
{657}{}{Bavme se radìji o nìèem jiném...}
{660}{lbshp83}{ myslím... nebo nìco takového...}
{663}{}{Vıbornì... èas rozlousknout sejf... spìte dobøe, paní Bishopová.}
{665}{}{Víte, }
{666}{}{Aha. Díky.}
{670}{}{(Zamraèí se.) Co s ní? }
{671}{}{Jestli mi tu budete vykládat, jak jste spolu smilnili, tak si to nechte pro sebe. A doufám, e jste pouili kondom. }
{672}{}{Ta dìvka se vychrápe s kadım divochem, kterı na ni zamává svım náøadím...}
{673}{}{Eh... no... tak si pojïme povídat o nìèem jiném...}
{675}{lbshp87}{(Pokrèí rameny.) Není o èem mluvit. Je to banda nájemnıch hrdloøezù, oldákù, kurev, feákù a otrokù... (Otoèí se na druhı bok.) ...to je 'rodina' Bishopù. Ké bych si tak nikdy nezaèala s Johnem...}
{677}{}{Hmmmm. Chci se ještì zeptat...}
{680}{}{A co vaše manelství? Hmmmph. }
{681}{lbshp90}{Ne, moje 'manelství' nebylo šastné. Mùj nebotík manel se zajímal jenom o moc. To nenechávalo prostor... pro cokoliv jiného. }
{682}{lbshp91}{Ne, moje 'manelství' není šastné. Mého manela zajímá jenom moc. To nenechává prostor... pro cokoliv jiného. }
{683}{}{Vypadáte nešastnì. Mìla byste odejít, zaèít novı ivot nìkde jinde.}
{684}{}{Hmmm. Chci se ještì zeptat...}
{690}{lbshp92}{No to je ale SKVÌLİ nápad! A kam bych asi tak mìla jít? Do pouštì ít mezi divochy? Na jih do NCR? Na severozápad do Reddingu prodávat své tìlo horníkùm?}
{691}{}{Proè je pro vás tak nepøedstavitelné opustit Reno? Vdy nejste hloupá. Myslím, e byste se dokázala vypracovat v èemkoliv byste chtìla.}
{692}{}{Zapomeòte na to. Poslyšte, chci se ještì zeptat...}
{700}{lbshp93}{Kdy odejdu, tak mì manel pøivede zpátky. Rodina na sebe dohlíí, a u chtìjí nebo ne.}
{701}{lbshp94}{Hmmm. Moná bych mìla odejít... teï, kdy mìl John tu svoji zaslouenou nehodu. (Posmutnì se usmìje.) Moná to udìlám. Reno u mì... unavuje. (Zamyslí se.) Nebo moná potøebuje nového vùdce...}
{702}{}{Poslyšte, chci se ještì zeptat...}
{705}{lbshp95}{Ne. (Otoèí se a nìco v polospánku zamumlá.) Nebuïte idiot. Jakmile by se to lidé dozvìdìli, budete do konce vašeho krátkého ivota jen utíkat.}
{706}{}{Co kdy nikdo nepøijde na to, kdo to udìlal?}
{710}{lbshp96}{(Promne si oèi a mrkne.) O èem to MLUVÍTE? Nemluvte nesmysly.}
{711}{}{Co kdy ho zabije nìjaká past? Nebo se mu stane nìjaká nehoda?}
{712}{}{Tak dobøe. Poslyšte, chci se ještì zeptat...}
{715}{lbshp97}{(Vykulí oèi.) Jeho sejf... má nastraenou vıbušninu, kdyby se do nìj chtìl nìkdo dostat. Dá se bezpeènì otevøít jen tehdy, pokud se zadá pøesná kombinace. Ale kdyby se ta kombinace zmìnila... bez jeho vìdomí...}
{716}{}{Hmmmm. Moná kdy "opravím" zámek na jeho sejfu... musím si to zapamatovat. Poslyšte, chci se ještì zeptat...}
{720}{lbshp98}{Ano, *mluvím* jinak ne vìtšina místních lidí. Øíká se tomu 'vzdìlání.' (Otoèí se na bok.) Pojïte spát.}
{721}{}{Kde se dá získat takové vzdìlání?}
{725}{lbshp99}{*Zív*... vy u jste inteligentní dost... teï pojïte spát. Nepumpujte ze mì informace jako z nìjakého poèítaèe.}
{726}{}{To ne, to nechci.}
{730}{lbshp100}{(Pootevøe jedno oko.) Kdo vám to øekl?}
{731}{}{Tipnul jsem si to, kdy jsem vás slyšel mluvit o Vault City. Mìla jste takovı nostalgickı vıraz v oblièeji.}
{735}{lbshp101}{(Zaène se tváøit vánì a poté se otoèí, take ji nevidíš do tváøe.) Ani mi to místo nepøipomínejte.}
{736}{}{Co se stalo?}
{740}{lbshp102}{JOHN se stal. Kdysi jsem tam ila. Jednoho dne pøijel a úplnì mì okouzlil, protoe byl tak... drsnı, øekla bych. Úplnì jinı ne vìtšina Obèanù. Pochopitelnì mi dal okusit nìjaké drogy a... (Povzdechne si.)}
{741}{}{A?}
{745}{lbshp103}{Mìli pamìové moduly pro Pip-Boye, které obsahovaly slovníky a encyklopedie. Jeden z jazykovıch modulù jsem si vzala, kdy jsem odcházela, i kdy ani nevím proè.}
{746}{}{Kde je ten modul?}
{750}{lbshp104}{*Zív*... (Schoulí se do klubíèka.) Je v mém sejfu. Bez Pip-Boye je ale k nièemu. Ani nevím, proè ho ještì mám.}
{751}{}{Mùu si ho vzít?}
{752}{}{Hmmmnn. Chci se ještì zeptat...}
{760}{lbshp105}{(Pokrèí rameny.) Jistì, jestli ho chcete. Kombinace je }
{761}{}{Jak se to pouívá?}
{762}{}{Díky. Poslyšte, chci se ještì zeptat...}
{770}{lbshp106}{(Leslie se pøevrátí na bok a zavøe oèi. Bìhem nìkolika vteøin usne.)}
{771}{}{[Tiše vylézt z postele a obléknout se]}
{780}{lbshp107}{Jediná 'láska' mezi námi dvìma je, kdy vleze do mé lonice a nalehne na mì jako oralá brahmína. A to je moná jeho nejménì opovreníhodná vlastnost, kdy se zamyslím nad tím, èím se zabıvá.}
{781}{}{Èím se zabıvá?}
{790}{lbshp108}{Nejspíš chce bıt také souèastí obchodu s drogami v New California Republic. Chce zmanipulovat volby tam dole na jihuuu... *zív*}
{791}{}{Take on vlastnì chce, aby se Reno PØIDALO k Republice... hmmmm. Dobøe, bavme se o nìèem jiném...}
{792}{}{Zajímavé. Zajímaly by mì i ostatní Johnovy kšefty...}
{800}{lbshp109}{Drogy jsou ve Vault City pochopitelnì nelegální. Ostatní Obèané na to pøišli a zrušili mé Obèanství. John byl jedinı, na koho jsem se mohla obrátit... a on to samozøejmì vìdìl. Celé si to naplánoval.}
{801}{}{Take jste získala vzdìlání ve Vault City? A proto mluvíte jinak ne ostatní lidé v Renu?}
{810}{lbshp110}{Staèí si na hlavu nasadit helmu, dát si optickı senzor pøed pravé oko a poté pøipojit druhı konec... hmpphh... (Otoèí se.) ...k Pip-Boyi. Ucítíte drobnı tlak v hlavì, trochu se vám zvedne aludek a poté se vám hlava... proèistí.}
{815}{}{Mmmmmnnn...? Nevím. Moná je nìco v sejfu v jeho pokoji... má tam dùleité záznamy, kdyby chtìl nìkoho vydírat.}
{820}{lbshp112}{(Tvoje otázka se nedoèkala odpovìdi... Leslie Bishopová usnula. Má širokı úsmìv na tváøi, pevnì svírá polštáø a mumlá si tvoje jméno.)}
{821}{lbshp113}{(Tvoje otázka se nedoèkala odpovìdi... Leslie Bishopová usnula. Nemùeš si pomoct, ale napadá tì, jestli by nezùstala vzhùru déle, kdybys byl trochu... zkušenìjší, ale na tuhle myšlenku rychle zapomeneš, protoe zraòuje tvoje ego.)}
{822}{}{[Potichu vyklouznout z postele]}
{825}{lbshp114}{(Po pár minutách tvého milování paní Bishopová náhle usne. Zaène tiše chrápat.)}
{826}{}{[Obléknout se a poté odejít]}
{900}{}{Podaøilo se ti pøesvìdèit paní Bishopovou, e mùe zmìnit svùj ivot... k lepšímu.}
{1253}{}{.}
{1315}{}{...' Take... '}
{1510}{}{, mmm-mmmm... mmmzmzrrm}
{1511}{}{...oooch... }
{1512}{}{...mmm...}
{1591}{}{. }
{1665}{}{...(Paní Bishopová... Leslie... se otoèí a opøe se loktama o postel.) V jeho sejfu je nastraená vıbušnina, take buïte opatrnı, ano? Bez prstù jste mi k nièemu. (Usmìje se a pøevrátí se zpátky.)}
{1760}{}{. Modul je ve skryté schránce na dnì... zlodìj by ho nenašel, pokud by nevìdìl, kde hledat.}
{2315}{}{' ...co pro vás mùu udìlat?}
{2511}{}{...mmm}
