{100}{}{Vidíš zahalenou postavu.}
{101}{}{Vidíš uèence Gorise.}
{102}{}{Vidíš humanoida v hávu s dlouhımi rukávy a kapucí. Na jeho postoji je nìco zvláštního, ale nevíš pøesnì co.}
{103}{goris1}{Ahoj, já jsem Goris. Tebe neznám, jsi tu novı?}
{104}{}{Já}
{105}{}{Já jít.}
{106}{}{Jo, a co jako?}
{107}{}{Ahoj. Já jsem}
{108}{}{Ahoj, Gorisi. Gruthar øíkal, e tì mám vyhledat. Myslí si, e toho hodnì víš.}
{109}{}{Mùu se tì na nìco zeptat?}
{110}{}{Promiò, musím jít.}
{111}{}{Rád tì potkávám,}
{112}{}{Take znáš Gruthara. Má o mnì trochu zkreslenou pøedstavu. Ve skuteènosti nevím ani polovinu z toho, co si myslí, e vím. Kadopádnì...}
{113}{goris4}{Take ty pocházíš zvenèí! U jsem vidìl nìkolik takovıch jako ty. Nìkteøí jsou tady ve Vaultu, ale ty vypadáš jinak. Jsi trochu víc 'vyzrálejší', jestli mi rozumíš. Vsadím se, e u máš nìco procestováno. Nemám pravdu?}
{114}{}{Eh... 'vyzrálejší'?}
{115}{}{Já jít.}
{116}{}{Promiò, ale musím odejít.}
{117}{}{Ano, mám za sebou pár dobrodruství. Pokud by ti nevadilo odpovìdìt na pár otázek, mùu ti na oplátku o nìkterıch povyprávìt.}
{118}{}{Do toho ti nic není.}
{119}{}{Nebude ti vadit, kdy se na nìco zeptám?}
{120}{}{Platí! Rád si poslechnu vše, co mi øekneš.}
{121}{}{A navíc, nemùu pøeci odmítnout Grutharova pøítele.}
{122}{goris7}{Co potøebujete vìdìt?}
{123}{}{Co tu dìláš?}
{124}{}{Jsi tu vìzeò?}
{125}{}{Jak dlouho tady jsi?}
{126}{}{Co mi mùeš øíct o místních páraèích?}
{127}{}{Nevíš, co se stalo s lidmi, kteøí v tomhle vaultu ili?}
{128}{}{Co mi mùeš øíct o Grutharovi?}
{129}{}{Myslíš, e jsou páraèi hrozbou pro lidi?}
{130}{}{Máš nìjaké další informace o té Enklávì, o které jsi mluvil?}
{131}{}{Co víš o tom viru?}
{132}{}{Zmínil ses, e bys rád cestoval. Co kdyby ses ke mnì pøidal?}
{133}{}{Promiò, ale musím jít.}
{134}{goris8}{Hmm... pøekvapuje mì, e ti o mnì Gruthar neøekl. Ale budi. }
{135}{goris9}{Jsem nìco jako student. Snaím se dozvìdìt co nejvíce o svìtì a rùznıch kulturách, které se zde vyvinuly. Právì teï studuji spoleènost, kterou zde vytváøejí páraèi a srovnávám ji s tou lidskou na základì spoleènıch rysù. U jsem zde získal takøka veškeré informace, které jsem potøeboval. Velice by mi pomohlo, kdybych teï mohl trochu cestovat, nicménì nechci cestovat sám, jestli mi rozumíš.}
{136}{}{Zajímavé. Mùu se ještì na nìco zeptat?}
{137}{}{Take ty jsi uèenec. To je docela rarita v dnešní dobì.}
{138}{}{To musí bıt nuda. Ale budi... je jen na tobì, jak svùj ivot promarníš. Kadopádnì potøebuju ještì nìjaké informace.}
{139}{goris10}{Ne, mùu odejít kdykoliv se mi zachce. Neodešel jsem, protoe nechci cestovat sám. Jsem celkem houevnatı a dokáu se o sebe postarat, ale kdyby se nìco pøihodilo, poøád budu jen jedna osoba v poušti.}
{140}{}{Aha.}
{141}{}{Aha, trochu srábek na to, abys chodil sám. Je mi to jasné.}
{142}{}{Taky nesnáším cestování o samotì, take tì chápu.}
{143}{goris11}{Eh... asi nìkolik mìsícù. Pøišel jsem sem od pobøeí u pøed nìjakım èasem.}
{144}{}{Hmm, taky tu nejsi moc dlouho. Pokud ti to nevadí, chci vìdìt víc.}
{145}{}{Moc jsi mi toho neøekl. Nechceš mi toho povìdìt víc?}
{146}{}{Aha. Chci se ještì na nìco zeptat.}
{147}{goris12}{Tohle nejsou bìní páraèi, jak jistì víš. Mají zvıšenou inteligenci zpùsobem, kterému sami nerozumí. Má to na svìdomí skupina lidí známıch jako 'Enkláva.' Zdá se, e tato Enkláva potøebovala armádu a tak si vybrali páraèe kvùli jejich dravosti, fyzické síle a... no, však víš. Nicménì postrádali inteligenci. Potøebovali je dostateènì chytré na to, aby pochopili sloité rozkazy, ale ne natolik chytré, aby ohrozili 'ty u vesla.'}
{148}{}{To zní jako ta nejvìtší kravina, kterou jsem kdy ve svém ivotì slyšel!}
{149}{}{To je úasné. Jsi nejspíš velmi vzdìlanı. Mùu se ještì na nìco zeptat?}
{150}{}{Hmm... dobøe.}
{151}{goris13}{::vzdech:: Byli zajati Enklávou. Gruthar a jeho smeèka byli donuceni pomáhat pøi jejich zajetí. Nemìli na vybranou, protoe tou dobou byli zotroèeni. Od té doby tíí osud tìchto lidí Grutharovo svìdomí. Nikdy si neodpustil, e se úèastnil této události. Lidé byli zajati iví, ale kdo ví, co se s nimi od té doby stalo?}
{152}{}{(Vzdech) Byli zajati skupinou zvanou 'Enkláva.' Gruthar a jeho smeèka byli donucení pomáhat pøi jejich
 zajetí. Nemìli na vybranou, protoe tou dobou byli zotroèeni. Od té doby tíí osud tìchto lidí
 Grutharovo svìdomí. Nikdy si neodpustil, e se na tom podílel.
 Lidé byli zajati iví, ale kdo ví co se jim pak stalo.}
{153}{}{Hmm... chci se ještì na nìco zeptat.}
{154}{}{Take ti zatracení páraèi jsou za to pøeci jen zodpovìdní! Potøebuju další informace.}
{155}{}{Nìkdy se situace vymkne z rukou a my jsme nuceni dìlat nepøíjemné vìci. Gruthar by se mìl nauèit odpustit sám sobì.}
{156}{goris15}{Gruthar není zrùda, jak by se mohlo zdát. Svìdomitì se tu o nás všechny stará a dìlá pro naši bezpeènost a pøeití vše, co mùe. Všichni mu dùvìøujeme. Nevím, co víc o nìm øíct. Bude lepší, kdy ho nejprve poznáš a poté posoudíš podle svého.}
{157}{}{Nebudu o nìm dìlat ádné ukvapené závìry. Zaslouí si víc.}
{158}{}{Jistì. Promluvme si o nìèem jiném.}
{159}{}{Vdy je to páraè. Nechce se mi vìøit, e by mohl mít i nìjaké pøednosti.}
{160}{goris16}{No... potenciál by tu byl, obzvláš kdy vezmeš v potaz jejich novou inteligenci. Kadopádnì si nemyslím, e Gruthar a jeho smeèka pøedstavují hrozbu. Zdá se, e všichni respektují ivot a osobní svobodu pøed èímkoliv jinım. Neoèekávám, e mi teï budeš vìøit. Budu rád, kdy to posoudíš podle svého. Jsou tu i jiní, kterıch se mùeš na nìco zeptat.}
{161}{}{Jenom blbec by nedokázal v páraèích rozpoznat potenciální hrozbu!}
{162}{}{Díky za radu, poptám se kolem. Mùu se tì ještì na nìco zeptat?}
{163}{}{Hmm... dobøe, co takhle pár dalších otázek?}
{164}{goris17}{Ne, všechno u jsem ti øekl. I kdy poèkej, ještì jedna vìc. Enkláva projevovala jistı zájem o ruiny na západ odsud. Nevím proè. Víc nevím.}
{165}{}{No, kadı kousek informace se hodí a já ti za to dìkuju.}
{166}{}{Taková dùleitá vìc a ty to na mì vybalíš a teï!}
{167}{}{Aha.}
{168}{goris18}{Myslím, e se jmenuje FEV. Enkláva ho usilovnì zkoumá nebo alespoò zkoumala. Je mi líto, ale nic víc nevím.}
{169}{}{To je v poøádku, jdeme dál.}
{170}{}{To bys mìl. Øekli mi, e jsi studna vìdomostí!}
{171}{}{Moc jsi mi pomohl, Gorisi.}
{172}{goris19}{Dodrel jsem svou èást dohody a odpovìdìl na všechny tvé otázky. A co teï nìjaké ty slíbené dobrodruné historky?}
{173}{}{Bude mi potìšením. Dobøe se mi s tebou povídá.}
{174}{}{Slib? Jakı slib?}
{175}{}{Jo, jistì.}
{176}{goris20}{(Goris váhá a ty máš pocit, jako by si tì podrobnì prohlíel.) Bude mi ctí tì doprovázet!}
{177}{goris21}{(Goris váhá a ty máš pocit, jako by si tì podrobnì prohlíel.) Promiò, ale myslím, e nesdílíme stejné názory. Spoleèné cestování pro nás nebude to nejlepší.}
{178}{}{Dobøe, tvoje mínus.}
{179}{}{Chápu. Moná èasem zmìníš názor.}
{180}{}{Co? Nejsem pro tebe dost dobrı? Jdi se vycpat!}
{181}{}{Dobøe, chápu.}
{182}{goris46}{Nemám ti co øíct. U mì neotravuj.}
{183}{goris47}{ádal jsem tì, a mì u neotravuješ. Moná porozumíš troše násilí.}
{184}{}{}
{185}{goris22}{Jo, však víš, zcestovalı... vzdìlanı... zkušenı... nemáš ani ponìtí, o èem mluvím, e? }
{186}{}{Èert ví.}
{187}{}{Já teï jít.}
{188}{goris23}{E-he. No, tvoje IQ bude asi menší ne èíslo tvıch bot, ale oèividnì ti osud pøeje, kdy u se ti podaøilo v tomto svìtì pøeít tak dlouho... dobøe, zkusíme to jinak. Já chtít odejít odsud. Já chtít jít s ty. Dobøe?}
{189}{goris24}{E-he. No, tvoje IQ bude asi menší ne èíslo tvıch bot, ale oèividnì ti osud pøeje, kdy u se ti podaøilo v tomto svìtì pøeít tak dlouho... to musí bıt tím zlem, které z tebe cítím. No nic. Nashledanou.}
{190}{}{Eh... dobøe.}
{191}{}{Já jít.}
{192}{goris25}{Promiò, nechtìl jsem se vrtat v tvıch soukromıch záleitostech.}
{193}{}{Jo, no, u to nedìlej!}
{194}{}{To je jedno. Potøebuju ještì nìjaké informace.}
{195}{}{Promiò, Gorisi. U mì dnes chytá rapl. Chci se tì ještì zeptat na pár vìcí, pokud to nevadí.}
{196}{goris53}{To musely bıt zajímavé èasy. Jsi ze stejného tìsta, z jakého bıvají hrdinové a to ti závidím. Díky za rozhovor.}
{197}{goris54}{No... jsi chodící šílenec, take nejspíš pùjdu. Díky a nashle!}
{198}{}{Není zaè, Gorisi.}
{199}{goris26}{Ahoj. Jak to jde?}
{200}{}{Ty jít s já?}
{201}{}{Eh... já ztracen. Já jít.}
{202}{}{Jen mì tak napadlo se tu zastavit a pozdravit tì. Zatím.}
{203}{}{Poslyš, hledám spoleèníka na cesty. Jdeš do toho?}
{204}{}{Co pro tebe mùu udìlat,}
{205}{}{Ty zlá vìc! Proè ty neøíct?}
{206}{}{Ty jsi páraè? Je nìjakı dùvod, proè jsi mi to neøekl?}
{207}{goris27}{Jak to jen øíct... špatná vìc ty zabíjet, já nemluvit. Já neøíct, aby ty myslet, e já dobrá vìc. Nezabít mì. V pohodì kdy já zùstat s tebou?}
{208}{goris28}{Promiò, e jsem tì oklamal, ale vy lidé máte ve zvyku støílet páraèe na potkání. Domníval jsem se, e pro mì bude lepší, kdy skryju svoji identitu, dokud sám nepøijdeš na to, e jsem na tvé stranì. Jestli chceš, abych odešel, odejdu. Ale radìji bych zùstal a pomohl ti s tvım úkolem. Chci dokázat, e lidé a páraèi dokáí spolupracovat jako pøátelé, ne bıt nepøátelé.}
{209}{}{Já nelíbit, ty jít.}
{210}{}{Dobøe, ty zùstat.}
{211}{}{Promiò, ale nemám rád, kdy mì nìkdo tahá za fusekli. Mìl bys odejít.}
{212}{}{Chápu, proè ti pøipadalo nezbytné skrıvat svoji identitu. Myslím, e mùeme spolupracovat, take prosím zùstaò, ale u mì nebalamu, Gorisi.}
{213}{}{. Já tady novı.}
{214}{}{. Ano, nepocházím z vaultu.}
{215}{}{.}
{216}{}{?}
{217}{goris29}{Enkláva si zaèala pohrávat s nìjakım virem nebo nìèím takovım a vstøíkla ho páraèùm do krve. Tento vir byl známı tím, e dokáe zmutovat lidi v jakési superbytosti, take byli zvìdaví, co to s nimi udìlá. No a vısledkem bylo vyšlechtìní páraèù natolik chytrıch, e si uvìdomovali své pøedurèení k otroctví. A tak si hráli na hlupáky do té doby, ne mohli získat svobodu. A povedlo se!}
{218}{}{Jsem proti ubliování páraèùm.}
{219}{goris30}{Najednou mám pocit, e je moje smeèka v nebezpeèí. Je mi líto, e tì musím opustit, ale musím zkontrolovat své bratry.}
{220}{}{Dobøe.}
{221}{goris48}{Bezpeènostní kamery zachytily, co se stalo. Bude lepší, kdy se na to podíváš.}
{222}{}{Vidíš šedého páraèe. Je to Goris.}
{223}{}{Vidíš humanoida v hávu s dlouhımi rukávy a kapucí. Je to Goris.}
{1000}{}{Ano,}
{1001}{}{Ty léèit sebe.}
{1002}{}{Ty èekat tady. Já vrátit se.}
{1003}{}{Eh... teï ádná zbraò. Dobøe?}
{1008}{}{Ty páraè? Proè ty nic neøíct?}
{1009}{}{Já hotov.}
{1010}{}{Mìl by ses teï vyléèit.}
{1011}{}{Potøebuju, abys tu poèkal, ne se vrátím.}
{1012}{}{Schovej tu zbraò, ano?}
{1016}{}{Pojïme.}
{1017}{}{Ty jsi páraè? Je nìjakı dùvod, proè jsi mi to neøekl døív?}
{1018}{}{To bude prozatím všechno.}
{1019}{}{Jsem vyléèenı a pøipravenı vyrazit,}
{1020}{}{U jsem témìø úplnì vyléèenı,}
{1021}{}{Jsem témìø vyléèenı, ale budu ještì potøebovat další léky,}
{1022}{}{Vyléèil jsem se, jak to jen šlo, ale poøád jsem dost zranìnı,}
{1041}{}{Poèkám tu na tebe, dokud se nevrátíš,}
{1060}{}{Dìlám, co umím, abych nevypadal podezøele,}
{1064}{}{Ty zùstat blízko.}
{1065}{}{Ty nebıt daleko.}
{1066}{}{Ty moc blízko. Jít dál.}
{1073}{}{Dr se blízko mì.}
{1074}{}{Moc se nevzdaluj.}
{1075}{}{Mìli bychom se trochu rozestoupit.}
{1078}{}{To bude prozatím všechno.}
{1079}{}{Budu se dret tak blízko, jak to jen jde,}
{1098}{}{Trochu se vzdálím a nechám ti prostor,}
{1117}{}{Budu se dret vzadu a dám ti víc prostoru,}
{1136}{}{Promiò,}
{1137}{}{Na našich spoleènıch cestách jsem se toho hodnì nauèil. Pùjdu s tebou rád,}
{1156}{}{? }
{1157}{}{. }
{1158}{}{, máš s sebou pøíliš mnoho lidí. Poèkám tu, dokud se nìjaké místo neuvolní.}
{1159}{goris44}{Myslím, e mi to samotnému pùjde lépe.}
{1160}{goris49}{Nepatøíš k tìm, se kterımi bych se chtìl pøátelit, odcházím.}
{1161}{goris45}{Pøeji si pomstít svùj druh.}
{1162}{}{Tak dobøe. Pojïme na to.}
{1163}{}{Moná bys to mìl udìlat sám.}
{1164}{}{Ty mít pravda, my zabít.}
{1165}{}{Ty jít sám.}
{1166}{}{Mìli bychom zmìnit vzdálenost mezi sebou.}
{1167}{}{Já myslet ty pohnout jinak.}
{2000}{goris50}{Myslím, e jsem si nìco zlomil. Potøebuji lékaøskou péèi.}
{2001}{goris51}{Myslím, e mám nemoc z ozáøení. Mùeš mì nìjak vyléèit?}
{2002}{goris52}{Myslím, e jsem otrávenı. Mùeš mì nìjak vyléèit?}
