{100}{}{Vidíš velikého páraèe. Má mohutné vypracované svaly, ostré zuby a paøáty.}
{101}{}{Vidíš Gruthara, vùdce páraèù.}
{102}{}{Vidíš toho nejimpozantnìjšího páraèe, jakého si dokáeš pøedstavit. Musí bıt unikátní svého druhu.}
{103}{gruth3}{Neboj se mì, èlovìèe, nechci ti ublíit. Jsem Gruthar, vùdce této smeèky páraèù. Proè jsi tady?}
{104}{gruth4}{Proè jsi tady?}
{105}{}{Eh...}
{106}{}{Abych ti nakopal prdel!}
{107}{}{Jak je moné, e umí páraè mluvit... a tak dobøe?}
{108}{}{Chci vìdìt, co se stalo s lidmi, kteøí tu pøedtím ili.}
{109}{}{Hledám vìc zvanou GECK. Øekli mi, e tu jeden najdu.}
{110}{}{Poádali mì o vyèištìní doupìte nebezpeènıch páraèù...}
{111}{}{Vyšetøuju nájezdy na místní brahmíní farmy. Nevíš o tom nìco?}
{112}{}{Myslím, e radìji pùjdu.}
{113}{gruth5}{Nejsi ádnı idiot, èlovìèe. Vidím ti to na oèích. Nezkoušej mì prosím oklamat. Nemám trpìlivost na takové hry.}
{114}{gruth6}{Tak dobøe. Pokud chceš bıt za idiota, máš to mít. A si to rozmyslíš, vra se zpìt.}
{115}{gruth7}{Omlouvám se. Jsem na tebe asi trochu moc chytrı. Nepøedstavuješ pro mì a mou smeèku ádnou hrozbu. Vítej a povauj toto místo za bezpeènı úkryt pøed okolním svìtem. Nikomu neubliuj, nedìlej problémy a vdy tì tu rádi uvítáme.}
{116}{gruth8}{Odpus. Nechci bıt nezdvoøilı, ale nechápu, jakou to má souvislost s naší konverzací. Umím mluvit tvım jazykem a èíst tvé písmo. Co víc chceš slyšet?}
{117}{}{Aha.}
{118}{}{Nechci nìjak vyzvídat, ale jistì chápeš mùj zájem.}
{119}{}{Jooo, a co kdybys nechal posoudit mì, co má a co nemá souvislost?}
{120}{gruth9}{Ano, to zajisté chápu. Tak dobrá. Pokud se rozlouèíme v dobrém, èlovìèe, zajdi si promluvit s Gorisem. Má v této záleitosti více porozumìní ne já. Bude nejspíše v knihovnì vaultu.}
{121}{}{Díky. Tìším se na setkání s Gorisem.}
{122}{}{Nemám v úmyslu pøidávat páraèe na seznam svıch pøátel. Nashle!}
{123}{}{Tak dobøe.}
{124}{gruth10}{Jsou pryè, èlovìèe. Nezabili jsme je, ani jim nesebrali jejich domov. Nemáme ve zvyku zabíjet. Pochopím, kdy mi nebudeš vìøit, ale zároveò doufám, e mì budeš posuzovat na základì mıch èinù vùèi tobì a ne ze strachu nebo pøedsudkù.}
{125}{}{Nejspíš ti koneènì došlo, e ti mùu klidnì nakopat prdel.}
{126}{}{Pøipadáš mi jako poèestná bytost, Gruthare.}
{127}{}{Jo, asi jo.}
{128}{gruth11}{GECK. Není to ta malá ještìrka... ne, poèkat... to je geckon. Promiò, ale nevím, co je to GECK ani kde se dá najít.}
{129}{gruth12}{Ano, myslím, e u jsem to od tebe jednou slyšel. Nevím, co je to GECK ani kde se dá najít.}
{130}{}{Mùu se tu po nìm podívat?}
{131}{}{Hele, to s tou ještìrkou bylo opravdu vtipné. To je nìjakı tvùj pøíbuznı?}
{132}{}{Mluvit s tebou je oèividnì ztráta èasu. Sbohem.}
{133}{}{Popravdì ani já pøesnì nevím, co to je. Nebude ti vadit, kdy se tu po nìm podívám?}
{134}{gruth13}{Je mi líto, ale nenechám tu jen tak nìkoho procházet. Jsem zodpovìdnı za bezpeèí všech, kteøí zde ijí, take musím bıt obezøetnı. Ale podívám se ti po tom gecku a dám ti vìdìt, pokud ho najdu.}
{135}{gruth14}{Je mi líto, ale nenechám tu jen tak nìkoho procházet. Jsem zodpovìdnı za bezpeèí všech, kteøí zde ijí, take musím bıt obezøetnı.}
{136}{}{Podívej, nepatøí ti to tady. Moná se tu porozhlédnu kolem bez ohledu na to, jestli se ti to líbí nebo ne!}
{137}{}{Chápu, Gruthare, a budu respektovat tvoje pøání.}
{138}{}{Chápu tvoje obavy. Neznáš mì natolik, abys mi vìøil. Co kdy ti ale s nìèím pomùu a ty mì tu pak na oplátku necháš porozhlédnout?}
{139}{gruth15}{(Gruthar na tebe chvíli upøenì zírá.) Ty nám chceš pomoct? Souhlasím, cítím v tobì jen drobné zlo. Tak dobrá, budu ti dùvìøovat.}
{140}{gruth16}{(Gruthar na tebe chvíli upøenì zírá.) Myslím, e ne. Cítím v tobì ïábla, èlovìèe. Nemùu riskovat ivoty ostatních, pokud bych ti dal šanci.}
{141}{}{Díky.}
{142}{}{Fajn. Myslím, e kulka mezi oèi vyøeší celı mùj problém.}
{143}{}{Je mi líto, e to bereš takhle, Gruthare.}
{144}{}{V tom pøípadì odcházím.}
{145}{gruth17}{Je tu mnoho strojù, strojù postavenıch lidmi. Ruce páraèù je nemohou pouívat. Avšak je tu jeden stroj, kterı rozumí otázkám. Poádám jej, aby øídil ostatní stroje a on poslechne. Bohuel ji tento stroj neposlouchá, take nemùe øídit ostatní stroje. Dochází nám jídlo a voda, take jsem rozkázal nájezdy na lidské usedlosti, abychom vùbec pøeili. Nejsem na to hrdı a rád bych s tím pøestal. Pokud ten stroj opravíš, budu opìt schopen nakrmit svoji smeèku a rád zastavím ty nájezdy. Souhlasíš s tím?}
{146}{}{Promiò, ale nemám ponìtí jak takovı stroj opravit.}
{147}{}{Nejsem ádnı technik, ale mùu to zkusit.}
{148}{}{Hmm... zdá se, e odešel modul pro rozpoznávání hlasu. Pùjdu se na to podívat.}
{149}{}{Myslím, e ne, ale nechám si to ještì projít hlavou.}
{150}{}{Udìlám, co budu moct.}
{151}{}{Odmítám pomoct páraèùm.}
{152}{gruth18}{Dìkuji ti. Stroj je v øídícím centru vaultu ve tøetím patøe. Pokud to pùjde opravit, udìlej to prosím. Máš moji dùvìru, take ji nezkoušej zneuít. Vítej.}
{153}{}{Nezklamu tì, Gruthare. Máš moje slovo.}
{154}{}{Díky. Pustím se do toho.}
{155}{}{Vdycky se nìjakej blbec najde...}
{156}{gruth19}{Aha... no, páraèi jsou od pøírody nebezpeèní a èlovìk musí bıt velmi opatrnı, kdy je potká v pustinì. Avšak jak jistì vidíš, my jsme vıjimka. Moje smeèka není pro tebe ani pro lidské komunity ádnou hrozbou. Vyvinuli jsme se nad naše pøíbuzné a pøejeme si ít v poklidu.}
{157}{}{Hmm... jo tak.}
{158}{}{Gruthare, vaše zvıšená inteligence z vás dìlá ještì vìtší hrozbu, ne jakou pøedstavuje obyèejnı páraè.}
{159}{}{Vidím, e nejste brutální zabijáci, jak se o páraèích øíká.}
{160}{gruth20}{Strávil jsem mnoho probdìlıch nocí v hlubokém zamyšlení, uvaujíc o takovıch vìcech. Nakonec jsem došel k závìru, e s darem inteligence je spojené nespoèetné mnoství bøemen a povinností. Kadá myslící bytost má pouze dvì monosti. Buï pøijme ivot takovı, jakı je, a naplno vyuije tohoto daru pro sebe a své okolí, nebo jednoduše pøestane existovat. Vybral jsem si pøijmout vızvy ivota. Pokud to ze mì èiní hrozbu pro lidstvo, pak lituji všechny omezené jedince, kteøí si to myslí...}
{161}{}{Pravda, no... moná, e jsem omezenı jedinec, ale mám VELIKİ kvér.}
{162}{}{Nemùu ne souhlasit. Nemyslím, e jste hrozbou, Gruthare.}
{163}{}{Eh... jo. Je to pøesnì tak, jak øíkáš.}
{164}{gruth21}{(Gruthar se zarazí a vypadá, jako by pøemıšlel o své odpovìdi.) Je mi líto, e jsem naøídil ty nájezdy na lidské usedlosti. Zodpovídám tu za mnoho ivotù. Dochází nám jídlo, voda a další zásoby. Dokud se situace nezlepší, musím si já, páraè, brát od lidí vše, oè je nemùu ádat.}
{165}{}{Take teï, kdy znám pùvod nájezdù, tak ho prostì zlikviduju!}
{166}{}{To je mi líto. Je tu nìjakı zpùsob, jak vám mùu pomoct, abyste pøestali s tìmi nájezdy?}
{167}{}{U toho vím dost. Potøebuju si to promyslet.}
{168}{}{Chápu...}
{169}{gruth22}{Tvoje rozhodnutí se mi nelíbí, ale pøijímám ho. Mùeš odejít, ale pokud si to rozmyslíš, vra se prosím.}
{170}{}{Beru.}
{171}{}{Ahoj}
{172}{}{Ne, ale pustím se do toho.}
{173}{}{Je mi líto, Gruthare. Odešel hlasovı modul. Budu muset najít jinı.}
{174}{}{Nerozumím takovım vìcem, ale vìøím ti,}
{175}{}{Beru.}
{176}{}{Vrátím se, máš moje slovo.}
{177}{}{Ahoj}
{178}{}{Bohuel zatím ne. Ale opravdu se snaím.}
{179}{}{Ano, tady je!}
{180}{}{}
{181}{gruth26}{Navrátil jsi moji dùvìru v lidi. Dìkuji ti za vše, co jsi pro moji smeèku udìlal. Mùu ti to nìjak oplatit?}
{182}{}{Øíkal jsi, e mi dáš vìdìt, pokud tu najdeš GECK. Našel jsi ho?}
{183}{}{Ano, hledám GECK. Øekli mi, e by tu mohl bıt. Víš, kde je?}
{184}{}{Ne, díky. Nic víc nepotøebuju.}
{185}{gruth27}{Hm, podívám se. (Odejde a po chvíli se vrátí s nìjakım kovovım kuføíkem, kterı neohrabanì svírá ve svıch velkıch paøátech.) Ano, ve skladišti byl jeden GECK. Je tvùj a moc ti dìkuji.}
{186}{gruth28}{Ano, jeden GECK byl ve skladišti, ale teï chybí. Je mi líto, e ti ho nemùu dát jako odmìnu za tvoji štìdrou pomoc.}
{187}{}{Díky!}
{188}{}{Eh... to je dobrı. Zkusím ho najít nìkde jinde.}
{189}{gruth29}{Zdravím, èlovìèe. Doufám, e ze mì nechceš udìlat hlupáka.}
{190}{}{Chci se omluvit a zaèít od znovu, Gruthare.}
{191}{}{Promiò, musím bìet.}
{192}{}{Eh, já pardón.}
{193}{gruth30}{Zdravím tì, èlovìèe. Zmìnil jsi názor? Pomùeš mi?}
{194}{}{Ani omylem. Jen chci slyšet, jak zase przníš náš jazyk.}
{195}{}{Ne. Myslím, e ne.}
{196}{}{Ano, Gruthare. Pomùu ti.}
{197}{gruth31}{Zdravím tì, pøíteli. Díval ses u na ten stroj?}
{198}{}{Ještì ne, ale pustím se do toho.}
{199}{gruth41}{Ahoj, pøíteli. Podaøilo se ti zachránit smeèku a za to ti dìkujeme.}
{200}{}{}
{201}{}{}
{202}{gruth42}{Chcípni, proradnı èerve!}
{203}{}{}
{204}{}{}
{205}{gruth32}{Nemám s tebou nic co do èinìní, èlovìèe, a ani mít nechci. Snaím se to s tebou vyøešit v klidu, tak se o to sna i ty!}
{206}{}{Dobrá, promluvme si.}
{207}{}{Jsi páraè a to znamená ortel smrti... pro tebe!}
{208}{}{Promiò, Gruthare. Promluvme si.}
{209}{}{To je jedno. Odcházím.}
{210}{gruth33}{Ne. Já jsem tady vùdce, take já rozhoduji. Jestli se ti to nelíbí, mùeš se vrátit do zemì lidí!}
{211}{}{Vyli mi!}
{212}{}{Dobøe, tak já pùjdu.}
{213}{}{Jistì, Gruthare. Obèas zapomínám.}
{214}{gruth34}{Ujišuji tì, e jsem se nesnail bıt vtipnı ani tì tahat za nos. Omlouvám se, jestli ti to tak pøipadalo. Pomùu ti, pokud budu moct.}
{215}{}{Dobøe, díky.}
{216}{}{Promiò, nechtìl jsem ze sebe dìlat chytráka.}
{217}{}{Nech toho ušlechtilıho vatlání, kámo. To na mì neplatí.}
{218}{gruth35}{(Gruthar ze sebe vydá nìkolik hrdelních øevù.) Moná mi to tu nepatøí, èlovìèe, ale je to mùj domov i domov mnoha dalších, kteøí se spoléhají na mou ochranu. Nenu mì udìlat nìco, èeho budeme oba litovat!}
{219}{}{Promiò, pøekraèuju meze slušnosti.}
{220}{}{K èertu s tebou a takovımi jako ty!}
{221}{}{A sakra! Padám odsud.}
{222}{gruth36}{Dìkuji ti. Zajdi prosím do øídící místnosti a vymìò hlasovı modul.}
{223}{}{Jakoby se stalo!}
{224}{}{}
{225}{gruth37}{V tom pøípadì tu nejsi vítán. Odejdi.}
{226}{gruth38}{Sbohem.}
{227}{}{Sbohem.}
{228}{}{Beru.}
{229}{gruth39}{Omluva pøijata, èlovìèe. Pøeji hezkı den!}
{230}{}{Beru.}
{231}{}{. Díval ses u na ten stroj?}
{232}{}{. Budu èekat na tvùj návrat.}
{233}{}{. Podaøilo se ti najít náhradní souèástku na opravu toho stroje?}
{234}{}{Eh, dobøe.}
{235}{gruth43}{Doufám, e si uíváš pobyt.}
{236}{gruth40}{Bohuel k tomu muselo dojít. Dovolil jsem mu zùstat tak dlouho, dokud nepøedstavoval hrozbu pro smeèku. Vybral si svoji cestu. Doufám, e to chápeš.}
{237}{}{Ty zlı.}
{238}{}{Chápu, Gruthare.}
{239}{}{Ano. Matt nebıt dobrı.}
