{100}{}{Vidíš malého, nervóznì vypadajícího mue.}
{101}{}{Vidíš viceprezidenta Birda.}
{102}{}{Vidíš malého, nervóznì vypadajícího mue, obleèeného do obleku se skvrnami od jídla.}
{103}{bird1}{Vida, jeden z našich stateènıch vojákù. Co dìláte v kanceláøi viceprezidenta?}
{104}{bird2}{Zdravím vás, vojáku. Co dìláte v kanceláøi viceprezidenta?}
{105}{bird3}{Vypadáte povìdomì. Nemluvili jsme spolu u nìkdy? No, nevadí. Take, co pohledáváte v kanceláøi viceprezidenta?}
{106}{}{Kdo jste?}
{107}{}{Eh, jsem jen na rutinní obchùzce, eh, pane.}
{108}{}{Hledám vetøelce.}
{109}{}{Chci si ještì jednou projít naše tajné plány.}
{110}{}{Chci vás zabít.}
{111}{bird4}{Tak pokraèujte, vojáku. Pokraèujte. Vy a vaši chlapci odvádíte skvìlou práci. Jsme pøipraveni na jakékoliv neèekané události, které by se mohly naskytnout.}
{112}{}{He?}
{113}{}{Eh, ano. No, radìji dokonèím svoji obchùzku. Sbohem.}
{114}{bird5}{Hmm, povìzte mi, jak hláskujete "dcera"? S 'D' nebo bez?}
{115}{bird6}{Hmm, povìzte mi, jak hláskujete "domnìnka"? S 'N' nebo bez?}
{116}{bird7}{Hmm, povìzte mi, jak hláskujete "ethanol"? S 'H' nebo bez?}
{117}{bird8}{Hmm, povìzte mi, jak hláskujete "vèela"? S 'V' nebo bez?}
{118}{bird9}{Hmm, povìzte mi, jak hláskujete "nápad"? S 'D' nebo bez?}
{119}{}{Eh, asi s.}
{120}{}{Samozøejmì e bez.}
{121}{bird10}{To je samozøejmì správnì. Kadı vìrnı obèan našich skvìlıch Spojenıch Státù by odpovìdìl stejnì.}
{122}{}{Proè myslíte?}
{123}{}{Mám teï práci. Sbohem.}
{124}{bird11}{Tak pokraèujte, vojáku. Vstøíc lepším zítøkùm.}
{125}{}{Co tím myslíš?}
{126}{}{Ne pro vás. Vyhlazuju všechny Enklávské èervy a vy jste právì na øadì.}
{127}{}{Eh, jasnì. Sbohem.}
{128}{bird12}{Musíme spojit síly a pracovat spoleènì, protoe pokud neuspìjeme, riskujeme selhání.}
{129}{}{Moná, e by nebylo a tak špatné, kdybyste selhal.}
{130}{}{No, bude lepší, kdy pùjdu.}
{131}{bird13}{To vám jen tak neprojde.}
{132}{}{Uvidíme.}
{133}{}{Proè ne? }
{134}{bird14}{Zodpovìdnost kadého viceprezidenta se dá vyjádøit jedním slovem a to slovo je "bıt vdy pøipraven."}
{135}{}{Na co jste pøipraven?}
{136}{}{Nejsou to náhodou tøi slova? 'Pøipravenost' je jedno slovo. To jste mìl na mysli?}
{137}{bird15}{Ano, nejspíš ano. Ale nebudeme to rozvádìt. Koneckoncù, uvanìnost vede k nedorozumìní a nepochopení.}
{138}{}{To øíká ten pravı.}
{139}{}{Musím odejít. Sbohem.}
{140}{bird16}{Tím chci øíct, e se nesmíme vracet zpìt do minulosti. Musíme smìøovat kupøedu.}
{141}{}{Není to snad jedinı monı smìr?}
{142}{bird17}{No, opatrnosti není nikdy dost. Koneckoncù, nìkteøí opravdu podivní lidé by se mohli dostat na jistá delikátní místa a to by mohlo mít ohromnı dopad na historii.}
{143}{}{Ano, chápu.}
{144}{}{A jakı dopad na historii plánujete vy?}
{145}{bird18}{Ano, ten smìr mám rád. Osvìdèil se v minulosti a osvìdèí se i v budoucnu. Take se klidnì vydejme kupøedu.}
{146}{}{Eh, jo.}
{147}{bird19}{Vìøím, e jsme zapoèali nezvratnı trend smìøující k vìtší svobodì a demokracii... ale to se mùe zmìnit.}
{148}{}{Zneèištìnému ivotnímu prostøedí pustin by se hodila trocha svobody.}
{149}{}{U toho mám dost. Musíte zemøít.}
{150}{bird20}{Hlupáku. Zneèištìní nemá vliv na ivotní prostøedí. Za všechno mùou neèistoty ve vodì a v ovzduší.}
{151}{}{U musím opravdu jít.}
{152}{}{Kdybyste il na pevninì, nebral byste to tak na lehkou váhu.}
{153}{bird21}{A to je právì ono. Enkláva je toti umìle vytvoøenı ostrov obklopenı vodou.}
{154}{}{Vy si myslíte, e jste proti všemu, co se tady dìje, imunní? Ještì poøád ijeme na stejné planetì.}
{155}{}{Nechtìl byste k tomu ještì nìco dodat? Tøeba nìjakou pointu?}
{156}{bird22}{Jsem viceprezident Daniel Bird a jsem zatracenì rád, e vás poznávám.}
{157}{}{Jste jen malá èást celého tohohle problému.}
{158}{}{Jste cvok.}
{159}{bird23}{Já nejsem ádná èást problému. Jsem Republikán.}
{160}{}{Jak øíkám, jste èást problému.}
{161}{bird24}{No, jak moná víte, u dlouho pøemıšlíme o tom, e je naèase, aby lidská rasa vstoupila do sluneèní soustavy.}
{162}{}{Copak u nejsme v... eh, *kam* e to máme jít?}
{163}{}{Jak toho chcete dosáhnout?}
{164}{bird25}{Myslím, e takovı Mars by mohl bıt ideální, protoe je v podstatì na stejné obìné dráze... je pøiblinì ve stejné vzdálenosti od Slunce, co je velmi dùleité. Vidìli jsme obrázky, na kterıch jsou stopy po kanálech a vìøíme, e i po vodì. Pokud je tam voda, znamená to, e je tam i kyslík. A pokud je tam kyslík, znamená to, e tam mùeme dıchat.}
{165}{}{To byla neèekanì, eh, "vyèerpávající" odpovìï.}
{166}{}{Zbláznil jste se?}
{167}{bird26}{Jak primitivní oznaèovat všechny, kteøí jsou nìjak vıjimeèní, za blázny. Jak typické.}
{168}{}{No, moná to je typické, ale ve vašem pøípadì i opodstatnìné.}
{169}{}{O èem to sakra mluvíte?}
{170}{}{Tak a dost. Nemíním tu dál ztrácet èas. Sbohem.}
{171}{bird27}{Pro organizaci NASA má vesmír stále velmi vysokou prioritu.}
{172}{}{Aha a kam bysme se mìli vydat nejdøív?}
{173}{bird28}{To není pravda. Republikáni chápou, jak je dùleitı vztah mezi matkou a dítìtem. To je klíè k øešení všech našich problémù... musíme se vrátit k rodinnım hodnotám.}
{174}{}{Celá Enkláva vèetnì vás nemá s rodinnımi hodnotami vùbec nic spoleèného.}
{175}{bird29}{Pevnì si stojím za všemi chybnımi kroky, které jsem udìlal.}
{176}{}{Copak nechápete, e vytvoøíte jen další "Totální znièení", pokud budete pokraèovat?}
{177}{}{Jste naprostı šílenec. Uvìdomujete si to?}
{178}{bird30}{Období "Totálního znièení" bylo v našich národních dìjinách velice ošklivım obdobím. Myslím tím naše døívìjší mnohasetleté dìjiny. Naštìstí všichni ijeme v tomto století.}
{179}{}{Jste naprostı cvok.}
{180}{}{Nìkdo by vás mìl zbavit trápení. Pomodlete se, Birde.}
{181}{}{Musím odtud vypadnout.}
{182}{bird31}{D-C-E-R-A}
{183}{bird32}{C-E-R-A}
{184}{bird33}{E-T-H-A-N-O-L}
{185}{bird34}{E-T-A-N-O-L}
{186}{bird35}{Kam se podìly moje dvì piksly jahodové zmrzliny?}
{187}{bird36}{Caine je moje loï. Jenom moje, slyšíš?}
{188}{bird37}{Všichni jste proti mì, e ano? e ano?}
{189}{bird38}{Chy mì, jestli to dokáeš.}
{190}{bird39}{Pìkné, pìkné.}
{191}{bird40}{Nablıskané.}
{192}{bird41}{Ne, mami, to jsem nebyl já. U mì nemla!}
{193}{bird42}{Mami! Mami, kde jsi?}
{194}{bird43}{Tentokrát u nechci bıt pacientem.}
{195}{bird44}{Ne, jehly ne, cokoliv jenom ne jehly.}
{196}{bird45}{Ne, ne, e-he, ne. Neeeeee!}
