{100}{}{Vidíš velmi unavenì vypadajícího mue v bílém plášti.}
{101}{}{Vidíš Dr. Curlinga, vedoucího protichemickıch jednotek Spojenıch státù.}
{102}{}{Vidíš mue v laboratorním plášti potøísnìném chemikáliemi.}
{103}{curl48}{Co dìláte venku?}
{104}{curl49}{Myslím, e bychom vás mìli vrátit zpìt do cely.}
{105}{curl50}{Stráe! Máme tu dalšího uprchlíka.}
{106}{curl51}{Poèkejte tady, zavolám nìkoho, kdo se o vás postará.}
{107}{curl52}{Zajímavé. Netušil jsem, e se díky tomu toxinu stanou hloupìjší.}
{108}{curl53}{Haló? Haló. Je tam nìkdo?}
{109}{curl54}{Odkud se tu vlastnì berete?}
{110}{curl55}{Vypadnìte z mé laboratoøe, vojáku.}
{111}{curl56}{Tohle místo není souèástí vaší obchùzky.}
{112}{curl57}{Vypadnìte odsud, nebo zavolám vašeho nadøízeného.}
{113}{curl58}{Pokraèujte, vojáku.}
{114}{curl59}{ádné problémy jsem nehlásil.}
{115}{curl1}{Vítejte v sekci protichemickıch jednotek, vojáku. Jsem podplukovník doktor Charles Curling. A teï kdy jsme se pøedstavili, tak vypadnìte z mé laboratoøe.}
{116}{}{Nejsem ten, za koho mì máte. Jsem }
{117}{}{ z vesnice Arroyo. Musíme si spolu o nìèem promluvit.}
{118}{}{Promiòte, pane. Moje chyba. Sbohem.}
{119}{curl60}{Všichni na svá místa.}
{120}{curl61}{Uhnìte mi z cesty!}
{121}{curl62}{Pøipraven k akci!}
{122}{curl63}{Vypadnìte odsud, nemám èas se s vámi vybavovat.}
{123}{curl64}{Copak neslyšíte ten poplach?}
{124}{curl65}{Schovejte se! Byl spuštìn poplach!}
{125}{curl66}{Doufám, e je tu dost záchrannıch èlunù.}
{126}{curl67}{Všichni ven!}
{127}{}{Dobøe, }
{128}{}{, nevím sice, jak se vám podaøilo dostat z cely, ale pochybuji, e my dva se máme o èem bavit.}
{129}{}{Tak to se mılíte. A poøádnì.}
{130}{}{Máte pravdu. Jsem tu, abych vás zabil.}
{131}{}{Asi máte pravdu. Sbohem.}
{132}{curl3}{Jsem podplukovník doktor Charles Curling z protichemickıch jednotek Spojenıch státù. A kdo jste sakra vy?}
{133}{}{Jsem vaše nejhorší noèní mùra... mutant se zbraní a vlastním názorem.}
{134}{}{Jsem }
{135}{}{ z vesnice Arroyo. Musíme si spolu o nìèem promluvit.}
{136}{}{Jsem nìkdo, kdo si s vámi potøebuje promluvit.}
{137}{curl4}{Chcete se mnou mluvit? Kdo jste a proè si myslíte, e bych s vámi mìl ztrácet èas?}
{138}{}{Jsem z vesnice Arroyo a musím si s vámi promluvit o záchranì tisícù ivotù.}
{139}{}{Jsem }
{140}{}{ a bude lepší, kdy si se mnou promluvíte, jinak by se vám mohlo nìco pøihodit.}
{141}{}{Máte pravdu. Nemáme se spolu o èem bavit. Stejnì u jste mrtvı mu.}
{142}{}{Pokraèujte v práci, doktore. U odcházím. Sbohem.}
{143}{curl5}{Co jiného by se dalo èekat od primitivních tvorù. Tady je vidìt ten rozdíl mezi vámi a opravdovımi lidmi, jako jsme my.}
{144}{}{Jste si sám sebou nìjak moc jistı, nemyslíte?}
{145}{}{Zasranı fanatiku. Musím vás okamitì zlikvidovat.}
{146}{curl6}{Nevidím ádnı dùvod, proè bych mìl mluvit s mutantem. Zanedlouho, a skuteèní lidé pøevezmou zpìt tuto planetu, budete jen další nešastnou pøipomínkou války. }
{147}{}{Skuteèní lidé? O èem to mluvíte? Jsem èlovìk stejnì jako vy.}
{148}{}{V tom pøípadì mám pro vás jednu nepøíjemnou pøipomínku ve svém koeném pouzdøe.}
{149}{curl7}{Stráe! Pomoc! Stráe!}
{150}{curl8}{Stráe! Pomóóóóóóc!}
{151}{curl9}{Nutná okamitá pomoc v sekci protichemickıch jednotek! Okamitì!}
{152}{curl10}{Stráe! Poplach! Stráe!}
{153}{curl11}{A proè bych nemìl? Náš vızkum na vesnièanech jasnì prokázal zmìny v jejich DNA následkem radioaktivního ozáøení v ovzduší.}
{154}{}{No a co, e je naše DNA trochu odlišná?}
{155}{}{Nevím, co tím pøesnì myslíte, ale co je na tom, e jsme trochu odlišní?}
{156}{curl12}{Ne tak docela. Ve skuteènosti jste docela dost odlišní, alespoò tedy vaše DNA ano. Domnívám se, e je to následkem dlouhodobého pobytu v prostøedí zamoøeném radioaktivitou.}
{157}{}{No a co, e je naše DNA trochu odlišná?}
{158}{}{Nevím, co tím pøesnì myslíte, ale co je na tom, e jsme trochu odlišní?}
{159}{curl13}{Víte, vaše DNA není jen "trochu" odlišná. Je znaènì odlišná. Kdybych nemìl tolik práce s Projektem, velice rád bych provedl nìkolik dalších testù na vašich lidech. Samozøejmì jinıch testù ne tìch tıkajících se FEV. Je to opravdu fascinující práce.}
{160}{curl14}{O èem chceš vìdìt?}
{161}{}{Jak se naše DNA odlišuje?}
{162}{}{Vy dìláte testy na mém kmeni?}
{163}{}{Co je sakra ten "Projekt?"}
{164}{}{U toho mám dost. Zastøelím vás jako vzteklého geckona. Sbohem, kreténe.}
{165}{curl15}{Došlo k øadì velmi nepatrnıch zmìn, ale ještì jsem nemìl èas prozkoumat pøesné následky. Navíc bych musel zpìtnì vystopovat váš pùvodní genom, ne bych mohl vypracovat nìjakou hypotézu ohlednì smìru, kterım se zmìny v organismu ubírají. Ovšem celkovì vzato je jasné, jakı je závìr.}
{166}{}{Co je jasné? Jakı je závìr?}
{167}{}{Ano, moná. Chci se ještì na nìco zeptat, doktore.}
{168}{curl16}{To, e vy i váš kmen u dávno nejste lidé. No a protoe váš kmen opustil Vault (mám pocit, e to byl Vault 13, e ano?) teprve pøed nìjakımi osmdesáti lety, dá se s jistotou tvrdit, e kadı, kdo strávil venku delší dobu, je zasaen ještì více. Ano, obávám se, e závìr je jednoznaènı.}
{169}{}{Závìr? Jakı závìr?}
{170}{curl17}{Myslel jsem, e jsem se vyjádøil dost jasnì. Závìr je takovı, e vy a celı váš druh ji nejste lidé. K pøevzetí vlády nad zemí a zachování èistoty lidské rasy je nutné zlikvidovat všechny mutanty.}
{171}{}{Zlikvidovat? Co tím myslíte?}
{172}{curl18}{Projekt, kterému jsme se zde v Enklávì vìnovali nìkolik posledních desetiletí, má za cíl obnovit lidskou rasu na pevninì Spojenıch státù. Bùh ehnej Americe.}
{173}{}{Nevidím dùvod, proè by to mìlo zabrat celá desetiletí.}
{174}{}{U to nebudu poslouchat. Chci se zeptat na nìco jiného.}
{175}{curl19}{Ano, pouhé zøízení základny nezabere pøíliš dlouho. Vše ji máme zøízeno a pøipraveno v Navarru. Ale dlouho nám trvalo vypracování spolehlivé metody vyhlazovacího postupu.}
{176}{}{Vyhlazovacího postupu?}
{177}{curl20}{Ano, nemùeme se pøeci vrátit zpìt na pevninu a riskovat nakaení od všech tìch zmutovanıch skoro-lidskıch bytostí. Aby byly Spojené státy pro lidstvo bezpeèné, musí bıt nejdøíve všichni mutanti vyhlazeni.}
{178}{}{Coe!?! Zbláznil jste se? To je zrùdné!}
{179}{}{Vyhlazeni? Jak to chcete udìlat?}
{180}{curl21}{To si nemyslím. Spíš to vidím jako velmi dobrı pøíklad spoleèenského Darwinismu. Pøeitím nejsilnìjšího se zajistí reprodukce dalších generací. Úspìšná budoucnost dalších generací, celé lidské rasy, závisí na nás.}
{181}{}{Ano, zmìna je pravdìpodobnì nevyhnutelná èást ivota, ale jen proto, e jsme odlišní, ještì neznamená, e jsme špatní. Kdy nic víc, tak jsme alespoò ivım dùkazem odolnosti lidského druhu. A právì kvùli tomu si zaslouíme pøeít dokonce *víc* ne vaši lidé.}
{182}{}{Pøemıšlel jste nìkdy nad tím, e i kdy jsme rozdílní, mùeme bıt zrovna tak lidští jako vy?}
{183}{}{Vy u ádné budoucí generace mít nebudete, doktore, protoe budete zanedlouho mrtvı.}
{184}{curl22}{Hmm, takto jsem o tom nikdy nepøemıšlel... dejte mi prosím chvíli èasu, abych se nad tím mohl poøádnì zamyslet.}
{185}{}{Dobøe. Kolik jen budete chtít, doktore. Chápu, e je pro vás tahle pøedstava dost tìká.}
{186}{}{Nemáte ani minutu. Váš èas u dávno vypršel. Sbohem, kreténe.}
{187}{curl23}{To je absurdní. Jste asi takovı èlovìk jako je dvouhlavá kráva normální jalovice.}
{188}{}{Pokud tu nìkdy ily jednohlavé krávy, tak u jistì dávno vymøely. Ale kráva jako samotnı druh pøeila a stala se odolnìjší. Zmìna je nedílnou souèástí pøírodního øádu.}
{189}{}{Zabití všech na pevninì je prostì chyba.}
{190}{}{U mì unavují ty vaše kecy. Je èas setkat se s vaším stvoøitelem, Dr. Smrtko.}
{191}{curl24}{Váš druh není zcela zøejmì schopen porozumìt tomu, co se vám snaím øíct. Je to beznadìjné. Radìji odejdìte.}
{192}{}{No, zkusil jsem to. Je èas zemøít, fanatiku.}
{193}{}{Tak dobøe, u jdu. Jeden z nás je moná beznadìjnı, ale myslím, e já to nejsem. Sbohem.}
{194}{curl25}{Ano. Toxikologickou studii úèinnosti FEV toxinu.}
{195}{}{FEV toxin? Co je to?}
{196}{}{Chci se ještì na nìco zeptat.}
{197}{curl26}{FEV toxin je dokonalım øešením tohoto sloitého problému.}
{198}{}{Co je FEV toxin?}
{199}{}{Poèkejte chvíli. Chci se zeptat na nìco jiného.}
{200}{curl27}{Jedna z našich hlídek našla data z vızkumu a nìkolik vzorkù FEV viru v bıvalé, témìø zcela znièené vojenské základnì.}
{201}{}{Dobøe. Teï u vím, kde jste to našli, ale co je to vlastnì zaè?}
{202}{curl28}{Pùvodnì byl FEV navren jako virus, kterı mìl pøemìnit lidské bytosti na super vojáky. Tento experiment zøejmì zcela selhal, aèkoliv já jsem zkusil upravenou verzi viru na jednom z našich agentù tajnıch slueb a povedlo se mi dosáhnout jistého úspìchu.}
{203}{}{Gratuluju, ale co to má spoleèného s vyhlazováním?}
{204}{curl29}{Ach, ano, u jsem se k tomu dostával... FEV virus se váe jen na specifické ivoèišné druhy... na lidské glykoproteiny. Staèilo jen nìkolik let vızkumu FEV viru, abychom vyvinuli ještì smrtelnìjší verzi. Vısledek je dokonalı ve všech smìrech. }
{205}{}{Dokonalı? Jak to?}
{206}{curl30}{Není to snad jasné, mùj zmutovanı pøíteli? Díky mnì je FEV smrtící toxin a díky jednomu záhadnému géniovi, kterı si teatrálnì øíkal Vùdce, funguje pouze na lidi, a u zmutované nebo ne.}
{207}{}{Coe?}
{208}{curl31}{Take to znamená, e máme dokonalı vynález øešící veškeré problémy se skoro-lidskımi mutanty zamoøujícími planetu.}
{209}{}{Stále nechápu, v èem je "dokonalı."}
{210}{}{Chci se zeptat na jinı z vašich bláznivıch nápadù.}
{211}{curl32}{FEV toxin napadá pouze lidi a ostatních ivoèichù si vùbec nevšímá. Nejlepší na tom je, e bìhem jednoho mìsíce budou všichni mutanti mrtví a bez hostitelskıch organismù zanikne i samotnı FEV.}
{212}{}{Pochybuju, e máte dostatek létajících strojù na rozprášení toxinu po celé planetì.}
{213}{}{Asi z vás udìlám hostitele pro nìkolik vysoko-energetickıch projektilù. Pomodlete se.}
{214}{curl33}{Máte pravdu, nemáme. Ani je toti nepotøebujeme. Máme toti systém, kterı bude rozprašovat FEV ze speciálních kádí pøímo do venkovního ovzduší. Vítr za nás poté udìlá zbytek práce. Ke globálnímu nasycení atmosféry dojde bìhem dvou tıdnù.}
{215}{}{Dvou tıdnù?}
{216}{curl34}{Ano, dva tıdny na rozprášení viru a asi tak mìsíc na jeho úèinek. Poté budou Spojené státy pøipraveny na novou kolonizaci opravdovımi lidmi. Náš druh bude zachránìn.}
{217}{}{Vy si vánì myslíte, e dìláte správnou vìc, e ano?}
{218}{}{Humánní tedy moc nejste. Radìji odsud vypadnu, jinak se nedoijete rána. Sbohem.}
{219}{}{Váš druh moná ano, ale vy urèitì ne.}
{220}{curl35}{Ano, myslím. ádná cena není dost vysoká pro pøeití jednoho druhu.}
{221}{}{S tím s vámi souhlasím, ale nezdá se vám, e "mutanti", jak je nazıváte, jsou jen jinım typem lidskıch bytostí?}
{222}{}{S tím s vámi souhlasím, doktore. Myslím, e zaènu rozdávat rány za nás mutanty. A zaènu s vámi!}
{223}{curl73}{Øekl jsem vám, e potøebuji chvíli na rozmyšlenou.}
{224}{curl74}{Opravdu potøebuji nìjakı èas na pøemıšlení.}
{225}{curl75}{Není to snadné rozhodnutí.}
{226}{curl76}{Musím o tom pøemıšlet.}
{227}{curl77}{Dejte mi chvíli, ano?}
{228}{curl36}{Nerad to pøipouštím, ale asi máte pravdu. To, co jsme naplánovali, nebylo správné. Byl jsem natolik zaslepenı øešením problémù, e jsem vùbec nepøemıšlel o mravních zásadách tohoto poslání.}
{229}{}{No a teï kdy jste si to rozmyslel, mìl byste ten virus znièit.}
{230}{curl37}{To by... ne, to by nemìlo smysl.}
{231}{}{Proè ne?}
{232}{curl38}{Protoe by se tím nic nevyøešilo. I kdy budu mrtvı, stále je v Navarru spousta dat z vızkumu, z nich by nebyl problém replikovat moji práci. Chtìlo by to nìco velmi drastického.}
{233}{}{Velmi drastického? Co tím myslíte?}
{234}{curl39}{Enkláva musí bıt znièena. Úplnì znièena. Pokud k tomu nedojde, tak prostì nashromádíme veškerá potøebná data a zaèneme odznovu nìkde jinde.}
{235}{}{Je mi líto, e nìco takového slyším. Jakı zpùsob znièení Enklávy navrhujete, doktore?}
{236}{curl40}{Myslím, e nejlepší by bylo vypuštìní FEV toxinu do vìtracího systému. Jeliko je Enkláva hermeticky uzavøenı systém, mìlo by to zasáhnout kadého.}
{237}{}{A co moji lidé? Nebo já? Nebo vy, napøíklad?}
{238}{curl41}{Mùu vypustit protilátky do vìtracích systémù ve všech celách. Patro s celami má oddìlenı vìtrací systém od zbıvající èásti Enklávy. Všichni si budou myslet, e jsem spustil jen další test. Vám mohu naoèkovat protilátku pøímo teï a tady. (Pøistoupí k tobì se støíkaèkou.)}
{239}{}{Jau, díky, doktore. Co se stane po vypuštìní FEV toxinu?}
{240}{}{Hej, poèkejte chvíli. Nechci, abyste mi píchnul tu vìc!}
{241}{curl42}{Nebude to moc pìkné. Odejdìte odsud jak nejrychleji to pùjde. Radìji budu mít na svìdomí nìkolik tisíc mrtvıch ne nìkolik stovek tisíc. Náš èas je u konce. Naše šance vypršela.}
{242}{}{Jak osvobodím své lidi z vìzeòské oblasti?}
{243}{curl43}{Zkuste vypnout energii. Vím, e je reaktor øízen velikım poèítaèem poblí reaktoru, ale nevím, jak ho vypnout.}
{244}{}{Díky za poskytnuté informace. Na vaši obì budou vzpomínat všichni lidé z celého svìta.}
{245}{}{No u bylo naèase, abyste koneènì pøišel k rozumu. A teï si pospìšte.}
{246}{}{Kdy paprsky hvìzd zemi ozáøily,}
{247}{}{a jejich slzy nebe zaplavily,}
{248}{}{usmál se, kdy spatøil dílo své?}
{249}{}{Stvoøil krom Beránka boího i tìlo tvé?}
{250}{}{He?}
{251}{curl45}{To jsem si jen vzpomnìl na jednu dávno zapomenutou báseò. Zajímalo by mì, zda-li je v nebi ještì místo pro ty, kteøí pracovali na tak temném poslání. Náš èas vypršel, váš naopak právì zaèíná. Bìte!}
{252}{}{Aha, dobøe. Díky za pomoc, doktore. Jste stateènı mu.}
{253}{}{Jste blázen... ale uiteènı blázen. Sbohem.}
{254}{curl68}{Bìte!}
{255}{curl69}{Zmizte odsud.}
{256}{curl70}{Pospìšte si!}
{257}{curl71}{Nemáte moc èasu!}
{258}{curl72}{Bìte odtud, dokud mùete!}
{259}{curl46}{Copak to nechápete? Bez protilátky zemøete bìhem nìkolika hodin.}
{260}{}{No dobøe, v tom pøípadì mi to teda píchnìte, doktore. Co se stane po vypuštìní FEV toxinu?}
{261}{}{ádné jehly, ani omylem. Já u si nìjak poradím.}
{262}{curl47}{Nikdy se ke svım lidem nedostanete, pokud nebudete naoèkován. Co je to s vámi? Snad se nebojíte malého píchnutí?}
{263}{}{Samozøejmì, e ne... pokud se na to nebudu dívat. Jauvajs! No a co se vlastnì stane po vypuštìní FEV toxinu?}
