{100}{}{Vidíš hubeného, nervóznì vypadajícího mue.}
{101}{}{Vidíš "bezbolestného" doktora Johnsona, lékaøe Reddingu.}
{102}{}{Vidíš mrtvolnì bledého nervózního chlápka s vyboulenıma oèima.}
{103}{docj1}{Tvoje hlava je vìtší, ne jsem si myslel.}
{104}{docj2}{Tvoje pøeènívající oboèí potvrzuje moje obavy.}
{105}{docj3}{Máš nádhernì vyvinuté nadoènicové oblouky.}
{106}{docj4}{Zajímalo by mì, jestli se ti zmenšila mozková kapacita dlouhodobım vystavením radiace.}
{107}{docj5}{Tady není ádné jídlo. Vypadni!}
{108}{docj6}{Kšá, kšá!}
{109}{docj7}{Vra se do pustiny, neandrtálèe.}
{110}{docj8}{Škoda, e nejsou divoši tak pasivní jako brahmíny. Mohli by bıt uiteènìjší.}
{111}{docj9}{Vypadá to, e jste u správného èlovìka. Jsem doktor Johnson a mùu vás dát do poøádku.}
{112}{docj10}{Zdravím. Váš pøítel zøejmì potøebuje lékaøskou pomoc. Já jsem "bezbolestnı" doktor Johnson a mùu se o nìj postarat.}
{113}{docj11}{Vypadá to, e jste se dostali do poøádné šlamastiky. Já jsem doktor Johnson a jestli chcete, mùu vás dát do poøádku.}
{114}{docj12}{Zdravím, jsem doktor Johnson. Moje zkušené oko mi øíká, e nevypadáte zrovna nejlépe. Mám vás dát do poøádku?}
{115}{docj13}{Zdravím, jsem doktor Johnson. Jestli chcete, podívám se vám na vaše pøátele. Nevypadají moc dobøe.}
{116}{docj14}{A u jste chytli cokoliv, jsem si jistı, e to zvládnu. Jsem doktor Johnson.}
{117}{docj15}{Tak se mi zdá, e potøebujete dát do kupy, e? Ukate, doktor Johnson se na to podívá. Nemìjte obavy, jsem profesionál.}
{118}{docj16}{Tak copak se vám zase stalo? Ukate, starı doktor Johnsona se na to podívá.}
{119}{}{Díky, doktore. Kolik to bude stát?}
{120}{}{Chci jen koupit nìjaké lékaøské potøeby.}
{121}{}{Nepotøebuju teï vyléèit, potøebuju se na nìco zeptat.}
{122}{}{Tìší mì, ale myslím, e teï ádnou lékaøskou pomoc nepotøebuju. Díky, doktore. Sbohem.}
{123}{docj17}{Za kompletní uzdravení si úètuju $50.}
{124}{docj18}{Za uzdravení vašeho pøítele chci $50. Bude jako novı, to vám slibuju.}
{125}{}{Tady máte peníze, doktore.}
{126}{}{Bohuel si to teï nemùu dovolit. Promiòte, doktore, moná jindy.}
{127}{}{$50, jo? Moná nìkdy jindy. Sbohem, doktore.}
{128}{docj19}{Nìco vám øeknu: kdy vidím, jak na tom jste, nabídnu vám skupinovou slevu. Vyléèím vás všechny za pouhopouhıch $100.}
{129}{}{Tady máte peníze, doktore. Dejte nás do poøádku.}
{130}{}{Bohuel si to teï nemùu dovolit. Promiòte, doktore, moná nìkdy jindy.}
{131}{}{$100, jo? Moná nìkdy jindy. Sbohem, doktore.}
{132}{docj20}{Vypadá to, e na tom nejste zrovna nejlépe. Vyléèím vás všechny za $100. Mám se o to pokusit?}
{133}{docj21}{Váš pøítel nevypadá zrovna nejlépe. Vyléèím ho za $100. Mám se o to pokusit?}
{134}{}{Doufám, e dokáete i víc ne se o to jen pokusit. Tady jsou peníze.}
{135}{}{Bohuel si to teï nemùu dovolit. Promiòte, doktore, moná jindy.}
{136}{}{$100? Moná nìkdy jindy. Sbohem, doktore.}
{137}{docj22}{Koukám, e sem pøišla partièka trosek. No, mùu vás dát do poøádku, ale bude vás to stát $150. Mám se do toho pustit?}
{138}{}{Ano, prosím. Tady jsou peníze.}
{139}{}{To si teï bohuel nemùu dovolit. Promiòte, doktore, moná nìkdy jindy.}
{140}{}{$150, jo? Moná nìkdy jindy. Sbohem, doktore.}
{141}{docj23}{Rád bych vám pomohl, ale nemáte dost penìz na zaplacení. Lékaøské potøeby nìco stojí.}
{142}{}{Ale no tak, doktore, opravdu moc potøebujeme lékaøskou pomoc.}
{143}{}{Vrátím se, a budu mít víc penìz. Sbohem.}
{144}{docj24}{No tak dobøe, pro tentokrát udìlám vıjimku. Jen doufám, e pøíštì mi u zaplatíte.}
{145}{docj25}{Jednou jsem udìlal vıjimku, ale po druhé u ne... teï ty peníze toti nutnì potøebuju. Nic na tomhle svìtì nedostanete zadarmo... moje sluby nevyjímaje.}
{146}{}{Díky, doktore, váím si toho. Pøíštì vám to zaplatím. Slibuju.}
{147}{}{Nechci zneuívat vaší laskavosti. Radìji se vrátím, a budu mít na zaplacení.}
{148}{}{Dobøe, promiòte. Ale ne odejdu, chci se ještì na nìco zeptat.}
{149}{}{Dobøe, dobøe. U pùjdu. Sbohem, doktore.}
{150}{docj26}{Je mi líto, ale bez penìz do hospody nelezte. Nemùu zdarma vyléèit kadého, kdo si o to øekne. To bych byl za chvíli na mizinì. Pøijïte, a budete mít na zaplacení.}
{151}{}{Nemám sice peníze, ale mám nìjaké vìci na prodej. Mùu je vymìnit za vaše sluby?}
{152}{}{Ne odejdu, chci se ještì na nìco zeptat.}
{153}{}{Dobøe, zkusím nìkde sehnat víc penìz. Sbohem.}
{154}{docj27}{Co potøebujete vìdìt?}
{155}{docj28}{Co to bude teï?}
{156}{}{Myslím, e mám nìco, co vyøeší místní problém s Jetem.}
{157}{}{Øíká se, e má Redding poslední dobou problémy s vıvozem.}
{158}{}{Hodila by se mi lékaøská pomoc.}
{159}{}{Dìje se nìco zajímavého ve mìstì?}
{160}{}{Proè vám øíkají "bezbolestnı" doktor Johnson?}
{161}{}{Nemáte na prodej nìjaké lékaøské potøeby?}
{162}{}{Jenom se tak dívám. Sbohem, doktore.}
{163}{docj29}{Vypadá snad tohle jako nìjakı obchod? Ne, nemìním vìci za lékaøské sluby. Pøijímám pouze poctivé dolary, díky. Pøijïte, a nìjaké seenete.}
{164}{}{Tak dobøe. Chápu. Sbohem.}
{165}{docj30}{No, moná bych vám mohl obstarat nìjaké zásoby. Ukate, co mi mùete nabídnout.}
{166}{}{Dobøe, doktore.}
{167}{}{Nemyslím hned teï, jen mì zajímalo, jestli taky nìco prodáváte. Chci se ještì na nìco zeptat.}
{168}{}{No, zrovna teï nic nepotøebuju. Uvidíme se pozdìji, doktore.}
{169}{docj31}{Bude to všechno?}
{170}{docj32}{Take, hotovo?}
{171}{}{Ukate mi ještì jednou vaši nabídku.}
{172}{}{Díky, doktore. Chci se ještì na nìco zeptat.}
{173}{}{Myslím, e jo, doktore. Prozatím sbohem.}
{174}{docj33}{Tak a máte to za sebou. Potøebujete ještì nìco?}
{175}{}{Vlastnì se chci ještì na nìco zeptat.}
{176}{}{Ne, to bude všechno. Díky, doktore.}
{177}{docj34}{No, moc dlouho bych to neodkládal. Nìkterá zranìní mùou hnisat a pak je z toho infekce. Nìkdy dokonce i gangréna. Ale je pravda, e jsem poslední dobou svoje noe moc èasto nepouíval, take jsem trochu vyšel ze cviku. Víte co? Zatím se na to vykašlete a nechte to bıt. Snad vám s tím budu schopen pomoct pozdìji.}
{178}{}{Aha. A zatímco mám infekci, chci se ještì na nìco zeptat.}
{179}{}{Eh, jo, popøemıšlím o tom. Sbohem, doktore.}
{180}{docj35}{Poslední dobou tráví stále více horníkù èas "létáním" na Jetu místo toho, aby tìili. Pokud to takhle pùjde dál, produkce reddingského zlata se nejspíš úplnì zastaví, ale zdá se, e to New Renu pøíliš nevadí.}
{181}{docj36}{Vìtšina místních horníkù pracuje jenom proto, aby si mohli zase poøádnì šlehnout Jetu. Produkce zlata jde rapidnì dolù. Pokud to takhle bude pokraèovat, New Reno bude èasem ovládat Redding.}
{182}{docj37}{Všichni místní horníci jen poøád fetují. Nikdo z nich u skoro vùbec netìí zlato. Obávám se, e New Reno bude mít Redding brzy pod kontrolou. Pøál bych si, aby existoval zpùsob, jak tuhle závislost na Jetu zastavit.}
{183}{}{Co s tím má New Reno spoleèného?}
{184}{}{Odkud se ten Jet bere?}
{185}{}{Aha. Chci se ještì na nìco zeptat.}
{186}{}{Díky za informace. Uvidíme se pozdìji, doktore. Sbohem.}
{187}{docj38}{Zdravím, já jsem "bezbolestnı" doktor Johnson. Co pro vás mùu udìlat?}
{188}{docj39}{Co pro vás mùe starı doktor Johnson udìlat?}
{189}{}{Zdravím, doktore. Chci se ještì na nìco zeptat.}
{190}{}{Zajímalo by mì, jestli nemáte na prodej nìjaké lékaøské potøeby.}
{191}{}{Doktore, slyšel jsem o nìjakıch speciálních podkoních implantátech. Nevíte o tom nìco?}
{192}{}{Jenom se tak dívám, doktore. Tìšilo mì. Sbohem.}
{193}{docj40}{Díky vám nejspíš vyøeším místní problém s Jetem. Ten lék, kterı jsem podstrèil do zásob Jetu, odvádí skuteènì skvìlou práci. Všem feákùm je po nìm špatnì.}
{194}{}{Jsem rád, e to funguje. Chci se ještì na nìco zeptat.}
{195}{}{A nemají lidé podezøení, e jste jim prodal špatnou dávku Jetu?}
{196}{}{Jsem rád, e to funguje, doktore. Myslím, e u asi pùjdu. Sbohem.}
{197}{docj41}{Díky vaší protilátce jsou místní problémy s Jetem u konce. Vypadá to, e New Reno bude muset vymyslet jinı zpùsob, jak si nás podmanit.}
{198}{}{Rádo se stalo. Chci se ještì na nìco zeptat.}
{199}{}{A nemìli lidé podezøení, e jste jim prodal špatnou dávku Jetu?}
{200}{}{Co s tím má New Reno spoleèného?}
{201}{}{Jsem rád, e to fungovalo, doktore. Zatím sbohem.}
{202}{docj42}{Opravdu? Co máte na mysli?}
{203}{}{Mám toti protilátku na Jet. Vyrobil ji doktor Troy z Vault City a mìla by vyøešit místní problém se závislostí na Jetu.}
{204}{}{Vlastnì nic. Chci se ještì na nìco zeptat.}
{205}{docj43}{To opravdu máme. Pøíliš Jetu, málo práce... odkud to víte?}
{206}{}{McClure z Vault City mi o tom øekl.}
{207}{}{Obèas nìco zaslechnu.}
{208}{}{To není dùleité. Chci se ještì na nìco zeptat.}
{209}{docj44}{New Reno prodává Jet hodnì levnì. Jet je toti velmi návykovı, v tom se mu nic nevyrovná, take je napadlo, e pokud ho bude uívat dost lidí v jednom mìstì, udìlají cokoliv, jen aby ho mìli víc. To dává New Renu de facto kontrolu nad celou oblastí, tøeba jako je Redding.}
{210}{}{Aha. Chci se ještì na nìco zeptat.}
{211}{}{Kdy nechcete, aby New Reno ovládalo Redding, tak kdo by to tu podle vás mìl øídit?}
{212}{}{Díky za vysvìtlení, doktore. Sbohem.}
{213}{docj45}{Všechen místní Jet pochází z New Rena od rodiny Mordinù. Chodí vìtšinou ve velkıch krabicích a já ho pak pøelévám do ampulí... take pak vlastnì všechno prodávám já.}
{214}{}{Z toho máte urèitì velkı zisk.}
{215}{}{Urèitì máte New Reno velice rád.}
{216}{}{Aha. Chci se ještì na nìco zeptat.}
{217}{}{Nemìl byste pro mì trochu toho Jetu?}
{218}{docj46}{O tom pochybuju. Myslím, e jsou natolik zvyklí na to, e Jet pøelévám do ampulí, e vùèi mì nemají ani špetku podezíravosti. Dìlám to u docela dlouhou dobu a stále jsem tu doktorem.}
{219}{}{Jsem rád, e nemáte problémy. Chci se ještì na nìco zeptat.}
{220}{}{To je dobøe. Vìci by byli urèitì jinak, kdyby vás lidé podezírali. Sbohem, doktore.}
{221}{docj47}{No, kadı chce svùj podíl na reddingském zlatì, take nás stejnì bude nìkdo èasem ovládat. Já jen chci, aby to byl nìkdo, kdo je pro Redding nejpøínosnìjší.}
{222}{}{A tím máte na mysli koho?}
{223}{docj48}{Podle mì by pro Redding bylo nejlepší, kdyby to tu spravovalo Vault City. Pocházím odtamtud... take se mùe zdát, e jsem pøedpojatı, ale já si opravdu myslím, e Vault City dokáe vyjít vstøíc obèanùm Reddingu.}
{224}{}{Proè myslíte?}
{225}{docj49}{Protoe se ve Vault City o všechno starají spravedlivım a lidskım zpùsobem, take by udìlali to samé i pro Redding.}
{226}{}{Vault City se o svoje obèany stará dobøe, ale s tìmi, co nejsou obèané, zachází jako s hadrem.}
{227}{}{U chápu, doktore. To docela dává smysl.}
{228}{docj50}{Brzy si uvìdomí vıhody. Jsem si jistı, e pøivítají nadvládu Vault City s otevøenou náruèí, eh, èasem.}
{229}{}{Jasnì. Chci se ještì na nìco zeptat.}
{230}{}{No nevím. Sbohem.}
{231}{docj51}{To je nesmysl. Vault City sice zajišuje obèanùm zvláštní privilegia, ale jenom proto, e jsou k tomu zpùsobilejší ne necivilizovaní lidé. A navíc, kadı se mùe stát obèanem, pokud úspìšnì sloí zkoušky obèanství.}
{232}{}{No nevím, jak budou zdejší lidé reagovat na vládu Vault City.}
{233}{}{Jo, jasnì. Sbohem, doktore.}
{234}{docj52}{Plním ampulky s Jetem a pak je prodávám místním lidem. Nemám z toho ádnı zisk. Kdybych to nedìlal já, dìlal by to nìjakı šarlatán s nesterilními èi dokonce rezavımi nástroji a pak bych tohle mìsto u nikdy úplnì nevyléèil.}
{235}{}{Vy jste ale hodnı, doktore. Opravdu. Chci se ještì na nìco zeptat.}
{236}{}{To je od vás opravdu *ušlechtilé*, doktore.}
{237}{}{Zajímavé. Uvidíme se pozdìji, doktore. Sbohem.}
{238}{docj53}{Pro pøíštì si prosím odpuste ten sarkastickı tón. Klidnì si tomu øíkejte ušlechtilost, pokud chcete, ale já preferuju praktiènost. Majitelé dolù mi platí za lékaøskou péèi horníkù a jejich práceschopnost. Kdybych nechal pracovat na Jetu nìkoho jiného, nikdy bych nebyl schopen dìlat práci, za kterou jsem placenı.}
{239}{}{Aha. Chci se ještì na nìco zeptat.}
{240}{}{Hmm. Díky, e jste mi o tom povìdìl. Sbohem, doktore.}
{241}{docj54}{Doktor Troy? Toho znám. Je to neobyèejnì talentovanı lékaø. Kdy jsem byl ještì ve Vault City, pracoval jsem s ním. Povìzte mi o té protilátce.}
{242}{}{Vy jste pracoval ve Vault City?}
{243}{}{Doktor Troy mi øekl, e vám mám tu protilátku pøinést a vy u budete vìdìt co s ní.}
{244}{docj55}{Ano, tam jsem získal své lékaøské znalosti. Jsem obèan Vault City. Postupem èasu jsem ale zjistil, e je na svìtì spousta míst, kde potøebují mé lékaøské znalosti víc ne ve Vault City a proto jsem tady. Vrame se ještì k té protilátce...}
{245}{}{Doktor Troy mi øekl, e vám mám tu protilátku pøinést a vy u budete vìdìt co s ní.}
{246}{docj56}{To opravdu vím. Staèí, kdy mi ji dáte.}
{247}{}{Tady je, doktore.}
{248}{}{Ne tak rychle, doktore. Jakou má pro vás cenu?}
{249}{}{Myslím, e si ji ještì chvíli ponechám. Mìjte se, doktore. Sbohem.}
{250}{docj57}{Jakou má pro mì cenu? Ty malej syèáku! Já tì...}
{251}{}{Uklidnìte se, doktore. Víte, vìtšinou se zaènu tøást, kdy na mì nìkdo mluví tímhle zpùsobem. No a pak mám problémy udret pøedmìty v ruce... jako tøeba tuhle zkumavku s protilátkou.}
{252}{}{Dobøe, dobøe. Jenom si dìlám srandu. Tady to máte.}
{253}{docj58}{Díky. Teï dohlédnu na to, aby horníci dostali v pøíští dávce Jetu nìco *extra*.}
{254}{}{A nebudou vás z toho podezírat, doktore?}
{255}{}{Rádo se stalo. Chci se ještì na nìco zeptat.}
{256}{}{Dobøe. Nesnáším pohled na všechny ty "piloty" Jetu. Sbohem, doktore, a hodnì štìstí.}
{257}{docj59}{No dobøe, dostal jste mì. Dám vám za to $2000. Víc nemám.}
{258}{}{No, to bude muset staèit. Dobøe, tady to máte, doktore.}
{259}{}{Myslím, e si to ještì chvíli nechám. Sbohem, doktore.}
{260}{docj60}{To klidnì mùete, ale nemyslete si, e ze mì dostanete víc penìz. Já toti opravdu víc nemám.}
{261}{}{No, tak dobøe. Vezmu si tìch $2000. Tady máte tu protilátku, doktore.}
{262}{}{Uvidíme. Sbohem, doktore.}
{263}{docj61}{Znám McClura. Je èlenem mìstské rady Vault City. Co vám všechno øekl?}
{264}{}{Napøíklad to, e produkce dolù klesá a ceny zlata stoupají.}
{265}{}{Nevím, jestli vám to mùu øíct.}
{266}{docj62}{Opravdu? Co tøeba?}
{267}{}{Napøíklad to, e produkce dolù klesá a ceny zlata stoupají.}
{268}{}{Vlastnì jenom samé hovadiny. Chci se ještì na nìco zeptat.}
{269}{docj63}{To je pravda. Zdejší horníci se místo práce èím dál tím víc vìnují Jetu. Tím pádem jde vıvoz dolù a ceny nahoru. Taková situace nemùe dlouho vydret.}
{270}{}{To není dobré. Hmm, chci se ještì na nìco zeptat.}
{271}{}{To nezní moc dobøe. Sbohem, doktore.}
{272}{docj64}{To proto, e mí pacienti vìtšinou upadnou do bezvìdomí døív, ne je to zaène doopravdy bolet. Je to tak trochu vtip.}
{273}{}{Aha. No, to je, eh, uklidòující. Chci se ještì na nìco zeptat.}
{274}{}{Myslím, e u radìji pùjdu. Právì jsem si toti vzpomnìl, e mám dùleitou schùzku, eh, na jednom místì. Eh, sbohem, doktore.}
{275}{docj65}{Mì to mùete øíct, jsem doktor.}
{276}{}{No jo vlastnì, tak dobøe. Øekl mi, e je produkce hodnì dole a ceny vysoko.}
{277}{docj66}{Nìco jsem u o tom èetl. Není to tak tìká operace, pokud máte lékaøské znalosti. A vybavení, samozøejmì.}
{278}{}{Máte všechny potøebné vìci k provedení operace?}
{279}{docj67}{Témìø. Mám na to zkušenosti i znalosti, ale nemám materiál na implantáty.}
{280}{}{A co to znamená?}
{281}{docj68}{To znamená, e budeme muset improvizovat. Myslím, e všechno potøebné získám z bìné kevlarové zbroje. Mùu z ní vzít jak obranné pláty, tak termální membrány.}
{282}{}{To je skvìlé. Take mì mùete operovat?}
{283}{docj69}{No, ano... ale jakmile do vás vloím tyhle implantáty, tak zapomeòte na úèast v soutìi krásy.}
{284}{}{To mì nezajímá, já chci prostì vìtší ochranu. Take které operace dokáete provést?}
{285}{docj70}{V úvahu pøipadají ètyøi rozdílné operace. Jako první tu jsou standardní podkoní implantáty, které ochraòují vùèi fyzickému útoku, a pak jsou tu implantáty typu Phoenix, které ochraòují pøed árem. Potom tu ještì mám rozšíøenou verzi obou základních. Musíte mít ovšem nejdøív tu základní, pokud budete chtít i tu rozšíøenou.}
{286}{docj71}{O které operaci se toho chcete dozvìdìt víc?}
{287}{}{Myslím, e to není nic pro mì. Chci se ještì na nìco zeptat.}
{288}{}{Øeknìte mi víc o tìch implantátech. Chci, abyste mì operoval.}
{289}{}{To mi staèí. Promyslím si to. Sbohem.}
{290}{docj72}{O které operaci se chcete dozvìdìt víc?}
{291}{}{O standardních podkoních implantátech.}
{292}{}{O implantátech typu Phoenix.}
{293}{}{O rozšíøené verzi standardních implantátù.}
{294}{}{O rozšíøené verzi implantátù typu Phoenix.}
{295}{}{Doktore, myslím, e se radìji zeptám na nìco ménì... eh, problematického.}
{296}{}{Myslím, e o ádné operaci teï nechci nic slyšet. Sbohem.}
{297}{docj73}{Podle toho, co jsem èetl, by vám mìly tyto podkoní implantáty pøidat 5% odolnost vùèi vıbuchùm a normálnímu poškození. To se samozøejmì pøièítá ke kvalitì zbroje, kterou nosíte. Operace zabere asi dva dny, bude stát $5000 a budu na ni potøebovat jednu kevlarovou zbroj, kvùli materiálu. Zákrok by mìl bıt celkem jednoduchı... alespoò myslím. Hmm, moná ani nebudete mít ádné ošklivé jizvy.}
{298}{}{To zní skvìle, doktore. Mùeme zaèít. U mám dost toho, jak do mì poøád nìkdo støílí a bodá, ale úplnì ze všeho nesnáším, kdy se mì nìkdo snaí vyhodit do vzduchu.}
{299}{}{Povìzte mi nìco o jinıch operacích.}
{300}{}{Vrátím se, a budu mít víc penìz, doktore. Zatím sbohem.}
{301}{}{Vrátím se, a nìkde seenu kevlarovou zbroj, doktore. Zatím sbohem.}
{302}{}{Myslím, e teï ádnou operaci nepotøebuju. Sbohem, doktore.}
{303}{docj74}{Nejdøív budete potøebovat základní verzi podkoních implantátù, ne si budete moct dovolit tu rozšíøenou, ale u teï vám mùu øíct, co to pro vás bude znamenat. Získáte celkem 10% odolnost vùèi vıbuchùm a normálnímu poškození. To se samozøejmì pøièítá ke zbroji, kterou nosíte. Operace zabere nìkolik dní a bude vás stát $30000. Bohuel se vám ale po tomto zákroku sníí charisma, protoe díky všem tìm plátùm pod kùí budete vypadat trochu hranatì, ale zase dost uhlazenì. Ale komu by se nelíbilo jeho nové auto, e? Pokusím se vám neudìlat ádnı vırùstek.}
{304}{docj75}{Rozšíøená verze standardních podkoních implantátù vám zaruèí celkem 10% odolnost vùèi vıbuchùm a normálnímu poškození. To se samozøejmì pøièítá ke zbroji, kterou nosíte. Operace zabere nìkolik dní a bude vás stát $30000. Bohuel se vám ale po tomto zákroku sníí charisma, protoe díky všem tìm plátùm pod kùí budete vypadat trochu hranatì, ale zase dost uhlazenì. Ale komu by se nelíbilo jeho nové auto, e? Pokusím se vám neudìlat ádnı vırùstek. Mùeme zaèít?}
{305}{}{To zní skvìle, doktore. Mùeme zaèít. Chci maximální ochranu a je mi jedno, jak budu potom vypadat.}
{306}{}{Povìzte mi nìco o jinıch operacích.}
{307}{}{Vrátím se, a budu mít víc penìz, doktore. Zatím sbohem.}
{308}{}{Vrátím se, a nìkde seenu kevlarovou zbroj, doktore. Zatím sbohem.}
{309}{}{Myslím, e teï ádnou operaci nepotøebuju. Sbohem, doktore.}
{310}{docj76}{Podle všeho by vám mìly implantáty typu Phoenix zaruèit 5% odolnost vùèi áru (oheò, laser a plazma). To se samozøejmì pøièítá ke zbroji, kterou nosíte. Operace zabere nìkolik dní a bude vás stát jednu bìnou kevlarovou zbroj (kvùli teplu rozptylujícím membránám) a $8000. Nemusíte se ale znepokojovat, tahle operace vás bude stát *jenom* pár jizev... alespoò podle toho, co jsem èetl.}
{311}{}{To je skvìle, doktore. Koneènì nebudu potøebovat opalovací krém.}
{312}{}{Povìzte mi nìco o jinıch operacích.}
{313}{}{Vrátím se, a budu mít víc penìz, doktore. Zatím sbohem.}
{314}{}{Vrátím se, a nìkde seenu kevlarovou zbroj, doktore. Zatím sbohem.}
{315}{}{Myslím, e teï ádnou operaci nepotøebuju. Sbohem, doktore.}
{316}{docj77}{Nejdøív budete potøebovat základní verzi implantátù Phoenix, ne si budete moct dovolit tu rozšíøenou, ale u teï vám mùu øíct, co to pro vás bude znamenat. Získáte celkem 10% odolnost vùèi áru (plazma, oheò a laser). To se samozøejmì pøièítá ke zbroji, kterou nosíte. Operace zabere nìkolik dní a bude vás stát $48000. Bohuel se vám ale po tomto zákroku sníí charisma, protoe díky všem tìm tepelnım membránám pod kùí budete vypadat trochu hrbolatì, podobnì jako pøecpané burrito.}
{317}{docj78}{Rozšíøená verze implantátù Phoenix vám zaruèí celkem 10% odolnost vùèi áru (plazma, oheò a laser). To se samozøejmì pøièítá ke zbroji, kterou nosíte. Operace zabere nìkolik dní a bude vás stát $48000. Bohuel se vám ale po tomto zákroku sníí charisma, protoe díky všem tìm rozptylovaèùm tepla pod kùí budete vypadat trochu hrbolatì, podobnì jako pøecpané burrito.}
{318}{}{To zní dobøe, doktore. Mùeme zaèít.}
{319}{}{Povìzte mi nìco o jinıch operacích.}
{320}{}{Vrátím se, a budu mít víc penìz, doktore. Zatím sbohem.}
{321}{}{Vrátím se, a nìkde seenu kevlarovou zbroj, doktore. Zatím sbohem.}
{322}{}{Myslím, e teï ádnou operaci nepotøebuju. Sbohem, doktore.}
{323}{docj79}{Tak, hotovo. Operace byla úspìšná. U si nemusíte dìlat starosti o otoky a modøiny. Všechny puchıøe a bolestivá místa za pár dní odezní.}
{324}{docj80}{Nikdy bych neøekl, e se pod vaši kùi vejde tolik implantátù, ale operace se opravdu zdaøila. Nejenom e teï vypadáte jako Frankenstein, ale jste i tak houevnatı. Ještì nìco, vyhıbejte se pøímému slunci, dokud nezmizí vìtšina strupù.}
{325}{docj81}{Tak a je to hotové, alespoò myslím. Implantáty typu Phoenix šly implantovat mnohem snadnìji, ne jsem pøedpokládal. Všechno to svìdìní a pálení by mìlo za pár tıdnù odeznít... a si vaše vnitønosti zvyknou na všechny ty spoje.}
{326}{docj82}{Á, vidím, e jste koneènì vzhùru. Právì jste doslova nacpanı rozptylovaèi tepla a tepelnımi membránami. Za pár tıdnù u sice nebudete vypadat tak hrbolatì, ale i tak zapomeòte na úèast v soutìi krásy. Jo a zkuste se neškrábat kolem drenáí, dokud z nich nepøestane vytékat hnis.}
{327}{}{Díky za radu, doktore. Je to skvìlé. Poslyšte, chci se ještì na nìco zeptat.}
{328}{}{Díky za operaci, doktore. U musím jít. Sbohem.}
{329}{}{Protilátka na Jet byla doruèena doktoru Johnsonovi.}
