{100}{}{Vidíš opotøebovanì vypadající enu.}
{101}{}{Vidíš Fannie Mae, jednu z hostesek hospody U Malamuta.}
{102}{}{Vidíš enu, která vypadá, e u má najeto pìknıch pár mil. Mezi nohama.}
{103}{}{(Fannie je celá bledá a vrávorá smìrem k tobì.) Nazdar, drahoušku. Poslední dobou se necejtím moc dobøe. Mohl bys obìtovat trochu penìz na palivo? Vynahradím ti to. (ušklíbne se)}
{104}{}{(Fannie je celá bledá a vrávorá smìrem k tobì.) Nazdárek, sestro. Mohla bys obìtovat trochu penìz na pomoc nešastnı holce? Ne se zase postavím na nohy, víš.}
{105}{}{(Fannie nevypadá zrovna nejlépe.) Ahoj, slaïouši. Nechceš si uít trochu srandy s Fannie? Pro tebe jen za polovinu, drahoušku. Kam jsem jenom dala ten Jet?}
{106}{}{(Fannie nevypadá zrovna nejlépe.) Nazdárek, sleèinko, nemáš nìjakı drobnı? Nebo dokonce trochu Jetu?}
{107}{}{Fannie, vypadáš opravdu hroznì. Co kdybys toho Jetu na chvíli nechala?}
{108}{}{Myslím, e u jsi okusila hodnì z mojí dobroèinnosti a zdá se, e ti to vùbec nepomohlo.}
{109}{}{U jsi mìla dost.}
{110}{}{Co kdyby ses z toho radìji vyspala?}
{111}{}{Jet je jediná vìc, která mi umoní lítat. ./~Pojï létat se mnou ./~ Cítím se po nìm jako bohynì.}
{112}{}{Ty máš ale nápady... no nic, stejnì tì nepotøebuju. Je spousta lidí, co rádi zaplatìj za Faniin pùvab. Jestli mi nedáš prachy na Jet, tak odsud zmiz.}
{113}{}{Mám nìco, co dokáe vyléèit tvoji závislost na Jetu.}
{114}{}{Najdi si nìjakého jiného blbeèka, Fannie. Sbohem.}
{115}{}{Jestli v tom budeš pokraèovat, tak se jednou zabiješ. Nehodlám tì pøi tom pozorovat. Sbohem.}
{116}{fanni34}{Ty jsi ale kus.}
{117}{fanni35}{Fannie s blbeèkama nespí.}
{118}{fanni36}{Vra se, a budeš mít víc penìz, a Fannie tì moná nìèemu pøiuèí.}
{119}{fanni37}{Nejseš zrovna nejbystøejší, viï?}
{120}{fanni38}{Jseš chytrej jak lopata.}
{121}{}{Vyléèit? Jseš blázen? Vypadám snad, e chci vyléèit? Chceš snad, abych se cítila líp, drahoušku? Radši mi dej víc Jetu.}
{122}{}{No dobøe, ta trocha ti snad neublíí. Tady máš Jet.}
{123}{}{U jsi mìla dost Jetu. Poslední vìc, co chci vidìt, je další závislák na Jetu. Sbohem.}
{124}{}{Mít u sebe Jet, nechám ho si pro svoje vlastní potøeby. Sbohem.}
{125}{fanni8}{Jo, to jsem pøesnì potøebovala. Jooooo. To je skvìlı. Mmmmm...}
{126}{}{Eh, asi tì nechám o samotì, aby sis to mohla poøádnì uít. Sbohem.}
{127}{}{Vypadá to, e jsi teï pìknì sjetá. Uvidíme se pozdìji. Sbohem.}
{128}{fanni9}{Nazdar, fešáku. Chodíš sem èasto? Pøišel jsi sem navštívit Fannie Mae?}
{129}{fanni10}{Zdravím, sestro. Sháníš práci?}
{130}{}{Eh, jo. Pøišel jsem tì navštívit.}
{131}{}{Práci? Jakou práci?}
{132}{}{Eh, jenom se tak dívám. Sbohem.}
{133}{}{Jseš zlatej. A taky pìknì ostıchavej. Návštìva u mì tì bude stát $60, zlato.}
{134}{fanni12}{Snad u teï vydríš o trochu dıl, zlato. Víc si tak uiješ svejch $60.}
{135}{fanni13}{Ne tak zhurta, drahoušku. Zavedu tì do sedmıho nebe za pouhıch $60.}
{136}{}{60 babek, jo? To je docela rozumná cena. Tady máš peníze.}
{137}{}{Díky za nabídku, ale moná nìkdy jindy. Sbohem.}
{138}{}{$60? Myslím, e za takovou cenu nemám zájem. Sbohem.}
{139}{}{Byl jsi ke mnì tak milej. Cítila jsem, e to pro tebe nìco znamenalo. (vzlyk) Pøála bych si, aby to tak bylo pokadı.}
{140}{}{No, se mnou to takové bude pokadé.}
{141}{}{Ty opravdu víš, jak èlovìka potìšit.}
{142}{}{U to nechci dìlat. Já a mı kámoši odsud vypadneme a budeme ít spoøádanej ivot. Teda a zaplatím Lou.}
{143}{}{A zaplatíš Lou?}
{144}{}{Hele, u jsem ti dával peníze. O èem to mluvíš?}
{145}{}{No, víš... dluím Lou nìjakı prachy a nemùu odejít døív, ne jí zaplatím. A a to udìlám, (smrk) vezmu s sebou svıho pøítele a zmizíme odsud tak daleko, jak to jen pùjde. Pokud ale seenu nìjakı prachy.}
{146}{}{Kolik ještì musíš zaplatit Lou?}
{147}{}{A to ti s tìmi penìzi nemùe pomoct tvùj pøítel?}
{148}{}{To je opravdu smutnı pøíbìh, ale podle mì ty peníze brzy seeneš. Staèí kdy budeš poøádnì roztahovat nohy. Sbohem.}
{149}{}{Potøebuju jen $200 a mùj pøítel a já odsud odejdeme nezadluení a volní.
 U ádnı divnı, špinavı lidi, co mì osahávaj ve dne v noci. Eh, bez uráky.}
{150}{}{V pohodì. Já tì snad neosahával, nebo jo? Nicménì, mùu tì odsud vyplatit. Tady máš $200.}
{151}{}{To je opravdu smutné. No, asi by ses mìla vrátit do práce. Sbohem.}
{152}{}{Ach, díky, díky. A já myslela, e tak hodní lidi existujou jenom ve snech. Jseš nejlepší. Ještì jednou díky.
Poèkej, nechceš si to ještì jednou rozdat? Na úèet podniku?}
{153}{}{No, proè ne, Fannie. Rád tvou nabídku pøijmu.}
{154}{}{To opravdu není nutné, Fannie. Radìji bì pouít ty peníze, abys koneènì skonèila s tímhle ivotem. Sbohem.}
{155}{}{On by opravdu chtìl, ale stìí vychází ze svıho hornickıho platu. Poøád doufáme, e se mu podaøí najít poøádnı loisko zlata, ale zatím nic. A navíc na nìj minulej tejden spadl trám a zlomil mu nohu, take teï nemùe pracovat. Musím mu teï dávat tìch pár penìz, co našetøím, ne se uzdraví.}
{156}{}{To vypadá, e vy dva asi nemáte moc velké štìstí. Kolik e to potøebuješ?}
{157}{}{Ještì jednou díky. U to bìím øíct svımu pøíteli. Vypadneme odsud hned, jak se uzdraví.}
{158}{}{To bylo opravdu velkorysé podìkování, Fannie. Radìji odsud odejdu, dokud ještì mùu chodit. Rádo se stalo. Sbohem.}
{159}{}{Tvùj odchod bude pro tenhle podnik velká ztráta, Fannie. Sbohem.}
{160}{fanni21}{Zdravím. Nechceš strávit nìjakej èas s Fannie?}
{161}{}{Nedal jsem ti snad peníze, abys tohle pøestala dìlat?}
{162}{}{Jasnì, to zní dobøe. Ještì e jsi neodešla.}
{163}{fanni22}{No, ano... ale ukázalo se, e dluím Lou víc, ne jsem si myslela.}
{164}{}{Kolik ještì potøebuješ?}
{165}{}{U to nebudu poslouchat. Sbohem.}
{166}{}{Eh, já vím, a jsem ti opravdu vdìèná... ale bohuel dluím Lou víc, ne jsem si myslela. Potøebuju další prachy.}
{167}{}{To si snad dìláš srandu! Kolik ještì potøebuješ?}
{168}{}{No, ode mì u víc nedostaneš. Sbohem.}
{169}{fanni24}{To je v pohodì, zlato. U jsi mi pomohl dost. (smrk) Potøebuju u jenom $150.}
{170}{}{No, jestli to bude u koneènì staèit... ale víc ti u nedám. Myslím to vánì.}
{171}{}{Jo, jasnì. Padám odsud. Sbohem.}
{172}{}{Vítám tì zpátky. Chceš si trošku uít, nebo mi chceš dát víc penìz pro Lou?}
{173}{}{Pøišel jsem si jen uít, Fannie. Pak uvidíme.}
{174}{}{Kolik ještì musíš zaplatit Lou?}
{175}{}{Jenom tak procházím. Sbohem, Fannie.}
{176}{fanni26}{Vdycky jsem ráda, kdy se ke mnì zákazníci vracej. Kvùli tobì dokonce vymìním i prostìradlo.}
{177}{}{Ty opravdu víš, jak chlapa potìšit. Díky.}
{178}{}{Eh, rozmyslel jsem si to. Uvidíme se pozdìji, Fannie. Sbohem.}
{179}{fanni27}{Vdy víš, roztahování nohou. Vsadím se, e by sis s takovou figurou dokázala pìknì vydìlat.}
{180}{}{Vdy víš, roztahování nohou. Sice nevypadáš nic moc, ale stejnì by sis dokázala vydìlat. Horníci nejsou zrovna moc vybíraví, to mi vìø.}
{181}{}{Myslíš? Hmm, moná bych to mìla zkusit.}
{182}{}{To není nic pro mì. Sbohem.}
{183}{fanni29}{V tom pøípadì doufám, e nemáš moc vybíravej nosánek, protoe horníci nemaj zrovna moc v lásce vodu a mıdlo.}
{184}{}{Opravdu? No, moná to pro mì tak úplnì není. Ale díky za nabídku. Sbohem.}
{185}{}{Nechápu, jak to mùeš vydret, ale hádám, e taky asi nevydríš. Tím myslím ten smrad. Sbohem.}
{186}{}{(Fannie vypadá, jako kdyby z ní spadlo tìké bøemeno, které ji pøedtím tíilo.) Hej, to jsi ty! Lou mi øekla, co jsi udìlal. Z toho, co mi nalila do pití, se mi udìlalo pìknì blbì, ale od tı doby nemám vùbec nutkání si vzít další dávku Jetu. (Políbí tì na tváø.) Ani nevím, jak bych se ti mohla odvdìèit... teda, vìdìla bych o jednı *vìci*. Kdykoliv budeš mít náladu, tak se zastav. Bez placení. (mrkne)}
{187}{}{Budu na to myslet. Díky, Fannie.}
{188}{fanni31}{Ještì jednou díky. (olízne si ret) A pamatuj, pro tebe je to vdycky na úèet podniku. (mrkne)}
{189}{fanni32}{Zdravím! Nechceš strávit nìkolik pøíjemnejch chvilek s Fannie? Na úèet podniku, samozøejmì. (ušklíbne se)}
{190}{fanni39}{Promiò, zlato... ale nìjak se necejtím se ve svı kùi. Stav se pozdìji.}
{191}{}{Máš teï na chvilinku èas?}
{192}{fanni33}{Vra se kdykoliv budeš chtít! Vdycky si to ráda zopakuju.}
{193}{}{[KONEC]}
{200}{}{Nalil jsi protilátku na Jet do pití Fannie Mae.}
{210}{}{Dobøe, tady je $60. Co takhle si dát další èíslo?}
