{100}{}{Vidíš starého, pøátelsky vypadajícího chlapíka.}
{101}{}{Vidíš doktora Jubilee.}
{102}{}{Je to starı mu s bílou bradkou a lehce prázdnım pohledem.}
{103}{jub1}{Jsem doktor Jubilee. Co se dìje, mladı mui?}
{104}{jub2}{Co se dìje, mladı mui?}
{105}{}{Já zranìn.}
{106}{}{Potøebuju doktora.}
{107}{}{Nemùete si vzít nìjakı pilulky nebo nìco a pøestat mì otravovat s takovıma blbostma?}
{108}{}{Ale prdlajz, vdy sotva krvácíte.}
{109}{jub3}{No nevím. Myslím, e tu nohu nedokáu zachránit. Moná ji budu muset amputovat.}
{110}{}{To si dìláte srandu!}
{111}{}{Haha.}
{112}{jub4}{Tak a je to, synku.}
{113}{}{Znova.}
{114}{}{Díky, doktore. Moná byste mi mohl ještì zodpovìdìt pár otázek.}
{115}{}{Sbohem.}
{116}{}{Bude vás to stát $50.}
{117}{}{Prostì mì uzdravte.}
{118}{}{Mizím odsud.}
{119}{}{Ty dìlat líp.}
{120}{}{Já teï jít.}
{121}{jub7}{Ne. Nikdy neertuju. Radši tu nohu uøíznu døív, ne se do rány dostane snì.}
{122}{}{V ádném pøípadì se nebude nic øezat, rozumíte?}
{123}{}{Tak a dost, odcházím.}
{124}{jub8}{Dobrá, ale jestli to zaène hnisat, tak to na mì nesvádìjte.}
{125}{jub9}{Nedìlám to pro charitu. Budete muset sehnat nìjaké peníze, ne pro vás nìco udìlám.}
{126}{jub10}{Take, co pro vás mùu udìlat?}
{127}{jub11}{Mluvte.}
{128}{}{Vault 13?}
{129}{}{Nevíte, kde najdu Vault 13?}
{130}{}{Prı na tom pan Westin není dobøe. Je to pravda? Bojím se, aby se mu nìco nestalo. Dluí mi peníze.}
{131}{}{Slaneèek tvrdí, e jste mu ukradl mapu. O co jde?}
{132}{}{Hledám práci. Nevíte o nìèem?}
{133}{}{Doktore, nevíte nìco o skupinì, která bojuje s tìmi zlımi otrokáøi?}
{134}{jub12}{Nemusíte se obávat, synku. Pokud nebude svùj organismus pøetìovat, tak nás pravdìpodobnì všechny pøeije. Samozøejmì by mì ale musel nìkdy poslouchat nebo brát své léky.}
{135}{}{To je dobrá zpráva. Chci se ještì na nìco zeptat.}
{136}{}{Díky, doktore.}
{137}{jub13}{Ten starej opilec! Jediná vìc, kterou od nìj mám, je obraz s "Velvet Elvii", místo dluhu.}
{138}{}{Velvet Elvii? Mùu ho vidìt?}
{139}{}{Náhodou nevypadá jako mapa, e? No nic, zamìstnám váš mozek nìèím jinım.}
{140}{}{No, u musím jít.}
{141}{jub14}{O tom jsem neslyšel od té doby, co sem pøinesli starıho Slaneèka. S úpalem. Leel v horeèkách tøi dny a celou dobu blouznil o tom, jak našel Vault 13, svoji mateøskou ílu.}
{142}{}{Mateøskou ílu?}
{143}{}{Take kde to je?}
{144}{}{Kde vault?}
{145}{jub15}{To nedokáu øíct. Slaneèek poøád tvrdil, e má mapu, ale nikdo ji nikdy nevidìl.}
{146}{}{Slaneèek?}
{147}{}{Ptát se víc.}
{148}{}{No, aspoò vím víc ne pøedtím.}
{149}{jub16}{A velikou. Slaneèek je starı hledaè uranu, pøesnìji øeèeno opilec. Momentálnì ije u Westina.}
{150}{}{Další otázka...}
{151}{}{Díky za pøíbìh.}
{152}{jub17}{No, doufal jsem, e za nìj dostanu nìjaké peníze. Nechám vám ho za $}
{153}{}{Moná pozdìji, další otázka...}
{154}{}{Moná pozdìji, teï musím jít.}
{155}{jub18}{Slaneèek je starı hledaè uranu. Momentálnì ije u Westina.}
{156}{}{Další otázka...}
{157}{}{Díky za pøíbìh.}
{158}{jub19}{Nejlepší bude, kdy si promluvíte s prezidentkou Tandi. Slyšel jsem, e hledá nìkoho speciálního.}
{159}{}{Další otázka...}
{160}{}{Díky.}
{161}{jub20}{Moná jo... existuje skupinka, která bojuje proti otrokáøství a, no, vìtšinì neøestí. Nìkdy jsou k vidìní u toho velkého obchodu jak pracují na nìjakém autì.}
{162}{}{Další otázka...}
{163}{}{Díky.}
{164}{jub48}{Hej, dej od toho pracky pryè, hajzle!}
{165}{jub49}{Opatrnì! I nepatrné mnoství je nebezpeèné.}
{166}{jub50}{Vrate to zpátky! Mùete si tím dost ublíit.}
{167}{jub51}{Ty léky jsou pro pana Westina, ne pro vás. Vrate je zpátky.}
{168}{jub52}{Jdìte od toho. Musím bıt opatrnı, víte. Nechci, aby pan Westin dostal špatné léky.}
{169}{jub53}{Dávejte pozor! Právì jsem odmìøil dávku pro pana Westina.}
{170}{jub21}{Jsem doktor Jubilee. Co se dìje, sleèno?}
{171}{jub22}{Co se dìje, sleèno?}
{172}{jub23}{Tak a je to, sleèno.}
{173}{jub24}{Nemusíte se bát, sleèno. Pokud nebude svùj organismus pøetìovat, tak nás pravdìpodobnì všechny pøeije. Samozøejmì by mì ale musel nìkdy poslouchat nebo brát své léky.}
{174}{}{Jasnì. Tady je $}
{175}{jub25}{Díky, pokoušel jsem se dostat peníze ze Slaneèka, ale ten pobuda nikdy ádné nemìl.}
{176}{}{.}
{200}{}{Dávejte pozor, }
{201}{}{synku! }
{202}{}{sleèno! }
{203}{}{S tím si nemùete zahrávat! Právì jsem odmìøil dávku pro pana Westina a nechceme pøeci, aby dostal špatné léky. Co si pro pána krále myslíte, e dìláte?}
{204}{}{Jen mì zajímaly ty pilulky, co máte támhle na polici.}
{205}{}{Och, pardon. Jen se tak rozhlíím kolem.}
{206}{}{Promiòte. Odjakiva mám neodolatelné nutkání hrabat se ostatním ve vìcech a nemùu se toho zbavit.}
{207}{}{Upøímnì? Kdo by to byl øekl, e jste tak všímavı. Nejspíš budu muset improvizovat.}
{210}{jub28}{Opravdu? (Doktor Jubilee se na tebe rozvánì podívá.) Já myslel, e problémy se srdcem mají spíše starší lidé.}
{211}{}{To máte pravdu. Mùj pøítel Cassidy je potøebuje. Je to u starší chlap. Má špatné srdce a cestování pustinami mu nedìlá dobøe.}
{212}{}{Ké byste mìl pravdu. Mám to dìdiènì po svém otci. Alespoò to mi øekli.}
{213}{}{Ále, to vùbec ne. Jen moje zvìdavost nìkdy pøekraèuje meze.}
{220}{jub29}{No, to nemùete. Tohle je soukromá klinika a ne nìjakej obchod. Zkuste se podívat k Duppovi kousek na sever odsud.}
{221}{}{To zní pøesnì jako to, co hledám. Nashle.}
{222}{}{Podívám se tam. Nebude vám vadit, kdy se mezitím na nìco zeptám?}
{223}{}{Ne, myslím, e jsem na správném místì. Vidím, e tu odvádíte dobrou práci. Pøijímáte sponzorské dary?}
{230}{}{(Doktor zamrká a poté zamrká ještì jednou.) Moná by nebyl špatnı nápad si o tom s nìkım promluvit. Bohuel já nejsem ten správnej doktor. O tı polici vám øeknu jenom to, e jestli smícháte nebo upravíte nìkterı z tìch pøedpisù, tak to nìjakej uboák pìknì odskáèe, pokud bude vùbec schopnej skákat. Radši na to nesahejte.}
{231}{}{Spolehnìte se, doktore. Ale, eh, poslyšte... mám pøítele, kterému by se ty vaše pilulky na srdce docela hodily. Myslíte, e byste mi mohl nìjaké prodat?}
{240}{}{Víte, }
{241}{}{synku, }
{242}{}{sleèno, }
{243}{}{rád bych vám pomohl, ale teï nepøijímám ádné nové pacienty. Úøady mi platí pevnou mzdu. Ani vám nemùu prodat ádné pilulky... Westinovi lidé si pro nì mají pøijít bìhem }
{244}{}{ dní, }
{245}{}{ jednoho dne }
{246}{}{a v ádném pøípadì nebudu mít èas na to, abych do té doby namíchal další várku.}
{247}{}{Rozumím, doktore. Moná najdu nìjakého slušného lékárníka jinde. Pokud toho od vás nebudu ádat pøíliš, mohl byste mi dát nìjakou radu ohlednì srdeèních problémù? Takové léky se nedají tak snadno sehnat.}
{248}{}{Tak u to chodí. Ale myslím, e to bude v pohodì. Ze starıch komixù mám naèteno *tuny* vìcí o kardiomagii. Sníit poèet denních dávek lékù na dvì, MAXIMÁLNÌ, cvièit v krátkıch, ale intenzivních intervalech, aby srdce pracovalo tak, jak má, a podobné chytré rady.}
{250}{jub33}{Cítím s vámi, pøíteli, ale obávám se, e tyto pilulky jsou urèené pro pana radního Westina a u nepøijímám ádné nové pacienty, take vám ani nebudu moct pøedepsat recept. A teï u se prosím nehrabte v té polici. Jestli se ty recepty zamíchají, tak to nìkdo šerednì odskáèe.}
{260}{}{Nìco si ujasníme, }
{261}{}{pane. }
{262}{}{sleèno. }
{263}{}{Co pøesnì myslíte tím "sponzorské dary?"}
{264}{}{Dobroèinnı pøíspìvek na podporu vaší sluby veøejnosti, øeknìme... $150? Mùete si to v zadní místnosti pøepoèítat. Zabere to jenom chvilinku, ne?}
{265}{}{Eh, vlastnì myslím, e se radìji poradím se svım úèetním, ne udìlám nìco ukvapeného. Uvidíme se pozdìji, doktore.}
{270}{}{Obávám se, e to nepùjde. Ty jsou pro radního Westina. Jeho lidé si je mají vyzvednout bìhem }
{271}{}{ dní, }
{272}{}{ jednoho dne }
{273}{}{a v ádném pøípadì nebudu mít èas na to, abych do té doby namíchal další várku. Urèitì nìkde najdete lékarníka, kterı nemá tolik práce.}
{274}{}{Chápu. No, tak díky.}
{280}{jub36}{(Doktor Jubilee na tebe chvíli zírá.) Aha, vy mì vodíte za nos, e jo? Urèitì mì vodíte za nos. (Opìt na tebe zírá, zatøese hlavou a oddechne si.) Fíha. Nicménì, co bych to byl za doktora, kdybych vám nedal alespoò pár rad.}
{281}{jub37}{Mno... pro zaèátek bych doporuèil pøestat s... no, skoro se vším. ádné pití, ádné kouøení, ádné èervené maso a ÁDNÉ léky. Pokud mono kadı den cvièit v MÍRNÉ zátìi a nepøetìovat se. ivot není závod, tedy alespoò v tomhle pøípadì není nutné bıt první. Abych øekl pravdu, tak tyhle øeèi stejnì nikdo neposlouchá, ale alespoò se mi bude dnes líp spát.}
{282}{jub38}{Ale dùleitìjší je najít slušného lékárníka a øíct mu, e potøebujete bìnou dávku Triproxinilu. Tri-prox-i-nil. V pustinách sice nemají tak pøepychové zboí jako mám já, ale chemicky je to všechno stejné, pokud se budeme bavit o tìch nejzákladnìjších slokách. 30 miligramù dvakrát dennì.}
{283}{jub39}{Taky musíte tyhle prášky zapíjet dostateènım mnostvím vody. A a vás ani nenapadne *dotknout* se práškù na potenci, co prodávají v New Renu, rozumíte? Vùbec to spolu nejde dohromady. Staèí smíchat jeden s Triproxinilem a váš Frantík nebude to jedinı, co budete mít ten den tvrdı, jestli mi rozumíte.}
{284}{}{(Mluví si pro sebe.) Hmm, to by mohlo fungovat. No jasnì. Moná nìco na zpùsob PDE-5 tlumící sloky...}
{285}{jub40}{Jo a pokud vás zastaví nìjakej poulièní prodavaè v Renu, tak vám bude moná vykládat o tom, e ty prášky ochránìj vaše srdce pøed kterımkoliv svinstvem, kterı zkusíte. No nebudu vám lhát... moná je to èásteènì pravda, ale stejnì z vás bude jenom obyèejnej feák. Nechci vás nìjak pouèovat, protoe jste dostateènì inteligentní a pubertu u máte za sebou, ale u se stalo.}
{286}{}{Mockrát díky, doktore. Nemáte ani ponìtí, jak moc jste mi pomohl. Mìjte se.}
{287}{}{Tri-prox-i-nil a ádné pilulky na e-rek-ci. Hehe. Budu si to pamatovat. Zatím, doktore.}
{290}{}{Vy si myslíte, e se bavíte s nìjakım podplatitelnım vesnickım felèarem, }
{291}{}{synku, }
{292}{}{dìvèe, }
{293}{}{je to tak? Tak to jste vedle. Já jsem kvalifikovanı a povìøenı profesionální zdravotník NCR a to má vìtší cenu ne nìjaká hrst drobnıch.}
{294}{}{Omlouvám se. Èlovìk vašeho kalibru má oèividnì cenu sponzorského daru v hodnotì alespoò $250.}
{295}{}{(Sklonit hlavu.) Poslyšte, opravdu se omlouvám. Nemám v oblibì nìco takového bìnì dìlat a rozhodnì si to nedám za rámeèek, ale musím se vám k nìèemu pøiznat: Ty pilulky zoufale potøebuju.}
{296}{}{Omlouvám se za ty nepøíjemnosti. Myslím, e radìji pùjdu, ne to pokazím ještì víc.}
{300}{}{(Doktor Jubilee zaèíná rudnout.) Asi jsem se pøedtím špatnì vyjádøil,}
{301}{}{ chlape, }
{302}{}{ enská, }
{303}{}{take nastrate poøádnì uši: Jsem doktor v NCR. Je to èestná práce a ta vyaduje èestnou pøísahu. Ještì jednou po mì budete chtít, abych se na tu pøísahu vysral a JEDINOU vìc, kterou z ní vyhodím, bude "Pøedevším neškodit." Chápete?}
{304}{}{Tak dobøe, kašlete na to. Kdy tvrdíte, e jste a tak dobrı, tak chci vidìt, jak se dáte po tomhle dokupy.}
{305}{}{Jejda. Nebylo v mém úmyslu se vás nìjak dotknout, doktore. Nechám vás na chvíli bıt.}
{310}{}{Poslyšte, doktore, zajímaly by mì ty pilulky, co máte támhle na té polici.}
{311}{}{Jste si opravdu jistı, e mi ty pilulky nechcete prodat?}
{320}{}{Je mi líto, lidé radního Westina si je mají vyzvednout bìhem }
{321}{}{ dní, }
{322}{}{ jednoho dne }
{323}{}{a v ádném pøípadì nebudu mít èas na to, abych do té doby namíchal další várku.}
{324}{}{(Mumlá si pro sebe.) Kam jsem sakra dal ty pilulky pro pana Westina? Bez nich mu to srdce dlouho nevydrí. (Podívá se vzhùru.) Och, promiòte. Co pro vás mùu udìlat?}
{325}{}{Nedalo se nepøeslechnout vaši zmínku o pilulcích na srdce. Vlastnì se vás chci na ty léky zeptat.}
{330}{jub47}{(Mumlá si pro sebe.) Nemùu uvìøit, e je pan Westin mrtvı. To nemohla bıt pøece moje chyba, mìl jsem ty pilulky nadávkované správnì. (Podívá se vzhùru.) Och, promiòte. Co pro vás mùu udìlat?}
