{100}{}{Vidíš cosi mezi psem a napùl kovovou vìcí. Zdá se, e je to v provozu.}
{101}{}{Je to RoboPes! Nejoblíbenìjší mazlíèek všech lidí!}
{102}{}{Buï je tahle vìc nìjaká hrùznì sešitá kombinace psa a stroje, nebo je to stroj, kterı je k nerozeznání od skuteèného psa. Tìko øíct.}
{103}{dogr16}{Òaf! <cvak> Haf!}
{104}{dogr17}{...bzzzzzz...}
{105}{dogr18}{.bzíík... Já nejsem pejsánek.}
{106}{dogr19}{Vrrrrrrrrrrrrrrrr...}
{107}{dogr20}{Haf! Ha-ha-ha-<klapk>haaf.}
{108}{dogr21}{<škrr> Mòau... chyba.}
{109}{dogr22}{Štìkštìkštìkštìkštìkštìk!}
{110}{dogr23}{Vrrr...}
{111}{dogr24}{Ha-ùùùù! <click-click> Ha-ùùùù!}
{112}{dogr25}{Jejda! Jejda! Jejda!}
{113}{dogr26}{Nebezpeèí! Nebezpeèí!}
{114}{dogr27}{Vrraf! <uk-uk-uk> Vrraf!}
{115}{dogr28}{<whirrr> Ani pták, ani letadlo, dokonce ani ába, jenom starı dobrı - RoboPes!<klap>}
{116}{dogr29}{Rooby-Doo!}
{117}{dogr30}{Eé-béé-déé-béé-éé-béé-déé-béé!}
{118}{dogr31}{Haf!}
{119}{dogr32}{VRRR-HAF!}
{120}{dogr1}{Òaf-òaf-òaf-òaf-òaf-òaf-òaf!}
{121}{}{OK}
{122}{}{Myslím, e se k tobì ještì nechci pøidat. Sbohem.}
{123}{dogr2}{Vrraf? <klap> Òaf?}
{124}{}{Jak se máš?}
{125}{}{Potøebuju, abys tu poèkal, ne se vrátím.}
{126}{}{To bude prozatím všechno.}
{127}{dogr3}{<klap> kòuèí.}
{128}{}{Zapomeò na to.}
{129}{}{OK}
{130}{}{HB:}
{131}{}{Kyberpes u nejde víc opravit.}
{132}{}{Kyberpes byl èásteènì opraven.}
{133}{}{Kyberpes byl zcela opraven.}
{1000}{dogr4}{Haf! Ha-ha-ha-<klap>haaf?}
{1100}{dogr5}{Òaf! <cvak> Haf!}
{1200}{dogr6}{Vrraf? <klap> Òaf?}
{1300}{dogr7}{<cvak> kòuèí.}
{1400}{dogr8}{Ha-ùùùù! <click-click> Ha-ùùùù!}
{1500}{}{Eé-béé-déé-béé-éé-béé-déé-béé!}
{1600}{}{Jistì, dám to pryè.}
{1700}{}{Haf-haf vzdálenost nastavena blízká.}
{1800}{}{Haf-haf vzdálenost nastavena støední.}
{1900}{}{Haf-haf vzdálenost nastavena velká.}
{2000}{dogr14}{.bzíík... Já nejsem pejsánek.}
{2100}{dogr33}{VRRR-HAF!}
{2200}{dogr15}{Haf! Ha-ha-ha-<klap>haaf?}
{2204}{}{Tvoje vzdálenost je momentálnì vyhovující.}
