{100}{}{Vidíš šedovlasého mue v uniformì NCR policie.}
{101}{}{Vidíš šerifa NCR.}
{102}{}{Tento mu je názorná ukázka toho, jak by mìl správnı policista vypadat - vlasy na jeka, hranatá èelist a pøímoèaré vystupování.}
{103}{dum1}{Vítej v NCR, cizinèe. Jmenuju se Dumont, šerif Dumont. Doufám, e si to tady uíváš v míru a poklidu.}
{104}{dum2}{Pøijmi malou radu od šerifa Dumonta, cizinèe - v tomhle mìstì nemáme rádi lidi, jako jsi ty. Jakékoliv potíe a pùjdu tvrdì po tobì. Mùu pro tebe teï nìco udìlat?}
{105}{dum3}{Zdravím. Mùu pro tebe nìco udìlat?}
{106}{dum4}{No tak se vymáèkni.}
{107}{}{Heegh.}
{108}{}{Hledám Vault 13. Nevíš, kde se nachází?}
{109}{}{Nemáš GECK?}
{110}{}{Hledám nìjakou poctivou práci. Nevíš o nìèem?}
{111}{}{Jo, je tu fajn. Všechno je bájeèné.}
{112}{dum5}{Primitiv, e? Ty. Otázky? Ptát já. Ano?}
{113}{}{Vault 13?}
{114}{}{GECK?}
{115}{}{Dobøe.}
{116}{dum6}{Ne, to nevím, ale je to nìco, co by ráda vìdìla i prezidentka Tandi. Vyøešilo by nám to spoustu problémù.}
{117}{}{Problémù? Jakıch problémù?}
{118}{}{Prezidentka Tandi?}
{119}{}{Dobøe. Jen zkouším štìstí. Díky.}
{120}{dum7}{Poslyš, já vedu prospìšnı ivot a mám èistı rejstøík! Nemám ádnı GECK ani cokoliv podobného.}
{121}{}{Tak promiò! Nevíš náhodou, kde se nachází Vault 13?}
{122}{}{Tak na to zapomeò. U pùjdu.}
{123}{dum8}{O nìèem bych vìdìl, jestli máš zájem.}
{124}{dum9}{Dìláš si srandu, ne? Po té události s Jackem? Myslím, e by se urèitì nìjaká slušná práce našla.}
{125}{}{Napøíklad?}
{126}{}{Zmìòme téma.}
{127}{}{Zapomeò na to, odcházím. Sbohem.}
{128}{dum10}{Ne Vault 13. Vault 15 ano.}
{129}{}{Pat-náct?}
{130}{}{Ne. Tøi-náct!}
{131}{dum11}{Ano, 15! Ty mluvit s Tandi. Velkı náèelník NCR. Tandi znát Vault. Hledat pomoc. Ty jít za Tandi.}
{132}{}{Tandi?}
{133}{}{Já nejít. Já chtít 13!}
{134}{dum12}{Po-slou-chej. ádnı Vault 13. Nenalezen. Nevidìt. Ne 13. Vault 15 - lidé najít. Lidé ít ve Vault 15. Ty rozumìt?}
{135}{}{Ne tøi-náct? Pat-náct?}
{136}{}{NE. JÁ CHTÍT TØINÁCT!}
{137}{dum13}{Ááááá! NENÍ ÁDNÁ 13, TY TUPEJ ZABEDNÌNÈE! ádná 13. Nenalezen. Vùbec! Nikdy!}
{138}{dum14}{Tandi velkı náèelník. Tandi chtít pomoct. Ty mluvit s Tandi. Jít do kon-gresu. Rozumìt?}
{139}{}{GECK?}
{140}{}{Dobøe.}
{141}{dum15}{Nepotøebovat GECK. Já zdravı. Ne nemocnı.}
{142}{}{Vault 13?}
{143}{}{Dobøe.}
{144}{dum16}{Rozhlédni se kolem sebe. NCR se neustále rozrùstá. Potøebujeme souèástky, poèítaèe a tak podobnì. Jenome máme problém se squattery, kteøí se zabydleli ve Vaultu 15.}
{145}{}{Vault 15? Squatteøi? O co tady jde?}
{146}{}{Kdo je to ta prezidentka Tandi?}
{147}{}{Díky za informace.}
{148}{dum17}{To je pøeci prezidentka NCR, kdo jinı? Musí mít opravdu velké starosti, protoe mì dokonce poádala o to, abych jí pùjèil jednoho ze svıch zástupcù na jednu speciální misi. Ale bohuel nemùu momentálnì nikoho postrádat, take jsem to musel velmi nerad odmítnout.}
{149}{}{A co tøeba já? Moná bys mì mohl doporuèit.}
{150}{}{Hmm. Koukám tìkı ivot.}
{151}{dum18}{Tebe? Hmmm... to by nešlo. Vdy tì ani neznám... ale je pravda, e nìkoho shání, take si s ní mùeš jít promluvit. Její kanceláø je v budovì Kongresu.}
{152}{}{Díky. Zastavím se tam.}
{153}{}{Nevíš nìco o vìci zvané GECK?}
{154}{dum19}{Hmm, to je od tebe sice zatracenì hezké, cizinèe, ale taky zatracenì drzé. Ani nevím, jestli vùbec pocházíš z Adama a Evy a navíc se mi ani trochu nelíbí tvùj pohled! Nikomu tì doporuèovat nebudu. A teï mám nìjakou práci.}
{155}{dum20}{No, zkus se zeptat Duppa ve Stockmanovì Asociaci. Najímá na brahmíní okruhy. A pak je tady pan Westin. Jestli s ním budeš mluvit, øekni mu, e tì posílám. A dokonce i prezidentka Tandi nìkoho hledá.}
{156}{dum21}{Duppo ve Stockmanovì Asociaci shání lidi na brahmíní okruhy. Zkus se ho zeptat.}
{157}{}{Westin?}
{158}{}{Prezidentka Tandi?}
{159}{}{Musím jít.}
{160}{dum22}{Roger Westin. Jeho pozemky se nacházejí v západní èásti mìsta. Má potíe s nìjakımi škùdci. Postaral by se o nì sám, jene jeho zdraví u není to co døív. Jak øíká doktor Jubilee, má špatné srdce.}
{161}{dum23}{Jo?}
{162}{}{Je v tomhle mìstì nìjaká práce?}
{163}{}{Zapomeò na to. U pùjdu.}
{164}{dum24}{Doufám, e to tak zùstane. Sbohem.}
{165}{dum25}{To byla zatracenì dobrá práce se starım Jackem, cizinèe, a protoe jsem šerif, tak to odteï pøebírám na starost.}
{166}{}{Je tvùj.}
{167}{}{Co takhle nìjaká odmìna?}
{168}{dum26}{No, bohuel pro tebe ádnou odmìnu nemám. Mùu ti jen podìkovat.}
{169}{}{Poèkej, mám ještì nìjaké otázky.}
{170}{}{Aha, rozumím. Tak dobøe.}
{171}{dum32}{Promiò, ale nemùu si s tebou teï povídat. U takhle pøijdu pozdì k soudnímu ohledání mrtvého, i kdy mi to pøijde celkem jasné.}
{172}{dum33}{Promiò, ale ádnı zloèin, ádnı viník.}
{173}{dum27}{Pouštní krysy jsou to. Pochop, e koøeny tohohle mìsta sahají a k Vaultu 15. Pøed dávnımi èasy se v nìm nejspíš vyskytl nìjakı problém a ti co pøeili, zaloili Shady Sands, take nám Vault 15 po právu patøí. Jene pøed nìkolika lety se tam nastìhovali nìjací squatteøi a zaèaly zase problémy. Nejlepší bude, kdy si o tom pùjdeš promluvit pøímo s Tandi.}
{174}{}{Tandi?}
{175}{}{Beru na vìdomí.}
{176}{dum28}{Nevím o ádné další práci.}
{177}{dum29}{Duppo ve Stockmanovì Asociaci shání lidi na brahmíní okruhy a prezidentka Tandi se shání po nìjakém šikovném èlovìku.}
{178}{dum30}{Kdokoliv jinı s tvou reputací by radìji opustil tohle mìsto, nato aby tady ještì hledal práci.}
{179}{dum31}{Duppo ve Stockmanovì Asociaci shání lidi na brahmíní okruhy. Zkus se ho zeptat. A pak je tady pan Westin. Jestli s ním budeš mluvit, øekni mu, e tì posílám.}
