{100}{}{Vidíš zamraèeného otrokáøe ve špinavém obleèení.}
{101}{}{Vidíš drsnì vypadajícího otrokáøe. Vypadá to, e tomu tady velí.}
{102}{}{Vidíš Dona, šéfa zdejšího tábora.}
{105}{don1}{Hej, co to má kurva znamenat?! Kdo sakra jseš?}
{106}{}{Jsem tvá nejhorší noèní mùra. Pøiprav se na smrt!}
{107}{}{Posílá mì Metzger.}
{108}{}{Chci se k vám pøidat.}
{109}{}{Eh, asi jsem na špatné adrese...}
{200}{don2}{Ty první, kreténe.}
{201}{don3}{Na tohle nemám èas. Na nì, hoši.}
{202}{}{Pøidat se k nám? Tohle není ádnı posranı náborovı centrum. Jestli se chceš pøidat k otrokáøùm, jdi do Denu a promluv si s Metzgerem. Potøebuješ teï ještì nìco, nebo mì chceš jenom nasrat?}
{203}{don5}{Metzger? (Trochu znejistí.) Neøíkej mi, e chce další otroky? No kurva, vdy jsme mu jednu várku pøed tejdnem poslali.}
{300}{}{Vlastnì ano, nìco ještì potøebuju.}
{301}{don6}{Take, proè tady jseš?}
{302}{}{Myslím, e u nic nepotøebuju.}
{303}{don7}{No tak odsud kurva vypadni. Nemáš tady co pohledávat a nejseš tu vítanej.}
{304}{}{Odcházím.}
{305}{}{Neboj, odejdu, ale nejdøív zabiju tebe i tvı kámoše.}
{307}{}{Ano, chce. Potøebuje se postarat o zábavu nìjakého vlivného èlovìka z New Rena, take chce nìkolik novıch dívek. Ale pokud nemùeš ádné postrádat... tak bude urèitì nadšenı, a pøijdu s prázdnou.}
{308}{don8}{(Na jeho potetovaném èele se objeví pot.) Hej, tak poèkat. Neøekl jsem, e nemùu ádnı postrádat. Tady si vezmi klíè od chatrèe, dríme tam naše, ehm, osobní favoritky. Dalo by se øíct, e je to vıbìr toho nejlepšího ze všeho toho odpadu. (Podá ti klíè a nervóznì se usmìje.)}
{309}{}{Díky. Pøimluvím se za tebe. Sbohem.}
{310}{don9}{Tak Metzger tì poslal, jo? Myslíš, e jsem slepej? Vdy na sobì nemáš ani naši posranou znaèku. Nevím, kdo jseš, ale podle mì pìknì kecáš a jen plejtváš mım èasem. A za to zemøeš. (Dává signál svım muùm.) Vyøídíme tohodle sráèe.}
{311}{don10}{Jo, jasnì. Podle mì kecáš a jen plejtváš mım èasem. A za to zemøeš. (Dává signál svım muùm.) Vyøídíme tohodle sráèe.}
{400}{don13}{Nemám èas. Jestli chceš na hon, jdi za Metzgerem do Denu.}
{450}{don11}{Neøekl jsem ti snad a vypadneš? Nemáme rádi vetøelce. Èas zemøít.}
{500}{}{[KONEC]}
{600}{don14}{Teï chcípneš!}
{601}{don15}{Chcípni, Rangerská špíno!}
{800}{don16}{Eh... pozdravuj ode mì Metzgera.}
{900}{}{Ne, ve skuteènosti mì sem poslal, a se podívám na tvoje zboí. Víš, mám ponìkud zvláštní poadavky, ale dobøe ti za to zaplatím.}
{901}{}{Hovno. Metzger sem ještì nikdy neposlal ádnıho zákazníka. Nevím, o co se tu snaíš, ale máš tøi sekundy na to, abys mi kurva zmizel z oèí, ne øeknu svejm hochùm, aby do tebe napumpovali olovo.}
