{100}{}{Vidíš velmi starého divocha.}
{101}{}{Vidíš náèelníka kmene.}
{102}{chief1}{(Starı mu kouøí dımku a dívá se na tebe svıma zakalenıma šedıma oèima, které jako by se snaily proniknout do tvé duše. Ukazuje ti, a se posadíš naproti nìmu do zakouøeného stanu.) Dìkuji ti za pøivedení Kurisu zpìt do naší vesnice. (Dlouze si popotáhne ze své dımky.) Duchové... o tobì hodnì povídají. Opravdu hodnì. Povìz mi, potøebuješ nìco?}
{103}{chief2}{(Starı mu kouøí dımku a dívá se na tebe svıma zakalenıma šedıma oèima, které jako by se snaily proniknout do tvé duše. Ukazuje ti, a se posadíš naproti nìmu do zakouøeného stanu.) Jsme velmi vdìèní za tvé sluby, poutníku. (Dlouze si popotáhne ze své dımky.) Duchové... o tobì hodnì povídají. Opravdu hodnì. Povìz mi, co tì pøivádí do naší vesnice?}
{104}{chief3}{Vítej zpìt, mé dítì. Potøebuješ ještì nìco?}
{105}{chief4}{Co pro tebe mùe staøík udìlat?}
{106}{}{Jsem na vıpravì za svatım GECKem. Nevíš o nìm nìco?}
{107}{}{Hledám ztracenou enu. Je to sestra mého pøítele Sulika.}
{108}{}{Je tu nìjaká práce?}
{109}{}{Ale nic. Nashle.}
{110}{chief5}{Svatı GECK... (Dlouze si popotáhne ze své dımky.) Jednoho takového tvora obèas lovíme... a obèas loví on nás. Geckon. Ne, myslím, e to není to, co hledáš. Obávám se, e tvùj svatı GECK je mimo mé chápání.}
{111}{}{Chci se ještì na nìco zeptat.}
{112}{}{To bude asi všechno. Nashle.}
{120}{chief6}{Sulik? (Kıvne.) Jeden z našich nejlepších muù. Zkušenı v umìní lovu a stejnì tak i v komunikaci s kostmi duchù. Vydal se hledat svou sestru Kurisu, která se doposud nevrátila z nedalekého kmene. Povìz mi, mé dítì, kde je Sulik teï?}
{121}{}{Je tady se mnou. Hej Suliku, pojï sem...}
{122}{}{Je v poøádku. Øekl jsem mu, a na mì poèká, dokud si nìco nezaøídím.}
{123}{}{Je mi líto, ale je mrtvı.}
{124}{chief7}{(Sulik a náèelník si vymìòují pozdravy.) Rád Sulika zase vidím. Kosti duchù mi øekli, e se dostal do nesnází. Co je s jeho sestrou Kurisu?}
{125}{}{Rád slyším, e je Sulik v poøádku. U jsme se obávali, e se dostal do nesnází. Take jeho sestra je stále nezvìstná? Je také èlenkou našeho kmene.}
{126}{chief9}{(Dlouze a potichu kouøí svoji dımku. Kdy u se chystáš odejít, tak koneènì promluví.) Sulik mìl silné duchy. Vdycky jsem si myslel, e mì jednoho dne nahradí, ale teï vidím, e s ním mìli duchové jiné plány. A co je s jeho sestrou Kurisu?}
{127}{}{Zajali ji otrokáøi. Nabídl jsem Sulikovi pomoc pøi hledání. Nevíš nìco, co by mi pomohlo ji najít?}
{128}{chief10}{(Zavøe na chvíli oèi. Kdy u si myslíš, e usnul, zaène mluvit.) Otrokáøe vede mu s temnou duší. Metzger. Pøebıvá v ruinách jednoho mìsta Starıch. Øíkají mu Den. (Otevøe oèi.) Moná ji tam drí. Kosti duchù u nic dalšího neøíkají.}
{129}{}{Díky. Chci se ještì na nìco zeptat.}
{130}{chief11}{Dìkuji ti, mé dítì, ale já jsem spokojenı. Je však moné, e ostatní ne. Poptej se po vesnici.}
{140}{}{Já hledat GECK.}
{141}{}{Já hledat chybìjící ena. Ona sestra kámoš Sulik.}
{142}{}{Èau.}
{150}{}{Já ptát víc.}
{160}{}{On pøímo tady. Sulik, náèerník chtít pokec.}
{161}{}{On dobrı. Èekat na já.}
{162}{}{Já promiò. On mrtvı.}
{170}{}{Ano, zlí lidé dostat ona. Já pomoct Sulik. Ty vìdìt, kde ona bıt?}
{200}{chief15}{Tvoje zlé èiny konèí zde, otrokáøi!}
{300}{chief12}{(Starı mu kouøí dımku a dívá se na tebe svıma zakalenıma šedıma oèima, které jako by se snaily proniknout do tvé duše. Ukazuje ti, a se posadíš naproti nìmu do zakouøeného stanu.) Dobrá práce, mé dítì. Slyším køiky mnoha høíšnıch kostí duchù, které se ztratily ve Velkém Slaném Jezeøe. Teï, kdy se ti podaøilo prokázat své kvality, ti u mùu sdìlit poslední veliké tajemství.}
{301}{}{Skvìlé, koneènì! Poslouchám.}
{302}{}{Nemám zájem, staøíku. Nashle.}
{310}{chief13}{(Silnì si popotáhne ze své dımky a poté zavøe oèi. Po chvíli kıvne.) Ano. Vidím, e tì duch Velkého Medvìda doprovázel na tvé vıpravì a vdechl novı ivot starım kostem. Ostatním také. Moná tì navštívili v nìjaké vizi. Pochází z pøedaleké gal... kam mají mutanti vstup zakázán.}
{311}{}{O èem to sakra mluvíš?}
{312}{}{Jo jo, u se mi podaøilo objevit náhodné setkání se Star Wars. Neøíkej mi, e to je to poslední veliké tajemství.}
{320}{chief14}{Poslední tajemství... nejvìtší tajemství celé této hry... je... (Popotáhne si ze své dımky bìhem dramatické pauzy, kdy mu najednou vyklouzne z ruky a spadne pøímo na jeho róbu, která se okamitì vznítí a zachvátí staøíka plameny.)}
{321}{}{Kurva!}
