{100}{}{Vidíš váleèníka.}
{101}{}{Vidíš Kroma, vrchního váleèníka tohoto kmene.}
{102}{}{Vidíš obrovského svalnatého váleèníka. Na jeho bronzové kùi jsou jizvy po nespoèetném mnoství bitev.}
{200}{krom1}{(Svaly tohoto opáleného obra vypadají, jako by byly vytesány z uly. Pod jeho èernou høívou se ukrıvají uhranèivé modré oèi, které se na tebe dívají pronikavım pohledem.) Jsem Krom, vrchní váleèník tohoto kmene. Kdo jsi a co tì sem pøivádí?}
{201}{krom2}{(Svaly tohoto opáleného obra vypadají, jako by byly vytesány z uly. Pod jeho èernou høívou se ukrıvají uhranèivé modré oèi, které se na tebe dívají pronikavım pohledem.) Jsem Krom, vrchní váleèník tohoto kmene. U sta hromù, holka, tvoje krása by dokázala pobláznit kdejakého mue.}
{202}{}{Jsem }
{203}{}{ a jsem na svaté vıpravì za záchranou své vesnice, Arroyo, pøed jistım znièením.}
{204}{}{Jsem }
{205}{}{ a mım posláním bylo záchranit svoji vesnici, Arroyo, pøed jistım znièením. U se mi ale všechno potøebné podaøilo najít.}
{206}{}{Jsem jen prostı poutník, nic víc. U pùjdu.}
{207}{}{[Usmát se] Dìkuju ti, Krome.}
{208}{}{Díky, ale co kdyby ses mi zaèal dívat do oèí. Rozumíš, svalovèe?}
{209}{}{Nech si ty komplimenty, ty úchyle, jasnı? Nechci se s tebou vyspat. Vlastnì s tebou nechci ani mluvit. Nashle.}
{210}{krom3}{Á, Arroyo, jeden ze severních kmenù. Ale proè mluvíš o "jistém znièení"? Tvoje vesnice je pøece dobøe chránìna velkım kaòonem nebo ne? Urèitì se dokáete ubránit nepøátelskım kmenùm i nájezdníkùm.}
{211}{}{Nikdo zvenèí nás neohrouje. Mùj kmen umírá zevnitø. Zaili jsme hrozivé sucho a zdá se, e je moje vesnice odsouzena k zániku, pokud vèas nenajdu svatı GECK.}
{212}{}{Nikdo zvenèí nás neohrouje. Mùj kmen umírá zevnitø. Zaili jsme hrozivé sucho a zdá se, e je moje vesnice odsouzena k zániku, pokud nepouiju GECK, kterı se mi podaøilo najít.}
{220}{krom4}{Á, GECK, èetl jsem o nìm ve starıch textech. (Pochmurnì se usmìje.) Je opravdu neštìstí, e tvùj kmen proívá tìké období, ale bylo by pošetilé vkládat veškerou nadìji do nìjakého "magického artefaktu" z doby pøed Velkım Tichem. Víš urèitì, e tì tvùj kmen neposlal na takovı nesplnitelnı úkol jen proto, aby se tì zbavil?}
{221}{krom5}{Á, GECK, èetl jsem o nich ve starıch textech. (Pochmurnì se usmìje.) Je opravdu neštìstí, e tvùj kmen proívá tìké období, ale bylo by pošetilé vkládat veškerou nadìji do nìjakého "magického artefaktu" z doby pøed Velkım Tichem. Jak víš, e to zaøízení zachrání tvùj lid?}
{222}{}{Vím to jistì. Úspìšnì se mi podaøilo projít Chrámem Zkoušek a získat tak vysoce respektovanı titul Vyvolenı. A pøesnì proto mi dali tenhle úkol, protoe jsem prokázal, e k tomu mám nejlepší pøedpoklady. Co ses doèetl o GECKu?}
{223}{}{Chceš mì snad urazit? Mìl bys vìdìt, e já jsem Vyvolenı. Omluv se, nebo ti ukáu.}
{224}{}{Jistì to nevím, ale u jsem kvùli tomu riskoval a a. Udìlám cokoliv pro záchranu svého kmene, a u to bude jakkoliv šílené nebo nebezpeèné.}
{230}{krom6}{(Pohrdavì pokrèí svımi mocnımi rameny.) Jen samé vìdecké bláboly Starších, které mají nahradit starı dobrı souboj tìce pracujícího èlovìka proti nemilosrdné Zemi bojujícího o svou vlastní existenci potem a krví. Ale pokud opravdu vìøíš, e je to zaøízení vaše jediná nadìje, pak ti doporuèuju vyhledat podzemní Vaulty Starších. Procestoval jsem celou zemi køíem kráem, ale nikdy jsem ádnı nenašel. Na druhou stranu, ani jsem je nehledal.}
{231}{}{Starší mého kmene si je jistá, e je nalezení GECKu naší nejvìtší šancí a pøesnì to mám za úkol a pøesnì to se chystám udìlat. Nicménì díky za radu.}
{232}{}{Øíkáš najít Vault? Páni, tomu øíkám opravdu *skvìlá* rada, proè jsem to jen nevìdìl døív? Díky moc za radu, svalovèe.}
{240}{krom7}{(Srdeènì se zasmìje a poté pozvedne své kopí a zaujme bojovı postoj s takovou rychlostí, která se nesluèuje s jeho impozantními rozmìry.) Tak Vyvolenı, jo? Vyvolenı k èemu, vládnout ukòouranım psùm? Jestli ty jseš to nejlepší, co mùe tvùj kmen nabídnout, tak je jejich osud zpeèetìn. A teï pozvedni svoji zbraò, nebo se mi kliï z oèí.}
{241}{krom8}{(Srdeènì se zasmìje a poté tì laškovnì plácne pøes zadek svojí rukou, která by dokázala rozbíjet kameny.) Máš v sobì jiskru, holka, a to se mi líbí. Tøeba bychom toho mohli vyuít, kdy u tu jseš. Co øíkáš?}
{242}{}{Dobøe, fajn,. Odcházím.}
{243}{}{Mì nikdo vyhroovat nebude, kreténe!}
{244}{}{K èertu s tebou. Odcházím. Sbohem.}
{245}{}{Mì se nikdo dotıkat nebude, kreténe! [Zaútoèit]}
{246}{}{Pokud se budeš dotıkat jenom sebe, tak ti *moná* pomùu.}
{247}{}{Záleí jak. [Svùdnì se usmát] Co máš na mysli, svalovèe? [Mrknout]}
{250}{krom9}{Sarkasmus mi není cizí. Ty svoje chytré øeèi si zkoušej na nìkoho jiného, nebo ti vyrvu jazyk z pusy.}
{251}{}{Dobøe, fajn,. Odcházím.}
{252}{}{Mì nikdo vyhroovat nebude, kreténe!}
{260}{krom10}{Jsi tvrdohlavı. U sta hromù, myslím, e tì budu mít nakonec rád. (Ušklíbne se a poté tì poplácá po zádech svojí rukou, která by dokázala rozbíjet kameny.) Kdy u jseš tady, moná bys nám mohl s nìèím pomoct. Co øíkáš?}
{261}{krom11}{Jsi tvrdohlavá. U sta hromù, myslím, e tì budu mít nakonec rád, holka. (Ušklíbne se a poté tì plácne pøes zadek svojí rukou, která by dokázala rozbíjet kameny.) Kdy u jseš tady, moná bys nám mohla s nìèím pomoct. Co øíkáš?}
{262}{}{Jistì, myslím, e bych ti mohla s nìèím pomoct. Co chceš, abych udìlala?}
{263}{}{Promiò, ale nemám èas. Vlastnì bych u mìla jít. Nashle.}
{264}{}{Jistì, myslím, e bych ti mohla s nìèím pomoct. Co chceš, abych udìlala?}
{265}{}{Pokud se budeš dotıkat jenom sebe, tak ti *moná* pomùu.}
{266}{}{Promiò, ale nemám èas. Vlastnì bych u mìla jít. Nashle.}
{267}{}{Mì se nikdo dotıkat nebude, kreténe! [Zaútoèit]}
{268}{}{Záleí jak. [Svùdnì se usmát] Co máš na mysli, svalovèe? [Mrknout]}
{270}{krom12}{(Chlípnì se ušklíbne. Je pøirozenì atraktivní, navzdory svému zjizvenému a drsnému vzhledu.) Povìz, holka, jak se jmenuješ a co tì pøivádí do naší vesnice?}
{280}{krom13}{Rád. (Podívá se ti do oèí a chlípnì se ušklíbne. Je pøirozenì atraktivní navzdory svému zjizvenému a drsnému vzhledu.) Povìz, holka, jak se jmenuješ a co tì pøivádí do naší vesnice?}
{290}{}{(Krom se na tebe chlípnì ušklíbne a poté tì vezme do svıch silnıch paí.)}
{291}{}{[Poddat se mu]}
{292}{}{Hej! Nech mì bıt, tak jsem to nemyslela!}
{300}{krom14}{K èertu s tebou, svùdnice! Bì si škádlit nìkoho jiného. Nebudu s tebou ztrácet èas.}
{301}{}{Jo, taky jdi do prdele. Nashle.}
{302}{}{Nevadí. Nashle.}
{310}{krom15}{(Ubìhlo nìkolik hodin zahalenıch do vyèerpávající a brutální vášnì. Nakonec si zcela vyèerpaná lehneš na podlahu Kromovy chıše. Krom leí vedle tebe a zírá na køivky tvého tìla.) U sta hromù, holka, jsi úasná!}
{311}{}{Díky. Ty taky nejsi nejhorší.}
{312}{}{Samozøejmì, e jsem. Jsem pøeci Vyvolená.}
{320}{krom16}{(Krom se na tebe podivnì ušklíbne.) Bohové vìdí, e jseš pro mì poklad, holka, ale nechtìla bys vyjít vstøíc i zbytku mého kmene?}
{321}{}{Jistì, myslím, e bych ti mohla s nìèím pomoct. Co chceš, abych udìlala?}
{322}{}{Ráda bych ti pomohla, ale u opravdu musím jít. Promiò.}
{323}{}{Chceš, abych ošukala i zbytek kmene? Kdo si myslíš, e jsem?}
{330}{krom17}{(Krom vyprskne smíchy.) Boe to ne, holka! Sice by to asi udìlalo s morálkou mıch váleèníkù divy, ale nerad bych se dìlil o takovı poklad, jako jseš ty. Ne, mám pro tebe mnohem dùleitìjší úkol, pokud máš zájem.}
{331}{}{Záleí na tom, o co jde. Co chceš, abych udìlala?}
{340}{krom18}{(Pozornì si tì prohlédne, jako by na moment nad nìèím uvaoval.) Mám se brzy setkat s jedním z tìch zatracenıch civilizovanıch obchodníkù. Je to zavalitı jednookı psanec, kterému vìøím asi tak jako hladovìjícímu radškorpionovi. Zatím nás sice nepodrazil, ale mám pocit, e se nìco stane na našem dalším setkání.}
{341}{}{K èemu?}
{342}{}{Nechápu, jak to souvisí se mnou. Kam tím smìøuješ?}
{350}{krom19}{Kdy jsme spolu poslednì mluvili, chlubil se, e mi pøiveze nìco opravdu zázraèného a e bych mìl pøinést všechny kùe zlatého geckona, které unesu. Nevím, co je to za zázraènou vìc, ale nejspíš je to nìjaká civilizovaná cetka, za kterou budu ochotnı nevìdomì zaplatit víc, ne jakou má doopravdy cenu. A proto bude nejlepší, kdy se o ten obchod postaráš ty.}
{351}{}{Proè já?}
{352}{}{Promiò, ale musím odmítnout. Nashle.}
{360}{krom20}{Protoe jsi mùj druh. Divoch, jak nám øíkají, ale i pøesto jsem poznal, e máš za sebou nedávnou zkušenost s civilizovanım svìtem. Pokud se o nìco pokusí, všimneš si toho spíš ty ne já. A navíc mám z tebe dobrı pocit a já vím, e mùu vìøit svım instinktùm.}
{361}{krom21}{Protoe jsi mùj druh. Divoška, jak nám øíkají, ale i pøesto jsem poznal, e máš za sebou nedávnou zkušenost s civilizovanım svìtem. Pokud se o nìco pokusí, všimneš si toho spíš ty ne já. A navíc mám z tebe dobrı pocit, holka, a já vím, e mùu vìøit svım instinktùm.}
{362}{}{Dobøe. Pojïme na to.}
{363}{}{Dobøe, ale musím se ještì pøipravit.}
{364}{}{A co z toho budu mít kdy ti pomùu?}
{370}{krom22}{(Usmìje se.) Nabízím ti pohostinnost našeho kmene a pøíleitost ohromit mì. Nic víc neslibuju.}
{371}{}{Dobøe. Pojïme na to.}
{372}{}{Dobøe, ale musím se ještì pøipravit.}
{373}{}{Nemám zájem. Nashle.}
{375}{krom23}{Mùeme jít?}
{376}{}{Ještì ne.}
{377}{}{Dobøe. Pojïme na to.}
{380}{krom61}{Rozhodnutí je na tobì.}
{390}{krom24}{(Krom si prohlíí jeden z koupenıch Stimpakù.) Tyhle se budou hodit. (Pøiloí si ho k nosu, pøièichne, a zamraèí se. Trochu rudé tekutiny si støíkne na ruku a ochutná ji.) Krucipísek! Jsou naplnìné brahmíní krví! Ten jednookej hajzl nás ojebal. Teï se nám nejspíš pìknì smìje a libuje si nad svımi novımi zlatımi kùemi.}
{391}{}{To je mi moc líto. Zdály se bıt v poøádku.}
{392}{}{Co u. Chybama se èlovìk uèí.}
{400}{krom25}{Jestli ještì nìkdy potkám toho podvodníka, tak mu s radostí rozpùlím tu jeho hnusnou lebku. A teï kdy mì omluvíš, musím se jít zbavit nìkolika ampulek s brahmíní krví. Moná by je vyuil šaman.}
{410}{krom26}{Sice mi byl ten hnusnı bastard lhostejnı, ale já ho proboha nechtìl zavradit. Jistì, mùeme si teï vzít jeho zboí zadarmo, ale jestli se nìkdo dozví, e k nám pøišel obchodovat a u se nevrátil, tak se nám budou všichni obchodníci vyhıbat.}
{411}{krom27}{Sice mi byl ten hnusnı bastard lhostejnı, ale já ho proboha nechtìl zavradit, holka. Jistì, mùeme si teï vzít jeho zboí zadarmo, ale jestli se nìkdo dozví, e k nám pøišel obchodovat a u se nevrátil, tak se nám budou všichni obchodníci vyhıbat.}
{412}{}{Promiò, asi to nebylo moc rozváné.}
{413}{}{Byl to pìknej hajzl a zaslouil si zemøít.}
{414}{}{A sakra.}
{420}{krom28}{Vidím, e to byla chyba svìøit ti tenhle úkol. Budu na tebe dávat pozor, kdy budeš ve vesnici. A teï pojï, postaráme se o ten nepoøádek a pùjdeme si kadı po svém.}
{430}{krom29}{Ten prolhanı bastard si to zaslouil. Jeho osud poslouí jako varování pro ostatní obchodníky, kteøí si usmyslí nás podvést. Dobrá práce pøi odhalování podvodu. Vidím, e jsem udìlal dobøe, kdy jsem ti vìøil. Vítej mezi námi a chovej se tu jako doma. Nicménì je moné, e budu èasem opìt potøebovat tvoji pomoc. A teï pojï, necháme ty mrtvoly hnít na slunci.}
{431}{krom30}{Ten prolhanı bastard si to zaslouil. Jeho osud poslouí jako varování pro ostatní obchodníky, kteøí si usmyslí nás podvést. Dobrá práce pøi odhalování podvodu. Krásná, bystrá a smrtící. Hrome, holka, jsi dokonalá. Vítej mezi námi a chovej se tu jako doma. Nicménì je moné, e budu èasem opìt potøebovat tvoji pomoc. A teï pojï, necháme ty mrtvoly hnít na slunci.}
{440}{krom31}{Nemám ti za zlé, e jsi neuskuteènil ten obchod. Taky jsem z toho nemìl nejlepší pocit. Pøiznávám, e by se ty Stimpaky hodily, ale doteï jsme si poradili i bez nich, take v tom budeme pokraèovat. Vítej mezi námi a chovej se tu jako doma. Nicménì je moné, e budu èasem opìt potøebovat tvoji pomoc. Díky za všechno.}
{441}{krom32}{Nemám ti za zlé, e jsi neuskuteènila ten obchod. Taky jsem z toho nemìl nejlepší pocit. Pøiznávám, e by se ty Stimpaky hodily, ale doteï jsme si poradili i bez nich, take v tom budeme pokraèovat. Vítej mezi námi, holka, a chovej se tu jako doma. Nicménì je moné, e budu èasem opìt potøebovat tvoji pomoc. Díky za všechno.}
{442}{}{ádnı problém.}
{443}{}{Rádo se stalo.}
{444}{}{Nevadí. Nashle.}
{450}{krom33}{Jestli ještì nìkdy potkám toho podvodníka, tak mu s radostí rozpùlím tu jeho hnusnou lebku. Dobrá práce pøi odhalování podvodu. Vidím, e jsem udìlal dobøe, kdy jsem ti vìøil. Vítej mezi námi a chovej se tu jako doma. Nicménì je moné, e budu èasem opìt potøebovat tvoji pomoc. Díky za všechno.}
{451}{krom34}{Jestli ještì nìkdy potkám toho podvodníka, tak mu s radostí rozpùlím tu jeho hnusnou lebku. Dobrá práce pøi odhalování podvodu. Vidím, e jsem udìlal dobøe, kdy jsem ti vìøil, holka. Vítej mezi námi a chovej se tu jako doma. Nicménì je moné, e budu èasem opìt potøebovat tvoji pomoc. Díky za všechno.}
{452}{}{ádnı problém.}
{453}{}{Rádo se stalo.}
{454}{}{Nevadí. Nashle.}
{460}{krom35}{(Obøí váleèník kıvne hlavou na pozdrav.) Vítej zpìt, pøíteli. Potøebuješ nìco?}
{461}{krom36}{(Obøí váleèník se ušklíbne, kdy se k nìmu pøiblííš.) U sta hromù, u jsem témìø zapomnìl, jak jsi pøekrásná. Potøebuješ nìco, holka?}
{462}{}{Mùu se tì na nìco zeptat?}
{463}{}{Ne, promiò, asi jsem ve špatném stanu. U pùjdu.}
{464}{}{[Svùdnì se usmát] Jo, svalovèe. Nìco bych potøebovala. [Mrknout]}
{470}{krom37}{Samozøejmì.}
{471}{}{Zdá se, e u jsi toho hodnì zail. Jakı je tvùj ivotní pøíbìh?}
{472}{}{Co mi mùeš øíct o téhle vesnici?}
{473}{}{Mùu ti s nìèím pomoct?}
{474}{}{Hmm, to je divné. U ani nevím, na co se chci vlastnì zeptat. Zastavím se pozdìji, pokud si vzpomenu. Nashle.}
{480}{krom38}{(Usmìje se.) Ano, myslím, e u jsem toho zail hodnì. Pocházím z kmene daleko na severu. Kdy mi bylo patnáct, pøepadli nás barbaøi. Toho dne jsem se probudil jako chlapec a šel spát jako mu. Kadı mu, ena, i dítì byli kromì mì mrtví. Ale co by to bylo za ivot, kdyby nebylo hádek a bojù? Buï tì to zlomí, nebo tì to zocelí. Svoje jizvy nosím s pıchou.}
{481}{}{Co jsi udìlal potom?}
{482}{}{Dobrá, to u by staèilo. Chci se ještì na nìco zeptat.}
{490}{krom39}{Navršil jsem mrtvoly na hromadu a sledoval, jak hoøí do noci. Pak jsem sbalil všechno, co jsem dokázal pobrat, a šel se toulat. Strávil jsem nìjakou dobu s nìkolika kmeny a bojoval v mnoha bitvách. Nìjakı èas jsem pobyl i mezi "civilizovanımi" lidmi, ale to mì rychle omrzelo. Je mezi nimi pøíliš mnoho neèestnıch psù schovávajících se za svımi zbranìmi. Mám radìji, kdy se bojuje pìstmi a kovem. Nejsem nároènı mu. Staèí mi bitvy, hostiny, víno a eny. Co jiného by mì mìlo zajímat na tomhle krutém svìtì?}
{491}{}{A jak jsi skonèil tady?}
{500}{krom40}{Pøišel jsem sem pøed nìkolika lety. Tenhle kmen mì vzal mezi sebe a dobøe se ke mnì choval. Nabídli mi pozici vrchního váleèníka, kterou jsem samozøejmì pøijal. Líbí se mi u Velké Slané Vody, ale cítím, jak ve mnì roste touha po cestování. Vìøím, e u brzo odejdu, abych zjistil, co si pro mì bohové zase pøichystají.}
{501}{}{Díky za pøíbìh. Mùu se ještì na nìco zeptat?}
{502}{}{Díky za pøíbìh. Nashle.}
{510}{krom41}{Hmmm... vìtšina pøíslušníkù téhle vesnice ve skuteènosti pochází ze tøí menších kmenù, které se rozhodly spojit pøed mnoha lety, aby zvıšily své šance na pøeití. Díky tomu vznikl zajímavı mix zvykù a náøeèí. Ale co je dùleitìjší, díky tomu tu máme zajímavé eny. Jinak není o èem mluvit. Je to prostá vesnice, která bojuje o svoje pøeití.}
{511}{}{Dobøe, díky. Mùu se ještì na nìco zeptat?}
{512}{}{Dobøe, díky. Nashle.}
{520}{krom42}{Zdá se, e má Marli nìjaké potíe se studnou. Jestli chceš pomoct, jdi za ním a zeptej se ho, v èem je problém.}
{521}{}{Dobøe, díky. Nashle.}
{522}{}{Dobøe, moná se ho zeptám, ale nejdøív se chci na nìco zeptat tebe.}
{530}{krom43}{Rád tì vidím, pøíteli. Hodila by se mi nìjaká pomoc, a budeš mít èas.}
{531}{krom44}{Rád tì vidím, holka. Hodila by se mi nìjaká pomoc, a budeš mít èas.}
{532}{}{Jistì. Co potøebuješ?}
{533}{}{Promiò, mám práci. Moná pozdìji.}
{540}{krom45}{Dva lovci, Serin a Jerem, se ještì nevrátili z lovištì a nìkteøí lidé zaèínají mít obavy. Jsou to naši dva nejlepší váleèníci a nechce se mi ani pomyslet na to, e se jim nìco stalo. Šel bych je hledat sám, ale kdyby lidé spatøili, e jsem se za nimi vydal, pøedpokládali by jen to nejhorší. Radìji je nebudu drádit, dokud nevím, co se dìje. Take, podíváš se po nich?}
{541}{}{Dobøe, kde mám hledat?}
{542}{}{Promiò, ale nemám èas je hledat. Urèitì se brzy objeví. Nashle.}
{543}{}{Nejsem tvùj sluha. Nashle.}
{550}{krom46}{Jdi se podívat na lovištì na severu. Nejrychlejší cesta vede skrz jeskyni na západì, kousek od Velké Slané Vody. Normálnì bych ti tu cestu nedoporuèil, jeliko tam hrozí nebezpeèí zøícení, ale tady jde o èas. Staèí, kdy budeš v té jeskyni dávat pozor kam šlapeš a nic se ti nestane.}
{551}{}{Dobøe, pokusím se je co nejrychleji najít.}
{552}{}{Poèkat, mám projít jeskyní, která se mùe zøítit? Hmm... do prdele, na nìco si teï vzpomínám! Musím zachránit svoji vesnici! Promiò, musím bìet.}
{560}{krom47}{Máš nìjaké novinky o tìch ztracenıch lovcích?}
{561}{}{Zatím ne. Budu pokraèovat v hledání.}
{562}{}{Jo, byli v té jeskyni. Jsou oba mrtví.}
{570}{krom48}{(Krom pøikıvne a jeho oblièej zesmutní.) Jak zemøeli?}
{571}{}{Došlo k závalu. Jednoho rozdrtily padající kameny a druhého zasypal štìrk a poté ho zaiva seral geckon. Bylo to pìknì kruté.}
{580}{krom49}{Zemøeli pod blbım závalem? Proklínám bohy! Nesnáším, kdy ztratím dobré mue takovım zpùsobem. Mìli zemøít v boji jako opravdoví váleèníci. (Zakroutí hlavou.) Jejich ztráta poznamená tenhle kmen. Nicménì ti dìkuju za slubu. U tì nebudu potøebovat.}
{581}{}{Jistì, kdykoliv. Nashle.}
{582}{}{Urèitì to byli dobøí mui. Nashle.}
{590}{krom50}{Dìkuju ti za nalezení tìch lovcù. Ztráta Jerema je velká, byl to zkušenı váleèník. Mìl zemøít v boji a ne pod nìjakım blbım závalem. Nicménì Serin by se mìl díky tobì uzdravit, pøíteli. Jsi tu vdy vítán.}
{591}{krom51}{Dìkuju ti za nalezení tìch lovcù. Ztráta Jerema je velká, byl to zkušenı váleèník. Mìl zemøít v boji a ne pod nìjakım blbım závalem. Nicménì Serin by se mìl díky tobì uzdravit, holka. Jsi tu vdy vítána.}
{592}{}{Díky. Mìj se, Krome.}
{800}{}{Moje kmen, Arroyo, potøebovat pomoc. Já pomoct. Já zvláštní vybranı pomocník.}
{801}{krom52}{(Krom se zasmìje.) Jo, jsi rozhodnì zvláštní. (Usmìje se a proèechrá ti vlasy rukou, která by dokázala rozbíjet kameny.) Rád pomáháš, jo? Jak by se ti líbilo bıt naším zvláštním pomocníkem?}
{802}{}{Já pomoct! Co ty potøebovat?}
{803}{}{Ne-e. Já pomoct Arroyo. Nemít èas pomoct jinım. Ahooj!}
{810}{krom53}{Potøebujeme špièaté zbranì. (Ukáe na své kopí.) Pìt takovıhlech kopí. (Ukáe na prstech.) *Pìt*. Dále potøebujeme *deset*, to je dvakrát tolik, noù. (Vytáhne nù a ukáe ti ho.) Jako je tenhle, jasnı? Pìt kopí, nezáleí na tom jak ostrıch, a deset bìnıch noù. Chápeš?}
{811}{}{Dobe. Já jít hledat špièatá vìci.}
{812}{}{Já mít spousta špièatá vìci. Já je všechny nepotøebovat.}
{820}{krom54}{Rozmyslel sis to? Chceš bıt naším zvláštním pomocníkem?}
{821}{}{Já zvláštní. Já bıt velkı pomocník pro kmen.}
{830}{krom55}{U máš všechny ty špièaté vìci, o které jsem tì poádal?}
{831}{}{Já najít.}
{832}{}{Já poøád hledat.}
{840}{krom56}{(Krom rychle prohlédne zbranì, poté se usmìje a poplácá tì po zádech.) Dobrá práce. Dìkuju ti. Teï bì a do nièeho se nemíchej.}
{841}{}{Èau!}
{850}{krom57}{(Krom ti proèechrá vlasy.) Á, to je mùj zvláštní pomocník. Teï bì a do nièeho se nemíchej.}
{851}{}{Èau!}
{860}{krom58}{Pokoušíš své štìstí, e jo?}
{861}{}{Ne, jdu ti nakopat prdel.}
{862}{}{Ne, chci se ti jen omluvit za tu uráku.}
{863}{}{Ne, zrovna odcházím.}
{870}{krom59}{Hmm, zdá se, e mám dnes odpouštìcí náladu, pøíteli. Co pro tebe mùu udìlat?}
{871}{krom60}{Nemám rád, kdy si se mnou zahrává ena, ale u sta hromù, jak mùu bıt naštvanı na takovou bohyni, jako jsi ty? Co pro tebe mùu udìlat?}
{872}{}{Ale nic. Nashle.}
{1000}{krom63}{(Obøí váleèník na tebe s úctou kıvne.) A hele, jestlipak to není náš velkı hrdina pustin. To byl velmi pùsobivı vıkon poslat ty Enklávské psy k èertu takovım zpùsobem. Vlastnì mì tvoje hrdinské èiny inspirovaly k tomu, abych se vrátil zpìt do pustin.}
{1001}{}{Kam pùjdeš?}
{1002}{}{Ty chceš odejít jen tak? Ale vdy jsi vrchní váleèník tohohle kmene.}
{1003}{}{Dobøe. Hodnì štìstí na cestách, Krome.}
{1010}{krom64}{(Pokrèí svımi širokımi rameny.) Vıchod nezní tak úplnì špatnì. Jo, myslím, e pùjdu na vıchod a uvidím, co mì tam èeká.}
{1020}{krom65}{Moji pozici brzo nahradí nìjakı jinı váleèník. Vrchní váleèníci stejnì vìtšinou neijou víc ne nìkolik let, take myslím, e si odpoèinek zaslouím.}
{2000}{}{Podaøilo se ti sehnat víc zbraní pro kmen.}
{2500}{}{Naletìl jsi na Royùv podvod.}
{2501}{}{Zbyteènì jsi zabil obchodníka.}
{2502}{}{Podaøilo se ti odhalit Royùv podvod a postarat se o to, e u nikdy nebude obchodovat.}
{2503}{}{Odmítl jsi obchodovat s Royem.}
{2504}{}{Podaøilo se ti odhalit Royùv podvod.}
{3000}{krom62}{Táhni, nièemnı otrokáøi!}
