{100}{}{Vidíš Amandu.}
{101}{}{Vidíš unavenì vypadající enu. Zdá se, e nedávno plakala.}
{102}{}{Vidíš Amandu.}
{103}{}{Vidíš unavenì vypadající enu. Zdá se, e nedávno plakala.}
{104}{}{Vidíš Amandu. Teï, kdy je Joshua volnı, vypadá mnohem šastnìji.}
{105}{}{Vidíš Amandu.}
{106}{}{Vidíš Amandu. Teï, kdy je Joshua volnı, vypadá mnohem šastnìji.}
{107}{ama11}{Ach, mùj Joshuo...}
{108}{ama12}{Co si mám poèít?}
{109}{ama13}{Všechny peníze u mi došly...}
{110}{ama14}{Kdyby ho tak Obèané nechali jít...}
{111}{ama15}{Joshuo, jsem tak šastná, e jsi volnı. Tolik jsem se bála...}
{112}{ama16}{Promiò, nemám nic, co bych ti mohla dát.}
{113}{ama17}{Prosím, nech mì bıt, nebo zavolám stráe.}
{114}{ama1}{Co chceš?}
{115}{}{Jsi v poøádku? Vypadáš rozèilenì.}
{116}{}{No nic. Promiò, e ruším.}
{117}{ama2}{Já... no, mùj... jde o mého manela Joshuu. On... dostal se do potíí v... baru. Nechtìnì udeøil Obèana a oni ho zavøeli. On to tak nemyslel, ale byl opilı a...}
{118}{}{Oni ho zavøeli? A kde je teï?}
{119}{}{Pokud se opil a nìkoho napadl, tak je ve vìzení právem.}
{120}{}{To je mi moc líto. Doufám, e ho brzy propustí.}
{121}{ama3}{Ve mìstì, v Centru rozdìlování sluebníkù... øíkají, e si svùj trest mùe odpracovat jako sluebník, ale to mùe trvat roky!}
{122}{}{Nedalo by se s tím nìco udìlat?}
{123}{}{Pokud se opil a nìkoho napadl, tak je ve vìzení právem.}
{124}{}{To je mi moc líto. Doufám, e ho brzy propustí.}
{125}{ama4}{Ale to byla nehoda! Já... on to urèitì nechtìl udìlat!}
{126}{}{Kde je teï?}
{127}{}{Nechtìl nikoho napadnout? To urèitì. Snad to pro vás oba bude dobrá lekce.}
{128}{}{To je mi moc líto. Doufám, e ho brzy propustí.}
{129}{ama5}{Moc penìz mi nezbylo a kdy nebudeme mít na zaplacení ochrany, budeme muset brzy odejít. Øíkají, e pokud tu budeme chtít s Joshuou zùstat, tak jen jako sluebníci...}
{130}{}{To zní jako rozumné øešení. Ve Vault City se chovají ke sluebníkùm pomìrnì slušnì nebo ne?}
{131}{}{Zkusím zjistit, jestli by se s tím nìco nedalo udìlat, ano? Zkusím promluvit s nìkım v Centru rozdìlovaní sluebníkù.}
{132}{}{Pomùu ti, ale bude tì to nìco stát.}
{133}{}{To je mi moc líto. Doufám, e ho brzy propustí.}
{134}{ama6}{Nechci, aby mùj syn vyrùstal jako otrok! Pøišli jsme do Vault City, protoe jsme slyšeli, e je to svobodné mìsto... ale kdy jsme pøišli... samé zákony, naøízení, placení stráí... všechno je jinak, ne nám tvrdili.}
{135}{}{Zkusím zjistit, jestli by se s tím nìco nedalo udìlat, ano? Zkusím promluvit s nìkım v Centru rozdìlovaní sluebníkù.}
{136}{}{To je mi moc líto. Doufám, e ho brzy propustí.}
{137}{ama7}{Má to tam na starosti Barkus, úøedník Barkus. Nemohla jsem se ani dostat do mìsta, abych s ním promluvila. Ani nevím, jestli je Joshua vùbec v poøádku! Já...}
{138}{}{Nemìj strach. Zkusím zjistit, jestli se s tím nìco nedá udìlat.}
{139}{ama8}{Ale já nemám skoro ádné peníze a...}
{140}{}{Nemám jsem na mysli peníze.}
{141}{}{To nic. Zkusím promluvit s nìkım v Centru rozdìlovaní sluebníkù.}
{142}{}{To je mi moc líto, vánì. Doufám, e ho brzy propustí. Sbohem.}
{143}{ama9}{Co tím myslíš...? Ach ne. To... nejde. Já.. ne...}
{144}{}{Chceš, aby manela pustili nebo ne? On se to nikdy nemusí dozvìdìt.}
{145}{}{To nic. Zkusím promluvit s nìkım v Centru rozdìlovaní sluebníkù.}
{146}{}{To je mi moc líto. Vypadá to, e tvùj manel u se nikdy na svobodu nedostane. Sbohem.}
{147}{ama10}{Kdy slíbíš, e ho osvobodí, já... já... dobøe. Já... zavøu vchod stanu. Myslím, e si syn hraje venku,take by nás tu nemìl rušit.}
{148}{}{Bez obav, tvého mue osvobodím. A dostanu svoji odmìnu.}
{149}{}{Zapomeò na to. Zkusím promluvit s nìkım v Centru rozdìlovaní sluebníkù.}
{150}{}{Kašli na to. Zapomeò, e jsme se potkali.}
{151}{}{Hej, a co já?!}
{152}{ama18}{Prosím, zachraò Joshuu. Je ve mìstì ve Centru rozdìlování sluebníkù.}
{153}{ama19}{Díky za záchranu mého mue! Prosím... pøijmi toto jako odmìnu. Není to moc, ale...}
{154}{ama20}{Ještì jednou díky za záchranu mého mue. Brzy se odstìhujeme.}
{155}{ama21}{Eh... díky za záchranu mého mue... prosím, neøíkej mu, co se mezi námi odehrálo.}
