{100}{}{Vidíš zanedbaného mue ve špinavém hnìdém triku. Jeho ruce jsou pokryté èervenou vyrákou a neustále se drbe.}
{101}{}{Vidíš "Doktora" Andrewa.}
{102}{}{Vidíš zanedbaného mue ve špinavém hnìdém triku. Jeho ruce jsou pokryté èervenou vyrákou a neustále se drbe.}
{103}{}{Vypadá to, e jste se do nìèeho pøipletl, pøíteli.}
{104}{}{Páni... vypadá to, e jste se pøimotal do nìèeho ostøejšího, pøíteli.}
{105}{}{Páni... vypadá to, e jste se pøimotal do poøádné bitky, pøíteli.}
{106}{}{Boe...! Z vás ta krev pøímo støíká!}
{107}{andr5}{Chcete, abych vás obvázal?}
{108}{}{Odvázat.}
{109}{}{Nee.}
{110}{}{Jo, potøebuju lékaøskou prohlídku.}
{111}{}{Eh, potøebuju odstranit vırùstek. Mùj šestı prst.}
{112}{}{No, spíš tady mùj pøítel by potøeboval prohlédnout.}
{113}{}{No, spíš tady moji pøátelé by potøebovali prohlédnout.}
{114}{}{Co je tohle za místo?}
{115}{}{Eh, co e je tohle za místo?}
{116}{}{V lékaøské databázi Vaultu se nacházely schémata bojovıch implantátù. Dokázal byste provést takovou operaci?}
{117}{}{Teï ne. Není to tak zlé, jak to vypadá.}
{118}{}{Ne, jsem v pohodì. Jen tudy procházím.}
{119}{andr6}{Tak dobøe... co se tak dívám, bude to stát }
{120}{}{ babek. Jestli máte prachy, mùeme se do toho dát hned teï.}
{121}{}{A na starıho Doka tam vzadu samozøejmì neposkytuju ádnı záruky...}
{122}{}{Odvázat? Odvázat! Tady peníze, ty odvázat mì.}
{123}{}{Pá pá.}
{124}{}{Né dost penìz. Pá pá.}
{125}{}{Tak dobøe.}
{126}{}{To je trochu moc. Co takhle }
{127}{}{?}
{128}{}{Zapomeòte na to. Mohl byste radìji prohlédnout mého pøítele?}
{129}{}{Zapomeòte na to. Mohl byste radìji prohlédnout mé pøátele?}
{130}{}{Co je tohle za místo?}
{131}{}{V lékaøské databázi Vaultu se nacházely schémata bojovıch implantátù. Dokázal byste provést takovou operaci?}
{132}{}{Nemám dost. Vrátím se, a budu mít trochu víc penìz.}
{133}{}{Ne, díky. Moná nìkdy jindy.}
{134}{}{No... tak dobøe. To zní fér.}
{135}{andr8}{Tak se do toho dáme. Jenom vás pøipojím k tomuhle starımu Doktorovi... strète ruce do tìhlech úchytù, já vás pøikurtuju a zajistím svorky...}
{136}{}{Tøísekundové bezvìdomí}
{137}{andr9}{Paráda! Vìdìl jsem, e mì starej Dok nezklame.}
{138}{}{Já povozit eštì! Eštì!}
{139}{}{Páá páá.}
{140}{}{Mùete vyléèit mého pøítele?}
{141}{}{Mùete vyléèit mé pøátele?}
{142}{}{Co je tohle za místo?}
{143}{}{V lékaøské databázi Vaultu se nacházely schémata bojovıch implantátù. Dokázal byste provést takovou operaci?}
{144}{}{U je mi mnohem lépe, díky.}
{145}{andr10}{Hmm, no, to by pro vás nemuselo bıt nejbezpeènìjší, pøíteli. Zdá se, e u jste se starım Dokem pár tripù podniknul. Ale kdy to chcete...}
{146}{}{Tøísekundové bezvìdomí}
{147}{andr11}{Eh...jak se cítíte? Je vám líp? Nebo hùø?}
{148}{}{Eštì! Eštì! Eštì!}
{149}{}{Já cejtít jako plnej straví, takše já teï fááájn. Pááááá.}
{150}{andr12}{Eh, no, varoval jsem vás...}
{151}{}{Tøísekundové bezvìdomí}
{152}{andr13}{A safra. Zdá se, e si tentokrát starej Dok vybral svou obì.}
{153}{}{Aaaauuu... bolíí... uvnitø... já u nikdy nechtít povozit v tı ošklivá vìc znovu...}
{154}{andr14}{No, nejsem mechanik, take vám s tím vaším mozkem nepomùu. Je mi líto, pøíteli.}
{155}{}{Mùete radìji vyléèit mì?}
{156}{}{Aha. Poslyšte, chci se vás na nìco zeptat...}
{157}{}{Co u. Kadopádnì díky.}
{158}{andr7}{Tak dobøe... co se tak dívám, bude to stát }
{159}{}{ babek. Jestli máte prachy, mùeme se do toho dát hned teï.}
{160}{}{A na starıho Doka tam vzadu samozøejmì neposkytuju ádnı záruky...}
{161}{}{Tak dobøe.}
{162}{}{To je trochu moc. Co takhle }
{163}{}{?}
{164}{}{Zapomeòte na to. Mùete radìji vyléèit mì?}
{165}{}{Co je tohle za místo?}
{166}{}{V lékaøské databázi Vaultu se nacházely schémata bojovıch implantátù. Dokázal byste provést takovou operaci?}
{167}{}{Nemám dost. Vrátím se, a budu mít trochu víc penìz.}
{168}{}{Rozmyslel jsem si to. Moná nìkdy jindy.}
{169}{andr15}{No, take... víte vy co? Dejte mi }
{170}{}{ babek za všechny a plácneme si. Co vy na to?}
{171}{}{Tak dobøe.}
{172}{}{Nevím. To je trochu moc. Co takhle }
{173}{}{ babek?}
{174}{}{Mùete radìji vyléèit mì?}
{175}{}{Co je tohle za místo?}
{176}{}{V lékaøské databázi Vaultu se nacházely schémata bojovıch implantátù. Dokázal byste provést takovou operaci?}
{177}{}{Nemám dost. Vrátím se, a budu mít trochu víc penìz.}
{178}{}{Rozmyslel jsem si to. Moná nìkdy jindy.}
{179}{}{No... tak dobøe. To zní fér.}
{180}{andr16}{Tak se do toho dáme. Jenom vás pøipojím k tomuhle starımu Doktorovi... strète ruce do tìhlech úchytù, já vás pøikurtuju a zajistím svorky...}
{181}{}{Tøísekundové bezvìdomí}
{182}{andr17}{Tak a všichni jsou zase v poøádku! Já vìdìl, e v Doktorovi ještì trocha ivota zbıvá.}
{183}{}{Díky. Poslyšte, potøebuju ještì nìco jiného...}
{184}{}{Tisíceré díky. Moná se tu zastavíme znovu.}
{185}{andr18}{Jste ve zdravotním støedisku Vault City. Já se starım Dokem dokáeme spravit prakticky kohokoliv, kdo to potøebuje.}
{186}{}{"Se starım Dokem?"}
{187}{}{Aha. Chci se ještì na nìco zeptat...}
{188}{}{Hmmm. Moná se vrátím, a budu potøebovat vaše sluby.}
{189}{}{Jo, ten Auto-Dok vzadu v místnosti. Je to zápùjèka z mìsta.}
{190}{andr19}{Obèas trochu neposlouchá, ale vìtšinou svou práci odvede. Vìtšinou.}
{191}{andr20}{V poslední dobì šlape jako hodinky, co je fajn. Pøi opakovaném pouití ale trochu zlobí.}
{192}{}{Vymìnil jsem pár kabelù a vyèistil vnitøek. Nemìl by u dìlat ádné problémy.}
{193}{}{Aha. Chci se ještì na nìco zeptat...}
{194}{}{Neposlouchá, jo? Tak na to se moná podívám...}
{195}{}{To rád slyším. Tak zatím, Andrewe.}
{196}{andr21}{Eh... no... mockrát vám dìkuju. To od vás bylo velmi milé, e jste to opravil gratis.}
{197}{}{To ale nebylo gratis. Oèekávám za své sluby nìjaké peníze.}
{198}{}{Mùu za to získat nìjakou slevu?}
{199}{}{ádnı problém. Rádo se stalo.}
{200}{andr22}{V ádnım pøípadì! Neprosil jsem vás, abyste nìco spravoval, take nic nedostanete. A bıt vámi, tak se o nic nepokouším, dokud jsou stráe nablízku.}
{201}{}{Klidnì si je zavolejte. Nedostanou se sem vèas, aby vám zachránili prdel.}
{202}{}{No, tak není zaè.}
{203}{andr23}{Take... mùu vám ještì s nìèím pomoct?}
{204}{andr24}{S èím ti mùu pomoct?}
{205}{}{Potøebuju lékaøskou prohlídku.}
{206}{}{Eh, potøebuju odstranit vırùstek. Mùj šestı prst.}
{207}{}{Mùj pøítel by potøeboval prohlédnout.}
{208}{}{Mí pøátelé by potøebovali prohlédnout.}
{209}{}{Co je tohle za místo?}
{210}{}{Co e je tohle za místo?}
{211}{}{V lékaøské databázi Vaultu se nacházely schémata bojovıch implantátù. Dokázal byste provést takovou operaci?}
{212}{}{Pro dnešek to bude všechno.}
{213}{andr25}{Bojové implantáty? Co tím myslíte?}
{214}{}{No, podle schémat lze transplantovat podkoní pláty a tepelné rozptylovaèe na lidskou kostru pomocí následujícího postupu...}
{215}{andr26}{Coe? No, myslím, e s pomocí starıho Doka bych tu operaci snad zvládnul, ale pochopitelnì budu nejdøív potøebovat pláty a ty rozptylovaèe... moná by se daly získat z kevlarové zbroje, pokud nìjakou najdete.}
{216}{}{Mohl byste mi øíct nìjaké detaily o tìch implantátech?}
{217}{}{Jednu kevlarovou zbroj u sebe mám. Mohl byste mi øíct nìjaké detaily o tìch implantátech?}
{218}{}{Hmmm. Tak dobøe. Poslyšte, potøebuju ještì nìco jiného...}
{219}{}{Díky. Moná se ještì vrátím.}
{220}{andr27}{Hehe! Vidím, e to berete vánì. No, je to docela riskantní proces. Jestli Obèané pøijdou na to, e starıho Doka pouívám na tyhle operace, vezmou si ho zpátky.}
{221}{}{Aha. Kolik chcete za ty implantáty?}
{222}{}{Nevadí. Potøebuju ještì nìco jiného.}
{223}{}{Tak na to zapomeòte. Moná nìkdy jindy.}
{224}{andr28}{Záleí na tom, co chcete. Chcete standardní implantát, zesílenı implantát, standardní ohnivzdornı nebo zesílenı ohnivzdornı? Kadı má jinou cenu.}
{225}{andr29}{Kterı? Standardní implantát, zesílenı implantát, standardní ohnivzdornı nebo zesílenı ohnivzdornı?}
{226}{}{Standardní implantát.}
{227}{}{Zesílenı implantát.}
{228}{}{Standardní ohnivzdornı.}
{229}{}{Zesílenı ohnivzdornı.}
{230}{}{Zapomeòte na to. Chci se ještì na nìco zeptat...}
{231}{}{Nevadí. U musím jít.}
{232}{andr30}{Standardní podkoní implantát pohltí èást poškození z explozí, kopù, ran a tak. Asi 5%. Budu potøebovat rozebrat kevlarovou zbroj na pláty a samotné vyrobení transplantátù mi zabere asi dva dny. 7 tácù by mìlo staèit.}
{233}{}{To zní dobøe.. tady je kevlarová zbroj a peníze.}
{234}{}{$7000? Eh, mám jen $5000.}
{235}{}{Hmmm. Povìzte mi o tìch dalších implantátech.}
{236}{}{Zapomeòte na to. Chci se ještì na nìco zeptat...}
{237}{}{Vrátím se a budu mít víc penìz.}
{238}{}{Vrátím se, a získám kevlarovou zbroj.}
{239}{}{Aha. Tak snad nìkdy jindy..}
{240}{andr31}{No, technicky vzato je "zesílenı impantát" standardní podkoní implantát s voperovanımi pláty pod kùi.}
{241}{}{Take nejdøív budete potøebovat standardní podkoní implantát.}
{242}{}{Fajn, co k tomu bude potøeba?}
{243}{}{Povìzte mi o tìch dalších implantátech.}
{244}{}{Zapomeòte na to. Chci se ještì na nìco zeptat.}
{245}{}{Aha. Tak snad nìkdy jindy..}
{246}{andr33}{No, budu potøebovat další kevlarovou zbroj kvùli dalším plátùm. Dobrá vìc je, e pláty navíc dokáou absorbovat dvojnásobné poškození, dohromady tedy 10%. Ale...}
{247}{}{Ano?}
{248}{}{Povìzte mi o tìch dalších implantátech.}
{249}{}{Zapomeòte na to. Chci se ještì na nìco zeptat.}
{250}{}{Aha. Tak snad nìkdy jindy..}
{251}{andr34}{Budete potøebovat rehabilitaci, aspoò nìkolik dní, pokud to starej Dok nezvorá. A je to drahé. Øekl bych nejmíò 40 tácù. A navíc...to nijak nepomùe vašemu vzhledu.}
{252}{}{Jak moc mì to zohaví?}
{253}{}{Povìzte mi o tìch dalších implantátech.}
{254}{}{Zapomeòte na to. Chci se ještì na nìco zeptat.}
{255}{}{Aha. Tak snad nìkdy jindy..}
{256}{andr35}{Všechny vaše køivky se zmìní na hrany, aspoò co já vím.}
{257}{andr36}{A s vámi skonèím, budete mít všude hrany.}
{258}{}{Nacpání všech tìhlech plátù do vašeho tìla poznamená vaši charismu. Poøád máte zájem?}
{259}{}{To je mi fuk. Tady jsou peníze a kevlarová zbroj.}
{260}{}{No, nevím. 40 tácù je docela dost. Ale 30 tisíc u sebe mám.}
{261}{}{Povìzte mi o tìch dalších implantátech.}
{262}{}{Zapomeòte na to. Chci se ještì na nìco zeptat.}
{263}{}{Vrátím se a budu mít víc penìz.}
{264}{}{Vrátím se, a získám kevlarovou zbroj.}
{265}{}{Aha. Tak snad nìkdy jindy..}
{266}{andr37}{Phoenix implantáty pohltí èást poškození ohnìm, laserem nebo plazmou... asi 5%. Budu potøebovat kevlarovou zbroj kvùli termálním membránám a operace mi zabere dva dny. 10 tácù by mìlo staèit.}
{267}{}{To zní dobøe. Tady je zbroj a peníze.}
{268}{}{$10000 je na mì trochu moc. Co takhle $8000?}
{269}{}{Povìzte mi o tìch dalších implantátech.}
{270}{}{Zapomeòte na to. Chci se ještì na nìco zeptat.}
{271}{}{Vrátím se a budu mít víc penìz.}
{272}{}{Vrátím se, a získám kevlarovou zbroj.}
{273}{}{Aha. Tak snad nìkdy jindy..}
{274}{andr38}{No, technicky vzato je "zesílenı ohnivzdornı" standardní Phoenix implantát s termálními rozptylovaèi pøipevnìnımi k membránách.}
{275}{}{Take nejdøív budete potøebovat základní Phoenix implantát.}
{276}{}{Fajn, co k tomu bude potøeba?}
{277}{}{Povìzte mi o tìch dalších implantátech.}
{278}{}{Zapomeòte na to. Chci se ještì na nìco zeptat.}
{279}{}{Aha. Tak snad nìkdy jindy..}
{280}{andr40}{No, budu potøebovat další kevlarovou zbroj kvùli teplotním rozptylovaèùm. Dobré je, e rozptylovaèe zvıší tepelnou odolnost, take pohltí asi 10% poškození. Ale...}
{281}{}{Ano?}
{282}{}{Povìzte mi o tìch dalších implantátech.}
{283}{}{Zapomeòte na to. Chci se ještì na nìco zeptat.}
{284}{}{Aha. Tak snad nìkdy jindy..}
{285}{andr41}{Budete mít na kùi puchıøe. Ošklivé. Budete vypadat trochu jako ten pøedváleènı bublinkovı balící materiál, take si po tom asi moc nezarandíte. A navíc je to docela drahé. 50 tácù. Pøedem.}
{286}{}{To je mi fuk. Tady jsou peníze... a tady další kevlarová zbroj.}
{287}{}{40 tácù a plácneme si.}
{288}{}{Povìzte mi o tìch dalších implantátech.}
{289}{}{Zapomeòte na to. Chci se ještì na nìco zeptat.}
{290}{}{Vrátím se a budu mít víc penìz.}
{291}{}{Vrátím se, a získám další kevlarovou zbroj.}
{292}{}{Aha. Tak snad nìkdy jindy..}
{293}{}{No... to zní fér.}
{294}{andr42}{Tak dobøe, teï vás pøikurtuju ke starımu Auto-Doku... snad není ten zásobník anestetik zase ucpanej... a pro jistotu se zakousnìte do tohohle kusu brahmíní kùe.}
{295}{}{Eh... dobøe. Chci øíct, prochází Auto-Dok pravidelnımi servisními prohlídkami, e ano? Hehe. Jak moc zlé to bude?}
{296}{}{Víte co? Zapomeòte na to. Nebudu riskovat, e starej Dok tuhle operaci nezvládne.}
{297}{}{Auuuuuuuuuuuu!}
{298}{}{Pauza 2 sekundy.}
{299}{andr43}{A sakra.}
{300}{}{Hráè vybuchuje v hrùznì morbidní animaci.}
{301}{}{Pauza 2 sekundy.}
{302}{}{Zdá se, e na to starej Dok nakonec nemìl...}
{303}{}{Pauza 2 sekundy.}
{304}{}{No, tohle nejsou špatnı boty. Moná bych je mohl støelit...}
{305}{}{Goto Death Screen}
{306}{}{No... to zní fér.}
{307}{andr42}{Tak dobøe, teï vás pøikurtuju ke starımu Auto-Doku... snad není ten zásobník anestetik zase ucpanej... a pro jistotu se zakousnìte do tohohle kusu brahmíní kùe.}
{308}{}{Tøísekundové bezvìdomí}
{309}{andr44}{Tak a je to tam. Eh, co se tıèe otokù a pøecitlivìlosti, to jsou podle mì jenom doèasné vedlejší efekty. Jo a ta bodavá bolest, která vám vystøeluje do nohou a paí, kdy se hıbete, by mìla zmizet bìhem pár tıdnù.}
{310}{andr45}{Slyšíte mì? Uf. U jsem myslel, e se do vás víc plátù nevejde, ale podaøilo se mi odøezat kupu chrupavek a odstranit spoustu svalové tkánì. Všechno je to tady v té nádobì, pokud chcete suvenır.}
{311}{andr46}{Slitování... byla to operace typu pokus-omyl, jestli mi rozumíte. Musel jsem odstranit nìkolik nervovıch zakonèení...to je to pálení a svìdìní, které cítíte. Nejspíš to zmizí bìhem pár tıdnù.}
{312}{andr47}{Doufám, e mì teï slyšíte. A se vám plnì vrátí schopnost vnímat, pocítíte neuvìøitelnì svìdivı pocit po celém tìle. Nesmíte se drbat! Pokud to udìláte, hnisavé boláky nad chirurgickımi øezy popraskají a zbudou po nich jizvy. Take to nechte pár tıdnù zahojit, jasnı?}
{313}{}{Fíky. Mùhu che heptat echtì na nìcho?}
{314}{}{Fiky, Angrefe. Sbohem.}
{315}{}{No... tak dobøe. To zní fér.}
{316}{andr48}{Tak se do toho dáme. Jenom nastartuju starıho Doka... tady je poloíme, pøikurtuju je a zajistím svorky...}
{317}{}{Tøísekundové bezvìdomí}
{318}{andr49}{Chmmm. Zdá se, e starej Dok zase trucuje. Krám jeden... ale jsem rád, e jsem staèil uvolnit ty svorky døív, ne se spustil pitevní program. Podruhé u snad pobìí v pohodì.}
{319}{}{Co...? Chci zpátky svoje peníze!}
{320}{}{Aha, no, to doufám. Poslyšte, chci ještì nìco...}
{321}{}{Jo, snad. Odcházím.}
{322}{andr50}{Je mi líto, ádné záruky, ádné vracení penìz. Prostì jste to zkusil. Pokud s tím máte problém, obrate se na stráe.}
{323}{}{Vrate mi ty peníze, nebo vás pøipojím ke "starımu Doku."}
{324}{}{Tak na to zapomeòte. Potøebuju ještì nìco jiného...}
{325}{}{To je jedno. Odcházím.}
{326}{andr51}{No, mùu to zkusit, ale je to samozøejmì bez jakıchkoliv záruk. A bude to nìco stát... a tìko øíct, jestli se operace podaøí. Mùe to zaèít rùst znova.}
{327}{}{To je mi jedno. Chci to pryè, ne z toho vyroste nové já.}
{328}{}{No tak nic. Chci se ještì na nìco zeptat...}
{329}{}{Tak na to zapomeòte. Moná nìkdy jindy.}
{330}{andr52}{Hmmmmm. Pìt set a plácneme si. Nemám povolení provádìt se starım Dokem amputace a kdyby se na to pøišlo, pøijdu o práci.}
{331}{}{Fajn. Pìt stovek. A teï mi odstraòte tu zatracenou vìc.}
{332}{}{To je trochu drahé. Co takhle $300?}
{333}{}{No tak nic. Chci se ještì na nìco zeptat...}
{334}{}{Tak na to zapomeòte. Moná nìkdy jindy.}
{335}{}{Zapomeòte na to. Tolik penìz u sebe nemám. Vrátím se pozdìji.}
{336}{}{No... tak dobøe. To zní fér.}
{337}{andr16}{Tak se do toho dáme. Jenom vás pøipojím k tomuhle starımu Doktorovi... strète ruce do tìhlech úchytù, já vás pøikurtuju a zajistím svorky...}
{338}{}{Tøísekundové bezvìdomí}
{339}{andr53}{Ten váš malı pøítel u je pryè. Doufám. Je tìké odstranit všechen ten zmutovanı hnis z kostní døenì. Nicménì, tady ho máte.}
{340}{}{Díky za pomoc. Poslyšte, potøebuju ještì nìco jiného...}
{341}{}{Doufám, e to znovu nevyroste. Opravdu.}
{342}{}{Mockrát dìkuju. Moná se ještì vrátím.}
{343}{}{Získáváš +2 max bodù zdraví navíc.}
{344}{}{Získáváš +4 max bodù zdraví navíc.}
{345}{}{Ztrácíš -2 max bodù zdraví.}
{346}{andr54}{Eh, no, dobøe... ale varoval jsem vás, e to nemusí bıt bezpeèné.}
{347}{}{ babek za vás všechny a mùeme si plácnout. A nebude to fungovat na robotickı mozek, pøíteli. Tak co vy na to?}
{348}{}{Paráda! Vdycky jsem chtìl vypadat jako Kryton! Tady jsou peníze a kevlarová zbroj.}
{349}{andr55}{Tak dobøe. Jdeme na to.}
{350}{}{Ztrácíš -4 max bodù zdraví.}
{351}{}{Cooo? Já poøád necítit dobrá. Já teï jít spát.}
{352}{}{Ehhhh... dobøe. Pá pá.}
