{100}{}{Vidíš špinavého, silnì vypadajícího mue.}
{101}{}{Vidíš Connara.}
{102}{cnr42}{Hej ty! Co tady dìláš?!}
{103}{cnr1}{Zùstaò, kde jsi, venkovane. Co tady pohledáváš?}
{104}{}{Zabíjím krtèí potkany.}
{105}{}{Proè, co je ti po tom?}
{106}{}{Proè ty øvát?}
{107}{cnr2}{Vsadím se, e tì poslali ti bastardi z Vault City. Radìji odejdi a nech tu všechno naivu.}
{108}{}{No, na to u je trochu pozdì.}
{109}{}{Jak to?}
{110}{}{Promiò, ale je to moje práce.}
{111}{cnr3}{Tihle tvorové jsou jedinou vìcí, která brání lidem z Vault City si z nás udìlat takzvané "sluebníky".}
{112}{}{Podívej, zaplatili mi za jejich vyhubení a pøesnì to hodlám udìlat.}
{113}{}{To mi neøekli.}
{114}{}{Zaplatili mi za jejich vyhubení a u je to hotové.}
{115}{cnr4}{Ty idiote! Proè jsi to k èertu udìlal!}
{116}{}{Potøebuju peníze.}
{117}{cnr5}{Víš, jestli to udìláš, tak si pro nás pøijdou.}
{118}{}{To není mùj problém.}
{119}{cnr6}{V tom pøípadì doufám, e se nimi udusíš. Brzy si pro nás pøijdou.}
{120}{}{Nevìdìl jsem, e to chtìli udìlat kvùli tomu.}
{121}{}{Jo, stejnì nejednám s takovım póvlem, jako jsi ty.}
{122}{cnr7}{To ti nemùeme dovolit.}
{123}{}{Kdy musíš, tak musíš.}
{124}{cnr8}{A ty jim to opravdu vìøíš? Máš se ještì co uèit, pøíteli.}
{125}{}{Mùu nìjak pomoct?}
{126}{}{Stráe Vault City nepatøí k nejstateènìjším. Staèí se jen zmínit o souboji a uteèou daleko za humny. Kdybychom mìli pár zbraní, mohli bychom se jim postavit.}
{127}{}{Moná vám mùu pomoct, ale zbranì nejsou levné. Jakı druh zbraní sháníte?}
{128}{}{(Podívá se na tebe váhavım pohledem.) Ty nám chceš opravdu pomoct? Tak dobøe. Jestli to myslíš vánì, hodily by se nám nìjaké pušky. Díky nim bychom je mohli odstøelovat z dálky. Take pokud nám chceš opravdu pomoct, pøines nám nìjaké automatické pušky. Ètyøi by mohli staèit. Jo a hodila by se i brokovnice pro pøípad, e se k nám dostanou na blízko.}
{129}{}{Uvidím, co se dá dìlat. Ale jak øíkám, zbranì nejsou levné, take budu potøebovat nìjaké peníze.}
{130}{cnr11}{Nechceme tì tu. Odejdi.}
{131}{}{Myslím, e ne. S èím vám mùu pomoct?}
{132}{}{Jo, stejnì tu u nebudeš moc dlouho.}
{133}{}{Jako by mì to zajímalo.}
{134}{cnr12}{Vítej zpátky! Máš pro nás ty zbranì?}
{135}{}{Co e to vlastnì potøebujete?}
{136}{}{Jo, tady jsou.}
{137}{cnr13}{Potøebujeme ètyøi útoèné pušky a brokovnici. Èím døív nám je pøineseš, tím lépe.}
{138}{}{Dobøe.}
{139}{}{Vıbornì! S tìmito hraèkami to tu snad v pøíštích mìsících zmìníme k lepšímu. Díky moc a jestli budeš nìkdy potøebovat nocleh, kdykoliv tì tu uvítáme, pøíteli.}
{140}{}{Není zaè.}
{141}{cnr43}{Ahoj! Jde to docela dobøe. Pøíští mìsíc se chystáme rozšiøovat vesnici.}
{142}{}{Zdravíèko! Jak vidíš, jde to docela dobøe. Klidnì se porozhlédni kolem, pokud máš èas.}
{143}{cnr44}{Poøád ještì stavíme. Doufáme, e pøíští mìsíc opìt rozšíøíme zdi.}
{144}{cnr52}{Zdravím! Vesnice se znovu rozšíøila, pøesnì jak jsme doufali. Samozøejmì tì tu vdy uvítáme.}
{145}{cnr45}{Teï u se Vault City nemusíme vùbec obávat a mùeme tu ít v klidu a míru. Ještì jednou díky, venkovane.}
{146}{cnr15}{Ne e tam nìco zabiješ, hlupáku.}
{147}{cnr16}{Co to sakra bylo?!?! Ty zasranej zrádèe! Nenávidím tì!!!}
{148}{}{A sakra...}
{149}{cnr46}{Pus mì ven!!!}
{150}{cnr47}{Co jsem ti kdy udìlal?}
{151}{cnr48}{Pomoc!}
{152}{}{Samozøejmì. Tady máš vše, co si mùeme dovolit. (Pøedá ti $5000.) Moná jsem hlupák, kdy vìøím venkovanovi, ale jsi naše jediná nadìje na zachování samostatnosti. Promluv si se Starım Joem na Pøedmìstí ve Vault City. Vìtšinou ho najdeš v místním baru nebo nìkde kolem. On u bude vìdìt co dìlat.}
{153}{}{Jdu na to.}
{154}{}{Mùu se na nìco zeptat?}
{155}{cnr18}{Samozøejmì, co chceš vìdìt?}
{156}{}{Odkud se vzali ti krtèí potkani a proè nejsou agresivní?}
{157}{}{Ale nic, nashle.}
{158}{}{No, to je takovı zvláštní pøíbìh. Víš, jednoho dne k nám pøišla skupina ghoulù. Mumlali nìco o "Obrození" a rozdávali tyhle prašivé amulety. (Ukáe ti amulet Ankh.) Tvrdili, e od této chvíle nás budou tito velicí hlodavci ochraòovat. Ghoulové odešli, nejspíše zpìt do Gecka, ale hlodavci tu od té doby zùstali. Jak jsem øekl, je to opravdu zvláštní. Není zrovna sranda po nich uklízet, ale k èertu, dokud nám budou chránit zadky pøed Vault City, tak ty krysí hovna nìjak pøetrpíme.}
{159}{}{Velmi zajímavé. Mùu si vzít jeden ten amulet?}
{160}{cnr20}{Klidnì. Dali nám jich tolik, e ani nevíme, co s nima máme sakra dìlat. Tady, vezmi si jeden.}
{161}{}{Díky moc. Nashle.}
{162}{}{Ne, ale mám skvìlou zprávu. Podaøilo se mi pøesvìdèit radu Vault City, aby vaši vesnici nechali na pokoji.}
{163}{cnr21}{Coe? Oni nás opravdu nechají na pokoji? To nechápu... jak se ti to povedlo? Jestli zjistím, e si ze mì dìláš prdel...}
{164}{}{Je to pravda, vìø mi. Povedlo se mi zatahat za pár nitek a porušit jednu dohodu, ale není tøeba zacházet do detailù. Dùleité je, e jste teï v bezpeèí.}
{165}{cnr22}{Z celého svého srdce ti dìkuji... ehm... mimochodem, poøád nevím, jak se vlastnì jmenuješ.}
{166}{}{Jmenuju se }
{167}{}{Dìkuju ti, }
{168}{}{, ale co se stalo s tìmi penìzi, které jsem ti dal na nákup zbraní?}
{169}{cnr23}{Vdy tì tu rádi uvítáme! Nashledanou.}
{170}{}{Ano, ale myslím, e je nebudete potøebovat. Alespoò ne proti Vault City. Podaøilo se mi pøesvìdèit radu Vault City, aby vaši vesnici nechali na pokoji.}
{171}{}{Udìlám to. Nejdøív se chci ale na nìco zeptat.}
{172}{}{Ale nic. Nashle.}
{173}{}{Ještì ne. Vrátím se, a je budu mít.}
{174}{}{Díky! Uvidíme se pozdìji.}
{200}{}{Náhodou mám u sebe pøesnì to, co potøebujete.}
{201}{}{Tak se zdá, e ty zbranì vlastnì dávno nosím s sebou. Myslím, e jich nìkolik mùu postrádat, ale jsi si jistı, e tohle je ten nejlepší zpùsob, jak to vyøešit?}
{202}{}{Mám ty zbranì, co potøebujete, ale upøímnì si myslím, e existuje i lepší zpùsob, jak to vyøešit. V radì Vault City je velmi rozumnı mu, vrchní èlen rady McClure. Urèitì ho dokáu pøemluvit k tomu, aby radu pøesvìdèil k pøistoupení na mírumilovné øešení.}
{203}{}{Upøímnì si myslím, e existuje i lepší zpùsob, jak to vyøešit. V radì Vault City je velmi rozumnı mu, vrchní èlen rady McClure. Urèitì ho dokáu pøemluvit k tomu, aby radu pøesvìdèil k pøistoupení na mírumilovné øešení.}
{205}{cnr24}{Ha! Opravdu si myslíš, e se nìkdo z vrchních èlenù rady zajímá o náš osud? Nebuï tak naivní, pøíteli, tìm parchantùm ve Vault City se nedá vìøit. A teï jdi prosím najít Joea na Pøedmìstí ve Vault City. Pokud nebude v baru, najdeš ho nìkde poblí. Starı Joe u bude vìdìt co dìlat. Mùeš mu vìøit. Prosím, pospìš si.}
{206}{}{Dobøe. Dám vìdìt, a budu mít nìjaké novinky.}
{210}{cnr25}{Vìø mi, zvaovali jsme alternativy, ale to jediné, na co ti parchanti z Vault City budou reagovat, je násilí. Dáš nám teï ty zbranì? Zaplatím ti za nì $5000. Svoboda je toti dùleitìjší ne peníze.}
{211}{cnr26}{Opravdu?! Vıbornì. Tady, dám ti za ty zbranì $5000. Jsou to sice všechny naše peníze, ale svoboda je dùleitìjší. Dìkujeme ti za tvoji slubu a vdy tì tu rádi uvítáme.}
{212}{}{Dobrá. Tady jsou ty zbranì.}
{213}{}{Ne, myslím, e ne. Sbohem.}
{214}{}{Svoboda je dùleitìjší ne peníze, jo? No, vím, jak funguje ekonomika. Rùst poptávky znamená rùst ceny.}
{215}{}{[KONEC]}
{216}{}{[ÚTOK]}
{217}{}{Poslouchej, zaèít válku s Vault City není øešení. Jistì, moná se dokáete ubránit po nìkolik mìsícù, moná i let, ale nevydríte vìènì. A v prùbìhu toho pøijde spousta lidí zbyteènì o ivot. Pokud se mi ale podaøí pøemluvit jednoho èlena rady ve Vault City, tak vìøím, e se dohodnete na mírumilovném øešení.}
{218}{cnr27}{Hmm... dobrá. Vidím, e máš zájem o naše dobro. Kdy myslíš, e se ti podaøí pøemluvit jednoho z jejich èlenù, pak tedy prosím, zkus to. Nicménì bych ti doporuèil promluvit si se Starım Joem a vyslechnout si jeho názor. Najdeš ho nìkde poblí baru na Pøedmìstí. Hodnì štìstí. Spoléháme na tebe.}
{220}{cnr28}{Mìl jsem tušit, e jsi jen další bezcitná svinì. Kvùli lidem, jako jsi ty, jsme zaloili tuto spoleènost. Víš co? Zapomeò na to. Nepotøebujeme pomoc od nìkoho, jako jsi ty. A teï radìji odejdi.}
{221}{cnr29}{Mìl jsem tušit, e jsi jen další bezcitná svinì. Kvùli lidem, jako jsi ty, jsme zaloili tuto spoleènost. (Povzdychne si.) Fajn, pøihodíme další tisícovku, ale u nám nic nezbyde. Teï u nám ty zbranì dáš?}
{222}{}{Jistì, bylo mi potìšením s vámi obchodovat. Nashle.}
{223}{}{Vlastnì myslím, e jinde udìlám lepší obchod. Sbohem.}
{225}{cnr30}{Vıbornì. Tady, dám ti za ty zbranì $5000. Jsou to sice všechny naše peníze, ale svoboda je dùleitìjší. Dìkujeme ti za tvoji slubu a vdy tì tu rádi uvítáme.}
{226}{}{Dobrá, dávejte na sebe pozor.}
{300}{cnr31}{Máš nìjaké novinky o našem problému?}
{301}{}{Zatím ne. Dám vìdìt, a nìco zjistím.}
{302}{}{Dobrá zpráva, podaøilo se mi pøesvìdèit radu Vault City, aby vaši vesnici nechali na pokoji.}
{310}{cnr32}{Nechceš se s námi podìlit o zbranì, které sebou nosíš? Nabídneme ti za nì $5000.}
{311}{}{To zní jako dobrı obchod. Tady jsou.}
{312}{}{Ne, nechci. Venku je to nebezpeèné a já potøebuju všechny zbranì, které u sebe mám. Sbohem.}
{400}{cnr49}{Díky, pøíteli. S tìmito zbranìmi máme koneènì šanci!}
{401}{cnr50}{Vítej zpìt. Díky tobì jsme úspìšnì odrazili hlídku Vault City. U nás nebudou obtìovat.}
{500}{cnr51}{Neobtìuj mì.}
{600}{}{Jak e se jmenoval tvùj kontakt ve Vault City?}
{601}{cnr33}{Starı Joe. Jak ji jméno napovídá, je to opravdu starı chlapík. Buï ho najdeš v baru na Pøedmìstí nebo bude nìkde kolem.}
{602}{}{Dobrá, díky.}
{603}{}{Kdo to vlastnì je?}
{604}{cnr34}{Starı Joe je opravdovı charakter. Tvrdí o sobì, e je mu pøes sto let, ale nevím, jestli mu to mám vìøit. Tvrdí o sobì hodnì vìcí. Dokonce i to, e jednou pomohl zachránit svìt. Zná spoustu historek, ale øekl bych, e vìtšina z nich jsou jen kecy, i kdy poutavé. Dohlíí za nás na vìci ve Vault City a jde mu to náramnì dobøe vzhledem k tomu, e je starı jako Metuzalém a skoro slepı.}
{605}{}{Zajímavé. U musím jít.}
{606}{}{Øíká, e pomohl zachránit svìt? Víš, také jsem na takové vıpravì za záchranou svìta, tedy alespoò za záchranou *svého* svìta.}
{610}{cnr35}{Aha. To se máš. No, tak a ti to vydrí. Jen nezapomeò na náš problém.}
{611}{}{Ne, nezapomenu. Uvidíme se pozdìji.}
{612}{}{Vlastnì na to nejspíš zapomenu. Mám tolik úkolù, e je tìké si je všechny pamatovat. Kdybych nemìl tenhle šikovnı Pip-Boy, kdo ví, kde by mì teï bylo konce? Zatím.}
{700}{}{Jo, jasnì. Tady máš. [Dát mu $5000]}
{701}{}{Promiò, objevily se nìjaké vıdaje.}
{702}{}{Do prdele, nemám dost na vrácení. Nejspíš jsem nìjaké peníze utratil, ani bych o tom pøemıšlel. Brzy ti je vrátím.}
{710}{cnr36}{Díky. Tady. (Vrátí ti zpìt $2500.) Nech si je. To je to nejmenší, èím se ti mùeme odvdìèit.}
{720}{cnr37}{Aha, chápu. No, pokud jsme si za to koupili svobodu, tak to za to stálo. Ještì jednou díky za všechno.}
{730}{cnr38}{Nìco ti povím, co takhle nám vrátit jen pùlku? Máš $2500?}
{731}{}{Jistì, tady. [Dát mu $2500]}
{732}{}{Promiò, nemám ani to.}
{740}{}{Dìkuju ti, }
{741}{}{. Váíme si tvé pomoci.}
{750}{cnr39}{Chápu... no, nedìlej si s tím starosti. Peníze nejsou tak dùleité jako naše svoboda. Dìkuju ti.}
