{100}{}{Vidíš Lıdii.}
{101}{}{Vidíš hnìdovlasou enu odìnou v hnìdém pracovním odìvu a kovové zbroji. Vypadá jako barmanka.}
{102}{}{Vidíš Lıdii.}
{103}{}{Vidíš hnìdovlasou enu odìnou v hnìdém pracovním odìvu a kovové zbroji. Vypadá jako barmanka.}
{104}{lydia34}{Vítej! Dáš si drink, Vyvolenı?}
{105}{lydia35}{Vítej, Vyvolenı! Prosím, posaï se na baru.}
{106}{lydia36}{Prosím! Posaï se a odpoèiò si!}
{107}{lydia37}{To je Vyvolenı! Kadı pozvednìte èíši na HRDINU Falloutu 2!}
{108}{lydia38}{Dobrı den, Kapitáne.}
{109}{lydia39}{Vault City vdy zvítìzí, Kapitáne.}
{110}{lydia40}{Zdravíèko, Obèane.}
{111}{lydia41}{Vault City vdy zvítìzí, Obèane.}
{112}{lydia42}{Mutant! Stráe! Stráe!}
{113}{lydia43}{Ghoul! Stráe! Stráe!}
{114}{lydia44}{Máme zavøeno. Pøijï ráno.}
{115}{lydia45}{Promiò, za chvíli zavíráme. Pøijï ráno.}
{116}{lydia46}{Máme zavøeno. Jen co dodìlám inventuru, tak zavøu.}
{117}{lydia1}{Zdravím, Vyvolenı! Zrovna jsme mluvili o tvıch dobrodrustvích... dáš si nìco k pití?}
{118}{}{Kdo whisky pít, ten blít.}
{119}{}{Odbelhat se.}
{120}{}{Co se dneska èepuje?}
{121}{}{Sháním nìjaké informace.}
{122}{}{Mám pro tebe ten alkohol.}
{123}{}{Dnes nic, díky.}
{124}{lydia2}{Eh... tak já páchnu. Ehm, ještì jednou díky za záchranu svìta a nás všech.}
{125}{}{Kdo pivo pít, ten chèít!}
{126}{}{Odbelhat se.}
{127}{lydia3}{Podívej, moná jsi zachránil celı svìt a nás všechny, ale dobrı básník zrovna nejsi. Radši toho nech.}
{128}{}{Brum, brum, brum, zboøit celej dùm!}
{129}{}{Odbelhat se.}
{130}{lydia4}{Poslyš, tohle si vezmi a vypadni odsud, ano? To ti snad na chvíli zavøe hubu.}
{131}{}{Dìkovala já smrdìla.}
{132}{}{Odbelhat se.}
{133}{lydia5}{Eh... co pro vás mùu udìlat, Kapitáne?}
{134}{lydia6}{Co pro tebe mùu udìlat, Obèane?}
{135}{lydia7}{Ano? Mohu vám pomoci?}
{136}{}{Ty? Tııı? Ííííí? Íííí lidi dìlat kdy já blízko.}
{137}{}{Odbelhat se.}
{138}{}{Co se dneska èepuje?}
{139}{}{Sháním nìjaké informace.}
{140}{}{Mám pro tebe ten alkohol.}
{141}{}{Dnes nic, díky.}
{142}{lydia8}{To je asi ta nejpodivuhodnìjší vìc, jakou jsem kdy slyšela. Vydr chvilku... chci, aby si to poslechli i stráe.}
{143}{}{Sráe? Sráèe. Sráèe nemít rád.}
{144}{}{Odbelhat se.}
{145}{lydia9}{Máme syntetická piva a lihoviny...vodku-H, deriváty tequily W a W2. Jo a vodu. A brahmíní mléko. Pivo a lihoviny jsou za $10, voda a mléko stojí $3.}
{146}{lydia10}{Tak tøeba...?}
{147}{}{Eh, nemáte nìjakı opravdovı alkohol?}
{148}{}{Dám si syntetické pivo.}
{149}{}{Syntetická vodka by fakt bodla.}
{150}{}{Tequila W2 by byla vıborná.}
{151}{}{Voda by byla vıborná.}
{152}{}{Brahmíní mléko.}
{153}{}{Vlastnì sháním nìjaké informace.}
{154}{}{Vrátím se a budu mít víc penìz.}
{155}{}{Myslím, e nic. Díky.}
{156}{lydia11}{Brahmíní mléko neèepujeme... toti, ne tak docela. Musela bych jít ven a rychle nìjaké sehnat.}
{157}{}{To nevadí, já klidnì poèkám. Mám opravdu chu na sklenici èerstvého mléka. Mmmmm-mmm. To by fakt bodlo.}
{158}{}{Tak já tedy zkusím nìco jiného.}
{159}{}{Nevadí. Chci tedy aspoò nìjaké informace...}
{160}{}{Zapomeòte na to. Vrátím se jindy.}
{161}{lydia12}{Tady to máš. Ještì nìco?}
{162}{}{Eh, nemáte nìjakı opravdovı alkohol?}
{163}{}{Dám si syntetické pivo.}
{164}{}{Syntetická vodka by fakt bodla.}
{165}{}{Tequila W2 by byla vıborná.}
{166}{}{Voda by byla vıborná.}
{167}{}{Brahmíní mléko.}
{168}{}{Vlastnì sháním nìjaké informace.}
{169}{}{Vrátím se a budu mít víc penìz.}
{170}{}{Myslím, e nic. Díky.}
{171}{lydia13}{Ano? Co konkrétnì?}
{172}{}{Kdo má na starosti Vault City?}
{173}{}{Kde je Vault?}
{174}{}{Mùeš mi øíct nìco o otroctví ve Vault City?}
{175}{}{Má Vault City nìjaké kontakty s okolním svìtem?}
{176}{}{Co tady èepujete?}
{177}{}{Mám pro tebe ten alkohol.}
{178}{}{Tak dobøe. Pøeju hezkı den.}
{179}{lydia14}{Pøece První Obèanka Lynette... jsi snad Obèan, nebo ne?}
{180}{lydia15}{První Obèanka Lynette. Je v budovì radnice smìrem na sever, jestli s ní potøebuješ mluvit.}
{181}{}{Chci se ještì na nìco zeptat...}
{182}{}{Tak dobøe. Pùjdu si s ní promluvit.}
{183}{lydia16}{Eh, to je ten velkı otvor ve skále na vıchod odtud... poslyš, jsi snad Obèan, nebo ne?}
{184}{lydia17}{Je to ten velkı otvor ve skále na vıchod odsud. Nemùeš to minout. Ale dovnitø se nedostaneš, pokud nejsi Obèan.}
{185}{}{Chci se ještì na nìco zeptat...}
{186}{}{Ale já jsem Obèan.}
{187}{}{No, jen si ovìøuju, e jdu správnì. Díky. Pùjdu se tam podívat.}
{188}{}{Hmmm. Díky za informace.}
{189}{lydia18}{Jistìe jsi. Bıt tebou, tak si dám pozor na to, komu to øíkáš, "Obèane." Nìkdo by si mohl všimnout, e máš kradené doklady od toho vydøiducha Skeeva. Take na sebe neupozoròuj, jasné?}
{190}{}{Eh, dobøe. Poslyš, chci se ještì na nìco zeptat...}
{191}{}{Aha. No, díky za radu.}
{192}{lydia19}{Podívej, mìla bych ti asi øíct, e tady v okolí bude lepší nepouívat vıraz "otroctví", pokud se nechceš dostat do potíí. Øíkáme jim "sluebníci", ne otroci. Ber to jako dobrou radu.}
{193}{}{Rozumím. Poslyš, chci se ještì na nìco zeptat...}
{194}{}{Díky. Budu na to myslet.}
{195}{lydia20}{Moc ne. Nejvíc kontaktù máme s karavany obchodníkù, kteøí jezdí Velkı okruh z Broken Hills, New Rena a Reddingu. Jediné další místo, o kterém vím, je Gecko.}
{196}{}{Povìz mi o Broken Hills.}
{197}{}{Povìz mi o New Renu.}
{198}{}{Povìz mi o Reddingu.}
{199}{}{Povìz mi o Gecku.}
{200}{}{Chci se ještì na nìco zeptat...}
{201}{}{Díky za informace.}
{202}{lydia21}{Je to tìební komunita stejnì jako Redding, akorát e leí daleko na jihu. Vìtšinu našeho uranu získáváme odtamtud.}
{203}{}{Povìz mi o New Renu.}
{204}{}{Povìz mi o Reddingu.}
{205}{}{Povìz mi o Gecku.}
{206}{}{Chci se ještì na nìco zeptat...}
{207}{}{Díky za informace.}
{208}{lydia22}{Najdeš ho smìrem na jihozápad. Ale slyším odtamtud jenom o samıch potíích. Nìkteøí obchodníci, a zvláštì otrokáøi, si tam však velice libují. Ostatní obchodníci... moc ne. Slyšela jsem, e je to mìsto, které se napovrch tøpytí... ale uvnitø je skrz naskrz prohnilé.}
{209}{}{Povìz mi o Broken Hills.}
{210}{}{Povìz mi o Reddingu.}
{211}{}{Povìz mi o Gecku.}
{212}{}{Chci se ještì na nìco zeptat...}
{213}{}{Díky za informace.}
{214}{lydia23}{Je to dùlní mìsto na západì. V poslední dobì jsme od nich moc karavan nevidìli, take zaèínáme mít trochu obavy. Obzvláš vrchní radní McClure.}
{215}{}{Povìz mi o Broken Hills.}
{216}{}{Povìz mi o New Renu.}
{217}{}{Povìz mi o Gecku.}
{218}{}{Chci se ještì na nìco zeptat...}
{219}{}{Díky za informace.}
{220}{lydia24}{Je to mìsto ghoulù ani ne jeden den na severovıchod. Øíká se, e loví poutníky, kteøí vstoupí na jejich území. Radši se odtamtud dr dál.}
{221}{}{Povìz mi o Broken Hills.}
{222}{}{Povìz mi o New Renu.}
{223}{}{Povìz mi o Reddingu.}
{224}{}{Chci se ještì na nìco zeptat...}
{225}{}{Díky za informace.}
{226}{lydia25}{Proè se ptáš? Hledáš snad nìco silnìjšího ne je syntetické pití?}
{227}{}{Moná. Víš, pití syntetického alkoholu se nedá srovnávat se skuteènım alkoholem.}
{228}{}{Ani ne. Spíš mì zajímají nìjaké informace...}
{229}{}{Dnes ne.}
{230}{lydia26}{To je pravda. Kdysi jsem mìla... vlastnì jsem znala jednoho obchodníka, kterı schovával ve skrıši láhev Maddogu 30/30. Opravdu tvrdé pití... vùbec jsem po nìm necítila jazyk, ale bylo to naprosto parádní.}
{231}{}{Co se s tou "obchodníkovou" skrıší stalo?}
{232}{}{Sháním nìjaké informace.}
{233}{}{Aha. No, moc hezky se mi s tebou povídalo.}
{234}{lydia27}{Nìkdo ji vypil. Ten obchodník mìl ve Vault City nìkolik "pøátel", kteøí mu s pitím pomáhali. Byli ochotní zaplatit opravdu velmi vysoké ceny, jen aby mìli pro zmìnu opravdové pití.}
{235}{}{O tom nepochybuju. Myslím, e by pro mì nebyl pøíliš velkı problém sehnat vìtší mnoství opravdového alkoholu. Moje cesty vedly i pøes místa, kde se k nìmu dá snadno dostat.}
{236}{}{Sháním nìjaké informace.}
{237}{}{Aha. No, moc hezky se mi s tebou povídalo.}
{238}{lydia28}{Opravdu? No, pokud mi seeneš nìjakı opravdovı alkohol, dobøe ti za to zaplatím. Ale nikdo se o tom nesmí dozvìdìt. A taky ho musíš nìjak propašovat skrz bránu.}
{239}{}{A kolik bys toho alkoholu chtìla?}
{240}{lydia29}{No, øeknìme bednu deseti lahví kvalitního alkoholu a deset lahví piva. Ale ne e mi pøineseš tu radioaktivní bøeèku z Gecka. Jenom starı, dobrı "chlast", jasné?}
{241}{}{Tak zrovna takové mnoství mám u sebe.}
{242}{}{Myslím, e pro tebe mùu nìco sehnat. A teï mám ještì nìjaké otázky...}
{243}{}{Hmmmm. Popøemıšlím o tom a pak se zastavím.}
{244}{lydia30}{Vıbornì! Tady máš... je to dvakrát tolik, ne kolik má ta bedna cenu. A nemusím ti doufám pøipomínat, e se tahle transakce nikdy neuskuteènila, jasné?}
{245}{}{ádnı problém. Poslyš, sháním nìjaké informace...}
{246}{}{Díky. S tebou je radost obchodovat.}
{247}{lydia31}{Ne, tyhle domácí pálenky, kterım se øíká alkohol, jsou ve Vault City ilegální. A radši ani nechci vìdìt, jak se destilují. Take, dáte si nìco k pití, Kapitáne...?}
{248}{}{Nevidím nic špatného na tom dát si tu a tam opravdovı alkohol. Ano, trpí tím vnímání, ale to i kdy si vezmeš pøíliš moc léèivıch práškù.}
{249}{}{Tak si dám nìco jiného.}
{250}{}{Nevadí. Chci se ještì na nìco zeptat...}
{251}{}{Aha. Kadopádnì díky.}
{252}{lydia32}{Tak o tom nic nevím. Prodávám jenom syntetickı alkohol. I kdyby se do Vault City nìjakı opravdovı alkohol dostal, nevìdìla bych o nìm.}
{253}{}{Nevadí. Chci se ještì na nìco zeptat...}
{254}{}{Aha. Kadopádnì díky.}
{255}{lydia33}{A...ha. No, eh, mìj se. Ano?}
{256}{}{Dìkovala já smrdìla.}
{257}{}{Odbelhat se.}
{258}{lydia47}{Chrrrrrr.}
