{100}{}{Vidíš malého veselého mue.}
{101}{}{Vidíš Šastného Harryho, majitele obchodu.}
{102}{hhary1}{Zdravíèko... co pro tebe mùu udìlat?}
{103}{}{Chci obchodovat. Mùu vidìt, co nabízíš?}
{104}{}{Ten pluh venku je poøád na prodej?}
{105}{}{Já koupit.}
{106}{}{Dnes nic, díky.}
{107}{hhary16}{Promiò. Nemùu ti pomoct, sousede.}
{108}{hhary2}{Ano, je. Mùu ti ho nechat za... øeknìme, osm set.}
{109}{}{Dám ti za nìj šest set.}
{110}{}{Dohodnuto. To beru.}
{111}{}{Eh, osm set? Vydr, vrátím se... s penìzi.}
{112}{}{Zapomeò na to. Jen a si Smithovi hladoví.}
{113}{}{Je tvùj. (Dá si do kapsy peníze.) Vezmeš si ho hned, nebo ho chceš nìkam dopravit?}
{114}{}{Doprav ho ke Smithovım.}
{115}{hhary4}{Promiò, pøíteli. Bude tì to stát osm set.}
{119}{hhary5}{Na zaplacení potøebuješ peníze, pøíteli.}
{120}{}{Vrátím se s penìzi.}
{121}{hhary6}{ádnı problém. Hned ho tam nechám dopravit.}
{122}{hhary17}{Chtìli jsme si pøilepšit, co? Zatracenej zlodìji... stráe! Stráe!}
{123}{}{Posílá mì Dave. Pokoušíme se opravit rozbitou vodní pumpu a on mi øíkal, e budeš mít náhradní motor.}
{124}{}{Pracuješ s Davem, jo? Jo, znám toho chlápka. Koukám, e se mu stále daøí pøemlouvat ostatní, aby udìlali práci za nìj. Parchant jeden línej. (Usmìje se.) No ale myslím, e mám pøesnì to, co potøebuješ, ale pro jistotu se zajdu podívat. (Harry odejde do zadní místnosti, odkud je slyšet, jak hıbe s nìjakımi krabicemi. Za minutu se vrátí.) Jo, mám ho tady. $500 a je tvùj.}
{125}{}{Jistì. Tady jsou peníze.}
{126}{}{$500? Sakra. Doufám, e se mi to vyplatí. Fajn, tady jsou peníze.}
{127}{hhary8}{Díky za obchod. Mìj se.}
{128}{}{Èau.}
{129}{}{Connar mì posílá pro nìjaké zboí.}
{130}{hhary9}{(Harryho oèi mihotají kolem a vypadá trochu nervóznì.) Ano, jistì. Jenom chvilièku...}
{131}{hhary10}{(Harry ti pøinese pušky.) Tady, vezmi si je. Bude to deset tisíc, ale rychle.}
{132}{}{Jistì, tady jsou peníze.}
{133}{}{Ale Connar mi dal jenom pìt tisíc.}
{134}{}{Ale Connar mi dal jenom dva tisíce.}
{135}{hhary11}{To není mùj problém. Promiò, ale obchody u nejsou to, co bıvaly. Jestli nìkdo zjistí, e zásobuju Connara zbranìmi, budou se dít ošklivı vìci. U takhle to má se slevou.}
{136}{hhary12}{Podívej, nasazuju kvùli tomu vlastní krk... ale k èertu s tím, nemám èas se hádat. Tak si je vem. (Dává si peníze do kapsy.) A teï odsud vypadni, ale pamatuj, e já ti je neprodal.}
{137}{hhary13}{Vıbornì. Ale pamatuj, e ty zbranì nemáš odsud.}
{138}{}{Dohodnuto. Nashle.}
{139}{}{[Více]}
{140}{}{Tak dobøe. Poèkej chvíli, ne seenu peníze.}
{141}{hhary14}{Tak jak, máš ty peníze?}
{142}{}{Co kdy ti dám jenom pìt tisíc?}
{143}{}{A co takhle dva tisíce?}
{144}{}{Ehmmm... deset tisíc?! Tolik penìz nemám. Poèkej chvíli, ne je seenu.}
{145}{hhary18}{Zatracenì! Kdo mì prásknul?!}
{146}{hhary19}{Hej! Za co jsem ve vìzení?}
{147}{hhary20}{No, alespoò to jídlo není špatnı.}
{148}{hhary21}{Na co èumíš?}
{149}{hhary22}{Co bude s mım obchodem?}
{200}{}{$500? Poslyš, nemohl bys mi dát nìjakou slevu? Pøeci jen ty a Dave jste pøátele, ne?}
{201}{hhary15}{Abych ti øekl pravdu, tak ten chlap mi byl vdycky ukradenej. $500 za ten motor. Ber, nebo nech bıt.}
{202}{}{Fajn. Tady jsou peníze.}
{203}{}{Zapomeò na to, padám odsud.}
{204}{}{$500!? Tak na to zapomeò, padám odsud.}
{1288}{}{Vypadá to, e nemám dost penìz. Nashle.}
