{100}{}{Vidíš mue s radikálním pohledem. Navzdory jeho neupravenım vlasùm a neoholenım vousùm jsou jeho šaty èisté a vyehlené.}
{101}{}{Vidíš Thomase Moorea.}
{102}{}{Vidíš Thomase Moorea. Navzdory jeho neupravenım vlasùm a neoholenım vousùm jsou jeho šaty èisté a vyehlené.}
{103}{moore1}{Buï zdráv a vítej, pocestnı! Slyšel jsi u dnešní zprávy?}
{104}{}{Uurmph.}
{105}{}{Ecch.}
{106}{}{Portzebie.}
{107}{}{Odbelhat se.}
{108}{}{Ne... neslyšel.}
{109}{}{A ty jsi...?}
{110}{}{Eh, ne, a ani nechci. Sbohem. }
{111}{moore2}{Svìt, mùj pøíteli... svìt je SOBECKİ. Pøidej k tomu aroganci a co dostaneš? Vault City... v celé své nadøazené slávì z otrokáøství.}
{112}{}{Proè tu tedy iješ, kdy to tu tak nenávidíš?}
{113}{}{Ámen, bratøe!}
{114}{}{Myslím, e u to nechci poslouchat. Sbohem.}
{115}{}{Bì si vykládat ty svoje bláboly nìkam jinam, kámo... takovejch, jako jsi ty, u tu bylo dost.}
{116}{moore3}{Ano! }
{117}{moore4}{Je NAÈASE vyslyšet naøíkání našich druhù za zdí a pustit je dovnitø! Máme víc ne dost k nasycení a ubytování našich bratrù... nepotøebujeme bıt bohatí zatímco je na svìtì TOLIK chudıch.}
{118}{}{Souhlasím!}
{119}{}{Koneènì nìkdo, kdo má rozum! Proè musí ostatní trpìt, kdy pomoc leí pøímo mezi tìmito zdmi?}
{120}{}{U to nebudu poslouchat. Sbohem.}
{121}{moore5}{Pøíteli... kdy se na tebe podívám, vidím SÍLU. Vidím VÍRU. Nešálí mì zrak? Nebo snad vidí spøíznìnou duši, která sdílí mé názory?}
{122}{}{To si piš!}
{123}{}{Ano! Myslím, e je NAÈASE... aby toto mìsto vybudované z høíchu a otroctví, otevøelo své brány pro všechny! }
{124}{}{Musím odejít. Bylo to hezké popovídání... eh, poslouchání.}
{125}{moore6}{Pak bych se rád zeptal na toto, mùj pøíteli... co všechno jsi SCHOPEN udìlat proto, aby se to dozvìdìl celı svìt?}
{126}{}{No, to závisí na tom, kolik penìz máš u sebe..."pøíteli."}
{127}{}{Nic není nemoné... a ádná vzdálenost není nepøekonatelná, kdy si stojíš za svım slovem a dodríš ho. Udìlám cokoliv bude tøeba!}
{128}{}{Nelíbí se mi smìr, kterım se tento rozhovor ubírá. Hezkı den.}
{129}{moore7}{I kdyby to mohlo znamenat vyhoštìní z této oázy?}
{130}{}{Tohle není ádná oáza, mùj pøíteli. Je to mìsto postavené na sobectví a chamtivosti. Potøebuje zachránit... myslíš, e je vyhoštìní pøíliš vysoká cena? Já myslím, e ne.}
{131}{}{Udìlám cokoliv pro osvobození svıch bratrù!}
{132}{}{Já nevím... co ode mì potøebuješ?}
{133}{}{Hmmm. No, kdy to øíkáš takhle, tak myslím e ne. Hezkı den.}
{134}{moore8}{(Nakloní se k tobì.) Mám kuføík... s ivotnì dùleitımi informacemi o našem cíli. Mùeš ho pro mì doruèit do New Rena? Udìlal bych to sám, ale ostatní Obèané mì sledují...}
{135}{}{Take pøipouštíš, e máš konexe s New Renem? To tì bude nìco stát... "pøíteli."}
{136}{}{Jistì. Dej mi ho.}
{137}{}{Ne, díky... je to pøíliš riskantní. Z toho mì vynech.}
{138}{moore9}{Tady je... doruè ho do New Rena mui jménem John Bishop. Buï opatrnı, mé dítì, a a tvé kroky provází štìstí.}
{139}{}{Mám doruèit tenhle kuføík Johnu Bishopovi? ádnı problém.}
{140}{moore10}{Moje jméno? Jsem Thomas Moore, kazatel slova a pravdy. Co tì ke mnì pøivádí, pøíteli? Hledáš pravdu?}
{141}{}{Pravdu?}
{142}{}{Eh, dnes ne, díky. Sbohem.}
{143}{moore11}{Dokonce i ti, je se jeví jako nevinní, mohou podvádìt posly pravdy... jak mám poznat, e jsi SKUTEÈNİ vìøící?}
{144}{}{Udìlám z tebe skuteèného vìøícího, a ti zarazím svoji botu do zadku!}
{145}{}{JSEM skuteènı vìøící, bratøe. Jak mám dokázat svoji oddanost?}
{146}{}{Vím, e je toto mìsto postavené na základech høíchu a otroctví a e potøebuje nìkoho poèestného, kterı by to napravil!}
{147}{}{Tøeba se ještì nìkdy potkáme.}
{148}{moore12}{Ignorantskı barbare! Máš uši, ale neslyšíš! Máš oèi, ale nevidíš! Zmiz mi z oèí, bídnı èerve!}
{149}{}{Bídnı... eh... èer... coe? Takhle se mnou nikdo mluvit nebude! Doufám e jsi bezdìtnı, protoe jinak budou tvoje dìti bez otce, mrtvolo...}
{150}{}{Takhle se mnou nikdo mluvit nebude a u vùbec ne nìjakı ubohı kazatel. Myslím, e je naèase, abys dostal lekci.}
{151}{}{Uklidni se. Odcházím.}
{152}{moore13}{Hmmmmmm. Èlovìk si musí dávat pozor na zmije, kteøí káou slova pravdy, avšak v jejich srdci hnízdí faleš.}
{153}{}{Ámen, bratøe! }
{154}{}{Pokud mezi námi není dùvìra, tak radìji odejdu. Sbohem.}
{155}{}{Eh... jistì. Tøeba se ještì nìkdy potkáme.}
{156}{moore14}{Coe?! Jak se OPOVAUJEŠ mì vydírat, ty... ty... (Zamraèí se.) ...máš moji pozornost.}
{157}{}{V tom pøípadì si promluvme o penìzích, co øíkáš?}
{158}{moore15}{Co... kde jinde bych mìl kázat ne tam, kde je to nejvíc potøeba?}
{159}{}{Asi máš pravdu. Kdo jsi?}
{160}{}{Pøesnì tak, bratøe! Hlásej pravdu!}
{161}{}{Pøesnì tak! Toto mìsto je postavené na základech høíchu a otroctví a potøebuje nìkoho poèestného, kterı by to napravil!}
{162}{}{Eh... jasnì. No, hezky se mi s tebou povídalo. Sbohem.}
{163}{moore16}{Tady... v tomto kuføíku jsou má èísla úètù. Doruè ho Johnu Bishopovi do New Rena a on ti k nim dá pøístup.}
{164}{}{Zapomeò na to. Stejnì tì prásknu.}
{165}{}{Kašlu na peníze, nejdu do Rena.}
{166}{}{Vıbornì! Doufám, e to bude stát za to.}
{167}{moore17}{Zdá se, e tì pøíroda u potrestala, divochu. Snad jednou budeš spasen i ty.}
{168}{moore18}{Eh... jak myslíš. Dávej si v pustinì pozor, mùj jednoduchı pøíteli.}
{169}{}{Urf.}
{170}{moore19}{Take, mùj pøíteli, u sis to rozmyslel?}
{171}{}{Rozmıšlel jsem o tom, e by mohlo mít tvoje tajemství docela velikou cenu. Chápeš?}
{172}{}{Spatøil jsem svìtlo, bratøe... co mám udìlat?}
{173}{}{Ne, díky. Hezkı den.}
{174}{moore20}{Eh? Co tady dìláš? Nemìl jsi snad doruèit...}
{175}{}{...Bishopovi kuføík? No, ZKUSIL jsem to, akorát e si pøeèetl malou poznámku, co jsi zanechal v kuføíku, a pokusil se mì ZABÍT. Legraèní, e? Doufám, e jsi pøipravenı zemøít, Moore.}
{176}{}{Udìlal jsem to, ale vrátil jsem se, abych z tebe udìlal cedník a pohøbil tì hluboko pod zem.}
{177}{}{Jen tì kontroluju. Nashle.}
{178}{moore21}{Á! Vítej zpìt, ty jen hledáš pravdu! Jak ti mohu dnes pomoci?}
{179}{}{Co víš o NCR?}
{180}{}{Chci se zeptat: Proè má Vault City otroky? Øíká se pøece, e je to svobodné mìsto.}
{181}{}{Chci slyšet slovo pravdy, bratøe!}
{182}{}{Toto mìsto je postavené na základech høíchu a otroctví a já jsem tu, abych to napravil!}
{183}{}{Dnes nic, díky.}
{184}{moore22}{Vím, e se snaí vzkøísit pravdu a spravedlnost, ale my nehneme ani prstem.}
{185}{}{Co mùeme dìlat?}
{186}{}{To zní trochu jako zrada.}
{187}{}{To je škoda. No nic, sbohem.}
{188}{moore23}{Mùeme otevøít naše brány dokoøán a pøivítat je! Potøebují naši pomoc, ale my ji STÁLE pøehlííme!}
{189}{}{Ámen! Vyspìlá technologie Vault City by mìla bıt pøístupná pro všechny a ne aby se hamonila.}
{190}{}{Hmm... já ti nevím. Máme se tady docela dobøe. Opravdu je potøebujeme? Koneckoncù, díky nim se sníí naše ivotní úroveò... a moná nás i nìèím nakazí.}
{191}{}{Hmmm. No, nìco na tom bude. Sbohem.}
{192}{moore24}{Na to neznám odpovìï, jeliko mìsto postavené na základì otroctví nemùe bıt nikdy skuteènì svobodné.}
{193}{}{Jo, ale mùou zbohatnout, e?}
{194}{}{Tvoje slova... je hudba pro mé uši. Moná, e je osvobození otrokù a jejich pøivítání to nejlepší pro Vault City.}
{195}{}{Mìli bychom osvobodit otroky a pøijmout je za své bratry!}
{196}{}{Ále, jdi s tím do háje. Otroctví... a Vault City... tady bude ještì pìknì dlouho.}
{197}{}{Zajímavé. Tøeba se ještì nìkdy setkáme.}
{198}{moore25}{Vidím, e jsi obchodník s lidskım masem. Nemám CO øíct lidem, jako jsi ty.}
{199}{}{Uurmph.}
{200}{}{Ecch.}
{201}{}{Portzebie.}
{202}{}{Odbelhat se.}
{203}{}{Hele, choval jsem se jako otrokáø jen proto, abych získal informace.}
{204}{}{No, chci se na nìco zeptat: Proè má Vault City otroky? Øíká se, e je to svobodné mìsto.}
{205}{}{To, e nìkdo páchá ty nejhorší skutky, ještì neznamená, e to tak i myslí.}
{206}{}{Budi. Nashle.}
{207}{}{Koukám, e se tu nesnášenlivosti daøí. Hezkı den.}
{208}{moore26}{Pøedstírání je to samé jako èin. Táhni, otroku.}
{209}{}{Ale já se ze svıch chyb pouèil!}
{210}{}{Tak a dost. Je naèase ti udìlat díru do bøicha a podívat se, co je uvnitø...}
{211}{}{Tak dobøe.}
{212}{moore27}{Nemám co øíct nìkomu tak prohnilému, jako jsi ty. Odejdi.}
{213}{}{Chceš prohnilou povahu? Já ti UKÁU, co je to prohnilá povaha...}
{214}{}{Vidím chyby své povahy. Pøicházím pro odpuštìní a chci slyšet pravdivé slovo!}
{215}{}{Moje srdce bylo rozpolcené myšlenkou lidské krutosti!}
{216}{}{Budi. }
{217}{moore28}{Vítej zpìt, poutníku! Doruèil jsi informace, jak jsem ádal?}
{218}{moore29}{Vítej zpìt, poutníku! Jak ti mohu dnes pomoci?}
{219}{}{Nech si ty kecy, "Tomcate." Vím všechno o tobì a tvıch "kamarádech" dole v NCR.}
{220}{}{Proè pracuješ pro NCR? Já myslel, e jsi poctivı èlovìk.}
{221}{}{Ano... víš, Bishop øíkal, e pracuješ pro NCR. Je to pravda?}
{222}{}{Chci ti jen øíct, e u je to hotové.}
{223}{moore30}{Je potìšující slyšet, e má slova zasela pochybnosti v tvém srdci. Snad se naše cesty opìt nìkdy zkøíí.}
{224}{}{Snad jo. Víra s tebou, bratøe.}
{225}{}{Sbohem.}
{226}{moore31}{NCR se snaí získat spravedlnost a vládu pro celou Kalifornii a Vault City má moc na to, aby to dokázalo! Pomysli na to, co bychom mohli dokázat, kdybychom mìli pøístup k technologii Vault City!}
{227}{}{To ti neeru. Myslím, e bude lepší, kdy tì prásknu... pokud si samozøejmì nechceš koupit moje mlèení.}
{228}{}{Ale to je technologie Vault City. Ostatní na ni nemají ádné právo.}
{229}{}{Ze lí a proradnosti nikdy nic dobrého nevzejde, Moore. Vault City si samo sobì nalhává u nìkolik let... tohle není úplnì nejlepší zpùsob, nemyslíš?}
{230}{}{Hmm. Musím si to promyslet.}
{231}{}{Máš pravdu. Omlouvám se, e jsem o tobì pochyboval.}
{232}{moore32}{VŠICHNI lidé mají právo na plody starého svìta. Technologie se musí sdílet, ne hamonit.}
{233}{}{Ty to prostì NECHÁPEŠ, e jo, Moore? Moná ti stará dobrá nakládaèka vrátí trochu rozum.}
{234}{}{Jo, jo, nech u tìch "svatouškovskejch" kecù. Naval prachy, nebo tì prásknu.}
{235}{}{Musím si to promyslet. Sbohem.}
{236}{moore34}{Prosím, doruè tento kuføík do New Rena, pøíteli. A pospìš si!}
{237}{moore33}{Co mùeme dìlat? Pøeci šíøit pravdu, to musí staèit. Nech svìtlo provází tvùj krok pustinou, mùj pøíteli. Pravda budi tvım svìtlem, s ním se neztratíš.}
{238}{}{Díky, bratøe. Udìlám, jak øíkáš.}
{239}{moore35}{Slyšel jsi u dnešní zprávy?}
{240}{moore36}{Slyšte pravdu! Pravda vás uèiní volnım!}
{241}{moore37}{Otroctví toto mìsto znièí!}
{242}{moore38}{Musíme otevøít brány Vault City a pøijmout okolní svìt!}
{243}{moore39}{Proè nemùeme sdílet naše bohatství?! }
{244}{moore40}{Copak neslyšíte náøky tìch, je trpí za našimi branami?!}
