{100}{}{Vidíš místní zdravotní sestru, Phyllis.}
{101}{}{Vidíš štíhlou mladou enu. Je slabkdì cítit dezinfekcí.}
{102}{}{Vidíš zdravotnici Phyllis.}
{103}{}{Vidíš štíhlou mladou enu. Je slabkdì cítit dezinfekcí.}
{104}{phl45}{Riskoval jsi vlastní ivot, abys nás VŠECHNY zachránil. Jsi nejstateènìjší èlovìk, jakého jsem kdy poznala.}
{105}{phl46}{Vetøelec! Pomóóóccc! Stráe!}
{106}{phl47}{Mutant! Pomóóóccc! Stráe!}
{107}{phl48}{Ghoul! Pomóóóccc! Stráe!}
{108}{phl49}{Potøebuju si vyjet Gregoryho záznamy...}
{109}{phl50}{Tak se podíváme na rozvrh. Máme objednané oèkování tøech sluebníkù na druhou odpoledne...}
{110}{phl51}{To pípání mì dohání k šílenství...}
{111}{phl52}{Pøísahám, e se ty lékaøské databáze mezi sebou domlouvají...}
{112}{phl53}{Tak co tu máme... tøi injekce, dezinfekèní, tøi ampule Rad-X...}
{113}{phl54}{Mìla bych pøipravit Dr. Troye na zítøejší pøednášku...}
{114}{phl55}{Jo, u mì ZASE donutili pracovat do noci. Vìtšinou vyplòuju seznamy.}
{115}{phl56}{Radìji pøijï ráno.}
{116}{phl57}{Myslím, e bych tì mohla napsat zítra na seznam, pokud je to naléhavé.}
{117}{phl58}{Nemùu se doèkat, a pùjdu domù. Vyplòování tìhlech seznamù mì unavuje.}
{118}{phl59}{Bude lepší, kdy pøijdeš ráno. Musím ještì vyplnit tyhle seznamy.}
{119}{phl60}{Chudák Dr. Troy. Nikomu NIC neudìlal!}
{120}{phl61}{Proè vyhnali Dr. Troye do exilu?}
{121}{phl62}{Doufám, e se Dr. Troyovi tam venku nic nestane...}
{122}{phl63}{Hmm. Teï si s tebou nemùu povídat, mám moc práce. Jestli nìco potøebuješ, jdi navštívit Dr. Troye.}
{123}{phl1}{Zdravím. Ještì jsem tì tady nikdy nevidìla... ty jsi novı Obèan?}
{124}{phl2}{Zdravím.}
{125}{}{Op-èan?}
{126}{}{Spravím?}
{127}{}{Mám bebí... *fòuk*... ouvej BOLÍ.}
{128}{}{Ve skuteènosti jsem novı Kapitán stráí.}
{129}{}{Jo, jsem Obèan teprve chvíli.}
{130}{}{Eh, jo, jsem Obèan teprve chvíli.}
{131}{}{Promiò, myslel jsem, e jsi nìkdo jinı. Hezkı den.}
{132}{phl3}{Jéje, vdy ty máš zranìní, e? Promiò, mìla jsem dávat vìtší pozor. Jdi za Dr. Troyem. On se o tebe postará.}
{133}{}{Eh... dobe? Jojo.}
{134}{}{Mùu se nejdøív na nìco zeptat?}
{135}{}{Díky. Pùjdu se za ním hned podívat.}
{136}{phl4}{Aha! Ty musíš bıt jeden ze sluebníkù, které sem pøidìlili na práci pøes den. Musíš... eh, hmmm. TY JÍT ZA MARTINEM.}
{137}{phl5}{Eh... hmmm. Ještì jednou mì poslouchej, tentokrát pozornì: TY JÍT ZA MARTINEM.}
{138}{}{TYDİT MARTIN.}
{139}{}{Mám bebí... *fòuk*... ouvej BOLÍ.}
{140}{}{Odbelhat se.}
{141}{phl6}{ANO, MARTIN. JÍT NA SPODNÍ PODLAÍ.}
{142}{}{ANO, MAR-TIN. JÍT NA SPODNÍ PODLAÍ.}
{143}{}{Mám bebí... *fòuk*... ouvej BOLÍ.}
{144}{}{Odbelhat se.}
{145}{phl7}{JÍT NA SPODNÍ PODLAÍ. PODLAÍ - TØI. TEÏ.}
{146}{}{JÁ JÍT TEÏ NA SPODNÍ PODLAÍ TØI.}
{147}{}{Mám bebí... *fòuk*... ouvej BOLÍ.}
{148}{}{Odbelhat se.}
{149}{phl64}{Moná, e naši sluebníci trpí nìjakım syndromem nedostatku inteligence...}
{150}{}{Aha! Tak vítejte ve Vault City, Kapitáne.}
{151}{}{No, tak vítej ve Vault City, Obèane.}
{152}{}{Nestává se pøíliš èasto, abychom tu vidìli nìkoho nového. Jmenuju se Phyllis. Jak se jmenuješ ty?}
{153}{}{Jmenuju se }
{154}{}{Jsem }
{155}{}{A ti budu chtít øíct svoje jméno, tak ti ho øeknu, "Syfilis"... nebo jak se to sakra jmenuješ.}
{156}{}{Promiò, ale nemám èas si s tebou povídat.}
{157}{phl8}{Co si to...! Ještì NIKDY jsem nepotkala nìkoho tak nevychovaného, jako jsi ty. Bude lepší, kdy odejdeš. Hned.}
{158}{}{Radìji si dávej pozor na pusu, nebo budeš mít problém.}
{159}{}{Jak myslíš. Stejnì si u s tebou nechci povídat.}
{160}{phl9}{Stráe! Dr. Troyi! Pomoc!}
{161}{}{Tak takhle ty, jo? No dobøe...}
{162}{phl10}{Jsem místní zdravotní sestra. Pracuju pro Dr. Troye.}
{163}{}{Co si myslíš o Dr. Troyovi?}
{164}{}{Mùu se tì na nìco zeptat?}
{165}{}{Skvìle. Potøebuju lékaøskou pomoc.}
{166}{}{Promiò, ale nemám èas si s tebou povídat.}
{167}{phl11}{Vítej zpìt. Mùu ti s nìèím pomoct?}
{168}{phl12}{Samozøejmì. Co chceš vìdìt?}
{169}{}{Co si myslíš o Dr. Troyovi?}
{170}{}{Mùeš mi øíct, kde je centrální poèítaè?}
{171}{}{Potøebuju vyléèit.}
{172}{}{Co tady dìláš?}
{173}{}{Mùete mi øíct nìco o Vault City?}
{174}{}{Vlastnì u nic. Ale stejnì díky.}
{175}{phl13}{No, Dr. Troy dokáe bıt nìkdy dost pøísnı, ale jinak je to dobrı èlovìk. Vault City má štìstí, e ho má.}
{176}{}{No nevím, chce po mì propašovat do mìsta nìjaké drogy.}
{177}{}{Mùu se ještì na nìco zeptat?}
{178}{}{Díky za tvùj èas. Sbohem.}
{179}{}{}
{180}{}{}
{181}{phl14}{Urèitì? To bych do Dr. Troye neøekla. Je pravda... e poslední dobou velmi tvrdì pracuje... ne, ne, to je nesmysl. Urèitì se mılíš.}
{182}{}{Myslím e ne. Øekl mi zcela jasnì, co ode mì chce.}
{183}{}{Hmmmm. Mùu se ještì na nìco zeptat?}
{184}{}{Tak na to zapomeò.}
{185}{phl15}{Bıt tebou, tak si dám VELKİ pozor na to, co øíkáš o Dr. Troyovi ve Vault City. Je to váenı èlen naší spoleènosti.}
{186}{}{Tak dobøe. Mùu se ještì na nìco zeptat?}
{187}{}{Díky za upozornìní. Asi si pùjdu popovídat s nìkım jinım.}
{188}{phl16}{Je dole na tøetím podlaí, pokud si dobøe vzpomínám. U jsem dole nebyla celou vìènost.}
{189}{}{Proè ne?}
{190}{}{Mùu se ještì na nìco zeptat?}
{191}{}{Díky za informace. Sbohem.}
{192}{phl17}{Ani nevím. Nemám dùvod chodit dolù do Vaultu. V souèasné dobì je pøevánì vyuíván jako skladovací prostor. Dole je jen jedinı èlovìk, Martin, a... no, jen tak mezi námi, není to zrovna nejlepší øeèník.}
{193}{}{Ehh... proè z nìj udìlali øeèníka, kdy mu to nejde?}
{194}{}{Mùu se ještì na nìco zeptat?}
{195}{}{Aha. Díky za informace.}
{196}{phl18}{Eh... asi bude lepší, kdy si s ním o tom pùjdeš promluvit. Vy dva toho moná máte spoleèného víc, ne jsem si pùvodnì myslela.}
{197}{}{Mùu se nejdøív na nìco zeptat?}
{198}{}{Tak dobøe. Pùjdu si s ním promluvit.}
{199}{phl19}{Vault City? No, ve skuteènosti není moc o èem mluvit. Chci øíct, jsem Obèankou u od narození... ale ve Vault City moc zábavy není. Vlastnì tu není ádná.}
{200}{}{To je škoda, e si taková pøekrásná mladá ena jako ty nemùe najít ÁDNOU zábavu ve Vault City.}
{201}{}{ádná? Ale no tak.}
{202}{}{Chci se ještì na nìco zeptat...}
{203}{}{To nic, jen se tak ptám.}
{204}{phl20}{Poslyš, já vím, e jsi novı Obèan, take ti nechci brát nadšení z tvého Obèanství, ale tohle mìsto dokáe bıt obèas VELMI nudné.}
{205}{}{Nudné? Jak to?}
{206}{}{To je opravdu škoda. Chci se ještì na nìco zeptat...}
{207}{}{To nic. Je mi to líto.}
{208}{phl21}{Všiml sis, jak jsou si všichni podobní? A jak jsou STAØÍ? Vìtšina pøednášek a spoleèenskıch akcí se orientuje na osmdesátníky. Je mi teprve dvacet pìt let, ale v tomhle mìstì se cítím na padesát.}
{209}{}{Eh... osm-desátníky? Máš na mysli hodnosti stráí?}
{210}{}{Kdy u mluvíš o stáøí, všiml jsem si, e ve mìstì nejsou ádné dìti.}
{211}{}{Všiml jsem si podobnosti mezi Obèany.}
{212}{}{To nic, jen se tak ptám.}
{213}{phl22}{Eh ne... "osmdesátníci" je pøídavné jméno, které se vztahuje na osoby, kterım je osmdesát. }
{214}{}{Eh, dobøe. Mùu se ještì na nìco zeptat?}
{215}{}{Tak dobøe. Tøeba si popovídáme pozdìji.}
{216}{phl23}{No... ano. Opravdu tu ádné nejsou. Zatím. Nevím, jestli ti to u nìkdo øíkal, ale Vault City je plánovaná spoleènost. Další tìhotenskı cyklus nás èeká a za nìkolik let.}
{217}{}{Eh... tìhotenskı cyklus?}
{218}{}{Mùu se ještì na nìco zeptat?}
{219}{}{Aha. No, díky za informace.}
{220}{phl24}{Ano. Tìhotenství je povolené jen v urèitıch letech. Zavedla to mìstská rada.}
{221}{}{Co kdy i tak otìhotníš?}
{222}{}{Aha. Chci se ještì na nìco zeptat...}
{223}{}{Aha. No, díky za informace.}
{224}{phl25}{A jak bych k tomu pøišla?}
{225}{}{Eh, pokud vím, tak SEX mùe zpùsobit otìhotnìní.}
{226}{}{Zapomeò na to. Poslyš, chci se na nìco zeptat...}
{227}{}{Zapomeò na to. Radìji u pùjdu.}
{228}{phl26}{Aha, ty myslíš pohlavní styk? Pohlavní styk je mimo tìhotenské cykly stále povolen.}
{229}{}{To z nìj nikdo neotìhotní?}
{230}{}{Aha. Chci se ještì na nìco zeptat...}
{231}{}{To nic, jen se tak ptám.}
{232}{phl27}{Kdepak... víš, naše otìhotnìní není následkem pohlavního styku.}
{233}{}{Bojím se zeptat, ale stejnì se zeptám.}
{234}{}{Víc u o tom nechci vìdìt, ale chci se ještì na nìco zeptat...}
{235}{}{To u by staèilo, u to nebudu poslouchat.}
{236}{phl28}{Mui Obèani "darují" Auto-Doku ve Vaultu svùj... materiál a nejvhodnìjší dárci jsou vybráni poèítaèem. Potom je vhodná Obèanka oplodnìna Auto-Dokem.}
{237}{}{Mùu taky "darovat"?}
{238}{}{To u nejsou eny schopné otìhotnìt pohlavním stykem? A co náhodná otìhotnìní?}
{239}{}{Víš, chci se tì zeptat na nìco jiného.}
{240}{}{Mùeš mì omluvit? Musím se jít podívat, jestli mùu zrušit svoje Obèanství.}
{241}{}{Myslím, e budu muset jít nìkam, kde se budu moct v klidu vyzvracet. Sbohem.}
{242}{phl29}{Ale samozøejmì. Uvítáme tvùj pøíspìvek. Vault City se urèitì bude hodit èerstvı genetickı materiál.}
{243}{}{Tak dobøe...}
{244}{}{Poslyš, mùu dostat nìjakı èasopis nebo nìco podobného?}
{245}{phl30}{Tvùj pøíspìvek je pùsobivı... zdá se, e jsi docela nadanı. Jak se cítíš?}
{246}{phl31}{Vıbornì! Díky.}
{247}{phl32}{Hmmm. Moná, e tvùj pøíspìvek není a tak kvalitní, jak jsem si myslela. V kadém pøípadì dìkuju.}
{248}{}{Musím øíct, e mi nikdy nechybìl primitivní zpùsob ivota v Arroyu víc ne v tuhle chvíli.}
{249}{}{Nikdy jsem necítil potøebu doteku víc ne v tuhle chvíli.}
{250}{}{Ne, to JÁ dìkuju.}
{251}{phl33}{No, vlastnì... víš, je to nìco, o èem jsem poslední dobou pøemıšlela. Zdá se, e Obèanky nemívají náhodná otìhotnìní. Jediná úspìšná otìhotnìní byla provedena pouze pomocí Auto-Doku.}
{252}{}{Víš, zbytková radiace mùe zpùsobit neplodnost, v horším pøípadì i poškodit chromozomy. Moná by stálo za to se na to podívat.}
{253}{}{Moná je to jen tím, e tu sex nikdo moc neprovozuje.}
{254}{}{To nic, jen se tak ptám.}
{255}{phl34}{Víš, myslím si to samé. Moná bych se o tom mìla zmínit Dr. Troyovi. Sice má poslední dobou moc práce, ale pøíští tìhotenskı cyklus tu bude co nevidìt, take...}
{256}{}{Mùu se vás ještì na nìco zeptat?}
{257}{}{Zmínit se o tom Dr. Troyovi zní jako dobrı nápad. Hodnì štìstí.}
{258}{phl35}{Jako by byli všichni... naklonovaní. Všichni se oblékají stejnì, chovají se stejnì a nejhorší na tom je, e všichni vypadají šastnì. Já... no, nìkdy se bojím, e skonèím jako oni. Nezní to trochu hloupì?}
{259}{}{Ani ne. Ten tlak pøizpùsobit se ostatním tu musí bıt poøádnì silnı, obzvláš kdy si uvìdomíme, jak moc je Vault City izolovaná spoleènost.}
{260}{}{To nic, jen se tak ptám.}
{261}{phl36}{Jo, nìkdy to mùe bıt opravdu stresující, ale koukám, e ti jen kazím tvùj názor na Vault City. Nevykládej si to špatnì, i tak je to skvìlé místo k ivotu.}
{262}{}{Myslím, e by ses moná mìla podívat za zdi Vault City nebo si alespoò promluvit s nìjakımi kupci na Pøedmìstí. Moná by ti mohli pomoct trochu rozšíøit obzory.}
{263}{}{Nepochybnì to má svoje vıhody. Mùu se ještì na nìco zeptat?}
{264}{}{Jsem rád, e jsi šastná. Tøeba si ještì nìkdy popovídáme.}
{265}{phl37}{No, chtìla jsem se jít podívat ven za bránu, ale ostatní Obèané mì pøed tím varovali...}
{266}{}{O dùvod víc proè to udìlat. Snad nechceš bıt jako OSTATNÍ Obèané, nebo jo? Oni se u nezmìní.}
{267}{}{No, venku to mùe bıt nebezpeèné. Poslyš, mùu se ještì na nìco zeptat?}
{268}{}{A mají pravdu. Nejspíš to není dobrı nápad. Radìji u pùjdu.}
{269}{phl38}{Víš, asi máš pravdu. A bude pøíleitost, pùjdu se podívat ven. Ráda bych se dozvìdìla víc o okolním svìtì.}
{270}{}{Skvìle. Poslyš, mùu se ještì na nìco zeptat?}
{271}{}{Urèitì ti to prospìje. Mìj se.}
{272}{phl39}{Prosím?}
{273}{}{Nemohl jsem si nevšimnout, e jsi atraktivní mladá ena, která by si mìla èas od èasu vyrazit ven. Co takhle ty, já a veèeøe?}
{274}{}{U nic. Mùu se ještì na nìco zeptat?}
{275}{}{To nic, jen se tak ptám.}
{276}{phl40}{Och. Já... víš, ráda bych, ale nemùu.}
{277}{phl41}{Och. No, to... bych ráda.}
{278}{}{Ale no tak, jsem tu teprve chvíli. Ještì se dostanu do maléru, kdy budu sám.}
{279}{}{Tak dobøe. Mùu se ještì na nìco zeptat?}
{280}{}{To nic, jen se tak ptám.}
{281}{}{Skvìle! Tak pojïme.}
{282}{phl65}{Díky za úasnı veèer.}
{283}{phl66}{Eh... jistì. Tøeba si vyrazíme nìkdy jindy. Já... eh, zavolám ti. Nashle.}
{284}{phl42}{Promiò, ale ne.}
{285}{}{Tak dobøe. Mùu se místo toho na nìco zeptat?}
{286}{}{To nic, jen se tak ptám.}
{287}{}{No, je vidìt, e se pøedsudku z lesbického sexu ve Vault City opravdu daøí. Nashle.}
{288}{}{. Co tu dìláš?}
{289}{}{. Mùu se na nìco zeptat?}
{290}{}{Aha a já u myslel, e tu nejsou ádné dìti, protoe hraju evropskou verzi Falloutu 2. Sbohem.}
{291}{}{Daroval jsi Vault City svùj kvalitní genetickı materiál.}
{292}{}{Daroval jsi Vault City svùj èerstvı genetickı materiál.}
{293}{}{Daroval jsi Vault City svùj genetickı materiál... a u je jakkoliv kvalitní.}
{294}{}{Podaøilo se ti pøesvìdèit Phyllis, aby si promluvila s Dr. Troyem o moné neplodnosti ve Vault City.}
{295}{}{Podaøilo se ti pøesvìdèit Phyllis, aby se podívala za brány Vault City.}
{296}{}{Rychle zjišuješ, e je Phyllis nezajímavá a sobecká. Rozhodneš se, e u nikdy nebudeš randit s nìkım, jako je ona.}
{297}{}{Kdy u mluvíme o osmdesát... eh, o starıch lidech, všiml jsem si, e ve Vault City nejsou ádné dìti.}
