{100}{}{Vidíš staøíka se známkami šílenství.}
{101}{}{Vidíš Starého Joea, místního blázna.}
{102}{ianoj1}{Ahoj. Dlouho jsme se nevidìli.}
{103}{}{My se známe?}
{104}{}{Jo, jasnì. U to bude nìjaká doba. Co jsi celou tu dobu dìlal?}
{105}{ianoj2}{No, u to bude nìjaká doba. Co jsi celou tu dobu dìlal?}
{106}{}{To a taky tamto. Odkud mì znáš?}
{107}{}{Podívej, staøíku, vùbec nevím, kdo sakra jsi.}
{108}{ianoj3}{Jo, to teda. No, potuloval jsem se všude monì a nakonec jsem skonèil tady na tomhle bohem zapomenutım místì. U to není jako za starejch dobrejch èasù. U ne, kamaráde.}
{109}{}{Jó, starı dobrı èasy. Vzpomínáš, jak jsme tenkrát...}
{110}{}{U to není jako døív, to teda ne. Poslyš... co máme vlastnì spoleèného?}
{111}{ianoj4}{Ty si na mì nevzpomínáš, e ne? No, zdáš se mi trošku moc mladej.}
{112}{}{Co se mi tím snaíš øíct?}
{113}{ianoj5}{Ale vypadáš tak povìdomì. Ach, moje oèi u nejsou to, co bıvaly. No nic, pøeju hezkej den.}
{114}{}{Eh, jo... sbohem.}
{115}{ianoj6}{Jo, udìlali jsme Vùdci ze ivota peklo, e jo? Ale po tvım odchodu to šlo pìknì do sraèek. Musel jsem se pøestìhovat a zmìnit si jméno. Co se stalo s tebou?}
{116}{}{Uíval jsem si ivota v jedné malé vesnièce.}
{117}{ianoj7}{No, radši si tu dávej na sebe bacha. U to není taková sranda jako døív. Radši si hlídej zadek.}
{118}{}{Dobøe, díky.}
{119}{ianoj8}{Jo, chvíli jsem hledal ten tvùj Vault, ale nikdy jsem ho nenašel. Máš nìjakı zajímavı historky pro svıho starıho pøítele Iana?}
{120}{}{Iana?}
{121}{ianoj9}{Jo, Ian. Nevzpomínáš si na mì? U je to pár let. Èlovìk by si myslel, e se nedá zapomenout na svıho nejlepšího kámoše. Teda... a na to støílení do zad. Za to se ti ještì jednou omlouvám.}
{122}{}{Promiò, ale ty si nejspíš myslíš, e jsem Zakladatel. Moje vesnice byla zaloena èlovìkem, kterı pocházel z Vaultu.}
{123}{ianoj10}{Aha, tak teï u to dává trošku vìtší smysl. No, jsem rád, e mìl mùj pøítel dobrej ivot. Starej Ian má pro tebe radu. Dávej tam venku na sebe pozor. Tohle místo není tak skvìlı, jak se zdá. }
{124}{}{Co se tady dìje?}
{125}{ianoj11}{No, Obèané Vault City si o sobì hodnì myslí a moc se nezajímají o lidi, jako jsem já nebo ty. Tohle si vezmi. Ochrání tì, kdy se vìci trochu vymknou z ruky. Poslyš, asi by tì nemìli vidìt, jak mluvíš se starım šílencem, take bude lepší, kdy u pùjdeš.}
{126}{}{Díky za pomoc. Nashle.}
{127}{ianoj23}{Nech starıho mue odpoèívat.}
{128}{ianoj24}{Vypadáš tak povìdomì...}
{129}{ianoj25}{Nech mì teï o samotì.}
{130}{ianoj26}{Radši odejdi.}
{131}{ianoj27}{Budou tì podezírat, jestli spolu budeme dál mluvit.}
{132}{ianoj28}{Bì u. A je na tebe mùj starı pøítel hrdej.}
{133}{}{Díky. Vlastnì ještì jedna vìc. Snaím se pomoct jedné malé vesnici severovıchodnì odsud. Chlapík jménem Connar mi øekl, a tì vyhledám a promluvím si s tebou.}
{134}{ianoj12}{Connar, jo? To je dobrej chlap. Dohlíím tu pro nìj na nìjakı vìci. Take co vlastnì Connar chce?}
{135}{}{Snaí se získat nìjaké zbranì. Myslí si, e by s nimi dokázali odráet hlídky Vault City.}
{136}{ianoj13}{Aha, take to je ten jeho novej plán, jo? V tom pøípadì zajdi do obchodu na Pøedmìstí a promluv si s Harrym. Øekni mu, e tì posílá Connar a on u ti pomùe. Mám pocit, e si pro takovı pøípady pár zbraní schovává, ale nejsem si tak úplnì jistej, jestli je to ten nejlepší zpùsob, jak øešit problémy.}
{137}{}{Dobøe, pùjdu si promluvit s Harrym. Mìj se, starej brachu.}
{138}{}{Proè? Co tím myslíš?}
{139}{ianoj14}{Connar a jeho lidi maj silnıho bojovnıho ducha, ale v tomhle pøípadì to nebude staèit. Vault City má takøka neomezenı prostøedky a nakonec by stejnì vyhráli. Nìkdy je lepší si o tom s nìkım promluvit a pokusit se to vyøešit diplomaticky. Pøesnì to jsem se nauèil od svıho starıho pøítele Zakladatele. Vrchní èlen rady Vault City McClure se zdá bejt jako rozumnej èlovìk. Tøeba by s ním bylo monı uzavøít nìjakou dohodu.}
{140}{}{Hmm... moná o tom popøemıšlím. Díky za všechno. Nashle.}
{141}{}{V tom pøípadì si s ním moná pùjdu promluvit. Nicménì by mì zajímali ti krtèí potkani, co ochraòují vesnici.}
{142}{ianoj15}{Jo, co je s nimi?}
{143}{}{Nevíš, odkud jsou nebo kdo je ovládá?}
{144}{ianoj16}{Tak to nevím. Pøišla s nimi parta ghoulù. Nosili divnı amulety a mluvili o nìjakı "Obrodì". Víc nevím. Moná by bylo lepší se zeptat v Gecku. Je to tam plnı ghoulù. Kdy u tak mluvíme o velkejch krysách, u jsem ti povídal, jak jsme tenkrát se Zakladatelem šli do Vaultu 15?}
{145}{}{Ne, ale ten pøíbìh velmi dobøe znám, jeliko se stal v mém kmeni svatou legendou. Moná se pùjdu podívat do Gecka a tøeba se mi nìco podaøí zjistit. Mìj se, Iane.}
{146}{}{Eh, díky za tip. Ale myslím, e jsi pøesnì ten mu, kterého hledám. Connar mì posílá kvùli jedné záleitosti.}
{147}{}{Tak moment! Connar mi øíkal, e máš nìjaké informace.}
{148}{}{Ne, ale ten pøíbìh velmi dobøe znám, jeliko se stal v mém kmeni svatou legendou. Moná se pùjdu podívat do Gecka a tøeba se mi nìco podaøí zjistit. Mìj se.}
{150}{}{Má zájem o nìjakou vızbroj, aby mohli odrazit hlídky Vault City, ale podaøilo se mi ho pøesvìdèit, e existuje i lepší øešení.}
{151}{ianoj17}{Aha, take to je ten jeho novej plán, jo? Jó, Connar je dobrej chlap, ale ne vdycky všechno promyslí. Nìkdy je jlepší si o tom s nìkım promluvit a pokusit se to vyøešit diplomaticky. Pøesnì to jsem se nauèil od svıho starıho pøítele Zakladatele.}
{152}{}{Nemáš tušení, s kım v radì si o tom mùu promluvit?}
{153}{}{Myslím, e starší èlen rady McClure by mohl bıt tím muem. Co myslíš?}
{154}{ianoj18}{Starší èlen rady Vault City, McClure, je rozumnej èlovìk. Moná by s ním bylo monı uzavøít nìjakou dohodu.}
{155}{}{Dobøe. Zkusím si s ním promluvit. Nashle.}
{156}{}{V tom pøípadì si s ním moná pùjdu promluvit. Nicménì by mì zajímali ti krtèí potkani, co ochraòují vesnici.}
{157}{ianoj19}{Je tvoje nejvìtší nadìje. Je v mìstskı radì jedinej, komu ještì zbyl zdravej rozum.}
{158}{}{Dobøe. Zkusím si s ním promluvit. Nashle.}
{159}{}{V tom pøípadì si s ním promluvím. Ale zajímali by mì ti krtèí potkani, co ochraòují vesnici.}
{200}{}{Poslyš, jestli jsi opravdu ten Ian, kterı cestoval s mım pøedkem, pak mám na tebe otázku.}
{201}{ianoj20}{Dobøe, poslouchám.}
{202}{}{Jak je sakra moné, e jsi ještì naivu? Musí ti bıt pøes sto let. Navíc je v pamìtech Zakladatele zmínka o tom, e tì v Necropolisu seehl supermutant s plamenometem.}
{203}{ianoj21}{(Chvíli se chraplavì smìje, poté se uklidní a setøe si z oèí nìkolik slz.) No, to je teda síla. Seehnutej plamenometem, haha! Víš, øekl jsem Vyvolenımu, aby si vymyslel nìjakej pøíbìh o mı smrti, paè jsem nechtìl, aby se mì nìjací staøí nepøátelé pokusili zabít. Proto jsem si zmìnil jméno. Øekl jsem mu, aby si o mì vymyslel nìco hrdinskıho a zdá se, e to vzal doslova. Haha, to se mi líbí.}
{204}{}{Hehe, tím se to asi vysvìtluje. Ale zajímali by mì ti krtèí potkani, co ochraòují vesnici.}
{205}{}{To stále nevysvìtluje, jak je moné, e jsi naivu i po tolika letech.}
{206}{ianoj22}{Hele, jsem z toho zmatenej stejnì jako ty. Kdo ví? Tøeba to má nìco spoleènıho s tou radiací, kterı jsem byl kdysi vystavenej. Kdy jsme byli v Kráteru, tak do sebe Zakladatel cpal jeden Rad-X za druhım, jako by to byly lentilky, ale myslíš, e nabídl starımu Ianovi? Jasnì e ne. Myslím, e byl poøád naštvanej kvùli tomu, jak jsem ho omylem párkrát postøelil. Hehe. (Povzdychne si.) To byly skvìlı èasy.}
{207}{}{To urèitì byly. Díky za pøíbìh, Joe, eh, Iane. Mìj se.}
{208}{}{To urèitì byly. Díky za pøíbìh, Joe, eh, Iane. Ale zajímali by mì ti krtèí potkani, co ochraòují vesnici.}
{300}{}{Tak moment! Ty jsi ten kontakt ve Vault City, o kterém Connar mluvil?}
