{100}{}{Vidíš muže obleèeného ve standardní vojenské kevlarové zbroji.}
{101}{}{Vypadá zdravì, ale zdá se být ponìkud zmatený.}
{102}{dobbs1}{Au, moje hlava.}
{103}{}{Kdo jsi?}
{104}{}{Ug!}
{105}{dobbs2}{Já-já jsem Dobbs... vojín Dobbs.}
{106}{}{Mohl bys mi øíct, jak ses sem dostal?}
{107}{}{Èau.}
{108}{dobbs3}{Byl jsem v boji. Ano, v boji. Všude kolem se støílelo, granáty vybuchovaly a lidi umírali. Mìl jsem strach, ale bojoval jsem dál. Potom... potom se objevil oslepující záblesk.}
{109}{}{A co se stalo potom?}
{110}{}{Nashle.}
{111}{dobbs4}{Potom si vzpomínám, že jsem vidìl svoje tìlo, jako bych byl nìkde nad ním. Slyšel jsem doktory jak øíkají, že jsem mrtvý a pak moje tìlo hodili na hromadu jiných mrtvých tìl. }
{112}{}{A potom?}
{113}{}{Èau.}
{114}{dobbs5}{Nìjací lidi pøišli a odnesli moje tìlo do laboratoøe. Potom jsem slyšel, jak mluvili o tom, že se pokusí zregenerovat moje tìlo ponoøením do nìèeho, èemu øíkali Biomed Gel.}
{115}{}{Ještì nìco?}
{116}{}{Èau.}
{117}{dobbs6}{A potom jsem se probudil tady. Musím jít! Musím se vrátit zpátky ke svojí jednotce.}
{118}{}{Èau.}
{200}{dobbs7}{Kde to jsem?}
{201}{dobbs8}{Bolí mì hlava... au.}
{202}{dobbs9}{Proè jsem pokrytej tímhle slizem?}
{300}{dobbs10}{Musím se vrátit zpátky ke svojí jednotce.}
{301}{dobbs11}{Ale ne! Teï je ze mì dezertér!}
{302}{dobbs12}{Kudy na první frontu?}
{303}{dobbs13}{Tohle je za tebe, Johny.}
{400}{}{Vojín Dobbs prodìlal post-kryogenický syndrom.}
