{100}{}{Tu vois un fantôme !}
{101}{}{Tu vois le fantôme d'Anna.}
{150}{}{C'est un fantôme. On n'en voit pas tous les jours.}
{151}{}{Elle a l'air très tourmentée.}
{152}{}{[Parler]}
{153}{anna1}{Oh, quelle douleur ! Ca brûle !}
{154}{}{Quel est le problème ?}
{155}{}{Qui es-tu ?}
{156}{}{Va-t'en, esprit maléfique !}
{157}{anna2}{Je m'arrête et je frappe à toutes les portes. Mais personne ne vient. Personne ne m'entend.}
{158}{}{Je t'entends moi. Que se passe-t-il ?}
{159}{}{Madame, j'crois qu'vous devriez éteindre votre Homme Invisible...}
{160}{anna3}{Où est-il ? Je ne le trouve pas ? Je suis perdue ! Oh...}
{161}{}{Que cherches-tu ? Je peux peut-être t'aider.}
{162}{}{Il faudrait vraiment que tu arrêtes de marmonner et que tu articules.}
{163}{anna4}{Mon médaillon ! Je ne l'ai plus. Au voleur ! Au voleur !}
{164}{}{Eh, j'viens d'arriver. J'ai rien fait moi !}
{165}{}{Je peux t'aider à le chercher ?}
{166}{anna5}{Oh, destin cruel !}
{167}{}{Tu m'entends ?}
{168}{}{Allez à plus, Mademoiselle le fantôme.}
{169}{}{Salut. Je vais essayer de me rendre utile.}
{170}{anna6}{Mon médaillon ! Donne-le-moi !!! Oh !!!}
{171}{}{Pas question ! C'est moi qui l'ai trouvé, il est à moi !}
{172}{}{D'accord. Voilà.}
{173}{}{Voilà. Je te souhaite de trouver le repos de l'âme.}
{174}{}{Ok.}
{175}{}{Non.}
{176}{anna7}{Mon médaillon, mon médaillon ! J'arrive, papa ! J'arrive !}
{177}{}{Au revoir.}
{178}{}{Attends ! Ne pars pas !}
{179}{}{Va dans la lumière !}
{200}{anna8}{Où peut-il bien être ?}
{201}{anna9}{Ohhh.}
{202}{anna10}{Maman ? Papa ? Où êtes-vous ?}
{203}{anna11}{Je ne le trouve pas !}
{500}{anna12}{Maman... Papa... J'arrive...}
{501}{anna13}{Il fait tellement clair...}
{502}{anna14}{Grand-mère, je te vois...}
{503}{anna15}{Oh, c'est le gentil M. Cain. Ca fait plaisir de vous revoir...}
{550}{}{Cette baraque est clean !}
{551}{}{Ooh, joli squelette.}
{560}{}{Exterminateurs !}
{561}{}{Ug.}
