{100}{}{Tu vois une jeune femme très séduisante.}
{101}{}{Tu vois Elisabeth.}
{150}{}{Voici Elisabeth, la propriétaire du Casino Bar de Babeth.}
{200}{rbcca1}{Bonjour, je m'appelle Elisabeth. Je t'offre un verre ? Tu as sûrement très soif après ce voyage à travers le désert.}
{201}{rbcca2}{Hé ! Tu veux un verre, ou tu reviens seulement dire bonjour ?}
{202}{rbcca3}{Salut ! Je suis contente de te revoir. Tu as des questions ou es-tu ici seulement pour le bon whisky ?}
{203}{rbcca4}{Je suis vraiment contente de te revoir. Quoi de neuf ? T'as besoin de quelque chose ?}
{204}{rbcca5}{J'espère que tout baigne pour toi ! Que puis-je faire pour t'aider ?}
{205}{rbcca6}{Bonjour !}
{206}{rbcca7}{C'est toujours un plaisir de te revoir.}
{207}{rbcca8}{Salut ! Tu veux un verre ? Le meilleur whisky du coin !}
{208}{rbcca9}{Salut !}
{209}{rbcca10}{C'est toi ! Je le savais. Tu veux un verre, mon chou ?}
{210}{rbcca11}{Tu es de retour pour goûter aux joies et délices d'Elisabeth ou au meilleur whisky du monde ?}
{211}{rbcca12}{Bienvenue au Casino Bar d'Elisabeth. Que puis-je faire pour toi ?}
{212}{rbcca13}{Bonjour. Que puis-je faire pour toi ?}
{213}{rbcca14}{Qu'est-ce qui t'amène ? Tu veux un verre ?}
{214}{rbcca15}{Tu veux un verre, ou bien autre chose ?}
{215}{rbcca16}{Que puis-je faire pour toi ?}
{216}{rbcca17}{Bonjour à toi. Que puis-je t'offrir ?}
{217}{rbcca18}{Tu as besoin de quelque chose ?}
{218}{rbcca19}{Ca fait plaisir de te revoir. Que puis-je faire pour toi aujourd'hui ?}
{219}{rbcca20}{Quoi ?}
{220}{rbcca21}{Oui ?}
{221}{rbcca22}{Quoi encore ?}
{222}{rbcca23}{Dépêche-toi s'il te plaît. La journée a été dure. Que veux-tu ?}
{223}{rbcca24}{Que veux-tu ? Je suis très occupée.}
{224}{rbcca25}{Tu veux prendre un verre ? Les tables sont là-bas.}
{225}{rbcca26}{Je ne suis pas de très bonne humeur. Qu'y a-t-il ?}
{226}{rbcca27}{Déjà de retour ? Je suppose que tu veux boire un verre.}
{240}{rbcca28}{Bien sûr, trésor !}
{241}{rbcca29}{Que veux-tu savoir ?}
{242}{rbcca30}{Avec plaisir.}
{243}{rbcca31}{Mais certainement.}
{244}{rbcca32}{Certainement.}
{245}{rbcca33}{Ca m'est égal.}
{246}{rbcca34}{Je t'aiderai volontiers si je peux.}
{247}{rbcca35}{Bien sûr, ne sois pas stupide...}
{248}{rbcca36}{Tout ce que tu veux. Alors qu'y a-t-il ?}
{249}{rbcca37}{Je ferai tout mon possible pour t'aider. Que veux-tu savoir ?}
{250}{rbcca38}{Demande toujours.}
{251}{rbcca39}{Si tu insistes.}
{252}{rbcca40}{Je suppose que oui.}
{253}{rbcca41}{Mets pas trois heures s'il te plaît. J'ai un commerce à faire tourner moi.}
{254}{rbcca42}{Bon, d'accord. Qu'y a-t-il ?}
{255}{rbcca43}{Je suppose.}
{256}{rbcca44}{Quoi ?}
{257}{rbcca45}{Non, désolé.}
{258}{rbcca46}{Pas maintenant.}
{270}{}{J'ai besoin d'un verre.}
{271}{}{Je cherche un marchand qui vend des équipements de l'Abri.}
{272}{}{Je cherche un marchand nommé Vic.}
{273}{}{Tu as du travail ?}
{274}{}{A propos de ce boulot...}
{275}{}{Tu as encore du travail pour moi ?}
{276}{}{Rien. Salut.}
{277}{}{Ouiki.}
{278}{}{Rou-rou ?}
{279}{}{Aïo shasha.}
{280}{}{Daii.}
{281}{}{Rou-rou ?}
{300}{rbcca47}{Le whisky, c'est ma spécialité. C'est presque une tradition dans la famille Dyer. Et ça ne coûte que $5.}
{301}{rbcca48}{Les alcools sont toujours à $5, et ceux de la famille Dyer sont les meilleurs au monde.}
{302}{rbcca49}{Est-ce que ça va ? Tu veux un whisky ? Seulement $5.}
{303}{}{Je prendrais bien un verre.}
{304}{}{Pourquoi tes boissons sont si bon marché ?}
{305}{}{Dyer ?}
{306}{}{Puis-je te poser une question ?}
{307}{}{Au revoir.}
{308}{}{Ouik.}
{309}{}{Urka.}
{320}{rbcca50}{Oh, c'est mon nom de famille. On est dans les alcools depuis très longtemps, bien avant la guerre bien sûr.}
{321}{rbcca51}{Comme je l'ai dit, c'est mon nom de famille. Avant, il y avait des pubs et des saloons portant le nom de Dyer dans le monde entier.}
{322}{}{Je prendrais bien un verre.}
{323}{}{Je peux te poser une autre question ?}
{324}{}{Au revoir.}
{330}{rbcca52}{Tu es un bon client, je vais te révéler un petit secret. En fait, c'est très simple: j'ai un alambic. Un ami qui habite dans un village voisin m'a appris à en fabriquer un. Alors, t'en veux un autre ?}
{331}{rbcca53}{Secret professionnel. Et puis, je ne te connais pas bien. Je ne voudrais pas que Frankie le sache. Il me pose déjà assez de problèmes. Tu en voulais un autre ? C'est du super.}
{332}{}{D'accord, j'en prends un.}
{333}{}{Je peux te poser une autre question ?}
{334}{}{D'accord, merci.}
{340}{rbcca54}{Et voilà. Merci beaucoup.}
{341}{}{Merci. Je peux te poser une question ?}
{342}{}{D'accord, merci.}
{343}{}{Mèsssssi.}
{344}{}{Essstion ?}
{350}{rbcca55}{Je regrette. Je ne pense pas.}
{351}{rbcca56}{Fred me doit $200. Si tu peux récupérer cet argent pour moi, on peut s'arranger.}
{352}{rbcca57}{On me doit encore de l'argent que j'ai prêté.}
{353}{rbcca58}{Derek m'a emprunté un livre il y a quelque temps. Je te donne $80 si tu peux le récupérer.}
{354}{rbcca59}{Je suis toujours à la recherche d'un de mes livres.}
{355}{}{C'est quoi l'arnaque ?}
{356}{}{Quoi d'autre ?}
{357}{}{Je peux te poser une question ?}
{358}{}{Au revoir.}
{370}{rbcca60}{Arnaque ? Oh, si tu connaissais Fred, tu comprendrais. Il me doit cet argent depuis longtemps. J'avais fait une croix dessus, mais si je peux retrouver mon argent, ça me surprendrait beaucoup... et ça me ferait très plaisir évidemment. Il est quelque part en ville, j'en suis sûre.}
{371}{rbcca61}{Le titre du livre c'est "La Lavande". Derek doit être chez La Mamma dans le quartier Est.}
{372}{}{Je vais voir ce que je peux faire.}
{373}{}{Ca a l'air facile.}
{374}{}{Je l'ai déjà trouvé.}
{375}{}{Je reviendrai te voir.}
{385}{rbcca62}{Tu ne l'as pas trouvé, n'est-ce pas ? Ca m'aurait étonnée.}
{386}{rbcca63}{Oh, tu as trouvé mon livre ? Derek n'a pas intérêt de l'avoir abîmé !}
{387}{}{Si, si...}
{388}{}{Je regrette. Il est mort.}
{389}{}{Je regrette, mais Derek aussi est mort.}
{390}{}{Je regrette, mais il est mort.}
{391}{}{Oui. Le voici.}
{392}{}{Non, désolé.}
{400}{rbcca64}{J'arrive pas à y croire ! Comment as-tu fait ? Oh, peu importe. Pour te montrer ma gratitude, je vais faire moitié-moitié avec toi. Merci encore, c'est très honnête de ta part.}
{401}{rbcca65}{Oh, quelle joie que tu l'aies trouvé... Merci infiniment ! Voilà ton argent.}
{402}{}{Pas d'quoi.}
{410}{rbcca66}{C'est incroyable qu'ils soient tous les deux morts ! Quel dommage. Merci pour tout. Si tu veux bien m'excuser...}
{411}{rbcca67}{Je n'arrive pas à croire qu'il est mort... après toutes ces années !}
{412}{}{Certainement.}
{413}{}{...}
{420}{rbcca68}{Ouais, je sais qui c'est. C'est Vic. Le gars que Metzger a enfermé.}
{421}{rbcca69}{Ouais, je le connais Vic. Metzger l'a enfermé. Mais je sais pas pourquoi.}
{422}{}{Qui c'est Metzger ?}
{423}{}{Je voudrais te poser une autre question.}
{424}{}{Super ! Salut.}
{430}{rbcca70}{Tu viens à La Fosse et tu ne sais pas qui est Metzger ? C'est le Maître des Esclavagistes. Il est dans le quartier Est de la ville. Difficile de le manquer.}
{431}{}{Je voudrais te poser une autre question.}
{432}{}{Merci.}
{440}{rbcca85}{Assassin !}
{441}{rbcca86}{Tueur d'enfants !}
{442}{rbcca87}{Va-t'en, s'il te plaît.}
{443}{rbcca88}{Je ne fais pas affaire avec les gens de ton espèce.}
{444}{rbcca89}{Je ne plierai pas sans me battre.}
{450}{rbcca71}{Buffy ?! C'est toi ?! Comment vas-tu ? Ca fait tellement longtemps.}
{451}{}{Hein ?}
{452}{}{Hein ?}
{460}{rbcca72}{David te passe le bonjour. Il aurait aimé être là mais il a dû fuir.}
{461}{}{Où va-t-on ?}
{470}{rbcca73}{A cause d'un commando... ou peut-être poursuivait-il un commando ? Je ne sais pas exactement. Quelque chose dans le genre.}
{471}{}{Oh !}
{480}{rbcca74}{Oh, il m'a dit de te donner ça. C'est un cadeau de la famille Hendee. Ca devrait t'aider.}
{481}{}{Qu'y a-t-il ?}
{490}{rbcca75}{Oh, des babioles, c'est tout. Et voilà. [Babeth te donne 1000 $, 5 Stimpaks, une armure en métal, un Uzi, 5 chargeurs de munitions, une grenade à plasma, et une fleur.]}
{491}{}{Merci !}
{500}{rbcca76}{Pas de problème. Je les gardais pour toi. Bon, il faut que je retourne au boulot.}
{501}{}{Merci. Salut.}
{510}{rbcca77}{T'as pas entendu ! Il est mort ! Oh, je sais, je ne devrais pas me réjouir, mais il était très cruel.}
{511}{}{Il s'est sûrement bien battu.}
{512}{}{Je voudrais te poser une question.}
{513}{}{Oui, c'est vrai. Au revoir.}
{514}{}{Tuer !}
{520}{rbcca78}{Quoi ? Toi ? Je... ne sais pas quoi dire. Il était tellement cruel...}
{521}{}{Merci suffira.}
{522}{}{Hum.}
{530}{rbcca79}{Oh, merci suffira. Je sais que ce n'est pas bien, mais... voilà, prends cet argent. [Babeth te donne 1000 dollars.]}
{531}{}{Garde ton argent Elisabeth.}
{532}{}{Merci infiniment.}
{533}{}{Mèssi !}
{534}{}{Ugg ! Jolie da-dame.}
{540}{rbcca80}{Tu es merveilleux... même si je ne peux pardonner ton geste. Tu as rendu un fier service au monde entier.}
{541}{rbcca81}{Tu es merveilleuse... même si je ne peux pardonner ton geste. Tu as rendu un fier service au monde entier.}
{542}{}{Merci.}
{550}{rbcca90}{Ta présence ici n'est pas la bienvenue. Va-t'en, s'il te plaît.}
{551}{rbcca91}{Va-t'en, s'il te plaît.}
{560}{rbcca82}{Pourquoi as-tu détruit mon alambic ? Que t'ai-je fait ?}
{561}{}{On m'a payé pour le faire.}
{562}{}{Je n'ai de comptes à rendre à personne.}
{563}{}{Je sais pas de quoi tu parles.}
{564}{}{Peu importe.}
{565}{}{Ouba Gouba.}
{570}{rbcca83}{Ah bon ? J'suis sûre que c'est Frankie qui t'a mis sur le coup... J'en fabriquerai un autre, tu sais.}
{571}{}{Ca fait rien. J'ai reçu mon argent.}
{572}{}{Alors.}
{573}{}{Ca ne me surprendrait pas.}
{580}{rbcca84}{Alors, tu te débines ? Ca m'étonne pas.}
{581}{}{...}
