{100}{}{Un homme en SuperArmure.}
{101}{}{Arthur, fils de Uther Pendragon.}
{102}{}{Sa braguette est descendue.}
{103}{arth1}{Hola, voyageurs ! Je m'appelle Arthur, fils de Uther Pendragon, membre de la Confrérie de l'Acier. Nous sommes à la recherche de la sainte grenade d'Antioche. L'avez-vous vue ?}
{104}{}{La sainte quoi, de où ?}
{105}{}{Réponse du joueur.}
{106}{}{Unga.}
{107}{arth13}{Pas le temps de parler. Nous menons une quête.}
{108}{arth14}{Nous cherchons la sainte grenade d'Antioche.}
{109}{arth15}{Pour la Confrérie de l'Acier !}
{110}{arth16}{Hum... Une hirondelle africaine ou européenne ?}
{111}{arth17}{Hé ! Ca ne t'appartient pas !}
{112}{arth18}{Je te préviens. Laisse tes mains où elles sont !}
{113}{arth19}{Ca suffit maintenant ! J'en ai assez !}
{114}{arth2}{La Sainte Grenade d'Antioche ? C'est la mine antipersonnelle la plus puissante jamais développée.}
{115}{}{Pourquoi cherchez-vous des armes aussi terribles ?}
{116}{arth3}{La Confrérie de l'Acier veut découvrir les armes les plus puissantes qu'avaient nos ancêtres et les mettre en sécurité contre ceux qui voudraient abuser de la Sainte Grenade d'Antioche.}
{117}{}{Pourquoi ?}
{118}{arth4}{Eh bien... car la Confrérie de l'Acier se consacre à la protection des faibles, et de ceux qui sont sans défense et ce truc pourrait faire beaucoup de mal.}
{119}{}{Pourquoi ?}
{120}{arth5}{Hum... Parce que c'est l'ultime acte moral à réaliser.}
{121}{}{Pourquoi ?}
{122}{arth6}{Hum... Ecoute, on a vraiment beaucoup de travail. Tu vas nous aider ou pas ? Tu as vu la Sainte Grenade d'Antioche ?}
{123}{}{Oui.}
{124}{}{Non.}
{125}{arth7}{Pourquoi tu ne l'as pas dit plus tôt. Si tu nous indiques l'endroit, on peut partir tout de suite, et toi tu peux aller où bon te semble.}
{126}{}{[Tu montres une direction au hasard.]}
{127}{arth8}{Bon. Merci pour ton aide. Voilà pour le dérangement.}
{128}{}{Attendez, moi aussi j'ai une quête. Je cherche le J.E.K sacré. L'avez-vous vu ?}
{129}{arth9}{Bon, alors, ce n'est pas la peine de continuer cette conversation. Nous partons.}
{130}{}{[Terminé]}
{131}{arth10}{Saleté de paysans !}
{132}{}{[Terminé]}
{133}{arth11}{Un sacré J.E.K ? Eh bien oui, on en a deux. On n'en a pas besoin d'autres. Merci pour tout en tout cas.}
{134}{}{Puisque vous en avez deux, vous pourriez peut-être m'en donner un ?!}
{135}{arth12}{Non. Je ne peux pas faire ça. Ca ne serait pas juste de terminer ta quête aussi facilement. Il te reste encore beaucoup à faire. Chacun sa quête. [Il te montre une direction de l'index, à peu près là où tu lui as indiqué l'emplacement de la Sainte Grenade d'Antioche.] }
{136}{}{[Terminé]}
{200}{arth20}{Parles-tu la langue des rois ?}
{201}{arth21}{Bonjouuuur.}
{202}{arth22}{Hé, je suis là.}
{203}{arth23}{Tu aurais une minute ?}
{204}{arth24}{Ah... hum.}
{205}{arth25}{Allez. Ne m'ignore pas.}
{206}{arth26}{Je t'en prie, j'aimerais te poser une question importante !}
{207}{arth27}{Nous devons continuer notre quête de la Sainte Grenade d'Antioche. Allez, viens, Patsy.}
{300}{}{Notre quête a été accomplie !}
{301}{}{Arthur, à votre service.}
