{100}{}{Tu vois un homme qui porte une SuperArmure Mk II. Il n'a pas l'air très amical.}
{101}{}{Tu vois Kaga dans sa SuperArmure Mk II.}
{102}{}{Un gros morceau de métal avec des bras et des fusils.}
{103}{kaga41}{Il en a marre de cette chasse. Finissons-en.}
{104}{kaga42}{C'est la dernière fois que tu rencontres Kaga.}
{105}{kaga43}{Tu n'es pas à la hauteur de Kaga.}
{106}{kaga44}{Il a hâte de t'envoyer dans ta prochaine vie !}
{107}{kaga45}{Tu as été un digne adversaire.}
{108}{kaga46}{Cette région du désert n'a pas besoin d'une bonne âme dans ton genre.}
{109}{kaga47}{Il va te tuer, et il deviendra la personne la plus respectée de cette région du désert !}
{110}{kaga48}{Il a hâte de retourner à Arroyo... pour tout brûler !}
{111}{kaga49}{Kaga sera célèbre pour le meurtre de ta petite personne.}
{120}{}{Kagaaaaaaaa !}
{150}{kaga1}{[Un grand guerrier puissamment bâti se tient devant toi, ses yeux reflètent la haine alors qu'il te passe en revue] Alors comme ça, ils ont chassé Kaga, et ont fait de TOI l'Etre Elu ? Ha ! Tu penses qu'être le petit fils de l'Habitant de l'Abri te rend exceptionnel ?! Tu crois que tu vaux mieux que moi, Kaga le Grand ?!}
{151}{}{Hé bien, JE SUIS, l'Etre Elu, n'est-ce pas ?}
{152}{}{Hé, attends une seconde. J'ai jamais dit que je valais mieux que toi.}
{160}{kaga2}{Ce titre ne voudra plus rien dire lorsque Kaga t'arrachera la tête !}
{161}{kaga3}{Aucune parole ne te sauvera la peau. Toi mort, mon honneur sera restauré. Kaga va maintenant prendre sa revanche !}
{200}{}{Ooglie ?}
{201}{kaga4}{Quoi !? C'est *toi* qu'ils ont choisi comme Etre Elu ? Ho-la-la, ils doivent être désespérés.}
{202}{}{Moi pas aimer toi. Toi l'air méchant.}
{203}{kaga5}{Je n'ai pas de temps à perdre à te parler. Prépare-toi à mourir des mains de Kaga !}
