{100}{}{Tu vois un homme qui porte une armure métallique.}
{101}{}{Tu vois Kaga.}
{102}{}{Ouais, c'est Kaga le pas si Magnifique que ça. Il porte une armure métallique et veut te tuer.}
{103}{kaga24}{Encore toi !}
{104}{kaga25}{Il commence à en avoir marre de nos rencontres incessantes.}
{105}{kaga26}{Etre Elu, hum...}
{106}{kaga27}{Finissons-en !}
{107}{kaga28}{Tu regretteras d'avoir entendu un jour le nom de Kaga !}
{108}{kaga29}{Ses compétences ont progressé depuis notre dernière rencontre.}
{109}{kaga30}{Ca devient une sale manie !}
{110}{kaga31}{Kaga a besoin de plus d'entraînement.}
{111}{kaga32}{Kaga reviendra !}
{120}{}{Tiens Kaga, comme on se retrouve.}
{150}{kaga1}{[Un grand guerrier puissamment bâti se tient devant toi, ses yeux reflètent la haine alors qu'il te passe en revue] Alors comme ça, ils ont chassé Kaga, et ont fait de TOI l'Etre Elu ? Ha ! Tu penses qu'être le petit fils de l'Habitant de l'Abri te rend exceptionnel ?! Tu crois que tu vaux mieux que moi, Kaga le Grand ?!}
{151}{}{Hé bien, JE SUIS, l'Etre Elu, n'est-ce pas ?}
{152}{}{Hé, attends une seconde. J'ai jamais dit que je valais mieux que toi.}
{160}{kaga2}{Ce titre ne voudra plus rien dire lorsque Kaga t'arrachera la tête !}
{161}{kaga3}{Aucune parole ne te sauvera la peau. Toi mort, mon honneur sera restauré. Kaga va maintenant prendre sa revanche !}
{200}{}{Ooglie ?}
{201}{kaga4}{Quoi !? C'est *toi* qu'ils ont choisi comme Etre Elu ? Ho-la-la, ils doivent être désespérés.}
{202}{}{Moi pas aimer toi. Toi l'air méchant.}
{203}{kaga5}{Je n'ai pas de temps à perdre à te parler. Prépare-toi à mourir des mains de Kaga !}
