{100}{}{Tu vois un vieux mutant qui n'a pas l'air commode.}
{101}{}{Tu vois Zaius, le chef de la mine.}
{102}{}{En y regardant de plus près, tu vois un vieux mutant robuste avec une pioche et un casque de mineur.}
{103}{zaius1}{C'est toi le nouvel arrivage ?}
{104}{}{Argg, ouga ouga !}
{105}{}{Nouvoo ! Moi ! Arrivaaage !}
{106}{}{C'est exact.}
{107}{}{Ouais, ça fait un p'tit moment que j'suis là.}
{108}{}{Non, Einstein, j'ai toujours habité ici et t'as jamais rien remarqué.}
{109}{}{Il paraît que tu as un petit problème avec la mine.}
{110}{}{Que pouvez-vous me dire sur cet endroit ?}
{111}{zaius2}{Hum... Je vois. Ecoute. Voilà quelques dollars. Va au saloon et prends toi quelque chose à boire.}
{112}{}{Gnag ? Oug ? Groink !}
{113}{zaius3}{J'te suis pas. Pourquoi t'irais pas au saloon. Qui sait, peut-être que Francis t'accordera un bras de fer...}
{114}{}{Bra verre ? O-KKKK !}
{115}{zaius4}{Ouais. Je m'appelle Zaius. Maintenant qu'on se connaît... T'es habile de tes dix doigts ? On a un problème avec notre purificateur d'air au niveau inférieur de la mine, mais on n'a pas les pièces pour le réparer ni l'équipement de protection contre le radon qui s'est accumulé.}
{116}{}{C'est pas trop mon truc. Je regrette.}
{117}{}{Pas trop mal. De quoi s'agit-il ?}
{118}{zaius5}{Bien, j'espère que ton séjour aux Collines Brisées sera agréable.}
{119}{}{[Suite]}
{120}{zaius6}{Ha. Ha. Très drôle. Rien de mieux qu'une grande gueule pour résoudre un problème.}
{121}{}{Grande gueule peut-être mais moins con que n'importe qui dans cette ville pourrie !}
{122}{}{Oh ? T'as un problème ? Qu'est-ce que c'est ?}
{123}{}{Le problème c'est que t'es débile.}
{124}{}{Cherche pas plus loin. Quel est le problème ?}
{125}{zaius7}{Notre purificateur d'air est cassé. Il se trouve au dernier niveau. On n'a pas de pièces de rechange, ni d'équipement de protection. Sans les pièces, on peut pas réparer. Sans protection, le radon ne nous laisse aucune chance. T'es habile ?}
{126}{}{Je vais bien.}
{127}{}{Non. Pas vraiment.}
{128}{zaius8}{Encore toi, hein ?}
{129}{}{Yark ! Ouag ! Ouga ouga !}
{130}{}{Saaalut ! SAAALUUT ! Moi !}
{131}{zaius9}{Camarade, je t'ai déjà donné de l'argent. Va embêter quelqu'un d'autre, d'accord ?}
{132}{zaius10}{Re-salut. Pourquoi ne pas aller... Voyons voir... à la banque, en ville ? Sûr qu'il y a des tas de gens là-bas qui voudraient bien te parler.}
{133}{zaius11}{Bon, si jamais tu trouves une solution, tiens-moi au courant.}
{134}{zaius12}{Vraiment ? Tu le ferais pour moi... et, surtout, pour les Collines Brisées ?}
{135}{}{Qu'est-ce que j'y gagne ?}
{136}{}{D'accord, je vais faire ça.}
{137}{}{Pas maintenant.}
{138}{zaius13}{Vrai de vrai ? Eh bien, si t'es un crac, pourquoi ne pas réparer le purificateur d'air en bas ? Tu auras besoin des pièces, et il te faudra trouver un moyen de respirer le gaz. Tant que tu n'auras pas fait ça, je crois que je vais m'en tenir à ma première impression, à savoir que t'es une grande gueule.}
{139}{}{Qu'est-ce que j'y gagne ?}
{140}{}{D'accord, je vais faire ça.}
{141}{}{Tu plaisantes ?}
{142}{zaius14}{Le problème c'est que je suis pas stupide. Je le répète parce que je n'arrive pas à croire que ce crétin vient de débiter un truc qui ressemblait à des mots. Barre-toi de là, vermine !}
{143}{zaius15}{A part les nazes qui me harcèlent, le problème c'est le purificateur d'air de la mine. Il est foutu, et on a pas l'équipement de protection pour respirer le radon ni les pièces nécessaires pour le réparer. Tu peux, si j'ai bien compris ? Parce que t'es une grande gueule ?}
{144}{}{Qu'est-ce que j'y gagne ?}
{145}{}{D'accord, je vais faire ça.}
{146}{}{Tu veux rire ? Jamais de la vie.}
{147}{zaius16}{. Qu'en dis-tu ?}
{148}{}{C'est nul. Je veux plus.}
{149}{}{Pas mal du tout.}
{150}{}{Laisse tomber. J'abandonne.}
{151}{zaius17}{Super ! T'auras besoin des pièces, bien sûr. Va à New Reno et trouve Renesco. Il a des outils dans sa boutique. Dis-lui que c'est Zaius qui t'envoie. Dis-lui que je t'ai dit « Le canari a cassé sa pipe ». Je sais pas où trouver d'équipement de protection contre le gaz. Je suppose que tu pourrais t'en passer mais ça fera mal. Encore une fois, merci.}
{152}{}{Pas de problème. Salut.}
{153}{zaius18}{Non ? Bien, si toutefois tu changes d'avis, tu sais où me trouver.}
{154}{}{C'est ça. Salut.}
{155}{zaius19}{ et c'est un marché conclu. Prends la moitié maintenant. Je te donnerai le reste quand tu auras terminé. Va à New Reno et trouve Renesco. Il a des outils plein sa boutique. Il devrait pouvoir t'aider pour les pièces.}
{156}{}{A plus. }
{157}{zaius20}{Je regrette mais je peux pas aller plus loin. C'est ça ou rien.}
{158}{}{J'achète.}
{159}{}{Je le laisse.}
{160}{zaius21}{Ok. Laisse tomber. Non merci.}
{161}{}{Peu importe.}
{162}{zaius22}{Salut !}
{163}{zaius23}{Ah, bien. Te voilà de retour.}
{164}{zaius24}{Salut.}
{165}{zaius25}{Je savais que ces salauds de Franc, Manson, Jacob et Hélène nous attendaient au tournant. Félicitations ! Alors...}
{166}{zaius26}{J'espère que tu as pensé à rendre le minerai à la ville... alors...}
{167}{zaius27}{Merci d'avoir vendu le minerai. On aurait aussi bien pu l'utiliser. Alors...}
{168}{zaius28}{Merci mille fois d'avoir rendu ce minerai. T'imagines pas comme on bosse dur pour ce truc !}
{169}{zaius29}{Que veux-tu encore ?}
{170}{}{Parle-moi de la ville.}
{171}{}{J'ai entendu dire que vous aviez des problèmes à la mine.}
{172}{}{Comment va ?}
{173}{}{Tu t'entends bien avec les humains ?}
{174}{zaius30}{T'as déjà changé d'avis au sujet de la mine ?}
{175}{}{Qu'est-ce que j'y gagne ?}
{176}{}{D'accord, je vais faire ça.}
{177}{}{Pas maintenant.}
{178}{}{Non.}
{179}{zaius31}{Comment ça se présente ? J'espère que tu vas t'occuper de ça bientôt...}
{180}{}{Ca se présente pas mal.}
{181}{}{J'ai beaucoup à faire. J'ai pas encore eu le temps de m'en occuper.}
{182}{}{Je devrais pouvoir t'en dire plus bientôt.}
{183}{zaius32}{T'as les pièces ? Super... J'espère que tu as quelque chose pour te protéger. Les émanations peuvent être fatales.}
{184}{}{Je peux y aller.}
{185}{}{J'irai bientôt.}
{186}{zaius32}{T'as les pièces ? Super... J'espère que tu as quelque chose pour te protéger. Les émanations peuvent être fatales.}
{187}{}{Je peux y aller.}
{188}{}{J'irai bientôt.}
{189}{zaius33}{Réparé ? Génial ! Ecoute, je sais que tu faisais ça gratuitement, mais... je pouvais pas te laisser faire. Les gars et moi, on s'est cotisés et on t'a pris ça. C'est un fusil de combat. Bonne chance. Et merci !}
{190}{}{Y'a pas d'quoi. Merci !}
{191}{zaius34}{Tu l'as réparé ? Génial ! Comme convenu, voici le reste de ce qu'on te doit. Encore merci.}
{192}{zaius35}{Saloperie. Tu vas crever maintenant !}
{193}{zaius36}{Bien bien. Mais dépêche-toi... La ville a besoin de ce qu'on tire de là-bas.}
{194}{}{Bien sûr. A plus tard.}
{195}{}{Me presse pas. J'ai pas que ça à faire moi !}
{196}{zaius37}{Je regrette, votre ALTESSE, mais je pense que la survie de la ville est certainement un peu plus importante. Grouille-toi, Ok ?}
{197}{}{Compte sur moi. J'y veillerai. A plus.}
{198}{}{Ca suffit comme ça. T'es un homme mort.}
{199}{zaius38}{Je t'en prie, dépêche-toi ! La mine est vitale pour la ville.}
{200}{}{Très bien, très bien.}
{201}{zaius39}{Bien, la meilleure personne à qui parler à ce sujet c'est Marcus, à la banque, ou Steve, l'hôte d'accueil de la ville.}
{202}{}{Hum. D'accord, merci.}
{203}{}{Je vais voir avec eux, alors.}
{204}{zaius40}{Ils sont pas mal. Mais bon... C'est sûr qu'ils pourraient toujours être mieux.}
{205}{}{Ok. Merci pour toutes ces infos.}
{206}{zaius41}{Bien, étant donné que les mutants ne deviennent pas vieux et séniles (le gaz les préserve, un truc dans ce genre), les choses se présentent bien. Je veux dire, on veut pas tuer tout le monde, et il me semble que les humains ne nous voient pas d'un trop mauvais oeil. Evidemment, je parle pas des humains des autres villes du coin... Ceux-là sont des salauds.}
{207}{}{D'accord, merci. Salut.}
{300}{zaius16}{. Qu'en dis-tu ?}
{301}{zaius16}{. Qu'en dis-tu ?}
{302}{}{$}
{381}{}{Je suis une femme occupée. J'ai pas encore eu le temps.}
{382}{}{Me presse pas. J'suis une femme occupée moi.}
{383}{zaius42}{Je regrette, Madame la DUCHESSE, mais je pense que la survie de la ville est certainement un peu plus importante. Grouille-toi, Ok ?}
{400}{}{J'ai là un papier où figure ton nom. J'l'ai trouvé sur une morte dans les tunnels. Tu pourrais m'expliquer ça ?}
{401}{zaius43}{Attends, j'ai seulement reçu ce message. Va voir Francis, Ok ? C'est lui qui l'a écrit.}
{402}{}{Si tu as une part de responsabilité dans la mort de ces gens, je veux le savoir.}
{403}{}{D'accord. A plus.}
{404}{zaius44}{Non ! On se protège simplement contre la conspiration. Marcus croit dans la justice et les preuves, et même s'il sait que ces gens sont dangereux, il ne sait pas qu'ils sont. Et il est trop honnête pour créer lui-même des preuves. De mon côté, j'essaie juste d'empêcher Francis de se venger de façon radicale.}
{405}{}{Bizarre ton scénario. Je vais vérifier ce qu'en dit Francis.}
{406}{zaius45}{Je savais bien que Francis ne pourrait pas supporter son implication. Il connaissait les risques, mais il pensait sans doute ne jamais être pris. Il s'en remettra. J'espère qu'on pourra en dire autant des Collines Brisées.}
{407}{}{Je l'espère moi aussi. Mais dis-moi...}
{408}{}{Moi aussi. Salut.}
{1130}{}{ !}
