{100}{}{Tu vois un jeune homme élégant.}
{101}{}{Voici Davin.}
{102}{}{Tu vois un jeune homme d'une vingtaine d'années. Il ressemble beaucoup à Grisham.}
{150}{davin1}{Si tu m'avais demandé, j'aurais bien voulu.}
{151}{davin2}{Hmpf ! Miria n'est pas si bonne que ça au lit. }
{152}{davin3}{J'arrive pas à croire que tu m'aies vendu.}
{153}{davin4}{La prochaine fois, on essaiera une partie à trois.}
{154}{davin5}{Oooh... Il est mignon.}
{155}{davin6}{Demande lui.}
{156}{davin7}{C'était super, à qui le tour ?}
{157}{davin8}{Salut ! Je m'appelle Davin, j'aide mon père à l'abattoir de Modoc.}
{158}{}{Je cherche la montre en or de Cornélius. L'as-tu vue quelque part ?}
{159}{}{Que fais-tu à l'abattoir ?}
{160}{}{J'ai entendu des rumeurs au sujet de la Brahmine et toi.}
{161}{}{Parle-moi de ton père.}
{162}{davin9}{Rebonjour.}
{163}{davin10}{Je savais que tu reviendrais me voir.}
{168}{}{Pourquoi ne pas nous mettre plus à l'aise ?}
{171}{}{Reste ici.}
{172}{davin11}{Bien sûr. J'ai rien d'autre à faire.}
{178}{davin12}{Non, je ne l'ai vue nulle part.}
{179}{}{Puis-je vous poser encore quelques questions ?}
{180}{davin13}{Eh bien, je... euh... Je veux dire... Je dirige, je m'occupe de certains trucs. Je suis le fils du propriétaire après tout. Je vais hériter de l'abattoir quand mon père sera mort.}
{182}{davin14}{C'est un mensonge. Je vais juste la nuit dans la grange pour... Vérifier que tout est bien fermé à clef. Avec tous ces animaux sauvages... Vaut mieux être prudent.}
{184}{davin15}{Mon père s'occupe de l'abattoir. Il n'est pas plus mauvais père qu'un autre. Un petit conseil si tu veux faire des affaires avec lui. Il semblerait que les affaires vont plus loin qu'il ne veut bien l'avouer.}
{186}{davin16}{Reviens me voir si tu voulais qu'on... parle encore.}
{187}{davin17}{Ouah ! je n'aurais jamais cru qu'une si belle femme tenterait de me séduire. Quoi ! Tu n'es pas une femme ! N'aie crainte, tu es tellement joli, je ne dirai rien si tu ne dis rien.}
{188}{davin18}{Je dois rêver. Je n'arrive pas à croire qu'une si belle femme essaie de me séduire. Tu essaies de me séduire, n'est-ce pas ?}
{189}{}{Mon regard se perd dans tes yeux et c'est un vrai paradis. Ne brisons pas avec des mots la magie d'un instant aussi précieux. Laissons parler nos gestes.}
{190}{}{Tais-toi, tu vas tout gâcher. Détends-toi et apprécie.}
{191}{}{Il doit y avoir une erreur, je voulais seulement te poser quelques questions.}
{192}{}{Merci pour la proposition, mais non, euh... Je dois partir.}
{193}{davin19}{Oh oui ! Prends-moi ! Prends-moi tout de suite ! [Il déchire ses vêtements, puis les tiens... puis... pour la suite, fais appel à ton imagination...]}
{194}{davin20}{[Ricanements.] C'est moi qui fais l'homme. Ce sera ton tour la prochaine fois.}
{195}{}{[Deux heures plus tard... La terre a tremblé et ce lit ne sera plus jamais le même.]}
{196}{}{[Une heure plus tard... et le meilleur orgasme que tu n'aies jamais eu.]}
{197}{}{[Une demi-heure plus tard, tu es sur les rotules.]}
{198}{}{[15 minutes et quelques grognements plus tard.]}
{199}{}{[Tu as quand même pris le temps de retirer ta chemise, juste avant de n'en plus ressentir le besoin.]}
{200}{}{Je dois partir. Au revoir.}
{400}{davin21}{Papa !}
{401}{}{Ouh oh !}
{402}{davin22}{C'est bien mon cas !}
{405}{davin23}{Oncle Biff !}
{410}{}{Euh...}
{411}{}{Uhhh... Continue s'il te plaît...}
{412}{}{Je n'ai jamais...}
{413}{}{Um... Moi oui !}
{450}{davin24}{Ouhhh, ce n'est pas à moi qu'il faut dire ça.}
{500}{davin25}{Dis donc, il faut que je m'occupe de tout, ici.}
{1000}{davin26}{Oui, mon coeur.}
{1001}{davin27}{Que puis-je faire pour toi, mon lapin ?}
{1005}{}{Tu ne comprends pas. Je n'ai pas envie que tu t'accroches à moi comme ça quand on se déplace.}
{1006}{}{Ce que t'as fait de mal, c'est que je veux que tu marches loin derrière.}
{1007}{davin28}{Mais... Mais... Qu'est-ce que j'ai fait de mal ?}
{1008}{davin29}{Qu'attends-tu donc de moi, mon trésor ?}
{1009}{}{Merci, ça commençait à taquiner. Et maintenant, mon amour ?}
{1010}{davin30}{Avant, j'allais dépecer les Brahmines à l'abattoir, alors je me débrouille au couteau. Et une fois, mon père m'a fait battre à mort une Brahmine avec une barre de fer. Je crois que je peux utiliser une massue s'il le faut. Euuh, ah ouais, mon père m'a emmené tirer au fusil une fois, mais j'ai eu tellement peur que j'ai failli lui tirer dessus.}
{1020}{}{J'ai besoin d'un peu d'espace, Davin.}
{1100}{davin31}{Je suis totalement guérie, prête à partir.}
{1200}{davin32}{Il me reste à peine quelques égratignures. Ne t'en fais pas, mon canard.}
{1300}{davin33}{Eh bien, je suis pratiquement guéri, mais j'aimerais bien recevoir encore quelques soins à l'occasion.}
{1400}{davin34}{Je me suis soignée autant que j'ai pu, mais je suis encore pas mal esquintée.}
{1500}{davin35}{Non mon chou, je veux venir avec toi.}
{1600}{davin36}{Certainement, je le range.}
{1700}{davin37}{Ok, je reste tout le temps derrière toi.}
{1800}{davin38}{Alors, je ne serais plus en mesure de te protéger. Non, je ferai mieux de rester proche.}
{1900}{davin39}{Quoi ? Pas question. Je ne veux pas te quitter de vue, mon petit pistolet en sucre.}
{2000}{davin40}{Bobo. Je pense m'être cassé un membre. Peux-tu faire un bisou guérisseur ?}
{2001}{davin41}{Ugh, j'ai l'impression de brûler. Je crois que je suis irradié.}
{2002}{davin42}{Ugh, je me sens vraiment malade. Je crois que je suis empoisonné.}
