{100}{}{Tu vois une jolie jeune femme en tenue de combat.}
{101}{}{Voici Elise.}
{102}{}{Elle a un air de quelqu'un à qui on ne la fait pas, comme si elle était habituée à donner des ordres et à se faire obéir.}
{103}{elise1}{Que veux-tu ?}
{104}{elise2}{Encore toi ?}
{105}{}{C'est Karl qui m'envoie.}
{106}{}{Dr Jubilé m'a dit que je devrais te parler.}
{107}{}{Qui es-tu ?}
{108}{}{Hein ?}
{109}{}{Je cherche un groupe qui déteste l'esclavage. Il s'appelle le Commando de la Nouvelle Californie.}
{110}{}{Tu peux réparer ma voiture ?}
{111}{}{Je croyais que cet endroit était déserté.}
{112}{elise3}{Est-ce qu'il savait ? Que t'a-t-il dit ?}
{113}{}{Pas grand-chose. Que vous étiez de braves gens et que j'irais peut-être au pieu avec toi.}
{114}{}{Il a dit que tu payais bien.}
{115}{elise4}{Moi, c'est Elise. Et voilà Gond. On est membres d'un *groupe* qui essaie de faire le bien.}
{116}{}{On ne dirait pas une fondation charitable ou une église.}
{117}{}{Ca a l'air intéressant. Le bien dans quel sens ?}
{118}{}{Je veux seulement faire réparer ma voiture.}
{119}{elise5}{Sors d'ici. Le saloon, c'est sur l'avenue principale.}
{120}{elise6}{Qui déteste l'esclavage, hein ? Intéressant. Que ferais-tu si tu trouvais ce groupe ?}
{121}{}{Je leur demanderais si je peux me joindre à eux.}
{122}{}{Je leur casserais la gueule.}
{123}{}{Rien.}
{124}{elise7}{Ca ne te regarde pas. Maintenant, va-t'en.}
{125}{elise8}{On ne s'occupe plus de voiture. C'est fermé, pour toujours. Au revoir.}
{126}{elise9}{Non. Au revoir.}
{127}{elise10}{D'accord. Alors, dis-moi. Que penses-tu des esclavagistes ?}
{128}{}{Je les déteste. Ils sont dégoûtants, vils, abjects.}
{129}{}{S'ils me fichent la paix, je leur fiche la paix.}
{130}{}{Plusieurs de mes meilleurs amis sont esclavagistes.}
{131}{elise11}{Y'a que l'argent qui t'intéresse ?}
{132}{}{Bien sûr que non. Je crois en la vérité, la justice, et la lutte en faveur des opprimés.}
{133}{}{C'est un début, en attendant que quelqu'un lance une meilleure cause.}
{134}{}{Quoi d'autre ?}
{135}{elise12}{Me raconte pas de conneries. Je vois le genre. Au revoir.}
{136}{elise13}{Si tu ne sais pas, j'ai perdu mon temps. Au revoir.}
{137}{elise14}{Non, nous ne sommes pas une organisation religieuse. Je peux te poser une question ?}
{138}{}{Vas-y.}
{139}{elise15}{Pas si vite. Tu dois passer un test avant d'entrer dans le Commando.}
{140}{}{Bien. Dis-moi.}
{141}{}{Un test ? On est où ici, à l'école ?}
{142}{elise16}{Il y a un esclavagiste à la sortie de la ville. Tu as peut-être vu sa maison. Libère ses esclaves et reviens nous raconter.}
{143}{}{Pas de problèmes.}
{144}{}{Pas question. Je ne veux pas créer d'ennuis.}
{145}{elise17}{Eh bien, c'est ton jour de chance.}
{146}{elise18}{C'est ce genre d'attitude qui cautionne l'atrocité de l'esclavage. Je regrette mais il n'y a pas de place pour toi dans notre organisation.}
{147}{}{Ok.}
{148}{elise19}{Alors, tu as changé d'avis ? Tu veux faire tes preuves ?}
{149}{}{Certainement.}
{150}{}{Que dois-je faire ?}
{151}{elise20}{Tu n'as pas quelque chose à faire ? Reviens quand le travail sera fini.}
{152}{elise21}{J'ai entendu la nouvelle. Tu as libéré les esclaves. Joli travail ! Alors, tu veux faire partie du Commando ?}
{153}{}{Oui.}
{154}{}{Non.}
{155}{elise22}{J'ai entendu dire que tu as libéré tous les esclaves qui étaient hors de la ville. Ce que tu as fait est très bien et je voulais te serrer la main.}
{156}{}{Merci.}
{157}{elise23}{C'est simple. Nous croyons que l'esclavage est mal et que nous devons le combattre. En RNC, nous avons beaucoup d'amis en haut lieu. Grâce à eux, nous avons aboli l'esclavage dans le Sud, et nous espérons gagner au Nord.}
{158}{}{Le Commando, j'aimerais faire partie d'un tel groupe. Inscris-moi.}
{159}{}{Intéressant... Je vais réfléchir à ce que tu m'as dit.}
{160}{elise24}{Jures-tu de combattre l'esclavage dès que l'occasion se présentera et d'aider les membres du Commando ?}
{161}{}{Oui.}
{162}{}{Non.}
{163}{elise56}{Félicitations, tu fais partie du Commando.}
{164}{elise52}{Tu es des nôtres. Mais en ce moment il n'y a pas grand-chose à faire, c'est dommage. La plupart de nos hommes sont partis en patrouille. Je préviendrai tout le monde que tu es des nôtres désormais. Je n'ai pas envie que tu te fasses tirer dessus par l'un d'entre nous.}
{165}{elise25}{Nous cherchons toujours de braves gens pour servir notre cause. Si tu changes d'avis, viens me voir. Tu ne veux pas saisir ta chance et te joindre à nous ?}
{166}{}{Non.}
{167}{}{Maintenant que tu le dis, je crois que j'aimerais bien faire partie du Commando.}
{168}{elise26}{Je vois. Je représente un groupe, le Commando de la Nouvelle Californie. Avec tes opinions, tu peux prétendre à devenir membre. Ca t'intéresse ?}
{169}{}{Super ! Inscris-moi.}
{170}{}{Ca a l'air intéressant. Que peux-tu me dire sur le Commando ?}
{171}{elise27}{Je vois. Merci de nous avoir rendu visite mais je crois que nous n'avons plus rien à nous dire. Si tu changes d'avis, viens me voir.}
{172}{}{Ok.}
{173}{elise28}{Puisqu'il en est ainsi, je te demanderai de sortir d'ici. Immédiatement !}
{174}{}{Ok.}
{175}{elise29}{Un esclavagiste ! Barre-toi d'ici sinon je remplace ton tatouage par une balle !}
{176}{}{Certainement.}
{177}{}{Essaie !}
{178}{elise30}{On a des agents et des sympathisants dans plusieurs villes du Nord. On fait passer le message et on attaque les esclavagistes à chaque occasion.}
{179}{elise31}{Rebonjour. T'as changé d'avis... Tu te joins à nous ?}
{180}{}{Ca ne fait rien.}
{181}{elise53}{Ca ne t'appartient pas. Alors tu dégages ou je vais me mettre en rage !}
{182}{elise54}{Je ne sais pas ce que t'as fait à Gond, mais tu vas payer !}
{200}{elise32}{Félicitation, tu es maintenant un ranger. C'est ton devoir de combattre l'esclavage partout où il peut apparaître. Au revoir mon ami.}
{201}{}{Avant que je m'en aille, j'ai des informations qui peuvent t'intéresser.}
{202}{elise33}{Oui, qu'est-ce que c'est ?}
{203}{}{J'ai été averti de l'emplacement d'un grand camp d'esclaves au Nord-Ouest, le repaire. C'est l'une des possessions principales de Metzger.}
{204}{}{En es-tu sur ? Bien, il doit être détruit immédiatement. Nos hommes ont essayé de trouver de tels endroits dans tout le Nord, mais en vain. La destruction de ce camp horrible est cruciale à notre succès dans le combat contre l'esclavage. Mais, à quel point est-elle gardée ? Et où ?}
{205}{}{Détends-toi. J'ai déjà pris soin de tout. Le camp d'esclave a été détruit.}
{206}{}{Il y a presque une douzaine d'hommes qui gardent ce camp.}
{207}{}{Je ne suis pas certain de leur nombre. Je n'y suis pas encore allé.}
{208}{}{C'est fait ? Excellent. Cela affectera beaucoup les esclavagistes. Nous sommes tes débiteurs.}
{209}{}{En tant que Ranger, tes remerciements sont tout ce que je recherche. Prends soin de toi.}
{210}{}{Si tu es si contente de mon boulot, Que dirais tu de me donner une petite récompense ?}
{211}{elise36}{Nous devons les attaquer immédiatement. Serais-tu disposé à nous aider dans cette bataille ?}
{212}{}{Je pense que j'ai suffisamment travaillé aujourd'hui. Au revoir.}
{213}{}{C'est mon devoir de Ranger. Bien sûr je vous aiderai.}
{214}{elise37}{Excellent ! Reviens me faire votre rapport quand tu auras éliminé le camp.}
{215}{}{Donne-moi un peu de temps. J'y retournerai quand je serai prêt.}
{216}{}{Bien sûr. A la prochaine.}
{217}{}{Je suis un individu spontané. Je n'ai pas besoin de me préparer. Nous en parlerons en chemin.}
{218}{}{Actuellement, je ne pense pas que je puisse faire plus. Plus tard peut-être.}
{219}{}{En fait, je pense que ça serait mieux si quelques ranger venaient avec moi. Ils garantiraient le succès de l'opération et la fin de l'esclavage.}
{220}{elise38}{Non, je suis désolé. Je n'ai pas les ressources pour rassembler ces hommes. C'est quelque chose que tu devras faire tout seul.}
{221}{}{Bien, je le ferai seul. Je viendrai faire mon rapport quand j'aurai fini.}
{222}{}{Bien, je le ferai seul. Il me faut un peu de temps. Je reviendrai.}
{223}{}{Je dois refuser. Au revoir.}
{224}{elise39}{Tu as raison. J'aurai les hommes qu'ils te faut. Es-tu prêt à y aller maintenant ?}
{225}{}{J'ai besoin de temps pour me préparer. Je reviendrai.}
{226}{}{Je suis prêt. c'est parti.}
{227}{elise40}{De l'argent ? Bien, je suppose qu'il est le minimum que nous puissions faire. Voilà, $1 000 en dédommagement. Merci encore.}
{228}{}{Mon plaisir. Au revoir.}
{229}{elise41}{Es-tu prêt à attaquer le camp d'esclaves ?}
{230}{}{J'ai encore besoin de temps.}
{231}{}{Je suis prêt à partir.}
{232}{elise42}{Tu rencontreras les autres rangers sur le chemin. Que la chance soit avec toi.}
{233}{}{[Terminé]}
{234}{elise43}{J'ai entendu les nouvelles. Merci de ton aide. Nous sommes tes débiteurs.}
{235}{elise55}{S'il te plaît, ne sois pas trop long. Cette attaque est importante dans notre combat contre l'esclavage..}
{236}{}{Tu aides les Rangers dans leur lutte continuelle contre l'esclavage.}
{240}{}{Merci. Au revoir.}
{250}{elise44}{En fait. Tu es une personne de confiance. Quelqu'un qui ne cautionne pas l'esclavage.}
{251}{}{Bien, j'ai juste éliminé un camp entier. Qu'as-tu à l'esprit ?}
{252}{}{Je pense que j'en ai fait assez pour l'humanité aujourd'hui. A la prochaine.}
{260}{elise45}{Qu'est-ce que tu fous ici ? C'est privé -- Heu, attends une minute, je crois que j'ai entendu parler de toi. Tu serais pas celui qui a libéré un des camps d'esclaves de Metzger ?}
{261}{}{Oui. C'est moi.}
{262}{}{Et comment que je l'ai fait. Ca te pose un problème ? }
{263}{}{Peut-être... Pourquoi ?}
{264}{}{Je ne sais pas de quoi tu parles. Si tu veux bien m'excuser, je dois y aller.}
{270}{elise46}{C'était du sacré bon boulot que tu as fait, et j'aimerais te serrer la main.}
{271}{elise47}{Pas du tout, en fait, j'aimerais te serrer la main.}
{272}{elise48}{Parce que tu as sacrément bien agi et j'aimerais te serrer la main.}
{273}{}{Si tu es si contente de mon boulot, Que dirais tu de me donner une petite récompense ?}
{274}{}{Y a pas de quoi. A présent, si tu me disais qui tu es ?}
{280}{elise49}{On n'a pas grand-chose ici, mais tu nous a rendu un grand service, alors je suppose que je peux te filer une récompense. Voici 1000$.}
{281}{}{Merci. Au revoir.}
{282}{}{Merci. A présent, pourquoi ne pas me dire qui tu es ?}
{290}{elise50}{Je m'appelle Elise. Et voici Gond. Nous sommes les membres d'un groupe de lutte contre l'esclavage appelé "les nouveaux rangers californiens". On pourrait utiliser tes services. Si ça t’intéresse de te joindre à nous, j'aurais du boulot pour toi.}
{291}{}{Dis m'en plus.}
{292}{}{Jamais de la vie, espèce de... Salut.}
{300}{elise51}{J'peux aider pour quelque chose, Ranger ?}
