{100}{}{Tu vois un homme trapu, bien habillé et qui se déplace avec une lenteur calculée.}
{101}{}{Voici Merk. Ici on l'appelle *Le Boss*.}
{102}{}{Ce gars a un air arrogant et froid. On dirait qu'il se soucie de toi comme de la mouche qu'il vient d'écraser entre ses doigts.}
{103}{merk61}{Hé, je t'ai vu dans des films ! T'es là pour me faire un show, c'est ça ?}
{104}{merk62}{Pour qui te prends-tu pour venir troubler ma tranquillité comme ça ? Dégage !}
{105}{merk63}{Pardon, j'ai des affaires urgentes à régler.}
{106}{merk64}{Si tu veux parler affaires, viens me voir au Rawhide. Sinon, laisse-moi tranquille.}
{107}{merk65}{C'est sur le grand écran que j'ai dû t'voir, c'est ça ? T'as des grosses... références.}
{108}{merk66}{Tu as cette lueur dans les yeux, j'aime ça. Passe au Rawhide. Tu pourrais faire quelque chose pour moi.}
{109}{merk67}{Merde, qu'est-ce que ça sent ? Quelque chose est entré dans la pièce.}
{110}{merk68}{Va me chercher un autre whisky. Vite.}
{111}{merk69}{J'ai pas l'temps maintenant.}
{112}{merk70}{Je suis un invité ici. Arrête de m'ennuyer.}
{113}{merk71}{Hé mon chou. Les goûts de Carlson s'améliorent.}
{114}{merk72}{Je ne traite pas d'business ici.}
{115}{merk73}{Je n'te connais pas. Je suis un homme d'affaires respectable.}
{116}{merk74}{Quelle mauviette ! Va-t'en et laisse-moi tranquille.}
{117}{merk75}{Alors, tu as quand même décidé de venir me voir, hein ?}
{118}{merk76}{Je sais rien, rien du tout, tu entends ?}
{119}{merk77}{Le vice-président n'appréciera pas que tu déranges ses invités.}
{120}{merk78}{On picole du bon jus chez le boss.}
{121}{merk79}{Pousse-toi de là !}
{122}{merk80}{Si tu veux parler à quelqu'un, va t'acheter un ami.}
{123}{merk81}{Je montre pas le chemin et je rends pas la monnaie. Casse-toi.}
{124}{merk82}{C'est quoi ça, le quart d'heure mondain ?}
{125}{merk1}{Moi, c'est Merk. Qu'est-ce que tu veux ?}
{126}{merk2}{Encore toi ?}
{127}{merk3}{Bon, un peu de courtoisie, sale punk, ou ça pourrait mal finir.}
{128}{}{<Burp>}
{129}{}{Je cherche du travail.}
{130}{}{Les gens bien informés disent que c'est toi qu'il faut voir quand on veut parler affaires, si tu vois ce que je veux dire.}
{131}{}{Le bruit court que c'est toi qui as dévalisé ma voiture.}
{132}{}{Je cherche des renseignements.}
{133}{}{Il paraît que tu t'y connais en, euh disons, pièces détachées de voitures.}
{134}{merk4}{Encore toi ? Alors, le boulot est terminé ?}
{135}{}{<Glup>}
{136}{}{Non.}
{137}{}{J'ai quelques questions.}
{138}{merk5}{Hum... Robuste... Imbécile... Si tu veux du boulot, va parler à Mira. Compris ? Mi-ra. Là-bas.}
{139}{merk6}{Tu aimes faire des bruits ? Quelqu'un peut-il jeter cette bouse dehors ?}
{140}{merk7}{T'es débile ou quoi ? Tu crois que je vais engager n'importe qui ? Si tu veux travailler pour moi, il faut montrer ce que tu sais faire.}
{141}{}{Et si je flinguais Lenny ? Il le mérite.}
{142}{}{Montrer de quelle manière ?}
{143}{}{Tu connais quelqu'un qui serait intéressé par du Jet ?}
{144}{}{Ecoute, moi c'est }
{145}{}{C'est ça, faut que je fasse mes preuves. Va te faire voir, grosse limace.}
{146}{merk8}{C'était ce salaud de Doofus, hein ? Ce sale junkie parle trop. Ecoute, rends-moi un service, tu le zigouilles et après on discute.}
{147}{}{Tope là.}
{148}{}{Hé, mon sang froid a des limites !}
{149}{merk9}{Et ils te traiteront de pauvre imbécile ! Les gars...}
{150}{merk10}{Intéressant. Et qui dirait un truc pareil ?}
{151}{}{Me raconte pas des conneries, mon gros. Rends-moi ce qui m'appartient, ou tu peux déjà t'habiller pour ton enterrement.}
{152}{}{Comme c'est mignon. Tu vas répondre à mes questions, oui ou non ?}
{153}{}{Oh, c'est seulement ce que j'ai entendu. Je voulais juste savoir ce que tu dirais.}
{154}{merk11}{En supposant que je sais quelque chose, qu'est-ce que ça change ?}
{155}{}{Bon, si quelqu'un avait perdu quelque chose, tu crois qu'il pourrait le racheter ?}
{156}{}{Rends-moi la came, gros plein de soupe !}
{157}{}{Et si j'en touchais un mot aux autorités ?}
{158}{merk12}{Ca suffit. Les gars, occupez-vous de notre invité.}
{159}{merk13}{Je ne crois pas que Lenny aimerait ça.}
{160}{}{C'est probable, mais c'est pas à lui que je demande.}
{161}{}{Fais comme tu veux.}
{162}{}{Ouais. On s'ennuie par ici. C'est le moment pour un petit tête à tête au sous-sol. Allez Lenny, je veux te regarder tuer ce type.}
{163}{merk14}{Je cherche une solution à mes problèmes.}
{164}{}{C'est-à-dire ?}
{165}{merk15}{Du Jet ? Tu me fais une proposition ?}
{166}{}{Mon ami que tu vois là sait en fabriquer. Ca t'intéresse ?}
{167}{}{C'est illégal ! Non, je ne me mouille pas.}
{168}{merk16}{Bizarre. Je paie $1 000 tes services... de façon permanente.}
{169}{}{Tope là.}
{170}{}{Non, je peux pas faire ça à un ami.}
{171}{merk17}{Je crois qu'on va pouvoir s'entendre. Voilà ce que je te propose : il y a un toubib dingo en ville, le Dr Henry. Il a des papiers que j'aimerais avoir. Je te donnerai $1 000. Mais ne lui fais pas de mal. Il est plus utile vivant que mort. Ca t'intéresse ?}
{172}{}{J'm'en occupe.}
{173}{}{Non, c'est pas mon genre.}
{174}{merk18}{Le savoir, ça se paie. Tu me suis ?}
{175}{merk19}{"Le prix de la sagesse dépasse celui des rubis."}
{176}{}{Voici $50.}
{177}{}{Laisse tomber.}
{178}{merk20}{Oh, tu fais l'affaire.}
{179}{}{[Continuer]}
{180}{merk21}{Si tu veux mon avis, tu n'es qu'un tas de fumier.}
{181}{merk22}{Je pensais que tu étais une mauviette.}
{182}{merk23}{D'ac. Pas de problème. Je veux pas d'ennuis. Ecoute, mes gars remettront tout à sa place.}
{183}{}{Y'a intérêt ou t'auras de mes nouvelles.}
{184}{}{Arrête tes conneries !}
{185}{merk24}{Une telle personne peut en être capable.}
{186}{merk25}{Maintenant, je te conseille de partir.}
{187}{merk26}{Mais appelez donc la police ! Je suppose que tu apportes les preuves de ce que tu avances.}
{188}{}{Ouais, bien sûr.}
{189}{}{Ca ne fait rien.}
{190}{merk27}{Un Hubologiste installé en ville m'a énervé. Une fois que tu auras crevé cet abcès, reviens me voir et on parlera.}
{191}{}{C'est comme si c'était fait. J'ai ce qu'il faut pour crever l'abcès. Mais... C'est quoi un Hubologiste et où puis-je le trouver ?}
{192}{}{Comment oses-tu t'opposer à la vraie croyance ?}
{193}{}{Je regrette, je ne m'implique pas dans les guerres de religion.}
{194}{merk28}{Eh bien, je suis un érudit. Quelle est ta question ?}
{195}{merk29}{Demande toujours.}
{196}{}{Je cherche l'Abri 13.}
{197}{}{As-tu déjà entendu parler d'un J.E.K ?}
{198}{}{Que sais-tu sur un groupe nommé le Commando ?}
{199}{}{Que sais-tu sur un gars nommé Westin ?}
{200}{}{Je cherche des renseignements sur le vice-président Carlson.}
{201}{}{Voilà.}
{202}{merk30}{Cet argent te donne droit à une réponse. La prochaine question te coûtera $50.}
{203}{}{D'accord, voilà.}
{204}{}{J'ai toutes les données qu'il me faut.}
{205}{merk31}{Il se trouve que j'ai une carte de l'Abri 13. Ca fait seulement $1 000. Ca t'intéresse ?}
{206}{}{Bien sûr. Je la prends.}
{207}{}{Et je parie que tu me vends le pont pour m'y rendre.}
{208}{}{Peut-être plus tard.}
{209}{merk32}{S'il y a des stupéfiants à New Reno ? Je n'en ai jamais entendu parler.}
{210}{}{Non. J'ai d'autres questions à te poser.}
{211}{}{C'est tout ce que je voulais savoir.}
{212}{merk33}{Ces salauds ! Qu'ils ne mettent pas un pied chez moi, sinon je leur troue la cervelle.}
{213}{}{C'était enrichissant. Une autre question.}
{214}{}{C'est tout ce que je voulais savoir.}
{215}{merk34}{Le propriétaire du ranch ? Il est venu ici une fois, presque mort. Le toubib est accouru avec des pilules. Il paraît que Westin a des problèmes cardiaques. C'en était fini du commerce pour le reste de la nuit.}
{216}{}{Merci pour ces renseignements. J'ai encore quelques questions.}
{217}{}{C'est tout ce que je voulais savoir.}
{218}{merk35}{En bon citoyen, j'applaudis l'opposition de Carlson à toute influence de New Reno par ici. Depuis que Westin est mort, je donne un coup de main à la sécurité pour le vice-président.}
{219}{}{Je crois que je n'aurai jamais le plaisir de le rencontrer. J'ai tellement entendu parler de lui.}
{220}{}{C'est tout ce que je voulais savoir.}
{221}{merk36}{C'est tout ?}
{222}{}{Non, j'ai encore quelques questions.}
{223}{}{Ouais, c'est tout pour le moment.}
{224}{merk37}{Hé, qui ne tente rien n'a rien. L'Abri 13, c'est presque une religion par ici. Ils ont même érigé la statue d'un crétin qui serait originaire de là-bas. C'est tout ce que je sais.}
{225}{merk38}{Tu m'as acheté une carte pour ça. Utilise-la.}
{226}{merk39}{La carte ne t'a pas servi ? Pourtant, le gars m'a juré qu'elle était vraie. Comment aurais-je pu savoir ? Je ne sais pas où est l'Abri 13.}
{227}{}{J'ai encore des questions à te poser.}
{228}{}{C'est tout ce que je voulais savoir.}
{229}{merk40}{Ecoute, j'aime ta façon de travailler et Carlson a besoin d'un autre garde. Si t'attends un peu, il y aura bientôt un boulot pour toi ici.}
{230}{}{J'en suis, Merk.}
{231}{}{Je n'ai pas besoin du boulot. Merci quand même.}
{232}{merk41}{Parfait. Reviens quand tu auras fini.}
{233}{merk42}{C'est très troublant. Les gars, tuez moi ça et récupérez les preuves.}
{234}{merk43}{Ta tentative d'intimidation est presque amusante. Maintenant, j'te conseille de partir avant que je me lasse de ce petit jeu.}
{235}{merk44}{Ah, j'ai entendu la nouvelle. T'es toujours après du boulot ?}
{236}{}{Ouais, j'en ai marre des extras. J'aimerais bien un vrai boulot.}
{237}{}{Non.}
{238}{merk45}{Qu'est-ce que tu fous chez moi ?}
{239}{}{J'ai joué perso. Je ne le ferai plus. Accorde-moi un peu de ton temps...}
{240}{}{Je fais ce que je veux, espèce de fouine.}
{241}{merk46}{Casse-toi de là, phacochère !}
{242}{merk47}{Alors qu'est-ce que tu fous là, tas de merde ? Si tu veux m'impressionner, fais ton boulot.}
{243}{merk48}{Je ne te parle plus tant que le boulot n'est pas fini !}
{244}{merk49}{Ca me déçoit. D'habitude, j'élimine les choses qui me déçoivent. Mais dans ton cas, je serai généreux. Pars et ne reviens pas. J'oublierai tout.}
{245}{merk50}{Alors, cette histoire avec le Dr Henry est-elle réglée ?}
{246}{}{Ouais, j'ai les papiers que tu voulais.}
{247}{}{Non.}
{248}{merk51}{Les jours comme aujourd'hui me rendent heureux. Bon, concluons notre affaire.}
{249}{merk52}{J'ai appris que l'ingénieux docteur a rendu l'âme pendant ta visite. C'était contre mes ordres. Pour dédommager les pertes afférentes, je crois qu'un remboursement s'impose.}
{250}{}{Ecoute, je te donne $500 et on oublie toute l'affaire.}
{251}{}{Va t'faire !}
{252}{merk53}{Bien, bonne chance pour la suite. Nous n'aurons plus l'occasion de nous reparler.}
{253}{}{Ca me va.}
{254}{merk54}{Marché conclu, mais seulement parce que c'est toi. Un conseil : ne reviens pas de sitôt.}
{255}{merk55}{Je crois que je vais simplement te tuer, reprendre mon argent et toucher la récompense. C'est ça être bon citoyen !}
{256}{merk83}{Encore toi ! CREVE !}
{257}{merk84}{Je t'avais pourtant dit de ne plus me déranger.}
{258}{}{ et je m'en fous. Demande à quelqu'un d'autre.}
{259}{}{ ce type.}
{260}{}{ cette nana.}
{261}{merk56}{Un Hubologiste est un cinglé, un fanatique religieux. On en trouve à l'église en ville.}
{262}{}{Je m'en vais.}
{263}{merk57}{Je ne te parle plus tant que le boulot n'est pas terminé ! Il me faut les papiers qui sont chez le Dr Henry, illico !}
{264}{}{Non, mais j'ai besoin d'informations.}
{265}{merk85}{Je sais que la mort de Lenny a rien d'un accident, salopard.}
{266}{}{Hé, cette carte était un faux.}
{267}{}{Bon, et l'argent que je t'ai donné ?}
{268}{merk58}{Je te l'ai dit, je regrette que ça n'ait pas marché comme tu le voulais.}
{269}{}{Eh, ça te dirait d'avaler cette balle pour soulager mes misères ?}
{270}{}{<Hummphf>}
{271}{}{Tu reçois }
{272}{}{points d'expérience pour avoir récupéré les papiers du Dr Henry.}
{300}{merk86}{Où penses-tu aller ?! Essaie ça encore et je te botte le cul.}
{301}{merk87}{Je t'avais prévenu !}
