{100}{}{Tu vois une chose étrange, mi-chien, mi-métal. Ca bouge.}
{101}{}{Voici Robochien ! L'animal préféré de tous !}
{102}{}{Soit cette horrible chose est un mélange entre un chien et une machine, soit ce n'est qu'une machine, habilement réalisée pour ressembler à un chien. C'est difficile à dire.}
{103}{dogr16}{Ouaf ! <Clic> Ouaouf !}
{104}{dogr17}{<Bzzzzzz...>}
{105}{dogr18}{<Fffffrrrrr...> Je suis pas Daggit.}
{106}{dogr19}{<Grrrrrrrrrrrrrrrr...>}
{107}{dogr20}{Ouaf ! oua-oua-oua <Clic> ouaf !}
{108}{dogr21}{<Pchiiit> Miaou... erreur}
{109}{dogr22}{Ouafouafouafouafouafouaf !}
{110}{dogr23}{<Grrr...>}
{111}{dogr24}{Oua-houuuuuuuuu ! <Clic-clic> Oua-houuuuuuuuu !}
{112}{dogr25}{Yep ! Yep ! Yep !}
{113}{dogr26}{Danger ! Danger !}
{114}{dogr27}{Ouaf ! <Tic-tic-tic> Ouaf !!!}
{115}{dogr28}{<Ffffrrrrr> Ni oiseau, ni avion, ni grenouille... Ce n'est que moi, Robochien ! <Click>}
{116}{dogr29}{Roubi-Douuu !}
{117}{dogr30}{Ii-bii-dii-bii-ii-bii-dii-bii !}
{118}{dogr31}{Wouaf !}
{119}{dogr32}{GRRR OAUF !}
{120}{dogr1}{Ouaf ouaf ouaf ouaf ouaf !}
{121}{}{D'accord.}
{122}{}{Je ne pense pas vouloir que tu viennes pour le moment. Au revoir.}
{123}{dogr2}{Ouaf ? <Boing> Scratch ?}
{124}{}{Comment vas-tu ?}
{125}{}{Je veux que tu attendes ici jusqu'à mon retour.}
{126}{}{C'est tout pour l'instant.}
{127}{dogr3}{<Clic> ::Gémissements::}
{128}{}{Ca ne fait rien.}
{129}{}{D'accord.}
{130}{}{PI :}
{131}{}{On ne peut plus réparer Cyberchien à cette heure-là.}
{132}{}{Cyberchien a été en partie réparé.}
{133}{}{Cyberchien est complètement réparé maintenant.}
{1000}{dogr4}{Ouaf ! Hou-hou-hou- <Clic> Ouaf ?}
{1100}{dogr5}{Ouaf ! <Clic> Ouaouf !}
{1200}{dogr6}{Ouaf ? <Boing> Scratch ?}
{1300}{dogr7}{<Clic> ::Gémissements::}
{1400}{dogr8}{Oua-houuuuuuuuu ! <Clic-clic> Oua-houuuuuuuuu !}
{1500}{}{Ii-bii-dii-bii-ii-bii-dii-bii !}
{1600}{}{Certainement, je le range.}
{1700}{}{Ouaf ouaf réglage de la distance sur proche !}
{1800}{}{Ouaf ouaf réglage de la distance sur moyenne !}
{1900}{}{Ouaf ouaf réglage de la distance sur éloignée !}
{2000}{dogr14}{<Fffffrrrrr...> Je suis pas Daggit.}
{2100}{dogr33}{GRRR OAUF !}
{2200}{dogr15}{Ouaf ! Hou-hou-hou- <Clic> Ouaf ?}
{2204}{}{D'accord, t'es à la bonne distance pour l'instant.}
