{100}{}{Tu vois un petit homme à l'air jovial.}
{101}{}{Tu vois Harry le Ravi, le propriétaire du magasin.}
{102}{hhary1}{Euh, salut... que puis-je faire pour toi ?}
{103}{}{Je cherche à faire du business. Puis-je voir ce que tu as en stock ?}
{104}{}{Elle est toujours à vendre cette charrue ?}
{105}{}{Moi acheter.}
{106}{}{Rien pour aujourd'hui, merci.}
{107}{hhary16}{Je regrette, je peux pas t'aider mon gars.}
{108}{hhary2}{Ben, oui, toujours. Je la laisse partir pour... disons, huit cents.}
{109}{}{Je t'en donne six cents.}
{110}{}{Ok, ça marche. Je la prends.}
{111}{}{Hein, huit cents, tu dis ? Bon, je reviendrai... avec l'argent.}
{112}{}{Laisse tomber. Les Smith peuvent crever.}
{113}{}{Elle est à toi. [Il empoche l'argent.] Tu la prends tout de suite, ou il faut la livrer quelque part ?}
{114}{}{Dépose-la chez les Smith.}
{115}{hhary4}{Je regrette l'ami, ça va te coûter huit cents.}
{119}{hhary5}{Tu as besoin d'argent pour me payer, mon ami.}
{120}{}{Je reviens avec le pognon.}
{121}{hhary6}{Y'a pas de problème. Je vais la faire livrer tout de suite.}
{122}{hhary17}{Tu voulais te servir, hein ? Saleté de voleur... Gardes ! Gardes !}
{123}{}{Un marchand nommé Dave m'envoie. Je travaille avec lui sur un projet et on a besoin d'un nouveau moteur pour une pompe à eau.}
{124}{}{Tu bosses avec Dave, hein ? Ouais, je connais ce mec. Je crois que j'ai ce qu'il te faut, laisse-moi voir. [Harry va dans son arrière-salle et tu entends des boîtes se mélanger et se déplacer dans tous les sens. Il revient au bout d'une minute.] Ouais, je l'ai. Ca te fera $500 pour ça.}
{125}{}{Ca marche. Voilà la monnaie.}
{126}{}{500 ? Bon sang. J'espère que je serai remboursé. Bien, voilà le fric.}
{127}{hhary8}{Merci pour cette affaire. Prends soin de toi.}
{128}{}{Au revoir.}
{129}{}{Connar m'a envoyé pour les fournitures.}
{130}{hhary9}{[Les yeux d'Harry tournent rapidement en tous sens pour regarder autour de lui, il semble un brin nerveux] Oui, bien sûr. Juste un petit instant...}
{131}{hhary10}{[Harry t'amène les armes.] Tiens, prends ça. Ca te coûtera en tout $10 000.}
{132}{}{Bien sûr, voilà l'argent.}
{133}{}{Mais Connar m'a seulement donné $5 000.}
{134}{}{Mais je n'ai reçu que $2 000 de Connar.}
{135}{hhary11}{Désolé, mais les affaires ne vont pas très bien en ce moment. Si quelqu'un découvre que je fournis des armes à Connar, alors les choses risquent de mal tourner. Je lui ai déjà fait une remise.}
{136}{hhary12}{Tu es sûr... ? Eh bien, prends-les. [Il met l'argent dans sa poche.] Mais souviens-toi, tu n'as pas acheté ces armes ici.}
{137}{hhary13}{Excellent. Mais rappelle toi, tu n'as rien acheté ici, Ok ?}
{138}{}{C'est entendu. Salut.}
{139}{}{[Suite]}
{140}{}{Eh bien alors, attends un instant avant que je ne trouve l'argent.}
{141}{hhary14}{Alors, tu as apporté le fric ?}
{142}{}{Que dirais-tu de $10 000 ?}
{143}{}{Que dirais-tu de $8 000 ?}
{144}{}{Heu... $12 000 ?! Je n'ai pas autant d'argent, attends un peu que je les aie.}
{145}{hhary18}{Bon sang ! Qui a bien pu me jouer ce tour là ?!}
{146}{hhary19}{Hé ! Pourquoi ai-je été arrêté ?}
{147}{hhary20}{Eh bien, au moins la nourriture est bonne.}
{148}{hhary21}{Qu'est-ce que tu regardes ?}
{149}{hhary22}{Qu'est-ce qui va arriver à mon magasin maintenant ?}
{200}{}{$500 ? Hé, tu pourrais me donner une certaine forme de remise, je veux dire, toi et Dave êtes des amis, non ?}
{201}{hhary15}{Pour te dire la vérité, je n'ai jamais vraiment pris soin de mon pote. $500 pour le moteur. C'est à prendre ou à laisser.}
{202}{}{Bien. Voici l'argent.}
{203}{}{Oublie ça, je me casse.}
{204}{}{$500 !? Oublie ça, je me casse.}
{1288}{}{On dirait que je n'ai pas assez d'argent. Salut.}
