{100}{}{Ves a un monje de mediana edad.}
{101}{}{Ves al Hermano Matthew.}
{102}{}{Él está de pie en un podio predicando a los ciudadanos de Abadía.}
{200}{bmatt8}{Buenas personas de Abadía. Tómense un momento para escuchar,porque tengo mucho que decir.}
{201}{bmatt9}{Aquí recogemos, las sagradas reliquias de un era pasada.}
{202}{bmatt10}{Arrasada por el Diluvio de Llamas, en la oscuridad, fueron arrojados.}
{203}{bmatt11}{Un Memorial que debemos hacer, para preservar la sabiduría de los antiguos.}
{204}{bmatt12}{Debemos guardarlo y cuidarlo, aunque la llama se haya enfriado;}
{205}{bmatt13}{Podría encenderse una vez más, debido al mal uso de su sabiduría.}
{206}{bmatt14}{Por lo tanto, nadie debe aprender, por temor a otro, Diluvio de Llamas.}
{207}{bmatt15}{Pero un día, el hombres se elevara por encima de su deseo de destrucción.}
{208}{bmatt16}{Y los Memorial estarán allí, esperando re-introducirse.}
{209}{bmatt17}{Así servimos nuestra santa tarea, no sea que toda esa sabiduría, la perdamos.}
{210}{bmatt18}{Debemos preservarla y protegerla, pero nunca debe ser usada.}
{211}{bmatt19}{Así ahora mis amigos, y dejen que sus espíritus se eleven;}
{212}{bmatt20}{Por los guardianes del conocimiento, cada uno de nosotros, ha sido dotado.}
{213}{bmatt21}{Ahora, por favor tomen un momento y reflexionen en lo que e dicho.}
{224}{}{Ahora, por favor tomen un momento y reflexionen en lo que e dicho.}
{300}{}{Saludos, amiga. No creo que te haya visto por aquí antes. Mi nombre es el Hermano Matthew y yo ayudo a difundir la palabra sobre la importancia de preservar el conocimiento de los antiguos.}
{301}{}{Es bueno conocerte Matt. Mi nombre es }
{302}{}{ y estoy en una misión para el sagrado GECK.}
{303}{}{Lo siento, he de irme.}
{400}{}{Un GECK, ¿eh? Me parece recordar haber leído algo sobre eso durante una de mis sesiones de transcripción. Entonces debe
estar en nuestra base de datos, pero me temo que el acceso a nuestras computadoras está restringido. Sin embargo, si hablas con el Abad, es
posible que te otorgue acceso. No podría doler intentarlo, de todos modos. Ah, y siéntase libre de navegar a través de nuestra colección
de sagradas reliquias de la pre-guerra. Te pediría que no dañes nada, pero me temo que todo está roto más allá de toda reparación.}
{401}{}{Creo que podría hacerlo. Pero tengo algunas preguntas.}
{402}{}{Gracias. Creo que voy a lo haré ahora.}
{500}{bmatt3}{Estoy a tu servicio. ¿Qué quieres saber?}
{501}{}{¿Qué puedes contarme sobre este lugar?}
{502}{}{Pareces ser muy poético en tu predicación. ¿Alguna razón para eso?}
{503}{}{Olvídalo. Cuídate.}
{600}{}{La Abadía es el hogar de cualquiera, siempre y cuando no causen problemas. Somos una comunidad independiente y rara vez recibimos
visitantes, como usted. La mayoría de los que ves aquí descienden de los fundadores originales que se establecieron en
este antiguo monasterio no mucho después del gran Diluvio de Llamas.}
{601}{}{Continúa.}
{602}{}{La tranquilad, cualidad pacífica de este lugar que lo ha convertido en un hogar atractivo para otros viajeros que han vagado
aquí a lo largo de los años, buscando escapar del oscuro caos del Yermo. Por supuesto, el verdadero valor de este lugar yace
en su vasta biblioteca. Está lleno de tomos viejos, que contienen la extraña sabiduría de una edad perdida. Con el tiempo, hemos llegado a
imaginarnos los cuidadores y guardianes de esa sabiduría.}
{603}{}{Muy interesante. Otra pregunta}
{604}{}{Interesante. Bien, he de irme. }
{700}{}{[El hombre se ríe de tu pregunta] No, no hay una razón en particular. He leido mucha poesía a lo largo de mi vida
 y me gusta aplicarla a mis enseñanzas. Ayuda a dejar un mayor impacto en los que escuchan.}
{701}{}{Me parece justo. Otra pregunta}
{800}{}{Qué bueno verte de nuevo.}
{801}{}{. ¿Qué puedo hacer por ti?}
{802}{}{Tengo algunas preguntas.}
{803}{}{Nada. Ya nos veremos.}
