{100}{}{Ves a Lara.}
{150}{}{Ella es la líder de esta banda.}
{200}{}{Mi nombre es Lara, yo mando en esta banda. Será mejor que no hayas venido a causar problemas o vas a pasarlo fatal.}
{201}{larad2}{Hola otra vez. ¿Quieres algo?}
{202}{}{¿Tienes trabajo?}
{203}{}{Sólo estaba mirando.}
{204}{}{Estoy buscando a un mercader llamado Vic.}
{205}{}{Aruh.}
{206}{}{Rara.}
{220}{larad3}{No tenemos doctores en el pueblo y yo no puedo ayudarte.}
{221}{larad4}{Lo siento, sigo sin entenderte.}
{222}{}{Ack.}
{230}{larad5}{El nombre no me suena, pero no suelo estar al tanto de quién llega y se va del pueblo. Prueba con Becky. Todo el mundo acaba allí, así que puede que ella lo sepa.}
{231}{}{¿Tienes trabajo?}
{232}{}{Gracias. Adiós.}
{240}{larad6}{Si no has venido a La Guarida por ninguna razón en particular deberías irte. Este no es un lugar muy seguro.}
{241}{larad7}{Oh, vale.}
{242}{}{¿Tienes trabajo?}
{243}{}{Puedo arreglármelas sola.}
{244}{}{Vale, gracias.}
{250}{larad8}{No lo dudo. De otro modo, seguramente no hubieras llegado viva aquí.}
{251}{larad9}{Uh, sí, eso he oído. Lo que tú digas.}
{252}{}{¿Tienes trabajo?}
{253}{}{Vale, gracias.}
{260}{larad10}{Bueno, depende de si eres buena en algo. Hay un tema sobre el que tengo curiosidad. Si puedes averiguar algo, te pagaré.}
{261}{larad11}{Como he dicho, busco información sobre cierto objeto... o lugar. Te pagaré, por supuesto.}
{262}{}{Claro, ¿sobre qué?}
{263}{}{Quizá más tarde.}
{270}{larad12}{Si cambias de idea házmelo saber.}
{271}{}{De acuerdo.}
{280}{}{Bien, hay una iglesia al este de aquí. Metzger tiene a alguna gente vigilando lo que quiera que haya dentro. Averigua qué es y te pagaré 200 dólares.}
{281}{}{Eso es fácil. Ya sé qué es.}
{282}{}{Claro.}
{283}{}{Sé lo que podemos hacer.}
{290}{larad14}{Gracias. No te metas en peleas... todavía. Tengo un plan.}
{291}{}{No hay problema.}
{292}{}{Volveré.}
{300}{larad15}{¿Qué es eso?}
{301}{}{Componentes químicos en bruto metidos en grandes cajas.}
{302}{}{Unos grandes contenedores que contienen alguna clase de productos químicos.}
{303}{}{Deja que vuelva a comprobarlo.}
{310}{larad16}{Eso tiene sentido. Gracias. Aquí está tu dinero.}
{311}{}{¿Y eso por qué?}
{312}{}{No hay problema. Adiós.}
{320}{larad17}{He visto caravanas de Ciudad Refugio traerlas y a otras de Nuevo Reno recoger las cajas.}
{321}{}{¿Y? ¿Por qué tiene eso sentido?}
{322}{}{Oh.}
{340}{larad18}{Nuevo Reno es la capital de la droga. Necesitan materias primas para fabricar sus drogas, ¿no? Pues parece que están consiguiendo algunas, sino todas, de Ciudad Refugio.}
{341}{}{¿Dónde está Nuevo Reno?}
{342}{}{Vale, gracias.}
{350}{larad19}{No estoy segura del todo. En algún lugar al sur, creo. Nunca he estado allí, sólo veo a sus caravanas parar aquí de vez en cuando... muy de vez en cuando.}
{351}{}{Oh, de acuerdo. Gracias.}
{360}{larad20}{¿Quieres ganar dinero de forma fácil y rápida? 50 dólares. Dinero fácil.}
{361}{}{Claro.}
{362}{}{Que sea rápido.}
{370}{larad21}{Necesito que averigües si a Metzger le parecería bien que Tyler y yo arreglamos algunos viejos asuntos. Él lo entenderá.}
{371}{}{¿Por qué quieres que yo se lo pregunte?}
{372}{}{Lo haré si tengo la oportunidad.}
{373}{}{Vale.}
{380}{larad22}{Porque no quiero que Tyler vea a nadie de mi gente hablando con Metzger. No quiero decubrir nuestras cartas.}
{381}{larad23}{¿No lo entiendes? Si Tyler me ve de repente hablando con Metzger podría sospechar que algo huele a podrido.}
{382}{}{Ya veremos.}
{383}{}{Vale.}
{390}{larad24}{¿Has averiguado qué hay dentro?}
{391}{}{Componentes químicos en bruto metidos en grandes cajas.}
{392}{}{Unos grandes contenedores que contienen alguna clase de productos químicos.}
{393}{}{Aún no.}
{400}{larad25}{¿Así que ya hablaste con él? ¿Qué te dijo?}
{401}{}{Dijo que sí. Si ganas, tendrás su trabajo, como antes.}
{402}{}{Na.}
{410}{larad26}{Genial. Esperaba eso. He oído que últimamente estaba quejándose de ellos. Aquí tienes tu dinero.}
{411}{}{¿He de asumir que hay algo más?}
{412}{}{Gracias. Adiós.}
{420}{larad27}{Tengo un trabajo más para ti. No sé que tal lo harás, pero dado que fuiste capaz de meterte dentro quizás confíen en ti.}
{421}{}{Me metí de tapadillo.}
{422}{}{¿Qué es eso?}
{430}{larad28}{Estoy segura de que podrás averiguar algo.}
{431}{}{Vale, ¿de qué se trata?}
{440}{}{No podemos hacerles frente en nuestro estado actual. Tienen fondos extra y nos superan en número ligeramente. Si pudieras encontrar algún punto débil que pudiéramos usar para mejorar nuestras posibilidades, o quizás alguna ventaja que pudiéramos explotar...}
{441}{}{¿Eh? ¿Encontrar un punto flaco? ¿Cómo se supone que voy a hacer eso?}
{442}{}{¿Cuánto?}
{443}{}{Considéralo hecho.}
{450}{larad30}{Te daremos 150 dólares. No hay forma de que podamos acercarnos lo suficiente como para averiguarlo por nosotros mismos.}
{451}{}{Me pondré con ello.}
{452}{}{Vale.}
{460}{larad31}{No lo sé. Por eso te estoy pidiendo ayuda.}
{461}{}{Lo intentaré.}
{462}{}{Esto es inútil.}
{470}{larad32}{¿Encontraste algo?}
{471}{}{Sí. Van a dar una fiesta esta noche.}
{472}{}{Aún no. Te lo haré saber.}
{473}{}{Gra.}
{474}{}{Na.}
{480}{}{¡Excelente! Dejarán a muy poca gente. Debería ser una buena ocasión. Nos ocuparemos de la gente de la fiesta después de atacar la iglesia.}
{481}{}{¿Y mi dinero?}
{490}{}{Todavía no, Tendrás que venir con nosotros si quieres tu dinero. No tendrás que luchar, pero es para estar seguros de que no es una trampa. Te daremos 300 dólares en total.}
{491}{larad35}{¿Estás lista?}
{492}{}{Vale, hagámoslo.}
{493}{}{Dame un momento para prepararme.}
{494}{}{De ninguna manera. ¡Guárdate tu dinero!}
{500}{larad36}{Vale, pero tenemos que actuar pronto, así que no te retrases o arruinarás el plan.}
{501}{}{Vale.}
{510}{larad37}{No tienes que luchar. Es dinero fácil.}
{511}{larad38}{Bien, ¿has cambiado de idea?}
{512}{}{Vamos. Estoy lista.}
{513}{}{Vale, volveré.}
{514}{}{No.}
{515}{}{B-bueno.}
{520}{larad50}{Por tu culpa se jodió el plan.}
{521}{larad51}{¡Cobarde!}
{522}{larad52}{No te daremos nada.}
{523}{larad53}{De todas formas seguro que era una trampa.}
{524}{larad54}{Lo siento, no eres de fiar.}
{525}{larad55}{No me fío de ti.}
{530}{larad56}{¡Lo hicimos!}
{531}{larad57}{Gracias por tu ayuda.}
{532}{larad58}{¡Muchísimas gracias!}
{533}{larad59}{Por fin me he vengado por lo que Tyler le hizo a mi hermano.}
{534}{larad60}{Gracias otra vez.}
{540}{larad61}{Ahora que Metzger está muerto, no sé qué va a pasar.}
{541}{larad62}{Quizás deberíamos hacer las maletas.}
{542}{larad63}{¿Has oído que Metzger murió? Ahora no sé que hacer.}
{543}{larad64}{¿Qué será ahora de La Guarida? Quizás vayamos a mejor.}
{544}{larad65}{Esto podría ser lo mejor para todos.}
{550}{larad66}{¡Bastardo!}
{551}{larad67}{¡Puta!}
{560}{larad39}{Gracias. Aquí está tu dinero y 100 dólares extra.}
{570}{larad40}{¿Has matado a Tyler y sus guardias? ¿Y ahora cómo vamos a mostrarle nuestra valía a Metzger? Ahora nunca nos contratará. Era nuestra única oportunidad.}
{571}{larad41}{No tenemos trabajo. Alguien mató a los guardias de Metzger y ahora no quiere hablarnos. Piensa que fuimos nosotros. Oh, vaya.}
{572}{}{Lo siento.}
{573}{}{Mala suerte.}
{574}{}{Fui yo, y vosotros sois los siguientes.}
{575}{}{Oh. Vale, adiós.}
{576}{}{¿Uhr?}
{577}{}{Uhg.}
{590}{larad42}{Te dije que fuéramos juntos. Como no había nadie para vigilar el sitio, fue saqueado y ahora Metzger está la leche de cabreado.}
{591}{larad43}{¡Te dije que encontraras un punto flaco, no que los mataras! Como no había nadie para vigilar el sitio, fue saqueado y ahora Metzger está la leche de cabreado.}
{592}{larad44}{¡Maldición! ¡Te dije que se lo preguntaras a Metzger, no que los mataras! Como no había nadie para vigilar el sitio, fue saqueado y ahora Metzger está la leche de cabreado.}
{593}{larad45}{¡Maldición! ¡Te dije que no les atacaras! Como no había nadie para vigilar el sitio, fue saqueado y ahora Metzger está la leche de cabreado.}
{594}{}{Oh, vaya, debo irme.}
{595}{}{Es una pena.}
{596}{}{Eres la siguiente, puta.}
{597}{}{¡Hmph!}
{598}{}{Tú siguiente.}
{610}{larad68}{Tú si que sabes joder las cosas, ¿no?}
{611}{larad69}{No necesitamos más de tu ayuda.}
{612}{larad70}{Vete a molestar a otro.}
{613}{larad71}{Mejor que Metzger no nos culpe de nada.}
{614}{larad72}{Lo siento. No puedo ayudarte.}
{615}{larad73}{No puedo hablar contigo. Estoy intentando pensar que hacer ahora.}
{616}{larad74}{Espero que Metzger no piense que estamos involucrados.}
{617}{larad75}{¿Y ahora qué vamos a hacer?}
{618}{larad76}{Será mejor que nos vayamos pronto por si acaso Metzger piensa que fuimos nosotros los que matamos a sus guardias.}
{619}{larad77}{¿Has estado en Nuevo Reno? Quizás nos dirijamos allí... o al norte.}
{650}{larad78}{¡De acuerdo! ¡Vamos! ¡Seguidme todos!}
{700}{}{Muy bien, nos ocupamos de la pandilla esqueleto aquí en la iglesia, pero todavía Tyler y sus compinches están en el área residencial. Deberían estar bastante borrachos por ahora y podemos atraparlos desprevenidos fácilmente. ¿Estás lista para terminar esto?}
{701}{}{Déjame sanar primero. Te avisaré cuando estoy listo.}
{702}{}{Vamos.}
{710}{larad47}{¿Estás lista para atacar a Tyler y su equipo?}
{720}{larad48}{Bueno, no te alejes demasiado. Necesitamos terminar esto esta noche o lo haremos sin ti.}
{721}{}{Volveré pronto.}
{722}{}{Vamos.}
{730}{larad49}{Lo hicimos. ¡No puedo creerlo! Regresamos a la iglesia para tomar el mando. Encuéntranos allí por tu recompensa.}
