{100}{}{Ves a una joven muy atractiva.}
{101}{}{Ves a Rebecca.}
{150}{}{Ves a Rebecca, la dueña del Casino Bar de Becky.}
{200}{rbcca1}{Hola, soy Rebecca. ¿Te sirvo algo de beber? Estoy segura de que tienes sed después de haber viajado por el Yermo.}
{201}{rbcca2}{¡Oye! ¿Quieres una copa o sólo has vuelto a saludar?}
{202}{rbcca3}{¡Hola! Me alegra que hayas vuelto. ¿Alguna pregunta o estás aquí para tomar algo de buen whisky?}
{203}{rbcca4}{Estoy encantada de volver a verte. ¿Necesitas algo?}
{204}{rbcca5}{¡Espero que todo le vaya bien a mi cliente favorita! ¿Qué podemos hacer por ti?}
{205}{rbcca6}{¡Hola!}
{206}{rbcca7}{Siempre me alegra volver a verte.}
{207}{rbcca8}{¡Hola! ¿Quieres una copa? ¡El mejor whisky de la zona!}
{208}{rbcca9}{¡Hola!}
{209}{rbcca10}{¡Eres tú! Eso me había parecido. ¿Qué tal una copa, cariño mío?}
{210}{rbcca11}{¿Vuelves a por más del mundialmente famoso whisky de Rebecca?}
{211}{rbcca12}{Bienvenida de nuevo al Bar y Casino de Rebecca. ¿En qué puedo servirte?}
{212}{rbcca13}{Hola. ¿En qué puedo ayudarte?}
{213}{rbcca14}{¿Qué deseas? ¿Quizás una copa?}
{214}{rbcca15}{¿Querrás una copa, o quizás otra cosa?}
{215}{rbcca16}{¿En qué puedo servirte?}
{216}{rbcca17}{Saludos. ¿Qué podemos hacer por ti?}
{217}{rbcca18}{¿Necesitas algo?}
{218}{rbcca19}{Me alegra volver a verte. ¿En qué puedo ayudarte?}
{219}{rbcca20}{¿Qué?}
{220}{rbcca21}{¿Sí?}
{221}{rbcca22}{¿Y ahora qué?}
{222}{rbcca23}{Por favor, date prisa. Hoy es un día ajetreado. ¿Qué necesitas?}
{223}{rbcca24}{¿Qué puedo hacer por ti? Estoy muy ocupada.}
{224}{rbcca25}{¿Has venido a por una copa? Las mesas están allí.}
{225}{rbcca26}{No estoy de buen humor. ¿Qué quieres?}
{226}{rbcca27}{¿Ya has vuelto? Supongo que querrás una copa?}
{240}{rbcca28}{Claro, guapa.}
{241}{rbcca29}{¿Qué es lo que quieres saber?}
{242}{rbcca30}{Me encantaría.}
{243}{rbcca31}{Por supuesto.}
{244}{rbcca32}{Claro.}
{245}{rbcca33}{No importa.}
{246}{rbcca34}{Te ayudaré si puedo.}
{247}{rbcca35}{Por supuesto, no seas tonta.}
{248}{rbcca36}{Lo que sea. ¿Qué querías?}
{249}{rbcca37}{Haré lo que pueda para ayudarte. ¿Qué querías saber?}
{250}{rbcca38}{Pregunta lo que quieras.}
{251}{rbcca39}{Si insistes.}
{252}{rbcca40}{Supongo que sí.}
{253}{rbcca41}{Que sea rápido. Tengo un negocio que llevar.}
{254}{rbcca42}{Bien, vale. ¿Qué va a ser?}
{255}{rbcca43}{Supongo.}
{256}{rbcca44}{¿Qué?}
{257}{rbcca45}{No, lo siento.}
{258}{rbcca46}{Ahora mismo no.}
{270}{}{Necesito una copa.}
{271}{}{Estoy buscando a un mercader que vende objetos de Refugios.}
{272}{}{Estoy buscando a un mercader llamado Vic.}
{273}{}{¿Tienes algún trabajo disponible?}
{274}{}{Sobre ese trabajo...}
{275}{}{¿Algo más de trabajo que pueda hacer?}
{276}{}{Nada. Adiós.}
{277}{}{Wekee.}
{278}{}{¿Ruh ruh?}
{279}{}{Iho shasha.}
{280}{}{dy.}
{281}{}{¿Ruh ruh?}
{300}{rbcca47}{El whisky es mi especialidad. Es casi una tradición en la familia Dyer. Y sólo al barato, baratísimo precio de 5 dólares.}
{301}{rbcca48}{Las copas siguen a 5 dólares, y la familia Dyer sigue haciendo las mejores bebidas del mundo entero.}
{302}{rbcca49}{¿Tú bien? ¿Quieres whisky? Sólo 5 dólares.}
{303}{}{Tomaré una copa.}
{304}{}{¿Por qué son tan baratas tus copas?}
{305}{}{¿Dyer?}
{306}{}{¿Puedo hacerte una pregunta?}
{307}{}{Adiós.}
{308}{}{Wekee.}
{309}{}{Urka.}
{320}{rbcca50}{Oh, es el nombre de la familia. El nombre de los Dyer ha estado en el negocio de los bares desde hace largo tiempo... anterior a la guerra, por supuesto.}
{321}{rbcca51}{Como dije, es mi nombre familiar. Solía haber pubs, salones y otros sitios de los Dyer por todo el mundo.}
{322}{}{Tomaré una copa.}
{323}{}{¿Puedo preguntarte otra cosa?}
{324}{}{Adiós.}
{330}{rbcca52}{Bueno, dado que eres tan buen cliente, te confiaré un pequeño secretillo. Es muy simple... tengo una destilería. Un amigo de un pueblo cercano me enseñó como construir una. ¿Querrás otra copa?}
{331}{rbcca53}{Lo siento, es un secreto. Además, no te conozco demasiado. No querría que Frankie se enterara. Ya supone un problema tal y como es. ¿Sigues queriendo una copa? Seguro que es lo que necesitas.}
{332}{}{Claro. tomaré una.}
{333}{}{¿Puedo preguntarte otra cosa?}
{334}{}{Vale, gracias.}
{340}{rbcca54}{Aquí tienes. Muchísimas gracias.}
{341}{}{Gracias. ¿Puedo hacerte otra pregunta?}
{342}{}{Vale, gracias.}
{343}{}{Gra-cia a ti.}
{344}{}{¿Preguntar-y?}
{350}{rbcca55}{Lo siento. Creo que no.}
{351}{rbcca56}{Fred me debe 200 dólares. Si puedes conseguir de algún modo que me pague, te daré algo por las molestias.}
{352}{rbcca57}{Todavía está esa deuda que necesita ser cobrada.}
{353}{rbcca58}{Le presté a Derek un libro mío hace un tiempo. Te pagaré 80 dólares si consigues que me lo devuelva.}
{354}{rbcca59}{Aún sigo queriendo mi libro.}
{355}{}{¿Cuál es el truco?}
{356}{}{Cuéntame más.}
{357}{}{¿Puedo hacerte una pregunta?}
{358}{}{Adiós.}
{370}{rbcca60}{¿Trampa? Oh, vaya, si conocieras a Fred lo entenderías. Me debe el dinero desde hace bastante tiempo. Lo daría por perdido, pero si pudieras recuperarlo, me dejarías anonadada... y te estaría agradecida. Está en algún lugar del pueblo, estoy segura.}
{371}{rbcca61}{El libro era 'La Flor de Lavanda'. Derek debería estar cerca del local de Mamá, al este del pueblo.}
{372}{}{Sé lo que podemos hacer.}
{373}{}{Parece fácil.}
{374}{}{Ya lo encontré.}
{375}{}{Te lo traeré.}
{385}{rbcca62}{¿No lo habrás conseguido, no? Me dejarías alucinada.}
{386}{rbcca63}{Oh, ¿has encontrado mi libro? Será mejor que Derek no lo haya estropeado.}
{387}{}{Sí, lo he hecho.}
{388}{}{Lo siento. Está muerto.}
{389}{}{Lo siento, pero Derek también está muerto.}
{390}{}{Lo siento, pero ha muerto.}
{391}{}{Sí. Aquí está.}
{392}{}{No, lo siento.}
{400}{rbcca64}{No puedo creerlo. ¿Cómo lo has hecho? Oh, no importa. Es que estoy impresionada, eso es todo. Para mostrarte mi agradecimiento, lo compartiré contigo, a medias. Muchas gracias, ha sido un acto muy honesto por tu parte.}
{401}{rbcca65}{Oh, estoy tan contenta de que hayas podido encontrarlo... Muchísimas gracias. Aquí está tú dinero.}
{402}{}{No hay de qué.}
{410}{rbcca66}{No puedo creerme que ambos estén muertos. Lo siento. Gracias por decírmelo. Si me disculpas...}
{411}{rbcca67}{No puedo creerme que haya muerto... tras todos estos años.}
{412}{}{Claro.}
{413}{}{...}
{420}{rbcca68}{Sí, sé quién es. Ese Vic... es el tipo al que Metzger ha encerrado.}
{421}{rbcca69}{Sí, conozco a Vic. Metzger le ha encerrado. No estoy segura del porqué.}
{422}{}{¿Quién es Metzger?}
{423}{}{Tengo otra pregunta.}
{424}{}{¡Genial! Adiós.}
{430}{rbcca70}{¿Has venido a La Guarida y no sabes quién es Metzger? Es el maestro esclavista. Está en la parte este del pueblo. Es difícil de no ver.}
{431}{}{Tengo otra pregunta.}
{432}{}{Gracias.}
{440}{rbcca85}{¡Asesina!}
{441}{rbcca86}{¡Infanticida!}
{442}{rbcca87}{Por favor, vete.}
{443}{rbcca88}{No hago tratos con los de tu calaña.}
{444}{rbcca89}{¡No voy a morir sin luchar!}
{450}{rbcca71}{¡Buffy! ¡Eres tú! ¿Qué tal estás? ¡Cuanto tiempo!}
{451}{}{¿Eh?}
{452}{}{¿Eh?}
{460}{rbcca72}{Dave te manda saludos y dijo que ojalá pudiera estar aquí para decirte hola, pero tuvo que marcharse.}
{461}{}{¿Por qué?}
{470}{rbcca73}{Por algo de un comando... o de que iba a ir tras un comando. No estoy muy segura. Algo así.}
{471}{}{Oh.}
{480}{rbcca74}{Oh, dijo que te diera esto. Es un regalo de la familia Hendee. Debería serte de ayuda.}
{481}{}{¿Qué es eso?}
{490}{rbcca75}{Oh, tan sólo unas cuantas cosillas. Aquí las tienes. [Becky te da 1.000 dólares, 5 estimulantes, una armadura metálica, una Uzi, 5 cargadores de munición, una granada de plasma y una flor].}
{491}{}{¡Gracias!}
{500}{rbcca76}{No hay problema. Te las estaba guardando. Bueno, será mejor que vuelva al trabajo.}
{501}{}{Gracias, adiós.}
{510}{rbcca77}{¡No lo has oído! ¡Está muerto! Oh, sé que no debería alegrarme, pero era un hombre muy malvado.}
{511}{}{Seguro que dio bastante guerra antes de morir.}
{512}{}{Tengo una pregunta.}
{513}{}{Sí, lo era. Adiós.}
{514}{}{ mata!}
{520}{rbcca78}{¿Qué? ¿Tú? Yo... no sé que decir. Era un hombre tan malvado...}
{521}{}{Dar las gracias sería suficiente.}
{522}{}{Humph.}
{530}{rbcca79}{Oh, sí, dar las gracias sería suficiente. Sé que no está bien, pero... toma, guárdate este dinero. [Becky te da 1.000 dólares]}
{531}{}{Guárdate tu dinero, Rebecca.}
{532}{}{Muchas gracias.}
{533}{}{¡Gacias!}
{534}{}{¡Ug! Mujer guapa.}
{540}{rbcca80}{Eres un hombre maravilloso. Incluso aunque no apruebe tus acciones. Le has hecho un gran servicio al mundo.}
{541}{rbcca81}{Eres una mujer maravillosa. Incluso aunque no apruebe tus acciones. Le has hecho un gran servicio al mundo.}
{542}{}{Gracias.}
{550}{rbcca90}{Aquí no eres bienvenida. Por favor, vete.}
{551}{rbcca91}{Por favor, vete.}
{560}{rbcca82}{¿Por qué destruiste mi destilería? ¿Qué te había hecho yo a ti?}
{561}{}{Me pagaron para hacerlo.}
{562}{}{No tengo porque dar explicaciones a nadie.}
{563}{}{No sé de que estás hablando.}
{564}{}{Lo que sea.}
{565}{}{Ooba gooba.}
{570}{rbcca83}{Oh, ¿de verdad? Ese ruin de Frankie te hizo hacerlo, estoy segura. Sólo haré otra, sabes.}
{571}{}{No me importa. Yo ya he cobrado.}
{572}{}{Ya.}
{573}{}{No me sorprendería.}
{580}{rbcca84}{Así que, ¿tú también eres una cobarde? Ya me lo figuraba.}
{581}{}{...}
