{100}{}{Un hombre con servoarmadura.}
{101}{}{Arthur, hijo de Uther Pendragón.}
{102}{}{Lleva la bragueta bajada.}
{103}{arth1}{Saludos, viajeros. Mi nombre es Arturo, hijo de Uther Pendragón, de la Hermandad del Acero. Estamos buscando la Santa Granada de Antioquía. ¿Viéronla vuesas mercedes?}
{104}{}{¿La Santa qué?}
{105}{}{Respuesta del jugador}
{106}{}{Unga.}
{107}{arth13}{No hay tiempo para charlas. Estamos en una misión.}
{108}{arth14}{Buscamos la Santa Granada de Antioquía.}
{109}{arth15}{¡Por la Hermandad del Acero!}
{110}{arth16}{Hmm... ¿una golondrina africana o europea?}
{111}{arth17}{¡Oíd vos! Eso no es vuestro, ¿no?}
{112}{arth18}{Os aviso. Mantened las manos alejadas.}
{113}{arth19}{Basta. Ya es suficiente.}
{114}{arth2}{¿La Santa Granada de Antioquía? Tan sólo es el arma antipersonal de mano más grande de su clase.}
{115}{}{¿Por qué buscas un arma tan terrible?}
{116}{arth3}{Somos la Hermandad del Acero. Buscamos encontrar la más devastadora de las armas de nuestros ancestros, y ponerla a buen recaudo de aquellos que quieran abusar del poder de la Santa Granada de Antioquía.}
{117}{}{¿Por qué?}
{118}{arth4}{Bueno... porque la Hermandad del Acero se dedica a proteger a los débiles e indefensos, y esa cosa podría herir a alguien.}
{119}{}{¿Por qué?}
{120}{arth5}{Umm... porque es el único acto que la moral nos permite hacer.}
{121}{}{¿Por qué?}
{122}{arth6}{Porque... um... Mirad, estamos muy ocupados. ¿Vais a ayudarnos o no? ¿Habéis visto la Santa Granada de Antioquía?}
{123}{}{Sí.}
{124}{}{No.}
{125}{arth7}{Bien, ¿por qué no lo habéis dicho? Si pudiérais decirnos dónde, partiríamos y vos podríais volver a lo que quiera que estuviérais haciendo.}
{126}{}{[Señalas una dirección al azar]}
{127}{arth8}{De acuerdo entonces. Gracias por vuestra ayuda. Aquí tenéis algo por las molestias.}
{128}{}{¡Espera! Yo también estoy en una misión. Busco el sagrado GECK. ¿Lo has visto?}
{129}{arth9}{Bien, entonces no tiene sentido continuar esta conversación. Nos marchamos.}
{130}{}{[FIN]}
{131}{arth10}{¡Maldita plebeya!}
{132}{}{[FIN]}
{133}{arth11}{¿GECK habéis dicho? Porque si, tenemos un par de ellos. No necesitamos otro. Gracias de todos modos.}
{134}{}{Dado que tenéis un par, podríais darme uno.}
{135}{arth12}{No. No. No puedo hacer eso. No sería correcto que terminárais vuestra misión de esa forma. Id a conseguir el vuestro. [Señala en una dirección de la misma forma que lo hiciste tú cuando te preguntó donde estaba la Santa Granada de Antioquía]}
{136}{}{[FIN]}
{200}{arth20}{¿Habláis en la lengua del rey?}
{201}{arth21}{Holaaaa.}
{202}{arth22}{Eh, estoy aquí.}
{203}{arth23}{Si pudiérais prestarme un momento de vuestro tiempo.}
{204}{arth24}{Ejem...}
{205}{arth25}{Vamos. No me ignoréis.}
{206}{arth26}{¡Por favoooor! Necesito preguntaros algo importante.}
{207}{arth27}{Bien, debemos continuar nuestra búsqueda de la Santa Granada de Antioquía. Vamos, Patsy.}
{300}{}{Nuestra búsqueda se ha cumplido!}
{301}{}{Arthur, a vuestro servicio.}
