{100}{}{Ves a un hombre apenas vestido.}
{101}{}{Ves a Kaga.}
{103}{}{Lleva pantalones y parece que viene de una tribu.}
{104}{kaga6}{¡Kaga debería haber sido El Elegido!}
{105}{kaga7}{Cómo se atreve Arroyo a desterrarme de la tribu.}
{106}{kaga8}{¡Kaga se vengará de ti!}
{107}{kaga9}{Kaga te enviará al otro mundo.}
{108}{kaga10}{¡Volverás a ver a Kaga!}
{109}{kaga11}{¡Kaga nunca ha sido derrotado!}
{110}{kaga12}{Kaga se dedicará en cuerpo y alma a buscar tu destrucción.}
{150}{kaga1}{[Un alto y fornido guerrero está frente a ti, sus ojos brillan con odio mientras te mira.] Entonces, ellos echan a Kaga, ¿y te consideran el Elegido? ¡JA! ¡¿Crees que ser la nieta del Morador del Refugio te hace especial?! ¡¿Crees que eres mejor que yo, Kaga el Grande?!}
{151}{}{Bueno, yo SOY el Elegido, ¿no?}
{152}{}{Hey ahora, espera un segundo. Nunca dije que era mejor que tú.}
{160}{kaga2}{¡Ese título no significará nada cuando Kaga te arranque la cabeza de tus hombros!}
{161}{kaga3}{No hay palabras que puedan salvar tu piel. Con tu muerte, el honor de Kaga será restaurado. ¡Kaga ahora tomará su venganza!}
{200}{}{¿Ooglie?}
{201}{kaga4}{¿¡Qué!? ¿Te eligieron a *ti* para ser el Elegido? Oh mi, se han vuelto desesperados.}
{202}{}{No gusta. Parece mal.}
{203}{kaga5}{Kaga ni siquiera se molestará en hablar contigo más. ¡Prepárate para morir a manos de Kaga!}
