{100}{}{Ves a un apuesto joven.}
{101}{}{Ves a Davin.}
{102}{}{Ves a un hombre joven, en la veintena. Se parece mucho a Grisham.}
{150}{davin1}{Si me lo hubieras preguntado, hubiera sido todo tuyo.}
{151}{davin2}{¡Hmpf! Miria no es tan buena en la cama como yo.}
{152}{davin3}{No me puedo creer que me hayas hecho prostituirme.}
{153}{davin4}{La próxima vez hagamos un trío.}
{154}{davin5}{Ooohhh… él es una preciosidad.}
{155}{davin6}{Pregúntale a ella.}
{156}{davin7}{Eso ha sido genial, ¿quién es el siguiente?}
{157}{davin8}{¡Hola! Me llamo Davin; ayudo a mi padre a llevar el matadero de Modoc.}
{158}{}{Estoy buscando el reloj de oro de Cornelius. ¿Lo has visto?}
{159}{}{¿Qué es lo que haces en el matadero?}
{160}{}{He oído rumores sobre las cosas que haces con los brahmines.}
{161}{}{Háblame de tu padre.}
{162}{davin9}{Hola de nuevo.}
{163}{davin10}{Sabía que volverías.}
{168}{}{¿Por qué no nos ponemos más cómodos?}
{171}{}{Quédate aquí.}
{172}{davin11}{Claro, ahora no estoy ocupado. Pregunta.}
{178}{davin12}{No, no lo he visto por ninguna parte.}
{179}{}{¿Puedo hacerte más preguntas?}
{180}{davin13}{Bueno, yo... quiero decir, yo... superviso y me ocupo de cosas. Después de todo, soy el hijo del dueño. Voy a heredar este sitio cuando mi padre la palme.}
{182}{davin14}{Es mentira. Solo voy al establo por la noche para... comprobar que todo está cerrado. Sabes, por los animales salvajes y eso.}
{184}{davin15}{Papá lleva el matadero. Para ser un padre no está mal. Un consejo si haces negocios con él. Al tratar con él, siempre hay que estar al tanto de la letra pequeña.}
{186}{davin16}{Vuelve y ven a verme si quieres... hablar otra vez.}
{187}{davin17}{Caramba, nunca pensé que una mujer tan hermosa intentaría seducirme. ¡Un momento! ¡Tú... no eres una mujer! Oh... no te preocupes, no tengo prejuicios. No le diré nada a nadie si no quieres.}
{188}{davin18}{Debo de estar soñando. No me creo que una mujer tan hermosa este intentando seducirme. ¿Estás intentando seducirme, verdad?}
{189}{}{Mirarte a los ojos es como estar en el paraíso. No rompamos la magia del momento con palabras. Que nuestros actos hablen por nosotros.}
{190}{}{Deja de hablar; vas a arruinar el momento. Tan sólo túmbate y disfruta.}
{191}{}{Debe haber un error; tan sólo quería hacerte algunas preguntas.}
{192}{}{Gracias por la oferta, pero no. Uhhh... me marcho ya.}
{193}{davin19}{¡Oh Dios! ¡Tómame! ¡Tómame ahora! [Se arranca la ropa, entonces te arranca la tuya y luego... usa tu imaginación].}
{194}{davin20}{[Risilla] ¡Me pido furgón de cola! La próxima vez puedes serlo tú.}
{195}{}{[Dos horas después: La tierra ha temblado y esta cama nunca volverá a ser la misma].}
{196}{}{[Una hora después, y tras el mejor orgasmo que hayas tenido nunca...]}
{197}{}{[Media hora después, yaces exhausta...]}
{198}{}{[Quince minutos después, tras un par de jadeos...]}
{199}{}{[Has conseguido llegar a quitarte la camiseta antes de que desaparecieran las ganas].}
{200}{}{Tengo que irme. Adiós.}
{400}{davin21}{¡Papá!}
{401}{}{¡Oh-oh!}
{402}{davin22}{¡Sí quiero!}
{405}{davin23}{¡Tío Biff!}
{410}{}{Uhh...}
{411}{}{Ehhh... Continúa, por favor...}
{412}{}{Yo... eh... yo…}
{413}{}{Um… Sí quiero.}
{450}{davin24}{Uhhh, no es conmigo con quien deberías hablar.}
{500}{davin25}{Oh chica, voy a ser el jefe de todo esto.}
{1000}{davin26}{Sí, cariñito.}
{1001}{davin27}{¿Qué puedo hacer por ti, amorcito?}
{1005}{}{No lo entiendes. No quiero tenerte pegado a mí cuando estamos andando por ahí.}
{1006}{}{Lo que estás haciendo mal es que necesito que vayas bastante por detrás de mí.}
{1007}{davin28}{¿Pero... pero... qué he hecho mal?}
{1008}{davin29}{¿Qué es lo que quieres, querida?}
{1009}{}{Gracias, estaba empezando a fastidiarme. ¿Ahora qué, amor?}
{1010}{davin30}{Suelo despellejar a los brahmines en el matadero, así que soy bastante hábil con el cuchillo. Además, papá me hizo matar un brahmin a golpes con una palanca. Supongo que podría usar una maza si fuera necesario. Uhhh, oh, papá me enseñó una vez a disparar con la pistola, pero me asusté y casi le disparo sin querer.}
{1020}{}{Necesito más espacio, Davin.}
{1100}{davin31}{Estoy completamente sana y lista para irnos.}
{1200}{davin32}{No me queda más que algún rasguño.}
{1300}{davin33}{Bueno, estoy casi curado pero me vendría bien algo más de curación cuando tengamos la oportunidad.}
{1400}{davin34}{Me he curado todo lo que he podido pero sigo bastante malherida.}
{1500}{davin35}{No, cariño; quiero ir contigo.}
{1600}{davin36}{Sí, lo dejaré a un lado.}
{1700}{davin37}{Vale, voy detrás tuyo.}
{1800}{davin38}{Entonces no seré capaz de protegerte. No, mejor me quedo cerca.}
{1900}{davin39}{¿Ah, sí? De ninguna manera. No voy a quitarte el ojo, mi pequeña máquina sexual.}
{2000}{davin40}{Ayy. Creo que me he roto un miembro. ¿Puedes besarlo y hacerlo mejor?}
{2001}{davin41}{Eh, siento que estoy ardiendo. Creo que estoy irradiado.}
{2002}{davin42}{Eh, me siento muy enfermo. Creo que estoy envenenado.}
