{100}{}{Ves a un hombre de apariencia dura y bien vestido, moviéndose con lentitud deliberada.}
{101}{}{Es Merk: las gentes de por aquí lo llaman El Hombre.}
{102}{}{Este tipo tiene un arrogante aire de frialdad, como si le importases lo mismo que la mosca que acaba de aplastar entre sus dedos.}
{103}{merk61}{¡Oye, te he visto en las películas! Vienes a enseñarme algo de acción, ¿verdad?}
{104}{merk62}{¿Qué significa esto, perturbando mi descanso así? Lárgate de aquí.}
{105}{merk63}{Perdóname, tengo un negocio que dirigir.}
{106}{merk64}{Si quieres hablar conmigo de negocios, puedes reunirte conmigo en el Rawhide. De lo contrario, déjame.}
{107}{merk65}{Te he visto en la pantalla, ¿no? Tienes impresionantes, eh... credenciales.}
{108}{merk66}{Tienes cierta mirada de seguridad en los ojos. Pásate por el Rawhide: siempre puedo servirme de alguien como tú.}
{109}{merk67}{Mierda, ¿qué es ese olor? Algo que acaba de entrar en la habitación.}
{110}{merk68}{Ve a servirme otro whisky, y rapidito.}
{111}{merk69}{Ahora mismo no tengo tiempo.}
{112}{merk70}{Aquí soy un invitado. Deja de molestarme.}
{113}{merk71}{Oye, muñeca, lo tienes todo en su sitio. El gusto de Carlson está mejorando.}
{114}{merk72}{No hago negocios aquí.}
{115}{merk73}{No te conozco. Soy un hombre de negocios respetable.}
{116}{merk74}{Vaya, que me aspen si no es la cobardica. Lárgate y déjame en paz.}
{117}{merk75}{Así que has decidido venir a verme después de todo, ¿eh, muñeca?}
{118}{merk76}{No sé nada acerca de nada, comprendo.}
{119}{merk77}{Al vice no le va a gustar que molestes a sus invitados.}
{120}{merk78}{Aquí se sirve un licor bueno de cojones.}
{121}{merk79}{¡Apártate de mi camino!}
{122}{merk80}{Si quieres hablar con alguien, cómprate un amigo.}
{123}{merk81}{No doy indicaciones ni devuelvo el cambio. Lárgate.}
{124}{merk82}{¿Qué es esto? ¿La hora de la sociabilidad?}
{125}{merk1}{Soy Merk. ¿Qué puñetas quieres?}
{126}{merk2}{¿Otra vez tú?}
{127}{merk3}{Bien, mantenga cortés, punk, o esto podría ponerse feo.}
{128}{}{Oort.}
{129}{}{Estoy buscando trabajo.}
{130}{}{Fuentes informadas dicen que eres el hombre al que ver para hacer negocios, si sabes a lo que me refiero.}
{131}{}{Se dice que tú eres el hombre que despiezó mi coche.}
{132}{}{Estoy buscando algo de información.}
{133}{}{Hay quien dice que puede que sepas un par de cosas sobre, eh, digamos, piezas que se pierden de los coches.}
{134}{merk4}{¿Otra vez tú? ¿El trabajo está hecho?}
{135}{}{Glub.}
{136}{}{No.}
{137}{}{Tengo algunas preguntas.}
{138}{merk5}{Hmm... Fuerte. Idiota... Si quieres un trabajo, habla con Mira. ¿Entendido? Mi-ra. Por ahí.}
{139}{merk6}{¿Igual que hacer ruidos? ¿Puede alguien sacar a este mojón de brahmin de aquí?}
{140}{merk7}{¿Eres así de estúpida? ¿Crees que simplemente voy a contratar a cualquiera? Para trabajar para mí, tienes que demostrar que eres buena para algo.}
{141}{}{¿Y qué tal si simplemente le disparo a Lenny? Se lo merece.}
{142}{}{¿Probarlo cómo?}
{143}{}{¿Quizá conoces a alguien que querría algo de jet?}
{144}{}{Escucha, soy}
{145}{}{Claro. Igual que tengo que probarme a mí mismo para ti. Olvídalo, escoria.}
{146}{merk8}{Fue el maldito Doofus, ¿verdad? Ese drogadicto habla demasiado para su propio bien. Te diré algo: lo silencias por mí (considéralo un favor) y entonces hablaremos.}
{147}{}{Es un trato.}
{148}{}{¡Eh, eh! ¡Yo no tengo tanta sangre fría!}
{149}{merk9}{Y van a decir que eras una tonta del culo. Muchachos...}
{150}{merk10}{Interesante. ¿Y quién diría algo así?}
{151}{}{Déjate de gilipolleces, gordinflón. Si no recupero lo que es mío, alguien va tener que ir a comprarse un traje para su entierro.}
{152}{}{Precioso. ¿Vas a contestar a mi pregunta o no?}
{153}{}{Oh, sólo es algo que he oído. Sólo quería saber qué es lo que dirías.}
{154}{merk11}{Suponiendo que sepa algo. ¿Qué pasa con ello?}
{155}{}{Ahora bien, si una persona tenía algunas cosas que ahora le faltan, ¿supones que tendría que comprar dichas cosas de nuevo?}
{156}{}{¡Quiero mi mierda de vuelta, gordinflón!}
{157}{}{¿Qué te parece si hablo con la ley?}
{158}{merk12}{Me he hartado de esto. Muchachos, encargaos de nuestra invitada.}
{159}{merk13}{Creo que a Lenny no le gustaría eso.}
{160}{}{Probablemente, pero no lo estaba pidiendo.}
{161}{}{Hazlo a tu manera.}
{162}{}{Cierto. Ha estado demasiado aburrido por aquí. Es hora de un poco de un uno-a-uno en el sótano. Vamos, Lenny, quiero verte matar a éste.}
{163}{merk14}{También yo tengo problemas que necesitan solución.}
{164}{}{¿Cómo qué?}
{165}{merk15}{¿Jet? ¿Estás proponiendo algo...?}
{166}{}{Aquí mi amigo sabe cómo conseguirlo. ¿Te interesa?}
{167}{}{¿Algo ilegal? No, no lo haría.}
{168}{merk16}{Intrigante. Te daré 1.000 dólares por sus servicios.}
{169}{}{Es un trato.}
{170}{}{No, no puedo hacerle eso a un amigo.}
{171}{merk17}{Parece que podemos hacer negocios, amiga. Este es el trato: hay un científico chiflado en la ciudad, el doctor Henry. Tiene ciertos papeles que quiero. Pagaré $1.000 por ellos. Oh, y no quiero que se haga daño al doctor Henry. Vivo resulta útil. ¿Te interesa?}
{172}{}{Estoy en ello.}
{173}{}{Paso, no es mi estilo.}
{174}{merk18}{Saber cuesta dinero. ¿Hablo claro?}
{175}{merk19}{"El precio de la sabiduría es superior al de los rubíes".}
{176}{}{Aquí tengo 50 dólares.}
{177}{}{Olvídalo.}
{178}{merk20}{Oh, tú eres esa persona.}
{179}{}{Continúa}
{180}{merk21}{Bueno, por lo que a mí respecta, aquí no eres más que un montón de estiércol.}
{181}{merk22}{Ya te había supuesto una cobarde.}
{182}{merk23}{Vale. No pasa nada. No quiero problemas. Te diré una cosa, incluso haré que mis muchachos pongan el material justo donde lo encontraron.}
{183}{}{Mejor que sea así, o volveré.}
{184}{}{¡No me vengas con historias!}
{185}{merk24}{Tal persona podría ser capaz de hacerlo.}
{186}{merk25}{Ahora, te sugiero que te vayas.}
{187}{merk26}{Por supuesto, avisa a los oficiales. Desde luego, asumo que tienes pruebas que respalden una acusación de esa naturaleza.}
{188}{}{Sí, claro.}
{189}{}{No importa.}
{190}{merk27}{Como cierta maldita Hubologista en la ciudad que me ha irritado. En cuanto hayas rascado esa picazón, vuelve a hablar conmigo.}
{191}{}{Considéralo hecho. Tengo justo el rascador preciso para él, pero... ¿qué es una Hubologista y dónde puedo encontrarla?}
{192}{}{¡Cómo te atreves a hablar en contra de la auténtica creencia!}
{193}{}{Lo siento, no me involucraré en guerras religiosas.}
{194}{merk28}{Bien, soy un hombre culto. ¿Cuál es tu pregunta?}
{195}{merk29}{Pregunta lo que quieras.}
{196}{}{Estoy buscando el Refugio 13.}
{197}{}{¿Alguna vez has oído hablar de un GECK?}
{198}{}{¿Qué sabes acerca de cierto grupo llamado los Rangers?}
{199}{}{¿Qué puedes decirme de cierto tipo llamado Westin?}
{200}{}{Estoy buscando información sobre el vicepresidente Carlson.}
{201}{}{Eso es todo.}
{202}{merk30}{Lo que pagas te permite una pregunta. Otra te costará otros 50.}
{203}{}{Bien, aquí están.}
{204}{}{Tengo todos los datos que necesito.}
{205}{merk31}{Da la casualidad de que tengo un mapa al Refugio 13. Por sólo 1.000 pavos. ¿Te interesa?}
{206}{}{Claro. Me lo llevo.}
{207}{}{Seguro que también venderías hielo a un esquimal.}
{208}{}{Quizá más tarde.}
{209}{merk32}{¿Es alguna clase de droga en Nuevo Reno? Nunca he oído hablar de ello.}
{210}{}{No. Sin embargo, tengo algunas preguntas más.}
{211}{}{Eso es todo lo que necesitaba saber.}
{212}{merk33}{¿Esos bastardos? Mejor que se mantengan lejos de aquí o les abriré un agujero.}
{213}{}{Bien, eso ha resultado aleccionador. Otra pregunta.}
{214}{}{Eso es todo lo que necesitaba saber.}
{215}{merk34}{El ranchero, ¿eh? Vino aquí una vez, a punto de pasar a mejor vida. El doctor de la ciudad tuvo tuvo que presentarse con unas pastillas: parece que Westin tiene una afección cardíaca. Arruinó el negocio para el resto de la noche.}
{216}{}{Gracias por la información. Tengo algunas preguntas más.}
{217}{}{Eso es todo lo que necesitaba saber.}
{218}{merk35}{Como buen ciudadano, aplaudo la oposición de Carlson a cualquier influencia de Nuevo Reno por aquí. Desde que Westin está muerto, he estado ayudando con la seguridad del vicepresidente.}
{219}{}{Oh, bueno, supongo que nunca llegaremos a conocer al hombre. También he oído hablar mucho de él.}
{220}{}{Eso es todo lo que necesitaba saber.}
{221}{merk36}{¿Eso es todo?}
{222}{}{No, yo tengo algunas preguntas más.}
{223}{}{Sí, eso es todo por ahora.}
{224}{merk37}{Oye, un hombre tiene que intentarlo. El Refugio 13 es prácticamente una religión por aquí. Incluso construyeron una estatua de algún idiota que se supone que procedía de allí. Eso es todo lo que sé.}
{225}{merk38}{Te vendí un mapa. Prueba a usarlo.}
{226}{merk39}{¿Ese mapa no sirvió? Lo siento. El tipo juró que era genuino. ¿Cómo iba yo a saberlo? No sé donde está el Refugio 13.}
{227}{}{Tengo algunas preguntas más.}
{228}{}{Eso es todo lo que necesito saber.}
{229}{merk40}{¿Sabes qué? Me gusta tu trabajo y Carlson podría tener otro guardia. Espera un poco y habrá un trabajo esperando por ti ahí abajo.}
{230}{}{Estoy en ello, Merk.}
{231}{}{No necesito un trabajo. Gracias de todos modos.}
{232}{merk41}{Excelente. Vuelve cuando lo hayas hecho.}
{233}{merk42}{Eso es muy preocupante. Muchachos, matadlo y recuperad la evidencia.}
{234}{merk43}{Tus patéticos intentos de intimidarme son casi divertidos, pero ahora te sugiero que te vayas antes de que me canse de este juego.}
{235}{merk44}{Ah, he escuchado las noticias. ¿Sigues interesado en un trabajo?}
{236}{}{Sí, estoy cansado de regalitos. Podría hacer el trabajo.}
{237}{}{No.}
{238}{merk45}{¿Qué demonios estás haciendo aquí?}
{239}{}{Antes me pasé de la raya. No lo volveré a hacer. Sólo necesito un poco de tu tiempo.}
{240}{}{Haré lo que quiera, comadreja.}
{241}{merk46}{¡Sal de aquí, borrica!}
{242}{merk47}{¿Entonces que estás haciendo aquí, pedazo de imbécil? ¡Si quieres impresionarme, entonces haz lo que debes!}
{243}{merk48}{¡No voy a hablar contigo hasta que el trabajo esté hecho!}
{244}{merk49}{Eso me decepciona. Normalmente elimino las cosas que me decepcionan. Sin embargo, en tu caso puedo ser generoso. Simplemente vete y no vuelvas, y lo olvidaré todo.}
{245}{merk50}{Entonces, ¿el pequeño negocio referente al doctor Henry está hecho?}
{246}{}{Pues sí, tengo los papeles que quieres.}
{247}{}{No.}
{248}{merk51}{Los días como éste me hacen tan feliz... Bien, terminemos nuestro negocio.}
{249}{merk52}{He llegado a mi conocimiento que el ingenioso doctor expiró durante tu visita. Eso fue en contra de mis órdenes. Para recuperar las pérdidas futuras creo que será necesario que reciba un reembolso.}
{250}{}{Mira, sólo te daré 500 pavos y olvidaremos todo el asunto.}
{251}{}{Jódete.}
{252}{merk53}{Bien, que tengas éxito en tus aventuras. No encuentro razones para que volvamos a hablar.}
{253}{}{Por mí está bien.}
{254}{merk54}{Tenemos un trato, pero sólo porque me gustas. Te sugiero que no vuelvas pronto.}
{255}{merk55}{Creo que te voy a matar, recuperaré mi dinero, y obtendré una recompensa. Después de todo, eso es todo lo que se espera de un buen ciudadano.}
{256}{merk83}{¡Otra vez tú! ¡MUERE!}
{257}{merk84}{Pensé que te había dicho que no me molestases más.}
{258}{}{ y soy una hijoputa peligrosa. Ve a preguntarle a otro.}
{259}{}{ tipo.}
{260}{}{ chica.}
{261}{merk56}{Un Hubologista es un fanático religioso chiflado. Se los puede encontrar en la iglesia de la ciudad.}
{262}{}{Estoy en camino.}
{263}{merk57}{¡No hablaré contigo hasta que el trabajo esté hecho! Necesito esos papeles del local del doctor Henry, pronto.}
{264}{}{No, pero necesito algo de información.}
{265}{merk85}{Sé que la muerte de Lenny no fue ningún accidente, zorra.}
{266}{}{Eh, ese mapa era una falsificación.}
{267}{}{Bien, ¿y qué hay sobre el dinero que te di?}
{268}{merk58}{Como ya he dicho, no tuvo éxito.}
{269}{}{Bien, ¿y qué tal si te comes esta bala por las molestias?}
{270}{}{Hmmphf.}
{271}{}{Has "encargado" la Hubologista para Merk.}
{272}{}{Has recuperado los papeles del doctor Henry.}
{300}{merk86}{¿Dónde diablos crees que vas?! Inténtalo otra vez y te voy a patear el culo.}
{301}{merk87}{Yo lo advertí!}
