{100}{}{Ves a la asistente técnico sanitario Phyllis.}
{101}{}{Ves a una joven delgada. Huele débilmente a antiséptico.}
{102}{}{Ves a la ATS Phyllis.}
{103}{}{Ves a una joven delgada. Huele débilmente a antiséptico.}
{104}{phl45}{Arriesgaste tu propia vida para salvarnos a TODOS. Eres la persona más valiente que he conocido jamás.}
{105}{phl46}{¡Una intrusa! ¡Aaaaah! ¡Guardias!}
{106}{phl47}{¡Un mutante! ¡Aaaaah! ¡Guardias!}
{107}{phl48}{¡Un necrófago! ¡Aaaaah! ¡Guardias!}
{108}{phl49}{Necesito imprimir los mapas de Gregory...}
{109}{phl50}{Veamos. Tenemos tres vacunaciones de siervos programadas para las 1400 horas...}
{110}{phl51}{Todo ese ruido me está volviendo loca...}
{111}{phl52}{Juraría que esas bases de datos médicas están hablando entre ellas...}
{112}{phl53}{Veamos... tres hipodérmicas, antiséptico, tres ampollas de Rad-X...}
{113}{phl54}{Mejor que prepare al doctor Troy para ese seminario de mañana...}
{114}{phl55}{Sí, me tienen trabajando hasta tarde OTRA VEZ. Sobre todo haciendo listas.}
{115}{phl56}{Es posible que quieras volver por la mañana.}
{116}{phl57}{Creo que te pondré en la lista para mañana temprano, si no se trata de una emergencia.}
{117}{phl58}{No puedo esperar a volver a casa. Hacer todas estas listas me agota.}
{118}{phl59}{Lo mejor sería que volvieras por la mañana. He de compilar estas listas.}
{119}{phl60}{Pobre doctor Troy. ¡Él no HIZO nada!}
{120}{phl61}{¿Por qué exiliaron al doctor Troy?}
{121}{phl62}{Espero que el doctor Troy esté bien en el mundo exterior...}
{122}{phl63}{Hmmph. Estoy demasiado ocupada para hablar contigo ahora mismo. Si necesitas algo, habla con el doctor Troy.}
{123}{phl1}{¡Oh! Hola. No te he visto nunca por aquí... ¿eres una nueva Ciudadana?}
{124}{phl2}{¡Oh! Hola de nuevo.}
{125}{}{¿Ci-Ciu-dana?}
{126}{}{¿N-nueva?}
{127}{}{Tengo pupita... *llorando*... pupita DUELE}
{128}{}{En realidad, soy la nueva capitán de la Guardia.}
{129}{}{Sí, he conseguido recientemente mi Ciudadanía.}
{130}{}{Eh, sí, he conseguido recientemente mi Ciudadanía.}
{131}{}{Perdona, pensaba que eras otra persona. Buenos días.}
{132}{phl3}{Dios, estás herida, ¿verdad? Lo siento, debería haber prestado más atención. Ve a ver al doctor Troy. Él se ocupará de ti.}
{133}{}{¿De... cuerdo? Sí, sí sí.}
{134}{}{¿Podría hacerte algunas preguntas antes?}
{135}{}{Gracias. Iré a verlo ahora.}
{136}{phl4}{¡Oh! Debes ser una de los siervos asignados aquí hoy. Deberías... uh, hmmm. TÚ - VE CON - MARTIN.}
{137}{phl5}{Uh... hmmm. Escúchame otra vez, atentamente ahora: VE CON - MARTIN.}
{138}{}{BECON MARTIN.}
{139}{}{Tengo pupita... *llorando*... pupita DUELE}
{140}{}{Dejas de balbucear}
{141}{phl6}{SÍ, MARTIN. VE - NIVEL - INFERIOR.}
{142}{}{SI, MAR-TIN. VE AL NIVEL DE ABAJO.}
{143}{}{Tengo pupita... *llorando*... pupita DUELE}
{144}{}{Dejas de balbucear}
{145}{phl7}{VE - AL - NIVEL - DE ABAJO. NIVEL - TRES. AHORA.}
{146}{}{YO VOY ABAJO NIVEL TRES AHORA}
{147}{}{Tengo pupita... *llorando*... pupita DUELE}
{148}{}{Dejas de balbucear}
{149}{phl64}{Quizá nuestros siervos tienen alguna clase de síndrome de déficit de inteligencia...}
{150}{}{¡Oh! De acuerdo, bienvenida a Ciudad Refugio, capitán.}
{151}{}{Vale, bienvenida a Ciudad Refugio, apreciada Ciudadana.}
{152}{}{No vemos muchas caras nuevas por aquí. Soy Phyllis. ¿Cual es tu nombre?}
{153}{}{Mi nombre es }
{154}{}{Soy }
{155}{}{Si quisiera darme mi nombre, te lo habría dicho, "Sí-filis"... o como diablos te llames.}
{156}{}{Lo siento, no tengo tiempo para hablar contigo ahora mismo.}
{157}{phl8}{Por qué, de todos los...! NUNCA me he encontrado con nadie con tan poca clase como tú. Te sugiero que te vayas. Ahora.}
{158}{}{Te sugiero que vigiles tu tono, o va a haber problemas.}
{159}{}{Como sea. De todas formas ya he terminado de hablar contigo.}
{160}{phl9}{¡Guardias! ¡Doctor Troy! ¡Ayuda!}
{161}{}{Conque así es como va a ser, ¿eh? De...}
{162}{phl10}{Soy la asistente técnico sanitario. Trabajo para el doctor Troy.}
{163}{}{¿Qué opinas del doctor Troy?}
{164}{}{¿Puedo hacerte unas preguntas?}
{165}{}{Fantástico. Podría necesitar atención médica.}
{166}{}{Lo siento, no tengo tiempo para hablar contigo ahora mismo.}
{167}{phl11}{Bienvenida de nuevo. ¿Hay algo en lo que pueda ayudarte?}
{168}{phl12}{Por supuesto. ¿Qué te gustaría saber?}
{169}{}{¿Qué opinas del doctor Troy?}
{170}{}{¿Puedes decirme dónde está la computadora central?}
{171}{}{Necesito que me curen.}
{172}{}{¿Qué haces aquí?}
{173}{}{¿Puedes hablarme de Ciudad Refugio?}
{174}{}{No importa, en realidad. Gracias de todos modos.}
{175}{phl13}{Oh, el doctor puede ser bastante estricto a veces, pero en el fondo es un buen hombre. Ciudad Refugio tiene suerte de contar con él.}
{176}{}{Bueno, me pidió que metiese de contrabando ciertas drogas en la ciudad.}
{177}{}{¿Puedo preguntarte otra cosa?}
{178}{}{Gracias por tu tiempo. Adiós.}
{179}{}{}
{180}{}{}
{181}{phl14}{¿Estás segura? Eso no parece propio del doctor Troy. Aunque... ha estado trabajando duro últimamente... no, no, es imposible. Debes estar equivocada.}
{182}{}{No lo creo. Fue muy claro con lo que pedía.}
{183}{}{Hmmmm. ¿Puedo hacerte otra pregunta?}
{184}{}{No importa, entonces.}
{185}{phl15}{Yo sería MUY cuidadosa con lo que digo acerca del doctor Troy en Ciudad Refugio. Se trata de un respetado miembro de nuestra comunidad.}
{186}{}{De acuerdo entonces. ¿Puedo hacerte otra pregunta?}
{187}{}{Gracias por el aviso. Quizá debería hablar con otra persona.}
{188}{phl16}{Está en el tercer nivel, si lo recuerdo bien. No he bajado allí desde hace años.}
{189}{}{¿Por qué no?}
{190}{}{¿Puedo preguntarte otra cosa?}
{191}{}{Gracias por las indicaciones. Adiós.}
{192}{phl17}{Oh, no lo sé. No hay muchas razones para bajar al Refugio. Hoy en día se usa fundamentalmente como espacio de almacenamiento. El único que baja ahí es Martin, y... bien, entre tú y yo, no es un gran conversador.}
{193}{}{Uhh.... ¿Por qué le hicieron conversador si no es bueno en su trabajo?}
{194}{}{¿Puedo preguntarte otra cosa?}
{195}{}{Ya veo. Gracias por la información.}
{196}{phl18}{Eh... quizá DEBERÍAS hablar con él. Puede que los dos tengáis más en común de lo que pensé al principio.}
{197}{}{¿Puedo hacerte antes otra pregunta?}
{198}{}{De acuerdo entonces. Iré a hablar con él.}
{199}{phl19}{¿Ciudad Refugio? Bueno, en realidad no hay mucho que decir. Quiero decir, he sido una Ciudadana toda mi vida... pero no hay mucho que hacer en Ciudad Refugio. En absoluto.}
{200}{}{Es una vergüenza que una bella joven como tú no encuentre NADA que hacer en Ciudad Refugio.}
{201}{}{¿Nada en absoluto? Anda ya.}
{202}{}{¿Puedo hacerte otra pregunta...}
{203}{}{Oh, bueno. Sólo quería preguntar.}
{204}{phl20}{Mira, sé que eres una nueva Ciudadana y todo eso, y no quiero amargarte tu Ciudadanía, pero esta ciudad puede ser MUY aburrida a veces.}
{205}{}{¿Aburrida? ¿Cómo es eso?}
{206}{}{Qué pena. Tenía más preguntas...}
{207}{}{Oh, bueno. Lamento oír eso.}
{208}{phl21}{Quiero decir, ¿has notado cómo se parece todo? ¿Y lo VIEJO que es todo? La mayoría de seminarios y actividades extra-curriculares se dirigen a octogenarios. Apenas tengo veinticinco años, y esta ciudad me hace sentir como si tuviera cincuenta.}
{209}{}{Eh... ¿octo-genarios? ¿Te refieres a guardias?}
{210}{}{Hablando de vejez, he notado que no hay ningún niño en la ciudad.}
{211}{}{He notado la similitud entre Ciudadanos.}
{212}{}{Oh, bueno. Sólo quería preguntar.}
{213}{phl22}{Eh, no… "octogenario" es un adjetivo que se refiere a una persona de ochenta años de edad. }
{214}{}{Ah, de acuerdo. ¿Puedo hacerte otra pregunta?}
{215}{}{De acuerdo, entonces. Tal vez hablemos más tarde.}
{216}{phl23}{Bien... es verdad. En realidad, no hay. Todavía. No sé si nadie te ha contado que Ciudad Refugio es una comunidad planificada. No tenemos otro ciclo de embarazo hasta dentro de varios años.}
{217}{}{Eh... ¿un ciclo de embarazo?}
{218}{}{¿Puedo preguntarte otra cosa?}
{219}{}{Ya veo. Bien, gracias por la información.}
{220}{phl24}{Sí. Sólo se permiten los embarazos durante ciertos años establecidos por el Consejo.}
{221}{}{¿Y si te quedas embarazada de todos modos?}
{222}{}{Oh. Tenía algunas preguntas más...}
{223}{}{Ya veo. Bien, gracias por la información.}
{224}{phl25}{¿Cómo podría suceder?}
{225}{}{Eh, la última vez que pregunté, el sexo PUEDE producir un embarazo.}
{226}{}{Olvida lo que he preguntado. Mira, tenía algunas preguntas más...}
{227}{}{No importa. Mejor que me vaya.}
{228}{phl26}{Oh, ¿te refieres a relaciones sexuales? Las relaciones se permiten fuera del ciclo de embarazo.}
{229}{}{¿Eso no hace que la gente se quede embarazada?}
{230}{}{Oh. Tenía algunas preguntas más...}
{231}{}{Oh, bueno. Sólo quería preguntar.}
{232}{phl27}{Oh, no, no... verás, nuestros embarazos no son el resultado de una relación sexual.}
{233}{}{Voy a lamentar preguntarlo. Pero lo haré de todas formas.}
{234}{}{No quiero saber nada más. Aunque tenía otras preguntas...}
{235}{}{Creo que ya he oído bastante.}
{236}{phl28}{Los Ciudadanos varones "donan" al Auto-Doc en el Refugio y la computadora elije las donaciones más favorables. Después, la Ciudadana hembra apropiada es inseminada por el Auto-Doc.}
{237}{}{¿Yo puedo donar?}
{238}{}{¿Las personas no se quedan embarazadas debido a las relaciones? ¿Qué pasa con los embarazos accidentales?}
{239}{}{¿Sabes? Me encantaría preguntarte cualquier otra cosa en este momento.}
{240}{}{¿Podrías perdonarme? Voy a ver si puedo revocar mi Ciudadanía.}
{241}{}{Creo que voy a ir a alguna parte a enfermar gravemente. Adiós.}
{242}{phl29}{Naturalmente. Agradeceríamos tu contribución. Ciudad Refugio podría usar material genético fresco puro.}
{243}{}{De acuerdo entonces...}
{244}{}{¿Y podría disponer de una revista o algo así?}
{245}{phl30}{Tu contribución es impresionante... te hace parecer bastante dotado. ¿Cómo te sientes?}
{246}{phl31}{¡Excelente! Gracias.}
{247}{phl32}{Hmmm. Quizá tu contribución no era tan valiosa como había pensado. Aunque gracias de todos modos.}
{248}{}{Puedo decir honestamente que nunca había renegado del primitivo encanto de Arroyo más que en este momento.}
{249}{}{Nunca he sentido la necesidad de que me abracen más que en este momento.}
{250}{}{No, gracias a TI.}
{251}{phl33}{Bueno, en realidad... verás, esto es algo en lo que he estado pensado últimamente, ya que los Ciudadanos no parecen tener embarazos accidentales. Los únicos embarazos exitosos han sido facilitados por el Auto-Doc.}
{252}{}{Ya sabes, la radiación de fondo podría tener como consecuencia la esterilidad o, peor aún, daños cromosómicos. Puede que valga la pena comprobarlo.}
{253}{}{Tal vez es sólo debido a que no tienen mucho sexo de verdad por aquí.}
{254}{}{Oh, bueno. Sólo quería preguntar.}
{255}{phl34}{¿Sabes? Estaba pensando en lo mismo. Quizá debería mencionárselo al doctor Troy. Ha estado demasiado ocupado últimamente como para comprobarlo, pero el próximo ciclo de embarazo se acerca, así que...}
{256}{}{¿Puedo hacerte alguna otra pregunta?}
{257}{}{Mencionárselo al doctor Troy podría ser una buena idea. Buena suerte.}
{258}{phl35}{Es como si todos fueran... clones. Todos visten igual, actúan igual, y lo peor es que todos parecen felices así. Yo... bueno, a veces me preocupa terminar igual que ellos. Probablemente suena tonto, ¿verdad?}
{259}{}{No, en absoluto. La presión para encajar debe ser un poco dura aquí, especialmente considerando una comunidad aislada como es Ciudad Refugio.}
{260}{}{Oh, bueno. Sólo quería preguntar.}
{261}{phl36}{Sí, puede ser algo abrumador a veces. Pero aquí estoy, haciendo que disminuya tu opinión sobre Ciudad Refugio. No me malinterpretes. Es un lugar genial para vivir.}
{262}{}{Es sólo una sugerencia, pero quizá quieras viajar un poco fuera de Ciudad Refugio. Incluso hablar con algunos de los comerciantes del Patio. Podrían ampliar un poco tus horizontes.}
{263}{}{Tiene sus ventajas, sin duda. ¿Puedo hacerte alguna pregunta más?}
{264}{}{Me alegra que seas feliz aquí. Tal vez hablemos de nuevo.}
{265}{phl37}{Bueno, me he visto tentada para cruzar las puertas, pero los demás Ciudadanos me han prevenido contra ello...}
{266}{}{Esa no es más que otra razón para hacerlo. ¿Quieres hacer lo que los DEMÁS Ciudadanos hacen? Ninguno de ellos se sale de su camino.}
{267}{}{Bien, ahí fuera puede ser peligroso. Oye, ¿puedo hacerte otra pregunta?}
{268}{}{Tienen razón. Probablemente no es una buena idea. Será mejor que me vaya.}
{269}{phl38}{¿Sabes?, tienes razón. Tal vez cruce las puertas cuando tenga la oportunidad. Me gustaría saber más del mundo exterior.}
{270}{}{Fantástico. Oye, ¿puedo hacerte otra pregunta?}
{271}{}{Será bueno para ti. Ten cuidado.}
{272}{phl39}{¿Perdóname?}
{273}{}{No he podido dejar de notar que eres una joven atractiva que podría estar dispuesta a escaparse de vez en cuando. ¿Qué tal si tú y yo vamos a cenar?}
{274}{}{No importa. ¿Puedo hacerte otra pregunta?}
{275}{}{Oh, bueno. Sólo quería preguntar.}
{276}{phl40}{Oh. Yo... ya sabe, me encantaría, pero no puedo.}
{277}{phl41}{Oh. Bueno, Yo... me encantaría.}
{278}{}{Anímate. Soy nuevo. Tendré problemas si ando por ahí yo solo.}
{279}{}{De acuerdo. ¿Entonces puede hacerte algunas preguntas?}
{280}{}{Oh, bueno. Sólo quería preguntar.}
{281}{}{¡Genial! Vamos.}
{282}{phl65}{Gracias por una tarde maravillosa.}
{283}{phl66}{Eh... desde luego. Quizá salgamos en algún otro momento. Te... eh, llamaré. Adiós.}
{284}{phl42}{Lo siento, pero no.}
{285}{}{De acuerdo. ¿Puedo entonces hacerte algunas preguntas?}
{286}{}{Oh, bueno. Sólo quería preguntar.}
{287}{}{En fin, es bueno saber que los prejuicios sobre la homosexualidad están bien vivos en Ciudad Refugio. Adiós.}
{288}{}{. ¿Qué estás haciendo por aquí?}
{289}{}{. ¿Te importa si te hago algunas preguntas?}
{290}{}{Oh, bueno, pensé que no había niños porque esta podría ser la versión europea de Fallout 2. Adiós.}
{291}{}{Has hecho una donación a Ciudad Refugio e introducido material genético favorable en su comunidad.}
{292}{}{Has hecho una donación a Ciudad Refugio e introducido material genético puro en su comunidad.}
{293}{}{Has hecho una donación a Ciudad Refugio... para lo que sea que sirva.}
{294}{}{Has convencido a Phyllis para que le hable al doctor Troy de la esterilidad potencial de Ciudad Refugio.}
{295}{}{Has convencido a Phyllis para que vea el mundo exterior.}
{296}{}{Descubres rápidamente que Phyllis es bastante aburrida y egoísta. Decides no volver a tener nunca una cita con alguien como ella.}
{297}{}{Hablando de octo-genéric- eh, octo-genos, eh, ancianos, he notado que no hay niños en Ciudad Refugio.}
