{100}{}{Vedi Lara.}
{150}{}{E' la leader di questa banda.}
{200}{}{Mi chiamo Lara; sono il capo di questa banda. Sara' meglio che tu non sia qui per causare guai o preparati a sperimentare un nuovo modo di intendere il dolore.}
{201}{larad2}{Ciao. Ti serve qualcosa?}
{202}{}{Hai del lavoro?}
{203}{}{Stavo solo dando un'occhiata in giro.}
{204}{}{Sto cercando un mercante di nome Vic.}
{205}{}{Aruh.}
{206}{}{Rara.}
{220}{larad3}{Non ci sono dottori qui in citta' e io non posso aiutarti.}
{221}{larad4}{Scusa, continuo a non capire.}
{222}{}{Ack.}
{230}{larad5}{Questo nome non mi dice molto, ma comunque io non sto molto attenta a chi entra o esce dalla citta'. Prova a chiedere a Becky. Prima o poi tutti passano dal suo locale. Forse lei lo sa.}
{231}{}{Hai del lavoro?}
{232}{}{Grazie. Ciao.}
{240}{larad6}{Se non sei venuto al Den per un motivo specifico, probabilmente faresti meglio ad andartene. Questo non e' un posto molto sicuro.}
{241}{larad7}{Oh, okay.}
{242}{}{Hai del lavoro?}
{243}{}{So badare a me stesso.}
{244}{}{Okay, grazie.}
{250}{larad8}{Non ne dubito. Altrimenti non ce l'avresti mai fatta ad arrivare vivo fino a qui.}
{251}{larad9}{Uh, si', lo so. Me l'hai gia' detto prima.}
{252}{}{Hai del lavoro?}
{253}{}{Okay, grazie.}
{260}{larad10}{Beh, dipende da quello che sei in grado di fare. C'e' qualcosa che mi incuriosisce. Se riesci a scoprire quello che voglio, ti paghero'.}
{261}{larad11}{Come ti ho detto, sto cercando informazioni su un certo oggetto... o luogo. Ti paghero', naturalmente.}
{262}{}{D'accordo. Di cosa si tratta?}
{263}{}{Magari piu' tardi.}
{270}{larad12}{Fammi sapere se cambi idea.}
{271}{}{Okay.}
{280}{}{Beh, c'e' una chiesa ad est di qui. Metzger ha messo delle persone a guardia di quello che c'e' all'interno. Scopri di cosa si tratta e ti daro' 200$.}
{281}{}{E' facile. Lo so gia'.}
{282}{}{Bene.}
{283}{}{Vedro' di fare il possibile.}
{290}{larad14}{Grazie. Non farti coinvolgere in uno scontro... per adesso. Ho un piano.}
{291}{}{Nessun problema.}
{292}{}{Torno subito.}
{300}{larad15}{Di cosa si tratta?}
{301}{}{Composti chimici grezzi contenuti in grandi casse.}
{302}{}{Grossi contenitori che contengono prodotti chimici di qualche tipo.}
{303}{}{Vorrei controllare un'altra volta.}
{310}{larad16}{Il tutto ha un senso. Grazie. Ecco i tuoi soldi.}
{311}{}{Perche'?}
{312}{}{Nessun problema. Addio.}
{320}{larad17}{Ho visto alcune carovane provenienti da Vault City scaricare quelle casse, che vengono poi prelevate da altre carovane arrivate qui da New Reno.}
{321}{}{E allora? Perche' dici che tutto ha un senso?}
{322}{}{Oh.}
{340}{larad18}{New Reno e' la capitale della droga. Da qualche parte dovranno pur prendere i materiali grezzi per produrla, no? E sembra proprio che ne prendano una parte, o addirittura tutti, da Vault City.}
{341}{}{Dove si trova New Reno?}
{342}{}{Okay, grazie.}
{350}{larad19}{Non lo so con esattezza. Da qualche parte a sud, credo. Non ci sono mai stata, ho solo visto le loro carovane fermarsi qui una volta, parecchio tempo fa.}
{351}{}{Ah, okay. Grazie.}
{360}{larad20}{Che ne diresti di qualche soldo veloce-veloce? 50$. Soldi facili.}
{361}{}{Bene.}
{362}{}{Dimmi tutto.}
{370}{larad21}{Voglio che tu vada da Metzger a chiedergli se ci puo' dare il suo nulla-osta per sedare una vecchia questione tra me e Tyler. Lui capira' a cosa mi riferisco.}
{371}{}{Perche' vuoi che vada io a chiederglielo?}
{372}{}{Se capitera' l'occasione.}
{373}{}{Okay.}
{380}{larad22}{Perche' non voglio che Tyler veda qualcuno della mia banda entrare o uscire dal palazzo di Metzger. Non voglio rovinare la sorpresa.}
{381}{larad23}{Non lo capisci? Se Tyler dovesse vedermi parlare con Metzger, potrebbe sospettare qualcosa.}
{382}{}{Vedremo.}
{383}{}{Okay.}
{390}{larad24}{Allora, hai scoperto cosa c'e' la' dentro?}
{391}{}{Composti chimici grezzi contenuti in grandi casse.}
{392}{}{Grossi contenitori che contengono prodotti chimici di qualche tipo.}
{393}{}{Non ancora.}
{400}{larad25}{Hai gia' parlato con Metzger? Che cosa dice?}
{401}{}{Dice di si'. Se vincete, potete prendere il loro lavoro, come sempre.}
{402}{}{Na.}
{410}{larad26}{Ottimo. Speravo proprio che dicesse cosi'. Ho sentito che ultimamente si era lamentato di loro. Ecco i tuoi soldi.}
{411}{}{Adesso immagino ci sia qualcos'altro da fare, giusto?}
{412}{}{Grazie. Ciao.}
{420}{larad27}{Ho un altro lavoro per te. Non so come tu possa fare, ma dal momento che sei riuscito ad entrare, forse significa che si fidano di te.}
{421}{}{In realta' sono entrato di nascosto.}
{422}{}{Cosa?}
{430}{larad28}{Sono sicura che riuscirai ad inventarti qualcosa.}
{431}{}{Okay, di cosa si tratta?}
{440}{}{Non possiamo batterli, data la loro forza attuale. Loro hanno piu' soldi e ci sono leggermente superiori di numero. Se tu riuscissi a trovare una qualche loro debolezza che ci consenta di equilibrare le forze, o se tu scoprissi qualcosa da sfruttare a nostro favore...}
{441}{}{Eh? Trovare una debolezza? E come credi che possa farcela?}
{442}{}{Quanto?}
{443}{}{Consideralo fatto.}
{450}{larad30}{Ti daremo 150$. Non c'e' modo per noi di avvicinarci abbastanza a loro da scoprirla.}
{451}{}{Vedro' di fare il possibile.}
{452}{}{Okay.}
{460}{larad31}{Non lo so. E' per questo che ti sto chiedendo aiuto.}
{461}{}{Ci provero'.}
{462}{}{Tutto questo non ha senso.}
{470}{larad32}{Hai scoperto qualcosa?}
{471}{}{Si'. Stanotte faranno una festa.}
{472}{}{Non ancora. Te lo faro' sapere.}
{473}{}{Gra.}
{474}{}{Na.}
{480}{}{Eccellente! Lasceranno sicuramente un corpo di guardia ridotto all'osso. Questo sara' un gran bel vantaggio per noi. Faremo fuori quelli alla festa dopo aver assaltato la chiesa.}
{481}{}{E i miei soldi?}
{490}{}{Non credo che te li daro' subito. Se vuoi vedere i tuoi soldi, dovrai venire con noi. Non ti sto chiedendo di combattere, ma voglio essere sicura che non sia una trappola. In totale ti daremo 300$.}
{491}{larad35}{Sei pronto?}
{492}{}{Okay, andiamo.}
{493}{}{Dammi un attimo per prepararmi.}
{494}{}{Puoi scordartelo. Tieniti pure i tuoi soldi!}
{500}{larad36}{Okay, ma noi ci muoveremo presto, quindi non impiegarci troppo o perderemo la nostra occasione.}
{501}{}{Okay.}
{510}{larad37}{Non devi combattere. Soldi facili.}
{511}{larad38}{Beh, hai cambiato idea?}
{512}{}{Andiamo. Sono pronto.}
{513}{}{Okay, torno subito.}
{514}{}{No.}
{515}{}{Uk}
{520}{larad50}{Per colpa tua abbiamo perso la nostra occasione.}
{521}{larad51}{Codardo!}
{522}{larad52}{Non vedrai un quattrino.}
{523}{larad53}{Probabilmente era una trappola.}
{524}{larad54}{Mi spiace, ma non sei affidabile.}
{525}{larad55}{Non posso fidarmi di te.}
{530}{larad56}{Ce l'abbiamo fatta!}
{531}{larad57}{Grazie dell'aiuto.}
{532}{larad58}{Grazie mille!}
{533}{larad59}{Finalmente ho ripagato Tyler per quello che ha fatto a mio fratello.}
{534}{larad60}{Grazie di nuovo.}
{540}{larad61}{Adesso che Metzger e' morto, non so cosa succedera'.}
{541}{larad62}{Forse dovremmo sciogliere la banda.}
{542}{larad63}{Hai sentito che Metzger e' morto? Adesso non so cosa fare.}
{543}{larad64}{Adesso cosa accadra' al Den? Forse le cose miglioreranno.}
{544}{larad65}{La morte di Metzger forse migliorera' le cose.}
{550}{larad66}{Bastardo!}
{551}{larad67}{Puttana!}
{560}{larad39}{Grazie. Ecco i tuoi soldi e un bonus di 100$.}
{570}{larad40}{Hai ucciso Tyler e la sua banda? E adesso come faremo a dimostrare la nostra forza a Metzger? Non ci assumera' mai. Questa era la nostra unica possibilita'.}
{571}{larad41}{Non abbiamo piu' un lavoro. Qualcuno ha ucciso le guardie di Metzger e adesso lui non ci rivolge la parola. Crede che siamo stati noi. Davvero magnifico...}
{572}{}{Scusa.}
{573}{}{Che peccato.}
{574}{}{Sono stato io, e voi siete i prossimi.}
{575}{}{Oh. Okay, ciao.}
{576}{}{Uhr?}
{577}{}{Ug.}
{590}{larad42}{Ti avevo detto che dovevamo andare insieme. Dal momento che non c'era nessuno a sorvegliare la chiesa, qualcuno l'ha ripulita e adesso Metzger e' incazzato nero.}
{591}{larad43}{Ti avevo detto di trovare un punto debole, non di ucciderli! Dal momento che non c'era nessuno a sorvegliare la chiesa, qualcuno l'ha ripulita e adesso Metzger e' incazzato nero.}
{592}{larad44}{Dannazione! Ti avevo detto di andare a chiedere il permesso a Metzger, non di ucciderli! Dal momento che non c'era nessuno a sorvegliare la chiesa, qualcuno l'ha ripulita e adesso Metzger e' incazzato nero.}
{593}{larad45}{Dannazione! Ti avevo detto di non attaccarli! Dal momento che non c'era nessuno a sorvegliare la chiesa, qualcuno l'ha ripulita e adesso Metzger e' incazzato nero.}
{594}{}{Oh, beh, devo andare.}
{595}{}{Un vero peccato.}
{596}{}{E tu sei la prossima, troia.}
{597}{}{Hmph!}
{598}{}{Tu essere prossima!}
{610}{larad68}{Sai davvero come mandare a puttane le cose, vero?}
{611}{larad69}{Non abbiamo piu' bisogno del tuo aiuto.}
{612}{larad70}{Va' a disturbare qualcun altro.}
{613}{larad71}{Sara' meglio per te che Metzger non dia la colpa a noi.}
{614}{larad72}{Mi dispiace. Non posso aiutarti.}
{615}{larad73}{Non posso parlare. Sto cercando di capire cosa fare adesso.}
{616}{larad74}{Spero che Metzger non pensi che noi c'entriamo qualcosa.}
{617}{larad75}{E adesso che cosa faremo?}
{618}{larad76}{Faremo meglio ad andarcene in fretta in caso Metzger pensasse che siamo stati noi ad uccidere le sue guardie.}
{619}{larad77}{Sei mai stato a New Reno? Forse ci dirigeremo la' - o a nord.}
{650}{larad78}{Okay! Andiamo! Seguitemi!}
{700}{}{Alright, we took care of the skeleton crew here at the church, but there still is Tyler and his cronies over in the Residential area.
 They should be pretty drunk by now and we can easily catch them off guard. You ready to finish this?}
{701}{}{Let me heal first. I'll tell you when I am ready.}
{702}{}{Andiamo.}
{710}{larad47}{You ready to take Tyler and his crew out?}
{720}{larad48}{Well, don't stray too far. We need to finish this tonight or we'll do it without you.}
{721}{}{I'll be back shortly.}
{722}{}{Andiamo.}
{730}{larad49}{We did it. I can't believe it! We're heading back to the church to take charge. Meet us back there for your reward.}
