{100}{}{Morlist látod, a nagynénédet, aki sohasem szeretett téged.}
{101}{mor20}{Miért zavarsz, unokaöcsém? Nem látod, hogy most nem érek rá?}
{102}{}{Hmm, rendben. Bocsánat.}
{103}{mor1}{Mi az? Tudod, hogy nagyon sok dolgom van!}
{104}{}{Hát, Mynoc azt mondta...}
{105}{mor2}{Mit mondott Mynoc? Ki vele, kölyök!}
{106}{}{Azt, hogy, hát, talán van néhány kovaköved.}
{107}{mor3}{Van. Talán akarsz egyet?}
{108}{}{Hát igen...}
{109}{mor4}{Na, figyelj rám szépen... Három zsák gyógyító porra van szükségem. Rossz idõk jönnek, és fel akarok készülni. Hozdd el, amit akarok, és megkaphatod a kovakövet. Gyerünk, lódulj!}
{110}{}{Igen, nénikém!}
{111}{mor5}{Ne fecséreld az idõmet! Megvannak a gyógyító porok?}
{112}{}{Igen, itt vannak.}
{113}{}{Még nincsenek.}
{114}{mor6}{Itt a kovakõ. Most tûnj innen! Nincs idõm csevegni.}
{115}{}{Köszönöm, Morlis nagynéni.}
{116}{mor7}{Újfent csak fecsérled az idõmet, hitvány unokaöcs! Hogy lehettél pont te a Kiválasztott?}
{117}{}{Igenis, Morlis nagynéni.}
{118}{}{Öö, Morlis nagynéni, itt van mind a három.}
{150}{}{Morlis nagynéni, egy nagyon veszélyes küldetésre indulok a falu megmentéséért. A túlélési esélyeim sokkal jobbak lennének, ha megtarthatnám a gyógyító porokat, te pedig ideadnád a kovakövet. Egyetértesz?}
{151}{mor8}{Mit csinálsz, fiam? Egy Kiválasztott nem viselkedhet így. Takarodj a szemem elõl!}
{152}{mor9}{Ha ez a kovakõ olyan fontos, hogy bemocskolod érte a Kiválasztott nevet, hát tessék. Most pedig tûnés a szemem elõl!}
{153}{}{Igenis, Morlis nagynéni.}
{154}{mor10}{Nos... Jól van. Itt a kovakõ. Biztonságos utat kívánok, gyermekem!}
{155}{mor11}{Nem. Ne fecséreld az idõm, és szedd a sátorfádat!}
{156}{}{Igenis, Morlis nagynéni.}
{200}{mor12}{Visszatértél hát... Megtaláltad a szent 13-ast?}
{201}{}{Nem, Morlis nagynéni, én...}
{202}{mor13}{Akkor tûnj el innen, és folytasd a keresést! Tõled függ az életünk!}
{203}{}{Igenis, Morlis nagynéni.}
{204}{mor14}{Szóval újra itt vagy... Még mindig sikertelen a küldetésed?}
{205}{}{Igen, Morlis nagynéni, de...}
{206}{mor15}{Akkor tûnj innen, és ne gyere vissza, amíg nem jársz sikerrel! Miért fecséreled az idõmet azzal, hogy visszajössz ide, amikor a keresésre kéne fordítanod!?}
{207}{}{Igenis, Morlis nagynéni.}
{208}{mor16}{A tény, hogy itt állsz, azt bizonyítja, hogy megcsináltad a küldetést. Ugye nem fecsérelnéd arra az idõt, hogy üres kézzel térj vissza?}
{209}{}{Igen, Morlis nagynéni. Vagyis nem, Morlis nagynéni. Öö... Most mennem kell, Morlis nagynéni.}
{210}{mor17}{Tehát ismét itt állsz elõttem. Megint üres kézzel jöttél?}
{211}{}{Igenis, Morlis nagynéni.}
{212}{}{Figyelj, }
{213}{}{. az emberek haldokolnak, a marhák pusztulnak, a termés pedig elenyészik. Mindenki vagy éhes, vagy beteg, vagy mindkettõ. Az idõ sürget. Ha rövidesen nem találod meg az ÉLET-et, eljön a végzetünk. Értesz engem?}
{214}{}{Igenis, Morlis nagynéni.}
{215}{mor19}{Akkor indulj, és keresd meg az ÉLET-et! Tõled függ az életünk!}
{216}{}{Igenis, Morlis nagynéni.}
{300}{mor22}{Úgy tûnik valamerre elraktam a kovakövemet. De legalább megvan a porom. Most tûnj innen! Nincs idõm csevegni.}
{301}{mor21}{Miért zavarsz, unokahúgom? Nem látod, hogy most nem érek rá?}
{302}{mor23}{Sehol sem találom a kovakövemet. Biztos vagyok benne, hogy elvetted mikor nem figyeltem. Egyszer már tetten értelek régebben. Most tûnj el! Nincs idõm pletykálni.}
{303}{mor24}{Nos... Sajnálom, úgy tûnik elraktam valahová a kovakövemet. Biztonságos utat kívánok, gyermekem!}
{304}{mor25}{Már odaadtam neked a kovakövemet idióta. Ne fecséreld az idõm, és szedd a sátorfádat!}
{305}{mor26}{Már odaadtam neked a kovakövemet idióta. De legalább megkaptam a poromat. Most tûnj innen! Nincs idõm csevegni.}
