{100}{}{Szerelõ.}
{101}{}{Raul, a szerelõ.}
{102}{}{Egy koszos katonai gyakorlót viselõ fickó. Az olajfoltokból ítélve inkább szerelõ lehet, mint katona.}
{103}{}{Bocsi, de nincs idõm veled dumálni. Ennek a madárkának hamarosan repüni kell, érted?}
{104}{}{Doki akarni javít K-9. Mongya lenni nálad alkatrész.}
{105}{}{Öhm... oké.}
{106}{}{Öhm... Quincy akar látni, azt mondani, mennyé oda.}
{107}{}{A doki meg akarja javítani a kutyáját. Engem küldött az alkatrészért.}
{108}{}{Remek. Viszlát!}
{109}{}{Raul, Quincy látni akar.}
{110}{}{Quincy, mi? Hát, Raul meg nem akarja látni. Elege van már abból a szarevõbõl.}
{111}{}{Oké.}
{112}{}{Quincy mondani neked seggfej. Nem lenni elég tökös hozzá, hogy elmenni.}
{113}{}{Rendben.}
{114}{}{Quincy szerint egy szánalmas seggfej vagy, aki még ahhoz sem elég tökös, hogy személyesen jelentkezzen nála.}
{115}{}{Hé ember, Raul nem nyeli tovább ezeket a sértéseket! Láttad Quincyt ezeken a gépeken dolgozni? Nem, ezek a bébik csak Raulé. És tudod miért? Mert Quincy egy tehetségtelen FASZ, azért!}
{116}{}{Öö...}
{117}{}{Hát...}
{118}{}{Jól van, sajnálom. Raulnak nem kellene így beszélnie veled, végtére is csak egy hírvivõ vagy. Hé, figyelj csak, sok a dolgod most?}
{119}{}{Nem lenni túl elfoglalt, mért?}
{120}{}{Nem igazán, miért?}
{121}{}{Figyelj, Raul most elmegy meglátogatni Qiuncy-t. Addig te maradj itt és vigyázz Raul madárkáira, rendben?}
{122}{}{Vigyázni rájuk.}
{123}{}{Rendben, Raul. Megteszem.}
{124}{}{Hé, köszike! Raul jön neked eggyel! Ne menj túl messzire, és ha valaki bántani merészelné õket, akkor seggbelövöd, rendben?}
{125}{}{Oké.}
{126}{}{Hé, mit csinálsz? Húzzál onnan, mint a vadliba, bazze! Raulnak a ti baszogatásotok nélkül is épp elég gondja van a madárkákkal.}
{127}{}{Hé, mondtam, hogy ne buzeráld a madárkákat! Most Raul ad neked egy kis leckét. Na, gyere ki a hóra! Vedd le azt a rohadt nagy páncélt, és állj ki Raul ellen egy kis bunyóra!}
{128}{}{Nem, mi nem gondolni úgy.}
{129}{}{Baszóggyá meg, Raul! Szétlõni segged!}
{130}{}{Nem kösz, te túl kemény vagy nekem, haver.}
{131}{}{Minek öklözni, ha van itt más is, ami tökéletesen megteszi?}
{132}{raul9}{Ne basztasd Raul madárkáit! Tûnj el onnan!}
{133}{}{Oké.}
{134}{raul11}{Raul szerint csak valami nudista sétálgathat itt egyenruha nélkül.}
{135}{}{Hé, ember! Ha az õrmi elkap egyenruha nélkül, szétrúgja a segged.}
{136}{raul13}{Miért nincs rajtad egyenruha?}
{137}{raul14}{Szent szar! Megtámadtak bennünket!}
{138}{raul15}{Behatolók! Õrség!}
{139}{raul16}{Behatolók! Erõsítést a hangárba!}
{140}{raul17}{Na, mi van, he? Megtámadtak minket?}
{141}{raul18}{Miért szól a sziréna? Mi történik?}
{142}{raul19}{Mi folyik itt?}
{143}{raul20}{Raul most szépen beutal téged az intenzívre, csávókám.}
{144}{raul21}{Hé, ideje imádkozni!}
{145}{raul22}{Raul szétrúgja a segged.}
{146}{}{Hé, az alkatrészek a szekrényben vannak mögöttem. Add át a dokinak Raul üdvözletét!}
{147}{}{Kösz.}
{150}{raul23}{Hé, ember! Raul nem szereti, ha az emberek a cuccait buzerálják! Tûnj onnan!}
{151}{raul24}{Raul figyelmeztetett! Õrség!}
{200}{raul25}{Raul hallotta, hogy a háta mögött mocskolod.}
{201}{raul26}{Raullal ez már megtörtént egyszer, de nem fog még egyszer megismétlõdni!}
{300}{raul27}{Nem látod, hogy Raul elfoglalt?}
