{100}{}{Egy vékony, koszos ember áll elõtted.}
{150}{}{Flick, aki éppen a tökét vakarássza. }
{151}{}{Ennek a mocskos alaknak idõnként visszataszítóan rángatózik az arca.}
{200}{flick25}{Takaroggyá kifele, hallod-e, faszkalap!?}
{201}{flick26}{Mi van má', hurkatõ'tõ! Húzzá' innét elfele!}
{202}{flick27}{Megsüketûté', vagy csak meghülyûté'?}
{203}{flick28}{Na, mongyad, mi a gondod!}
{204}{flick29}{Takaroggyá' innét francba!}
{220}{flick1}{Egen? Flick vagyok. Mi faszt akarol, mi?}
{221}{flick2}{Na, mi legyen? Idõmet pazarlom itten csak, hela!}
{222}{}{Mi ez a bolondos akcentus, Flick?}
{223}{}{Mi a fenével foglalkozol te itt?}
{224}{}{Meg akarok találni egy Menedéket és egy Vic nevû kereskedõt. Nem tudsz segíteni?}
{225}{}{Kereskedni akarok.}
{240}{flick3}{Kõne még valami?}
{241}{}{Éppenséggel megnézném még egyszer, milyen cuccaid vannak.}
{242}{}{Tulajdonképpen akarok valamit kérdezni.}
{243}{}{Egyelõre megteszi. Majd találkozunk, Flick.}
{260}{flick4}{Kibaszott beszerzõ vagyok én, mit gondósz? Én vagyok helyi jó szamuráj-itánus.}
{261}{}{Hogy mondod?}
{262}{}{He, öö, rendben... hadd kérdezzek valamit!}
{263}{}{Na, jó... oké. Viszlátásra, Flick!}
{280}{flick5}{Azér' dógozok, hogy a kis paisanos érezzék jól maguk.}
{281}{}{Hogy a kis pajzánok jól érezzék magukat?}
{290}{flick6}{Pai-san-o, tudod, kölkök. Én kölkeim.}
{291}{}{A te kölkeid?}
{292}{}{Õszintén remélem, hogy most nem gyerekek pajzánkodásáról fogok hallani. Hadd kérdezzek valami mást!}
{300}{flick7}{Bizony, nekem dógoznak. Hoznak nekem dógokat. Aprócska dógokat. Tudod...}
{301}{}{Öö, nincs.}
{302}{}{Aha, oké. Akkor hadd kérdezzek valami mást!}
{303}{}{Értem már. Nem akarlak ööö... kellemetlen helyzetbe hozni. Viszlát!}
{315}{flick8}{Ide hozzák cuccokat, amit talá'nak. Ici-pici dógokat. Ami má' senkinek se nem kõ. Cserébe gongyukat viselem nekijjük.}
{316}{}{Remek egyezségnek látszik.}
{325}{flick9}{(Flick vállat von). E'vagyunk, mint befõtt...}
{326}{}{Akkor hadd kérdezzek valami mást!}
{327}{}{Biztos hoztak valamit, amiért érdemes alkudni. Hadd nézzem, mid van!}
{328}{}{Csak szétnéztem. Rendben, viszlát, Flick!}
{340}{flick10}{Mirõ' beszé'sz? Aztat gondolod, hogy valami kibaszott pirla vagyok? Valami süket filio di puttana? Valami bohócnak képzõ'sz? Azé' vagyok tán itten, hogy szórakoztassalak?}
{341}{}{Ó, nem. Elnézést, csak kiváncsi voltam. Hadd kérdezzek valami mást!}
{342}{}{Aha, így igaz szarfej. És semmi nem fog jobban mulattatni, mint a haláltusád.}
{343}{}{Rendben, ha ennyitõl megsértõdtél, akkor lelépek.}
{360}{flick11}{Menedék, he? Talán Mama tuggya valamit, mer' én nem. De én ismerem Vic gyereket, Metzgerné' van az a porca pistola.}
{361}{flick12}{Vic? Nem õ az ott veled? Marharépa... a Mamát viszont ismerem.}
{362}{}{Ki az a Metzger?}
{363}{}{Ki az a Mama?}
{364}{}{Kösz. Most akkor visszatérnék a kérdéseimre.}
{365}{}{Kösz, csak ennyit akartam tudni. Viszlát!}
{380}{flick13}{Mama kosztoldát üzemeltet városnak keleti részin. Temetõ mögött. Szép hely az ottan, van neki jó pasta. Mama mia!}
{381}{}{Kösz. Mi van azzal a Metzger gyerekkel, akinél Vic van?}
{382}{}{Kösz. Most akkor visszatérnék a kérdéseimre.}
{383}{}{Kösz, csak ennyit akartam tudni. Viszlát!}
{400}{flick14}{Ez igaz. Metzger, az a stronzo, halott. De nem tudni, mi történje Vic-kel.}
{401}{flick15}{Az a Metzger, az egy igazi rompiballe. Õ Rabszolga-Céh vezére, keleti részen, északra Mama vendéglõjétõ'. Akárhogyis, nála van Vic, tudom.}
{402}{}{Kösz, mit tudsz a Mamáról?}
{403}{}{Kösz. Most akkor visszatérnék a kérdéseimre.}
{404}{}{Kösz, csak ennyit akartam tudni. Viszlát!}
{410}{}{Well fuck me sideways, look who came by. The good samaritan who "saved the children" decided to grace me with his presence.
 You know, I'm a good Samurai-itan guy myself -- providin' fer them little paisanos and all. That is, until you came along and made that
 fuckin' orphanage idea a reality.}
{411}{}{Well fuck me sideways, look who came by. The good samaritan who "saved the children" decided to grace me with her presence.
 You know, I'm a good Samurai-itan guy myself -- providin' fer them little paisanos and all. That is, until you came along and made that
 fuckin' orphanage idea a reality.}
{412}{}{Hogy a kis pajzánok jól érezzék magukat?}
{413}{}{You sound like you don't like the fact that the children are no longer roaming the streets.}
{420}{flick18}{Hey, don't get me wrong. Life on the street is tough fer them kids, but it's the end of our little arrangement that gets me down.}
{421}{}{What arrangement?}
{422}{}{You mean them pickpocketing from people and bringing the items to you to sell.}
{430}{flick19}{Don't you get smart with me asshole. The kids bring me items they *find.* I don't know where they get them and frankly, I don't give a fuck.}
{431}{}{Folytatom.}
{432}{}{You're full of it. I'm sick of skum like you who use people for their own benefit. Time to die!}
{440}{flick20}{Pai-san-o, tudod, kölkök. Én kölkeim.}
{441}{}{And you have an arrangement with them?}
{450}{flick21}{Ide hozzák cuccokat, amit talá'nak. Ici-pici dógokat. Ami má' senkinek se nem kõ. Cserébe gongyukat viselem nekijjük.}
{451}{}{Remek egyezségnek látszik.}
{460}{}{Yeah... business was good 'til you came along. See, yer little stunt's gonna cost me. My business is gonna suffer thanks to you.
 Because of this, I don't really like you too much. In fact, I fuckin' hate you. But, I'm a business man, so if you need to barter,
 get to it. If not, fuck off.}
{461}{}{Alright, let's see what you have in stock then.}
{462}{}{I think I have all I need. Goodbye.}
{463}{}{I think I'll stay... and kick your ass.}
{470}{}{You again? You better be here to make some good trades, 'cause I'm getting real fuckin' sick of looking at you.
 In fact, I vomit in my mouth a little every time I see yer face. That's how much you disgust me. And if yer not here to
 trade, then I suggest you turn around and walk the fuck outta here.}
{471}{}{Kereskedjünk!}
{472}{}{Csak szétnéztem. Rendben, viszlát, Flick!}
{480}{flick24}{You done wastin' my time?}
{481}{}{Let me take another look.}
{482}{}{That should do it. Goodbye Flick.}
