{100}{}{Õ Lara.}
{150}{}{Õ ennek a bandának a fõnöke.}
{200}{}{Lara vagyok. Én vezetem ezt a bandát. Jobb, ha nem csinálsz itt semmi zûrt, különben hatalmas ruhát kapsz.}
{201}{larad2}{Szia! Kell valami?}
{202}{}{Nincs nálatok melólehetõség?}
{203}{}{Csak nézelõdök.}
{204}{}{Egy Vic nevû kereskedõ után nyomozok.}
{205}{}{Aruh.}
{206}{}{Rara.}
{220}{larad3}{Nincs orvosunk a városban és én sem tudok rajtad segíteni.}
{221}{larad4}{Bocs, de még mindig nem értem.}
{222}{}{Ack.}
{230}{larad5}{Nem ugrik be a név, de ismétlem, nem tartom számon, kik járkálnak ki-be a városban. Kérdezd meg Becky-t! Mindenki nála köt ki végül, õ lehet, hogy ismeri.}
{231}{}{Nincs nálatok melólehetõség?}
{232}{}{Köszönöm. Viszlát!}
{240}{larad6}{Ha nem valami határozott céllal jöttél Rejtekbe, akkor jobban teszed, ha elmész. Nem túl biztonságos errefelé.}
{241}{larad7}{Ó, oké.}
{242}{}{Nincs nálatok melólehetõség?}
{243}{}{Magam is meg tudom oldani.}
{244}{}{Oké, kösz.}
{250}{larad8}{Nem kétlem, különben aligha jutottál volna el ide élve.}
{251}{larad9}{Izé, igen, úgy hallottam. Már mondtad.}
{252}{}{Nincs nálatok melólehetõség?}
{253}{}{Oké, kösz.}
{260}{larad10}{Attól függ, mihez értesz? Van valami, amit meg szeretnék tudni. Ha kideríted, fizetek is érte.}
{261}{larad11}{Ahogy már mondtam, több információra van szükségem egy bizonyos dologról... vagy helyrõl. Persze fizetek érte.}
{262}{}{Persze, mi lenne az?}
{263}{}{Talán késõbb.}
{270}{larad12}{Szólj, ha meggondoltad magad!}
{271}{}{Értem.}
{280}{}{Naszóval... innen keletre van egy templom. Metzger néhány embere õrzi, akármit is
 tárolnak odabenn. Derítsd ki, mi az, és fizetek érte 200 dollárt.}
{281}{}{Ez nagyon egyszerû. Idõközben megtudtam.}
{282}{}{Persze.}
{283}{}{Majd kiderül, mit tudok tenni az ügy érdekében.}
{290}{larad14}{Kösz. Ne szállj be bunyóba... egyelõre! Van egy tervem.}
{291}{}{Nem probléma.}
{292}{}{Majd jövök.}
{300}{larad15}{Mi az?}
{301}{}{Vegyipari nyersanyagok nagy ládákba csomagolva.}
{302}{}{Nagy dobozok, valamiféle vegyszerekkel.}
{303}{}{Megnézem még egyszer.}
{310}{larad16}{Ez beleillik a képbe. Kösz. Itt a pénzed.}
{311}{}{Hogyhogy?}
{312}{}{Nem probléma. Üdv!}
{320}{larad17}{Egy Menedékvárosból érkezett karavánt láttam bemenni, aztán a cuccok egy részét New Renóból érkezõ karavánok vitték el.}
{321}{}{És? Mi ebben a nagy szám?}
{322}{}{Ó.}
{340}{larad18}{New Reno a drog fõvárosa. Ahhoz, hogy drogot csinálhassanak, valahonnan kapniuk kell a nyersanyagot, tiszta? Úgy látszik, hogy részben vagy egészben Menedékvárosból szerzik be.}
{341}{}{New Reno merre van?}
{342}{}{Oké, kösz.}
{350}{larad19}{Nem tudom pontosan. Szerintem valahol délen. Még soha nem jártam arra, csak a karavánjaikat láttam egyszer régen... nagyon régen.}
{351}{}{Ah, oké, kösz.}
{360}{larad20}{Nem érdekel egy újabb gyors és könnyû kereset? 50 dolcsi? Könnyû pénz.}
{361}{}{Persze.}
{362}{}{Fogd rövidre!}
{370}{larad21}{Tudd meg nekem Metzgertõl, hogy nem bánja-e, ha Tylerrel lerendezünk egy régi ügyet. Tudni fogja mirõl van szó.}
{371}{}{Miért akarod, hogy éppen én kérdezzem meg?}
{372}{}{Ha lesz rá módom.}
{373}{}{Oké.}
{380}{larad22}{Mert nem akarom, hogy Tyler meglássa bármelyik emberemet, amint ki-be jár Metzgernél. Nem akarok tippeket adni.}
{381}{larad23}{Nem érted? Ha Tyler meglátja, hogy hirtelenjében Metzgerrel tárgyalok, megneszeli, hogy bûzlik valami.}
{382}{}{Meglátjuk.}
{383}{}{Oké.}
{390}{larad24}{Szóval, rájöttél, hogy mi van odabenn?}
{391}{}{Vegyipari nyersanyagok nagy ládákba csomagolva.}
{392}{}{Nagy dobozok, valamiféle vegyszerekkel.}
{393}{}{Még nem.}
{400}{larad25}{Na, beszéltél már vele? Mit mondott?}
{401}{}{Azt mondta, hogy mehet. Ha tied a gyõzelem, tied a munka, akárcsak a régi szép idõkben.}
{402}{}{Nem.}
{410}{larad26}{Klassz! Ebben bíztam. Hallottam, hogy nemrég panaszkodott rájuk. Itt a pénzed.}
{411}{}{Jól sejtem, hogy van még valami?}
{412}{}{Köszönöm. Viszlát!}
{420}{larad27}{Van még egy feladatom a számodra. Nem tudom, hogy fogod megcsinálni, de mivel már egyszer bejutottál, talán megbíznak benned.}
{421}{}{Belopóztam.}
{422}{}{Mi az?}
{430}{larad28}{Biztosan ki tudsz találni valamit.}
{431}{}{Oké, mi lenne az?}
{440}{}{Jelenleg nem volnánk képesek legyõzni õket. Jó a felszerelésük és enyhe számbeli fölényben is vannak. Találj valami gyenge pontot, ami kiegyenlíti az esélyeket vagy amit ki tudnánk használni...}
{441}{}{Hogyan? Találjak egy gyenge pontot? Mégis, hogy képzeled?}
{442}{}{Mennyibe?}
{443}{}{Tekintsd úgy, hogy már el is intéztem!}
{450}{larad30}{Kapsz 150 dolcsit. Mi egyszerûen nem tudunk elég közel jutni ahhoz, hogy kiderítsük.}
{451}{}{Ha össze tudom hozni...}
{452}{}{Oké.}
{460}{larad31}{Nem tudom. Ezért van szükségem a segítségedre.}
{461}{}{Megpróbálom.}
{462}{}{Ennek semmi értelme.}
{470}{larad32}{Találtál valamit?}
{471}{}{Igen. Ma éjjel bulit csapnak.}
{472}{}{Még nem. Majd szólok.}
{473}{}{Gra.}
{474}{}{Nem.}
{480}{}{Tökéletes! Biztosan csak egy maroknyi õrséget hagynak. Ez jó esélyt jelent. Miután lecsaptunk a templomra, elintézzük a bulizókat is.}
{481}{}{És a pénzemmel mi lesz?}
{490}{}{Lassan a testtel! Ha kell a pénzed, velünk kell jönnöd! Nem kell harcolnod, de biztosnak kell lennem, hogy nem csaltak csapdába minket. Kapsz összesen 300 dolcsit.}
{491}{larad35}{Készen állsz?}
{492}{}{Oké, mehetünk.}
{493}{}{Adj egy kis idõt, hogy felkészüljek!}
{494}{}{Szó sem lehet róla! Tartsd meg a pénzed! }
{500}{larad36}{Rendben, de gyorsan kell cselekednünk, szóval ne tartson soká, vagy elcsesszük az esélyeinket!}
{501}{}{Oké.}
{510}{larad37}{Nem kell harcolnod. Könnyû pénz.}
{511}{larad38}{Nos, meggondoltad magad?}
{512}{}{Mehetünk, készen állok.}
{513}{}{Oké, mindjárt visszajövök.}
{514}{}{Nem.}
{515}{}{Uk}
{520}{larad50}{Miattad puskáztuk el!}
{521}{larad51}{Gyáva!}
{522}{larad52}{Nem kapsz semmit!}
{523}{larad53}{Amúgy is biztos csapda lett volna!}
{524}{larad54}{Bocs, de megbízhatatlan vagy!}
{525}{larad55}{Nem bízom meg benned.}
{530}{larad56}{Megcsináltuk!}
{531}{larad57}{Köszönöm a segítséget.}
{532}{larad58}{Külön köszönet neked!}
{533}{larad59}{Végre megfizettem Tylernek azért, amit a bátyámmal csinált.}
{534}{larad60}{Köszönöm még egyszer.}
{540}{larad61}{Most, hogy Metzger halott, nem tudom, mi lesz.}
{541}{larad62}{Talán egyszerûen csak fel kéne cuccolni.}
{542}{larad63}{Hallottad, hogy Metzger meghalt? Nem tudom, mit tegyek most.}
{543}{larad64}{Mi lesz most Rejtekbõl? Talán valami jobb.}
{544}{larad65}{Ebbõl végül még jó is kisülhet.}
{550}{larad66}{Köcsög!}
{551}{larad67}{Rohadék!}
{560}{larad39}{Kösz. Itt a pénzed és még 100 dollár jutalom.}
{570}{larad40}{Kinyírtad Tylert és az õreit? Most hogyan bizonyítsunk Metzger elõtt? Soha nem fog felfogadni minket! Ez volt az egyetlen esélyünk.}
{571}{larad41}{Nincs meló. Valaki kinyírta Metzger õreit és most nem áll szóba velünk. Azt hiszi, mi tettük. Isteni.}
{572}{}{Elnézést.}
{573}{}{Nagy kár.}
{574}{}{Én voltam, és most te jössz!}
{575}{}{Rendben, viszlát!}
{576}{}{He?}
{577}{}{Aghhh!}
{590}{larad42}{Azt mondtam, hogy együtt megyünk! Mivel senki nem vigyázott a cuccra, valaki megfújta és Metzger most pokoli dühös.}
{591}{larad43}{Azt mondtam, derítsd ki a gyenge pontjukat, nem azt, hogy öldd meg õket! Mivel senki nem vigyázott a cuccra, valaki megfújta és Metzger most pokoli dühös.}
{592}{larad44}{A francba! Azt mondtam, hogy kérdezd meg Metzgert, nem azt, hogy öldd meg õket! Mivel senki nem vigyázott a cuccra, valaki megfújta és Metzger most pokoli dühös!}
{593}{larad45}{A francba! Megmondtam, hogy ne támadj rájuk! Mivel senki nem vigyázott a cuccra, valaki megfújta és Metzger most pipább, mint valaha!}
{594}{}{Ó, igen, sajnos mennem kell.}
{595}{}{Ez szégyen!}
{596}{}{Most rajtad a sor, kurva!}
{597}{}{Uff!}
{598}{}{Te jössz!}
{610}{larad68}{Te aztán tudod, hogyan csesszél el dolgokat, igaz?}
{611}{larad69}{Nincs már szükségünk a segítségedre.}
{612}{larad70}{Eridj, idegesíts valaki mást!}
{613}{larad71}{Metzger jobb ha nem tesz semmit ellenünk.}
{614}{larad72}{Elnézést, nem tudok segíteni.}
{615}{larad73}{Most nem beszélgetek! Megpróbálom kitalálni, mi a fenét csináljunk most.}
{616}{larad74}{Remélem, Metzger nem hiszi, hogy benne voltunk.}
{617}{larad75}{Most mit csináljunk?}
{618}{larad76}{Jobb, ha gyorsan lelépünk, mielõtt Metzger azt hiszi, megöltük az õreit.}
{619}{larad77}{Voltál valaha New Renóban? Lehet, hogy arra megyünk... vagy északnak.}
{650}{larad78}{Rendben, induljunk! Mindenki utánam!}
{700}{}{Alright, we took care of the skeleton crew here at the church, but there still is Tyler and his cronies over in the Residential area.
 They should be pretty drunk by now and we can easily catch them off guard. You ready to finish this?}
{701}{}{Let me heal first. I'll tell you when I am ready.}
{702}{}{Gyerünk!}
{710}{larad47}{You ready to take Tyler and his crew out?}
{720}{larad48}{Well, don't stray too far. We need to finish this tonight or we'll do it without you.}
{721}{}{I'll be back shortly.}
{722}{}{Gyerünk!}
{730}{larad49}{We did it. I can't believe it! We're heading back to the church to take charge. Meet us back there for your reward.}
