{100}{}{Egy gonosz külsejû pasast látsz.}
{101}{}{Metzger, a rabszolga-hajcsárok fõnöke.}
{150}{}{Metzger, a Rabszolga-Céh feje.}
{200}{metzg1}{Ezért megfizetsz!}
{210}{metzg2}{Mi a faszt akarsz?! Ez a Rabszolga-Céh, nem valami menedék az ilyen kibaszott narkósoknak!}
{211}{metzg3}{Mi a francot akarsz, te ocsmány kurva? Ez a Rabszolga-Céh, nem egy kibaszott kupleráj!}
{212}{metzg4}{Mit akarsz, te kurva? Ez a Rabszolga-Céh, nem egy kibaszott kupleráj!}
{213}{metzg5}{Kezdesz kiakasztani! Most meg mi a fenét akarsz?}
{214}{metzg6}{Na, mi van, a jó életbe?}
{215}{metzg7}{Hogy mondod?}
{216}{metzg8}{Jobb, ha rövidre fogod!}
{217}{metzg9}{A rohadt változatosságért akarsz itt dolgozni?}
{218}{metzg10}{Már kezdem megszokni az ocsmány pofád. Nahát... akarsz valamit, vagy mi van?}
{219}{metzg11}{Úgy nézek ki, mint a kibaszott apád, vagy mi? Kurvára remélem, hogy nem. Na, köpd már ki, mit akarsz?}
{220}{metzg12}{Na, nézd csak, ki van itt! Azt hiszed, te valami különlegesség vagy, mi? Beszélj, vagy tûnj a picsába!}
{221}{metzg13}{És most mit akarsz, hajcsár?}
{222}{metzg14}{Egész nap itt fogsz ácsorogni, vagy mondani is akarsz valamit?}
{223}{metzg15}{Szólalj már meg! Nem érek rá egész nap ezzel szarakodni!}
{230}{metzg16}{Ó, és mégis ki lenne az? Remélem, többé nem akarod majd látni...}
{231}{metzg17}{Nincs veled senki, aki érdekelne. Engem csak emberek érdekelnek - mármint a normálisak.}
{232}{metzg18}{Te kibaszott idióta, minek nézel te engem, egy kibaszott boltnak, vagy mi? Ha van eladó rabszolgád, bökd ki! Ha mást akarsz eladni, keress egy kibaszott boltot!}
{233}{}{Miria}
{234}{}{Davin}
{235}{}{Vic}
{236}{}{Myron}
{237}{}{Cassidy}
{238}{}{Sulik}
{239}{}{Kérdezhetnék inkább valami mást?}
{240}{}{Meggondoltam magam. Viszlát!}
{241}{}{Dex}
{242}{}{Cat Jules}
{243}{}{Kitsune}
{245}{metzg19}{Magyarázza csak!}
{246}{metzg20}{Valóban?}
{247}{metzg21}{Nem vagyok a rohadt szolgád, úgy hogy igyekezz!}
{248}{metzg22}{Mi van? Nem érek rá egész nap.}
{249}{metzg23}{Na, lökjed!}
{250}{metzg24}{Talán.}
{255}{}{Van valaki, akit el akarok adni.}
{256}{}{Vicrõl, a kereskedõrõl...}
{257}{}{Keresek egy kereskedõt.}
{258}{}{Lara megbízott, hogy kérjek engedélyt tõled Tyler megtámadására.}
{259}{}{Beléphetek a Céhbe?}
{260}{}{Mit tudsz mondani nekem a Céhrõl?}
{261}{}{Szeretnék elmenni egy rabszolga-vadászatra.}
{262}{}{Mindegy. Viszlát!}
{263}{}{ akar akció.}
{264}{}{Nem.}
{265}{}{I was looking over the slaves you got back there, but you see, I have very, uh...*selective* tastes, and none of
 them are quite what I'm looking for. Are these all the slaves you have to offer?}
{270}{metzg25}{Na, mi van, kedvet kaptunk hozzá? Nem veszek ám be akárkit... a francba. Ha nem válsz be, úgyis eladlak. Kapsz egy tetoválást a homlokodra, amibõl mindenki láthatja, hogy rabszolga-hajcsár vagy. Ez örökre megmarad, szóval nincs visszaút.}
{271}{metzg26}{Nocsak, visszatért a mi kis nebáncsvirágunk! Mi van, meggondoltad magad? Mégiscsak akarod azt a tetkót?}
{272}{metzg27}{Igen, beszállhatsz... Nem kell túl sok ész hozzá. Ha elcseszed, egyszerûen eladlak. Ha bevállalod, kapsz egy tetoválást a homlokodra, amibõl mindenki megtudja, hogy rabszolga-hajcsár vagy.}
{273}{}{Készen.}
{274}{}{Ezt még meg kell gondolnom. Visszajövök késõbb.}
{275}{}{Talán mégsem. Viszlát!}
{276}{}{Uja! (bólintasz)}
{277}{}{Nem, nem, nem, nem!}
{285}{metzg28}{Mégis, mi a faszt képzelsz? Ez a Rabszolga-Céh. Rabszolgákat adok, veszek.}
{286}{}{Honnan szerzed a rabszolgákat?}
{287}{}{Szeretnék beállni!}
{288}{}{Még szeretnék valamit kérdezni.}
{289}{}{Ó, rendben. Viszlát!}
{300}{metzg29}{Hát, innen is, onnan is. Általában a benszülötteket és a nomádokat gyûjtjük be, ha épp beléjük botlunk.}
{301}{}{Jól hangzik! Hogy vehetnék részt ilyesmiben?}
{302}{}{Kérdeznék valami mást.}
{303}{}{Ó, rendben. Viszlát!}
{310}{metzg30}{Nahát, el se bõgted magad! Marha büszke vagyok rád... igazából a tetkó is baromi jól mutat rajtad. Csak sikíts, ha készen állsz az elsõ vadászatra!}
{311}{}{Köszönöm. Viszlát!}
{312}{}{Készen állok.}
{313}{}{Én ölni MOSTAN!}
{314}{}{Oké-zsoké.}
{320}{metzg31}{Két emberem egész közel visz a célpontokhoz. A pénzed az általad begyûjtött rabszolgák számától függ, de figyelned kell a többiekre is. Ha valakit megölnek, keményen levonok a fizetségedbõl.}
{321}{metzg32}{A francba, teljesen kifogytunk. Várni kell, hogy néhány primitív népség visszamerészkedjen a környékre. Lehet, hogy el kéne kezdeni tenyészteni õket.}
{322}{metzg33}{Bocs, de egyszerûen nem váltál be. Túl nagy a veszteség és ez bizony üzlet. Én keresni akarok, nem ráfizetni.}
{323}{metzg34}{Rendben. Készen állnak.}
{324}{metzg35}{Rendben, mehetsz!}
{325}{metzg36}{Akkor mozogjunk!}
{326}{metzg37}{Rendben. Keress fel, ha készen vagy!}
{327}{}{Oké.}
{328}{}{Ööö.}
{340}{metzg38}{Meg kell ölni az összes ellenségeset! Ha megtámadnak, nyírd ki õket! Nem akarok többet foglalkozni velük, kibaszott nagy zûrt csinálnak. Ha végeztél, a többiek majd összeterelik és megjelölik a maradékot.}
{341}{}{Oké.}
{342}{}{Ó.}
{350}{metzg39}{Ha elkezdik megjelölni a rabszolgákat, visszajöhetsz, ha akarsz. Ez különleges gyakorlatot igényel, szóval ne akard lefõzni a többieket! Ameddig nem teszel kárt az áruban, azt csinálsz, amit akarsz!}
{351}{}{Értem.}
{352}{}{Ahha.}
{360}{metzg40}{Ó, igen. Egész csinos. Adok érte }
{361}{metzg41}{Õ rendben van. Valószínûleg le tudnám csapni a kezedrõl némi pénzért. Legyen mondjuk }
{362}{metzg42}{Te hülye állat! Mi a francból gondoltad, hogy vissza akarom kapni ezt a hülyét? Egy örökkévalóságig tartott, amíg megjavította azt a rohadt rádiót. Egy rádiót! Veled marad. Nem akarom, hogy bármit is tönkre tegyen itt.}
{363}{metzg43}{Hát nem is tudom... ez meglehetõsen nyeszlett... okos legalább? Ez még érhet valamit. Kapsz érte }
{364}{metzg44}{Ez egész jó harcosnak látszik. Hmmm... }
{365}{metzg45}{Egy újabb benszülött? Fura egy szerzet... Mindegy, erõsnek látszik, és ez a külsõ önmagában hozhat némi plussz pénzt. Mit szólnál }
{366}{}{Mit szólnál valami máshoz?}
{367}{}{Izé, hadd kérdezzek valami mást akkor.}
{368}{}{Oké.}
{369}{}{Rendben.}
{370}{}{Oké.}
{371}{}{Nem éri meg.}
{372}{}{Nem.}
{380}{metzg46}{Oké fiúk, zárjátok az ólba!}
{381}{metzg47}{Oké fiúk, zárjátok az ólba!}
{382}{}{Rendben, fõnök.}
{390}{metzg48}{Akkor meg ne herdáld a kibaszott idõmet! Akkor gyere vissza, ha eladóvá válik valaki akitõl meg akarsz válni.}
{391}{}{Szeretnék mégvalamit kérdezni.}
{392}{}{Oké. Viszlát!}
{400}{metzg49}{Mi a franctól izgult be ilyen nagy hirtelen? Egyszer már adtam egy esélyt annak a kurvának. Nem hiszem, hogy elég tökös lenne hozzá, hogy megpróbálja.}
{401}{}{Mirõl beszélsz?}
{402}{}{Tehát rendben?}
{410}{metzg50}{Ó, ne add nekem az ártatlant! Pontosan tudom, mire készül. Egyszer már adtam neki egy sanszot, amivel nem tudott élni, de ha úgy gondolja, hogy megpróbálná...}
{411}{}{Vagyis rendben van?}
{420}{metzg51}{Nos, én azt mondtam, hogy él az ajánlatom. Ha úgy véli, hogy szét tudja rúgni a seggét és jobban tud vigyázni a szajrémra...}
{421}{}{Nos?}
{422}{}{Akkor ez most igen?}
{430}{metzg52}{Figyelj rám: szarok rá, hogy melyikõjük õrzi a cuccot. Amíg semminek nem esik baja, engem nem érdekel.}
{431}{}{Még egy kérdést, ha lehet...}
{432}{}{Oké, kösz.}
{440}{metzg53}{Mi a faszt akarsz tõlem? Úgy nézek ki, mint egy kibaszott... várj csak! Te bizonyára Vicet keresed.}
{441}{metzg54}{Menedék-technológiákra "specializálta" magát, legalábbis ezt állítja magáról. Most már az enyém és nem megy innen sehova.}
{442}{}{Mi van vele?}
{443}{}{Igen, rá gondoltam.}
{444}{}{Találkozhatnék vele?}
{445}{}{Miért tartod itt?}
{446}{}{Oké, rendben. Viszlát!}
{455}{metzg55}{Ez a kis fasz eladott nekem egy rádiót, amirõl azt mondta, hogy képes venni bizonyos adásokat. Persze nem képes. Elkaptam a faszit, mikor megpróbált elõlem meglógni a városból. Nagy hiba volt tõle. Senki sem baszhat ki velem. Szerencséje van, hogy még él.}
{456}{metzg56}{Ahogy mondtam. Elõbb meg kell javítania valamit. Utána beszélhetünk.}
{457}{metzg57}{Hát, nagy nehezen sikerült megjavítania azt a rohadt rádiót, de ez nem jelenti azt, hogy hagyom ilyen egyszerûen elmenni.}
{458}{metzg58}{Ettõl még megpróbált átverni.}
{459}{}{Találkozhatnék vele?}
{460}{}{Milyen adásokról beszélsz?}
{461}{}{Oké, kösz.}
{462}{}{Esetleg egy kis pénz segítene tisztába tenni a dolgokat?}
{463}{}{Milyen adásokról beszéltél az elõbb?}
{475}{metzg59}{Minek? Á, bazmeg, mindegy. Csak ne zavard annak a szaros rádiónak a javításában! Jobb, ha minél elõbb kész van vele. A tököm tele van, hogy egy lusta disznót kell etetnem.}
{476}{}{Miért tartod itt?}
{477}{}{Kösz.}
{485}{metzg60}{Az Enklávé és New... hé! Mi a francért érdekel? Ez üzlet. Biztos akarok lenni abban, hogy senki nem ver át. Ennél többet nem kell tudnod.}
{486}{metzg61}{Törõdj a saját dolgoddal!}
{487}{}{Oké.}
{495}{metzg62}{Bocsi, de ennek ára van. }
{496}{metzg63}{, }
{497}{}{Nem intézhetnénk ezt el másképp?}
{498}{}{Oké, itt van.}
{499}{}{Kérdezhetnék még egy pár dolgot elõbb?}
{500}{}{Bocs, de ennyit nem engedhetek meg magamnak.}
{510}{metzg64}{Oké, a tiéd, de húzza el a belét, mielõtt meggondolom magam, és golyót eresztek abba a kibaszott hülye fejébe.}
{511}{}{Kérdezhetnék elõbb még egy pár dolgot?}
{512}{}{Köszönöm.}
{520}{metzg65}{Ó igen. Elintézhetünk mindent szépen simán... Féláron megkapod, ha megérsz nekem annyit...}
{521}{metzg66}{Jobb, ha nem húzol tovább picim! Nem vagyok egy türelmes típus.}
{522}{}{Csak ha jó leszel hozzám.}
{523}{}{Persze, miért ne?}
{524}{}{Talán késõbb.}
{530}{metzg67}{Pedig jobb, ha elhiszed.}
{531}{}{Jó.}
{540}{metzg68}{Itt van }
{541}{metzg69}{Itt van }
{542}{metzg70}{Jó munkát végeztetek. Itt a pénzed}
{543}{metzg71}{Itt a pénzed, }
{544}{metzg72}{, }
{545}{metzg73}{Nos, ez }
{546}{metzg74}{Nem is volt olyan nehéz, igaz? Legközelebb ne hibázz. Itt a pénzed, }
{547}{metzg75}{, }
{548}{metzg76}{Ugyan már! }
{549}{metzg77}{Ne feledd, vigyázzatok egymásra és csak az ellenséges egyedeket öljétek meg. Itt a pénzed, }
{550}{metzg78}{Csak pénz}
{551}{metzg79}{Akarsz pénzt keresni vagy nem? Kiakasztasz! Mi olyan kibaszott nehéz ebben? Nesze, itt a zsozsód, }
{552}{metzg80}{Mi a franc volt veled? Szart se kerestél. Azért csináljuk az egészet, hogy pénzt keressünk, nem azért, hogy szarakodjunk.}
{553}{}{Legközelebb jobb leszek.}
{554}{}{Nesze semmi, fogd meg jól...}
{555}{}{Kösz.}
{556}{}{Aghhh!}
{570}{metzg81}{Átkozott kurva, ez az elsõ volt neked? Tuti, hogy az volt!}
{571}{metzg82}{A francba, kislány, ez az elsõ volt neked?}
{572}{metzg83}{Szerintem egész jó.}
{573}{metzg84}{Nem rossz, nem rossz, lehet, hogy még csinálhatjuk máskor is.}
{574}{metzg85}{A francba! Ez... ez a pénz aztán jó helyre ment!}
{575}{metzg86}{A francba! Te voltál a legjobb segg, akivel valaha dolgom akadt, pedig jó sokan voltak!}
{600}{metzg87}{TE OSTOBA FASZ! Hogy merted cserbenhagyni a vadásztársaidat? [Szembe köp] VÉGEZZETEK VELE!}
{601}{}{De én...}
{602}{}{Rendben, legyen...}
{620}{metzg88}{Hát, jó látni, hogy sikerült visszatérned.}
{621}{}{Ja, kemény menet volt.}
{622}{}{Kösz. Akadt egy-két gond odakint.}
{623}{}{Agra Moo ne!}
{630}{metzg89}{Ó, pénzt akarsz? Azt akarod, hogy kifizesselek?}
{631}{}{Ja.}
{632}{}{Ööhh.}
{640}{metzg90}{Hát persze, hogy SZERETNÉK segíteni neked, de... van egy kis problémám... azzal, hogy rátámadtál egy emberemre.}
{641}{}{Bocsi! Nem akarni, öö nem direkt... Ögh...}
{642}{}{Ajjaj!}
{650}{metzg91}{Ó, ne aggódj, biztos találok rá módot, hogy fizessek - pontosabban megfizessek neked! Emberek, fizetésnap!}
{651}{metzg92}{Ó, ne aggódj. Biztos vagyok benne, hogy találok rá módot, hogy fizessek - pontosabban megfizessek neked! Emberek, intézzétek el ezt a kurvát!}
{652}{}{Jaj...}
{653}{}{Garaka!}
{654}{}{Uh... Tank?}
{670}{metzg93}{Ó, biztos vagyok benne. Ezt a munkát nem lehet félvállról venni. Bizalom és hûség kell hozzá. Vigyázunk egymásra. Ez a helyes hozzáállás, nem gondolod?}
{671}{}{Valahogy úgy.}
{672}{}{Izé, mi folyik itt?}
{673}{}{Feltétlenül.}
{680}{metzg94}{Valahogy úgy? Nem gondoltam volna, hogy ilyen ravasz vagy. Igazából te egy ostoba fasz vagy. [Metzger rádbámul, aztán az õrökre néz és feléd int.]}
{681}{}{Akció lesz?}
{682}{}{Hogy mondod?}
{690}{metzg95}{Ó, szóval nem is vagy olyan hülye, mint ahogy a tetteidbõl látszik. Tudod, van egy kis gondom. Valaki volt olyan bátor, hogy megtámadja az embereimet.}
{691}{}{Tényleg?}
{692}{}{Baleset volt!}
{700}{metzg96}{Valóban? Örülök, hogy egyetértesz. És akkor mit csinálnál, ha valaki elárulná ezt a bizalmat?}
{701}{}{Izé, figyelmeztetni kéne õket?}
{702}{}{Rögvest megmutatom! [támadás]}
{703}{}{Megfizettetném velük!}
{710}{metzg97}{Úgy gondolod? Tényleg? Nem is tudom. Én valami... tartósabbra gondoltam. [Egy gonosz mosollyal Metzger az õrök felé néz és biccent nekik.]}
{711}{}{Hogy mondod?}
{712}{}{Jaj, öcsém...}
{720}{metzg98}{Örülök, hogy megegyeztünk. [Metzger az õrökre pillant.] Emberek, fizetésnap!}
{721}{}{Öö...}
{730}{metzg99}{Igen, tényleg szégyenletes. Ennek az alaknak egyszerûen nem esik le, de úgy látom a többiek már kapisgálják. [Metzger egy kis kézmozdulatot tesz az emberei felé.] Kezdõdhet a mûsor!}
{731}{}{Ó, tényleg?}
{732}{}{Hûha.}
{740}{metzg100}{Igen, errefelé egész gyakran történnek balesetek. Attól tartok, mindjárt lesz egy újabb. [Metzger kedélyesen vigyorog, majd biccent az embereinek.]}
{741}{}{Akkor hadd szóljon!}
{742}{}{Ebbõl nem tudok kimászni, igaz?}
{750}{metzg101}{Viszont eléggé poénos lesz! Bízz bennem!}
{751}{}{Baszd meg!}
{752}{}{Öö, oké.}
{800}{}{Megölted a Rabszolga-Céh vezetõjét.}
{900}{metzg102}{What you see is what you get. If you don't like my merchandise, then get the fuck out of my face and stop wasting my time.}
{901}{}{Uh, sorry. Let me ask you something else then.}
{902}{}{Right. I think I'll go then.}
{903}{}{Actually, I think I'm going to waste *you* and your whole sick fucking operation.}
{910}{}{This is all I've got in stock here, you picky fuck, but I've always got new merchandise coming in from my other slave camp.
 Maybe if you check back later, I'll have something that tickles your fancy -- but they're mostly ignorant tribals that all look the
 fucking same, so if that's not your thing, you might be shit outta luck.}
{911}{}{Look, this might be an unusual request, but I'd really like to get first dibs on any new merchandise you got. Is there some
 way I could go check out the stock at your other camp? Of course, I'd be willing to pay a premium price.}
{912}{}{Alright, I'll keep checking back then.}
{913}{metzg104}{Good, but next time do me a favor and don't waste my time unless you've got actual business to discuss.}
{914}{}{Premium price, huh? Now you're talking my kinda language. We usually handle sales here, but I suppose an exception could be made,
 as long as you're serious. I'll tell you how to get there, but you better keep it to your fucking self. I swear, if you turn out to be a
 spy for them fucking Rangers, I'll hunt you down and skin you alive. [You listen to his directions, and note the Slaver Camp's location in your Pip-Boy.]}
{915}{}{Got it. Let me ask you something else.}
{916}{}{Thanks. I'll be on my way now. Bye.}
{1360}{}{ dolcsit. Mit szólsz hozzá?}
{1361}{}{ barátoddal?}
{1363}{}{ dollár.}
{1364}{}{ dollár.}
{1365}{}{ barátoddal?}
{1496}{}{ dollár.}
{1540}{}{dollár. Kibaszottul jó munka volt.}
{1541}{}{ dollár. Jónéhány kemény alakot is elintéztél. Csak így tovább...}
{1542}{}{ dollár.}
{1543}{}{. $}
{1544}{}{ nem olyan dolog, amin röhögni lehet, de másra nincs nagyon lehetõség..}
{1545}{}{ dollárt ér ezúttal. Egész jó munka volt.}
{1546}{}{ dollár.}
{1547}{}{ dollár? Nem rossz.}
{1548}{}{ dollár? Ennél többet is ér az!}
{1549}{}{ dollár.}
{1550}{}{ dolcsi! Ez baszottmód sajnálatos! Na, rázd gatyába magad, vagy kirúglak!}
{1551}{}{ dollár és kifelé!}
{2540}{}{ dollár.}
{2543}{}{ dollár.}
{15401}{}{dollár. Kibaszottul jó munka volt.}
