{100}{}{Egy nagyon vonzó és fiatal nõt látsz.}
{101}{}{Rebecca.}
{150}{}{Õ Rebecca, a Becky Kaszinó Bár tulajdonosát.}
{200}{rbcca1}{Helló, a nevem Rebecca. Kérsz valamit inni? Biztos vagyok benne, hogy megszomjaztál a hosszú úton.}
{201}{rbcca2}{Helló! Kérsz egy italt, vagy csak benéztél?}
{202}{rbcca3}{Szia! Örülök, hogy újra látlak. Van valami kérdésed, vagy csak egy kis jófajta whiskey-ért jöttél?}
{203}{rbcca4}{Örülök hogy látlak. Mi a helyzet? Szükséged van valamire?}
{204}{rbcca5}{Remélem, minden rendben van az én kedvenc vevõmmel! Mit tehetek ma érted?}
{205}{rbcca6}{Szia!}
{206}{rbcca7}{Mindig örülök, ha láthatlak.}
{207}{rbcca8}{Helló! Egy italt? A környék legjobb whiskey-jét nálunk találod!}
{208}{rbcca9}{Üdv!}
{209}{rbcca10}{Te vagy az? Gondoltam. Mit szólnál egy italhoz, kedves?}
{210}{rbcca11}{Rebecca miatt jöttél vissza, vagy csak egy pohár italra vágysz?}
{211}{rbcca12}{Üdvözöllek Rebecca bárjában és kaszinójában. Miben segíthetek?}
{212}{rbcca13}{Szia. Miben segíthetünk?}
{213}{rbcca14}{Kérsz valamit? Esetleg egy italt?}
{214}{rbcca15}{Egy italra van szükséged, vagy esetleg valami másra?}
{215}{rbcca16}{Miben segíthetek?}
{216}{rbcca17}{Üdvözöllek. Miben lehetek a szolgálatodra?}
{217}{rbcca18}{Kérsz valamit?}
{218}{rbcca19}{Örülök hogy látlak. Miben segíthetek?}
{219}{rbcca20}{Hogy mondod?}
{220}{rbcca21}{Igen?}
{221}{rbcca22}{Most meg mit akarsz?}
{222}{rbcca23}{Kérlek, röviden add elõ, nagy ma a forgalom! Mit kérsz?}
{223}{rbcca24}{Mit tehetek érted? Elfoglalt vagyok.}
{224}{rbcca25}{Inni jöttél? Az asztalok arra vannak...}
{225}{rbcca26}{Nem nagyon értem, mire gondolsz. Mi legyen tehát?}
{226}{rbcca27}{Máris visszajöttél? Egy italt kérsz, nem?}
{240}{rbcca28}{Rendben.}
{241}{rbcca29}{Mit szeretnél tudni?}
{242}{rbcca30}{Boldoggá tesz.}
{243}{rbcca31}{Természetesen}
{244}{rbcca32}{Persze.}
{245}{rbcca33}{Nem érdekes.}
{246}{rbcca34}{Segítek, ha tudok}
{247}{rbcca35}{Naná, ne viccelj!}
{248}{rbcca36}{Nem számít. Szóval, mi volt az?}
{249}{rbcca37}{Segítek, ha tudok. Mi érdekel?}
{250}{rbcca38}{Kérdezz!}
{251}{rbcca39}{Ha kitartasz mellette.}
{252}{rbcca40}{Meghiszem azt!}
{253}{rbcca41}{Csak röviden, rengeteg dolgom van, nem várhat a kiszolgálás.}
{254}{rbcca42}{Hát, rendben. Mi az?}
{255}{rbcca43}{Gondolom.}
{256}{rbcca44}{Hogy mondod?}
{257}{rbcca45}{Bocs, de nem.}
{258}{rbcca46}{Most nincs.}
{270}{}{Szeretnék egy italt.}
{271}{}{Egy kereskedõ után nyomozok, aki menedékbõl származó felszereléseket árul.}
{272}{}{Egy Vic nevû kereskedõ után nyomozok.}
{273}{}{Volna itt valami munka?}
{274}{}{A munkával kapcsolatban...}
{275}{}{Van még valami munka a számomra?}
{276}{}{Semmit. Viszlát!}
{277}{}{Vikíí.}
{278}{}{Ruhh ruhh?}
{279}{}{Iho Sasa.}
{280}{}{dy.}
{281}{}{Ruhh ruhh?}
{300}{rbcca47}{A specialitásom a Whiskey. A Dyer családban ez szinte tradíció. Mindössze 5 dollárért hozzájuthatsz.}
{301}{rbcca48}{Az italok változatlanul csak 5 dollárba kerülnek, és még mindig ez a világ legjobb helye, ha inni akar az ember.}
{302}{rbcca49}{Jól érzed magad? Akarsz Whiskeyt? 5 dolcsi.}
{303}{}{Kérnék egy italt.}
{304}{}{Miért ilyen olcsók az italok?}
{305}{}{Dyer?}
{306}{}{Feltehetek egy kérdést?}
{307}{}{Viszlát!}
{308}{}{Vikíí}
{309}{}{Urka.}
{320}{rbcca50}{Ó, az a családunk neve. A Dyer név régóta ismert a kocsmák világában. Még a háború elõttrõl persze.}
{321}{rbcca51}{Ahogy mondtam, ez a családnevem. A háborút megelõzõen szerte a világban voltak Dyer kocsmák, szalonok, szórakozóhelyek, meg ilyesmik.}
{322}{}{Kérnék egy italt.}
{323}{}{Feltennék még pár kérdést.}
{324}{}{Viszlát!}
{330}{rbcca52}{Mivel ilyen jó kuncsaftom vagy, elárulok neked egy aprócska titkot. Tényleg egyszerû. Van egy szeszlepárlóm. Az egyik közeli városban lakó barátom tanított meg, hogyan kell csinálni. Szeretnél esetleg még egyet?}
{331}{rbcca53}{Nagyon sajnálom, ez üzleti titok. Ráadásul nem is nagyon ismerlek. Nem akarom, hogy Frankie megtudja. Elég gondot okoz így is. Még mindig akarsz egyet? Nagyon jó minõség.}
{332}{}{Rendben, kérek egyet.}
{333}{}{Feltennék még pár kérdést.}
{334}{}{Oké, kösz.}
{340}{rbcca54}{Parancsolj... Nagyon köszönöm.}
{341}{}{Köszi. Lehetne egy kérdésem?}
{342}{}{Oké, kösz.}
{343}{}{Kouösszi széppeny.}
{344}{}{Asky?}
{350}{rbcca55}{Bocs, nem hiszem.}
{351}{rbcca56}{Fred 200 dollárral tartozik nekem. Ha valahogy meg tudod nekem szerezni, kigondolunk valamit.}
{352}{rbcca57}{Még mindig szükségem van a kölcsönadott pénzre.}
{353}{rbcca58}{Derek kölcsönkérte egy könyvemet régebben. 80 dollárt fizetek, ha visszaszerzed nekem.}
{354}{rbcca59}{Még mindig keresem a könyvemet...}
{355}{}{Mi a pálya vele?}
{356}{}{Mesélj még!}
{357}{}{Feltehetek egy kérdést?}
{358}{}{Viszlát!}
{370}{rbcca60}{Nagyon régóta tartozik nekem azzal a pénzzel. Leírtam, mint veszteséget, de ha vissza tudnád szerezni, nagyon hálás lennék.}
{371}{rbcca61}{A könyvnek az a címe, hogy "A levendula virága". Derek valahol a Mama bárja mellett lesz a keleti oldalon.}
{372}{}{Majd kiderül, mit tudok tenni az ügy érdekében.}
{373}{}{Igazán könnyûnek hangzik.}
{374}{}{Már megtaláltam.}
{375}{}{Ezügyben késõbb még visszajövök...}
{385}{rbcca62}{Valóban megtaláltad? Ez nagyszerû!}
{386}{rbcca63}{Óh, megtaláltad a könyvem? Remélem, Derek nem tette tönkre.}
{387}{}{Igen.}
{388}{}{Sajnálom, de meghalt.}
{389}{}{Sajnálom, Derek is halott.}
{390}{}{Sajnálom, de Õ halott.}
{391}{}{Igen, itt van.}
{392}{}{Bocs, de nem.}
{400}{rbcca64}{Alig hiszem el! Hogy csináltad? Végül is mindegy. Egész le vagyok taglózva. Barátságom jeleként megosztozunk, rendben? Köszönöm még egyszer, ez igazán nagyon kedves volt tõled.}
{401}{rbcca65}{Nagyon örülök, hogy megtaláltad. Nagyon köszönöm, itt a pénzed.}
{402}{}{Szóra sem érdemes.}
{410}{rbcca66}{El sem tudom hinni, hogy mindketten halottak. Sajnálom. Köszönöm, hogy utánanéztél nekem. Ha most megbocsátasz...}
{411}{rbcca67}{Alig bírom elhinni, hogy meghalt... ennyi hosszú év után...}
{412}{}{Persze.}
{413}{}{Ó...}
{420}{rbcca68}{Igen, tudom, kirõl beszélsz. Vic lesz az, a pasas, akit Metzger bezárt.}
{421}{rbcca69}{Igen, ismerem Vicet. Metzger hét lakat alatt õrzi. Nem vagyok benne biztos, miért.}
{422}{}{Ki az a Metzger?}
{423}{}{Kérdeznék valami mást.}
{424}{}{Nagyszerû! Viszlát!}
{430}{rbcca70}{Idejösz Rejtekbe, és nem tudod, ki Metzger? Õ egy rabszolga-kereskedõ. A város keleti részén tanyázik. Nehéz eltéveszteni.}
{431}{}{Kérdeznék valami mást.}
{432}{}{Kösz.}
{440}{rbcca85}{Gyilkos!}
{441}{rbcca86}{Gyerekgyilkos!}
{442}{rbcca87}{Kérlek, menj el!}
{443}{rbcca88}{Nem tudom megérteni a szándékaidat.}
{444}{rbcca89}{Harc nélkül nem adom fel!}
{450}{rbcca71}{Buffy! Te vagy az? Mi van veled, hosszú idõ telt el, amióta nem láttalak...}
{451}{}{Hogy?}
{452}{}{Hogy?}
{460}{rbcca72}{Dave üdvözletét küldi, sajnos most nem tud itt lenni velünk, el kellett mennie.}
{461}{}{Hova?}
{470}{rbcca73}{Valami kommandóval kapcsolatos. Nem tudom pontosan, valami ilyesmi.}
{471}{}{Ó.}
{480}{rbcca74}{Ja, és azt mondta, adjam ezt oda neked. Ez a Hendee család ajándéka. Remélem, ez segít neked valamicskét.}
{481}{}{Mi az?}
{490}{rbcca75}{Csak pár apróság. Tessék... [Becky átad neked ezer dollárt, 5 Stimpakkot, egy fémpáncélt, egy Uzit, 5 tárat hozzá, egy plazmagránátot, és egy szál virágot]}
{491}{}{Köszönöm!}
{500}{rbcca76}{Szívesen, csak eltettem neked pár dolgot. Jobb, ha most visszatérek a munkámhoz.}
{501}{}{Köszönöm, viszlát!}
{510}{rbcca77}{Nem hallasz? Meghalt! Tudom, örülnem kéne, mert gonosz egy ember volt, annyi szent.}
{511}{}{Nem mondom, jól küzdött.}
{512}{}{Volna egy kérdésem.}
{513}{}{Igen. Viszlát!}
{514}{}{ ÖL!}
{520}{rbcca78}{Micsoda? Te? Nem is tudom, mit mondjak. Annyira gonosz ember volt...}
{521}{}{Egy sima köszönöm bõven elég lesz.}
{522}{}{Hümm.}
{530}{rbcca79}{Hát, azt hiszem, egy szimpla köszönöm elég lesz. Tudom, hogy ez nem helyes, de... tessék, fogd ezt a pénzt. [Becky 1000 dolcsit nyom a kezedbe!]}
{531}{}{Tartsd meg a pénzed, Rebecca!}
{532}{}{Nagyon köszönöm.}
{533}{}{Kösz!}
{534}{}{Úg!}
{540}{}{Csodálatos ember vagy. Még akkor is, ha nem tudom neked elnézni, amiket tettél. 
 Nagy szolgálatot tettél az emberiségnek.}
{541}{}{Csodálatos ember vagy. Még akkor is, ha nem tudom neked elnézni, amiket tettél. 
 Nagy szolgálatot tettél az emberiségnek.}
{542}{}{Kösz.}
{550}{rbcca90}{Nem látunk itt szívesen. Menj el, kérlek!}
{551}{rbcca91}{Kérlek, menj el!}
{560}{rbcca82}{Miért tetted tönkre a lepárlómat? Ártottam én neked valaha is?}
{561}{}{Megfizették...}
{562}{}{Nem vagyok köteles válaszolni senkinek sem.}
{563}{}{Nem tudom, mirõl beszélsz.}
{564}{}{Jól van, jól van...}
{565}{}{Úba gúba.}
{570}{rbcca83}{Valóban? Biztos vagyok benne, hogy az a tetû Frankie rángatott bele. Fogok ám csinálni egy másikat!}
{571}{}{Nem számít, én megkaptam a pénzemet.}
{572}{}{Úgy legyen...}
{573}{}{Nem lennék meglepve.}
{580}{rbcca84}{Tehát te is ilyen beszari vagy? Jellemzõ...}
{581}{}{Ó...}
