{100}{}{Egy prostit látsz.}
{150}{}{Egy szokásos, "tizenkettõ-egy-tucat" prostituált.}
{152}{}{[Beszéd]}
{153}{shela1}{Hé, csajokkal nem nyomom!}
{154}{}{Jól van, jól van...}
{155}{}{Elnézést.}
{156}{}{Mama?}
{157}{shela2}{Hé, ha közönség is lesz, többe kerül!}
{158}{}{Hé, oda fognak menni, ahova én is.}
{159}{}{Velem jönnek.}
{160}{}{Még visszatérek.}
{161}{}{Mama?}
{162}{shela3}{Óh, bébi. Hol voltál egész eddigi életemben?}
{163}{}{Pont itt, bébi.}
{164}{}{Mennyi lesz, kishúgom?}
{165}{}{Ömm, mennem kell. Szia.}
{166}{}{Tyûû!}
{167}{shela4}{A nagy darab mamlaszokat kedvelem.}
{168}{}{Rám illik!}
{169}{}{Jéj!}
{170}{}{Jaj, ne. Na, szia!}
{171}{shela5}{Milyen nagy fiú vagy!}
{172}{}{Ahogy te szereted.}
{173}{}{Igen, asszonyom.}
{174}{}{Mennem kell.}
{176}{}{Oké!}
{177}{}{Nem. Üdv!}
{178}{shela6}{Vissza fogsz te még jönni...}
{179}{}{Meglátjuk.}
{180}{}{Öhm, aligha.}
{181}{}{[nyáladzol]}
{182}{shela7}{Nincs elég zsozsód. Tûnj innen, édes!}
{183}{}{Késõbb visszajövök.}
{184}{}{Nem éred meg a pénzem, cunci.}
{185}{}{Bah!}
{186}{shela8}{Csodálatos voltál!}
{187}{}{Mint mindig, bébi.}
{188}{}{Jól van, jól van...}
{189}{}{Te is.}
{190}{}{Csõd-állatos!}
{191}{shela9}{Remek voltál!}
{192}{}{Kösz. Te is.}
{193}{}{Hmm.}
{194}{}{Aha.}
{195}{}{Nagyszerû!}
{196}{shela10}{Oké, végeztünk. Szia.}
{197}{}{Na, ebbõl elég!}
{198}{}{Oké. Szia.}
{199}{}{Jó volt.}
{200}{}{Viszla.}
{201}{shela11}{Nem fizetnek eleget ezért.}
{202}{}{Nem mintha megérted volna a pénzed.}
{203}{}{Hiányolni fogsz.}
{204}{}{Viszlát!}
{205}{}{Eltévedtél?}
{206}{shela12}{Gyere, amikor csak akarsz!}
{207}{}{Oké. Viszlát!}
{208}{}{Igen, igaz.}
{209}{}{Húúú!}
{210}{shela13}{Viszlát!}
{211}{}{Viszlát!}
{212}{}{Viszla.}
{213}{shela14}{Egy menet }
{214}{}{ dollárba kerül. Elõre kell fizetni.}
{215}{shela17}{Kövess!}
{216}{shela18}{Várok.}
{217}{shela19}{Nem fogok egész nap ebben a hideg szobában álldogálni.}
{218}{shela20}{Sietnél egy kicsit?}
{219}{shela21}{Utolsó esély.}
{220}{shela22}{Rendben, nem várok tovább.}
{221}{shela23}{Gyerünk, gyerünk!}
{222}{shela16}{Kezdesz már felizgulni, vagy valami?}
{223}{shela24}{Kövess!}
{224}{shela25}{Hé, haver, vedd le a kezed az áruról!}
{225}{shela26}{Hagyd abba! Nem vagyok játékszer.}
{230}{shela15}{Hogy...? Ez volt az elsõ alkalom?}
