{100}{}{Õ a bolt tulajdonosa.}
{101}{}{Tubby.}
{150}{}{Õ az üzlet tulajdonosa.}
{151}{}{Õ Tubby, az üzlet tulaja.}
{152}{}{[Beszéd]}
{153}{tubby1}{Örülnék, ha máshol intézné a dolgait.}
{154}{}{Maga üzletember. Üzleteljünk.}
{155}{}{Kérdezhetek valamit?}
{156}{}{Viszlát!}
{157}{tubby2}{Annyira örülök, hogy újra látom. Miben segíthetek?}
{158}{}{Kereskedjünk!}
{159}{}{Kérdezhetek valamit?}
{160}{}{Most nem kérek semmit. Viszlát!}
{161}{tubby3}{Üdvözlöm, uram, Isten hozta Tubby boltjában. Én vagyok a tulajdonos. Segíthetek valamiben?}
{162}{}{Igen, csereberéli szeretnék.}
{163}{}{Információra lenne szükségem.}
{164}{}{Viszlát!}
{165}{tubby4}{Üdvözlöm, hölgyem. A barátaim Tubbynak hívnak, nagyon szívesen látom magát az üzletemben. Miben segíthetek?}
{166}{}{Vennék néhány dolgot.}
{167}{}{Információra lenne szükségem.}
{168}{}{Viszlát!}
{169}{tubby5}{Jobban örülnék, ha inkább távozna.}
{170}{}{Viszlát!}
{171}{tubby6}{Mit szeretnél tudni?}
{172}{}{Ki vezeti ezt a várost?}
{173}{}{Miért árul mindenki drogokat?}
{174}{}{Tudja, merre van a Menedék?}
{175}{}{Mégiscsak úgy döntöttem, hogy csereberélnék.}
{176}{}{Semmi, szia.}
{177}{tubby7}{Nahát! Úgy tûnik, a kommunikációval lesz egy kis gondunk. Kérlek bólints, ha szeretnél csereberélni.}
{178}{}{[Bólintasz]}
{179}{}{Sziaszia.}
{180}{tubby8}{Attól tartok, senki. Rejtek olyan hely, ahol anarchia uralkodik és egyfajta darwini kiválasztódás érvényesül. Itt csak a legerõsebb, a leggyorsabb vagy a legokosabb marad életben.}
{181}{}{Öm, köszi.}
{182}{}{Oké. A drogok képezik a város gazdaságának alapját épp úgy ahogy más városok esetében a gabona vagy arany.
Redding egy másik kiváló példa egy város drogoktól hajtva.
 Azok a kibaszott bányászok mindig inkább be vannak állva mintsem bármi hasznos munkát végezzenek.
 Én magam sosem jártam ott, de csak néhány nap járásra van inenn dél-kelet felé ha meg akarnád nézni magad.}
{183}{}{Kösz.}
{184}{tubby10}{Hallottam egy Menedékváros nevû helyrõl, de hogy hol van pontosan, meg nem tudnám mondani magának. Nálunk nagyon kevesen tudnak elfogadható cserealappal szolgálni a menedékvárosiak által nyújtott egészségügyi ellátás fejében, így a legtöbbünk még soha nem járt ott.}
{185}{}{Oké. Köszi.}
{186}{tubby11}{Ez nem olyan infó, amit csak úgy bárkinek elmondanék.}
{187}{}{Egy százas megoldaná a nyelvét?}
{188}{}{Mi lenne, ha adnék 50 dolcsit és elmondaná nekem.}
{189}{}{Mit szólna, ha kapna két lehetõséget? Vagy elmondja az infót, vagy csinálok egy újabb lyukat a fejébe. Na?}
{190}{}{Hagyjuk!}
{191}{}{Akkor kérdezhetek valami mást?}
{192}{tubby12}{Persze, ez az összeg TALÁN segítene, de nincs magánál ennyi!}
{193}{}{Biztos elvesztettem valahol. Megyek, azt' megkeresem.}
{194}{tubby13}{Nem hiszem, hogy ennyi elég lesz.}
{500}{tubby14}{Persze, Petey. Mindjárt jövök.}
{501}{tubby15}{Kitartás, Petey!}
{502}{tubby16}{Jövök már, jövök.}
{510}{tubby17}{Tessék, Petey...}
{511}{tubby18}{Tudja, Petey, le kéne állnia ezzel a szarral!}
{512}{tubby19}{Fogja és tûnjön innen a francba, Petey!}
{520}{tubby20}{Öröm, ha együtt üzletelünk.}
