{100}{}{Rabszolga.}
{101}{}{Vic.}
{150}{}{Úgy tûnik, ezt a rabszolgát nagyon szemmel tartják.}
{151}{}{Õ Vic.}
{152}{}{[Beszéd]}
{153}{}{Megmondaná neki, hogy én nem... na megálljunk! Ki vagy te? Te nem vagy hajcsár. Mit keresel itt?}
{154}{}{A nevem }
{155}{}{. Azért jöttem, hogy megszöktesselek.}
{156}{}{A nevem }
{157}{}{ az én nevem, de téged miért zártak be ebbe a szobába?}
{158}{}{Meg tudnád mondani, merre van a 13-as Menedék?}
{159}{}{A nevem }
{160}{}{ a nevem. Késõbb még visszajövök.}
{161}{}{Dubba iba }
{162}{}{ dollár.}
{163}{}{Metzger még mindig nagyon mérges rám, annak ellenére, hogy megjavítottuk azt a nyamvadt rádióját. Azzal fenyeget, hogy elad valakinek! Ha kijuttatsz ebbõl a nagy rakás kupiból, bármit megteszek neked, amire csak kérsz!}
{164}{}{Renden, rendben.}
{165}{}{Bocsi, nem tudlak. Minden jót!}
{166}{}{Hohóóó.}
{167}{}{Nahát, újra erre jártál? Ez a piszok rádió nem fog magától megjavulni! Hogyan is várhatná el tõlem Metzger, hogy helyre pofozzam?!}
{168}{}{Honnan szerezhetném be az alkatrészeket?}
{169}{}{Én talán meg tudnám javítani.}
{170}{}{Hasznát vennéd ennek a rádiónak, amit találtam?}
{171}{}{Majd kiderül, mit tudok tenni az ügy érdekében.}
{172}{}{Spa pa?}
{173}{}{Tudom, hogy semmiség megcsinálni, csak kellene egy-két alkatrész. Van egy régi rádióm Klamathban, a házikóm hátsó részében. Pont olyan, amilyen kell. Ismered a Duntonék üzletét? A házikóm az övékétõl keletre áll.}
{174}{}{Erre a rádióra gondolsz?}
{175}{}{Megyek és megkeresem!}
{176}{}{Hmmm... Még visszanézek!}
{177}{vic5}{Nagyszerû! Pillanatokon belül megjavítom a rádiót!}
{178}{}{Oké, beszélek Metzgerrel.}
{179}{vic6}{Kösz.}
{180}{}{Viszlát!}
{181}{vic7}{Hogy? Elnézést, de nem értem.}
{182}{}{Hmm.}
{183}{vic8}{Köszönöm szépen! Örökké adósod maradok. Hogyan hálálhatnám meg?}
{184}{}{Mondd meg, hol van a 13-as Menedék!}
{186}{}{Csatlakozz hozzám! Jól jönne a segítség!}
{187}{}{Á, semmiség, ugyan már! Ég veled!}
{188}{}{Van cukorka?}
{189}{}{A 13-as Menedék? Innen keletre ott van Menedékváros. Néhányszor jártam ott üzletelni.}
{190}{}{Eljössz velem oda?}
{191}{}{Köszönöm. Viszlát!}
{192}{}{Naná! Beállok hozzád! Ez a vén trotty már látott egy-két érdekes dolgot, ebben biztos vagyok! Ráadásul szinte mindent meg tudok szerelni, bármit is mondjon Metzger!}
{193}{}{Nagyszerû, induljunk!}
{194}{}{Üdvözöllek a csapatban!}
{195}{}{Jól van, jól van...}
{196}{}{Vic legjobb barátom!}
{197}{}{Akarsz segíteni a keresésben?}
{198}{}{Nagyon jó! Kösz!}
{203}{vic11}{Menedékváros innen keletre van. Mindjárt megmutatom a térképeden.}
{204}{}{Kösz.}
{206}{vic12}{Pontosan itt van. [egy térképre mutat]}
{220}{vic13}{A fene egye meg! Majdnem megvan, de szükségem lenne a rádiómra a klamath-i házamból. Tudom, hogy pontosan ugyanolyan alkatrészek vannak benne, mint amik nekem kellenek.}
{300}{vic14}{Ja, valószínûleg tudok rajtad segíteni, de elõtte ki kell hoznod engem innen.}
{301}{vic15}{Megmondtam. Amennyiben ki tudsz innen jutattni, rám bármiben számíthatsz.}
{302}{}{Hogy kellene csinálni?}
{303}{}{Akkor saját magadra vagy utalva.}
{304}{}{Okés, majd meglátom mit tehetnék ezügyben.}
{350}{vic117}{Szerinted én ki tudnálak innen hozni?}
{351}{vic118}{Metzger még mindig nem enged elmenni.}
{352}{vic119}{Én nem bírom itt tovább!}
{353}{vic120}{Akármit megteszek érted, ha segítesz rajtam!}
{354}{vic121}{Megtérítem az összes költségedet!}
{400}{}{Ugye még nem voltál a házamban? Tényleg nagyon kellene az a rádió, Metzger kezd egyre jobban begõzölni!}
{450}{}{Honnan szerezted azt a kulacsot?}
{451}{}{Van egy kulacsom, rajta egy bazi nagy sárga tizenhármassal. Emlékszel még, honnan szerezted?}
{500}{vic17}{Na, ja! Emlékszem bizony. Ed-tõl vettem. Õ egy menedékvárosi brahminkupec.}
{501}{}{Kulacs? Óh, várj csak! Ja, van egy jó pár tucattal belõle. Elég jól el lehet passzolni. Ed-tõl, a menedékvárosi brahminkupectõl szereztem.}
{502}{}{Menedékvárost mondtál?!}
{550}{}{Abbahagynád ezt a folytonos fõnöközést?}
{600}{vic19}{Hogyne, fõnök!}
{601}{}{Azt mondtam, hogy ELÉG!}
{602}{}{Remélem, ez megteszi.}
{650}{vic20}{Rendicsek, komám!}
{651}{}{Úúg!}
{700}{}{Legyééél a barátom!}
{710}{}{Megmondanád neki, hogy ezt nem tudom megcsinálni pótalkatrészek nélkül. Hát nem tudom... várj! Ki vagy te? Valami új ember? Ugye azért küldött ide, hogy megint buzeráljon, mint a múltkor? Ettõl még semmi nem fog megváltozni! Itt nem tudom megcsinálni!}
{750}{}{Igazán megtennéd ezt értem? Semmit sem tudok tenni, amíg nem keveredtem ki innen. A gond csak az, hogy Metzger egy rádió megjavítása miatt zárt be ide, és nincsenek meg a szükséges pótalkatrészek.}
{753}{}{Honnan tudnám elõkeríteni azokat az alkatrészeket?}
{754}{}{Majd kiderül, mit tudok tenni az ügy érdekében.}
{760}{}{Ez egy bonyolult és hosszú történet. Szerintem annyi elég lesz röviden, hogy Metzger itt tart engem, amíg meg nem javítom neki ezt a nyamvadt rádiót. A kristály kiégett, és nincs semmilyen pótalkatrészem. Így hogy a francba várhatja el tõlem, hogy megcsináljam?!}
{761}{}{Azért jöttem, hogy kiszabadítsalak.}
{764}{}{Nem tudom. Na, minden jót!}
{800}{vic24}{Meg kell szerelnem ezt a rádiót. Ha tudnál nekem segíteni ebbe, esetleg tudnánk mire hivatkozni.}
{801}{}{Miben segíthetek?}
{803}{}{Kétlem. Sok szerencsét!}
{810}{vic25}{Miért ölted meg szegény Mamát? Bizonyára megvolt rá az okod... Elnézést, fõnök! Nekem ugyebár nem osztottak lapot itt. Ez egy nagyon gonosz város. Biztos vagyok benne, hogy õ is valami gonoszságot mûvelt.}
{811}{vic26}{Hé, fõnök! Kösz, hogy kirángattál abból a slamasztikából, amibe Metzgerrel keveredtem! Kell valami? Mama volt olyan rendes és ellátott, amíg nem voltál itt. Segítek neki a ház körül...}
{812}{}{Viszlát!}
{813}{}{Óóoooh...}
{814}{}{Szia szia!}
{823}{}{Még egyszer megkérdem: hol találom Ed barátodat?}
{830}{vic27}{Megtenném, ha tudnám, de problémásnak tûnsz. Csak felesleges teher lennék. Most, hogy a Mama meghalt, világgá megyek. Még nem tudom, hova. Talán látjuk még egyszer egymást valamikor. Mindent köszönök, amit értem tettél!}
{831}{vic28}{Megtenném, ha tudnám, de problémásnak tûnsz. Látszik, hogy csak alig tudod megvédeni magad. Én meg csak púp lennék a hátadon. Majd állok és várok itt, a Mama fõztje emlékeztet a volt feleségemére...}
{832}{vic29}{Szívesen megtenném, de tényleg! Szinte bármit megtennék érted. Csak mostanában nem tûnsz túl jó fõnöknek. Én csak konc lennék a nyakadon. Egy kicsit visszanézek a Mamához... Amíg a dolgok tisztázódnak. Már vagy ezer éve nem ettem abból a csodálatos házi kosztból.}
{833}{vic30}{Sajnálom, fõnök. Túl sokan vagytok. Most, hogy a Mama eltávozott, fogom magam és felszívódok. Azt sem tudom még, hogy hova... Egyszer még majd találkozunk valamikor. Köszönök mindent, amit értem tettél!}
{834}{vic31}{Nem férek be a csapatba, fõnök. Itt várok rád, amíg megoldódnak a dolgok. A Mama fõztje emlékeztet a volt nejemére... Nem vagyok benne biztos, hogy ez jót vagy rosszat jelent...}
{835}{vic32}{Én benne lennék, fõnök, de szemlátomást kevés hely van nálad. Elmegyek a Mamához. Rég nem voltam már náluk. Majd nézz arra, ha lenne még kiadó hely a csapatodban.}
{840}{vic33}{Ed Menedékvárosban lakik. Brahminkereskedõ. A számos ellátóim egyike volt. Menedékváros nincs messze innen.}
{845}{vic34}{Mondtam... itt van, ni! [Vic rámutat egy helyre a PipBoyodon.]}
{900}{}{Megtudtad, hogy Vic kereskedõ.}
{1000}{}{Meg kell kérdeznem valamit.}
{1100}{vic35}{Teljesen fel vagyok gyógyulva, fõnök. Egyéb teendõ?}
{1200}{vic36}{Majdnem tökéletes formában vagyok, fõnök.}
{1300}{vic37}{Nagyjából be vannak kötözve a sebeim, fõnök, de voltam már jobban is.}
{1400}{vic38}{Próbáltam, fõnök, de nem eszik olyan forrón a kását! Megteszek minden tõlem telhetõt.}
{1500}{vic39}{Ahogy parancsolja, kedves fõnök!}
{1501}{vic40}{Itt? Pont itt? Rendben, te vagy a fõnök.}
{1502}{vic41}{Oké. Itt maradok, amíg vissza nem jössz, fõnök. Ugye vissza fogsz jönni?}
{1503}{vic42}{Ameddig csak akarod. Én egy tapodtat sem mozdulok innen!}
{1504}{vic43}{Természetesen, fõnök!}
{1600}{vic44}{Ha te mondod...}
{1601}{vic45}{Jó beszólás, fõnök!}
{1602}{vic46}{Nagy ötlet, fõnök!}
{1603}{vic47}{Naná, fõnök! Más egyéb?}
{1604}{vic48}{Messze van, fõnök!}
{1605}{vic49}{Nem gond, fõnök!}
{1606}{vic50}{Kész, fõnök!}
{1700}{vic51}{Naná, fõnök!}
{1701}{vic52}{Közel van, fõnök!}
{1702}{vic53}{Te tudod a legjobban, fõnök.}
{1703}{vic54}{Mögötted vagyok, fõnök!}
{1704}{vic55}{Tapadok, mint a pióca, fõnök!}
{1705}{vic56}{Ha így akarod, fõnök.}
{1706}{vic57}{Óh! Okés, fõnök!}
{1800}{vic58}{Rendben, tartok némi távolságot, de nem megyek túl messzire, fõnök!}
{1801}{vic59}{Oké, nem fogok, fõnök.}
{1802}{vic60}{Akkor egy kicsit lemaradok, fõnök.}
{1803}{vic61}{Naná, fõnök!}
{1900}{vic62}{Jól van, fõnök! Kicsit lemaradok.}
{1901}{vic63}{Ahogy parancsolja, kedves fõnök!}
{1902}{vic64}{Te mész elõl, fõnök.}
{1903}{vic65}{Lemaradok, fõnök.}
{1904}{vic66}{Hátrébb megyek, fõnök.}
{1905}{vic67}{Arrébb húzódok, fõnök!}
{1906}{vic68}{Okés, fõnök!}
{2000}{vic69}{Ööhm... fõnök? Egy kicsit sokan vagyunk. Itt maradok, és várok rád.}
{2100}{}{Megrémisztesz, fõnök! Mi történt veled? Olyan... izé, ijesztõen nézel ki. Asszem, itt maradok egy ideig...}
{2200}{vic70}{Kétségtelen, fõnök!}
{2201}{vic71}{Állatira rendben lesz, fõnök!}
{2202}{vic72}{Tutira, fõnök!}
{2203}{vic73}{Amint kész vagy, én is kész vagyok, fõnök!}
{2204}{vic74}{Nagyszerû! Menjünk!}
{2205}{vic75}{Nagyszerû!}
{2206}{vic76}{Te vagy a legjobb, fõnök!}
{2207}{vic77}{Nem leszel többé csalódott. Nem lesz itt több hiba!}
{2208}{vic78}{Ezúttal óvatosabb leszek, ne aggódj!}
{2209}{vic79}{Tudtam, hogy meg fogsz bocsátani nekem ezért... Ööhm. Na, akkor ööö... fõnök. Mi a terv?}
{2210}{vic80}{Nem engedlek meghalni, fõnök!}
{2211}{vic81}{Szuper vagy, fõnök!}
{2212}{vic82}{Tudtam, hogy annyira öreg azért nem vagyok még ehhez. Csak kicsi volt a valószínûsége! Ugye, fõnök?}
{2300}{}{Ed-tõl. A fickó brahminokkal kereskedik Menedékvárosban. Jártál már arra? Hadd mutatassam meg azon a térkép-izéden!}
{2305}{vic199}{Menedékvárosban. Itt! Hadd mutassam meg azon az aranyos térkép-micsodádon!}
{2310}{vic84}{Neki valahol itt kell lennie.}
{2311}{vic85}{Menedékvárosban. Nézd meg azon a térkép-bigyón!}
{2403}{}{Hol szerezted a 13-as Menedék kulacsát?}
{2404}{}{Rá se ránts!}
{2500}{vic86}{Naná, fõnök!}
{2501}{vic87}{Kérdezz bármit, fõnök!}
{2502}{vic88}{Segítek, ha tudok, fõnök!}
{2503}{vic89}{Ugye nem vagyok bajban, fõnök?}
{2504}{vic90}{Valamit rosszul csináltam, fõnök?}
{2505}{vic91}{Természetesen.}
{2600}{vic92}{Most mit fogunk csinálni, fõnök?}
{2601}{vic93}{Mi a terv, fõnök?}
{2602}{vic94}{A legjobbat próbálom kihozni magamból, fõnök!}
{2603}{vic95}{Mit tehetek érted, fõnök?}
{2604}{vic96}{Változik a terv, fõnök?}
{2605}{vic97}{Más stratégia, fõnök?}
{2700}{}{Elég jól ellátták a bajom, fõnök! Szerezned kell nekem egy orvost! Nem tudom, hogy valaha tudok-e még segíteni neked...}
{2701}{}{Orvosra van szükségem, fõnök! Elég rosszul nézek ki. Nem tudom, hogy valaha tudok-e még harcolni az oldaladon.}
{2702}{vic100}{Szépen tropára mentem, fõnök! El kell vinned Lennyhez, hogy meg tudjon vizsgálni.}
{2800}{vic101}{Hé, fõnök! Azt akarod, hogy csatlakozzam hozzád most?}
{2801}{vic102}{Hé, fõnök! Nem okoz gondot, hogy várni kell rád. Nagyon türelmes ember vagyok.}
{2802}{vic103}{Újra együtt fogunk nyomulni, fõnök? Sokkal jobban fogok vigyázni.}
{2803}{vic104}{Féltem, hogy esetleg sosem fogsz visszajönni. Örülök, hogy újra látlak, fõnök!}
{2804}{vic105}{Megint szükséged van rám?}
{2805}{vic106}{Készen állok, fõnök!}
{2806}{vic107}{Tudtam, hogy nem hagysz el!}
{2807}{vic108}{Kell némi erõsítés?}
{2808}{vic109}{Ugye valamit meg kellene bütykölni? Én vagyok a te embered, fõnök!}
{2809}{vic110}{Ne aggódj, fõnök! Sulik és én nagyon jól ki fogunk jönni egymással.}
{2810}{vic200}{Gyerünk!}
{2811}{vic201}{Maradj itt! Mindjárt jövök.}
{2812}{vic202}{Megyek.}
{3100}{vic111}{Mi? Ööhm. Rendben, fõnök! Ha egyszer ezt mondtad...}
{3101}{vic112}{Felvehetnék valami mást, fõnök? Egy kicsikét aggódom.}
{3102}{vic113}{Okés! Nem fogsz engem itthagyni... Ugye, fõnök?}
{3103}{vic114}{De... Értem... Természetesen, fõnök! Leszakadok.}
{3200}{vic115}{Nos, fõnök... Elég tûrhetõen bánok a kisebb fegyverekkel. Tudok lõni szinte bármilyen puskával, sörétessel, és a legtöbb kis-közepes méretû pisztollyal is. Jól "forgatom" a késeket is. Ezen kívül jól tudok dobni, de célozni már nem annyira... Mondjuk úgy, rettenetesen. Nézd el nekem, fõnök! Én tényleg a legjobbat próbálom kihozni magamból.}
{3201}{vic116}{Ahogy már mondtam, fõnök, a kisebb fegyverek kezelésében vagyok leginkább járatos. Rengeteg puskát ismerek - köztük a sörétest is - , a kis és közepes méretû pisztolyok többsége sem okoz gondot. Ha nagyon bajban lennénk, akár a kés vagy egyéb fegyverek dobásával is megpróbálkoznék.}
{3300}{vic203}{Alap szinten bánok a késekkel és nagyon jól tudok dobni. Mondjuk nem vagyok túl jó célzó. Igazság szerint elég szörnyû. Bocsáss meg, fõnök! Minden erõmmel azon vagyok, hogy fejlesszem magam.}
{3301}{vic204}{Mint már említettem, fõnök, forgatom a késeket is és nagyon jól tudok dobni... Csak egy picikét félre...}
{3400}{vic122}{Na, eddig a pontig bírtam!}
{3401}{vic123}{Letépem azt a tetves fejedet! Senki sem bánthajta a családomat!}
{4000}{vic124}{Inkább ide?}
{4001}{vic125}{Jobb így, fõnök?}
{4002}{vic126}{Ez a hely megfelel?}
{4003}{vic127}{Igen, fõnök!}
{4004}{vic128}{Hogy mondod?}
{4005}{vic129}{Hova megyünk?}
{4006}{vic130}{Indulunk, fõnök?}
{4007}{vic131}{Már megyek is!}
{4008}{vic132}{Bocsánat, fõnök!}
{4009}{vic133}{Így jobb?}
{4010}{vic134}{Úúuuuf!}
{4011}{vic135}{Így jó lesz, fõnök?}
{4012}{vic136}{Akkor most ideállok.}
{4013}{vic137}{Na, akkor arrébbállok szépen.}
{4100}{vic138}{Fõnök! Nem érzem valami jól magam.}
{4101}{vic139}{Szükségem van egy orvosra!}
{4102}{vic140}{Ó, ember! Ez tényleg fáj!}
{4103}{vic141}{Ááá!}
{4104}{vic142}{Jaj!}
{4105}{vic143}{Francba!}
{4106}{vic144}{Orvost!}
{4107}{vic145}{Még elvagyok... de már csak alig...}
{4200}{vic146}{Soha nem szerettem ezt a helyet.}
{4201}{vic147}{Miért ilyen tiszta ez a hely?}
{4202}{vic148}{Nem érzel valami szagot, fõnök?}
{4203}{vic149}{Te tudod, fõnök. Nem hiszem, hogy miután elmentünk innen, valaha is visszajönnék ide. Már nem érzem az otthonomnak.}
{4204}{vic150}{Határozottabban mocskosabb, mint amire emlékeztem.}
{4205}{vic151}{Ugye nem maradunk itt sokáig, fõnök?}
{4206}{vic152}{Ez a hely sosem fog megváltozni.}
{4207}{vic153}{Nem fogom hiányolni ezt a helyet, fõnök.}
{4208}{vic154}{Még egyszer kösz, hogy kihoztál onnan, fõnök!}
{4209}{vic155}{Valóban jövök neked egyel, fõnök!}
{4210}{vic156}{Nem semmi, ez a hely nagyon megváltozott.}
{4211}{vic157}{Már évek óta nem jártam itt.}
{4212}{vic158}{Itt fogok nyugdíjba menni.}
{4213}{vic159}{Nyithatnék itt egy szerelõmûhelyt.}
{4300}{vic160}{Íme, a lakhelyek lakhelye. Ez volt az én kis házikóm, de erre nyilván már magad is rájöttél. Ugye, fõnök?}
{4400}{vic161}{Sulik, ne nézz így rám!}
{4401}{vic162}{Fõnök, Sulik már megint engem bámul!}
{4402}{vic163}{Aranyos kutyus.}
{4500}{vic164}{Trallala}
{4501}{vic165}{Hm-hm.}
{4502}{vic166}{Várom a fõnököt...}
{4503}{vic167}{Várom a fõnökömet.}
{4504}{vic168}{Csak várok.}
{4505}{vic169}{A fõnök tuti nem hagyna el...}
{4506}{vic170}{Kopp-kopp, ki van ott? Várj! Hogy is...}
{4507}{vic171}{Még várok.}
{4508}{vic172}{Mi ez a szag?}
{4509}{vic173}{Van itt valami javítanivaló?}
{4510}{vic174}{Itt vagyok! Várok a fõnökre.}
{4511}{vic175}{Egy magamfajta vénember csak elpazarolja a tehetségét a céltalan álldogálással.}
{4512}{vic176}{Bárcsak lenne egy gumi nálam... már az idejét sem tudom, mikor voltam nõvel...}
{4513}{vic177}{Ki kellene szállnom az ereklyeüzletbõl... Csak a gond van vele.}
{4514}{vic178}{Miért ilyen fárasztó a várakozás...?}
{4600}{vic179}{Üühm, kösz, fõnök!}
{4601}{vic180}{Kösz.}
{4602}{vic181}{Biztosan tudod, mit csinálsz?}
{4603}{vic182}{Egyszerûen nem pihenhetnénk helyette?}
{4604}{vic183}{Ne üssünk tábort?}
{4605}{vic184}{Ennyire rosszul lennék?}
{4700}{vic185}{Ne sokat, fõnök!}
{4701}{vic186}{Ha ragaszkodsz hozzá, fõnök...}
{4702}{vic187}{Fõnök, ugye nem fog szétrobbani a fejem?}
{4703}{vic188}{Fõnök, van egy olyan érzésem, hogy kezdem megkedvelni ezt a vackot.}
{4704}{vic189}{Egy kicsit mókásan érzem magam, fõnök.}
{4705}{vic190}{Látom, van elég nálad.}
{4706}{vic191}{Hogyne, fõnök! Beadom magamnak.}
{4707}{vic192}{Kösz, fõnök!}
{4708}{vic193}{Nem vészes.}
{5000}{vic194}{Kezdek éhes lenni. Késõbb beszélünk Mamánál.}
{5500}{vic195}{Úgy érzem mintha eltörtem volna egy végtagomat Fõnök. Jobb lenne, ha vetnél rá egy pillantást.}
{5501}{vic196}{Ógy érzem mintha lázam lenne Fõnök. Jobb lenne ha vetnél rá egy pilantást.}
{5502}{vic197}{Úgy érzem magam mintha megmérgeztek volna Fõnök. Jobb lenne, ha megvizsgálnál.}
