{100}{}{Ez az ember erõpáncélt visel.}
{101}{}{Arthur, Uther Pendragon fia.}
{102}{}{Lenn van a slicce...}
{103}{arth1}{Üdv néktek, utazók! Arthur vagyok, Uther Pendragon fia, az Acél Testvériségének tagja. A Szent Antiókiai Kézigránát nyomában járunk. Láttátok vala?}
{104}{}{A szent miatúrót keresed?}
{105}{}{Játékos Válasza}
{106}{}{Unga.}
{107}{arth13}{Nincs idõ a beszédre! Szent küldetésben járunk.}
{108}{arth14}{A Szent Antiókiai Kézigránát nyomában járunk.}
{109}{arth15}{Az Acél Testvérisége számára!}
{110}{arth16}{Hmm... Afrikai vagy Európai fecske?}
{111}{arth17}{Hékás! Az nem a tied ám!}
{112}{arth18}{Figyelmeztetlek! Csak semmi meggondolatlan mozdulat!}
{113}{arth19}{Na, ami sok az sok!}
{114}{arth2}{A Szent Antiókiai Kézigránát a létezõ legjobb kézbõl használatos, élõerõt pusztító harci eszköz a maga nemében.}
{115}{}{Miért keresitek ezt a szörnyû fegyvert?}
{116}{arth3}{Mi, az Acél Testvériségének tagjai azt a célt tûztük ki magunk elé, hogy megleljük õseink leghatásosabb fegyverét és eltüntetjük azok elõl, akik csak visszaélnének az Antiókiai Szent Kézigránát erejével.}
{117}{}{Miért?}
{118}{arth4}{Hát... azért mert az Acél Testvériségének az a dolga, hogy a gyengéket és védteleneket oltalmazza, és az a vacak könnyen megsebesíthet valakit.}
{119}{}{Miért?}
{120}{arth5}{Ööö... mert ezt diktálja a jó erkölcs.}
{121}{}{Miért?}
{122}{arth6}{Min... öö... na figyelj ide, nekünk sok dolgunk van. Akarsz segíteni, avagy sem? Láttad az Antiókiai Szent Kézigránátot, avagy sem?}
{123}{}{Igen.}
{124}{}{Nem.}
{125}{arth7}{Akkor miért nem ezzel kezdted? Ha elmondod, merre van, itthagyunk, és mehetsz a dolgodra!}
{126}{}{[A hasadra ütsz, és elmutatsz valamerre...]}
{127}{arth8}{Jól van. Köszönjük a segítséget. Itt van valami a segítségért...}
{128}{}{Várjatok! Én is egy küldetést teljesítek. A szent ÉLET-et keresem. Láttátok valahol?}
{129}{arth9}{Na, jó, nincs sok értelme, hogy folytassuk ezt a beszélgetést. Útnak indulunk.}
{130}{}{[Befejezés]}
{131}{arth10}{Mocskos paraszt!}
{132}{}{[Befejezés]}
{133}{arth11}{ÉLET-et mondtál? Ami azt illeti, van itt nálunk kettõ, egy harmadik már fölösleges lenne. Amúgy köszönjük.}
{134}{}{Hát, ha már kettõ van nektek, az egyiket akár oda is adhatnátok.}
{135}{arth12}{Nem-nem. Ez lehetetlen. Ilyen könnyen azért nem fogod befejezni a küldetésed. Van még épp elég, szerezz egyet magadnak! [Ugyanabba az irányba mutat, amerre az útmutatásod szerint az Antiókiai Szent Kézigránát található.]}
{136}{}{[Befejezés]}
{200}{arth20}{Beszélsz a király nyelvén?}
{201}{arth21}{Hellóóó.}
{202}{arth22}{Hé, itt vagyok!}
{203}{arth23}{Ha egy pillanatra zavarhatnálak...}
{204}{arth24}{Ahem.}
{205}{arth25}{Ugyan már, ne nézz már át rajtam, mint a kirakaton!}
{206}{arth26}{Légysziiii! Valami nagyon fontosat kell kérdeznem.}
{207}{arth27}{Az a helyzet, hogy folytatnunk kell a kutatást az Antiókiai Szent kézigránát nyomában. Jer, Balfi!}
{300}{}{Our quest has been fulfilled!}
{301}{}{Arthur, at your service.}
