{100}{}{Ez a kutya naggggggyon ádáz fajta.}
{101}{}{Dogmeat.}
{102}{}{Dogmeat.}
{103}{dogmt1}{Amikor a kutya meglátja a Menedék kezeslábasát, szûkölni kezd. Úgy tûnik, melléd akar szegõdni.}
{104}{}{[Füttyentesz]}
{105}{}{Talán jöhetel velem, ha lenni több hej csapatba'.}
{106}{}{Nem-nem, kutyuli. Maradol!}
{107}{}{Gyerünk, komám! Itt az idõ, hogy szétcsapjunk azok közt, akik megérdemlik!}
{108}{}{Te csak ne aggódj, koma! Amint lesz hely a csapatban, visszajövök érted.}
{109}{}{Bocsesz, Dogmeat. Most nem lehet.}
{110}{dogmt2}{A kutya torkos módon bekebelezi a nyársas iguanát, utána várakozóan néz rád...}
{111}{}{[Füttyentesz]}
{112}{}{Talán jöhetel velem, ha lenni több hej csapatba'.}
{113}{}{Nem-nem, kutyuli. Maradol!}
{114}{}{Gyerünk, komám! Itt az idõ, hogy szétcsapjunk azok közt, akik megérdemlik!}
{115}{}{Te csak ne aggódj, koma! Amint lesz hely a csapatban, visszajövök érted.}
{116}{}{Bocsesz, Dogmeat. Most nem lehet.}
{117}{dogmt3}{Ez a kutya naggggggyon ádáz fajta.}
{118}{}{[Füttyentesz]}
{119}{}{Talán jöhetel velem, ha lenni több hej csapatba'.}
{120}{}{Maradol, kutyuli, ne mozdujj!}
{121}{}{[Továbbállsz]}
{122}{}{Gyerünk, komám! Itt az idõ, hogy szétcsapjunk azok közt, akik megérdemlik!}
{123}{}{Visszajövök érted, amint lesz hely a csapatomban.}
{124}{}{Ragadj rám! Értesz engem?}
{125}{}{Tarts közepes távolságot, Dogmeat!}
{126}{}{Maradj hátrébb, Dogmeat! Fedezz engem!}
{127}{}{Itt maradsz, Dogmeat! Itt maradsz!}
{128}{}{Azt hiszem, most békén hagyom Dogmeatet.}
{129}{dogmt4}{Dogmeat hangosan felvakkant, aztán morogni kezd.}
{130}{}{Ragadj rám! Értesz engem?}
{131}{}{Tarts közepes távolságot, Dogmeat!}
{132}{}{Maradj hátrébb, Dogmeat! Fedezz engem!}
{133}{}{Itt maradsz, Dogmeat! Itt maradsz!}
{134}{}{Köszi, Dogmeat! Király vagy!}
{135}{dogmt5}{Vaúúúúúúúúúúú...}
{136}{dogmt11}{Vaúúúúúúúúúúú...}
{137}{}{Hela, ne csesztesd a kutyámat!}
{138}{dogmt7}{Grrrrr....}
{139}{}{(Kiváncsi vagyok, rá tudnám-e venni Dogmeatet, hogy máshogy kövessen?)}
{150}{dogmt8}{Vaú! Vaú!}
{200}{}{Here boy, I got something for you! Let's see somebody mess with you now! (You place the K-9 Kevlar on Dogmeat.)}
{201}{}{Is the armor weighting you down, boy? Here, let's take that thing off. (You remove the K-9 Kevlar from Dogmeat.) }
{300}{dogmt9}{*nyüszít*}
{301}{dogmt10}{Vaúúúúúúúúúúú... *nyüszít*}
{1110}{dogmt6}{A kutya torkos módon bekebelezi a kutyakaja konzervet, utána várakozóan néz rád...}
