{100}{}{Egy férfit látsz harci páncélban.}
{101}{}{Kagát látod harci páncélban.}
{102}{}{Harci páncélt visel, és úgy tûnik, néhány egész tûrhetõ fegyvere is van.}
{103}{kaga33}{Ez alkalommal felkészültem rád.}
{104}{kaga34}{A Kiválasztott sosem tér vissza Arroyóba!}
{105}{kaga35}{Kaga porrá zúz téged!}
{106}{kaga36}{Kaga nem fél senkitõl!}
{107}{kaga37}{Maradj mozdulatlan, hogy Kaga pontosan célozhasson!}
{108}{kaga38}{Még találkozunk!}
{109}{kaga39}{Ez nem az utolsó alkalom, hogy láttad Kagát.}
{110}{kaga40}{Kagának határozottan több gyakorlásra van szüksége...}
{120}{}{Go away Kaga!}
{150}{kaga1}{[A tall and powerfully built warrior stands before you, his eyes blaze with hatred as he looks you over.] So, they cast out Kaga, then deem YOU the Chosen One? Ha! You think being the grandchild of the Vault Dweller makes you special?! You think you are better than I, Kaga the Great?!}
{151}{}{Well, I AM the Chosen One, aren't I?}
{152}{}{Hey now, hold on a second. I never said I was better than you.}
{160}{kaga2}{That title will mean nothing when Kaga rips the head from your shoulders!}
{161}{kaga3}{No words can save your hide. With your death, Kaga's honor shall be restored. Kaga will now take his vengeance!}
{200}{}{Ooglie?}
{201}{kaga4}{What!? They picked *you* to be the Chosen One? Oh my, they've become desperate.}
{202}{}{Me no likie. U lookie bad.}
{203}{kaga5}{Kaga won't even bother speaking with you further. Prepare to die at the hands of Kaga!}
