{100}{}{Egy alig felöltözött férfit látsz.}
{101}{}{Kaga.}
{103}{}{Az illetõ ágyékkötõt visel, és úgy néz ki, mintha valami törzs tagja lenne.}
{104}{kaga6}{Nekem kéne a Kiválasztottnak lennem!}
{105}{kaga7}{Hogy mert elûzni engem Arroyo a törzsbõl?!}
{106}{kaga8}{Most megbosszulom!}
{107}{kaga9}{Kaga a következõ életbe küld téged.}
{108}{kaga10}{Még találkozunk!}
{109}{kaga11}{Még soha nem gyõztek le!}
{110}{kaga12}{Az elpuszításodnak szentelem az életem!}
{150}{kaga1}{[A tall and powerfully built warrior stands before you, his eyes blaze with hatred as he looks you over.] So, they cast out Kaga, then deem YOU the Chosen One? Ha! You think being the grandchild of the Vault Dweller makes you special?! You think you are better than I, Kaga the Great?!}
{151}{}{Well, I AM the Chosen One, aren't I?}
{152}{}{Hey now, hold on a second. I never said I was better than you.}
{160}{kaga2}{That title will mean nothing when Kaga rips the head from your shoulders!}
{161}{kaga3}{No words can save your hide. With your death, Kaga's honor shall be restored. Kaga will now take his vengeance!}
{200}{}{Ooglie?}
{201}{kaga4}{What!? They picked *you* to be the Chosen One? Oh my, they've become desperate.}
{202}{}{Me no likie. U lookie bad.}
{203}{kaga5}{Kaga won't even bother speaking with you further. Prepare to die at the hands of Kaga!}
