{100}{}{Egy fémpáncélt viselõ férfit látsz.}
{101}{}{Kaga.}
{102}{}{Egen, ez Kaga, a nem-is-annyira-nagy. Fémpáncélja van, és bizony éppen meg akar ölni téged.}
{103}{kaga24}{Megint te vagy?}
{104}{kaga25}{Kezdek belefáradni, hogy állandóan találkozunk.}
{105}{kaga26}{Kiválasztott... hogy oda ne rohanjak!}
{106}{kaga27}{Vessünk véget ennek!}
{107}{kaga28}{Meg fogod bánni, hogy hallottad Kaga nevét!}
{108}{kaga29}{Utolsó találkozásunk óta gyarapodtak a képességeim.}
{109}{kaga30}{Ez most már kezd rossz szokássá válni.}
{110}{kaga31}{Kagának még egy kis gyakorlásra van szüksége.}
{111}{kaga32}{Kaga visszatér még...}
{120}{}{So we meet again, Kaga.}
{150}{kaga1}{[A tall and powerfully built warrior stands before you, his eyes blaze with hatred as he looks you over.] So, they cast out Kaga, then deem YOU the Chosen One? Ha! You think being the grandchild of the Vault Dweller makes you special?! You think you are better than I, Kaga the Great?!}
{151}{}{Well, I AM the Chosen One, aren't I?}
{152}{}{Hey now, hold on a second. I never said I was better than you.}
{160}{kaga2}{That title will mean nothing when Kaga rips the head from your shoulders!}
{161}{kaga3}{No words can save your hide. With your death, Kaga's honor shall be restored. Kaga will now take his vengeance!}
{200}{}{Ooglie?}
{201}{kaga4}{What!? They picked *you* to be the Chosen One? Oh my, they've become desperate.}
{202}{}{Me no likie. U lookie bad.}
{203}{kaga5}{Kaga won't even bother speaking with you further. Prepare to die at the hands of Kaga!}
