{100}{}{Ez itt egy punk srác mosolynak is nevezhetõ arckifejezéssel.}
{101}{}{Õ Borz.}
{102}{}{Ez itt egy punk srác, arcán olyasféle arckifejezéssel, amit akár kaján mosolynak is nevezhetnénk.}
{103}{badge1}{::Hangosan böfög::: Mit akarsz?}
{104}{}{::Böfögsz::}
{105}{}{Te vagyol ki?}
{106}{}{Ki vagy?}
{107}{}{Tudnál mondani valamit errõl a tankerrõl!}
{108}{}{Mit csinálsz itt?}
{109}{}{Szeretném, ha meghekkelnéd nekem a számítógépet.}
{110}{}{Hogy halad a hekkelés?}
{111}{}{Semmit. Jó büfizést!}
{112}{badge2}{::Megereszt egy újabb öblös büffentést::}
{113}{}{::Még hangosabban büfögsz::}
{114}{}{Picsába.}
{115}{badge3}{::Olyan éktelen nagyot büfög, hogy égzengésnek is beillene::}
{116}{}{::Megtapsolod::}
{117}{badge4}{Borz vagyok. Volt egy zenekarom... ::felsóhajt:: Az volt a nevünk, hogy "Elégtünk". Most én vagyok az ügyeletes számítógép buherátor San Franban.}
{118}{}{Ah, köszi!}
{119}{}{Miket tudsz varázsolni a számítógéppel?}
{120}{}{Gondolom befuccsoltatok a bandával.}
{121}{}{Jó volt az a zenekar?}
{122}{}{Köszönöm. Viszlát!}
{123}{badge5}{Ööö... oké.}
{124}{}{Üdv!}
{125}{badge6}{Ezügyben beszélj Marc-kal vagy a Kapitánnyal!}
{126}{}{Hol találom Marcot?}
{127}{}{Hol találom a kapitányt?}
{128}{badge7}{Én vagyok a helyi számítógép-zseni.}
{129}{}{Miket tudsz varázsolni a számítógéppel?}
{130}{}{Köszönöm. Viszlát!}
{131}{badge37}{Ne basztass már... ::Fingik egyet:: Dolgozom rajta, ha nem látnád!}
{132}{}{Jól van, jól van. Majd szólj, ha kész van!}
{133}{badge8}{Hát mondjuk úgy, hogy én egy információszerzõ specialista vagyok.}
{134}{}{Tudnál nekem is szerezni dolgokat?}
{135}{}{Hova akarsz kilyukadni?}
{136}{badge9}{Hát akkor baszódj meg!}
{137}{}{Hé!}
{138}{}{Baszódj meg te!}
{139}{badge10}{Hát jobb, ha tudod, hogy királyok voltunk! Az énekesünk... ööö... egy kicsit ripacs volt, Aaron folyton problémázott, minden egyebet meg Todd szúrt el. Ennek ellenére jók voltunk.}
{140}{}{Kár, hogy már nem játszotok együtt. Szívesen meghallgattalak volna titeket.}
{141}{}{Öö. Hogyne. Hadd kérdezzek valamit.}
{142}{}{Fogadjunk, befuccsoltatok.}
{143}{badge11}{Marc rendszerint lenn a bárban múlatja az idõt.}
{144}{}{Köszönöm. Volna még néhány kérdésem.}
{145}{}{Köszi. Ez minden.}
{146}{badge12}{A Kapitány általában a hídon tartózkodik. A bárból feljuthatsz a lépcsõn.}
{147}{}{Köszönöm. Volna még néhány kérdésem.}
{148}{}{Köszi. Ez minden.}
{149}{badge13}{Oké, de ezért a zsebedbe kell nyúlnod.}
{150}{}{Mennyit kérsz?}
{151}{}{Igen, hogyne... de most mennem kell.}
{152}{badge14}{Ez azt jelenti, hogy ha adatokat akarsz felkutatni, én vagyok a te embered.}
{153}{}{Megcsinálnál nekem valamit?}
{154}{}{Értem. Ez király. Még kérdeznék valamit, ha nem zavar.}
{155}{}{Értem. Köszi.}
{156}{badge15}{Igen, kéne. Egyébként vissza kell térnem ehhez a vacakhoz.}
{157}{}{Várj! Még akarok kérdezni valamit.}
{158}{}{Köszi. Viszlát!}
{159}{badge16}{Szerintem vagyunk annyira jóban, hogy segítsek neked. Kit látogassak meg?}
{160}{}{A Hubologistákat.}
{161}{}{A Shiket.}
{162}{}{Senkit. Csak tájékozódom.}
{163}{badge17}{Asszem, amiért megmentetted a csajomat, ingyen megcsinálom. Persze eltart majd egy darabig. Hova törjek be neked?}
{164}{}{A Hubologistákat.}
{165}{}{A Shiket.}
{166}{}{Senkit. Csak tájékozódom.}
{167}{badge18}{Elõször is tégy nekem egy szívességet! A barátnõmnek nyoma veszett a tankerben. Találd meg nekem és akkor megcsinálom.}
{168}{}{Megegyeztünk. Üdv!}
{169}{}{Ne is álmodj róla! Üdv!}
{170}{badge19}{Ez olyan, mint cukorkát lopni egy kisgyerektõl. Sosem fognak megtalálni. Mit akarsz tõlük?}
{171}{}{Nagyszerû! Viszont lenne még néhány kérdésem.}
{172}{}{Nagyszerû! Késõbb visszajövök.}
{173}{badge20}{El tudom érni õket. Az infó szerint elégé védettek, a gépeiket komoly J.É.G. védi. Teljesen biztos vagy abban, hogy igényled a segítségemet ez ügyben?}
{174}{}{Akkor jó szerencsét! Ellenben kérdeznék egy-két dolgot.}
{175}{}{Jó szerencsét! Késõbb visszajövök.}
{176}{badge21}{Találd meg nekem a barátnõmet és akkor majd beszélgethetünk.}
{177}{}{Elnézést, csupán félreértés volt.}
{178}{badge22}{Meghalt? MEGHALT? Hogy halt meg? Ne, inkább mégse mondd el... tartsd meg magadnak! Adj néhány órát, hogy összeszedjem magam.}
{179}{}{Hogyne, hogyne.}
{180}{}{Ne durcáskodj már, öcsém! Csomó dolgunk van, vazze!}
{181}{badge23}{Rendben. Már jobban vagyok.}
{182}{}{Jó. Meg kell, hogy kérdezzek valamit.}
{183}{}{Na, tessék. Én nem akartam veled beszélni.}
{184}{badge24}{Köszönöm, köszönöm, köszönöm. Nem tudom eléggé megköszönni, hogy megmentetted õt. Miben segíthetek?}
{185}{}{Volna néhány kérdésem.}
{186}{}{A hálád elég nekem. Viszlát!}
{187}{badge25}{Oké, behatoltam a Shi számítógépekbe. Nem tudom, észrevettek-e. Szerintem most a legjobb az lesz, ha meghúzzuk magunkat. Egyéb teendõ?}
{188}{}{Igen.}
{189}{}{Nincs. Üdv!}
{190}{badge26}{Megfogtam a Hubologistákat. Nem ügy. Segíthetek bármi egyébben?}
{191}{}{Igen.}
{192}{}{Nincs. Üdv!}
{193}{badge27}{Nagy hibát követtél el, haver! A számítógépeken keresztül a Shiket és a Hubologistákat is neked ugrasztottam. Neked véged van, mint a botnak San-Franciscóban.}
{194}{}{Hát, akkor asszem, most megöllek.}
{195}{badge28}{Adj néhány órát, hogy összeszedhessem magam!}
{196}{badge29}{Egy formázott számítógépbe hatoljak be? Az információnak már annyi. Rá nem veszel erre.}
{197}{badge38}{Elhagyom ezt a helyet.}
{198}{badge39}{Jó, hogy látlak.}
{199}{}{Üzemanyag után hajkurászok.}
{200}{badge30}{Úgy hallottam, a Hubologistáknak van üzemanyaguk, esetlek ránézhetek a számítógépükre.}
{201}{badge31}{Az összes üzemanyagot a Shik birtokolják nálunk. Ha akarod, rákukkanthatok neked a számítógépükre.}
{202}{}{Megtennéd?}
{203}{badge40}{Mi a fenét akarsz?}
{204}{}{Borzot, a punk-ot, szerintem.}
{205}{}{Megszégyenítetted az Uralkodónkat!}
{206}{badge41}{Asszem, megyek cukorkáért Lao Chouhoz a városba.}
{207}{}{Ennyit a tisztességes tárgyalásról. Hmmm...}
{208}{badge42}{Haver, fogd vissza magad! Én csak egy kis cukorkát szerettem volna.}
{209}{}{Át tudnád irányítani az üzemanyagot az ûrhajóból a tankerbe?}
{210}{}{Tudnál szerezni egy példányt a gépmadár terveibõl?}
{211}{}{Át tudnád irányítani az üzemanyagot és mellé meg tudod szerezni nekem a terveket?}
{212}{}{Igen, szükségem van a dolgaikra.}
{213}{}{Na, mindegy, majd valahogy megoldom.}
{214}{badge32}{Jó-jó, de szar kerülhet a palacsintába.}
{215}{}{Át tudnád irányítani az üzemanyagot a tartályokból a tankerbe?}
{216}{}{Na, sebaj, majd máshogy megoldom.}
{217}{}{Rá se ránts!}
{218}{badge33}{Rendben. Kábé egy napon belül gyere vissza és megbeszéljük.}
{219}{}{Megszerezted, amit kértem?}
{220}{badge34}{Igen, megvan az üzemanyag.}
{221}{badge35}{Igen, megvan a gépmadár terve.}
{222}{badge36}{Igen, megvannak a tervek meg az üzemanyag is.}
{223}{}{Nagyon szépen köszönöm. Még látjuk egymást.}
