{100}{}{Ez itt egy kopasz punk.}
{101}{}{Õ Chip. Már sokkal jobban néz ki.}
{102}{}{Ez itt egy kopasz punk. Egész tûrhetõen rendbejött.}
{103}{chip1}{Ó, a belem... aj, aj, aj,..}
{104}{}{Velem?}
{105}{}{Baj?}
{106}{}{Mi bajod van?}
{107}{}{Fáj valami? Ha ha ha.}
{108}{}{Ki vagy?}
{109}{}{Tudsz valamit a népemrõl?}
{110}{chip2}{Jaj, a belem! Fájdalmaim vannak. Légyszi, hagyj békén!}
{111}{}{Oki-doki.}
{112}{chip3}{Hogy mi van velem? Megmondom én. Az a bajom, hogy a múlt héten leittam magam, kártyázni kezdtem Lao Chouval és vesztettem. Annyira segg részeg voltam, hogy a lépemet tettem meg tétnek. Elnyerte tõlem, de már nagyon kéne vissza.}
{113}{}{Te ELJÁTSZOTTAD a lépedet?}
{114}{}{Hát ez szar ügy.}
{115}{}{De nagy marha vagy!}
{116}{}{Namost nekem információk kellenének, a hasfájásod kevéssé érdekel.}
{117}{chip4}{::Levegõért kapkod:: Baszódj meg!}
{118}{chip5}{::Levegõért kapkod:: Húzz a francba!}
{119}{}{Persze, persze.}
{120}{}{Hé, meggondoltam magam. Segítek, ha akarod.}
{121}{chip6}{Igen, pénzzé tettem. Részeg voltam! Ráadásul szerintem Lao Chou egy kis Jetet csempészett az italomba. Kéne vissza a lépem, mert egyre több betegséget kapok el.}
{122}{}{Hát ha elveszítetted, az a te bajod. Élj együtt a problémával!}
{123}{}{Hát a franc ott essen bele, utánanézek neked!}
{124}{chip7}{Így van. Vissza kéne kapnom a lépem, mert egyre több betegséget kapok el.}
{125}{}{Hát ha elveszítetted, az a te bajod. Élj együtt a problémával!}
{126}{}{Hát a franc ott essen bele, utánanézek neked!}
{127}{chip8}{Ez nagyon rendes tõled. Beszélj Lao Chouval, a kereskedõvel, és mondd meg neki, hogy most már ideje lenne visszakapnom a lépemet.}
{128}{}{Még visszatérek.}
{129}{chip9}{Chip vagyok. Mindenem fáj.}
{130}{}{Mi bajod van?}
{131}{}{Fáj valami? Ha ha ha.}
{132}{}{Hát ez szar ügy. Na, csá...}
{133}{chip10}{Nekem itt fáj mindenem, te meg információt akarsz?}
{134}{}{Mi bajod van?}
{135}{}{Fáj valami? Ha ha ha.}
{136}{}{Rövid úton felejtsd el!}
{137}{chip11}{Megtaláltad már a lépemet?}
{138}{}{Igen. Dr. Wong Yi Tze birtokában van, és vissza fogja neked adni. Csak beszélned kell vele.}
{139}{}{Igen. Menj, és kutasd át érte Dr. Wong hulláját!}
{140}{}{Fogjuk rá. Dr. Wong Yi Tze birtokában van, de nem akarja odaadni.}
{141}{}{Megtudtam, kinél van, de szerintem Dr. Wong egyszerûen megette.}
{142}{}{Nem, még nem. De ne csüggedj!}
{143}{}{Nem. Az a helyzet, hogy nem foglalkoztam vele.}
{144}{chip12}{Rendben. ::liheg:: Mindenekelõtt kéne valami módot találni, hogy visszakerüljön belém. Beszélnél Dr. Funggal ez ügyben? Köszi.}
{145}{}{Értem.}
{146}{}{Nem.}
{147}{chip13}{Igazán nagyra értékelem, amit értem teszel. Soha nem fogom elfelejteni.}
{148}{}{No problemo.}
{149}{chip14}{Haver, mozdulni is alig tudok! Ha nem segítesz, nekem annyi.}
{150}{}{Jól van. Beszélek Funggal.}
{151}{}{Jó. Egyébként szart se érdekelsz.}
{152}{chip15}{Ha esetleg tudnál csinálni valamit... öldd meg, vagy dumáld meg a fejét, vagy akármi... a lépem nélkül ki fogok nyiffanni.}
{153}{}{Majd kiderül, mit tudok tenni az ügy érdekében.}
{154}{}{Bocs, barátom... de neked akkor annyi. Nem tudok segíteni.}
{155}{chip16}{Lép nélkül ki fogok nyiffanni. Amúgy kösz a segítségért.}
{156}{}{Megtaláltam! Menj el Dr. Wonghoz érte!}
{157}{}{Ó, majd én kisegítelek. Irány Fung!}
{158}{}{No problemo. Jó szerencsét!}
{159}{chip17}{Beszéltél már Funggal?}
{160}{}{Igen, és azt mondta, ingyen odaadja.}
{161}{}{Igen, de 1000 dollárt kért tõlem.}
{162}{}{}
{163}{chip18}{Az igen! Neked aztán vannak kapcsolataid! Gyere vissza holnap és majd meglátjuk, miféle segítséggel tudnám ezt kompenzálni.}
{164}{}{Legyen.}
{165}{chip19}{Ki tudsz segíteni?}
{166}{}{Ja, igyekszem...}
{167}{}{Nem.}
{168}{chip20}{Igazán nagyra értékelem, amit értem teszel. Gyere vissza holnap és megnézzük, milyen segítséggel tudnám ezt kompenzálni.}
{169}{}{A te érdeked.}
{170}{chip21}{Magamtól ezt nem tudom kifizetni. Azt hiszem, meg fogok halni.}
{171}{}{Ne aggódj, kisegítelek.}
{172}{}{Nehéz ügy. Ki vagyok készülve.}
{173}{chip22}{El nem tudom mondani, mennyivel jobban érzem magam. Szóval mit is szerettél volna tõlem?}
{174}{}{Hogy kell mûködtetni ezt a hajót?}
{175}{}{Hol találom a népemet? Nem tudsz róluk valamit?}
{176}{}{Szeretnék egy kis számítógépes munkát végeztetni.}
{177}{}{Most semmit, köszi. Szia.}
{178}{chip23}{Nézz be a Kapitányhoz! Odafönn az emeleten megtalálod a kapitányi irodában.}
{179}{}{Köszi. Volna azért néhány kérdésem...}
{180}{}{Köszönöm. Viszlát!}
{181}{chip24}{Azt rebesgetik, hogy nyugat felé cipelték õket, keresztül a nagy vizen. Ha azt akarod, hogy legyen valami keresnivalód, be kéne röffenteni ezt a teknõt.}
{182}{}{Köszi. Volna azért néhány kérdésem...}
{183}{}{Köszönöm. Viszlát!}
{184}{chip25}{Számítógépes munkát akarsz? Ha a Shik vagy a Hubologisták nem tudnak segíteni, beszélj a Borzzal! Õ itt az ügyeletes zseni.}
{185}{}{Köszi. Volna azért néhány kérdésem...}
{186}{}{Köszönöm. Viszlát!}
{187}{chip26}{Picsába. Beszélj a Hubologistákkal vagy a Shikkel! Mivel a Borz meghalt, egyéb ötletem nincs.}
{188}{}{Köszi. Volna azért néhány kérdésem...}
{189}{}{Köszönöm. Viszlát!}
{190}{chip29}{Mocsok!}
{191}{chip30}{Szükséged lesz egy kis fájdalomcsillapítóra.}
{192}{chip31}{Szemétláda! Most neked annyi!}
{193}{}{Ez itt egy kopasz punk.}
{194}{}{Õ Chip. Láthatólag nagy fájdalmai vannak.}
{195}{}{Ez itt egy punk. Miközben az oldalát fogja, levegõért kapkod fájdalmában.}
{196}{}{Rendben. Beszélek ezzel a Funggal.}
{197}{chip27}{Van valami fejlemény a lépem ügyében?}
{198}{}{Beszéltem az orvossal. Ezer dollárt kért a lépért, és ki is fizettem.}
{199}{chip32}{Kösz, hogy segítettél, barátom.}
{200}{chip28}{Haver, úgy hallottam, megtaláltad a lépemet. Beszéltél Dr. Funggal, hogy lehetne visszatenni belém?}
