{100}{}{Arrogáns Shi gengszter.}
{101}{}{Õ Lo Pan, egy dölyfös, kíméletlen férfi.}
{102}{}{Egy selyemruhába öltözött Shi gengszterhez van szerencséd. A keze alaposan fel van keményítve. Veszélyes és idegesítõ embernek tûnik.}
{103}{lopan1}{Mit akar?}
{104}{}{Daggle aggle aggle!}
{105}{}{Ki vagy!}
{106}{}{Kivel verekedtél?}
{107}{}{Ki vagy?}
{108}{}{Szeretnék úgy verekedni, ahogy te. Taníts, kérlek!}
{109}{}{Ezennel kihívást intézek hozzád!}
{110}{}{Rövid úton felejtsd el!}
{111}{lopan2}{Tûnés innen, idióta! Nincs mit mondanom a számodra!}
{112}{}{GRR!}
{113}{lopan3}{Lo Pan vagyok. A Sárkányt leszámítva én vagyok a város legjobb harcosa. Egy nap persze meg fog halni. Ha ez megtörténik, elkezdem tanítani a stílusomat.}
{114}{}{Taníts!}
{115}{}{Köfönömm.}
{116}{lopan4}{Tanulni akarsz? Megvan, ami kell hozzá? Na, lássuk csak...}
{117}{}{[RENDBEN]}
{118}{lopan5}{Miért is kéne téged tanítanom? Túlságosan öntörvényû embernek látszol. Tûnj innen!}
{119}{}{Mi a... ?}
{120}{lopan6}{Ó, te szerencsétlen... nem akarok beszélni veled. Eridj innen!}
{121}{}{Duhhh...}
{122}{lopan7}{A Sárkánnyal. Nyápic egy alak, aki a gyengeséget pártfogolja.}
{123}{}{A nép egy nagy nyáj. Légy a magad ura!}
{124}{}{Micsoda? Te gonosz ember vagy akkor?}
{125}{}{Értem. Hadd kérdezzek még egy-két dolgot.}
{126}{lopan8}{Gonosz? Aligha. Csak ravasz. Ha problémád van azzal, ha ennyire aggaszt a nép sorsa, eridj, beszélj a Sárkánnyal! Õ szereti a hozzád hasonló szenvelgõ puhányokat.}
{127}{}{[RENDBEN]}
{128}{lopan9}{Igen, azt kéne. Sõt azt is teszem. Sajnos a Sárkány az utamban áll. Túlságosan kiegyenlítettek a harci képességeink. Szükségem van egy képzett emberre, aki segítene nekem.}
{129}{}{Én elvállalom.}
{130}{}{Értem. Hát... talán inkább kérdeznék valami mást.}
{131}{}{Értem. Hát... viszlát!}
{132}{lopan10}{Akár... képes vagy puszta kézzel és lábbal verekedni, védõfelszerelések és fegyverek nélkül?}
{133}{}{Képes, de miért is kéne ilyesmit tennem?}
{134}{}{Elfogadhatónak hangzik. Mibõl áll ez a próba?}
{135}{}{Ó... hát ebben az esetben most inkább továbbállnék.}
{136}{lopan11}{Mivel a közemberek el fognak engem átkozni és sokkal nehezebb lesz õket betörni, amikor legyõztem a Sárkányt.}
{137}{}{Fogom. Kezdjük a tesztet!}
{138}{}{Fogom. Akkor kérdeznék valami mást.}
{139}{}{Hát perszeeee. Viszlát!}
{140}{lopan12}{Életre halálra akarsz harcolni, vagy csak leellenõrizni, melyikünk a jobb?}
{141}{}{A végsõkig. Elbírok veled.}
{142}{}{Csak a képességeimet akarom tesztelni. Nem akarlak megölni.}
{143}{}{Egyik sem érdekel. Felejtsd el még az ötletet is!}
{144}{lopan13}{Nagyszerû! Remélem, már megvan a sírhelyed. A Sárkány küldött téged?}
{145}{}{Igen. A Shik nevében jöttem.}
{146}{}{Nem. Azért csinálom, mert utálom a hozzád hasonló söpredéket.}
{147}{lopan14}{Szívós vagy, mi? Elõször az embereimmel fogsz harcolni, aztán majd meglátjuk, érdemes vagy-e arra, hogy kiálljak veled.}
{148}{}{[Kezdés]}
{149}{lopan15}{Lo Pan vagyok. A Sárkány "esküdt" ellensége. Hogy miért kell neki esküdt ellenség, fogalmam sincs. Ugyanúgy harcolok, mint õ, de szerintem õ nem elég elszánt és hagy másokat is érvényesülni. Azért vagyunk ellenségek, mert ugyanazt a stílust ûzzük, és bármelyikünk is nyer, õ viszi tovább a hagyományt.}
{150}{}{Én sem vagyok túl béna a pusztakezes harcban. Nem akarsz kipróbálni?}
{151}{}{Ez érdekes. Bizonyára kifizetõdõ. Kérdezhetek még?}
{152}{}{Köszönöm. Viszlát!}
{153}{lopan16}{Lehet, hogy egy söpredék vagyok, de azt sosem fogják rámfogni, hogy nem állok ki a népemért. Mielõtt meghalnál, fájdalmat fogok okozni neked.}
{154}{}{[RENDBEN]}
{155}{lopan17}{Akkor viszont eszetlen bolond vagy, hogy mások ugráltatnak. Nevetni fogok, amikor meghalsz.}
{156}{}{[Attack now, with armor and weapons.]}
{157}{}{[ belépsz a szorítóba, leveszed a védõöltözéked, lerakod a fegyvereidet és puszta kézzel küzdötök ]}
{158}{lopan18}{Jó. Legalább a magad ura vagy. Elég szívósnak érzed magad, hogy védõöltözék és fegyverek nélkül küzdj?}
{159}{}{[Attack now, with armor and weapons.]}
{160}{}{[ belépsz a szorítóba, leveszed a védõöltözéked, lerakod a fegyvereidet és puszta kézzel küzdötök ]}
{161}{lopan33}{Beee, birka, beee! Menj vissza a palástba burkolt barátaidhoz! Nincs mit mondanom számodra.}
{162}{}{[RENDBEN]}
{163}{lopan19}{Nem mondtam volna, hogy a morális aggályaiddal a Sárkányt boldogítsd? Õ majd fogja a kezed. Én nem. Most pedig távozz!}
{164}{}{[RENDBEN]}
{165}{lopan20}{El kell ismernem, még nálam is jobb harcmûvész vagy. Nem akarsz próbát tenni a Sárkánnyal?}
{166}{}{Igen. Most azonnal.}
{167}{}{Ez nem igazán az én harcom.}
{168}{}{Dehogynem, viszont szeretnék még kérdezni ezt-azt.}
{169}{lopan21}{Nem, nem így van. Viszont a Sárkány még mindig legyõz engem. Ha van benned gerinc, kiiktatod õt. Mellesleg sosem gondoltam volna, hogy egy lao wai-t ekkora büszkeség feszítsen.}
{170}{}{Helyes. Van néhány kérdésem.}
{171}{}{Igen, hát persze. Üdv!}
{172}{lopan22}{Épp most jöttem vissza, megöltem egy lao wai-t, aki megpróbálta ellopni a titkainkat. A Sárkánnyal karöltve csináltuk és el kell ismernem, egész jól dolgoztunk együtt.}
{173}{}{Nagyszerû! Válaszolj néhány kérdésemre!}
{174}{}{Nagyszerû! Viszlát!}
{175}{lopan23}{A Sárkány meghalt... Alig hiszem el. Mostantól legalább nem kell, hogy folyton a bosszantó hagyományok határozzák meg minden egyes lépésünket. Köszönet illet.}
{176}{}{Nagyszerû! Válaszolj néhány kérdésemre!}
{177}{}{Nagyszerû! Viszlát!}
{178}{}{Rendben. Most azonnal megteszem.}
{200}{}{Lo Pan észleli közeledésedet és elgáncsol.}
{201}{lopan34}{Nézd, nem szeretem, ha valaki ellopja a dolgaimat. Menj máshova tolvajkodni! Távozz innen!}
{202}{lopan35}{Azt mondtam, hogy távozz, nem azt, hogy halj meg! Anyám.}
{203}{lopan24}{Nagyon úgy tûnik, hogy tõlem te már nem tudsz semmit tanulni.}
{204}{lopan25}{A mai edzésnek vége. Gyere vissza holnap.}
{205}{}{Khung mester vagyok, az utolsó ellenfeled.}
{206}{}{Imbot vagyok. Készülj!}
{207}{}{Wejungh a nevem. Légy készen!}
{208}{}{Loopal vagyok. Innen nem mész tovább!}
{209}{}{Smitty vagyok. Itt az idõ, hogy elverjen valaki!}
{210}{}{Krall mester vagyok. Most véged!}
{211}{lopan36}{HARC!}
{212}{lopan37}{Többet kell edzened!}
{213}{lopan38}{Készülj!}
{214}{}{Igazi halálig tartó küzdelemben gyõzted le Lo Pant. Valami oknál fogva mintha fényesebben sütne ma a nap.}
{215}{lopan26}{Már legyõzted az embereimet. Átmentél a teszten. Készen állsz, hogy megküzdj a Sárkánnyal.}
{216}{lopan27}{Már éppen elég jó vagy. Menj, tanulj lõni, vagy akármi...}
{217}{lopan39}{Kezdjük akkor! Kövess!}
{218}{lopan40}{A napi tréning már megvolt.}
{219}{lopan41}{Jól tanultál.}
{220}{lopan28}{Már legyõzted az embereimet. Nincs ember, aki ki merne ellened állni.}
{221}{lopan29}{Segítettél nekem, és még csak nem is tudtál róla. A Sárkány halálával többé nem kell követnem az idejétmúlt hagyományokat.}
{222}{}{Örömmel tettem. Viszlát!}
{223}{}{Nem tesz semmit. Viszlát!}
{224}{}{Nem tesz semmit. Kérdezhetek valamit?}
{225}{}{Sebaj. Baj ha én kérdezni?}
{226}{lopan42}{GYÕZTÉL!}
{227}{lopan43}{VESZTETTÉL!}
{228}{lopan44}{Következõ Ellenfél!}
{229}{lopan45}{Hé, nézzétek már, mit találtam!}
{230}{lopan30}{Elõször is be kell bizonyítanod, hogy képes vagy megcsinálni. Ki kell állnod öt emberemmel, persze egyszerre csak egyikükkel. Ha mindegyiket legyõzöd, jöhet a végsõ próbatétel.}
{231}{}{Mibõl áll ez?}
{232}{}{Ez elég gázosan hangzik. Na, csá.}
{233}{lopan31}{Le kell, hogy gyõzd a választott tanítványomat. Mindazonáltal egyik összecsapásnak sem kell életre-halálra menni - az embereim védelmében persze. [gúnyosan mosolyog]}
{234}{}{Bunyóra fel!}
{235}{}{A Sárkánnyal magadnak kell elbánni!}
{236}{lopan32}{[Lo Pan végigmér, majd egy gyors ütéssel úgy orrba vág, hogy még reagálni sem tudsz.] Nem vagy elég jó.}
{237}{}{Rendben, de legalább kérdezhetek valamit?}
{238}{}{Remek. Viszlát!}
