{100}{}{Egy világító ghoult látsz, arcán az aggodalom jeleivel.}
{101}{}{Õ Hank, a világító ghoul. Munkás az erõmûben.}
{102}{}{Õ egy világító ghoul. Folyamatosan ellenõriz néhány mérõmûszert.}
{110}{hank1}{Üdv, Hank vagyok. Én felügyelem a reaktormag környékét. Nem mintha túl sok mindenre kéne itt felügyelni.}
{111}{hank2}{Üdv, örülök, hogy megint erre jársz. Az ember olyan ellazultnak érzi magát itt a reaktormag közelében. A legtöbb simabõrû nem tudja, mit hagy ki.}
{112}{}{Helló, Hank. Be kéne jutnom a reaktormaghoz.}
{113}{}{Hank barátom, hoztam Haroldtól egy hûtõközeg jelentést, amit meg kéne nézned. Tessék...}
{114}{}{Üdvözlet, Hank. Csak körbenézek. Viszlát!}
{120}{hank3}{Hehe... Nem javaslom, simabõrû barátom. Ropogósra sülnél az biztos. Én ugyan szeretem a meleget, de mégsem ajánlanám kipróbálásra. Egy egész pici hõség és sugárzás van odabenn. Az erõmûvet építõ simabõrûek ezért raktak be oda egy karbantartó robotot.}
{121}{}{Miféle karbantartó robotot?}
{122}{}{Köszönöm szépen. Viszlát!}
{130}{hank4}{Na, hadd nézzem csak... E szerint a hûtõközeg szintje túl magas. Azt gondolná az ember, hogy a hûtés kikapcsolása azonnali leolvadáshoz vezet, de lehet, hogy mégse. Azt hiszem, jobb lesz, ha lekapcsolom a hûtést.}
{131}{}{A jelentés szerint a hûtõközeg szintje túl magas. Mit gondolsz, nem kéne kikapcsolni?}
{132}{}{Remek okfejtés, Hank. Na, akkor én megyek is. Viszlát!}
{133}{}{Most, hogy jobban végiggondolom, talán várhatnál vele egy kicsit. Hadd egyeztessek Harolddal, mielõtt lekapcsolnád a hûtést. Hamarosan jövök.}
{140}{}{Hát igen, a reaktort építõ simabõrûek sem akartak megsülni, ezért rakták oda a robotot.
 Arra tervezték, hogy távirányítással tudjon karbantartó munkákat végrehajtani abból a terminálszobából.}
{141}{}{Remek, ezt kipróbálom!}
{142}{}{Ezt ki kell próbálnom. Majd még jövök.}
{150}{hank6}{Szép kis alkatrészed van. Épp erre volt szükségünk.}
{151}{}{Örülök, hogy tetszik. Van kedved üzembe helyezni?}
{152}{}{Kösz, nekem is igazán tetszik. Viszlát!}
{160}{hank7}{Szeretnék segíteni, de nem tudom, hogy kell az ilyesmit beszerelni. Én többnyire csak figyelem itt a mûszereket. Próbáld meg Festust. Õ itt a két lábon járó zseni... csak kérdezz rá nála.}
{161}{}{Hol találom Festust?}
{162}{}{Nincs más mód?}
{163}{}{Rendben. Késõbb találkozunk.}
{170}{hank8}{Beszéltél már Festussal az alkatrész beszerelésérõl?}
{171}{}{Hol találom meg?}
{172}{}{Nincs más mód?}
{173}{}{Még nem. Talán most sort kerítek rá. Üdv!}
{180}{hank9}{Festust arra találod, amerrõl jöttél. Az irányítóteremben tölti az idejét. Nem igazán lehet összetéveszteni senkivel. Egy nagy rakás egoizmusba csomagolt bûzlõ, nyavalygó fazon. Ellenben van esély, hogy segíthet rajtad.}
{181}{}{Kösz, viszlát!}
{190}{hank10}{Hát ha képes lennél irányítani a karbantartó robotot, az megcsinálná helyetted a beszerelést. Vagy, ha nincs jobb dolgod, menj be magad, és csináld meg egyedül.}
{191}{}{Karbantartó robotot mondtál?}
{192}{}{Én csináljam meg egyedül?}
{200}{hank11}{Hát mostanában nem mûködött valami fényesen. Folyton túlhevült. Nincs szükség rá, hogy használjuk, ezért nem törtük magunkat, hogy megjavítsuk a rajta lévõ hõpajzsot. Ha kibogarászod a vezérlõkódokat, és nem használod túl sokáig, lehetséges, hogy megteszi, amit akarsz tõle.}
{201}{}{Kösz, viszlát!}
{210}{hank12}{Köszönjük, hogy megjavítottad a reaktort.}
{211}{hank13}{Nincs itt hûvösebb mostanában?}
{212}{hank14}{Köszönjük, hogy segítettél rajtunk.}
{220}{hank15}{Még sosem hallottam így zümmögni.}
{221}{hank16}{Úgy dorombol, mint egy kiscica.}
{222}{hank17}{Jobban mûxik, mint valaha.}
{230}{hank18}{Csak ne lábatlankodj és ne nyúlj semmihez!}
{231}{hank19}{Hogy jöttél be ide?}
{232}{hank20}{Miért nem sétálsz át azon az ajtón? Takaros kis hely az, kellemesen világít. Hehehe...}
{300}{}{Telebeszélted Hank fejét, hogy elindítson egy reaktorolvadást.}
{900}{hank21}{Nem látod, hogy nem érek rá?!}
