{100}{}{Ez a ghoul az átlagosnál is nagyobb termetû.}
{101}{}{Õ Zomak, becenevén a Megsemmisítõ.}
{102}{}{Ez a ghoul szép nagyra nõtt. Arcán az ostoba felsõbbrendûség tükrözõdik.}
{110}{zomak1}{Jöjjön a Megújhodás, bajtársam! Zomak vagyok. Néhányak a Megsemmisítõnek neveznek. Mi járatban minálunk?}
{111}{zomak2}{Jöjjön a Megújhodás, bajtársam! Mit csinálsz idelenn? Add elõ Zomaknak, a Megsemmisítõnek, mi járatban vagy itt!}
{112}{}{Megújj!}
{113}{}{Rendi?}
{114}{}{Csak körülnézek.}
{115}{}{Szeretnék Megújhodni.}
{116}{}{Eltévedtem, tisztán látszik.}
{120}{zomak3}{Máshol tedd ezt, vagy Zomak fogja megvilágosítani az elmédet.}
{130}{zomak4}{Akkor látnod kell Õt.}
{131}{}{Õt? Hol van Õ? Merre találom?}
{132}{}{Nem vagyok érdemes rá, hogy lássam Õt. Viszlát!}
{140}{zomak5}{Õ a megvilágosodás apostola. Valamennyi követõje beteljesedik a Megújhodás által.}
{141}{}{Alig várom a Megújhodást. Hol találom Õt?}
{142}{}{Na, egy újabb vadbarom. Csá..}
{150}{zomak6}{Nos, Õt megtalálod a... Hé! Ki a franc vagy te, ha nem vagyok indiszkrét?}
{151}{}{Egy vándor vagyok.}
{152}{}{A Kiválasztott vagyok.}
{153}{}{Az évente esedékes Megújhodásra jöttem.}
{154}{}{Nem lesz semmi gond. Csak néhány kérdést akarok neki feltenni.}
{160}{zomak7}{Akkor vándoroljál szépen kifelé innen!}
{161}{}{Ööö... rendben. Viszlát!}
{170}{zomak8}{Nos, ebben az esetben... Jer velem. A következõ helyiségben megtalálod Õt. Ne várasd meg!}
{171}{}{Én ugyan nem. Megyek is. Viszlát!}
{172}{}{Lehet, hogy késõbb még visszajövök. Viszlát!}
{180}{zomak9}{Addig menj innen, amíg még megteheted. Kifelé!}
{181}{}{Oké.}
{200}{zomak10}{Igen, mindenki Megújhodhat odabenn.}
{201}{}{Oké.}
{210}{zomak11}{Rendi? Ez mit akar jelenteni? Zaza vagy?}
{211}{}{Goop?}
{220}{zomak12}{Tûnés innen! Az Agynak nincs ideje az ilyenekre.}
{221}{}{Rendben. Már itt sem vagyok.}
{230}{zomak13}{Itt nincs más semmi, csak az Agy barlangja. Barátocskám, te aztán zaza vagy a javából.}
{231}{}{Miféle Agy?}
{232}{}{Csak teszteltelek, és megfeleltél. Most engedj be.}
{233}{}{Szerintem egy kicsit megzavarodtam hirtelen. Lehet, hogy a sugárzástól van. Viszlát!}
{240}{zomak14}{Ah... Nincs itt semmi. Semmi az égadta világon. Csak egyszerûen távozz innen!}
{241}{}{Biztos vagy benne, hogy semmi nincs itt?}
{242}{}{Rendben. Késõbb találkozunk.}
{250}{zomak15}{Igen. Az vagyok. Most pedig tûnés!}
{251}{}{Ha maga mondja... Na, isten vele.}
{260}{zomak16}{Ó, hehe... persze. Tudtam én. Ööö... nos... átmentem?}
{261}{}{Át. Most pedig engedj be!}
{262}{}{Nem mentél át, és most jelenteni fogom ezt!}
{270}{zomak17}{Akkor rendben. Menj csak elõre!}
{271}{}{Rendben. Késõbb találkozunk.}
{280}{zomak18}{Viseled a jelet! Az ajtó nyitva áll elõtted.}
{281}{}{Meeegy...}
{282}{}{Jól értettem? Jelet mondtál?}
{283}{}{Féld a jelet! Viszlát!}
{290}{zomak19}{Igen, a Megújhodás felszentelt jelét. Jöjjön a Megújhodás, bajtársam! Jöjjön a Megújhodás!}
{291}{}{Hát hogyne... Neked is jó ujjazást. Viszlát!}
{300}{zomak20}{Jöjjön a Megújhodás, fivér. Átmehetsz!}
{301}{zomak21}{Jöjjön a Megújhodás, nõvérem. Átmehetsz!}
