{100}{}{Egy keménykötésû, öregedõ mutánst látsz.}
{101}{}{Zaius, a bányavezetõ.}
{102}{}{Egy keménykötésû, öregedõ mutánst látsz. Kezében csákány, fején bányászsisak.}
{103}{zaius1}{Te vagy az az új ember a városban?}
{104}{}{Íík, úúg og!}
{105}{}{Új! Vagyok! Város!}
{106}{}{Így van!}
{107}{}{Aha, nemrég érkeztem.}
{108}{}{Nem, zsenikém, mindigis itt éltem, csak sosem vettél észre.}
{109}{}{Úgy hallottam, van egy kis gond a bányával.}
{110}{}{Mit tudna mondani errõl a helyrõl?}
{111}{zaius2}{Ööö... hát peeersze. Tudod, mit? Itt egy pár dolcsi, eridj és vegyél magadnak valamit inni a kocsmában!}
{112}{}{Jagga? Ogg? Gronk!}
{113}{zaius3}{Nem értelek, haver. Mért nem mész el inkább a kocsmába? Talán Francis szkanderozna veled.}
{114}{}{Kanderozna? O-KÉ!}
{115}{zaius4}{Rendben. Nos, a nevem Zaius. Most pedig, hogy bemutatkoztunk... jó a kézügyességed? Van egy kis gond ugyanis a légtisztító berendezéssel a bánya alsó szintjén, de sajnos nincs hozzá megfelelõ alkatrészünk, sem védõruhánk, ami megvédjen minket az odalent szétterjedt radongáztól.}
{116}{}{Nem, sajnos nem.}
{117}{}{Nem túl rossz. Mire van szükség?}
{118}{zaius5}{Hát, remélem, jól fogod érezni magad itt Broken Hillsben.}
{119}{}{(tovább)}
{120}{zaius6}{Ha ha. Vicces. Épp egy ilyen csodás elmére van szükségünk a probléma megoldásához.}
{121}{}{Okosabb vagyok bárkinél ebben a segglyuknyi faluban.}
{122}{}{Nocsak? Van itt valami probléma? Mi volna az?}
{123}{}{A legfõbb probléma az, hogy te egy idióta vagy.}
{124}{}{Ez lennék én. Csodás elme. Mi a probléma?}
{125}{zaius7}{Tönkrement az alsó szinten lévõ légtisztítónk. Nincs hozzá alkatrészünk, és nincs védõfelszerelésünk sem. Megfelelõ alkatrész nélkül nem tudjuk megjavítani, védõruha nélkül pedig taccsra vág minket a radongáz. Jó a kézügyességed?}
{126}{}{Jól vagyok.}
{127}{}{Nem, nem igazán.}
{128}{zaius8}{Már megint te vagy?}
{129}{}{Ork! Úúú! Ug ug!}
{130}{}{Hi! HIIIII! Me }
{131}{zaius9}{Haver, már adtam pénzt. Menj, idegesíts valaki mást, jó?}
{132}{zaius10}{Helló! Miért nem nézed meg... ööö... a városi bankot? Biztos vagyok benne, hogy ott sok ember nagyon szívesen elbeszélgetne veled.}
{133}{zaius11}{Hát, ha meggondolod magad, csak szólj!}
{134}{zaius12}{Tényleg? Megtennéd nekem... és méginkább Broken Hillsért?}
{135}{}{Mit ajánlasz cserébe?}
{136}{}{Rendben van, vállalom.}
{137}{}{Most nincs.}
{138}{zaius13}{Úgy lenne? Hát, agyas barátom, akkor miért nem javítod meg a légtisztító berendezést a bányában? Szükséged lesz az alkatrészekre és valamire, amivel lélegezni tudsz odalent. Ha ez megvan, megmutathatod, mit tudsz! De szerintem, csak a szád nagy.}
{139}{}{Mit ajánlasz cserébe?}
{140}{}{Rendben van, vállalom.}
{141}{}{Viccelsz?}
{142}{zaius14}{A legfõbb probléma az, hogy idióta vagyok. Ezt ismételgetem magamnak, mert nehéz elhinni, hogy a seggedbõl épp most hallatszott ki valami, ami szavakra hasonlított. Menj innen a fenébe, tökmag!}
{143}{zaius15}{Eltekintve a seggfejektõl, akik folyton bosszantanak, a problémát a légtisztító okozza a bányában. Ugyanis meghalt, és nincs védõruhánk, amivel a radongáz ellenére lemehetnénk, és nincsenek megfelelõ alkatrészeink sem, amivel megjavíthatnánk. De te biztosan meg tudod csinálni, ugye? Hiszen te olyan okos vagy.}
{144}{}{Mit ajánlasz cserébe?}
{145}{}{Rendben van, vállalom.}
{146}{}{Viccelsz? Soha.}
{147}{zaius16}{. Mit szólsz hozzá?}
{148}{}{Szarra sem elég. Többet akarok!}
{149}{}{Jól hangzik.}
{150}{}{Felejts el! Nem vállalom.}
{151}{zaius17}{Nagyszerû! Akkor be kell szerezned az alkatrészeket. Menj el New Renóba és keresd fel Renescót! Neki van mindenféle alkatrész a boltjában. Mondd meg neki, hogy Zaius küldött! Azt is közöld vele, hogy "Kipurcant a kanári."! Nem tudom, hogy a gáz ellen hol találsz védõfelszerelést, de talán bemehetsz anélkül is, csak kicsit fájni fog. Még egyszer, kösz.}
{152}{}{Nem probléma. Üdv!}
{153}{zaius18}{Nem? Ha meggondolod magad, itt megtalálsz.}
{154}{}{Tiszta sor. Viszlát!}
{155}{zaius19}{ dollár akkor. A felét most, a felét, ha kész vagy. Menj el New Renóba és keresd meg Renescót! Neki van mindenféle alkatrész a boltjában. Biztos tud segíteni.}
{156}{}{Viszlát!}
{157}{zaius20}{Bocs, de nem adhatok többet. Vagy elfogadod, vagy nem.}
{158}{}{Megveszem.}
{159}{}{Itthagyom.}
{160}{zaius21}{Rendben. Akkor ne fogadd el!}
{161}{}{Jól van, jól van...}
{162}{zaius22}{Hi, friend!}
{163}{zaius23}{Oh, good. It's you again.}
{164}{zaius24}{Szevasz.}
{165}{zaius25}{Tudtam hogy ezek a mocskok, Franc, Manson, Jacob és Aileen terveznek valamit ellenünk. Szép munka! Naszóval...}
{166}{zaius26}{Remélem, gondolkoztál azon, hogy azt az ércet visszaadd a városnak... Naszóval...}
{167}{zaius27}{Kösz, hogy eladtad az ércet a városnak. Van mire használni. Naszóval...}
{168}{zaius28}{Kösz, hogy visszaadtad az ércet. Nem is tudod, milyen keményen dolgozunk érte.}
{169}{zaius29}{Most mit akarsz?}
{170}{}{Mesélnél a városról?}
{171}{}{Úgy hallottam, gondok vannak a bányával.}
{172}{}{How're things?}
{173}{}{Jól kijössz az emberekkel?}
{174}{zaius30}{Meggondoltad magad a légtisztító ügyében?}
{175}{}{Mit ajánlasz cserébe?}
{176}{}{Rendben van, vállalom.}
{177}{}{Most nincs.}
{178}{}{Nem.}
{179}{zaius31}{Mi újság? Remélem, hamarosan elintézed a dolgot...}
{180}{}{Minden a legjobb úton halad.}
{181}{}{Sok a dolgom, még nem tudtam vele foglalkozni.}
{182}{}{Nemsokára meglesz.}
{183}{zaius32}{Megvannak az alkatrészek? Nagyszerû... Remélem, van védõruhád is. A gáz elég veszélyes.}
{184}{}{Felkészültem, hogy lemenjek.}
{185}{}{Hamarosan lemegyek.}
{186}{zaius32}{Megvannak az alkatrészek? Nagyszerû... Remélem, van védõruhád is. A gáz elég veszélyes.}
{187}{}{Felkészültem, hogy lemenjek.}
{188}{}{Hamarosan lemegyek.}
{189}{zaius33}{Megjavítottad? Csodás! Tudom, hogy ingyen vállaltad, de... ezt nem hagyhatom. A srácokkal összedobtunk egy keveset és ezt szereztük neked. Egy harci sörétes. Sok szerencsét, és még egyszer, kösz!}
{190}{}{Nem gond. Kösz!}
{191}{zaius34}{Megjavítottad? Csodás! Ahogy megegyeztünk, itt van, amivel még tartozom. Kösz még egyszer.}
{192}{zaius35}{Te mocsok! Most meghalsz!}
{193}{zaius36}{Jó, jó. Kérlek, siess... a városnak kell a bánya.}
{194}{}{Tiszta sor. Viszlát!}
{195}{}{Ne sürgess már! Elfoglalt ember vagyok.}
{196}{zaius37}{Sajnálom, Mr. Nagy és Csodás, de talán a város sorsa egy kicsivel fontosabb. Siess, légy szíves!}
{197}{}{Rendben. Megcsinálom. Viszlát!}
{198}{}{Ez volt az utolsó húzásod. Viszlát, hullajelölt!}
{199}{zaius38}{Kérlek, siess! A bánya a városunk éltetõ ereje.}
{200}{}{Elnézést, csupán félreértés volt.}
{201}{zaius39}{Hát, a legjobb, akivel errõl beszélhetsz, az Marcus, a banknál, vagy Steve, a város üdvözlõ embere.}
{202}{}{Hmm. Rendben, kösz.}
{203}{}{I'll go ask them, then.}
{204}{zaius40}{Azt kell mondjam, hogy egész tûrhetõen. Persze... mehetnének jobban is.}
{205}{}{Heh. Kösz az infót.}
{206}{}{Well, as the mutants are not only getting old and senile -- the gas keeps them young, or
 something -- I'd have to say things are pretty good. I mean, we don't want to kill everyone, and as
 far as I can tell, the humans don't think too poorly of us. 'Course, that's not including the humans
 from the other places around here... now those are some bastards.}
{207}{}{Értem, kösz. Viszlát!}
{300}{zaius16}{. Mit szólsz hozzá?}
{301}{zaius16}{. Mit szólsz hozzá?}
{302}{}{, }
{381}{}{Elfoglalt nõ vagyok. Még nem tudtam vele foglalkozni.}
{382}{}{Ne sürgess már! Elfoglalt nõ vagyok.}
{383}{zaius42}{Sajnálom, Mrs. Nagy és Csodás, de talán a város sorsa egy kicsivel fontosabb. Siess, légy szíves!}
{400}{}{Van nálam egy cetli, amin rajta van a neved. Az alagutakban találtam egy hullarakás mellett. Van hozzáfûznivalód?}
{401}{zaius43}{Hé, én csak megkaptam azt az üzenetet. Menj, beszélj Francisszel, oké? Õ írta.}
{402}{}{Ha benne voltál azoknak az embereknek a meggyilkolásában, szeretném tudni.}
{403}{}{Rendben. Viszlát!}
{404}{zaius44}{Nem! Csak védekezünk az összeesküvés ellen. Marcus hisz a törvényben és a bizonyítékok erejében, és ha tudta is, hogy azok az emberek veszélyesek, nem tudta, kik is õk. Õ túl becsületes, hogy bizonyítékot hamisítson. Az én feladatom, hogy távoltartsam Francist a bosszútól.}
{405}{}{Ez túl jól hangzik. Megyek, beszélek Francisszel.}
{406}{zaius45}{Tudtam, hogy Francis nem tud majd mit kezdeni a leleplezõdéssel. Tisztában volt a tettei kockázatával, de szerintem nem hitte, hogy elkaphatják. Végülis nem lesz semmi baja. Remélem, Broken Hillsnek sem.}
{407}{}{Én is remélem. Lenne pár kérdésem.}
{408}{}{Én is. Viszlát!}
{1130}{}{. menet!}
