{100}{}{You see a handsome young man.}
{101}{}{Õ Davin.}
{102}{}{You see a young man in his twenties. He looks a lot like Grisham.}
{150}{davin1}{Ha rákérdeznél, én benne lennék.}
{151}{davin2}{Hmm! Miria nem valami jó az ágyban.}
{152}{davin3}{Nem hiszem, hogy ki akarnál használni engem.}
{153}{davin4}{Próbáljuk legközelebb hármasban.}
{154}{davin5}{Ohhh... nagyon csini fiú.}
{155}{davin6}{Kérdezd õt.}
{156}{davin7}{Ez már volt valami. Ki a következõ?}
{157}{davin8}{Üdv! A nevem Davin. A modoci mészárszéken segítek apámnak.}
{158}{}{Cornelius aranyóráját keresem. Nem láttad valahol?}
{159}{}{Mit csinálsz a mészárszéken?}
{160}{}{Hallottam rólad meg a brahminokról néhány pletykát.}
{161}{}{Mesélnél az apádról?}
{162}{davin9}{Üdv minálunk.}
{163}{davin10}{Tudtam, hogy visszajössz hozzám.}
{168}{}{Nem helyezhetnénk magunkat kényelembe?}
{171}{}{Maradj itt!}
{172}{davin11}{Hogyne, nincs dolgom. Kérdezz csak.}
{178}{davin12}{Nem, sehol nem láttam.}
{179}{}{Feltehetek néhány további kérdést?}
{180}{davin13}{Öööö... szóval én felügyelem és gondozom itt a dolgokat. Végül is a tulaj fia vagyok. Én öröklöm majd a pucerájt, ha az apám feldobja a bakancsát.}
{182}{davin14}{Ez hazugság! Csak azért megyek éjszaka az istállóba, hogy megnézzem, minden rendben van-e. Tudod, hogy van ez... rengeteg vadállat jár errefelé.}
{184}{davin15}{Apám üzemelteti a mészárszéket. Adnék egy tanácsot, ha netán üzletelnétek. Többnyire több van az üzletei mögött, mint amennyit elárul belõlük.}
{186}{davin16}{Gyere vissza bármikor, ha beszélgetni akarsz velem.}
{187}{davin17}{Ejha, sosem gondoltam volna, hogy egy ilyen szépséges nõ megpróbál elcsábítani. HÉ, VÁRJUNK! Te nem is vagy nõ! Na, sebaj, attól még elég csinos vagy. Ha nem szólsz semmit, én sem szólok egy szót sem.}
{188}{davin18}{Szerintem álmodom. Nem hiszem el, hogy egy ilyen szép nõ el akar engem csábítani. Gondolom, el akarsz csábítani, nem?}
{189}{}{Ha csak a szembedbe nézek, máris elolvadok. Ne törjük meg e drága pillanat varázsát puszta szavakkal. Beszéljenek magukért a tetteink.}
{190}{}{Csitt. Minkettõnkét elrontod. Csak dõlj hátra és élvezd.}
{191}{}{Itt valami félreértés lesz. Én csak fel akartam tenni néhány kérdést.}
{192}{}{Kösz az ajánlatot, de inkább ne. Uhhh... mennék is, ha lehet...}
{193}{}{Oh god! Take me! Take me now! [He rips off his clothes, then your clothes... then... Use your
 imagination.]}
{194}{davin20}{[Kuncog] Akkor én leszek a "dugattyú"! Legközelebb te lehetsz.}
{195}{}{[Két órával késõbb: A földgolyó fordult egyet, és ez az ágy sem lesz már a régi.]}
{196}{}{[Egy órával és a valaha tapasztalt legjobb orgazmussal késõbb.]}
{197}{}{[Fél órával késõbb kimerülten heversz.]}
{198}{}{[Tizenöt perccel és néhány mély sóhajjal késõbb.]}
{199}{}{[Addig jutottál, hogy levetted az inged, aztán már nem érzed, hogy szükséged van erre az egészre.]}
{200}{}{Mennem kell. Viszlát!}
{400}{davin21}{Apa!}
{401}{}{Hûha!}
{402}{davin22}{El hát!}
{405}{davin23}{Uncle Biff!}
{410}{}{Ajjaj...}
{411}{}{Izé... folytassa, kérem...}
{412}{}{Már hogy a francba ne...}
{413}{}{Hát... legyen úgy...}
{450}{davin24}{Ajaj, nem én vagyok az, akivel beszélned kéne.}
{500}{davin25}{Barátom, nekem kell itt a fõnöknek lenni.}
{1000}{davin26}{Igen, édesem.}
{1001}{davin27}{Mit tehetek érted, szépfiú?}
{1005}{}{Nem érted a lényeget. Nem akarom, hogy miközben jövünk-megyünk, ennyire rámtapadj.}
{1006}{}{Az a baj, hogy jóval messzebbrõl kéne követned engem.}
{1007}{davin28}{De... de... mi a baj velem?}
{1008}{davin29}{Mit szeretnél tõlem, kedvesem?}
{1009}{}{Köszi, amúgy is bajom volt vele. Akkor tehát mi legyen, kedvesem?}
{1010}{davin30}{Egyszer magam nyúztam meg egy brahmint a mészárszéken, szóval elég jól áll a kés a kezemben. Más alkalommal apám feszítõvassal agyonveretett velem egy másik brahmint. Szerintem akár egy bunkót se esne nehezemre használnom. Egyébként egyszer apa már adott pisztolyt is a kezembe, de betojtam és véletlenül majdnem lelõttem vele.}
{1020}{}{Kicsit lemaradhatnál, Davin.}
{1100}{davin31}{Teljesen felgyógyultam, és mehetnékem van.}
{1200}{davin32}{Alig maradt már sérülés rajtam.}
{1300}{davin33}{Nos, hellyel-közel meggyógyultam, de ha van rá lehetõség, elkelne még egy kis lábadozás.}
{1400}{davin34}{Amennyire tudtam, próbáltam magam ellátni, de még mindig rossz bõrben vagyok.}
{1500}{davin35}{Nem, kicsim. Veled akarok menni.}
{1600}{davin36}{Hát hogyne, elteszem...}
{1700}{davin37}{OK, állandóan mögötted leszek.}
{1800}{davin38}{Akkor nem leszek képes védeni téged. Inkább közel maradok.}
{1900}{davin39}{Valóban? Szó sem lehet róla. Nem engedlek el, kis szexgépem.}
{2000}{davin40}{Owie. I think I broke a limb. Can you kiss it and make it better?}
{2001}{davin41}{Ugh, I feel like I am burning up. I think I am radiated.}
{2002}{davin42}{Ugh, I feel so sick. I think I am poisoned.}
