{100}{}{Õ Eldridge.}
{150}{}{Ennek a fickónak tiszta olaj a ruhája, és állig fel van fegyverezve. Miközben a falon elhelyezkedõ fegyvergyûjteményét szemrevételezi, álmodozva mosolyog.}
{151}{}{Ez a fickó Eldridge. Miközben a falon elhelyezkedõ fegyvergyûjteményét szemrevételezi, álmodozva mosolyog.}
{200}{eld47}{Fogadd gratulációimat. A hõsünk vagy! Nagy dolgot mûveltél!}
{201}{eld48}{::Fegyverével a levegõbe lõ, és örömében nagyokat ordít:: Az Enklávénak ANNYI! ANNYI! ANNYI! Jihíjj!}
{202}{eld49}{::Bimm-bamm, az Enklávé kész, az Enklévé kész...::}
{203}{eld50}{Az Enklávé tökéletesen jó okot szolgáltat arra, hogy az átlagemberek fegyvert viseljenek.}
{204}{}{Ha legközelebb az Enklávéhoz mész, ne felejts el beugrani hozzám... Én majd gondoskodom róla, hogy legyen tûzerõ a háznál!}
{210}{eld52}{Szent gatyamadzag! Ez egy Energia Páncél!}
{211}{eld53}{Aztaaaa. ::Megdörzsöli a szemét:: Jól látok, az egy Energia Páncél?}
{212}{eld54}{Valaki csípjen már meg! Az tényleg egy Energia Páncél?}
{213}{eld55}{Tapossátok meg a síromat és pisáljátok le az elsõszülöttemet, ha az nem egy Energia Páncél! Itt Renóban!}
{214}{eld56}{Barátom, nem adod el azt az Energia Páncélt?!! Hé! Van odabenn valaki?}
{220}{eld57}{A 9 mm-es NEM ROSSZ, de a .233-asnak van megállító ereje.}
{221}{eld58}{Minden vágyam egy Red Ryder BB puska.}
{222}{eld59}{Remélem, hogy elõttem senki nem szerez egy turbó plazma puskát.}
{223}{eld60}{Kíváncsi vagyok, a Salvatore család honnan szerzi azokat a lézerfegyvereket.}
{224}{eld61}{Múlt éjjel már megint plazmafegyverekkel álmodtam...}
{225}{eld62}{El kéne már vinni az új puskalõszer-szállítmányt a Wrightéknak.}
{226}{eld63}{Remélem, a Mordinóknak van elég suskájuk, hogy kifizessék a számlát.}
{227}{eld64}{Hogy mit tud az a fegyver? Simán átviszi a fémfalat is.}
{228}{eld65}{Az a srác egy zseni... Elsõre nemigen látszana...}
{229}{eld66}{Asszem, ki kéne vinnem a kutyákat, mielõtt telehugyozzák az egész helyiséget.}
{230}{eld67}{A Mosdatlan Falusiak egyre több fegyvert halmoznak fel... kemény kis társaság.}
{231}{eld68}{Bárcsak valaki megpróbálna kirabolni... jól lepuffanthatnám.}
{232}{eld69}{Le kéne mosni a polcokat...}
{233}{eld70}{Alig bírom kivárni a jövõ hetet. Megyünk rossz fiúkat vadászni...}
{234}{eld71}{Van géppisztolyom, pisztolyom, dinamitom, gránátom... az emberek mégis kardokat meg számszeríjakat akarnak.}
{240}{}{Üdv, hõsöm! Rohadt kemény munkát végeztél az Enklávéval... megmentetted az irhánkat, bizony, én pedig hálával tartozom. A nevem Eldridge. Azért jöttél, hogy telepakold a fegyvertokodat valami jó kis "vassal"?}
{241}{eld2}{Üdv, fiatalúr... Eldridge-nek hívnak. Azért jöttél, hogy telepakold a fegyvertokodat valami jó kis "vassal"?}
{242}{eld3}{Üdvözlet, utazó... Eldridge-nek hívnak. Azért jöttél, hogy telepakold a fegyvertokodat valami jó kis "vassal"?}
{243}{}{Örhhhh? Tökködet?}
{244}{eld92}{Attól függ, mit árulsz.}
{250}{eld4}{Üdv nálunk újra, hõsöm! Rohadt kemény munkát végeztél az Enklávéval... megmentetted az irhánkat... bizony... én pedig hálával tartozom. }
{251}{eld5}{Ha valami megtetszene, csak szólj, és kitalálunk valami *speciális* árengedményt a számodra, rendbe'?}
{252}{}{Reeendicsekk}
{253}{}{Elpályázol}
{254}{}{Nagyszerû! Láthatnám az árudat?}
{255}{}{Nem tudom, tudnál-e segíteni... valami különlegeset keresek.}
{256}{}{A fõnököm... }
{257}{}{Jules azt mondta, ha fegyvert akarok magamnak, hozzád jöjjek.}
{258}{}{A Salvatore klán nálad vásárolja a fényhozóit?}
{259}{}{Meghoztam a lézerpisztolyt, amit ígértem.}
{260}{}{Foglalkozol fegyverek tuningolásával?}
{261}{}{Akkor késõbb még beugrom egy mustrára.}
{262}{}{Kiváló... láthatnám a különlegességeidet?}
{270}{eld6}{Itt a New Reno-i fegyverboltban áruljuk a legújabb személyi védõfelszereléseket, amelyekkel bármilyen parasztikus vadbarmot ott helyben kinyúvaszthatsz. (Gonoszul mosolyog.)}
{272}{eld7}{Üdv nálunk újra, barátom. Segíthetek?}
{273}{eld8}{Ûgymint?}
{274}{}{Cucc én szeret cucc te szeret cucc?}
{276}{}{Akkor te vagy az én emberem. Vethetnék egy pillantást a készletedre?}
{277}{}{Megnézhetném az árudat?}
{283}{}{Tudsz fegyvereket módosítani vagy tuningolni?}
{284}{}{Most nem vagyok vevõ semmire, köszi.}
{285}{}{Tõled? Semmit.}
{286}{}{Can I see your special stock?}
{300}{eld9}{Valami jó kis fényes tárgyat esetleg? Gyerünk, biztos van itt valami, amitõl összefut a nyál a szádban!}
{301}{eld10}{Öö... hogyne, hogyne. (Kritikus szemmel néz rád.) Al, a rabszolgám jut eszembe rólad. Akarod látni az árunkat, barátom.}
{302}{}{Eggen}
{303}{}{Én akkar walami nem szokvány}
{304}{}{Nehm}
{310}{eld11}{Nocsak, Jules küldött hozzám? }
{311}{eld12}{Itt az ideje, hogy az a lusta disznó megcsinálja a munkáját... szóval mit tehetek érted, miszter?}
{312}{eld13}{Itt az ideje, hogy az a lusta disznó megcsinálja a munkáját... szóval mit tehetek érted, kisasszony?}
{330}{}{Nem, nem... régen benne voltunk az ilyesmiben, de... (Fájdalmas arcot vág.) ...hát, történt egy kis baleset... és nem akarjuk, hogy újra megessen. Valami egyebet adhatok?}
{331}{}{Rendben van. Valami más érdekelne...}
{340}{eld15}{Hogy a francba ne tudnék? Mit akarsz kikupálni?}
{341}{}{Tudsz valamit csinálni ezekkel a pisztolyokkal?}
{342}{}{Az egyik puskámra elkelne ez-az.}
{343}{}{Tudsz valamit csinálni ezzel az ösztökével?}
{344}{}{Na, mindegy. Inkább más érdekelne...}
{345}{}{Tulképpen most semmi különöset nem akarok.}
{350}{eld16}{(Észreveszi a magnumodat.) Rátehetek a magnumodra egy gyorstöltõt? Az ára }
{351}{eld17}{Ott van az a Desert Eagle... ha akarod, rárakhatok egy kibõvített tárat. Az ára }
{352}{}{Rakd rá a magnumomra a gyors-utántöltõt.}
{353}{}{Csináld meg a tárbõvítõt erre a Desert Eagle-re!}
{354}{}{Igazság szerint egy másik fegyverre gondoltam...}
{355}{}{Felejtsük el! Valami mást szeretnék.}
{356}{}{Mennem kell, viszlát!}
{357}{}{Ez túl sokba kerül. Visszajövök, ha több lém lesz.}
{365}{eld18}{(Megtanulmányozza a puskáidat, és bólogat.) }
{366}{eld19}{Arra a vadászpuskára tudnék szerelni egy teleszkópot. Az ára }
{367}{eld20}{Látom van egy gépkarabélyod... tudnék rá rakni egy kibõvített tárat. Az ára }
{368}{eld21}{Van egy éjjellátó teleszkópom, amit rárakhatnék az FN FAL-ra. Az ára }
{369}{}{Legyen... szerelj rá egy teleszkópot a Colt vadászpuskára.}
{370}{}{Rendben, tegyél egy tárbõvítõt az AK-112 gépkarabélyra.}
{371}{}{Jöhet az éjjellátó az FN FAL-ra.}
{385}{eld22}{Szeretnéd egy kicsit feldobni az ösztökédet? Mit szólnál egy túltöltõhöz. Az ára }
{386}{}{Persze.}
{395}{}{(Eldridge átveszi a fegyvert, és kritikus szemmel megvizsgálja.) Oké... várnod kell egy kicsit, megnézem, mit tehetek. (Eltûnik a hátsó helyiségben.)}
{396}{}{Oké.}
{400}{eld24}{(Vársz...)}
{401}{}{Folytasd!}
{405}{eld25}{(És még mindig vársz...)}
{406}{}{Düm dü düm dü düm...}
{410}{}{(Már éppen le akarsz lépni, amikor hirtelenjében Eldridge visszatér.) Bocs a várakozásért... tessék. Ez egy kicsit megdobja az esélyeidet, ha egy faszkalap elédlépne a sötétben.}
{411}{}{Köszönöm. Esetleg más fegyveremre is ránéznél?}
{412}{}{Köszi. Térjünk akkor másra...}
{413}{}{Köszi. Megyek és kipróbálom.}
{420}{}{Óh... szóval egy válogatós kuncsafthoz van szerencsénk, mi? Hát van rá eset, hogy egy-egy jobb darab is becsusszan a városba.. vegyük ezt itt például. (Valami nagyon furcsát tart eléd.) Hamisítatlan háború elõtti technológia. Na, mit szólassssz? }
{423}{}{Öö... mi ez az izé? Megnézhetem közelebbrõl?}
{424}{}{Hát hogyismondjam... Asszem, valami más érdekelne...}
{425}{}{Nem dobogtatja meg a szívem. Amúgy kösz.}
{430}{eld28}{(A kérdéses tárgy egy mûanyag lap, tele lyukakkal, és fémcsíkokkal a felszínén. Néhány furcsa jelet is rávéstek. Valamiféle mechanikus kinézetû mirelit kajára emlékeztet, ezért összefut a nyál a szádban.)}
{431}{eld29}{(Úgy néz ki, mint egy nyomtatott áramkör. Elég poros, de még jó állapotban van. Valószínûleg egy alkatrész. A ráírt felirat szerint ez egy: "MenedékTek hangfelismerõ modul.")}
{432}{eld30}{(Ez egy összetett nyomtatott áramkör. Memóriakártyát is szereltek rá, az oldalán pedig egy csomó számítógépes csatlakozót látsz. Be- és kimenetek. A ráírt felirat szerint ez egy: "MenedékTek hangfelismerõ modul.")}
{433}{}{Én akar fini lapka}
{434}{}{Én akar valamás}
{435}{}{Én akarja menni}
{436}{}{"MenedékTek?" Ez fontos tárgynak tûnik. Mennyibe kerül?}
{437}{}{Na, végre... mennyibe kerül ez a modul?}
{438}{}{Kösz nem kérem, nézzünk valami mást...}
{439}{}{Ma nem, kösz.}
{450}{eld31}{Háromezer pénz. Kell vagy nem?}
{451}{eld32}{Utoljára is csak annyit tudok mondani: háromezer pénz. Kell vagy nem?}
{452}{}{Oki-doki}
{454}{}{Elkapod a torkát és elveszed a mechanikus mirelit kaját}
{455}{}{Nemkõ}
{457}{}{Öö, hát ez egy kicsit drágácska... Mit szólnál mondjuk ezeröthöz?}
{458}{}{Kösz nem. Térjünk valami másra...}
{459}{}{Itthagyom.}
{470}{eld33}{Legyen kétezerötszáz. Ez az utsó ajánlatom.}
{471}{}{Rendben, rendben. Itt van, tessék.}
{472}{}{Akkor felejtsd el! Térjünk valami másra...}
{473}{}{Akkor nem kérem, kösz. Viszlát!}
{474}{}{Ez túl sok nekem. Beszéljünk róla máskor, ha van elég pénzem.}
{480}{eld34}{(Mosolyog, és miközben leperkálod a pénzt, a kezét dörzsölgeti.) Tessék, a tied. }
{481}{}{(Gondolkodik egy kicsit, fürkészõen néz rád, aztán bólint.) Legyen... egy igazi rabló vagy, de nem számít. (Átnyújtja a modult, és bezsebeli a pénzét.) }
{482}{eld36}{Másvalamit?}
{485}{}{Igen-igen, nézzünk valami egyebet...}
{486}{}{Ma már nem, kösz...}
{495}{}{(Meglepetten pislog, aztán elneveti magát.) Hah! Nem, nem... azok a fegyverek azért más tészta, hidd el! Persze hazudnék, ha azt mondanám, hogy nem fogadnék el egy olyat... megnézném a hatótávját, az erejét, a tûzgyorsaságát... (Elnéz a semmibe és nagyot sóhajt.)}
{496}{}{Mi lenne, ha szereznék egyet?}
{497}{}{Hát tényleg jó lenne szerválni egyet. Na, térjünk valami másra...}
{498}{}{Hát... mindenképp meg akartam kérdezni. Kösz, Eldridge.}
{505}{}{(Rádkacsint, mintha nem tudná eldönteni, bízhat-e benned, vagy sem.) Nem mondanék nemet... ha fû alatt szereznél egyet. Fizetnék a fáradságodért... (Összevonja a szemöldökét.) ...feltéve ha nem sántikálsz rosszban.}
{506}{}{Nem fáradság ez nekem... itt van egy nálam. Tessék.}
{507}{}{Rendben, hozok egyet, de mielõtt mennék, valamit akarok még...}
{508}{}{Vedd úgy, hogy nem is említettem. Talán tudsz nekem segíteni valami másban...}
{509}{}{Legyen! Szerválok egyet, és elhozom neked.}
{510}{}{Nem tudok ígérni semmit... VELEM sajnos együtt jár a baj. Na, viszlát, Eldridge.}
{520}{eld39}{Heh, most már az én farkammal is verheted a csalánt! }
{521}{eld40}{Azt a büdös mindenségit! Állom a szavam, fogadd el ezt a fáradságodért. }
{522}{eld41}{(Átveszi a pisztolyt, és ad egy rakás pénzt.) A fenébe... nagyon furán néz ki ez itten... (Megvizsgálja a csövét.) Hmmm...}
{523}{}{Valami mást akartam inkább...}
{524}{}{Öröm veled üzletelni, Eldridge. Leld benne örömöd!}
{530}{}{(Eldridge végigmér, és a hangja azonnal tisztelettudóbbá válik.) Hogyne, persze. Hadd mutassam meg a különlegességeimet... persze diszkontáron adom õket.}
{532}{}{Tulajdonképpen egész más érdekel...}
{533}{}{Hagyjuk. Majd máskor visszajövök.}
{545}{eld72}{Ti kutyák most azonnal befogjátok a pofátokat, he!?}
{546}{eld73}{Pofát befogni, ugató banda!}
{547}{eld74}{Inkább éjszaka ugatnátok! Pofa be!}
{548}{eld75}{Packard! Buck! Missy! Fogjátok be a csõrötöket, mert odamegyek!}
{549}{eld76}{Még egy vakkantás és odamegyek!}
{550}{eld77}{Nyavalyás kutyák!}
{560}{eld78}{Szerinted be van kötve a szemem?}
{561}{eld79}{Veszed le a kezed arról az ajtóról!}
{562}{eld80}{Ne tapizd azt az ajtót még egyszer!}
{563}{eld81}{Ha még egyszer hozzáérsz ahhoz az ajtóhoz, többet nem fogsz semmihez nyúlkálni!}
{564}{eld82}{Vicces, hogy aki utoljára hozzáért ahhoz az ajtóhoz, most a Golgotán pihenget. Ne nyúlj hozzá többször!}
{575}{eld83}{Neked ott semmi dolgod! Tûnés! Tûnés onnan!}
{576}{eld84}{Te nem mehetsz oda be! Tûnés kifelé!}
{577}{eld85}{Húzzál onnan kifelé, mielõtt szitává lyuggatlak!}
{578}{eld86}{Ha nem mész onnan, céltáblának foglak használni!}
{600}{eld87}{Zárva vagyunk, haver... }
{601}{eld88}{Zárva vagyunk, kisasszony... }
{610}{eld89}{Felajánlom, hogy addig húzz onnan kifelé, amíg szarrá nem lõlek.}
{700}{eld93}{Rohadt kutyák! Hátra kell mennem aludni.}
{701}{eld90}{Idióta kutyái... Holnap az lesz az elsõ, hogy mindannyiótokat elaltatlak...}
{702}{eld91}{Would you dogs shut up! Nobody's stupid enough to break into a gun store!}
{800}{}{Szereztél egy lézerpisztolyt Eldridge számára.}
{801}{eld43}{Hey, do I look like some magician to you? You are gonna need the gun if you wanna upgrade it. Now get out of here and go find one I can upgrade... Sheesh!}
{802}{eld44}{Come back when you got the money.}
{1340}{}{Hogy a francba ne tudnék? (Ránéz a cuccaidra.) Az a baj, hogy nincs nálad semmi, amit megbütykölhetnék. Ha hozol valami szûz... illetve... "közönséges" pisztolyt vagy puskát, akkor talán segíthetek.}
{1345}{}{Rendben. Térjünk valami másra...}
{1346}{}{Úgy lesz. Na, üdv...}
{5256}{}{ ...azt mondta, hogy nézzek be, és hogy majd te "egyenesbe hozol engem".}
{5500}{eld46}{ dollár.}
