{100}{}{Õ Marjorie Reed, a kutatók vezetõje.}
{150}{}{Ez a nõ igen fáradtnak tûnik. Haja kopaszra van nyírva és fehér köpenyt visel.}
{151}{}{A hölgy Marjorie Reed. Miközben magában morgolódik, éppen egy fecskendõt tölt fel.}
{200}{marj26}{Üdv, Myron.}
{201}{marj27}{Myron, van egy perce...?}
{202}{marj28}{Nincs hír róla, mikor jönnek új rabszolgák, Myron?}
{203}{marj29}{Myron, az új eredmények igen bíztatóak...}
{204}{marj30}{Myron, volna egy perce?}
{215}{marj31}{Hol a fenében van Myron?...}
{216}{marj32}{Hozzátok ide Myront! Ezt neki is látnia kell.}
{217}{marj33}{A rabszolgák igazán befoghatnák már a szájukat...}
{218}{marj34}{Hol hagytam azt a fecskendõt?...}
{219}{marj35}{Látta valaki a 31-es alanyt? Az elõbb még itt volt.}
{220}{marj36}{A rabszolgák hozzanak még több Béta Jetet!}
{221}{marj37}{A Béta Jet teszteredményei nagyon bíztatóak, de...}
{222}{marj38}{Ha megnézzük az egy dózis/óra periódust... a "belövõdés" 15 perctõl egy óráig is eltarthat... hmmmmmm.}
{223}{marj39}{A 12-es alanynak egyfolytában vérzik az orra...}
{224}{marj40}{Ez már az ötödik alkalom, hogy a 12-es Alanynak rohamai vannak... adjuk be a dózist, és nézzük meg, mi történik...}
{225}{marj41}{Szóval miféle hallucinációi voltak a fickónak?}
{226}{marj42}{Nézzük meg a szívritmusát! Ha a tûréshatáron belül van, adjuk be a dózist!}
{227}{marj43}{Miért lett öngyilkos az a nõ a kontroll-csoportból? Még rá sem került a sor!}
{228}{marj44}{Az átkozott õrök tudnak vigyázni a saját seggükre...}
{235}{marj45}{Üdvözlet, Myron úr. A tesztek a tervek szerint haladnak.}
{236}{marj46}{Ez az új Jet hihetetlenül addiktív, Myron úr. A rabszolgák meggyilkolnák egymást érte.}
{237}{marj47}{Myron úr, ha meglátja az eredményeket, elégedett lesz. Az új Jet ugyanis annyira ütõs, hogy a rabszolgák még étel helyett is azt akarnak bevenni.}
{238}{marj48}{Kik ezek az emberek magával, Myron? Új tesztalanyok?}
{239}{marj49}{Az összes közül a harmadik tesztcsoport ígérkezik a legjobbnak, Myron úr.}
{240}{marj50}{Myron úr, ha volna egy kis ideje... szerintem a következõ tesztcsoportba kéne legalább három gyerek.}
{241}{marj51}{Myron úr, a 46-os Alany szívrohamot kapott. Mostantól naponta csak hat dózist engedélyezünk.}
{242}{marj52}{Myron úr, kérem... rövidesen új fecskendõszállítmányra lesz szükség Menedékvárosból. Örökké nem használhatjuk ezeket.}
{243}{marj53}{Van valami hír, mikor szállítanak be új rabszolgákat, Myron úr?}
{244}{marj54}{Myron úr, mivel légzési zavaraik voltak a múlt héten, három rabszolgát áttettünk a kontroll-csoportból a tesztcsoportba.}
{245}{marj55}{Myron úr, rossz híreim vannak. Le kellett lõnünk egy menekülõ rabszolgát. Nagy pazarlás ez...}
{246}{marj56}{Myron, ez az ön által kifejlesztett új hallucinogén nagyon ígéretes, viszont nem annyira addiktív, mint a Jet...}
{250}{marj1}{(A kopasz nõ fel sem néz a jegyzettömbjébõl.) Igen?}
{251}{}{Nem!}
{252}{}{Igeeen!}
{253}{}{He-he. Tar vagyol. Nézel ki mint férfi}
{254}{}{Delenn?}
{255}{}{Otthagyod}
{256}{}{Ki vagy?}
{257}{}{Elnézést, összetévesztettem egy másik kopasz nõvel, aki jegyzettömböt szorongat. Már itt sem vagyok.}
{265}{marj2}{(A nõ felemeli a tekintetét és rádbámul.) Maga az egyik kontroll alany? Nem mintha számítana... Õrség! Vigyék a helyére ezt a rabszolgát!}
{266}{}{Hol lenni rabszolga? Én nem lát egyet senem}
{275}{marj3}{Nézze, nagyon elfoglalt ember vagyok, szóval, ha nem haragszik... [Felpillant a jegyzettömbbõl és elkomorul.] Maga kicsoda? Hogy került ide?}
{276}{marj4}{Nézze, nagyon elfoglalt ember vagyok, szóval, ha nem haragszik... [Felpillant a jegyzettömbbõl és elkomorul.] Már megint maga az? Mit akar?}
{277}{}{Istálló ajtója nyitottan vanik. Hehe... érteni? Nekem teccik.}
{278}{}{Én vagyok az új alkalmazottak egyike. Ide rendeltek.}
{279}{}{Myront keresem. Itt van valahol?}
{280}{}{Abban a jegyzetfüzetben az új teszteredmények vannak? Vethetnék rájuk egy pillantást?}
{282}{}{Hagyjuk. Bocs, hogy zavartalak.}
{295}{marj5}{Ezt a területet idegenek nem látogathatják. Távozzék, különben hívom az õrséget!}
{296}{}{De hát szerettem volna feltenni egy-két kérdést önnek...}
{298}{}{Abban a jegyzetfüzetben az új teszteredmények vannak? Vethetnék rájuk egy pillantást? Én magam is kutató vagyok.}
{300}{}{Jól van. Elnézést, hogy zavartam önt.}
{310}{marj57}{Õrség! Õrség, vigyék innen ezt a személyt!}
{315}{}{Szóval még több õrt raknak ide... Szépen vagyunk! Mintha számítana egyáltalán hányan vannak... nézze, bárki is küldte ide magát, nyilván ellátta instrukciókkal. Beszéljen a többi õr valamelyikével, hogy megtalálja, hova van beosztva! Menjen!}
{316}{}{Nem vagyok õr. Az új kutatók egyike vagyok. Van számomra valami feladata?}
{317}{}{Elnézést, de azt reméltem, hogy körbevezet engem. Láttam, hogy itt áll, és erõs kényszert éreztem, hogy beszéljek magával. A vizit után akár vacsorázhatnánk is...}
{318}{}{Köszönöm. Ön igen segítõkész.}
{325}{marj7}{Ön KUTATÓ...? Hmmmm. Sosem láttam itt azelõtt. Mennyit tud a gyógyszerészeti kutatásokról?}
{326}{}{Öö, eleget. Csak dõljön hátra és figyeljen.}
{327}{}{Elég sokat tudok az alapvetõ neurokémiai összetevõk elegyítésérõl és gyártásáról, és azt hiszem, hasznossá tudnám tenni magam ön mellett.}
{328}{}{Mennem kell.}
{335}{marj8}{Ha! Pontosan ezt fogom tenni. Figyelem, ahogy elmegy innen. Pont. Távozzon, mielõtt hívom az õrséget!}
{336}{}{Értem.}
{337}{}{Megyek... ::aztán magadban hozzáteszed:: kopasz kurva.}
{345}{}{Hmmmm. Jól van. Hadd vázoljam, mit is csinálunk itt. Egy Jetnek nevezett metamfetamin hatásait és hatékonyságát vizsgáljuk.}
{346}{}{Értem. És hogy halad a kutatás?}
{347}{}{Azt hiszem, támadt egy ötletem. Egyedül fogom szemrevételezni a tesztterület többi részét.}
{355}{marj10}{Nem túl rózsás. A határidõk szorosak és rövid idõn belül le kell tisztáznunk a Jet gyártási folyamatát.}
{356}{}{Miért? A Jet már így is éppen elég addiktív.}
{357}{}{Mire fel a szoros határidõ?}
{358}{}{Hát nem egyszerû feladat annyi szent. Nézze, valamit nagyon sürgõsen el kell intéznem. Mindjárt visszajövök.}
{365}{}{Mondjuk senki nem mondott konkrétumot, de valószínûleg a reddingi Jet disztribúciónak köszönhetõ. A Jet *eléggé* potens anyag, de van még mit javítani rajta, és a nagykutyák növelni akarják a reddingi Jet-függõséget.}
{366}{}{Mi ez a reddingi balhé?}
{367}{}{Hát sok szerencsét a határidõk betartásához...}
{375}{}{A Jet *eléggé* potens anyag, de van még mit javítani rajta, és a nagykutyák növelni akarják a reddingi Jet-függõséget. Olyan közel szeretnék a száz százalékhoz, amennyire csak tõlünk telik. Ehhez még jó sokat kell túlóráznunk.}
{377}{}{Köszönöm az információt. Késõbb még jövök.}
{385}{marj13}{Addict the miners in Redding to Jet, and whoever controls the Jet, controls Redding. Typical power play.}
{386}{}{Nos... kinek a kezében is van a drog?}
{395}{}{Hogy kinek a kezében van a drog? A Mordinók kezében. Természetesen Myron rakta le a Jet-gyártás alapjait, nekünk csak a tucatmunka marad.}
{396}{}{Myron az ön fõnöke?}
{405}{}{Akár ANNAK is nevezheti. Okos ember, ezt nem tudom elvitatni tõle, de nem sokat törõdik vele, mi történik idefenn. Leginkább az alagsori kuckójában tartózkodik... látogatókat nem fogad, csak a prostituáltak hadait. Tipikus projekt vezetõ.}
{406}{}{Benézhetnék hozzá?}
{407}{}{Igen, de a marketingesek rosszabbak. Mindenesetre kösz az információt. Késõbb még benézek.}
{415}{}{Gondolom... hadd adjak egy belépõjelvényt. Csak mutassa meg az õröknek. Ne sokat maradjon, ha nem muszáj! Myron nem szereti, ha sok idejét rabolják.}
{416}{}{Gondolom... hadd adjak egy belépõjelvényt. Csak mutassa meg az õröknek. Ne sokat maradjon, ha nem muszáj! Myron nem szereti, ha sok idejét rabolják... persze a maga esetében lehet, hogy kivételt tesz.}
{417}{}{Köszönöm a jelvényt. Késõbb találkozunk.}
{425}{marj18}{Nézze, nagyon elfoglalt vagyok, szóval, ha nem bánja...}
{426}{marj19}{Nézze, én... én, ööö, nagyon elfoglalt vagyok, szóval, ha nem bánja...}
{427}{}{Akkor hagyjuk...}
{428}{}{Sebaj, azért kösz.}
{429}{}{Mindenesetre köszönöm... ::halkan hozzáteszed még:: te beképzelt golyófejû ribanc.}
{435}{marj20}{Hát... hmmm... nagyon hízelgõ, de momentán én is nagyon elfoglalt vagyok... szóval... ööö...}
{436}{}{Nem bánná, ha munka után magáért jönnék? Semmi nem kötelezõ... csak egy kis vacsora, kellemes beszélgetés. Ahogy így elnézem magát, jót tenne egy kis lazítás. Az itteni munka nagyon megviselheti.}
{437}{}{Hát csak úgy megkérdeztem. Mindenesetre köszönöm.}
{445}{}{Oh, not THAT busy... heh... well, no, pretty busy. I mean, mostly it's routine drug testing, and occasionally we have
 a slave go over the edge...}
{446}{}{A kísérleti metamfetamin rabszolgasorba hajtott emberi lényekbe való szándékos injektálása nem kérdõjelezi meg az alapvetõ emberiességét?}
{447}{}{Úh. Ez aztán veszélyesnek hangzik! Nem szokott megsérülni? Sok halálos mûhiba szokott történni?}
{448}{}{Drogteszt? Tényleg? Hogy áll a projekt?}
{449}{}{Érdekesen hangzik, de most mennem kell... ööö, késõbb biztos visszajövök.}
{455}{marj22}{Ez valami gyenge próbálkozás volt, hogy viccesnek tûnjön?}
{456}{}{Csak úgy megkérdeztem. Gondoljon bele... mi lenne, ha önt elhurcolnák rabszolgának, ide lehoznák és telenyomnák drogokkal?}
{457}{}{Ööö, igen. Most mennem kell.}
{465}{}{Én a karám egyik oldalán állok, õk pedig a másik oldalán. Mivel kezdünk hipotézisekbe bocsátkozni, megérdeklõdöm, hogy esetleg nincs-e kedve személyesen meggyõzõdni, milyen is lehet a másik oldalon állni. Van egy-két kihasználatlan karámunk.}
{466}{}{Várjunk egy pillanatot...}
{467}{}{Öö, kösz nem kérek belõle. Bocsánat, hogy zavartam.}
{475}{}{A rabszolgák halála érdekli? Nem sok történik. Többnyire véletlen túladagolás szokta okozni, általában egy asszisztens hibájából, de elõfordul, hogy egy rabszolga saját magát sebesíti meg. Némelyek túl sok Jetet vesznek be, mert a repülést túl komolyan gondolják.}
{476}{}{Ezt leszámítva, hogy halad a drogteszt?}
{477}{}{Fogadni mertem volna. Azért kösz az információt. Ön igen segítõkész.}
{485}{}{Próbálkozzon lent a laborban! Az õrzött ajtónál. Ha találkoznak, mondja már meg neki, hogy ha van ideje, jöjjön fel ide. Ha nem ANNYIRA elfoglalt...}
{1000}{}{Kaptál egy ideiglenes belépõt Marjorie-tõl.}
