{100}{}{Egy ember, aki az Enklávé erõpáncélját viseli.}
{101}{}{Granite õrmester.}
{102}{}{Egy katonát látsz õrmesteri sráfokkal a vállán.}
{103}{grani16}{Kapjátok el azt az õrültet!}
{104}{grani17}{Engedj, majd én!}
{105}{grani18}{Tölts és szegezz! Utánam!}
{106}{grani19}{Készenlétben!}
{107}{grani20}{Szedjétek le azt a vadbarmot!}
{108}{grani21}{Lõjétek hamuvá!}
{109}{grani22}{Készenállok.}
{110}{grani23}{Gyerünk!}
{111}{grani24}{Felgyújtom a rohadékot!}
{112}{grani25}{Utálok idiótákra lõszert pazarolni.}
{113}{grani26}{Mehetsz.}
{114}{grani27}{Nem láttam semmit.}
{115}{grani28}{Nem ezeket a droidokat keressük.}
{116}{grani29}{Mozgás!}
{117}{grani30}{Elegem van már a gyilkolászásból!}
{118}{grani31}{Gyerünk, tûnj már innen!}
{119}{grani32}{Csak nyugodtan, fiúk!}
{120}{grani33}{Néha nézz a hátad mögé is, kicsi mutáns!}
{121}{grani34}{Sok szerencsét, mutáns! Szükséged lesz rá!}
{122}{grani1}{Megállni! Mit csinálsz te itt?}
{123}{}{Az embereimhez próbálok visszajutni.}
{124}{}{Semmi közöd hozzá!}
{125}{}{Nincs idõm most kérdezz-feleleket játszani.}
{126}{}{Ki a franc vagy te?}
{127}{grani2}{Hát, tudod, az a szörnyszülött Horrigan, mármint Horrigan ügynök, az imént viharzott el mellettünk. Valakinek ki akarja tekerni a nyakát.}
{128}{}{Ki ez a Horrigan?}
{129}{grani3}{Hát, ebben tévedsz. Mondjuk úgy, én csak a dolgomat végzem. De mondd csak, mit keresel te itt?}
{130}{}{A hajót próbálom elérni, hogy elmenekülhessek a törzsemmel.}
{131}{grani4}{Akkor jó lesz kapkodni a lábadat!}
{132}{}{Miért kéne már kapkodnom?}
{133}{}{Nincs rá idõ! Hullákat gyártok és épp ti vagytok a következõk!}
{134}{grani5}{Jól van, eredj, de ne mondd, hogy nem figyelmeztettelek!}
{135}{}{Figyelmeztetni? Mire?}
{136}{}{Jól van, figyelmeztettél. Viszont engedd meg, hogy én is figyelmeztesselek: eljött a halálod napja, te Enklávés gyökér!}
{137}{grani6}{Horrigan valami genetikailag összetákolt szörnyeteg, megspékelve egy tonna acéllal. Az Elnök testõre volt régen. Most már legalább a fele gép.}
{138}{}{Hm, ez rosszul hangzik.}
{139}{}{Rosszabbat is öltem már. Hamarosan csak egy újabb folt lesz a falon.}
{140}{}{Húúú, nagyon megijesztettél. Fogd be inkább!}
{141}{grani7}{Igen, sõt, rosszabb! Fel fogja mosni a padlót veled. Kemény, szívós és gyors. Láttam, hogy intézi a mutáns-ügyeit, és nem valami szép látvány.}
{142}{}{Nem vagyok mutáns... egyébként mit csinált?}
{143}{grani8}{Nem szeretek errõl beszélni. Rémálmaim lesznek tõle. Annyit viszont hadd mondjak, hogy a falakat nem csak rozsda borítja azóta.}
{144}{}{Úgy látszik, nem lesz egyszerû csak úgy elsétálni mellette.}
{145}{grani9}{Ha, ez az év legjobb optimista dumája. Szánlak, haver, de tényleg.}
{146}{}{Pity me? You should feel bad for yourself. Your power plant's control computer got fried and now you're headed for a meltdown. You're all dead men unless...}
{147}{}{Kösz, de nem kell. Nektek viszont meg kell halnotok.}
{148}{}{Eh, elég dolgom van így is. Ti mind úgyis halottak vagytok. Próbáljátok kiélvezni utolsó földi perceiteket. Na, minden jót!}
{149}{grani10}{Hacsak!?}
{150}{}{Hacsak nem segítetek elagyalni Horrigan-t és feljutni a hajóra.}
{151}{}{Áh, hagyjuk. Nincs idõm errõl dumálni. Viszlát!}
{152}{grani11}{Na, persze. Van még ilyen vicced? Ha a reaktor felrobbant, akkor miért van még mindig világítás? He, okoscsávó? Nincs még ilyen vicced?}
{153}{}{Ez csak a vészvilágítás. Hé, én láttam, mi történt a reaktorral. Nem elromlott, meghalt. Kész, vége. Én mondom nektek, ti is mind halottak vagytok, hacsak...}
{154}{}{I don't have time to argue about this anymore. Hope you're all strong swimmers. Goodbye.}
{155}{grani12}{Na, ne mondd már! Röhögnöm kell! Tudod, szerintem elérheted az egy perces álomhatárt Horrigan-nel. Új túlélési rekord lesz, az ám! Sok szerencsét, kicsi mutáns.}
{156}{}{Nagyon nagylelkû vagy. Szerintem jobb, ha bemelegítek egy kicsit. Rajtad és a csapatodon.}
{157}{}{Reméljétek, hogy a páncélotok képes lebegni a vízen. Viszlát!}
{158}{grani13}{Oké, oké, várj! Nem szólhatok mindenkinek, de én és a csapatom melléd állunk. Együtt jól elláthatjuk Horrigan baját. Nem akarok megfulladni, mint egy patkány.}
{159}{}{Remek ötlet. Gyerünk, kapjuk el!}
{160}{grani14}{Granite õrmester az EBA divíziótól.}
{161}{}{EBA divízió?}
{162}{grani15}{Enklávé Biztonsági Alakulat. A külsõ védelmi vonalakért felelünk, általában.}
{163}{}{Áh, értem. Hogy érted azt, hogy általában?}
