{100}{}{Egy hosszú palástot viselõ szemkápráztató nõhöz van szerencséd.}
{101}{}{Õ a Megvilágosodott.}
{102}{}{Távolbaveszõ pillantása, agymosottakra jellemzõ üdvözült arckifejezése eléggé zavaró lenne, ha nem lenne olyan békés.}
{103}{eo1}{Üdvözlöm, gyermekem! Maga is a Megvilágosodottak közé tartozik?}
{104}{}{<Nyáladzol>}
{105}{}{Hogyne, miért ne?}
{106}{}{Hát... én vagyok a Kiválasztott.}
{107}{}{Nem nagyon értem, hogy mirõl beszél.}
{108}{}{Szóval maga a szálka Merk szemében...}
{109}{}{Igen.}
{110}{}{Nem.}
{111}{}{Most magányra vágyom inkább...}
{112}{eo2}{Hahó? Van ott valaki?}
{113}{}{Guh.}
{114}{}{Nin-csen senki.}
{115}{eo3}{Jó ég, egy újabb egyes szintû, de még a primitív állapotában. Talán egy zéta-szken behangolás segítene. Benne van?}
{116}{}{Zééé-tta!}
{117}{}{Nem!}
{118}{eo4}{Please don't mock the Church of Hubology. It's oppressors like you who make things hard for the rest of us. Oh, dear. I'm all turbulent!}
{119}{eo5}{Kiválasztott? Nem BHK-egy-re gondolt? Milyen forrásokból tanult?}
{120}{}{Egyszerû. Azért vagyok a Kiválasztott, mivel annak kell lennem.}
{121}{}{BHK egy?}
{122}{}{A törzsfõm mondta, hogy az vagyok.}
{123}{}{Mirõl beszélsz?}
{124}{}{Nem térhetnénk rá arra a részre, amikor rámlöttyinti a szentelt vizet, vagy valami ilyesmi?...}
{125}{eo6}{Ó... Szóval, az igaz megértést és a spirituális békét keresi? Segíthetünk...}
{126}{}{Nem, egy ÉLET-et keresek.}
{127}{}{Milyen módon akarnak segíteni?}
{128}{}{Egy rakétavetõ éppen elég spirituális békét nyújt nekem, hölgyem.}
{129}{}{"True understand" this! (Rude hand gesture with the middle finger.)}
{130}{eo7}{Merk? Mit akar?}
{131}{}{Nagyon egyszerû. Holtan akarja látni magát. Mondjon búcsút az életnek...}
{132}{}{Nem tudom, mit követett el, de felbérelt, hogy tegyem el magát láb alól.}
{133}{eo8}{Csodálatos, testvérem. Elmondaná milyen szintû?}
{134}{eo9}{Én kérdeztem elõször.}
{135}{}{Maga milyen szintû?}
{136}{}{Jaj... nem is tudom, miért feltételeztem, hogy látja az aurámat. Elnézést.}
{137}{}{Jaj... nem is tudom, miért feltételeztem, hogy látja az aurámat. Elnézést.}
{138}{}{Well, last time I checked the character screen, I was at level }
{139}{}{A Transzcendencia határán vagyok.}
{140}{}{Ööö... nem udvariatlanság a szintekrõl érdeklõdni?}
{141}{eo10}{Õszintén! Nem tudom, mit várnak tõlem, ha ilyen perem pépekkel vagyok körbevéve!}
{142}{eo11}{Ah, micsoda lelkesedés! Jöjjön velem!}
{143}{eo12}{"Elveszett emberek azok, kik nem ismerik a Hubot..." Ha valaha is meggondolná magát, itt mindig szívesen látjuk.}
{144}{eo13}{Ne kiabáljon! Most nézze meg... be kell hangolnom a neurodinjaimat!}
{145}{eo14}{Predesztináció? És mi van a szabad akarattal? A maguk hite alapján a maguk cselekedeteinek semmi értelme, hiszen minden meg van elõre írva. Nagyon úgy néz ki, hogy maguk csak szánalmas sakkfigurák.}
{146}{}{Félreért! Csak a Kiválasztottságomból fakadó lehetõségeim elõre meghatározottak. A döntéseim és a tetteim határozzák meg, hogy mi lesz ezekkel a lehetõségekkel.}
{147}{}{Az univerzum nyilván determinált! Végül is olyan céllal vagyunk itt, amit a teremtõnk nagyon is jól ismer.}
{148}{}{Nonszensz! Nincsen semmilyen sorsunkat meghatározó szervezõ erõ. Az a nagy büdös helyzet, hogy semmiféle "felsõbb hatalom" nem létezik. Az univerzum egy eshetõség. Azért vagyok a Kiválasztott, mivel mások annak választottak. Ennyi és pont.}
{149}{eo15}{Behangolt Hub Keresõ. Maga nyilván nem Megvilágosodott.}
{150}{eo16}{Primitív egy hit... viszont ígéretesnek tûnik. Magasabb ösvényekre tudnánk vezetni magát. Akar róla többet tudni?}
{151}{}{Igen.}
{152}{}{Nem.}
{153}{eo17}{Nem tudok segíteni. Mellesleg a San Francisco-i tudósaink többet tudhatnak. Meglátogathatná õket.}
{154}{eo18}{Megszabadítjuk a negatív pszichikai energiától. Ez az energia tartja magát elnyomó állapotban. Csak ezt követõen válhat Megvilágosodottá!}
{155}{eo19}{A Neurodinok a test pszichikai központjai. A háborúban elhunytak spirituális maradványaitól szennyezõdnek. Pszi-energiájuk már a születéskor bevésõdik a neurodinjainkba és elnyomó állapotban tartanak bennünket. A Behangolás kitörli ezeket a bevésõdéseket...}
{156}{eo20}{Amíg az agymûködését negatív pszichikai behatások érik, az igazi spirituális képességei el vannak nyomva. Nagy baj, hogy az elnyomók képesek ezt az energiát továbbítani, kivéve, ha nagyon, de nagyon erõs akaratúak.}
{157}{eo21}{A Megvilágosodás akkor jön el, amikor az összes neurodinját behangolták. Ekkor válik BHK-vá, Behangolt Hub Keresõvé. Minden Hubologistának ez a vágya.}
{158}{}{Mik a neurodinok?}
{159}{}{Megvilágosodott?}
{160}{}{Mi ez az elnyomó állapot?}
{161}{}{Hogy mûködik ez a megtisztítás? Nem fáj?}
{162}{eo22}{Egyáltalán nem fáj. Csak átesik egy zéta-szkenen. Ha óhajtja, most megcsinálom.}
{163}{}{Persze.}
{164}{}{Nem!}
{165}{eo23}{A Hubológia Egyháza azért létezik, hogy felszabadítsa az emberiséget azon láncok alól, mely rabságban tartja a kiteljesedni vágyó spiritualitását.}
{166}{}{Ezt hogy viszik végbe?}
{167}{}{Hát persze, valami olyasmi, hogy "Gyere, psziché, most szépen kimész belõlem..." ugye?}
{168}{eo24}{Ilyen képességgel nem rendelkezem. Van valami, amiben segíthetnék? Egy behangolás esetleg?}
{169}{}{Elfogadom a behangolást.}
{170}{}{Információra volna szükségem. 13-as Menedék... mond ez magának valamit?}
{171}{}{Hogy mennek a dolgok mostanában?}
{172}{}{Ne is törõdjön vele! Nincsenek kemény gondolatok bennem. Ez minden.}
{173}{eo25}{That's impressive. Though I believe we are speaking about two different things, it still sounds like you deserve an experience bonus.}
{174}{}{Yes!!}
{175}{}{It's done. Just remember though, there's more to life than gaining enough experience points to reach the next level. There's a whole "real" world out there.
 Now that we have that out of the way, shall we try again?}
{176}{}{Transzcendencia? Õszintén megvallva nem tudom, hogy várják el tõlem az ige hirdetését, ha nem 
értesítenek a legújabb doktrínákról!?}
{177}{}{(Folytatás)}
{178}{eo28}{Maga aludt az betanítás során? Hmm... Maga nem tartozik a Megvilágosodottak közé!}
{179}{eo29}{Tehát azt állítja, hogy létezik egy magasabb hatalom, aki szándékosan hoz létre bennünket, aztán magunkra is hagy? Nem hiszem, hogy bármely lény ilyen érzéketlen lenne. Jöjjön, ölelje kebelére a Hubológia Egyházát! Hadd mutassuk meg az igaz utat!}
{180}{}{Miféle igaz utat?}
{181}{}{Háááát...}
{182}{eo30}{Az élete fölötti irányítás híján, mi az élet értelme? Bármit csinál, nem ér semmit. Önszántából kelt fel ma reggel? Nem, maga csak egy bábu, melyet a saját filozófiája rángat. Nálunk, a Hubologista Egyházban megtalálja az igaz választ.}
{183}{}{Mégpedig?}
{184}{}{Biztos vagyok benne.}
{185}{eo31}{Jaj, milyen szomorú és üres filozófia ez! Még ha igaz is lenne, az egyetlen járható út az, ha saját magát fejleszti. Egyedül efölött van döntési joga. A Hubológia Egyháza segítséget tud nyújtani.}
{186}{}{Hogyan?}
{187}{}{Tûnjön a szemem elõl!}
{188}{eo32}{13-as Menedék? A tudósaink nyakra-fõre keresték nyugati irányban. Ennyit tudok róla. Biztos benne, hogy nem akar egy behangolást?}
{189}{}{Persze, miért ne?}
{190}{}{Nem, köszönöm, jól megvagyok behangolatlanul is.}
{191}{eo33}{Elmondom magának, hogy a Hubológia tanainak hirdetése sokkal keményebb, mint azt gondolja! BHK-9 egyszerûen nem látja át a nehézségeket. Az a helyzet, hogy mindent papírra vetettem. Megkérhetném magát, hogy elvigyen egy levelet BHK-9 számára San Franciscóba? Nem tudok jutalmat ígérni, de tudom, hogy BHK-9 hálás lesz érte.}
{192}{}{Hogyne, miért ne?}
{193}{}{Nem, köszönöm. Nem akarok belekeveredni ebbe.}
{194}{eo34}{Kiváló! Tessék, a levél. Tehetek még valamit magáért? Egy zéta-szkent esetleg?}
{195}{}{Szkent? Miért ne?}
{196}{}{Máris épp eleget tett. Minden jót!}
{197}{eo35}{Then I've spoken too much already. Goodbye.}
{198}{eo36}{Üdvözlöm! Miben segíthet a Hubológia Egyháza?}
{199}{}{<Nyáladzol>}
{200}{}{Szóval maga a szálka Merk szemében...}
{201}{}{Nem nagyon értem, hogy mirõl beszél.}
{202}{}{Mit csinál ez az egyház?}
{203}{}{Jaj... Rossz ajtót választottam.}
{204}{eo37}{Azzal, hogy megöl, semmilyen célt nem szolgál. Merk számára nem jelentek fenyegetést, csak a hitem miatt érez ellenszenvet irántam. Remélem, hogy nem tesz eleget a bérgyilkosságnak.}
{205}{}{Igaz, ami igaz, elég ártalmatlannak tûnik.}
{206}{}{Verje ki a fejébõl! Maga csak egy újabb halott Hubologista.}
{207}{eo41}{Nincs idõm idióták számára. Kérem, menjen el!}
{208}{eo42}{Kifelé, hitehagyott!}
{209}{eo43}{Nem tud mit mondani, hogy a Hubológia Egyházától bocsánatot nyerjen, szentségtörõ!}
{210}{eo38}{Hunyja be a szemét! Nem fog fájni.}
{211}{eo39}{Tessék. Kitöröltünk néhány csúnya bevésõdést! Maga mostantól BHK-1. Most pedig, ha megbocsát, intéznem kell az egyház ügyeit.}
{212}{eo44}{Üdvözlöm, keresõ társam. Többet nem tehetek magáért. BHK-1-ként kell folytatnia a saját útját!}
{213}{eo45}{A templom zárva van. Jöjjön vissza holnap!}
{214}{eo46}{Szíves örömest segítenék, de még egy BHK-4-nek is kell aludnia. Jöjjön vissza napközben!}
{215}{eo47}{Behatoló! Meg akarja szentségteleníteni ezt a helyet? Kifelé!}
{216}{eo40}{Csodálatos, nõvérem! Tehát milyen szinten van?}
{217}{}{. I'm sure if I keep wandering and killing random creatures I'll hit level 99 in no time.}
{218}{}{ }
{219}{}{ experience points for "taking care of" the Hubologist for Merk.}
