{100}{}{Egy furcsa, félig kutya, félig fém dolgot látsz. Úgy látszik, be van kapcsolva.}
{101}{}{Ez itt egy Roboeb! Mindenki kedvence!}
{102}{}{Ez a valami vagy egy szörnyûséges módon összetákolt kutya-gép kombináció vagy teljes mértékben gép és csak külsõre néz ki kutyának. Nehéz megmondani.}
{103}{dogr16}{Arf! <katt> Vaúú!}
{104}{dogr17}{...bzzzzzz...}
{105}{dogr18}{...whirrrrr... Nem vagyok kutyuli.}
{106}{dogr19}{Grrrrrrrrrrrrrrrr--}
{107}{dogr20}{Vau! Va-va-va-<katt>vaúú.}
{108}{dogr21}{<sprzzzt> Miáú... hiba.}
{109}{dogr22}{UgatUgatUgatUgatUgatUgatUgat!}
{110}{dogr23}{Grrr...}
{111}{dogr24}{Háuúúúúú! <kitt-katt> Háúúúú!}
{112}{dogr25}{Yipe! Yipe! Yipe!}
{113}{dogr26}{Veszély! Veszély!}
{114}{dogr27}{Rowf! <tick-tick-tick> Rowf!}
{115}{dogr28}{<whirrr> Nem madár, nem repülõ, nem is béka, csak én magam - Roboeb!<katt>}
{116}{dogr29}{Rooby-Doo!}
{117}{dogr30}{Ee-bee-dee-bee-ee-bee-dee-bee!}
{118}{dogr31}{Vaú!}
{119}{dogr32}{GRRR-ROWF!}
{120}{dogr1}{Arf-arf-arf-arf-arf-arf-arf!}
{121}{}{OKÉ}
{122}{}{Nincs kedvem újra csatlakozni hozzád. Viszlát!}
{123}{dogr2}{Rowf? <bang> Raggy?}
{124}{}{Hogy vagy?}
{125}{}{Várj itt, amíg vissza nem jövök!}
{126}{}{Egyelõre ennyi.}
{127}{dogr3}{<katt> nyaff}
{128}{}{Rá se ránts!}
{129}{}{OKÉ}
{130}{}{HP:}
{131}{}{A kiberebet most nem lehet tovább javítani.}
{132}{}{A kibereb egy kicsit jobban van.}
{133}{}{A kibereb most már teljesen ép.}
{1000}{dogr4}{Vau! Va-va-va-<katt>Vaúú?}
{1100}{dogr5}{Arf! <katt> Vaúú!}
{1200}{dogr6}{Rowf? <bang> Raggy?}
{1300}{dogr7}{<katt> nyaff.}
{1400}{dogr8}{Háuúúúúú! <kitt-katt> Háúúúú!}
{1500}{}{Ee-bee-dee-bee-ee-bee-dee-bee!}
{1600}{}{Hát hogyne, elteszem...}
{1700}{}{Arf-arf távolág: közel.}
{1800}{}{Arf-arf távolág: közepes.}
{1900}{}{Arf-arf távolág: messze.}
{2000}{dogr14}{...whirrrrr... Nem vagyok kutyuli.}
{2100}{dogr33}{GRRR-ROWF!}
{2200}{dogr15}{Vau! Va-va-va-<katt>Vaúú?}
{2204}{}{Ok, you're at a good distance for now.}
