{100}{}{Ez az õsz hajú férfi az ÚKK rendõrségének egyenruháját viseli.}
{101}{}{Õ az ÚKK seriffje.}
{102}{}{Ez a férfi a konzervativizmus netovábbja... a keményen dolgozó, ellentmondást nem tûrõ fajta.}
{103}{dum1}{Üdvözöljük az ÚKK-ban, idegen. A nevem Dumont, én vagyok a seriff. Remélem, zavartalanul tölti nálunk az idejét.}
{104}{dum2}{Fogadjon meg egy tanácsot Dumont serifftõl, idegen! Ezt a várost hidegen hagyja a maga fajtája. Bármilyen gondot okoz, bekeményítek. Nos, tehetek magáért valamit?}
{105}{dum3}{Üdv! Tehetek valamit magáért?}
{106}{dum4}{Na, köpje már ki!}
{107}{}{Örrrgh.}
{108}{}{A 13-as Menedéket keresem. Nem tudja, merre van?}
{109}{}{Nincs egy ÉLETED?}
{110}{}{Tisztességes munkát keresek. Tudna segíteni?}
{111}{}{Ó, rendben. Minden nagyon faszányos.}
{112}{dum5}{Elmaradottak vagyunk picit? Hozzád beszélek. Kérdezni akarsz? Hát kérdezz! Oké?}
{113}{}{Tizen-háromos menedék?}
{114}{}{ÉLET?}
{115}{}{Oké.}
{116}{dum6}{Nem, fogalmam sincs. Errõl még Tandi elnöknõ is szívesen hallana egy-két kézzelfogható információt. Sok problémát megoldana.}
{117}{}{Miféle problémát?}
{118}{}{Tandi elnöknõt mondott?}
{119}{}{Nagyszerû! Ilyen az én formám... Köszönöm.}
{120}{dum7}{Figyeljen rám! Tiszta és egészséges életet élek! Mindenki firtassa a magáét!}
{121}{}{So-rry! I don't suppose you know where Vault 13 is?}
{122}{}{Felejtsük el, hogy megkérdeztem! Most magára hagyom...}
{123}{dum8}{Egy halom dolgot tudnék említeni, ha érdeklõdést tanúsít.}
{124}{dum9}{Maga viccel, nemde? Azután, amit Jackkel tett? Gondolom, tud rendes munkát találni magának.}
{125}{}{Úgymint?}
{126}{}{Nem, térjünk rá valami más témára!}
{127}{}{Felejtse el! Meggondoltam magam, viszlát!}
{128}{dum10}{Nem 13-as, 15-ös Menedék, igen...}
{129}{}{Tizen-ötös?}
{130}{}{Nem. Tizen-háromos!}
{131}{dum11}{Igen, 15-ös! Te beszél Tandi. Nagy fõnök ÚKK. Tandi ismer Menedék. Akar segítni. Menny Tandi.}
{132}{}{Tandival? Õ kicsoda?}
{133}{}{Nem menni! Akarni 13!}
{134}{dum12}{Figyelni! Nem tizenháromos Menedék. Nem taláni. Nem látni. Nincsen tizenháromos. 15-ös van - népek talájják meg. Népek élnek 15-ös Menedékbe. Érteni?}
{135}{}{Nem tizen-háromos? Tizen-öttös?}
{136}{}{NEM. AKARNI TIZENHÁROMOS!}
{137}{dum13}{Arrgh! NINCSEN 13, OSTOBA FAJANKÓ! Nincsen 13! Nem találni. Sohase! Soha!}
{138}{dum14}{Tandi nagy fõnök. Tandi akarja segít. Beszélni Tandi. Menny Kon-gresszus ház. Rendbe'?}
{139}{}{ÉLET?}
{140}{}{Oké.}
{141}{dum15}{Enyém élet rendbe'...}
{142}{}{Tizen-háromos menedék?}
{143}{}{Oké.}
{144}{dum16}{Nézzen körül! Az ÚKK gyorsan növekvõ hely. Szükségünk van mindenféle berendezésre, számítógépre, miegymásra. Ez már azóta problémát jelent, hogy a földbitorlók beköltöztek a 15-ös Menedékbe.}
{145}{}{15-ös Menedék? Földbitorlók? Mi folyik itt?}
{146}{}{Mi ez a dolog Tandi elnöknõvel?}
{147}{}{Köszönöm az információt.}
{148}{dum17}{Az ÚKK elnöke, ki más? Az események annyira aggasztják, hogy még a helyettesemet is kölcsön akarta kérnni. Ki akart osztani neki valami különleges küldetést. Utálok ellentmondani, de egyszerûen nem nélkülözhetem az embereimet.}
{149}{}{Mit szólna hozzám? Esetleg ajánlhatna engem...}
{150}{}{Hmm. Az élet nem habostorta...}
{151}{dum18}{Magát? Hmmm... Nem lehet. Nem is ismerem magát. Mondjuk Tandi elnöknõ mindenképp fel akar valakit bérelni, szóval nyugodtan beszéljen vele személyesen! Az irodája a Kongresszusi Épületben van.}
{152}{}{Köszönöm. Így lesz.}
{153}{}{Tud valamit az ÉLET-rõl?}
{154}{dum19}{Hát, ez aztán fene rendes magától, idegen... meg egy kicsit merész is. Nem ismerem magát úgy, mint a tenyeremet, és a kinézete sem tetszik! Senkinek nem fogom ajánlani magát. Most pedig dolgom van...}
{155}{dum20}{Well, there's Duppo at the Stockman's. He does the hiring for the brahmin drives. Then there's Mr. Westin. If you talk to him, tell him I sent you. Even President Tandi's been asking around for some help.}
{156}{dum21}{Duppo up at the Stockman's Association wrangles hands for the brahmin drives. Go try him.}
{157}{}{Westin?}
{158}{}{Tandi elnöknõt mondott?}
{159}{}{Mennem kell.}
{160}{dum22}{Roger Westin. His spread's just out the west gate. He's been having some problem with varmints. He'd take care of it himself, but his health ain't what it used to be. Bad ticker, Doc Jubilee says.}
{161}{dum23}{Valóban?}
{162}{}{Van valami munkalehetõség a városban?}
{163}{}{Áh, hagyjuk... Mennem kell.}
{164}{dum24}{Gondoskodjon róla, hogy így is maradnak a dolgok. Viszlát!}
{165}{dum25}{Nem semmi, amit a vén Jack gyerekkel csinált, idegen. Seriffként is megemelem a kalapomat.}
{166}{}{Nem tesz semmit.}
{167}{}{Mit szólna esetleg egy kis jutalomhoz?}
{168}{dum26}{Hát, nem igazán van jutalomra szánt pénzünk. A köszönetemen kívül mással nem szolgálhatok..}
{169}{}{Vérjon! Szeretnék néhány kérdést feltenni.}
{170}{}{Megértem... viszlát!}
{171}{dum32}{Elnézést, most nem beszélgethetek. Már így is elkéstem a halottszemlérõl. Számomra mondjuk tiszta ügy.}
{172}{dum33}{Elnézést, se bûnözés, se idõzés.}
{173}{dum27}{Sivatagi patkányok. Meg kell értenie... ez a város a 15-ös Menedékbõl származtatja magát. Úgy tûnik, volt itt a múltban valami zûr, és a túlélõk alapították Shady Sands városát. A 15-ös Menedék bennünket illet. Néhány évvel ezelõtt néhány földbitorló beköltözött oda, és azóta is csak a baj van velük. Beszéljen Tandival ezügyben!}
{174}{}{Tandival? Õ kicsoda?}
{175}{}{Megfontolás tárgyává teszem...}
{176}{dum28}{Tudomásom szerint nincs több munkalehetõség.}
{177}{dum29}{Duppo up at the Stockman's Association wrangles hands for the brahmin drives. President Tandi's been asking around for some help.}
{178}{dum30}{Ezzel a szellemi potenciállal mindenki itthagyná ezt a várost, nemhogy még munkát keressen itt.}
{179}{dum31}{Duppo up at the Stockman's Association wrangles hands for the brahmin drives. Go try him. Then there's Mr. Westin. If you talk to him, tell him I sent you.}
