{100}{}{Amanda.}
{101}{}{Egy könnyes szemû, kimerült nõt látsz.}
{102}{}{Amanda.}
{103}{}{Egy könnyes szemû, kimerült nõt látsz.}
{104}{}{Amandát látod. Most, hogy Joshua szabad, sokkal boldogabbnak tûnik.}
{105}{}{Amanda.}
{106}{}{Amandát látod. Most, hogy Joshua szabad, sokkal boldogabbnak tûnik.}
{107}{ama11}{Óh, Joshua !!!}
{108}{ama12}{Most mit csináljak?}
{109}{ama13}{Elfogyott a pénzem.}
{110}{ama14}{Bárcsak szabadon engednék szegényt.}
{111}{ama15}{Joshua, úgy örülök, hogy szabad vagy! Annyira aggódtam!}
{112}{ama16}{Sajnálom, de nincs semmim, amit adhatnék neked.}
{113}{ama17}{Kérlek, hagyj magamra, különben hívom az õröket!}
{114}{ama1}{Mit akar?}
{115}{}{Jól vagy? Egy kissé zaklatottnak tûnsz.}
{116}{}{Semmi-semmi. Bocsánat, hogy zavartam.}
{117}{ama2}{Szóval... a férjem, Joshua bajban van. Megütött egy Polgárt és letartóztatták. Nem állt szándékában, de hát ivott és...}
{118}{}{Letartóztatták? Hol van most?}
{119}{}{Ha ittasan megtámadott valakit, megérdemli a büntetést.}
{120}{}{Sajnálom. Remélem, hamarosan szabadon engedik. Minden jót!}
{121}{ama3}{A városban, a Szolgaközvetítõ Központban. Azt mondták, ledolgozhatja a börtönbüntetését, mint Szolga, de ez évekig fog tartani.}
{122}{}{Nem tudsz rajta segíteni?}
{123}{}{Ha ittasan megtámadott valakit, megérdemli a büntetést.}
{124}{}{Sajnálom. Remélem, hamarosan szabadon engedik. Minden jót!}
{125}{ama4}{De hát csak baleset volt... õ nem akarta...}
{126}{}{Elhiszem, de most már nyugodj meg, kérlek! Hol van most?}
{127}{}{Nem akart megtámadni senkit? Na, persze, véletlenül belemászott az ökle egy Polgár képébe, igaz? Még hogy baleset! Remélem, mindketten tanultatok a történtekbõl.}
{128}{}{Sajnálom. Remélem, hamarosan szabadon engedik. Minden jót!}
{129}{ama5}{Elfogyott a pénzem, már nincs mibõl fizetni az õröket. Hamarosan el kell mennem innen. Azt mondták, ha Joshuával akarok maradni, belõlem is Szolgát csinálnak... *zokog*}
{130}{}{Ez jó megoldásnak tûnik. A Szolgáknak jó életük van itt, nem igaz?}
{131}{}{Megnézem, mit tehetek, csak ne bõgj már! Kivel beszéljek?}
{132}{}{Tudok segíteni, de nem ingyen.}
{133}{}{Sajnálom. Remélem, hamarosan szabadon engedik. Minden jót!}
{134}{ama6}{Nem akarom, hogy a fiam rabszolgaként nõjön fel. Azért jöttünk Menedékvárosba, mert úgy gondoltuk, itt új életet kezdhetünk, de amikor ideértünk... szóval itt van ez a csomó törvény, meg a fizetség az õröknek. Semmi sem olyan, mint amilyennek elképzeltük.}
{135}{}{Megnézem, mit tehetek, csak ne bõgj már! Kivel beszéljek?}
{136}{}{Sajnálom. Remélem, hamarosan szabadon engedik. Minden jót!}
{137}{ama7}{A Szolgák fõnökét Barkusnak hívják, Barkus Hivatalnok. Még csak be sem tudtam jutni a városba, hogy lássam a férjemet. Azt sem tudom, él-e még egyáltalán.}
{138}{}{Ne aggódj, beszélek vele! Visszakapod a férjed.}
{139}{ama8}{De hát nekem... nincs pénzem.}
{140}{}{Én nem is pénzre gondoltam... szivi.}
{141}{}{Rendben, ingyen is segítek. Kit kell keresnem?}
{142}{}{Hát az bizony nagy kár.}
{143}{ama9}{Mire célzol? Ó... nem... AZT... nem lehet. Úgy értem...}
{144}{}{Mindent megtennél, hogy a férjedet szabadon engedjék, igaz? Egyébként is nem kell megtudnia.}
{145}{}{Rendben, ingyen is segítek. Kit kell keresnem?}
{146}{}{Úgy érted... nem? Hát bizony az NAGY kár, aranyom. NAGY élményben lett volna részed.}
{147}{ama10}{Ha megígéred, hogy kiszabadítod a férjemet, én... én... hát legyen. Behajtom a sátorajtót. Azt hiszem, a fiam még mindig kint játszik, nem fog senki megzavarni minket.}
{148}{}{Ne aggódj! Kiszabadítom a férjedet, miután jó alaposan... megismertük egymást.}
{149}{}{Bocsáss meg, csak hülye tréfa volt. Megnézem, mit tehetek.}
{150}{}{Tudod mit? Felejtsük el az egészet!}
{151}{}{Hé, és velem mi lesz?!}
{152}{ama18}{Kérlek, szabadítsd ki Joshuát! A városban van, a Szolgaközvetítõ Központban.}
{153}{ama19}{Köszönöm, hogy kiszabadítottad a férjemet. Kérlek, fogadd el ezt a kis pénzt! Nem sok, de ennél többet nem tudok adni.}
{154}{ama20}{Még egyszer köszönöm, hogy kiszabadítottad a férjemet. Hamarosan elmegyünk innen.}
{155}{ama21}{Köszönöm, hogy kiszabadítottad a férjemet... és... kérlek, ne mondd el neki, mi történt köztünk!}
