{100}{}{Lydia.}
{101}{}{Ez a barna hajú nõ katonai terepruhát hord. Úgy tûnik, õ a csapos.}
{102}{}{Lydia.}
{103}{}{Ez a barna hajú nõ katonai terepruhát hord. Úgy tûnik, õ a csapos.}
{104}{lydia34}{Üdvözöllek! Egy italt, Kiválasztott?}
{105}{lydia35}{Üdvözöllek, Kiválasztott! Kérlek, foglalj helyet a bárban!}
{106}{lydia36}{Kérlek, foglalj helyet, pihenj egy kicsit!}
{107}{lydia37}{Õ a Kiválasztott !!!! Senki sem állhat ellen a Fallout 2 HÕSÉNEK!}
{108}{lydia38}{Jó napot, Kapitány.}
{109}{lydia39}{Menedékváros mindenek felett, Kapitány!}
{110}{lydia40}{Jó napot, Polgártárs!}
{111}{lydia41}{Menedékváros mindenek felett, Polgártárs!}
{112}{lydia42}{Egy mutáns! Õrség! Õrség!!!}
{113}{lydia43}{Egy ghoul! Õrség! Õrség!!!}
{114}{lydia44}{Zárva vagyunk. Gyere vissza reggel!}
{115}{lydia45}{Sajnálom, késõn jöttél. Gyere vissza holnap!}
{116}{lydia46}{Zárva vagyunk. Amint befejeztem a leltározást, lehúzom a rolót.}
{117}{lydia1}{Hé, Kiválasztott! Épp a kalandjaidról beszélgettünk... hozhatok neked egy italt?}
{118}{}{Humma..aa... bambinaa... humba aa.}
{119}{}{[Továbbállsz]}
{120}{}{Mit tud adni?}
{121}{}{Néhány információra lenne szükségem.}
{122}{}{Meghoztam a megbeszélt alkohol szállítmányt.}
{123}{}{Tõled? Semmit.}
{124}{lydia2}{Aha... persze. Hmmm... még egyszer kösz, hogy megmentetted a világot, meg minden.}
{125}{}{Humma... aa... hubba... aa... bambaa... djoo ez a aaa... pi aaa...}
{126}{}{[Továbbállsz]}
{127}{lydia3}{Nézd! Lehet, hogy megmentetted a világot meg minden, de pocsék a hangod. Muszáj neked énekelned?}
{128}{}{Hummaaa...da... bumbaa...djoo... ez a piiiaaa...}
{129}{}{[Továbbállsz]}
{130}{lydia4}{Nézd, itt van még egy ital, de most már tûnj el, oké? Remélem, amíg iszol, abbahagyod az éneklést.}
{131}{}{Kösz... ikeee... eee...}
{132}{}{[Továbbállsz]}
{133}{lydia5}{Mit tehetek érted, Kapitány?}
{134}{lydia6}{Mit tehetek érted, Polgártárs?}
{135}{lydia7}{Igen? Segíthetek?}
{136}{}{Te? Tee? Thee? Tehhhe...hukk .. thheee is úgy beszész, mint a több'ek, amikor meglátnak.}
{137}{}{[Továbbállsz]}
{138}{}{Mit tud adni?}
{139}{}{Néhány információra lenne szükségem.}
{140}{}{Meghoztam a megbeszélt alkohol szállítmányt.}
{141}{}{Tõled? Semmit.}
{142}{lydia8}{Ez volt a legelbûvölõbb dolog, amit valaha is hallottam. Várj egy kicsit, szólok az õröknek... hadd hallják õk is.}
{143}{}{Túl? Thúl. Túúúhhhl. Túúúhhhl szhekszi a ruhháimhozz}
{144}{}{[Továbbállsz]}
{145}{lydia9}{Van szintetikus sörünk és likõrünk, úgymint vodka-H és W, valamint tekila származékok, például W2. Friss vízzel is szolgálhatok, de kapható brahmin-tej is. A sör és likõr tíz dollár, a víz és a tej három.}
{146}{lydia10}{Mivel szolgálhatok?}
{147}{}{Vodka-H? Tekila W2?? Igazi alkoholotok nincs?}
{148}{}{Szintetikus sört kérek.}
{149}{}{Egy kupica Vodka-H most jól esne.}
{150}{}{Az a tekila W2 remekül hangzik.}
{151}{}{Csak egy pohár vizet szeretnék.}
{152}{}{Brahmin-tejet kérek.}
{153}{}{Igazából néhány információra lenne szükségem.}
{154}{}{Sajnos most nincs pénzem, de majd benézek még ide. Tetszik ez a hely.}
{155}{}{Értem, köszönöm. Sajnos most mennem kell. Viszlát!}
{156}{lydia11}{Tejet?! Bátor ember. Sajnos ezzel pillanatnyilag nem szolgálhatok, persze ha van idõd és megvárod, amíg megfejek egy állatot...}
{157}{}{Megvárom, idõmilliomos vagyok. A tej élet, erõ, egészség... és még a légutakat is tisztíccsa. Szóval, ide vele!}
{158}{}{Inkább kipróbálok valami mást.}
{159}{}{Akkor hagyjuk! Viszont néhány információra lenne szükségem.}
{160}{}{Most mennem kell. Viszlát!}
{161}{lydia12}{Egészségedre! Esetleg... még egy italt?}
{162}{}{Vodka-H? Tekila W2?? Igazi alkoholotok nincs?}
{163}{}{Szintetikus sört kérek.}
{164}{}{Egy kupica Vodka-H most jól esne.}
{165}{}{Az a tekila W2 remekül hangzik.}
{166}{}{Most inkább csak vizet innék.}
{167}{}{Brahmin-tejet kérek.}
{168}{}{Igazából néhány információra lenne szükségem.}
{169}{}{Sajnos most nincs pénzem, de majd benézek még ide. Tetszik ez a hely.}
{170}{}{Értem, köszönöm. Sajnos most mennem kell. Viszlát!}
{171}{lydia13}{Éspedig?}
{172}{}{Ki irányítja Menedékvárost?}
{173}{}{Hol van a Menedék?}
{174}{}{Mit tudsz a helyi rabszolgaságról?}
{175}{}{Milyen Menedékváros kapcsolata a külvilággal?}
{176}{}{Innék valamit. Mit ajánlasz?}
{177}{}{Meghoztam a megbeszélt alkohol szállítmányt.}
{178}{}{Sajnos mennem kell, Viszlát!}
{179}{lydia14}{Hát, Lynette Elsõ Polgár, ki más,... de te ugye Polgár vagy? Ezt azért illene tudni.}
{180}{lydia15}{Lynette Elsõ Polgár. Ha esetleg beszélni szeretnél vele, a Tanács épületében találod, innen északra.}
{181}{}{Értem. Kérdeznék valami mást.}
{182}{}{Igen, ez a szándékom. Akkor megyek is, viszlát!}
{183}{lydia16}{Innen keletre, egy nagy lyuk a hegy oldalában... de nem azt mondtad, hogy Polgár vagy? Ezt akkor tudnod kéne.}
{184}{lydia17}{Innen keletre, egy nagy lyuk a hegy oldalában. El sem lehet téveszteni. Azért jobb ha tudod,  oda csak Polgárok léphetnek be.}
{185}{}{Értem. Kérdeznék valami mást.}
{186}{}{De hát nekem Polgári jogaim vannak.}
{187}{}{Csak tájékozódtam. Már megyek is.}
{188}{}{Kösz, viszlát!}
{189}{lydia18}{Hát persze, hogy az vagy... ahogy a kedves vendég óhajtja. Én a helyedben azért kétszer is meggondolnám, kinek mondom azt, hogy "Polgártárs". Esetleg valaki felismeri azokat a lopott papírokat, amit attól a vérszívó Skeev-tól vettél. Csak egy baráti jó tanács. Húzd meg magad, rendben?}
{190}{}{Persze, kösz Lydia. Viszont szükségem lenne még néhány információra.}
{191}{}{Rendben. Viszlát!}
{192}{lydia19}{Nézd! Az elsõ dolog, amit meg kell tanulnod, hogy nem hagyhatja el a szádat a "rabszolga" szó, mert komoly zûrbe keveredhetsz. Használd a "szolgák" kifejezést, rendben? Csak egy baráti jó tanács.}
{193}{}{Értem, észben tartom. Kérdeznék még valamit.}
{194}{}{Kösz, mennem kell.}
{195}{lydia20}{Nem sokat tudunk a kinti világról. A legtöbb információt a kereskedõk szolgáltatják, akik a "Nagy Kört" járják. Az egyetlen hely, amit ezen a kereskedõ úton kívül ismerek, az Gekkó.}
{196}{}{Mesélnél nekem Broken Hillsrõl?}
{197}{}{Mesélj New Renóról!}
{198}{}{Mesélj Reddingrõl!}
{199}{}{Mesélj Gekkóról!}
{200}{}{Értem. Kérdeznék valami mást.}
{201}{}{Köszönöm az információkat.}
{202}{lydia21}{Broken Hills egy bányász kommuna, hasonlít Reddinghez. Annyit tudok róla, hogy messze délen van és az uránszállítmányaink nagy részét onnan kapjuk.}
{203}{}{Mesélj New Renóról!}
{204}{}{Mesélj Reddingrõl!}
{205}{}{Mesélj Gekkóról!}
{206}{}{Értem. Kérdeznék valami mást.}
{207}{}{Köszönöm az információkat.}
{208}{lydia22}{Dél-nyugatra találod. Egymásnak ellentmondó véleményeket hallottam Renóról. Néhány kereskedõ, különösen a rabszolga-kereskedõk, imádják a helyet, mások meg nagy ívben kerülik. Rengeteg a csillogás és a balhé is arrafelé, ahogy hallom.}
{209}{}{Mesélnél nekem Broken Hillsrõl?}
{210}{}{Mesélj Reddingrõl!}
{211}{}{Mesélj Gekkóról!}
{212}{}{Értem. Kérdeznék valami mást.}
{213}{}{Köszönöm az információkat.}
{214}{lydia23}{Az egy bányaváros messze nyugaton. Az utóbbi idõben nem sok karaván érkezett onnan és ez a fejeseket egy kicsit aggasztja. Fõként McClure Fõtanácsost.}
{215}{}{Mesélnél nekem Broken Hillsrõl?}
{216}{}{Mesélj New Renóról!}
{217}{}{Mesélj Gekkóról!}
{218}{}{Értem. Kérdeznék valami mást.}
{219}{}{Köszönöm az információkat.}
{220}{lydia24}{Az egy ghoul város, kevesebb mint egy napi járásra észak-kelet felé. Azt beszélik, hogy minden utazót foglyul ejtenek, aki belép a területükre. Jobb messzire elkerülni azt a helyet.}
{221}{}{Mesélnél nekem Broken Hillsrõl?}
{222}{}{Mesélj New Renóról!}
{223}{}{Mesélj Reddingrõl!}
{224}{}{Értem. Kérdeznék valami mást.}
{225}{}{Köszönöm az információkat.}
{226}{lydia25}{Igazi?! Minek az? Nagyon ütõs anyag ez, hidd el nekem! Egyszer, az egyik kedves vendég annyira berúgott, állat módjára úgy leittasodott, hogy...}
{227}{}{Nem ezzel van a baj. Nem is tudom, a színe... a zamata... az illata. Vagy te még sose ittál igazi alkoholt?}
{228}{}{Igazad van, nincs ezekkel semmi baj. Kérdeznék még valamit.}
{229}{}{Te tudod. Viszlát!}
{230}{lydia26}{De... egyszer. Ismertem egy kereskedõt, akinek volt egy üveg Maddog 30/30-a és meghívott egy pohárkára. Keserû cucc, utána nem éreztem a nyelvemet, de... üdítõen más volt.}
{231}{}{Ugye? És mi történt azután?}
{232}{}{Néhány információra lenne szükségem.}
{233}{}{Értem. Viszlát!}
{234}{lydia27}{Nem nehéz kitalálni, berúgtunk, mint az albán szamár. Tivornyázás közben persze akadt néhány segítõkész száj is, akikkel közösen benyeltük a készletet. Bár a kereskedõ aranyárban mérte az italt, tolongtak érte a cimborák.}
{235}{}{I'll bet. You know, I could probably get some more of the real stuff, easy. I've been traveling the wastes a lot, and getting a hold of alcohol is no big deal.}
{236}{}{Néhány információra lenne szükségem.}
{237}{}{Értem. Viszlát!}
{238}{lydia28}{Sajnálom, de Menedékvárosban kizárólag mesterséges alkoholt szolgálhatunk fel... [körbepillant, majd közelebb hajol]... persze, ha lenne egy ügyes ember, aki bejuttatna a kapun egy szállítmány eredetit...}
{239}{}{Ügyes?! Errõl vagyok híres... többek között. Ez utóbbit azért ne nagyon firtassuk! Egész pontosan, mire is lenne szükséged?}
{240}{lydia29}{Mondjuk tíz üveg jó minõségû égetett szeszre és tíz üveg sörre. De ne az a radioaktív lötty legyen, ami Gekkóból jön, csak a régi, hagyományos, jó öreg "pia" érdekel. Mindez maximális titoktartás mellett. Rendben?}
{241}{}{Ennyi épp van nálam. Tessék.}
{242}{}{Nem lesz gond, leszállítom az árut és köztünk marad az ügy. De kérdeznék még valamit.}
{243}{}{Nem is tudom, még gondolkodom a dolgon. Viszlát!}
{244}{lydia30}{Nagyszerû! Tessék a pénzed... pont a duplája annak, amennyit érnek. És ez a tranzakció meg se történt, rendben?}
{245}{}{Természetesen. Egyébként kérdezhetek valamit?}
{246}{}{Kösz, öröm veled üzletelni.}
{247}{lydia31}{Szó sem lehet róla. Azok a pusztából származó készítmények illegálisak itt, Menedékvárosban. Még azt sem akarom tudni róluk, hogy léteznek. Adhatok valamit inni, Kapitány?}
{248}{}{Nincs semmi rossz egy kis alkoholban. Persze az észlelésed ideiglenesen megsínyli a fogyasztásukat, de hát ugyanez történik, ha túl sok gyógyító port használsz.}
{249}{}{Az bizony jól esne.}
{250}{}{Felejtsd el, hogy megkérdeztem! Néhány információra lenne szükségem.}
{251}{}{Értem, rendben van.}
{252}{lydia32}{Mi csak legális, szintetikus italokat tartunk. Ha esetleg valami módon igazi alkohol kerülne Menedékvárosba, arról nekem nem kell tudnom.}
{253}{}{Néhány információra lenne szükségem.}
{254}{}{Értem, rendben van.}
{255}{lydia33}{Értem... Nos, hmmm... vigyázz magadra, oké?}
{256}{}{Kösz... ikeee... eee...}
{257}{}{[Továbbállsz]}
{258}{lydia47}{Zzzzzzzz.}
