{100}{}{You see a man dressed in standard military combat armor.}
{101}{}{Egészségesnek tûnik, de kicsit zavarodott.}
{102}{dobbs1}{Ó, a fejem!}
{103}{}{Ki vagy?}
{104}{}{Aggr!}
{105}{dobbs2}{É-én Dobbs... õrvezetõ vagyok, Elsõ Hadosztály.}
{106}{}{Aztán el tudnád-e mondani nekem, hogy kerültél ide?}
{107}{}{Viszlát!}
{108}{dobbs3}{Persze... csatában voltam. Igen, egy ütközetben. Csak a fegyverek zaját és a robbanásokat hallottam minden irányból. Emberek haldokoltak. Rémült voltam, de tovább kellett harcolnom. Aztán jött az a vakító fény...}
{109}{}{Utána mi történt?}
{110}{}{Viszlát!}
{111}{dobbs4}{A következõ dolog, amire emlékszem, hogy látom a testemet... fölülrõl. Hallottam, hogy az orvosok szerint végem van, aztán a testemet egy csomó hulla közé lökték.}
{112}{}{És aztán mi történt?}
{113}{}{Viszlát!}
{114}{dobbs5}{Jött néhány ember és a testemet egy laboratóriumba cipelték. Arról beszélgettek körülöttem, hogy megpróbálják regenerálni a testemet. Bele akartak tenni egy folyadékba, amit Bio-Med Gélnek neveztek.}
{115}{}{És aztán?}
{116}{}{Viszlát!}
{117}{dobbs6}{Aztán itt ébredtem fel. Most mennem kell! Vissza kell térnem az egységemhez.}
{118}{}{Viszlát!}
{200}{dobbs7}{Hol vagyok?}
{201}{dobbs8}{Fáj a fejem.}
{202}{dobbs9}{Miért vagyok csupa ragacs?}
{300}{dobbs10}{Újra csatlakoznom kell az egységemhez!}
{301}{dobbs11}{Ó, ne! Engedély nélküli eltávozással fognak vádolni!}
{302}{dobbs12}{Merre van a frontvonal?}
{303}{dobbs13}{Ezt érted teszem, Jonny.}
{400}{}{Dobbs közlegény elsõ kézbõl tapasztalja meg a Poszt-Kriogén Szindróma áldatlan hatását...}
