{100}{}{Widzisz prostytutkê.}
{150}{}{Wygl¹da jak typowa, ciê¿ko pracuj¹ca prostytutka.}
{152}{}{[ROZMAWIAJ]}
{153}{shela1}{Hej, kobiet nie obs³ugujê!}
{154}{}{Jak chcesz.}
{155}{}{Przykro mi.}
{156}{}{Mama?}
{157}{shela2}{Za tê publicznoœæ zap³acisz ekstra.}
{158}{}{Tam, gdzie ja tam i oni.}
{159}{}{Chcê, ¿eby byli ze mn¹.}
{160}{}{Wrócê do ciebie.}
{161}{}{Mama?}
{162}{shela3}{Skarbie, gdzieœ ty by³ przez ca³e moje ¿ycie?}
{163}{}{Tutaj, skarbie.}
{164}{}{Ile za tê przyjemnoœæ?}
{165}{}{Muszê ju¿ iœæ, pa.}
{166}{}{£iii!}
{167}{shela4}{Lubiê takich du¿ych i g³upich.}
{168}{}{To w³aœnie ja!}
{169}{}{Jej!}
{170}{}{Oj. Nie. Pa.}
{171}{shela5}{Ale z ciebie du¿y ch³opiec!}
{172}{}{Tak jak lubisz.}
{173}{}{Tak, proszê pani.}
{174}{}{Muszê ju¿ iœæ.}
{176}{}{Œwietnie!}
{177}{}{Nie. Czeœæ.}
{178}{shela6}{Jeszcze do mnie wrócisz.}
{179}{}{Zobaczê, co siê da zrobiæ.}
{180}{}{Um, nie.}
{181}{}{[Œlini siê]}
{182}{shela7}{Masz za ma³o kasy. Spadaj, s³onko.}
{183}{}{Jeszcze tu wrócê.}
{184}{}{Nie jesteœ warta z³amanego grosza, laluniu.}
{185}{}{£aaa!}
{186}{shela8}{To by³o niesamowite!}
{187}{}{Jak zwykle, skarbie.}
{188}{}{Jak chcesz.}
{189}{}{Tak, cudowne!}
{190}{}{Niesmakowite?!}
{191}{shela9}{To by³o cudowne!}
{192}{}{Dziêki tobie.}
{193}{}{Hmm.}
{194}{}{Tak.}
{195}{}{Wspaniale!}
{196}{shela10}{Dobra, koniec. Czeœæ.}
{197}{}{To wszystko?}
{198}{}{Dobra, czeœæ.}
{199}{}{By³o nieŸle.}
{200}{}{PA PA.}
{201}{shela11}{Za ma³o mi za to p³ac¹.}
{202}{}{I tak nie by³o warto.}
{203}{}{Jeszcze za mn¹ zatêsknisz.}
{204}{}{Bywaj.}
{205}{}{Szukasz czegoœ?}
{206}{shela12}{Wracaj, kiedy zechcesz.}
{207}{}{Dobra, pa.}
{208}{}{Jasne.}
{209}{}{JA!}
{210}{shela13}{Czeœæ.}
{211}{}{Bywaj.}
{212}{}{PA PA.}
{213}{shela14}{Biorê $}
{214}{}{ za sesjê. P³atne z góry.}
{215}{shela17}{ChodŸ za mn¹.}
{216}{shela18}{Czekam.}
{217}{shela19}{Nie bêdê tu sterczeæ do bia³ego rana.}
{218}{shela20}{Rusz siê wreszcie!}
{219}{shela21}{Ostatnia szansa.}
{220}{shela22}{Trudno. Mam doœæ tego czekania.}
{221}{shela23}{No chodŸ, no chodŸ!}
{222}{shela16}{Napalony czy co?}
{223}{shela24}{ChodŸ za mn¹.}
{224}{shela25}{Hej, koleœ, ³apy z dala od towaru!}
{225}{shela26}{Odwal siê! Co ja jestem - zabawka jakaœ, czy co?}
{230}{shela15}{Eee...? Czy to by³ twój pierwszy raz?}
