{100}{}{Widzisz straaasznie groŸnie wygl¹daj¹cego psa.}
{101}{}{Widzisz Dogmeata.}
{102}{}{Widzisz Dogmeata.}
{103}{dogmt1}{Pies cichutko skamle, gdy dostrzega strój z Krypty. Chyba chce iœæ z tob¹.}
{104}{}{[Zagwizdaj.]}
{105}{}{Nie mogie cie wzi¹æ piesek - mieæ za du¿o ludziów.}
{106}{}{Y y, piesek. Zostaæ.}
{107}{}{ChodŸ, piesku. Czas na odrobinê akcji.}
{108}{}{Nie martw siê, piesku. Wrócê, jak tylko bêdzie w mojej dru¿ynie puste miejsce.}
{109}{}{Przykro mi, Dogmeat. Nie tym razem.}
{110}{dogmt2}{Pies chciwie po³yka iguanê na patyku i spogl¹da na ciebie z wyczekiwaniem.}
{111}{}{[Zagwizdaj.]}
{112}{}{Nie mogie cie wzi¹æ piesek - mieæ za du¿o ludziów.}
{113}{}{Y y, piesek. Zostaæ.}
{114}{}{ChodŸ, piesku. Czas na odrobinê akcji.}
{115}{}{Nie martw siê, piesku. Wrócê, jak tylko bêdzie w mojej dru¿ynie puste miejsce.}
{116}{}{Przykro mi, Dogmeat. Nie tym razem.}
{117}{dogmt3}{Widzisz straaasznie groŸnie wygl¹daj¹cego psa.}
{118}{}{[Zagwizdaj.]}
{119}{}{Nie mogie cie wzi¹æ piesek - mieæ za du¿o ludziów.}
{120}{}{Czekaæ, piesek. Nie ruszaæ.}
{121}{}{OdejdŸ bez s³owa.}
{122}{}{ChodŸ, piesku. Czas na odrobinê akcji.}
{123}{}{Nie martw siê, piesku. Wrócê, jak tylko bêdzie w mojej dru¿ynie puste miejsce.}
{124}{}{Trzymaj siê blisko mnie, w porz¹dku, piesku?}
{125}{}{Dogmeat, staraj siê zachowaæ œredni¹ odleg³oœæ ode mnie.}
{126}{}{Trzymaj siê ode mnie z dala, Dogmeat. Os³aniaj mnie.}
{127}{}{Zostañ, Dogmeat. Zostañ!}
{128}{}{Chyba zostawiê Dogmeata w spokoju.}
{129}{dogmt4}{Dogmeat wydaje ostre szczekniêcie, potem ciche warkniêcie.}
{130}{}{Trzymaj siê blisko mnie, w porz¹dku, piesku?}
{131}{}{Dogmeat, staraj siê zachowaæ œredni¹ odleg³oœæ ode mnie.}
{132}{}{Trzymaj siê ode mnie z dala, Dogmeat. Os³aniaj mnie.}
{133}{}{Zostañ, Dogmeat. Zostañ!}
{134}{}{Dziêki, Dogmeat. Szarik móg³by siê od ciebie uczyæ.}
{135}{dogmt5}{A³uuuuuuuuuuu}
{136}{dogmt11}{A³uuuuuuuuuuu}
{137}{}{Co jest brachu, przypieprzasz siê do mego psiaka.}
{138}{dogmt7}{Grrrrr....}
{139}{}{[Ciekawe, czy uda³oby mi siê namówiæ Dogmeata do pod¹¿ania za mn¹ w jakiœ inny sposób?]}
{150}{dogmt8}{Hau! Hau!}
{200}{}{Popatrz co tu mam dla ciebie, malutki! Niech teraz ktoœ z tob¹ spróbuje zadrzeæ! [Zak³adasz Dogmeatowi Kevlar K9.]}
{201}{}{Masz za ciê¿ki pancerz co, kolego? Pozwól, ¿e go z ciebie œci¹gne. (Œci¹gasz Dogmeatowi Kevlar K9.) }
{300}{dogmt9}{*Skowyt*}
{301}{dogmt10}{A³uuuuuuuuuuu! *skowyt*}
{1110}{dogmt6}{Pies chciwie po³yka zawartoœæ puszki karmy dla psów i spogl¹da na ciebie z wyczekiwaniem.}
