{100}{}{Widzisz mê¿czyznê w skórzanej zbroi.}
{101}{}{Widzisz Kagê.}
{102}{}{Jest ubrany w skórzan¹ zbrojê i ma denerwuj¹cy zwyczaj mówienia o sobie w trzeciej osobie.}
{103}{kaga13}{To ju¿ twoje ostatnie spotkanie z Kag¹.}
{104}{kaga14}{Jak ju¿ Kaga ciê zabije, pójdzie zrównaæ z ziemi¹ ca³e Arroyo.}
{105}{kaga15}{Poczuj gniew Kagi!}
{106}{kaga16}{Jestem Kaga Wielki!}
{107}{kaga17}{Kaga budzi strach w sercach wrogów.}
{108}{kaga18}{Kaga zrobi sobie z twojej g³owy trofeum.}
{109}{kaga19}{Poddaj siê, a twoja œmieræ bêdzie szybka.}
{110}{kaga20}{Kaga jeszcze wróci!}
{111}{kaga21}{Nie mo¿esz zabiæ Wielkiego Kagi!}
{112}{kaga22}{Masz szczêœcie, ¿e Kaga ma teraz wa¿niejsze sprawy gdzie indziej.}
{113}{kaga23}{Kaga jeszcze ciê znajdzie.}
{120}{}{To znowu on, Kaga.}
{150}{kaga1}{[Staje przed tob¹ wysoki, potê¿nie zbudowany wojownik. Patrzy na ciebie, a w jego oczach p³onie nienawiœæ.] Wiêc to tak, wyrzucaj¹ Kagê, a potem okrzykuj¹ CIEBIE Dzieckiem Przeznaczenia? Tak?! Myœlisz, ¿e to ¿e twój dziadek by³ Przybyszem z Krypty cokolwiek tutaj znaczy?! Myœlisz, ¿e Kaga Wielki jest od ciebie gorszy?!}
{151}{}{Có¿, to JA JESTEM, Dzieckiem Przeznaczenia, prawda?}
{152}{}{Hej stój, czekaj chwileczkê. Kto mówi, ¿e jesteœ ode mnie gorszy.}
{160}{kaga2}{Ten tytu³ bêdzie gówno wart kiedy Kaga wyrwie ci g³owê z ramion!}
{161}{kaga3}{¯adne s³owa nie uratuj¹ twojego ty³ka. Wraz z twoj¹ œmierci¹, Kaga odzyska honor. Kaga teraz siê zemœci!}
{200}{}{Brzyyydal?}
{201}{kaga4}{Co!? Wybrali *ciebie* na dziecko przeznaczenia? Cholera, musz¹ byæ naprawdê zdesperowani.}
{202}{}{Ja nie lubieæ. Ty byæ z³y.}
{203}{kaga5}{Kaga nawet nie bêdzie z tob¹ gadaæ. Przygotuj siê na œmieræ z r¹k Kagi!}
