{100}{}{Widzisz mê¿czyznê w pancerzu bojowym.}
{101}{}{Widzisz Kagê w pancerzu bojowym.}
{102}{}{Ma na sobie pancerz bojowy i zdaje siê byæ nieŸle uzbrojony.}
{103}{kaga33}{Tym razem Kaga jest przygotowany na spotkanie z tob¹.}
{104}{kaga34}{Dziecko Przeznaczenia nigdy ju¿ nie wróci do Arroyo!}
{105}{kaga35}{Kaga ciê zmia¿d¿y!}
{106}{kaga36}{Kaga nie lêka siê nikogo!}
{107}{kaga37}{Stój w miejscu, Kaga chce dobrze wycelowaæ.}
{108}{kaga38}{Jeszcze spotkasz Kagê!}
{109}{kaga39}{Nie po raz ostatni widzisz Kagê.}
{110}{kaga40}{Kaga zdecydowanie musi jeszcze trochê potrenowaæ.}
{120}{}{Kaga, idŸ sobie!}
{150}{kaga1}{[Staje przed tob¹ wysoki, potê¿nie zbudowany wojownik. Patrzy na ciebie, a w jego oczach p³onie nienawiœæ.] Wiêc to tak, wyrzucaj¹ Kagê, a potem okrzykuj¹ CIEBIE Dzieckiem Przeznaczenia? Tak?! Myœlisz, ¿e to ¿e twój dziadek by³ Przybyszem z Krypty cokolwiek tutaj znaczy?! Myœlisz, ¿e Kaga Wielki jest od ciebie gorszy?!}
{151}{}{Có¿, to JA JESTEM, Dzieckiem Przeznaczenia, prawda?}
{152}{}{Hej stój, czekaj chwileczkê. Kto mówi, ¿e jesteœ ode mnie gorszy.}
{160}{kaga2}{Ten tytu³ bêdzie gówno wart kiedy Kaga wyrwie ci g³owê z ramion!}
{161}{kaga3}{¯adne s³owa nie uratuj¹ twojego ty³ka. Wraz z twoj¹ œmierci¹, Kaga odzyska honor. Kaga teraz siê zemœci!}
{200}{}{Brzyyydal?}
{201}{kaga4}{Co!? Wybrali *ciebie* na dziecko przeznaczenia? Cholera, musz¹ byæ naprawdê zdesperowani.}
{202}{}{Ja nie lubieæ. Ty byæ z³y.}
{203}{kaga5}{Kaga nawet nie bêdzie z tob¹ gadaæ. Przygotuj siê na œmieræ z r¹k Kagi!}
