{100}{}{Widzisz mê¿czyznê w pancerzu wspomaganym MKII. Nie wygl¹da na przyjaŸnie nastawionego.}
{101}{}{Widzisz Kagê w pancerzu wspomaganym MKII.}
{102}{}{Wielki kawa³ ¿elastwa z rêkoma i broni¹.}
{103}{kaga41}{Mam ju¿ doœæ tego poœcigu. Pora to skoñczyæ.}
{104}{kaga42}{To ju¿ ostatnie twoje spotkanie z Kag¹.}
{105}{kaga43}{Nie masz szans z Kag¹.}
{106}{kaga44}{Przygotuj siê na pobyt w zaœwiatach.}
{107}{kaga45}{Godny by³ z ciebie przeciwnik.}
{108}{kaga46}{Ta czêœæ pustkowi nie potrzebuje takiego dobroczyñcy jak ty.}
{109}{kaga47}{Kiedy Kaga ciê zabijê, bêdzie najgroŸniejsz¹ osob¹ w tej czêœci pustkowi.}
{110}{kaga48}{Kaga nie mo¿e siê ju¿ doczekaæ powrotu do Arroyo... ¿eby puœciæ j¹ z dymem.}
{111}{kaga49}{Kaga bêdzie s³awny za zabicie ciebie.}
{120}{}{Kagaaaaaaaa! Ty têpy chuju!}
{150}{kaga1}{[Staje przed tob¹ wysoki, potê¿nie zbudowany wojownik. Patrzy na ciebie, a w jego oczach p³onie nienawiœæ.] Wiêc to tak, wyrzucaj¹ Kagê, a potem okrzykuj¹ CIEBIE Dzieckiem Przeznaczenia? Tak?! Myœlisz, ¿e to ¿e twój dziadek by³ Przybyszem z Krypty cokolwiek tutaj znaczy?! Myœlisz, ¿e Kaga Wielki jest od ciebie gorszy?!}
{151}{}{Có¿, to JA JESTEM, Dzieckiem Przeznaczenia, prawda?}
{152}{}{Hej stój, czekaj chwileczkê. Kto mówi, ¿e jesteœ ode mnie gorszy.}
{160}{kaga2}{Ten tytu³ bêdzie gówno wart kiedy Kaga wyrwie ci g³owê z ramion!}
{161}{kaga3}{¯adne s³owa nie uratuj¹ twojego ty³ka. Wraz z twoj¹ œmierci¹, Kaga odzyska honor. Kaga teraz siê zemœci!}
{200}{}{Brzyyydal?}
{201}{kaga4}{Co!? Wybrali *ciebie* na dziecko przeznaczenia? Cholera, musz¹ byæ naprawdê zdesperowani.}
{202}{}{Ja nie lubieæ. Ty byæ z³y.}
{203}{kaga5}{Kaga nawet nie bêdzie z tob¹ gadaæ. Przygotuj siê na œmieræ z r¹k Kagi!}
