{100}{}{Widzisz sk¹po odzianego mê¿czyznê.}
{101}{}{Widzisz Kagê.}
{103}{}{Nosi tylko spodnie i wygl¹da jakby by³ z jakiegoœ plemienia.}
{104}{kaga6}{To Kaga powinien byæ "Dzieckiem Przeznaczenia"!}
{105}{kaga7}{Jak œmieli wygnaæ Kagê z Arroyo, wykluczyæ z plemienia.}
{106}{kaga8}{Kaga zemœci siê... na TOBIE!}
{107}{kaga9}{Kaga wyœle ciê na tamt¹ stronê!}
{108}{kaga10}{Jeszcze spotkasz Kagê!}
{109}{kaga11}{Nikt, nigdy wczeœniej nie pokona³ Kagi!}
{110}{kaga12}{Kaga poœwiêci swoje ¿ycie, ¿eby ciê zniszczyæ.}
{150}{kaga1}{[Staje przed tob¹ wysoki, potê¿nie zbudowany wojownik. Patrzy na ciebie, a w jego oczach p³onie nienawiœæ.] Wiêc to tak, wyrzucaj¹ Kagê, a potem okrzykuj¹ CIEBIE Dzieckiem Przeznaczenia? Tak?! Myœlisz, ¿e to ¿e twój dziadek by³ Przybyszem z Krypty cokolwiek tutaj znaczy?! Myœlisz, ¿e Kaga Wielki jest od ciebie gorszy?!}
{151}{}{Có¿, to JA JESTEM, Dzieckiem Przeznaczenia, prawda?}
{152}{}{Hej stój, czekaj chwileczkê. Kto mówi, ¿e jesteœ ode mnie gorszy.}
{160}{kaga2}{Ten tytu³ bêdzie gówno wart kiedy Kaga wyrwie ci g³owê z ramion!}
{161}{kaga3}{¯adne s³owa nie uratuj¹ twojego ty³ka. Wraz z twoj¹ œmierci¹, Kaga odzyska honor. Kaga teraz siê zemœci!}
{200}{}{Brzyyydal?}
{201}{kaga4}{Co!? Wybrali *ciebie* na dziecko przeznaczenia? Cholera, musz¹ byæ naprawdê zdesperowani.}
{202}{}{Ja nie lubieæ. Ty byæ z³y.}
{203}{kaga5}{Kaga nawet nie bêdzie z tob¹ gadaæ. Przygotuj siê na œmieræ z r¹k Kagi!}
