{100}{}{Widzisz bardzo aktywnego staruszka.}
{101}{}{Widzisz Grishama.}
{102}{}{Nie mo¿esz go sobie przypomnieæ, niemniej wygl¹da on dla ciebie znajomo.}
{151}{grish57}{Powiedzia³em ci, ¿e dostanie ci siê!}
{152}{grish58}{Buahahaha!}
{153}{grish59}{OdejdŸ!}
{154}{grish60}{Jestem zajêty!}
{155}{grish61}{Wiedzia³em, ¿e moja córka jest dziwna.}
{156}{grish62}{Ró¿ni ludzie, ró¿ne gusta - jak przypuszczam.}
{157}{grish63}{Chyba siê porzygam.}
{158}{grish64}{Wiedzia³em, ¿e mój syn jest dziwny.}
{159}{grish65}{Chyba teraz jesteœ w mojej rodzinie.}
{160}{grish66}{Opiekuj siê dobrze moj¹ córk¹.}
{161}{grish67}{Opiekuj siê dobrze moim synem.}
{162}{grish1}{Nazywam siê Grisham. Witaj w mojej rzeŸni. Zostawiasz coœ, czy raczej zabierasz?}
{163}{}{Raczej zabieram? Chcê tu zrobiæ pewne zapasy na drogê.}
{164}{}{Nie widzia³eœ przypadkiem, aby le¿a³ gdzieœ tutaj z³oty zegarek?}
{165}{grish2}{Co mogê dla ciebie zrobiæ?}
{166}{}{Chcê kupiæ trochê twojej s³ynnej wêdzonki.}
{168}{}{Czy mo¿esz mi powiedzieæ coœ o rzeŸni?}
{169}{}{Widzê, ¿e susza jeszcze nie wp³ynê³a zbytnio na twój biznes?}
{170}{grish3}{Wiedzia³em, ¿e dasz sobie z tym radê. Wiêc jestem ci winien $1000 za ukoñczenie tej roboty. Niemniej, z powodu twojej nieostro¿noœci pog³owie bramin zmniejszy³o siê o }
{171}{}{ . Licz¹c po $100 za braminê, twoja nagroda wynosi }
{172}{}{. Nie zadawaj sobie trudu, i nie zmyœlaj liczby bramin, które zosta³y zabite - jeden z moich ch³opaków poszed³ za tob¹ i obserwowa³ ciê z ukrycia.}
{173}{}{Nie mówi³eœ nic o obci¹¿aniu mnie w przypadku œmierci jakiejkolwiek braminy!}
{174}{}{Ty wredny, dwulicowy starcu! Argh! Uprzedzam ciê - to jest ostatni raz, gdy zachowujê siê tak grzecznie!}
{175}{}{Dziêki, ojczulku, interesy z tob¹ to przyjemnoœæ.}
{176}{grish4}{Jak œmiesz pokazywaæ tutaj swoj¹ twarz! Przez twoje tchórzostwo straci³em dziesiêæ bramin! Jakkolwiek, jeœli chcesz mi to wynagrodziæ, to myœlê, ¿e $1500 pokry³oby wiêkszoœæ moich strat.}
{177}{}{Te braminy nie by³y warte wiêcej ni¿ $1000.}
{178}{}{Nie mam takich pieniêdzy, a nawet gdyby, to nie dam ich takiemu cwaniakowi, jak ty.}
{179}{}{Pieni¹dze mam w swoim pokoju. Pójdê po nie i zaraz wrócê.}
{180}{grish5}{Ach! Oczywiœcie, oczywiœcie. Zobaczmy, na podró¿... Polecam znane na ca³ym œwiecie paski wêdzonki z bramin. Nie zepsuj¹ siê w podró¿y, a do tego s¹ smaczne. Tylko $10 za paczkê. Nadal zainteresowany?}
{181}{}{Brzmi nieŸle. Daj mi jedn¹ paczkê.}
{182}{}{Na razie dziêki, mo¿e póŸniej. Chcê jednak zadaæ ci kilka pytañ.}
{183}{grish6}{Mi³o siê z tob¹ handlowa³o. Czy jest coœ jeszcze, w czym móg³bym ci pomóc?}
{185}{grish7}{Czekaj! Nie wygl¹dasz mi na przeciêtnego podró¿nika. Nie chcesz zarobiæ paru groszy?}
{186}{grish8}{Nie interesuje ciê ma³y interes? Jestem dziwnie przekonany, i¿ nie stanowi³oby to dla ciebie wiêkszego problemu.}
{187}{}{To zale¿y. Ile, co mam zrobiæ, no i przede wszystkim, ILE?}
{188}{grish9}{Ha! Przypominasz mi samego siebie, kiedy by³em jeszcze m³ody. To proste... parê dzikich psów zesz³o ostatnio za jedzeniem ze wzgórz. Myœlê, ¿e uzna³y braminy za ³atw¹ zdobycz i regularnie w nocy atakuj¹ moje stada. Zmieæ ich watahê z powierzchni ziemi, a zap³acê ci $1000.}
{189}{}{Ukrywasz coœ przede mn¹, starcze. Gdzie jest haczyk?}
{190}{grish10}{Ha! Podobasz mi siê! Wiedzia³em, ¿e nie bêdê w stanie naci¹gn¹æ ciê na cokolwiek. Chodzi o to, ¿e jeœli pozwolisz, aby zginê³a jakakolwiek bramina, to bêdzie ciê to kosztowaæ $100 od sztuki. P³acê dobrze za dobr¹ robotê, ale tak¿e obci¹¿am za straty. To jest ryzyko, które podejmujesz, pracuj¹c dla mnie.}
{191}{grish11}{Œwietnie! IdŸ w nocy na pastwisko i zabij te dzikie psy, które atakuj¹ moje byd³o. Wróæ do mnie, kiedy skoñczysz robotê.}
{192}{grish12}{Do stu tysiêcy beczek z kiszon¹ kapust¹! Cornellius nadal szuka swojego zgubionego zegarka? Dlaczego nie mo¿e siê pogodziæ z tym, ¿e ju¿ go nie ma? Ten cholerny zegarek i tak nigdy nie dzia³a³, a ja jestem wujem braminy, jeœli by³ on naprawdê ze z³ota. Poddaj siê, i tak nigdy go nie znajdziesz.}
{193}{}{Tak naprawdê, to Farrel mnie poprosi³. Dlatego go szukam.}
{194}{}{Czy mogê ci zadaæ kilka pytañ?}
{195}{}{Tak czy inaczej, dziêki, ale poszukam go jeszcze.}
{196}{grish13}{Nie powiedzia³em? Na pewno? Móg³bym przysi¹c, ¿e mówi³em ci o tym. Mo¿e nastêpnym razem, kiedy ktoœ ci zaproponuje pracê, dowiesz siê wszystkich szczegó³ów, zanim j¹ przyjmiesz.}
{197}{grish14}{Hahaha. Zale¿y. Planujesz zostaæ w mieœcie na d³u¿ej? Buahahahaha!}
{198}{grish15}{Widzê, ¿e mo¿na siê z tob¹ dogadaæ. OK - $1000 wobec tego i uznamy to za przyklepane. Podaj mi rêkê na zgodê.}
{199}{}{[Podaj rekê Grishamowi]}
{200}{}{Poczekaj chwilkê. Teraz, gdy o tym pomyœlê, to te braminy wygl¹da³y na nieco wychudzone. Co powiesz na $750, zamiast $1000?}
{201}{}{Zmieniam zdanie: nie chcê ci za nic p³aciæ.}
{202}{grish16}{[Wyszczerza do ciebie zêby.] Dobrze wiedzieæ, ¿e jesteœ osob¹ z charakterem.}
{203}{grish17}{[Grisham robi siê czerwony jak burak i mówi do ciebie przez zaciœniête zêby.] OK, mo¿e byæ $750. Daj mi pieni¹dze!}
{204}{}{Wiesz co, $750 dalej wydaje siê byæ znacznie zawy¿on¹ kwot¹. Te braminy i tak by zdech³y, nawet gdyby nie dopad³y ich te psy. Znaj jednak moja dobroæ. Dam ci $50.}
{206}{grish18}{DOBRA! DAWAJ MI PIENI¥DZE I WYNOŒ SIÊ ST¥D!}
{207}{}{[WyjdŸ bez p³acenia]}
{208}{grish19}{Uwa¿aj na moje s³owa, i tak dostaniesz, co ci siê nale¿y. Jeœli nie ode mnie, to od kogoœ innego.}
{209}{grish20}{[Grisham uœmiecha siê do ciebie w taki sposób, ¿e podœwiadomie cofasz siê o krok] Dlaczego po prostu nie zatrzymasz pieniêdzy przy sobie? Mam przeczucie, ¿e mo¿esz ich potrzebowaæ nieco póŸniej.}
{210}{grish21}{Niewiele mam do opowiadania. Prowadzê rzeŸniê w Modoc. Jeœli chcesz coœ ubiæ, przyprowadzasz to do mnie. Zabijê to dla ciebie i zrobiê z tego doskona³¹, chrupi¹c¹ i aromatyczn¹ wêdzonkê.}
{211}{}{A co ze skór¹ i innymi czêœciami zwierzêcia?}
{213}{grish22}{W sumie, to pomog³o mi to nieco w biznesie. Nikt nie jest w stanie wyhodowaæ wystarczaj¹cej iloœci zbo¿a na paszê dla swoich bramin, wiêc musz¹ oni znacznie pomniejszaæ swoje stada. Ale to tylko tymczasowe. Musisz na to spojrzeæ z szerszej perspektywy. Mój biznes mo¿e tylko ucierpieæ na spadku populacji bramin.}
{215}{grish23}{[Grisham obchodzi ciê dooko³a, szturcha kilka razy, otwiera ci usta i sprawdza zêby] Ach! Piêkny, zdrowy okaz. Nadajesz siê doskonale. Khm... z³e pieski, zabijaj¹ dobre braminy. IdŸ i zabij z³e pieski, dla twojego przyjaciela Grishama. Grisham da duuu¿¹ nagrodê. Zgoda?}
{216}{}{Nie, moja lubiæ pieski. Tylko Ÿli ludzie nie lubiæ piesków. Moja iœæ daleko od z³ego pana.}
{217}{}{Moja zrobiæ. Iœæ tam teraz!}
{218}{grish24}{Doskonale! Pamiêtaj, z³e rzeczy robi¹ "Hau! Hau!". Dobre rzeczy robi¹ "Muu". Staraj siê nie zabijaæ dobrych rzeczy.}
{219}{grish25}{Chyba nie masz chwilowo pieniêdzy. Nie sprzedajê na krechê, i nie wierzê w rozdawanie czegoœ za nic.}
{221}{grish26}{Oto co mam z zatrudniania neandertalczyka. IdŸ ju¿ sobie, sio!}
{222}{grish27}{Eh... chrum iik unga bunga. B¹dŸ dobry neandertalczyk, bierz swoj¹ kasê i wyjdŸ.}
{223}{grish28}{Szybko myœlisz, co? Dobra, jeœli ciê to interesuje, to mo¿esz zabraæ ka¿d¹ czêœæ zwierzêcia. Balthus jest przewa¿nie zainteresowany skór¹, a Rose kupi ka¿de skrawki, których nie chcesz. U¿ywa ich do gotowania zupy i karmienia swoich psów.}
{225}{grish29}{Chyba ¿artujesz. Wszyscy wiedz¹, ¿e to Farrel zabra³ zegarek. Dlaczego mia³by ciê prosiæ o znalezienie go... chyba, ¿e on go wcale nie ukrad³! A mo¿e to jest tylko taka sztuczka, która ma na celu przekonanie wszystkich, ¿e on go nie wzi¹³. Muszê to wszystko przemyœleæ.}
{228}{grish30}{Ch³opcze, nie próbuj nawet siê z tego t³umaczyæ. Nie chcê tego wszystkiego s³uchaæ. Wezwê naszego kaznodziejê, uprawomocnimy to wszystko, a ty opuœcisz nas i zabierzesz ze sob¹ mojego syna.}
{229}{grish31}{Nie mogê powiedzieæ, aby mnie to cieszy³o, niemniej po tym, co zobaczy³em, nie mogê jej pozwoliæ na dalsze mieszkanie w tym domu. Musicie siê pobraæ i wyjechaæ.}
{230}{grish32}{Czy ktoœ mo¿e mi objaœniæ, co tu siê dzia³o z moj¹ córk¹?}
{231}{grish33}{Czy ktoœ mo¿e mi objaœniæ, co tu siê dzia³o z moim synem?}
{232}{}{Pozwól mi to wyt³umaczyæ, ojczulku. Wiesz, to jest tak, ¿e s¹ pszczó³ki i kwiatki... }
{233}{}{Jestem lekarzem i w³aœnie j¹ dok³adnie bada³em.}
{234}{}{Jestem lekarzem i w³aœnie go dok³adnie bada³em.}
{235}{}{To nie jest to, na co wygl¹da.}
{236}{grish34}{Œwietnie. Bêdê mieæ m¹dralê za ziêcia. Có¿, chodŸmy... synu. Miejmy ju¿ to za sob¹.}
{237}{grish35}{Œwietnie. Bêdê mieæ m¹dralê za synow¹. Có¿, chodŸmy... córko. Miejmy to ju¿ za sob¹.}
{238}{grish36}{Hmmm. Wygl¹da³o to tak, jakby moja córka wraz z tob¹ udawa³a braminy podczas okresu rozrodczego.}
{239}{grish37}{Hmmm. Wygl¹da³o to tak, jakbyœcie, ty i mój syn, tañczyli poziome tango wœród przeœcierade³.}
{240}{}{OK, mo¿e to faktycznie by³o to, na co wygl¹da³o. Ale to tylko seks, miedzy nami nie ma ¿adnych uczuæ, ani niczego takiego.}
{241}{grish38}{Doskonale to rozumiem. Te hormony, no i ta specjalna pora roku.}
{242}{}{Cieszê siê, ¿e to rozumiesz.}
{243}{grish39}{Rozumiem. Liczê na to, ¿e wy te¿ rozumiecie, i¿ musicie za siebie wyjœæ. Wiecie, nie mogê pozwoliæ, aby po mieœcie kr¹¿y³y jakieœ plotki. ChodŸmy do naszego duchownego. I nie prowokuj mnie, albo nafaszerujê ciê o³owiem.}
{244}{grish40}{Naprawdê? Wobec tego czemu i ty jesteœ bez ubrania?}
{245}{}{Zarazki? Tak, ZARAZKI! Bardzo wa¿ne jest, aby byæ ca³kowicie czystym podczas tych badañ.}
{246}{grish41}{Có¿, skoro faktycznie jesteœ lekarzem, to wszystko jest w porz¹dku. Lepiej ju¿ siê ubierzcie - z takich nieporozumieñ rodz¹ siê póŸniej najgorsze plotki. Jeszcze jedno - odczuwam ostatnio jakieœ bóle w odbycie - póki tu jesteœ, czy mo¿esz zerkn¹æ na to okiem?}
{247}{}{Emm... póŸniej to obejrzê. Czeka na mnie nastêpny pacjent. Do widzenia.}
{248}{grish42}{Tia. Dlaczego nie pójdziemy po prostu do ksiêdza? Nie próbuj mnie wykiwaæ, albo to ty bêdziesz potrzebowaæ lekarza.}
{260}{grish43}{Wiedzia³em, ¿e sobie z tym poradzisz. Hmm, wiêc jestem ci winien $1000 za ukoñczon¹ robotê. Proszê, oto one.}
{300}{grish68}{Co tu siê, do cholery, dzieje?}
{301}{}{Uuch... Wiêc, proszê pana, ja w³aœnie...}
{302}{grish69}{Zabieraj od niej swoje cholerne ³apska...}
{350}{}{[Patrz¹c na Bessy.] Zostawiam.}
{360}{}{Chcê, abyœ przygotowa³ dla mnie trochê wêdzonki.}
{400}{grish70}{Co tu siê dzieje?}
{402}{grish71}{Cholera jasna! Wiedzia³em, ¿e }
{403}{grish72}{Jak mo¿na by³o tak zhañbiæ moje dziecko! }
{404}{grish73}{Ech, Jo, czy mo¿emy pomin¹æ te nudne kawa³ki?}
{406}{grish74}{Ch³opcze...}
{407}{grish75}{Panienko...}
{410}{grish76}{Nie zmuszaj mnie, aby }
{412}{grish77}{Miria}
{413}{grish78}{Davin}
{414}{grish79}{Yyy, Bo, mo¿emy pomin¹æ tê czêœæ o wi¹zaniu?}
{420}{grish80}{Nigdzie nie pójdziesz, ch³opcze!}
{421}{grish81}{Nigdzie nie pójdziesz, panienko!}
{452}{grish82}{ jest trochê nie tego, ale jest tylko jedna metoda, aby to wszystko wyprostowaæ!}
{453}{grish83}{! Wiesz, ¿e jest tylko jedna metoda, aby to naprawiæ!}
{460}{grish84}{ sta³a siê wdow¹.}
{461}{grish85}{ sta³ siê wdowcem.}
{500}{grish44}{O, ten okaz wygl¹da na ca³kiem dorodny. Powinno byæ z niego sporo dobrej wêdzonki. Wiesz co, powiedzmy, ¿e zatrzymam sobie czêœæ tego miêsa jako zap³atê. Co ty na to?}
{501}{}{Nie ma mowy! Kocham Bess. Nikt nie bêdzie z niej robi³ ¿adnej wêdzonki.}
{502}{}{Jak dla mnie, brzmi nieŸle. Kiedy mogê przyjœæ po moj¹ wêdzonkê?}
{503}{}{Zapomnij o tym, dziadku. Spadam st¹d.}
{510}{grish45}{Ach... nale¿ysz do 'tych'. Nie chcia³bym zabieraæ ci twojej 'przyjació³ki'. Bez niej noce na pustkowiu by³yby zapewne bardzo... samotne. Nie mam na to czasu, mam du¿o roboty do zrobienia.}
{515}{grish46}{Œwietnie! PrzyjdŸ do mnie mniej wiêcej za tydzieñ. Bêdziesz móg³ odebraæ swoj¹ wêdzonkê w wêdzarni, która jest zaraz za rzeŸni¹. Zostawiê j¹ dla ciebie w sakwie. Mi³o by³o z tob¹ robiæ interesy.}
{600}{}{Witaj, }
{601}{}{Hej, przecie¿ to }
{602}{}{Eeeee, on nie ¿yje.}
{603}{}{Eeeee, ona nie ¿yje.}
{604}{}{Przed moim odejœciem Miria by³a jeszcze ¿ywa ale mam przeczucie, ¿e teraz jest ju¿ martwa.}
{605}{}{Przed moim odejœciem Davin by³ jeszcze ¿ywy ale mam przeczucie, ¿e teraz jest ju¿ martwy.}
{606}{}{Davin, eeee, nie móg³ udaæ siê w podró¿ ale kiedy siê tylko z nim zobaczê, to przeka¿ê mu twoje pozdrowienia.}
{607}{}{Miria, eeee, nie mog³a udaæ siê w podró¿ ale kiedy siê tylko z ni¹ zobaczê, to uœciskam j¹ od ciebie.}
{700}{grish47}{Aaach... [Twarz Grishama wykrzywia siê w paroksyzmie bólu, po czym ³apie siê on za serce i pada na pod³ogê]}
{750}{grish48}{Có¿, muszê teraz wróciæ do pracy. Do zobaczenia.}
{800}{}{Uda³o ci siê uratowaæ braminy Grishama.}
{1101}{}{Widzisz wuja Biffa.}
{1155}{grish86}{Wiedzia³em, ¿e moja bratanica by³a jakaœ dziwna.}
{1156}{grish87}{Ró¿ni ludzie, ró¿ne gusta - jak przypuszczam.}
{1157}{grish88}{Cieszê siê, ¿e Grisham tego nie do¿y³.}
{1158}{grish89}{Wiedzia³em, ¿e mój bratanek by³ jakiœ dziwny.}
{1159}{grish90}{Opiekuj siê dobrze moj¹ córk¹.}
{1160}{grish91}{Dobrze siê opiekuj moj¹ bratanic¹.}
{1161}{grish92}{Dobrze siê opiekuj moim bratankiem.}
{1228}{grish49}{Ch³opcze, nawet nie próbuj tego wyjaœniæ. Nie chcê tego s³yszeæ. Idê po kaznodziejê, za³atwimy to zgodnie z prawem, a potem wyjedziesz i zabierzesz ze sob¹ mojego bratanka.}
{1229}{grish50}{Nie mogê powiedzieæ, ¿e nie jestem tym wkurzony, ale muszê zrobiæ to co zrobi³by Grisham. Musicie siê hajtn¹æ i wyjechaæ.}
{1230}{grish51}{Mo¿esz mi wyjaœniæ, co robisz z moj¹ bratanic¹?}
{1231}{grish52}{Mo¿esz mi wyjaœniæ, co robisz z moim bratankiem?}
{1232}{}{Pozwól wyjaœniæ mi to delikatnie, wuju Biffie. S¹ ptaszki i pszczó³ki i widzisz one }
{1236}{grish53}{Œwietnie. Bêdê mia³ teraz cwaniaczka w rodzinie. Có¿... chodŸ bratanku, za³atwmy to szybko.}
{1237}{grish54}{Œwietnie. Bêdê mia³ teraz cwaniaczkê w rodzinie. Có¿... chodŸ bratanico, za³atwmy to szybko.}
{1238}{grish55}{Popatrzmy. Wygl¹da mi na to, ¿e ty i moja bratanica naœladowaliœcie braminy w sezonie parzenia.}
{1239}{grish56}{Popatrzmy. Wygl¹da mi na tu, ¿e ty i mój bratanek odstawialiœcie poziome tango miêdzy przeœcierad³ami.}
{1403}{grish93}{Jak œmiesz plamiæ honor }
{1412}{grish94}{córki mojego brata.}
{1413}{grish95}{syna mojego brata.}
{1600}{}{. Mam nadziejê, ¿e dobrze opiekujesz siê moj¹ córk¹, Miri¹. Ona jest dla mnie œwiate³kiem rozjaœniaj¹cym moje ¿ycie. Pêk³o by mi serce, gdyby coœ mia³o siê jej staæ. Gdzie ona jest, tak przy okazji? Mia³em nadziejê, ¿e znowu siê z ni¹ zobaczê.}
{1601}{}{. Jak tam ci siê ¿yje w ma³¿eñstwie? Widzê, ¿e mój syn, Davin, nie podró¿uje z tob¹. Bardzo mi go brak. Mo¿e kiedy tu wpadniesz nastêpnym razem, to i on móg³by tu przyjœæ razem z tob¹? Staruszek ucieszy³by siê, gdyby móg³ znowu zobaczyæ swojego syna.}
