{100}{}{Widzisz dziwn¹ rzecz - pó³ psa, pó³ maszynê. Chyba jest w³¹czony.}
{101}{}{To Robopies! Ulubiony przyjaciel ka¿dego mê¿czyzny i ka¿dej kobiety!}
{102}{}{Albo jest to jakieœ okropne po³¹czenie psa z maszyn¹, albo maszyna, sprytnie skonstruowana w ten sposób, a¿eby wygl¹da³a zupe³nie jak pies. Trudno powiedzieæ.}
{103}{dogr16}{Ha³! <klik> Hau!}
{104}{dogr17}{...bzzzzzz...}
{105}{dogr18}{Wrrrrr... Nie jestem Szarik.}
{106}{dogr19}{Grrrrrrrrrrrrrrrr...}
{107}{dogr20}{Hau! Ha-ha-ha-<klikk>hau.}
{108}{dogr21}{<sprzzzt> Miauuu... b³¹d.}
{109}{dogr22}{Barkbarkbarkbarkbarkbarkbark!}
{110}{dogr23}{Grrr...}
{111}{dogr24}{Ha³-a³uuuu! <klik-klikk> Auuuuuu!}
{112}{dogr25}{Iiiii! Iiiii! Iiiii!}
{113}{dogr26}{Niebezpieczeñstwo! Niebezpieczeñstwo!}
{114}{dogr27}{Rau! <tik-tik-tik> Rau!}
{115}{dogr28}{<wirrr> Nie ptak, nie szpak, nie bies. Po prostu malutki ja - Robopies!<klik>}
{116}{dogr29}{Rubi-Dubi-Du!}
{117}{dogr30}{Ee-bee-dee-bee-ee-bee-dee-bee!}
{118}{dogr31}{Hau!}
{119}{dogr32}{GRRR-ROF!}
{120}{dogr1}{Arf-arf-arf-arf-arf-arf-arf!}
{121}{}{OK}
{122}{}{Chyba jeszcze nie chcê z tob¹ podró¿owaæ. Do zobaczenia.}
{123}{dogr2}{Ruf? <skacze> Pan?}
{124}{}{Jak siê masz?}
{125}{}{Poczekaj tu a¿ wrócê, dobrze?}
{126}{}{To tyle. Przynajmniej na razie.}
{127}{dogr3}{<klik> [skamle]}
{128}{}{Niewa¿ne.}
{129}{}{OK}
{130}{}{Punkty obra¿eñ:}
{131}{}{Cyberpies nie mo¿e byæ w tym momencie bardziej naprawiony.}
{132}{}{Cyberpies zosta³ nieco naprawiony.}
{133}{}{Cyberpies jest ju¿ ca³kowicie naprawiony.}
{1000}{dogr4}{Hau! Ha-ha-ha-<klikk>hau?}
{1100}{dogr5}{Ha³! <klik> Hau!}
{1200}{dogr6}{Ruf? <skacze> Pan?}
{1300}{dogr7}{<klick> [skamle]}
{1400}{dogr8}{Ha³-a³uuuu! <klik-klikk> Auuuuuu!}
{1500}{}{Ee-bee-dee-bee-ee-bee-dee-bee!}
{1600}{}{Oczywiœcie, ju¿ odk³adam.}
{1700}{}{Arf-arf odleg³oœæ ustawiona na blisk¹.}
{1800}{}{Arf-arf odleg³oœæ ustawiona na œredni¹.}
{1900}{}{Arf-arf odleg³oœæ ustawiona na dalek¹}
{2000}{dogr14}{Wrrrrr... Nie jestem Szarik.}
{2100}{dogr33}{GRRR-ROF!}
{2200}{dogr15}{Hau! Ha-ha-ha-<klikk>hau?}
{2204}{}{W porz¹dku, twoja odleg³oœæ jest na razie dobra.}
