{100}{}{Widzisz cz³owieka ubranego w standardowy pancerz bojowy.}
{101}{}{Wygl¹da zdrowo, ale wydaje siê byæ zdezorientowany.}
{102}{dobbs1}{Och, moja g³owa.}
{103}{}{Kim jesteœ?}
{104}{}{Uga!}
{105}{dobbs2}{Ja... nazywam siê Dobbs... Szeregowy, Pierwszej Klasy.}
{106}{}{Czy mo¿esz mi powiedzieæ, jak siê tu dosta³eœ?}
{107}{}{Bywaj.}
{108}{dobbs3}{By³em na polu bitwy. Tak, bitwy. Wszêdzie by³o s³ychaæ strza³y z karabinów i wybuchy. Umieraj¹cy ludzie. By³em przera¿ony, lecz musia³em nadal walczyæ. Wtedy ujrza³em oœlepiaj¹ce œwiat³o.}
{109}{}{Co siê sta³o potem?}
{110}{}{Do widzenia.}
{111}{dobbs4}{Nastêpn¹ rzecz¹, jak¹ pamiêtam, by³ widok mojego cia³a, jakbym patrzy³ na nie z góry. S³ysza³em, jak lekarze mówi¹, ¿e nie ¿yje i rzucili moje cia³o na stos innych cia³.}
{112}{}{I co wtedy?}
{113}{}{Bywaj.}
{114}{dobbs5}{Jacyœ ludzie przyszli i zabrali moje cia³o do laboratorium. S³ysza³em, jak mówili, ¿e spróbuj¹ zregenerowaæ moje cia³o zanurzaj¹c je w czymœ, co nazywali ¯elem Biomedycznym.}
{115}{}{Coœ jeszcze?}
{116}{}{Bywaj.}
{117}{dobbs6}{Wtedy obudzi³em siê tu. Muszê iœæ! Muszê wróciæ do swojej jednostki.}
{118}{}{Bywaj.}
{200}{dobbs7}{Do widzenia?}
{201}{dobbs8}{Boli mnie g³owa.}
{202}{dobbs9}{Dlaczego jestem pokryty tym gównem?}
{300}{dobbs10}{Muszê powróciæ do oddzia³u.}
{301}{dobbs11}{O nie! Jestem na samowolce!}
{302}{dobbs12}{Którêdy na liniê frontu?}
{303}{dobbs13}{To dla ciebie, Jonny.}
{400}{}{Szeregowy Dobbs cierpi na Syndrom Post-Kriogeniczny.}
