{100}{}{You see a slave.}
{101}{}{You see Vic.}

{150}{}{This slave seems to be kept under tight surveillance.}
{151}{}{This is Vic.}
{152}{}{[TALK]}

# Node 1
{153}{vic1}{Would you tell him I can't... wait. Who are you? You're not a
 slaver. What are you doing here?}
{154}{}{My name is }
{155}{}{. I'm here to get you out.}
{156}{}{I'm }
{157}{}{, but why have you been locked in this room?}
{158}{}{Can you tell me where Vault 13 is?}
{159}{}{I'm }
{160}{}{. I'll be right back.}
{161}{}{Dubba iba }
{162}{}{.}

# Node 2
{163}{vic2}{Metzger's still quite upset with me, even though we fixed his darn radio.
 He's threatening to sell me off! I'll do anything you ask if you can get me out
 of this mess.}
{164}{}{OK, I will.}
{165}{}{Sorry, I can't. Bye.}
{166}{}{Whoo.}

# Node 3
{167}{vic3}{Oh, hi again. This darn radio isn't going to repair itself. How does
 he expect me to fix it?}
{168}{}{Where can I get the parts?}
{169}{}{Maybe I can repair it.}
{170}{}{Can you use this radio I found?}
{171}{}{I'll see what I can do.}
{172}{}{Spa pa?}

# Node 4
{173}{vic4}{I know I can do it, I just need some spare parts. There is an old radio in
 my shack back in Klamath that has exactly what I need. You been to the Dunton's?
 My shack's... well, it was just east of their place.}
{174}{}{Do you mean this radio?}
{175}{}{I'll go look for it.}
{176}{}{Hmmm... I'll be back.}

# Node 4b
{206}{vic12}{It's right here. [pointing to a map]}

# Node 5
{177}{vic5}{That's great! I'll have the radio fixed in no time.}
{178}{}{Okay, I'll talk to Metzger.}

# Node 6
{179}{vic6}{Thanks.}
{180}{}{Bye.}

# Node 7
{181}{vic7}{Pardon? I'm sorry but I don't understand.}
{182}{}{hurm.}

# Node 8
{183}{vic8}{Thank you! I'm forever in your debt. What can I do to repay you?}
{184}{}{Tell me where Vault 13 is.}
{186}{}{Come with me, I could use a hand.}
{187}{}{It was nothing. Good bye.}
{188}{}{Candy?}

# Node 9
{189}{vic9}{Vault 13? There's a Vault City east of here. I trade there,
 sometimes.}
{190}{}{Want to go there with me?}
{191}{}{Thanks. Bye.}

# Node 10
{192}{vic10}{Sure, I'll join up with you! This old fart has one big adventure left
 in him. I'm sure of it! I'm pretty good at repairing things too, despite what
 Metzger says.}
{193}{}{Great, let's go.}
{194}{}{Welcome aboard.}
{195}{}{Whatever.}
{196}{}{Vic me bess frend.}

# Node 11
{197}{}{Want to join me on my search?}
{198}{}{Great! Thanks.}

# Node 12 OLD IF IN PARTY. REMOVED NODE. Lines 199, 200, 202 (Don't know where 201 is)

# Node 13
{203}{vic11}{Vault City is east of here. I'll point it out on that map of yours.}
{204}{}{Thanks.}

# Node 14
{220}{vic13}{Darn it. That's close, but I need the radio from my shack in Klamath. I know that one has the parts I need.}

# used in node 12 REMOVED 230 that was here. Node 12, removed. was What else do you need to know?

# Node 15
{300}{vic14}{Yeah, I can probably help you, but you've got to get me out of here first.}
{301}{vic15}{I told you. If you can get me out of here, I'll help you with anything you want.}
{302}{}{How do we do that?}
{303}{}{You're on you own then.}
{304}{}{Okay, I'll see what I can do.}

# Node 2b
{350}{vic117}{You think you can help me out?}
{351}{vic118}{Metzger still won't let me leave.}
{352}{vic119}{I can't take much more of this.}
{353}{vic120}{I'll do anything for you if you help me.}
{354}{vic121}{I'll earn back any expenses you may incur!}

# 3b
{400}{vic16}{You haven't been by my place yet have you? I really need that radio,
 Metzger's getting angrier with me by the day.}

# water flask question, Question used in Node 9 and Node 1010
{450}{}{Where did you get this water flask?}
{451}{}{I had a water flask that had a big yellow 13 on it. Do you remember where you got it?}

# Additions to Node 11
{500}{vic17}{Oh, yeah. I remember that. I bought that from Ed. He's a brahmin dealer over in Vault City.}
{501}{vic18}{Water Flask? Oh, wait. Yea, I had a few dozen of'm. Sold pretty well. I got'm from Ed, a
 brahmin dealer over in Vault City.}
{502}{}{Vault City?}

# Node 1000, if said Boss many times.
{550}{}{Would you stop calling me Boss?}

# Node 16
{600}{vic19}{Sure thing, Chief!}
{601}{}{I mean it! STOP IT!}
{602}{}{I guess that'll have to do.}

# Node 17
{650}{vic20}{You got it, Sport!}
{651}{}{Uggg!}

{700}{}{Bee my friend.}

# Node 1b - Added a line to node 1 for Vic
{710}{vic21}{Would you tell him I can't fix this without the parts. I don't know... wait.
 Who are you? Some new recruit? He didn't send you here to rough me up again did
 he? It's not going to make any difference. I can't fix it here.}

# 20. Here to get you out. (From 1)
{750}{vic22}{Wow! You'd do that for me? I'd do anything if you could get me out this mess.
 Only problem is that Metzger's got me locked up here until I fix this radio and
 I don't have the parts I need.}
{753}{}{Where can I get the parts you need?}
{754}{}{I'll see what I can do.}

# 21. Why in this room? (From 1)
{760}{vic23}{It's a long story. I guess you could say that Metzger's keeping me here until
 I fix this darn radio. The crystal's shot and I don't have any spare parts. How does
 he expect me to fix it?}
{761}{}{Well, I'm here to get you out.}
{764}{}{Don't know. See ya.}

# 22. How do we do that?
{800}{vic24}{I've got to get this radio fixed. If you can help me do that, then maybe we can reason with him.}
{801}{}{How can I help?}
{803}{}{I doubt it. Good luck.}

# 23. In Mom's, never joined party. (From WTG)
{810}{vic25}{Why'd you kill poor Mom... I guess you had your reasons... I'm sorry, Boss. It's not my place to question you. This is a pretty bad town. I'm sure she did something pretty bad.}
{811}{vic26}{Hey, Boss. Thanks for getting me out of that mess with Metzger. You need anything? Mom's been kind enough to feed me while you've been gone. I help her around the place...}
{812}{}{Bye.}
{813}{}{Oooh.}
{814}{}{Beiye}

# Additions to Node 9
{823}{}{Where is your friend Ed, again?}

# Additions to Node 10
{830}{vic27}{I would if I could, but you're just not looking good. I'd only be a burden. Now that Mom's gone, I think I'll just head out. Don't know where... maybe we'll see each other again. Thank you for everything you've done for me.}
{831}{vic28}{I would if I could, but you're just not looking good. Looks like you can barely take care of yourself. I'd only be a burden. I'll just wait here, Mom's cooking reminds me of my ex-wife...}
{832}{vic29}{I would, honest. I'd do almost anything for you. It's just that you don't look like you're in any shape to lead anyone. I'd only be a burden. I'll just head over to Mom's, in a bit... until you can work things out. I haven't had her home cooking for a long time.}
{833}{vic30}{Sorry, Boss. Looks like you're pretty crowded. Now that Mom's gone, I think I'll just head out. Don't know where... maybe we'll see each other again. Thank you for everything you've done for me.}
{834}{vic31}{You're looking a bit crowded, Boss. I'll just wait here for you until you've worked things out. Mom's cooking reminds me of my ex-wife... not sure if that's a good thing or bad thing...}
{835}{vic32}{I would love to, Boss. It's just that you don't look like you have any more room. I'll just head over to Mom's. I haven't been there in a while. Just come get me if you find some room for me.}

# Additions to Node 11
{840}{vic33}{Ed's over at Vault City. He's a Brahmin Dealer. He was just one of my many suppliers. Vault City's not too far from here.}

# Additions to Node 13
{845}{vic34}{I told you, it's over here. [Vic points to a location on your Pip-Boy 2000.]}

{900}{}{You learned about Vic being a trader.}

# 1000 in party dialog
{1000}{}{I need to ask you something.}

# 1001 After healing
{1100}{vic35}{Fully healed, Boss. Anything else?}
{1200}{vic36}{Almost perfect condition, Boss.}
{1300}{vic37}{I'm mostly healed up, Boss, but I've been better.}
{1400}{vic38}{I tried, Boss, but I'm not doing so hot. I'll do what I can though.}

# 1002 I need you to wait here until I come back
{1500}{vic39}{Whatever you say, Boss.}
{1501}{vic40}{Here? Right here? Okay, you're the Boss.}
{1502}{vic41}{Right. I'll stay here until you come back, Boss. You will come back, right?}
{1503}{vic42}{As long as you want. I'm not going anywhere.}
{1504}{vic43}{Of course, Boss.}

# 1003 Put your weapon away.
{1600}{vic44}{If you say so.}
{1601}{vic45}{Good call Boss.}
{1602}{vic46}{Great thinking, Boss.}
{1603}{vic47}{Sure, Boss. Anything else?}
{1604}{vic48}{Away it is, Boss.}
{1605}{vic49}{No problem, Boss.}
{1606}{vic50}{Done, Boss.}

# 1004 Stay close to me
{1700}{vic51}{Sure, Boss.}
{1701}{vic52}{Close it is, Boss.}
{1702}{vic53}{You know best, Boss.}
{1703}{vic54}{I'm right behind ya, Boss.}
{1704}{vic55}{Like glue, Boss.}
{1705}{vic56}{If you say so, Boss.}
{1706}{vic57}{Oh. Okay, Boss.}

# 1005 Don't get too far away.
{1800}{vic58}{OK, I'll keep my distance, but not too far, Boss.}
{1801}{vic59}{Okay, I won't, Boss.}
{1802}{vic60}{I'll just stay back a little then, Boss.}
{1803}{vic61}{Sure, Boss.}

# 1006 We should spread out a bit
{1900}{vic62}{Right Boss. I'll hang way back.}
{1901}{vic63}{What ever you say, Boss.}
{1902}{vic64}{There you go, Boss.}
{1903}{vic65}{Standing back, Boss.}
{1904}{vic66}{Backing away, Boss.}
{1905}{vic67}{Spreading out, Boss.}
{1906}{vic68}{Okay, Boss.}

# 1100a Rejoin: Crowded
{2000}{vic69}{Uh, Boss? You seem a bit crowded. I'll just keep waiting here for ya.}

# 1100b Rejoin: Additional NPC response, PC Charisma 1
{2100}{vic198}{You're scaring me, Boss. What's happened to you? You look... well,
 scary. I think I'll just hang out here for a while...}

# 1100c Rejoin:
{2200}{vic70}{You bet, Boss!}
{2201}{vic71}{Darn right I will, Boss.}
{2202}{vic72}{Sure thing, Boss.}
{2203}{vic73}{Ready to go when you are, Boss.}
{2204}{vic74}{Great! Let's go.}
{2205}{vic75}{Great!}
{2206}{vic76}{You're the best, Boss!}
{2207}{vic77}{You won't be disappointed. No more mistakes!}
{2208}{vic78}{I'll be careful this time, don't you worry!}
{2209}{vic79}{I knew you would forgive me for that... um. So, uh, Boss. What's the plan?}
{2210}{vic80}{I won't let you down, Boss!}
{2211}{vic81}{You're super, Boss!}
{2212}{vic82}{I knew I wasn't too old for this. Those were just bad odds! Right, Boss?}

# 1007 Vault 13 Flask?
{2300}{vic83}{From Ed. He's a brahmin dealer over in Vault City. You been there before?
 Let me show you on that map thing of yours.}

# 1008 Where's Ed again? Not Marked
{2305}{vic199}{Vault City. Here. Let me show you on that fancy map thing of yours.}

# 1009 Where's Ed again?
{2310}{vic84}{He should be around here somewhere.}
{2311}{vic85}{Vault City. Check that fancy map thing of yours.}

# 1010 Other Questions
{2403}{}{Where did you get the Vault 13 water flask?}
{2404}{}{Never mind.}

# 1011 Other questions greeting (From 1000)
{2500}{vic86}{Sure, Boss.}
{2501}{vic87}{Ask anything, Boss.}
{2502}{vic88}{I'll help you if I can, Boss.}
{2503}{vic89}{I'm not in trouble am I, Boss?}
{2504}{vic90}{Did I do something wrong, Boss?}
{2505}{vic91}{Of course.}

# 1012 Standard Greeting, (WTG) Moved From Node 1000
{2600}{vic92}{What'll we do now, Boss?}
{2601}{vic93}{What's the plan, Boss?}
{2602}{vic94}{Doing my best, Boss.}
{2603}{vic95}{What can I do for you, Boss?}
{2604}{vic96}{Change of plans, Boss?}
{2605}{vic97}{Different strategy, Boss?}

# 1013 Crippled
{2700}{vic98}{Boss, they got me good. You've got to get me to a doctor. I don't know if I can
 back you up anymore.}
{2701}{vic99}{I need a doctor, Boss. I'm really messed up. I don't know if I can fight
 with you anymore.}
{2702}{vic100}{Boss, I'm really messed up. You got to get Lenny to check me out.}

# 1014 Waiting
{2800}{vic101}{Hey, Boss. You want me to join up with you now?}
{2801}{vic102}{Hey, Boss. I don't mind waiting for you. I'm a real patient man.}
{2802}{vic103}{We joining up again, Boss? I'll try harder.}
{2803}{vic104}{I was afraid you might not come back. It sure is nice to see you again, Boss.}
{2804}{vic105}{You looking for company again?}
{2805}{vic106}{I'm ready to go, Boss.}
{2806}{vic107}{I knew you wouldn't leave me.}
{2807}{vic108}{Need some back up?}
{2808}{vic109}{Need something repaired, don't you? I'm your man, Boss!}
{2809}{vic110}{Don't worry, Boss. Sulik and I'll get along, honest.}
{2810}{vic200}{Let's go.}
{2811}{vic201}{Stay here. I'll be right back.}
{2812}{vic202}{Me go.}

# 1017 Remove armor: Yes
{3100}{vic111}{What? Uh... okay, Boss. If you say so.}
{3101}{vic112}{Can I put something else on, Boss? I'm a little worried.}
{3102}{vic113}{Okay... you're not going to leave me here... Are you, Boss?}
{3103}{vic114}{But... I mean... Of course, Boss. Coming right off.}

# 1018 Best Weapon
{3200}{vic115}{Well, Boss... I'm pretty good with small arms. I can handle almost any rifle, shotgun, and most small-medium pistols. I 'can' use knives. I've also got a pretty good throwing arm, but my aim's not the best in the world... actually, it's pretty horrible. Sorry, Boss. I'm really trying to get better.}
{3201}{vic116}{Like I said, Boss, I prefer small arms. I can handle almost any rifle, shotgun, and most of those small-medium pistols. If we're really in a pinch I can try using a knife or even thrown weapons.}

# 1019 Other weapons he can use.
{3300}{vic203}{I 'can' use knives and I've got a pretty good throwing arm, but... my aim's not the best in the world. Actually it's pretty horrible. Sorry, Boss. I'm really trying to get better.}
{3301}{vic204}{Like I said, Boss. Knives and I've got pretty good throwing arm... I just miss a lot.}

# 1020 Hostile
{3400}{vic122}{I've had it up to here!}
{3401}{vic123}{I'm going to rip your darn head off! No one hurts my family!}

# 1101 Vic's being Pushed
{4000}{vic124}{Over here?}
{4001}{vic125}{This better Boss?}
{4002}{vic126}{How 'bout here?}
{4003}{vic127}{Yes Boss.}
{4004}{vic128}{What?}
{4005}{vic129}{Where we going?}
{4006}{vic130}{We leaving Boss?}
{4007}{vic131}{I'm moving.}
{4008}{vic132}{Sorry Boss.}
{4009}{vic133}{Better?}
{4010}{vic134}{Ooof.}
{4011}{vic135}{How's this Boss?}
{4012}{vic136}{I'll stand over here.}
{4013}{vic137}{I'll just move over here now.}

# 1102 BGF: Crippled
{4100}{vic138}{Boss! I'm not doing so well here.}
{4101}{vic139}{I need a doctor.}
{4102}{vic140}{Oh, boy. This really hurts.}
{4103}{vic141}{Ow!}
{4104}{vic142}{Ouch.}
{4105}{vic143}{Dang it.}
{4106}{vic144}{Medic?}
{4107}{vic145}{I'm hanging in there... barely.}

# 1103 Removed

# 1104 BGF: Random on Specific Map
{4200}{vic146}{I never liked this place.}
{4201}{vic147}{Why is this place so clean?}
{4202}{vic148}{Do you smell something, Boss?}
{4203}{vic149}{You know, Boss. I don't think I'll be coming back here when we're through. I can no longer call it home.}
{4204}{vic150}{It sure is a lot dirtier than I remember.}
{4205}{vic151}{We're not staying here long, are we Boss?}
{4206}{vic152}{This place'll never change.}
{4207}{vic153}{Boss, I'm not going to miss this place.}
{4208}{vic154}{Thanks again for getting me out of this place, Boss.}
{4209}{vic155}{I really owe you one, Boss.}
{4210}{vic156}{Wow, this place sure has changed.}
{4211}{vic157}{I haven't been here in ages.}
{4212}{vic158}{I'm going to retire here.}
{4213}{vic159}{I could open a repair shop around here.}

# 1105 BGF: for specific area on a map
{4300}{vic160}{Ah, a sight for sore eyes. This is... was my place, but I guess you knew that. Right, Boss?}

# 1106 Removed

# 1107 BGF: with Specific NPC
{4400}{vic161}{Sulik, don't you be looking at me like that.}
{4401}{vic162}{Boss, Sulik's glaring at me again.}
{4402}{vic163}{Nice pooch.}

# 1108. BGF: Level Up, Not to be Placed in MSG file

# 1109. BGF: Waiting
{4500}{vic164}{La de da...}
{4501}{vic165}{Ho hum.}
{4502}{vic166}{Waiting for the Boss...}
{4503}{vic167}{I'm waiting for the Boss.}
{4504}{vic168}{Just waiting.}
{4505}{vic169}{The Boss sure wouldn't leave me behind...}
{4506}{vic170}{Knock Knock... who's there... wait. How'd that go...}
{4507}{vic171}{Still waiting.}
{4508}{vic172}{What's that smell?}
{4509}{vic173}{Anything to repair around here?}
{4510}{vic174}{Here I am... waiting for the Boss.}
{4511}{vic175}{An old man like me, wasting away his talents, just standing here.}
{4512}{vic176}{I sure wish I had a stick of gum... it's been decades.}
{4513}{vic177}{I need to get out of the relic business... nothing but trouble.}
{4514}{vic178}{Why is waiting so tiring...}

# 1110. PC used Healing on PC
{4600}{vic179}{Uh, thanks, Boss.}
{4601}{vic180}{Thanks.}
{4602}{vic181}{You sure you know what you're doing?}
{4603}{vic182}{Can't we just rest instead?}
{4604}{vic183}{Should we make camp?}
{4605}{vic184}{Am I that bad off?}

# 1111. PC used Drugs on NPC
{4700}{vic185}{Not too much, Boss.}
{4701}{vic186}{If you insist, Boss.}
{4702}{vic187}{Boss, my head's not going to explode, is it?}
{4703}{vic188}{Boss, I think I'm starting to like that stuff.}
{4704}{vic189}{I'm feeling a bit funny, Boss.}
{4705}{vic190}{You sure you have enough of that to spare.}
{4706}{vic191}{Sure, Boss. I'll take some.}
{4707}{vic192}{Thanks, Boss.}
{4708}{vic193}{Not bad.}

{5000}{vic194}{I'm a bit hungry at the moment. We'll talk again at Mom's.}

#added by killap - NPC info
{5500}{vic195}{I feel like I broke a limb, Boss. You better have a look.}
{5501}{vic196}{I feel like I am burning up, Boss. You better have a look.}
{5502}{vic197}{I feel like I have been poisoned, Boss. You better have a look.}
