{100}{}{You see a man wearing minimal clothing.}
{101}{}{You see Kaga.}
{103}{}{He is wearing pants and looks like he came from a tribe.}
{104}{kaga6}{I should have been the Chosen One!}
{105}{kaga7}{How dare Arroyo cast me out of the tribe.}
{106}{kaga8}{I will have my revenge on you!}
{107}{kaga9}{Kaga will send you to the next life.}
{108}{kaga10}{We will meet again!}
{109}{kaga11}{I have never been beaten before!}
{110}{kaga12}{I will dedicate myself to your destruction.}

#added by RP 1.3
{150}{kaga1}{[A tall and powerfully built warrior stands before you, his eyes blaze with hatred as he looks you over.] So, they cast out Kaga, then deem YOU the Chosen One? Ha! You think being the grandchild of the Vault Dweller makes you special?! You think you are better than I, Kaga the Great?!}
{151}{}{Well, I AM the Chosen One, aren't I?}
{152}{}{Hey now, hold on a second. I never said I was better than you.}

{160}{kaga2}{That title will mean nothing when Kaga rips the head from your shoulders!}
{161}{kaga3}{No words can save your hide. With your death, Kaga's honor shall be restored. Kaga will now take his vengeance!}

#dumb dialogue
{200}{}{Ooglie?}
{201}{kaga4}{What!? They picked *you* to be the Chosen One? Oh my, they've become desperate.}
{202}{}{Me no likie. U lookie bad.}
{203}{kaga5}{Kaga won't even bother speaking with you further. Prepare to die at the hands of Kaga!}
