{100}{}{You see a man wearing leather armor.}
{101}{}{You see Kaga.}
{102}{}{He is wearing leather armor and has an annoying habit of talking about himself in the third person.}
{103}{kaga13}{This will be the last time Kaga meets you.}
{104}{kaga14}{After Kaga kill you, he will burn Arroyo to the ground.}
{105}{kaga15}{Feel the wrath of Kaga!}
{106}{kaga16}{I am the great Kaga!}
{107}{kaga17}{Kaga is to be feared by all.}
{108}{kaga18}{Kaga will have your head for a trophy.}
{109}{kaga19}{Surrender and your death will be quick.}
{110}{kaga20}{Kaga will be back!}
{111}{kaga21}{You cannot kill the great Kaga!}
{112}{kaga22}{You are lucky Kaga has business elsewhere.}
{113}{kaga23}{Kaga will meet you again.}

{120}{}{It's that Kaga guy again.}

#added by RP 1.3
{150}{kaga1}{[A tall and powerfully built warrior stands before you, his eyes blaze with hatred as he looks you over.] So, they cast out Kaga, then deem YOU the Chosen One? Ha! You think being the grandchild of the Vault Dweller makes you special?! You think you are better than I, Kaga the Great?!}
{151}{}{Well, I AM the Chosen One, aren't I?}
{152}{}{Hey now, hold on a second. I never said I was better than you.}

{160}{kaga2}{That title will mean nothing when Kaga rips the head from your shoulders!}
{161}{kaga3}{No words can save your hide. With your death, Kaga's honor shall be restored. Kaga will now take his vengeance!}

#dumb dialogue
{200}{}{Ooglie?}
{201}{kaga4}{What!? They picked *you* to be the Chosen One? Oh my, they've become desperate.}
{202}{}{Me no likie. U lookie bad.}
{203}{kaga5}{Kaga won't even bother speaking with you further. Prepare to die at the hands of Kaga!}


