{100}{}{You see a strange half-dog, half-metal thing. It appears to be activated.}
{101}{}{It's Robodog! Everybody's favorite pet!}
{102}{}{Either this thing is some horrible stitched together combination of dog and machine or it's all machine, cunningly done to look like a dog. It's hard to tell.}
{103}{dogr16}{Arf! <click> Woof!}
{104}{dogr17}{...bzzzzzz...}
{105}{dogr18}{.whirrrrr... I am not a Daggit.}
{106}{dogr19}{Grrrrrrrrrrrrrrrr--}
{107}{dogr20}{Woof! Wo-wo-wo-<click>woof.}
{108}{dogr21}{<sprzzzt> Meow... error.}
{109}{dogr22}{Barkbarkbarkbarkbarkbarkbark!}
{110}{dogr23}{Grrr...}
{111}{dogr24}{How-woooo! <click-click> How-wooo!}
{112}{dogr25}{Yipe! Yipe! Yipe!}
{113}{dogr26}{Danger! Danger!}
{114}{dogr27}{Rowf! <tick-tick-tick> Rowf!}
{115}{dogr28}{<whirrr> Not bird, nor plane, nor even frog, just lil' old me - Robodog!<click>}
{116}{dogr29}{Rooby-Doo!}
{117}{dogr30}{Ee-bee-dee-bee-ee-bee-dee-bee!}
{118}{dogr31}{Woof!}
{119}{dogr32}{GRRR-ROWF!}
{120}{dogr1}{Arf-arf-arf-arf-arf-arf-arf!}
{121}{}{OK}
{122}{}{I don't think I want to rejoin you just yet. Goodbye.}
{123}{dogr2}{Rowf? <boing> Raggy?}
{124}{}{How are you?}
{125}{}{I need you to wait here until I come back.}
{126}{}{That's it for now.}
{127}{dogr3}{<click> whimper}
{128}{}{Never mind.}
{129}{}{OK}
{130}{}{HP:}
{131}{}{Cyberdog can't be repaired anymore at this time.}
{132}{}{Cyberdog has been repaired some.}
{133}{}{Cyberdog is all fixed now.}

#specific party messages
{1000}{dogr4}{Woof! Wo-wo-wo-<click>woof?}
{1100}{dogr5}{Arf! <click> Woof!}
{1200}{dogr6}{Rowf? <boing> Raggy?}
{1300}{dogr7}{<click> whimper.}
{1400}{dogr8}{How-woooo! <click-click> How-wooo!}
{1500}{dogr9}{Ee-bee-dee-bee-ee-bee-dee-bee!} #Wait here resoponse
{1600}{dogr10}{Sure thing, I'll put it away.}  #Put weapons away
{1700}{dogr11}{Arf-arf proximity set to close.} #Close
{1800}{dogr12}{Arf-arf proximity set to medium.} #Medium
{1900}{dogr13}{Arf-arf proximity set to far.} #Far
{2000}{dogr14}{.whirrrrr... I am not a Daggit.}
{2100}{dogr33}{GRRR-ROWF!}
{2200}{dogr15}{Woof! Wo-wo-wo-<click>woof?}

{2204}{}{Ok, you're at a good distance for now.}
