{100}{}{Vedi un fantasma!}
{101}{}{Vedi Anna, il fantasma.}
{150}{}{Questo e' un fantasma. Non e' certo una cosa che si vede tutti i giorni.}
{151}{}{Sembra che qualcosa la tormenti.}
{152}{}{[PARLA]}
{153}{anna1}{Oh, che dolore! Brucia cosi' tanto!}
{154}{}{Cosa ti affligge?}
{155}{}{Chi sei?}
{156}{}{Vade retro, spirito maligno!}
{157}{anna2}{Mi fermo e busso ad ogni porta, ma nessuno arriva, nessuno sente.}
{158}{}{Io posso sentirti. Che cosa ti affligge?}
{159}{}{Penso che dovreste spegnere il vostro Stealth Boy, signora.}
{160}{anna3}{Dov'e'? Non riesco a trovarlo! Sono perduta! Oh...}
{161}{}{Che cosa stai cercando? Forse ti posso aiutare.}
{162}{}{Dovresti davvero smetterla di mugugnare e di lamentarti e iniziare a dire qualcosa di sensato.}
{163}{anna4}{Il mio medaglione! E' sparito. Ladro! Ladro!}
{164}{}{Whoa, sono appena arrivato. Non l'ho rubato io.}
{165}{}{Posso aiutarti a trovarlo?}
{166}{anna5}{Oh, fato crudele.}
{167}{}{Non puoi sentirmi, vero?}
{168}{}{A dopo, ragazza fantasma.}
{169}{}{Ci vediamo. Cerchero' di aiutarti.}
{170}{anna6}{Il mio medaglione! Dammelo!!! Oh!!!!}
{171}{}{Scordatelo! Va' all'inferno. L'ho trovato e me lo tengo.}
{172}{}{OK. Eccolo.}
{173}{}{Ecco. Possa tu riposare in pace.}
{174}{}{OK.}
{175}{}{No.}
{176}{anna7}{Il mio medaglione, il mio medaglione! Sto arrivando, papa'! Sto arrivando!}
{177}{}{Arrivederci.}
{178}{}{Aspetta! Non andare!}
{179}{}{Va' verso la luce.}
{200}{anna8}{Dove puo' essere?}
{201}{anna9}{Ohhh.}
{202}{anna10}{Mamma? Papa'? Dove siete?}
{203}{anna11}{Non riesco a trovarlo!}
{500}{anna12}{Mamma... Papa'... Sto arrivando...}
{501}{anna13}{E' tutto cosi' luminoso...}
{502}{anna14}{Nonna, posso vederti...}
{503}{anna15}{Oh, ma voi siete il gentile signor Cain! E' bello rivedervi...}
{550}{}{La casa e' vuota.}
{551}{}{Nostro Signore, belle ossa.}
{560}{}{ACCHIAPPAFANTASMI!}
{561}{}{Ug.}
