{100}{}{Vedi una giovane donna molto attraente.}
{101}{}{Vedi Rebecca.}
{150}{}{Vedi Rebecca, la proprietaria del Becky's Casino Bar.}
{200}{rbcca1}{Ehila', io sono Rebecca. Posso prepararti qualcosa da bere? Sicuramente sarai assetato, dopo aver viaggiato nelle Lande.}
{201}{rbcca2}{Ehi! Vuoi da bere o sei tornato solo per salutare?}
{202}{rbcca3}{Ciao! Sono felice che tu sia tornato. Hai delle domande da farmi o sei qui per un po' di buon whiskey?}
{203}{rbcca4}{Mi fa davvero piacere vederti. Come va? Ti serve qualcosa?}
{204}{rbcca5}{Spero che vada tutto bene al mio cliente preferito! Cosa posso fare per te, oggi?}
{205}{rbcca6}{Ciao!}
{206}{rbcca7}{E' sempre bello rivederti.}
{207}{rbcca8}{Ciao! Vuoi qualcosa da bere? Qui serviamo il miglior whiskey della regione!}
{208}{rbcca9}{Ehila'!}
{209}{rbcca10}{Sei tu! Lo sapevo. Cosa ne dici di un drink, zuccherino mio?}
{210}{rbcca11}{Sei tornato per il grande divertimento che il locale di Rebecca ti offre o per il suo whiskey famoso in tutto il mondo?}
{211}{rbcca12}{Bentornato al Casino' Bar di Rebecca. Come posso aiutarti?}
{212}{rbcca13}{Salve. Come posso aiutarti?}
{213}{rbcca14}{Cosa desideri oggi? Che ne dici di un drink?}
{214}{rbcca15}{Cosa vuoi che ti serva oggi? Un drink, o preferisci qualcos'altro?}
{215}{rbcca16}{Come posso servirti?}
{216}{rbcca17}{Benvenuto. Cosa posso servirti?}
{217}{rbcca18}{Ti serve qualcosa?}
{218}{rbcca19}{E' bello rivederti. Come posso aiutarti?}
{219}{rbcca20}{Cosa?}
{220}{rbcca21}{Si'?}
{221}{rbcca22}{E adesso cosa c'e'?}
{222}{rbcca23}{Ti prego, sii breve. Oggi siamo pieni di clienti. Cosa ti serve?}
{223}{rbcca24}{Cosa posso fare per te? Sono molto occupata.}
{224}{rbcca25}{Sei qui per bere? I tavoli sono laggiu'.}
{225}{rbcca26}{Non sono proprio dell'umore adatto. Cosa c'e'?}
{226}{rbcca27}{Sei gia' tornato? Immagino che tu voglia da bere, giusto?}
{240}{rbcca28}{Certo, bellezza.}
{241}{rbcca29}{Cosa vorresti sapere?}
{242}{rbcca30}{Ne sarei felice.}
{243}{rbcca31}{Ma certamente.}
{244}{rbcca32}{Bene.}
{245}{rbcca33}{Non c'e' problema.}
{246}{rbcca34}{Ti aiutero', se posso.}
{247}{rbcca35}{Certamente, non fare lo stupido.}
{248}{rbcca36}{Qualsiasi cosa. Dimmi.}
{249}{rbcca37}{Faro' del mio meglio per aiutarti. Che cosa vorresti sapere?}
{250}{rbcca38}{Chiedi pure.}
{251}{rbcca39}{Se proprio insisti.}
{252}{rbcca40}{Credo di si'.}
{253}{rbcca41}{Sii breve. Ho un locale da mandare avanti.}
{254}{rbcca42}{Bene, okay. Di cosa si tratta?}
{255}{rbcca43}{Credo di si'.}
{256}{rbcca44}{Cosa?}
{257}{rbcca45}{No, mi dispiace.}
{258}{rbcca46}{Non adesso.}
{270}{}{Vorrei qualcosa da bere.}
{271}{}{Sto cercando un mercante che vende apparecchiature provenienti dal Vault.}
{272}{}{Sto cercando un mercante di nome Vic.}
{273}{}{Hai del lavoro?}
{274}{}{A proposito di quel lavoro...}
{275}{}{Hai altri lavori per me?}
{276}{}{Nulla. Arrivederci.}
{277}{}{Wekee.}
{278}{}{Ruh ruh?}
{279}{}{Iho shasha.}
{280}{}{Dy.}
{281}{}{Ruh ruh?}
{300}{rbcca47}{Il whiskey e' la mia specialita'. Si puo' dire che sia una tradizione della famiglia Dyer. Lo vendo ad un prezzo basso, bassissimo: solo 5$.}
{301}{rbcca48}{I drink vengono sempre 5$, e la famiglia Dyer fa i migliori drink al mondo.}
{302}{rbcca49}{Stai bene? Vuoi del whiskey? Sono solo 5$.}
{303}{}{Prendero' qualcosa da bere.}
{304}{}{Come mai i tuoi drink sono cosi' a buon mercato?}
{305}{}{Dyer?}
{306}{}{Posso farti una domanda?}
{307}{}{Addio.}
{308}{}{Wekee}
{309}{}{Urka.}
{320}{rbcca50}{Oh, e' il nome della mia famiglia. I Dyer sono nel giro della ristorazione da molto tempo - da prima della guerra, addirittura.}
{321}{rbcca51}{Come ho gia' detto, e' il nome della mia famiglia. Una volta c'erano locali Dyer un po' in tutto il mondo.}
{322}{}{Prendero' qualcosa da bere.}
{323}{}{Posso farti un'altra domanda?}
{324}{}{Addio.}
{330}{rbcca52}{Beh, dal momento che sei un cosi' buon cliente, ti faro' parte di un piccolo segreto. E' molto semplice, davvero - ho un distillatore. Un amico di una citta' qui vicino mi ha insegnato come costruirne uno. Allora, che ne dici di un altro goccetto?}
{331}{rbcca53}{Mi spiace, e' un segreto. In piu', non ti conosco poi cosi' bene. Non vorrei che Frankie lo scoprisse. Mi da' gia' abbastanza problemi anche adesso. Vuoi un altro bicchiere? Il mio whiskey e' proprio buono, vero?}
{332}{}{Certo. Ne prendo un altro bicchiere.}
{333}{}{Posso farti un'altra domanda?}
{334}{}{Okay, grazie.}
{340}{rbcca54}{Ecco a te. Grazie mille.}
{341}{}{Grazie. Posso farti una domanda?}
{342}{}{Okay, grazie.}
{343}{}{Graie miie.}
{344}{}{Come scusa?}
{350}{rbcca55}{Mi spiace. Credo proprio di no.}
{351}{rbcca56}{Fred mi deve 200$. Se riuscirai a recuperarli in qualche modo, ci potremo mettere d'accordo.}
{352}{rbcca57}{Ho ancora quel debito da recuperare.}
{353}{rbcca58}{Derek ha preso in prestito un mio libro, qualche tempo fa. Ti paghero' 80$ se riuscirai a riportarmelo.}
{354}{rbcca59}{Sto ancora cercando quel mio libro.}
{355}{}{Dove sta l'inghippo?}
{356}{}{Continua.}
{357}{}{Posso farti una domanda?}
{358}{}{Addio.}
{370}{rbcca60}{Inghippo? Oh, beh, se tu conoscessi Fred capiresti. Mi deve quei soldi da un bel po', ormai. Li avevo gia' dati per persi, ma se tu riuscissi a recuperarli, ne sarei davvero meravigliata... e riconoscente. Si trova da qualche parte qui in citta', sono sicura.}
{371}{rbcca61}{Il libro si intitola "Il Fiore di Lavanda". Derek dovrebbe trovarsi nelle vicinanze del ristorante di Mama, nella zona est.}
{372}{}{Vedro' di fare il possibile.}
{373}{}{Sembra davvero un lavoretto da nulla.}
{374}{}{L'ho gia' trovato.}
{375}{}{Tornero' presto.}
{385}{rbcca62}{Dimmi la verita': non sei riuscito a recuperare quei soldi, vero? Mi stupirei del contrario.}
{386}{rbcca63}{Oh, hai ritrovato il mio libro? Sara' meglio per Derek che non sia rovinato.}
{387}{}{Si', l'ho fatto.}
{388}{}{Mi spiace. E' morto.}
{389}{}{Mi spiace, ma anche Derek e' morto.}
{390}{}{Mi dispiace, ma e' morto.}
{391}{}{Si'. Ecco qua.}
{392}{}{No, mi dispiace.}
{400}{rbcca64}{Non posso crederci. Come ci sei riuscito? Oh, non importa. Sono solo sbalordita, ecco tutto. Per dimostrarti la mia gratitudine, dividero' la cifra fra noi due, proprio a meta'. Grazie ancora, sei stato molto onesto.}
{401}{rbcca65}{Oh, sono cosi' felice che tu l'abbia trovato... Grazie mille. Ecco i tuoi soldi.}
{402}{}{Di nulla.}
{410}{rbcca66}{Non riesco a credere che siano entrambi morti. Mi dispiace molto. Grazie per avermelo detto. Se adesso vuoi scusarmi...}
{411}{rbcca67}{Non posso credere che sia morto... dopo tutti questi anni...}
{412}{}{Bene.}
{413}{}{...}
{420}{rbcca68}{Certo, so di chi si tratta. E' Vic - il tipo che Metzger tiene prigioniero.}
{421}{rbcca69}{Certo, conosco Vic. Metzger lo tiene prigioniero. Non saprei dirti il motivo preciso, pero'.}
{422}{}{Chi e' Metzger?}
{423}{}{Ho un'altra domanda.}
{424}{}{Ottimo! Ci vediamo.}
{430}{rbcca70}{Sei venuto qui al Den e non sai chi e' Metzger? E' il Mastro Schiavista. Lo puoi trovare nella zona est della citta'. E' difficile non notarlo.}
{431}{}{Ho un'altra domanda.}
{432}{}{Grazie.}
{440}{rbcca85}{Assassino!}
{441}{rbcca86}{Uccisore di bambini!}
{442}{rbcca87}{Sei pregato di andartene.}
{443}{rbcca88}{Non faccio affari con gente come te.}
{444}{rbcca89}{Non mi arrendero' senza combattere!}
{450}{rbcca71}{Buffy! Sei tu! Come va? Sara' passato un secolo!}
{451}{}{Eh?}
{452}{}{Eh?}
{460}{rbcca72}{Dave ti manda i suoi saluti e avrebbe voluto essere qui per abbracciarti, ma doveva scappare.}
{461}{}{Dove?}
{470}{rbcca73}{Ha detto qualcosa riguardo ad un commando... o che stava inseguendo un commando. Non ne sono sicura. Una cosa del genere.}
{471}{}{Oh.}
{480}{rbcca74}{Oh, mi ha detto di darti questo. E' un regalo da parte della famiglia Hendee. Dovrebbe esserti d'aiuto.}
{481}{}{Cosa?}
{490}{rbcca75}{Oh, e' solo un piccolo pensiero per te. Ecco. [Becky ti da' 1000$, 5 Stimpak, un'Armatura di Metallo, un Uzi, 5 caricatori, una Granata al Plasma, e un fiore]}
{491}{}{Grazie!}
{500}{rbcca76}{Di nulla. Non ho fatto altro che tenerli da parte per te. Beh, sara' meglio che torni al lavoro.}
{501}{}{Grazie, arrivederci.}
{510}{rbcca77}{Hai sentito?! E' morto! Oh, so che non dovrei essere felice, ma si trattava di un uomo davvero malvagio.}
{511}{}{E' stato un degno avversario.}
{512}{}{Ho una domanda.}
{513}{}{Si', lo era. Arrivederci.}
{514}{}{ uccide!}
{520}{rbcca78}{Cosa? Tu? Io... non so cosa dire. Era un uomo cosi' malvagio...}
{521}{}{Un grazie sara' sufficiente.}
{522}{}{Humph.}
{530}{rbcca79}{Oh, "un grazie sara' sufficiente"! So che questo non e' giusto, ma... ecco, prendi questi soldi. [Becky ti da' 1000 dollari]}
{531}{}{Tieni pure i soldi, Rebecca.}
{532}{}{Grazie mille.}
{533}{}{Grassie!}
{534}{}{Ug! Signora gentile.}
{540}{}{You are a wonderful man. Even though I don't condone your actions. You did the
 world a great service.}
{541}{}{You are a wonderful woman. Even though I don't condone your actions. You did the
 world a great service.}
{542}{}{Grazie.}
{550}{rbcca90}{Non sei il benvenuto qui. Sei pregato di andartene.}
{551}{rbcca91}{Sei pregato di andartene.}
{560}{rbcca82}{Perche' hai distrutto il mio distillatore? Cosa ti ho fatto di male?}
{561}{}{Mi hanno pagato per farlo.}
{562}{}{Non devo dare risposte a nessuno, io.}
{563}{}{Non so di cosa tu stia parlando.}
{564}{}{Vabbe'.}
{565}{}{Ooba gooba.}
{570}{rbcca83}{Oh, davvero? Sara' stato quel lurido di Frankie a mandarti, ne sono certa. Ne costruiro' un altro, non preoccuparti.}
{571}{}{Non m'importa. L'ho fatto solo per denaro.}
{572}{}{E allora?}
{573}{}{Non mi sorprenderebbe.}
{580}{rbcca84}{Allora sei anche un codardo? C'era da immaginarlo.}
{581}{}{...}
