{100}{}{Vedi uno schiavo.}
{101}{}{Vedi Vic.}
{150}{}{Questo schiavo sembra sia tenuto sotto stretta sorveglianza.}
{151}{}{E' Vic.}
{152}{}{[PARLA]}
{153}{}{Potresti dirgli che non posso... aspetta. Chi sei tu? Tu non sei uno schiavista. Che cosa ci fai qui?}
{154}{}{Il mio nome e' }
{155}{}{. Sono qui per farti uscire.}
{156}{}{Sono }
{157}{}{. Perche' ti tengono chiuso in questa stanza?}
{158}{}{Puoi dirmi dove si trova il Vault 13?}
{159}{}{Sono }
{160}{}{. Torno subito.}
{161}{}{Dubba iba }
{162}{}{.}
{163}{}{Metzger e' ancora piuttosto arrabbiato con me, sebbene io abbia riparato la sua dannata ricetrasmittente. Minaccia di vendermi! Faro' tutto quello che mi chiedi se riuscirai a tirarmi fuori da questo casino.}
{164}{}{OK, lo faro'.}
{165}{}{Mi spiace, non posso. Addio.}
{166}{}{Whoo.}
{167}{}{Oh, ci rivediamo. Questa dannata ricetrasmittente non puo' essere riparata senza pezzi di ricambio. Come pensa che possa metterla a posto in queste condizioni?}
{168}{}{Dove posso trovare i pezzi che ti servono?}
{169}{}{Forse posso ripararla io.}
{170}{}{Puoi usare questa ricetrasmittente che ho trovato?}
{171}{}{Vedro' di fare il possibile.}
{172}{}{Spa pa?}
{173}{}{So di potercela fare; mi servono solo alcuni pezzi di ricambio. C'e' una vecchia ricetrasmittente nella mia baracca, a Klamath, che e' proprio quello che mi serve. Hai presente la casa dei Dunton? La mia baracca... ecco, e' proprio a est della loro abitazione.}
{174}{}{Stai parlando di questa ricetrasmittente?}
{175}{}{Andro' a cercarla.}
{176}{}{Hmmm... I'll be back.}
{177}{vic5}{Splendido! Riparero' questa ricetrasmittente in un batter d'occhio.}
{178}{}{Okay, parlero' con Metzger.}
{179}{vic6}{Grazie.}
{180}{}{Addio.}
{181}{vic7}{Come? Scusa, ma non riesco a capirti.}
{182}{}{hurm.}
{183}{vic8}{Grazie! Ti saro' per sempre debitore. Cosa posso fare per ripagarti?}
{184}{}{Dimmi dove si trova il Vault 13.}
{186}{}{Vieni con me, mi farebbe comodo una mano.}
{187}{}{Non e' nulla. Addio.}
{188}{}{Dolcetto?}
{189}{}{Vault 13? C'e' una Vault City a est di qui. A volte vado a vendere della roba, laggiu'.}
{190}{}{Vuoi venirci con me?}
{191}{}{Grazie. Ciao.}
{192}{}{Certo, mi uniro' a te! Questo vecchio stupido puo' ancora affrontare una grande avventura. Ne sono certo! E sono anche discretamente bravo a riparare le cose, a dispetto di quello che dice Metzger.}
{193}{}{Ottimo, andiamo.}
{194}{}{Benvenuto a bordo.}
{195}{}{Vabbe'.}
{196}{}{Vic mio piu' migliore amico.}
{197}{}{Vuoi unirti a me nella mia ricerca?}
{198}{}{Benissimo! Grazie.}
{203}{vic11}{Vault City e' a est di qui. Te la indichero' sulla tua mappa.}
{204}{}{Grazie.}
{206}{vic12}{E' proprio qui. [indica una mappa]}
{220}{vic13}{Dannazione. Ci sono vicino, ma mi serve la ricetrasmittente che si trova nella mia baracca a Klamath. Sono sicuro contenga il pezzo che mi serve.}
{300}{vic14}{Si', probabilmente posso aiutarti, ma prima tu devi farmi uscire da qui.}
{301}{vic15}{Te l'ho detto. Se riesci a farmi uscire da qui, ti aiutero' in tutti i modi che vuoi.}
{302}{}{Come posso farlo?}
{303}{}{Arrangiati, allora.}
{304}{}{Okay, vedro' di fare quel che posso.}
{350}{vic117}{Pensi di potermi aiutare?}
{351}{vic118}{Metzger non mi permettera' di andarmene.}
{352}{vic119}{Non resistero' ancora a lungo.}
{353}{vic120}{Faro' qualsiasi cosa per te se mi aiuti.}
{354}{vic121}{Vedrai che sapro' ripagare tutte le spese che potresti sostenere!}
{400}{}{Non sei andato a casa mia, vero? Mi serve davvero quella ricetrasmittente, Metzger si arrabbia ogni giorno di piu'.}
{450}{}{Dove hai preso questa fiaschetta?}
{451}{}{Avevo una fiaschetta con su disegnato un grande 13 giallo. Ti ricordi dove l'hai presa?}
{500}{vic17}{Oh, certo. Me lo ricordo. L'ho comprata da Ed. E' un venditore di brahmin giu' a Vault City.}
{501}{}{Fiaschetta? Oh, aspetta. Si', ne avevo un paio di dozzine. Sono riuscito a piazzarle bene. L'ho comprata da Ed. Un venditore di brahmin giu' a Vault City.}
{502}{}{Vault City?}
{550}{}{Potresti smetterla di chiamarmi boss?}
{600}{vic19}{Certamente, capo!}
{601}{}{Dico sul serio! SMETTILA!}
{602}{}{Immagino che dovro' accontentarmi di questo...}
{650}{vic20}{D'accordo, Sport!}
{651}{}{Uggg!}
{700}{}{Essere mio amico.}
{710}{}{Potresti dirgli che non posso ripararla senza i pezzi giusti? Non so... ehi, aspetta un attimo. Chi sei tu? Una nuova recluta? Non ti ha mandato qui per picchiarmi di nuovo, vero? Tanto non farebbe alcuna differenza. Non posso ripararla senza pezzi di ricambio.}
{750}{}{Wow! Faresti questo per me? Farei qualsiasi cosa se tu mi tirassi fuori da 'sto casino. L'unico problema e' che Metzger mi terra' chiuso qui dentro finche' non riusciro' a riparare questa ricetrasmittente... e non ho i pezzi che mi servono.}
{753}{}{Dove posso recuperare i pezzi che ti servono?}
{754}{}{Vedro' di fare il possibile.}
{760}{}{E' una lunga storia. Credo si possa dire che Metzger mi terra' qui finche' non avro' riparato questa dannata ricetrasmittente. Lo schermo e' andato e non ho pezzi di ricambio. Come crede possa ripararla?}
{761}{}{Beh, sono qui per liberarti.}
{764}{}{Non saprei. Ci si vede.}
{800}{vic24}{Devo riuscire a riparare questa ricetrasmittente. Se mi aiuti a farlo, forse potremo ragionare con lui.}
{801}{}{Come posso aiutarti?}
{803}{}{Ne dubito. Buona fortuna.}
{810}{vic25}{Perche' hai ucciso Mama...? Immagino tu abbia avuto le tue ragioni... Scusami, Boss. Non e' compito mio criticarti. Questa e' una citta' piuttosto cattiva. Sicuramente Mama avra' fatto qualcosa di male.}
{811}{vic26}{Ehi, Boss. Grazie per avermi tirato fuori da quel casino con Metzger. Ti serve qualcosa? Mama e' stata cosi' gentile da sfamarmi mentre tu eri via. La aiuto con il locale....}
{812}{}{Addio.}
{813}{}{Oooh.}
{814}{}{Caioe}
{823}{}{Dove si trovava il tuo amico Ed?}
{830}{vic27}{Lo farei se potessi, ma non hai un bell'aspetto. Sarei solo un peso per te. Adesso che Mama e' morta, credo che me ne andro' da qualche altra parte. Non so dove... forse ci incontreremo ancora. Grazie per tutto quello che hai fatto per me.}
{831}{vic28}{Lo farei se potessi, ma non hai un bell'aspetto. Sembra quasi che tu faccia fatica a badare anche solo a te stesso. Sarei solo un peso per te. Aspettero' qui; i piatti di Mama mi ricordano la mia ex-moglie...}
{832}{vic29}{Lo farei, sul serio. Farei praticamente qualsiasi cosa per te. Ma mi sembra che tu non sia in grado di guidare un gruppo. Sarei solo un peso per te. Andro' da Mama, per un po'... finche' non avrai fatto quel che devi. E' da un po' di tempo che non mangio da lei.}
{833}{vic30}{Mi dispiace, Boss. Credo proprio che siate gia' in troppi. Adesso che Mama e' morta credo che me ne andro' da qualche altra parte. Non so dove... forse ci incontreremo ancora. Grazie per tutto quello che hai fatto per me.}
{834}{vic31}{Credo che siate un po' in troppi, Boss. Ti aspettero' qui finche' non avrai fatto quel che devi. I piatti di Mama mi ricordano la mia ex-moglie... non so se questa sia una buona o una cattiva cosa...}
{835}{vic32}{Mi piacerebbe, davvero, Boss. E' solo che non mi pare tu abbia molto spazio per me. Me ne andro' da Mama. E' da un po' che non ci vado. Vieni a prendermi se trovi un po' di posto per me.}
{840}{vic33}{Ed vive giu' a Vault City. E' un venditore di Brahmin. E' solo uno dei miei molti fornitori. Vault City non e' molto distante da qui.}
{845}{vic34}{I told you, it's over here. [Vic points to a location on your Pip-Boy 2000.]}
{900}{}{Hai scoperto degli elementi sul passato da mercante di Vic.}
{1000}{}{Devo chiederti una cosa.}
{1100}{vic35}{Completamente a posto, Boss. Qualcos'altro?}
{1200}{vic36}{Quasi in perfette condizioni, Boss.}
{1300}{vic37}{Sono quasi a posto, Boss, ma sono stato meglio.}
{1400}{vic38}{Ci ho provato, Boss, ma non ci riesco molto bene. Faro' quello che posso.}
{1500}{vic39}{Come vuoi, Boss.}
{1501}{vic40}{Qui? Proprio qui? Okay, sei tu il capo.}
{1502}{vic41}{D'accordo. Rimarro' qui finche' non torni, Boss. Tornerai, vero?}
{1503}{vic42}{Per quanto tempo desideri. Non andro' da nessuna parte.}
{1504}{vic43}{Certamente, Boss.}
{1600}{vic44}{Se lo dici tu.}
{1601}{vic45}{Buona idea, Boss.}
{1602}{vic46}{Grande pensata, Boss.}
{1603}{vic47}{Certo, Boss. Qualcos'altro?}
{1604}{vic48}{L'ho gia' messa via, Boss.}
{1605}{vic49}{Nessun problema, Boss.}
{1606}{vic50}{Fatto, Boss.}
{1700}{vic51}{Certo, Boss.}
{1701}{vic52}{Ti sto vicino, Boss.}
{1702}{vic53}{Tu si' che sai come fare, Boss.}
{1703}{vic54}{Sono proprio dietro di te, Boss.}
{1704}{vic55}{Come la colla, Boss.}
{1705}{vic56}{Se lo dici tu, Boss.}
{1706}{vic57}{Oh. Okay, Boss.}
{1800}{vic58}{OK, me ne staro' a distanza, ma non troppo lontano, Boss.}
{1801}{vic59}{Okay, non lo faro', Boss.}
{1802}{vic60}{Allora me ne staro' un poco dietro, Boss.}
{1803}{vic61}{Certo, Boss.}
{1900}{vic62}{D'accordo, Boss. Me ne staro' ben dietro.}
{1901}{vic63}{Come vuoi, Boss.}
{1902}{vic64}{Ecco fatto, Boss.}
{1903}{vic65}{Sto nelle retrovie, Boss.}
{1904}{vic66}{Vado dietro, Boss.}
{1905}{vic67}{Mi allontano un po', Boss.}
{1906}{vic68}{Okay, Boss.}
{2000}{vic69}{Uh, Boss? Credo siate un po' in troppi. Ti aspettero' qui.}
{2100}{}{Mi spaventi, Boss. Cosa ti e' successo? Hai un aspetto... beh, spaventoso. Credo che me ne rimarro' qui da solo per un po'...}
{2200}{vic70}{Puoi scommetterci, Boss!}
{2201}{vic71}{Diamine se lo faro', Boss.}
{2202}{vic72}{Certo, Boss.}
{2203}{vic73}{Sono pronto a partire quando vuoi, Boss.}
{2204}{vic74}{Magnifico! Andiamo.}
{2205}{vic75}{Grande!}
{2206}{vic76}{Sei il migliore, Boss!}
{2207}{vic77}{Non rimarrai deluso. Basta errori!}
{2208}{vic78}{Questa volta staro' attento, non temere!}
{2209}{vic79}{Lo sapevo che mi avresti perdonato...uhm. Allora, uh, Boss. Cos'hai in mente?}
{2210}{vic80}{Non ti deludero', Boss!}
{2211}{vic81}{Sei super, Boss!}
{2212}{vic82}{Lo sapevo di non essere troppo vecchio! Si e' trattato solo di episodi sfortunati! Giusto, Boss?}
{2300}{}{Da Ed. E' un venditore di brahmin giu' a Vault City. Ci sei mai stato? Aspetta che te la indico sulla mappa.}
{2305}{vic199}{A Vault City. Qui. Aspetta, te la mostro su quella tua strana mappa.}
{2310}{vic84}{Dovrebbe essere qui attorno, da qualche parte.}
{2311}{vic85}{A Vault City. Controlla quella tua strana mappa.}
{2403}{}{Dove l'hai presa la fiaschetta del Vault 13?}
{2404}{}{Nulla.}
{2500}{vic86}{Certo, Boss.}
{2501}{vic87}{Chiedimi qualsiasi cosa, Boss.}
{2502}{vic88}{Ti aiutero' come posso, Boss.}
{2503}{vic89}{Non sono nei guai, vero Boss?}
{2504}{vic90}{Ho fatto qualcosa di sbagliato, Boss?}
{2505}{vic91}{Certamente.}
{2600}{vic92}{Cosa faremo adesso, Boss?}
{2601}{vic93}{Qual e' il tuo piano, Boss?}
{2602}{vic94}{Sto facendo del mio meglio, Boss.}
{2603}{vic95}{Cosa posso fare per te, Boss?}
{2604}{vic96}{Hai modificato il piano, Boss?}
{2605}{vic97}{Hai in mente una strategia diversa, Boss?}
{2700}{}{Boss, mi hanno beccato in pieno. Devi portarmi da un dottore. Non so se potro' restare ancora al tuo fianco.}
{2701}{}{Mi serve un dottore, Boss. Sono davvero messo male. Non so se potro' combattere ancora insieme a te.}
{2702}{vic100}{Boss, sono davvero messo male. Devi farmi visitare da Lenny.}
{2800}{vic101}{Ehi, Boss. Vuoi che mi unisca a te, adesso?}
{2801}{vic102}{Ehi, Boss. Non mi da' fastidio aspettarti. Sono un uomo molto paziente.}
{2802}{vic103}{Torniamo a far squadra insieme, Boss? Mi impegnero' di piu'.}
{2803}{vic104}{Temevo che saresti piu' tornato. Ti assicuro che sono molto felice di rivederti, Boss.}
{2804}{vic105}{Cerchi di nuovo compagnia?}
{2805}{vic106}{Sono pronto ad andare, Boss.}
{2806}{vic107}{Lo sapevo che non mi avresti abbandonato.}
{2807}{vic108}{Ti serve un aiuto?}
{2808}{vic109}{Hai bisogno di riparare qualcosa, vero? Io sono l'uomo che fa per te, Boss!}
{2809}{vic110}{Non temere, Boss. Sulik e io andremo d'accordo, davvero.}
{2810}{vic200}{Andiamo.}
{2811}{vic201}{Sta' qui. Tornero' tra poco.}
{2812}{vic202}{Me va.}
{3100}{vic111}{Cosa? Uh... okay, Boss. Se lo dici tu...}
{3101}{vic112}{Posso indossare qualcos'altro, Boss? Sono un po' preoccupato.}
{3102}{vic113}{Okay... non e' che mi vuoi lasciare qui... Vero, Boss?}
{3103}{vic114}{Ma... cioe'... Certamente, Boss. Lo faccio subito.}
{3200}{vic115}{Beh, Boss... Sono abbastanza bravo con le armi di piccolo taglio. Posso maneggiare praticamente ogni tipo di fucile, anche quelli a pompa, e praticamente tutte le pistole medio-piccole. "So" usare i coltelli. Ho anche un bel braccio robusto, adatto per lanciare, ma la mia mira non e' la migliore del mondo... in realta', e' discretamente orribile. Mi spiace, Boss. Sto cercando di migliorare.}
{3201}{vic116}{Come ti ho gia' detto, Boss, preferisco le armi di piccolo taglio. Posso maneggiare praticamente ogni tipo di fucile, anche quelli a pompa, e praticamente tutte le pistole medio-piccole. In caso di bisogno estremo posso provare ad usare un coltello o addirittura armi da lancio.}
{3300}{vic203}{"So" usare i coltelli e ho anche un bel braccio robusto, adatto per lanciare, ma la mia mira non e' la migliore del mondo... in realta' e' discretamente orribile. Mi spiace, Boss. Sto cercando di migliorare.}
{3301}{vic204}{Come ti ho gia' detto, Boss. Coltelli. Ho anche un braccio robusto, per lanciare... Ma ho ancora tanto da imparare.}
{3400}{vic122}{Ne ho fin sopra i capelli!}
{3401}{vic123}{Ti stacchero' quella dannata testa dal collo! Nessuno puo' far del male alla mia famiglia!}
{4000}{vic124}{Qua?}
{4001}{vic125}{Cosi' va meglio, Boss?}
{4002}{vic126}{Che ne dici di qui?}
{4003}{vic127}{Si', Boss.}
{4004}{vic128}{Cosa?}
{4005}{vic129}{Dove stiamo andando?}
{4006}{vic130}{Stiamo andando via, Boss?}
{4007}{vic131}{Mi muovo.}
{4008}{vic132}{Scusa, Boss.}
{4009}{vic133}{Meglio?}
{4010}{vic134}{Ooof.}
{4011}{vic135}{Come va cosi', Boss?}
{4012}{vic136}{Me ne staro' qui.}
{4013}{vic137}{Adesso mi sposto.}
{4100}{vic138}{Boss! Le cose non mi vanno molto bene.}
{4101}{vic139}{Ho bisogno di un dottore.}
{4102}{vic140}{Oh, cavoli. Fa davvero male.}
{4103}{vic141}{Ow!}
{4104}{vic142}{Ouch.}
{4105}{vic143}{Dannazione.}
{4106}{vic144}{Un dottore?}
{4107}{vic145}{Mi sto trascinando... a fatica.}
{4200}{vic146}{Non mi e' mai piaciuto questo posto.}
{4201}{vic147}{Perche' questo posto e' cosi' pulito?}
{4202}{vic148}{Non senti anche tu uno strano odore, Boss?}
{4203}{vic149}{Sai, Boss, non credo che tornero' qui una volta che saremo arrivati alla fine della nostra avventura. Non riesco piu' a chiamare "casa" questo posto.}
{4204}{vic150}{E' sicuramente piu' sporco di quanto mi ricordassi.}
{4205}{vic151}{Non rimarremo qui a lungo, vero, Boss?}
{4206}{vic152}{Questo posto non cambiera' mai.}
{4207}{vic153}{Boss, questo posto non mi manchera' di certo.}
{4208}{vic154}{Grazie ancora per avermi tirato fuori da questo posto, Boss.}
{4209}{vic155}{Ti devo un favore, Boss.}
{4210}{vic156}{Wow, questo posto e' cambiato un bel po'.}
{4211}{vic157}{Sono anni che non vengo qui.}
{4212}{vic158}{Penso che mi ritirero' qui.}
{4213}{vic159}{Potrei aprire un negozio di riparazioni da queste parti.}
{4300}{vic160}{Ah, e' una gioia per gli occhi. Questa e'... *era* casa mia, ma credo tu lo sappia gia'. Giusto, Boss?}
{4400}{vic161}{Sulik, non guardarmi in quel modo.}
{4401}{vic162}{Boss, Sulik mi sta fissando di nuovo.}
{4402}{vic163}{Bel cagnolino.}
{4500}{vic164}{La de da...}
{4501}{vic165}{Ho hum.}
{4502}{vic166}{Aspetto il Boss...}
{4503}{vic167}{Sto aspettando il Boss.}
{4504}{vic168}{Sto solo aspettando.}
{4505}{vic169}{Il Boss di certo non mi abbandonerebbe mai...}
{4506}{vic170}{Knock Knock... chi e'... aspetta... Com'era?}
{4507}{vic171}{Sto ancora aspettando.}
{4508}{vic172}{Cos'e' 'sta puzza?}
{4509}{vic173}{Non c'e' niente da riparare da queste parti?}
{4510}{vic174}{Eccomi qua... in attesa del Boss.}
{4511}{vic175}{Un uomo vecchio come me... starsene qui in attesa, a sprecare i suoi talenti.}
{4512}{vic176}{Avrei tanto voluto un pacchetto di cicche... saranno decenni...}
{4513}{vic177}{Dovrei abbandonare il mercato dell'antiquariato... non porta altro che guai.}
{4514}{vic178}{Chissa' perche' l'attesa e' cosi' snervante?}
{4600}{vic179}{Uh, grazie, Boss.}
{4601}{vic180}{Grazie.}
{4602}{vic181}{Sei sicuro di sapere quello che fai?}
{4603}{vic182}{Non potremmo semplicemente riposare?}
{4604}{vic183}{Possiamo accamparci?}
{4605}{vic184}{Sono messo cosi' male?}
{4700}{vic185}{Non troppo, Boss.}
{4701}{vic186}{Se proprio insisti, Boss.}
{4702}{vic187}{Boss, la mia testa non esplodera', vero?}
{4703}{vic188}{Boss, credo che quella roba inizi a piacermi.}
{4704}{vic189}{Mi sento un po' strano, Boss.}
{4705}{vic190}{Ne hai davvero tanta da offrire.}
{4706}{vic191}{Certo, Boss. Ne prendo un po'.}
{4707}{vic192}{Grazie, Boss.}
{4708}{vic193}{Non male.}
{5000}{vic194}{Ho un po' di fame adesso. Parleremo di nuovo da Mom.}
{5500}{vic195}{Credo di avere un arto rotto, Boss. Faresti meglio a dare un'occhiata.}
{5501}{vic196}{Credo di avere la febbre, Boss. Faresti meglio a dare un'occhiata.}
{5502}{vic197}{Credo di essere stato avvelenato, Boss. Faresti meglio a dare un'occhiata.}
