{100}{}{Vedi un uomo che indossa un'armatura di cuoio.}
{101}{}{Vedi Kaga.}
{102}{}{Indossa un'armatura di cuoio e ha la seccante abitudine di parlare di se' in terza persona.}
{103}{kaga13}{Qeusta sara' l'ultima volta che Kaga ti incontra.}
{104}{kaga14}{After Kaga kill you, he will burn Arroyo to the ground.}
{105}{kaga15}{Assaggia l'ira di Kaga!}
{106}{kaga16}{Sono il grande Kaga!}
{107}{kaga17}{Tutti devono temere Kaga.}
{108}{kaga18}{Kaga prendera' la tua testa come trofeo.}
{109}{kaga19}{Arrenditi e la tua morte sara' rapida.}
{110}{kaga20}{Kaga tornera'!}
{111}{kaga21}{Non puoi uccidere il grande Kaga!}
{112}{kaga22}{Sei fortunato che Kaga abbia degli affari da sbrigare.}
{113}{kaga23}{Kaga ti incontrera' di nuovo.}
{120}{}{It's that Kaga guy again.}
{150}{kaga1}{[A tall and powerfully built warrior stands before you, his eyes blaze with hatred as he looks you over.] So, they cast out Kaga, then deem YOU the Chosen One? Ha! You think being the grandchild of the Vault Dweller makes you special?! You think you are better than I, Kaga the Great?!}
{151}{}{Well, I AM the Chosen One, aren't I?}
{152}{}{Hey now, hold on a second. I never said I was better than you.}
{160}{kaga2}{That title will mean nothing when Kaga rips the head from your shoulders!}
{161}{kaga3}{No words can save your hide. With your death, Kaga's honor shall be restored. Kaga will now take his vengeance!}
{200}{}{Ooglie?}
{201}{kaga4}{What!? They picked *you* to be the Chosen One? Oh my, they've become desperate.}
{202}{}{Me no likie. U lookie bad.}
{203}{kaga5}{Kaga won't even bother speaking with you further. Prepare to die at the hands of Kaga!}
