{100}{}{Vedi un uomo che indossa un'armatura da combattimento.}
{101}{}{Vedi Kaga in armatura da combattimento.}
{102}{}{Indossa un'armatura da combattimento e sembra avere delle armi decenti.}
{103}{kaga33}{Questa volta sono pronto ad affrontarti.}
{104}{kaga34}{Il prescelto non ritornera' mai piu' ad Arroyo!}
{105}{kaga35}{Kaga ti schiaccera'!}
{106}{kaga36}{Kaga non ha paura di nessuno!}
{107}{kaga37}{Stai ferno, cosi' Kaga puo' prendere bene la mira.}
{108}{kaga38}{Ci rivedremo!}
{109}{kaga39}{Questa non sara' l'ultima volta che vedrai Kaga.}
{110}{kaga40}{Kaga ha sicuramente bisogno di allenarsi di piu'.}
{120}{}{Go away Kaga!}
{150}{kaga1}{[A tall and powerfully built warrior stands before you, his eyes blaze with hatred as he looks you over.] So, they cast out Kaga, then deem YOU the Chosen One? Ha! You think being the grandchild of the Vault Dweller makes you special?! You think you are better than I, Kaga the Great?!}
{151}{}{Well, I AM the Chosen One, aren't I?}
{152}{}{Hey now, hold on a second. I never said I was better than you.}
{160}{kaga2}{That title will mean nothing when Kaga rips the head from your shoulders!}
{161}{kaga3}{No words can save your hide. With your death, Kaga's honor shall be restored. Kaga will now take his vengeance!}
{200}{}{Ooglie?}
{201}{kaga4}{What!? They picked *you* to be the Chosen One? Oh my, they've become desperate.}
{202}{}{Me no likie. U lookie bad.}
{203}{kaga5}{Kaga won't even bother speaking with you further. Prepare to die at the hands of Kaga!}
