{100}{}{Vedi un punk con un mezzo sorriso sulla faccia.}
{101}{}{Vedi Badger.}
{102}{}{Vedi un punk con un mezzo ghigno sulla faccia.}
{103}{badge1}{::rutta fragorosamente:: 'zzo vuoi?}
{104}{}{::rutta::}
{105}{}{Chi tu?}
{106}{}{Chi sei?}
{107}{}{Puoi dirmi qualcosa a proposito della petroliera?}
{108}{}{Di che cosa ti occupi?}
{109}{}{Vorrei che ti infiltrassi in un computer per me.}
{110}{}{Come va l'hackeraggio?}
{111}{}{Niente. Bel rutto.}
{112}{badge2}{::Emette un altro rutto gutturale::}
{113}{}{::Rutta piu' forte::}
{114}{}{Che roba.}
{115}{badge3}{::Spara fuori un rutto cosi' tremendo da scuotere le fondamenta del paradiso in lungo e in largo::}
{116}{}{::Fai un applauso::}
{117}{badge4}{Sono Badger. Un tempo avevo una band. ::sospiro:: Ci chiamavamo "There We Smolder". Adesso faccio il tecnico informatico qui a San Fran.}
{118}{}{Oh! Grazie!}
{119}{}{Che tipo di trucchetti sai fare con il computer?}
{120}{}{Scommetto che la tua banda faceva schifo.}
{121}{}{Era in gamba la tua band?}
{122}{}{Grazie. Ciao.}
{123}{badge5}{Uhh... okay.}
{124}{}{Ciao!}
{125}{badge6}{Dovresti parlarne con Marc o col Capitano.}
{126}{}{Dove posso trovare Marc?}
{127}{}{Dove posso trovare il Capitano?}
{128}{badge7}{Sono il genio dei computer di questo posto.}
{129}{}{Che tipo di trucchetti sai fare con il computer?}
{130}{}{Grazie. Ciao.}
{131}{badge37}{Non rompere. ::scoreggia:: Ci sto lavorando, okay?}
{132}{}{D'accordo, d'accordo. Fammi sapere quando hai finito.}
{133}{badge8}{Beh, diciamo che sono un esperto nel recuperare informazioni.}
{134}{}{Puoi recuperare un po' di roba per me?}
{135}{}{Che cosa significa?}
{136}{badge9}{Certo, beh, fottiti.}
{137}{}{Ehi!}
{138}{}{Fottiti anche tu.}
{139}{badge10}{Puoi dirlo forte! Eravamo grandi! Il nostro cantante era... umm... un mezzo recchione, e Aaron sudava sempre, e tutto il resto era colpa di Todd. Ma eravamo bravi.}
{140}{}{E' un peccato che vi siate sciolti. Mi sarebbe piaciuto ascoltarvi.}
{141}{}{Umm. Certo. Ho delle altre domande.}
{142}{}{Scommetto che facevate schifo.}
{143}{badge11}{Di solito puoi trovare Marc al bar.}
{144}{}{Grazie. Ho delle altre domande.}
{145}{}{Grazie. E' tutto.}
{146}{badge12}{Il Capitano e' in plancia, di solito. Basta che sali le scale che trovi nel bar.}
{147}{}{Grazie. Ho delle altre domande.}
{148}{}{Grazie. E' tutto.}
{149}{badge13}{Certo, ma ti costera'.}
{150}{}{Qual e' il tuo prezzo?}
{151}{}{Si', vabbe'. Devo andare.}
{152}{badge14}{Significa che posso trovare i dati di cui hai bisogno.}
{153}{}{Puoi fare qualcosa per me?}
{154}{}{Capisco. Forte. Ho delle altre domande.}
{155}{}{Capisco. Grazie.}
{156}{badge15}{Si', ti sarebbe piaciuto. Adesso pero' devo tornare al mio lavoro.}
{157}{}{Aspetta. Ho delle altre domande.}
{158}{}{Grazie. Ci si vede.}
{159}{badge16}{Tu mi piaci abbastanza: potrei anche fartelo subito... A chi vuoi che faccia una visitina?}
{160}{}{Gli Hubologisti.}
{161}{}{Gli Shi.}
{162}{}{Nessuno. Volevo solo controllare.}
{163}{badge17}{Credo di potertelo fare gratuitamente, dato che hai salvato la mia ragazza. Ci vorra' un po', pero'. Chi vuoi che colpisca?}
{164}{}{Gli Hubologisti.}
{165}{}{Gli Shi.}
{166}{}{Nessuno. Volevo solo controllare.}
{167}{badge18}{Prima devi farmi un favore. La mia ragazza si e' persa nella petroliera. Trovala e io faro' quello che mi hai chiesto.}
{168}{}{D'accordo. Ci vediamo.}
{169}{}{Scordatelo. Ci vediamo.}
{170}{badge19}{Come rubare le caramelle ad un bambino. Non mi beccheranno mai. Cosa vuoi da loro?}
{171}{}{Ottimo. Ho delle altre domande.}
{172}{}{Ottimo. Tornero'.}
{173}{badge20}{Posso fregarli. Sono piuttosto protettivi nei confronti delle loro informazioni e hanno messo un bel po' di protezioni a difesa delle loro macchine. Sei sicuro di volere che penetri nei loro sistemi?}
{174}{}{Beh, buona fortuna. Ho delle altre domande.}
{175}{}{Buona fortuna. Tornero' piu' tardi.}
{176}{badge21}{Ehi, trova la mia ragazza e poi ne parleremo.}
{177}{}{D'accordo... d'accordo...}
{178}{badge22}{E' morta? E' MORTA? Com'e' morta? No, aspetta... non dirmelo. Dammi qualche ora per riprendermi.}
{179}{}{Certo, certo.}
{180}{}{Riprenditi, Sparky. Abbiamo del lavoro da fare.}
{181}{badge23}{D'accordo. Adesso sto meglio.}
{182}{}{Bene. Devo chiederti qualche cosa.}
{183}{}{Buon per te. Non volevo parlarti.}
{184}{badge24}{Grazie, grazie, grazie. Non ti potro' mai ringraziare abbastanza per averla salvata. Che cosa vuoi?}
{185}{}{Ho delle domande da farvi.}
{186}{}{Mi basta la tua gratitudine. Ci vediamo.}
{187}{badge25}{Okay, sono penetrato nei computer degli Shi. Non so se sono riuscito a non farmi beccare. Credo che la cosa migliore da fare adesso sia nascondersi. Vuoi qualcos'altro?}
{188}{}{Si'.}
{189}{}{No. Ci vediamo.}
{190}{badge26}{Hubologisti fregati. Nessun problema. Ti serve qualcos'altro?}
{191}{}{Si'.}
{192}{}{No. Ci vediamo.}
{193}{badge27}{Hai fatto un grosso errore, amico. Ti ho appena messo gli Shi contro tramite i loro computer. Qui a San Francisco sei FINITO. }
{194}{}{Allora credo che farei meglio ad ucciderti.}
{195}{badge28}{Dammi un paio d'ore per riprendermi.}
{196}{badge29}{Vuoi che violi un computer formattato? Le informazioni sono andate. Non puo' funzionare.}
{197}{badge38}{Mi tocchera' andarmene da questo posto.}
{198}{badge39}{Mi fa piacere vederti.}
{199}{}{Sto cercando un po' di carburante.}
{200}{badge30}{Ho sentito dire che gli Hubologisti sono in possesso di un certo quantitativo di carburante. Potrei dare una sbirciatina nei loro computer per te.}
{201}{badge31}{Gli Shi hanno il controllo su tutto il carburante della citta'. Potrei dare uno sguardo al loro mainframe per te.}
{202}{}{Puoi farlo?}
{203}{badge40}{Cosa diavolo vuoi?}
{204}{}{Badger il punk, suppongo?}
{205}{}{Hai disonorato il nostro Imperatore per l'ultima volta!}
{206}{badge41}{Credo che andro' a prendermi qualche dolcetto da Lao Chou, giu' in citta'.}
{207}{}{Alla faccia del giusto processo. Hmmm...}
{208}{badge42}{Ragazzo, rilassati. Volevo solo qualche dolcetto.}
{209}{}{Puoi trasferire il carburante dalla loro astronave alla petroliera?}
{210}{}{Puoi prelevare una copia dei loro schemi tecnici del vertibird?}
{211}{}{Puoi trasferire il carburante e prelevare gli schemi tecnici?}
{212}{}{Si', mi serve quello che hanno.}
{213}{}{Nah, trovero' un altro modo.}
{214}{badge32}{D'accordo, ma potrebbero beccarci.}
{215}{}{Puoi trasferire il carburante dalle loro riserve alla petroliera?}
{216}{}{Come non detto, lo faro' in un altro modo.}
{217}{}{Nulla.}
{218}{badge33}{Okay. Torna da me tra un giorno circa e ti faro' sapere.}
{219}{}{Hai quello che ti ho chiesto?}
{220}{badge34}{Si', ho il carburante.}
{221}{badge35}{Si', ho gli schemi tecnici del vertibird.}
{222}{badge36}{Si', ho il carburante e gli schemi tecnici.}
{223}{}{Grazie mille. Ci si vede.}
