{100}{}{Vedi un ghoul piu' grosso della media.}
{101}{}{Vedi Zomak, noto ad alcuni come "il Distruttore".}
{102}{}{Vedi un ghoul grosso e massiccio, la faccia del quale, sotto una fronte molto sfuggente, tradisce vaste riserve di sempliciotta superiorita'.}
{110}{zomak1}{Rinnova, compagno! Io sono Zomak. Qualcuno mi chiama Zomak il Distruttore. Cosa ci fai qui?}
{111}{zomak2}{Rinnova, compagno! Che cosa ci fai qui? Di' a Zomak il Distruttore il motivo della tua visita.}
{112}{}{Ri! Uova!}
{113}{}{Ook?}
{114}{}{Sto solo dando un'occhiata.}
{115}{}{Vorrei Rinnovare.}
{116}{}{Ho sbagliato strada.}
{120}{zomak3}{Dovresti andare a dare un'occhiata a qualcos'altro, o Zomak ti mostrera' le stelle.}
{130}{zomak4}{Allora devi vedere LUI.}
{131}{}{Lui? Chi e' lui... cioe'... LUI?}
{132}{}{Non sono degno di vederlo. Addio.}
{140}{zomak5}{E' il concessore dell'illuminazione. E' lui che promette Rinnovamento per tutti i suoi seguaci.}
{141}{}{Beh, un Rinnovamento non mi farebbe male. Dove si trova, LUI?}
{142}{}{A me pare la solita combriccola di pazzi. Me ne vado.}
{150}{zomak6}{Beh, sta proprio… Ehi, a proposito! Chi sei tu?}
{151}{}{Sono un semplice viandante.}
{152}{}{Sono il Prescelto.}
{153}{}{Sono qui per il mio rinnovamento annuale.}
{154}{}{E' tutto a posto. Devo solo fargli un paio di domande.}
{160}{zomak7}{Beh, allora vedi di "viandare" da qualche altra parte.}
{161}{}{Uh, okay. Addio.}
{170}{zomak8}{Beh, in questo caso... Entra pure. LUI si trova proprio nella prossima stanza. Non farlo aspettare.}
{171}{}{Non io. Entro subito. Ci vediamo.}
{172}{}{Forse tornero' piu' tardi. Ci vediamo.}
{180}{zomak9}{Beh, allora faresti meglio ad andartene. Fuori di qui.}
{181}{}{Okay.}
{200}{zomak10}{Si', qui ci si puo' Rinnovare.}
{201}{}{Okay.}
{210}{zomak11}{Ook? Che cosa vuol dire? Cosa sei, stupido?}
{211}{}{Goop?}
{220}{zomak12}{Fuori di qui. Il Prof non ha tempo da perdere con i tipi come te.}
{221}{}{Okay. Adesso vado.}
{230}{zomak13}{Qui sotto non c'e' altro che il covo del Prof. Cavoli se sei stupido.}
{231}{}{Il Prof?}
{232}{}{Stavo semplicemente mettendoti alla prova. Hai superato l'esame. Adesso lasciami passare.}
{233}{}{Credo di aver perso l'orientamento. Dev'essere colpa di tutte queste radiazioni. Addio.}
{240}{zomak14}{Oops. Uh, non c'e' nulla qui. Nulla di nulla. Adesso vattene.}
{241}{}{Sei sicuro che non ci sia nulla qui?}
{242}{}{Okay. Ci vediamo.}
{250}{zomak15}{Yup. Ne sono sicuro. Adesso vattene.}
{251}{}{Beh, se lo dici tu... ci vediamo.}
{260}{zomak16}{Oh, heh, heh... yeah. I knew that. Umm, well, er, did I pass? }
{261}{}{Certo. Adesso lasciami passare.}
{262}{}{No, non ce l'hai fatta, e adesso saro' costretto a fare rapporto.}
{270}{zomak17}{Okay, allora. Puoi passare.}
{271}{}{Okay. Ci vediamo.}
{280}{zomak18}{Hai l'emblema. Passa pure.}
{281}{}{Gooo.}
{282}{}{L'emblema?}
{283}{}{Inginocchiati davanti all'Emblema. Addio.}
{290}{zomak19}{Si', il sacro talismano del Rinnovamento. Rinnova, compagno! Rinnova!}
{291}{}{Si'... tre uova anche a te. Ci vediamo.}
{300}{zomak20}{Rinnova, fratello. Puoi passare.}
{301}{zomak21}{Rinnova, sorella. Puoi passare.}
