{100}{}{Vedi un ragazzo di bell'aspetto.}
{101}{}{Vedi Davin.}
{102}{}{Vedi un ragazzo di circa vent'anni. Assomiglia molto a Grisham.}
{150}{davin1}{Se me l'avessi chiesto, avresti potuto avere me.}
{151}{davin2}{Hmpf! Miria non e' poi cosi' brava a letto.}
{152}{davin3}{Non posso credere che tu mi abbia sedotto e abbandonato.}
{153}{davin4}{La prossima volta proviamo una cosa a tre.}
{154}{davin5}{Ooo... e' cosi' carino.}
{155}{davin6}{Chiedi a lei.}
{156}{davin7}{E' stato bellissimo; chi e' il prossimo?}
{157}{davin8}{Ciao! Mi chiamo Davin; aiuto mio padre a gestire il macello di Modoc.}
{158}{}{Sto cercando l'orologio d'oro di Cornelius. L'hai visto da qualche parte?}
{159}{}{Cosa fai esattamente al macello?}
{160}{}{Ho sentito delle voci a proposito di te e i brahmin...}
{161}{}{Parlami di tuo padre.}
{162}{davin9}{Ciao.}
{163}{davin10}{Lo sapevo che saresti tornato da me.}
{168}{}{Perche' non ci mettiamo un po' piu' comodi?}
{171}{}{Sta' li'.}
{172}{davin11}{Certo, non sono occupato. Chiedi pure.}
{178}{davin12}{No, non l'ho visto da nessuna parte.}
{179}{}{Posso farti qualche altra domanda?}
{180}{davin13}{Beh, io... uhm... cioe', io... io faccio il supervisore e mi occupo di varie cose. Sono il figlio del proprietario, in fondo. Saro' io a ereditare tutto quando mio padre tirera' le cuoia.}
{182}{davin14}{E' una bugia. Io alle stalle ci vado di notte solo per... controllare che sia tutto chiuso. Sai, con tutti gli animali selvatici che ci sono in giro...}
{184}{davin15}{Papa' e' il proprietario del macello. E' un tipo a posto, per quanto un padre possa esserlo. Se vuoi discutere di affari con lui, ti metto in guardia. Nelle sue proposte non sempre dice tutto quello che c'e' da sapere.}
{186}{davin16}{Torna a trovarmi se vuoi... parlare ancora.}
{187}{davin17}{Wow, non avrei mai creduto che una cosi' bella donna avrebbe cercato di sedurmi. Cosa! Tu non sei una donna! Non preoccuparti, sei cosi' carino che non diro' nulla, se non lo dici tu.}
{188}{davin18}{Sto sicuramente sognando. Non posso credere che una cosi' bella donna stia cercando di sedurmi. Perche' tu *stai* cercando di sedurmi, vero?}
{189}{}{Guardare nei tuoi occhi vuol dire trovare il paradiso. Non rompiamo l'incanto di questo magico momento con le parole. Lasciamo che siano le azioni a parlare.}
{190}{}{Basta parlare; rovinerai tutto se continui cosi'. Siediti e divertiti.}
{191}{}{Dev'esserci un errore; volevo solo farti qualche domanda.}
{192}{}{Grazie per l'offerta, ma... no. Ehmmm... Devo proprio andare.}
{193}{}{Oh god! Take me! Take me now! [He rips off his clothes, then your clothes... then... Use your
 imagination.]}
{194}{davin20}{[Fa una risatina] Io faccio la "galleria"! La prossima volta puoi farla tu.}
{195}{}{[Due ore dopo: la terra si e' mossa, e questo letto non sara' mai piu' lo stesso.]}
{196}{}{[Un'ora -e il miglior orgasmo che tu abbia mai avuto- dopo...]}
{197}{}{[Mezz'ora dopo, disteso e senza un briciolo di energia in corpo...]}
{198}{}{[Quindici minuti e un paio di grugniti dopo...]}
{199}{}{[Prima di non sentirne piu' il bisogno, hai fatto in tempo a toglierti solo la maglietta.]}
{200}{}{Devo andare. Ciao.}
{400}{davin21}{Papa'!}
{401}{}{Uh-oh!}
{402}{davin22}{Assolutamente si'!}
{405}{davin23}{Zio Biff!}
{410}{}{Uhh...}
{411}{}{Uhhh... Continua, per favore...}
{412}{}{Per tutti i diavoli, certo che...}
{413}{}{Um... lo giuro.}
{450}{davin24}{Uhhh, non sono quello al quale dovresti parlare.}
{500}{davin25}{Oh cavoli, diventero' il capo di tutto, qui.}
{1000}{davin26}{Si', tesoro.}
{1001}{davin27}{Cosa posso fare per te, tesorino?}
{1005}{}{Non capisci. Semplicemente non voglio che tu mi stia attaccato mentre camminiamo.}
{1006}{}{Hai sbagliato nel non startene lontano mentre camminiamo.}
{1007}{davin28}{Ma... ma... cos'ho fatto di sbagliato?}
{1008}{davin29}{Che cosa vuoi da me, tesoro mio?}
{1009}{}{Grazie, stava gia' cominciando a prudermi. Allora, cosa c'e', amore?}
{1010}{davin30}{Giu' al macello ero solito scuoiare i brahmin, quindi sono piuttosto bravo con i coltelli. Inoltre, una volta papa' mi ha fatto uccidere un brahmin a sprangate. Credo di poter usare una mazza, in caso di necessita'. Uhm, ah si', una volta papa' mi ha fatto provare a sparare con un pistola, ma io mi sono spaventato e a momenti sparavo a lui.}
{1020}{}{Ho bisogno di un po' di spazio, Davin.}
{1100}{davin31}{Sono completamente sana e pronta a partire.}
{1200}{davin32}{Non mi rimangono che pochi graffi.}
{1300}{davin33}{Beh, sono quasi a posto, ma mi farebbe comodo qualche cura in piu' non appena ce ne sara' la possibilita'.}
{1400}{davin34}{Mi sono curata meglio che potevo, ma sono ancora messa piuttosto male.}
{1500}{davin35}{No, baby; voglio venire con te.}
{1600}{davin36}{Certo, la metto via.}
{1700}{davin37}{OK, ti staro' sempre appiccicato.}
{1800}{davin38}{Ma cosi' non sarei in grado di proteggerti. No, meglio che ti stia vicino.}
{1900}{davin39}{E' cosi', eh? Assolutamente no. Non voglio perderti di vista, mio pistolino amoroso.}
{2000}{davin40}{Ahia. Credo di essermi rotto qualcosa. Potresti darmi un bacio per mandar via la bua?}
{2001}{davin41}{Ugh, Mi sento bruciare. Credo di essere contaminato.}
{2002}{davin42}{Ugh, Non mi sento per niente bene. Credo di essere avvelenato.}
