{100}{}{Vedi un uomo dall'aria molto stanca, che indossa un camice bianco.}
{101}{}{Vedi il Dr. Curling, capo della Divisione Chimica dell'Esercito degli Stati Uniti.}
{102}{}{Vedi un uomo che indossa un camice da laboratorio macchiato di prodotti chimici.}
{103}{curl48}{Che cosa ci fai di fuori?}
{104}{curl49}{Penso sia meglio riportarti alla tua cella.}
{105}{curl50}{Guardie! Abbiamo un altro evaso.}
{106}{curl51}{Aspetta qui, vado a chiamare qualcuno che si occupi di te.}
{107}{curl52}{Interessante. Non pensavo che la tossina li rendesse piu' stupidi.}
{108}{curl53}{Ehila'? Ehilaaa'. C'e' nessuno?}
{109}{curl54}{Ma come hai fatto ad entrare qui dentro?}
{110}{curl55}{Fuori dal mio laboratorio, soldato.}
{111}{curl56}{Questa zona non rientra nei percorsi di pattugliamento.}
{112}{curl57}{Esci di qui, o chiamero' il sergente.}
{113}{curl58}{Fuori di qui, soldato.}
{114}{curl59}{Non ho richiesto alcun intervento armato.}
{115}{curl1}{Benvenuto nei laboratori della Divisione Chimica, soldato. Io sono il Ten. Col. Dr. Charles Curling. Adesso che ci siamo presentati - fila via dal mio laboratorio.}
{116}{}{Io non sono chi lei pensa. Mi chiamo }
{117}{}{, vengo da Arroyo e noi due abbiamo qualcosa di cui parlare.}
{118}{}{Mi scusi, signore. Errore mio. Buona giornata.}
{119}{curl60}{Seguite tutti le procedure d'emergenza.}
{120}{curl61}{Fuori dai piedi!}
{121}{curl62}{Lasciate libero il passaggio!}
{122}{curl63}{Fuori di qui, sono troppo occupato per pensare a te.}
{123}{curl64}{Non hai sentito l'allarme?}
{124}{curl65}{Cercate un riparo! L'allarme sta suonando!}
{125}{curl66}{Mi auguro che ci siano abbastanza scialuppe di salvataggio.}
{126}{curl67}{Tutti fuori!}
{127}{}{Beh, }
{128}{}{, non so come tu abbia fatto ad uscire dalla tua cella, ma non penso che noi due abbiamo qualcosa di cui parlare.}
{129}{}{Ed e' qui che si sbaglia. Per ben due volte.}
{130}{}{Hai ragione. Sono qui solo per ucciderti.}
{131}{}{Forse ha ragione. Buona giornata.}
{132}{curl3}{Sono il Ten. Col. Dr. Charles Curling, Divisione Chimica dell'Esercito degli Stati Uniti. E tu chi diavolo saresti?}
{133}{}{Sono il tuo incubo peggiore: un mutante con una pistola ed un bruttissimo carattere.}
{134}{}{Sono }
{135}{}{ di Arroyo, e noi due abbiamo qualcosa di cui parlare.}
{136}{}{Sono una persona che ha bisogno di parlare con lei.}
{137}{curl4}{Tu vorresti parlare con me? Tu chi sei e perche' mai dovrei sprecare tempo a parlare con te?}
{138}{}{Vengo da Arroyo e devo parlarle a proposito del salvataggio di migliaia di vite.}
{139}{}{Sono }
{140}{}{ e faresti meglio a parlare con me, perche' adesso ho io il coltello dalla parte del manico.}
{141}{}{Hai ragione. Non abbiamo nulla da dirci. Ma tu sei un uomo morto.}
{142}{}{Continua pure, dottore. Adesso ti lascio. Buona giornata.}
{143}{curl5}{Ecco l'ultima risorsa di tutti i primitivi dalla mente ristretta. E' cosi' facile notare cosa vi differenzia dai veri umani come noi.}
{144}{}{Lei e' cosi' dannatamente sicuro di se', eh?}
{145}{}{Fottuto bigotto che non sei altro. Qualcuno deve mettere fine alla tua vita... immediatamente.}
{146}{curl6}{Non credo di aver molto da dire ad un mutante. Presto, quando i veri umani si saranno ripresi il pianeta, tu sarai soltanto un altro degli spiacevoli ricordi della guerra.}
{147}{}{Veri umani? Di che cosa sta parlando? Sono umano quanto lei.}
{148}{}{Ce l'ho io, uno spiacevole ricordo per te... proprio qui, nella mia fondina.}
{149}{curl7}{Guardie! Aiuto! Guardie!}
{150}{curl8}{Guardie! Aiuuuuuutoooooo!}
{151}{curl9}{Aiuto richiesto nei laboratori chimici! E' urgente!!}
{152}{curl10}{Guardie! Allarme! Guardie!}
{153}{curl11}{Perche' non dovrei esserlo? Le nostre ricerche sugli abitanti del villaggio mostrano chiaramente delle alterazioni nel loro DNA. E' l'effetto della radiazione di fondo.}
{154}{}{E queste leggere differenze nel DNA hanno davvero tanta importanza?}
{155}{}{Non so esattamente di cosa stia parlando, ma queste leggere differenze hanno davvero tanta importanza?}
{156}{curl12}{No, ti sbagli. In realta' sei molto diverso da me, o almeno lo e' il tuo DNA. Un malaugurato effetto di anni di esposizione alla radiazione di fondo, immagino.}
{157}{}{E queste leggere differenze nel DNA hanno davvero tanta importanza?}
{158}{}{Non so esattamente di cosa stia parlando, ma queste leggere differenze hanno davvero tanta importanza?}
{159}{curl13}{Oh, il tuo DNA e' molto piu' che *leggermente* diverso. E' molto diverso. Se il Progetto non avesse dei tempi da rispettare, mi piacerebbe svolgere degli altri esperimenti sulla tua gente... oltre agli esami tossicologici relativi al FEV, naturalmente. Un lavoro davvero interessante. }
{160}{curl14}{Che cosa ti interessa sapere?}
{161}{}{Come mai il nostro DNA e' diverso?}
{162}{}{State svolgendo degli esperimenti sulla mia tribu'?}
{163}{}{Che cosa diavolo e' "il Progetto"?}
{164}{}{Ho sentito abbastanza. Ti meriti d'essere ammazzato come un gecko idrofobo. Addio, rottinculo.}
{165}{curl15}{Esistono diverse differenze molto sottili, principalmente. Tuttavia, non ho ancora avuto il tempo di studiare le ramificazioni di questi cambiamenti. Inoltre devo isolare il vostro corredo genomico originario, prima di azzardare qualche ipotesi sulla direzione che questi cambiamenti hanno intrapreso. Tutto sommato, pero', le informazioni in nostro possesso sono sufficientemente chiare.}
{166}{}{Cos'e' sufficientemente chiaro? Quali informazioni?}
{167}{}{Si'... forse. Lasci che le chieda qualcos'altro, dottore.}
{168}{curl16}{Ma le informazioni che ci dicono che tu e la tua tribu' non siete piu' degli umani, naturalmente! Dal momento che la tua tribu' e' rimasta fuori da un vault (vediamo... era il Vault 13, giusto?) per circa ottant'anni, chiunque sia rimasto esposto alle radiazioni per un periodo piu' lungo, sicuramente avra' un grado di mutazione ancora maggiore. Si', temo che la conclusione sia inappellabile.}
{169}{}{Conclusione? Che conclusione?}
{170}{curl17}{Beh, credevo di essere stato abbastanza chiaro. La conclusione che tu, e tutti quelli come te, non siete piu' degli esseri umani. Per far si' che noi si possa riprendere possesso della Terra e per mantenere pura la razza umana, tutti voi mutanti dovrete essere distrutti.}
{171}{}{Distrutti? Cosa significa?}
{172}{curl18}{Il Progetto, al quale l'Enclave si e' dedicata per interi decenni, ha come scopo il ritorno della razza umana sul territorio continentale degli Stati Uniti. Dio benedica l'America.}
{173}{}{Non mi sembra una cosa cosi' complessa da richiedere tutti questi anni di lavoro.}
{174}{}{Ho sentito abbastanza. Lasci che le chieda qualcos'altro.}
{175}{curl19}{Oh, stabilire un semplice avamposto non richiederebbe molto tempo. L'abbiamo gia' fatto con la base di Navarro. Ma e' stato necessario un periodo di tempo piu' lungo per trovare il procedimento adatto per la procedura di estirpazione.}
{176}{}{Procedura di estirpazione?}
{177}{curl20}{Certamente; non possiamo tornare sul continente e correre il rischio che la nostra razza venga contaminata dai mutanti umanoidi che si trovano la'. Per rendere gli Stati Uniti un posto sicuro per l'umanita', i mutanti dovranno prima essere sterminati.}
{178}{}{Cosa!?! Siete pazzi? E' un'idea abominevole!}
{179}{}{Sterminati? E come pensate di procedere?}
{180}{curl21}{Non sono d'accordo. Preferisco vederla come la forma piu' raffinata di Darwinismo sociale. Sopravvive solo chi si dimostra piu' abile nell'assicurare la propria riproduzione. Il futuro delle prossime generazioni, e dell'intera razza umana, dipendono da noi.}
{181}{}{Il cambiamento e' probabilmente l'unica costante universale. Il solo essere diversi da voi, non ci rende peggiori di voi. Inoltre, noi siamo la prova vivente della straordinaria resistenza dell'umanita'. Per questo motivo meritiamo di sopravvivere... forse anche *piu'* di voi.}
{182}{}{Non si e' mai fermato a pensare che forse, anche se diversi, noi siamo degli esseri umani proprio come voi?}
{183}{}{Tu non vedrai nessuna prossima generazione, doc. Infatti stai per morire.}
{184}{curl22}{Non avevo mai pensato alla cosa da questo punto di vista... Aspetta un secondo, per favore, mentre ci ragiono su piu' approfonditamente.}
{185}{}{OK. Faccia pure con comodo, dottore. E' un concetto molto grosso da assimilare.}
{186}{}{Non ce l'hai, un secondo. Il tuo tempo e' gia' scaduto da un pezzo. Addio, stronzo.}
{187}{curl23}{Questo e' ridicolo. Tu non sei piu' simile a me di quanto una mucca mutante bicipite lo sia ad una giovenca normale.}
{188}{}{Anche se in passato c'erano delle mucche con una sola testa, ormai sono scomparse da tempo. Ma la mucca, come specie, e' sopravvissuta ed e' diventata piu' forte. Il cambiamento e' parte integrante dell'ordine naturale.}
{189}{}{Uccidere tutti coloro che si trovano sul continente e' totalmente sbagliato.}
{190}{}{Sono stanco di tutte le tue stronzate. E' ora che tu vada ad incontrare il tuo creatore, Dr. Morte.}
{191}{curl24}{E' chiaro che quelli come te non sono in grado di capire cio' che sto cercando di spiegare. E' inutile. Adesso faresti meglio ad andartene.}
{192}{}{Beh, ci ho provato. E' tempo di morire, bigotto.}
{193}{}{D'accordo, me ne vado. Uno di noi non riesce a capire, e non credo di essere io. Addio.}
{194}{curl25}{Studi tossicologici sull'efficacia della tossina FEV, si'.}
{195}{}{La tossina FEV? Di cosa si tratta?}
{196}{}{Lascia che ti chieda qualcos'altro.}
{197}{curl26}{La tossina FEV. E' la soluzione perfetta per questo difficile problema.}
{198}{}{Cos'e' la tossina FEV?}
{199}{}{Aspetti un attimo. Lasci che le chieda qualcos'altro.}
{200}{curl27}{Una delle nostre pattuglie ha trovato le informazioni sul virus FEV, oltre a diversi campioni del virus stesso, in una ex base di ricerca militare semidistrutta.}
{201}{}{Okay, adesso so dove l'avete trovato, ma che cosa fa?}
{202}{curl28}{Il FEV era stato progettato, in un primo tempo, come un virus in grado di trasformare gli esseri umani in super-soldati. Gli esperimenti in tal senso, pero', sembra che si siano rivelati un completo fallimento, sebbene io stesso abbia provato ad inoculare una versione modificata del virus in uno dei nostri agenti del Servizio Segreto, ottenendo un risultato soddisfacente.}
{203}{}{Buon per lei, ma cos'ha a che fare tutto questo con la procedura d'estirpamento?}
{204}{curl29}{Oh, certo, beh, ci stavo arrivando... Il virus FEV e' specie-specifico, e si lega solamente alle glicoproteine umane. Sono bastati pochi anni per rendere il virus F.E.V. piu' letale di quanto non fosse gia'. Il risultato e' proprio come lo volevamo: perfetto sotto ogni punto di vista. }
{205}{}{Perfetto? Cioe'?}
{206}{curl30}{Non e' lampante, mio mutato amico? Il FEV e', grazie a me, una tossina letale e, grazie ad un misterioso genio chiamato - con un certa dose di drammaticita' - il Master, agisce solamente sugli umani, mutati e non.}
{207}{}{E allora?}
{208}{curl31}{Cio' significa che abbiamo a disposizione lo strumento perfetto per l'eliminazione totale di tutti i mutanti umanoidi che infestano il pianeta.}
{209}{}{Ancora non riesco a capire perche' e' "perfetto".}
{210}{}{Voglio chiederle qualcosa a proposito di qualcun'altra delle sue folli idee.}
{211}{curl32}{La tossina FEV colpira' soltanto gli umani, lasciando tutto il resto in vita. Meglio ancora, entro un mese tutti i mutanti saranno morti e la tossina FEV scomparira' non appena non ci saranno piu' ospiti viventi.}
{212}{}{Non credo che abbiate un numero sufficiente di vertibird per diffondere la tossina in tutto il globo.}
{213}{}{Sto per farti diventare l'ospite di uno dei miei proiettili ad energia. Di' le tue preghiere.}
{214}{curl33}{Hai ragione, non li abbiamo. Ma non ci servono. Abbiamo un sistema di rilascio che scarichera' la tossina FEV dalle vasche di contenimento direttamente nell'atmosfera esterna. Le correnti faranno il resto. La saturazione globale avra' luogo entro due settimane.}
{215}{}{Due settimane?}
{216}{curl34}{Si', due settimane perche' la tossina si diffonda, piu' un mese perche' termini il suo effetto, e a quel punto gli Stati Uniti saranno pronti ad essere nuovamente colonizzati da veri esseri umani. La nostra specie sara' stata salvata.}
{217}{}{Lei crede davvero di essere nel giusto, eh?}
{218}{}{Non c'e' dubbio, hai davvero uno spirito umanitario. Devo andarmene da qui prima che mi venga voglia di ucciderti. Addio.}
{219}{}{La tua specie forse si salvera', ma di sicuro non ti salverai tu.}
{220}{curl35}{Si'. Il prezzo da pagare per salvare una specie non e' mai troppo alto.}
{221}{}{Sono d'accordo con lei. Ma non ha mai pensato che anche i "mutanti", come li chiama lei, non sono che un altro tipo di esseri umani?}
{222}{}{Sono proprio d'accordo con te, doc. Credo che faro' tutto il possibile per salvare noi mutanti. E comincero' uccidendo te!}
{223}{curl73}{Ti ho detto che mi serviva un po' di tempo per pensarci.}
{224}{curl74}{Ho davvero bisogno di tempo per pensarci su.}
{225}{curl75}{Non e' una decisione facile.}
{226}{curl76}{Devo pensarci su.}
{227}{curl77}{Mi vuoi lasciare in pace per un secondo, o no?}
{228}{curl36}{Odio ammetterlo, ma credo che tu abbia ragione. Tutto cio' che abbiamo progettato finora e' sbagliato. Ero cosi' preso dal tentativo di superare gli ostacoli da non pensare alla moralita' delle mie ricerche.}
{229}{}{Beh, adesso che se ne e' reso conto, dovrebbe distruggere la tossina.}
{230}{curl37}{Questo potrebbe... No, non funzionerebbe.}
{231}{}{Perche' no?}
{232}{curl38}{Perche' il Progetto ripartirebbe comunque. Anche se io dovessi morire, infatti, tra qui e Navarro ci sono abbastanza informazioni da permettere di riprendere le ricerche e lo sviluppo della tossina. Solo qualcosa di piu' drastico porrebbe definitivamente fine alla questione.}
{233}{}{Qualcosa di piu' drastico? Cioe'?}
{234}{curl39}{L'Enclave deve essere distrutta. Completamente distrutta. Se non venissimo eliminati completamente, saremmo sempre in grado di rimetterci in piedi e di cominciare nuovamente da un'altra parte.}
{235}{}{Mi dispiace. Uh, dottore, come pensa che si dovrebbe procedere per distruggere l'Enclave?}
{236}{curl40}{Credo che il modo migliore sia quello di rilasciare la tossina FEV nel sistema di filtraggio dell'aria. Dal momento che l'Enclave e' un sistema a se' stante, la tossina colpira' chiunque si trovi qui dentro.}
{237}{}{E cosa ne sara' della mia gente? E di me? E di lei, per quel che importa?}
{238}{curl41}{Posso rilasciare l'antidoto nelle celle tramite i dotti d'aerazione. Il livello detentivo possiede un sistema d'aerazione separato rispetto al resto dell'Enclave. Tutti penseranno che io stia semplicemente conducendo l'ennesimo esperimento. Per quel che riguarda te, posso iniettarti l'antidoto direttamente e immediatamente (si avvicina a te con una siringa)}
{239}{}{Ahia, grazie Doc. Cosa succedera' quando la tossina FEV verra' rilasciata?}
{240}{}{Ehi, aspetta un secondo, non avvicinarti a me con quel coso!}
{241}{curl42}{Non sara' un bello spettacolo. Dovresti andartene da qui il piu' presto possibile. Io preferisco avere sulla coscienza il peso della morte di un migliaio di persone, piuttosto che quello della morte di centinaia di migliaia d'esseri umani. Il nostro tempo qui e' scaduto. Abbiamo avuto la nostra chance.}
{242}{}{Come posso liberare la mia gente dalle celle?}
{243}{curl43}{Dovresti disattivare il generatore di energia. Il reattore e' controllato da un grande computer situato nelle immediate vicinanze del reattore stesso. Non so esattamente cosa dovrai fare, pero'.}
{244}{}{La ringrazio per le informazioni che mi ha dato. Il suo sacrificio verra' ricordato da tutti i popoli della terra.}
{245}{}{Era ora che tornassi in te, vecchio tacchino. Adesso sbrighiamoci.}
{246}{}{When the stars threw down their spears,}
{247}{}{                      And water'd heaven with their tears,}
{248}{}{                            Did he smile his work to see?}
{249}{}{                                  Did he who made the Lamb make thee?}
{250}{}{Eh?}
{251}{curl45}{Oh, e' solo una cosa che ricordo di un poeta morto da molto tempo. Mi chiedo se c'e' ancora posto per quelli che hanno cosi' a lungo operato per raggiunere una fine cosi' tetra. Il nostro tempo si e' concluso, il vostro e' appena cominciato. Sbrigati!}
{252}{}{Oh, okay, grazie dell'aiuto, dottore. Lei e' un uomo valoroso.}
{253}{}{Sei un pazzo - ma un pazzo utile. Addio.}
{254}{curl68}{Sbrigati!}
{255}{curl69}{Esci subito di qui.}
{256}{curl70}{Muoviti!}
{257}{curl71}{Non c'e' piu' tempo!}
{258}{curl72}{Va', finche' sei ancora in tempo!}
{259}{curl46}{Ma non capisci? Senza di questo sarai morto nel giro di poche ore.}
{260}{}{Oh, beh, se la mettiamo cosi'... Si avvicini pure, doc. Cosa succedera' quando la tossina FEV verra' rilasciata?}
{261}{}{Niente aghi, senza se, senza ma. Mi prendo le mie responsabilita'.}
{262}{curl47}{Non ce la farai mai a salvare la tua gente senza l'antidoto. Cos'e'? Hai paura di una piccola puntura?}
{263}{}{No, credo di no. Sempre che non io la guardi mentre me la fa. Youch! Allora, cosa succedera' quando la tossina FEV verra' rilasciata?}
