{100}{}{Vedi Lydia.}
{101}{}{Vedi una donna con i capelli castani che indossa dei pantaloni marroni e un'armatura di metallo. Sembrerebbe essere la barista.}
{102}{}{Vedi Lydia.}
{103}{}{Vedi una donna con i capelli castani che indossa dei pantaloni marroni e un'armatura di metallo. Sembrerebbe essere la barista.}
{104}{lydia34}{Benvenuto! Che ne dici di bere qualcosa, Prescelto?}
{105}{lydia35}{Benvenuto, Prescelto! Prego, accomodati pure.}
{106}{lydia36}{Prego! Prendi una sedia e riposati per un attimo!}
{107}{lydia37}{E' il Prescelto! Facciamo tutti un bel brindisi per l'EROE di Fallout 2!}
{108}{lydia38}{Buon giorno, Capitano.}
{109}{lydia39}{Vault City prevale, Capitano.}
{110}{lydia40}{Buongiorno, Cittadino.}
{111}{lydia41}{Vault City prevale, Cittadino.}
{112}{lydia42}{Un mutante! Guardie! Guardie!}
{113}{lydia43}{Un ghoul! Guardie! Guardie!}
{114}{lydia44}{Il bar e' chiuso. Torna domattina.}
{115}{lydia45}{Mi spiace, le ordinazioni sono chiuse. Torna domattina.}
{116}{lydia46}{Siamo chiusi. Appena avro' finito di compilare la lista delle scorte del locale me ne andro' a letto.}
{117}{lydia1}{Ehila', Prescelto! Stavamo giusto parlando delle tue avventure... posso portarti qualcosa da bere?}
{118}{}{Lazzo, pazzo, come pozzo nero puzzo.}
{119}{}{-Allontanati-}
{120}{}{Cosa avete da bere?}
{121}{}{Vorrei alcune informazioni.}
{122}{}{Ho la partita di alcolici che mi avevi chiesto.}
{123}{}{Per oggi niente, grazie.}
{124}{lydia2}{Uh... lo sento. Um, grazie ancora per aver salvato il mondo, eh.}
{125}{}{Puzzo, struzzo me essere rozzo!}
{126}{}{-Allontanati-}
{127}{lydia3}{Ascolta, avrai anche salvato il mondo, ma un poeta non lo sei di certo. Adesso dacci un taglio.}
{128}{}{Rizzo razzo me essere pazzo!}
{129}{}{-Allontanati-}
{130}{lydia4}{Senti, prendi questi e fila fuori di qui, okay? Dovrebbero tenerti la bocca occupata per un po' di tempo.}
{131}{}{Grazie-strazie a tutte le ragazzie}
{132}{}{-Allontanati-}
{133}{lydia5}{Uh... cosa posso fare per lei, Capitano?}
{134}{lydia6}{Cosa posso fare per te, Cittadino?}
{135}{lydia7}{Si'? Posso aiutarla?}
{136}{}{Ti? Tu? Tuu? Tuiiiii. Ptuiiiii essere suono che altri fare quando vedere me.}
{137}{}{-Allontanati-}
{138}{}{Cosa avete da bere?}
{139}{}{Vorrei alcune informazioni.}
{140}{}{Ho la partita di alcolici che mi avevi chiesto.}
{141}{}{Per oggi niente, grazie.}
{142}{lydia8}{Credo che questa sia la cosa piu' affascinante che io abbia mai sentito. Voglio che anche le guardie la sentano... aspetta.}
{143}{}{Ta? To. Tu. Tuuu sexiiii for mai cloooss.}
{144}{}{-Allontanati-}
{145}{lydia9}{Abbiamo birra e liquori sintetici... vodka-H, e i derivati W e W2 della tequila. Oh, e acqua. E latte di brahmin. La birra e gli altri alcolici sintetici vengono 10 dollari, acqua o latte tre.}
{146}{lydia10}{Tipo...?}
{147}{}{Uh, non avete dei veri alcolici?}
{148}{}{Provero' un po' di birra sintetica.}
{149}{}{Un bicchierino di vodka sintetica sarebbe un vero toccasana.}
{150}{}{Un po' di tequila W2 credo possa andare.}
{151}{}{Un po' d'acqua andra' benissimo.}
{152}{}{Latte di brahmin.}
{153}{}{In realta', vorrei delle informazioni.}
{154}{}{Tornero' quando avro' piu' soldi.}
{155}{}{Credo che non prendero' nulla, grazie.}
{156}{lydia11}{Il latte di brahmin non l'abbiamo al bancone... beh, non esattamente. Dovrei andare fuori a procurarmene un po'.}
{157}{}{Va bene. Non ho problemi ad aspettare. Non vedo l'ora di bermi un bel bicchiere di latte fresco. Mmmmm-mmm. Sarebbe un vero toccasana.}
{158}{}{Penso che provero' qualcos'altro, allora.}
{159}{}{Come non detto. Senti, vorrei delle informazioni...}
{160}{}{Dimentichi cio' che ho detto. Tornero' un'altra volta.}
{161}{lydia12}{Ecco a te. Nient'altro?}
{162}{}{Uh, non avete dei veri alcolici?}
{163}{}{Provero' un po' di birra sintetica.}
{164}{}{Un bicchierino di vodka sintetica sarebbe un vero toccasana.}
{165}{}{Un po' di tequila W2 credo possa andare.}
{166}{}{Un po' d'acqua andra' benissimo.}
{167}{}{Latte di brahmin.}
{168}{}{In realta', vorrei delle informazioni.}
{169}{}{Tornero' quando avro' piu' soldi.}
{170}{}{Credo che non prendero' nulla, grazie.}
{171}{lydia13}{Oh? Ad esempio?}
{172}{}{Chi e' che comanda, qui a Vault City?}
{173}{}{Dov'e' il Vault?}
{174}{}{Puoi dirmi qualcosa riguardo alla pratica della schiavitu' qui a Vault City?}
{175}{}{Vault City ha molti contatti con il mondo esterno?}
{176}{}{Cos'avete da bere?}
{177}{}{Ho la partita di alcolici che mi avevi chiesto.}
{178}{}{Bene. Allora, buona giornata.}
{179}{lydia14}{Uh, il Primo Cittadino Lynette... tu sei un Cittadino, no?}
{180}{lydia15}{Il Primo Cittadino Lynette. Se devi parlare con lei, la puoi trovare nel palazzo del Consiglio situato a nord di qui.}
{181}{}{Vorrei sapere qualcos'altro...}
{182}{}{Okay. Andro' a parlare con lei, allora.}
{183}{lydia16}{Uh, e' quel grosso buco sul fianco della montagna a est di qui... ma scusa, tu non sei un Cittadino?}
{184}{lydia17}{E' quel grosso buco nella montagna a est di qui. Non puoi sbagliare. Non puoi entrare, pero', a meno che tu non sia un Cittadino.}
{185}{}{Vorrei sapere qualcos'altro...}
{186}{}{Ma io sono un Cittadino.}
{187}{}{Certo, volevo solo avere dei punti di riferimento, grazie. Adesso devo andare.}
{188}{}{Hmmm. Grazie delle informazioni.}
{189}{lydia18}{Certo che lo sei. Io, se fossi in te, starei attenta a non dire in giro una cosa del genere, "Cittadino". Qualcuno sapra' riconoscere qualsiasi documento falso ti abbia venduto quella sanguisuga di Skeev. Quindi cerca di mantenere un basso profilo, okay?}
{190}{}{Uh, okay. Senti, vorrei sapere un'altra cosa...}
{191}{}{Oh. Bene, grazie per il consiglio.}
{192}{lydia19}{Ascolta, la prima cosa che posso dirti e' che, da queste parti, faresti meglio a non chiamarla "schiavitu'" o ti troverai in un mare di guai. Si chiamano "servi", non schiavi. Questo e' solo un consiglio.}
{193}{}{Ho capito l'antifona. Senti, vorrei sapere un'altra cosa...}
{194}{}{Grazie. Me ne ricordero'.}
{195}{lydia20}{Non molti. La maggior parte dei contatti con gli Esterni sono quelli con i mercanti che percorrono la via carovaniera del "Grande Giro" e che arrivano da Broken Hills, New Reno e Redding. L'unico posto che conosco all'infuori di questa via e' Gecko.}
{196}{}{Parlami di Broken Hills.}
{197}{}{Parlami di New Reno.}
{198}{}{Parlami di Redding.}
{199}{}{Parlami di Gecko.}
{200}{}{Vorrei sapere qualcos'altro...}
{201}{}{Grazie delle informazioni.}
{202}{lydia21}{E' una comunita' di minatori come Redding, ma si trova molto a sud di qui. Gran parte dell'uranio che importiamo arriva da li'.}
{203}{}{Parlami di New Reno.}
{204}{}{Parlami di Redding.}
{205}{}{Parlami di Gecko.}
{206}{}{Vorrei sapere qualcos'altro...}
{207}{}{Grazie delle informazioni.}
{208}{lydia22}{E' a diversi giorni di distanza in direzione sudovest. Ho sentito voci contrastanti su Reno. Alcuni mercanti, soprattutto gli schiavisti, lo adorano, quel posto. Altri mercanti... no. Una citta' piena di lustrini... e di guai, mi dicono.}
{209}{}{Parlami di Broken Hills.}
{210}{}{Parlami di Redding.}
{211}{}{Parlami di Gecko.}
{212}{}{Vorrei sapere qualcos'altro...}
{213}{}{Grazie delle informazioni.}
{214}{lydia23}{E' una citta' mineraria molto a ovest di qui. Ultimamente non si sono viste molte carovane provenire da Redding e qualche alto papavero e' piuttosto preoccupato. Il Senatore McClure, in particolare.}
{215}{}{Parlami di Broken Hills.}
{216}{}{Parlami di New Reno.}
{217}{}{Parlami di Gecko.}
{218}{}{Vorrei sapere qualcos'altro...}
{219}{}{Grazie delle informazioni.}
{220}{lydia24}{E' una cittadina di ghoul a meno di un giorno da qui in direzione nordest, mi pare. Si dice che assalgano ogni viandante che si avventuri nel loro territorio. Meglio stare alla larga.}
{221}{}{Parlami di Broken Hills.}
{222}{}{Parlami di New Reno.}
{223}{}{Parlami di Redding.}
{224}{}{Vorrei sapere qualcos'altro...}
{225}{}{Grazie delle informazioni.}
{226}{lydia25}{Perche'? Stai forse cercando qualcosa con un po' di carica in piu' rispetto a questi liquori sintetici?}
{227}{}{Forse. Tra liquore vero e liquore sintetico non c'e' proprio storia.}
{228}{}{Veramente no. Stavo invece cercando delle informazioni...}
{229}{}{Non oggi.}
{230}{lydia26}{Non c'e' dubbio. Una volta avevo una... beh, un tempo conoscevo un mercante che aveva una bottiglia di Maddog 30/30. Roba potente... dopo averla bevuta non mi sentivo piu' la lingua, ma aveva un gusto... "diverso".}
{231}{}{Cos'e' successo al liquore di questo mercante?}
{232}{}{Vorrei alcune informazioni.}
{233}{}{Capisco. Beh, e' stato bello parlare con te.}
{234}{lydia27}{E' stato bevuto tutto. Questo e' quello che ho sentito dire. C'erano anche alcuni altri "amici", qui a Vault City, che aiutarono il mio amico a scolarsi il liquore. Pur di bere qualcosa di diverso, pagarono una bella sommetta.}
{235}{}{Lo credo. Sai, non dovrei avere problemi a procurarmi degli alcolici. Ho viaggiato a lungo nelle Lande e recuperare un po' di alcol non e' certo un problema per me.}
{236}{}{Vorrei alcune informazioni.}
{237}{}{Capisco. Beh, e' stato bello parlare con te.}
{238}{lydia28}{Davvero? Beh, se ti dovessi trovare nella situazione di volerti disfare di un po' di alcol, io potrei aiutarti. Naturalmente questo sarebbe il nostro piccolo segreto. E toccherebbe a te contrabbandare la roba all'interno delle mura.}
{239}{}{Quanto alcol ti servirebbe?}
{240}{lydia29}{Vediamo... una cassa di dieci bottiglie di liquore e dieci bottiglie di birra. Ed evita di portarmi quella roba radioattiva che ho sentito essere prodotta a Gecko. Voglio solo un po' della cara e vecchia "sgnapa", okay?}
{241}{}{Casualmente ho qui con me proprio la quantita' di alcol che mi hai chiesto.}
{242}{}{Dovrei riuscire a portarti qualche bottiglia. Senti, adesso vorrei alcune informazioni...}
{243}{}{Hmmmm. Ci pensero' su e tornero'.}
{244}{lydia30}{Magnifico! Ecco la tua ricompensa... questa somma e' pari al doppio del costo di quelle bottiglie. E questa transazione non ha mai avuto luogo, d'accordo?}
{245}{}{Nessun problema. Ehi, adesso vorrei alcune informazioni...}
{246}{}{Grazie. E' stato un piacere fare affari con te.}
{247}{lydia31}{No, quegli intrugli che nelle lande chiamano "alcol puro" sono proibiti qui a Vault City. Non voglio nemmeno sapere come li fanno. Adesso posso darle qualcosa da bere, Capitano...?}
{248}{}{Non c'e' niente di male a farsi un goccetto di liquore vero, di tanto in tanto. Certo, la Percezione ne risente un po', ma questo succede anche quando esageri con la polvere curativa...}
{249}{}{Prendero' qualcos'altro, allora.}
{250}{}{Come non detto, allora. Vorrei alcune informazioni...}
{251}{}{Capisco. Grazie lo stesso.}
{252}{lydia32}{Io non ne so nulla. Qui serviamo solo alcolici sintetici. Se per caso degli alcolici autentici entrassero a Vault City, io non ne saprei nulla.}
{253}{}{Come non detto, allora. Vorrei alcune informazioni...}
{254}{}{Capisco. Grazie lo stesso.}
{255}{lydia33}{Capisco... Beh, uh, stammi bene. Okay?}
{256}{}{Grazie-strazie a tutte le ragazzie}
{257}{}{-Allontanati-}
{258}{lydia47}{Zzzzzzzz.}
