{100}{}{Vedi un uomo che indossa con un'armatura militare standard da combattimento.}
{101}{}{Sembra essere in forma, ma un po' disorientato.}
{102}{dobbs1}{Oh, la mia testa.}
{103}{}{Chi sei?}
{104}{}{Ug!}
{105}{dobbs2}{Io-io sono Dobbs... Soldato Semplice, Prima Classe.}
{106}{}{Mi puoi dire come sei arrivato qui?}
{107}{}{Addio.}
{108}{dobbs3}{Ero in battaglia. Si', una battaglia. C'erano spari ed esplosioni dappertutto. Gente che moriva. Ero terrorizzato ma dovevo continuare a combattere. Poi c'e' stato un lampo accecante.}
{109}{}{E poi cos'e' successo?}
{110}{}{Ciao, }
{111}{dobbs4}{La cosa seguente che ricordo e' una visione del mio corpo come se lo stessi guardando dall'altro. Sentivo i dottori dire che ero morto e poi hanno gettato il mio corpo su un mucchio di altri corpi.}
{112}{}{E poi?}
{113}{}{Addio.}
{114}{dobbs5}{Degli uomini sono arrivati e hanno portato il mio corpo in un laboratorio. Li ho sentiti dire qualcosa a proposito di cercare di rigenerare i miei tessuti mettendomi in immersione dentro un qualcosa chiamato Gel Biomed.}
{115}{}{E poi?}
{116}{}{Addio.}
{117}{dobbs6}{E poi mi sono svegliato qui. Devo andare! Devo tornare alla mia unita'.}
{118}{}{Addio.}
{200}{dobbs7}{Dove sono?}
{201}{dobbs8}{Mi fa male la testa.}
{202}{dobbs9}{Perche' sono coperto di gelatina?}
{300}{dobbs10}{Devo ritrovare la mia unita'.}
{301}{dobbs11}{Oh no! Mi sono allontanato senza permesso!}
{302}{dobbs12}{Dov'e' il fronte?}
{303}{dobbs13}{Questo e' per te, Jonny.}
{400}{}{Il Soldato Dobbs subisce gli effetti della Sindorme Post-Criogenica.}
