{100}{}{Ves a un joven de aspecto fuerte.}
{101}{}{Ves al señor Peterson.}
{200}{pet1}{Hola, amigo. No te he visto por aquí antes. ¿Primera vez a la Abadía?}
{201}{pet2}{¡Es bueno que hayas vuelto! ¿Qué puedo hacer por ti?}
{202}{}{Sí. ¿Qué puedes contarme sobre este lugar?}
{203}{}{Estoy en una misión para el sagrado GECK. ¿Sabes algo de esto?}
{204}{}{El hermano Samuel dijo que podrías saber algo sobre quién está perturbando las tumbas. Él dijo que escuchaste algunos
ruidos provenientes de los cultivos.}
{205}{}{Olvídelo, debo irme.}
{300}{}{La esposa y yo vinimos hace unos años en una caravana. Nos gustó tanto que decidimos quedarnos y comenzar nuestra propia
pequeña granja. Déjame decirte, la Abadía podría no ser tan llamativa como Nuevo Reno, o tan avanzada como Ciudad Refugio, pero en lo que
a mí respecta, este lugar es tan bueno como el Yermo. La gente aquí es decente, y las personas se cuidan mutuamente.
Claro, algunos lugares pueden ofrecer más seguridad, pero a costa de la libertad personal. No gracias.}
{301}{}{¿Viniste en una caravana? ¿Vienen aquí a menudo?}
{302}{}{Realmente no. La Abadía es demasiado pequeña y está aislada para que las caravanas nos presten mucha atención. Sin embargo, no importa, somos
una comunidad bastante auto suficiente - cultivamos nuestra propia comida, elaboramos nuestra propio licor - por lo que nos las arreglamos bien. De todos modos, Bill es el hombre
para hablar sobre caravanas, dirige la tienda general justo al suroeste de aquí.}
{303}{}{Eso sueña genial, pero realmente debo marcharme.}
{304}{}{Interesante. Tenía curiosidad por algo más.}
{305}{}{Olvídelo, debo irme.}
{400}{pet5}{¿Qué más querías saber?}
{401}{}{¿Qué puedes contarme acerca de la Abadía?}
{402}{}{¿Sabes algo sobre el Kit de Creación del Jardín del Edén?}
{500}{}{Lo siento amigo, nunca he oído hablar de eso. Pero si tiene que ver con los tiempos de la pre-guerra, entonces apuesto a que hay algo al respecto
en las computadoras del monasterio. Desafortunadamente para ti, esos monjes son realmente protectores de su información, temerosos de que
conduzca a otra guerra o algo así si las personas aprenden demasiado. Aún así, podría valer la pena preguntar por allí.}
{501}{}{Gracias, lo haré. Sin embargo, tengo algunas preguntas más.}
{502}{}{Gracias por el consejo. Voy a comprobar eso ahora.}
{600}{pet7}{¿El hermano Samuel te envió aquí? ¿Qué es de ese borracho hasta ahora?}
{601}{}{Cuidando de las tumbas como de costumbre supongo. Entonces, sobre lo que escuchaste ...}
{602}{}{[John se sienta en su silla y se sirve una trago de whisky.] Todo comenzó hace un par de días. Mi esposa y
yo estábamos preparándonos para irnos a la cama cuando escuchamos un crujido en el campo. Agarré mi linterna y corrí afuera para ver
si podia encontrar la fuente del ruido. Tan pronto como llegué a los campos, los ruidos se habían detenido.}
{603}{}{Continúa.}
{604}{}{Mira, realmente debo irme.}
{605}{}{Bueno, la siguiente noche no escuchamos nada. Pero la noche después de esa, volvimos a escuchar ruidos provenientes del campo. 
 Esta vez me acerqué sigilosamente a la ventana y miré hacia afuera en lugar de correr hacia fuera. Mirando hacia la oscuridad, 
 vi una luz tenue, como la de una antigua linterna o algo así, moviéndose entre los cultivos. Después de un par de minutos, 
 la luz se dirigió hacia el cementerio.}
{606}{}{Yo quería salir y enfrentarme a quien sea o lo que fuera, pero mi esposa me convenció para que permaneciera adentro y revisara 
 las cosas en la mañana. Así que a la mañana siguiente, veo que se han comido algunos de mis cultivos y huellas frescas alrededor. 
 Ahora, no me importa alimentar a los pobres, pero no me agradan los ladrones.}
{607}{}{Trataré de atrapar a este individuo. Quizás espere alrededor de la medianoche y veré si puedo encontrar algo. 
 Bueno, gracias por la información. Cuídese.}
{608}{}{Veré lo que puedo hacer. Tengo algunas preguntas más antes de irme...}
{609}{}{Esta historia se está haciendo un poco demasiado largo. Adiós.}
{610}{}{Déjeme entenderlo. Estarías feliz de ayudar a alguien que acecha en su casa por la noche, roba sus cultivos, 
y trata de robar a sus muertos? He conocido a muchos locos en mi época, pero es posible que te lleves el pastel. 
 Es una maravilla que hallas sobrevivido tanto tiempo.}
{611}{}{[Él entorna los ojos, pero se las arregla para mantener la compostura.] Así es como hacemos las cosas aquí en la Abadía. Su amabilidad 
 es tan ofensivo para ti, entonces te sugiero que te vayas de mi casa. No voy a sentarme aquí y dejar que un tribal errante 
 me insulte frente a mi esposa.}
{612}{}{Vale, vale, ya me voy.}
{613}{}{OKAY tipo duro. Este "tribal errante" te va a matar frente a tu esposa, y quizás también la mate a ella. De hecho 
 podría matar a todos en este lugar de mierda. ¿En serio pensabas que podías escapar del horror que acecha en el Yermo? 
 Bueno, te tengo noticias cabron, el horror te ha encontrado. Y su nombre es}
{700}{pet14}{Vete al diablo aquí,}
{710}{pet12}{Qué bueno verte de nuevo. Tom ha sido de gran ayuda por aquí. Gracias de nuevo por ordenar todo eso. Ahora, ¿qué puedo hacer por ti?}
{6061}{}{Después de eso, le pregunté al hermano Samuel si había pasado algo en el cementerio. Fue entonces cuando me dijo que alguien había comenzado a desenterrar algunas de las tumbas. 
 Al parecer, quienquiera que esté haciendo esto no es lo suficientemente fuerte como para cavar en una sola noche. 
 Supongo que es algún viejo mendigo que espera desenterrar algún tesoro. 
 Si alguna vez descubres quién está haciendo esto, por favor dile que se detenga. 
 No hay necesidad de robo aquí en la Abadía y estaré encantado de ayudar a esta persona en cualquier forma que pueda.}
