{100}{}{Ves a una mujer joven.}
{101}{}{Ves a Chrissy, la hija de Rebbeca.}
{102}{}{Ves a un bella joven. Parece tener mucha confianza en sí misma y ser capaz de manejarse en una pelea.}
{103}{chrsy1}{Si has venido a intentar violarme, te pondré los huevos de corbata, ¿lo entiendes?}
{104}{chrsy2}{Déjame adivinar. Los chicos estaban cansados de que les diera donde más duele, así que te han mandado para que hagas alguna obscenidad. Bien, a ti también puedo hacerte daño, sólo necesito pegarte más fuerte. ¿Lo pillas?}
{105}{}{¿Corbata?}
{106}{}{}
{107}{}{¿Qué hay aquí? ¿Quién tú?}
{108}{}{}
{109}{}{Quiero saber quien eres y que esta pasando aquí.}
{110}{chrsy3}{Sí. Un trozo de tela que se lleva alrededor del cuello como adorno. Es como una bufanda, pero para hombres. Ahora me estoy imaginando dándote TAN fuerte que terminarías llevándolos en el cuello colgando. ¿Lo pillas?}
{111}{}{Entiendo yo. No hagas daño.}
{112}{}{Capto el mensaje; por favor, no me hagas daño.}
{113}{chrsy4}{De acuerdo, entonces: ¿por qué estás aquí?}
{114}{}{}
{115}{}{¿Aquí tú quiero saber? ¿Quién tú?}
{116}{}{}
{117}{}{Quiero saber quien eres y que esta pasando aquí.}
{118}{chrsy5}{¿En serio? ¡Fenomenal! Vamos.}
{119}{}{Vale.}
{120}{chrsy6}{Me llamo Chrissy y soy de los Okupas. Estaba explorando la semana pasada cuando encontré una entrada por allí. Pensé que podría ser una mina abandonada o algo así, y entonces decidí comprobarlo. Bien, no es una mina; es una entrada secreta al Refugio 15. El refugio lo están usando como base una banda de saqueadores llamados Nuevos Khans. Me pillaron curioseando por los alrededores y su líder, Darion, me encerró aquí.}
{121}{}{Vale. Yo llevo a casa tuya.}
{122}{}{De acuerdo, te llevaré a tu hogar.}
{123}{chrsy7}{Bien, que me aspen. Hoy debe de ser mi día de suerte. ¿A qué debo el placer de volver a verte?}
{124}{}{}
{125}{}{¿Qué hay aquí? ¿Quién tú?}
{126}{}{}
{127}{}{Quiero saber quien eres y que esta pasando aquí.}
{128}{chrsy12}{Por favor, llévame con mi madre, Rebecca.}
{129}{chrsy8}{Mi caballero de brillante armadura vuelve. Bueno, brillaría si la limpiaras de vez en cuando. Oh, y también puedes pensar en bañarte. Así que, ¿qué puedo hacer por ti?}
{130}{}{Sólo digo hola. Marcho.}
{131}{}{Solo venía a saludarte. Debo irme ahora.}
{132}{chrsy9}{Eh, sé que soy demasiado mordaz, pero quiero que sepas que te estoy muy agradecida por salvarme el trasero. ¡Muchas gracias!}
{133}{}{De nada.}
{134}{}{No hay de qué.}
{135}{chrsy10}{La gente del campamento de Okupas están protegiendo a esos chicos para mantener el secreto del Refugio, pero no saben lo que está pasando aquí en realidad. Darion nos dijo que el Refugio estaba siendo reparado para que pudiéramos tener un lugar seguro donde vivir, con mucha comida y agua, pero todo es mentira. He estado allí y he visto los alrededores. El Refugio está muerto, y las máquinas de comida y agua no funcionan. Nuestra comida y agua procede del botín de los saqueos a las caravanas.}
{136}{chrsy11}{Oye, tengo que volver a casa y advertirles de todo lo que está pasando realmente. No podemos ayudar a esos monstruos. ¿Me llevarás a mi hogar?}
