{100}{}{Ves a un hombre de aspecto malvado.}
{101}{}{Ves a Metzger, el maestro esclavista.}
{150}{}{Metzger es el líder del Gremio de Esclavistas.}
{200}{metzg1}{Me las vas a pagar.}
{210}{metzg2}{¿Qué cojones quieres? Esto es el Gremio de Esclavistas, no un refugio para yonkis del jet como tú.}
{211}{metzg3}{¿Qué cojones quieres, puta fea? Esto es el Gremio de Esclavistas, no una jodida casa de putas.}
{212}{metzg4}{¿Qué cojones quieres, puta? Esto es el Gremio de Esclavistas, no una jodida casa de putas.}
{213}{metzg5}{Estás empezando a cabrearme. ¿Y ahora qué demonios quieres?}
{214}{metzg6}{Joder, ¿y ahora qué?}
{215}{metzg7}{¿Qué?}
{216}{metzg8}{Oh, será mejor que hables rápido.}
{217}{metzg9}{¿Estás aquí para trabajar por un jodido cambio?}
{218}{metzg10}{Estoy empezando a acostumbrarme a tu horrible cara. Y... ¿has venido para algo o qué?}
{219}{metzg11}{¿Te parezco tu puto papaíto o qué? Joder, espero que no. Ahora suéltalo, ¿qué quieres?}
{220}{metzg12}{Oh, mira quién ha venido. ¿Te crees especial o algo? Habla o vete a tomar por culo.}
{221}{metzg13}{¿Qué quieres ahora, esclavista?}
{222}{metzg14}{¿Te vas a quedar ahí parado o vas a decir algo?}
{223}{metzg15}{Habla. No tengo todo el día para esta mierda.}
{230}{metzg16}{Oh, ¿y quién sería? Espero que no pienses en volver a ver a esa persona...}
{231}{metzg17}{No tienes a nadie en quién este interesado. Sólo me interesa la gente... los normales, quiero decir.}
{232}{metzg18}{Puto imbécil, ¿qué te crees que soy? ¿Una puta tienda o qué? Si tienes un esclavo que quieras vender, házmelo saber. Si quieres vender otra cosa, vete a una puta tienda.}
{233}{}{Miria}
{234}{}{Davin}
{235}{}{Vic}
{236}{}{Myron}
{237}{}{Cassidy}
{238}{}{Sulik}
{239}{}{En vez de eso, ¿puedo hacerte otra pregunta?}
{240}{}{He cambiado de idea. Adiós.}
{241}{}{Dex}
{242}{}{Cat Jules}
{243}{}{Kitsune}
{245}{metzg19}{Adelante.}
{246}{metzg20}{¿Sí?}
{247}{metzg21}{No soy tu puto sirviente, así que date prisa.}
{248}{metzg22}{¿Qué ocurre? No tengo todo el día.}
{249}{metzg23}{Dispara.}
{250}{metzg24}{Puede ser.}
{255}{}{Tengo a alguien al que me gustaría vender.}
{256}{}{Sobre Vic el Mercader...}
{257}{}{Estoy buscando a un mercader.}
{258}{}{Lara quiere que te pida permiso para luchar contra Tyler.}
{259}{}{¿Puedo unirme al gremio?}
{260}{}{¿Qué puedes contarme sobre el gremio?}
{261}{}{Quiero apuntarme a una cacería de esclavos.}
{262}{}{No importa. Adiós.}
{263}{}{ quiere unir gremio.}
{264}{}{Na.}
{265}{}{Estuve mirando a los esclavos que tienes allí, pero ya ves, tengo muy, eh ... * gustos selectivos, y ninguno de
 ellos son bastante como lo que estoy buscando. ¿Son estos todos los esclavos que tienes para ofrecer?}
{270}{metzg25}{¿Crees que podrás soportarlo? No suelo aceptar a cualquiera... qué demonios. Si la jodes, te vendo como esclavo. Tendremos que hacerte un tatuaje en la frente que te identifique ante todo el mundo como esclavista. Es permanente, así que piénsatelo bien.}
{271}{metzg26}{Así que nuestra delicada florecilla ha vuelto... Entonces, ¿has cambiado de idea? ¿Te harás el tatuaje después de todo?}
{272}{metzg27}{Sí, quizás puedas hacerlo... No hace falta mucho cerebro para ir de cacería. Si la jodes, te venderé como esclavo. Si crees que puedes hacerlo tendremos que hacerte un tatuaje en la frente que te identifique como esclavista ante todo el mundo.}
{273}{}{Hagámoslo.}
{274}{}{Tengo que pensármelo. Volveré.}
{275}{}{Mejor no. Adiós.}
{276}{}{¡Uya! [asiente]}
{277}{}{¡No no no no no!}
{285}{metzg28}{¿Qué coño crees? Esto es un gremio de esclavistas. Compro y vendo esclavos.}
{286}{}{¿De dónde consigues los esclavos?}
{287}{}{Me gustaría unirme.}
{288}{}{Otra pregunta, por favor.}
{289}{}{Oh, vale. Adiós.}
{300}{metzg29}{Oh, de aquí y de allí. Principalmente capturamos a primitivos y a nómadas cuando nos cruzamos con ellos.}
{301}{}{Parece divertido. ¿Cómo puedo unirme?}
{302}{}{Tengo otra pregunta.}
{303}{}{Oh, vale. Adiós.}
{310}{metzg30}{Quién lo iba a decir, ni siquiera lloraste. Estoy tan orgulloso de ti... de hecho, ese tatuaje te queda bastante bien. Pégame un grito cuando estés listo para tu primera cacería de esclavos.}
{311}{}{Gracias. Adiós.}
{312}{}{Ya estoy listo.}
{313}{}{¡Yo mato AHORA!}
{314}{}{Va-le.}
{320}{metzg31}{Dos de mis hombres te dejarán bastante cerca de nuestros objetivos. Te pagaré en base al número de esclavos que traigáis, pero vigila la espalda de tus compañeros. Si alguno resulta muerto, tu paga se verá reducida considerablemente.}
{321}{metzg32}{Maldición, nos hemos quedado sin presas. Tendremos que esperar a que algunos primitivos regresen a la zona. Quizás deberíamos hacer que se reprodujeran.}
{322}{metzg33}{Lo siento, pero no sirves para esto. Demasiadas pérdidas y esto es un negocio. Necesito ganar dinero, no perderlo.}
{323}{metzg34}{De acuerdo. Están listos.}
{324}{metzg35}{Bien, ya podéis marchar.}
{325}{metzg36}{Entonces, id moviéndoos.}
{326}{metzg37}{Bien. Ven a verme cuando hayas acabado.}
{327}{}{Vale.}
{328}{}{Uh.}
{340}{metzg38}{Mata sólo a los hostiles. Si te atacan, mátalos. No quiero tener que lidiar con ellos, son un fastidio demasiado grande. Una vez que hayas acabado, los otros esclavistas rodearan y marcarán al resto.}
{341}{}{Vale.}
{342}{}{Oh.}
{350}{metzg39}{Una vez que empiecen a marcar a los esclavos, puedes volverte si quieres. Se necesita un entrenamiento especial, así que no trates de someterlos por ti mismo. Puedes hacer lo que quieras siempre y cuando no dañes a la mercancía.}
{351}{}{De acuerdo.}
{352}{}{Oh oh.}
{360}{metzg40}{Ah, sí. Es bastante guapa. Te daré}
{361}{metzg41}{Está bien. Podría quitártelo de encima por, oh, digamos... ¿}
{362}{metzg42}{Puto idiota. ¿Qué te hace pensar que quiero a ese imbécil de vuelta? ¡Le costó una eternidad arreglar una maldita radio! ¡Una radio! Es todo tuyo. No le quiero por aquí rompiendo más cosas.}
{363}{metzg43}{No lo sé, está bastante delgaducho... ¿pero es listo? Eso podría valer algo. Te daré el dinero}
{364}{metzg44}{Este parece que pudiera defenderse bastante bien en una pelea. Hmm... }
{365}{metzg45}{Otro primitivo. Esto parece un espectáculo de monstruitos. Aunque parece fuerte y ese aspecto podría darme más dinero. ¿}
{366}{}{¿Qué tal otro?}
{367}{}{Bueno, entonces déjame hacerte otra pregunta.}
{368}{}{Vale.}
{369}{}{Bien.}
{370}{}{Vale.}
{371}{}{No es suficiente.}
{372}{}{No.}
{380}{metzg46}{De acuerdo, chicos, metedle en las jaulas.}
{381}{metzg47}{De acuerdo, chicos, metedla en las jaulas.}
{382}{}{De acuerdo, jefe.}
{390}{metzg48}{Bien, entonces no me hagas perder el puto tiempo. Si alguna vez das con alguien de quien quieras separarte, ven a verme.}
{391}{}{Tengo otra pregunta que hacerte.}
{392}{}{Vale. Adiós.}
{400}{metzg49}{¿Qué pulga le ha picado de repente? Le dí a esa puta una oportunidad hace tiempo. No pensé que tuviera suficientes pelotas para intentar esto.}
{401}{}{¿De qué estás hablando?}
{402}{}{Así que, ¿está bien?}
{410}{metzg50}{Oh, no juegues a hacerte el tonto conmigo. Sé exactamente lo que está planeando. Le dí una oportunidad hace tiempo y no estuvo a la altura, pero si cree que puede hacerlo...}
{411}{}{Así que, ¿está bien?}
{420}{metzg51}{Bueno, yo diría que la oferta sigue en pie. Si realmente cree que puede patearle el culo y que está más capacitada para vigilar mis cosas...}
{421}{}{¿Bien?}
{422}{}{Entonces, ¿eso es un sí?}
{430}{metzg52}{Mira, me importa una mierda cuál de los dos las vigile. Mientras mi mercancía no resulte dañada, no me importa.}
{431}{}{Otra pregunta, por favor.}
{432}{}{Vale, gracias.}
{440}{metzg53}{¿Qué cojones me estás preguntando? ¿Te parezco un jodido... oh, espera. ¿Estás buscando a Vic?}
{441}{metzg54}{Él es el que está 'especializado' en tecnología de los Refugios, o eso dice. Ahora es de mi propiedad. No va a ir a ninguna parte.}
{442}{}{¿Qué pasa con él?}
{443}{}{Sí, es él.}
{444}{}{¿Puedo verle?}
{445}{}{¿Por qué le retienes aquí?}
{446}{}{Vale, gracias. Adiós.}
{455}{metzg55}{Ese jodido idiota... me vendió una radio que decía sería capaz de captar algunas transmisiones. No podía. Le pillé intentando escaparse del pueblo antes de que me diera cuenta. Un gran error. Nadie me jode. Tiene suerte de seguir vivo.}
{456}{metzg56}{Como dije, primero tiene que arreglarla. Después ya veremos.}
{457}{metzg57}{Bien, finalmente ha hecho funcionar esa maldita radio, pero eso no quiere decir que vaya a salir de esta tan fácilmente.}
{458}{metzg58}{Intentó engañarme.}
{459}{}{¿Puedo verle?}
{460}{}{¿De qué clase de transmisiones hablas?}
{461}{}{Vale, gracias.}
{462}{}{¿Quizás algo de dinero ayude a resolver las cosas?}
{463}{}{¿De qué clase de transmisiones hablabas antes?}
{475}{metzg59}{¿Para qué? Ah, joder, da igual. Tan sólo no hagas que deje de arreglar esa radio... y será mejor que la arregle pronto. Estoy harto de alimentar a ese culo gordo.}
{476}{}{¿Por qué le retienes aquí?}
{477}{}{Gracias.}
{485}{metzg60}{El Enclave y Nuevo... Eh, ¿qué demonios te importa a ti? Es mi negocio. Tengo que asegurarme de que nadie intenta joderme. Es todo lo que tengo que decir.}
{486}{metzg61}{Métete en tus propios asuntos.}
{487}{}{Vale.}
{495}{metzg62}{Claro, pero te costará }
{496}{metzg63}{¿}
{497}{}{¿No podemos llegar a un acuerdo?}
{498}{}{Bien. Aquí tienes.}
{499}{}{Podría hacerte antes unas preguntas.}
{500}{}{Lo siento, no puedo permitírmelo.}
{510}{metzg64}{Bien, es tuyo, pero saca su culo de aquí antes de que cambie de idea y le meta una bala en la puta cabeza.}
{511}{}{¿Podría hacerte antes una pregunta?}
{512}{}{Gracias.}
{520}{metzg65}{Oh, sí, podemos llegar a un acuerdo placentero tú y yo... Será tuyo por la mitad si haces que merezca la pena...}
{521}{metzg66}{Mejor que dejes de burlarte de mí, chica. No tengo mucha paciencia.}
{522}{}{Sólo si eres bueno conmigo.}
{523}{}{Claro, por qué no.}
{524}{}{Quizá más tarde.}
{530}{metzg67}{Oh, sí que lo seré...}
{531}{}{Bien.}
{540}{metzg68}{Aquí tienes }
{541}{metzg69}{Aquí tienes tus }
{542}{metzg70}{Bien hecho ahí fuera. Ten }
{543}{metzg71}{Aquí está tu dinero, }
{544}{metzg72}{¿}
{545}{metzg73}{Bien, son }
{546}{metzg74}{No era tan difícil, ¿no? La próxima vez no quiero fallos. Aquí tienes}
{547}{metzg75}{¿}
{548}{metzg76}{¡Vamos! }
{549}{metzg77}{Recuerda, vigila la espalda de tus compañeros y mata sólo a los esclavos hostiles. Aquí tienes }
{550}{metzg78}{¡Sólo $}
{551}{metzg79}{¿Quieres ganar algo o no? Me estás cabreando. ¿Cómo puede ser de difícil? Ahora toma tus $}
{552}{metzg80}{¿Qué cojones de problema has tenido? No has ganado una mierda esta vez. Estamos en esto para hacer dinero, no para ir haciendo el idiota.}
{553}{}{Lo haré mejor la próxima vez.}
{554}{}{Gracias por nada.}
{555}{}{Gracias.}
{556}{}{Uhg.}
{570}{metzg81}{Maldita puta, ¿era tu primera vez? Es imposible que no fuera tu primera vez.}
{571}{metzg82}{Maldita chica, ¿era tu primera vez?}
{572}{metzg83}{Ha estado bastante bien, supongo.}
{573}{metzg84}{Muy bueno, quizás podamos repetirlo otro día.}
{574}{metzg85}{¡Carajo! Eso ha sido... un dinero muy bien gastado.}
{575}{metzg86}{¡Carajo! Ha sido el mejor polvo que he echado nunca, y he echado muchos.}
{600}{metzg87}{¡ESTÚPIDO IDIOTA! ¿Cómo te atreves a abandonar a tus camaradas ahí afuera? [Te escupe en la cara] ¡MATADLE!}
{601}{}{Pero yo...}
{602}{}{De acuerdo, venid a por mí.}
{620}{metzg88}{Bien, me alegra ver que pudiste contarlo.}
{621}{}{Si, fue una cacería dura.}
{622}{}{Gracias. Las cosas se pusieron difíciles.}
{623}{}{¡Agra Di ero!}
{630}{metzg89}{Oh, ¿quieres dinero? ¿Quieres que te pague?}
{631}{}{Yah.}
{632}{}{Ugh.}
{640}{metzg90}{Por supuesto, me ENCANTARÍA ayudarte aunque resulta que... hay un pequeño problema... algo acerca de que atacaste a uno de mis hombres.}
{641}{}{¡Lo siento! Yo no quería... Es decir... ¿Ug?}
{642}{}{Oh, oh.}
{650}{metzg91}{Oh, no te preocupes. El cuerpo me está pidiendo pagarte... quiero decir, hacértelo pagar. Chicos, hoy es el día de paga.}
{651}{metzg92}{Oh, no te preocupes. El cuerpo me está pidiendo pagarte... quiero decir, hacértelo pagar. Chicos, acabad con esta puta.}
{652}{}{Ups.}
{653}{}{¡Garaka!}
{654}{}{Uh... ¿Gacias?}
{670}{metzg93}{Oh, estoy seguro. Este trabajo no se puede tomar a la ligera. Exige confianza y lealtad. Cuidamos de nuestros compañeros. Una buena política, ¿no crees?}
{671}{}{Supongo.}
{672}{}{Eh, ¿qué ocurre?}
{673}{}{Desde luego que sí.}
{680}{metzg94}{¿Supones? No pensaba que fueras tan listo. Eres un puto idiota. [Metzger se te queda mirando y entonces mira a sus hombres señalándote con la mirada.]}
{681}{}{¿Qué vas a hacer?}
{682}{}{¿Qué?}
{690}{metzg95}{Oh, así que no eres tan idiota como parece. Bueno, es una pena. Veras, tengo un pequeño dilema. Alguien tuvo las agallas de atacar a mis hombres.}
{691}{}{¿De verdad?}
{692}{}{¡Fue un accidente!}
{700}{metzg96}{¿De verdad? Me alegra que estés de acuerdo. ¿Y qué harías si alguien traicionara esta confianza?}
{701}{}{Eh, ¿darles una advertencia?}
{702}{}{Mira, deja que te lo muestre. [Atacas]}
{703}{}{Hacer que lo paguen.}
{710}{metzg97}{¿Eso crees? ¿Honestamente? No lo sé. Yo pensaba en algo más... permanente. [Con una sonrisa malévola, Metzger mira a sus guardias y les guiña el ojo.]}
{711}{}{¿Qué?}
{712}{}{Oh, caray...}
{720}{metzg98}{Me alegra que estemos de acuerdo. [Metzger mira a sus guardias.] Chicos, día de paga.}
{721}{}{Eh...}
{730}{metzg99}{Sí. Es una pena, la verdad. Esta persona no parece entenderlo, pero va a hacerlo muy pronto. [Ves como Metzger realiza un pequeño gesto con la mano a sus hombres.] Hora de jugar.}
{731}{}{Oh, ¿en serio?}
{732}{}{Oh, oh.}
{740}{metzg100}{Si, me temo que los accidentes suelen ocurrir por aquí con bastante frecuencia. De hecho, presiento que estamos a punto de tener otro. [Metzger sonríe agradablemente y entonces le guiña el ojo a sus hombres.]}
{741}{}{¡Que vengan!}
{742}{}{¿No voy a salir vivo de esto, no?}
{750}{metzg101}{Oh, pero va a ser divertido. Confía en mí.}
{751}{}{Vete a la mierda.}
{752}{}{Eh, está bien.}
{800}{}{Has matado al líder del Gremio de Esclavistas.}
{900}{metzg102}{Lo que ves, es lo que hay. Si no te gusta mi mercancía, entonces vete a la mierda y deja de hacerme perder mi tiempo.}
{901}{}{Eh, lo siento. Entonces déjame preguntarte otra cosa.}
{902}{}{Bien. Creo que iré entonces.}
{903}{}{En realidad, creo que voy a malgastar-*te* y toda tu maldita operación enferma.}
{910}{}{Esto es todo lo que tengo, selectivo de mierda, pero siempre recibo nuevos productos de mi otro campamento de esclavos.
Tal vez si vuelves más tarde, tendré algo que te haga gracia, pero en su mayoría son tribus ignorantes que se ven jodidamente igual, entonces si eso no es lo tuyo, tal vez no seas afortunado.}
{911}{}{Mira, esta podría ser una solicitud inusual, pero realmente me gustaría obtener las primeras impresiones sobre cualquier mercancía nueva que hayas obtenido. Hay posibilidad de ir a ver la mercancía en tu otro campamento? Por supuesto, estaría dispuesto a pagar un precio superior.}
{912}{}{Está bien. Volveré más tarde entonces.}
{913}{metzg104}{Bien, pero la próxima vez hazme un favor y no pierdas mi tiempo a menos que tengas asuntos reales para discutir.}
{914}{metzg105}{Precio premium, ¿eh? Ahora estás hablando mi lenguaje. Generalmente manejamos las ventas aquí, pero supongo que se puede hacer una excepción, mientras seas serio. Te diré cómo llegar allí, pero será mejor que te lo guardes. Lo juro, si resultas ser un espía para ellos, jodidos Rangers, te perseguiré y te sacaré la piel. [Escuchas sus instrucciones y notas la ubicación del campamento de esclavos en tu Pipboy.]}
{915}{}{Entiendo. Déjame hacerte otra pregunta.}
{916}{}{Gracias. Estaré en camino ahora. Adiós.}
{1360}{}{ dólares por ella. ¿Qué te parece?}
{1361}{}{?}
{1363}{}{.}
{1364}{}{.}
{1365}{}{?}
{1496}{}{.}
{1540}{}{. Un gran trabajo, joder.}
{1541}{}{. Has estado genial. Sigue así.}
{1542}{}{.}
{1543}{}{. }
{1544}{}{ no es que sea poco dinero, pero no te mereces mucho más que eso.}
{1545}{}{ dólares esta vez. Muy buen trabajo.}
{1546}{}{.}
{1547}{}{? No está mal.}
{1548}{}{? Puedes hacerlo mejor que eso.}
{1549}{}{.}
{1550}{}{! ¡Esto es una puta miseria! Hazlo mejor o te daré una paliza.}
{1551}{}{ dólares y fuera de aquí.}
{2540}{}{.}
{2543}{}{.}
{15401}{}{. Un gran trabajo, }
