{100}{}{Ves a una prostituta.}
{150}{}{Una prostituta corriente y moliente.}
{152}{}{[HABLAR]}
{153}{shela1}{Eh, ¡no lo hago con chicas!}
{154}{}{Lo que sea.}
{155}{}{Lo siento.}
{156}{}{¿Mamá?}
{157}{shela2}{Eh, te costará más si traes audiencia contigo.}
{158}{}{Eh, ellos vienen donde voy yo.}
{159}{}{Quiero que estén conmigo.}
{160}{}{Volveré.}
{161}{}{¿Mamá?}
{162}{shela3}{Oh, chico. ¿Dónde has estado toda mi vida?}
{163}{}{Justo aquí, nena.}
{164}{}{¿Cuanto, hermana??}
{165}{}{Um, tengo que irme. Adiós.}
{166}{}{¡Yeehhee!}
{167}{shela4}{Mmmm, me gustan grandes y tontitos.}
{168}{}{¡Ese soy yo!}
{169}{}{¡Yay!}
{170}{}{Oh. No. Adiós.}
{171}{shela5}{¡Qué chico más grande eres!}
{172}{}{Como a ti te gustan.}
{173}{}{Sí, señora.}
{174}{}{Tengo que irme.}
{176}{}{¡SI!}
{177}{}{No. Adiós.}
{178}{shela6}{Volverás.}
{179}{}{Ya veremos.}
{180}{}{Um, no.}
{181}{}{[babeas]}
{182}{shela7}{No tienes suficiente dinero. Piérdete, cariño.}
{183}{}{Volveré.}
{184}{}{No lo vales, guapa.}
{185}{}{¡Wah!}
{186}{shela8}{¡Eres increíble!}
{187}{}{Siempre lo soy, nena.}
{188}{}{Lo que sea.}
{189}{}{Tú también lo eres.}
{190}{}{¡In-e-ible Yooooooo!}
{191}{shela9}{¡Ha sido genial!}
{192}{}{Gracias. Tú también has estado genial.}
{193}{}{Hmm.}
{194}{}{Sí.}
{195}{}{¡Genial!}
{196}{shela10}{Vale, ya está. Adiós.}
{197}{}{¿Es eso?}
{198}{}{Vale. Adiós.}
{199}{}{Ha estado bien.}
{200}{}{Adiós.}
{201}{shela11}{No me pagan lo suficiente para esto.}
{202}{}{De todas formas no es que valgas el dinero que cuestas.}
{203}{}{Tú te lo pierdes.}
{204}{}{Adiós.}
{205}{}{¿No fuki fuki?}
{206}{shela12}{Vuelve cuando quieras.}
{207}{}{Vale. Adiós.}
{208}{}{Sí, claro.}
{209}{}{¡Whoo!}
{210}{shela13}{Nos vemos.}
{211}{}{Adiós.}
{212}{}{Adiós.}
{213}{shela14}{Te costará }
{214}{}{ por una sesión. Primero paga.}
{215}{shela17}{Sígueme.}
{216}{shela18}{Estoy esperando.}
{217}{shela19}{No voy a quedarme parada en esta habitación todo el día.}
{218}{shela20}{¿Podrías darte prisa?}
{219}{shela21}{Última oportunidad.}
{220}{shela22}{Bien; no pienso esperar más.}
{221}{shela23}{Vamos, vamos.}
{222}{shela16}{¿Llevas una pistola en el bolsillo o es que te alegras de verme?}
{223}{shela24}{Sígueme.}
{224}{shela25}{Eh, amigo, las manos fuera de la mercancía.}
{225}{shela26}{¡Para ya! No soy ningún juguete.}
{230}{shela15}{¿Qué...? ¿Era tu primera vez?}
