{100}{}{Ves al dueño de la tienda.}
{101}{}{Ves a Tubby.}
{150}{}{Este es el dueño de la tienda.}
{151}{}{Este es Tubby, el dueño de la tienda.}
{152}{}{[HABLAR]}
{153}{tubby1}{Preferiría que te marcharas con tus asuntos a otro lado.}
{154}{}{Eres un hombre de negocios. Hagamos negocios.}
{155}{}{Quiero hacerte una pregunta.}
{156}{}{Adiós.}
{157}{tubby2}{Me alegro tanto de verte de nuevo. ¿Qué puedo hacer hoy por ti?}
{158}{}{Vamos a hacer negocios.}
{159}{}{¿Puedo preguntarte una cosa?}
{160}{}{Ahora mismo nada. Adiós.}
{161}{tubby3}{Hola y bienvenido a la tienda de Tubby. Soy el dueño. ¿Puedo ayudarte?}
{162}{}{Sí, quiero comerciar.}
{163}{}{Necesito información.}
{164}{}{Adiós.}
{165}{tubby4}{Hola, señorita. Mis amigos me llaman Tubby y te doy la bienvenida a mi tienda. ¿En qué puedo ayudarte?}
{166}{}{Quiero comprar algunas cosas.}
{167}{}{Necesito información.}
{168}{}{Adiós.}
{169}{tubby5}{En vez de eso, preferiría que te largaras.}
{170}{}{Adiós.}
{171}{tubby6}{¿Qué es lo que quieres saber?}
{172}{}{¿Quién está al mando en el pueblo?}
{173}{}{¿Por qué todo el mundo vende drogas?}
{174}{}{¿Sabes dónde se encuentra el Refugio 13?}
{175}{}{Me gustaría hacer negocios.}
{176}{}{Olvídalo . Adiós}
{177}{tubby7}{Oh, Dios. Creo que tenemos un problema de comunicación. Por favor, guiña el ojo si quieres comprar o vender algo.}
{178}{}{[Guiñas el ojo].}
{179}{}{Adioooos.}
{180}{tubby8}{Nadie, me temo. La Guarida es un lugar anárquico donde se aplican las teorías de la evolución darwinianas. Sólo los más fuertes, rápidos o inteligentes sobreviven. Estoy seguro de que hallarás tu lugar aquí.}
{181}{}{Um, gracias.}
{182}{tubby9}{Vale. Las drogas son la base del sistema económico de esta ciudad, al igual una otra ciudad puede usar grano o oro. Redding es un otro ejemplo de cuidad alimentada por drogas. Malditos mineros están demasiado drogado todo el tiempo para hacer cualquier trabajo real. Nunca he estado allí, pero es un par de días al sureste de aquí si quieres verlo.}
{183}{}{Gracias.}
{184}{tubby10}{He oído hablar de un lugar llamado Ciudad Refugio. Desgraciadamente, no puedo indicarte la dirección hasta allí. Verás, muy poca de la gente del pueblo puede costearse los tratamientos médicos que ofrecen, así que la mayoría nunca ha ido allí.}
{185}{}{De acuerdo. Gracias.}
{186}{tubby11}{Esa no es la clase de información que le DARÍA a cualquiera.}
{187}{}{¿Qué tal si cien pavos te hacen cambiar de idea?}
{188}{}{Qué tal si te doy 50 dólares y me lo cuentas.}
{189}{}{¿Qué me dices? Tú me das la información y yo no te abro un nuevo agujero en la cabeza.}
{190}{}{No importa.}
{191}{}{Bueno, ¿puedo preguntarte otra cosa, entonces?}
{192}{tubby12}{Claro, el dinero PODRÍA hacerme cambiar de idea. ¡Pero no lo tienes!}
{193}{}{Debo habérmelo dejado en alguna parte. Voy a buscarlo.}
{194}{tubby13}{Creo que esto no va a ser suficiente.}
{500}{tubby14}{Claro Petey. Estaré ahí en un segundo.}
{501}{tubby15}{¡Aguanta, Petey!}
{502}{tubby16}{Ya voy, ya voy.}
{510}{tubby17}{Aquí tienes, Petey.}
{511}{tubby18}{Sabes, Petey, deberías dejar esta mierda.}
{512}{tubby19}{Toma esto y lárgate de aquí, Petey.}
{520}{tubby20}{Un placer hacer negocios contigo.}
