{100}{}{Ves a un esclavo.}
{101}{}{Ves a Vic.}
{150}{}{Este esclavo parece estar bajo estricta vigilancia.}
{151}{}{Este es Vic.}
{152}{}{[HABLAR]}
{153}{}{¿Le vas a decir que no puedo... espera. ¿Quién eres tú? No eres un esclavista. ¿Qué estás haciendo aquí?}
{154}{}{Me llamo }
{155}{}{. He venido para sacarte de aquí.}
{156}{}{Soy }
{157}{}{, ¿pero por qué has sido encerrado en esta habitación?}
{158}{}{¿Puedes decirme dónde está el Refugio 13?}
{159}{}{Soy }
{160}{}{. Volveré.}
{161}{}{Dubba iba }
{162}{}{.}
{163}{}{Metzger sigue estando bastante enfadado conmigo, incluso aunque hayamos arreglado su maldita radio. ¡Está amenazándome con venderme! Haré lo que quieras si eres capaz de sacarme de este lío.}
{164}{}{Vale, lo haré.}
{165}{}{Lo siento, no puedo. Adiós.}
{166}{}{Whoo.}
{167}{}{Oh, hola otra vez. Está maldita radio no va a repararse sola. ¿Cómo espera que la arregle?}
{168}{}{¿Cómo puedo ayudarte?}
{169}{}{Quizás yo pueda repararla.}
{170}{}{¿Puedes usar esta radio que encontré?}
{171}{}{Sé lo que podemos hacer.}
{172}{}{¿Spa pa?}
{173}{}{Sé que puedo hacerlo. Tan sólo necesito algunas piezas sueltas. Hay una vieja radio en mi choza de Klamath que es exactamente lo que necesito. ¿Has estado donde los Dunton? Mi choza... bueno, estaba justo al este de su local.}
{174}{}{¿Quieres decir esta radio?}
{175}{}{Iré a buscarla.}
{176}{}{Hmmm... Volveré.}
{177}{vic5}{¡Eso es genial! Tendré la radio arreglada en un momento.}
{178}{}{Vale, hablaré con Metzger.}
{179}{vic6}{Gracias.}
{180}{}{Adiós.}
{181}{vic7}{¿Perdón? Lo siento pero no te entiendo.}
{182}{}{hurm.}
{183}{vic8}{¡Gracias! Estaré siempre en deuda contigo. ¿Qué puedo hacer para devolverte el favor?}
{184}{}{Dime dónde está el Refugio 13.}
{186}{}{Ven conmigo, me vendría bien algo de ayuda.}
{187}{}{No fue nada. Adiós.}
{188}{}{¿Carameeelo?}
{189}{}{¿Refugio 13? Ciudad Refugio está al este de aquí. A veces voy a allí a comerciar.}
{190}{}{¿Quieres ir allí conmigo?}
{191}{}{Gracias. Adiós.}
{192}{}{Claro, ¡iré contigo! A este viejo aún le quedan ganas de una última aventura. ¡Estoy seguro! Soy bastante bueno arreglando cosas, a pesar de lo que Metzger diga.}
{193}{}{Genial, vamos.}
{194}{}{Bienvenido a bordo.}
{195}{}{Lo que sea.}
{196}{}{Vic mi amigo me-jor.}
{197}{}{¿Quieres unirte a mí en mi búsqueda?}
{198}{}{¡Genial! Gracias.}
{203}{vic11}{Ciudad Refugio está al este de aquí. Te la señalaré en ese mapa tuyo.}
{204}{}{Gracias.}
{206}{vic12}{Está justo aquí [señalándola en el mapa].}
{220}{vic13}{Maldición. Eso estuvo cerca, pero necesito la radio de mi choza de Klamath. Sé que tiene las piezas que me hacen falta.}
{300}{vic14}{Sí, probablemente pueda ayudarte, pero primero tienes que sacarme de aquí.}
{301}{vic15}{Te lo dije. Si me sacas de aquí, te ayudaré con lo que quieras.}
{302}{}{¿Y cómo hacemos eso?}
{303}{}{Entonces estás sólo.}
{304}{}{Vale, veré lo que puedo hacer.}
{350}{vic117}{¿Crees que puedes sacarme de aquí?}
{351}{vic118}{Metzger sigue sin dejar que me vaya.}
{352}{vic119}{No podré aguantar esto mucho más tiempo.}
{353}{vic120}{Haré cualquier cosa por ti si me ayudas.}
{354}{vic121}{¡Te devolveré todos los gastos que tengas que hacer!}
{400}{}{¿Aún no has ido a mi casa, verdad? Necesito esa radio de verdad, Metzger está cada día más furioso conmigo.}
{450}{}{¿De dónde has sacado esta cantimplora de agua?}
{451}{}{Tenía una cantimplora de agua que tenía grabado un gran número 13 amarillo. ¿Recuerdas dónde la conseguiste?}
{500}{vic17}{Oh, sí. Lo recuerdo. Se la compré a Ed. Es un tratante de ganado de Ciudad Refugio.}
{501}{}{¿Cantimplora de agua? Oh, espera. Sí, tenía una docena de ellas. Se vendieron bastante bien. Se las compre a Ed, un tratante de brahmines de Ciudad Refugio.}
{502}{}{¿Ciudad Refugio?}
{550}{}{¿Podrías dejar de llamarme Jefe?}
{600}{vic19}{¡Claro, Jefe!}
{601}{}{¡Lo digo en serio! ¡PARA!}
{602}{}{Supongo que tendré que conformarme con eso.}
{650}{vic20}{¡Lo has pillado!}
{651}{}{¡Uggg!}
{700}{}{Ser mi amigo.}
{710}{}{Podrías decirles que no puedo arreglar esto sin las piezas necesarias. No sé... espera. ¿Quién eres tú? ¿Algún recluta nuevo? Te ha enviado aquí para presionarme otra vez, ¿no? No va serviros de nada. Aquí no puedo arreglarla.}
{750}{}{¡Caray! ¿Harías eso por mí? Haré lo que sea si puedes sacarme de este lío. El único problema es que Metzger me ha encerrado aquí hasta que arregle esta radio y no tengo las piezas que necesito.}
{753}{}{¿Dónde puedo encontrar las piezas que necesitas?}
{754}{}{Sé lo que podemos hacer.}
{760}{}{Es una larga historia. Se podría decir que Metzger me ha metido aquí hasta que arregle esta maldita radio. El cristal está roto y no tengo piezas de recambio. ¿Cómo espera que la arregle?}
{761}{}{Bien, he venido para sacarte de aquí.}
{764}{}{No lo sé. Nos vemos.}
{800}{vic24}{Tengo que conseguir arreglar esta radio. Si puedes ayudarme a hacerlo, quizás podamos razonar con él.}
{801}{}{¿Cómo puedo ayudar?}
{803}{}{Lo dudo. Buena suerte.}
{810}{vic25}{Por qué tuviste que matar a la pobre Mamá... Supongo que tendrías tus razones... Lo siento, Jefe. No debería cuestionarte. Este es un pueblo bastante malvado. Seguro que hizo algo bastante malvado.}
{811}{vic26}{Eh, Jefe. Gracias por sacarme de ese lío con Metzger. ¿Necesitas algo? Mamá ha sido muy amable conmigo dándome de comer mientras estabas fuera. La he ayudado a llevar el local...}
{812}{}{Adiós.}
{813}{}{Oooh.}
{814}{}{Adiooos.}
{823}{}{¿Puedes decirme otra vez dónde está tu amigo Ed?}
{830}{vic27}{Lo haría si pudiera, pero lo tuyo no tiene buena pinta. Sólo sería una carga. Ahora que Mamá se ha ido, creo que me marcharé. No se a dónde... quizás nos volvamos a ver. Gracias por todo lo que has hecho por mí.}
{831}{vic28}{Lo haría si pudiera, pero lo tuyo no tiene buena pinta. Parece que apenas eres capaz de cuidar de ti mismo. Yo tan sólo sería una carga. Yo me quedaré aquí, la comida de Mamá me recuerda a la de mi ex-mujer...}
{832}{vic29}{Lo haría, honestamente, haría casi cualquier cosa por ti. Es tan sólo que ahora mismo no pareces ser capaz de liderar a nadie. Yo tan sólo sería una carga. Me quedaré con Mamá, un tiempo... hasta que puedas arreglar las cosas. No he probado su comida desde hace mucho tiempo.}
{833}{vic30}{Lo siento, Jefe. Parece que ya tienes bastante gente contigo. Ahora que Mamá se ha ido, creo que me marcharé. No se a dónde... quizás nos volvamos a ver. Gracias por todo lo que has hecho por mí.}
{834}{vic31}{Ya llevas demasiada gente contigo, Jefe. Esperaré aquí hasta que hasta que puedas arreglar las cosas. La comida de Mamá me recuerda a la de mi ex-mujer... aunque no sé si eso es algo bueno o malo...}
{835}{vic32}{Me encantaría, Jefe. Pero parece que no tienes espacio para nadie más en el grupo. Me quedaré en el local de Mamá. No he estado allí desde hace un tiempo. Ven a verme si encuentras sitio para mí.}
{840}{vic33}{Ed se encuentra en Ciudad Refugio. Es un tratante de brahmines. Él tan sólo era uno de mis muchos proveedores. Ciudad Refugio está al este, no muy lejos de aquí.}
{845}{vic34}{Ya te lo he dicho, está por aquí. [Vic señala el lugar en tu Pip-Boy 2000].}
{900}{}{Vic te ha hablado de su vida como mercader.}
{1000}{}{Necesito preguntarte algo.}
{1100}{vic35}{Curado del todo, Jefe. ¿Algo más?}
{1200}{vic36}{Estoy casi en perfectas condiciones, Jefe.}
{1300}{vic37}{Estoy casi curado, Jefe, pero he estado mejor otras veces.}
{1400}{vic38}{Lo intenté, Jefe, pero no me encuentro muy bien. Aunque haré lo que pueda.}
{1500}{vic39}{Lo qué tú digas, Jefe.}
{1501}{vic40}{¿Aquí? ¿Justo aquí? Vale, tú eres el Jefe.}
{1502}{vic41}{De acuerdo. Me quedaré aquí hasta que vuelvas, Jefe. Porque vas a volver, ¿verdad?}
{1503}{vic42}{Todo el tiempo que quieras. No me iré a ninguna parte.}
{1504}{vic43}{Por supuesto, Jefe.}
{1600}{vic44}{Si tú lo dices.}
{1601}{vic45}{Buena idea, Jefe.}
{1602}{vic46}{Bien pensado, Jefe.}
{1603}{vic47}{Claro, Jefe. ¿Algo más?}
{1604}{vic48}{Bajada está, Jefe.}
{1605}{vic49}{Sin problemas, Jefe.}
{1606}{vic50}{Hecho, Jefe.}
{1700}{vic51}{Claro, Jefe.}
{1701}{vic52}{Lo más cerca que pueda, Jefe.}
{1702}{vic53}{Tú sabes lo que es mejor, Jefe.}
{1703}{vic54}{Justo tras de ti, Jefe.}
{1704}{vic55}{Como el pegamento, Jefe.}
{1705}{vic56}{Si tú lo dices, Jefe.}
{1706}{vic57}{Oh. Vale, Jefe.}
{1800}{vic58}{Vale, mantendré la distancia, pero no tan lejos, Jefe.}
{1801}{vic59}{Vale, No lo haré, Jefe.}
{1802}{vic60}{Entonces me quedaré sólo un poco por detrás tuyo, Jefe.}
{1803}{vic61}{Claro, Jefe.}
{1900}{vic62}{Cierto Jefe. Me retrasaré un poco.}
{1901}{vic63}{Lo qué tú digas, Jefe.}
{1902}{vic64}{Allá voy, Jefe.}
{1903}{vic65}{Me quedo atrás, Jefe.}
{1904}{vic66}{Detrás tuyo, Jefe.}
{1905}{vic67}{Distanciándonos, Jefe.}
{1906}{vic68}{Vale, Jefe.}
{2000}{vic69}{¿Eh, Jefe? Pareces que llevas a mucha gente. Me quedaré aquí esperándote.}
{2100}{}{Me estás asustando, Jefe. ¿Qué te ha pasado? Das... bueno, miedo. Creo que me quedaré aquí un rato...}
{2200}{vic70}{¡Apuesta a que sí, Jefe!}
{2201}{vic71}{Claro que sí, Jefe.}
{2202}{vic72}{Claro que sí, Jefe.}
{2203}{vic73}{Listo cuanto tu lo estés, Jefe.}
{2204}{vic74}{¡Genial! Vamos.}
{2205}{vic75}{¡Genial!}
{2206}{vic76}{¡Eres el mejor, Jefe!}
{2207}{vic77}{No te arrepentirás. ¡No más errores!}
{2208}{vic78}{Tendré cuidado esta vez, ¡no te preocupes!}
{2209}{vic79}{Sabía que me perdonarías por eso... Así que, eh, Jefe. ¿Cuál es el plan?}
{2210}{vic80}{¡No te decepcionaré, Jefe!}
{2211}{vic81}{¡Eres súper, Jefe!}
{2212}{vic82}{Sabía que no era demasiado viejo para esto. ¡Sólo fue algo de mala suerte! ¿Verdad, Jefe?}
{2300}{}{De Ed. Es un tratante de brahmines de Ciudad Refugio. ¿Has estado allí? Déjame señalártela en ese mapa tuyo.}
{2305}{vic199}{En Ciudad Refugio. Aquí. Déjame señalártela en ese mapa chulo que tienes.}
{2310}{vic84}{Debería estar por aquí, en alguna parte.}
{2311}{vic85}{Ciudad Refugio. Mira ese mapa chulo que tienes.}
{2403}{}{¿Dónde conseguiste la cantimplora de agua del Refugio 13?}
{2404}{}{No importa.}
{2500}{vic86}{Claro, Jefe.}
{2501}{vic87}{Pregunta lo que quieras, Jefe.}
{2502}{vic88}{Te ayudaré si está en mi mano, Jefe.}
{2503}{vic89}{No me he metido en problemas, ¿verdad, Jefe?}
{2504}{vic90}{¿Hice algo mal, Jefe?}
{2505}{vic91}{Por supuesto.}
{2600}{vic92}{¿Qué hacemos ahora, Jefe?}
{2601}{vic93}{¿Cuál es el plan, Jefe?}
{2602}{vic94}{Lo hago lo mejor que puedo, Jefe.}
{2603}{vic95}{¿Qué puedo hacer por ti, Jefe?}
{2604}{vic96}{¿Cambio de planes, Jefe?}
{2605}{vic97}{¿Otra estrategia, Jefe?}
{2700}{}{Jefe, me han dado bien. Tienes que llevarme a un doctor. No sé si podré volver a seguirte.}
{2701}{}{Necesito un médico, Jefe. Estoy realmente jodido. No sé si podré volver a luchar contigo.}
{2702}{vic100}{Jefe, estoy realmente jodido. Tienes que hacer que Lenny me eche un vistazo.}
{2800}{vic101}{Eh, Jefe. ¿Quieres que me una a ti?}
{2801}{vic102}{Eh, Jefe. No me importa esperarte. Soy un hombre muy paciente.}
{2802}{vic103}{Nos juntamos otra vez, ¿Jefe? Intentaré hacerlo mejor.}
{2803}{vic104}{Tenía miedo de que no fueras a volver. Me alegro de volver a verte, Jefe.}
{2804}{vic105}{¿Buscas compañía de nuevo?}
{2805}{vic106}{Listo para irnos, Jefe.}
{2806}{vic107}{Sabía que no me abandonarías.}
{2807}{vic108}{¿Necesitas ayuda?}
{2808}{vic109}{Necesitas que repare algo, ¿no? ¡Soy tu hombre, Jefe!}
{2809}{vic110}{No te preocupes, Jefe. Sulik y nos llevamos bien, honestamente.}
{2810}{vic200}{Vamos.}
{2811}{vic201}{Quédate aquí. Volveré.}
{2812}{vic202}{Yo ir.}
{3100}{vic111}{¿Qué? Oh… vale, Jefe. Si tú lo dices.}
{3101}{vic112}{¿Puedo ponerme otra cosa, Jefe? Estoy un poco preocupado.}
{3102}{vic113}{Bien… pero no vas a dejarme aquí... ¿Verdad, Jefe?}
{3103}{vic114}{Pero… es decir... por supuesto, Jefe. Ya me la quito.}
{3200}{vic115}{Bueno, Jefe… Soy bastante bueno con las armas pequeñas. Puedo manejar casi cualquier rifle, escopetas y la mayoría de pistolas pequeñas y medianas. También 'puedo' usar cuchillos y se me da bien lanzar cosas, pero... mi puntería no es la mejor del mundo. De hecho, es bastante horrible. Lo siento, Jefe. Intentaré mejorar.}
{3201}{vic116}{Lo que ya te dije, Jefe. Prefiero las armas pequeñas. Puedo manejar casi cualquier rifle, escopetas y la mayoría de pistolas pequeñas y medianas. Si no nos queda otro remedio puedo intentar usar un cuchillo o incluso armas para lanzar.}
{3300}{vic203}{'Puedo' usar cuchillos y se me da bien lanzar cosas, pero... mi puntería no es la mejor del mundo. De hecho, es bastante horrible. Lo siento, Jefe. Intentaré mejorar.}
{3301}{vic204}{Lo que ya te dije, Jefe. Cuchillos y se me da bien lanzar cosas... pero suelo fallar un montón.}
{3400}{vic122}{¡Hasta aquí hemos llegado!}
{3401}{vic123}{¡Te voy a arrancar la maldita cabeza! ¡Nadie le hace daño a mi familia!}
{4000}{vic124}{¿Por aquí?}
{4001}{vic125}{¿Así mejor, Jefe?}
{4002}{vic126}{¿Qué tal así?}
{4003}{vic127}{Sí, Jefe.}
{4004}{vic128}{¿Qué?}
{4005}{vic129}{¿A dónde vamos?}
{4006}{vic130}{¿Nos vamos, Jefe?}
{4007}{vic131}{Ya me muevo.}
{4008}{vic132}{Lo siento, Jefe.}
{4009}{vic133}{¿Mejor así?}
{4010}{vic134}{Uf.}
{4011}{vic135}{¿Así, Jefe?}
{4012}{vic136}{Me pondré allí.}
{4013}{vic137}{Me moveré allí.}
{4100}{vic138}{¡Jefe! No me encuentro bien.}
{4101}{vic139}{Necesito un doctor.}
{4102}{vic140}{Oh, chico. Esto si que duele.}
{4103}{vic141}{¡Ow!}
{4104}{vic142}{Ouch.}
{4105}{vic143}{Maldición.}
{4106}{vic144}{¿Un médico?}
{4107}{vic145}{Apenas me tengo en pie.}
{4200}{vic146}{Nunca me gustó este sitio.}
{4201}{vic147}{¿Por qué está este sitio tan limpio?}
{4202}{vic148}{¿Hueles algo, Jefe?}
{4203}{vic149}{Sabes, Jefe. No creo que vuelva aquí cuando hayamos acabado. Ya no puedo llamarlo hogar.}
{4204}{vic150}{Esto está bastante más sucio de lo que recordaba.}
{4205}{vic151}{No nos quedaremos mucho por aquí, ¿verdad, Jefe?}
{4206}{vic152}{Este sitio nunca cambiará.}
{4207}{vic153}{Jefe, no voy a echar de menos este sitio.}
{4208}{vic154}{Gracias de nuevo por sacarme de este lugar, Jefe.}
{4209}{vic155}{De verdad que te debo una, Jefe.}
{4210}{vic156}{Vaya, este sitio si que ha cambiado.}
{4211}{vic157}{No he estado aquí desde hace años.}
{4212}{vic158}{No me retiraré a vivir aquí.}
{4213}{vic159}{Podría abrir un taller de reparaciones por aquí.}
{4300}{vic160}{Ah, da gusto verlo. Este era... mi hogar, pero supongo que ya lo sabías. ¿Verdad, Jefe?}
{4400}{vic161}{Sulik, no me mires así.}
{4401}{vic162}{Jefe, Sulik está volviendo a mirarme.}
{4402}{vic163}{Perrito bueno.}
{4500}{vic164}{La de da…}
{4501}{vic165}{Ho hum.}
{4502}{vic166}{Esperando al Jefe…}
{4503}{vic167}{Estoy esperando al Jefe.}
{4504}{vic168}{Esperando.}
{4505}{vic169}{Estoy seguro de que el Jefe no me dejaría tirado aquí…}
{4506}{vic170}{Knock Knock… quién es... espera. ¿Cómo seguía?...}
{4507}{vic171}{Sigo esperando.}
{4508}{vic172}{¿Qué es ese olor?}
{4509}{vic173}{¿Alguien quiere que le repare algo?}
{4510}{vic174}{Aquí estoy... esperando al Jefe.}
{4511}{vic175}{Un hombre mayor como yo, desperdiciando su talento, aquí parado.}
{4512}{vic176}{Ojala tuviera algo de chicle... han pasado décadas.}
{4513}{vic177}{Necesito salir del negocio de las reliquias... no trae más que problemas.}
{4514}{vic178}{Por qué esperar cansa tanto…}
{4600}{vic179}{Oh, gracias, Jefe.}
{4601}{vic180}{Gracias.}
{4602}{vic181}{¿Estás seguro de que sabes lo que haces?}
{4603}{vic182}{¿Y no podríamos descansar en vez de eso?}
{4604}{vic183}{¿Deberíamos acampar?}
{4605}{vic184}{¿Tan mal estoy?}
{4700}{vic185}{No muchas, Jefe.}
{4701}{vic186}{Si insistes, Jefe.}
{4702}{vic187}{Jefe, no me va a explotar la cabeza, ¿verdad?}
{4703}{vic188}{Jefe, creo que empieza a gustarme esto.}
{4704}{vic189}{Me siento un poco raro, Jefe.}
{4705}{vic190}{Seguro que tienes bastantes de estas para darme.}
{4706}{vic191}{Claro, Jefe. Me tomaré algunas.}
{4707}{vic192}{Gracias, Jefe.}
{4708}{vic193}{No está mal.}
{5000}{vic194}{Ahora mismo estoy un poco hambriento. Volveremos a hablar en el local de Mamá.}
{5500}{vic195}{Siento que me rompí una extremidad, Jefe. Será mejor que eche un vistazo.}
{5501}{vic196}{Siento que estoy ardiendo, Jefe. Será mejor que eche un vistazo.}
{5502}{vic197}{Siento que he sido envenenado, Jefe. Será mejor que eche un vistazo.}
