{100}{}{Ves a un hombre que lleva una armadura de cuero.}
{101}{}{Ves a Kaga.}
{102}{}{Lleva una armadura de cuero y tiene el desagradable hábito de hablar de sí mismo en tercera persona.}
{103}{kaga13}{Está será la última vez que Kaga te encuentre.}
{104}{kaga14}{Después de que Kaga te mate, él reducirá Arroyo a cenizas.}
{105}{kaga15}{¡Siente la ira de Kaga!}
{106}{kaga16}{¡Este es el gran Kaga!}
{107}{kaga17}{Kaga es temido por todos.}
{108}{kaga18}{Kaga usará tu cabeza como trofeo.}
{109}{kaga19}{Ríndete y tu muerte será rápida.}
{110}{kaga20}{¡Kaga volverá!}
{111}{kaga21}{¡Tu no puedes matar al gran Kaga!}
{112}{kaga22}{Tienes suerte de que Kaga tenga asuntos que tratar.}
{113}{kaga23}{Kaga volverá a verte.}
{120}{}{Es este Kaga tipo de nuevo.}
{150}{kaga1}{[Un alto y fornido guerrero está frente a ti, sus ojos brillan con odio mientras te mira.] Entonces, ellos echan a Kaga, ¿y te consideran el Elegido? ¡JA! ¡¿Crees que ser el nieto del Morador del Refugio te hace especial?! ¡¿Crees que eres mejor que yo, Kaga el Grande?!}
{151}{}{Bueno, yo SOY el Elegido, ¿no?}
{152}{}{Hey ahora, espera un segundo. Nunca dije que era mejor que tú.}
{160}{kaga2}{¡Ese título no significará nada cuando Kaga te arranque la cabeza de tus hombros!}
{161}{kaga3}{No hay palabras que puedan salvar tu piel. Con tu muerte, el honor de Kaga será restaurado. ¡Kaga ahora tomará su venganza!}
{200}{}{¿Ooglie?}
{201}{kaga4}{¿¡Qué!? ¿Te eligieron a *ti* para ser el Elegido? Oh mi, se han vuelto desesperados.}
{202}{}{No gusta. Parece mal.}
{203}{kaga5}{Kaga ni siquiera se molestará en hablar contigo más. ¡Prepárate para morir a manos de Kaga!}
