{100}{}{Ves a un hombre que lleva una armadura de metal.}
{101}{}{Ves a Kaga.}
{102}{}{Sí, es Kaga el no-tan-Grande. Lleva una armadura de metal y quiere matarte.}
{103}{kaga24}{¡Tú otra vez!}
{104}{kaga25}{Kaga se está cansando de nuestros continuos encuentros.}
{105}{kaga26}{Elegido... ¡hmph!}
{106}{kaga27}{Acabemos con esto.}
{107}{kaga28}{¡Te arrepentirás de haber oído el nombre de Kaga!}
{108}{kaga29}{Las habilidades de Kaga han mejorado desde la última vez que nos vimos.}
{109}{kaga30}{Esto se está convirtiendo en una mala costumbre.}
{110}{kaga31}{Kaga necesita entrenar un poco más.}
{111}{kaga32}{Kaga volverá.}
{120}{}{Así que nos encontramos de nuevo, Kaga.}
{150}{kaga1}{[Un alto y fornido guerrero está frente a ti, sus ojos brillan con odio mientras te mira.] Entonces, ellos echan a Kaga, ¿y te consideran el Elegido? ¡JA! ¡¿Crees que ser el nieto del Morador del Refugio te hace especial?! ¡¿Crees que eres mejor que yo, Kaga el Grande?!}
{151}{}{Bueno, yo SOY el Elegido, ¿no?}
{152}{}{Hey ahora, espera un segundo. Nunca dije que era mejor que tú.}
{160}{kaga2}{¡Ese título no significará nada cuando Kaga te arranque la cabeza de tus hombros!}
{161}{kaga3}{No hay palabras que puedan salvar tu piel. Con tu muerte, el honor de Kaga será restaurado. ¡Kaga ahora tomará su venganza!}
{200}{}{¿Ooglie?}
{201}{kaga4}{¿¡Qué!? ¿Te eligieron a *ti* para ser el Elegido? Oh mi, se han vuelto desesperados.}
{202}{}{No gusta. Parece mal.}
{203}{kaga5}{Kaga ni siquiera se molestará en hablar contigo más. ¡Prepárate para morir a manos de Kaga!}
