{100}{}{Ves a un hombre con armadura de combate.}
{101}{}{Ves a Kaga con una armadura de combate.}
{102}{}{Lleva una armadura de combate y parece portar armas bastante decentes.}
{103}{kaga33}{Esta vez Kaga está preparado para ti.}
{104}{kaga34}{¡El Elegido nunca regresará a Arroyo!}
{105}{kaga35}{¡Kaga te aplastará!}
{106}{kaga36}{¡Kaga no le teme a nadie!}
{107}{kaga37}{Quédate quieto, para que Kaga pueda apuntar bien.}
{108}{kaga38}{¡Volverás a ver a Kaga!}
{109}{kaga39}{Esta no es la última vez que oyes hablar de Kaga.}
{110}{kaga40}{Kaga necesita entrenarse mejor.}
{120}{}{¡Vete, Kaga!}
{150}{kaga1}{[Un alto y fornido guerrero está frente a ti, sus ojos brillan con odio mientras te mira.] Entonces, ellos echan a Kaga, ¿y te consideran el Elegido? ¡JA! ¡¿Crees que ser el nieto del Morador del Refugio te hace especial?! ¡¿Crees que eres mejor que yo, Kaga el Grande?!}
{151}{}{Bueno, yo SOY el Elegido, ¿no?}
{152}{}{Hey ahora, espera un segundo. Nunca dije que era mejor que tú.}
{160}{kaga2}{¡Ese título no significará nada cuando Kaga te arranque la cabeza de tus hombros!}
{161}{kaga3}{No hay palabras que puedan salvar tu piel. Con tu muerte, el honor de Kaga será restaurado. ¡Kaga ahora tomará su venganza!}
{200}{}{¿Ooglie?}
{201}{kaga4}{¿¡Qué!? ¿Te eligieron a *ti* para ser el Elegido? Oh mi, se han vuelto desesperados.}
{202}{}{No gusta. Parece mal.}
{203}{kaga5}{Kaga ni siquiera se molestará en hablar contigo más. ¡Prepárate para morir a manos de Kaga!}
