{100}{}{Ves un espécimen de los tanques de almacenamiento.}
{101}{}{Ves a Kitsune.}
{102}{}{Sus ojos son de colores diferentes. Uno de ellos de color marrón como malmbrick, el otro de color verde brillante.}
{103}{}{Ves a una mujer delgada y de pelo oscuro que parece difícil de predecir.}
{104}{}{Ella tiene un rostro suave y fascinantes ojos.}
{150}{}{No es agradable mirar fijamente.}
{200}{}{Antes de que usted se encuentra en un tanque abierto con el hielo de agua fría poco a poco se drena a través de un largo, serpentina de la tubería. En el interior, una
 mujer, desnuda de pies a cabeza, se encuentra jadeando y temblando. Mirando a su alrededor rápidamente, usted arrebatar un paquete de ropa suelta
 en las inmediaciones de un armario y desplegarlas sobre ella por el calor.}
{201}{}{Whoa. Que tenía que ser algún viaje. Te encuentras bien?}
{202}{kit2}{Y sí, el p-p-preservator r-restaurado mi b-cuerpo t-t-temperatura.}
{203}{}{No todos, se ve como. }
{204}{}{[Le das algo de tiempo para sus dientes, para dejar de parloteo. Ella se recupera mucho más rápido de lo que usted esperaba que ella
 y mira que con repentina gravedad.] Es... es sobre?}
{205}{}{¿Qué ha terminado? }
{206}{}{¿Te refieres a la guerra?}
{207}{kit4}{La Guerra. Todas esas armas nucleares.}
{208}{kit5}{La guerra, si.}
{209}{}{Que la guerra terminó hace mucho tiempo. Terminado tan pronto como empezó.}
{210}{kit6}{[Ella pinceles húmedos mechones de cabello de sus ojos. Observa uno de los ojos es de color marrón, mientras que el otro es de color verde esmeralda.] ¿Quién ganó?}
{211}{}{Nadie.}
{212}{kit7}{[Ella le mira fijamente. Ella es muy fácil en los ojos, especialmente para alguien que acaba de ser descongelado a partir de un bloque de hielo.]}
{213}{}{Cuando el 90% del mundo es quemado a un crujiente de color marrón, yo diría que es difícil para declarar un ganador claro.
 Quiero decir, no quedaba mucho la pena ganar.}
{214}{kit8}{¿Qué... qué fecha es? ¿De qué año? Es todavía 2077?}
{215}{}{El infierno, no. [Te muestre la fecha en tu Pip-Boy del calendario.]}
{216}{kit9}{[Ella se queda mirando el parpadeo de la pantalla, congelada en el tiempo como ella nunca dejó el tanque.]}
{217}{}{¿Estás Bien?}
{218}{kit10}{Mi Dios. No me lo creo. Yo estaba en esa cosa por más de un siglo?!}
{219}{}{Parece. Hey, escucha, no me mires así. Yo no tenía nada que ver con poner allí. El infierno,
 mi abuelo no estaba aún con vida en aquel entonces. Me tropecé con la ubicación de este lugar y decidí echarle un vistazo.}
{220}{kit11}{Bien, me va a ayudar, o te gustaría mejor si yo seguía sentado desnudo en tus pies?}
{221}{}{Yo estaba a punto de. [Le ayuda a sus pies.]}
{222}{kit12}{¿Por qué me despertaste?}
{223}{}{No hay ninguna razón en particular.}
{224}{}{Tengo esta terrible costumbre de tocar todo lo que me encuentro. Una cosa llevó a la otra.}
{225}{kit13}{¿Dices que ni siquiera trabajas en este lugar?}
{226}{}{Eso es lo que dije}
{227}{}{Entonces, si usted no hubiera venido a lo largo, yo he sido atrapado en la que la cosa aún más. Tal vez para siempre.
 (Saca una de las camisetas que envolvió su en encima de su cabeza.) ¿Qué se siente ahora, el mundo de fuera?
 Usted dijo que el 90% de ella fue destruida?}
{228}{}{Mi mundo es un páramo donde cada día es una lucha por la supervivencia. La mayoría de las personas han tomado refugio en las ruinas de las antiguas.
 Otros, como mi tribu, intento de forjar un simple existencia en el duro desierto. A decir verdad, se podría siglos antes de que ni siquiera se aproxime a la recuperación.}
{229}{kit15}{No puede ser tan malo como suena. [No suena como si estuviera convencido de una sola palabra, ella simplemente dijo.]}
{230}{}{No es nada como estados unidos en el año 2077, eso es seguro.}
{231}{kit16}{[Ella saca un par de pantalones.] Así que, ¿y ahora qué?}
{232}{}{Nunca nos hizo correctamente introducir a nosotros mismos. Mi nombre }
{233}{}{¿Cuál es el tuyo?}
{234}{kit17}{Puedes llamarme Kitsune.}
{235}{}{Kitsune, ¿qué hacías cryoed en ese tanque?}
{236}{kit18}{Yo no lo sé. Ellos sabían que la Guerra estaba a punto de suceder, así que me pusieron en un preservator como los demás.}
{237}{}{¿Tienes idea de lo que es este lugar?}
{238}{}{A partir de lo que saben, es una rama de los Estados unidos Agencia de Protección Ambiental. Yo estaba en Arizona, cuando el
 Una guerra que pasó. Que fue tomada de aquí inmediatamente.}
{239}{}{Usted debe haber sido bastante importante para ellos desea conservar usted. Fue Elegido Uno, como yo?}
{240}{kit20}{Uh, no exactamente. Yo era un ama de casa, casada con un concejal. Antes de que me escribió para varias publicaciones de noticias. No era lo que se llama una terriblemente excitante vida.}
{241}{}{¿Qué le pasó a él, a tu marido?}
{242}{kit21}{No sé. Probablemente uno de los miles de millones de víctimas. Dudo que alguno de mi familia lo hizo a través de la guerra. Mi Dios, incluso si lo hicieron, que ha pasado tanto tiempo... todos los que he conocido está muerto. [Ella se muerde el labio y sus ojos comienzan a brillo de las lágrimas, pero ella rápidamente se borra y suspiros, trayendo a sí misma bajo control.]}
{245}{}{Bueno, ya que estamos me da una opción... (sonriendo)}
{246}{kit22}{[Ella te mira sin palabras.]}
{247}{}{Oh, me refiero, por supuesto, voy a ayudarle a subir. [Le ayuda a sus pies.]}
{250}{}{¿Y ahora qué vas a hacer?}
{251}{}{No sé. ¿Qué hacer cuando usted ha estado hibernando durante más de un siglo? Hasta los osos no dormir por mucho tiempo.
 El mundo no es el mundo que yo conocía. Yo no sé si podría soportar ver lo que se ha convertido en.}
{252}{}{Sé que es un páramo, pero todavía tienes toda una vida para vivir. Estás perdiendo tiempo aquí abajo.
 Ven conmigo y tal vez podamos hacer algo.}
{253}{}{No se ve que tienes mucho de una elección. Usted puede sentarse aquí y a la podredumbre, o podrías venir conmigo. Es hasta usted.}
{260}{}{Usted sabe, usted está en lo correcto. Yo podría volver a ser congelado y el sueño de otros cien años, pero que
 sería la salida barata. Tengo que ver por mí mismo lo que es el mundo del ser, y desempeñar un papel en poner de nuevo juntos.}
{261}{}{Venga a continuación. Vamos a ir a tomar un brahmán filete primero.}
{262}{kit97}{No me hagas arrepentirme de esto.}
{270}{kit25}{Olvidarse de él. Ha sido de esta manera por más de un centenar de años. ¿Qué te hace pensar que vamos a solucionar ahora?}
{271}{}{Volveré. Tal vez cambies de opinión.}
{272}{kit26}{Tal vez. Pero no se confíe en lo que está sucediendo. Solo debo volver a dormir para el otro siglo o así.}
{280}{}{Lo que si estas máquinas y dejó de funcionar, aunque? Usted estaría muerto y usted nunca sabe
 si el mundo que se voló a sí mismo nunca volver.}
{281}{kit27}{A continuación, voy a ver lo que pasa desde donde estoy.}
{282}{}{¿Cómo sabe usted por seguro que vas a ser tomada en algún lugar en especial después de que el sueño el gran sueño? Yo vengo de una
 tribu que cree en la vida después de la muerte y profecías, pero desde un punto de vista pragmático todos somos sólo un montón de orgánicos
 las máquinas que pensar y hablar y sentir, porque de la carne y de los componentes químicos. Lo que si no hay nada después de la muerte -- nosotros
 se cierra como los equipos, y esto es todo lo que tienes?}
{283}{kit28}{Prefiero tomar mis posibilidades en suspensión criogénica de vagar ese erial.}
{284}{}{¿Venga, sí? Ya no pareces tan seguro.}
{285}{kit29}{[Kitsune medita sus palabras por un buen largo tiempo. Por último, dijo que las líneas de sus ojos con los suyos.] Yo no puedo pretender que usted no tiene un punto. Tal vez... tal vez voy a tomar mis posibilidades con usted.}
{286}{}{Vamos a salir de aquí, entonces. Es hora de que la izquierda esta volcado detrás.}
{287}{kit30}{En realidad, creo que voy a lanzarme por mi cuenta. Siempre he sido el tipo independiente, por lo que no debería ser la piel de mi espalda. Mucho ha cambiado desde que he estado fuera y me gustaría verlo por mí mismo. Gracias por unthawing mí. Usted toma el cuidado de sí mismo.}
{288}{}{[HECHO]}
{300}{kit31}{¿Sí?}
{301}{kit32}{Estoy escuchando.}
{302}{kit33}{¿Querías algo?}
{303}{kit34}{¿Qué pasa? Parece que tienes algo que decir.}
{304}{kit35}{¿Qué te ocurre?}
{305}{kit36}{¿Hay algo que necesites de mí?}
{310}{}{Kitsune, estoy bastante seguro de que no se han congelado en un crio tanque por ninguna buena razón.
 Estoy interesado en saber qué era exactamente lo que hizo antes de poner en el hielo.}
{311}{kit37}{¿Por qué te importa? Es en el pasado.}
{312}{}{Estamos en el camino juntos. Quiero saber más sobre ti.}
{313}{kit38}{[Suspira.] Bueno, supongo que no hay necesidad de secreto más. Es muy difícil romper un hábito permanente. Usted ve, yo estaba bastante nacido un espía.}
{314}{kit39}{Mi padre era Chino, pero él y su familia no eran amigos del gobierno Chino. Nació en Pekín, pero tiene el aspecto más importante de su educación aquí, en los Estados unidos. Cuando regresó a su casa y consiguió un trabajo como un servidor público, que ya había sido reclutado por los Estadounidenses como un agente de inteligencia.}
{315}{}{Yo no estoy demasiado familiarizado con la política de su tiempo, pero creo que voy a seguir lo que usted está diciendo: Tu padre era Chino, pero secretamente era un espía para los Americanos. Así lo hicieron los Chinos jamás sospechar de él?}
{316}{kit40}{Mi padre trabajaba en el Ministerio de Agricultura de treinta y ocho años.}
{317}{}{Uh, bien, supongo que eso es un "no". Así que cuando entraste en la foto?}
{318}{kit41}{Bien, un día, un ayudante de los oficiales de mi padre trabajaba para lo cogí de la realización de copias de documentos secretos.}
{319}{}{Eso no puede ser nada bueno...}
{320}{kit42}{En realidad, no es tan malo. Usted ve, ella pensaba que a lo largo de las mismas líneas como mi padre, y dentro de un par de meses, se casaron.}
{321}{}{Algunos chicos tienen toda la suerte, ¿eh?}
{322}{}{Que me tenía un año más tarde. Yo me crié en China bajo la fachada de un patriota. En la escuela me gustaría escribir acerca de la manera en que China era el más fuerte cuando unificada, y cómo teníamos que seguir luchando hacia la igualdad social. 
 Cuando yo era más viejo que yo escribí para los nacionalistas prensa y participó en los debates de apoyo al partido gobernante.}
{323}{}{Wow, la mayoría de los que se fue por encima de mi cabeza. Pero si he entendido bien, estás diciendo que tú y tus padres engañado a los Chinos a pensar que eran leales.}
{324}{}{Los padres hacían grandes esfuerzos para asegurarse de que su familia verdaderas lealtades se quedó en secreto.}
{325}{kit44}{Toda guerra se basa en el engaño. Mis padres amaban a su país. Simplemente odio a la gente que corría y pensé que estaría mejor como una democracia. La manera en que la vi, no estaban traicionando a China - que estaban trabajando en contra de un gobierno que no creen que era bueno para ella.}
{326}{}{Continúa.}
{327}{kit45}{Me casé con un funcionario que trabajaba para el Ministerio Chino de Defensa Nacional. Yo lo escogí a él porque él era el más dispuesto a hablar de su trabajo cuando estábamos juntos. Así que desempeñó el papel de las obediente esposa, mientras que el secreto de reporte de información relevante de vuelta a mi American superiores. Pero luego las cosas se pusieron complicadas.}
{328}{}{¿Cómo es eso?}
{329}{kit46}{Mi padre fue contactado por el Dr. Raynard Muldrake, un viejo colega que había trabajado durante su tiempo en los Estados unidos. El Dr. Muldrake solicitado una reunión privada, pero mi padre estaba en mal estado de salud en el momento y no estaba en condiciones para el viaje a América. El Dr. Muldrake acordaron reunirse a mí en su lugar.}
{330}{}{¿Y qué pasó?}
{331}{kit47}{Resultó Muldrake fue parte de un proyecto de alto secreto en un Oeste Tek centro de investigación en el Sur de California. El proyecto había iniciado inocentemente, como un intento de encontrar una manera de hacer que la gente inmune a la Nueva Plaga, pero se convirtió en algo más siniestro. Algo que se llama Forzado Evolutivo de Virus, o FEV.}
{332}{}{Continúa.}
{333}{kit48}{Tenía el potencial para mejorar enormemente de una persona y la fuerza del intelecto, pero la FEV era peligrosamente inestable. A pesar de esto, los militares esperaba utilizar para crear un ejército de súper soldados que podría aplastar a los Chinos.}
{334}{kit49}{El Dr. Muldrake estaba en contra de que el cambio en la dirección del proyecto, pero mantuvo su boca cerrada por temor por su vida. Pero cuando se enteró de que el ejército era una prueba de que el virus de incautos, pequeñas ciudades Americanas, él sabía que tenía que tomar acción. El mundo necesitaba saber la verdad.}
{335}{}{Así que eso es cuando ha contactado a tu padre...}
{336}{kit50}{A la derecha. Cuando yo lo conocí, él me dio un holodisk que contiene clasificado de la documentación de la FEV proyecto. Que me puso en una posición difícil: me podrían dar la información contenida en el holodisk y traicionar al país que me había jurado a mi lealtad, o podría destruir el disco y enterrar la fea verdad de la gente.}
{337}{}{Mierda. No me digas...}
{338}{kit51}{Me enviaron una copia de la holodisk a casi todas las principales agencias de noticias en el mundo. Es casi destruye cualquier simpatía con el gobierno Estadounidense todavía tenía. Yo podría haber revelado la verdad para el mundo, pero me temo que también en el movimiento de su destrucción... las Cosas se intensificó rápidamente, y ocho meses más tarde, las bombas fueron lanzadas.}
{339}{}{¿Cómo terminaste en ese tanque donde te encontré?}
{340}{kit52}{El gobierno Americano fue a la caza de la persona responsable de la filtración de la información. Finalmente me ha alcanzado justo antes de la final. Ya estaban preparando para congelar mí cuando las sirenas primer sonaba. Probablemente para preservar mí en caso de que yo tenía más secretos que yo no había dicho.}
{341}{}{¿Lo hiciste?}
{342}{kit53}{No importa ahora. Todos muertos...}
{345}{}{¿Tienes idea de lo que trajiste?}
{346}{kit54}{Lo que *puede* han traído. El mundo hubiera quemado a sí mismo, tarde o temprano, de todos modos. Era sólo cuestión de tiempo.}
{347}{}{Tal vez usted debería abstenerse de compartir este pequeño pedacito de información con nadie más.}
{348}{kit55}{Entiendo tu deriva.}
{350}{}{Yo sé lo que usted debe estar pensando, pero no puede culparse a sí mismo por algo como eso.}
{351}{kit56}{Siempre es más fácil no aceptar la responsabilidad.}
{352}{}{Usted no podría haber conocido. Además, hubo otros conflictos entre los "poderes". La hubieran quemado unos a otros
 hasta pronto o más tarde. Era sólo cuestión de tiempo.}
{353}{kit57}{Los humanos son las peores cosas.}
{354}{}{No me considero tan malo.}
{355}{}{La naturaleza ha estado tratando de limpiar con nosotros durante milenios. Todas estas nuevas enfermedades, los desastres naturales. Que era una especie
 de evolución en el error. Tal vez en que se produjo demasiado pronto o no supongo que para venir a todos. Hemos hecho más daño
 para este planeta que cualquier cosa viva o muerta.}
{356}{}{Pero podemos expiar por él. Eso es lo que es especial acerca de nosotros.}
{357}{kit59}{Tienes una muy buena manera de decirlo. Gracias por escucharme a cabo. Casi me siento como si me puede pasar.}
{360}{}{Es decir, desde que eras un espía, estoy seguro de que eres bastante experto en sigilo y todo eso. Cualquier cosa que usted me puede enseñar?}
{361}{}{Sí, he tenido un poco de práctica con sigilo, cerrajería, y el robo. Aquí, te voy a mostrar un par de cosas
 que no te enseñan en los libros.}
{362}{kit61}{Tienes que hacerlo ahora. Recuerde que la práctica hace al maestro.}
{363}{}{Hey, gracias. Creo que ya es hora de que salgamos.}
{370}{}{Acerca de tu ojos...}
{371}{kit62}{¿Qué pasa con ellos?}
{372}{}{Tienen distintos colores.}
{373}{}{¿Cuál es el término para ella... heterocromía? Es que lo que usted tiene?}
{374}{}{La mía no es una condición natural. El de la izquierda no me pertenecen a mí. He perdido a la antigua en un accidente.
 Y nunca he aprendido a apreciar que hasta ahora.}
{375}{}{¿Qué quieres decir?}
{376}{}{Desde el trasplante siempre sentí que estaba viendo el pasado en un ojo y en el otro.
 Más que nunca ahora. Y que me ayuda a continuar.}
{377}{}{Todos tenemos nuestras maneras de sobrellevarlo.}
{410}{kit65}{¿Qué quieres saber?}
{411}{kit66}{Tengo un cinturón negro en sanshou. Puedo apuñalar a un hombre a la muerte si la situación lo requiere. Pistolas, rifles y como soy decente con.}
{420}{}{Tenemos que hablar sobre la distancia entre nosotros.}
{421}{kit67}{¿Qué tiene de malo?}
{422}{}{Quedarse cerca de mí.}
{423}{kit68}{De acuerdo. Te cubro la espalda.}
{424}{}{No te alejes demasiado.}
{425}{kit69}{Necesitas algo espacio, entiendo.}
{426}{}{Separémonos.}
{427}{kit70}{Bien. Estamos más difícil objetivos de distancia.}
{430}{kit71}{No tome demasiado tempo o me voy sin ti.}
{431}{kit72}{Voy a jugar al solitario o algo hasta que vuelvas.}
{432}{kit73}{Estoy seguro de que encontraré algo que hacer mientras estás fuera.}
{440}{kit74}{Siempre que me necesitas.}
{441}{kit75}{Me alegro de que esté de vuelta. Llevé a cabo las audiciones, pero no pude encontrar un buen reemplazo para usted.}
{442}{kit76}{¿Extrañas a mi compañía?}
{443}{kit77}{Sentirse culpable acerca de tomar sin mí?}
{444}{kit78}{Estoy empezando a pensar que no estabas planeado regresar.}
{445}{kit79}{Sobre el tiempo. En la Antigua China, la tardanza se le ahorcado, arrastrado y descuartizado.}
{446}{kit80}{Oye. Estaba pensando en ti ahora.}
{450}{kit81}{Estás seguro de que tomó su tiempo haciendo lo que estaba haciendo sin mí.}
{451}{kit82}{Es bueno estar en el camino de nuevo.}
{452}{kit83}{¿Por qué?}
{453}{kit84}{¿Hacia dónde nos dirigimos entonces?}
{454}{kit85}{Adelante, capitán.}
{460}{kit86}{Tienes suficiente gente ya. Usted no necesita un séquito.}
{461}{kit87}{Tal vez cuando hayas liberado algo de espacio. Yo no funcionar bien con las multitudes.}
{462}{kit88}{¿Estás listo para llevarme contigo?}
{463}{}{Vamos.}
{464}{}{No, aún no.}
{470}{kit89}{Jesús, te pareces a la parca. Usted debe obtener desprotegido.}
{480}{kit90}{No hay problema. Estoy más ligero en mis pies sin eso.}
{490}{kit91}{Nunca ha sido mejor. Vamos.}
{491}{kit92}{He estado peor. Sólo un par de rasguños.}
{492}{kit93}{Yo no soy tan mala. Sólo algunas heridas de la carne.}
{493}{kit94}{No estoy haciendo muy bien. Más sangre de la que me han saliendo de mí.}
{494}{kit98}{Necesito un médico o no podré ayudarte con una maldita cosa.}
{495}{kit99}{No puede seguir por más tiempo... me dejan detrás o llevarme a un médico. Rápido.}
{500}{kit95}{Si usted insiste. Todavía puedo tomar la cabeza de un hombre con mis manos.}
{1000}{kit100}{No puedo creer que pasé más de cien años en este lugar.}
{1010}{kit101}{No es mi tipo de lugar para nacer en el, sin ofender a nadie.}
{1020}{kit102}{Esto se parece a algunas Siglo 15 del emperador tumba de inhumación.}
{1030}{kit103}{Este lugar huele a estiércol de ganado en todo.}
{1040}{kit104}{Creo que no sería sabio a la cabeza en este lugar sin el calzado adecuado.}
{1050}{kit105}{He visto cosas peores lugares, créanme. No es que yo soy demasiado aficionado a este.}
{1060}{kit106}{Rústico. Me gusta.}
{1070}{kit107}{Este lugar se ve directamente de una película de tabaco.}
{1080}{kit108}{Puedo degustar la radiación en el aire.}
{1090}{kit109}{¿Qué se supone que es esto, un campo de trabajo?}
{1100}{kit110}{Dentro de lo tienen mucho mejor que los que están fuera. El mundo no ha cambiado tanto.}
{1110}{kit111}{¿Qué clase de pueblo minero le llamas a esto?}
{1120}{kit112}{No es mi tipo de lugar para nacer en el, sin ofender a nadie.}
{1130}{kit113}{Buen lugar para esconderse si la ley está en su cola.}
{1140}{kit114}{Me pregunto si hay más bunkers como este por aquí.}
{1150}{kit115}{La ciudad más pequeña del mundo. Apuesto a que sí.}
{1160}{kit116}{No pueden retener sólo ganado aquí...}
{1170}{kit117}{La muerte por todas partes...}
{1171}{kit118}{Yo no quiero ser enterrado aquí.}
{1180}{kit119}{Acabamos de pasar por delante de la naturaleza y seguir evolucionando, no? }
{1190}{kit120}{No he visto edificios de altura desde el 101 se estabilizó.}
{1200}{kit121}{Seguro que bloquea este lugar apretado.}
{1210}{kit122}{He oído acerca de estos lugares...}
{1220}{kit123}{Se siente muy agradable para caminar en una ciudad que parece ha juntos.}
{1230}{kit124}{He oído acerca de estos lugares...}
{1240}{kit125}{El único lugar santo en estos profano de los desechos.}
{1250}{kit126}{Hace calor aquí.}
{1251}{kit127}{Yo estoy sudando balas.}
{1252}{kit128}{Estoy reseco.}
{1253}{kit129}{Me gustaría mejor si esto fuera una playa.}
{1254}{kit130}{Sulik, usted sabe algo acerca de la lluvia baila?}
{1260}{kit131}{Esto es tan lejos de la civilización como se pone.}
{1270}{kit132}{Dudo que el agua es potable, incluso si filtra toda la sal.}
{1271}{kit133}{Cualquier pescado que encontramos en estas aguas están obligados a ser mutantes de algún tipo.}
{1272}{kit134}{Hace frío aquí fuera.}
{1273}{kit135}{Cientos de dólares a cualquiera que se atreva a ir flaco-inmersión en esas aguas.}
{1280}{kit136}{Yo no puedo ver absolutamente nada aquí.}
{1281}{kit137}{Este lugar huele mal y si la pude ver mejor sería probablemente un aspecto aún peor.}
{1282}{kit138}{Cuidado. Probablemente hay algo feo y maloliente encerrado aquí.}
{1283}{kit139}{Son los murciélagos que oigo yo?}
{1284}{kit140}{¿Qué vamos a hacer, spelunk?}
{1285}{kit141}{Mejor encender una vela que maldecir la oscuridad.}
{1290}{kit142}{La guerra... un montón de cosas buenas que nos hizo.}
{1291}{kit143}{Polvo al polvo...}
{1292}{kit144}{Yo solía vivir en un lugar como este...}
{2001}{kit145}{Mis ojos error que mucho?}
{2002}{kit146}{Yo podría usar un baño en un manantial de agua caliente. Pregunto si hay alguno de los que se quedan más.}
{2003}{kit147}{Me gustaría matar a encontrar a alguien para jugar mahjong con.}
{2004}{kit148}{Todo el mundo come y bebe. Sin embargo, sólo unos pocos aprecian el sabor.}
{2005}{kit149}{Este mundo es el infierno. Todos los trece niveles.}
{2006}{kit150}{Yo creo en Dios y el Diablo. Pero yo mantenerlos a distancia.}
{2007}{kit151}{Estamos viviendo un sueño, o el sueño de otra persona?}
{2008}{kit152}{Me gusta lo que hemos hecho a nosotros mismos.}
{2009}{kit153}{Me pregunto cuánto tiempo va a tomar para recuperarse de la Guerra.}
{2010}{kit154}{Si el cielo nos hizo, la tierra se va a encontrar algunos utilizan para nosotros.}
{2011}{kit155}{Tienes sed? Estoy seguro que soy.}
{2012}{kit156}{*bostezo*}
{2013}{kit157}{El hombre propone y Dios dispone".}
{2020}{kit158}{Hey, Sulik. ¿Qué son los espíritus diciendo?}
{2030}{kit159}{Usted interesado en adelgazar, Vic? Me pregunta cualquier momento para clases de taebo.}
{2040}{kit160}{Su esposa habla demasiado maldito mucho acerca de sí misma.}
{2041}{kit161}{Dígale a su paisano esposa a dejar de venir a mí.}
{2050}{kit162}{Mi pecho y sus ojos no tienen ningún negocio, Myron.}
{2051}{kit163}{¿Y cerrando hasta por dos minutos, Myron? Tendría que matarte?}
{2052}{kit164}{No, Myron. Yo no sueño con usted si usted me construido una máquina del tiempo.}
{2053}{kit165}{Escuchar, Myron. No mantener las manos a sí mismo, voy a hacer un eunuco.}
{2060}{kit166}{¡Oye, Myron! ¿Quieres lucha de brazos?}
{2070}{kit167}{Tenemos suficiente perros siguiendo a nuestro alrededor. No necesitamos otro.}
{2100}{kit168}{Ugh, me siento como el infierno.}
{2101}{kit169}{Creo que he sido envenenado...}
{2110}{kit170}{Algo no se siente bien en mí...}
{2111}{kit171}{Me siento extraño...}
{2112}{kit172}{Mi mano. Esta brillando.}
{2113}{kit173}{Soy un zorro, una serpiente... ¿por Qué mi descamación de la piel?}
{2114}{kit174}{Esta quema por dentro... Lo que me está pasando?}
{2120}{kit175}{Tengo una fractura, creo. Necesidad de obtener miró.}
{2121}{kit176}{Siento que rompí algo...}
{2130}{kit177}{Apenas puedo ver, maldita sea.}
{2131}{kit178}{Odio ser ciego.}
{2330}{}{¿Qué tal si me dices tu nombre? Soy}
{3000}{kit179}{Es mejor.}
{3001}{kit180}{Te lo agradezco. Esos son un regalo del cielo.}
{3002}{kit181}{Ya me siento mejor. Gracias.}
{3003}{kit182}{Gracias. Yo necesitaba eso.}
{3004}{kit183}{¿Tienes suficiente para ti?}
{3010}{kit184}{Materia sólida. Cosa buena que yo pueda mantener mi licor.}
{3011}{kit185}{No sé por qué me estoy bebiendo este. Gustos como limpiador de desagües.}
{3012}{kit186}{Nunca le gustó la bebida todo lo que mucho. Pero adormece el dolor.}
{3013}{kit187}{¿Tienes algo más para beber?}
{3014}{kit188}{Esperemos que no me despierto en una piscina de mi propio vómito.}
{3015}{kit189}{Ahí van mis planes de mantenerse sobrio hoy.}
{3020}{kit190}{Mierda... esperemos que no tenga que hacer frente a una banda saltó sobre estos.}
{3030}{kit191}{Mejor ir fácil. Este material se mete con su testosterona.}
{3040}{kit192}{Esperemos que esto no me convertirá en un idiota una vez que se gasta.}
{3050}{kit193}{Los hábitos son las arañas en primer lugar, los hilos de la última.}
{3051}{kit194}{La espada es más poderoso que el cielo.}
{3052}{kit195}{Ojo por diente, diente por todos.}
{3053}{kit196}{Una persona necesita una cara como un árbol que necesita de la corteza.}
{3054}{kit197}{El árbol se cae cuando los monos subir.}
{3055}{kit198}{Todos los cuervos del mundo son más inteligentes que el promedio de halcón.}
{3056}{kit199}{Un punto de nueve ahorra diez.}
{3057}{kit200}{Un tigre hijos no son los leones.}
{3058}{kit201}{Aprender. Y en el aprendizaje a ir mal.}
{3059}{kit202}{El viaje viene antes de la caída.}
{3060}{}{Lucha de arena con el fuego, la magia con el polvo.}
{3061}{}{Todos debemos prepararnos para la guerra de la paz.}
{3062}{}{Añadir rayas a una serpiente después de completar el dibujo de la misma.}
{3063}{}{El tigre puede librarse de sus spots por ser de difícil bajar.}
{3064}{}{Uno no puede negarse a comer porque hay una oportunidad de crecimiento hambre todo de nuevo.}
{3065}{}{Una pintura es digno de un centenar de años de dolor.}
{3066}{}{Viciosa como una tigresa puede ser, nunca lo hace ella come su propia cangrejos.}
{3067}{}{Una sirena de los dedos son cortos y dulces.}
{3068}{}{Matar a miles de personas a menguar uno.}
{3069}{}{Mantener a tus enemigos cerca, y a tus amigos por debajo de usted.}
{3070}{}{Para evadir la más segura de la debilidad de uno golpea a los más fuertes de la delantera.}
{3071}{}{Si tu enemigo está bien entrenado, prepararse para el éxtasis.}
{3072}{}{Al enemigo, para él, para prepararse a sí mismo.}
{3073}{}{Él, que no sabe cómo luchar, pero cuando van a abrazar la victoria.}
{3074}{}{La imprudente quedan a la espera de un enemigo que no puede, y por lo tanto va a ganar.}
{3075}{}{La invisibilidad posiblemente radica en la defensa del enemigo en el ataque de la victoria.}
{3076}{}{Conócete a ti mismo. Conoce a tu enemigo. Conocer a sus amigos y familia.}
{3077}{}{Las oportunidades se multiplican a medida que nos estornudar.}
{3078}{}{Empalar a su oponente con su ego.}
{3079}{}{Fingir debilidad. Dar ánimo a los del adversario de la ignorancia.}
{3080}{}{Estrategia táctica medio de un seguro de la victoria.}
{3081}{}{Cauteloso de los gobernantes son, en general, todos pecadores.}
{3082}{}{Salir de suprema excelencia, y una nación estremecerán los beneficios de la prolongada guerra.}
{3083}{}{Tácticas para conquistar a los hombres. Estrategia para desarrollar viendo.}
{3084}{}{Hay millones de maneras para que un gato a despojarse de su piel.}
{3085}{}{No se puede exprimir guijarros a partir de una gota de sangre.}
{3086}{}{No hay sangre sea más espesa que la del agua.}
{3087}{}{Debe haber dos soles en el cielo.}
{3088}{}{Robar la carne y la marcamos.}
{3089}{}{Lo Mental es la carne, llevando el potencial que se desvanece.}
{3090}{}{Un pájaro canta porque su canción es la respuesta.}
{3091}{}{Baja la voz y aumentar su fuerza.}
{3092}{}{Comer más allá de sus límites, a pie de acuerdo a las longitudes vas a ir.}
{3093}{}{Si una palabra vale más que el jeque silencio que ser digno de un emperador.}
{3094}{}{Él que vive fuera de este plano muere con honor.}
{3095}{}{Engañar a los pobres. Insulto a los ricos.}
{3096}{}{Una vez que el calor que ha pasado, te olvidas de la sombra del árbol.}
{3097}{}{Nadie está más cerca de la muerte como el que escucha.}
{3098}{}{Cada uno para todos y todos para nosotros.}
{3099}{}{Todos los hombres son inmortales, como el de Ocho.}
{3100}{}{Cuando te estás muriendo de sed, no es demasiado tarde para excavar en busca de agua.}
{3101}{}{El más alto, el bambú crece, más cerca de la panda llega a los emergentes.}
{3102}{}{Nunca se debe confiar en la gloria de la mañana o la sonrisa de su madre-en-ley.}
{3103}{}{Los ojos son nuestra única de windows.}
{3104}{}{La vejez se arrastra para arriba en usted como un viejo y sucio hombre.}
{3105}{}{El cielo nunca es la culpa. Los impíos serán pagados sus salarios en el tiempo.}
{3106}{}{La justicia es el alma virtuosa que se distribuye en el desierto.}
{3107}{}{Es mejor que diez inocentes morir de un hombre culpable de sufrir.}
{3108}{}{Las salas en las salas de justicia son los únicos de la justicia.}
{3109}{}{Bloqueo del establo cuando el caballo es robado.}
{3110}{}{Haymakers bajo el sol brillando.}
{3111}{}{Nunca tome un regalo de un caballo en la boca sin preguntar primero.}
{3112}{}{El mundo se ríe de ti. Luego llorar con sus compañeros.}
{3113}{}{Muchas manos hacen las luces de trabajo.}
{3114}{}{Un plato de zanahorias limpias, sin limpiar, con verduras.}
{3115}{}{Un burro labios los besos de una boca del caballo sólo cuando se alimenta con forraje extra durante la noche.}
{3116}{}{Traer un club en un tigre de la guarida.}
{3117}{}{Un porcina arroja un collar de perlas.}
{3118}{}{Caviar Emperador.}
{3130}{}{De acuerdo. Ahora estamos llegando a algo.}
{3210}{}{Bien, ahora que sé que su papá la historia de la vida, ¿te importaría llegar a la parte acerca de usted?}
{3260}{}{De modo que eran traidores a su pueblo, sino por su gente buena. Lo consiguió.}
{3261}{}{Mira, estoy harto de escuchar acerca de sus padres. ¿Cómo 'bout llegar a la parte que eres un espía?}
{5000}{kit96}{[Como la mujer se ve en su rostro, sus ojos de repente crecen amplia y ella comienza a jadear por aire.]}
{5001}{}{[FIN]}
{5002}{}{¡Joder!}
