{100}{}{Ves a un necrófago más grande de lo normal.}
{101}{}{Ves a Zomak, conocido por algunos como El Destructor.}
{102}{}{Ves a un necrófago grande y fornido cuyo rostro, bajo una frente fuertemente inclinada, refleja vastas
 reservas de estúpida superioridad.}
{110}{zomak1}{¡Renuévate, Camarada! Soy Zomak. Hay quien me llama Zomak el Destructor. ¿Qué te trae por aquí?}
{111}{zomak2}{¡Renuévate, Camarada! ¿Qué estás haciendo aquí? Dile a Zomak el Destructor qué te trae por aquí.}
{112}{}{¡Reno!}
{113}{}{¿Vaaaaaaaaale?}
{114}{}{Tan sólo estoy echando un vistazo.}
{115}{}{Deseo la Renovación.}
{116}{}{He tomado el pasillo equivocado.}
{120}{zomak3}{Deberías echarlo en algún otro lugar. O Zomak te hará ver las estrellas.}
{130}{zomak4}{Entonces debes verlo a Él.}
{131}{}{¿Él? ¿Dónde está ese Él?}
{132}{}{No soy digno de verlo. Adiós.}
{140}{zomak5}{Él es el garante de la iluminación. Él es quien promete Renovación a todos los que le siguen.}
{141}{}{Bueno, estoy listo para la Renovación. ¿Dónde está?}
{142}{}{A mí me pareces otro chiflado más. Me largo de aquí.}
{150}{zomak6}{Bueno, está justo… ¡Oye!, De todos modos, ¿quién eres tú?}
{151}{}{Sólo soy un trotamundos.}
{152}{}{Soy el Elegido.}
{153}{}{Estoy aquí para mi Renovación anual.}
{154}{}{Estará bien. Sólo tengo que hacerle un par de preguntas.}
{160}{zomak7}{Bien, pues trota fuera de aquí.}
{161}{}{Eh, de acuerdo. Adiós.}
{170}{zomak8}{En ese caso está bien. Entra. Está en la siguiente estancia. No le hagas esperar.}
{171}{}{No, iré directamente. Adiós.}
{172}{}{Puede que vuelva más tarde. Adiós.}
{180}{zomak9}{Puedes deberías elegir seguir vivo. Lárgate de aquí.}
{181}{}{Vale.}
{200}{zomak10}{Sí, puedes Renovarte por completo ahí dentro.}
{201}{}{Vale.}
{210}{zomak11}{¿Ook? ¿Qué quieres decir con eso? ¿Es que eres tonto?}
{211}{}{¿Goop?}
{220}{zomak12}{Lárgate de aquí. El Cerebro no tiene tiempo para los de tu clase.}
{221}{}{Vale. Ya me marcho.}
{230}{zomak13}{Aquí abajo no hay nada excepto la guarida del Cerebro. Muchacho, eres tonto.}
{231}{}{¿El Cerebro?}
{232}{}{Sólo te estaba probando. Y lo has hecho bien. Ahora, déjame entrar.}
{233}{}{Supongo que estoy confuso. Debe de ser toda esta radiación. Adiós.}
{240}{zomak14}{Ups. Eh, aquí no hay nada. Nada de nada. Límitate a marcharte ahora.}
{241}{}{¿Estás seguro de que aquí no hay nada?}
{242}{}{Está bien. Adiós.}
{250}{zomak15}{Que sí. Estoy seguro. Desaparece.}
{251}{}{Bueno, si tú lo dices. Adiós.}
{260}{zomak16}{Oh, je, je... sí. Lo sabía. Emm, bien, err, ¿he aprobado? }
{261}{}{Desde luego. Ahora, déjame entrar.}
{262}{}{No, no lo has hecho, y ahora tengo que informar sobre ti.}
{270}{zomak17}{Está bien. Puedes entrar.}
{271}{}{Está bien. Adiós.}
{280}{zomak18}{Tienes el símbolo. Entra.}
{281}{}{Entro.}
{282}{}{¿El símbolo?}
{283}{}{Paso de símbolos. Adiós.}
{290}{zomak19}{Sí, el talismán sagrado de la Renovación. ¡Renueva, camarada! ¡Renueva!}
{291}{}{Sí, Reno también para ti. Adiós.}
{300}{zomak20}{Renuévate, Hermano. Puedes pasar.}
{301}{zomak21}{Renuévate, Hermana. Puedes pasar.}
