{100}{}{Ves a un extraño mitad perro, mitad cosa. Parece estar activado.}
{101}{}{¡Es Roboperro! ¡La mascota favorita de todo el mundo!}
{102}{}{O esta cosa es una horrible mezcla de perro y máquina, o es una máquina astutamente diseñada para parecer un perro. Es difícil de decir.}
{103}{dogr16}{¡Arf! <click> ¡Woof!}
{104}{dogr17}{...bzzzzzz...}
{105}{dogr18}{.whirrrrr... No soy un perrito.}
{106}{dogr19}{Grrrrrrrrrrrrrrrr--}
{107}{dogr20}{¡Woof! Wo-wo-wo-<click>woof.}
{108}{dogr21}{<sprzzzt> Miau... error.}
{109}{dogr22}{¡Barkbarkbarkbarkbarkbarkbark!}
{110}{dogr23}{Grrr...}
{111}{dogr24}{¡How-woooo! <click-click> ¡How-wooo!}
{112}{dogr25}{¡Yipe! ¡Yipe! ¡Yipe!}
{113}{dogr26}{¡Peligro! ¡Peligro!}
{114}{dogr27}{¡Rowf! <tick-tick-tick> ¡Rowf!}
{115}{dogr28}{<whirrr> No es un pájaro, no es un avión, ni siquiera es una rana, sólo tu viejo amigo: ¡Roboperro!<click>}
{116}{dogr29}{¡Rooby-Doo!}
{117}{dogr30}{¡Ee-bee-dee-bee-ee-bee-dee-bee!}
{118}{dogr31}{¡Guau!}
{119}{dogr32}{¡GRRR-ROWF!}
{120}{dogr1}{¡Arf-arf-arf-arf-arf-arf-arf!}
{121}{}{Vale}
{122}{}{No creo que quiera volverme a juntar contigo. Adiós.}
{123}{dogr2}{¿Rowf? <boing> ¿Raggy?}
{124}{}{¿Cómo estás?}
{125}{}{Necesito que esperes aquí hasta que vuelva.}
{126}{}{Esto es todo por ahora.}
{127}{dogr3}{<click> whimper}
{128}{}{No importa.}
{129}{}{Vale}
{130}{}{HP:}
{131}{}{El ciberperro no puede ser reparado en este momento.}
{132}{}{El ciberperro ha sido parcialmente reparado.}
{133}{}{Ahora el ciberperro está totalmente reparado.}
{1000}{dogr4}{¡Woof! Wo-wo-wo-<click>¿woof?}
{1100}{dogr5}{¡Arf! <click> ¡Woof!}
{1200}{dogr6}{¿Rowf? <boing> ¿Raggy?}
{1300}{dogr7}{<click> whimper.}
{1400}{dogr8}{¡How-woooo! <click-click> ¡How-wooo!}
{1500}{}{¡Ee-bee-dee-bee-ee-bee-dee-bee!}
{1600}{}{Sí, lo dejaré a un lado.}
{1700}{}{Arf-arf proximidad cercana.}
{1800}{}{Arf-arf proximidad media.}
{1900}{}{Arf-arf proximidad lejana.}
{2000}{dogr14}{.whirrrrr... No soy un perrito.}
{2100}{dogr33}{¡GRRR-ROWF!}
{2200}{dogr15}{¡Woof! Wo-wo-wo-<click>¿woof?}
{2204}{}{Vale, ahora estás a una buena distancia.}
