{100}{}{Ves a Amanda.}
{101}{}{Ves a una mujer de apariencia cansada. Parece como si hubiera estado llorando.}
{102}{}{Ves a Amanda.}
{103}{}{Ves a una mujer de apariencia cansada. Parece como si hubiera estado llorando.}
{104}{}{Ves a Amanda. Parece mucho más feliz ahora que Joshua está libre.}
{105}{}{Ves a Amanda.}
{106}{}{Ves a Amanda. Parece mucho más feliz ahora que Joshua está libre.}
{107}{ama11}{Oh, Joshua...}
{108}{ama12}{¿Qué voy a hacer?}
{109}{ama13}{Se ha agotado el dinero...}
{110}{ama14}{Si tan solo los Ciudadanos le dejasen marchar...}
{111}{ama15}{Joshua, cómo me alegra que estés libre. Estaba tan preocupada...}
{112}{ama16}{Lo siento, no tengo ningún folleto para darte.}
{113}{ama17}{Por favor, déjame sola, o llamaré a los guardias.}
{114}{ama1}{¿Qué quieres?}
{115}{}{¿Estás bien? Pareces disgustada.}
{116}{}{Nada. Perdón por molestarte.}
{117}{ama2}{Yo... yo... es mi marido, Joshua. Él... tuvo algún tipo de problema en... el bar. Golpeó accidentalmente a un Ciudadano y lo arrestaron. No era su intención, pero había estado bebiendo, y...}
{118}{}{¿Arrestado? ¿Dónde está ahora?}
{119}{}{Si estaba borracho y atacó a alguien, entonces debió ser arrestado.}
{120}{}{Lamento oír eso. Espero que lo dejen ir.}
{121}{ama3}{Dentro de la ciudad, en el Centro de Asignación de Siervos... dijeron que podría cumplir su sentencia como siervo, ¡pero eso le llevará años!}
{122}{}{¿Qué se puede hacer?}
{123}{}{Si estaba borracho y atacó a alguien, entonces debió ser arrestado.}
{124}{}{Lamento oír eso. Espero que lo dejen ir.}
{125}{ama4}{¡Pero fue un accidente! Yo... él no pretendía hacerlo!}
{126}{}{¿Dónde está ahora?}
{127}{}{¿Él no pretendía atacar a alguien? Ya, claro. Quizá esta sea una buena lección para ti.}
{128}{}{Lamento oír eso. Espero que lo dejen ir.}
{129}{ama5}{No me queda mucho dinero, y nos tendremos que ir pronto si no nos podemos permitir pagar la protección de los guardias. Dijeron que si queríamos quedarnos con Joshua, entonces también podríamos convertirnos en siervos...}
{130}{}{Eso parece una solución. Tratan bastante bien a los siervos en Ciudad Refugio, ¿no es verdad?}
{131}{}{Déjame comprobar lo que puedo hacer, ¿vale? Tal vez pueda hablar con alguien en el Centro de Asignación.}
{132}{}{Podría ayudarte. Pero tiene su precio.}
{133}{}{Lamento oír eso. Espero que lo dejen ir.}
{134}{ama6}{¡No quiero que mi hijo se críe como un esclavo! Vinimos a Ciudad Refugio porque habíamos oído que era una ciudad libre... pero llegamos aquí... y todo lo que hay son esas leyes, y pagos a los guardias y... no se parece en nada a lo que nos habían contado.}
{135}{}{Déjame comprobar lo que puedo hacer, ¿vale? Tal vez pueda hablar con alguien en el Centro de Asignación.}
{136}{}{Lamento oír eso. Espero que lo dejen ir.}
{137}{ama7}{La persona al cargo es Barkus, el oficial Barkus. Ni siquiera he podido entrar en la ciudad para verlo. ¡Ni siquiera sé si Joshua está bien! Yo...}
{138}{}{No te preocupes. Veré lo que puedo hacer.}
{139}{ama8}{Pero no tengo mucho dinero, y...}
{140}{}{No estaba pensando en dinero.}
{141}{}{No importa. Tal vez pueda hablar con alguien en el Centro de Asignación.}
{142}{}{Lamento escuchar eso, entonces. Quizá simplemente lo dejen ir. Adiós.}
{143}{ama9}{¿En qué estabas pens...? Oh, no. Yo... no podría. Quiero decir, yo...}
{144}{}{¿Quieres a tu marido libre, o no? Él nunca lo sabrá.}
{145}{}{No importa. Tal vez pueda hablar con alguien en el Centro de Asignación.}
{146}{}{Lamento oír eso. Parece que tu marido nunca será libre. Adiós.}
{147}{ama10}{Si prometes liberar a mi marido, yo... yo... está bien. Yo... cerraré el faldón de la tienda. Yo... creo que mi hijo sigue jugando por ahí fuera, así que no nos molestará.}
{148}{}{No te preocupes, liberaré a tu marido. Después de recibir mi pago.}
{149}{}{Olvídalo. Quizá pueda hablar con alguien en Centro de Asignación.}
{150}{}{No importa. Olvida que nos hemos conocido.}
{151}{}{Oye, ¡¿y yo?!}
{152}{ama18}{Por favor, rescata a Joshua. Está dentro de la ciudad, en el Centro de Asignación de Siervos.}
{153}{ama19}{¡Gracias por rescatar a mi marido! Por favor... acepta esto como recompensa. No es mucho, pero...}
{154}{ama20}{Gracias de nuevo por rescatar a mi marido. Pronto nos marcharemos.}
{155}{ama21}{Eh... gracias por rescatar a mi marido... por favor, no le digas lo que sucedió entre nosotros.}
