{100}{}{Du siehst einen Geist.}
{101}{}{Du siehst Anna, den Geist.}
{150}{}{Das ist ein Geist, also etwas, das du nicht alle Tage siehst.}
{151}{}{Sie sieht ziemlich gequält aus.}
{152}{}{[GESPRÄCH]}
{153}{anna1}{Oh, diese Schmerzen! Es brennt so!}
{154}{}{Was ist los?}
{155}{}{Wer bist du?}
{156}{}{Hinfort, abscheulicher Geist!}
{157}{anna2}{Ich halte an jeder Tür und klopfe. Aber niemand öffnet. Niemand hört mich.}
{158}{}{Ich kann dich hören. Was ist los?}
{159}{}{Ich glaube, du solltest mal deinen Stealth Boy ausschalten, junge Dame.}
{160}{anna3}{Wo ist es? Ich kann es nicht finden! Ich bin verloren! Oh...}
{161}{}{Was suchst du? Vielleicht kann ich dir helfen.}
{162}{}{Hör doch mit diesem Stöhnen und Jammern auf und sag, was los ist.}
{163}{anna4}{Mein Medaillon! Es ist weg! Dieb! Dieb!}
{164}{}{Huah, ich bin gerade erst gekommen. Ich war's nicht.}
{165}{}{Soll ich dir helfen, es zu suchen?}
{166}{anna5}{Oh, grausames Schicksal.}
{167}{}{Du kannst mich nicht hören, nicht wahr?}
{168}{}{Bis später, Geistermädchen.}
{169}{}{Tschüss. Ich werd versuchen, dir zu helfen.}
{170}{anna6}{Mein Medaillon! Gib es mir!!! Oh!!!!}
{171}{}{Niemals! Ich hab's ganz ehrlich gefunden.}
{172}{}{OK. Hier hast du es.}
{173}{}{Hier. Ruhe in Frieden. }
{174}{}{OK.}
{175}{}{Nein.}
{176}{anna7}{Mein Medaillon, mein Medaillon! Ich komme, Papa! Ich komme!}
{177}{}{Wiedersehn.}
{178}{}{Warte! Geh nicht!}
{179}{}{Geh in das Licht!}
{200}{anna8}{Wo könnte es sein?}
{201}{anna9}{Ohhh.}
{202}{anna10}{Mama? Papa? Wo seid ihr?}
{203}{anna11}{Ich kann es nicht finden!}
{500}{anna12}{Mama... Papa... ich komme...}
{501}{anna13}{Es ist so hell...}
{502}{anna14}{Oma, ich kann dich sehen...}
{503}{anna15}{Oh, es ist der nette Herr Cain... Schön dich wieder zu sehen.}
{550}{}{Dieses Haus ist sauber.}
{551}{}{Oh, schöne Knochen.}
{560}{}{GEISTERJÄGER!}
{561}{}{Agh.}
