{100}{}{Du siehst eine sehr hübsche junge Dame.}
{101}{}{Du siehst Rebecca.}
{150}{}{Du siehst Rebecca, die Besitzerin von Beckys Kasino.}
{200}{}{Hallo. Ich heiße Rebecca, kann ich dir was zu trinken bringen? Du hast bestimmt Durst
 nach deiner Reise durch die Öde.}
{201}{rbcca2}{Hey! Willst du was zu trinken, oder bis du nur zurück gekommen, um Hallo zu sagen?}
{202}{}{Hallo! Schön, dass du zurückgekommen bist. Hast du Fragen, oder bist du wegen dem guten
 Whiskey hier?}
{203}{rbcca4}{Wirklich schön, dich zu sehen. Was ist los? Brauchst du etwas?}
{204}{}{Ich hoffe, bei meinem Lieblingsgast ist alles in Ordnung. Was können wir heute für dich
 tun?}
{205}{rbcca6}{Hallo!}
{206}{rbcca7}{Es ist immer wieder schön, dich wiederzusehen.}
{207}{rbcca8}{Hallo! Möchtest du was trinken? Der beste Whiskey im Land!}
{208}{rbcca9}{Hallo!}
{209}{rbcca10}{Du bist es! Das habe ich mir gedacht. Willst du was trinken Schatz?}
{210}{}{Bist du wegen Rebeccas großartiger Unterhaltung oder dem weltbekannten Whiskey
 zurückgekommen?}
{211}{rbcca12}{Willkommen in Rebeccas Bar und Kasino. Was kann ich für dich tun?}
{212}{rbcca13}{Hallo. Können wir dir helfen?}
{213}{rbcca14}{Möchtest du etwas? Vielleicht was zu trinken?}
{214}{rbcca15}{Möchtest du was zu trinken oder vielleicht etwas anderes?}
{215}{rbcca16}{Wie kann ich dienen?}
{216}{rbcca17}{Guten Tag. Was dürfen wir bringen?}
{217}{rbcca18}{Brauchst du etwas?}
{218}{rbcca19}{Schön, dich wiederzusehen. Wie kann ich dir helfen?}
{219}{rbcca20}{Was?}
{220}{rbcca21}{Ja?}
{221}{rbcca22}{Was ist denn jetzt schon wieder?}
{222}{rbcca23}{Fass dich bitte kurz. Es ist heute viel los. Was brauchst du?}
{223}{rbcca24}{Was kann ich für dich tun? Ich habe wirklich zu tun.}
{224}{rbcca25}{Bist du hier, um was zu trinken? Die Tische sind da drüben.}
{225}{rbcca26}{Ich bin eigentlich nicht in Stimmung. Was ist?}
{226}{rbcca27}{Du schon wieder? Dann willst du wahrscheinlich was zu trinken?}
{240}{rbcca28}{Klar doch!}
{241}{rbcca29}{Was möchtest du denn wissen?}
{242}{rbcca30}{Sehr gern.}
{243}{rbcca31}{Aber natürlich.}
{244}{rbcca32}{Sicher.}
{245}{rbcca33}{Ich hätte nichts dagegen.}
{246}{rbcca34}{Ich helfe, wenn ich kann.}
{247}{rbcca35}{Natürlich! Sei nicht dumm!}
{248}{rbcca36}{Was auch immer. Was war es denn nun?}
{249}{rbcca37}{Ich werde alles tun, um Dir zu helfen. Was möchtest du wissen?}
{250}{rbcca38}{Frage weiter.}
{251}{rbcca39}{Wenn du darauf bestehst.}
{252}{rbcca40}{Sieht so aus.}
{253}{rbcca41}{Fass dich kurz. Ich muss den Laden führen.}
{254}{rbcca42}{In Ordnung. Was ist es?}
{255}{rbcca43}{Nehme ich an.}
{256}{rbcca44}{Was?}
{257}{rbcca45}{Leider nein.}
{258}{rbcca46}{Nicht jetzt.}
{270}{}{Ich brauche was zu trinken.}
{271}{}{Ich bin auf der Suche nach einem Händler, der Vaultausstattung verkauft.}
{272}{}{Ich suche nach einem Händler namens Vic.}
{273}{}{Hast du Arbeit?}
{274}{}{Zu diesem Job...}
{275}{}{Gibt's noch mehr Arbeit für mich?}
{276}{}{Nichts. Tschüss.}
{277}{}{Wikie.}
{278}{}{Ruh ruh?}
{279}{}{Icha schascha.}
{280}{}{daj.}
{281}{}{Ruh ruh?}
{300}{}{Whiskey ist meine Spezialität. Das ist in der Familie Dyer fast eine Tradition. Ich
 verlange den spottbilligen Preis von nur $5.}
{301}{rbcca48}{Drinks kosten immer noch $5 und die Familie Dyer macht die besten Drinks der Welt.}
{302}{rbcca49}{Bist du in Ordnung? Willste 'n Whiskey? Nur $5.}
{303}{}{Ich nehm einen Drink.}
{304}{}{Warum sind deine Drinks so billig?}
{305}{}{Dyer?}
{306}{}{Kann ich eine Frage stellen?}
{307}{}{Tschüss.}
{308}{}{Wikie}
{309}{}{Urka.}
{320}{}{Oh, das ist mein Familienname. Schon vor dem Krieg war der Name Dyer ein Begriff im
 Kneipengeschäft.}
{321}{}{Wie gesagt, es ist mein Familienname. Früher gab es auf der ganzen Welt Dyer-Kneipen,
 Dyer-Saloons und sowas.}
{322}{}{Ich nehm einen Drink.}
{323}{}{Kann ich noch eine Frage stellen?}
{324}{}{Tschüss.}
{330}{}{Weil du so ein guter Kunde bist, werd ich dir ein kleines Geheimnis verraten. Es ist ganz
 einfach - ich hab einen Destillator. Ein Freund aus einer nahegelegenen Stadt hat mir gezeigt,
 wie man einen baut. Also, möchtest du noch einen?}
{331}{}{Tut mir leid, das ist ein Betriebsgeheimnis. Außerdem kenn ich dich nicht so gut. Ich
 möcht nicht, dass Frankie es rauskriegt. Er macht mir so schon genug Schwierigkeiten. Wolltest du
 noch einen? Sie sind wirklich spitze.}
{332}{}{Klar. Ich nehm noch einen.}
{333}{}{Kann ich noch eine Frage stellen?}
{334}{}{Okay, danke.}
{340}{rbcca54}{Hier. Vielen Dank.}
{341}{}{Danke. Kann ich dich was fragen?}
{342}{}{Okay, danke.}
{343}{}{Dankey Direy.}
{344}{}{Fraag?}
{350}{rbcca55}{Nein, ich glaube nicht.}
{351}{rbcca56}{Fred schuldet mir $200. Wenn du es eintreiben kannst, können wir einen Handel machen.}
{352}{rbcca57}{Ich habe immer noch dieses einzutreibende Darlehen.}
{353}{}{Derek hat sich vor einiger Zeit ein Buch von mir geliehen. Ich gebe dir $80, wenn du es
 mir wieder besorgen kannst.}
{354}{rbcca59}{Ich suche immer noch nach meinem Buch.}
{355}{}{Wo ist der Haken?}
{356}{}{Erzähl mir mehr.}
{357}{}{Darf ich dich was fragen?}
{358}{}{Tschüss.}
{370}{}{Haken? Naja, du müsstest wahrscheinlich Fred kennen, um das zu verstehen. Er schuldet mir
 schon seit einiger Zeit das Geld. Ich habe es als Verlust abgeschrieben, aber wenn du es
 zurückholen kannst, wäre ich freudig überrascht... und dankbar. Ich bin mir sicher, er ist
 irgendwo in der Stadt.}
{371}{rbcca61}{Das Buch war "Die Lavendelblüte". Derek müsste eigentlich bei Mom auf der Ostseite sein.}
{372}{}{Ich werde sehen, was ich tun kann.}
{373}{}{Hört sich einfach an.}
{374}{}{Ich habe es schon gefunden.}
{375}{}{Ich werde mich wieder mit dir in Verbindung setzen.}
{385}{rbcca62}{Du hast es nicht wirklich, oder? Das würde mich schon sehr überraschen.}
{386}{rbcca63}{Oh, hast du mein Buch gefunden? Derek hat da besser keinen Mist gemacht.}
{387}{}{Ja.}
{388}{}{Tut mir leid. Er ist tot.}
{389}{}{Leider ist Derek ebenfalls tot.}
{390}{}{Tut mir leid, aber er ist tot.}
{391}{}{Ja. Hier ist es.}
{392}{}{Leider nein.}
{400}{}{Ich kann's nicht glauben. Wie hast du das gemacht? Na lass mal. Ich bin nur überrascht,
 das ist alles. Um dir meine Dankbarkeit zu zeigen, werde ich es mit dir teilen, Halbe-Halbe.
 Noch mal danke, das war sehr ehrlich von dir.}
{401}{rbcca65}{Ich bin so froh, dass du es gefunden hast... Vielen Dank. Hier ist dein Geld.}
{402}{}{Gern geschehen.}
{410}{}{Ich kann es kaum glauben, dass sie beide tot sind. Das tut mir leid. Danke, dass du es für
 mich herausgefunden hast. Wenn du mich jetzt entschuldigst...}
{411}{rbcca67}{Ich kann nicht glauben, dass er tot ist... nach all den Jahren.}
{412}{}{Sicher.}
{413}{}{...}
{420}{rbcca68}{Ja, ich weiß, wer das ist. Es ist Vic - der Typ, den Metzger eingesperrt hat.}
{421}{rbcca69}{Ja, ich kenne Vic. Metzger hat ihn eingesperrt. Ich weiß aber nicht, warum eigentlich.}
{422}{}{Wer ist Metzger?}
{423}{}{Ich habe noch eine Frage.}
{424}{}{Klasse! Tschüss.}
{430}{}{Du kommst nach Den und weißt nicht, wer Metzger ist? Er ist der Sklavenhändlermeister. Er
 ist im Osten der Stadt. Du kannst ihn kaum verfehlen.}
{431}{}{Ich habe noch eine Frage.}
{432}{}{Danke.}
{440}{rbcca85}{Mörder!}
{441}{rbcca86}{Mörder!}
{442}{rbcca87}{Bitte geh.}
{443}{rbcca88}{Ich gebe mich mit Leuten wie dir nicht ab.}
{444}{rbcca89}{Ohne Kampf gebe ich mich nicht geschlagen!}
{450}{rbcca71}{Buffy! Du bist es! Wie geht es dir? Lange nicht mehr gesehen!}
{451}{}{Häh?}
{452}{}{Häh?}
{460}{}{Dave schickt seine besten Grüße und lässt dir ausrichten, er wäre auch gekommen, wenn er
 nicht hätte abhauen müssen.}
{461}{}{Wohin gehts?}
{470}{}{Irgendein Kommandotrupp oder er verfolgte einen solchen Trupp. Weiß ich eigentlich
 nicht genau. Irgend sowas.}
{471}{}{Oh.}
{480}{}{Er bat mich, dir das hier zu geben. Es ist ein Geschenk der Familie Hendee. Es müsste dir
 eine Hilfe sein.}
{481}{}{Was ist es?}
{490}{}{Oh, nur so ein paar Sachen. Hier. [Becky gibt dir $1000, 5 Stimpaks, eine Metallrüstung,
 eine Uzi, 5 Munitionsstreifen, eine Plasmagranate und eine Blume]}
{491}{}{Danke auch!}
{500}{}{Kein Problem. Ich habe sie nur für dich aufgehoben. Ich gehe dann wieder an die Arbeit
 zurück.}
{501}{}{Danke, Tschüss.}
{510}{}{Hast du nicht gehört? Er ist tot! Oh, ich weiß, dass man sich darüber nicht freuen sollte,
 aber er war ein sehr schlechter Mensch.}
{511}{}{Er wusste, wie man kämpft.}
{512}{}{Ich habe eine Frage.}
{513}{}{Ja, das war er. Wiedersehn.}
{514}{}{ töten!}
{520}{rbcca78}{Was? Du? Ich weiß nicht, was ich sagen soll. Er war so ein schlechter Mensch.}
{521}{}{Ein Dankeschön wäre schon genug.}
{522}{}{Hmpf.}
{530}{}{Oh, ein Dankeschön wäre schon genug. Ich weiß, dass das nicht ganz richtig ist, aber...
 hier, nimm das Geld. [Becky gibt dir 1000 Dollar]}
{531}{}{Behalte dein Geld, Rebecca.}
{532}{}{Vielen Dank.}
{533}{}{Tank!}
{534}{}{Ug! Schön Frau.}
{540}{}{Du bist ein wunderbarer Mann. Ich bin zwar nicht mit deinen Taten einverstanden, aber du
 hast der Welt einen großen Dienst erwiesen.}
{541}{}{Du bist eine wunderbare Frau. Ich bin zwar nicht mit deinen Taten einverstanden, aber du
 hast der Welt einen großen Dienst erwiesen.}
{542}{}{Danke.}
{550}{rbcca90}{Du bist hier nicht willkommen. Bitte geh.}
{551}{rbcca91}{Bitte geh.}
{560}{rbcca82}{Warum hast du meinen Destillator zerstört? Was habe ich dir getan?}
{561}{}{Ich wurde dafür bezahlt.}
{562}{}{Ich muss niemandem antworten.}
{563}{}{Ich weiß nicht, wovon du sprichst.}
{564}{}{Wie du willst.}
{565}{}{Uuba Guuba}
{570}{}{Wirklich? Dazu hat dich dieser Frankie gebracht, da bin ich mir sicher. Ich bau einfach
 einen neuen.}
{571}{}{Egal. Ich wurde bezahlt.}
{572}{}{Also.}
{573}{}{Ich wäre nicht überrascht.}
{580}{rbcca84}{Also bist du auch noch ein Feigling? Eigentlich klar.}
{581}{}{...}
