{100}{}{Du siehst einen Sklaven.}
{101}{}{Du siehst Vic.}
{150}{}{Dieser Sklave scheint unter strenger Überwachung zu stehen.}
{151}{}{Das ist Vic.}
{152}{}{[GESPRÄCH]}
{153}{}{Kannst du ihm sagen, ich kann nicht... warte mal. Wer bist du? Du bist kein
 Sklavenhändler. Was machst du hier?}
{154}{}{Ich heiße }
{155}{}{. Ich bin hier, um dich hier rauszuholen.}
{156}{}{Ich bin }
{157}{}{, aber warum wurdest du in diesem Raum eingesperrt?}
{158}{}{Kannst du mir sagen, wo Vault 13 ist?}
{159}{}{Ich bin }
{160}{}{. Ich bin gleich zurück.}
{161}{}{Dubba iba }
{162}{}{.}
{163}{}{Metzger ist immer noch ziemlich sauer auf mich, obwohl wir sein verdammtes Funkgerät
 repariert haben. Er droht, mich zu verkaufen! Ich tu alles, wenn du mich nur aus diesem
 Schlamassel hier rausholst.}
{164}{}{OK.}
{165}{}{Tut mir leid, ich kann nicht. Tschüss.}
{166}{}{Huuh.}
{167}{}{Oh, hallo. Dieses verdammte Funkgerät repariert sich nicht von selbst. Was glaubt er, wie ich
 es wieder hinkriegen soll?}
{168}{}{Wo bekomme ich die Teile?}
{169}{}{Vielleicht kann ich es reparieren.}
{170}{}{Kannst du dieses Funkgerät verwenden, das ich gefunden habe?}
{171}{}{Ich werde sehen, was ich tun kann.}
{172}{}{Ärsatz-tajle?}
{173}{}{Ich weiß, dass ich es kann, ich brauch nur einige Ersatzteile. In meiner Hütte drüben in
 Klamath steht ein altes Funkgerät mit allem, was ich brauche. Warst du schon mal bei den Duntons?
 Meine Hütte ist... ähm, war direkt östlich von ihnen.}
{174}{}{Meinst du dieses Funkgerät?}
{175}{}{Ich werd es holen.}
{176}{}{Hmmm... Ich komme wieder.}
{177}{vic5}{Großartig! Ich werde das Funkgerät in Null-Komma-Nix fertig haben.}
{178}{}{Okay, ich red mit Metzger.}
{179}{vic6}{Danke.}
{180}{}{Tschüss.}
{181}{vic7}{Wie bitte? Tut mir leid, aber ich versteh nicht.}
{182}{}{hähm.}
{183}{vic8}{Danke! Ich steh für immer in deiner Schuld. Wie kann ich mich revanchieren?}
{184}{}{Sag mir, wo Vault 13 ist.}
{186}{}{Komm mit, ich kann Hilfe gebrauchen.}
{187}{}{Es war nichts. Wiedersehn.}
{188}{}{Schoko?}
{189}{}{Vault 13? Es gibt die sogenannte Vault City östlich von hier. Ich handle dort
 manchmal.}
{190}{}{Kommst du mit dorthin?}
{191}{}{Danke. Tschüss.}
{192}{}{Sicher, ich begleite dich! Diese alten Knochen sind noch gut für ein großes Abenteuer.
 Ich bin sicher! Ich bin auch ziemlich geschickt Reparieren, egal, was Metzger sagt.}
{193}{}{Großartig, los.}
{194}{}{Willkommen an Bord.}
{195}{}{Wie du willst.}
{196}{}{Vic best Freund von mir.}
{197}{}{Willst du mich bei meiner Suche begleiten?}
{198}{}{Super, danke.}
{203}{vic11}{Vault City ist östlich von hier. Hier, ich zeig's dir auf der Karte.}
{204}{}{Danke.}
{206}{vic12}{Es ist genau hier. [Zeigt auf eine Karte]}
{220}{}{Verdammt. Bin schon nah dran, aber ich brauch das Funkgerät aus meiner Hütte in
 Klamath. Da drin sind die passenden Teile.}
{300}{vic14}{Ja, ich kann dir wahrscheinlich helfen, aber du musst mich hier erst rausholen.}
{301}{}{Ich hab's dir gesagt. Wenn du mich hier rausholen kannst, helfe ich dir mit allem, was du
 willst.}
{302}{}{Wie machen wir das?}
{303}{}{Dann bist du auf dich selbst gestellt.}
{304}{}{Okay, ich werd sehen, was ich tun kann.}
{350}{vic117}{Meinst du, du kannst mir helfen?}
{351}{vic118}{Metzger wird mich immer noch nicht gehen lassen.}
{352}{vic119}{Ich halte das nicht mehr lange aus.}
{353}{vic120}{Ich tu alles für dich, wenn du mir hilfst.}
{354}{vic121}{Ich arbeite alle Ausgaben ab, die du vielleicht hast!}
{400}{}{Du warst noch nie bei mir, oder? Ich brauch das Funkgerät unbedingt, Metzger wird von Tag zu
 Tag wütender auf mich.}
{450}{}{Woher hast du diese Wasserflasche?}
{451}{}{Ich hatte eine Wasserflasche mit einer großen gelben 13 darauf. Weißt du noch, woher du
 sie hattest?}
{500}{}{Oh, ja. Ich weiß es noch. Ich habe sie von Ed gekauft. Er ist ein Brahminhändler drüben
 in Vault City.}
{501}{}{Wasserflasche? Oh, warte. Ja, ich hatte ein paar Dutzend davon. Gingen ziemlich gut. Hab
 sie von Ed gekriegt. Einem Brahminhändler drüben in Vault City.}
{502}{}{Vault City?}
{550}{}{Hörst du bitte auf, mich Boss zu nennen?}
{600}{vic19}{Klar, Chef!}
{601}{}{Ich mein es ernst! HÖR AUF!}
{602}{}{Ich denke, das muss so gehen.}
{650}{vic20}{Das ist es, Sportsfreund!}
{651}{}{Uggg!}
{700}{}{Sei Freund.}
{710}{}{Sag ihm bitte, dass ich es ohne die Teile nicht reparieren kann. Ich weiß nicht... warte.
 Wer bist du? Ein Neuer? Er hat dich nicht geschickt, um mich wieder aufzumischen, oder? Das wird
 auch nichts ändern. Ich kann's hier nicht hinkriegen.}
{750}{}{Wow! Das würdest du für mich tun? Ich tu alles, wenn du mich nur hier rausholst.
 Das Problem ist, dass Metzger mich hier eingesperrt hat, bis ich das Funkgerät repariert hab, ich hab
 aber nicht die nötigen Ersatzteile.}
{753}{}{Wo krieg ich die Teile her, die du brauchst?}
{754}{}{Ich werde sehen, was ich tun kann.}
{760}{}{Das ist eine lange Geschichte. Man könnte sagen, dass Metzger mich hier festhält, bis ich
 das verdammte Funkgerät repariert habe. Der Quarz ist durchgebrannt und ich hab keine Ersatzteile.
 Was glaubt er, wie ich es so hinkriegen soll?}
{761}{}{Nun, ich bin hier, um dich rauszuholen.}
{764}{}{Weiß nicht. Bis später.}
{800}{}{Ich muss dieses Funkgerät wieder hinkriegen. Hilf mir, wenn du kannst. Vielleicht lässt er dann
 mit sich reden.}
{801}{}{Wie kann ich helfen?}
{803}{}{Das bezweifle ich. Viel Glück.}
{810}{vic25}{Warum hast du die arme Mom umgebracht...wahrscheinlich hattest du deine Gründe...tut mir leid, Boss, es steht mir nicht zu, dich auszufragen. Diese Stadt ist ziemlich verdorben. Sie hat sicher etwas Schlechtes getan.}
{811}{vic26}{He, Boss! Danke für die Hilfe in dem Schlamassel mit Metzger. Brauchst du irgendwas? Mom war so gut, mir zu essen zu geben, während du fort warst. Ich helfe ihr ein bisschen im Laden... }
{812}{}{Tschüss.}
{813}{}{Uuuh.}
{814}{}{Tschüüßßß.}
{823}{}{Wo ist dein Freund Ed noch mal?}
{830}{vic27}{Das würde ich, wenn ich könnte, aber du siehst nicht besonders fit aus. Ich würde dir nur zur Last fallen. Jetzt, wo Mom nicht mehr ist, werde ich wohl einfach fortgehen, wohin weiß ich nicht... Vielleicht sehen wir uns ja irgendwann wieder. Danke für alles, was du für mich getan hast.}
{831}{vic28}{Das würde ich, wenn ich könnte, aber du siehst nicht besonders fit aus. Leute wie du können ja kaum für sich selbst sorgen. Ich würde dir nur zur Last fallen. Ich werde hier bleiben. Moms Küche erinnert mich an meine Exfrau....}
{832}{vic29}{Ich würd ja gern, ehrlich. Ich würde alles für dich tun. Aber du siehst nicht so aus, als wärest du in der Verfassung, jemanden anzuführen. Ich würde dir nur zur Last fallen. Ich geh mal rüber zu Mom... bis du alles im Griff hast. Es ist lange her, dass ich ihr hausgemachtes Essen genossen habe.}
{833}{vic30}{Tut mir leid, Boss. Aber du siehst aus, als hättest du genug Gesellschaft. Jetzt, wo Mom nicht mehr ist, werde ich wohl einfach fortziehen. Wohin weiß ich nicht. Vielleicht sehen wir uns ja irgendwann wieder. Danke für alles, was du für mich getan hast.}
{834}{vic31}{Du siehst aus, als hättest du genug Gesellschaft, Boss. Ich bleib hier und warte, bis du alles im Griff hast. Moms Küche erinnert mich an meine Exfrau... weiß nich', ob das gut oder schlecht ist...}
{835}{vic32}{Das würde ich wirklich gern, Boss. Aber es sieht aus, als hättest du wirklich keinen Platz mehr. Ich geh mal rüber zu Mom, war schon lange nicht mehr da. Komm und hol mich ab, wenn du etwas mehr Platz für mich hast. }
{840}{vic33}{Ed ist drüben in Vault City. Er ist ein Brahminhändler. Er war nur einer meiner vielen Lieferanten. Vault City ist nicht weit von hier.}
{845}{vic34}{Ich hab dir doch gesagt, es ist hier drüben. [Vic zeigt auf einen Ort auf deinem PIPBoy 2000.]}
{900}{}{Du hast erfahren, dass Vic ein Händler ist.}
{1000}{}{Ich muss dich was fragen.}
{1100}{vic35}{Vollständig geheilt, Boss. Noch was?}
{1200}{vic36}{Bin quasi in Topform, Boss.}
{1300}{vic37}{Ich bin fast wiederhergestellt, Boss, aber mir ging's schon besser.}
{1400}{}{Ich hab's versucht, Boss, aber ich krieg keine Glanzleistungen mehr hin. Trotzdem, werd
 ich tun, was ich kann.}
{1500}{vic39}{Was immer du sagst, Boss.}
{1501}{vic40}{Hier? Genau hier? Okay, du bist der Boss.}
{1502}{vic41}{Genau. Ich bleibe hier, bis du zurückkommst, Boss. Du kommst doch zurück, oder?}
{1503}{vic42}{Solange du willst. Ich gehe nirgendwohin.}
{1504}{vic43}{Natürlich, Boss.}
{1600}{vic44}{Wenn du's sagst.}
{1601}{vic45}{Gut gesagt, Boss.}
{1602}{vic46}{Gute Idee, Boss.}
{1603}{vic47}{Sicher, Boss. Noch was?}
{1604}{vic48}{Abstand - alles klar, Boss.}
{1605}{vic49}{Kein Problem, Boss.}
{1606}{vic50}{Erledigt, Boss.}
{1700}{vic51}{Klar, Boss.}
{1701}{vic52}{Dicht dran - alles klar, Boss.}
{1702}{vic53}{Du weißt es am besten, Boss.}
{1703}{vic54}{Ich bin direkt hinter dir, Boss.}
{1704}{vic55}{Wie Leim, Boss.}
{1705}{vic56}{Wenn du's sagst, Boss.}
{1706}{vic57}{Oh, okay, Boss.}
{1800}{vic58}{OK, ich halte Abstand, aber nicht zu viel, Boss.}
{1801}{vic59}{Okay, ich werde es nicht tun, Boss.}
{1802}{vic60}{Ich bleibe dann also ein Stück zurück, Boss.}
{1803}{vic61}{Klar, Boss.}
{1900}{vic62}{Genau, Boss. Ich bleib ein wenig zurück.}
{1901}{vic63}{Was immer du sagst, Boss.}
{1902}{vic64}{Sofort, Boss.}
{1903}{vic65}{Falle zurück, Boss.}
{1904}{vic66}{Zieh mich zurück, Boss.}
{1905}{vic67}{Schwärme aus, Boss.}
{1906}{vic68}{Okay, Boss.}
{2000}{vic69}{Äh, Boss? Du siehst etwas belagert aus. Ich warte einfach weiter hier auf dich.}
{2100}{}{Du machst mir Angst, Boss. Was ist mit dir passiert? Du siehst... naja, gruselig aus. Ich
 glaube, ich treibe mich hier noch eine Weile herum...}
{2200}{vic70}{Und ob, Boss!}
{2201}{vic71}{Verdammt richtig, ich werde es tun, Boss.}
{2202}{vic72}{Klar doch, Boss.}
{2203}{vic73}{Bin bereit, wenn du bereit bist, Boss.}
{2204}{vic74}{Großartig! Dann los.}
{2205}{vic75}{Klasse!}
{2206}{vic76}{Du bist einfach super, Boss!}
{2207}{vic77}{Du wirst nicht enttäuscht werden. Keine Fehler mehr!}
{2208}{vic78}{Ich werde diesmal vorsichtig sein, keine Sorge!}
{2209}{vic79}{Ich wusste, du würdest mir verzeihen...äh. Also, Boss, was hast du vor?}
{2210}{vic80}{Ich werde dich nicht enttäuschen, Boss!}
{2211}{vic81}{Du bist klasse, Boss!}
{2212}{vic82}{Ich wusste, ich bin noch nicht zu alt dafür. Es war einfach Pech. Stimmt's, Boss?}
{2300}{}{Von Ed. Er ist Brahminhändler drüben in Vault City. Warst du schon mal da? Komm, ich zeig's dir auf deinem Kartending da.}
{2305}{vic199}{Vault City. Hier. Komm, ich zeig's dir auf deinem schicken Kartending da.}
{2310}{vic84}{Er müsste hier irgendwo sein.}
{2311}{vic85}{Vault City. Schau es auf deinem neumodischen Kartending da nach.}
{2403}{}{Woher hast du denn die Wasserflasche aus Vault 13?}
{2404}{}{Macht nichts.}
{2500}{vic86}{Klar, Boss.}
{2501}{vic87}{Frag mich alles, was du willst, Boss.}
{2502}{vic88}{Ich werde dir helfen, soweit ich kann, Boss.}
{2503}{vic89}{Ich hab doch keinen Ärger, oder, Boss?}
{2504}{vic90}{Hab ich was falsch gemacht, Boss?}
{2505}{vic91}{Natürlich.}
{2600}{vic92}{Was machen wir jetzt, Boss?}
{2601}{vic93}{Was hast du jetzt vor, Boss?}
{2602}{vic94}{Ich tu mein Bestes, Boss.}
{2603}{vic95}{Was kann ich für dich tun, Boss?}
{2604}{vic96}{Hat sich was am Plan geändert, Boss?}
{2605}{vic97}{Eine andere Strategie, Boss?}
{2700}{}{Boss, sie haben mich erwischt. Du musst einen Arzt holen. Ich weiß nicht, ob ich dich noch unterstützen kann.}
{2701}{}{Ich brauche einen Arzt, Boss. Ich bin echt im Eimer. Ich weiß nicht, ob ich noch mit dir weiterkämpfen kann.}
{2702}{vic100}{Boss, ich bin echt im Eimer. Du musst Lenny herholen, damit er mich untersucht.}
{2800}{vic101}{He, Boss. Soll ich jetzt mit dir kommen?}
{2801}{vic102}{He, Boss. Ich warte gern auf dich. Ich bin ein sehr geduldiger Mensch. }
{2802}{vic103}{Tun wir uns wieder zusammen, Boss? Ich werde mir mehr Mühe geben.}
{2803}{vic104}{Ich hatte Angst, du würdest nicht zurückkommen. Wirklich schön, dich zu sehen, Boss.}
{2804}{vic105}{Suchst du wieder einen Begleiter?}
{2805}{vic106}{Ich bin bereit, Boss.}
{2806}{vic107}{Ich wusste, du würdest mich nicht verlassen.}
{2807}{vic108}{Brauchst du Unterstützung?}
{2808}{vic109}{Du hast was zu reparieren, nicht wahr? Ich bin dein Mann, Boss!}
{2809}{vic110}{Keine Sorge, Boss. Sulik und ich werden uns verstehen, ehrlich.}
{2810}{vic200}{Lass uns gehen.}
{2811}{vic201}{Bleib hier. Ich bin gleich wieder da.}
{2812}{vic202}{Ich gehen.}
{3100}{vic111}{Was? Äh...na gut, Boss. Wie du meinst.}
{3101}{vic112}{Kann ich mir nicht noch was anderes anziehen, Boss? Ich bin etwas in Sorge.}
{3102}{vic113}{Also gut...du lässt mich doch nicht hier...oder Boss?}
{3103}{vic114}{Aber...ich, äh...natürlich, Boss. Schon da.}
{3200}{vic115}{Weißt du, Boss... ich kann ziemlich gut mit kleinen Waffen umgehen. Ich kann mit fast jedem Gewehr, jeder Flinte und den meisten mittleren Pistolen schießen. Ich 'kann' mit Messern umgehen. Außerdem habe ich einen recht guten Wurfarm, aber ich ziele nicht besonders gut... ehrlich gesagt ziele ich ziemlich schlecht. Tut mir leid, Boss. Ich bemühe mich wirklich, besser zu werden.}
{3201}{vic116}{Wie schon gesagt, Boss, ich ziehe kleine Waffen vor. Ich kann mit fast jedem Gewehr, jeder Flinte und den meisten mittleren Pistolen schießen. Wenn wir wirklich in der Klemme sitzen, kann ich versuchen, ein Messer zu benutzen oder sogar Wurfwaffen.}
{3300}{vic203}{Ich 'kann' mit Messern umgehen und habe einen recht guten Wurfarm, aber...ich ziele aber nicht besonders gut. Ehrlich gesagt ziele ich sogar ziemlich schlecht. Tut mir leid, Boss. Ich bemühe mich wirklich, besser zu werden.}
{3301}{vic204}{Wie gesagt, Boss. Messer, und ich habe einen ziemlich guten Wurfarm...leider werfe ich ziemlich oft daneben.}
{3400}{vic122}{Ich hab die Nase gestrichen voll!}
{3401}{vic123}{Ich werde dir den verdammten Schädel vom Hals reißen! Niemand vergreift sich ungestraft an meiner Familie!}
{4000}{vic124}{Hier drüben?}
{4001}{vic125}{Ist es so besser, Boss?}
{4002}{vic126}{Wie ist es hier?}
{4003}{vic127}{Ja, Boss.}
{4004}{vic128}{Was?}
{4005}{vic129}{Wohin gehen wir?}
{4006}{vic130}{Gehen wir, Boss?}
{4007}{vic131}{Ich geh woanders hin.}
{4008}{vic132}{Tut mir leid, Boss.}
{4009}{vic133}{Besser?}
{4010}{vic134}{Uufff.}
{4011}{vic135}{Wie ist das, Boss?}
{4012}{vic136}{Ich stell mich hier drüben hin.}
{4013}{vic137}{Ich stell mich jetzt hier rüber.}
{4100}{vic138}{Boss! Mir geht's hier nicht so besonders.}
{4101}{vic139}{Ich brauch einen Arzt.}
{4102}{vic140}{Oh, Mann. Das tut echt weh.}
{4103}{vic141}{Aua!}
{4104}{vic142}{Autsch.}
{4105}{vic143}{Zum Henker!}
{4106}{vic144}{Sani?}
{4107}{vic145}{Ich halt mich wacker...noch.}
{4200}{vic146}{Ich mochte diesen Ort noch nie.}
{4201}{vic147}{Wieso ist es hier so sauber?}
{4202}{vic148}{Riechst du was, Boss?}
{4203}{vic149}{Weißt du, Boss. Ich glaube, hier werde ich nicht wieder herkommen, wenn wir fertig sind. Dies ist nicht mehr mein Zuhause.}
{4204}{vic150}{Es ist jedenfalls sehr viel schmutziger, als ich es in Erinnerung habe.}
{4205}{vic151}{Wir bleiben doch nicht lange hier, Boss, oder?}
{4206}{vic152}{Hier wird sich nie was verändern.}
{4207}{vic153}{Boss, dieser Ort wird mir bestimmt nicht fehlen.}
{4208}{vic154}{Danke nochmals, dass du mich hier rausgeholt hast, Boss.}
{4209}{vic155}{Ich schulde dir einen Gefallen, Boss.}
{4210}{vic156}{Wow, hier hat sich ja einiges verändert!}
{4211}{vic157}{Ich war seit Ewigkeiten nicht hier.}
{4212}{vic158}{Hier werde ich mich zur Ruhe setzen. }
{4213}{vic159}{Ich könnte hier in der Gegend eine Werkstatt aufmachen.}
{4300}{vic160}{Ach, was sehen meine wunden Augen! Das ist...war mein Zuhause, aber das weißt du sicher schon, nicht wahr, Boss?}
{4400}{vic161}{Sulik, hör auf, mich so anzusehen.}
{4401}{vic162}{Boss, Sulik starrt mich schon wieder so an.}
{4402}{vic163}{Niedlicher Kläffer.}
{4500}{vic164}{La di da...}
{4501}{vic165}{Ho hum.}
{4502}{vic166}{Warte auf den Boss...}
{4503}{vic167}{Ich warte auf den Boss.}
{4504}{vic168}{Ich warte hier bloß.}
{4505}{vic169}{Der Boss würde mich bestimmt nicht einfach so zurücklassen...}
{4506}{vic170}{Wer hat Angst vorm Schwarzen Mann... Niemand. Wie war das noch...}
{4507}{vic171}{Ich warte immer noch.}
{4508}{vic172}{Was riecht da so?}
{4509}{vic173}{Gibt's hier irgendwas zu reparieren?}
{4510}{vic174}{Da bin ich nun ... und warte auf den Boss.}
{4511}{vic175}{Ein alter Mann wie ich...ich vergeude meine Fähigkeiten, wenn ich hier nur so rumstehe.}
{4512}{vic176}{Ich wünschte, ich hätte einen Kaugummi...es ist Jahrzehnte her.}
{4513}{vic177}{Ich muss mich aus dem Reliktegeschäft zurückziehen... nichts als Ärger.}
{4514}{vic178}{Wieso macht Warten nur so müde...}
{4600}{vic179}{Äh, danke, Boss.}
{4601}{vic180}{Danke.}
{4602}{vic181}{Weißt du auch bestimmt, was du tust?}
{4603}{vic182}{Können wir uns nicht lieber ausruhen?}
{4604}{vic183}{Sollen wir das Lager aufschlagen?}
{4605}{vic184}{Steht es so schlecht mit mir?}
{4700}{vic185}{Nicht zu viel, Boss.}
{4701}{vic186}{Wenn du darauf bestehst, Boss.}
{4702}{vic187}{Boss, mein Kopf wird doch nicht platzen, oder?}
{4703}{vic188}{Boss, ich glaube, ich fange an, das Zeug zu mögen.}
{4704}{vic189}{Ich fühl mich ein bisschen komisch, Boss.}
{4705}{vic190}{Bist du sicher, dass du etwas davon entbehren kannst?}
{4706}{vic191}{Klar, Boss. Ich nehm was davon.}
{4707}{vic192}{Danke, Boss.}
{4708}{vic193}{Nicht schlecht.}
{5000}{vic194}{Ich bin im Moment ein wenig hungrig. Wir reden später bei Mom's weiter.}
{5500}{vic195}{Ich glaube ich hab mir was gebrochen, Boss. Kannst du dir das mal ansehen?}
{5501}{vic196}{Ich fühle mich als würde ich brennen, Boss. Kannst du dir das mal ansehen?}
{5502}{vic197}{Ich glaub ich bin vergiftet, Boss. Kannst du dir das mal ansehen?}
