{100}{}{Ein Mann in Powerrüstung.}
{101}{}{Arthur, Sohn von Uther Pendragon.}
{102}{}{Sein Hosenschlitz ist offen.}
{103}{arth1}{Heil euch, Reisende. Ich bin Arthur, Sohn von Uther Pendragon, von der Brotherhood of Steel. Wir sind auf der Suche nach der Heiligen Handgranate von Antiochien. Hast du sie gesehn?}
{104}{}{Heilige was von wem?}
{105}{}{Spielerantwort}
{106}{}{Unga.}
{107}{arth13}{Keine Zeit zum Reden. Wir sind auf der Suche.}
{108}{arth14}{Wir suchen die Heilige Handgranate von Antiochien.}
{109}{arth15}{Für die Brotherhood of Steel!}
{110}{arth16}{Hmm...Afrikanische oder europäische Schwalbe?}
{111}{arth17}{He! Das ist nicht deins, oder?}
{112}{arth18}{Ich warn dich. Nimm deine Pfoten weg.}
{113}{arth19}{Jetzt reicht's. Genug ist genug.}
{114}{arth2}{Die heilige Handgranate von Antiochien? Natürlich weil sie die tollste gegen Menschen gerichtete Handfeuerwaffe ihrer Art ist.}
{115}{}{Warum suchst du nach einer so schrecklichen Waffe?}
{116}{arth3}{Wir von der Brotherhood of Steel möchten diese so vernichtende Waffe unserer Vorfahren finden und sie vor denen schützen, die die Macht der heiligen Handgranate von Antiochien missbrauchen würden.}
{117}{}{Warum?}
{118}{arth4}{Na...weil die Brotherhood of Steel sich geschworen hat, die Schwachen und Schutzlosen zu schützen und dieses Ding könnte wirklich jemanden verletzen.}
{119}{}{Warum?}
{120}{arth5}{Hmm...weil es die einzig moralische Wahl ist.}
{121}{}{Warum?}
{122}{arth6}{Wa...hm...Du siehst ja, wir sind ziemlich beschäftigt. Hilfst du uns jetzt oder nicht? Hast du die heilige Handgranate von Antiochien gesehen oder nicht?}
{123}{}{Ja.}
{124}{}{Nein.}
{125}{arth7}{Ja, warum denn nicht gleich? Wenn du uns nur noch schnell sagen könntest, wo, sind wir auch schon weg und du kannst mit dem weitermachen, was du vorher gemacht hast.}
{126}{}{[Du zeigst in eine beliebige Richtung.]}
{127}{arth8}{Alsdann. Danke für deine Hilfe. Hier ist etwas für deine Mühe.}
{128}{}{Warte! Ich bin auch auf der Suche. Ich suche das heilige GECK. Hast du's gesehn?}
{129}{arth9}{Na dann können wir diese Unterhaltung ja beenden. Wir packen's.}
{130}{}{[Ende]}
{131}{arth10}{Verdammter Prolet!}
{132}{}{[Ende]}
{133}{arth11}{GECK, sagst du? Natürlich ja, wir haben zwei davon. Brauchen nicht noch eins. Dennoch danke.}
{134}{}{Nachdem du ja zwei hast, kannst du mir ja vielleicht eins geben.}
{135}{arth12}{Nein. Nein. Das kann ich nicht. Wär nicht richtig, deine Suche so leicht zu beenden. In der Richtung gibt's noch mehr davon. Hol dir dein eignes. [Er deutet in ungefähr dieselbe Richtung, in die du gezeigt hast, als du ihm sagtest, wo die heilige Handgranate von Antiochien ist.]}
{136}{}{[Ende]}
{200}{arth20}{Sprichst du die Sprache des Königs?}
{201}{arth21}{Hallooo.}
{202}{arth22}{He, ich bin hier drüben.}
{203}{arth23}{Wenn du einen Augenblick Zeit hättest.}
{204}{arth24}{Ähem.}
{205}{arth25}{Hey, ignorier mich nicht einfach.}
{206}{arth26}{Biiiiiiiitte! Ich muss dich was Wichtiges fragen.}
{207}{arth27}{Na denn, wir müssen unsre Suche nach der Handgranate von Antiochien fortsetzen. Komm schon, Mathias.}
{300}{}{Unsere Aufgabe ist erfüllt!}
{301}{}{Arthur, zu euren Diensten.}
