{100}{}{Du siehst einen Mann der eine Lederrüstung trägt.}
{101}{}{Du siehst Kaga.}
{102}{}{Er trägt eine Lederrüstung und hat die Unsitte bei einer Unterhaltung über sich selbst in der dritten Person zu Sprechen.}
{103}{kaga13}{Das wird das letzte Mal sein wo du Kaga siehst.}
{104}{kaga14}{Nachdem dich Kaga getötet hat, wird er Arroyo niederbrennen.}
{105}{kaga15}{Fühle den Zorn des Kaga!}
{106}{kaga16}{Ich bin der große Kaga!}
{107}{kaga17}{Kaga wird von allen gefürchtet.}
{108}{kaga18}{Kaga wird deinen Kopf als Trophäe behalten.}
{109}{kaga19}{Gib auf und dein Tod wird schnell sein.}
{110}{kaga20}{Kaga wird zurückkommen!}
{111}{kaga21}{Du kannst den großen Kaga nicht töten!}
{112}{kaga22}{Du hast Glück, dass Kaga woanders geschäftliche Dinge zu erledigen hat.}
{113}{kaga23}{Kaga wird dich wiedertreffen.}
{120}{}{Es ist wieder dieser Kaga-Typ.}
{150}{kaga1}{[Ein großer, kräftig gebauter Krieger steht vor dir, seine Augen glänzen hasserfüllt als er dich ansieht.] So, sie vertreiben Kaga und jetzt sollst du das "Auserwählte Wesen" sein? Ha! Du glaubst du bist was besonderes weil du das Enkelkind des Vaultbewohners bist. Du glaubst du bist besser als ich, Kaga der Große?!}
{151}{}{Nun, Ich BIN das "Auserwählte Wesen", oder?}
{152}{}{Hey wart mal ne Sekunde. Ich hab nie gesagt dass ich etwas besseres als du bin.}
{160}{kaga2}{Dieser Titel bedeutet nichts, wenn Kaga dir den Kopf von den Schultern reißt!}
{161}{kaga3}{Deine Worte sind umsonst. Mit deinem Tod wird meine Ehre wiederhergestellt. Kaga bekommt jetzt seine Rache!}
{200}{}{Ggrrr?}
{201}{kaga4}{Was!? Du bist das neue "Auserwählte Wesen"? Oh man Sie müssen echt verzweifelt sein.}
{202}{}{Mich nicht mögen. Du sehen aus Schlecht.}
{203}{kaga5}{Ich werde mich hier nicht mit einer großen Rede herumschlagen. Bereite dich darauf vor durch die Hand von Kaga zu Sterben!}
