{100}{}{Du siehst einen Mann der eine Kampfrüstung trägt.}
{101}{}{Du siehst den verdammten Kaga in einer Kampfrüstug.}
{102}{}{Das glaube ich jetzt nicht... Kaga hat nun eine Kampfrüstung und scheint einige anständige Waffen zu besitzen.}
{103}{kaga33}{Dieses mal bin ich vorbereitet!}
{104}{kaga34}{Das "Auserwählte Wesen wird niemals nach Arroyo zurückkehren!}
{105}{kaga35}{Kaga wird dich zerquetschen!}
{106}{kaga36}{Kaga fürchtet niemanden!}
{107}{kaga37}{Stillhalten, damit Kaga einen guten Treffer landen kann.}
{108}{kaga38}{Wir werden uns wiedersehen!}
{109}{kaga39}{Dies ist nicht das letzte mal an dem du Kaga sehen wirst.}
{110}{kaga40}{Kaga braucht definitiv mehr Training.}
{120}{}{Verschwinde Kaga!}
{150}{kaga1}{[Ein großer, kräftig gebauter Krieger steht vor dir, seine Augen glänzen hasserfüllt als er dich ansieht.] So, sie vertreiben Kaga und jetzt sollst du das "Auserwählte Wesen" sein? Ha! Du glaubst du bist was besonderes weil du das Enkelkind des Vaultbewohners bist. Du glaubst du bist besser als ich, Kaga der Große?!}
{151}{}{Nun, Ich BIN das "Auserwählte Wesen", oder?}
{152}{}{Hey wart mal ne Sekunde. Ich hab nie gesagt dass ich etwas besseres als du bin.}
{160}{kaga2}{Dieser Titel bedeutet nichts, wenn Kaga dir den Kopf von den Schultern reißt!}
{161}{kaga3}{Deine Worte sind umsonst. Mit deinem Tod wird meine Ehre wiederhergestellt. Kaga bekommt jetzt seine Rache!}
{200}{}{Ggrrr?}
{201}{kaga4}{Was!? Du bist das neue "Auserwählte Wesen"? Oh man Sie müssen echt verzweifelt sein.}
{202}{}{Mich nicht mögen. Du sehen aus Schlecht.}
{203}{kaga5}{Ich werde mich hier nicht mit einer großen Rede herumschlagen. Bereite dich darauf vor durch die Hand von Kaga zu Sterben!}
