{100}{}{Du siehst Eldridge.}
{150}{}{Du siehst einen schwer bewaffneten, fettverschmierten Mann. Er sieht sich seine Waffensammlung an den Wänden mit verträumtem Lächeln an.}
{151}{}{Du siehst Eldridge. Er sieht sich seine Waffensammlung mit verträumtem Lächeln an.}
{200}{eld47}{Glückwunsch, Held! Hast du gut gemacht!}
{201}{eld48}{::Feuert einmal in die Luft, beginnt zu tröten und zu brüllen:: Die Enklave is' TOT! TOT! TOT! Jippieeeh!}
{202}{eld49}{::Ding-dong, die Enklave is' tot, die Enklave is' tot... ::}
{203}{eld50}{Enklave is' 'n guter Grund für jeden Bürger, 'ne Waffe tragen zu dürfen.}
{204}{}{Nächstes Mal geh nich' zur Enklave, ohne vorher hier vorbeizuschau'n... ich sorg schon dafür, dass du alle Feuerwaffen hast, die du BRAUCHST.}
{210}{eld52}{Heeeiiiliger Jesus, Maria und Josef - 'ne Powerrüstung!}
{211}{eld53}{Wowiiiiee. ::Reibt sich die Augen:: Das 'ne Powerrüstung?!}
{212}{eld54}{Kneif mich mal einer. Is' das 'ne POWERRÜSTUNG?}
{213}{eld55}{Triff mich der Schlag im Stehen! Eine Powerrüstung! In Reno!}
{214}{eld56}{Verkaufst du mir die Powerrüstung, Freund?!! Hey! Irgend jemand zu Hause?!!}
{220}{eld57}{'Ne 9mm is' OK, aber 'ne Kaliber 233 hat mannstoppende Wirkung...}
{221}{eld58}{Eigentlich will ich ja 'n Red-Ryder-Luftgewehr.}
{222}{eld59}{Ich hoff nur, dass niemand vor mir 'n Turboplasmagewehr in die Finger bekommt...}
{223}{eld60}{Ich frag mich nur, wo die Salvatores diese Laserwaffen herhaben...}
{224}{eld61}{Hab letzte Nacht wieder von Plasmawaffen geträumt...}
{225}{eld62}{Sieh besser zu, dass diese Ladung Gewehrpatronen für die Wrights reinkommt...}
{226}{eld63}{Ich hoffe nur, die Mordinos haben genug Gold, um ihre Bestellung zu bezahlen...}
{227}{eld64}{Diese Waffe? Die kann 'n Loch durch 'ne Metallwand stanzen, kann die.}
{228}{eld65}{Der Junge is' 'n Genie... möchte man kaum glauben, wenn man ihn so anschaut...}
{229}{eld66}{Führ besser mal die Hunde aus, bevor die noch überall hinpinkeln.}
{230}{eld67}{Diese ungewaschenen Dörfler horten viele Waffen... is' 'ne rauhe Bande. }
{231}{eld68}{Wenn mich doch nur jemand überfallen würde - dann könnt ich ihn erschießen.}
{232}{eld69}{Muss hier bald mal 'n bisschen Ordnung schaffen.}
{233}{eld70}{Kann die Gang-Jagd nächste Woche kaum erwarten.}
{234}{eld71}{Ich hab MPs, Pistolen, Dynamit, Granaten... und trotzdem kommen hier die Leute rein und wollen Schwerter und Armbrüste. }
{240}{}{Willkommen, Held! Wirklich klasse Arbeit, was du mit der Enklave gemacht hast... hast uns allen den Hintern gerettet, jawohl, und dafür dank ich dir. Eldridge heiß ich. Biste vielleicht auf der Suche nach 'n bisschen Eisen, um dein Holster zu füllen?}
{241}{eld2}{Willkommen, der Herr... Eldridge heiß ich. Biste vielleicht auf der Suche nach 'n bisschen Eisen, um dein Holster zu füllen?}
{242}{eld3}{Willkommen, Reisender... Eldridge heiß ich. Biste vielleicht auf der Suche nach 'n bisschen Eisen, um dein Holster zu füllen?}
{243}{}{Ernnnnh? Hollll-sterrr?}
{244}{eld92}{Hängt davon ab, was du so verkaufst.}
{250}{eld4}{Willkommen, Held! Wirklich klasse Arbeit, was du mit der Enklave gemacht hast... hast uns allen den Hintern gerettet, jawohl, und dafür dank ich dir.}
{251}{eld5}{Wenn du was siehst, das du magst, lass es mich wissen, dann machen wir dir 'n *Spezialrabatt* aus, alles klar?}
{252}{}{Aaaalles klar}
{253}{}{Geh weiter}
{254}{}{Klasse! Kann ich mal sehen, was du so am Lager hast?}
{255}{}{Ich weiß ja nicht, ob du mir helfen kannst... Ich such was Bestimmtes.}
{256}{}{Mein Boss... }
{257}{}{Jules hat mir gesagt, ich soll hierher kommen, wenn ich 'ne Waffe suche.}
{258}{}{Kaufen die Salvatores ihre Lichtwerfer hier?}
{259}{}{Ich habe dir die Laserpistole gebracht, die ich dir versprochen habe.}
{260}{}{Kannst du Waffen aufrüsten?}
{261}{}{Dann komm ich noch mal wieder, um mich umzuschauen.}
{262}{}{Exzellent... kann ich mal deine Sonderposten sehen?}
{270}{eld6}{Hier im Waffenladen von New Reno haben wir die aktuellen Geräte zum Personenschutz, die man braucht, um irgendwelche feigen Spinner unter die Erde zu bringen. (Lächelt böse.)}
{272}{eld7}{Na, hallöchen, Freund. Was kann ich für dich tun?}
{273}{eld8}{Und das wäre?}
{274}{}{Kram ich mögen Kram du auch mögen Kram?}
{276}{}{Dann bist du genau der Mann, den ich suche. Kann ich mal sehen, was du so am Lager hast?}
{277}{}{Kann ich mal sehen, was du so am Lager hast?}
{283}{}{Kannst du Waffen ändern oder aufrüsten?}
{284}{}{Ich bin gerade nicht interessiert, danke.}
{285}{}{Heute nichts, danke.}
{286}{}{Kann ich mal deine Sonderposten sehen?}
{300}{eld9}{Siehst du irgend etwas Glänzendes, das du möchtest? Komm schon, irgendwas muss dich doch interessieren.}
{301}{eld10}{Äh... sicher, sicher. (Sieht dich kritisch an.) Du erinnerst mich an meinen Sklaven, Al. Möchtest du mal sehen, was wir so am Lager haben, Freundchen?}
{302}{}{Jah}
{303}{}{Will was NICHT Lager}
{304}{}{Nee}
{310}{eld11}{Jules hat dich also hergeschickt, hm? }
{311}{eld12}{Is' ja auch langsam Zeit, dass der faule Hund was tut für sein Geld... also was kann ich für dich tun, Mister?}
{312}{eld13}{Is' ja auch langsam Zeit, dass der faule Hund was tut für sein Geld... 'tschuldige die Ausdrucksweise. Was kann ich denn für dich tun, Frollein?}
{330}{}{Nein, nein... wir haben das mal gemacht, aber... (sieht gequält aus) ...na ja, da war so ein Unfall... und nu machen wir das eben nich' mehr. Kann ich vielleicht was anderes für dich tun?}
{331}{}{Also gut. Ich interessier mich da für noch was...}
{340}{eld15}{Klar können wir das. Was willste denn aufgemöbelt haben?}
{341}{}{Kannst du irgend etwas mit den Pistolen anfangen, die ich hier habe?}
{342}{}{Eins meiner Gewehre könnte noch 'n paar Extras gebrauchen.}
{343}{}{Kannst du irgend etwas mit diesem Elektrostab hier anfangen?}
{344}{}{Na, egal. Ich hab da an noch etwas Interesse...}
{345}{}{Eigentlich nichts heute.}
{350}{eld16}{(Entdeckt deine Magnum.) Ich kann in diese Magnum einen Schnellader einbauen, und zwar für $}
{351}{eld17}{Diese Desert Eagle, die du da hast... wenn du willst, kann ich ihr Magazin erweitern, und zwar für $}
{352}{}{Bau den Schnellader in die Magnum ein.}
{353}{}{Erweitere das Magazin dieser Desert Eagle hier.}
{354}{}{Eigentlich hab ich da an eine andere Waffe gedacht...}
{355}{}{Na, egal. Ich wollte was anderes...}
{356}{}{Nein danke, interessiert mich alles nicht. Ich muss gehen.}
{357}{}{Das ist ein bisschen viel für mich. Da muss ich erst mehr Geld auftreiben.}
{365}{eld18}{(Sieht sich dein Gewehr genau an, nickt.) }
{366}{eld19}{Ich kann an dieses Jagdgewehr da ein Zielfernrohr anbauen, und zwar für $}
{367}{eld20}{Dieses Sturmgewehr, das du da hast... ich kann das Magazin erweitern, für $}
{368}{eld21}{Ich hab ein Nachtsicht-Zielfernrohr, das ich in diese FN FAL da einbauen kann, für $}
{369}{}{In Ordnung... bring das Zielfernrohr am Jagdgewehr an.}
{370}{}{Bau das größere Magazin in das AK-112-Sturmgewehr ein.}
{371}{}{Bau das Nachtsichtgerät beim FN FAL ein.}
{385}{eld22}{Du willst, dass ich diesen Elektroschocker aufmotze? Ich kann ihn dir ÜBERLADEN, und zwar für $}
{386}{}{Sicher.}
{395}{}{(Eldridge nimmt die Waffe, untersucht sie kritisch.) Also gut... wart 'nen Augenblick, und ich seh, was ich für dich tun kann. (Er verschwindet nach hinten.)}
{396}{}{OK.}
{400}{eld24}{(Du wartest...)}
{401}{}{Moment...}
{405}{eld25}{(Und wartest immer noch...)}
{406}{}{Dum-di-dum-di-dum...}
{410}{}{(Du bist am Einschlafen, als Eldridge endlich zurückkommt.) Tut mir leid, dass du so lange warten musstest... hier. Damit solltest du es jedem Spinner geben können, der versucht, dir auf den Schatten zu treten.}
{411}{}{Danke. Kannst du welche von meinen anderen Waffen aufrüsten?}
{412}{}{Danke. Ich wollte da noch etwas...}
{413}{}{Danke. Ich geh es mal ausprobieren.}
{420}{}{Oh... wir sind also ein kritischer Kunde, was? Tja, manchmal machen's auch ein paar nette Teile in unsere Stadt... das hier, zum Beispiel. (Hält etwas... Seltsames hoch.) Echte Vorkriegstechnik. Is' das nix?}
{423}{}{Äh... klar, das ist schon "etwas". Kann ich's mir mal anschauen?}
{424}{}{Klar. Ich interessier mich aber für etwas anderes...}
{425}{}{Kein Interesse. Trotzdem danke.}
{430}{eld28}{(Es ist ein hübsches Plastikquadrat mit Löchern und Metallinien überall. Es sind einige seltsame Wortsymbole darauf geschrieben. Es sieht aus wie eine Art mechanischer Toast, und dir läuft das Wasser im Munde zusammen.)}
{431}{eld29}{(Es sieht aus wie eine Schaltplatine. Sie ist etwas staubig, aber noch in guter Verfassung. Sieht aus wie ein Teil von... etwas. Auf die Schaltplatine ist 'Vault-Tec-Stimmerkennungsmodul' gedruckt.)}
{432}{eld30}{(Es ist eine komplizierte Schaltplatine. Ein Speicherchip ist integriert, und an der Seite sind eine Reihe von Computer- anschlüssen, inklusive einem In- und einem Output. Auf die Platine ist 'Vault-Tec-Stimmerkennungsmodul' gedruckt.)}
{433}{}{Ich wollen lecker Platte}
{434}{}{Ich wollen was andres}
{435}{}{Ich wollen gehn}
{436}{}{"Vault-Tec"? Das *muss* was Wichtiges sein. Wieviel willst du?}
{437}{}{Wird ja auch Zeit... wieviel willst du für dieses Modul?}
{438}{}{Nein danke, ich möchte etwas anderes...}
{439}{}{Nicht heute, danke.}
{450}{eld31}{Dreitausend Mäuse. Nimm es oder lass es.}
{451}{eld32}{Das letzte Mal: dreitausend Mäuse. Nimm es oder lass es.}
{452}{}{Aaaalso guuuut.}
{454}{}{Spring ihm an den Hals und nimm den mechanischen Toast}
{455}{}{Lasses}
{457}{}{Äh, das is' 'n bisschen viel. Wie wär's mit... 1500?}
{458}{}{Nein danke. Ich wollte etwas anderes...}
{459}{}{Ich lass es sein.}
{470}{eld33}{$2500. Und das ist mein letztes Angebot.}
{471}{}{Also gut, also gut. Hier hast du.}
{472}{}{Dann vergiss es. Ich wollte etwas anderes...}
{473}{}{Nein danke. Man sieht sich.}
{474}{}{Das ist mir zuviel. Lass uns noch mal darüber reden, wenn ich etwas mehr Geld habe.}
{480}{eld34}{(Lächelt, reibt sich die Hände, während du das Geld auf den Tisch legst.) Also gut, hier hast du's. }
{481}{}{(Denkt einen Moment darüber nach, sieht dich prüfend an, nickt dann.) Also gut... ist praktisch geschenkt, aber da hast du. (Gibt dir das Modul, nimmt dein Geld.) }
{482}{eld36}{Noch irgendwas?}
{485}{}{Ja, ich interessiere mich da für noch etwas...}
{486}{}{Heute nichts mehr, danke.}
{495}{}{(Blinzelt überrascht, lacht dann.) Ha! Nein, nein... diese Waffen sind schon was anderes, was? Ich WÜRDE ja gern eine in meine Finger bekommen... sieh dir mal die Reichweite an, die Kraft, die Feuergeschwindigkeit... (Starrt in die Ferne, seufzt.)}
{496}{}{Und wenn ich dir nun anbiete, dir eine zu besorgen?}
{497}{}{Wär schon nett, eine zu haben. Sag mal, ich wollte da noch was anderes...}
{498}{}{Na ja. Ich musste mal fragen. Danke, Eldridge.}
{505}{}{(Schielt dich an, als ob er entscheidet, ob er dir trauen kann.) Ich würde nicht nein sagen... wenn du das, na, im Stillen tätest. Ich würd dich für den Ärger bezahlen... (runzelt die Stirn) ...falls du mir keinen MACHST.}
{506}{}{Das macht keinen Ärger... ich hab eine dabei. Hier ist sie.}
{507}{}{Ich tu's. Aber vorher will ich noch etwas anderes...}
{508}{}{Na, was soll's. Vielleicht kannst du mir mit etwas anderem helfen...}
{509}{}{Mach ich. Ich treib dir eine auf und komme dann damit zurück.}
{510}{}{Das kann ich nicht versprechen... Ärger scheint mein ständiger Begleiter zu sein. Man sieht sich, Eldridge.}
{520}{eld39}{Na, da wird doch der Hund in der Pfanne verrückt!}
{521}{eld40}{Teufel auch! Ich halte mein Versprechen, hier ist etwas für den Ärger...}
{522}{eld41}{(Gibt dir einen Haufen Chips, nimmt die Pistole.) Mist... sieht komisch aus, oder? (Untersucht den Lauf.) Hmmm...}
{523}{}{Ich wollte noch etwas anderes...}
{524}{}{Ist mir eine Freude, mit dir zu handeln, Eldridge. Viel Spaß.}
{530}{}{(Eldridge sieht dich von oben bis unten an, und sein Ton wird respektvoller.) Klar, na sicher. Lass mich dir unsere Sonderposten zeigen... natürlich zu Sonderpreisen.}
{532}{}{Eigentlich interessiere ich mich für etwas anderes...}
{533}{}{Was soll's. Ich komm zurück.}
{545}{eld72}{Haltet die Schnauze, ihr Hunde, hört ihr?}
{546}{eld73}{Haltet die Schnauze, ihr winselnden Köter!}
{547}{eld74}{Kreaturen der Nacht... haltet die Schnauze!}
{548}{eld75}{Packard! Buck! Missy! Ihr haltet besser alle die Schnauze, oder ich komm euch da gleich rein!}
{549}{eld76}{Noch ein einziges WUFF von euch, und ich komm euch da rein!}
{550}{eld77}{Vermaledeite Hunde!}
{560}{eld78}{Was, glaubst du, ich hätte die Augen verbunden?}
{561}{eld79}{Hände weg von der Tür!}
{562}{eld80}{Lass bloß die Tür in Ruhe.}
{563}{eld81}{Du berührst die Tür, und danach berührst du nie wieder was.}
{564}{eld82}{Seltsam, die letzte Person, die diese Tür angefasst hat, liegt jetzt auf Golgotha begraben. Fass die nicht noch mal an.}
{575}{eld83}{Da drin hast du nichts zu suchen! Raus! Raus da!}
{576}{eld84}{Du hast keinen Zutritt da hinten! Raus!}
{577}{eld85}{Raus aus dem Hinterzimmer, bevor ich dich durchlöchere!}
{578}{eld86}{Wenn du da hinten drin bleibst, benutze ich dich als Zielübung!}
{600}{eld87}{Junge, wir haben geschlossen... }
{601}{eld88}{Mädchen, wir haben geschlossen...}
{610}{eld89}{Ich schlag dir vor, dass du da schnell rauskommst, bevor ich dich totschieße.}
{700}{eld93}{Elende Hunde! Ich geh zurück ins Bett.}
{701}{eld90}{Dumme Hunde! Morgen früh schläfere ich euch ein.}
{702}{eld91}{Haltet ihr blöden Hunde endlich die Schnauze! So blöd wär niemand, in ein Waffengeschäft einzubrechen!}
{800}{}{Du hast Eldridge eine Laserpistole geliefert.}
{801}{eld43}{Hey, seh ich aus wie ne Art Zauberer? Du brauchst erst eine Waffe wenn du sie Aufrüsten willst. Jetzt hau ab und find ne Knarre die ich Aufrüsten kann... Meine Güte!}
{802}{eld44}{Komm wieder wenn du die Kohle hast.}
{1340}{}{Klar können wir das. (Wirft einen Blick auf deine Ausrüstung.) Aber sieht nicht so aus, als ob du was hättest, an dem ich rumfummeln könnte. Bring mir 'ne Jungfrau... äh, ich mein, "normale" Pistolen und Gewehre, und dann könnt ich dir vielleicht sogar helfen.}
{1345}{}{Also gut. Ich interessier mich da für noch etwas...}
{1346}{}{Das werde ich tun. Wiedersehn.}
{5256}{}{...hat mir gesagt, ich sollte mal reinschauen, und dass du mich schon "ausrüsten" würdest.}
{5500}{eld46}{.}
