{100}{}{Du siehst eine merkwürdige Mischung, zur Hälfte Hund, zur anderen Hälfte aus Metall.
 Das Ding scheint aktiviert zu sein.}
{101}{}{Es ist ein Robodog! Das allseits beliebte mechanische Haustier!}
{102}{}{Entweder ist dieses Ding eine furchtbar schlampig zusammengestöpselte Kombination aus
 Hund und Maschine, oder es ist durch und durch Maschine, der man geschickterweise das Aussehen
 eines Hundes verliehen hat. Schwer zu sagen.}
{103}{dogr16}{Arf! <klick> Wuff!}
{104}{dogr17}{...bssssss...}
{105}{dogr18}{.schwirrrrr... Ich bin kein Daggit.}
{106}{dogr19}{Grrrrrrrrrrrrrrrr--}
{107}{dogr20}{Wuff! Wu-wu-wu-<klick>wuff.}
{108}{dogr21}{<sprzzzt> Miau...ups, Fehler}
{109}{dogr22}{Bellbellbellbellbellbellbell!}
{110}{dogr23}{Grrr...}
{111}{dogr24}{Ha-wuh! <klick-klick> Ha-wuh!}
{112}{dogr25}{Japs! Japs! Japs!}
{113}{dogr26}{Gefahr! Gefahr!}
{114}{dogr27}{Rawuff! <tick-tick-tick> Rawuff!}
{115}{}{<schwirrr> Weder Vogel noch Flugzeug, nicht mal ein Bock, nur ich, der kleine alte
 Robodog!<klick>}
{116}{dogr29}{Robi-Duh!}
{117}{dogr30}{I-bi-di-bi-i-bi-di-bi!}
{118}{dogr31}{Wuff!}
{119}{dogr32}{GRRR-RAWUFF!}
{120}{dogr1}{Arf-arf-arf-arf-arf-arf-arf!}
{121}{}{OK}
{122}{}{Ich glaub, ich will noch nicht wieder mit. Wiedersehn.}
{123}{dogr2}{Rawuff? <boing> Raggy?}
{124}{}{Wie geht's?}
{125}{}{Du musst hier warten, bis ich wieder da bin.}
{126}{}{Das wär's dann vorerst mal.}
{127}{dogr3}{<klick> winsel}
{128}{}{Macht nichts.}
{129}{}{OK}
{130}{}{TP:}
{131}{}{Cyberhund kann diesmal nicht mehr repariert werden.}
{132}{}{Cyberhund wurde teilweise repariert.}
{133}{}{Cyberhund ist wieder vollkommen funktionstüchtig.}
{1000}{dogr4}{Wuff! Wu-wu-wu-<klick>wuff?}
{1100}{dogr5}{Arf! <klick> Wuff!}
{1200}{dogr6}{Rawuff? <boing> Raggy?}
{1300}{dogr7}{<klick> winsel.}
{1400}{dogr8}{Ha-wuh! <klick-klick> Ha-wuh!}
{1500}{}{I-bi-di-bi-i-bi-di-bi!}
{1600}{}{Klare Sache, ich tu's weg.}
{1700}{}{Arf-arf-Abstand auf nah eingestellt.}
{1800}{}{Arf-arf-Abstand auf mittel eingestellt.}
{1900}{}{Arf-arf-Abstand auf weit eingestellt.}
{2000}{dogr14}{.schwirrrrr... Ich bin kein Daggit.}
{2100}{dogr33}{GRRR-RAWUFF!}
{2200}{dogr15}{Wuff! Wu-wu-wu-<klick>wuff?}
{2204}{}{Okay, du ziehst dich jetzt erst mal ein bisschen zurück.}
